### ISSUE TITLE
Hyrri's Truth doesn't have reduced mana reservation

### ISSUE THREAD

**Issue by Chichigami** [PathOfBuildingCommunity/PathOfBuilding#1000]
![image](https://user-images.githubusercontent.com/47513960/84937478-cfc55880-b0a9-11ea-99e9-d60cdd0fe3b4.png)
![image](https://user-images.githubusercontent.com/47513960/84937499-d94ec080-b0a9-11ea-8ea7-7ed2089aec8e.png)

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
