### ISSUE TITLE
Mortal Conviction does not prevent life reservation of aura

### ISSUE THREAD

**Issue by korbok** [PathOfBuildingCommunity/PathOfBuilding#1007]
* With Mortal Conviction (and by extension Blood Magic) allocated, Mortal Conviction does not prevent the reservation of life while using only one aura skill.
* I was attempting to activate an aura while using Mortal Conviction so that it would not reserve life.
* From a blank build, socket a non-Banner aura, activate it, then allocate Mortal Conviction.
* It reproduces every time.
* https://pastebin.com/hFuyrf54 (example build)

Thank you!

**Comment by clawface** [comment]
I was investigating same thing and an earlier bug report said that red text is not yet parsed/implemented so I am not sure if it's supposed to be working at this time.

**Comment by ppoelzl** [comment]
Mortal Conviction has been removed in game patch 3.17.0.
