### ISSUE TITLE
Critical Strike Multiplier from Shaman's Dominion cluster is counted twice for Totems

### ISSUE THREAD

**Issue by vodalus87** [PathOfBuildingCommunity/PathOfBuilding#1008]
It appears it is giving the Brand Crit multiplier to Totems as well. I tested brands to see if the reverse was true, and it seems to be working properly for Brands.

![bug](https://user-images.githubusercontent.com/67081158/84964158-36ee0780-b0c0-11ea-86f1-9f702ad14d1a.png)

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
