### ISSUE TITLE
maims shouldn't stack

### ISSUE THREAD

**Issue by zmike** [PathOfBuildingCommunity/PathOfBuilding#1010]
According to the [wiki](https://pathofexile.gamepedia.com/Maim) maims don't stack. In path of building, however, sources of maim do stack; Flesh and Stone and the Maim support gem both apply separate instances of the 'enemies take more damage' effect, which makes it seem like too much damage is being done.

**Comment by tranmanh1008** [comment]
maim is a debuff that applies 30% reduced movement speed which cant be stack. maim dont cause enemies take x% increased physical damage, ''Enemies Maimed by Supported Skills take X% increased Physical Damage'' came from gem only on condition that enemies is maimed. 
https://pathofexile.gamepedia.com/Maim_Support this will help

**Comment by zmike** [comment]
It's the `enemies take increased physical damage` debuff which will stack in path of building. This comes from both Maim support as well as F&S, but it's impossible for each gem to apply a separate instance of the Maim debuff. Thus `enemies take increased physical damage` cannot stack, as both gems cannot separately apply their own instance of Maim which would be required to have the behavior that path of building currently displays.

**Comment by tranmanh1008** [comment]
You are right, its my mistake, i thought you were taking about maim link with fns. Markggg already confirm that maim damage increased dont stack with fns without link, only strongest maim effect will apply. Pob seem to stack them all

**Comment by Mwoua** [comment]
I confirm that the bug is still here

**Comment by Wires77** [comment]
This is working correctly.

Flesh and Stone says `Enemies Maimed by this Skill take (13-16)% increased Physical Damage`
Maim Support says `Enemies Maimed by Supported Skills take (10-14)% increased Physical Damage`

Since the supported skill is F&S, Maim Support will apply its debuff, along with the standard debuff from F&S.  Two maims aren't being applied, just one, but both skills have debuff that apply when maimed.

**Comment by Mwoua** [comment]
Not its not.

When maimed is not linked to F&S but to your damaging skill, PoB stacks the maim, but it shouldnt

![image](https://user-images.githubusercontent.com/7242471/107439636-5bd83480-6b00-11eb-9e1a-2736d774f5a3.png)

**Comment by Wires77** [comment]
I understand now, there's wasn't mention of linking maim separately from F&S in the rest of these comments.  I don't think this will ever get prioritized, frankly, as PoB doesn't distinguish between sources of maim, and only this niche case cares about the source of maim, if I recall correctly.
