### ISSUE TITLE
Timetwist with negative skill effect duration cause error

### ISSUE THREAD

**Issue by btsrkex** [PathOfBuildingCommunity/PathOfBuilding#1011]
Before creating an issue:
Check that the bug hasn't been reported in an existing issue. View similar issues on the left of the submit button.
**no opened issue**
Make sure you are running the latest version of the program. Click "Check for Update" at the bottom left corner.
**1.4.169.3**
If you've found an issue with offence or defence calculations, make sure you check the breakdown for that calculation in the Calcs tab to see how it is being performed, as this may help you find the cause.
**not**
When creating an issue:
Please provide detailed instructions on how to reproduce the bug, if possible.
**To reproduce this, simply select Timetwist Moonstone ring and drag the bar of Skill Effect Duration to negative value. This is 100% reproducible so far (5/5).**
Provide the build share code to a build that is affected by the bug, if possible. In the "Import/Export Build" tab, click "Generate", then "Share with Pastebin" and add the link to your post.
**No because it just bug out and cannot be saved before error**
Error Screenshot:
![image](https://user-images.githubusercontent.com/34084904/84971927-5fbddd80-b150-11ea-8c3b-8243771384a6.png)

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
