### ISSUE TITLE
The ability to choose what kind of DPS to sort support gems by

### ISSUE THREAD

**Issue by KashouC** [PathOfBuildingCommunity/PathOfBuilding#1012]
Currently we are only sorting support gems in the skill gem screen by total DPS, but at times you want to scale bleeds or ignites for example, and it becomes very difficult when you have to sort through the gems to find which ones increase the right part of the skill.

Just having some kind of options in the Gem Options section to determine what to sort by, and not just have a sort checkbox would be a good addition. 👍

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1

**Comment by KashouC** [comment]
Great work. 👍
