### ISSUE TITLE
Issues Running Application

### ISSUE THREAD

**Issue by sweigle333** [PathOfBuildingCommunity/PathOfBuilding#1013]
I downloaded the installer and when I allowed the installer to open PoB after installation, I was able to access PoB. However, when I use the executable file in the PoB folder after closing PoB, I am prompted with a cmd.exe screen asking me to press any key to continue. After I press any key, nothing ends up happening. I feel like there is an issue with my computer and not with the program/installation, but I was unable to find any information online about the cmd.exe screen popping up rather than the program when running an executable.

**Comment by Fish013** [comment]
Duplicate of #994. The problem will be investigated and seems to be related to the installer. As a workaround you can download the zip version

**Comment by sweigle333** [comment]
Sorry about that. I will close the thread and go post some details in that thread. Thanks for responding.
