### ISSUE TITLE
Required level for skill tree not updating

### ISSUE THREAD

**Issue by aaahrens** [PathOfBuildingCommunity/PathOfBuilding#1017]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Levels required per skill points are not updating
* **What were you trying to do?**
* **What steps will reproduce the bug?**
Make a skill tree
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

Shown as below.
![image](https://user-images.githubusercontent.com/10015258/85083052-75012f00-b185-11ea-9e74-0428ce41b920.png)

**Comment by LocalIdentity** [comment]
It's not updating yet as you get 22/24 free skill points throughout the acts, once you've allocated the amount of free points, it will start tracking the levels
