### ISSUE TITLE
3.11 Patch notes changed/recently added, fix tree pls

### ISSUE THREAD

**Issue by kadir1299** [PathOfBuildingCommunity/PathOfBuilding#1024]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
3.11 Patch notes changed/recently added, fix tree pls
Recently Added
Molten Strike
Projectiles now have a minimum travel distance of 2 units (from 6) and a maximum travel distance of 25 (from 20) by default. Modifiers to projectile speed, as well as modifiers to area of effect, now affect the distance projectiles can travel.

User Interface Improvements
If you have no reclaimable hideout decorations, the button which reclaims all hideout decorations is replaced with a button that instead resets your hideout to its default layout.
You can now instantly buy all decorations (that cost only Favour) that your hideout template needs, as long as you have unlocked them and have enough Favour to do so.
Improved the error messages displayed when there are problems importing a hideout template, including one that will specify how much more Favour you need to buy missing decorations.

Bug Fixes
Fixed a bug where dying in a map where Alva was present could under certain circumstances prevent you from doing any remaining Incursions when you returned.

Less Duration Support
Now gains 0.5% less Skill Effect Duration per 1% gem quality (from 0.5% reduced Skill Effect Duration per 1% gem quality).

Unique Items Balance
Al Dhih: No longer triggers Abyssal Cry on hit. Existing versions of this item now trigger level 1 Intimidating Cry on hit. New versions now cause enemies taunted by your Warcries to explode on death, dealing 8% of their maximum life as Chaos Damage. Now grants 25% increased Warcry buff effect (from 50%). Existing versions will be updated to the new values if you use a Divine Orb. Now causes Warcry skills to have a cooldown of 4 seconds (from 2). This change affects all versions of this item.
The Scourge: New copies of this item no longer have a chance to trigger Summon Spectral Wolf on kill. Now causes increases and reductions to Minion Damage to also affect you at 150% of their value (from 100%), which affects all versions of the item. Existing versions of this item now trigger level 10 Summon Spectral Wolf on kill (from 18), however the skill has been significantly changed, and you are now granted added physical damage to attacks. The minions from this skill are now also affected by your modifiers to critical strike chance and critical strike multiplier. In other words, it's a lot better now.

***Ascendancy Balance
Chieftain's Hinekora, Death's Fury now grants 100% chance to Cover Rare or Unique Enemies in Ash for 10 Seconds on Hit (from 20%).
Berserker's War Bringer has been redesigned. It now causes Warcries to grant 10 Rage per 5 Power if you have less than 25 Rage, and causes them to sacrifice 10 Rage if you have at least 25 Rage. It also causes Exerted Attacks to deal 50% more Damage if a Warcry sacrificed Rage recently.
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by LocalIdentity** [comment]
pasting the patch notes doesn't constitute a bug report. We'll be updating everything for the patch notes into PoB in due time
