### ISSUE TITLE
Purposeful Harbinger Cluster Jewel Node does not do anything.

### ISSUE THREAD

**Issue by PrinceDijinn** [PathOfBuildingCommunity/PathOfBuilding#1026]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
