### ISSUE TITLE
Installed as Administrator's application

### ISSUE THREAD

**Issue by Ninufa** [PathOfBuildingCommunity/PathOfBuilding#1031]
* **What happened?**
My Windows account is non-administrator user, so administrator privileges are required to install PoBC.
This behavior itself is okay, but after installation, PoBC will be owned by the administrator.
The symptoms by that is:
-Start menu item is registered into administrator's menu, so not displayed on user's menu (when logged-on with administrator, it is displayed.)
-Build save path is "C:\Users\Administrator\Documents\Path of Building". Of course, build data cannot be saved there.

* **What were you trying to do?**
Installing PoBC

* **What steps will reproduce the bug?**
Just double click setup file with non-administrator user.

* **Does it reproduce every time? If not, why so?**
I tried uninstall and reinstall three times, but all the same result.

* **Additional information:**
OS: Windows10 Pro 1909 64bit
Setup File: PathOfBuildingCommunity-Setup-1.4.169.3.exe
User account information: non-administrator, local user(non-microsoft account)

Also, if install original PoB(PathOfBuilding-Setup-1.4.168.exe) on same environment, it will be owned by non-administrator user account in spite of using administrator privileges.

**Comment by LillieSatou** [comment]
use the zip archive.

**Comment by Ninufa** [comment]
I found a difference between the original version and Community version about the state after installation. The original version creates the menu item under "C:\ProgramData\Microsoft\Windows\Start Menu", but the Community version creates it under "C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu".

I know this installer is made using NSIS, and current installer's script probably sets SetShellVarContext to "current" (or leaving the default). If so, it should be "all". By this change, the behavior of the installer becomes the same for the original version and Community version, and this issue will be fixed, I think.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.4.
