### ISSUE TITLE
Gems aren't updated?

### ISSUE THREAD

**Issue by k0rn0ux** [PathOfBuildingCommunity/PathOfBuilding#1048]
There are no new warcries and few attack skills I've checked aren't updated: 
https://photos.app.goo.gl/Payn9DAKzcJaQ9rV9
https://photos.app.goo.gl/T4iPjEAcPc6CcCQDA
https://photos.app.goo.gl/nmCFtvaN4HnH9vZG9

I completely reinstalled PoB and downloaded portable version and the problem is still there.

**Comment by k0rn0ux** [comment]
Just checked Openarl's version and it's not updated with new skills, do we have to wait for Openarl to update base PoB to have the updates here?

**Comment by LocalIdentity** [comment]
Updated now
