### ISSUE TITLE
item-specific toggles stay ticked and become invisible when said item is deleted from the build

### ISSUE THREAD

**Issue by xkomachi** [PathOfBuildingCommunity/PathOfBuilding#105]
Repro steps:
1. Add unique bow 'arborix' and equip it
2. tick 'you have iron reflexes'
3. delete arborix. you still gain armour instead of evasion from items. you cannot see the tickbox anymore

**Comment by pHiney** [comment]
Just as a note, if you swap between weapon sets, the effect of 'you have iron reflexes' is removed, so there is code for adjusting this.

**Comment by pHiney** [comment]
Bug probably exists for all items.

Add Augyre. change it's effect to ResTech and the problem exists for this item. (check saved .xml)

**Comment by pHiney** [comment]
I have a [fix](https://github.com/pHiney/PathOfBuilding/tree/issue105) for this but it comes with complications.
PoB appears not mean't to delete configuration option settings.
So my fix works correctly when the item is deleted. You can save and reopen the build and all will work as expected.
This fails in the following circumstances, **before exiting the build and re opening it**:
- Ctrl-Z is used to bring the item back. 
- the item is re-added.

In these two circumstances, the configuration option for the item MAY appear to be set to it's previous value, but it isn't. Saving and reopening the build will reveal that the configuration option wasn't restored.

So if this complication is acceptable, I'll add a PR.

P

**Comment by deathbeam** [comment]
This was probably solved by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4716
