### ISSUE TITLE
Brewed for Potency life/mana recovery for hybrid flasks

### ISSUE THREAD

**Issue by UberHaxorMarty** [PathOfBuildingCommunity/PathOfBuilding#1058]
Allocating Brewed for Potency doesn't show any changes on my hybrid flask.
This happens on the flask effect duration and chaos damage multiplier medium cluster jewel (only ones I tested).
The mod line reads "20% increased Life and Mana recovery from flasks".
This applies in game on a hybrid flask, but in pob it shows no difference on your hybrid flask with this node. Profane Chemistry has similar wording, but it works on hybrid flasks in pob (30% increased Life Recovery from Flasks).

**Comment by LocalIdentity** [comment]
This is fixed for the next update

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
