### ISSUE TITLE
Archmage Support No Longer Working

### ISSUE THREAD

**Issue by Reithan** [PathOfBuildingCommunity/PathOfBuilding#1060]
Archmage Support no longer seems to be adding mana or damage to supported skills, as explained in #598

Noted when using Archmage with Arc

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/85256210-e6e9b900-b4a2-11ea-9aed-815dcda0a913.png)
can you please provide pastebin for build so we can recreate bug?

**Comment by Reithan** [comment]
https://pastebin.com/8LkiN9qz

**Comment by Reithan** [comment]
It's my local copy of Enki's 3.11 Arc Witch build

**Comment by LocalIdentity** [comment]
You have Vaal Clarity active, archmage will not give you a damage boost if your mana cost is 0

**Comment by Reithan** [comment]
I definitely overlooked that setting. Thanks. :)
