### ISSUE TITLE
fist of war support is incorrectly implemted

### ISSUE THREAD

**Issue by Durandle** [PathOfBuildingCommunity/PathOfBuilding#1062]
fist of war is not taking into account attack speed having a thresholded effect
noticed that a level 20 fist of war support was going to be a 66.5% dps up despite being a 148% more on the next attack every 1.8 seconds
this means that it can only be an increase of 148%, 74%, 49.3%, 37%, ect
depending on your attack time using the maths of attack time/fist of war cooldown rounded up times the more damage that fist of war gives

as a demo to to prove that is not working correctly yet i made a "build" that gets +498% from fist of war support

https://pastebin.com/FAAk8g7P

i get that this is a new support that does comparably odd things but i figured i should report it anyway

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
