### ISSUE TITLE
"Brand damage" nodes does not affect Spells conected with Arcanist brand

### ISSUE THREAD

**Issue by VayneHolt** [PathOfBuildingCommunity/PathOfBuilding#1063]
All "brand damage" nodes in the tree doesn't work with Arcanist Brand.
With Penance Brand everything is fine.
![Screenshot_24](https://user-images.githubusercontent.com/67261847/85265118-0fa58a80-b472-11ea-8fb5-c5ba3109a006.png)
![Screenshot_25](https://user-images.githubusercontent.com/67261847/85265123-10d6b780-b472-11ea-9e4e-559a7f2479cf.png)

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
