### ISSUE TITLE
Arcanist Brand does not correctly support skills from items.

### ISSUE THREAD

**Issue by nova-a** [PathOfBuildingCommunity/PathOfBuilding#1065]
I have The Whispering Ice equipped as Weapon 1, and Arcanist Brand and some other supports socketed in it. The Icestorm skill, when hovered over as shown, does not show that it is supported by Arcanist Brand Support, and when viewed on the left-side panel, still shows its own cast speed and mana cost, as though it can be casted. 
![issue1](https://user-images.githubusercontent.com/25011379/85282657-1de7ac80-b45a-11ea-8aab-cf0097cd8acf.jpg)
![issue2](https://user-images.githubusercontent.com/25011379/85282658-1de7ac80-b45a-11ea-8b0b-ef90cfc99dc0.jpg)

**Comment by limzw** [comment]
Hi, any updates on this?
