### ISSUE TITLE
Zombie Spectres support

### ISSUE THREAD

**Issue by BassOfBass** [PathOfBuildingCommunity/PathOfBuilding#107]
Aukuna's Will allows to raise Spectres out of Zombies, so please add them to the pool of available spectres.

**Comment by pHiney** [comment]
I wonder what stats they would have.
Data\3_0\Spectres.lua has all the stats hard coded. 
For the new Spectres (from zombies), code may need to be written to take the stats of current Raised Zombies ?

**Comment by BassOfBass** [comment]
I am not sure it includes current zombie stats, since they don't inherit the size from Mon'tregul's Grasp for example. I assume they don't get bonuses from zombie gem levels either, along with any non-spectre support gems.

**Comment by QuickStick123** [comment]
Closing in favour of putting all of them in one issue https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4558.
