### ISSUE TITLE
Add please the spectre "Baranite Sister"

### ISSUE THREAD

**Issue by JasderoFox** [PathOfBuildingCommunity/PathOfBuilding#1071]
I can't find spectre "Baranite Sister". Add please :)
https://i.imgur.com/LCuroZU.png

Video with this spectres: https://www.youtube.com/watch?v=pr7ndTWtzqU

**Comment by LocalIdentity** [comment]
Will be in the next update coming out within the hour

**Comment by LocalIdentity** [comment]
Added in 1.4.170.2
