### ISSUE TITLE
Rage Support adds no damage regardless of the amount of rage set in the config panel

### ISSUE THREAD

**Issue by bwoods89** [PathOfBuildingCommunity/PathOfBuilding#1072]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
I have Rage Support linked to Tectonic Slam, and Rage in the config panel set to 50, but my dps does not increase. Varying the amount of rage has no effect, from 0 to 60
* **What were you trying to do?**
See the DPS increase of using the Rage Support Gem
* **What steps will reproduce the bug?**
Equip a melee weapon. Equip a melee attack gem. Support that attack with rage. Set your rage to more than 0. Observe that dps does not change.
* **Does it reproduce every time? If not, why so?**
Every time I've varied my amount of rage, it happens.
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Quotae** [comment]
Just put a PR up that fixes this over at #1081 . Until that gets merged, you can add "Gain 1 rage on hit with attacks, no more than once every 0.3 seconds" as a mod on an item or flask and Rage will work correctly for you.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
