### ISSUE TITLE
Text bug in the item area

### ISSUE THREAD

**Issue by zakt4n** [PathOfBuildingCommunity/PathOfBuilding#1073]
There is a bug where some text from the item stays in the background after you press "Cancel".
Works with a shield I got from my acquisition and it's a legacy shield, I don't know if the combination of legacy mods somehow bugs the text but i don't think it does.

https://i.imgur.com/Vj20ek8.png
https://i.imgur.com/WA529OJ.png

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
