### ISSUE TITLE
Can not import any build,invalid code

### ISSUE THREAD

**Issue by Denizberdan** [PathOfBuildingCommunity/PathOfBuilding#1079]
As the title says,I can not import any build because it says that the code is invalid,
I am currently running version 1.4.170.2

**Comment by LocalIdentity** [comment]
Please provide an example of a build that does not import

**Comment by Denizberdan** [comment]
https://pastebin.com/NV7UqnNU
https://pastebin.com/GhDyyfZD
https://pastebin.com/r3EEZjCa

None of these codes work and one of them is the one my friend currently uses so I know the link works

**Comment by Nostrademous** [comment]
@Denizberdan all of these work for me today.

Where you getting a 302 error?

**Comment by Denizberdan** [comment]
There's no error code. Just a red line of text that says 'Invalid code' right next to the textbox that says 'To import a build,enter the code here:'. 
![unknown](https://user-images.githubusercontent.com/59388168/85852784-2562ca80-b766-11ea-922c-1c71fdceda0e.png)

**Comment by LocalIdentity** [comment]
All the Pastebin links you posted work just fine. Have you blocked PoB in your firewall?

**Comment by Nostrademous** [comment]
Why aren't you using the "Import from Pastebin" feature and instead copy/pasting the code directly? Also, the 3 pastebin's you linked ... none of them end in the sequence of your screenshot above.

**Comment by Denizberdan** [comment]
I am aware that the build PoB links work but even with the firewall turned off PoB still can't get the builds for me. Also I am not using the Import from Pastebin because I live in Turkey which means pastebin.com is blocked for some reason and I haven't had any luck with using a proxy on PoB either so I just figured I could use a VPN on my chrome and copy and paste the code.It worked until I reset my PC like 4 weeks ago. The build I'm trying to import mainly is this one.
https://pastebin.com/zUaYCxtV
I just gave you three links I was sure that worked.The problem persists though.
On a side note I can import my own characters using character import.The only problem is with build PoB links

**Comment by Nostrademous** [comment]
I'm sorry I cannot reproduce your error. All links, even when I just copy/paste the RAW build code still work for me.

**Comment by pikzen** [comment]
This sounds like an issue that is more related to local conditions. ISP injecting data, or doing weird redirects ? Considering pastebin is blocked, there might be some DNS issues too.

@Denizberdan before it stopped working, were you per chance using custom DNS settings (8.8.8.8, or 1.1.1.1, or, well, any DNS that is not your ISP's) ?

**Comment by Denizberdan** [comment]
Yeah it was local decided to format my pc again and that fixed it.
