### ISSUE TITLE
Flat damage supports working on wintertide brand.

### ISSUE THREAD

**Issue by Brambird** [PathOfBuildingCommunity/PathOfBuilding#1080]
When I try to add supports to wintertide brand it shows a lot of flat damage supports, like added cold damage and added lightning damage, as the top dps increasers. Adding those supports gives wintertide brand an average hit and gives it a total DPS, which obviously shouldn't work like that on a DoT only skill.

I also feel like the dps isn't correct, since with a full cold damage over time/brand build I only get about 10k dps.

**Comment by MustDy** [comment]
Can confirm. 
Wintertide brand dps calculation is incorrect. 
Flat added damage should not affect dot dps;
it is hardly affected by cast time, as activation frequency is affected by it, however it provides zero deference in case of adding/removing cast speed;
Also it should have two different calculations, as per mechanics - before activation single target, while it gains stages, and after activation, AoE dps.

I guess its dps calculation should be rewritten from scratch.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
