### ISSUE TITLE
Allow dynamic gem levels based on current character level when comparing support damage

### ISSUE THREAD

**Issue by AnnanFay** [PathOfBuildingCommunity/PathOfBuilding#1082]
Quite often I'm looking at what the best supports are during the campaign, levels 40-60. Setting gem level to 20 will give inaccurate results but setting to level 1 is even worse. Gems with a high base level are pushed to the top.

My current work around is to set it to the average level of my current gems, add the top 10 supports by damage, then manually set their levels to match my current character level and remove gems 1 at a time.

The solution I'd like to see is a checkbox or other input in the Gem Options form next to "Default gem level" which offers to make the gem level based on the current character level.

Alternatively you could make the default behaviour based on current character level. Then you wouldn't need a new form input. If the gem level is empty make it based on the character's level, otherwise set it to the requested gem level.

**Comment by ppoelzl** [comment]
PoB's main identity is as an endgame build planner and optimiser. It seems to me your specific use case is both niche enough and already possible to accomodate to not warrant any action from our side.
