### ISSUE TITLE
Barrage Support Gem is the same name as Barrage skill

### ISSUE THREAD

**Issue by donq123** [PathOfBuildingCommunity/PathOfBuilding#1083]
Version 1.4.170.2

Name is the same under Socket Groups

![image](https://user-images.githubusercontent.com/12173403/85370010-1547b280-b4fc-11ea-93d3-39904b66fb4b.png)

**Comment by LocalIdentity** [comment]
This is cause all the support gems in PoB don’t have the “support” label after them in the gem list so it can make it confusing. I don’t particularly want to add the word “support” to all the gems in PoB that need it and would prefer to only have it for this one. I’ll look into it when I get back from my break

**Comment by LocalIdentity** [comment]
More meaningful discussion in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3227
