### ISSUE TITLE
ProgramData folder place on a same disk as PoB instead of system disk

### ISSUE THREAD

**Issue by FastMethod** [PathOfBuildingCommunity/PathOfBuilding#1088]
Dont wanted PoB to be installed on a system disk (SSD), so choosed to place is on another disk. Suddenly a "ProgramData" folder appeared in the root of that another disk with "Path of Building Community" subfolder inside. This is misbechavior.

My OS is Windows 10

Btw PoB itself works normally.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.4.
