### ISSUE TITLE
Mana Reservation Rounding

### ISSUE THREAD

**Issue by jehzir** [PathOfBuildingCommunity/PathOfBuilding#1090]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

Version 1.4.170.2

* **What happened?** The amount of mana reserved by 2 - 20% skills are being rounded by POE (19.9 + 19.9) = 39.8
* **What were you trying to do?** Attempting to match in game mana reserve. It has the correct total as 1429, however the reserve is off by 14 points... Unreserved Mana: 28 in PoB to Unreserved Mana in PoE: 42
* **What steps will reproduce the bug?** Put together a spellslinger, volatile dead, detonate dead and elemental proliferation. PoE has a reserve of 39%  
* **Does it reproduce every time? If not, why so?** Yes, based on PoB tree, and skills. The CORRECT rounded total is 40% but the game is rounding the totals based on the reservation from the tree, as it is a float variable.
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

![PoBBug](https://user-images.githubusercontent.com/59735392/85480718-58923780-b575-11ea-9b03-875bc8229804.jpg)
![PoBBugTree](https://user-images.githubusercontent.com/59735392/85480833-8c6d5d00-b575-11ea-9347-429ce0f78201.jpg)

**Comment by ppoelzl** [comment]
> Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

Without a build, this is impossible to debug. Please provide one. @jehzir

**Comment by Nostrademous** [comment]
Fixed
