### ISSUE TITLE
Shock's increased damage taken is counted twice for minion stats

### ISSUE THREAD

**Issue by Sectoidfodder** [PathOfBuildingCommunity/PathOfBuilding#1099]
Simple PoB showing the bug: https://pastebin.com/K2R9NC4J

With "enemy is shocked" checked and "15%" in the shock effect box, minion stats end up with 30% incr damage taken.

**Comment by LocalIdentity** [comment]
Fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1126

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
