### ISSUE TITLE
Multi monitor crash 

### ISSUE THREAD

**Issue by codydbgt** [PathOfBuildingCommunity/PathOfBuilding#1100]
simply crashes when i go to tree after 2-3 seconds of clicking. only crashes when i have my desktop extnded to anohter monitor if i move the window over to the 2ndary monitor it works fine. im not shure if there are logs but it just pops up with a windows error i hope this was helpfule in some way.

**Comment by CollinHerber** [comment]
Hey @codydbgt ! Are you using the full screen option or simply extending the window to another screen? Perhaps using something that the GPU drivers offer such as Eyefinity?

I tried this on my Machine and am unable to replicate.

Are you able to copy/paste the error that appears, if any? Or perhaps take a video of this happening?

Thanks!

**Comment by codydbgt** [comment]
this no longer happens
there was no error btw or i dont know the log file location
