### ISSUE TITLE
Soul of Shakari is outdated

### ISSUE THREAD

**Issue by nitoplol** [PathOfBuildingCommunity/PathOfBuilding#1102]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
In patch 3.11, Soul of Shakari was updated. It no longer makes the player immune to poison. Instead, it provides 50% less Duration of Poisons and the player cannot be Poisoned while there are at least 5 Poisons on them.
* **What were you trying to do?**
Select Soul of Shakari in Path of Building.
* **What steps will reproduce the bug?**
Start Path of Building, create a new build, click on the second dropdown of Pantheon, hover Soul of Shakari.
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
