### ISSUE TITLE
Wintertide brand

### ISSUE THREAD

**Issue by Aleksidius** [PathOfBuildingCommunity/PathOfBuilding#1107]
Brand stages are 20% more multiplier for each stage and not 20% increased per stage as it is curently.

**Comment by Quotae** [comment]
They seem to be applying as more multiplier for me. Could you check again and post a pastebin if you're still having the issue?
![image](https://user-images.githubusercontent.com/39030429/85749703-b1291800-b6ce-11ea-8efe-5e81f4eaefdc.png)
