### ISSUE TITLE
Combined DPS Disappears When Equipping Certain Quivers

### ISSUE THREAD

**Issue by dsnvwlmnt** [PathOfBuildingCommunity/PathOfBuilding#1108]
1.4.170.2

I can't make heads or tails of why it's happening, some quivers bug it, some don't. I even tried remove mods down to the minimum that affects my build, and it still bugs (see image 2).

Occurs every time without fail with these 2 quivers.

Build code: https://pastebin.com/hKV2G6Rt

![image](https://user-images.githubusercontent.com/14173022/85754099-a87e1500-b6c1-11ea-9782-52d5c94407d4.png)
![image](https://user-images.githubusercontent.com/14173022/85754183-b9c72180-b6c1-11ea-8e96-8d7540c39a71.png)
![image](https://user-images.githubusercontent.com/14173022/85754441-e8dd9300-b6c1-11ea-8a79-84d2f62c770f.png)

**Comment by LocalIdentity** [comment]
The Pastebin code you provided has expired, can you please provide another Pastebin link with no timer

**Comment by dsnvwlmnt** [comment]
what the heck, since when do pob pastebins expire, and so quickly... Is this normal?

I don't have the pastebin from the OP (I thought they persisted forever), but the character continues on, and the problem persists. with uniques even. Switch to any quiver but the original and Combined DPS disappears from the build forever, it seems.


eNrtfelz27i25-fWX8Fy1Z16r-KFALjmJfeOvDvxFst2Ov0lBZGQxJgiFS52lKn5398BQEkkRcqQYnfeTN3uKscmgQOc_fxAEHz3rx_jUHtkSRrE0fsttKtvaSzyYj-Ihu-37m6Pd5ytf_2z8-6aZqOrwX4ehPzOPzt_vBO_ayF7ZOH7LcfZ0jKaDFl2PyNFvgKpPo38ILuMkzGFVpdxxGbX3m99TGiQTaPZhQuWeEHI0nTWzgtpml7SMXu_dUOjIUu2NJp6LPIPFjf4tAZB5PObYxpEvdh7YNlJEucTYGZLm9AoG7E4ugiiODmJ_fdbJzTJH0Y0Kt2j34p7vTikSZBuaY8Be7qIfRjg7OL66uZ2NseDJGczPkAGf7y7DumUJb2MZloKP95vdUGUdMgO6Rh-AiEa5kDFss1dbNu6QRyEXXdrr7lzb8KYP--Ed5Fj4Jdoe52wo8GAeVnwyA4SYAP490qz27Xbeja0Nnct7Kxqf5GHWTAJA66T-fR00tbldGkEx2hrextnNDy87s2b2sQ2dm1dN13TcJC9ul-cLSaELQcbu6btYKDQys7ZMAoyVh6Q7JomfqZ5VfcImLet1iE-B9loeRhMDKzjXYfoDsGu1arYOEjjqNJRJ2iXEGLpNrJd8kzH6kwNGxm7GNu6qVsgllUzbhjYxLZr7hJsYWwYrTM-iMf9IGL-Uldn1wFlqHTtPg7LckKuC77lrJTTBY3oQZwu9E_MVr_KFmaL2lV9w75XWuqtYx-yH6VhjRUEyy0xareyKCsZl7OCYKWlidpangeDknvjdleFmOO95a3PIm9B2DJWEb6LEpay5LEUrFYNUe1yDTmBlZnQ9VUdb9iQRSWO9V3HsVd1OGfMG51A3rihWSkeWrvIBRfCEK1dbK8yqsVgCOsrxcZbl8Vm41V0G6S2AwFBrUtdajvIgfhrgndjh_9cRaUqQmzvrmzdLD8Yjhh2u2UeRSwZTnujgIUL9my0UnzlPmUxtjtyuUeVK12lSzNr7V0fKS97FuxYK1M3MCQ7VDyp3UUvWMgYdPFZPXc7L9jlOom_8SohXLNfNxnHefK8kATjsnGZb9xqY9ejaRp4kLpForphfg6zi1U0OSt3LuJHNgZnEOUSlHQLYe-2Z5r9EMrIGvermArDtXp0s4x6D4exP6yL2DRXjtLUpd3MjoMERJYGpbRnm-3JlXtJpbG5IkgPR1kEOECd_IjGaa31Trva4yeWQBfAE-nz4iy3vqClZNsqmIRFP6fK9CvNlQY4ivw84VpSHqPeQ2mYrrBwqG3Z-DwYB6U0KXq82xMQjf92Np7ESaYBbsq6nhfnUXZK09H7LZ-alu1Zuum7yKaO6Xo-MXRHN7BNkUWZoRP4nwK4411vGA3HIO8D-SefKvUylkhanutA1UmgdIREpXuEMYA7tukaOnWtAXOIYzCCkTSRdwc09FLB1lk0yTMtEnBuHKTe134-GHDwtQVsJgKGHh0fHx3cnt0fFZIod0kfgjD8GuXjPscb8t-ZBP5412MiYGheHIZ0kjIAeQMapkA74HiP9-1BnPQypfYAVYqSWaU1xxtKsxBITqUlR1dKDUHfNGTqMridThg3rFRVDEUQUmm9H6qyJ0GFGoMCMampgXl0qtRynvKVWh-FrBuEPLeoSe0CbFumJbX2kCWSoJ9nTK25KOKV5sHLViUGy2Wa0oxlGaBEuyiXVNoWaUPN1iANK2vjkA0YWLGafKXj39IHFhXRdRbC3gkXSrUUQuwJG6f7UwC3x1xqNbhbafB-K0tyoO2zAc1Dfv1TTsMgm77fioKwfP1cLrGJq-kofurlk4mkxN2WL5dd3Vx0z-WClJiLWAqT2UH8LWYq1sNC2ue0Lrpnl2-12_hH4Gk33OA1FtF-yFmWs0rDmNdBsT_VZsVdjSYnx0f84x1MpOh-EsZ9GuK53L7POALMMVspRO6WNmTjM64DllGfZnTvDDJYusdFs8dnczXoAYM8bYrgzptWL5dHQ7Mp1zjg2YHXm3zxZ8GmIHgRRGKFspePxzEo5xqCWUbTsbQDNYZ0VYYW2roI-MpgN_FGPFPNWVvZ4JommVDceixLSlqFVJ1rUZKdxCFbh297fbZnNfwCXBT1b7H4VBeEUvsN5XIfeEGcp9qCdvqS0oHiZm3xQEoAbr3psiBqdzZkuUblRfjcwPjv48CHzBNM8pBKCFdnt6XFppoGaloDuRfm31Bkv-v7AZ8FDUU0X-a-uYEi88X8SkqHev_pZT1_A53f0Engy_Jrid_yvfU023sKBpnWHQzCQC4GbMID1hV56IVckMvxosRKW5NNlSfpvVaM2kAGxwD2WCKj8DL71btr8io7a7J3uhEb5NVccEOne1VdnLM0BWOTSGmJhYa7m1qhJKVVaP0uAwTNFIO1FQ3LLdZkVxDQBAWtgvH3RLW7Rm29f3X45a12yGg2-l90Eqf_lWpX8LsmH02ny5N44Vq7FKgtVfkmHo1YL08aRbt0c8OULAlpZUovnZlM1czEV5IBleVJSzHS3GBDxrkraXNSr5pyD-KIP_qBoZgvFxuWeWtqsx5DZQpaQWIjtpz_9ysJZZv7_RXwq8bol8Yxy-l1RmbDuHx6dH7xVtsPg-gB4mwSP21r1yEd5kzbZzThxXLjGsgpC8cs2ygkl0JcbUqlO8XFg1DsedrA9zkp-E0wJvgqaWDpYmk2G5hUSXi1AC6n_6qhrce8OPI_B5G_qnQ7iOPQj5-itWOBoK4J8nuvkGsLLUmLmxncnI2DGGSactsaJXHu_5rj16z6VRItUlTaWeQljKbM78I_V4O2lLSq2YZSmJPUOE0tHmgVqn9zKVuon2-dYvyZVi9jk7IYQnFjicdiwPagOCeoCYob6VLNcEFLtAyaZhfWjOJFt1eU8T2l4UlCvXIpW7-2aQ7idDRJ6JU5gFA7HGU1FmYXN5l10XfD5HlyfnV_1HurnbKEhj73pu4wjqbbUGAAb-A2YktCYwKFaT7yJYwXTaDrJxI586uBmHdJrk3X5-axnDPxunGoJrFa-KmM3oNCFtB7yMvqV16NDULGH4tEDctZh6wfAGGx6-nXnAUG0Sqj_K6FSDlu29pBw91NWZaktAqtX2H6JR2gJA4ajBvEsLi6wv7XfxS1IPvrxaIyGvmdD50aHOFVnzptIB6xN1DydhUd52EotwAvmcSKZpsKQ5LTwEs4Qa1E8X-MoxRpuGD8kSW3wZh184SWJNR681e9pZRO25xmkzXJq1vI3rJa3NYOWTqhQdL61D_O0r9rDbJSGJfk-7m5IH5GfEWv18WhfCem2HTX8Ciofm9D8CLoaGVCvy118pd5Wrgt31s3Ucp3hJjkMX0VHmbVdB5GUGWJoqZc-NWcQFU1s26vOONjSBCjbuT3MrEmVFrNiWO_RyN_9pjgV0xMDKIBMU0Os2Fkubo9PbpZGua1a31FICWdBf7KMpb0RVRb2PDS1fUi9_JjWzGY1ka3PCLfbP26CX4_pOlkxMYNy7H1W5sm8gWdV4TCt4zvXKYhhLsqWKnfWHPys-5a0f8VF04S5gVpdb2_63lQMHhT8HG-pTctlQ-baqM-zN9WTK3lischTFjOomyX4laQVO78CgZp800xvFYepS6m0gRf0ap_S4BXs4tFBih-EztcbxPGNCoDuiBOit2m8IeWBVnI3m8lcT4caVnsx5X3tDlfBOYV-3yrqmUghLaxbjj6tqE7iGwjy7W3CbYMnf-08LZlYtfaNhHS0bapG6a7jQxkQhmZwSRKb5fzNWhvNgIu8svdzbn45Y9Rlk3St3t7T09PuxOajeIB-wHAa9eLx3sT6ASc7AiB7HCye134b797dtg97nYjrJ_Ef-50B2b_69EF8y_1p_eC-N6M-rviWb4cqvhLsMjngizMH2wGmTSE4p2PhnYImbpCOws5xFBohw3XVqEHonVV5mc4lu2qjEu4Kp5t5oK-FZoRy1LilhiGQ1RmB8wqSc-ysakyLrFNlXEJstTm59oIq2jNRK6KdpFuEhV6lm4TFX5t19LVjE_FCAzLRK6SlC2iQs8yTEdNG7rKsMhwXaLEBlFqh8FYLBXluqajZHzYtpTmhxxbZVzXdm0VNrDrqvkQclWGNVzdUYt82FGJGaaBsK1kVa6jFtHUYgaysZI1G5bjKPkksiwl-RmQNZXMACuZC3YM21SyA35WhgofhpJckGMQNXuxlPRhOPygDYVxMbKUogsmKmZq6IauFJoJUkrQoDWkFNQsVy1IukjN24jeYAVQBy6qHfgDSr6l2u9_n9t4RdVHMEJQ5EFsdbbBF6C8I6LIIxbGCK5gx4VSj8BdWQLCdcee1YfERsa2YRJL33aNbSitzG1s246zjR0d4W0MscQtKkoRHreRbdlQM7rQDcEPg1eUSN-GhELcbQPGNWAACwaAysB0th0dCk1Ldw0-rgmVp2nAECbMkk8WJrHtYt0qSlELAhfZhixhO_A7gjFNy4YhTNGO6HwsDNO1gYVtCMK6vW1CArW2EQZnhGYOUMUmgu6GztsQ17LMbVHMbIuUvE2EICBRQhviAB_bDpcbMA43sYlBDhCeQG5AEmaOCSEwIBRNwK5hwWXiwPxloW260AFGJXweBgIWwfBBOtjUgXPkEgxlOHIsYM_BRS2OQRTbrmPz3xzoRxzXBXoml48NxRl0cLm-kOPAYLqDXWDchs4wVehj6CYIBWFetmMXynlIMdvctHhNj7nCODMOAVlBmIW_XRP4Au257t9U4p8iFHU_kouzaPjtT6zrXi8YmPTy0XSzy78-_rjo7rODszD9doJSjx5_6p5-tfdzz_r0kJx9TRIcW4O7b7p7-TBy9-2hcdW7DFwzDFDv4BrbX64Pr_L0jtDh_Vn3KviaBmb34eHWuvzyNLj86-5L-N3_Pkl-jJLr7JrQg2zw8X6_d_79_i4Lkg_55cXpcf9Dcne237_D18zX0cH17eCbE31hH87Zx6uPx4lzEn8a5h8m9zc35uj25It1e2p9Op5-f_h-2-v551eh74w-fbh0P9FvzLWm3aeuPba-__l5GF7bj9_-DWP-p8GYlqC7OYxRq8NVUYxqhn5pFKOKTlRTpSoqUk3RqjhGtTRQxTuKOEa1cPlNMEYZZr0sjFFFT6owRhWeqMId1SUDVRijXIYrwhhVWPT_C4xRhW2q8PN3wRjVJRxFlK-65qK8ovayMKa2MEjWgDFeniTPwhhZ8hIdAaZAtiEAjIA0ooaXkEbWuxLMyLpYFsNlMONwuACltqz3AaKYdgFjREUFFbcDmAJ-wjgS6hSwyDRdIgv0EtIB8lCr89ZOgXokGAKXBUwgIkaBNWRBbsKYEhHJWlzU_xJdYAIOLIFWCSFJKCIQUlHjC5wE5I0ZUDD4gBIyGcAJkrhAIhkJn0yYmF7AJwkgSvBJ4kB-5l4BICQ-MKEuM_isobur624FPhWgxsF4hp4sPmOJtgSSkWhFIhsBlQrw5Bj67FkDyAEaSpQlgJEETxLrIS77AjZJaGWY0FNiJxPMgBRPLySELEAreLBbIL8SfpJATMJJgcyAqkkkbJOYVmI6KC5gNDAbuAeZ0i0Q7AI_FZhNoEmBnywDW-bfh58-PgCGevh0mf08OElBwjaZfA2DnxPAHeghOXo6y8-6f0b0YGqjT92D_Kr_eXr5aJ_99WFyd2L-nBxMzOzjFHDV2P589OOv5MdJrP8VPNJv_e_x50f8Mf3zqHsW3OHeqX5yv__JPPtzcP7lsUfP7u7Y6dS-P5scPjxE_T-n0-vDw6v0-0TgrfPbm7Bn3B3co_gniem3Hbov8FZ2ubP_w86uja_WxenT2fn3T8f73wFnTfLLm53zr0fXfXqWT0ZGjg8vhkdfP_z84h799dc5u3DuB8Zhfjhxs979aYwmHG_Zd2fTa2yS2yf06TPqnz09eQPr-gijSyAv8db3q48o_BRef00__A14i1j_Bly_FXD9pudGtTSHrV-GXGqYQbXIUkVmqtjixZ8cVREmcX710ZHqWrYi5lIs2jZ8coTdXy0qVZGy6iOm3_ToSLXorWEu4v4qGHh50KUG9lRBlzKIUwRJyqBLEeyprqy8NOhSXZNQXRFTXLBTXTJRfiD-sqCrZX2tGXS92-P7ifgvl3HGxD1-cfaH2G10H7AnLWU08Ua9LHm_Nc7HWijeFfgZx-Mv3H_cXcBa4EQmRHIsj8Y7ZTS7oJP5Fi3etjg-zywOz8todhgMBiwRR__Ntk3xhn--39qxbH0XQdWu66bFBSlO-hM7uIrtT_z3HpP7sfKUFS8lMzqJI3FZDixPKYWm4uhAVOx-vaFJkE3fajfdm6NO74G__sDfN-5005SX25G2Hz91RC8x57eaTTrFoYBvNax3Clm-1U525v93RNMb9v2tZuHO2XgSBl7A26DOG2z-Q8tiTW4Y0_hOQ_6KiwbyDB6YtvhMQ2f29kvx4tJbjeg7jtup95CHfsJAu7b-j05xZo82YYkmxQCD7hJD-w-aD_mxmMz_z84h-wFTRxgmw6ciJsvfhZOsMJ-zrPG9cR37H1qweGVX0NbEyajQ1VHk4_94CR0A1f_7hkjWy-e5aPEjzJS_rVHuws2Si7yqMaxXNXZ3efbp7qjTzZN8_Bgn9Ednn6bc_vnhE0DlLgq-50w7O3yrMdPUB27f59iceDo2PBt5lgHZ0rFwH5CDb2A66BueZdtoYAx0YtOB50Px0CfUs2jFACyr2QD2d_a1m5Lqkb2p6iGNlwVfs4QO1v-hJfIsFE0Kg2tPOsQgzsF435iuGIqCNR-F4qxt6C7P7OTmknbeEPGWjzak_CRM6JZojHoj7Shi46k2CjKtP52dANWiD6uqDnngZeeEQ1utB1b5UNaA65i0T5iJfWwCMEfMs4iHHKT7A5c6UOX61LMJGzg-MgwXI1-nxCR9xzRt4js1DZQ8sCJ_7noVkRO9LMcWwUsPamESkUaj-5Tzffj8-MpOb8RPceZRosyuTbHTt9DAQ4jpCKpf5BNHH1DTt10X-XwVAsxvwPQ-c3Xs632oGSlUyZbRh25ehV0wslURRyvHG7MsAL3zBuncDsDjM8YZ6CBdX2Vatds1l-cnl1A1k3HdyjDzl-xmtIjL5zXbcw2SzIJoKPQVioN55HRadGI1hO4TKoiDQjv7SUz9EaO-PBVDA2U9VuMBWNyg75ABsk2dWp7tYhsc3_AMPDAN0_OoCUrqW4aN9YFPLOx6jol1anoWdENoUI0HuCR_w6haYNf3U83ivCJclza_ykPtTGaiLeJXscZ3XpeazZqsCMi2COZj-iPgaZk7d4esVkKzdAGwL0v3ME_5QDApsHeaPGRxnI2q4q3kyLJIzHocNBRCzzTOk0bBNMhwuZmpzU_Db2jXJKo3WEZMIfdFoITJEpm04tAvX59nNYRbVdIsX6cxoPS8OJkEcTQ7neyAh-7_GMfiBLSApv_ZZtUVS3RXiH0dS3xj1MOGa-w6Um3isx1MHjO1KDO0pxE3LF4v8f3yEFuFmCy9xQKLcZt7vQFv5OMXB1IX0WHRuCc30Iu2vA4JWo4VaenhrqkxYiqr7N9aen0tacGAh4d_PTLNG_Fv0M36ANP8BLRw2qJHsyGwXUCtD86dxBHtnHMurlmY1WNZS_a92dmv1Pq2Xk2-UF9AJWDKehuZcDfKxIU3CFcV98YxliMSwS0RSRfXFxGuKSyZZll8VRW1mbndaOa3tJ-HFLqmtNMLxvz90Ju4z5qF8nln_n9VFi1DNldXS-c0AhrL-Ith4hiOqnb0FdrRqgX5EhZD6JkqWb7yw8GSWYVQQrXI0Qvd6qbULdKdzklCoywtUBXW5aGTGn-bTBPv7oAC3dmoi88JdJDRGpWQQ6rewyfVeWORJZsBfviZJrJz4bziAwrQjaayzZc41zIKda9h6lUsxuNEKuMET8qk-CPl5wJ85DM_icEUjyH1T5IAeGxTKm7zs880WQDrmX5PaNKvqhQ1lvcn4G3c426qOnVqFX9ZUrPvDBVyFEpznEJnDpE6g3_fODV3tKzlwNaxjBUuBbbkNBQVVrMLF0i40YX5sWP5JGvNRshuEO9VlIZgnqNM-wCq7xwkeUp9UKd4k3JMg7AiYRO1A4r9JUhhkKorz5yCELviE1WJAGUTVe-LT1do8tsVoDl72aMsYxYsUREs5xAG_mRhGAyZSA542SHEW3WVMUCPDYUeIY06QRXI3cvySBAUH6_giYUvVEw7MC6dH2u3lJ_n38IqLXpg3W2wpRbPQc0ReAQgFcaPILB05HlEaRA-yDCskqpuKmnKcKv6lJGLGJ35-s-JWFpL-LGw4u1kuAQluYxoyNSWj-WtdR1RyM2yVrigw8ADR7AbdFiReFVzqFKRVBTYsjhkt4ruaAyofwxF2AFNuNYuggxiV9uSXiWZcWcoRxuzluGFsRJXihD-VZIg5ITSKUwFahHywUZVqm-s9pgiG5YMuCpOeUT0_IDb56OK3hBVzmNxRjLkKL_AfemDWBGN6wJcHVBa8fE8f1qFu2Pwz3owRk0O9MYhDa5tN2K1lRVTdYmoljFabK1p6fiqHwaPfIJ8j9Kk0x1CpaJ1x3nIquUkFPxt0sCLsNENIe4AhbT4HoxcqoKSH4tCEf5k0TCTbxJXvOoNqTSoOdKSEBvsa210Xop1RmNobZZiUxrrToDrcDpJwTuegiTkZstLMj7Zmr2VhGi1CFG-Vp1qafFaNZ_5Fz5z-Z41N4Rbfjh8EbBwpWSeuSDRl0WEdNJkkpbbIM3n1mFxczpaFPLrgtUmRz6NI873eRxP2kQKhVQpzrXZpRDfccLYT9aPw2wmP58BSXX54Tr8aZBcBf61rHITo9nfi-urEZKMu2Im2KoWwqW1omYhuw0yLiIsN4iPUZx1bp_iHfGS_zOyJuba5uvFeaZguqhUfVIBcytySmeKmMm9VjzZ5pJSFqsKGtrFMlAsUAPQQ-UufLW4QypVs1hAnlMpnEd41DN-0pK1mtYqb-NEhvARaDCExJVNhwGNIOmmrJ7255mqW4URp5SvJHb7UwArYfFgDMy0wZaJ01Li681pGtlLdeYsSXOcxcNs0M6v02R4FEw1nKZjHvXpZAW_xpr8GvZ65jETxnICxu0OecMG_FuPKeDNhvUucdpd4Y1g7m0ZuQY5L7onZwedLpTMQ5bMgCZUKEn2k583kj7wUCIG_sGqlYxlViqZhZtiu1q42FZ7YtX8XBz_K4diYpWrTaONM-8xlo3E4jXUFBBBhKPNJ36S8PC3FFSMlplbtaLVshaPD7tj_t3RGb6BpHIWcbVkC8RzNh7nEQ--vKoYcTDUxNwNG_MDZYsWIIg8bcv7RhPD4lOr4sRksIksGASzWDFnmu8iqD7SdV2DDSyLUGwbOvVoH_vYIq7DmNMfuMR3UJ9_7NR2LdukpkeJafRtZBlYt1zPqBZlThkAtNf7RF8lupKkZIqUUXfEHxWuEtpS40J-5dHmhbykUKycBqkGqQYacUK-RjN5fqMIvJWGfsxk0085y1sxFGlSzTVLJizLxfPSoM-_8LlQCl_QqduhqbfYIao9GjsA3-EVLtV645g_hw3j3Oe836XyGffCveQHeGtGKeLDQZ6kQGOVeIsmK40SmY0BJPRGEI7TbBFCAigKgpBvWpgLoZfRPPJGSzVqqxysGv4u2Y34LmtbBJkxNG9UsFTN_kVjvsyxZDwtJWNDUvk8CtJJcYj5ZMT4cz-x74dfOJoy7QN7YmHZH50-drBBHaPvY9M2jQHGlGLcN7FtM2x5huvbvtu3kD8YuH3HdAzXNhyC-7Zn-jYiVRsi5cjr1J5pY7uhJMeLzMMdqSnVpB2oRTzxtF_KOpArRjzhclmeArh5Cvhi7crij1irk_AEcHKnN-a1zEGYi09pSWmtX26LGhXyotz4L9eP08ptXkOIoapttCFfhQZs1LqMsqIvDdN4RuCNsbRws6JnQzEqA1AHFatGlQ48fvEvD3E13QeZcJa22NRUcvfiPOSJIck6F-ARwNqLCNz8BYE38M5jhADMMhCpSh6veGIGvwliswm2SvcCasBkCuUJS_jXwXmMam1buHzKqYuHFu1NqRTwrFBs8RN3dVzpJn1IJknnIk98lvCzmBeBpRJIzTJawrVgUMWXtRq1AXzazzxWlKEemOWYNgNO69uFnnnIiK3WhbTTeMI690ES-Lw8X2bUrC3MWq1TFVFqP35Kq202CYktunPaVxH2RbmyihG7FrEdBUaUdhdV1p3sVeudpBzpi5syxLfpbTW0AtNcyXHNLBuf5lWepo9ALVwXdGasdqsmrVWMmusyajQtEMHUIolBxRaqZCWvqMYrXl58WOzrrD1Yqaxv26vt4pAOhxzzVSz52XVF1BR2jsaTKYwTaVcJP4wxUkkYlTVGfVXCMH4hYVQXaCsmQkWwlws_tPjKh3LeJu2IuzWsH0LlAog7TQVubm9XfFRTPLV5jKe_mCdQW2aHFBfEnQO-aTNrCpc1OyzWWp_fXmyviJkrVg5b4kbT7CfgPZk84nOVJ1mknswUOUB6q09V3U3UDU2bKXshgEHuCotvwcxfQ7KLU0dLbSQOKb3DYCy32WdhtmiAKi3kPv3yeagzmqXXQDBR61J6RQLj5XnIhy6lNqhhrvI4_flk9WZ2aiti5ZFJm5BKb1yghtnJ1xIqrazlVrMP3M3amO2EtN4TnSxaWk3Mlr5iOp-_3UoS1UjiBunwNe0yE0Rvk0fpRThkthAqyXXFtEqEZiot3vxY8dZHOcSoWH2jjLk86rbQ9GbNM-bzTJc2J1OeElpNXxrVi3R6hpO5Ia03VnMEUaKsNiG8rhJ5mFDus1aQazBGZWmtFRrbQsGaomiLqiphVUkVaANVoPV9EDWcQqISwxutcIO4sKorUjPi5dShkjvWSB7q2WOd9KGUPxTc4lmfbTVxpBJ_G_KVSsJSzVh7RcoSr1yKp9n8t4M4GgRDmdKiST6jM56XfBLZXUUCDoPP5-M-S_iD6L2lTqPy5-ug-szFl4t6HF0tOhp6Q0_GiZ-l-3HKv-qQ8VWa91u90-710U1D68XkjqI0ogAHxBgH_LHIYiB9ZU_5baDmnqShJ0_xYvedkAP_jBnzt7R-HIcA7oqAuKKXeDw1--TobJx5VVLukvFtN_z9ruvYvxKrZ5NFD3PVGHynLPNnq0TPT64_-76A3MReEnz38nDVQHxhatUw7_ZmVvVu75pmo6vBfh6IRYd_dv4bxxADDA==

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/85992333-dea9f480-ba33-11ea-9c83-bad6d5c7113a.png)
This may be due to github formatting the string, which is why we generally ask for pastebins, also likely related to the fact you are no longer igniting when you swap quiver though as to why that cuases the issue I dont know, as
 https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/Modules/Build.lua#L268 clearly should work with ignite being 0

**Comment by dsnvwlmnt** [comment]
> ![image](https://user-images.githubusercontent.com/49933620/85992333-dea9f480-ba33-11ea-9c83-bad6d5c7113a.png)
> This may be due to github formatting the string, which is why we generally ask for pastebins

I updated the comment so the code is in a code block, that should work now, no github formatting. Quoting the reply also gets the proper code.

I can't replicate the issue if I import the current character (account: unsane, character: unsaneExperiment), even if I paste in the original quiver that may have started the issue (Gale Spike).

I updated all kinds of things in config and etc over time, so I don't know exactly what caused the issue. What I do know is that it occurred relatively early on, and I always just kept the Gale Spike equipped while updating my character over time, because I wanted to see my Combined DPS.

**Comment by Quotae** [comment]
Everything's technically working as intended here. Skills with a DoT component like Toxic Rain don't make the Combined DPS output show up, even with poison. However, the Combined DPS output is coded to show up whenever there's more than one secondary output(poison, ignite, bleed, impale). When you equip Gale Spike, it's adding fire damage to your attacks, adding ignite DPS and making the combined output show up.

Combined DPS is still calculated in the background so that you can still sort by it and see node power on the tree and such. It's just not shown to you. Maybe it should be? Not sure!

**Comment by dsnvwlmnt** [comment]
I'll have to defer to your knowledge that it's working as intended... I just know I always want to see my total combined dps, that's the only number I care about.

Oddly enough, when I just launched PoB fresh right now, and switched to my real quiver (Scorpion's Call), this time the Combined DPS stayed! Yay! I don't know what's different, but I guess based on your comment, perhaps since I last tried one of my slots changed and I have bleed or something somewhere now.

**Comment by Quotae** [comment]
Well, unless something's changed since the screenshots in your first comment, for your build there's not gonna be much difference between your Combined DPS and your DoT DPS. I know that having everything added into one number is simpler, but since 90% of your damage is from DoT DPS, there's not a big functional difference. That's why it's coded the way it is. For skills with a DoT component like Toxic Rain or Essence Drain or Vortex, you pretty much only ever focus on the DoT component; having the Combined DPS output would basically be redundant.

**Comment by dsnvwlmnt** [comment]
Fair enough, thanks for the help! There's a lot to this program, just like PoE. Never stop learning. :)

**Comment by masonk** [comment]
I strongly believe this shouldn't be considered WAI. For some builds, the difference between DoT and Combined DPS is enormous. Secondarily, it took me hours of digging to find out why it wasn't showing me the number I needed to see.

I am scaling poison damage, for instance, not DoT. The DoT component of my Toxic Rain is therefore negligible compared to my combined DPS number. Also, it took me a long time (hours) to figure out why Combined DPS wasn't showing up in my PoB but was in my friend's extremely similar POB. The difference came down to him having a few points of fire damage on his jewel, turning on ignites.

<img width="233" alt="DotWithoutPoison" src="https://user-images.githubusercontent.com/449998/89366948-bcd40b00-d68c-11ea-8c12-95ef82b340a1.png">
<img width="256" alt="DotVsPoison" src="https://user-images.githubusercontent.com/449998/89366951-bd6ca180-d68c-11ea-9379-eea66c82a41d.png">
