### ISSUE TITLE
"The Nomad" not increasing "projectile attack damage" with Abrasive catalyst

### ISSUE THREAD

**Issue by Pimmalage** [PathOfBuildingCommunity/PathOfBuilding#1110]
The Nomad unique belt when created within pob doesn't suggest Abrasive catalyst does anything when infact in-game it does scale the "Increased projectile damage while you have atleast 200 Dexterity"
Replicated every time and not just a visual bug
[Example of the Belt with 20% Abrasive in-game](https://i.imgur.com/EMPGpcW.png)
[Showing in POB the belt with 20% Abrasive quality](https://i.imgur.com/DOoxZjq.png) Which should be 60% Increased projectile attack damage.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
