### ISSUE TITLE
Mystic Bulwark mana regen per spell block chance does not work even though it's not red

### ISSUE THREAD

**Issue by Xeverous** [PathOfBuildingCommunity/PathOfBuilding#1114]
Basically, title. Make any build that allocates Mystic Bulwark. Taking Glancing blows with any spell block chance does not change the mana regen. My character in game has significantly higher regen than PoB shows.

**Comment by Xeverous** [comment]
![image](https://user-images.githubusercontent.com/20820409/85860234-bcf40780-b7be-11ea-989f-5aa0a850b004.png)

This is certainly wrong...

https://pastebin.com/9cT3BzFS

**Comment by dbrowdy** [comment]
I'm seeing this issue too. It doesn't work when I add nodes like Enigmatic Defense or Whirling Barrier or Glancing Blows.  I even tried just adding flat spell block to a custom item and it doesn't work.

**Comment by cakegod** [comment]
This bug is still present in the last version (1.4.170.14)
![image](https://user-images.githubusercontent.com/36206278/95366273-80629c80-08d3-11eb-881a-10035ee85912.png)

**Comment by randomflyingtaco** [comment]
Pull request was 4 days after 1.4.170.14, so it's not in the live version yet.
