### ISSUE TITLE
Consider showing minimum level for any Spell (helps when planning/levelling a build)

### ISSUE THREAD

**Issue by shrewdlogarithm** [PathOfBuildingCommunity/PathOfBuilding#1116]
PoBs are frequently the main source of 'build guide' info and it would be nice to quickly check what level is required for each gem

PoB currently shows the level required for the gem level (usually 20/21 in most PoBs) - it wouldn't be much work to add "Base Level Requirement of Gem XX" which would help people plan/know the source of most gems...

Expanding on this - offering a list of gems in the build in-order-of base gem level would be an AWESOME feature but that's a BIT more work perhaps?

Taking this to the nth degree, including information on where gems can be found/which quest/act they appear-in and what class restrictions they have would be amazing - but that's a LOT more work/maintenance I guess??

Thanks for maknig PoB - always keen to see it improve (PoE isn't PoE without PoB!)

**Comment by ppoelzl** [comment]
There are third-party resources available to accomplish all that.

**Comment by shrewdlogarithm** [comment]
> There are third-party resources available to accomplish all that.

With that mentality, you'll achieve very llttle in your life - anyone more ambitious here?

**Comment by ppoelzl** [comment]
Please note that Path of Building is no substition for game knowledge or competently written guides.

> Thanks for maknig PoB - always keen to see it improve (PoE isn't PoE without PoB!)

While PoB can be a worthwhile addition to your game experience, it certainly is not required to play the game, accomplish your goals and have fun.

Regarding your modifications:
All you do is display the level requirement of a level 1 gem. For that, you could simply change the level of the gem to 1.

> I think the 'Available from Level X" should be included in the gem popup - it's just too useful (as it usually hints at WHERE as well as when it's available)

There are a lot of questions left unanswered:
* Do I get this gem for my class?
* Do I get it as a quest reward or can I purchase it from a vendor?
* How much does it cost?
* Which quest do I have to complete to get this gem?
* In which act is it?
* Which NPC do I have to talk to?

To reiterate: there are tools readly available online that competently answer these questions for you. Build authors who wish to make leveling guides can use them as a suplementary tool, just like with PoB.

**Comment by Regisle** [comment]
Also as a side note, if you think your "hack" (its just normal coding but whatever) is good enough, you can submit a PR, the code is open source and this community accepts PR's from anyone as long as the code is good enough, thats part of the point of github

so if theres something you would like changed, change it yourself and submit a PR and it might be added

**Comment by shrewdlogarithm** [comment]
Most of the 'gem questions' are best answered by the Wiki - I don't think the LUA 'wrapper' supports embedding web content but opening it in the browser wouldn't hurt?

The starting level of a gem gives a lot of clues as-to-who sells the gem during levelling - there's only 1 seller per "base" +Siosa - builds which rely on 'offclass' gems usually say something about that (Notes or comments or similar)

Also - many build guides include a socketgroup for levelling (e.g. Freezing Pulse) which means sorting by socketgroup shows how to level through 

I'm going to keep playing with my hacked version because I find it useful and experience suggests other people might too - I'd like to make it 'self-contained' tho, installing PoB (esp the Community version) is a big enough hurdle as-is...
