### ISSUE TITLE
[Linux] when loading a build it crashes 

### ISSUE THREAD

**Issue by Sasalu123** [PathOfBuildingCommunity/PathOfBuilding#1119]
* **What happened?**
PoB crashed when i selected to load a build
* **What were you trying to do?**
load a saved build
* **What steps will reproduce the bug?**
1. save a build (was not a specific build)
2. quit PoB and restart it (did not test if one needed it)
3. load the build
4. crash
* **Does it reproduce every time? If not, why so?**
it does with all 3 steps
* **Additional information:**
Linux version, Manjaro from the AUR: https://aur.archlinux.org/packages/path-of-building-community-git
Crashes in Both PoB (normal and community)

**Comment by ppoelzl** [comment]
Please note that we cannot offer support for packages or distributions that come from third parties that incorporate this software. We are not affiliated with the AUR package you linked and strongly recommend to obtain this software from our releases page only.

Try using one of our [releases](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases) and if this bug persists, feel free to open a new issue.
