### ISSUE TITLE
Unnerve should not increase dot damage.

### ISSUE THREAD

**Issue by Zarania** [PathOfBuildingCommunity/PathOfBuilding#1121]
Checking unnerve increases damage over time on vortex and other dots.  According to Mark at GGG this should not be the case.

https://www.pathofexile.com/forum/view-thread/2784387#p22947950

**Comment by LocalIdentity** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/843
