### ISSUE TITLE
Warcries Damage

### ISSUE THREAD

**Issue by igorcastroo** [PathOfBuildingCommunity/PathOfBuilding#1124]
Pob is not exhibiting increased damage at exerted attack points, nor is anything happening with the active screams in the main skill

or am i forgetting to do something on the pob?

**Comment by CollinHerber** [comment]
@igorcastroo Could you provide a pastebin for your POB and let us know exactly what you are expecting to happen with certain calculations? 

Thanks!

**Comment by igorcastroo** [comment]
My Pastebin:
https://pastebin.com/LGvPQpUS

points like exerted attack damage does nothing, or intimidating cry that does double damage does not increase the damage of the main skill

sorry for my bad English

**Comment by CollinHerber** [comment]
No problem. Thank you for providing that. I'll look into it

**Comment by Regisle** [comment]
do note this may be related to potential fix #1086

**Comment by Nostrademous** [comment]
Correct, Exerted Attack support (and buffs from many of the new warcries) are not supported in currently released version. They are currently in development on dev branch and slated for support in an upcoming release once the proposed implementation is validated and approved in PR: #1164

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
