### ISSUE TITLE
Crash on empty Default gem level or quality

### ISSUE THREAD

**Issue by Vwert** [PathOfBuildingCommunity/PathOfBuilding#1130]
Version 1.4.170.2

* **What happened?**
The program crashed when I deleted the numbers in the Default gem level and Default gem quality boxes

The Default gem level and Default gem quality were set to 20 in my build but when I delete the numbers in the boxes the program crashes and I get these error messages

* **What were you trying to do?**
I was trying to delete the numbers in the Default gem level and Default gem quality boxes

* **What steps will reproduce the bug?**
If a number is entered into the Default gem level and Default gem quality boxes and is then deleted the program will crash, it doesn't seem to matter what numbers are entered to cause the crash.
The crash occured in both a preexisting build and a new empty build.

Error messages and Build pastebin included below

Before crash
![Before crash](https://user-images.githubusercontent.com/43323401/86235859-02cf1800-bb91-11ea-8dcf-ef560f820ae6.png)

Default gem level
![Gem level crash](https://user-images.githubusercontent.com/43323401/86235827-f64abf80-bb90-11ea-8a5c-9d62517a2c81.png)

Default gem quality
![Gem quality crash](https://user-images.githubusercontent.com/43323401/86235844-fc40a080-bb90-11ea-9641-26765ef64946.png)

Build pastebin
https://pastebin.com/Xt52vjzP

**Comment by CollinHerber** [comment]
@Vwert Looks like there is an open PR to address your issue. https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1131

Thank you for your report.
