### ISSUE TITLE
[Linux]lcurl.dll missing module

### ISSUE THREAD

**Issue by AndyHoang** [PathOfBuildingCommunity/PathOfBuilding#1133]
Please try to fill in as much of the template below as you're able.

* **What happened?**
After a few recent update, it cant be used anymore because of error
* **What were you trying to do?** 
Start the app on version `PathOfBuildingCommunity-Setup-1.4.170.2` and standalone (zip) version

* **What steps will reproduce the bug?**
open the app using wine on lutris

* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**

```
Please wait while we complete installation...

Saving Z:\home\andyhoang\Games\path-of-building\Launch.cfg
Engine shutdown complete.

--- SCRIPT ERROR ---
Runtime error in 'Z:\home\andyhoang\Games\path-of-building\Launch.lua':
error loading module 'lcurl.safe' from file '.\lcurl.dll':
	Module not found.

stack traceback:
	[C]: at 0x10049df0
	[C]: in function 'require'
	UpdateCheck.lua:11: in main chunk
	[C]: in function 'LoadModule'
	Z:\home\andyhoang\Games\path-of-building\Launch.lua:30: in function <Z:\home\andyhoang\Games\path-of-building\Launch.lua:15>
```

**Comment by ppoelzl** [comment]
This isn't a bug with Path of Building, you are missing dependencies: https://forum.manjaro.org/t/cannot-start-path-of-building/90321/16
