### ISSUE TITLE
Awakened Void Manipulation not correctly scaling with level

### ISSUE THREAD

**Issue by dcgaines** [PathOfBuildingCommunity/PathOfBuilding#1134]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Awakened Void Manip has the same stats at levels 2-5 as at level 1

* **What were you trying to do?**
See the effect of leveling my gem

* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
Version 1.4.170.2
https://pastebin.com/3vcYASca

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by dcgaines** [comment]
Steps taken to reproduce the bug:
This bug is not with this gem in particular. This will occur with all the gems in a currently selected link-set when a build is re-imported. For example, I select my Essence Drain setup, import items/gems, it will occur with ED and all its links. I select my Contagion setup, import items/gems, it occurs with Contagion and all its links, but ED works fine.

**Comment by ppoelzl** [comment]
Cannot reproduce this bug in version 1.4.170.16.
