### ISSUE TITLE
Text not removed after item edit

### ISSUE THREAD

**Issue by aiolos01** [PathOfBuildingCommunity/PathOfBuilding#1137]
Sometimes when I edit an item some text (specifically craft removal) stays and is mixed with the import item instructions that are displayed when no item is in edit mode. Using the latest version, win7 x64.
[url=https://postimg.cc/rDJB8nqh][img]https://i.postimg.cc/rDJB8nqh/Snap214.png[/img][/url]

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
