### ISSUE TITLE
Rolling Flames Jewel - threshold effect not working

### ISSUE THREAD

**Issue by ad3z10** [PathOfBuildingCommunity/PathOfBuilding#1138]
* **What happened?**
In 3.11 Rolling Flames was updated to:
_(10-15)% increased Fire Damage_
_With at least 40 Intelligence in Radius, Fireball cannot ignite_
_With at least 40 Intelligence in Radius, Fireball has +(30-50)% chance to inflict scorch_
Currently, only the first line is correctly working as Ignite damage is still being calculated and no option for Scorch is available.

* **What were you trying to do?**
Calculate the change in damage from Scorch

* **What steps will reproduce the bug?**
Socket Rolling Flames with at least 40 Int within its radius

* **Additional information:**
The Jewel should operate identically to the "Secrets of Suffering" Keystone, just limited to Fireball, which was implemented in 1.4.167.1 and was given the ability so select Scorch from the configuration screen in 1.4.170.1.

**Comment by LocalIdentity** [comment]
The first part of the jewel is now working

**Comment by ppoelzl** [comment]
Added in 1.4.170.19.
