### ISSUE TITLE
Installer not working correctly

### ISSUE THREAD

**Issue by MorbiusProductions** [PathOfBuildingCommunity/PathOfBuilding#1139]
I ran the latest installer, the exe version, and it installs and runs the community edition but when I shut it down and reload PoB Community by double clicking the exe in the folder where I installed it it runs regular PoB.

**Comment by Wires77** [comment]
You'll want to find your manifest.xml file and change the github path to this repository.  I'm guessing if you didn't fully uninstall the old PoB, the manifest file didn't change

**Comment by ppoelzl** [comment]
@Wires77 This is not how this works anymore. For the record, please use a release from https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases instead of editing the manifest.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.4.
