### ISSUE TITLE
is chaos converting damage calculation working properly? minions specific in this case (skeleton atrophy/triad grip)

### ISSUE THREAD

**Issue by xerance** [PathOfBuildingCommunity/PathOfBuilding#1147]
![image](https://user-images.githubusercontent.com/16266200/86526915-14b70080-be9a-11ea-9d26-dde9cf9b2162.png)

https://pastebin.com/PNh7t6jx
am i completely mad or does this make zero sense? i'm already at 100% converted damage(settings are set to 15 withered stacks) and of some reason this nodes imply that going over the converted cap would increase my damage by a lot.

**Comment by LocalIdentity** [comment]
The line that is not working properly is the Wither one, it's applying another 15 stacks of Wither when you allocate the node. We need to get around to reworking how Wither is coded in PoB cause there's a bunch of other cases where it doesn't work properly too

**Comment by xerance** [comment]
so i should remove wither in the settings to get proper values?

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.4
