### ISSUE TITLE
Jewel Tooltips Too Tall

### ISSUE THREAD

**Issue by livejamie** [PathOfBuildingCommunity/PathOfBuilding#115]
Builds with multiple jewels will get tooltips that are too tall/unreadable. It makes it impossible to see what the impact of a jewel in certain slots will be.

It would be nice to have some sort of solution for this, maybe a scrollbar or a mouse wheel scroll?

![image](https://user-images.githubusercontent.com/49513/71918090-658dac80-3136-11ea-88d3-6da4a92c4acc.png)

**Comment by Wires77** [comment]
Fixed by #325

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
