### ISSUE TITLE
Rage Support is Not Supported in PoB When Applied to Lacerate

### ISSUE THREAD

**Issue by NocturneAequitas** [PathOfBuildingCommunity/PathOfBuilding#1151]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
When importing a build with a skill gem that is supported by Rage Support, there is no visualization to the change of calculations when increasing the value of the "Rage" configuration. 
* **What were you trying to do?**
Gauge the difference in DPS output between Impale and Rage using the passives and notables on the skill tree.  
* **What steps will reproduce the bug?**
Imported character
Configured Character and Items to maximize min/max DPS values
Selected Skills Tab
Selected Lacerate
Selected Rage Support in an open field from the list
Enabled Rage Support
Returned to Configuration Screen 
Changed the value in the configuration "Rage" from different values between 0 and 60 (notable on tree enabled)
DPS output did not increase
* **Does it reproduce every time? If not, why so?**
It reproduces each time.  
* **Additional information:**
I have tried this with a couple different builds and even building from scratch and the same issue occurs.  
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Wires77** [comment]
Can you add a link to your build?  I have a similar build in PoB and it increases the DPS appropriately

**Comment by LocalIdentity** [comment]
This is a bug with the current live version of PoB, and is fixed for the next update. For the moment add this to one of your pieces of gear "Gain 1 rage on hit with attacks, no more than once every 0.3 seconds" to fix it

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
