### ISSUE TITLE
Error on editing Jewel-modifier (null-value in list)

### ISSUE THREAD

**Issue by Bregylais** [PathOfBuildingCommunity/PathOfBuilding#1153]
Impact: Minor
Version: 1.4.170.2

**Problem:**

An error appears after hovering the mouse on the an empty dropdown while editing the jewel-modifier. Consistently reproducable.

**Steps to reproduce:**

1. (Create new build)
2. Create new crimson jewel
3. Click 'Add modifier ...'-button
4. Select Source: Crafting Bench
5. Open dropdown by clicking Modifier-list
6. Hover mouse over empty dropdown-option for ~1 second

**Additional information:**
Error can be dismissed by pressing ESC; issue is non-critical.

**Screenshots:**
![x1](https://user-images.githubusercontent.com/67902963/86586455-31316680-bf88-11ea-91cf-788f6ad1bb63.PNG)

![x2](https://user-images.githubusercontent.com/67902963/86586528-4ad2ae00-bf88-11ea-85c7-7d7998c9178a.PNG)

**Comment by ppoelzl** [comment]
Cannot reproduce anymore on 1.4.170.20.
