### ISSUE TITLE
Serpentine Spellslinger cluster sometimes not adding % chance to poison on hit

### ISSUE THREAD

**Issue by traviskm** [PathOfBuildingCommunity/PathOfBuilding#1155]
I noticed this when I was making a build for a Blade Vortex Assassin and in game I had a 110% chance to poison but in PoB I had a 85% chance. The Serpentine Spellslinger cluster, right below CI, is sometimes not adding chance to poison on hit for spells. Very easy to reproduce, just equip a spell and allocate that cluster. Through my own testing there are some spells, I've found, that never seem to work (like Arc and Fireball). But some (strangely enough blade vortex is one of them) always work when just making a brand new build then going straight to that cluster. Bit of a head scratcher.

Here's my build link for reference:
https://pastebin.com/tW4h9fta

**Comment by traviskm** [comment]
Ah sorry here's the updated build link, I had edited a piece of my gear and put extra % chance to poison on it to compensate. Here's the tree without that: https://pastebin.com/h9uD2nmr

**Comment by Wires77** [comment]
Only physical or chaos damage can poison, so even if you got 100% chance to poison, Fireball nor Arc would ever poison without any added physical or chaos damage.

**Comment by traviskm** [comment]
Oh woops of course, though it still doesn't answer why it wasn't adding the % chance to poison in my build. I'll look more into the specifics of what I'm doing and try to find out what's causing that chance to not be added to Blade Vortex.

**Comment by Wires77** [comment]
Yeah, if you can link your character and a screenshot of your in-game chance to poison, I can take another look.  Hard to tell from just PoB though

**Comment by traviskm** [comment]
The character's name is "Whirly_Bonks" [My Profile](https://www.pathofexile.com/account/view-profile/The_Ordinary/characters)
I'm at work right now and can't get an in game screenshot, but I'll come back later with it.

**Comment by traviskm** [comment]
Ugh please disregard everything I said, I'm an idiot. I was going over my problem again and noticed that in the "Calcs" section I had Cyclone selected in my CwC Cyclone/Blade Vortex setup. Cyclone isn't a spell so of course it wouldn't add the poison chance. I'm stupid, case closed.
