### ISSUE TITLE
Cluster Notable not found Error opening POB in Community Fork that opens OK in std version. 

### ISSUE THREAD

**Issue by cjhowell** [PathOfBuildingCommunity/PathOfBuilding#1156]
* **What happened?**
Opening POB from Youtube build results in error
![Jorgen POB error](https://user-images.githubusercontent.com/659377/86605722-666ea080-bfea-11ea-9bbb-762cd995a5c3.png)

* **What were you trying to do?**
Trying to open this POB: https://pastebin.com/ixUFD9qx from https://www.youtube.com/watch?v=YEKbY_BZ4tg

The link validates OK but then errors on import.

* **What steps will reproduce the bug?**
Use POB link above to open in latest community build.

The file opens OK in standard version of POB

* **Does it reproduce every time? If not, why so?**
Yes, every time and if you refer to comments on Youtube video others are having issue too.

**Comment by LocalIdentity** [comment]
Same issue as #1261

**Comment by Nostrademous** [comment]
Closed.
