### ISSUE TITLE
thread of hope large circle

### ISSUE THREAD

**Issue by Roellie81** [PathOfBuildingCommunity/PathOfBuilding#1161]
Thread of hope large circle can only appoint skills in a very small circle (putting stone next to instability)

**Comment by Wires77** [comment]
I just checked and this works fine.  Did you make sure to edit Thread of Hope by double-clicking on it and change the size of the ring?

![image](https://user-images.githubusercontent.com/1209372/86816804-e415c900-c049-11ea-822c-83348b653922.png)

**Comment by Roellie81** [comment]
I imported my character and there it failed. The text on the item shows large, only didn't check if the actual mod of the item is also set large (will check later tonight).

________________________________

**Comment by Roellie81** [comment]
nm guess I got 2 pob installed and was playing with the non-fork version. This one works, sorry.
