### ISSUE TITLE
Shaman's Dominion passive applies crit only to totems, not globally

### ISSUE THREAD

**Issue by mijell** [PathOfBuildingCommunity/PathOfBuilding#1165]
* **What happened?** Shaman's Dominion did not apply to the Global crit chance (it seems to apply only to totems)
* **What were you trying to do?** Was experimenting with a build which included a small amount of totem synergies - selecting Shaman's Dominion does not seem to increase crit chance with spells / attacks, only with totems
* **What steps will reproduce the bug?** 
1. Open a build which includes both totem skills and spells or attacks, and select passives up to "Shaman's Dominion"
2. Check crit chance with a totem before and after selecting the passive (increased as intended)
3. Check crit chance with a spell/attack before and after selecting the passive (notice no change - _presumably unintended?_)
* **Does it reproduce every time? If not, why so?** Yes
* **Additional information:** Running 1.4.170.2 - based on the tooltip for Shaman Dominion, I assume the "Global" text implies crit chance for anything, but it's possible that it's intended for only totem crit chance to be buffed. If so sorry I'll delete.

**Build:** https://pastebin.com/M6kLqgGY

**Comment by mijell** [comment]
After looking through the recent change to totems, maybe this issue is a side-effect of the "recently placed a totem" configuration option not being settable through the Configuration tab? The calc shows the 100% increased crit chance, but it doesn't seem to be taking effect - I would guess because the Recently Placed a Totem flag isn't getting enabled, but I don't see anywhere to do that currently. 

If you're using a totem skill though, it seems to set the Recently Placed Totem flag. I don't see an option to control it manually though.

PR #881 includes the recent changes I was thinking might be relevant, but I'm not confident enough in my understanding of the project to say for sure

**Comment by LocalIdentity** [comment]
Had a look and the condition was only flagged as true when you had a totem skill selected as the main skill. I'll add a checkbox for it to appear on the calcs page so you can see the effect it has on other non-totem skills

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
