### ISSUE TITLE
Bannerman notable does not count 30% attack damage with placed banner

### ISSUE THREAD

**Issue by randomnf** [PathOfBuildingCommunity/PathOfBuilding#1166]
PoB v 1.4.170.2

When i check `Is Banner Planted?` checkbox in `Configuration` tab total dps does not change. I mean it is changing but only with bonus from banner stages, this option does not count additional `30% increase attack damage` from respective notable.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
