### ISSUE TITLE
Vile Reinvigoration cluster jewel notable not fully working

### ISSUE THREAD

**Issue by david-carson** [PathOfBuildingCommunity/PathOfBuilding#1180]
In version 1.4.170.2 the "Regenerate 2% of Energy Shield per second if you've Killed an Enemy Recently" element of the Vile Reinvigoration cluster jewel notable is not working.

It looks like a problem with unicode apostrophe characters in `TreeData/3_11/tree.lua`.

The pull request https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/746 fixed this issue in the 3.10 tree, probably needs the same fix applied to the 3.11 tree.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
