### ISSUE TITLE
Thread of Hope jewel broken again

### ISSUE THREAD

**Issue by vocabbusters** [PathOfBuildingCommunity/PathOfBuilding#1184]
Thread of Hope only seems to work sporadically. 
Difficult to replicate - it seems as though it will work if you completely restart the PoB and re-import everything fresh, but if you re-import the same build or move between builds it will not work.

**Comment by ImaginaryDevelopment** [comment]
Another issue in the same vein, sometimes you click a node in a working Thread of hope, and have to remove the connecting passives because it added them too. Also I think moving between trees has some issues.

**Comment by zmike** [comment]
Doesn't seem to be working at all in the latest release. Can't allocate any nodes without allocating all connecting nodes.

**Comment by Wires77** [comment]
> 
> 
> Doesn't seem to be working at all in the latest release. Can't allocate any nodes without allocating all connecting nodes.

Please provide a pastebin link to your build.  It's working fine for me.

**Comment by zmike** [comment]
Just the simplest test seems to fail: https://pastebin.com/qVRdv4fX

It doesn't seem that there's any way to add nodes within the radius without also adding the connecting nodes.

**Comment by Wires77** [comment]
Unfortunately that pastebin got removed.  https://pastebin.com/5Jp2Z9Qj is one I made with several passives in the ring allocated without allocating all the connecting nodes.

**Comment by zmike** [comment]
Mine was starting at Duelist, allocating the socket directly south of that, and then trying to use Thread of Hope to allocate nodes within that area. I was unable to allocate anything without having it connect the nodes, and attempting to deallocate the connector nodes deallocated all of the nodes instead of just the one.
