### ISSUE TITLE
Error: attempt to index a null value

### ISSUE THREAD

**Issue by dagutten** [PathOfBuildingCommunity/PathOfBuilding#1194]
* **What happened?**

Getting below error when uploading the character which I imported from my profile

![image](https://user-images.githubusercontent.com/31007906/87297871-71a15f00-c509-11ea-9ab5-935f7ad0a7f2.png)

* **What were you trying to do?**

Open my character POB

* **What steps will reproduce the bug?**
1. Import my character from my account.  Account: dagutten, Character: SPINN_TO_FAIL
2. Save the character
3. Go back to character selection and try to open it again. At this moment, the error occurs

* **Does it reproduce every time? If not, why so?**
Yes, every time

**Comment by PJacek** [comment]
This is caused by bugged items without a name.

You can delete your Vaal Axe before saving to fix the build.

**Comment by Nostrademous** [comment]
Closed.
