### ISSUE TITLE
Vaal Molten Shell not applying the more armour modifier.

### ISSUE THREAD

**Issue by dp101428** [PathOfBuildingCommunity/PathOfBuilding#1197]
* **What happened?**
The more modifier from Vaal Molten Shell didn't show up in the armour calculations portion of the calcs window, and it also isn't applying to the armour, only the flat value is
* **What were you trying to do?**
Check what my actual physical damage reduction values are
* **What steps will reproduce the bug?**
1. Add the Vaal Molten Shell skill gem
2. Make sure Vaal Molten Shell is enabled
3. Look at the calculations window
* **Does it reproduce every time? If not, why so?**
Yes, as far as I can tell

Link to build where problem is observed: [https://pastebin.com/jgCwiqiF](url)

**Comment by Regisle** [comment]
Fixed in next version

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
