### ISSUE TITLE
Cluster Jewels not showed properly

### ISSUE THREAD

**Issue by jcyxxx** [PathOfBuildingCommunity/PathOfBuilding#1203]
* **What happened?**
![image](https://user-images.githubusercontent.com/10475153/87377441-999eca00-c5be-11ea-8d36-96471a17771c.png)

* **What were you trying to do?**
Open a saved build.

* **What steps will reproduce the bug?**
Can you try to import this? → https://pastebin.com/Dd9rVfbr 

* **Does it reproduce every time? If not, why so?**
Yes. I guess.

**Comment by LocalIdentity** [comment]
GGG is 3.11 changed the enchant on the medium jewels from `+5% to Chaos Damage over Time Multiplier` to `+4% to Chaos Damage over Time Multiplier`. You will need to change the cluster jewels manually then they will show up properly on the tree
