### ISSUE TITLE
Summon Spectral Wolf isn't updated to the 3.11 version (and Law of the Wilds isn't added)

### ISSUE THREAD

**Issue by L7mon** [PathOfBuildingCommunity/PathOfBuilding#1205]
What the title says.

**Comment by LocalIdentity** [comment]
Just made a PR for it, will be in the update coming out later today

**Comment by ppoelzl** [comment]
Summon Spectral Wolf is still missing "Modifiers to Claw Critical Strike Chance also apply to Minions" and "Modifiers to Claw Critical Strike Multiplier also apply to Minions".

**Comment by ppoelzl** [comment]
Closing in favour of #1312
