### ISSUE TITLE
Rallying Cry issues

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1216]
Rallying Cry relies on the "# of Nearby Allies" configuration option to calculate the Rallying Cry effect modifier, but adding Rallying Cry to a build does not actually make that option visible meaning Rallying Cry essentially does nothing without taking Guardian's Radiant Crusade or manually adding a similar effect to an item. It also has no upper limit when it should cap at 5 allies / 25% more.

Version: 1.4.170.4

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.5
