### ISSUE TITLE
Melee Ailment Issues

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1217]
The current way melee ailments are handled leaves a lot to be desired.

Ruthless is calculated as an average value with no option to see the actual (maximum) multiplier, which realistically is the only number that will matter for Bleed on single target as their duration will typically be longer than 5 seconds.

The way Seismic Cry is calculated for Ailments is inconsistent with Fist of War, with 99% less Attack Speed Seismic Cry acts as a 1.75x multiplier for Bleed while Fist of War is a 2.00x multiplier: ![](http://puu.sh/G7txq/fe2b207f21.png)

Unless I'm missing something here Seismic Cry should be a 2.50x multiplier for Bleed and Ignite given 0.01 attack speed, and again seeing the maximum (not average) value should be a configuration option (for everything -- Seismic Cry, Ruthless, Fist of War, etc) as the average value is largely irrelevant unless you're using Crimson Dance or have extremely-short duration Ignites.

Finally the Calcs tab damage breakdown for Ignite is missing some details as stuff like Seismic Cry is calculated behind the scenes but not actually visible anywhere. Compare (Bleed: http://puu.sh/G7tFh/91d14c389a.png vs Ignite: http://puu.sh/G7tHb/d6ce69ce65.png)

PoB used for testing: https://pastebin.com/rYyr5Gs4

Version: 1.4.170.4

**Comment by Lothrik** [comment]
Seismic Cry also has a very confusing implementation for it's increased Area of Effect that both seems wrong, and doesn't actually do anything:
![](http://puu.sh/G7tL3/404504ca8a.png) -- It says "75% more AoE" but doesn't actually modify the Area of Effect, and it should be 150% increased not 75% more.

**Comment by Lothrik** [comment]
Also, the more Damage multiplier on Seismic Cry is implemented incorrectly.

"seismic cry provides 30% more damage and 60% more damage to the third attack, which is not the same as 90% more" - [Mark_GGG](https://www.reddit.com/r/pathofexile/comments/hb56kp/path_of_exile_harvest_gem_information/fv7d54d/?context=3)

Slam 1: 30% more Damage, 30% increased AOE

Slam 2: 30% more Damage, 30% more Damage, 60% increased AOE, 69% more Damage total

Slam 3: 30% more Damage, 60% more Damage, 90% increased AOE, 108% more Damage total

Slam 4: 30% more Damage, 90% more Damage, 120% increased AOE, 147% more Damage total

Slam 5: 30% more Damage, 120% more Damage, 150% increased AOE, 186% more Damage total

<.. and so on>

**Comment by Nostrademous** [comment]
Fixing this stuff right now...

**Comment by Lothrik** [comment]
Seismic Cry still appears incorrect in 1.4.170.6, as it's still adding the more Damage multipliers together when they're separate according to Mark_GGG.

![](http://puu.sh/G9Hn1/3991b62c38.png) <- This should be 186% more Damage (1.3 * 2.2) not 150% (1 + 0.3 + 1.2).

Rallying Cry also doesn't support the Added Attack Damage per 5 Power, this is with 5 nearby allies and 20 power: ![](http://puu.sh/G9HnO/f18286e074.png)

**Comment by LocalIdentity** [comment]
Rallying Cry does not provide a buff to the player that uses it, only nearby allies. I'll look into the other 2 issues

**Comment by Lothrik** [comment]
Ruthless is still calculated as an average value instead of the max hit value under "Max Hit" mode: ![](http://puu.sh/G9Xyq/f71a38088d.png) -- I'm not entirely sure how practical it is to line up Seismic Cry with Ruthless, but it seems worth mentioning.

There's also a random extraneous space in the Warcry Calculation Mode tooltip: ![](http://puu.sh/G9XCj/230c36ca65.png)

Everything else appears to be working correctly as of 1.4.170.7.
