### ISSUE TITLE
Add limiter to # of Warcries used recently

### ISSUE THREAD

**Issue by mataski** [PathOfBuildingCommunity/PathOfBuilding#1221]
Scales to infinite

![image](https://user-images.githubusercontent.com/62036912/87608211-f35edb80-c707-11ea-8f82-fd5dc9036ec4.png)

There's about ~7 warcries in the game, should be limit?

**Comment by mataski** [comment]
![image](https://user-images.githubusercontent.com/62036912/87612428-34a8b880-c713-11ea-8b8c-a6f9ee63d457.png)

Are you stationary? is not a checkbox.

**Comment by mataski** [comment]
![image](https://user-images.githubusercontent.com/62036912/87612508-6faaec00-c713-11ea-8139-515aa729e233.png)

Perforate AOE mod wrong values? Over 8000%?

**Comment by Nostrademous** [comment]
Regarding Warcry Limit - I will cap it at 14 as there are 7 warcries and you could Second Wind support them all (across multiple pieces of gear).

**Comment by Wires77** [comment]
> 
> 
> Regarding Warcry Limit - I will cap it at 14 as there are 7 warcries and you could Second Wind support them all (across multiple pieces of gear).

Technically you can get the cooldown low enough to cast each warcry every 3 seconds or less, but then we're getting into some absurd territory...

**Comment by Nostrademous** [comment]
I will cap it at 100 for now

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.6
