### ISSUE TITLE
Pride not active when build is loaded

### ISSUE THREAD

**Issue by aiolos01** [PathOfBuildingCommunity/PathOfBuilding#1223]
Just updated to 1.4.170.5. I loaded a build that uses Pride and noticed the DPS is a lot lower than expected. In the configuration tab "Initial Effect" is by default selected for Pride but in the Calcs tab Pride does not appear in the debuffs as it should.
If I change the setting to "Maximum effect" and then back to "Initial" Pride starts working as expected, appears in the debuffs and the correct DPS is calculated.
If I save the build after that and then load it again Pride works as expected.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.6
