### ISSUE TITLE
Warcries incorrectly display "Has infinite Power"

### ISSUE THREAD

**Issue by scottord** [PathOfBuildingCommunity/PathOfBuilding#1232]
Noticed that all Warcries display this text, despite it only being granted by a single item at the time ([Redblade Banner](https://pathofexile.gamepedia.com/Redblade_Banner)).

Steps:
- Create a new build
- Create a new socket group
- Add any Warcry (all Warcries show this text as of 1.4.170.5)
- Observe the blue text when you hover over a Warcry in the skills list for that socket group

Expected:
- Warcries display their "per-power" effects

Actual:
- "Has infinite Power" is displayed for the "per-power" effect

**Comment by PJacek** [comment]
Fixed in 1.4.170.12
