### ISSUE TITLE
Infernal Cry increased fire damage taken is uncapped, should be capped at 20%

### ISSUE THREAD

**Issue by dp101428** [PathOfBuildingCommunity/PathOfBuilding#1234]
* **What happened?**
Infernal Cry was adding more than 20% increased fire damage to enemies when the skill tooltip says that that effect is capped at 20%
* **What were you trying to do?**
Test current DPS using Infernal Cry
* **What steps will reproduce the bug?**
Get a character that does fire damage, socket infernal cry, set warcry power to a high number (I used 20), then hover over the effective DPS modifier under fire in the calculations screen

PoB example: [https://pastebin.com/duGL6hwB](https://pastebin.com/duGL6hwB)

Note that this can be worked around if you manually set enemies to be covered in ash, as that will lock the increased damage to 20%

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.6
