### ISSUE TITLE
Seems like DoT it's not being calculated

### ISSUE THREAD

**Issue by RobertBrasil** [PathOfBuildingCommunity/PathOfBuilding#1239]
It seems like this new version of PoB it's not calculating everything in the build to generate the DoT and the combined DoT values, i have this problem with 2 build

![image](https://user-images.githubusercontent.com/68493651/87869073-eeea2b00-c972-11ea-8348-34df577404d4.png)

in this image it show only 175k of combined DoT, while in his stream on twitch he said he deals almost 11M of DoT in the total.

**Comment by Lothrik** [comment]
That just means the build isn't configured properly in PoB.

Calculating DPS accurately is a bit more involved than just importing a character and having it all magically work.

You need to go through every buff and item verifying that everything is enabled and working as appropriate. Wither for example is not going to enable itself on a freshly imported character.
