### ISSUE TITLE
Item quality always 20%

### ISSUE THREAD

**Issue by Jeferson-Emanuel** [PathOfBuildingCommunity/PathOfBuilding#1241]
Latest build of PoB is pasting all armor and weapons with 20% quality when copied from game. Bug was present before version 1.4.170.3, was fixed in that version and now is back in version 1.4.170.5. Creating an item with the info or pasting it directly in the Shared Items space has the same result.
![PoB20%](https://user-images.githubusercontent.com/40230023/87894209-750c7d00-ca18-11ea-86f2-6c18cfb8b757.jpg)

**Comment by LocalIdentity** [comment]
This is not a bug, but a feature of PoB and has been in for a couple of years now. 99% of the time people only care about the pDPS of a weapon or piece of gear if it has the minimum 20% quality on it

**Comment by Jeferson-Emanuel** [comment]
Understandable, but some people like to see what the actual gear will improve when leveling up in campaign. Maybe put a switch that allow to disable and enable this behavior, and allow the user to choose what to use? Thanks.
