### ISSUE TITLE
error installing fork via pamac on Manjaro Linux

### ISSUE THREAD

**Issue by yarikhh** [PathOfBuildingCommunity/PathOfBuilding#1242]
patching file lzip.cpp
patching file Launch.lua
Hunk #1 succeeded at 52 with fuzz 2 (offset 1 line).
Hunk #2 succeeded at 294 (offset 8 lines).
Hunk #3 succeeded at 312 (offset 8 lines).
patching file Modules/Main.lua
Hunk #1 FAILED at 42.
Hunk #2 succeeded at 931 (offset 14 lines).
1 out of 2 hunks FAILED -- saving rejects to file Modules/Main.lua.rej
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by LocalIdentity** [comment]
We do not currently support installing PoB on platforms other than Windows
