### ISSUE TITLE
Add simulated statweights

### ISSUE THREAD

**Issue by AndersKromann** [PathOfBuildingCommunity/PathOfBuilding#125]
It could be pretty cool if we attempted to simulate the DPS changes based on getting 1% extra of various stats, to make it easier to find jewels for example.

E.g.
1% Increased Spell Damage will increase your dps by 0.3%
1% Increased Global Critical Strike Multiplier will increase your dps by 0.8%

Eventually maybe could add a way to copy paste them easily into a 'weighted sum' filter or similar on trade sites.

Obviously the numbers would only be based on the current snapshot of the character and so would mostly work for filling unused jewel slots or crafting extra mods on open craft slots.

**Comment by LocalIdentity** [comment]
There's already a community made tool that does what you're looking for here: https://github.com/VolatilePulse/PoB-Item-Tester. Would be good to implement something like that into PoB in the future

**Comment by coldino** [comment]
I am one of the authors of that tool, which heavily relies on the work of @xanthics in [xanthics/PoE_Weighted_Search](https://github.com/xanthics/PoE_Weighted_Search).

PoB Item Tester is really at the limits of what we're willing/able to implement in Lua - hence the approach to extract the resulting data from PoB into Python.

There are some issues with the approach to consider - namely that *combinations* of stats cannot be accounted for using this method. But it would still be useful to see in PoB which mods are your build's most valuable.

Xanthics has worked hard on mapping these simple tested mod results to the many in-game mods - and this enables weighted searches on the official trade site that give an estimate of the DPS impact of each item.

**Comment by Nostrademous** [comment]
This is done by #3885 when merged.

**Comment by Nostrademous** [comment]
merged into `dev` already. Be part of next release.
