### ISSUE TITLE
Please Add Baranite Preacher to Specter List

### ISSUE THREAD

**Issue by mcmatt05** [PathOfBuildingCommunity/PathOfBuilding#1250]
Would be awesome if you could add this spectre to the list! 

https://poedb.tw/us/mon.php?n=Baranite+Preacher

Side note, is there anyway to make the list of spectres configurable so we can add to the list?

Thanks!

**Comment by Regisle** [comment]
Will be considered
to address your side note, heres a mini guide to add them yourself https://www.reddit.com/r/pathofexile/comments/hoip63/guide_to_manually_adding_spectres_to_pob/ which is made much easier thanks to chuanhsing (from PoEDB) adding an export lua button 
![image](https://user-images.githubusercontent.com/49933620/88074843-1d584800-cbb7-11ea-9cfb-7373baf2e0dd.png)
and to add a sidenote of my own, if you get any specters working and can PR it so we can easily have them added officially that would be amazing

**Comment by davoodinator** [comment]
ive been playing with adding various spectres. 

was able to add primal crushclaw and related skills 

redemption knight bugs out though and crahes pob

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.8.
