### ISSUE TITLE
Dancing Dervish/Duo breaks the POB

### ISSUE THREAD

**Issue by Tortorion** [PathOfBuildingCommunity/PathOfBuilding#1256]
I updated the Path of Building Fork to lastest version (1.4.170.6), previous version worked fine.

![243234123](https://user-images.githubusercontent.com/64162737/88144861-db9cc100-cbf9-11ea-8024-80de283e2be6.png)

This error shows every time I select "Main Skill" as Manifest Dancing Dervish and change the Default Attack to Cyclone. After that, the error appears. Hovering over any item while Cyclone is selected will also cause the error to show up. I cannot use any saved builds that had selected Cyclone instead of Default Attack.

ReproStep (100%)
1) Create new build
2) Add Dancing Dervish or Dancing Duo to your equipment
3) Set Main Skill as Manifest Dancing Dervish and change Default Attack to Cyclone

Or you can also try to open this build from the .xml file. POBF doesn't open it because it had the Cyclone selected.
[phys.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4958392/phys.zip)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.7
