### ISSUE TITLE
Error loading a build

### ISSUE THREAD

**Issue by JJMAIHEM** [PathOfBuildingCommunity/PathOfBuilding#1259]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Trying to load a build that yesterday worked (OnFRAME Classes/PassiveTreeView.lua:168: bad argument #1 to 'm_max' (number expected, got nil)
* **What were you trying to do?**
Open the program
* **What steps will reproduce the bug?**
Open the program with the build loaded
* **Does it reproduce every time? If not, why so?**
Every time
* **Additional information:**
![PoB Error](https://user-images.githubusercontent.com/5843379/88204596-ca7ca000-cc4b-11ea-92cb-7425188c5ca9.jpg)

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Nostrademous** [comment]
Need a pastebin link so we can reproduce.

**Comment by JJMAIHEM** [comment]
> Need a pastebin link so we can reproduce.
Here:
https://pastebin.com/PNLDG1wE

**Comment by Nostrademous** [comment]
Fixed long time ago.
