### ISSUE TITLE
Data display for support characters

### ISSUE THREAD

**Issue by VitusVarian** [PathOfBuildingCommunity/PathOfBuilding#1260]
**Is your feature request related to a problem? Please describe.**
A somewhat small group of the total player base, supports offer huge benefits in group play. While I can always assume that bigger numbers are better, it isn't always easy to determine what the best upgrade for a support might be. We currently have a small section in calcs that describes the currently selected aura in terms of area of effect and aura effect, but no "final" number on what that aura effect means. Being able to quickly see all auras with their effects in one place would be a great benefit to a support player.

**Describe the solution you'd like**
I would like to see a new tab/sub section of calcs that detailed out a support's benefits so that it is easier to decide on upgrades by making a direct comparison. There could be a table listing auras, sum of effect bonuses to that aura, benefit to caster of aura, benefit to nearby allies. Also included here could be things like Aspects, guardian/necro/ascendant aura buffs, animate guardian items, weapon aura buff, etc.

**Comment by Regisle** [comment]
There is one, though with generosity it might be hard to tell exactly what the aura is giving, if you temporarily add a minion and check the minions buffs you can see what your auras give to allies (screenshot from random build on poe ninja)
![image](https://user-images.githubusercontent.com/49933620/88232739-89b97100-ccb5-11ea-81fd-a8e781bb2cc1.png)

**Comment by VitusVarian** [comment]
I actually didn't realize that information was shown on hover. That does show a lot of information. Would it be possible to arrange this in a more presentable manner? Or perhaps just leave this part as is and have another part that shows the numbers all summed up?

**Comment by LocalIdentity** [comment]
The new party tab solves this issue
