### ISSUE TITLE
Cluster notable not found: Misery Everlasting

### ISSUE THREAD

**Issue by deathbeam** [PathOfBuildingCommunity/PathOfBuilding#1261]
After creating a PoB with Misery Everlasting on Large Cluster Jewel and exiting the build and reopening I get exception Cluster notable not found: 'Misery Everlasting'. The PoB was opening before after I dismissed the error but after PoB restart I can't even use PoB because it tries to open the build, fails on that exception but then also fails on `attempt to index field 'mainOuput' a nil value).

Example PoB with the issue:
https://pastebin.com/XmhTiDMd

1st exception:
![image](https://user-images.githubusercontent.com/5115805/88230037-fdd22580-cc71-11ea-897c-bd8aebc8a315.png)

2nd exception (after restart)
![image](https://user-images.githubusercontent.com/5115805/88230207-47bb0b80-cc72-11ea-9f4c-2d777b502291.png)

**Comment by LocalIdentity** [comment]
The error occurs cause you have a 3.10 and 3.11 tree in the build. The Misery Everlasting notable is new to 3.11 so it is crashing when PoB tries to get the 3.10 tree loaded in the background. Will look into creating a fix for this. In the mean time, you can delete the save for this build in your Documents/Path of Building folder and PoB will stop crashing. Here's a copy of the build with the 3.10 tree removed so it will work properly https://pastebin.com/Vm5QGGxt

**Comment by deathbeam** [comment]
Makes sense, and thank you for the extra effort on fixing the pastebin. (just as side note i am actually on linux, but I just have my builds configured to be stored in my dropbox so that was ez delete).
