### ISSUE TITLE
Crash when trying to add Support Gems to Any Spell while having "Gain no inherent bonuses from Attributes"

### ISSUE THREAD

**Issue by jokre33** [PathOfBuildingCommunity/PathOfBuilding#1263]
* **What happened?**
PoB crashed.
* **What were you trying to do?**
Add a support gem to any Spell, while it is selected on the left (for DPS sorting).
* **What steps will reproduce the bug?**
Click the empty gem box under any Spell Gem while it is selected on the left.
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**

Build Pastebin: https://pastebin.com/tbjn5JNd
Screenshot of error message: https://i.imgur.com/wTj8XXW.png
Second error message after trying to dismiss: https://i.imgur.com/eMxuAJl.png

This only happens when the following item is in the tree:
`Elegant Hubris`
`Timeless Jewel`
`Radius: Large`
`Limited to: 1`
`Implicits: 0`
`Commissioned (2000-160000) coins to commemorate Caspiro`
`Passives in radius are Conquered by the Eternal Empire`
`Historic`
`Ignore Attribute Requirements`
`Gain no inherent bonuses from Attributes`

Specifically the `Gain no inherent bonuses from Attributes` row seems to cause the crash.

**Comment by Nostrademous** [comment]
#1264 fixes this issue in my testing.

**Comment by PJacek** [comment]
Fixed in 1.4.170.8
