### ISSUE TITLE
Incinerate stages not correctly counted

### ISSUE THREAD

**Issue by aiolos01** [PathOfBuildingCommunity/PathOfBuilding#1267]
Incinerate Wiki: 25% more Damage with Hits and Ailments for each stage
I have a +2 incinerate stage enchant on my helmet so I should be getting 250% more. However I am only getting 225%. This is still true if I remove the helmet. I get 175% instead of 200%.
This is with the latest 1.4.170.7 version. A previous version (1.4.169.2) calculated the damage correctly as shown in the screenshots below:

1.4.170.7
[url=https://postimages.org/][img]https://i.postimg.cc/CM9dnSVQ/Snap214.png[/img][/url]

1.4.169.2
[url=https://postimages.org/][img]https://i.postimg.cc/VLMvjpfL/Snap215.png[/img][/url]

**Comment by LocalIdentity** [comment]
Fixed
