### ISSUE TITLE
stormbind skill importated as rune blast

### ISSUE THREAD

**Issue by mindyk** [PathOfBuildingCommunity/PathOfBuilding#1269]
if you import this guys pob from ninja https://poe.ninja/challenge/builds/char/flowzord/Mana_Protector?i=0&search=skill%3DStormbind the skill will be imported as rune blast. 

TBH i dont know whos bug this is, could be pob , could be ninja 🤷 

`eNrFXVtz28aSfg5_BUpV2RfrghnM1WufU7pZkmM5siTLcV5cA2AgIgYBGgAlM1v737dnAJAARUigYp9NKhIFdPf0dPd0fz0YMK_-_X2SOHc6L-Isfb2Fdt0tR6dBFsbp7eutj9dvdsTWv_81enWhyvHv0cEsTsydf41-eWU_O4m-08nrLcm3nFLlt7q8aUR5X0CUr9IwLt9n-UQB1fss1c217l_nOg_iRBdFczlIVFG8VxP9eutaT6aJyrccVQQ6DQ-Xd05jnWfTsUrLLWei4vQqC77q8iTPZlOYypYzhTtjnaXncZrlJ1nYCF9cV391rt_F-v48C82Yl8fHjW6H-Uw3ysPEf3l1kai5zq9KVToF_Hi9tQ_2U7f6SE3gJ4hRyQxkeIzjXYSlYIJzIrb21jNfTbUOl0y7HmbUcxnCmBD5_890kevjKNJBGd_pwxysAeYOlpNEaJexPt419GyXIO8x-vNZUsbTBDy7HKOP_vSBeEr7aK-zUiVHF1dLqRgjuksoJhhsIB7ny8oFn9tHeXabxqXuDOHtYvoEeTdmaK9tPsXleM0IGGOxy90nJmGYL7K4yNJnWOAwm_hxqsNnjNuw7t_dbjrqfq7V71EVepcqjGfFQgLpNdK5StVhViydJUjvYihbAYZ7nXqpv3Uo3V7KI_19Oexj8tqEvHf-Z-lyFoyKR-S1KRHnfZTv4qi1bCn2HkkTwUtDfZYGLRM9JvdjmutC53et9ILQMIYLyPy6NQN3l0NsUcGklB7xyGNSLvWtTp9emIb0ndbB-ARqxKUq9dMsJpBaTsdCPGotQ962FmHkMcnrzPXYGF2eVYs9EpOGsWskIfHuo8tnvaGI2BWwWF3JBCa8NxaOU53fzq_GsU7akeD2R6U1X5utE3SeHDJSd4aQXnYpGcK3fqoeGAhTSG-UI4L7FbhTBucs2aR8fI4VfXt6_W7TidbAEOqV8vYDOS7y7C9T1ZPN2PbzSTbLW_WWskenXdF31kZvmF-M50UcQLW1NfFShzPQr2Vi0jvUAqGcZ3d6AovDQh2AcstQ2hW9_jlIADeuGIDTR6aVJOtY-nHQflmq4OtRFt4OtrMdZSOON3EONiviVvXrn8RhZpbNQOJ38e24TAH2r3L0A7-xyooV6p1-KHSR3esceKB_WFZ5bwj1ufr-NMObXKd_z1flu4PIBw1wnIaz3Hhp8BirHA-HebVnGyzz6WwyzfLSXjxUSVBYkWfpdFY6qe2DJnERfPFnUWSaly0YIrfd2_GbN8eH12c3x7UWbZbia5wkX9LZxDdAu_q9RNpX2q48J8iSRE0LDR1SGidbTgwfrgznFeSboBxADRC9hrhP0xqUPWB828U8TWeaiQFkYFyV6KHzvp5PtXFjMWzq9dp9mvYgGTapCsQPmZZtFYYYXQdqPoBuUSwH0B4nej9OTB4eYqdziN4qgQ-hhlyax_6s1EOILeYdoIFBewOm1UY3AzStSuUAuTWUeJqyTqlD4gnq00DbH-lIQ5QOsWe1lK_VV53WSapJSK_s8iicAjLViZ4UB3NoF98YS600kB2C11tlPoOMFepIQd8P1z_MVBKX83rM5fV31T6TvVqMs_ur2XRaSTJLsgBrv3tX7c5YRex20L6FBPZvq6bdE9Kp8hMzqWrkIsnMRoKGaK03kVpchsHI_OUVjFNzniSZrxLc8H9r9IUWstkMQ2zLudWTM2NfXapQlWrvrIQ575mJ71nR8KkKpKoAgCLmqmF5r--7d9rjombclWmYpG7wFqQpy-vUzHtD1V9qbybymPYLw7-BX3E0b6le31vc2Ezzhm3vOSYXQ5VWRanzCpCt0bxzd0P1La9TMRePzCJSSfE809eBc6NUcmkwmc5mhYF9rYmsubcyjXr43nkYCc5ChGNlVJmhUuDZi-wgC-dO0z_8k5XmLQ2GNvXS5SzVzkGimiy62dpAfGCYQcOTawXJs72N9TDeesg2m9JCiGOkOFnk1HKeM8Gh6-iqzPLJgcpzu1G7Oq_u3U2nE83MZAx2SqEJAij7U2dymKVlDrUO6pMG5Nz0nKtT6iHbbG5LIU5bynMy3uA0vZ8HKtVXs26Vqe93bm42l4rVqXgHzwDh5QwGTmDRfl7oVJe5Mia7SMx-8Ops-ik3nNq9QTjgpIVApyXxx2TDT1pNAWWhHwU6BtYO8zANIq_ZoltYcOX6ZvaqmZ02NP456sMCsrtCd8Df0r57eeM1ueT9iapfrKzAi-csuk_qTpsMD0rfxcGPi0YY_87sW_yDWHxGaoIuJQvP1W0cPFzL7Xub2chyOhXrMwqHHBaIicpXYrC5smH41Ww_s8RV0PTQgJ4eyFvdexbgNawb1egfit_-OSjNyuI_lYMfwsOjWV1T-qHhkuS5sHAh4afijCsdQCb9FKfhGpgRhrHRQCWHWZaE2f3Gs6mkO1b8T0zSFag5TDLV7g47V5-Fkiren6j4mwSGPFLFuKV269qGK9swOpbzR2Id_B-qL83-in2EYnes9mEFtKNy9c5m5vlTK5hWPv8Zuyu17p9gxbZdWf-9IViwTD9PyaO4CMxRnbQNa9oXN1O3xbkSdfUnu894nWvtqCqELBuqt_3gj_YJMaMLBFyahWZ3kHtCbBMkyDbCmLrbnuAu2uaEkG2MJd5mFLveticFQduMYAQUjHlA7SJEtzGCG9sel1JuM09ytk2IxMDKDRchHjaXGYWfhPBtRBAFMYhRb5siTsQ2Ns-S4QrFIIwzKkEXFzO44rlwlxD4TDCXIMElxN0G6dSIlxgGdI3uVCKQ4CEOA4I6VICaBKaAOQX1MWYI5Egjk3AMo1PqgVaeK0EapYaXEkb5NvUIZfATZMPoBBlNMDN6ItCEugIkYPOIf9vzPGQ0YS7oDDMn9joYyUOMw2fXWFRwLrY9avRBknkUrmBprnsMtGLADJ8pjM6lBypjj28TJo1cJiRYCrmEbSMBRtoGvYS7LY0xwYhw02MCxHpECBCFXM9Y2ngQdAcBmGEOYsz5NfCmACXhswsCMAYHSM8aFIb3XGyM7jEJhuBGdbAANhfAC5gYPcGjCOYlJLBjicDJWHKBtoGYUxMwoCOEg5kpkS7oC0TetpDgWCS4kehxSuEnqA0mdMFp5jr8dD1kYgIUQBQGBG952FhQMONdBHbHcJMZrxt7cQrXEedgRxgaZudSmCnYSJr5goHhp2CgACIYZgZhBiaEWdsgAbN7oAzk4BKWSOsYJkL1cUqzJGidbz9evrMffhmX5bR4ubd3f3-_O4V8kUX6e5zo3SCb7E2BCdbZjl3cO0bs3j78c7D_8XD_4O_g-M3tHZ4G5enlhzN5wf6esFPmZkK9Je9vyNvLux0d30Un06PjmyPqRdEf793oHgXZ1z9P3xaH7OCQe98j9S3I-cFf-39O3D_ZzvWEpXd_3AQ-__rp7uzTm-n3z3l8jQ-v_7gqPx24748-nO58ybOrL6fTc_XbjYgPT4vTN-HV9I_555OLm6_xTpx9x9fvfhff8r-_qZtDeTsWhydvsHeRB99_m_958iV_e__2fTz78vkLi4_fXv2m5p8j8eck_XaLEvop3dn_Xf0OOejw9PPlH2d5dH2PxB8nZfTbtBgnXy7nR97lzYfPwR3K5En8JpsHV-_cq487R5i8O73H6O3HDx9OpTgWB5--8fHx-NsJ4vv8kOb58c3pSfqbvoj_Yn8ml5mI58H4kzt39d3s6zx4bZ2y13jlVXWStahcVP9lc5nxIWLYQP-4rFJ0_ZB5DR3kLncAHeQOjwyhI1R4A-ggl8gh-hHBuBxAhz0Twk-SQaobMqpN7Es6JHsJCRk0XVsdlnS4n5DIIfMw2WTIuJALPTbEbdgbEgVQJeQQOozNYeYB6pliNYQOMtug6bpQtYZEFYOJDDIz84a4w9bHVryIXoHIHRTNDAr0oHl4clD4QbgMCQNTpIeMC-WVDRkXipIY4l_JzcsBT4tziTso_EwdbLmD9RFyAB-Dkp85eDnEHYBDBoWVFIPCgMhhy4NjNCxJdrLQI8sXoNwgu5D2uIj3EzI2JP6wIHxI_FFYcEMCBjAaGuIQ5gKeGhTPbJABAfOyQfkPIzYkvwBYHbTOicGUQ-gIYoPyH2KDyhsg50F50sD6QXHluWvcAS3eEvLAH9DN2cbPtHvmw_us1Paeudj8YZvBm1jfO4VWeTC-KvPXW1vO31k2-Wz7WXNS5FSr8lxN67Mj5l59lsSrT5KUqjyKo0jn9hRM05cawj8a_V7Z7rduO83nK13a7Y5Zoet9L7vFYS9XD9irE3dAag_O1Nscl3av96VzuX95PDpWt4l2TvJ4Orq-z3auyizVzmWc3o4-pvG3mXbOjl46Ych8yTWEpg_Yn0vNOUe-xp4fMikRF5EQXGmqA1_4ngxcHSJJNPeYqwIoICOrgp3xS0eQkf10qb-9dBgfnU2g3Q7isnjpoNELxH51yswxR0MdlbYfflXHjsxRtmL0AiNDNVHf48ls4lRnouonP6MXhLdvmnNVIwxi48VeZGUB8wijMmmUzVLgQ8SOrZLEOU7sCV5zCKE9LBGWwhxHaN0Y_U-Qq6jU4f--QHRJYNS382iLMHFlBu16Bnc98_H92YePx6OzNIxvs3R0OvPzuHAO4zxIdNl2jMRuxGQIJkZIu0xEgVCMhtSnWCpoOkmgmFIkQCJUhIA3IL94rkYhRyGiUo6uxmqqc2uGrpPYqD4E9dLB7qheFhAzO5c7JzsHbQ_KtgfdEWK0bequa5Dbvtfx0CVE8B2oYkjAMebQnHM_1qkzz2Ymwh1l6Zw30ER-Hb3P0p04NUYtq8s1-9yJ8mxSERUOGA2WQdbchCFVYSWPqGwrYiWYV3bMyPUZsijLHa2CMUzfBZeaULBkRp2xeQAG2QEGB9HwK5mPMGlLtJt7TrW7t6mobWc2NUEE1O6vPQHjrQ2Y6zGExV0GVrg2x5NHVypOy_-CnFD8d-Gcqpmv86_t8MEqCBWPFBIRVPgoEtoLI-4JSoQrPIgsRHWEVQgh5FGCuUc8j8hQSmpWvlCdkOGiFTJiGTIHO592Dqp_exc-Xi6hWoYTZrqAfF0ujOo0RwSXtCc5-L9wXthkcN6KJscENf7VqYWNXnBjeOcsLc1ZjlsjZvTCc3tziOVH4K3L-nWXKmpeSPogs9j3PnSuSm0GNOdeHggqbHIe2fPoTUxAaJbm-X4Vr1ZnX0Og6Gqk9V4na72-X_4d53Hj5jdZ7Cd6dKFmytmfzFYSBnV9FEXU1a7LAyJJxKGBI0p7bki0F9HIDTFSLCQ-9J0o9D3ku4hxX3APRUS7HY8j1uPD_STJArBI4ZzHkASP8jj9CuHooQeLbmE9c9jTvAEDWdglD9M36c0bkgwQWldO0MXsHVeLDkOeys3rHebMUnOeF3i_zSB522PDPV6ga8roSQYFwzlJVZ6MLvIsMo9bPsF4bdsTRAlnyMUB9QSC6JIc4CiSkYulL1gkSIg0VE1AAYgKHMiAa6nc0GPYp8pXq1V0bYJeXWfc7RZY1DGXeWzq2LPsI-715a8RFu1by4pc34a6KR54bBEL13l8ewuLQDmVjgvhi-T-0SZ3m3Z7LM7Wxv1NFoe-eckAQuswS_-a5TBMdYagE_KEKYJMZ6eYSwLKGBZMYoEg3l2BJAcsjQINTnGR70dRIF0e4sDlBIUUWHrN3imLq3antGt32WP2KndZPlt8GhstAYiJWHBbxz3mtQLzkpIDYDP-qp3qiL8tNNa4BawY1F-GX3BmRr1elqJu8QOt6Eoeu1Xm8LQDC-o346fDLM9nU1C0x2N8rceuvs5BxXIMhssDbdxln3x3EE3AKcCXQIVch1pz6gaQd2QUekKGjEkahEHkRq5WxNWCha7CASYhgYrkegB-Bi0Si2EeKUdoGb51um5OXkFKqwEKmGcyX48TnTha1Pa0ysulNZuBng1eeIEQerBqvA4-at4jq0PFJKygcjTwGYfAsrHvIdUHrY13ViJjxJZJrs6NVUEbfW7AR5pVYKudNUdX5Sx1rse5huYEvA_VyrcqwQjUrQwAM8wrmQaIaRU2sK0nJMSatHkD0aC_O9ezPH2k_QBUKwnVLJAypCEgqVBGMCGhfcmUS6HX8DTgGBQI12eRIXOVK90AIEwY-hR1Y4I_2n6QLn7vaz_YAzixH4aFYxsPhCv-OnTgSn0ce_SCPUyU0K3YIdeN9M8bC7muVuXxxDmIDSLJ54WJ3QOddFBC5GnoFnwlGGXS54HnwxUeChz5wtOeB0BMMd_sSQbIl5EXED8kSEkfChXFoVjFha1yJFcMzuWTjRxEsk5vIWtAc_gIMUNrbEuX3WTLrAgvV4VtFeoFVJhGI2xZnXZkPhLcyF2b8C6gbwNYMFN5GKt0tJ8HY5tBAWjUareszkUokMBIU0DhCgXwQSkfypVLFVymAgKcU0QjxgVjfqTA7JpwpQAsQPPXDXMw9CB8wMTqCsBPNcF4fcUyhxiqYrW4tARbreNw6263sVgrTVW5qF5tR_p7qXOL5jF9QsceJ6EB-BnQ2yQuYD1PdDmG5VE3nC0_BYB3KKwC4lIuRUAiAO4uIkoElHPlAYLw_IBKj3LkB4RAVZIEu9qDBivSftAtURwv_YTclmOQ6PbVVXPR6SHs23DLptYJZwYN1RGt7fH7kXlZzjGbKsDcvNrc8APf8Xeoal2ptZQOP61K3sLWGwjoccXKjsf5_snZ4cge487SxhUHqlBJ7QAbaqWapcF4pToElCgKaFn4WAKMA5THvIC5oXKxhk-E-AzREP4MJXaxcpGQ0NGEoctCygnlHXew7rJZuoO4K-5w1xTjdi5Z4luoWAncXK3MZ5PJLDWdLvDbNy-N0da58FJPDKZdEkEKgTzVZ1lvnWXtq76G9xjWUNqgvoVlP5kE1TWrr0iEGNMKU2hVolBAxvF9LrkgAUGu5gKHxKO-1tI3z2RdFlBLgbWPiY56o7xjVka7ZjUAaNGUTbJZtS1Sbd5UFrP2PpzlBVjkMWvVJLWt2nKbk4ijiq96T8VAHLPbkFt2WFMQd7OkslOXcLEx8WGmZ71eIOu8sA9T1cAXAxiIE7PbtfDAfghFTplzRx0nUBn6voD0LyCruIJIc0ZIMRUxD2KaYehV_MDHIXgA-R4jwkNIQdDDfyzUtOsEt927tEK764K6yjbbKXVlHGHcD03XOqLHMHRtDr6cTRYZGHq5ILPHykdmg8cUywc5WAZhRJXpA6SLpFIsIDIMQs5lwLQPvzwcRAp78A93CXM1ozpCgBh9zJGI3F7DoPbuNOarpgGsdrhY9fb91hrcrSS_jiVemJZhla2zQ7iB_VjPzl9eI_DTbKoB2MWTAkL_rb7XSSdZEiZ0EEQ-Vz73sOaahCEEFg4Y0ZQDzvaMWbHBHYgHCLotpTSYj2ElPIK7UNobVV-K9NK5AXXMibquvX5Pk7mjqreqnYvqHA90R6lzY3Zq39k0acF--14l0glU6vjaabaSQuc-LsfZrISLxlRBlqYgFq6DRW0rYk4GjXaQ9zxosL5hPYXUDSjAbmNBz-ubcvTAphr6TyokwGKXM4whwgJYgxqgAYqEFr4fRpHEDPAxAyjAiYqQ4rBkOXZDHroruI0tbGrts7J700pjlzpKKgus1nW7sThConfPrDmVXW2JLb7jpKj6EEASSzco6DeuYRUW0LhPKmur6TSZVykCaggkSlx3hOVYx3n1BRJ9Zhbr9wWmAMBKO6diCnroXluTEAseEsiJQmKEAq4QxVyLgBNETJFiAiuCoiDgUlM3BAjABPWRdmmkALatYuTG1udQWWeTrrEXexw1eoWINGnfN-aJgKys-mEIvu7uTsfU5kvPjI0SbfZ8iNtpGpd23m62FdoubDZdAGZZU9vnI6TeTi4qgHEal_V2Q5U-78y-Yx7kcXuv4andGiTXuuWTKgFf5k1ePp7rqqGB6hk8dA1Crh8Kn4JvMINmnPrYM80L9JGYKhZp6FtQCPlEUld5mGMeKgw5OSSuIoTobmqhDwN_Cbf277I4rBNB9WUUMDW2zgfdHnHtLnL1PKjXgfWXQtTvO4Htc5uNzPc7wtox-M6wlQbvxVDcq2wHBP7caY5owxBmk9Juz-HGfTWy5tbrnWcXC1R9vvbRxMNx6rd3-p4tumv2AE7nU4hlcOPlLE5HVxOTLw-TmX2X5uGiEwiKKhGCulRAqYg8nwQShTLUnBIipBKmCRKhRJSGJIAfQjEZBB4nAaDu7qLz2rukou8JgtlN8Zqa0WxLtm-bfWSrdpfGuTXPhABY9jr0EV77sLAW8KLaCao6m9bewVB20QZRNsYGcrYeKLm7aPkw1DxJqh7zj5BTyepIMQj296mGslisVLkriML6G3eaV-yakw_NlydZkupkQftMvH0LAyBJ--gZbbNURGb_aEkhh8lsH38kw1haJ0AW3-zXUqN63LWkIWs0rd60aij4sHFbJ3wWX0HYErp8s2RB5T6kar7eY3FEc512rS8naOi8h3QGM3WGGzaN1okX1Ce1ZWLRO9MWURMN9XmUR86itI-gDAjJtRa-uldTZ9-fF4Xpo6szPWuOX63G5mCWjVbAYA3R4xpWgfFDmJ6wReO-Dcdau7wHCR6mD97UpWYR_wCfrslAayJzsLE2ylt9635DU_SkvAE5b5Aj0DMcgTZfj88w6ZqUvDYin5ExHmNFwwL6YSUYUgrWu8So8ZQb-svG-mX6tMyeEjNgfeDByv6AMFhT0obUtIFFba-uavYQqD1DYr_-MEuj-PbBlxmaomffLzYbvU3rteX4WQa9X1orv9fPZh8oH47tY-Kn2bShPisOsqJYftdidZpvDXVcfZ1N69ts7Bfc2Be6nxrJB1ga2k2usQ6vM6vm01wwXPcLNTezQ_XNgeGmbM0W-YBZzaJo8RVhD4lf7TVefrW3-n8d-D82Igkn`

**Comment by ppoelzl** [comment]
Runeblast is a secondary skill that is added by Stormbind. See https://pathofexile.gamepedia.com/Stormbind for more information.
