### ISSUE TITLE
Immortal Call and Second Wind

### ISSUE THREAD

**Issue by ValkyrieEndgame** [PathOfBuildingCommunity/PathOfBuilding#1274]
Immortal Call does not register as being supportable by Second Wind, even though it is in game. This issue is present in the following build: https://pastebin.com/gm9CkVi6

Linking Second Wind to Immortal Call in game shows as a supportable skill and it lowers the cooldown on the in-game tooltip.

**Comment by RuriRyan** [comment]
This is not a bug. As soon as you link CWDT, Second Wind becomes unlinked ingame. As you can see the gems are not highlighted on mouse over.

See:
https://i.imgur.com/VMtmAaQ.png
https://i.imgur.com/xliBTvm.png

**Comment by ppoelzl** [comment]
@RuriRyan Thank you for your testing!
