### ISSUE TITLE
Increased flask effect dosen't calculate correctly on Bottled Faith when +% to Critical Strike Chance is an integer

### ISSUE THREAD

**Issue by she02789222** [PathOfBuildingCommunity/PathOfBuilding#1278]
I have a Bottled Faith with +2% Critical Strike Chance and +42% increased flask effect (without Alchemist Genius from medium cluster passive Spiked Concoction, POB doesn't calculate Alchemist Genius which is another issue, otherwise it should be +62% increased flask effect):
![圖片](https://user-images.githubusercontent.com/27253279/88534905-920a0700-d03b-11ea-946f-5a070b8ad5b6.png)

The base crit chance should be (5 + 2 * 1.42)  = (5 + 2.84), but the following picture shows it remains (5+2):
![圖片](https://user-images.githubusercontent.com/27253279/88535024-c8478680-d03b-11ea-807b-440aadf0ee9d.png)

I modified Bottled Faith with +1.93% Critical Strike Chance:
![圖片](https://user-images.githubusercontent.com/27253279/88535160-0fce1280-d03c-11ea-8e9a-bb9d70dac845.png)

It then calculates correctly with (5 + 1.93 * 1.42) = (5 + 2.7406):
![圖片](https://user-images.githubusercontent.com/27253279/88535261-33915880-d03c-11ea-907f-fc8777610adf.png)

When I change +2% to +2.0%, it remains the same with +2%, the increased flask effect doesn't calculate. 
Same with +1%, the increased flask effect doesn't calculate either.

**Comment by SuperJelle** [comment]
Any update on this? The bug is still in effect. I believe it's specifically the interaction with Bottled Faith and Alchemist Genius, where the latter isn't applied when the former is an integer.
