### ISSUE TITLE
Add support for Mirage Archer as damage multiplier gem

### ISSUE THREAD

**Issue by deathbeam** [PathOfBuildingCommunity/PathOfBuilding#1279]
**Is your feature request related to a problem? Please describe.**
I would like to see the DPS gain with Mirage Archer on my skill instead of calculating it manually every time (at level 20 it is 27.6% damage multi).

**Describe the solution you'd like**
I would like to see Mirage Archer extra damage to be properly displayed when I look at skill it is linked to. Of course this should also account for on hit stuff not working with mirage archer, so for example life gained on hit not doing anything for that part of the damage etc.

**Describe alternatives you've considered**
Alternatively it could be displayed as dropdown under skill, but I guess that is a lot less elegant (and also creates issues with skills with multiple damage sources, like Explosive Arrow, Scourge Arrow).

**Comment by ppoelzl** [comment]
Mirage Archer is a separate damage source, not a damage multiplier to the skill it supports. This is not only relevant for the mechanics you pointed out, but also for ailments, stun and armour, to name a few. Because of that, it would be incorrect to implement Mirage Archer as proposed. It is more similar to The Saviour's Reflection skill than to Explosive Arrow or Scourge Arrow.

**Comment by deathbeam** [comment]
> 
> 
> Mirage Archer is a separate damage source, not a damage multiplier to the skill it supports. This is not only relevant for the mechanics you pointed out, but also for ailments, stun and armour, to name a few. Because of that, it would be incorrect to implement Mirage Archer as proposed. It is more similar to The Saviour's Reflection skill than to Explosive Arrow or Scourge Arrow.

Well even if its separate damage source, it is still damage multiplier in the end. Also now that you mentioned Saviour, i see that #976 is open and labeled, asking for basically same thing as I am, so why was this one closed? Mirage Archer can be implemented in same way, e.g as separate damage source but still calced in total DPS.

**Comment by ppoelzl** [comment]
> Well even if its separate damage source, it is still damage multiplier in the end.

While there is a multiplicate amount of damage > 1 dealt to an enemy as result of having a Mirage Archer active, at no point does the player actor gain a damage multiplier to their skills.

> Also now that you mentioned Saviour, i see that #976 is open and labeled, asking for basically same thing as I am, so why was this one closed?

While I disagree with major points of the proposed implementation in that issue on the same grounds as here, there is still an idea or two left to salvage. This proposed implementation, on the other hand, is incorrect in its entirety. For consitency's sake, I will also comment on #976 

> Mirage Archer can be implemented in same way, e.g as separate damage source but still calced in total DPS.

Mirage Archer should be implemented like other secondary actors the player actor spawns, such as minions or totems, While there are caveats to this approach, it makes it much more likely that this feature will be implemented.

Feel free to open a new issue for Mirage Archer support that incorporates this feedback.
