### ISSUE TITLE
Cast socketed curses mod missing on Vixen's Entrapment

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#1282]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Added Vixen's Entrapment from the unique DB, noticed it was missing the "Trigger Socketed Curse Spells when you cast a Curse" mod.  Mod exists in the gloves.lua file, so I'm not sure why it's not appearing

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by ppoelzl** [comment]
Unsupported mods on items are skipped by default until the mod parser encounters a mod it understands. You can work around that by inserting "Implicits: 0" on the line above the unsupported mod.

**Comment by Wires77** [comment]
Ah, I didn't realize that's how that worked, so I just submitted an issue for the time being.  I'll submit a PR for this unique to re-order the mods so it appears.

**Comment by PJacek** [comment]
Fixed in 1.4.170.8
