### ISSUE TITLE
Feature request: automatic Arcane Cloak+Indigon buff base calc.

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#1286]
There are hundreds if not thousands of builds on poeninja that utilize Arcane Cloak as their main buff for damage. However, poeninja does not use it for the damage calculations, which is because the base community PoB client doesn't use it either.

Arcane Cloak states how much max mana it can consume, and so do the helmet enchantment buffs. 

Would it be difficult to code in the baseline consumed mana (**[max mana - mana reserved] * mana consumed by arcane cloak)** also calculate how much damage buff does it grant with Indigon?

Thinking in terms of an automatically calculated and displayed number in "# of mana spent recently" window that can be changed manually if needed just like with number of p/f/e/i charges?

**Comment by Wires77** [comment]
Arcane Cloak's damage buff is already calculated in PoB, so I'm assuming you're talking about using that + Indigon, since you're talking about the "# of mana spent recently" config.  There are only about 400 builds using both on poe.ninja, anyway.

Personally, I don't like assuming you'll have spent that much recently, since at base numbers Arcane Cloak is only spending mana every 7 seconds unless you're getting hit a lot, so the "recently" buff isn't guaranteed.

**Comment by Ydoum** [comment]
> 
> 
> Arcane Cloak's damage buff is already calculated in PoB, so I'm assuming you're talking about using that + Indigon, since you're talking about the "# of mana spent recently" config. There are only about 400 builds using both on poe.ninja, anyway.
> 
> Personally, I don't like assuming you'll have spent that much recently, since at base numbers Arcane Cloak is only spending mana every 7 seconds unless you're getting hit a lot, so the "recently" buff isn't guaranteed.

You're right, however,
- Indigon does take the mana spent by AC into consideration (4sec buff)
- self-cast AC is a thing as well (in regards to your "unless you're getting hit a lot")

**Comment by Wires77** [comment]
I'm aware of both of those facts, the "unless you're getting hit a lot" was more talking about the buff disappearing not due to timeout, but due to damage taken, putting AC back on cooldown faster.

**Comment by ppoelzl** [comment]
It's out of scope for PoB to simulate combat. How much mana you've spent recently depends on a number of factors, most of which PoB can and will not account for. You can always manually override mana spent recently instead.
