### ISSUE TITLE
Feature: Tooltip that shows difference with gem quality 20%

### ISSUE THREAD

**Issue by Mocker** [PathOfBuildingCommunity/PathOfBuilding#1288]
**Is your feature request related to a problem? Please describe.**
When I gearing up a build it is very useful to know which gems I should get to 20% quality first. The current process of manually flipping between 0% - 20% quality to compare changes is annoying

**Describe the solution you'd like**
The skill links suggests the best support automatically, something similar for gem quality would help for prioritizing build. For example, a tooltip that shows what the difference would be for a gem at 20% when you hover over it. 

**Describe alternatives you've considered**
Current process is very manual and clumsy

**Additional Context**
The tooltip over the skills themselves would also be nice to display what quality adds to it.

**Comment by ppoelzl** [comment]
Starting with release 1.4.170.19, you're able to preview the effect of a skill gem's quality before equipping it.
