### ISSUE TITLE
Feature Request: Only show Jewel Stat changes for socket I'm looking at

### ISSUE THREAD

**Issue by tockity** [PathOfBuildingCommunity/PathOfBuilding#1289]
**Is your feature request related to a problem? Please describe.**
I like the new way Jewels are displayed, but, unfortunately, it's still a hot mess of information overload in some situations.

Here, I'm trying to compare stats between jewels in socket 10: https://puu.sh/GcZGi/fe629a056e.png

As you can see, Socket 10 isn't even visible.

With Cluster jewels mucking everything up, high numbers of jewels are pretty common nowadays.

**Describe the solution you'd like**
I'm really not sure what the purpose of showing stat changes for every socket is when looking at a specific jewel in a specific socket. 

Ideally, when you're looking at a specific jewel in a specific socket, only that socket would be displayed. This would make the display much cleaner, the information more digestible, and avoid the above issue altogether.

**Comment by Wires77** [comment]
As a counterpoint, most of the time I actually want to see which socket would be the best for the jewel I'm hovering over, I don't care about which socket it goes in.  As a workaround, you can double-click on a jewel and use the scrollbars to view all of the socket comparisons.

**Comment by ppoelzl** [comment]
As @Wires77 pointed out, all sockets are visible. You may have to use the scroll bar on the bottom.
