### ISSUE TITLE
Skill Gem passives are not imported

### ISSUE THREAD

**Issue by Wibbbs** [PathOfBuildingCommunity/PathOfBuilding#1290]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

When I import my character the passive that I am getting from cluster jewels are not being imported. The additional nodes are shown but are not shown as selected and also therefore not included in the calcs.

* **What were you trying to do?**

Import my skill tree from my character.

* **What steps will reproduce the bug?**

Import a characters tree that has jewels clusters and node activated.

* **Does it reproduce every time? If not, why so?**

Yes everytime I import those nodes are de-selected.

* **Additional information:**

Screenshot of my passives in POB after import.
![POB](https://user-images.githubusercontent.com/24574428/89108964-0c0b0900-d40b-11ea-82d9-4dabab5754b7.png)

Screenshot of my tree in game.
![in_game](https://user-images.githubusercontent.com/24574428/89109035-9eaba800-d40b-11ea-82d6-793384cbbb91.png)

Build link
http://poeurl.com/cYGH

**Comment by ppoelzl** [comment]
This only happens when you import a character from the game. As there is no information on which cluster jewel passives are allocated in the data we get from GGG's APIs, this is not an issue on Path of Building's end.
