### ISSUE TITLE
Import Canvas not working on MAC

### ISSUE THREAD

**Issue by Vliesie** [PathOfBuildingCommunity/PathOfBuilding#1292]
I can't seem to paste anything into the import field to actually load the Build.

1. Yes I tried cmd+c then cmd+a
2. Yes I tried copying the raw data instead
3. I tried in Firefox/Chrome/Safari 

I can't use any kind of Mac command on that field 

https://vimeo.com/444167387

**Comment by PJacek** [comment]
pob.party is not affiliated with this project. It says so when you open the page.
