### ISSUE TITLE
Brand Loyalty debuff not applied for non-brand skills

### ISSUE THREAD

**Issue by youngwookie** [PathOfBuildingCommunity/PathOfBuilding#1294]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Brand Loyalty (cluster jewel notable) debuff (5% enemy damage taken increase) is only applied to brand skills.

* **What were you trying to do?**
Checking calculations page of non-brand skills with # of brand attached set to 1 in configuration. shows no change in "MH Eff DPS mod," while brand skills will have the proper "enemy damage taken increase" calculated.
(non-brand skill in my case is raise spectre)

* **What steps will reproduce the bug?**
Allocating brand loyalty & checking the "MH Eff. DPS mod" of a brand skill will show the debuff, but any other skill will not.

* **Does it reproduce every time? If not, why so?**
It is reproducible with any non-brand skill.

* **Additional information:**
https://pastebin.com/8ZXhbHhT

**Comment by Lothrik** [comment]
I wasn't able to find what PR fixed this exactly, but this has definitely been working properly for at least 6+ months now.
