### ISSUE TITLE
Added Elemental Damage from weapons is calculated but not displayed

### ISSUE THREAD

**Issue by scottord** [PathOfBuildingCommunity/PathOfBuilding#1295]
I was testing a build using the "[Oro's Sacrifice](https://pathofexile.gamepedia.com/Oro%27s_Sacrifice)" unique sword, which adds Fire damage - the Calcs had the correct values, it appears, but there were nothing but zeroes appearing for Fire for the "Added Min" and "Added Max" calcs.

I noticed something similar when equipping "[Debeon's Dirge](https://pathofexile.gamepedia.com/Debeon%27s_Dirge)" - helpful as another data point if there is info not being displayed, hopefully I'm not just blind.

POB: https://pastebin.com/uLbP9HMn

Thanks as always for your work!

**Comment by Regisle** [comment]
This isnt a bug as its not added damage its base damage, this is displayed under the hit calculation like
![image](https://user-images.githubusercontent.com/49933620/89373703-864bce00-d728-11ea-8c32-d3423ed0f9ed.png)
