### ISSUE TITLE
Wrong resistance

### ISSUE THREAD

**Issue by uranmorte** [PathOfBuildingCommunity/PathOfBuilding#1307]
Hello. I don't know if it's a bug or not. After importing, my resistances are different compared to what is displayed in the game.

1.4.170.7
`https://pastebin.com/NXWaCkDw`

![res2](https://user-images.githubusercontent.com/47936213/89608706-29f6c480-d876-11ea-8c56-adb2ed67a0cf.png)
![res1](https://user-images.githubusercontent.com/47936213/89608710-2bc08800-d876-11ea-9327-c7e497ae1277.png)

**Comment by ppoelzl** [comment]
You do not have any nodes of your cluster jewels allocated. After importing your character, you have to manually set all passive points spent in cluster jewels. GGG currently does not provide the necessary information for PoB to allocate them for you.

**Comment by uranmorte** [comment]
> 
> 
> You do not have any nodes of your cluster jewels allocated. After importing your character, you have to manually set all passive points spent in cluster jewels. GGG currently does not provide the necessary information for PoB to allocate them for you.

Ty.
