### ISSUE TITLE
Viewing calc tab for spectre causes a crash

### ISSUE THREAD

**Issue by jezznar** [PathOfBuildingCommunity/PathOfBuilding#1308]
* **What happened?**
I was looking at this spectre build that I saw over the internet and was trying to check the calculations of the spectre damage to see how the damage came but it errors out.
* **What were you trying to do?**
Viewing calcs
* **What steps will reproduce the bug?**
1. Import https://pastebin.com/2UVUfNua
2. go to calcs
3. Select 6L Spectres as socket group
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**

**Comment by Regisle** [comment]
Known issue, Fixed by #1301

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.8.
