### ISSUE TITLE
Slayer - Headsman - Damage against unique enemies multiplier not applied to bleed

### ISSUE THREAD

**Issue by nomoarbleh** [PathOfBuildingCommunity/PathOfBuilding#1315]
Hello,

It seems that the slayer node "Headsman" applies only partially to bleed damage.
In configuration, "Is the enemy a Boss ?" is set to Sirus, so I expect the "20% more Damage against unique enemies" to apply (regardless of damage type/source) when allocating the node.
The weapon hit benefits from the multiplier, but not the bleed application.

Although, the "10% more Damage if you've Killed Recently" applies just fine when using the "Have you Killed Recently ?" checkbox in configuration.

![headsman_unallocated](https://user-images.githubusercontent.com/69507253/89879610-7f5b0a80-dbc3-11ea-9c18-3fcdbd220678.png)

![headsman_allocated](https://user-images.githubusercontent.com/69507253/89879622-82ee9180-dbc3-11ea-9d89-6f51d1fd61fd.png)

Example build : https://pastebin.com/FckHFdj7

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
