### ISSUE TITLE
Berserker - War Bringer - Exerted attacks multiplier not applied to bleed

### ISSUE THREAD

**Issue by nomoarbleh** [PathOfBuildingCommunity/PathOfBuilding#1316]
Hello,

It seems that the berserker node "War Bringer" does not apply to bleed damage.
I properly set up some warcries, and defined an amount of rage (if it ever required some to sacrifice it), so I expect the "Exerted Attacks deal 50% more Damage if a Warcry Sacrificed Rage Recently" to apply to any damage dealt through an exerted attack when allocating the node.
The weapon hit benefits from the multiplier, but not the bleed application.

By the way, the seismic cry, which uses the same wording, appears to be working just fine.
And as a sidenote, it has been confirmed that the "Exerted Attacks deal X% more Damage" should also apply to ailments here https://www.reddit.com/r/pathofexile/comments/hb56kp/path_of_exile_harvest_gem_information/fv75cxx/.

![warbringer_unallocated](https://user-images.githubusercontent.com/69507253/89882291-e9c17a00-dbc6-11ea-864b-ed1f245fb54a.PNG)

![warbringer_allocated](https://user-images.githubusercontent.com/69507253/89882296-eb8b3d80-dbc6-11ea-9711-f678cf92a210.PNG)

Example build : https://pastebin.com/zdrmKNdV

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
