### ISSUE TITLE
Wintertide Brand damage calculation

### ISSUE THREAD

**Issue by iceandfirewes** [PathOfBuildingCommunity/PathOfBuilding#1320]
Hi, I recently only started playing wintertide brand, one of the new brand just added this league. I think in the skill description, The mechanic of this brand is different compared to other brand it that it gain stages every .25s locally and "might" be modifiable through %brand frequency. The mechanic being, every .25s, the brand gain 1 stages, and it deals 20% more damage per stages. I don't know how damage is dealt in term of DoT damage, for example, does it take the damage over time divide by 1 second and every time the game tick it deal that amount of damage. The point is, PoB doesn't take into account these "stages" that make the brand deal more damage the more time they "stick" to an enemies. Or I'm just blind and can't see it. Thank you

**Comment by Regisle** [comment]
This what your looking for? 
![image](https://user-images.githubusercontent.com/49933620/90034284-9141c800-dcff-11ea-8eb6-555c948c8bf2.png)

**Comment by iceandfirewes** [comment]
oh thank you. Pepega me
