### ISSUE TITLE
Add Specter

### ISSUE THREAD

**Issue by McMuffin92** [PathOfBuildingCommunity/PathOfBuilding#1322]
Hi!

I hope u guys can add Redemption Knight to the add list on POB fork. Beacuse i can't see how much dmg they do or life or anything!
So it would help alot if you could put in the data for that Specter.

Hope more want it also!

**Comment by LocalIdentity** [comment]
I've already made a PR for them to be added in the next update

**Comment by Nightblade** [comment]
Working as of v 1.4.170.9 but I think GGG recently nerfed this minion, might need to check stats?  (-30% heath & damage from memory).

**Comment by NiekvanderLinden** [comment]
> (-30% health & damage from memory).

**Monster Changes**
Raised Spectre versions of Redemption Sentries and Redemption Knights now have approximately 33% less Life and Damage than before.

source: [patch notes](https://www.pathofexile.com/forum/view-thread/2935777/page/1#p23494374)

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.10.
