### ISSUE TITLE
Glancing Blows block % not appearing in stats when adding to Thread of Hope, and cannot allocate the skill using {crafted}Allocates Glancing Blows

### ISSUE THREAD

**Issue by mrk-han** [PathOfBuildingCommunity/PathOfBuilding#1329]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

**Version**: 1.4.170 Latest

Please try to fill in as much of the template below as you're able.

* **What happened?**

Steps to reproduce:
1) Equip Thread of Hope
2) Edit Jewel to have {crafted}Allocates Glancing Blows
3) Observe no allocation is present in tree
4) Select and edit jewel to add the following text to the tooltip:

```
Thread of Hope
Crimson Jewel
Unique ID: 6c31c1e5d70498c6d15287f4d78b006e36dd6e549745268be4d2ebf93aa95037
Item Level: 86
Implicits: 1
10% chance to Avoid being Stunned
Only affects Passives in Very Large Ring
Passives in Radius can be Allocated without being connected to your tree
-11% to all Elemental Resistances

{crafted}Allocates Precision
{crafted}Allocates Sanctity
{crafted}Allocates Glancing Blows
Chance to Block Attack Damage is doubled
Chance to Block Spell Damage is doubled
```

**Actual**: Glancing Blows is not allocated on skill tree, nor is the Chance to block atk/spell damage showing in the stats in PoB.

**Expected** Either method should work to help account for Glancing Blows,

* **What were you trying to do?**
Tried to manually account for stats because Thread of Hope was not automatically doing this. It does work for other skills, just not Glancing Blows for some reason.

* **Does it reproduce every time? If not, why so?**
Yes

* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Link to build:** https://pastebin.com/z2ijgc33

**Comment by mrk-han** [comment]
Possible regression of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/960/files

**Comment by ppoelzl** [comment]
@mrk-han You say you're on 1.4.170? It seems to me you are not using the community fork. We're on 1.4.170.7.

**Comment by Regisle** [comment]
Only notables can be allocated like that keystones are normally just added (see skin of the lords) but glancing blows isnt in the stat map yet, though why your thread of hope doesnt just have the ring is odd it should look like this:
which lets you just assign the points

**Comment by ppoelzl** [comment]
Get the fork from [here](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases). Thread of Hope is fully supported and you don't have to abuse Blight's anointment mechanic to allocate nodes in radius. Your item however is malformed. It should include `Radius: Variable` as one of its mods. Please get a new one once you're on the fork to make it work.

**Comment by ppoelzl** [comment]
`Allocates X` is how the anointment mechanic is implemented on item in-game. Only notables can be anointed, not keystones like Glancing Blows. This is correct behaviour and not a bug.

**Comment by mrk-han** [comment]
@ppoelzl @Regisle Thank you all for the help! Looking forward to helping contribute in the future where and when I can.
