### ISSUE TITLE
Regenerate #% of Energy Shield per second mod on chest breaks Net Life Regen calculation

### ISSUE THREAD

**Issue by zarichard** [PathOfBuildingCommunity/PathOfBuilding#1330]
Having Righteous Fire active and adding a chest piece with the mod Regenerate #% Energy Shield per second causes "Net Life Regen" to show the wrong value. It looks like the mod makes the calculation ignore the degen altogether and it's only showing the base life regen.

https://pastebin.com/f4A2scHW
This pastebin contains a repro case. Unequipping the chest piece should update the Net Life Regen to show the correct value of -94.1. Equipping it again changes it back to +0.9

**Comment by Regisle** [comment]
Net ES regen doesnt show up on the side but it does showup under calcs 
![image](https://user-images.githubusercontent.com/49933620/90606867-94790e80-e23f-11ea-872d-de4f0e1e0ef3.png)
Will look into fixing it

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.8.
