### ISSUE TITLE
Curse on hit corruption stat requirements

### ISSUE THREAD

**Issue by aiolos01** [PathOfBuildingCommunity/PathOfBuilding#1334]
PoB counts the stat requirements (strength, dexterity, intelligence) of all gems regardless of their origin. This creates the issue that when you have a curse on hit corruption (e.g. Enfeeble level 12 on your gloves) it indicates the skill stat requirements (in this case 121 intelligence) as if you were using a normal gem. However the curse is applied on hit even if you don't meet the intelligence requirement (tested in-game with lower intelligence). So in the case of skills coming from corrupted items the stat requirements should be ignored by PoB.

**Comment by ppoelzl** [comment]
Unable to reproduce this issue.
