### ISSUE TITLE
Timeless Jewels do not disable keystones

### ISSUE THREAD

**Issue by Tntmister** [PathOfBuildingCommunity/PathOfBuilding#1338]
Currently, keystones in range of a Timeless Jewel remain active, still applying their effect, which can get in the way of some things.
For example, having a Glorious Vanity with the _Doryani_ modifier and having the keystone "The Agnostic" in its range results in maximum energy shield being 0, even after manually adding the 'gain 20% of maximum life as extra maximum energy shield', therefore being unable to know the final energy shield value.

There are 2 possible solutions here:

- Implement the replacement of keystones

- Disable the keystone when its in range of the timeless jewel

The best option i think would be disabling the keystone, as someone can just add the modifiers to the jewel itself, but the keystone remaining active would mean needing to manually deallocate it and keeping track of the used point.

**Comment by Wires77** [comment]
#1211 is in the process of implementing the first point.  It's mostly done except for one mod, but if I can't get it to work timely I may release it as-is just to disable the mods for now.
