### ISSUE TITLE
Minion and Poison

### ISSUE THREAD

**Issue by Arkningy** [PathOfBuildingCommunity/PathOfBuilding#1340]
When you link the support gem "Poison" to a minion skill like Herald of Agony, If you go to the "Calcs" tab and check the box to show "Minions stats".
Then in the windows for poison, the row where it's written "Total More" is equal to "-30%" and when you put the mouse on it to get more details it shows 39 increased from the "Poison" support gem which is perfectly normal but below it, it shows "-50%" and it kind of suprised me so I thought it was a bug and let you know about it !

Thanks for your amazing work !

**Comment by ppoelzl** [comment]
Unable to reproduce this issue.
