### ISSUE TITLE
Arrow keys scroll tree by 1px

### ISSUE THREAD

**Issue by Nightblade** [PathOfBuildingCommunity/PathOfBuilding#1341]
**Is your feature request related to a problem? Please describe.**
Since there's no easy way to compare trees, I often have PoB opened twice, and flick between them to spot differences.  However it is difficult to line up the trees with the mouse.

**Describe the solution you'd like**
When the tree has focus, the arrow keys should scroll it 1px.

**Describe alternatives you've considered**
I tried using the arrow keys.  They didn't work.  I was sad.

**Additional context**
n/a  🥧

**Comment by ppoelzl** [comment]
Did you notice how a build retains its skill tree position after you close it? In the build XML file (in your save location), there is a tag like
```xml
<TreeView searchStr="" zoomY="286.10092592593" showHeatMap="false" zoomLevel="3" showStatDifferences="true" zoomX="61.859259259258"/>
```
just after the notes section, where `zoomX` and `zoomY` are the offset from the center of the skill tree.
Setting them to the same value in the builds you want to compare will likely give you better results than manually aligning them.

While it would be nice to allow to reposition the skill tree with the arrow keys, I think this feature is more about providing an alternative way to move around the skill tree than to align it pixel-perfect. Likely the only reason this would be relevant is to line up skill trees with one another, and I think this is better accomplished by editing the offset instead.

Eventually, there will be support for skill tree comparisons, making this obsolete. Based on the niche of this feature request and the proposed solutions, I will close this issue.

**Comment by Nightblade** [comment]
Oh.  Ok.  That can't be done in the console?

**Comment by ppoelzl** [comment]
Maybe. I don't really use the console during development, sorry!
