### ISSUE TITLE
Add support for Shadowstitch

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#1344]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`
Version: 1.4.170.7

Please try to fill in as much of the template below as you're able.

* **What happened?**
Shadowstitch is not included in PoB's unique items database.

* **What steps will reproduce the bug?**
Sarch for "Shadowstitch" in PoB's unique items database.

* **Does it reproduce every time? If not, why so?**
Yes.
* **Additional information:**
Shadowstitch should be automatically generated.
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Nightblade** [comment]
Works ok for me as of 1.4.170.9

**Comment by ppoelzl** [comment]
It is still missing its random implicits.

**Comment by uilman** [comment]
You can manually corrupt for the 2 implicits, it's that same set.

**Comment by ppoelzl** [comment]
On second thought, think manually corrupting it is good enough.
