### ISSUE TITLE
Maxed Out Uniques

### ISSUE THREAD

**Issue by jix91** [PathOfBuildingCommunity/PathOfBuilding#1355]
When theorycrafting I often use uniques from the search menu.
Sadly those uniques are always mid rolled. This is also true for crafting items - when adding a prefix/suffix or crafted mod they are always selected at 50% of their value.
I would like to have the option to set this value to 100%.
Just like in the gem selector where you can put level/quality before adding the gems.

**Comment by ppoelzl** [comment]
This is a very low priority issue. If you would like this to be done anytime soon, you will have to add support for this yourself.
