### ISSUE TITLE
Supreme Ego not working with any Auras

### ISSUE THREAD

**Issue by AmazingKrigor** [PathOfBuildingCommunity/PathOfBuilding#1359]
* **What happened?**
Supreme Ego is only reserving more mana.
Any other effect doesn't work.
For exemple "Aura from your skills have 50% more effect on you" doesn't work

* **What were you trying to do?**
Builds with Supremo Ego as a main Keystone

* **What steps will reproduce the bug?**
There are many ways to show how Supreme Ego doesn't work.
Minions or Totems receive Aura buffs(Like Hatred or Haste) when "Aura from your skills doesn't affect allies" is active.
Commander of Darkness( Necro ascendancy passive, far left) and Scion's Necromancer doesn't give more atk and cast speed with Supreme Ego( "Aura from your skills have 50% more effect on you"),  while they do in game.
Any normal auras and its vaal counterparts (Like Vaal Haste or Vaal Purity of Fire) doesn't give more bonuses, while they do in game, thanks to "Aura from your skills have 50% more effect on you".

* **Does it reproduce every time? If not, why so?**
Yes, It does.

* **Additional information:**
Here is a pastebin where you can do all this tests.
https://pastebin.com/y2m2pt5k

**Comment by Wires77** [comment]
- Minions and totems do not get buffed by auras when you have Supreme Ego, because it explicitly says "Auras from your skills do not affect allies"
- Everything else seems to work, I'm not sure what isn't working for you.  Double strike gets the increased fire damage from Anger, properly going down when unallocating Supreme Ego, loses the attack speed when turning off purity of ice, and also loses the attack speed by unallocating Commander of Darkness

Perhaps you were only testing with summon skeletons?  Otherwise I'm unable to reproduce this issue.

**Comment by AmazingKrigor** [comment]
Fist, turn off all this skills
Now, turn on, Anger, Double strike and Supreme Ego
If you turn On and Off Supreme ego, you will see that there is no change on Double Strike damage output. 
And this is wrong,\ because supreme ego should make double strike damage higher.

Now turn off all skills again.
Turn on Anger and Summon Skeletons.
If you turn on Supreme Ego, you will see that it doesn't change Skeletons dps.
And this is wrong because supreme ego makes aura not work on allies.

**Comment by AmazingKrigor** [comment]
Now with Commander of Darkness is a bit harder to see and probably this template build is not the most optimal to show you.

Make a new character in PoB
First, take Commander of Darkness on a witch.
Take some random spell, like Arc for exemple.
Take some random aura, like clarity for exemple.
Then take Supreme ego.

It should have more cast speed(1.5 more or something round up or down), but it doesn't change.

**Comment by Wires77** [comment]
I think you're using Openarl's version of Path of Building.  Check the lower left corner of your PoB, next to the "Check for Update" button, and it should say "PoB Community Fork".  If this isn't the case, I encourage you to reinstall PoB from the latest release on this repository https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v1.4.170.4

**Comment by AmazingKrigor** [comment]
Problem solved, thank you and sorry for the inconvenience.
