### ISSUE TITLE
No block chance with Emperor's Vigilance equipped

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#1361]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Equipped Emperor's Vigilance, went to Calcs tab, block chance is 0
* **What were you trying to do?**
View my total block chance
* **What steps will reproduce the bug?**
New build > Equip Emperor's Vigilance > observe 0% chance to block attacks (expecting 52% chance with Glancing Blows)
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Regisle** [comment]
It is a little unintuitive but you need to tick this :
![image](https://user-images.githubusercontent.com/49933620/92972352-431c1200-f4c1-11ea-91b0-037fdd3814e4.png)
which shows up when you equip the shield

**Comment by Wires77** [comment]
Oh wow, might I suggest having that ticked by default?  It kind of got lost in the config options (though I did find the override checkbox).  I assume you wouldn't use the shield unless you were confident in your ability to keep up ES, right?
