### ISSUE TITLE
Small request for proxy pastebin imports

### ISSUE THREAD

**Issue by Quasireal** [PathOfBuildingCommunity/PathOfBuilding#1369]
i have a rather small problem with pastebin imports.

For some reason pastebin is banned in my country (i guess in a few others) so i need to use a proxy or open a vpn to import stuff.

if PoB can accept 'pastebinp.com' as a valid url too, it would say me a lot of time doing PoB checks etc

cheers.

**Comment by ppoelzl** [comment]
This isn't something we're interested to support. If you would implement this yourself however, there is a high chance it might make it into PoB. Since there are frequent issues with pastebin.com, we're looking into alternatives for hosting build codes, so stay tuned!
