### ISSUE TITLE
Are you still able to update this after Patch 3.11.2?

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [PathOfBuildingCommunity/PathOfBuilding#1371]
I'm not an "IT guy" so maybe there is some misunderstanding.
GGG completely overhauled data files and structures in patch 3.11.2, rumor says if someone can't crack the new .bunble.bin files, everything like wiki or Poedb.tw or POB can't be updated.
Can you confirm it?

**Comment by Nostrademous** [comment]
The 3rd party tool developers as a group have a handle on what to do and how to handle the new bundle compression and containerization scheme. It is a bunch of work to overhaul the extraction system though so there might be delays in post league tool releases (and that’s assuming GGG doesn’t change it some more as the last patch modified it a bit more).

Part two of this though is a legality and licensing issue. They are using a proprietary compression scheme which they have a license to use (at least that’s assumed). If we were to crack it we could not release it and not be in violation of TOS. Meaning while we would be able to handle it and our system can be adjusted to work with it we would not be able to distribute that portion.

Note - these are my personal thoughts.

**Comment by evrardjp** [comment]
What's the proprietary compression scheme? Is that a new one GGG implemented? Is it something a general purpose library (compatibly licensed with this project) could fix?

**Comment by ParanoiaIsGreat** [comment]
> What's the proprietary compression scheme? Is that a new one GGG implemented? Is it something a general purpose library (compatibly licensed with this project) could fix?

Don't know. But a lot more difficult than before.
https://github.com/PoE-Tool-Dev/ggpk.discussion/wiki/Bundle-scheme

**Comment by Nostrademous** [comment]
They have transitioned to using Oodle compression (specifically Kraken). Here is a link: http://www.radgametools.com/oodle.htm

RAD Game Tools licenses the use of the tools to do the compression/decompression. GGG purchased a license (obviously I don't know this as a fact, but they had to have to be legally allowed to use it).

We have reached out to GGG to start the dialogue of how and if they are willing to help out 3rd-party Tool developers getting around this new compressed file scheme legally. They replied that they would be willing to help us out and now it's just a matter of figuring the best path forward regarding "how" this will be done and obviously GGG developers finding the time to implement their side. This might be delay a bit as they have a league start which is more important as their top priority.

**Comment by Nostrademous** [comment]
Issued Solved.
