### ISSUE TITLE
Missing documentation of tree zip files.

### ISSUE THREAD

**Issue by evrardjp** [PathOfBuildingCommunity/PathOfBuilding#1374]
I consider this as a bug rather than feature request:

docs/rundown.md contains a list of assets, it contains "tree" zip files, but doesn't explain what they do, or how to maintain/update those.
Without this information, external contributors cannot step up and help with maintenance.

Reason I ask: GGG just posted new json files on https://www.pathofexile.com/forum/view-thread/2935826 which contains "tree" information, but I am not sure where to bring that in (https://web.poecdn.com/public/news/2020-09-16/3120_PassiveSkillTree.zip)

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.12.
