### ISSUE TITLE
Dodge chance sources in the calc tab

### ISSUE THREAD

**Issue by ankantan** [PathOfBuildingCommunity/PathOfBuilding#1376]
Currently if you go to the calcs tab and hover over your dodge chance it doesn't show anything, it'd be great to see the sources of dodge.

Something like this.
![Path_of_Building_GLhIyMdFGb](https://user-images.githubusercontent.com/10431543/93342980-7a6f2380-f81f-11ea-812f-139b31d3bb88.png)

**Comment by Wires77** [comment]
Shows for me 
![image](https://user-images.githubusercontent.com/1209372/93345066-066d5500-f7f8-11ea-9049-7bd28b8d5c5c.png)

**Comment by ppoelzl** [comment]
Could not reproduce.
