### ISSUE TITLE
On a high number of jewels you cannot see what to change them

### ISSUE THREAD

**Issue by shagour18** [PathOfBuildingCommunity/PathOfBuilding#1377]
Depending on the POB window size, the jewel's image with the location overlaps the drop-down.
In my tests and in the screenshots below, on 1920x1080 it starts happening on 15th jewel.

 
![image](https://user-images.githubusercontent.com/59347745/93344908-e6ab5080-f83a-11ea-9525-1cbdf6d9c27c.png)

![image](https://user-images.githubusercontent.com/59347745/93345119-22461a80-f83b-11ea-8f81-3bdf1e314b96.png)

**Comment by Wires77** [comment]
As a workaround, you can still hover over the jewels list in the background to see the stats, but I can take a look at this

**Comment by shagour18** [comment]
> As a workaround, you can still hover over the jewels list in the background to see the stats, but I can take a look at this
> 
> Also, it very much depends on your screen size

You're right about the screen size, i'll edit the issue with it.
