### ISSUE TITLE
Suggestion: the ability to ignore nodes when calculating "top node" power on the tree

### ISSUE THREAD

**Issue by timeshifter** [PathOfBuildingCommunity/PathOfBuilding#1381]
Sometimes the top node is something that I'm simply not going to take, but there's no way to easily see what's the next best option. A keystroke or some way to remove a node from consideration would be quite nice.

**Comment by Wires77** [comment]
We have a plan to make a list of nodes for this exact scenario.

**Comment by timeshifter** [comment]
Beautiful, great to hear. Keep up the good work!

**Comment by ppoelzl** [comment]
Update 1.4.170.12 added a power report that allows you to rank all nodes.
