### ISSUE TITLE
Program is cut off on all sites / interface incorrectly sized

### ISSUE THREAD

**Issue by Marmeladenbrot** [PathOfBuildingCommunity/PathOfBuilding#1384]
* **What happened?**
PoB starts with window where elements are cut off on each side
Mouse cursor position is also off, buttons only clickable if you go under the button by ~10-20 pixels.

* **What were you trying to do?**
Normal usage of PoB

* **What steps will reproduce the bug?**
Starting the program

* **Does it reproduce every time? If not, why so?**
Reproducible

* **Additional information:**
Windows 10 x64 Professional 1903
Intel(R) HD Graphics 620
Dual Monitor Setup, both are set to 1920x1080 (default resolution)

Screenshot: 
![PoB_screen_cutoff](https://user-images.githubusercontent.com/9965585/93453437-f9c12d80-f8d9-11ea-885a-0d21c1d702d9.png)

**Comment by moonlightdrive** [comment]
Is your graphics driver up to date? I have had the same issue with this card & resolved by upgrading it.

**Comment by ppoelzl** [comment]
This does not seem to be a problem with PoB itself.

**Comment by tobsecret** [comment]
I'm having the same exact issue on my windows 7 laptop. Doesn't matter if I'm on an external monitor or the built-in monitor.

**Comment by tobsecret** [comment]
This is what it looks like when I run it with the "Run in 256 Colors" modifier:
![image](https://user-images.githubusercontent.com/10303623/103380460-f0d61f80-4ab6-11eb-9435-d8b82bd4494d.png)
It looks like this way the interface proportions are correctly loaded, albeit the colors being completely unusable.

**Comment by tobsecret** [comment]
Here are also some interesting things from the console on program start, maybe those are helpful for deciphering what's breaking:
```
Executing SimpleGraphic v1.0 x86 Release, built Dec    7   2017

Executing SimpleGraphic/SimpleGraphic.cfg
Warning: config file not found
Executing SimpleGraphic/SimpleGraphicsAuto.cfg
Warning: config file not found

[...]
Pixel format: need 32,24,0, using 32,24,8
```
![image](https://user-images.githubusercontent.com/10303623/103380951-570f7200-4ab8-11eb-857a-eaa190c46635.png)

**Comment by tobsecret** [comment]
@moonlightdrive which driver update did you do, do you remember? I went to the intel website, and updated whatever drivers were available, but to no avail.

**Comment by tobsecret** [comment]
Found a fix for my machine - it was indeed updating the drivers, but since I have a Lenovo machine and they apparently roll their own drivers, I had to go to their homepage, search for my machine, and have their update utility update my drivers instead of going to Intel, who made the actual graphics hardware.
