### ISSUE TITLE
Supreme Ego node power based on all active auras

### ISSUE THREAD

**Issue by CanoLathra** [PathOfBuildingCommunity/PathOfBuilding#1385]
**Is your feature request related to a problem? Please describe.**
Supreme Ego keystone calculates its node power based on all active auras in the skills section, rather than just one, even though it would limit the character to just one. Allocating it does not prevent having any number of permanent auras active in skills. Calculations are done with all active auras getting a 50% bonus simultaneously.

On a side note, nodes that increase mana reservation, including Supreme Ego, do not take reducing total mana below zero into account for their node power calculations, either. 

**Describe the solution you'd like**
Supreme Ego's node power should be calculated with the strongest active permanent aura (based on node power filter) in the players skills, with all other active permanent auras disabled. Allocating Supreme Ego with more than one permanent aura active in skills should disable all permanent auras and only allow one to be actived at a time, or at least provide a warning to the user.

For the mana reservation issue, the ability to have a 'possible' checkbox alongside 'top node' and 'power per point' that would force the calculations to take such things into account, much like the 'currently usable' option under 'any requirements' on the items screen, would be greatly appreciated.

**Comment by LocalIdentity** [comment]
Supreme Ego has changed an no longer works like this
