### ISSUE TITLE
Convert all trees to updated version

### ISSUE THREAD

**Issue by zombodotcom** [PathOfBuildingCommunity/PathOfBuilding#1392]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/13477955/93555419-19387480-f933-11ea-953f-51bed1557054.png)
I have to individually click each tree to convert them.

**Describe the solution you'd like**
please add button to ui to convert all trees to updated in batch format. 

**Describe alternatives you've considered**
batch convert?

**Additional context**

**Comment by deathbeam** [comment]
It would also be nice to have option to automatically delete th original trees after converting them
