### ISSUE TITLE
Skeletons Archer bugs

### ISSUE THREAD

**Issue by Malefactory** [PathOfBuildingCommunity/PathOfBuilding#1397]
I know summon skeletons gem is currently unable to take advantage of the new archer quality effect in PoB fork, so I've been trying to use the skeleton archers in vaal summon skeleton and then just running skills to prevent them from missing so I don't actually have to account for vaal skill's "cannot be evaded" modifier. That said, skeleton archers are unable to be selected in the current build; when I click the box, it just defaults to regular skeleton minions, though skeleton mage does work as normal. Additionally, skeletons do not gain the impale damage bonus from master of metal correct, which is to say, at all.

Sorry for a long bug report, and I know you're probably swamped. I'm thinking about contributing to coding sometime before next league after I finish up my classes.

**Comment by Wires77** [comment]
Will be fixed by #2147
