### ISSUE TITLE
Add an "Effective HP" setting for node power display

### ISSUE THREAD

**Issue by worldendDominator** [PathOfBuildingCommunity/PathOfBuilding#140]
Although node power display has settings for life, ES and mana, finding the best survivability nodes is still a bit difficult for hybrid builds and MoM users. I suggest adding a setting for effective HP.

**Comment by ppoelzl** [comment]
I think you mean combined HP, as the effective HP would be dependent on the damage source.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
