### ISSUE TITLE
1.4.170.8 -> 1.4.170.10, reduced Mana Reservation of Herald Skills has no effect

### ISSUE THREAD

**Issue by dhelmrich** [PathOfBuildingCommunity/PathOfBuilding#1402]
After the Update from version 1.4.170.8 to 1.4.170.10, all nodes that include "Reduced Mana Reservation of Herald Skills" have no effect anymore.
I updated the PoB to the latest version and encountered this effect.
My pastebin is https://pastebin.com/bgviYWvf
In this image, you can see that the effect is also not shown when hovering over a node and is also not factored in the calculation:
![image](https://user-images.githubusercontent.com/9272590/93663937-8a7b4300-fa6b-11ea-97ef-49cbdf67cf09.png)

The Conquerors Efficiency works and Reduced Mana nodes all work.

I tried restarting the application (ha) and it persists. I have unallocated and reallocated the nodes in case the calcs needed update.

Thanks for your hard work you guys are great!

**Comment by LocalIdentity** [comment]
This has been fixed in the update I just pushed out
