### ISSUE TITLE
Intensity default cap incorrect

### ISSUE THREAD

**Issue by QualityVan** [PathOfBuildingCommunity/PathOfBuilding#1407]
With Heist's launch, Intensity was changed to have a base cap of 3 instead of 4, along with increased scaling per stage. However, PoB's default cap for Intensity is still 4. 

I'm not super familiar with the codebase but this should be a one line fix at https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/Export/Skills/sup_int.txt#L361

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
