### ISSUE TITLE
[Minor] Life leech support Alt Qual 2 does not correctly affect maximum recovery per life leech

### ISSUE THREAD

**Issue by the42paradigm** [PathOfBuildingCommunity/PathOfBuilding#1410]
Life leech alt qual 2 gives 5% increased 'maximum recovery per life leech' per 1% quality.
Testing without gem shows that PoB leech calculations (with sufficient damage and leech %) correctly use the base max recovery of life leech (should see that 'average instances' = 5 x hits per second).
Other sources of 'maximum recovery per life leech' mods (such as scion slayer, offering of the serpent) correctly affect the number of reported average instances (i.e. you see average instances = 2.5 x hits per second).
Life leech support alt qual 2 however does not affect this number at all yet.

Sidenote: The Highwayman new unique ring has a line 'Total recovery per second from life leech is doubled'. This is not yet functionally parsed in PoB. I believe it should work the same way as vaal pact, essentially just multiplying all your raw leech by 2, so is equivalent to '100% more life leeched per second' (which is parsed correctly).

**Comment by Nostrademous** [comment]
Will be fixed next patch... ty.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.10.
