### ISSUE TITLE
Alternate Qualities are not calculated

### ISSUE THREAD

**Issue by Sanatorius** [PathOfBuildingCommunity/PathOfBuilding#1411]
Hi, i tried several Gems and none of the alternate Qualities are calculated to the stats of the Character. For Example take Discipline alternate Quality 1 should give 10 more damage if i'm on full ES, but it does not. 

But great work so far. It looks like alternate Quality Gems do have another name or the Quality is called by a special Name, maybe u can change this too. 1. Anomalous, 2. Divergent, 3. Phantasmal. They're called this on Poe.trade and it looks like the gem is also called this.

**Comment by ppoelzl** [comment]
Should both be fixed as of 1.4.170.12. If not, please let us know and I'll reopen this issue.
