### ISSUE TITLE
Predator Support rename [previously Deathmark] lost "marked by deathmark" skill option in Calculations

### ISSUE THREAD

**Issue by tgavankar** [PathOfBuildingCommunity/PathOfBuilding#1412]
v1.4.170.11

Previously, Deathmark support would give an option on the Calculations screen that would enable the extra DPS when an enemy is deathmarked. When renaming to Predator Support, this option seems to have disappeared altogether.

Example build: https://pastebin.com/jZMmuS7p

**Comment by wjdeclan** [comment]
Fixed here:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1433

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.12.
