### ISSUE TITLE
Effects of "Curse Aura Skills" not working at all on tree or jewels

### ISSUE THREAD

**Issue by Yunojelly** [PathOfBuildingCommunity/PathOfBuilding#1419]
None of the notables within the tree that has **Reduced Mana Reservation for Curse Aura Skills** are working.
This goes for all the medium cluster jewels too with the Notable "**Forbidden Words**"
Increases to Curse Effect aren't applied and Area of Effect doesn't work either.

Seems to be something globally wrong with "Curses" on tree and jewels within POB.

Kindest Regards.

**Comment by ppoelzl** [comment]
Fixed by #1558

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
