### ISSUE TITLE
Intensity on Crackling lance + Intensity Node Dmg Calculation

### ISSUE THREAD

**Issue by breennoliveira** [PathOfBuildingCommunity/PathOfBuilding#1425]
If you have Crackling Lance as your main skill and the Intensity Passive Node allocated, and you go to the configuration tab to select the # of Intensity you have, you're limited to 3 (You can put it to 4 but it does nothing to the damage calculation) even though you have a maximum of 4 intensity.

**Comment by PJacek** [comment]
Duplicate of #1407
