### ISSUE TITLE
Assassin's Mark problem.

### ISSUE THREAD

**Issue by BardsTale** [PathOfBuildingCommunity/PathOfBuilding#1426]
Effect "Hits against Cursed Enemies have +(30–49)% to Critical Strike Multiplier" is not working.

**Comment by wjdeclan** [comment]
Fixed here:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1436

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
