### ISSUE TITLE
Cannot save builds

### ISSUE THREAD

**Issue by xephuss** [PathOfBuildingCommunity/PathOfBuilding#1428]
Everytime I open community fork or when I close a build I get this error. Tried deleting everything and reinstalling still not working!
![error](https://user-images.githubusercontent.com/61663039/93780701-1917cd80-fbee-11ea-8dba-68fc08f793f1.PNG)

**Comment by ppoelzl** [comment]
Please post the build you are trying to open.

**Comment by xephuss** [comment]
It isn't a specific build. If I import my char it wont let me save. If exit the build I am shown the above error. If I import I can use temporarily but cannot save.

**Comment by ppoelzl** [comment]
This doesn't seem like something someone is able to reproduce then. Sorry!

**Comment by Nostrademous** [comment]
if you "import" you have a pastebin or raw import data you can share. We need to be able to reproduce to fix.

**Comment by xephuss** [comment]
The name may be misleading. It isn't an issue with any specific build. I can literally click new, then save and get the error. I had it fixed for a little while but then started doing it again. I have been trying to find where I found the fix, it had something to do with deleting a file or directory which then forces PoB to redownload it or something.

**Comment by xephuss** [comment]
So i figured it out. The old path of building settings.xml and builds didnt delete and it was trying to access those. I went in and deleted with administrator and no more error. Just a multiple installation issue!
