### ISSUE TITLE
Vitality not applying to life regen

### ISSUE THREAD

**Issue by GamerKilroy** [PathOfBuildingCommunity/PathOfBuilding#1429]
It seems that vitality has been changed for 3.12 but is not applying the buff to life regen.
Attached is a screenshot, you can see i'm using Vitality on the left, but when i check calculations for my life regeneration, Vitality is not applied.

EDIT: I've noticed that Vitality is not in the "Aura and Buffs skills" on the top of the calcs screen, but it is marked as Active in the skill list.

![image](https://user-images.githubusercontent.com/57183884/93790702-a2052800-fc33-11ea-9847-c9643cebc1f2.png)
![image](https://user-images.githubusercontent.com/57183884/93790629-8c8ffe00-fc33-11ea-85fb-32425064229c.png)

**Comment by wjdeclan** [comment]
Fixed here:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1432

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
