### ISSUE TITLE
Make node power easier to see

### ISSUE THREAD

**Issue by lxsli** [PathOfBuildingCommunity/PathOfBuilding#1430]
The node power mode is super useful but I find it extremely hard to tell which nodes are most powerful, they basically all just look red to me (average hit mode).

I propose adding a threshold to the bottom bar, so only nodes offering >X power are shown. I could tweak this until I have a reasonable set of alternatives to consider. EG I can see Doom Cast offers +2.5% / point for me, so I could set it to 2.4% and see if there's anything better. A hotkey to do that ("Search for better") could be nice but that's feature creep :)

An alternative/addition would be to use a wider colour range, EG red-blue-green. This would still pose a problem for colour-blind users and doesn't help to differentiate very close values.

The "Show top node" option may be trying to tackle the same issue, but for me, it just shows Supreme Ego which is 11 points away and would disable two of my defensive auras. Not too helpful.

**Comment by Quotae** [comment]
The node power highlighting only changes the brightness of the nodes to indicate relative strength. A brighter red means a stronger node. This image has 3 different strengths (the notable is the strongest, the travel node is the weakest):

![image](https://user-images.githubusercontent.com/39030429/94378243-990dce00-00ed-11eb-8147-ebc4a859df78.png)

It might be difficult to see for some people, but changing it to be different colors would create other problems, like you said. Maybe now that you know that it's *supposed* to all be the same color, you can see the difference more easily?

**Comment by lxsli** [comment]
Now I know it's meant to only be three colours, I can see those. I had expected smooth variation. The real issue here is that I want to be able to see more easily which nodes are most powerful, hence the threshold idea. Seeing 20 bright red nodes and having to mouse over each one to see which is actually best is a suboptimal user experience. Changing colours was only an "alternative suggestion" as per the issue form.

**Comment by ppoelzl** [comment]
@lxsli Check out the new "Power Report" feature added in 1.4.170.12. It ranks all nodes in a list. I believe this is what you are looking for.
