### ISSUE TITLE
Greater Multiple Projectiles default quality is missing attack speed bonus

### ISSUE THREAD

**Issue by McFrugal** [PathOfBuildingCommunity/PathOfBuilding#1431]
Setting the quality to 20 results in 10% inc cast speed, but not the 10% inc attack speed.  It has both!

**Comment by McFrugal** [comment]
The alternate 1 is missing the mana cost reduction as well.  I wonder if other gem qualities with multiple effects have the first effect missing?

**Comment by Nostrademous** [comment]
Fixed in next patch.
