### ISSUE TITLE
Lightning Tendrils does not factor in stronger pulse into damage

### ISSUE THREAD

**Issue by kcwoodwa** [PathOfBuildingCommunity/PathOfBuilding#1434]
As far as I can tell, the stronger pulse is never factored into the base damage. It could just be the added damage listed on the gem is the average of the 4 pulses, but I'm not sure.

**Comment by Wires77** [comment]
In the next update it'll have the strong pulse as a separate skill part you can select to see that damage.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.12.
