### ISSUE TITLE
Fat error after lauching app

### ISSUE THREAD

**Issue by Seb-Dupuis** [PathOfBuildingCommunity/PathOfBuilding#1437]
Hey ! 

I have a problem with pobc, when I start this, I get a lot of error messages.

I put you a link to a screenshot https://www.casimages.com/i/200921113327336512.png.htm

**Comment by Wires77** [comment]
Can you try this solution? https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1428#issuecomment-696196166

**Comment by Seb-Dupuis** [comment]
I had already tried, but to no avail. 

However, the solution gave me the idea to change the folder to save the path and it worked! 

Thank you for your answer at this time
