### ISSUE TITLE
"Do you have Onslaught?" has no effect on character sheet

### ISSUE THREAD

**Issue by Akkuma** [PathOfBuildingCommunity/PathOfBuilding#1443]
* **What happened?**
Clicked `Do you have Onslaught?` and saw no Attack Rate or DPS changes

* **What were you trying to do?**
Add onslaught to damage calculations

* **What steps will reproduce the bug?**
Click on & off and see no change

* **Does it reproduce every time? If not, why so?**
It does as far as I can tell

* **Additional information:**
https://www.pathofexile.com/passive-skill-tree/3.12.0/AAAABAIBAFb6fXUUdS9y98_QrZzH73p08apY6dp6hAOHEjCbje2DSQ_XLdhgOu35sQBegUHBiwxzLIVaGkHQFyZrkBjbGO_-uhmO034tnhLxd9ctTQHRCC6v6-4OpMKVZjXvIWBWySQu_kU=

**Comment by PJacek** [comment]
Onslaught can be enabled automatically in some conditions like using Silver Flask or Omeyocan. Check your Combat Buffs in the Calcs tab to see if it's present.
If you still experience this problem, provide us with complete build from the "Import/Export Build" tab.

**Comment by Akkuma** [comment]
Looks like that is what is happening, being enabled automatically.
