### ISSUE TITLE
Add full support for Replica Shroud of the Lightless

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#1445]
**Is your feature request related to a problem? Please describe.**
Replica Shroud of the Lightless only has two abyss sockets when it should have 6.

**Describe the solution you'd like**
Additional drop-downs for more than two abyss jewels when Replica Shroud of the Lightless is equipped.

**Comment by uilman** [comment]
Already fixed for next release

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
