### ISSUE TITLE
Archmage alternate quality 1 (Anamalous) doesn't add cold damage with quality.

### ISSUE THREAD

**Issue by jimmytrowbridge** [PathOfBuildingCommunity/PathOfBuilding#1447]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
  I was pulling down my character and it seemed unable to parse out my main skill at all.  (separate bug).  After manually setting it up I noticed when I added quality to my Anamalous archmage skill i was losing a lot of DPS.  When looking at the calcs section and also the item text, there is no cold damage being calculate or mentioned.

* **What were you trying to do?**
See dps numbers with my alt quality archmage and see how much damage i was losing by using lightning pen vs ele pen

* **What steps will reproduce the bug?**
Link any skill with archmage Alternate Quality 1 and increase the quality of the gem.  You should see cold damage be added to the calc but you do not.

You could also pull down my character: https://pastebin.com/3gdwY5YU
Main skill is shock nova.

* **Does it reproduce every time? If not, why so?**
yes

* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
