### ISSUE TITLE
Cant get latest version working

### ISSUE THREAD

**Issue by DsyncXO** [PathOfBuildingCommunity/PathOfBuilding#1449]
This is probably the most simplest thing in the world, but no matter what ever version I install of POB, i can not input the builds that i am copying please assist
![image](https://user-images.githubusercontent.com/57353855/94060641-2db9b880-fddc-11ea-95b9-745f974f145b.png)

**Comment by Wires77** [comment]
Can you link the build you're trying to copy?  Also from the file path it looks like you might be trying to launch PoB without extracting the files somewhere first.  If you're installing from the ZIP file, extract the whole folder before trying to run it.

**Comment by DsyncXO** [comment]
@Wires77 https://pastebin.com/WdR4d6Rd this is the paste im using from Zizaren, i even saw his video for POB Fork done that, extracted all folders still same error code, aint played in years so my brain is fried with all this shiz :/

**Comment by DsyncXO** [comment]
@Wires77 i got it working cheers anyway

**Comment by Wires77** [comment]
I'm glad you got it, I was just responding to see if you need to delete the settings file or something.  What was the issue so if other users have this problem we can have them try your solution?
