### ISSUE TITLE
Awakened Gems with two Quality bonuses missing original quality bonus

### ISSUE THREAD

**Issue by Mugsy13ms** [PathOfBuildingCommunity/PathOfBuilding#1451]
Awakened gems that have the original gem's quality bonus along with a second quality bonus exclusive to the awakened version are missing the original gem's quality bonus. I verified in the calculations for a few that the bonus is missing from the calculations.

ex. Awakened Burning damage quality gives the fire damage over time bonus but not the increased burning damage. Awakened Chain quality gives increased attack/cast speed but not projectile speed.

I checked this with other gems and put a list of awakened gems I confirmed the issue with below. If there are any other awakened gems which have both the original gem quality bonus as well as a new quality bonus it may apply to them as well. Notably Awakened Multistrike does NOT have this issue and looks to be correct. Maybe this bug was found and fixed already for Multistrike but not the others?

Awakened Ancestral Call
Awakened Blasphemy
Awakened Brutality
Awakened Burning Damage
Awakened Chain Support
Awakened Controlled Destruction
Awakened Deadly Ailments
Awakened Generosity
Awakened Hextouch
Awakened Melee Physical Damage
Awakened Spell Echo
Awakened Swift Afflictions
Awakened Unbound Ailments

v1.4.170.11

**Comment by uilman** [comment]
Already fixed in next release.

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
