### ISSUE TITLE
Earthquake and Earthshatter dont work while unarmed.

### ISSUE THREAD

**Issue by GornaGM** [PathOfBuildingCommunity/PathOfBuilding#1452]
As title says, the skills are disabled since because "no useable weapon is equipped", but ingame they are usable as unarmed.

**Comment by GornaGM** [comment]
Also Ice crash doesnt work

**Comment by Wires77** [comment]
Sounds like you're using the original Path of Building, which doesn't have all the features this one has.  Please download and install the version here instead: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v1.4.170.8
