### ISSUE TITLE
The Hidden Blade Ambusher item inclusion

### ISSUE THREAD

**Issue by KuroNecron** [PathOfBuildingCommunity/PathOfBuilding#1454]
**Is your feature request related to a problem? Please describe.**
The item The Hidden Blade Ambusher ([wiki link](https://pathofexile.gamepedia.com/The_Hidden_Blade); [poedb link](https://poedb.tw/us/The_Hidden_Blade)) and its included skill Unseen Strike are missing from PoB.

**Describe the solution you'd like**
Inclusion of the dagger and the skill for calculation and building purposes.

**Describe alternatives you've considered**
None really, couldn't think of any.

**Additional context**
None i can think of right now.

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
