### ISSUE TITLE
Crown of the Tyrant acts as an aura for Supreme Ego

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#1457]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Added Crown of the Tyrant to my Supreme Ego build, noticed the wrong added damage numbers (50% more damage)
* **What were you trying to do?**

* **What steps will reproduce the bug?**
Allocate supreme ego, equip crown of the tyrant
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
https://pastebin.com/RFWuuiKj

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
