### ISSUE TITLE
Remove outdated passive trees

### ISSUE THREAD

**Issue by dovry** [PathOfBuildingCommunity/PathOfBuilding#1467]
Old, irrelevant skilltrees are being loaded into the client on launch, which is easily half of the loading time, at least for me.

**Describe the solution you'd like**
Remove any tree older than $current_league -1 (so 3.12 and 3.11 at the time of writing)

**Describe alternatives you've considered**
Disable the trees in options?

**Additional context**
![image](https://user-images.githubusercontent.com/15201298/94293746-0f2ffa80-ff5f-11ea-8786-b175561783a7.png)
The application is ready (save for loading the current tree) after 0.3-0.4 seconds, why add 3 more seconds loading dead content?

**Comment by ppoelzl** [comment]
These skill trees are needed to upgrade from old ones. Also, not everyone updates all their builds every league.
