### ISSUE TITLE
Item Compare Overlay

### ISSUE THREAD

**Issue by cjmanca** [PathOfBuildingCommunity/PathOfBuilding#1479]
Since we all know that PoB is more accurate for character stats, I'd love to see a game overlay which lets you compare items you pick up using PoB. 

The idea is, you'd keep PoB updated with your current character, and then use a hotkey while hovering over an item in your inventory and get a window showing stat changes, and possibly an overall rating of how much better an item is (possibly split into offensive and defensive change, similar to Diablo 3 comparisons).

I apologize if this has been asked before, but I did a couple of searches and didn't see anything. May have searched with the wrong terms though.

**Comment by Regisle** [comment]
You can copy the item into PoB (game has function to copy item to clipboard same as trade site, PoB can handle items copied that way) which mostly does what your asking, doubtful PoB itself will ever support the exact thing your asking for but shouldnt be hard to make an ahk script to auto paste it into PoB if you copy somthing

**Comment by cjmanca** [comment]
Yeah, but that requires several extra steps and swapping out of game. An overlay/hotkey would make this whole process much faster/easier as a nice QoL. It could even use the same comparison that already exists in the items tab, just in an overlay based off of the item you're hovering on.

**Comment by coldino** [comment]
*Self-promotion alert*.
Check out an AHK script a couple of us put together that does this: https://github.com/VolatilePulse/PoB-Item-Tester

It runs PoB without its UI and loads your build, so should do exactly what you want.

**Comment by ppoelzl** [comment]
As @Regisle said, what you are asking here is unfortunately quite out-of-scope for PoB. While I haven't tested it myself and therefore cannot endorse it, it seems like PoB-Item-Tester offers all the funcionality you seek.
