### ISSUE TITLE
Make player's curse limit configurable

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#148]
So that you could easily test them together w/o jumping through hops. Thanks in advance.

**Comment by arne-z** [comment]
As a workaround, you can always put the mod "You can apply an additional Curse" on any of your items to enable an extra curse. This even works multiple times on the same item, like with this one:
```
Onyx Amulet
Quality: 0
LevelReq: 20
Implicits: 0
You can apply an additional Curse
You can apply an additional Curse
You can apply an additional Curse
```

(I know, this is likely exactly the kind of hoop you want to avoid jumping through, but maybe it helps.)

**Comment by pHiney** [comment]
> 
> 
> So that you could easily test them together w/o jumping through hops. Thanks in advance.

What is it that is happening, that the default mechanics is not taking into account ?
