### ISSUE TITLE
Display curse effect broken and how to fix

### ISSUE THREAD

**Issue by kokanas** [PathOfBuildingCommunity/PathOfBuilding#1480]
Here's how it looks like now:
![image](https://user-images.githubusercontent.com/7354849/94338835-ac3d7280-fff5-11ea-8b4f-cd590d3e3a09.png)
Change "Curse" in first line to "Hex"
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/2112a8b806fe8b9626221ed1fba3f443ea6e9b80/Modules/CalcOffence-3_0.lua#L561
```
	if activeSkill.skillTypes[SkillType.Curse] then
		output.CurseEffectMod = calcLib.mod(skillModList, skillCfg, "CurseEffect")
		if breakdown then
			breakdown.CurseEffectMod = breakdown.mod(skillModList, skillCfg, "CurseEffect")
		end
	end
```
TO:
```
	if activeSkill.skillTypes[SkillType.Hex] then
		output.CurseEffectMod = calcLib.mod(skillModList, skillCfg, "CurseEffect")
		if breakdown then
			breakdown.CurseEffectMod = breakdown.mod(skillModList, skillCfg, "CurseEffect")
		end
	end
```
after fix:
![image](https://user-images.githubusercontent.com/7354849/94338921-6af99280-fff6-11ea-83bb-cfb6ec86d915.png)

**Comment by Quotae** [comment]
Fixed in 1.4.170.12
