### ISSUE TITLE
Linux release pleasem Deb/PPA

### ISSUE THREAD

**Issue by BloodyIron** [PathOfBuildingCommunity/PathOfBuilding#1484]
Can we please get Linux builds of Path of Building? It would really be great to have a deb package, or maybe PPA/repo to get this tool from. People already use it on Linux, would be nice to have it native instead of having to run through WINE, etc.

Any chance we can get this at some point, please? :)

**Comment by ppoelzl** [comment]
I appreciate that you like PoB this much, but I don't think we will package it for Linux distros anytime soon.
* Path of Building.exe is not open source and so far there is no one capable and interested in reimplementing it
* No one of our community seems to use Linux as a daily driver and have any interest in porting to it
* No one of our community desires to create and maintain Linux packages
The current solution through WINE seems to work for most if not all users and doesn't require any additional effort on our side.
The best we can promise are best efforts to remain compatible through WINE, without any specific endorsement or support.
If you'd like to create and maintain Linux builds yourself, please get in touch with us.

**Comment by BloodyIron** [comment]
Ahh I thought the whole package was open source, my mistake! Kind of a bummer the core code is closed source, I can see how that would be a roadblock. :(
