### ISSUE TITLE
Ignite with chaos damage from Replica Volkuur's Guidance is not supported yet

### ISSUE THREAD

**Issue by wolfie-poe** [PathOfBuildingCommunity/PathOfBuilding#1485]
* **What happened?**
Ignite with chaos damage from Replica Volkuur's Guidance does not show up.

* **What were you trying to do?**
Equip Replica Volkuur's Guidance ("Your chaos damage can ignite") to gain ignite from chaos damage.

* **What steps will reproduce the bug?**
- Open this PoB link: https://pastebin.com/3HfaA0kF
- Select Scourge Arrow/Thorn Arrows as main skill -> ignite not shown.

* **Does it reproduce every time? If not, why so?**
Yes

* **Additional information:**
![Screenshot (285)](https://user-images.githubusercontent.com/64553042/94353628-e11ee900-0038-11eb-87c3-9571615865b0.png)

**Comment by Quotae** [comment]
Fixed in 1.4.170.12:
![image](https://user-images.githubusercontent.com/39030429/94378849-19363280-00f2-11eb-85fc-412e406a104f.png)
