### ISSUE TITLE
Supreme Ego increases the mana reservation of Herald skills

### ISSUE THREAD

**Issue by wolfie-poe** [PathOfBuildingCommunity/PathOfBuilding#1487]
* **What happened?**
Supreme Ego keystone increases the Herald reservation. According to poe wiki, [Supreme Ego](https://pathofexile.gamepedia.com/Supreme_Ego) only affects the [aura](https://pathofexile.gamepedia.com/Aura#Aura_Skills). Note: the aura page is linked directly from the Supreme Ego wiki page.

* **What were you trying to do?**
Enable Supreme Ego. Activated aura: Malevolence. Activated Heralds: Herald of Agony, Herald of Thunder.

* **What steps will reproduce the bug?**
Have the aura/herald setup as described above.

* **Does it reproduce every time? If not, why so?**
Yes.

* **Additional information:**

**Comment by PJacek** [comment]
Supreme Ego increases Herald reservation in-game

**Comment by wolfie-poe** [comment]
Oh right. How silly am I to only rely on the wiki without testing in game. Thanks for the reply.

**Comment by Wires77** [comment]
The wiki doesn't say it only increases the mana reservation of your aura.  "increases your mana reservation amount" doesn't specify just auras.
