### ISSUE TITLE
nvoglv32.dll

### ISSUE THREAD

**Issue by Andestyle** [PathOfBuildingCommunity/PathOfBuilding#1488]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** Whenever I opened PoB I got an issue regarding a Nvoglv32.dll. Which saying the following; "nvoglv32.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vender for support."

* **What were you trying to do?** Use PoB as I normally would.
* **What steps will reproduce the bug?** No idea, occurs everytime I open pob
* **Does it reproduce every time? If not, why so?** Yes
* **Additional information:**
![Screenshot_1](https://user-images.githubusercontent.com/45201448/94364743-dd887200-00cb-11eb-88e9-19c7c27a0d81.png)
https://gyazo.com/a46462bc61da5b705b72dcf2ab22c33f
Attaching 2 screenshots, in case one of them doesn't work.

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by ppoelzl** [comment]
This does not seem to be a problem with PoB, but your graphics driver. We cannot offer you any help for such issues. Sorry!
