### ISSUE TITLE
Is the enemy Hindered?

### ISSUE THREAD

**Issue by xtertristl** [PathOfBuildingCommunity/PathOfBuilding#1489]
Hello I'm not seeing the is the enemy hindered? checkbox in the configuration menu. I have wither and blight in my build but it's missing. When I import someone else's build I can see it in the menu between maimed and blinded but I can never see it in mine.

https://imgur.com/a/ceMPsoL

**Comment by Quotae** [comment]
This is working correctly. PoB doesn't care about the enemy's movement speed, which is the only thing Hinder does by default. The checkbox will show up if you have a mod that cares about whether the enemy is Hindered or not, such as Singularity's mod "x% increased Damage with Hits and Ailments against Hindered Enemies", or the Touch of Cruelty cluster jewel notable's mod "Enemies Hindered by you take 10% increased Chaos Damage".
