### ISSUE TITLE
Anointing notables that are under Timeless Jewels loses the bonuses gained.

### ISSUE THREAD

**Issue by Kroohpyyh** [PathOfBuildingCommunity/PathOfBuilding#1492]
PoB Community Fork
Version: 1.4.170.12

Explanation of what is happening:
Timeless Jewel Glorious Vanity with Doryani.
I have anointed Melding on my amulet. I use pure cold Glacial Cascade.
I've set Melding to be "Revitalizing Frost" (cold dmg leeched as life) from Timeless jewel. I normally have cold leech from my regular amulet.

What is wrong:
The cold leech does not function when said "Revitalizing Frost" is anointed. At least it does not show up on calcs tab's leech rate breakdown when you hover over it. It starts to function if I manually path to "Melding" while it is not anointed. Pathing manually to it when its anointed at same time also fails to provide stats.

100% reproduceable on my end.

From the jewel I've also set Arcane Visions to be Flesh Worshipper, it is functioning correctly as its manually pathed into.

I've added test amulets with just anointment and without anointment in the provided pastebin. The amulets provided in pastebin:
1. Wrath Clasp, Amber amulet = my normal ammy
2. Blank test amulet with anointment
3. Blank test amulet without anointment

Pastebin: https://pastebin.com/dnzF2Mk3
ps: setting Melding to Revitalizing Frost did break when LocalIdentity imported pastebin on his stream. So it might require to be set again.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.13.
