### ISSUE TITLE
Primordial Harmony Stat text changed and broke the Golem Skill CD calculations

### ISSUE THREAD

**Issue by Soggs** [PathOfBuildingCommunity/PathOfBuilding#1493]
The first two stats on Primoridal Harmony have been changed from:
>Golem Skills have 30% increased Cooldown Recovery **Speed**
>Golems have 31% increased Cooldown Recovery **Speed**

to

>Golem Skills have 30% increased Cooldown Recovery **Rate**
>**Summoned** Golems have 31% increased Cooldown Recovery **Rate**

Breaking the calculation of the second stat since I guess the parser does not recognize it anymore.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
