### ISSUE TITLE
New Power Report button cut off on 16:10 resolution

### ISSUE THREAD

**Issue by Volatar** [PathOfBuildingCommunity/PathOfBuilding#1494]
The new power report button is cut off on 16:10 resolution monitors such as my side monitors (1680x1050)

Screenshot: 
![image](https://user-images.githubusercontent.com/1719182/94372855-2a217c80-00cf-11eb-88ff-12d15e8936ec.png)

I suggest reducing the size of the search box until it has input in it.

**Comment by Wires77** [comment]
Fixed by #1496

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.13.
