### ISSUE TITLE
Timeless attribute on a notable doesn't count if the notable is anointed

### ISSUE THREAD

**Issue by lfigueirabr** [PathOfBuildingCommunity/PathOfBuilding#1495]
If you anoint a notable under the influence of a timeless keystone and set a timeless attribute for it, nothing happens. 
For example, if you choose "Add life", no life is added on the final calculation.

**Comment by LocalIdentity** [comment]
Duplicate of #1492

**Comment by lfigueirabr** [comment]
> 
> 
> Duplicate of #1492

Thanks for pointing out, after reading the description of that issue it's the same thing.
