### ISSUE TITLE
Add how many points needed in the power report, allow for filtering of values if they're too high/low

### ISSUE THREAD

**Issue by olafurw** [PathOfBuildingCommunity/PathOfBuilding#1497]
**Is your feature request related to a problem? Please describe.**
The new power report is amazing. It would be great if you could also see how many point you need to travel to it.

**Describe the solution you'd like**
Column next to the value column. Would be great as well if you could filter out things that would take too many points to travel to. Like if I do Life, the list is huge.

**Comment by xanthics** [comment]
I was going to post the same suggestion with an additional request to include an option to average the values over the default shortest path and sort on that.  Although I am aware that shortest path isn't always the most efficient if there are 2+ choices.

**Comment by Mamotromico** [comment]
I'm investigating on how to add different sorting options or ui elements on the power report UI. I'll likely make separate PR's for each of these features

**Comment by ppoelzl** [comment]
Distance sorting was added in 1.4.170.14.
