### ISSUE TITLE
Curse on Hit new mod text isn't parsed

### ISSUE THREAD

**Issue by jcai1** [PathOfBuildingCommunity/PathOfBuilding#1503]
Since 3.12 the Curse on Hit mods (e.g. from rings) look like:

    Curse Enemies with Frostbite on Hit, with 32% increased Effect

These aren't parsed by PoB. I think it is equivalent to the mod combination (which does get parsed):

    Curse Enemies with Level 1 Frostbite On Hit
    32% increased Frostbite Curse Effect

I have not actually confirmed this though.

**Comment by Regisle** [comment]
The issue with the above implementation is if you have another higher level frostbite that gets applied first, itll increase that ones effect when it shouldnt

**Comment by jcai1** [comment]
Yep you're right, it has to be tied to the mod if there are multiple.

**Comment by jcai1** [comment]
Resolved with 0bfa651ae4730b1224f5058e30d7635a36daea34.
