### ISSUE TITLE
New checkbox in Configuration - "Is the enemy marked?"

### ISSUE THREAD

**Issue by fatings** [PathOfBuildingCommunity/PathOfBuilding#1504]
New nodes on the tree, such as **Marked for Death** and **Mark the Prey** require a condition for the enemy being marked.

**Comment by uilman** [comment]
If you have a Mark and enough curse slots for the mark curse, the condition is met.

**Comment by Quotae** [comment]
As said above, this checkbox isn't necessary. Those mods apply automatically if you have a Mark on the enemy.

**Comment by fatings** [comment]
My bad, I assumed the mark was being detected but the mods on rings were modified, that's where the problem resides.

Assassin's Mark on hit on a shaper ring is a red line, check below:
![image](https://user-images.githubusercontent.com/39002567/94409134-a9fe2400-016d-11eb-8f84-5bf9cdc37857.png)
