### ISSUE TITLE
Timeless jewels attributes are not saved

### ISSUE THREAD

**Issue by lfigueirabr** [PathOfBuildingCommunity/PathOfBuilding#1505]
POB Community Fork
Version 1.4.170.12

When adding attributes to notables as part of the new support for Timeless jewels, they are not saved. The save button doesn't enable, and if you close the application all values are lost.
Even if you make other changes and save, these values are not persisted.

Tested with Lethal Pride jewel, its text edited to put the right number (the slider jumps numbers).

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.13.
