### ISSUE TITLE
Blazing Salvo Projectile Switch Does Not Change DPS for Mine Or Trap Support

### ISSUE THREAD

**Issue by Trilkin** [PathOfBuildingCommunity/PathOfBuilding#1506]
There's no difference between 1 Projectile and All Projectiles for damage. Average damage and DPS stays the same throughout. Curiously, if you swap gems in the Skills tab, you can still see the effective DPS gain with All Projectiles, but it won't reflect on the sheet. You can similarly see the difference when toggling the skill on and off.

**Comment by ppoelzl** [comment]
Cannot reproduce this bug anymore.

**Comment by jedahan** [comment]
I am using blazing salvo with cast on crit. I wonder since the skill is disabled, if its not showing that way. https://pastebin.com/EaX1SXY1

**Comment by jedahan** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/523 had a workaround - disabling the cast on crit gem in the skill chain shows the dps. hopefully will be fixed correctly with https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2204
