### ISSUE TITLE
Hexblast does not take Eye of Malice resistance increases into account

### ISSUE THREAD

**Issue by geisserf** [PathOfBuildingCommunity/PathOfBuilding#1508]
* **What happened?**
Eye of Malice increases nearby enemy cold and fire resistance by 50%. It therefore should change the resistance value that is used for the calculation of Hexblast, but this is not the case.

* **What steps will reproduce the bug?**
Make a new build with three skills: Hexblast, Frostbite, Ice Nova. Equip Eye of Malice. In the calculation tab for Hexblast chaos resistance multiplier is 1.44. However, the correct resistance multiplier should be 1.44 * 1.5 = 1.66. If we switch the calculation to Ice Nova we see that in this case Eye of Malice is correctly taken into account.

* **Does it reproduce every time?**
Yes.

* **Shareable build link**
My current character, where I noticed first that Eye of Malice does not increase the average Hexblast hit: https://pastebin.com/F4vHLn26

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
