### ISSUE TITLE
Lancing steel additional projectiles not calculated correctly

### ISSUE THREAD

**Issue by LennDG** [PathOfBuildingCommunity/PathOfBuilding#1512]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

While looking at Lancing Steel calculations, noticed that the amount of projectiles fired was not the one I expected it to be.
With GMP and the maximum amount of 4 shards used the calculation should be (1 + 3 + 4) * (1 + 200) which sums up to 24. This is also seen in game:

![image](https://user-images.githubusercontent.com/5593865/94429085-1428c000-0192-11eb-9107-846696202882.png)

PoB shows the amount of projectiles fired as 22. I suspect it is not using the 1 projectile that is the base of the skill.

* **What were you trying to do?**

Get information on how much damage my Lancing Steel skill was actually doing

* **What steps will reproduce the bug?**

Set up a lancing Steel skill with GMP and set "consumed shards" in the configuration to 4.

* **Does it reproduce every time? If not, why so?**

Yes

**Comment by PJacek** [comment]
Fixed in 1.4.170.13
