### ISSUE TITLE
Bleed DPS

### ISSUE THREAD

**Issue by razorbladehnt** [PathOfBuildingCommunity/PathOfBuilding#1514]
http://puu.sh/Gxf7U/1ca464193e.png
Total more % seems a bit too high

https://pastebin.com/6VPBFLZ3
v. 1.4.170.12

**Comment by Regisle** [comment]
value looks correct to me based on the more multipliers ((8.2 * 1.63 * 1.49 * 0.67 * 1.58 * 1.57 * 1.24 * 3 * 1.6 * 1.25 * 1.2 * 1.1 * 1.12) - 1) * 100 = 36306.9% more damage

can you elaborate if you believe any of those multipliers are wrong or if its just the total that seemed wrong?

**Comment by razorbladehnt** [comment]
Ok
I guess Total damage per bleed threw me off 
Mistook it for DPS
