### ISSUE TITLE
Missing spectre

### ISSUE THREAD

**Issue by pincoide** [PathOfBuildingCommunity/PathOfBuilding#1515]
Drox Arena Master is missing from the spectre list, here you can find the info: https://poedb.tw/us/mon.php?n=Arena+Master
It would be nice if the configuration could apply the attack speed buff to minions/player damage.

Thanks.

**Comment by Medivha** [comment]
also missing They of Tul https://poedb.tw/us/They_of_Tul

<3

**Comment by ppoelzl** [comment]
Superseded by #1775
