### ISSUE TITLE
indexing nodesInRadius (nil value) when trying to allocate cluster notables

### ISSUE THREAD

**Issue by trevorm4** [PathOfBuildingCommunity/PathOfBuilding#1519]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

![image](https://user-images.githubusercontent.com/11250934/94466590-af6c6600-018f-11eb-847d-29453739d9b1.png)

* **What were you trying to do?**
Attempting to allocate points in large cluster jewel

* **What steps will reproduce the bug?**

Import profile for "storm159", select first heist character and import it. Then try to allocate the cluster jewel nodes.

* **Does it reproduce every time? If not, why so?**
Yes, every time it does
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

https://pastebin.com/6hebczUs

**Comment by trevorm4** [comment]
Followup: this issue is created when you socket a thread of hope into a small cluster jewel slot

**Comment by Wires77** [comment]
Note that this doesn't occur for the top-leftmost Thread of Hope, I'm guessing because it's a Small Ring, and wouldn't be able to allocate any other nodes there.
