### ISSUE TITLE
Cyclone mana cost.

### ISSUE THREAD

**Issue by xecutable** [PathOfBuildingCommunity/PathOfBuilding#1520]
Using Cyclone on a 4L as it follows: Cyclone lvl 1 (base mana 2) + Fortify (130% mana multiplier) + Infused Channeling (140% mana multiplier) + Maim (115% mana multiplier).

Using the reduce mana wheel near templar for a total of 15% mana cost reduction to skills. The PoB calculations are as follow:

2 x 2.09 x 0.85 x 1 = 3.553 which in PoB is reported as 3 and in-game tooltip shows as 4.

**Comment by randomflyingtaco** [comment]
Used Shavronne's Revelation to confirm that this configuration actually subtracts mana in increments of 4 in game.
It should probably be rounding instead of floor on this line? https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/Modules/CalcOffence-3_0.lua#L895

**Comment by randomflyingtaco** [comment]
Tested with more skills and they all seem to round down in-game, so floor is probably correct.  Back to the drawing board.
