### ISSUE TITLE
Punishment inc dmg taken is not applying properly

### ISSUE THREAD

**Issue by ganuuk** [PathOfBuildingCommunity/PathOfBuilding#1524]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

![image](https://user-images.githubusercontent.com/72049563/94491736-2bca6d80-01bf-11eb-806c-33117416ec50.png)

Punishment increased damage taken is applying to player instead of target, as you can check on damage taken defensive calculation print above.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Mamotromico** [comment]
I can't seem to be able to reproduce, can you share a pastebin example?

**Comment by Reithan** [comment]
I'm also seeing other strange behavior from punishment. It seems like punishment LOWERS shown damage to the enemy? I can't figure out where the damage is being removed though.

Without: 
![image](https://user-images.githubusercontent.com/7475701/95778408-ec028c00-0c7c-11eb-9e9d-8688d7ee933e.png)

With: 
![image](https://user-images.githubusercontent.com/7475701/95778434-f58bf400-0c7c-11eb-822f-e28f49216001.png)

From this build's pastebin: https://www.pathofexile.com/forum/view-thread/2874329/page/1
Here: https://pastebin.com/gEjxHYi7

**Comment by Wires77** [comment]
@Reithan that build is trying to use 2 curses but only has 1 max curse, so when you add punishment it overrides the assassin's mark from the ring

**Comment by Reithan** [comment]
Ah, well, that explains that. 👍
