### ISSUE TITLE
Vall Discipline does not reserve Discipline by default.

### ISSUE THREAD

**Issue by Kraust** [PathOfBuildingCommunity/PathOfBuilding#1525]
* **What happened?**
Imported a Character with the skill "Vaal Discipline"

* **What were you trying to do?**
Imported a Character with the skill "Vaal Discipline" to see how much damage was gained with Pain Atonement with Blood Magic + Discipline

* **What steps will reproduce the bug?**
1. Import Character that is using Vaal Discipline
2. Check to see if Discipline is enabled by default
3. See that Vaal Discipline is enabled by default and not Discipline.

* **Does it reproduce every time? If not, why so?**
Yes

* **Additional information:**
This doesn't seem like the correct functionality. The aura should take precedence to be enabled by default not the Vaal Aura.

**Comment by Mamotromico** [comment]
That's the standard behavior of all Vaal auras. It's not a bug.

**Comment by ppoelzl** [comment]
This is intended behaviour. It is common to use a Vaal aura only, especially with Discipline and Grace, for example.
