### ISSUE TITLE
60% chance for Poisons inflicted with this Weapon to deal 100% more Damage working with spells etc

### ISSUE THREAD

**Issue by Hapseleg** [PathOfBuildingCommunity/PathOfBuilding#153]
I am not 100% sure this is a bug since its hard to test, but the affix "60% chance for Poisons inflicted with this Weapon to deal 100% more Damage" (or 300% with Darkscorn) is currently working with spells.
Since the affix states "inflicted with this Weapon" I believe it should only work with bow attacks right?

[Pastebin that shows the problem:](https://pastebin.com/ETdXs50g)

**Comment by LocalIdentity** [comment]
Yeah it should only work with attacks, I'll fix it for the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
