### ISSUE TITLE
Rage stops calculating after 50

### ISSUE THREAD

**Issue by Genhain** [PathOfBuildingCommunity/PathOfBuilding#1531]
* **What happened?**
When configuring my build for having 85 rage due to Rigwalds royal axe and a sword in other hand plus the "berserking" passive, i noticed the damage will not increase passed 50 rage.
* **What were you trying to do?**
calculate damage with Rigwalds combination with rage and bleeding and rage support
* **What steps will reproduce the bug?**
put the damage to 50 then increase it incrementally and see no change
* **Does it reproduce every time? If not, why so?**
yes
* **Additional information:**
https://pastebin.com/Rk9ZMVQw
So this affects quite a fair bit with the overall DPS, needless to say rage on its own, along with Rage support gem and Rigwald's command having its bleed DoT increased with rage

**Comment by Wires77** [comment]
Works for me just fine, I opened your build, went into the Config tab, and incremented the Rage amount, and the DPS numbers changed all the way up to 85.  What version are you using in the bottom left corner?

**Comment by Genhain** [comment]
1.4.169.3

**Comment by LocalIdentity** [comment]
> 1.4.169.3

Our current version is on 1.4.170.12, you need to update your PoB

**Comment by Genhain** [comment]
I just noticed that, i was using the web client pob.party rather than the release
