### ISSUE TITLE
Iron mass is not equipped by skeletons

### ISSUE THREAD

**Issue by AsenIvanov** [PathOfBuildingCommunity/PathOfBuilding#1535]
Hello,

With the new update the Iron mass unique mostly works, the mods and triple damage all work, however the stats from actually equipping a copy on the skeletons does not function. This is the flat damage from the weapon itself, and the change in attack speed from 1.25 to the weapon attack speed.

**Comment by Nostrademous** [comment]
Which part doesn't work? See image below.
![IronMass](https://user-images.githubusercontent.com/1735956/94609327-9b4a6680-026c-11eb-86ea-5ef9fb0d68bc.png)

**Comment by AsenIvanov** [comment]
HI, I posted this before the 170.13 patch, it works now thank you.
