### ISSUE TITLE
Fated End, Paua Ring implementation is scaling curse effect **for each** equiped curse

### ISSUE THREAD

**Issue by cashoes** [PathOfBuildingCommunity/PathOfBuilding#1536]
* **What happened?**
Ignite damage was being scaled by reduced resistances from Flammability + Elemental Weakness to a ridiculous level.

* **What were you trying to do?**
Ignite scaling using Elemental Weakness, Flammability, Despair, Vulnerability, stacking Doom with the Fated End, Paua Ring.

* **What steps will reproduce the bug?**
1. Socket Fireball + Combustion.
2. Equip items to increase curse limit (Cospri's Will, Vixen's Entrapment, Windscream Greaves, etc.)
2. Socket Elemental Weakness, Flammability, Despair, Vulnerability.
3. In Calcs tab, select Fireball and note that Ignite damage scaling for Fireball is accurate (Effective DPS Mod) for base Elemental Weakness, Flammability (reducing resistances by the expected amounts), Despair (increased damage over time), and Vulnerability (increased burn rate).
4. (Optional) Modifying Doom numbers does nothing.
5. Equip Fated End, Paua Ring 
6. In Calcs tab, note that Ignite damage scaling for Fireball is >3x larger.
7. In Calcs tab, select any curse and note that the Curse Effect Mod is accounting for increased Doom effect multiple times.
8. (Optional) Adding additional curses as separate skills (even repeated curses) scales Ignite damage infinitely...

* **Does it reproduce every time? If not, why so?**
Yes.

* **Additional information:**
Pastebin: https://pastebin.com/thGmYBjm

**Comment by PJacek** [comment]
Fixed in 1.4.170.14
