### ISSUE TITLE
"Show top node" and "Power per point" not affecting "Defence" nodes on "Offence/Defence" mode

### ISSUE THREAD

**Issue by Reithan** [PathOfBuildingCommunity/PathOfBuilding#1537]
# 🐞 bug report

**Describe the bug**
"Show top node" and "Power per point" not affecting "Defence" nodes on "Offence/Defence" mode

**To Reproduce**
Simple repro, just do open any POE build

**Expected behavior**
Expect these toggles to affect both Offence and Defence nodes when selected

**Screenshots**

![image](https://user-images.githubusercontent.com/7475701/94518242-6d1e4580-01de-11eb-9be8-32c5a4b40c32.png)

## 🌍  Your Environment

- OS: Win 10 x64
- Version: 1.4.170.12
- PoE: Steam version

**Comment by Wires77** [comment]
Fixed by #1527

Check for updates in your PoB, a release went out earlier with this fix.

**Comment by Reithan** [comment]
@Wires77 Is the fix in a release, yet? My PoB isn't detecting any update.

Checking main repo page it shows my version is still latest (1.4.170.12)

Just checked, after several restarts of PoB it started working again, but my version number hasn't changed. Maybe this is an intermittent error?

**Comment by Wires77** [comment]
Oh, looks like @LocalIdentity still needs to add 1.4.170.13 as a release on the repo.  I'm not sure why the version number didn't change on your PoB.
