### ISSUE TITLE
Speed Runner / New Player - "Skill Gem Obtained At" List

### ISSUE THREAD

**Issue by ttgx1000** [PathOfBuildingCommunity/PathOfBuilding#1539]
**Is your feature request related to a problem? Please describe.**
Having to tab out to figure out where gems come from and compiling a list each league for each build I want to do takes a lot of time. With this it would be on the fly and extremely easy to see what gems come from where.

**Describe the solution you'd like**
I did a little prototyping with the picture below and found that I can get all the current gems in the build, the level requirement of level 1 version of the gem and display that in a new list type.

What's missing is the data from where you can obtain the gems: 

https://docs.google.com/spreadsheets/d/1bm_5CbVppiapbR7BWYjtByKEK8i0xZS9ARDx9tDgUeA/edit#gid=509118471

This google doc has it all laid out and would most likely need to be another separate data set that is manually maintained as GGG does not provide that information from what I can see. This data can then be added to gemInstance data.

**Describe alternatives you've considered**
Sorting by Act, Gem Requirement level and Gem Type would be useful as well.

**Additional context**
![Gem Level Obrtained](https://user-images.githubusercontent.com/12674007/94632442-84ba0480-0298-11eb-900a-95d11008d274.PNG)

**Comment by ppoelzl** [comment]
This is our of scope for PoB. However there are other third-party resources that let you accomplish what you are suggesting.
Check out https://poe-roadmap.com/ to see where you get your skills gems and more.

**Comment by ttgx1000** [comment]
> This is our of scope for PoB. However there are other third-party resources that let you accomplish what you are suggesting.
> Check out https://poe-roadmap.com/ to see where you get your skills gems and more.

Sounds good, thanks for getting back so quickly and thanks for the link. Cheers.
