### ISSUE TITLE
Bladestorm's "Are you in bloodstorm?" should not affect other attack skills

### ISSUE THREAD

**Issue by GeorgeTheDefiler** [PathOfBuildingCommunity/PathOfBuilding#1540]
After several testing in game, bladestorm's blood stance buff : " #% more Attack Speed while you're in a Blood Bladestorm " only affect bladestorms itself, and does not affect other skill ( tested with cleave [aoe], groundslam [slam] and dual strike [strike] ), not sure if this is intended, but it's what it's.

However ticking option " Are you in Bloodstorm? " under section Configuration > Skill options, will affect or apply said buff to other attack skill as well, please fix

Thank you for your hardwork!!

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.

**Comment by purpleHaze3333** [comment]
POB version 2.21.1 
This bug is still present.
