### ISSUE TITLE
Is infusion active checkbox missing from the Configuration tab.

### ISSUE THREAD

**Issue by PrototypeRak** [PathOfBuildingCommunity/PathOfBuilding#1543]
Is infusion active checkbox is missing in the configuration tab, damage calculation is not taking it into effect as well.

**Comment by LocalIdentity** [comment]
Please provide a pastebin for the build you cannot see it on. It works fine for me

**Comment by PrototypeRak** [comment]
Hi there, My apologies, this was misunderstanding on my part. I will close the issue. Thanks for your response.
