### ISSUE TITLE
Add support for plugins

### ISSUE THREAD

**Issue by rogueyoshi** [PathOfBuildingCommunity/PathOfBuilding#1548]
There is an issue with features that the community would like, but are denied due to being "out of project scope" (like the recent gem reward tracker).

If you add a plugin/module system for developers to offer their own integrations that don't fit the core scope, it can solve this issue.

There really isn't a better alternative than this. Otherwise people will be making their own multitude of forks just to use features they want.

**Comment by coldino** [comment]
Just my opinion, but this may not be necessary. It's already quite possible to use PoB (with its UI disabled) *inside* another app, or by another Lua script.

So for example a developer could make an app that handles gem rewards as you requested, even with a live overlay in game, just by using your existing PoB and build file.

There are no changes to PoB required to do this today.

**Comment by ppoelzl** [comment]
The approach @coldino outlined is vastly prefered by @PathOfBuildingCommunity/maintainer compared to a traditional plugin system.
