### ISSUE TITLE
Tooltip doesn't show 20% bleed source from Vulnerability

### ISSUE THREAD

**Issue by mataski** [PathOfBuildingCommunity/PathOfBuilding#1551]
![image](https://user-images.githubusercontent.com/62036912/94751901-689a8e00-0392-11eb-961d-7b59f472d44c.png)

20% from Vuln ticked doesn't display under Source. Confusing to track down where the extra 20% come from.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
