### ISSUE TITLE
Explosive Arrow level does not scale with damage properly

### ISSUE THREAD

**Issue by DaveOshiCZ** [PathOfBuildingCommunity/PathOfBuilding#1556]
Hi,
I went with pure phys/bleed explosive arrow build this league (3.12) and noticed, that level of explosive arrow gem does not scale with Bleed DPS, TDpB, nor CTD. Only number of fuses. I use Brutality gem, so only phys and mostly bleed is applied. I guess this is not ok?

![exarbleed1](https://user-images.githubusercontent.com/68417887/94791431-e6cd5380-03d7-11eb-8e41-174d6ba01c23.PNG)
![exarbleed2](https://user-images.githubusercontent.com/68417887/94791433-e7fe8080-03d7-11eb-98f2-56812dfa7d22.PNG)

**Comment by Regisle** [comment]
Level on explosive arrow only adds flat fire so has no effect on bleed

**Comment by DaveOshiCZ** [comment]
How does it scale with Bleed DPS if it only applies flat fire dmg and why does Arrow stacks scale?

**Comment by Regisle** [comment]
Base damage of the bow still applies, and it adds together all the stacks for the bleed source, this means 5 fuses will deal 400% more bleed damage than 1 fuse, it also gets 3% more ailment damage per fuse (another 15% more multiplier)

its just the level of the gem has no effect on either of those 2 effects

**Comment by DaveOshiCZ** [comment]
I see. Thank you.
