### ISSUE TITLE
Curse aura mana reserved node doesn't work

### ISSUE THREAD

**Issue by Akhrone** [PathOfBuildingCommunity/PathOfBuilding#1557]
Hello, firstly great work on this fork ;)

I found an issue : nodes as "reduced mana reservation of cruse skills" or the culster node Forbidden Words don't change mana reserved while using a blasphemy setup.

**Comment by LocalIdentity** [comment]
I figured this out and will have a fix for the next update

**Comment by ppoelzl** [comment]
Duplicate of #1419
