### ISSUE TITLE
Quick and Deadly with lacerate both slashes and axe and sword not working

### ISSUE THREAD

**Issue by Genhain** [PathOfBuildingCommunity/PathOfBuilding#1561]
* **What happened?**
Was doing a build and testing out the cluster jewel notable "Quick and Deadly" while using an axe and sword and noticed that it enabled and disabling the node does not change the damage. even when i have it set to both slashes.
* **What were you trying to do?**
Test the notable to see the damage difference while using it
* **What steps will reproduce the bug?**
have rigwald's sword and axe and try assign and unassign the "Quick and Deadly" Notable
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
https://pastebin.com/hM7xpn2C

**Comment by Sethman1** [comment]
I would like to add to the Quick and Deadly issue. I t seems to think that thrusting swords and non thrusting swords are two different weapon types and while using Paradoxica and Saviour it would add damage in PoB, but in game this does not work.
