### ISSUE TITLE
can some1 help me with this error please , been trying to few hours to fix

### ISSUE THREAD

**Issue by nivar15** [PathOfBuildingCommunity/PathOfBuilding#1562]
![fe11b7ed80d71d6ceb57972558253179](https://user-images.githubusercontent.com/72227080/94855145-bcf74980-0436-11eb-8867-1103e3c8a10b.png)
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by nivar15** [comment]
cant open any path of exile pastebin when i try to i get this error please help ;)

**Comment by nivar15** [comment]
tried reinstalling pretty much everything

**Comment by Nostrademous** [comment]
It has to do with Thread of Hope

**Comment by Nostrademous** [comment]
Modify the XML of the file you want to load by deleting the item for now... 

OR 

wait until we push a fix

**Comment by nivar15** [comment]
okay thank you very much ill try it and let u know

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
