### ISSUE TITLE
Divergent Rallying Cry effect not working

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#1563]
Hello,

Rallying cry with divergent alt quality does not provide more damage to minions than the regular quality. 

Edit: Still occurs in 170.14 version

https://i.imgur.com/JaGwGnI.png 0%

https://i.imgur.com/N7SJwrB.png 20%

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
