### ISSUE TITLE
Phantasmal Earthquake spell damage scaling

### ISSUE THREAD

**Issue by Kyle-corbeel** [PathOfBuildingCommunity/PathOfBuilding#1581]
![image](https://user-images.githubusercontent.com/37397551/94931930-a994be80-04c8-11eb-9189-35301baaa1b7.png)
![image](https://user-images.githubusercontent.com/37397551/94931955-b44f5380-04c8-11eb-9735-374e1308c837.png)
![image](https://user-images.githubusercontent.com/37397551/94932012-c92be700-04c8-11eb-934a-801c7ae856d1.png)
When selecting the phantasmal alternate quality from earthquake, spell damage doesn't seem to increase the damage of the attack, while it does in-game.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
