### ISSUE TITLE
Sort by xxx by average per point

### ISSUE THREAD

**Issue by Hapseleg** [PathOfBuildingCommunity/PathOfBuilding#159]
Hello

My idea is that you can use the sort option on the passive tree, but it will color the nodes by "average life/dps" or whatever you choose, instead of it being the exact nodes where ever they are on the tree.
I think this will give a better visual of what nodes to choose since the "best" nodes will have even more color corresponding to your current passive tree.

Keep up the great work, I might learn some lua and join the train :)

**Comment by LocalIdentity** [comment]
I was thinking about this exact idea today too. I think it should be added as a checkbox thougg so it can be used on all sorting stats

**Comment by Hapseleg** [comment]
Yes for sure, that makes sense :) hope I'm not spamming with too many ideas ;)

**Comment by LocalIdentity** [comment]
Ideas and identifying bugs is great, thanks for the help

**Comment by ppoelzl** [comment]
Added in 1.4.170.3.
