### ISSUE TITLE
"Are you stationary" is a number field when it should be a boolean/checkbox

### ISSUE THREAD

**Issue by MatthewSbar** [PathOfBuildingCommunity/PathOfBuilding#1591]
The title says it all. If using something like Peace Amidst Chaos which cares if you're stationary, the "Are you stationary" field in configs is a number value rather than a checkbox.

**Comment by ppoelzl** [comment]
This is intentional. There are game mechanics that care about how long you have been stationary. Putting in any positive number is considered "true" for any other purposes.

**Comment by MatthewSbar** [comment]
Then the field should be named "# of seconds you've been stationary" or similar, it's not intuitive that a yes/no question requires a numerical answer.

Also, if this is the desired route for the UX, "is the enemy shocked" should be removed in favor of entering in a shock effectiveness only, right?
