### ISSUE TITLE
Weird and rare error caused by Malachai's Artifice and catalyst

### ISSUE THREAD

**Issue by lostcoaster** [PathOfBuildingCommunity/PathOfBuilding#1594]
Version: 1.4.170.14

How to replay the error:
1. Select any unique that has multiple rolled values, say Emberwake (fire damage/cast speed/ignite speed)
2. Double click to edit it, select the rolls drop box to anything, **except for the default one**
3. Do nothing and just "add to build", or close it, or skip to next step, all the same 
4. Search for "Malachai's Artifice Unset Ring"
5. Double click to edit it, select catalyst as "Prismatic (Resistance)" 

Now the roll selection dropbox appears, with the same list of the unique you picked in Step 1. 

Any attempt to change the values/selection now causes an error in ItemTabs.lua: 692 -- trying to index a nil value.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
