### ISSUE TITLE
Divine Flesh (Glorious Vanity Jewel) does not apply to RF (Righteous Fire) degen.

### ISSUE THREAD

**Issue by s3784231** [PathOfBuildingCommunity/PathOfBuilding#1597]
When using Glorious Vanity (Xibaqua) and allocating Divine Flesh, total degen from Righteous Fire is not decreased.
![image](https://user-images.githubusercontent.com/53242276/94998858-c03e3100-0600-11eb-8667-470a36a3fc75.png)
In this case, my fire resistance is 81% and my chaos resistance is 90% so there should be a difference in life regeneration, but it is not reported in the allocation tool tip nor the stat panel.
This occurs even if I exit to my builds, exit the application, or copy the build. Perhaps just an oversight as opposed to a bug.
Here is my build for it.
https://pastebin.com/xFRqvSA2

**Comment by Regisle** [comment]
I had planned on fixing this eventually, but damage taken as only works for hits in PoB at the moment, and requires a fair amount of work to make some of the work with dots (iirc only the keystones and the new shield) and some of them not

**Comment by s3784231** [comment]
At least it's a known issue, thanks for the response. I don't mind doing manual calculation, if it's this much effort for something so niche.
