### ISSUE TITLE
Add support for Sigil of Power less damage dealt by enemies

### ISSUE THREAD

**Issue by HiPoEGH** [PathOfBuildingCommunity/PathOfBuilding#1598]
Two sources of damage taken are not showing on the calculations page.
These sources come from Enfeeble, and Sigil of Power.

Enfeeble needs to account for curse effect, and what type of enemy it is effecting (normal, rare, unique, or boss).
Boss monsters like Sirus have 66% less curse effect, which will change the overall curse effect from "less damage taken".
_Oddly enough, Sigil of Power is not hindered by monster type with curse effect, and is a better option for defense against bosses._

* **What were you trying to do?**
Calculate effective damage reduction under "Damage Taken" category.
* **What steps will reproduce the bug?**
Use any level enfeeble, with any amount of curse effect.

**Comment by LocalIdentity** [comment]
Enfeebles works but Sigil of Power does not
