### ISSUE TITLE
How to set number of golems?

### ISSUE THREAD

**Issue by frakc** [PathOfBuildingCommunity/PathOfBuilding#1601]
There are several buffs like Elemanser, which impruves golems buffs  per each summoned golem (not summoned golem type) 
Thus I would be very useful to be able to have an ability to set arbitrary number/ Currently it  looks like pob tried to assume maximum golem number, but numbers are wrong. Eg ingame i have 1600 hp regen and pob shows just 1200

**Comment by randomflyingtaco** [comment]
Golem regen calculations look fine from my testing.  Can you link your profile/POB URL and a screenshot of your in-game stats along with showing your buff bar?

**Comment by ppoelzl** [comment]
Closed due to inactivity.
