### ISSUE TITLE
Add support for mods on Replica Wings of Entropy

### ISSUE THREAD

**Issue by Plyticus** [PathOfBuildingCommunity/PathOfBuilding#1602]
When I try to use Replica Wings of Entropy in PoB, the %More attack speed with main hand and + Critical Strike chance for offhand mods do not work.  I tried it with Dual Strike and Shattering Steel, and its showing no difference between main hand and off hand Attack Speed/Critical Strike Chance.

**Comment by Regisle** [comment]
The mods are both red for me, which means they are not yet supported
![image](https://user-images.githubusercontent.com/49933620/95031615-88b5ae80-06fe-11eb-81c7-f38cf905a2a8.png)
