### ISSUE TITLE
How to add a catalyst on an existing rare item ?

### ISSUE THREAD

**Issue by DaveInDev** [PathOfBuildingCommunity/PathOfBuilding#1605]
Hi,

I added an existing rare item in POB and I want to simulate the effect of adding 20 intrinsic catalysts on it (enhance attributes). But I do not see any corresponding option under "add modifier". I read that POB supports catalyst, so I wonder where I can find this feature ? 

Thanks for your help and this great tool.

**Comment by Wires77** [comment]
PoB currently only supports catalysts for items that are crafted from scratch within PoB.  For imported items, as a workaround you can click "Edit" and add "{tags:attribute}" in front of any mods that would be affected by an intrinsic catalyst.

**Comment by DaveInDev** [comment]
thanks for this clear answer. Indeed it works and makes a "catalyst" field appear with a slider.
