### ISSUE TITLE
Incorrect values for calculating bleed damage

### ISSUE THREAD

**Issue by Deathel** [PathOfBuildingCommunity/PathOfBuilding#1608]
![bleed_bug](https://user-images.githubusercontent.com/72413358/95123376-238ba880-0752-11eb-9323-a7d946c4328c.jpg)

Hello,
It seems the calculations for bleed are incorrect according to wiki. Its supposed to be 210% more multiplier for moving enemies, instead of 200.

**Comment by uilman** [comment]
> 70% per second if the target is standing still (10% if an enemy monster applied it), if the target is moving bleeding deals additional damage equal to **twice** the base, for a **total** of 3 times base damage while moving
70% + (200% more of 70%) = 210%, PoB is correct.
