### ISSUE TITLE
Update to bleed dps calculation method

### ISSUE THREAD

**Issue by Deathel** [PathOfBuildingCommunity/PathOfBuilding#1609]
I haven't found anything about that here, but using average damage from hit to calculate bleed damage is pointless. Due to the mechanics of bleed, there is absolutely no point in showing average value as stronger bleed overwrites weaker bleed. My suggestion would be putting in a box when "enemy is bleeding" box is ticked, in which you could type in a value from 0 to 100 that would represent what percentage of max dmg roll you want to be used when calculating bleed damage (If 0 then the calulations use min dmg roll, if 100 the calcs use max dmg roll, and the numbers in between would represent the values in between, im sure u get what im talking about).

Calculations would probably go somewhere like this (for the hit).
Source DMG = (Max DMG + (Min DMG+(var*0.01*(Max DMG - Min DMG))))/2
where var is the value of the variable from the box, multiplied by 0,01 to turn it into a percentage.

This approach would be great for an accual calculation of bleed dps, the inclusion of Ryslatha's Coil would also be in here so doing that would be like hitting 2 birds with 1 stone.

**Comment by Nostrademous** [comment]
We started doing this for some things like Exerted attacks (option in Config tab to use Max versus Avg). It can be added for bleeds when we have time.

**Comment by Regisle** [comment]
Additionally we had been working on a solution to this months ago, but want to do it without a config option, the issue is there are many factors and it makes the maths very complex to do without simulation

**Comment by ppoelzl** [comment]
Superseded by #2057
