### ISSUE TITLE
Highlighting Minimum percentage per point

### ISSUE THREAD

**Issue by erickRecai** [PathOfBuildingCommunity/PathOfBuilding#1610]
**Is your feature request related to a problem? Please describe.**
With options "Show Node Power" and "Power per point" on, it usually highlights a large number of unallocated passive skills. I would like a filter on what is highlighted based on minimum percentage per point to make selecting the best skill easier. 

I also want to comment that the current highlight system isn't very useful, It isn't easy to differentiate what is the best skill that gives the most DPS per point versus all the other 5 skills that are also highlighted.

**Describe the solution you'd like**
An additional text box to input minimum percentage.
When empty, simply highlights all passives that apply.
Shows up only when "Power per point" is 'on'.
The expected input range should be around 1.0% to 10.0% but there might be scenarios that give higher percentages.
Only skills that provide the minimum percentage per point or higher are highlighted. All other skills are not highlighted.

**Describe alternatives you've considered**
A text box for a raw number instead probably takes too much UI space.
Could also be a special command that can be typed into the search as you see below to save UI space.

**Additional context**
Here is how the text box could look like which I just highlighted in red.
The skill shown gives at least 2.6% to total dps per point so this skill should be highlighted.
![concept1](https://user-images.githubusercontent.com/56102383/95144514-8fe7b700-0714-11eb-943a-64c6a55e2f9e.png)

Not similar to this request. #1347 
But probably an alternative.

**Comment by ppoelzl** [comment]
The power report feature added in 1.4.170.12 allows you to sort all passive nodes by relative power increase.

**Comment by erickRecai** [comment]
The power report only reports the value of single nodes which isn't as useful as the ratio of percentage/point as I suggest.
