### ISSUE TITLE
Right clicking an equipped item should select it as if double clicking on it in "All items" section.

### ISSUE THREAD

**Issue by kilpsz** [PathOfBuildingCommunity/PathOfBuilding#1612]
**Is your feature request related to a problem? Please describe.**
Editing equipped items is always a PITA since finding them in the "all items" section takes unnecessary time.

**Describe the solution you'd like**
As said in the title, i wish we could just right click(any ctrl etc combo is fine as well) an equipped item which would then select it as if double clicking on it in "all items" section.

**Describe alternatives you've considered**
Search box for "All items", but i think my solution is simple and straight forward enough.

**Comment by LiakGamer** [comment]
This seems like a Huge QoL upgrade. Another solution is always temporally sorting the all items category so that equipped items are on top in order(although the suggested change is better).

**Comment by QuickStick123** [comment]
You can press e while hovering equipped items to open them in the edit menu.
