### ISSUE TITLE
Effective Health Pool

### ISSUE THREAD

**Issue by cyanophage** [PathOfBuildingCommunity/PathOfBuilding#1613]
**Is your feature request related to a problem? Please describe.**
I really find the "effective health pool" for Phys and Ele on the Calcs tab really useful. Sometimes getting the most Life% doesn't give the best defenses for a build. It would be great if we could access this info on the "Tree" tab and select it in the "Show Node Power" drop down menu. 

**Describe the solution you'd like**
Add "Effective Health Pool" to  "Show Node Power" drop down menu. 

**Describe alternatives you've considered**
Can't think of any alternatives right now

**Comment by ppoelzl** [comment]
Added in 1.4.170.15.
