### ISSUE TITLE
Sadist Cluster skill brings no damage increase

### ISSUE THREAD

**Issue by seedlern** [PathOfBuildingCommunity/PathOfBuilding#1614]
I have a cluster Jewel with the Sadist skill active. 

>Sadist:
15% increased Elemental Damage if you've Chilled an Enemy Recently
25% increased Elemental Damage if you've Shocked an Enemy Recently
20% increased Elemental Damage if you've Ignited an Enemy Recently

But when i check in the config that the enemy is ignited shocked and chilled/frozen it doesnt do anything to my damage output.

In game i use the Anomalous Controlled Destruction Support to achieve the ailments needed

>  Anomalous Controlled Destruction Support:
Supported Skills have 60% reduced Critical Strike Chance
Supported Skills have 10% chance to Freeze, Shock and Ignite

**Comment by Wires77** [comment]
The config options look like this under the "When In Combat" section:
![image](https://user-images.githubusercontent.com/1209372/95256716-cb53b580-07e8-11eb-8bfa-5012c13b5c1a.png)
