### ISSUE TITLE
Feature Request: Scorching Ray Fire Exposure Checkbox

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#1617]
Would it be possible to have the client pop a checkbox to apply the -25% fire resistance fire exposure when Scorching Ray is active on your skill list?

That's a lot of resistance shredding that is not calculated at the moment, and scorching ray is quite popular as a debuffer in ignite/RF builds.

**Comment by ppoelzl** [comment]
Set Scorching Ray to 8 stages, either under the main skill in the sidebar or in the calcs tab to automatically apply Exposure.
