### ISSUE TITLE
Timeless Jewel - might of the vaal-socket 4 ([1.4.170.14)

### ISSUE THREAD

**Issue by tools4hackers** [PathOfBuildingCommunity/PathOfBuilding#1619]
Assigning this slot in pob makes it crash  
------------------------
Gem info
------------------------
Rarity: Unique
Glorious Vanity
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 81
--------
Bathed in the blood of 7968 sacrificed in the name of Doryani
Passives in radius are Conquered by the Vaal
Historic
![vaal](https://user-images.githubusercontent.com/16124106/95338441-38338200-08b3-11eb-8600-456c4f1b19e6.png)
![erroir](https://user-images.githubusercontent.com/16124106/95338453-3b2e7280-08b3-11eb-8724-55b21b2ea5a9.png)

**Comment by Wires77** [comment]
Might of the Vaal and Legacy of the Vaal give 3 completely random modifiers, it seems.  I'm not sure we'll be able to support them, but perhaps I can at least stop it from throwing an error.

**Comment by Wires77** [comment]
Added a PR to fix this crash, and added open text boxes so you can write in your own mods.
