### ISSUE TITLE
Replica Volkuur's Guidance -- Less ignite duration

### ISSUE THREAD

**Issue by Jigglefrizz** [PathOfBuildingCommunity/PathOfBuilding#1621]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Ignite duration not changing when equipping this item

* **What were you trying to do?**
Calculate ignite duration

* **What steps will reproduce the bug?**
Open POB
Equip fireball
Check Ignite duration
Equip Replica Volkuur's Guidance
Check ignite duration

* **Does it reproduce every time? If not, why so?**
Yes

* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by LocalIdentity** [comment]
No longer an issue
