### ISSUE TITLE
Something is wrong with the calculations

### ISSUE THREAD

**Issue by Ruba87** [PathOfBuildingCommunity/PathOfBuilding#1623]
This is the Syndicate_Operative monster statistics:

![](http://dl4.joxi.net/drive/2020/10/08/0003/0405/197013/13/b314340f7e.jpg)
52+28=80 and not 95

![](http://dl3.joxi.net/drive/2020/10/08/0003/0405/197013/13/52de526b75.jpg)
There's also something wrong here. Or is there something I don't know?!

**Comment by Regisle** [comment]
thats a more multiplier so its multiplicative, 1.52 * 1.28 = 1.9456
same with the other one, 0.9 * 0.77 * 0.86 * 1.48 * 1.1 = 0.97025544

**Comment by Ruba87** [comment]
Thank you, I didn't know it was done this way.
