### ISSUE TITLE
Build comparaison and "next item to focus on"

### ISSUE THREAD

**Issue by xqvier** [PathOfBuildingCommunity/PathOfBuilding#1625]
**Is your feature request related to a problem? Please describe.**
When importing a build from a guide or a "wishlist build", it's really hard to know which next item your current build is missing to really shine.

**Describe the solution you'd like**
It would be nice to be able to compare 2 builds to see the differences, with an option to sort difference by power gain.
If this could list tree node / item / skill / or whatever that would make the current build increase in power. 

for instance, let's say I follow a build and this one use awakened support gem that I'm not using yet, it should show me that and this should be sorted to see which item / skill / node will be the most impactfull from a power perspective (let it be selectable as to which I wanna focus on more ES, or more DPS, or more attack speed, etc...).

**Comment by ppoelzl** [comment]
What one might consider the "next best item" for one's build depends on a multitude of factors, most of which Path of Building can and will not account for. While Path of Building is a simulation tool, it cannot compensate or substitute the required game knowledge for your personal goals. Being able to compare builds is a feature that has already been requested before, so I'm closing this issue as it doesn't add anything new to the conversation.
