### ISSUE TITLE
Negative Accuracy calculation

### ISSUE THREAD

**Issue by Pixel-Fusion** [PathOfBuildingCommunity/PathOfBuilding#1626]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**  Increases and reduction to accuracy when base accuracy is negative (Replical Trypanon) have opposite effect. In game increases to negative accuracy does not further reduce accuracy.
* **What were you trying to do?**  Undeniable Juggernaut with negative accuracy and negative attack speed to reach permenant -100%+ attack speed.
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:** Enfeeble reduction to accuracy increases base accuracy when it is negative.
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by Wires77** [comment]
Can you post a screenshot detailing your accuracy rating and attack speed with and without enfeeble?  All of the other increases/reductions modify stats away from zero, like Eye of Desire for resistances.

**Comment by Pixel-Fusion** [comment]
https://i.imgur.com/j2M7aXA.jpg
This is in game screenshot. It seems that in game accuracy floor is 0 and does not go negative for the calculations of undeniable at least. 
https://i.imgur.com/Tm3mRsy.png
This is PoB, if i remove Undeniable the attack rate matches at 0.49

**Comment by Wires77** [comment]
Interesting, the accuracy stat must just disappear when it gets to 0, since it's there on all other builds.  I'll take a look at the code, then.
