### ISSUE TITLE
Champion's Master of Metal bonuses are being increased by Aura effect bonuses when they shouldn't be.

### ISSUE THREAD

**Issue by rudradevbasak** [PathOfBuildingCommunity/PathOfBuilding#163]
If you have Champion's Master of Metal node allocated, and are wearing a chest with the "20-25% increased effect of Auras on you", in PoB it also increases the effect of the bonuses from the ascendancy node.

But I checked in-game, atleast the armor bonus, is not increased by aura effect. I assume the same is true for the added phys dmg. 

Worth noting, this bug was introduced during v1.4.157.2 as part of the aura effect breakdown change I believe. The PoB behavior was correct before that.

**Comment by ppoelzl** [comment]
A quick test on v1.4.157.1 reveals that this in incorrect.

**Comment by notLiria** [comment]
I'll take a look at it. It seems that the added phys damage is treated as an aura at least.

**Comment by notLiria** [comment]
To recreate this, it seems that you need to have a number of impale stacks that is not the "default" number for it to work. It seems that this is because Master of Metal's modifiers are implemented with an ExtraAura

**Comment by LocalIdentity** [comment]
Easy fix to add a check in CalcPerform line ~2990 for players and minions
This probably effects other `ExtraAura` skills too that should be unscalable

**Comment by LocalIdentity** [comment]
No longer an issue as there aren't any mods in the game that can scale this
