### ISSUE TITLE
Ball Lightning base radius should be 18

### ISSUE THREAD

**Issue by ghost** [PathOfBuildingCommunity/PathOfBuilding#1630]
The base radius of ball lightning is showing as 22 when it was nerf'd to 18 in 3.12.

![image](https://user-images.githubusercontent.com/71898137/95619063-e2530b80-0a65-11eb-8112-6e1ed8f6b086.png)

**Comment by Wires77** [comment]
Fixed by #1611 in the next update

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.13.
