### ISSUE TITLE
Voidforge not imported correctly

### ISSUE THREAD

**Issue by HalfThere** [PathOfBuildingCommunity/PathOfBuilding#1633]
The Voidforge in the unique item list has
Gain 300% of Weapon Physical Damage as Extra Damage of an Element

However, the real Voidforge has
Gain 300% of Weapon Physical Damage as Extra Damage of a random Element

Which is not a mod understood by PoB. This can lead to confusion when importing a Voidforge build.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
