### ISSUE TITLE
Error 404 When creating Pastebin link

### ISSUE THREAD

**Issue by skenarrull** [PathOfBuildingCommunity/PathOfBuilding#1635]
I have been trying to share my POB link for about 3 days now, every time I do my pastebin link has a 404 error, for example https://pastebin.com/ihVEHRSs "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff." I am using the latest version of POB and I have reinstalled it too.

**Comment by Lothrik** [comment]
Pastebin itself is automatically deleting uploads like this now. Some other text hosting service will likely be required.

Personally I'm not surprised, how Path of Building was using Pastebin was rather abusive, with thousands of people constantly uploading encoded nonsense over an API without even setting an expiration date.

**Comment by skenarrull** [comment]
So is it just deleting all of POBs at this point? I cant make a single POB work

**Comment by emeria** [comment]
I wonder how hard it would be to modify the pastebin piece of code to use hastebin or ControlC, or even add a drop down to select one of those sites and then paste from any.

**Comment by ppoelzl** [comment]
It seems like Pastebin stopped deleting build codes.
