### ISSUE TITLE
Aura Effect, DoTs, and Mines

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1636]
If you link any DoT skill (such as Essence Drain, or Toxic Rain) to High-Impact Mine, PoB currently thinks that Aura Effect (such as the 100% increased Aura Effect from Demolitions Specialist) is a direct multiplier to DoT DPS. Hit skills (such as Glacial Cascade) receive no such damage multiplier.

It would be awesome if that was actually true, but I can't find anything that suggests this behavior is correct.

![](http://puu.sh/GBMFx/1760ed8441.png)

**Comment by Wires77** [comment]
Looks like this is fixed in 1.4.170.27
