### ISSUE TITLE
Attack Speed, DoTs, Mines, and Traps

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1637]
Currently any modifiers to Attack Speed will increase the DoT DPS of skills like Toxic Rain when linked to Blastchain Mine or High-Impact Mine Support. If DoT DPS is going to factor in any type of speed for mines it should go off of the expected number of mines thrown per second, as attack speed is completely irrelevant for mines. Trap Support has the exact same issue with attack speed.

**Comment by Wires77** [comment]
Fixed in 1.4.170.27 using mine/trap throwing speed.
