### ISSUE TITLE
Cant open builds no matter what, Create new builds and cant even open those

### ISSUE THREAD

**Issue by AdrothII** [PathOfBuildingCommunity/PathOfBuilding#1638]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened? I cant open any of my builds that ive made or copied from other creators
* **What were you trying to do? trying to update or create new builds but cant open them now
* **What steps will reproduce the bug? atleast on my end saving anything or whatever i cant open any builds
* **Does it reproduce every time? If not, why so? yes it does
* **Additional information:**
i noticed that the folder its trying to access is read only but the other PoB i was using before switching to the Fork can open
all my builds and such so maybe its something on my end but i tried to remove the read only but it keeps turning itself back
on no matter what i do.

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by ppoelzl** [comment]
Could you list the folder in question, its permissions and path, as well as the permissions of the build files? Currently you do not provide enough information for us to reproduce this error.

**Comment by ppoelzl** [comment]
Closed due to inactivity.
