### ISSUE TITLE
Maximum Physical Hit Taken is calculated using incorrect logic

### ISSUE THREAD

**Issue by qikink** [PathOfBuildingCommunity/PathOfBuilding#1645]
In the Calcs tab, "Damage Taken" section, the line item for "Maximum Hit Taken" is calculated by taking your total EHP pool, and dividing it by your damage taken modifier, as it should be.

However, for physical damage, the damage taken modifier is calculated according to the hit configured in the Configuration tab. Normally this is fine, but this in the case of max hit taken definitely has issues. With a configured hit size of 1k, my character might say my max hit taken is 30k. But if my character were hit for 30k, it'd be dead several times over because my mitigation is much less effective against the 30k hit.

Expected behavior would be, given the function DT(h) which returns the damage taken modifier for a give hit size h, this line item would show the solution to the equation EHP/DT(h) = h.

**Comment by Regisle** [comment]
Known issue and on my list of things to fix, theres actually more issues with the maximum hit taken and EHP calcs which is why this hasnt been fixed yet
