### ISSUE TITLE
Storm Burst - Implement Duration Scaling

### ISSUE THREAD

**Issue by Butsuon** [PathOfBuildingCommunity/PathOfBuilding#1648]
"Exploding Orbs deal 75% of Skill Damage **_for each 0.4 seconds of remaining Duration_**, Orbs jump every 0.4 seconds". 

Skill effect duration currently causes no increases in the damage of this skill.

**Comment by Regisle** [comment]
Known issue, PR in the works for this seems abandoned #680 if you want to take a look

**Comment by uilman** [comment]
Note that the explosions are not going to be calculated for, just the impact of having more jumps per orb

**Comment by ppoelzl** [comment]
Added in 1.4.170.15.
