### ISSUE TITLE
Gem alternate quality selections aren't saved

### ISSUE THREAD

**Issue by gitdash** [PathOfBuildingCommunity/PathOfBuilding#1651]
Should be pretty easy to verify. Select any alternate quality option for a gem, save the build, exit the build [or program], reload it, and you'll notice that all the gems are back to the default option. This is on 1.4.170.14.

**Comment by rainbolts** [comment]
This is fixed in 1.4.170.15. I tested both leaving the build and closing the program. Alternate quality was preserved in both cases.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.15.
