### ISSUE TITLE
Vaal Impurity Maximum resistance increase not working

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#1652]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Using Vaal Impurity of Fire, maximum resistance is still 75%, even though that skill gives +5% to maximum
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

PoB code:

`eNrNW1tz2sgSfg6_YoqqVGVrMdboLpe9WxjfSIzDguNk9yU1lgbQWkhEGuGQrf3vp2ckgcBcBjnn1MkDEdLX956e7hE-_f37JEAzGid-FJ7VcVOpIxq6keeHo7P6p_urI7v--2-10x5h44_D89QP-JPfam9OxTUK6IwGQFdHjMQjyh4KTtpX4PRIQs9nd1E8IQC6i0Ja3Fv91qWx6wc0SYrbbkCS5I5M6Fm9S2KSejSuI5K4NPTay0ftsU-HjPhhHU3gcxC5T5Rdx1E6Bfl1NCUhG9Mo7PphFF9HXsF8cZ_8vXJ_5tPnbuQB406397F_X2jXjlNaqA-WvzntBWRO4wEjDCXwcVZvgQPJiN74DLiQIAUWSv14J_aCTOBzP3wwpdRbwLSm-b8D9mJ6ORxSl_kz2o7BD2MSuhIqH4rtpgHzp4HPY5zjcdPYRnHzgjlWtrK_jxgJLnqD_YpkyGgZQENRmjbWHGxi0zStbXSffTYGsrKMAyjPA4iFlH4c3RmFPqPS8F7kJ1F4kPUVzGhHk0c_XLXiQNLWbCSxbmJKPg6zhOwTz0-TZQ6r24i6JCTtKClFdeuqYKXs07cy7NNvZaRjbwNe0O9Lfqqzg18ZuZ1fJ1waoek72JWB2DC26zeLGFTq_Y6_9YelteYYO-qKe8LBndBd4FV9F9tPYUwTGs9K9WiHgFWKHuwZtGyrstOCPh3RpbFm01Z3yrml1B1fw6bSJ0yijPE8W-aYtdNFHFt20U6mmzykyxGsO0jVm4aJdUUzFNuydi6ZVWfh5k6JB7rqMqTxaD6ArTvwpLY_96RMIuW5MsGqLVIkh1o0I0l5JWFV3WNPRlA2xdq68LsU9gig8OjatmebP5GkF0d_850-OJCuFU-idFkPDd3ZaXkGLxuub3VVbzxPfBe2JdEp9amXuisFy94qatG1dKMZncAaEC0PtHbLEG0jPQ-giZRtXoBtEBxE0WKMuE8XkTeiBwk5iOLKj8FdiV_a9ixjP_gjNKZtMl3uMsb2fZsvqxUBR4ayH70uYUfBHo1ZCIOGvJQ1EmlR4NQoWRdjysClRfSiZ0CO-XyUHIbukmVroG2NYEzDH3Np_itwKQGXoZfGPPWkZaxTvBRzeizmR37VmUyjmImbbRK4iWDZCacpQ6EY8yZ-4n59TIdDPpzVQUQshtPLq6vL9n3n4TLXokySPPlB8DVMJ498qMj-X676ARWVBLlREJBpQmECHJIgAd4-XA447QBKqMuk8DCQ5MOcDPozid3YByfKgPk8IqWyGOlkkHzekgJCVEhA5R12P59SngGJrM_yaiaDFlOSFDIbeeQMFMOUXBioS-ZSyEXnIIW-DGjLD_gGJee1LiyEbG-Tw8NuE_uPKZPMNtHoS-nBu10pA8u9npTGWTshxTvvumSweX2XyzXYzqWjcUGHFLJYcjWLKnFPnmiY18Ci3p2KJZSgBArhNZ0k53OYpq-419bm6xXAWZ3FKfD26JCkAb__R0oCn83P6qEflO_fZqd04m4yjp4H6XSaceLLNgG_395mR1tCEXGa1hIdlPgu1BSHfAF55Iz4GSF5DLh9mQprBBzL2b05BRE59jqIHkmgLjzyrdBVqReniKpSXwHjBVjU846XNRNQmlIoY_P8do_ETCg3ohMO6VJGPMLIcYeBp465u46FVnD1QEiw7EdasEktFOmIhS48VmK8NH3NYr7P8Jb2rM55okInFA1Rpyhrrzc_k7WwnjdrS-sl7V12eNvtlTeOc_tZ1q0Hd9HDHWzjWvf3MwxdsMzXdibvNYskCSJ-fkmh4rPXLRn1kKTJyg7vVu_9Cc1cI-HWTWQlj7YCRuMQ5uNdS6MLLcQsCuhyo3-9F_9rpWbNbecBT4AKNaYgPCj9cqI1J-VXYou4jylFJDNckOC8YsOX8qsRLk8D1tArgyM1x9Hshu44lt3ApmUZcI3h2nBMxWzopmo7DVWxsdowNcfidwx4qlsYkJpp6FrD0G3Tbqi6bqkNmzPTVMXBDV3DptpQbU1TgKUODDSs2ErDVLGiAdxS9IaDHaXhGBoXCuwbAFDh0wRFQJCDlQbWLKw3sIN1vaFpuuU0NMc2gbvOuRhYBb6WCRBNsTRgC-pqQAQEDUczDEBYNiitYNxQNayqDcNWuXSQ1zAUB3TACthpOjZuGGAJGOVYFnDWFB1MNhRNb-i2DnrrmmbpdcTAy6V3WFjN30VxrxaJdulB4-jdcQeLG-U7iMJlFA8oD7KuwLyKfJfzasGIo17wTxHSDtxMjqfAGeKZHPPqcxcxnhwfocEL-d2m5yVZHLO3XX068xmkVAI1CV3F4lSbP-WqqRjikKn35o2mvEV-6MaUQAeC-HaHssWcPVaa6lte4EoPkOhbAUwSxLvAzKrjpVmZ4cfrlp9-6t9mQseMTZOT4-Pn5-fmlLBxNKTf_YA23WhSWHkkVtIR9_BxC_6dty4vWu-f288_pudju0XMO6IoD1fdI-pjOzK_4qA_nLRvvw0f0mgyMb89_9E3SO_Dl87Rn0HPvgk_PClf31vu0d1f7z_MO7c3E-tz0rdH3ZtHQ794CFhXd598e_rhwmTk05h8_WJdXKutXnqtfPlz9hfzfvy4PWrHePTts36WmVdYc5q9SSyim31b-BryHtsQVpaVgnwI3oDDWIR_H87EtqbL4HTD1iRwquo4MvxgXVuODD8NYwmYoysyXtFMU8pa1bH44tuPw44txc-0VENGP80yZLwM5U8qGpquS-EMA4qljJstx5JJFqiXMuZasA9IecXUZJIAtg8sk1O6oisycqHUW1L6YUUqlWHzk7JCc6RWGuSKKRNbx7BlgoFhn5aRC9uiKWOHauuWjFwDtm9Lag1hR8ZebOuaKVX5VNuW8rPcGtcAJ5kGUlmFLVUum03blqlV4GZTJr7Q_ZiOlP9MUyr_MBRJqZ3D0m0pubqUX7BiaFJ-cUxbbseyTFvKzwCUkgsdq0xeqZYpty5NLIMzVU1KrOlIFV3eSUtFTVM2VAOYMZbdDnyBcUJMHnze4BfQlmbdHr9ZfBHTyINPn1FCSeyOByzOD90RHQ7r6EcUTf48qx_ZatOxxOxg8Y0_O326oYR1yXQxnnFwfkKl5OdTjLALHxrhWJyuFeMSB345q9t204B_kK1YsfTsZfupGMTy-YhfD2g2sKUJHVBotr3PlEyjUNzO5GYvDQAqDufy5r5P-Px_gj7ddf74dFlrxzRhvFm-oIkf09pVkEIDjM5h3vJDymq3lIxSeoJuqJ-wWn78doJUpZY79QRd14RtffrtBBl2rTOZBr7r8ydK7Qb6bYwyaO2fmIQjeqI0jX9_fWcc2b8gFiFByxXIQCCbz5qrWE05MpRf3nJ4rsFLgsW3_KTRoyRAF1EKA0cxHJR4voOp6QgLpstBIjubRST0UH72KtKnG3l9TogEOYSwaWTHnWqRYFsR2l5E8QpSzNnLgM0gSiRkXEYuamPwojhNXML4vHQZ-N_9uNZPH-foCga6p9pDxuME9WKK1KbZVJa32mkMmcdq2VsgsH3xRF0J8jKyeC2y_-Qqnqj_gi_LbrxIY8IPiWviVWIxgHkRTWClMvQ45-MSyk7OUXZ0jryUv_LiSwvUqfXpJIKhERFYbY8ppGdIxdQGFzzd8-ceCvg9P0Ex_wUEBanZgLfKGpAxUmEZ8zWSSPha2-jrQZQGqE0YTJExd1HMfuR-LpZIJ3RTMVevel5rYuV1rletra4vpbQ438uTf0xmFL2zIcXV1RTnb8f4Tw4Q1DP_iaLsHdWa-xf88Tb-YnG9M4G_ssq_CPZmfupufhv03c0P77RfNd5CZnipy4uCiF4EpW6VVZko5QJXHud-VJUjnau1woy_A-PxnUEs-RuRRdbvXO66bEHYgTD3Iiy5oqJvT_S-P53-_-Q5Xi8x-Vt3ETLpdNXyME6imO5NrD2J4UWilpHpNJhvzIcyL_6I176F2hcrvGArI2HOJfN77vDN6-bXd2AG3wod5Rc0Id_9STopOJdJbqMkL6GF2OcxDdE8ShGoCEIICqG9IeDSMlk7CpN0AujuKmsukdfeElSYnDkKdE8Q5QfCHFeQ5Ly8TLII1itz336R2YMgKn4TIbyGSv1p8au-EqZ4OVFAcBmSNVfls-uCaalLVV8yzTClQaD4pUnep-3o0cqtWZllBkR48EymqPU4TxLhZtHvbupxN5Cuk6lyZLtR51HEkooKbbJlj1LnNGAHkmzLgk0qqZtU0qq5V84J6k8i06spaVaTJkm2yZtV8mlPBLI1fKigDZlkVpGzJ_2uA966VmGsVV9FuIo8vVou4GqZp-8Pj4xjD2W7Kb0qGi5Vd4wK-lSogdo-Md68GGcPC99mL1fKL6MKkdSSfLF9V9i_Jaw2KjtZrZAFZrV1pVVLZu3wnNOrbwIVMhxXdr4ms051GdDLjm6v2q9ohSQjWT0KZoWsrB6GV6SLbIHmtJKrRh5awXN9Ps2pVQqrWtm9FcuFfDyrmKNJ-AlXD4Ne2VtGFWtk1kv1JN-jUmuSBvRlS5RNvjBAilcY4p2A-LuCKBz6oxd_JcBHTp8fR4ifv_Cf-qHHKAooCfNNMv-Vbk59erz-V_D_AdcDVTg=`

**Comment by LocalIdentity** [comment]
Fixed in this PR for the next update https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1611
