### ISSUE TITLE
Need to add Impale Support gem

### ISSUE THREAD

**Issue by Hermitus** [PathOfBuildingCommunity/PathOfBuilding#1653]
Added in 3.7.0

**Comment by Wires77** [comment]
Impale support has been in this fork of PoB for a while, I'm guessing you're using Openarl's fork.  Please go here and install the latest version of PoB: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v1.4.170.14

**Comment by Hermitus** [comment]
Sorry.  Being new-ish to the game, I didn't realize Impale was a debuff and not a stand-alone skill.
