### ISSUE TITLE
Clarity Watcher's Eye numbers outdated

### ISSUE THREAD

**Issue by Jonsman** [PathOfBuildingCommunity/PathOfBuilding#1654]
The numbers on a Clarity Watcher's Eye mod are outdated:
'increased Mana Recovery Rate while affected by Clarity'

From GGG's tradesite:
![2020-10-14 20_34_54-Window](https://user-images.githubusercontent.com/72886841/96031700-0051af00-0e5e-11eb-8c44-495dab47303d.png)

In PoB:
![2020-10-14 20_35_52-Window](https://user-images.githubusercontent.com/72886841/96031725-0778bd00-0e5e-11eb-92b4-40a29295dc98.png)
{variant:10}
![2020-10-14 20_39_20-Window](https://user-images.githubusercontent.com/72886841/96031733-09428080-0e5e-11eb-9cc9-0e4f2f954529.png)

**Comment by Wires77** [comment]
Fixed by #1582 in the next update
