### ISSUE TITLE
tool-tip improvement

### ISSUE THREAD

**Issue by Hermitus** [PathOfBuildingCommunity/PathOfBuilding#1658]
When selecting a gem the tool-tip doesn't include information about whether it is a skill or support gem. Only *after* selecting the gem does the tool-tip describe the gem and include support info.  I think it's worth considering adding a simple line such as (support gem) or (skill gem) to the selection tool-tip, so newbs like myself know which type of gem we are looking at.

**Comment by uilman** [comment]
Like a checkmark to indicate support?

**Comment by Hermitus** [comment]
How is one supposed to know what a checkmark means? From the non-existent documentation? Once you know, you know. But before you know?   What does the '+' sign on some gems mean?  I've looked high and low for the answer.  These are the sorts of questions one gets when things are *not* clear. :)

**Comment by ppoelzl** [comment]
@Hermitus You are always welcome to create that documentation yourself. No programming skills required.

**Comment by ZzZombo** [comment]
This always bothers me. I want to see the tooltip on hover when I'm choosing gems. I do not have even a quarter of them memorized, and currently I have to pick a gem, read what it does, maybe play around with qualities, rinse an repeat.

**Comment by ppoelzl** [comment]
Added in 1.4.170.19.
