### ISSUE TITLE
Character 

### ISSUE THREAD

**Issue by TheIrregularPlayer** [PathOfBuildingCommunity/PathOfBuilding#1666]
{
    "name": "Darkist",
    "version": "3.12.4",
    "parts": [
        {
            "label": "Assassin",
            "link": "https://pathofexile.com/passive-skill-tree/3.12.4/AAAABAYBAAOWBkAG5wdjDkgPFw-rEJIWvxewG8ge8B9BH0whwCHDIzEjNiSLJpUsRi2oMjI11jY9Oyg8vT8nRQpFuUZxSotKyE7HUEJTEFRHVGJVS1fhWW1aUlvTXfJfmF-wYENh4mqMbWxuPW-ecFJ1_XaCe197w33jguSDCYRvhHeExYlridOKr4wLjDaQEZDWlPGYU5smm12btZ7EoS-iLqLZpAWmf6a-qJqw2LGQsw60DLQ4tUi3dbfWuQK5fLxvvV2-gL6KvrzDOsgMyBTKSsrTy73N6s8yz93UQtmG21nfoOEP4tXjhOUZ5oHndOjW6xTsdOyw7UHuFfJ18pf0xvVv-Jf5Zfv1-_0="
        }
    ]
}

**Comment by LocalIdentity** [comment]
No explanation of issue
