### ISSUE TITLE
Effective "Health" Pool calculation for physical damage ignores reduced damage reduction from large hits

### ISSUE THREAD

**Issue by dambrisco** [PathOfBuildingCommunity/PathOfBuilding#1668]
**Is your feature request related to a problem? Please describe.**
The `Maximum Hit Taken` calculation simply uses the effective base physical damage reduction. This is misleading. If you were to enter the value provided there into the `Enemy Hit Damage` field in the Config tab, you'll see your `Phys. Damage. Reduction` stat get reduced accordingly. The _actual_ `Maximum Hit Taken` value for physical damage should, in almost all cases, be significantly lower than it is.

**Describe the solution you'd like**
The formula for calculating `Phys. Damage Reduction` should be integrated into the `Maximum Hit Taken` formula for Physical damage.

**Describe alternatives you've considered**
N/A

**Additional context**
More than happy to provide screenshots if requested, but this is trivial should be trivial to replicate as described.

**Comment by Regisle** [comment]
Known issue, duplicate of #1645

**Comment by dambrisco** [comment]
Whoops, missed that. Closing.
