### ISSUE TITLE
New update breaks PoB fork, starts into windows command prompt

### ISSUE THREAD

**Issue by OneHellOfANight** [PathOfBuildingCommunity/PathOfBuilding#1670]
Pretty much as title says, just updated to newest version on windows 10, and it will no longer start up, goes straight into windows command prompt. Only shows "press any key" which will close the command prompt. Happens every time. Had no issues with previous versions.

**Comment by ppoelzl** [comment]
Cannot reproduce, try reinstalling.

**Comment by gkabos** [comment]
I get the same issue.
Applying update...
Updating 'C:......\Path of Building Community/SimpleGraphic.dll'

Looks to me that the slash is in the wrong direction. Could be the issue?

**Comment by sparkcomputers** [comment]
Can confirm this bug

**Comment by TheOptimisticFactory** [comment]
Upgrading from `v1.4.170.14` result in the "restart to upgrade" getting stuck at applying upgrade on SimpleGraphic.dll as reported by @gkabos 

![image](https://user-images.githubusercontent.com/2607260/96356349-5425f780-10ed-11eb-803b-1f000a87bc6e.png)

**Comment by ppoelzl** [comment]
As I already recommended above, try reinstalling and see if the issue persists.

**Comment by sparkcomputers** [comment]
> As I already recommended above, try reinstalling and see if the issue persists.

I will try this now, but what we're saying is updating through POB itself is causing this issue, what's the point of an in-app upgrade if it's not working. The vast majority of users will have this issue.

**Comment by uilman** [comment]
I just updated and didn't have this issue on win10.

**Comment by ppoelzl** [comment]
If you obtained Path of Building Community by installing via manifest update, or from one of the following releases:
* 1.4.169.1
* 1.4.169.3
* 1.4.170.2
* 1.4.170.12
you may need to reinstall it. This cannot be fixed.

**Comment by gkabos** [comment]
Reinstalled 1.4.170.14, loads as version 1.4.170.15 and was stuck on Checking..... (~5mins) for the update. Working now.

**Comment by Myojim** [comment]
Having the same issue. Tried reinstalling 3 times. Still happening every time. What information can I give to help?

**Comment by sparkcomputers** [comment]
I reinstalled, it worked until I closed it, opening it again it needed to update again and was broken.

In terms of it unable to be fixed, I think @gkabos might be right with the slash in the directory

**Comment by ppoelzl** [comment]
@Myojim I'd need your operation system including version number, installer version and install path.

**Comment by Myojim** [comment]
Windows 10 Home edition
2004 version
OS build 19041.508
Experience pack 120.2212.31.0

C:\Users\jim\AppData\Roaming\Path of Building Community

**Comment by heinz408** [comment]
i have same issue, i tried reinstalling 1.4.170.14 through the zip file a few times but still get the cmd prompt saying "press any key to continue.."

**Comment by dclamage** [comment]
@Myojim @heinz408 and anyone else having the issue: Can you check if you have any kind of virus scan / computer security software that could be blocking SimpleGraphic.dll from being replaced?

Either way, what is the timestamp and size of your SimpleGraphic.dll in your installation directory?

**Comment by Myojim** [comment]
@dclamage I don't have any extra security software installed. Just windows security.

Date modified: 10/17/2020 10:19PM
Size 1,109 KB

**Comment by dclamage** [comment]
@Myojim OK, it looks like the update to the DLL was applied. So to clarify, when you try to run PoB it hangs on a command prompt like TheOptimisticFactory's screenshot above?

**Comment by Myojim** [comment]
@dclamage No I haven't had the same issue as TheOptimisticFactory. I get the command prompt with "Press Any Key" which then closes when I press a key, same as the OP and heinz408.

**Comment by dclamage** [comment]
@Myojim Can you try installing the Visual Studio 2019 redistributable? It is the first x86 link from this page: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

The link should be this, but feel free to grab it straight from there if you don't trust my link: https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by Myojim** [comment]
@dclamage Woo! That seems to have done it. Thank you sir! 👍

**Comment by heinz408** [comment]
downloading that works!

**Comment by techpta** [comment]
Problem solved!
Just add in the readme.md that it requires the installation of (https://aka.ms/vs/16/release/vc_redist.x86.exe) so Path of Building can work.

=]

**Comment by techpta** [comment]
And I think this issue can be closed

**Comment by Arandomnameok** [comment]
This didnt fix it for me, installed it and the same thing persists. Uninstalled the newest and installed it nothing, installed the older version still nothing because it basically forces to the lastest update which is this one that's broken.

**Comment by zedzedUK** [comment]
I'm the same as Arandomnameok - installed the new VS2019 as above, and I still hangs when updating the "SimpleGraphic.dll"

I downloaded this a good while ago, completed many "in-app" upgrades. i.e. clicking the link that says "update ready".  This is the first that has failed.

**Comment by LocalIdentity** [comment]
Try running PoB with admin privileges,  that has fixed it for some people

**Comment by zedzedUK** [comment]
> 
> 
> Try running PoB with admin privileges, that has fixed it for some people

I ran as admin, and this time I can see the CMD window with the original SimpleGraphic.dll message flash past, and then I get to a new CMD window with "Press any key to continue ...".  After this - nothing - so I restart PoB and I'm still v1.4.170.16.  Weird though ... it's now saying no update available, and when I check check for updates I'm on most recent version.

**Comment by Arandomnameok** [comment]
I ran it as admin and no changes.

I can't play poe for now until this gets sorted out somehow, hope you guys catch whatever it's doing this since it was working fine before this update!

**Comment by CalamityAngel** [comment]
just updated it myself and it downloaded the patch and installed it but
the mouse pointer is highlighting about 2cm above where it is on the screen.
everywhere else its fine :(

**Comment by dclamage** [comment]
@CalamityAngel Can you create a separate issue for this and provide more details about your OS and anything else which might be relevant? For example, if you're running a special theme, monitor resolution, DPI, or something else like that.

**Comment by OneHellOfANight** [comment]
Downloading the mentioned link fixed it for me. Cheers.  https://aka.ms/vs/16/release/vc_redist.x86.exe
