### ISSUE TITLE
Thread of Hope does not display radius when socketed into Cluster Jewels

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [PathOfBuildingCommunity/PathOfBuilding#1671]
After updating to 1.4.170.15, the Thread of Hope jewel no longer crashes when it is used in a cluster jewel, however the radius from the Thread of Hope is not displayed when it is socketed into a cluster jewel.

A reproduction image can be seen here:

![Thread](https://user-images.githubusercontent.com/31759736/96357107-ee654b80-10ab-11eb-9243-9dc706ff20bb.PNG)

And the build can be found here: https://pastebin.com/nBZdNmSc

**Comment by ppoelzl** [comment]
Cluster jewel sockets are not considered to be in range of any passive skill.
