### ISSUE TITLE
Aura Effect from Purposeful Harbinger not added in Calcs Tab

### ISSUE THREAD

**Issue by jix91** [PathOfBuildingCommunity/PathOfBuilding#1673]
Purposeful Harbinger:
Aura Buffs from Skills have 8% increased Effect on you for each Herald affecting you, up to 40%.

If you gain Aura's from other character's this acts as a multiplier. For the user itself it is just regular Aura effect and additive with all the other Aura effect.
It would be easier to see/calculate your breakpoints on Aura effect if this was added to the Aura Effect overview in the Calcs tab.

![image](https://user-images.githubusercontent.com/61379609/96366928-07710980-114b-11eb-9065-dca6cbfd1af6.png)

Thanks!

**Comment by Meller127** [comment]
Any work being done on this bug?, still exists in 2.8.0.

**Comment by FlyingThunder** [comment]
This bug also affects Introspection.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4977.
