### ISSUE TITLE
Close Combat is not activating the Melee Distance check in Config

### ISSUE THREAD

**Issue by corosou** [PathOfBuildingCommunity/PathOfBuilding#1675]
* **What happened?**

Adding "Close Combat" as a link is not enabling the option to select melee range distance in Config

* **What were you trying to do?**

Import my Heist character to check Close Combat calc
Loading a save with the melee range already enabled also does not show the checkbox in Calcs, but the calculation is being applied

* **What steps will reproduce the bug?**

Add Close Combat as a link
Load a PoB Export that previously had Melee Range ticked in Config

* **Does it reproduce every time? If not, why so?**

Ever since the patch that broke the update and I had to download the full installer.

* **Additional information:**

No errors at all

![image](https://user-images.githubusercontent.com/28074748/96378063-a439a400-1157-11eb-9ff4-a381bebbc51d.png)
![image](https://user-images.githubusercontent.com/28074748/96378080-b7e50a80-1157-11eb-97b5-f6bed250bff4.png)

**Comment by corosou** [comment]
I have an update on this bug. Importing a character with Close Combat as a link may or may not automatically enable the Melee Range check in Config, but if it doesn't, just moving the skill around in the Socket Groups order seems to reset something and then it starts working:

Upon Import:
![image](https://user-images.githubusercontent.com/28074748/96878416-d2193400-1448-11eb-86f0-1daac7386083.png)

After Moving the Skill to the top of the Socket Groups list:
![image](https://user-images.githubusercontent.com/28074748/96878470-e78e5e00-1448-11eb-9074-eb9a199eeae6.png)

**Comment by Kroohpyyh** [comment]
Melee distance is also missing from Slayer's Impact ascendancy node if the skill isn't top of the list like Corosou commented 4 days ago.

**Comment by nahuelleiva** [comment]
The bug still persists even if the skill is on top of the list, I've opened a new issue #1710

**Comment by DavidStrid** [comment]
Melee Distance to enemy showing seems to be connected to whether or not the currently selected socket group in the calculations tab contains a melee skill or not. Give that a try to see if it resolves the issue for you too.

Screenshots from Nahuelleivas pob link
![bild](https://user-images.githubusercontent.com/75178050/100524007-e32a3300-31b4-11eb-9098-c0e554a71014.png)
![bild](https://user-images.githubusercontent.com/75178050/100524048-24224780-31b5-11eb-8db0-e20c340ee286.png)

**Comment by ppoelzl** [comment]
See #1710
