### ISSUE TITLE
Support for Skeletal Archer Dps From Phantasmal Summon Skeletons

### ISSUE THREAD

**Issue by wkingston1248** [PathOfBuildingCommunity/PathOfBuilding#1676]
Currently you have the option to find the damage of a normal skeleton and a skeleton caster when using the summon skeletons skill, however you can't select a skeletal archer. It would be very helpful if it was possible to also select skeletal archer, especially since the normal skeleton won't properly use ranged support gems like viscous projectiles.

**Comment by Wires77** [comment]
Will be fixed by #2147

**Comment by Wires77** [comment]
Fixed in 1.4.170.27
