### ISSUE TITLE
Black Bars on Program Screen

### ISSUE THREAD

**Issue by CalamityAngel** [PathOfBuildingCommunity/PathOfBuilding#1679]
Running version 1.4.170.16

Downloaded the new patch and now have black bars on the bottom and right side of the program

downloading patch, didn't touch anything 

not sure how you would reproduce it since i had no input
 
Yup its stuck like that even if i close the program, uninstall and reinstall it
if i install the original PoB it goes back to normal but wont open any builds cause it doesn't recognize community forks changes
and goes back when i reinstall fork
![Capture](https://user-images.githubusercontent.com/73081172/96412362-8eef7300-1246-11eb-8574-70c21ae9f98a.JPG)
![hk](https://user-images.githubusercontent.com/73081172/96412378-944cbd80-1246-11eb-86e3-848f67e83587.JPG)

**Comment by dclamage** [comment]
Your laptop seems to be quite out of date. It's on an old service pack of 32-bit Windows 7. Is it possible to see if an updated Windows 7 fixes your issue?

**Comment by CalamityAngel** [comment]
Nope it didn't work.
as i said i dont have the problem with the original PoB or your 1.4.170.14 version which i would go back too if i knew how to disable the auto update on installing it.
for some reason the UI is up and to the right instead of being locked in center or auto fitted to sit inside the window

**Comment by ppoelzl** [comment]
We will not commit to offer support for discontinued operating systems like Windows 7. As far as I'm aware, this issue doesn't exist on Windows 8/10. If anything, I'd advise you to upgrade for security reasons alone. Otherwise, you're on your own.
