### ISSUE TITLE
Malachai's Artifice doubles up on Elemental Equilibrium

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#1680]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
I was trying to create an ignite build based around big lighting damage from Stormfire and Malachai's Artifice was suggested as the best ring in my other slot.
* **What steps will reproduce the bug?**
Create a build that ignites and path to EE, selecting lightning/cold as the hit-by damage.  Notice that both EE and Malachai's Artifice are affecting the Effective DPS for ignite.
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
![image](https://user-images.githubusercontent.com/1209372/96524170-1df78d80-123d-11eb-85d1-65cb8015f897.png)
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

https://pastebin.com/kVk3y9QP is the minimal build that reproduces the issue

**Comment by uilman** [comment]
Probably just need to move the mods into a flag check instead of parsers

**Comment by Wires77** [comment]
Fixed by #1849 in v1.4.170.22
