### ISSUE TITLE
Suggestion: Use self host instead of pastebin

### ISSUE THREAD

**Issue by jeanroyce** [PathOfBuildingCommunity/PathOfBuilding#1683]
**Is your feature request related to a problem? Please describe.**
Recently pastebin is marking PoB code as spam, deleting them.

**Describe the solution you'd like**
I was thinking about something like a selfhost pastebin but exclusive for Path of Building, accepting only valid code.
![Sem título](https://user-images.githubusercontent.com/8617825/96807536-34dce200-13ed-11eb-9821-938b5f9769d2.png)
Maybe something like this, a page with a basic preview about the build, with a button that works like a zoom meet (automatic open path of build and import build), but not removing current import workflow (you can still direct paste build link on PoB)

**Additional context**
I know there is a cost behind a site like this, my solution is to use a non-intrusive ad system but i dont know if is something cool or even if the ads can pay enough to keep cost balance.

~~sorry, english is hard~~

**Comment by ppoelzl** [comment]
If at all, we would implement this quite differently than you are suggesting here. Also please not that pastebin.com stopped deleting new build codes.
