### ISSUE TITLE
incrs% melee damage nodes not scaling ignite damage?

### ISSUE THREAD

**Issue by azaryc2s** [PathOfBuildingCommunity/PathOfBuilding#1684]
So i'm not sure, if i'm missing something, but in my vigilant strike ignite build, when i pick up nodes like "incrs% melee physical damage", with 90% phys -> fire conversion, it does add to the fire dmg dealt, but this seems to have no effect on the ignite damage (the base damage taken into account doesn't change). So is it somehow bugged, or am i missing some mechanic?

**Comment by azaryc2s** [comment]
The same happens for bleeding with pure phys dmg. Those nodes do not increase the bleeding dps

**Comment by azaryc2s** [comment]
I'm starting to think that i misunderstood the mechanic...i thought the damage will be dealt on the mob, and based on the damage it received, the bleeding dmg is calculated, but it looks like it doesn't matter what the actual damage dealt on the mob is -> the bleeding dmg is just based on the base dmg of the weapon (before global increases). At least this is the behaviour in PoB - but does it really work like this in game? The same goes for "overwhelm % physical reduction" -> this also seem not to effect the bleed dps, but if the bleed dmg depended on the actual damage dealt, it should also increase...i'm confused

**Comment by uilman** [comment]
https://pathofexile.gamepedia.com/Ailment#Damage_with_ailments

**Comment by azaryc2s** [comment]
Well okay, this confirms my "suspicion" - why i missed this page is beyond me - was reading all the specific descriptions on bleed ignite etc. So the question i have left is: does the crit chance roll separately for bleed/ignite when calculating its damage? Cause based on the wiki, there is no real dependency on the actual hit, which is imo completely different from what you would normally expect...(in the actual game - not PoBs fault ofc if they implemented it like this ^^)

**Comment by PJacek** [comment]
Read the wiki page and linked forum post by Rory. Critical strikes add a 50% damage multiplier. You can use Perfect Agony to convert normal crit multi into this stat. 
![1](https://user-images.githubusercontent.com/18018499/97014626-df1e4c00-154a-11eb-9188-75134f5804e6.png)

**Comment by azaryc2s** [comment]
Ok this is turning more into "i don't get this mechanic" than something PoB is doing wrong. I'd have to clarify this somewhere else. But thanks for the crit chance explanation - didn't know that. My question still remains though, if it depends on the actual attack criting or if the applied bleed rolls it's own crit - but if all it does is just add a DoT-Multiplier of 50% and doesn't scale up the base dmg, then the question is irrelevant and makes no real difference i guess. The only difference would be, that you could not crit with the attack but apply a higher bleeding, cause the bleeding itself rolled as a crit.

Sorry for the false issue then and thanks for your answers!
