### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Iceteaisgood** [PathOfBuildingCommunity/PathOfBuilding#1686]
Hello and thanks for looking at this 

i just downloaded the latest version of path of building (1.4.170) when i clikk new build -> import/export -> import from pastebin (it then says code is valid) when i then click the import button i get this error message.

![error](https://user-images.githubusercontent.com/73348276/97010320-84362600-1545-11eb-8537-e06b9cabcf9c.png)

Sorry for bad english its not my native language
Hope you can help.

**Comment by Wires77** [comment]
The latest version of this fork is 1.4.170.16, it sounds like you're using the Openarl fork of PoB.  Please download and install the latest version from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v1.4.170.16

**Comment by Iceteaisgood** [comment]
Thank you it worked i had downloaded a wrong version.
