### ISSUE TITLE
1.4.170.16 update broken

### ISSUE THREAD

**Issue by noraj** [PathOfBuildingCommunity/PathOfBuilding#1688]
I have 1.4.170.16 installed, the last version available in the release section. 

But I still have the option to update.

![image](https://user-images.githubusercontent.com/16578570/97049803-92536900-157c-11eb-94f0-dc4be94678f3.png)

But the changelog doesn't show any new version:

![image](https://user-images.githubusercontent.com/16578570/97049852-a7c89300-157c-11eb-8590-cb93e5a047b1.png)

And when trying to update it bugged I have this window that is doing nothing for hours.

![image](https://user-images.githubusercontent.com/16578570/97049924-c9297f00-157c-11eb-8322-74f239067a92.png)

**Comment by ppoelzl** [comment]
Known error, fixed by reinstalling our latest release.
