### ISSUE TITLE
SkeletonMages has no Crit Chance (Lightning and Cold)

### ISSUE THREAD

**Issue by xxxhadesxxx** [PathOfBuildingCommunity/PathOfBuilding#1689]
Hi,
im use Version 1.4.170.16 

I think the calculator should calculate the damage (Lightning and Cold) from the SkeletonMages wrong. In both cases no Crit Chance is given. It is set to 0%. But with fire the crit is displayed correctly.

I use only a Witch - Necromancer with a Dead Renocking Jewel and Skill gem VaalSummonSkeletons.

Calcs -> VaalSummonSkeletons -> Show Minion Stats "Yes" -> Summon Skeletons Caster -> Minion Skill "Cold or Lightning Projectile" -> orange Box Crits: 0% x XXX 

In the path Data/3_0/Skills/minion.lua under "SkeletonMinionProjectileFire" the BaseCrit chance is given as 5. But for "SkeletonMinionProjectileLightning" and "SkeletonMinionProjectileCold" this value is missing.

Can you fix it for all? Or is that not a bug?

Kind Regards 
xXxHADESxXx

**Comment by ppoelzl** [comment]
Only fire-based skeleton mages can crit.
