### ISSUE TITLE
Berserker's Warbringer exerted attack bonus damage is not applied to attacks exerted by General's Cry

### ISSUE THREAD

**Issue by cashoes** [PathOfBuildingCommunity/PathOfBuilding#1690]
* **What happened?**
Berserker's Warbringer ("Exerted Attacks deal 50% more Damage if a Warcry Sacrificed Rage Recently") does not provide any additional damage to attacks supported by General's Cry Support.

* **What were you trying to do?**
Building a General's Cry Earthquake Berserker.

* **What steps will reproduce the bug?**
Berserker's Warbringer 50% more damage bonus is usually assumed to be active if a suitable skill is selected (e.g. Earthquake) and a means of exerting attacks present (e.g. Seismic or Intimidating Cry).
Replace Seismic/Intimidating Cry with General's Cry and note that Warbringer no longer provides it's bonus damage. General's Cry Support includes the line: "Attacks with Supported Skills count as Exerted."

* **Does it reproduce every time? If not, why so?**
Steps above should work every time.

* **Additional information:**
N/A

**Comment by uilman** [comment]
General's Cry is still not actually supported.

**Comment by gvach11** [comment]
Came here to report this, it's not just the Warbringer node, the small nodes on exert cluster jewels also don't count as any damage at all, makes it impossible to calculate actual damage of General's Cry supported skills.

**Comment by Nostrademous** [comment]
Fixed in #2294

**Comment by Nostrademous** [comment]
Fixed in 2.0.0
