### ISSUE TITLE
Can no longer see "does minions have x charges"?

### ISSUE THREAD

**Issue by polo2005x** [PathOfBuildingCommunity/PathOfBuilding#1691]
after updating to last version, i can no longer see the checkbox for any charges for minions?

**Comment by ppoelzl** [comment]
Cannot reproduce. Please provide a build code that exhibits your described behaviour.

**Comment by polo2005x** [comment]
ex 1: https://pastebin.com/EZxu7ezt
ex 2: https://pastebin.com/gxwWmDNT

**Comment by polo2005x** [comment]
ex1 screenshot
![image](https://user-images.githubusercontent.com/72583826/97120576-57863800-1718-11eb-9327-86eee9a8966a.png)
ex2 screenshot
![image](https://user-images.githubusercontent.com/72583826/97120570-4d643980-1718-11eb-9268-7151758fdac1.png)

pob community fork v 1.4.170.16

**Comment by Wires77** [comment]
Try changing your skill selected in the Calcs tab to a minion skill.  That seemed to work for me

**Comment by ppoelzl** [comment]
Configuration options are dependent on your main skill calculations. This is intended behaviour.

**Comment by FWidm** [comment]
I can reporude this on my Domblow Char with v1.4.170.16
PC: `FaustVIII` > SSF Heist `WhereNextToConquer`

![grafik](https://user-images.githubusercontent.com/3480240/100362609-f0e88880-2ffb-11eb-88b7-29f026eb1aad.png)


When adding skele gem on this pob it won't bring up charges as well:

![grafik](https://user-images.githubusercontent.com/3480240/100362795-2c835280-2ffc-11eb-8288-c85a5869e4d0.png)

When opening a new build and adding skele gem it shows as usual
