### ISSUE TITLE
Max Lighting Resist incorrect in Calcs Window

### ISSUE THREAD

**Issue by Maldini999** [PathOfBuildingCommunity/PathOfBuilding#1692]
https://imgur.com/a/lLGm5gy

In the first image in the above link, look in the left hand column for Lightning Resist.  It is listed as 85 (which is correct)
Now look in the same image, look on the far right where the mouse is and you will see Lightning Resist is listed as 84.

I believe the one on the right is missing the +1 to Lightning Max taken from the node Unnatural Calm, as shown in the second image in the above link.

**Comment by ppoelzl** [comment]
Please provide a build code. Without it, we're not able to investigate your reported issue.

**Comment by Wires77** [comment]
The issue is you're viewing the stats in the Calcs tab for your Carrion Golem, which does not benefit from Unnatural Calm.  If you uncheck "Show Minion Stats" the two resistance values should agree.
