### ISSUE TITLE
Incorrect quality breakpoint on Less Duration Support

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#1694]
Hello,

The breakpoints for less duration on the support gem happen at incorrect points. It jumps from 60% to 61% between 20% and 21% quality, and from 61% to 62% from 22% to 23% leading to a total 62% less duration compared to 61% ingame. The same is true for values below and above these.

**Comment by Wires77** [comment]
Less Duration only goes up to 59% less Skill Effect Duration at 20/20.  Please share a build link or character so we can see what else your character is using.

**Comment by Aggnog** [comment]
Well of course it does but this has nothing to do with a 20/20 gem as I hate clearly stated above. A 21/23 gem in game is 61% less duration, a 21/23 gem in POB is 62% less duration on a completely empty profile. I don't know how I can make this any more clear for you.

**Comment by Wires77** [comment]
For starters, mentioning that the gem you were looking at was level 21 _at all_ would've be incredibly helpful, if not mandatory, as a level 20 gem cannot "jump from 60% to 61% between 20% and 21% quality".  This is why I asked for a pastebin link so I can see for myself what things you left out of your initial description of the issue.

**Comment by Aggnog** [comment]
Sorry, looking at it now it wasn't very clear. As the issue was the quality bonus rounding up instead of down I didn't think it was relevant at the time. Thanks for the quick fix.
