### ISSUE TITLE
Divergent Ensnaring Arrow not calculating inc. spell damage taken by the enemy

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#1695]
When selecting "enemy is moving" or choosing the amount of snares on the enemy whilst both Ensnaring Arrow and Spell are active, the average hit and other dps calculations of the spell do not increase in value.

It should work exactly like unnerve checkbox does at 20% quality.

Tested in both my own build and a clean testing environment with just an active spell and divergent EA.

**Comment by pundm** [comment]
Provide PoB pls.

**Comment by Lothrik** [comment]
Fixed by #2330.
