### ISSUE TITLE
Low-prio crush with Power Report

### ISSUE THREAD

**Issue by pda898** [PathOfBuildingCommunity/PathOfBuilding#1699]
* **What happened?** Crush on pressing power report button
* **What were you trying to do?** Looking for power report functionality 
* **What steps will reproduce the bug?** Open empty build, enable node power for Total DPS, show top node + power per point and press report button.
* **Does it reproduce every time?** Yes
* **Screenshots:** [stacktrace](https://prnt.sc/v9smls)

**Comment by Wires77** [comment]
This happens when you click Power Report before the passive tree is done highlighting nodes.  It's a known issue, but one we will fix at some point.  In the meantime, if you wait long enough for the node highlighting to be done, the Power Report function should work again.

**Comment by Wires77** [comment]
Fixed in 2.0.0
