### ISSUE TITLE
Failing to update - Windows 10

### ISSUE THREAD

**Issue by gozo1** [PathOfBuildingCommunity/PathOfBuilding#1703]
Hi,

I have the same issue as this linked comment from another report:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1678#issuecomment-717266342

Windows 10.
Same screen appears each and every time I try to update. Sits at the black screen and nothing happens.

I'll probably just export my builds, reinstall and then reimport the builds. Haven't done this before, but I'm sure it's pretty straightforward.

I am on version 1.4.170.16 but the update is saying the same version? Maybe just a bug with the update process itself?

**Comment by ppoelzl** [comment]
Known problem, you will have to run Path of Building as administrator or reinstall from the latest release.

**Comment by noraj** [comment]
@ppoelzl 
![image](https://user-images.githubusercontent.com/16578570/100225224-27e86c80-2f1e-11eb-8087-de82e937a6e4.png)

I have the latest version 1.4.170.18 (no newer in the changelog). But it shows there is an update available.

Also the last git tag and github release is 1.4.170.16 so I can't reinstall with a new binary that fix an update bug or so.
