### ISSUE TITLE
PoB not updating

### ISSUE THREAD

**Issue by DntBlnk4Phonebx** [PathOfBuildingCommunity/PathOfBuilding#1704]
Every time I try to update to the latest version of PoB Community Fork, it opens and sits on screenshotted screen and does not update.  I would just redownload app, but don't want to have to pastebin in all my builds again.

Help p&ty.
![PoB update not working](https://user-images.githubusercontent.com/73758719/97788687-bcaeb300-1b88-11eb-9a02-462f6a9b4ab9.png)

**Comment by coldino** [comment]
Reported in #1678, #1688, #1703 and others.

This is a known issue that can be bypassed by running PoB once as admin while it updates, or by simply uninstalling/reinstalling. Reinstalling should not remove your builds, but if you are worried you can simply navigate to the builds directory and back them up.

**Comment by DntBlnk4Phonebx** [comment]
Thank you!
