### ISSUE TITLE
Quality on default Dominating Blow affects player damage instead of minion

### ISSUE THREAD

**Issue by VitorCBSB** [PathOfBuildingCommunity/PathOfBuilding#1705]
Running on the latest version (1.4.170.16 as of this issue's creation). 

Changing the quality of the Dominating Blow gem changes the player's damage even though it's stated as "Minions deal X% increased damage" for X% quality. This is pretty simple to reproduce, but [here's a code with nothing but a level 20 Dominating Blow gem](https://pastebin.com/mgiS3c3G). Observe the player and minion damage as you change the quality from 0 to 20 (or whatever other number). Minion damage is unaffected, but player damage is changed, happens on all sentinel moves.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.19.
