### ISSUE TITLE
Can't copy gem links

### ISSUE THREAD

**Issue by BuHoGPaD** [PathOfBuildingCommunity/PathOfBuilding#1706]
Build https://pastebin.com/ghqXidJD
When try to Ctrl+C any gem link - get crash
![image](https://user-images.githubusercontent.com/31807434/97815706-ab54cc00-1c98-11eb-98b6-e40c42f05ed0.png)

**Comment by ppoelzl** [comment]
We're unable to reproduce this error.

**Comment by BuHoGPaD** [comment]
I've updated my PoB to latest version and still crashes when I press Ctrl+C on any link in this build.

![image](https://user-images.githubusercontent.com/31807434/113127548-8baed900-9221-11eb-8839-0f8bc926700c.png)
