### ISSUE TITLE
In-game resist does not match POB resist

### ISSUE THREAD

**Issue by jezznar** [PathOfBuildingCommunity/PathOfBuilding#1709]
* **What happened?**
When I check my in-game resist I'm literally over cap, but POB shows less.
I don't have any resist aura at all.

* **What were you trying to do?**
Check resist between POB and in-game values

* **What steps will reproduce the bug?**
Just check the resist.

* **Does it reproduce every time?**
No, only in one of my characters.

* **Provide a build code:**
https://pastebin.com/M33PwVwk

* **Screenshots:**

POB:
![image](https://user-images.githubusercontent.com/13676977/97983057-a5cdc200-1e0f-11eb-9092-4af5f92ac875.png)

In-game:
![image](https://user-images.githubusercontent.com/13676977/97983094-b5e5a180-1e0f-11eb-923a-28789e436866.png)

**Comment by Regisle** [comment]
Firstly your passive tree is a level 71 tree, part of that is that your cluster jewels arnt allocated, but even if I add those your still only at an 87 tree, im guessing you have Alira as well (which puts your resistances to the same value as ingame) but your still missing a point (go type /passives ingame)

**Comment by jezznar** [comment]
@Regisle you're right. I've taken Alira, I forgot to set Alira as bandit and yes I'm missing 1 (+2 coz I'm gonna take alira off).
