### ISSUE TITLE
Close Combat Support gem not recognized in PoB

### ISSUE THREAD

**Issue by nahuelleiva** [PathOfBuildingCommunity/PathOfBuilding#1710]
* **What happened?**
After importing my build into PoB, Close Combat Support is not recognized. The "Melee distance to enemy" option is not available in the "Configuration" tab.
* **What were you trying to do?**
Trying to calculate my Vaal Double Strike DPS from my Champion character.
* **What steps will reproduce the bug?**
Select "Import/Export build", set "Educmack" as the character's account name. Click on "Start", select "Heist" as the league, select "DSHeistShit" (is the only character I have currently in Heist league). Only import "Items and Skills", after doing that the "Melee distance to enemy" option is not available anymore, even after setting Vaal Double Strike as my main DPS skill.
* **Does it reproduce every time?**
Yes.
* **Provide a build code:**
https://pastebin.com/ahS6Pp7g (current tree)
* **Screenshots:**

> Vaal Double Strike with Close Combat Support in links
![VDS with Close Combat Support in links](https://user-images.githubusercontent.com/35842291/98052361-d19f7680-1e14-11eb-8eb4-cd7a6f2a662a.png)

> Configuration tab where the "Melee distance to enemy" option is not available
![Configuration tab](https://user-images.githubusercontent.com/35842291/98052263-7cfbfb80-1e14-11eb-9dbd-3ea514a3f4ee.png)

For more information:
* System: Windows 10
* PoB Version: PoB Community Fork Version 1.4.170.16 (released 16 days ago)

**Comment by corosou** [comment]
I just want to clarify that I didn't say moving it to the top of the list was the solution.

What I originally said was: 

"... just moving the skill around in the Socket Groups order seems to reset something and then it starts working"

Sometimes the main skill gets added to the top immediately, sometimes not, so if yours gets listed by default at the top on import, just move it down a few spaces down and that may reset whatever it is that isn't being set on import.

**Comment by nahuelleiva** [comment]
@corosou yet I did what you said, either if Close Combat is on top of the list or moving it around the Socket Group the Melee Distance option in the Configuration tab is not available. The bug still persists today.

**Comment by nahuelleiva** [comment]
Any news about this? Close Combat still not recognized in the Fork version...

**Comment by DavidStrid** [comment]
Melee Distance to enemy showing seems to be connected to whether or not the currently selected socket group in the calculations tab contains a melee skill or not. Give that a try to see if it resolves the issue for you too.

Screenshots from Nahuelleivas pob link
![bild](https://user-images.githubusercontent.com/75178050/100524007-e32a3300-31b4-11eb-9098-c0e554a71014.png)
![bild](https://user-images.githubusercontent.com/75178050/100524048-24224780-31b5-11eb-8db0-e20c340ee286.png)

**Comment by nahuelleiva** [comment]
@DavidStrid glad to know this could be a solution. I'll give it a try and I let you know. Thank you!

**Comment by nahuelleiva** [comment]
@DavidStrid yes, it worked! Previously, I remember that PoB automatically set the main skill in the Socket Group, maybe with the new version you have to do it manually. Shouts to @corosou too because I misunderstood what he previously said and he was also on the right track providing the same solution.

Thank you to both of you!
