### ISSUE TITLE
Rounding mismatch of buff durations vs in-game stats

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#1711]
Hello, 
For the example I'm using a saqawal tornado build with different primary and secondary buff durations on aspect of the avian. 
You can see all the stats used here https://i.imgur.com/FA8qvtW.png and the individual durations as follows:

https://i.imgur.com/W74O560.png

https://i.imgur.com/KzjZNFw.png

Now the primary duration is not correct as you have 2.00 x 0.06 = 0.12, however POB shows 0.11seconds duration

The secondary duration is correct, 2.04 x 0.06 = 0.1224sec rounded down to 0.12. 

I assume there is an issue where rounding occurs incorrectly.

For reference the ingame tooltip shows 0.12sec on both of them https://i.imgur.com/K4gC3qm.png

As an additional feature related to this I believe the server tick rounding should be implemented for buff durations as well. 

Best regards

**Comment by Regisle** [comment]
0.15 * 0.38 = 0.057 which for display reasons was rounded up to 0.06
possibly the game rounds up somewhere we dont but where in the chain that is I dont know, or more likely the game rounds up the displayed duration and it is actually less than 12

**Comment by ppoelzl** [comment]
This seems to be a display issue within Path of Exile itself.
