### ISSUE TITLE
Build Save Path is Cleared After Closing Application

### ISSUE THREAD

**Issue by dshulman130** [PathOfBuildingCommunity/PathOfBuilding#1713]
Every time I close Path of Building the build save path clears. The next time I open it, I have to reselect the build save path in explorer.

Version 1.4.170.16

**Comment by ppoelzl** [comment]
This is likely a permission issue; try running PoB as administrator once. That should properly create a configuration file to save your build folder path. However, for best results we recommend reinstalling the latest release, which should fix your particular issue.
