### ISSUE TITLE
Sigil Of Power Helmet Crit Chance enchantment not functioning.

### ISSUE THREAD

**Issue by MichaelJCU** [PathOfBuildingCommunity/PathOfBuilding#1717]
When I add the "Sigil of Power's Buff also grants 30% increased Critical Strike Chance per Stage" enchantment, my damage/crit chance does not increase. 
With Enchant
![image](https://user-images.githubusercontent.com/13550445/98465228-ef594b00-221b-11eb-9abc-2ac66f973c1e.png)
Not appearing in calc menu with other sigil buffs
![image](https://user-images.githubusercontent.com/13550445/98465301-6393ee80-221c-11eb-8e4a-7610cbc394e0.png)
With other enchant to show lack of change
![image](https://user-images.githubusercontent.com/13550445/98465248-1b74cc00-221c-11eb-88d6-5944ec0d0fdf.png)

**Comment by Wires77** [comment]
In general, red text in PoB means the mod is currently unsupported.  Also, adding a pastebin link is helpful for testing, so please follow the issue template when submitting an issue.

That being said, this is an easy mod to add, so I've done so.
