### ISSUE TITLE
"inventoryId": "Trinket"

### ISSUE THREAD

**Issue by afq984** [PathOfBuildingCommunity/PathOfBuilding#1721]
**Is your feature request related to a problem? Please describe.**
Support `"inventoryId": "Trinket"` which was introduced in 3.12, https://pathofexile.gamepedia.com/Trinket
It takes the bottom-left slot.
![Screenshot_2020-11-12_20-20-19](https://user-images.githubusercontent.com/4318379/98939621-adcee580-2524-11eb-91fd-64fadad0a120.png)

**Describe the solution you'd like**
Maybe have `["Trinket"] = "Trinket"` added here: (not sure if the mapped slot name must match something)
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/68414f7722163aa10d8ef92ff7e50a74968f410f/Classes/ImportTab.lua#L578
Probably there's other work to properly support trinkets?
(Disclaimer: I no longer play this game, please forgive me if I've got this horribly wrong :/)

**Describe alternatives you've considered**

**Additional context**
Example data
```
curl 'https://www.pathofexile.com/character-window/get-items' \
    --data-raw 'accountName=TheAgonizingEnd&realm=pc&character=OokOokShootShoot' \
    --compressed > get-items.json
```
backup: [get-items.json.gz](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/5530524/get-items.json.gz)

**Comment by Wires77** [comment]
Trinkets don't affect a build in any way outside of Heist-specific content, so we won't be adding them to PoB.  This is already the case for league-specific content, like "against abyssal monsters" mods, and would fall outside of the project's scope.
