### ISSUE TITLE
Catalyst Calculation Error

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1723]
Catalysts do not correctly scale values past certain thresholds.

Example:
0.8% of Physical Attack Damage Leeched as Mana turns into 0.10% instead of 1.0% after 20% quality from Fertile Catalysts.
![](http://puu.sh/GMUJk/7f77c229d1.png)

**Comment by ppoelzl** [comment]
Duplicate of #838
