### ISSUE TITLE
Anointing No Witnesses

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1724]
* **What happened?** Anointing No Witnesses does not allocate the notable correctly on the skill tree. 
* **What were you trying to do?** N/A
* **What steps will reproduce the bug?** Anoint No Witnesses, look at No Witnesses on the skill tree.
* **Does it reproduce every time?** Yes
* **Provide a build code:** https://pastebin.com/rTJiDjsb
* **Screenshots:**
![](http://puu.sh/GN0sP/988b943ced.png)
![](http://puu.sh/GN0s8/52df81c1a7.png)

**Comment by ppoelzl** [comment]
Please fill out the bug report template to report bugs.

**Comment by Wires77** [comment]
This happens because in the tree data, there are actually two nodes called "No Witnesses".  I'm really not sure why that's the case, but the anoint mod only assumes there is one, and it has the wrong nodeId, which is what the tree allocation is based on.
