### ISSUE TITLE
Anomalous Precision quality rounding error

### ISSUE THREAD

**Issue by holyzeus** [PathOfBuildingCommunity/PathOfBuilding#1727]
Anomalous Precision, which has the quality effect of reserving less mana has a rounding error.

Currently, at uneven quality numbers, the effectiveness of the quality gets rounded down instead of up (since reduced mana reserved is treated as a negative stat).

This means, for example, that a 23% Anomalous Precision grants 12% reduced mana reservation in PoB, but in reality only grants 11% in the game.

Unrelated:
This bug probably extends to any other effect that has increase/reduce effects that are below 1.

**Comment by holyzeus** [comment]
After some investigation it seems that this issue is derived from #1694, which has a fix up already. I will leave this up for now so an actual contributer can confirm and close this.

**Comment by Wires77** [comment]
That's correct, the fix for that issue fixes this one as well.
