### ISSUE TITLE
Cold DoT Multiplier

### ISSUE THREAD

**Issue by vetoll** [PathOfBuildingCommunity/PathOfBuilding#1729]
I have checked from both the ascendancy points, jewels and also unique items, such as Rime Gaze, that PoB does not count or include the "Cold Damage over Time Multiplier" as a registered attribute, it only calculates the default "Damage over Time Multipliers"

**Comment by Wires77** [comment]
What version of PoB are you using?  It should say "PoB Community Fork" in the bottom left.  That mod is working in the current version of the fork:

![image](https://user-images.githubusercontent.com/1209372/99157548-79c40380-268f-11eb-8dec-223b5212c4fa.png)
