### ISSUE TITLE
Anomalous Anger burning damage not working

### ISSUE THREAD

**Issue by emiracles** [PathOfBuildingCommunity/PathOfBuilding#1732]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

Anomalous Anger doesn't increase the damage of burning arrow.

* **What were you trying to do?**

swap from default to anomalous anger

* **What steps will reproduce the bug?**

swap from default to anomalous anger

* **Does it reproduce every time?**

yes

* **Provide a build code:**

https://pastebin.com/2JxCqbcn

Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
Actually, it seems even Divergent Anger doesn't work.  The movement speed doesn't increase either.

In testing this I also found that divergent Zealotry also doesn't give the regen.

Here's a simpler pastebin: https://pastebin.com/a2ZL9BN7

**Comment by ppoelzl** [comment]
I've also investigated this issue and I think that the mods in question are applied to Anger itself instead of as an aura of its own.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.19.
