### ISSUE TITLE
Started receiving an error about a month ago from last update. So I reverted back to last version. When i tried to update again today I received the unable to recognize tree error, so I unistalled and downloaed latest version from Github and received this notification after installing?

### ISSUE THREAD

**Issue by LordStorm7** [PathOfBuildingCommunity/PathOfBuilding#1735]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by LordStorm7** [comment]
![image](https://user-images.githubusercontent.com/74108164/99292295-034e0f80-280f-11eb-9c4d-4b0db40defe3.png)

**Comment by Wires77** [comment]
Open Settings.xml from wherever you have PoB installed.  There should be a section that looks like this, and the 'mode' attribute is causing an error.  Try changing it to "BUILD" if it isn't already, see if that fixes it.

![image](https://user-images.githubusercontent.com/1209372/99313015-78780f80-2824-11eb-8635-3804c2ac6ea5.png)

**Comment by ppoelzl** [comment]
Alternatively, you can just delete your `Settings.xml`.
