### ISSUE TITLE
Lancing steel hit rate is calculated incorrectly (as 60% less hit rate)

### ISSUE THREAD

**Issue by deathbeam** [PathOfBuildingCommunity/PathOfBuilding#1736]
Lancing steel hit rate for stuff like lgoh/mgoh or max poison stacks is calculated incorrectly. It is calculating the 60% less damage after first projectile as 60% less projectiles what is wrong.

Example pob:
https://pastebin.com/QTaF0C1G

The actual mgoh is 468, lgoh is 4680, max poison stacks 18420

**Comment by QuickStick123** [comment]
Might be implementable properly with https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5676?
