### ISSUE TITLE
"Increased effect of Arcane Surge" is not working

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#174]

**Comment by homutan** [comment]
Band-aid solution: https://github.com/homutan/PathOfBuilding/commit/83216d92feabae02c349a95a4d2b9ae82fd3c26c
Support gems like Arcane Surge and Nightblade that give buffs don't have an `activeSkillBuff` property, so `skillCfg` for them would be `nil`, and `skillCfg` is used by `modStore` to find things. Definetely not the best solution, but I don't really know better one for now.

**Comment by ppoelzl** [comment]
That is not the right way to fix this issue. The Arcane Surge-specific buff effect scaling should be registered with it in `CalcPerform.lua`. However, I wanted to look into ways to register the scaling though dynamic programming to avoid having to completely redo buffs once they recieve effect scaling options.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
