### ISSUE TITLE
Blood Magic interacts wrong with Archmage Support

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1744]
Archmage Support only works when spending mana. Due to the big mana multiplier of Blood Magic Support the program wrongly suggests to use this gem instead of a more appropriate one. The effects of Blood Magic from any source on the linked gems should fully disable Archmage Support from working.

**Comment by Wires77** [comment]
Fixed in 2.7.0
