### ISSUE TITLE
Path of Building crashes on startup if LUA_PATH is set

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#1745]
* **What happened?**
Path of Building crashes on startup.
* **What were you trying to do?**
Run Path of Building.
* **What steps will reproduce the bug?**
Have the LUA_PATH environment variable set. Example value: `C:\Users\Peter\PycharmProjects\PathOfBuilding\?.lua`.
* **Does it reproduce every time?**
Yes.
* **Provide a build code:**
This bug occurs before Path of Building is loaded.
* **Screenshots:**
![lua_path_crash](https://user-images.githubusercontent.com/33464174/99889427-4536e580-2c55-11eb-996a-461eaa1671db.png)

**Comment by Wires77** [comment]
Looks like there might be a flag we can set now that we have the runtime source (it might already be set, even).  https://github.com/Openarl/PathOfBuilding/issues/1062#issuecomment-396120534

Maybe we can dig into the Lua source as Openarl did and set the same flag
