### ISSUE TITLE
Archmage Support should stop providing ANY damage if the mana cost can't be paid

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1747]
When sorting items out for my build I noticed that the Indigon is still considered the top item for the build despite the fact the implied mana cost is way higher than my maximum mana with the given config value for the mana spent recently. Archmage Support however explicitly states it doesn't have any effect in such a case.

**Comment by ppoelzl** [comment]
In many case just like this one, the user is ultimately responsible to make plausible calculations. We do not desire to restrict user's freedom when providing specific overrides to theoretically unbounded stats like the amount of mana spent recently.
