### ISSUE TITLE
Factor in Frost Shield for Effective Health Pool calculations

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1754]
**Is your feature request related to a problem? Please describe.**
Right now Frost Shield only provides ES degen and critical chance. Factoring it in EHP calculations is missing.

**Describe the solution you'd like**
Frost Shield increases your EHP.

**Describe alternatives you've considered**
None.

**Comment by Regisle** [comment]
Frost Shield is similar to guard skills and although I want those also factored in to EHP I am waiting for them to have better support (like #956 which is yet to be merged), Frost Shield will likely be done along with those

**Comment by ZzZombo** [comment]
Your PR allows to see the actual damage amount absorbed by Arcane Cloak, am I right? That's one issue less to create then.

**Comment by Regisle** [comment]
#956 isnt mine, but I am planning on using it for that yes

**Comment by LocalIdentity** [comment]
Supported now
