### ISSUE TITLE
Option to include enemy damage dealt as EHP

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1755]
**Is your feature request related to a problem? Please describe.**
If enemy deals X% less/more damage ("less/more" not in the PoE-specific sense), it's effectively X% more/less EHP for me, right? An option to include such modifiers to enemy damage in EHP would be nice.

**Describe the solution you'd like**
Enemy damage modifiers affect your EHP.

**Describe alternatives you've considered**
None.

**Comment by ppoelzl** [comment]
Currently we do not desire to add specific enemy modifiers to the simulation.
