### ISSUE TITLE
Support for the "Trigger a socketed spell when you use a skill" crafted modifier

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1756]
**Is your feature request related to a problem? Please describe.**
At this moment it does nothing as an unrecognized modifier.

**Describe the solution you'd like**
It should apply a cooldown to socketed active spell gems and make them count as triggered.

**Describe alternatives you've considered**
N/A.

**Additional context**
This is very important when you need to consider uptime vs cooldown, etc.

**Comment by Nostrademous** [comment]
I will look to add this in #2294

**Comment by Nostrademous** [comment]
Implemented in 2.0.0
