### ISSUE TITLE
Triggered skills still report attack/cast rate and mana cost

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1758]
Because all triggered skills happen instantly and w/o a manacost, it's simply misleading and pointless. Additionally, when choosing/hovering over a trigger gem, it doesn't show the change to manacost and attack/cast rate as one of its effects in the tooltip.

**Comment by Nostrademous** [comment]
Fixed by #2294

**Comment by Wires77** [comment]
Fixed in 2.0.0
