### ISSUE TITLE
Show the stat being sorted by in the tooltip

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1760]
**Is your feature request related to a problem? Please describe.**
Currently only a limited subset of all calculated stats is shown in tooltips, understandably. But when sorting by a stat not shown ordinarily often all you get is a meaningless tooltip that does a bad job conveying the effect on the said stat because it's not reported there.

**Describe the solution you'd like**
Such stats are shown on the tooltip.

**Describe alternatives you've considered**
Only manual checking in the Calcs tab comes to mind.

**Comment by ppoelzl** [comment]
Hey @ZzZombo ! You seem to be quite invested in Path of Building. You might want to consider joining the development team. We'd be able to help you out to put some of your proposed improvements into effect yourself then.

**Comment by ppoelzl** [comment]
What I can get from your description isn't exactly actionable, so I'm going to close this.
