### ISSUE TITLE
Account profile is private, seriuosly?

### ISSUE THREAD

**Issue by zombiezkurz** [PathOfBuildingCommunity/PathOfBuilding#1768]
actually has enable the profile to public and steam too
![1](https://user-images.githubusercontent.com/44405374/100497353-f5f72600-3128-11eb-9d01-8721eb893778.png)
![2](https://user-images.githubusercontent.com/44405374/100497354-f7c0e980-3128-11eb-8b43-1b74862f93e5.png)
what POB still mention account profile is private
is issue has include a topic with captchas??

**Comment by Regisle** [comment]
you didnt hide your details very well, and either way it works for me? 
![image](https://user-images.githubusercontent.com/49933620/100497630-aa865b80-31ac-11eb-88a4-d03e9db472db.png)
that is your character right? (level 73 inquis as per profile page so assumed as last played)

**Comment by Wires77** [comment]
It only works because he set his profile to public now.  I did just test setting my profile to private, inputting my POESESSIONID, and importing my character and it worked fine, though.

**Comment by zombiezkurz** [comment]
issue start when making login with the same account on 2 browsers different and captchas are active so browser cloud protection to block part of access on the application

**Comment by DishangPatil** [comment]
Hey 
M still facing this issue. 
What kind of troubleshooting you did?
