### ISSUE TITLE
Add Infernal Sentinel Spectre

### ISSUE THREAD

**Issue by Hyoukar** [PathOfBuildingCommunity/PathOfBuilding#1769]
Can u Add the Spectre Infernal Sentinel
https://poedb.tw/us/Infernal_Sentinel#Metadata_Monsters_Guardians_GuardianFire2_Schism

**Comment by QuickStick123** [comment]
Closing in favour of putting all of them in one issue https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4558.
