### ISSUE TITLE
Expedition's End unique modifier considering cold damage twice

### ISSUE THREAD

**Issue by DavidStrid** [PathOfBuildingCommunity/PathOfBuilding#1770]
* **What happened?** 
The Damage from Crits calculation is considering cold damage twice. Cold Damage + All Damage.
* **What were you trying to do?** 
While attempting to find breakpoints for ailment thresholds for my meme build, I noticed the Damage from Crits Number for freeze being higher than expected. 
It displays damage from Crits as: 608,892.6 instead of 326,289.5 which is the total damage dealt. 
The total cold damage is 282,603.1 
My guess is that the program is considering both the cold damage and the total damage and combining the two: 
282,603.1 + 326,289.5 = 608,892.6  [Cold + Total = Shown Value]

* **What steps will reproduce the bug?** 
Equipping Expedition's End on a character with both cold and other damage types being dealt with main skill. 
In the provided build code there's also an item with only the: All your damage can freeze mod for showing correlation.
* **Does it reproduce every time?** 
Yes
* **Provide a build code:** 
https://pastebin.com/4hEfE76C

* **Screenshots:**
Main Skill and Calculations info:
![bild](https://user-images.githubusercontent.com/75178050/100522789-cb9a7c80-31ab-11eb-8f5a-fdb1502aa23e.png)
With Expeditions End equipped: 
![bild](https://user-images.githubusercontent.com/75178050/100522702-1c5da580-31ab-11eb-9e9d-e8710dd0b805.png)
Without Expeditions End equipped:
![bild](https://user-images.githubusercontent.com/75178050/100522821-0ac8cd80-31ac-11eb-8cd1-04c6aa5b01d6.png)

This is my first proper bug report, if you'd like more clarity in my future reports please let me know!

**Comment by Wires77** [comment]
Thanks for the report, this issue will be fixed in the next release!
