### ISSUE TITLE
Feature Request: Add Arena Master and its buff to the spectre pool

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#1775]
Monster stats: https://poedb.tw/us/Arena_Master#Lvl84
Monster's primary ability that is sadly not listed on poedb: buff called Arena Master's Presence

![image](https://user-images.githubusercontent.com/47370800/100605442-382a8e00-3308-11eb-9367-b4fea048c592.png)

Buff is AoE and provides to everyone in range:
- 20% increased damage
- 20% increased Attack Speed
- 20% increased cast speed
- 20% increased movement speed
Base duration: 3 seconds

With that, please also provide a checkbox when Arena Master is selected as an active spectre: "Are you and your minions affected by Arena Master's Presence?"

**Comment by SerebryanskiySergei** [comment]
+, for most summoners build who has 3/3+ scpectres arena master is the good one, his buff has huge effect

**Comment by SteffenSchreiber** [comment]
Please add this spectre to PoB.
