### ISSUE TITLE
XP calculations seem to be off for high level maps (87 or T20)

### ISSUE THREAD

**Issue by Noctis-** [PathOfBuildingCommunity/PathOfBuilding#1781]
* **What happened?**

When looking for the XP multiplier at the top, trying to figure out which level maps give what xp multiplier, i've noticed that for some reason, the highest Tier (87/T20) gives less xp than the previous Tier (86/T19)

* **What steps will reproduce the bug?**

Open the experience multiplier tool, and look at the latest values for characters level 87 and higher

* **Does it reproduce every time?**

yep

* **Provide a build code:**

what is the build code ??? couldn't find anything that looks like it ... my build ? the pob build ? 
pob version is 1.4.170.18

* **Screenshots:**

![image](https://user-images.githubusercontent.com/6160139/101129090-afd02400-364c-11eb-9b7b-c7254fd5dac0.png)

**Comment by Wires77** [comment]
Tier 20 is a fairly rare scenario, but the math is correct from what we know (See https://pathofexile.gamepedia.com/Experience )  I also find it odd that the experience would go down though, so we're trying to calculate it in-game by comparing experience from a mob both inside a +1 vaal side area and outside at tier 20/19

**Comment by Noctis-** [comment]
Cool cool ...
so ..basically, T16 map, +4 unique sextants (make 83-> 87 ?) ah ..no ..can only use 3 ..so ... T16 + 3 sextants ->  19, and with vaal prophecy to get a +1 you get the T20 ....
right ..
so, for now, i'll just avoid those vaal areas in them T19 maps :) 

BTW ... y'all legends :)

**Comment by ppoelzl** [comment]
To our best knowledge, the current experience calculation is accurate.
