### ISSUE TITLE
Feedback: Don't Completely Remove Support for Old Builds

### ISSUE THREAD

**Issue by dsnvwlmnt** [PathOfBuildingCommunity/PathOfBuilding#1782]
Where did the 1.4.170.17 change come from? "Remove support for loading builds from before game version 3.0.0." I can find no reference to the change anywhere.

I'm not a fan! One of the reasons I use this tool is loading old PoE builds to see what the tree etc. looked like. Largely because the PoE website itself doesn't properly support its own game's old builds.

Are we going to lose support for all 3.X builds when 4.0 comes out too?

This is the first ever PoB.communitybuild change making me consider moving away from it. Why remove backwards compatibility that was already there? All I want is to be able to look at old PoE builds.

If it's a load time issue, it could be made a setting. I.e. default behavior = current one that loads only 3.0.0+. With a setting that lets you load old ones on launch if you prefer. If it's a download size issue you could make a separate package or download or setting available for support of old PoE builds.

If there are complex problems behind the decision, you could consider making old Poe builds appear in a sort of read-only mode, where you display the build, but you can't make changes.

Thanks for reading! <3

**Comment by ppoelzl** [comment]
I understand your concerns. I've created a wiki entry that might help you understand our position and how you can still access old builds [here](https://github.com/PathOfBuildingCommunity/PathOfBuilding/wiki/Loading-Outdated-Builds).

I take it that you haven't tried loading a build from before 3.0.0. in Path of Building Communtiy version 1.4.170.17+ yet. You would notice that you can still convert your old builds to the current game version. Also you probably didn't load any such builds in the months before either, as you would have noticed that loading them was broken for a long time now.
