### ISSUE TITLE
creating or importing Magic or Normal Rarity item is not working properly

### ISSUE THREAD

**Issue by impbk2002** [PathOfBuildingCommunity/PathOfBuilding#1787]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

Some types of bases are impossible to create or import with normal or magic rarity, just spitting out other bases instead

* **What were you trying to do?**
* **What steps will reproduce the bug?**

Heist new Two handed axe Bases are impossible to create or import with normal or magic rarity, and just create one handed stupid cleaver instead with Two handed axe implicit.

* **Does it reproduce every time?**
Yes
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.

I think Classes\item.lua line 112 to 122 contain the bug

	if self.rarity == "NORMAL" or self.rarity == "MAGIC" then
		for baseName, baseData in pairs(data.itemBases) do
			local s, e = self.name:find(baseName, 1, true)
			if s then
				self.baseName = baseName
				self.namePrefix = self.name:sub(1, s - 1)
				self.nameSuffix = self.name:sub(e + 1)
				self.type = baseData.type
				break
			end
		end

* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

creating two handed axe, but one handed axe pops out
![bug1](https://user-images.githubusercontent.com/29122714/101311963-f95f7f80-3895-11eb-86d4-e4c54795ce45.PNG)

![bug2](https://user-images.githubusercontent.com/29122714/101312288-b9e56300-3896-11eb-85e7-185575fa048e.PNG)

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.19.
