### ISSUE TITLE
Latest download contained HEU_AEGISCS922 and TSC_GENCLEAN

### ISSUE THREAD

**Issue by needtoreport** [PathOfBuildingCommunity/PathOfBuilding#1791]
I downloaded the latest release, Release 1.4.170.16 and after installing and attempting to run was informed by Trend Micro Internet Security that it was affected by HEU_AEGISCS922 and TSC_GENCLEAN
![TempReport](https://user-images.githubusercontent.com/75712367/101572128-1037da80-3a2c-11eb-82b4-3aadde3b24e8.png)

**Comment by PJacek** [comment]
Looks like a false positive. Both the installer ([VirusTotal](https://www.virustotal.com/gui/file/49dca9dfa3382d285a1614ed0e01a37e93aa1db6ba8af1d1b40fa79897037238/detection)) and PoB executable ([VirusTotal](https://www.virustotal.com/gui/file/2777057dfc4cd5e5852749ff62cb77a1b9bc7c7cc3e15e7aaed455b7eca48df4/detection)) should be clean (notice TrendMicro results).   
However, depending on the settings used you may get different detection results and the threat identification "HEU" suggests you are using heuristics which means your av is performing informed guesses. TSC_GENCLEAN is just some [additional clean-up](https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/tsc_genclean).  
It's possible that something is tampering with your exe files. If you're a bit tech-savvy (and willing to pause your av) you can check if the files are identical by computing SHA-256 hashes. Open PowerShell and run `(Get-FileHash "path/to/file").Hash`. The string you'll get should be equal to the one from VirusTotal report.
