### ISSUE TITLE
Question - is there a CLI / API for using PoB as an evaluation for a genetic algorithm

### ISSUE THREAD

**Issue by DavidEl03** [PathOfBuildingCommunity/PathOfBuilding#1795]
Hi! I have a design / API / Implementation question in regards to how to modify the PoB code to suit my project needs.

**Background**

I currently working on making a "Genetic algorithm skill tree builder / Optimiser" and currently I am lacking an effective way to evaluate a skill tree.
I want to create a wrapper / add an API / CLI to PoB if it is not already implemented to make my system work with yours and hopefully if it all goes well I will publish it all.

**Technical details**

I should be able to process multiple skill trees a second, with a pre-selected set of gear and skills, the running should be done  preferably without GUI or restarting the PoB client

INPUTS - 
1. Gear and skill gems (with supports) - Preset / User-defined - Sort of the baseline of the character.
2. Skill tree - This will be created by my algorithm given a starting point and a point amount
3. Config - Like the typical "target enemy" and "Power charge stacks", etc.

Output -
1. All the data on the character panel on the right
2. DPS and the Damage breakdown of the skills

**Questions I would love to be answered by the contributors**
1. How difficult will it be to add this kind of API?
2. Any ideas on where should I focus my efforts in the code? Is there a class or a function that does all of this calculation and ill just wrap it with my own code?
3. What is the current speed of the evaluation?

Thanks in advance for everyone answering and helping out. I know this is not a typical issue you encounter!

**Comment by ppoelzl** [comment]
To answer your questions:
1) Interfacing with PoB has been done before, for example [here](https://github.com/VolatilePulse/PoB-Item-Tester). I'd recommend asking there instead, as we don't have any experience with this topic. 
2) There's a [wrapper](
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/HeadlessWrapper.lua) available to drive PoB headless. It is not officially supported by us and there is no guarantee that it will work.
3) We do not currently measure performance, as it seems to be _fast enough_ for manual use. There is some way to measure performance buried in the skill tree related code. Haven't looked into it though.

Please note that we do not offer an official API. Therefore everything is to be considered an implementation detail and can break, anytime, without prior notice.

**Comment by coldino** [comment]
The interface part of the mentioned PoB-Item-Tester is my work. Also see https://github.com/coldino/pob_wrapper for an example of a more useful wrapper in Python, although it is likely to need some thought before putting into bulk use.

You can certainly access all of the data in the side panels and more, including full DPS or average hit calculations. It's possible to perform these calculations given a certain input - like including a new node on the tree or a different piece of gear. The APIs we use for this are fairly stable in PoB and have only changed once in my memory (when the old version support was removed recently).

Feel free to get in touch via PoB-Item-Tester's Discord for more.

**Comment by ppoelzl** [comment]
I hope this sufficiently answers your questions. If you need anything more, feel free to reopen this issue.
