### ISSUE TITLE
Divergent Arcane Cloak - Buff effect changes the mana consumed on PoB

### ISSUE THREAD

**Issue by SpiritKinay** [PathOfBuildingCommunity/PathOfBuilding#1797]
Inside PoB, the divergent arcane cloak buff effect increases the "Spends #% of current mana" and it also increases the "added lightning damage" making the buff effect double dip.

However, in game, only the "added lightning damage" is increased.
Below are 2 screenshots, one with 44% quality, one with 20% quality. The mana consumed hasn't changed (in both cases, it gives a shield of 5077).

![screenshot-0204](https://user-images.githubusercontent.com/5437862/102742504-0e6ef080-4323-11eb-90d2-c28419727de4.png)
![screenshot-0205](https://user-images.githubusercontent.com/5437862/102742505-0f078700-4323-11eb-9022-393af6848efd.png)

**Comment by pundm** [comment]
Fixed in v2.0.0
