### ISSUE TITLE
Imaple DPS does not show/work in portable version, but in installed version is show that

### ISSUE THREAD

**Issue by erdodip** [PathOfBuildingCommunity/PathOfBuilding#1798]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Imaple DPS does not show
* **What were you trying to do?**
* Searching google what is happend. Installing the installer version. That works fine.
* **What steps will reproduce the bug?**
* Try it portable version with my character
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![screenshot 975](https://user-images.githubusercontent.com/65724132/102781620-4401f100-4398-11eb-918c-08c52abfe6bd.jpg)

**Comment by ppoelzl** [comment]
> Try it portable version with my character

@erdodip You did not provide your character. Please fill out the entire issue template.

**Comment by erdodip** [comment]
my bad: acc -TomFiresGame charName - Veonsea

**Comment by erdodip** [comment]
But I made a new build with new button in portable version and imported the char again, it worked!

**Comment by ppoelzl** [comment]
Could not reproduce this bug.
