### ISSUE TITLE
SimpleGraphic.dll update that hangs

### ISSUE THREAD

**Issue by Cirwik** [PathOfBuildingCommunity/PathOfBuilding#1801]
My PoB says there is a new version even if it my version is same as last version 1.4.170.20
When i start the update it wants to install/update SimpleGraphic.dll and the console just hangs there. When I go to the project https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/releases it seems it has not been updated since 2017 so I am puzzled why this is happening.

My PoB works, it is just a bit annoying to always have it say there is new version that does nothing but hangs the update.

**Comment by Wires77** [comment]
Try downloading the DLL from here instead: https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/actions/runs/407747978

I'll see if I can incorporate that into making a release page for the future

**Comment by Cirwik** [comment]
Thank you! Issue solved
