### ISSUE TITLE
Opens on 2 monitors when trying to switch to 2nd monitors

### ISSUE THREAD

**Issue by slapnu** [PathOfBuildingCommunity/PathOfBuilding#1804]
I recently reinstalled pob fork to newest version and now when it opens on my first monitor i try to switch to second one and it opens on both i am lost can someone help me please. than 1 st monitor gets washed out colors .Main lg oled 120hz 4k gsync/ 2nd samsung 60hz

**Comment by ppoelzl** [comment]
@slapnu Please fill out the bug report template, or I will have to close your issue.

**Comment by slapnu** [comment]
ok done

**Comment by ppoelzl** [comment]
@slapnu Take a look at [this issue](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1745) for example to see what a correctly filled out bug report template looks like. Do you need any assistence with this?

**Comment by ppoelzl** [comment]
Closed due to inactivity.
