### ISSUE TITLE
Inverse Power Heatmap For Finding Bad-Power-Per-Point Allocated Passives

### ISSUE THREAD

**Issue by IdrisQe** [PathOfBuildingCommunity/PathOfBuilding#1806]
**Reason**
Something I've felt is missing for a while is the ability to accurately gauge where you could best save points you've already spent- for example if you allocated a few points, then changed something in the build which makes those points do almost nothing. Currently you need to manually check around for issues like this.

**Solution**
I'd like to see a toggle in the Node Power overlay that instead shows the power (based on selected heatmap criteria) inversely, for allocated nodes. For example, if "Combined DPS" is selected, any nodes you have allocated which have extremely low effect (but not NO effect, to prevent visual clutter) on your Combined DPS will be brightly highlighted so you can decide if they're really worth the invested points for like a 1000 DPS gain each, etc. while nodes which boost your DPS by several hundred-thousand (or rather using a percentile system) would be very dim so you know those are nodes your build relies on. "Bad" nodes which are required to reach better nodes you have allocated wouldn't be as brightly highlighted since they're necessary to reach a better goal, or basically worth it in "power per point" sense.

**Alternatives**
There honestly aren't many alternatives I could think of, other than just having a menu like the Power Report for this, though I don't see why it would be any less difficult to implement- in fact implementing it the above way would probably let it integrate with the Power Report menu already. Really the only alternative is currently just looking around and hovering over nodes, or rebuilding your whole passive tree from scratch.

**Comment by ppoelzl** [comment]
Rebuilding your passive tree looks like the best possible solution for me. If you're aiming for an optimal tree setup with an endgame build, swapping out a single skill cluster could dramatically alter your overall pathing. Your proposed solution doesn't account for that. Also changing support gems might outright remove the damage contribution of certain nodes, which would not be caught implementing your proposed solution. I'm keeping a close eye on possible improvements to the power report, especially in finding underperforming allocated nodes. However, an acceptable solution will likely be implemented quite differently.
