### ISSUE TITLE
scourge arrow

### ISSUE THREAD

**Issue by FARR1R** [PathOfBuildingCommunity/PathOfBuilding#1807]
the stages of scourge arrow are broken the  dps goes down instead of up and they are not the same  before the update

**Comment by ppoelzl** [comment]
Scourge Arrow is working as intended after the 1.4.170.19 update. See [this Reddit post](https://old.reddit.com/r/pathofexile/comments/kgn93v/latest_pob_fork_is_broken_for_me_how_do_i_use_old/) for an explanation on the DPS changes.
