### ISSUE TITLE
Cluster Jewels Damage/DPS

### ISSUE THREAD

**Issue by ZanapherOfficial** [PathOfBuildingCommunity/PathOfBuilding#1808]
I just downloaded the lastest version of PoB and I see that when you craft a Cluster Jewel and you choose a Special Affixe, you can't see anymore the DPS increased or decreased. It says "Allocating XXX doesn't do anything".
It's a minor bug, but I just wanted to notify. Thanks !
Have a good new year !

**Comment by Wires77** [comment]
Hey @ZanapherOfficial can you fill out the bug report template?  Having a pastebin and ideally a screenshot of what you're seeing is needed to investigate this bug.

**Comment by ZanapherOfficial** [comment]
Hey, thanks for your reply, sorry, I didn't think of this, here's an exemple of my build with pastebin : https://pastebin.com/0y7qCS55
And here's a screen of what I see in attachement:

![PoB_Bug_Cluster_Jewel_DPS](https://user-images.githubusercontent.com/76758070/103326972-fa2da080-4a52-11eb-94ff-45af0944454c.jpg)

Thanks for your help ! See you !

**Comment by ppoelzl** [comment]
@ZanapherOfficial You still have not filled out our bug report template. Do you need any help with it?

**Comment by Wires77** [comment]
Looking into this some more, it seems this line is intended to show up for anointing nodes on amulets, but also happens to appear on cluster jewels, which it isn't really supported for.  It will probably simply be removed from cluster jewels during the crafting process, and you'll have to look at the node on the tree to see the stat comparisons.

**Comment by andrewkhunn** [comment]
@Wires77 Was the tooltip calculating DPS incorrectly? It was incredibly helpful to be able to see what notables you should target while theorycrafting cluster jewels. I've missed this a lot since the latest build was released since selecting notables and flipping back over to the tree is so inconvenient.

**Comment by Wires77** [comment]
Oh, my mistake, I didn't realize this was even something we had implemented before.  I've found the commit that broke this, and fixed the problem in the linked PR

**Comment by andrewkhunn** [comment]
@Wires77 Thank you for the fix!
