### ISSUE TITLE
'Null error' when adding an empty socket 

### ISSUE THREAD

**Issue by arinarong** [PathOfBuildingCommunity/PathOfBuilding#1809]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
In Skills-Socket groups, when attempting to "enable" a socket first before "selecting" a gem, an error pops up stating there is a problem indexing gemdata and it reads a nil value and seems to be stuck in loop since pressing "esc" or "enter" does not allow you to exit the error pop-up. This error only seems to pop up after attempting to select the gem. 

No error if:
-Left blank 
-A gem is very quickly selected (if selected within a -+1 sec)

I found that when spamming esc that I can exit out of the error loop and prevent further popups if I click away from the drop-down to keep the selection "blank" but I'm not quick enough to move my mouse from the drop down the error begins to loop again. 

* **What were you trying to do?**
I was attempting to use a 4-linked, empty socket on a glove piece I imported. 

* **What steps will reproduce the bug?**
Under Skills/Socket Groups:
1. Enable a "disabled" socket using the check box
2. Attempt to select a gem using drop-down menu

* **Does it reproduce every time?**R
Yes. Also confirmed that I have the current updates. I was able to reproduce the error after exiting the app, trying it on other items, after re-importing, etc. It seems to error when attempting to select the gem AFTER selecting the enable box.

Selecting the gem menu BEFORE selecting the enable box does not produce an error.

* **Provide a build code:**
https://pastebin.com/pBXhsqn1

* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
This appears to happen when hovering over the gem, and I can get the error to go away if I move my mouse outside of the dropdown and press Esc.  This does seem to be an issue, regardless, and we probably just shouldn't allow the "Enabled" box to be checked if there isn't a skill selected yet.

**Comment by Wires77** [comment]
What is the use case for checking the "Enabled" box before selecting a gem?  Selecting a gem automatically checks the box, so if I disable the box before selecting a gem does that remove functionality for you?
