### ISSUE TITLE
Arcane sure not have in configuration

### ISSUE THREAD

**Issue by chautv55** [PathOfBuildingCommunity/PathOfBuilding#1810]
I have  a watcher's eyes but no have button check "if i have Arcane sure"

![image](https://user-images.githubusercontent.com/76828962/103432529-cf8a4600-4c12-11eb-80bc-430885cb1131.png)
![image](https://user-images.githubusercontent.com/76828962/103432537-f2b4f580-4c12-11eb-8bca-8b55e402ac24.png)
![image](https://user-images.githubusercontent.com/76828962/103432539-f9dc0380-4c12-11eb-94ae-a06fe9d74de5.png)

**Comment by ppoelzl** [comment]
If you need the Arcane Surge Buff, add a level 1 Arcane Surge Support skills gem to one of your skills. It is not supported in the configuration tab.
