### ISSUE TITLE
PoB panics with unprotected error in call to Lua API (not enough memory)

### ISSUE THREAD

**Issue by johnramsden** [PathOfBuildingCommunity/PathOfBuilding#1811]
* **What happened?**
  * PoB panics with `PANIC: unprotected error in call to Lua API (not enough memory)`
* **What were you trying to do?**
  * Allocate cluster jewel passive nodes
* **What steps will reproduce the bug?**
  * Allocate cluster jewel passive nodes
* **Does it reproduce every time?**
  * Yes
* **Provide a build code:**
  * [build.xml](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/5758607/ColbySpectre.xml.txt)

* **Screen capture:**
  * [Video](https://user-images.githubusercontent.com/8735102/103433018-a92ac300-4b9e-11eb-9c25-528419d6bf8d.mp4)

**Comment by Wires77** [comment]
It looks like this isn't an issue with PoB itself, but the environment you're running it in.  While people have been running PoB on Linux through Wine (as it looks like you are doing as well), it is not officially supported and we are unable to help with this issue.

**Comment by johnramsden** [comment]
It's not actually running in wine, [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=path-of-building-community-git) is the build script, but yes, I am running on Linux.

Thanks.

**Comment by Wires77** [comment]
Gotcha, you might be better off posting this issue in @philroberts pobfrontend project or to the build script maintainer to see if they recognize/can reproduce this issue.  For what it's worth, I loaded your build just fine in wine if you could use that as a stopgap.

A cursory glance tells me that playing with the luajit version might be fruitful, but I can't say much beyond that.

**Comment by philroberts** [comment]
Hi, I loaded your build and was able to allocate the cluster jewel nodes without crashing, though it did use a lot of memory. As a workaround, can you try disabling "Show Node Power" while allocating the node? I've noticed that is slow and memory-hungry of late.
