### ISSUE TITLE
Bug: Warstave mod pool seems incorrect.

### ISSUE THREAD

**Issue by NewGuy5005** [PathOfBuildingCommunity/PathOfBuilding#1815]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?
Went to craft "craft item", selected warstave, eventuality rod. Selected prefix and desired to put on fire dot multi over time. Option is not there. Upon looking more closely at mods I also see shaper/elder mods in normal affix pool (with no influence selected). Affix do not match possibilities according to poedb. (or items I've searched in poe trade official).   
 
* **What were you trying to do?**
See above

* **What steps will reproduce the bug?**
I have tried both in old character templates and new character templates, problem persists. 

* **Does it reproduce every time?**
Seems so, also for other warstaves.

* **Provide a build code:**
https://pastebin.com/CnF32pY7
See Equipped weapon mods

* **Screenshots:**
![PobForkPotentialBug](https://user-images.githubusercontent.com/76872509/103459900-1c047d00-4d0a-11eb-826e-cf1fda88cae2.PNG)
Hopefully screenshot works, computer dunce here.

**Comment by Wires77** [comment]
There are some staff mods missing on warstaves that I'll add back in the next update.

The extra mods you're seeing there actually aren't shaper/elder mods, but old mods that could be acquired from delve fossils.  These items do exist on the official poe trade, see this search, for example: https://www.pathofexile.com/trade/search/Standard/n7jz6qMs0

They're no longer craftable, however, so it might be worth seeing if they can be removed.

**Comment by Wires77** [comment]
Fixed in v1.4.170.22
