### ISSUE TITLE
Gem tooltip incorrect on hover when searching

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#1818]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
  * Searched for a specific gem in the skills tab, only saw the preview for the first gem in the list
* **What were you trying to do?**
  * View the gem description for a gem I was hovering over
* **What steps will reproduce the bug?**
  * Search for gem, hover over other gems that appear
* **Does it reproduce every time?**  Yes
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![image](https://user-images.githubusercontent.com/1209372/103476555-8eae4080-4d7c-11eb-9c18-e0f40e58028a.png)

**Comment by Wires77** [comment]
Looks like this can be fixed by removing these lines, but I'm not sure what the lines are there for or what other affect it might have.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/ee47088b95d361ed31bb7961f062c6d69a6e6ddf/Classes/GemSelectControl.lua#L334-L335

**Comment by uilman** [comment]
It shouldn't break anything, it's just the gem tooltip, not the comparison.
