### ISSUE TITLE
Runebinder Keystone/Brand attachment support for dps buff.

### ISSUE THREAD

**Issue by mschifter** [PathOfBuildingCommunity/PathOfBuilding#1820]
Greetings O Master of the Build Planning and Analysis System Named PoB,

* **What happened?**
* I added the Runebinder keystone to double down on brand attachment.
* **What were you trying to do?**
* Trying to find out what 1 or 2 brands attached will do in dps calcs for my minions.
* **What steps will reproduce the bug?**
* Increase the enemy brand attachment number in configuration screen. From 1 attachments, dps for minion does not change.
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* on clicking "Generate" I get a dialog error. Pastebin.com: Error creating paste. Since it is critical for debugging, I'm pasting it the full raw code here...
* 
You can contact me at mschifter@cfl.rr.com if I can be of further assistance, and thanks for looking into this. -- Matt Schifter

eNrtPdty2ziWz62vYLlq9iVOTNyJbDJbvtudm9t2kp5-6QJJ0GaHIh2Ssq1s7b_vAUhJpETKtFvJTPXMdFVGpg6Ac78BhF79z_04cW51XsRZ-noLvXC3HJ0GWRinV6-3Pl4ePfe2_ufvo1dnqrz-EO1N4sR88_fRT6_sZyfRtzp5veWJLadU-ZUuP82mIr_DVDcqLa91lr5Tf2T5cRa-3nqfpXrL8VUaxuXsryBRRfFejfXrrc9xGVxvOaoIdBruL56_10GejVUa6HzLGas4vciCL7o8zrPJzesttuXcxvruXRYC6Om7sw_nl42147S5NuD-06uLGx2UuXZiePpOlypUpdp5l6VFCejvHE9UHsYqXXw6inO9tTNg6Futrib6RMdFuXOe-Vn9734C6N5l-ZfjLNHj_SwJ62nqSc8SNdX5RalKp4B_Xm_tBmV8qwF14OXbeByXQKFKJtrQ2jcEpKiu9EkD1n0A9kCN4d-HwQFZHc7ByAtGERKcCpd5Hv7nDzrL9WEUacuy_Twu96-NojxM1mNh302SMr5JYqODNTx6IfpGnKxMjtze6S-zUiUHZxcPI1JBZgOEDLZ0vZcAPwfNa6BPr9K41IPBz7K4yNJHYT0IeD8b-3E6EO8Z8O7t1cPA71Sq9rNiwTxEeuV3US7EjFEv2Ln-2oREXu_iB_p-AcbxmglbkKzX4k_TBSHYo2smbEFS3I_hbVaCx3mYkW_jaKHXxKNsjUEHLw30aRosaEJo3cQf01wXOr9teoI1S7SHnOkcYkc5xOjMwHN9pRf0YhcioCRrl3qrdXB9DCHoXJV6mMo1kMFkLacMdJNTBK-bt4NRz5Erhg1ZZhSMfEGZpIS41HWFt26WNtcIeiHXQT-SY4epzq-mF9exThZ0YY7WMq45qMVAPmSZNj2DMHssUbeqaFoW5-sVoYZvktKvYhq8PAwI9dBo9vgRZ3n2h4mwyeOG7ebjbNLwjrxfHpbsCn6YAM-up0UcQFixWcy5DidBy3mhXtuZZwvvsls9BiOwaQekj4243h8Y9kwytxzavTVkJUnXENI7ZLcsVfDlIAuvBvPZrvKoESalPddF3AiGgj0M_AEyx3110_Bo_YHZ2NXABRbAywsw2u-Mr67LFMqRwassjVheqtcigadZsbzKEOjlFfrNK7sDyGtTQhWPg36n7h8m4CjX6bfp4Plb4IMWOEzDSW4Ub_AayyMGLfNwWVR992CpwxDi4gWRvG_YciHieX2QK6k7kh7D8gWVnD4wqCOLX4HszOKHLNGd0A8duZrbP4asrsx9BbgrzR-ySCv3RCBDKdaBLmV4QpIXkq4bsD6yrwzpTFcIHwLenXasHbIOuVc7tiljPp2Ob7K8dBJVlLtBkE3S8kQV17Y80dwPCcHIC7QmrpDCF9LFvmBC-hypKMRIyy079FyrZAzuZr_601iqCkqdV3OREAYhGakgQB4mOAoD5HpICY8TQgKfIB-xgAQVbvsqCQpL32l6Mymd1PZ1iuvsrqJ3y_GzLNEqfb1V5pNZY6QF-yVOkt_Tydg3BXj1_wvDb0KO4yL43Z9EkekIbQEXc9vOOjw6Oty_PP10OGvlaJswOEGWJOqm0OHrrUglBYwwzZ0Ls9wFJEpBOQge6v3ayQyB_qzyII_BUQ4BNo5iEMrWaQ2BNO2MQYCgSCrRwxl2Ob3RRnWLoTyr85Uh0NYNDoKsvNcwAq2LHCYGHajpIMi5lQ6CPkz0bpyYPHQY196Belcp7DB4yCfz2J-UA7XN-tdBeJjSdhCBTRc5COOqbBg0d11YDYGtU7hhugYZ-2BpHOhIgxYPtGbrJS7VF53WbnvmG19ZEyqcAnz3sR4Xe1OIjUeGa0vRsgVQO0wn1JGaJOb5LxOVxOX09VYaJ83nb6tuvX1qPO_F5OammsmYbQF8f_u2bpAbRGyjvUq57N8WTYghJhr4ZiKzV6D8xNBXoVAkmSmQsgw0c3m0GWjm_ukVrFcPPE4yXyV4zh7r4uv4116x8U39EABKiEWmu56ZyFtvRWB3y7nS49Nme_60BF7tGIbt2Gnh08VkPLaL1HMU9RKnYXPmYhUli00TezQj_mvF9VPrKSzL588qtJaYZWKVKXphQYuM07fuCq07D_FxIC_m4t_LUnBYsGCTC9W3ja82TPVi5k3RU8v2RJW5Sd7npMwebJiAetqNS-NYg7_MCkBgVRzN7zZMTmPqyo1VDP3z_uAcsi8HP8khPE7w-1l6mwWq6gLNOdd6umGeNefeLNMAxVtd_ACmHUAy3-DWL5O47j1tnFl2pQ3b-oEudJDbWmhOQuPZpimYz7xhMj4plUBV1SKj8ezxZCC5hgwzs1NNPZQOxAfRcZbrIC7a9gcF6ATqxuluGpqyo9iFvzYumcXCmzXDz1rdQGhGP8AQTTz8AGm9KVYb7Gs__g4x2JnPvvFIBolwloaf4zRcjWS7YRgbv6mSfSj8w-xu8965Wt6x62_YYC_1GDLmctb2mRO39HzDBNWzO61SalOqvpeFU2e2YfOdk_cNnJyZCwwNEti5igs9HzuXV8fj75zs2xWdriU3d6BoiEMfaMKVAzxM7D7ZbLPtLJkUqxa9BnTDPNy9M9WzDp35Yk61mnMXl9dOtYFWbJwXn-IgzibFYi-06GZEH9z34kK9ntNY8DtUJbmGxCevD0Hp5lqrVcoa2E1XLdVSzmytJzFhqAJUdrrOBlYhvpfQq5WcZs95k-K2_AyU2fFcoXHx1aYDttnGdg6D6-z7pHF_qghlwxpLZZaP93LVSnmgTAwncXkRX8Wb76PYFZ1qyY2rwf4kL_SH1J4qXdaD5nebbq3o-zKbBBsvF4_yrCj9uFVnNZ5tmIrFzJvV5hOdjHW54STtcYzcTeMx-N1Zurgo9jqeLydUjYdm5gtdfo88q8bEmZ3hXkq16q_D5lbDRksf29Od5yfV1kN1NGfZjnpBNx89FvkS0D3dPNVHWpsXBKoDJH3R0dSbaWG0tmbIps2uQsKpsdj5UTZhM_vfzD7NSoXRevpDCoyOFeuvwvqr79MocS7uzIGnp4dZ5A3dtMgnpeVHx6bF4quHmLubQPaYgifAg3sm88l3Nk5S0tkqqR8_Xk_WkpHM2yL_aVr_p2ndImOgui5aePWO87ou3xxk0yEtbZwg2YAx_lU72f9JGv-TNP6YpPHfOZ_6t0im_wWTRvmXSxofH4Tt8a51IbgG2LR7GN-Y9xGGB2D5b5IN_zDtbhwi2M2DpSME8GT_2hxF3TDH7CECs9y_KNMebz-_nq0zHvPtxlPXxLyRpFdSvfqTPRN6mWvtqIoFdhRa3GHQvCjBrE9g9iw0JzkF8bxtIgUi25hK4W4jiVyyzSilYpswAo-Ji8W2JBJvEyGl3MYCAwTyXPiSM-GibYRcmIUxJN1tzKmHtrnrwmeKCYW5JGEAyD2YwOXM2xZEUFjT9dg2wZLgbc6Fy7eZ63G8jZEEEAA346nkAmZEksMaFMMTgRky8AhmIFRIWIkxuo0YdatFAAZmdrc5okha_ABXKmWFq6EBpt5GrhBoGxYHXJEhhyBPsG3KEPxr0KFADqfcIgKLS25pMGhiCbziGAMGnCFmZneZADyERNuUu8AnmJeZ9YAtwCcE1HJKMUxGMbKYCcMhRg1tHuewLEFiGwkPo20mgIPwHIMsCGcUuCMQBgI5AVSBl9sYC1iPUfhjmxEMPKASAw-YSzHQRxk2rITlCDFjCAIeUhCxwRzEhwjIBqaWFAYiIzIqCLKMB0QZ4GCQJgADkxpI846NGQtIAxXAQgoEADzzYHaMCLGCAlIpRcBajGE-UBKOEGiNx40CecAlIYCFTFDDMG6E4sIg4LJhAAYIQJ1ho4yVFhmiAUzCA84J3XJK0O_GrSEI1xeCVPpcGfshGKEO3xvVtg-aTxzIT8osv9DGwhDxhAsmFwc2Xc_LHXxg_rXmdAoPi50bmBtsqdg5tDE8gfAV53qeRr3PSmOtL8KwqIypuoDkIpmMnbdZHlYPDXJYIF4j-NNPVTJWOKEGr-i5f3PiNMi1guyw3qGr0N5Z4P0vRIgLAvpLEEIJx38JQowD-0sQYtzF9yIEnCQeRobJVew7GubPZbRNF8ep3qdpIc7kDHHaRFVbSCeLnPdZ-tzugTpmisKJ8mzsTLNJ7lTR-7uSMxfGMjmzd9qd-hXWGUXUE2Ju5aRJUXvEP0cI9qVpp9nwmOEN8yN3hvcz_jenzJxl6H8OzvPXybvxFhDr5ngjYhHvGvJPUpPW8ZE51p6k3aEA4X8Ve63e_50bKqRBc4xbOI7VfTw2HgngH4kpxQz_IA8JqebC0WzaQ_5AOqAEkN8vGxJQEjR4RhCay5yvlTlYnjW82RfmJotl2_vpmWdhOr9jzekvIFlNr8rrP4c-IdgTc5VtcadqLA8irD3QPAfcA3Dl-bSKREeQRX8pagqxayjcDP5QGLlzz1av6SBAB2KixePuWqcmEDoTiI3Kse86Tytw1OJn9Y0zOwC-IMC83d5FZn3KM8pyR6vg2injsTYr_Ze6yYr_vtVO_V51aKaCkJZMHy3F5oOq2nj18fxtRe11Wd4UL3d27u7uXtyo8jqL9H0M5hFk45klPbcdhOemqtnZhf_t7b472N37FoynR9fxl6_RQYB-86YXd8mx_PqL-9v9G3TwazIO73n-NfntPrgNvdPg201cXr25PM6TX49zHo4_7U-Dyc8f9u-fT9-c7ePfJx9-zz_cHF_cXWSXQfHxsCDTg-Ik-u3XL9Nv-_jk294t33s_GbsHJ29ufk_Oj3-_nXx9Xr69O3k-PVBnb-73Pn4Oidgbpxl_fvzHlTy4-wf7_OHXyz_kbnR37B_KK-TdZ18Pfr27jw4v0PTg29vzL0efr1j-xy-fQv8P9UUf_cM9VvTk5Fv-5mu8e3yZfkRvbv03058_eUmOpxdfP8fl0fn9b7cffimy52XGP37e_xnv3mN19EcuMk9VrJ5x9lV1n-Osuqv-Wigcx2bXDqRi-zn1RQkdcAgxdwAchzqYDoGjUAsPgMNYyiHzUY8bO3p4PvBvA8AkdYdwpa6zZ3Be76pSmOL7YeyQ9IZQC7U-ZkPwI4IN4TJBfJA0CKWD4GxfawFHe9kspBiiLK4gQ8gVkruDuMJJQwlQr05xhoboFDW3ug2xIYLEIPyQO0iVqRyiypQTOcjSTJtviGwl84YIw3YQF3CiFw7SzCF0YI-KIesyirAYZENINuglvfh5lPBBng973iA-D7NxAnAD1aCpVbyXDoGHaTM398EOgEOYD9Er2-JcwMl-_nE-SP8QOMlBkUNQb5DcaJMvuJd_LhRZQ-iV3BsWsQT3BvEZAAet63oNPWC9eoXFILmBeNEQOI7JIKcGNcwQM-cSDcsziNvhDV7tNLId-ONGB3bPx-z0mA9QdFWZp3k4-8PuA32K9Z1TaMhxryGJNXto37Js_A97j-0LySVlLugnF9X1Hidale_UzXxjzMDWV4DI-gKQUpUHsXn9015fMtuhMoC_mklhVs9FDFE7qb2sxO6h1ftRzYM4kOrXb3vaDTz7uFq3up4JQO3tJ3XhcK7yuJy-dM53zw9H77LcjyEvN82R0fG1KiBvdw6n2vlZ3-lk9DGNv060c3rw0kEycqn0XEDZkxD5QhwFSAkNf6lQExkRoiX2kO9GGGMdhK6UTCowCxoqJYKRxcMy4aXjkZH9dK6_vnQYHp2Ob5I4iMvipeOOnmHZrBtt3dUqa-3XiDlqvkPozG6knBW5z_DfnOp-IwNrr5Rxqldc6jomjmyZdAf8rx-Fjj-FkukkLhcVzGzZawUFDlSFQWPKOA2dLLXwzVffrGIZWtvMx23mf3x_-svHw9HlNRRGoaneTrIbPdrP43EBc64wH7uR0qF2wxCCUoila27lVqEbMIYxiTwK0iA-PJEB00IQqhVU6iRCXsgiKXSb-Xx0rsJ4Asz-BOiYLkNbAB9SUAJVXXPknNVtCqjinHdQmoJEzK0So-bzajonUKnja2c3SczFDMBQw5dsUsJD03cDFU1hSngO_LPNWlOqjZ6b-hWeKPP-0fy8U-NUVQ9HSSdHP6Y6tadmTibplc5H-2bDuFzlqJQe4sbHEs_jYRSGmmNXeRiSF-LiAGNGgeM0EEJg4D0GtY5c3w0JliHlirc56s45WrFoZK9ItJSC8NrcbemUaLcgtDK6UHXER-YyQEeVTgLflg51ndO0BA2Or4zHWLB926nOQs1ebK1nVg5zmwp7pWDERTYBJtu39kwhj11wacZzFEaT30D13MNr2uE63uTmdThYVeVfRm_NTZLOfjIx786ucjtQMhRRAIk1MJBGLlFMe0y5mElX-EQEAUcqVBKUDgChGtJEIx24UaBQ4GPZ5jZuOA_uNrlLRv8b5CoCzv_fbghUeTP1ne0LzL_GDgAA09rfOyqvXZ9TB4rWhIbJY6OnS6OucpWWL51217ar97ZmDnDY2Wwi_PShz2hnQw11kevEppOf6juV9APM3nDdi21fqEs7WId2HOTqCnQKQsmo9hq9ysER6EEgkB96buAFYSh8j4C5YShNIoYDEngkUCwS1PUpYS6Socew8CEEYeL7fks5hGxGFrpOOVivcvQyQ7WU4zG6wZ-4kTVU7NUmR5f_7Bdtdd4ZzDYbj1Uagrfs1wIN3jQC57GA7dYF3umVj7LceKYCht_qFDDu9ctu5EmkNSKMR2EEoSyMJCiGhqKN2kstZSBIhENQCi1UhAMGQQ78s6tDzH1Clj3FGr-Muv2ytV7COkyw5bmfIbSaYlQ5QA_8AynJqO74L4t5EV-Nc7oEeRfgu8eWiFFsLiuADGLJA5Xgmh3c3f3vkprolJp9t0PbPbO53D7FeWyOZ69KTgUgM991tRdpHugIack8X2ofPlMRcexFngiVTxgkhgHnkBeCDUNWY24s9RX-85KzfG63uWuBVNura-D2TYjtgsLNGGrfc5nNCYlfsQSMVoErCVvYDcrXLoeBgtzcvd61kdwlZa9TyrupKrOxTZ7fpNldogHtXvMUvs-0q6OAC_DMIeOuVBTzQAQe1L9RFLoKKS6QBzGd-CqkkI1GBMSOBVirQG0h07mQbf7QlqrXuwljvTcyPH7XeOzcQHAh7SRpkYrOudzDG9kRw86MoxtnqYlekO8XxYOhzNMU-5qF1MXSixT2I4q1r9wg0B73I1cy4IxPfQZuTSvPxTiIvJC4SgUBBna12YP-LUMZ7U-JzSd7ZqSe8YdGttlRiCXzOZ-M42oPzES3NMjsBaSjYyAG_FW1FdiyIEiCpYASjiLGdOQKjzFjGRGHzNcNIdgFGEJQIHyomwWkOBDaFCdgY6A-foSXC4_65S5TIzbTYm-5pnYfiFZOOMnt2wYG4Vqso2fIfaCO7hrVw7-u_sOePYYL1W8WgSMqLZfMvSJQWLbqX-T7gmpIE7lHCaHK5ZEkQjCwLQSxQ0AuqLknNDijSCoPQeCBaOOHxi9JoUaHCQjWMbi0-cda_Ktz_pfO3vO958fPzxsMJWKJoYS1tnWR7NhMfsbESifjmXVcdmKjzsYYWvcSOeaQNEwvquM2WRI2cznZ3k2dpA6obC2X2RZuo8jBaw8bdUoJd0jJXnUEuMTG2RW6rDoADfmEkoSMCIzA_5u2EAXW4xDLwIXUnQgaIokgO2OB8qCkg1SfS0yRF0bcDRnlaFmpF4JousCmBNDoRJkgULuvZ9Ry-kDfg18GxIGBuMn66h7k-vYu-NLtrJKembSv76zQnKvPGF2Rag8zu3sUl3kMIf04j28goBTXTvXubpOfNEAsMm0eolyPK2b6DqE56wxhgmDXaD9jYArgFIhWzJcsDBAkxSHRGB6o5WbbXMkbrD1-bv9r6vhSpwK1Tx5VSm0Vrs3OWVYSZCnoX2kTE1DtpZ7cnOH1nyZcnxstriQ4fBJrE41JwF-YPsRjp1kIuTHXXgISeDxG9lBcY5rP18b3L81jkzbWTBGPAPNvehv4aOzXMLa6E71PnbraMBdfJuBCLq_jvDBVVXqbfTE0fYbZmhpFtEfDgGHfD7UrQVskPJGCMCV9ChW1VgSr0GWeDn2huAIvC4kMDwNwtURospy4Ldwmb6oUOM6GQgncNtl9qBvyDNCtj8C9y8I4inVejHAr22uVRYj0JOodnrQaWMX2yo-uwtRrN4CWBTSkfOA9SM29BBj51RWogqrVYE7W_IjOR3tEx-LRJ_Clzsq73ePT_dFuElzrMbilWdph67QiTsxhoCoQmzwphMgEMkp1q9cSuqbwIhqcNVZaQhkmTcrhyohE4G8gg2eYag-KMgS-WggXQw7vYjfUDHRG9zqWVvaBeNuRtKXbjkOdGQRmqznmiJBFvXMAWaDNs3oYx7sYd6F1eW0NPr4FvlRVw5xhZs-mZTFEeG6gOfcU9VHoSU08KUOfUSJdjaHyiQLTpaSBQEQJKVwUUV9i32MUqtyoxSou-hI1t80qzhdE7o7Nz4fM4joo12lqYlG5iPSn4_EEHMZ04UysF9k3d3t3MvYc6hnTtF8BBouYFL2OR3Q4npMszzNI7sGZlRMFyOwWZW62YhJzgqypc8QPXU9gDXUQihCVTHPkkoABF32tfalB-XhIPTcEIIFVEAriAnNdriSVdHQCXOjM3pr65y3c0Ofn5r-9JWfEl5yRbcis3Xd4JmlH-uZ2Jmaz1GHlfLT9pRltLoFw0AtJFkf1TJyouu-1l5qtU_2-ioGbdfQXXqW_KJ6DsC4Q84MRfcL1ujK-ZHoDiQnUcTcQVK7MfZcdSR8iUhKieRAijMAsIpdB9u0rJHGIGAVj8ZDZgpIs8CPicSw5RJcoVFz4JFzT1GftYvc5MhVdFN_PI4aRWnZXBYGLSdT51WyKRZgBR52mWensaVvUXJnxjLQTx0VzgdDVHAEez_b5ngmvQzvYQzpFu_VnkV3WU1iAyj7bGtXXwUBdLYx9lecm2p1DiWs2EfLg2u70mOykSt4aAtWhSzwPSRqGFOEgCiPEzbt2FLs-92QUGjFD3UW9wFOuj-E7T4YqZD4EEeSK0X4-KdS80ILkTgMLugyX95dde71V7CCTJdZkZ_UX7hARaT2zhvHM1gomvtuDyvZ9e6f-dbSlL-0PwC2-Y6vl8eIWzKV28FzE5udpTAIBFt7MZaGeObwHF9pKJ_u2k90ujzy9Ae2OA-dtlXi-hYh2bZJanbQim8eEDELthZQpz3eRa6poRSgXVATaFSLShIEtU_OjkS6HMs03bzJGIdLSDXk7CRC0KTC6JDCyupX_DKM1lZkkqwOoXJUY7T44Pnv-QAWHvKfZGO7uYWSZuQm2MOK6KDWkmvtxHiS6xXTJoSCOOKXUla7ygJVSBC4NI0zgA8aYE-m7kRsh5vqIQ4oGnxSEv5BiHUZubwuj15bOl6yJLveESCs3nqepdYJsU-P5w2N79gSYXb-dXR2XqAYjbzamkteqzBtBkHgv0EoAbPe18cNBzvazZvI3EuwSeK8UcVd2uL-cVKu8_LZIDy9KNUmD66UYiKBggliGqBauqdkZ933mK-7piEbC_jqbFaJHqZQellEEyU_kB1pQDyqwdqEO7q47ScRLzadm5792RSZ7C1v5oP3NLsOQdXngHGht_ofJAIbtqcJsGcwZ9tnc49PmFui9FL5GLtZupBWCZAAyQe0HSkMGDeGFMUgYMPUiyBxY6CnIGhWBslTjCGvTAm9yS_Zwiy6l1Eaf-rlVFfCmb12s5VQNsp5PtOeUj3Z-jtN7WP_nyR-T0X5sfhYPwsN4suQkfMqVH0DkpZgJLgTVnEWYYqWCKAD1cQPgmAvlmdkVh7SLQcEhGWOmOPOFaJ9KYazX-HGj319vkUDAMeHCxCxgigmts_A563FaO2t02KgNjM39FnApqDsLbu-2Lbr5dn-gYu0IPfVlz_oFmNkbKuZrs-FmuvulPaPSGFFn1JXSVn7I11GW23dZ-sTaWYYfQYEfhyaGZEUxKSAuJSBNW3oHeTzO0ml7dzRUEklP6DA0zXwBDl75UkQ88hB4_RAHQmifhgJchMKR4FoF1ONSECE8kwg1Y25fR-8c_jt29tptU9mOycRd2WCZH5qrnGrNSPty0aV5zae-4RtS6Co9JjZycNZMX_p4xzsi5pEJBGdafRmdqDzRXyfmbNnSPkkofYFDhgIWBeAxEFae63s4MDtoHjwLAshUIT3V2lVcMSi4uWAslCxSGjLV6LHx8nylYGSizbi5yewl6pvxExcquc3seYHCwV0HBjYXYXn70vGRSWDmbYLZjwyCwQErc2u8Rfs8AxId6DXyIfqofOgiyWY_-Ln4lZb5-xKzn3htQFUetXFcGONVoNkVlvOJyCqMSWUbs7h9SzXO_iK2CjS7kW8-Ee-bqElYL1DjPDfqRalxOBx3ULa4J30-leyFmt3RM5-wg8bZb3_Np-tgeeuHR-aAomeyJi-8rsnsz-fNQdAqSBXxGnjPdKU-z7zmLHPzCHMXRwxDnF1_WkAWUlua03UCvIuZS8PwsGGrKr_Kjidi1EXMA1gZy3jkkF6r7FTMLpzI0xg8jAt4Q8Po05DkT1tt4LAubqIHJNylUA9IoHJ0j12oQ5X4U9Z5QP_6HP6AmcnT7Qg9hRL6NGVAT1M9-rB8VoNgB2sfO2-Xgj2R8kGupyNKP4zQE_wgeYjueRR8pAC72fwkDWNPGTTIKlfTnGF5zgBK2ZMZi5-givxp1kSepsHk8XpGn-77n6DV6MnMJ0OMsyOpHZbVPoj4n0iCBspyNYkeLAj-BMV8uiT-hMYMdcztSmGt4XQXFYOF8wDr-gqSAX4GP5nBT_QZwyW6WjcNoIcM4FRHtTVYEvTJ_GJPCXhDbGa1MBys6Q_g1FtU7tRVpX3F1749az7tZ2kUX1VVZ3ozmc2iUz2enhZ7WWF-W840aK9eb73P0tmvtTRh_dnvp8_vrrNb9nP0WsDVHbr2R8KKBSTugDR1r32h9dDgYpoxh_c3WTExP1bpZ1miVVq_J7w6tprfbjhe6_Ays1OsX05Xq9RrnsTl3nS-izK7nOyhZdso23Ns5ua7h4bp2eatudZ-RuTl9EYvWG_Ir9573plJ7NXOmSqvP0R7kzgxWwt_H_0_FRVwfg==

**Comment by Wires77** [comment]
Everything looks to be in order with this build.  There is nothing in your build that suggests having an extra brand would increase the damage your minions do.  In fact, removing the brand you do have (manually casting Frostbite, instead of using Hextouch) would deal the exact same damage your minions do right now.

PoB only calculates the damage from your main skill, and does not total up the damage from multiple skills, if that is what you were expecting.

Please let me know if I'm missing something and I can reopen the issue.
