### ISSUE TITLE
Herald of Ash does not provide more burning damage

### ISSUE THREAD

**Issue by Yahkobbb** [PathOfBuildingCommunity/PathOfBuilding#1821]
Herald of Ash should provide 0-38% more burning damage, but even at level 20 it provides 0%.
Can easily be tested with Scorching Ray/Any ignite.

**Comment by Wires77** [comment]
The "More Burning Damage" mod on Herald of Ash only applies to the overkill burn caused by Herald of Ash itself.

https://pathofexile.gamepedia.com/Herald_of_Ash#Skill_functions_and_interactions
