### ISSUE TITLE
Error opening PoB

### ISSUE THREAD

**Issue by wolfie-poe** [PathOfBuildingCommunity/PathOfBuilding#1825]
Hi there,

* **What happened?**
PoB finished loading screen and showed error screen as below:
![Screenshot 2021-01-08 145229](https://user-images.githubusercontent.com/21091886/104063271-882b2900-51c1-11eb-91ce-710fd136a1fb.png)
![Screenshot 2021-01-08 145254](https://user-images.githubusercontent.com/21091886/104063284-8cefdd00-51c1-11eb-8882-885ef80b804c.png)

* **What were you trying to do?**
Just try to open PoB. Worked with no issue a day ago.

* **What steps will reproduce the bug?**
Not sure. I cannot get past the loading screen to get any info for further debug.

* **Does it reproduce every time?**
Yes. I basically cannot use PoB. I intend to re-install it, but I don't know if doing this would clear my stored builds that I'm working on.

* **Provide a build code:**

* **Screenshots:**
Please see above.

Thanks.

**Comment by Wires77** [comment]
Your builds are stored as XML files in your PoB install location in the folder named "Builds", so you can back those up if you'd like and do a complete reinstall.

**Comment by BootsElectric** [comment]
Hi I have also encountered this issue:

![poberror1](https://user-images.githubusercontent.com/22768146/104120447-e32e5e80-532e-11eb-9df1-ac4e8ba2afe4.PNG)
![poberror2](https://user-images.githubusercontent.com/22768146/104120453-ede8f380-532e-11eb-8af1-507239c67598.PNG)

I used Windows 10's  Settings: Apps and Features functionality to uninstall PoB community branch, then downloaded and installed the latest release from here (Release 1.4.170.20) and I'm still experiencing the issue.

Thanks.

**Comment by wolfie-poe** [comment]
Hi guys,

I have managed to fix the issue. Look like there is some configuration conflict after the update. The culprit seems to be located on the setting file: 
```
C:\<path>\Documents\Path of Building
Settings.xml
```

What I have done to get it (hot)-fixed :
1) Back up my Build folder as @Wires77 suggested. The build folder can be located on the same path as the Settings.xml aforementioned.
2) Uninstall Path of Building entirely, including removing the Settings.xml.
3) Re-install Path of Building with the latest version.
4) Copy your build backup back to `C:\<path>\Documents\Path of Building`.

From what I observed, my old Path of Building was installed to: `C:\Program File (x86\` while the default location for the new installation is: `C:\<path>\AppData\Roaming\Path of Building Community`.

Hope it helps.

**Comment by BootsElectric** [comment]
Hi,

This is also now resolved for me as well. 

In my case it turned out I had two different Settings.xml files in totally different drives, one of which being in the path @wolfie-poe pointed out (thanks for that), which I didn't realise was still there.

I removed the copy in that path and now PoB works fine.

Thanks.

**Comment by ppoelzl** [comment]
I've updated the relevant wiki page [here](https://github.com/PathOfBuildingCommunity/PathOfBuilding/wiki/Installing-this-Fork) to help adress this. Thank you @wolfie-poe and @BootsElectric for triaging this bug.

**Comment by JariGhysens** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/70757555/55d3de0a-c0a7-42dd-bc7b-b3c36c835325)

any advice on how to fix this issue? tried reintallind in different locations but no succes.

**Comment by Wires77** [comment]
> ![image](https://user-images.githubusercontent.com/70757555/270724633-55d3de0a-c0a7-42dd-bc7b-b3c36c835325.png)
> 
> any advice on how to fix this issue? tried reintallind in different locations but no succes.

Try deleting your Settings.xml file (make a backup first) and relaunching
