### ISSUE TITLE
pastebinp.com support

### ISSUE THREAD

**Issue by Jonixo** [PathOfBuildingCommunity/PathOfBuilding#1833]
Pastebin.com is (strangely) one of the inaccessible websites in Turkey (Not sure if its blocked anywhere else). We use notepads, pastebin proxy or alternative websites to share PoB builds between us. If you can make it so "https://pastebinp.com" link also work for importing we would be grateful.

**Comment by ppoelzl** [comment]
Path of Building already supports specifying network proxies, accessible via the "Options" menu in the lower left corner. Using a proxy is our recommended way to access blocked websites.
