### ISSUE TITLE
[Enhancement] Tree/Skill/Item/Calc views side by side

### ISSUE THREAD

**Issue by Rekrii** [PathOfBuildingCommunity/PathOfBuilding#1836]
**Is your feature request related to a problem? Please describe.**
Unrelated to a problem. Enhancement for rapid testing of skill/item/passive combinations. I'm currently trying to mix and match gems/passives/items and find it decent, however thought this may help the overall workflow.

**Describe the solution you'd like**
It would be great to be able to view two panels side by side, mockup below. 

![image](https://user-images.githubusercontent.com/32216352/104117264-dd4e7280-535a-11eb-83f7-3e7bb4d11df8.png)

**Pros / Cons**
Pros: Less clicks, more concurrent visibility of content
Cons: Increased clutter of the UI

**Additional context**
I have tried to look through the code base however I couldn't follow the UI flow unfortunately. I only suggest this **IF** it's fairly easy to add another 'UI element' and populate it with the required view. e.g. HTML would be fairly trivial to sneak in a new div and stick the component in it (data binding aside) - not sure if it's the same here!

**Comment by ppoelzl** [comment]
Not possible with the current application architecture. We're aware of this fact, but do not expect any improvements soon, if at all.
