### ISSUE TITLE
"Applying Update" is frozen

### ISSUE THREAD

**Issue by jesperhodge** [PathOfBuildingCommunity/PathOfBuilding#1838]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* I'm trying to update to the current version, today (10th jan 2021). The Update freezes in the Lua "Select UpdateApply" terminal while `Updating 'C:\Program Files (x86)\Path of Building Community/SimpleGraphic.dll'` (I left it for more than 2 hours but nothing happened). I assume everything will be fine once I uninstall it and just  install the latest version from the github, but I wanted to report the bug so you know about it.

I'm not sure what version I was on before. After quitting the Lua script with ctrl-c, PoB displays the current version as the installed version, but still shows "1 update available".

I was trying to update from within PoB by using the update button.

**Comment by ppoelzl** [comment]
See https://github.com/PathOfBuildingCommunity/PathOfBuilding/wiki/Installing-this-Fork.
