### ISSUE TITLE
Question> how do i import my old build xml files

### ISSUE THREAD

**Issue by eQuara** [PathOfBuildingCommunity/PathOfBuilding#1844]
i have my build files from 2league ago, but re installed, is there any way to install pob from this files or move these files to somewhere else?

**Comment by Wires77** [comment]
You can move those old build files (the .xml files) to the "Builds" folder in the same location where you installed PoB this time.

**Comment by eQuara** [comment]
pob didnt create "builds" folder after install even i saved few builds after that. there was no such a folder,  i copied old folder inside pob fork folder but that builds didnt show up in pob.
