### ISSUE TITLE
Error occurs when hovering over Gem Selector in Skills-Tab.

### ISSUE THREAD

**Issue by Iconoclast117** [PathOfBuildingCommunity/PathOfBuilding#1858]
* **What happened?**
Was hovering over the Gem Selector Menue in the Skills Tab as error appeared.
* **What were you trying to do?**
Selecting a gem.
* **What steps will reproduce the bug?**
Description above
* **Does it reproduce every time?**
Yes

* **Screenshots:**

![Screenshot 2021-01-13 153850](https://user-images.githubusercontent.com/77398217/104466413-80022d80-55b5-11eb-9740-89755751dc7a.png)
![2](https://user-images.githubusercontent.com/77398217/104466666-c5bef600-55b5-11eb-923f-a25004ef1a1b.png)

**Comment by Wires77** [comment]
Fixed in v1.4.170.24
