### ISSUE TITLE
Convergence persists when Elementalist's Heart of Destruction is unallocated

### ISSUE THREAD

**Issue by benjaminysmall** [PathOfBuildingCommunity/PathOfBuilding#1861]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* The new Elementalist node Heart of Destruction does not need to be allocated in order to have the Convergence (30% more ele damage) buff.
* **What were you trying to do?**
* Test allocating and unallocating Heart of Destruction. I expected that unallocating Heart of Destruction would remove the buffs it grants without having to manually take that step in the Configuration section.
* **What steps will reproduce the bug?**
* Allocate Heart of Destruction
* In Configuration, check the box for "Do you have Convergence?"
* Unallocate Heart of Destruction
* You retain the Convergence (30% more ele damage) buff
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* https://pastebin.com/JhBmcgt9
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
![image](https://user-images.githubusercontent.com/38334727/104467882-cf7c3580-5584-11eb-8c3c-33f46abbdbb6.png)
![image](https://user-images.githubusercontent.com/38334727/104467926-dc992480-5584-11eb-8a6e-75ea83b48cc4.png)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
Fixed in v1.4.170.24
