### ISSUE TITLE
Fanatacism is incorrectly applying area and mana cost buff to attacks

### ISSUE THREAD

**Issue by Oogablast** [PathOfBuildingCommunity/PathOfBuilding#1863]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* The mana cost and area of effect portion of the Fanatacism buff from Inquisitor's Instrument of Zeal was being applied to Attacks when the tool tip specifies Spells
* **What were you trying to do?**
* Checking tool tip numbers
* **What steps will reproduce the bug?**
* Adding an attack to Skills tab and allocating Inquisitor's Instrument of Zeal then checking off Fanatacism in the Configuration tab
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* https://pastebin.com/ZG0x12dM
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* 
![image](https://user-images.githubusercontent.com/53131972/104469969-208d2900-5587-11eb-9dff-bd9d0589a70b.png)
![image](https://user-images.githubusercontent.com/53131972/104470019-339ff900-5587-11eb-833b-cb04b42189c4.png)
![image](https://user-images.githubusercontent.com/53131972/104470116-57fbd580-5587-11eb-974c-679413f802c0.png)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
Fixed in 1.4.170.26
