### ISSUE TITLE
Heart of Destruction's ''Convergence'' buff does not affect spells like Scorching Ray and Flame Wall while it theoretically should.

### ISSUE THREAD

**Issue by Amunkar1** [PathOfBuildingCommunity/PathOfBuilding#1865]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Allocating Heart of Destruction and setting the state of the buff on Elemental Damage is not giving the 30% more elemental damage multiplier to Scorching Ray and Flame Wall. According to the PoE Wiki, elemental damage modifiers should scale with Scorching Ray and Flame wall. The area of effect state of Heart of Destruction does add properly to Flame Wall.
* **What were you trying to do?**
* Trying to integrate the Heart of Destruction notable from Elementalist to my build for optimization.
* **What steps will reproduce the bug?**
* - Open a new build template
* - Select Scorching Ray/Flame Wall as main skill
* - Allocate Heart of Destruction notable (Make sure to note the dps of the skill with passives taken up to Heart of Destruction_
* - Set the state of Heart of Destruction to ''elemental damage''
* - This should replicate the issue
* **Does it reproduce every time?**
* Yes, the bug reproduces everytime
* **Provide a build code:**
* https://pastebin.com/bSjkVGCh
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* 
![image](https://user-images.githubusercontent.com/77399511/104470884-7cbd7080-55ba-11eb-9110-b390a201661a.png)
![image](https://user-images.githubusercontent.com/77399511/104471083-b5f5e080-55ba-11eb-8c8d-796f7f41671f.png)
![image](https://user-images.githubusercontent.com/77399511/104471170-d1f98200-55ba-11eb-88f3-ba874315d67d.png)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by benjaminysmall** [comment]
Hi, the way it's currently implemented, the "Is Pendulum of Destruction active?" doesn't trigger the Convergence buff, there's a separate "Do you have Convergence?" checkbox (right above that) in the Configuration section. That checkbox does currently work (although it shows up under Lightning/Cold/Fire in the Calc screen, not "All Types" as in your screenshot).

Not saying this isn't a bug, it may still need changing, but in the meantime, there is an option for forcing Convergence.

**Comment by Amunkar1** [comment]
You are correct, benjamin. Thank you for informing me. I will close the bug report, as this is obviously not a bug.
