### ISSUE TITLE
Shaper of Flames more damage with ignites is not reflected in left side calc(and tooltips)

### ISSUE THREAD

**Issue by zfire** [PathOfBuildingCommunity/PathOfBuilding#1866]
* **What happened?**
More damage with ignites is not reflected in left hand side calc, but is visible in calc tab
* **What were you trying to do?**
Activate more damage with ignites from Shaper of Flames by having hit being largest with fire
* **What steps will reproduce the bug?**
Allocate small node just before Magmatic Strikes will change between fire being largest and not in supplied build
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/nL0Wfe40
* **Screenshots:**
![bug](https://user-images.githubusercontent.com/680630/104471878-a7f48f80-55bb-11eb-9b5c-38c890be7d42.png)

**Comment by fenlen** [comment]
Can confirm that the bug happens even when the hit is purely fire damage.

**Comment by AlphSpirit** [comment]
Can confirm this happens with a 100% fire hit with Burning Arrow, the damage is updated in the Calcs tab but not on the left side as @zfire said. Here is another working example: [https://pastebin.com/b2w547vY](https://pastebin.com/b2w547vY)

**Comment by Nostrademous** [comment]
Fixed in .22
