### ISSUE TITLE
Error in grantedEffectLevel when looking at Vitality.

### ISSUE THREAD

**Issue by Derasm** [PathOfBuildingCommunity/PathOfBuilding#1867]
Error occurs when choosing Vitality as skill gem. Clicking on the line pops a white Error box up with the following error.
![image](https://user-images.githubusercontent.com/22821429/104475257-2c94dd00-55bf-11eb-971c-138c5acdac7d.png)

**Comment by Wires77** [comment]
Duplicate of #1858
