### ISSUE TITLE
Error while trying to import a build

### ISSUE THREAD

**Issue by nogenem** [PathOfBuildingCommunity/PathOfBuilding#1868]
* What happened?
Error appeared
* What were you trying to do?
Import a build using a pastebin link
* What steps will reproduce the bug?
Just import the build
* Does it reproduce every time?
yes
* Provide a build code:
https://pastebin.com/JdVv3Za7
* Screenshots:
https://i.imgur.com/jbzMOCb.png

**Comment by carpentre1** [comment]
I'm getting the same error when loading a different build. The build loaded correctly prior to the latest update (1.4.170.21).
Build: https://pastebin.com/3ynJAaN9

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.22.
