### ISSUE TITLE
Hierophant "Conviction of Power" +1 to maximum charges not working

### ISSUE THREAD

**Issue by Tantrisse** [PathOfBuildingCommunity/PathOfBuilding#1870]
Edit : Btw, hi and thanks for all your work, you all rocks !

* **What happened?**

The "Conviction of Power" node on Hierophant ascendency is not correctly setting the maximum of power and endurance charge (it display 3 power and endurance charge in the calc tab instead of 4).

You can force PoB to calculate your DPS with 4 Power charge by manually setting in the configuration tab "Do you use Power Charges" to 4 but if we take another +1 max in the tree we need to change this again...

The problem seems to be with the line "+1 to Maximum Power Charges and Maximum Endurance Charges" not being parsed ?

* **What steps will reproduce the bug?**

  - Create a fresh build
  - Set as Hierophant
  - Click the "Conviction of Power" node
  - Check the calc tab
  - On top it display "Combat Buffs : 3 Power Charges, 3 Endurance Charges"

* **Does it reproduce every time?**
  * Yep
* **Provide a build code:**
  * Irrelevant, only the "Conviction of Power node is needed to see the bug

**Comment by Tantrisse** [comment]
Seem to be fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1860 feel free to close if it's the case !

**Comment by Nostrademous** [comment]
Yes, that PR will fix this issue. Leaving this open as it will get auto-closed when that PR is merged and it will "hopefully" prevent others from reporting the same issue.
