### ISSUE TITLE
Rupture not showing on Configuration even after allocating Rupturing

### ISSUE THREAD

**Issue by rmallermartins** [PathOfBuildingCommunity/PathOfBuilding#1873]
* **What happened?**
  * Rupture not showing on Configuration even after allocating Rupturing
* **What were you trying to do?**
  * Use Rupture for calculating DPS
* **What steps will reproduce the bug?**
  * Allocate Rupturing as Deadeye
  * Equip bow for % to Crit
  * Split Arrow + Chance to Bleed Support for inflicting Bleed
  * Go to Configuration tab
* **Does it reproduce every time?**
  * In my case Yes. For New and Existing Builds
* **Provide a build code:**
  * https://pastebin.com/3hhYn1zX
* **Screenshots:**
![image](https://user-images.githubusercontent.com/2859673/104481501-a075bc00-55a4-11eb-8929-55fe6e1e6de4.png)

**Comment by Wires77** [comment]
Fixed on the latest version, check for a new update
