### ISSUE TITLE
Renewal (cluster notable) is now showing as 6% chance instead of 5% chance

### ISSUE THREAD

**Issue by dannyo13** [PathOfBuildingCommunity/PathOfBuilding#1874]
As per the patch notes yesterday the Renewal node on cluster jewels (large and medium) was reduced from 10% chance to 5% chance. 

![image](https://user-images.githubusercontent.com/8967100/104482820-a196f100-5584-11eb-95cf-26b246ba2aa5.png)

After the most recent POB update Renewal is showing as 6% chance

![image](https://user-images.githubusercontent.com/8967100/104482726-7f9d6e80-5584-11eb-9572-d44c27a646e2.png)

**Comment by zfire** [comment]
This is imported from the official passive tree dump. So either that is incorrect or the patch notes are.

**Comment by dannyo13** [comment]
Lets hope its the patch notes an extra 1% would be nice =)

**Comment by Wires77** [comment]
Actually, since cluster jewels are items (not part of the passive tree), they'll be generated when we get the game files.  This will be updated the day of the release, most likely.
