### ISSUE TITLE
Error when selecting spell gems.

### ISSUE THREAD

**Issue by hemal4d** [PathOfBuildingCommunity/PathOfBuilding#1878]
Occasionally when selecting spell gems, I will get this error:
![Capture](https://user-images.githubusercontent.com/77367939/104483864-977dee00-5596-11eb-9548-ce08f94735fb.PNG)
Sometimes it will temporarily reduce the damage of the spell, as if disabling a support gem at random. It can be fixed by disabling and reenabling the unregistered gem.

**Comment by Teonlight** [comment]
Is Elementalist>Shaper of Flames allocated? I have this same issue but can only reproduce it when shaper of flames is allocated.

**Comment by hemal4d** [comment]
no, I'm playing trickster

**Comment by hemal4d** [comment]
> Is Elementalist>Shaper of Flames allocated? I have this same issue but can only reproduce it when shaper of flames is allocated.

No, I'm playing trickster

**Comment by Shadownot** [comment]
Same error when trying to select a spell to socket in Cospri's Malice as inquisitor.

**Comment by Danjojo** [comment]
i also get this all the time when hovering over some gems but i dont have the same error code. the build im on doesnt seem to matter

![image](https://user-images.githubusercontent.com/77409843/104501915-3c57f580-55ae-11eb-8729-f745de8509bb.png)

**Comment by Danjojo** [comment]
i just got this one when i hover on empower/enlighten/enhance socketed in a ngamahu's flame
![image](https://user-images.githubusercontent.com/77409843/104503232-ca33e080-55ae-11eb-99ab-5e9c18a98214.png)

**Comment by ActuallySkeletor** [comment]
> Is Elementalist>Shaper of Flames allocated? I have this same issue but can only reproduce it when shaper of flames is allocated.

I just got this error while doing elementalist with Shaper of Flames allocated. I click it, then try to add Armageddon Brand as a skill and I get pretty much the same error message.

**Comment by Flopolopogus** [comment]
i have the same issue wile modifying gems randomly as a raider

**Comment by Flopolopogus** [comment]
i get the same error when picking gems for a raider
![image](https://user-images.githubusercontent.com/77415109/104514536-a5d80400-55ae-11eb-9bc3-c15ee5d40980.png)

**Comment by Flopolopogus** [comment]
it happens excatly when i move my mouse into the window to select a gem

**Comment by Flopolopogus** [comment]
I can get it to pop up while typing frost some times in the skill window 
![image](https://user-images.githubusercontent.com/77415109/104514729-f7808e80-55ae-11eb-92ee-def48eeb1987.png)

**Comment by Flopolopogus** [comment]
it goes away if i remove the gem

**Comment by Wires77** [comment]
For those of you that are getting the error on gems that aren't Empower/Enlighten/Enhance/any gem that can't level to 20, try changing the variant quality from default to something else and back.

There is a fix coming, but let us know if that fixes the issue in the meantime.

**Comment by zmike** [comment]
I was having this with Fireball+High-Impact Mine+Minefield, triggered by mousing over any of the gems when Minefield was enabled.

Changing the quality for the gems to an alternate type and then back to default seems to have resolved it.

**Comment by Wires77** [comment]
Fixed by #1897 in the next release
