### ISSUE TITLE
Enduring Cry/Endurance Charge Issues

### ISSUE THREAD

**Issue by DonChalant** [PathOfBuildingCommunity/PathOfBuilding#1883]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* Enduring Cry seems to not properly calculate the added physical damage reduction and elemental resistance. With 7 endurance charges, I receive +0% Physical Damage Reduction and +4% Elemental Resistance. Also, when selecting a node to grant +1 Maximum Endurance Charge, the prediction window claims I will gain +5% resistances, but when it's 
* Activate Enduring Cry
* Activating Enduring Cry with several endurance charges and not being capped on resistances
* It seems to be consistent, but I only noticed the +5% issue once
* https://pastebin.com/Reup1i5s
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Debugnium** [comment]
Yeah, I had issues with this too. It seems that it is scaling that buff from increased duration for some reason, the more duration I had on enduring cry the higher the phys damage reduction and bonus resistances.

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
