### ISSUE TITLE
Exponential Filesize increase cause by renaming flasks

### ISSUE THREAD

**Issue by PlayLikeJay** [PathOfBuildingCommunity/PathOfBuilding#1887]
Greetings,
the video describes the problem the best.
tl;dr: Having a colon (the : sign) at the start of the name of a within pob crafted flask adds multiple lines to the description of the flask whenever the flask is loaded / saved causing for exponential file size increases when working with a save which will cause severe lag and making the save unable to load after a short period of time.

https://youtu.be/dyGZOAsa9t8

**Comment by Wires77** [comment]
Thanks for the in-depth description of the issue.  Internally, a colon means a lot on an item, so it's trying to interpret your label in a special way.  If you remove the colon, your label should still work fine, but I'll get a fix for this out so you can continue labeling the way you're used to.

**Comment by PlayLikeJay** [comment]
The fix is already out! Thank you very much for your fast response and action!
