### ISSUE TITLE
Medium cluster jewel with aura effect has 6% increased effect instead of 3%

### ISSUE THREAD

**Issue by Qwertzr** [PathOfBuildingCommunity/PathOfBuilding#1889]
As per patch notes 3.13:
Medium cluster jewels should grant: Added small passive skills grant: 3% increased effect of non-curse Auras from your skills.

In updated PoB (1.4.170.21) is still old value of 6% shown on imported cluster jewels and also on cluster jewels created by PoB Craft item... tool.

![image](https://user-images.githubusercontent.com/77411917/104504450-befaa800-55e2-11eb-8d9c-d2a15f30f188.png)

**Comment by Xebtria** [comment]
Changes to the cluster jewels are not yet included in the update, see the notes in the "about" window
