### ISSUE TITLE
Blackflame ring calculating ignite dps incorrectly

### ISSUE THREAD

**Issue by Pelmis** [PathOfBuildingCommunity/PathOfBuilding#1890]
Blackflame ring as said in the Q&A "It works like a "damage taken as X" stat. Essentially, your ignites will scale with your own fire/burning damage stats as usual and not with chaos damage stats. However, the monster's damage taken will be scaled by chaos damage affecting stats like chaos resistance and wither (and not by fire resistance, etc)."
However, currently in POB community fork, it appears like chaos damage and chaos damage over time are being applied to the ignite damage. https://pastebin.com/9AEySv6E is a build with this happening.

**Comment by Quotae** [comment]
In the build you provided, this is happening because your skill is Hexblast, which has base Chaos Damage and says "All Damage can Ignite". If you take increased Chaos Damage on a skill that doesn't have any base Chaos Damage, like Fireball, you'll see that the ignite DPS does not increase.
