### ISSUE TITLE
Fanaticism Bug: Applying to other passives trees once its checked

### ISSUE THREAD

**Issue by puppy000** [PathOfBuildingCommunity/PathOfBuilding#1891]
The new inquisitor node, instruments of zeal, has a buff "Fanaticism" that needs to be checked in the calculation tab in order for the buff to apply its affects to the calculations. Making a new tree with the "Manage Tree" function inherits that fanaticism buff regardless if you are inquisitor or not. You cannot uncheck fanaticism unless you go back to the inquisitor tree and uncheck it from the calculations. 

Reproducing the Bug: Make an inquisitor with instruments of zeal, check "Do you have Fanaticism?" in calcs, and then create a new a tree with the "Manage Tree" function with any class. The new tree will now have the fanaticisms buffs already applied to it. 

PoB code that has the bug: https://pastebin.com/nLHkZLqh

**Comment by Wires77** [comment]
Fixed by #1944 in v1.4.170.24
