### ISSUE TITLE
Error when hovering over Empower after Echos of Atlas update

### ISSUE THREAD

**Issue by Omegazed** [PathOfBuildingCommunity/PathOfBuilding#1896]
Worked fine before update, but after I applied update this happened
![Screenshot (15)](https://user-images.githubusercontent.com/30607929/104522086-36710d00-55cc-11eb-98a0-ba883c281259.png)

after a bit of messing around, it throws up the error when i open up the gem select menu over a gem already in the build and scroll to Empower. 
https://pastebin.com/kcnG367X

**Comment by Omegazed** [comment]
Detonate Mines also seems to cause this error
![image](https://user-images.githubusercontent.com/30607929/104526040-81d8ea80-55cf-11eb-8433-a0fe5b27734c.png)

**Comment by Hapseleg** [comment]
Also for incinerate
![image](https://user-images.githubusercontent.com/12915302/104528503-c2ecf100-5607-11eb-8320-4585f026596a.png)

**Comment by Omegazed** [comment]
try clicking on incinerate and scrolling through the list of gems?

**Comment by Wires77** [comment]
Duplicates #1878
