### ISSUE TITLE
Error when uploading build from pastebin

### ISSUE THREAD

**Issue by Aionurin** [PathOfBuildingCommunity/PathOfBuilding#1900]
* **What happened?**
Got weird bug!
* **What were you trying to do?**
Import my new starter build
* **What steps will reproduce the bug?**
Just normal import from link and copy from code, doesnt matter which
* **Does it reproduce every time?**
Yes, every single time...
* **Provide a build code:**
https://pastebin.com/teRdK2cX
* **Screenshots:**
![Capture](https://user-images.githubusercontent.com/77421558/104532650-fe3fed80-5610-11eb-8330-f210dff2ccf8.PNG)

**Comment by Wires77** [comment]
Seems like you're using the wrong version of PoB.  The bottom left corner should say "PoB Community Fork"  Download the latest one from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases

Feel free to reopen this issue if that's not the case.
