### ISSUE TITLE
The current Ascendency Elementalist Grid in PoB does not reflect the current structure in PoE.

### ISSUE THREAD

**Issue by TheNinjaofEarth** [PathOfBuildingCommunity/PathOfBuilding#1905]
![image](https://user-images.githubusercontent.com/36244470/104544891-8791f880-55ee-11eb-9e4d-9391972419a8.png)

**Comment by Wires77** [comment]
Path of Building has begun updating for the next league already, so by this weekend, the tree in PoE will reflect the tree in PoB.  We release the tree updates before the league starts so people can begin planning their new builds.

**Comment by TheNinjaofEarth** [comment]
Ok. Thank you.
