### ISSUE TITLE
Issue with shock calculations 

### ISSUE THREAD

**Issue by pomegranate013** [PathOfBuildingCommunity/PathOfBuilding#1907]
All PoBs from the following Version
![image](https://user-images.githubusercontent.com/77426893/104547283-041eda00-55e3-11eb-9541-99db997052ee.png)

* **What happened?**

PoB is computing strange numbers for shock calculations. Here are two different examples where I am seeing numbers I believe to be incorrect. 

Test #1 (https://pastebin.com/Mnpn5BpA) I have the following modifiers to lightning ailments
- 20% increased from the notable node Breath of Lightning
- 10% increased from the small node Lightning Damage and Lightning Ailment Effect 
- 15% increased from the small ascendancy node Elemental Damage, Lightning Ailment Effect
- 25% more Effect of Lightning Ailments you inflict with Hits if the highest Damage Type is Lightning from the ascendancy node Shaper of Storms 

The expected effect of shock should therefor me

15*(1.45)*(1.25) = 27.1875

The actual effect of shock is 21.75 which is 15*(1.45), so the more multiplier is not apply in this case even though a skill only dealing lightning damage is selected. 

![image](https://user-images.githubusercontent.com/77426893/104547065-78a54900-55e2-11eb-8ab6-c8de9840b91d.png)

(Note there is a visual bug here although I cannot always reproduce this). 

Test #2 (https://pastebin.com/3ECENd8u) I thought perhaps the more multiplier just wasn't working but something wonkier seems to be happening. If we change the skill used from crackling lance to arc (which has built in 29% increased effect of lightning ailments at rank 20) we get the following results

Shock Effect Mod = +117%  Which is correct since (1+ .29+.2 +.1+.15)*(1.25) =  2.175 however the "Current Shock" value remains 21.75! 

![image](https://user-images.githubusercontent.com/77426893/104547034-63c8b580-55e2-11eb-84d4-8af4b95f17bc.png)

**I hypothesize there are two issues with the shock calculations 1) The more multiplier from Shaper of Storms is not applying  and 2) The increased ailment effect from the skill gem Arc is not applying to the final shock calculation. **

* **What were you trying to do?** 

Have a shockingly good time.

* **What steps will reproduce the bug?**

I have tried a number of lightning skills and different quantities of ailment effect and gotten results consistent with the conclusions I outlined above. 

* **Does it reproduce every time?**

As far as I can tell, yes. 

* **Provide a build code:**

https://pastebin.com/Mnpn5BpA
https://pastebin.com/3ECENd8u

**Comment by strates** [comment]
Another example:

![image](https://user-images.githubusercontent.com/7341158/104807229-56bfe800-57d5-11eb-91d0-11e963175093.png)

**Current Shock** value doesn't factor the "more" modifier from Shaper of Storms into account (15 base * 1.6 = 24, should be 15 * 1.6 * 1.25 = 30). The value for **Shock Effect Mod** correctly resolves to +100%, though.

Adding Unbound Ailments Support, it is listed in the **Shock Effect Mod** and the total value correctly resolves to +144%, but **Current Shock** value remains unchanged at 24%.

![image](https://user-images.githubusercontent.com/7341158/104807278-b74f2500-57d5-11eb-97e0-d5fff3554e24.png)

I assume increased ailment effect values inherent to the skills/supports as well as the "more" modifier from Shaper of Storms aren't picked up when calculating the **Current Shock** value, despite the **Shock Effect Mod** value being calculated correctly.

In both cases no override value was set for the shock value in the Config tab. Setting the shock value to the correct amount in the Config tab did change the damage numbers, so this isn't just a visual issue.

**Comment by Quotae** [comment]
I'm the one who did all the Shock stuff. You're correct in your second comment; only global modifiers to Shock effect will affect the automatic Shock. Arc's local effect, Elementalist's more effect (which depends on a skill's damage types and isn't global), etc. won't apply to the automatic Shock. Everything is working as I intended it to, though I understand it's not intuitive. 

My intention was that the Elementalist's Shock should be a baseline. No matter what you Shock with, if you have the node and the enemy is Shocked, that's the lowest Shock they could ever have. I allowed you to overwrite it in the Config for cases like Arc where the skill has some Shock effect of its own and the Shock would be bigger.

I added this automatic Shock stuff a few patches ago. Since 3.13 and the Elementalist's new node, I've seen several complaints about this, so I think I'm going to change it. I'm not 100% sure yet though.

**Comment by TTFTCUTS** [comment]
As a followup to this, currently using version 2.6.0:

Shock doesn't appear to be applying at all for chaos damage while using Voltaxic Rift. The added effect reads as +0%, though the "shock as if you're doing 300% more damage" appears to be in the threshold calculation.

![image](https://user-images.githubusercontent.com/5436317/127443901-ac1d4ac1-bd4e-4259-b66e-e65e1c1f73b9.png)

Example build (shock currently manually set to 20% as a stopgap):
[https://pastebin.com/grqzwi1t](https://pastebin.com/grqzwi1t)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4790.
