### ISSUE TITLE
Rupture stack damage is being calculated incorrectly

### ISSUE THREAD

**Issue by amille14** [PathOfBuildingCommunity/PathOfBuilding#1909]
* **What happened?**
The Rupture calculation introduced in the latest update is incorrect. It's providing way more damage than it should because rupture's "bleeding expires 25% more quickly" per stack is being interpreted as "bleeding you inflict deals damage 25% faster" per rupture stack (I believe). The wording is different from the "faster bleeds" we've seen elsewhere on the tree, and implies that rupture just shortens the duration of existing bleeds without increasing dps.

* **What were you trying to do?**
Add rupture to my build.

* **What steps will reproduce the bug?**
Create a Deadeye, allocate Rupture notable, go to configuration tab and add rupture stacks. Notice that bleed DPS increases by much more than 25% per stack. The tooltip when hovering over the input even states the incorrect calculation.

* **Does it reproduce every time?**
Yes.

* **Provide a build code:**
https://pastebin.com/jWKL7xPw (can just use any deadeye tree though). Go into the config and add 1 stack of rupture, notice how it adds around 50% more bleeding damage instead of just 25% more.

* **Screenshots:**
![image](https://user-images.githubusercontent.com/640065/104552098-1cecb700-5606-11eb-937d-98101a630e73.png)

**Comment by Wires77** [comment]
This calculation looks correct to me, you can go into the Calcs tab to see the detailed breakdown of the math in the Bleed section.  Here is your build's breakdown: 

![image](https://user-images.githubusercontent.com/1209372/104553640-a26d6880-5600-11eb-87b1-dd6a0046f906.png)

If you see anything wrong after doing the math here, feel free to reopen this issue.  Note that Rupture works much like Pride, so enemies take MORE physical damage.  Bleeding is also inflicted faster, which has an effect on your DPS as well.

**Comment by amille14** [comment]
@Wires77 "Bleeding is also inflicted faster, which has an effect on your DPS as well."

This is the part that's incorrect. The wording of Rupture is "bleeding **expires** 25% more quickly" and not "bleeding you inflict deals damage 25% faster". This wording implies it reduces the overall duration of the bleed but does _not_ increase the dps (aside from the other 25% more damage taken multiplier).

Here's a far simpler PoB with no points allocated besides Rupture to illustrate: https://pastebin.com/pEv6sq4a

Notice that there are two spearate 1.25x multipliers (one for effective dps modifier and one for damage rate modifier).
![image](https://user-images.githubusercontent.com/640065/104619241-a2e71d00-565b-11eb-915c-9026927eb4de.png)

**Comment by Wires77** [comment]
Right, I may have been premature in closing this.  We'll track the bug in #1917 and once we can test it in-game, update PoB.  I feel like your interpretation is correct, so we may update to that before league start, but there's no way to confirm until then.

**Comment by amille14** [comment]
Ok, thanks
