### ISSUE TITLE
Endless Hunger Slayer

### ISSUE THREAD

**Issue by lextra2** [PathOfBuildingCommunity/PathOfBuilding#1910]
Allocating the slayer notable "Endless Hunger" reduces player damage done.

https://pastebin.com/N4sXJCdg
(tick/untick the Endless Hunger slayer notable to see damage difference)

**Comment by Wires77** [comment]
Please fill out the bug report template complete with a test build and ideally a screenshot of the issue.  Both of these are working fine that I can see.

**Comment by Regisle** [comment]
Are you Leeching does nothing if you have leech and "Life leech effects are not removed at full life" as it assumes you will always be leeching

**Comment by lextra2** [comment]
> 
> 
> Please fill out the bug report template complete with a test build and ideally a screenshot of the issue. Both of these are working fine that I can see.

Added link to build.



> 
> 
> Are you Leeching does nothing if you have leech and "Life leech effects are not removed at full life" as it assumes you will always be leeching

Just check the build link and tick/untick leeching box yourself. I didn't set box for "Always full life"

**Comment by lextra2** [comment]
Correction: Got confused with 3.12 and 3.13. Leeching checkbox shouldn't change any damage value because there is no longer any passive for it. So this is working correctly.

BUT "Endless Hunger" still causes a damage loss, which I think is a bug.

**Comment by Wires77** [comment]
So, you're using Earthquake and checking the aftershock damage.  Normally, attack speed doesn't affect this damage at all.  However, you're using warcries, which means the higher your attack speed, the less often you'll have an exerted attack available when the aftershock goes off.  In addition, you're using Fist of War Support, which has a similar issue, in that it might go off on the initial hit and not on the aftershock.  Therefore, on average, your damage will go down.

If you want to assume you'll have exerted attacks up, change the configuration option here to assume you'll line up your warcries with the aftershock: 
![image](https://user-images.githubusercontent.com/1209372/104556231-cf237f00-5604-11eb-89bb-787a9f9bf10d.png)

**Comment by lextra2** [comment]
Ahh yes. Makes sense. Thanks for the detailed explanation. Closing.
