### ISSUE TITLE
Energy Leech Support does not appear to be accounted for in ES Leech/On Hit Rate sidebar stat

### ISSUE THREAD

**Issue by NoIguanaForZ** [PathOfBuildingCommunity/PathOfBuilding#1912]
This is as of 1.4.170.22.  1.9% of Damage Leeched as Energy Shield from Energy Leech support does not appear to be included in ES Leech/On Hit Rate sidebar stat, per attached images; enabling it has no effect on the displayed number.  It also does not appear on the list of modifiers to life leech rate, even though other sources of "% of damage leeched as energy shield" do, per the last [edit: I guess it wound up as the *first*] attached screen capture, so I don't *think* the issue is, say, that I'm misunderstanding what the number is meant to represent...

Build Code Pastebin is https://pastebin.com/Apx1aFaS if I'm understanding the instructions correctly.

Also appears that while checking "Are You Always on Full Energy Shield" under the Configuration tab implements the More Damage multiplier from Energy Shield Leech under that condition, there's no way to make the DPS sidebar reflect the More Damage when Leeching Energy Shield stat.  It seems like there's a more general issue with the implementation of that skill gem in POB Community Fork?

![pobug4](https://user-images.githubusercontent.com/77429991/104554883-be1d4280-55f1-11eb-9709-cc72c2d265dc.jpg)
![pobug3](https://user-images.githubusercontent.com/77429991/104554888-bfe70600-55f1-11eb-94dd-a368e46607ea.jpg)
![pobug2](https://user-images.githubusercontent.com/77429991/104554890-c07f9c80-55f1-11eb-9df4-9ebceb3e8cda.jpg)

**Comment by wjdeclan** [comment]
I'm pretty sure your Leech Rate can't exceed your Leech Cap, which is why the number isn't increasing. In a lower damage build where you're nowhere near the cap it seems to work fine. Also under Configuration -> When in Combat there is a "Are you Leeching Energy Shield?" toggle which lets you get the bonus damage.

**Comment by NoIguanaForZ** [comment]
Huh, okay.  I considered that it might be that or something close, but per the first image it doesn't even show up as a source in the tooltip.  I guess the program stops counting sources once the cap is reached?

Confirmed it works with lower-damage build as described, so never mind.
