### ISSUE TITLE
Flameblast not calculating stages 2 and up for Average Hit/DPS.

### ISSUE THREAD

**Issue by Duguall** [PathOfBuildingCommunity/PathOfBuilding#1914]
Version: 1.4.170.22

* **What happened?**
     Since the update for multi-stage configuration, flameblast has been broken on the average hit/DPS side of things. Ailment base damage is calculated correctly. 

* **What were you trying to do?**
     Create the average hit/DPS for flameblast at 10 stages.

* **What steps will reproduce the bug?**
     In either the left column or in Calculations, setting flameblast to any stages will scale ailment damage, but not average hit/DPS of the skill.

* **Does it reproduce every time?**
     Yes

* **Provide a build code:**
     This works from scratch with nothing equipped but flameblast, but I will provide a code from poe.ninja, and a code with nothing but flameblast.

poe.ninja: https://pastebin.com/RNp7AjCc
just flameblast: https://pastebin.com/YjLcMcGF

* **Screenshots:**
     Not Required

**Comment by Nostrademous** [comment]
Fixed in .24
