### ISSUE TITLE
Pastebin Links are all 404 

### ISSUE THREAD

**Issue by FlyingThunder** [PathOfBuildingCommunity/PathOfBuilding#1916]
Im on the newest version, whenever i try to generate a pastebin from my code and then look it up in a browser it says

Not Found (#404)
This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by Wires77** [comment]
Pastebin was deleting PoB builds for a while.  We have another solution coming, but this particular issue is out of our hands.
