### ISSUE TITLE
Rupture bleed DPS may be calculating incorrectly

### ISSUE THREAD

**Issue by PseudoError** [PathOfBuildingCommunity/PathOfBuilding#1917]
* **What happened?**
I looked at the calcs screen to see how the Rupture math was being done, and it seems that the "Bleeding on Ruptured targets expires 25% more quickly" is being done simply as the similar "Bleeding you inflict deals Damage X% faster" modifier. However, given that Rupture uses "more quickly" instead of just "faster", it may in fact be the case that it's a separate more multipler of the "deals Damage faster" modifier. I obviously don't know yet until the patch comes out proper to play with it so it may not be a bug at all, but it's something that should be checked once possible. Or maybe you were able to get some GGG dev input on the matter.

* **What were you trying to do?**
Trying to figure out my bleed build DPS.

* **What steps will reproduce the bug?**
Look at the damage rate modifier stat in the Bleed Duration tooltip on the Calcs screen, with 3 Rupture stacks enabled and then 0 Rupture stacks enabled in the Configuration menu. See that the difference is exactly 0.75 apart. This may be correct, or it could be that you should be multiplying the 0 Rupture stacks damage rate modifier value by 1.75 instead of adding 0.75, which would be a larger value for most any bleed build.

* **Does it reproduce every time?**
Yes.

* **Provide a build code:**
https://pastebin.com/0RrBkS1r

**Comment by Nostrademous** [comment]
Fixed in 2.15.0
