### ISSUE TITLE
Elemental Equilibrium not working with cold DOT or Ignite.

### ISSUE THREAD

**Issue by Braunze** [PathOfBuildingCommunity/PathOfBuilding#1920]
I was working on a cold DOT build and with the latest patch, can't get Elemental Equilibrium work with the DOT damage.  I make sure it checkmark enemy was hit with lightning damage in configurations.  It will increase the 'average hit' stats but never the DOT as it should.  I also tried using the unique item malachai's artifice and put orb of storms in it and it doesn't work there either.  I went and tested a fresh ignite tree using fireball, no items, and same thing, it will increased hit damage but not the ignite DOT.  

https://pastebin.com/0igra52L

In my pastbin above you can see that taking EE off actually increased my DOT and lowers my average hit.

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/104584861-2122de00-56b3-11eb-8c07-ee8d3183be74.png)
