### ISSUE TITLE
Lioneye's Fall Viridian Jewel doesnt modify weapon types to bow 

### ISSUE THREAD

**Issue by nrique99** [PathOfBuildingCommunity/PathOfBuilding#1921]
Lioneye's Fall Viridian Jewel doesnt modify weapon types to bow.

**Comment by benjaminysmall** [comment]
Can you share a PoB link?

I think what's happening here is that the text on the node isn't changing, but it **is** working for damage calculations.

**Comment by cream1800** [comment]
Hi, I believe I have the same problem. This is the build I'm currently running: https://pastebin.com/MPHCanfT. I was wishing to compare damage from Lioneye's Fall to a group of cluster jewel but found that DPS wasn't calculated for the jewel.

**Comment by Incurablebookwyrm** [comment]
Also reporting Lioneye's Fall Viridian Jewel doesnt modify weapon types to bow.
Using this Bleed Bow build From Big Ducks
https://pastebin.com/BxTP2Ysq

It occurs even when importing from my actual character as well.
I can provide Screenshots upon request.

**Comment by benjaminysmall** [comment]
@cream1800 When I select and de-select nodes from inside the Lioneye's Fall radius, the calculated DPS appears to change for me. Can you be more specific about what you're seeing?

**Comment by benjaminysmall** [comment]
@Incurablebookwyrm I'm seeing the same thing I commented above -- the text of the nodes doesn't change, but the damage calculations appear to work correctly. Can you provide a screenshot of what you're seeing and describe how it's not working? Thanks!

> Also reporting Lioneye's Fall Viridian Jewel doesnt modify weapon types to bow.
> Using this Bleed Bow build From Big Ducks
> https://pastebin.com/BxTP2Ysq
> 
> It occurs even when importing from my actual character as well.
> I can provide Screenshots upon request.

**Comment by cream1800** [comment]
@benjaminysmall I'm now seeing the calculation. Not sure what happened, but thanks for the checking.

**Comment by Incurablebookwyrm** [comment]
@benjaminysmall It is displaying correctly now.
