### ISSUE TITLE
Support for "Spell Impale"

### ISSUE THREAD

**Issue by Butsuon** [PathOfBuildingCommunity/PathOfBuilding#1922]
Sources: Divergent Blade Blast, Divergent Ethereal Knives, Replica Heartbreaker.

Adjusting the quality for these gems or equipped Replica Heartbreaker does not cause any impale notations to be made.

I couldn't find a issue for it, but I imagine it's in the long lost queue somewhere.

**Comment by Wires77** [comment]
Fixed in 1.4.170.26
