### ISSUE TITLE
Aura Medium cluster jewel - still showing 6% aura effect instead of 3%

### ISSUE THREAD

**Issue by plasmaszap** [PathOfBuildingCommunity/PathOfBuilding#1924]
Title.

Patch 3.13 nerfed the aura cluster jewel to 3% effect per small node but POB is still showing 6%.  For some reason the "First amoung equals" notable from that cluster is properly updated to 8% instead of 10%.

Cheers

**Comment by Nostrademous** [comment]
This will be fixed when we get the 3.13 GGPK and data-mine via scripts. Cluster Jewels are items and require data be pulled from the GGPK database.
