### ISSUE TITLE
Death Wish from Maw of Mischief "Minion Explosion" does not count minion life into the damage

### ISSUE THREAD

**Issue by holmedog** [PathOfBuildingCommunity/PathOfBuilding#1928]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?***
* Death Wish damage calculation does not take Minion Life into consideration for total damage for "Minion Explosion".  Since it could come from multiple minion sources perhaps it should count the one with the highest life or possibly another drop down for each? 
* **What were you trying to do?**
* Calculate Death Wish DPS
* **What steps will reproduce the bug?**
* Equip Maw of Mischief in POB and allocate a minion life node - the Minion Explosion calculation does not change
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* https://pastebin.com/QEw0LfKm
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Nostrademous** [comment]
It doesn't b/c you could have all kinds of minions and they all have different life values and the up to 13 that are chosen are not know. The way to control this is to manual set the value in the upper left Config Tab entry field (forget the exact name and don't have PoB here at work) to the value you get for the minion you want to explode from the Calcs Tab minion life listed there.

**Comment by holmedog** [comment]
This would be better handled by the ability to select for a single minion, but definitely understood.  Thank you!
