### ISSUE TITLE
Effective Health Pool and Maximum Hit Taken is misleading or wrong

### ISSUE THREAD

**Issue by mdlai** [PathOfBuildingCommunity/PathOfBuilding#1930]
* **What happened?**
* Effective Health Pool for Maximum Hit Taken is incorrectly calculated if damage is converted from one type to another.  This also affects Effective Hit Pool
* In the example the calculation for maximum hit taken shows the lowest value, but I think the maximum hit you can take is `6859 / (0.5 * 0.25 + 0.5 * 0.17) = 32661` which is how it is calculated in the damage taken section
* This is may be intended as the maximum hit you could take if the other damage types are fully mitigated, but is misleading since taking a 53136 Lightning Hit would be much more than the total pool
* **What steps will reproduce the bug?**
* Using divine flesh vs not using divine flesh or any taken as mod
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
Version 1.4.170.22
commit 1ae6bd4726d519455c42bd789797a57abc47fa11
* **Screenshots:**
![image](https://user-images.githubusercontent.com/12861784/104614074-e6d72380-5655-11eb-86d4-72fc1ab9887b.png)

**Comment by Regisle** [comment]
Can I have a pastebin link to debug?

**Comment by mdlai** [comment]
https://pastebin.com/RA4zTWeu

**Comment by Regisle** [comment]
Yeah this is likely my fault trying to fix conversion with multiple pool sizes, basically what its doing atm is going, "ok I have this big of a pool and can take this much lightning damage (6642/0.25 = 26568), only half the damage I take is lightning so double that value"

which isnt entirely correct, but it better in many cases (eg hybrid builds with damage taken as chaos, so the chaos total pool would be much smaller), guess I got to go back and improve it again

**Comment by TheArisen** [comment]
I have the same Issue. Here is a build to really showcase that the calculation is just wrong https://pastebin.com/vraCJnRX Its just using divine flesh nothing else.

**Comment by alkaliexce** [comment]
Issue still exists as of v2.13.0, Issue seems to be logic problem with regards to ehp calculation. Does not seem correct to just take the lowest value when calculating maximum hit taken, the damage converted away does not magically disappear.

**Example**:
![image](https://user-images.githubusercontent.com/26573814/140231715-df7ec1f9-cc59-425f-98a9-171c0dcd2778.png)

In this case, 50770 gets reduced to 5077 cold and 5077 chaos damage. Unless the player is completely immune to chaos, he is dead twice over. A 50770/2 = 25385 hit results in 2538.5 cold dmg and 2538.5 chaos dmg taken which also results in a death. So would it not make more sense to use 25385 as the maximum hit the player can take?

**Conclusion**: the calculation should be Maximum hit taken = Sum(Total pool * Conversion % / Taken ).

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5196
