### ISSUE TITLE
{crafted}+1 to Minimum Endurance Charges

### ISSUE THREAD

**Issue by desep** [PathOfBuildingCommunity/PathOfBuilding#1931]
{crafted}+1 to Minimum Endurance Charges don't work with Hierophants Convictions of Power

**Comment by benjaminysmall** [comment]
In order for Minimum Endurance Charges to work, you need to also have Maximum Endurance Charges. Getting a 5th minimum endurance charge by crafting on an amulet will do nothing until you get a 5th Maximum Endurance Charge as well. This is working as intended.

Here's a PoB showing the minimum craft working if you allocated a maximum charge as well: https://pastebin.com/pTYqjmFM

Let me know if you're seeing something differently?

**Comment by Nostrademous** [comment]
@benjaminysmall is correct.
