### ISSUE TITLE
Vulconus "while you have avatar of fire" mods not global

### ISSUE THREAD

**Issue by Bunathema** [PathOfBuildingCommunity/PathOfBuilding#1932]
The modifiers that trigger while Avatar of Fire is active are not applying globally; they are being counted as local modifiers to the dagger itself. Here is the damage change for a blade vortex build with the modifiers as they are written on the dagger (I have added the avatar of fire keystone to the dagger mods to ensure that it is enabled for the build, though I do have it allocated on the tree I swear) 
![image](https://user-images.githubusercontent.com/77454550/104620605-cc507a80-5654-11eb-8dfa-a22c63aa2085.png)

Now, here is the damage change for that same build with the modifiers re-written to be global

![image](https://user-images.githubusercontent.com/77454550/104620917-25201300-5655-11eb-827d-88e1e47405b6.png)

While I know how to parse things, other people might appreciate the fix, especially with how popular battlemage inquisitor will likely be.

**Comment by Wires77** [comment]
Because Avatar of Fire is cyclic on that item, you have to specifically say you have Avatar of Fire in configuration: 
![image](https://user-images.githubusercontent.com/1209372/104766195-c7acc480-572f-11eb-9120-01ec14b7c2d6.png)
