### ISSUE TITLE
Shaper of Winter/Bonechill interaction

### ISSUE THREAD

**Issue by josec87** [PathOfBuildingCommunity/PathOfBuilding#1935]
* **What happened?**
* When allocating "Shaper of Winter", if we set the "Effect of Chill" on the Bonechill config higer than 30%, it should increase the damage, but it doesn't. It's still capped at the default value of 30%, so the new "Shaper of Winter" node isn't fully supported.
* **What steps will reproduce the bug?**
* Allocate "Shaper of Winter" and try to set the "Effect of Chill" on the Bonechill config between 30% and 40%. The damage doesn't go up.
* **Does it reproduce every time?**
* Yes
* **Version:**
* 1.4.170.22
* **Screenshots:**
https://imgur.com/a/HybLSb9

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3271
