### ISSUE TITLE
#+ to maximum number of Summoned Golems is applied automatically

### ISSUE THREAD

**Issue by arthur-st** [PathOfBuildingCommunity/PathOfBuilding#1937]
* **What happened?** Calculator displays buffs as if I have 4 golems out, when I have just one equipped.
* **What steps will reproduce the bug?** Setup an Elementalist with Liege, Elemancer, and Golem Commander, and a Flame Golem.
* **Does it reproduce every time?** Yes.
* **Provide a build code:** https://pastebin.com/LEVPkH8e

This may not be a bug _technically speaking_, but I find such behaviour to be quite opaque.

**Comment by Wires77** [comment]
99% of the time, people want to assume they have the maximum number of golems summoned, either to manually multiply their DPS by that number, or to get the full effect of `increased effect of buffs granted by your golems per summoned golem`  If there's a legitimate use case for not wanting the maximum number of golems (or minions in general) summoned, we could look into changing that, but this isn't going to be a high priority for us.

**Comment by arthur-st** [comment]
I hear you, that’s reasonable to have it work like the majority of users expects to.

For future reference, Elementalist’s rework opens up Liege+Primordial builds where golems are used just for buffs. Players going that route may want to be able to straightforwardly assess how much juice their build loses while some amount of golems is dead - they won’t have survivability seen in classical golemancer builds. How demanded that feature will be, if at all, remains to be seen, however.
