### ISSUE TITLE
Effective health pool does not update properly with Chaos Golem equipped

### ISSUE THREAD

**Issue by arthur-st** [PathOfBuildingCommunity/PathOfBuilding#1938]
* **What happened?** Physical damage EHP not updating.
* **What steps will reproduce the bug?** Create an Elementalist with Liege and Elemancer, equip Chaos Golem, and then take Golem Commander.
* **Does it reproduce every time?** Yes.
* **Provide a build code:** https://pastebin.com/Laa7MQWP

Possible rounding error somewhere?

* **Screenshots:**

![3buffs](https://user-images.githubusercontent.com/29796606/104636862-ace53c00-56ac-11eb-8527-9997e76efc67.png)
![4buffs](https://user-images.githubusercontent.com/29796606/104636865-ad7dd280-56ac-11eb-9c76-36bca719ee2e.png)

**Comment by Regisle** [comment]
the paste has error 404, but I can likely deduce whats happening, EHP was updated to be more accurate and part of that is to round up number of damaging hits to die, so in this case based on the config (which is likely empty) you can take damaging 5 hits before you die, with and without the golem

you can see it has an effect as the maximum hit does go up

**Comment by arthur-st** [comment]
Weird, Pastebin must be thinking PoB generates spam or something.

I'm not sure if I follow your logic. Is effective hit pool supposed to **only** say how much damage you can take based on being repeatedly hit by the same thing for the same amount of damage? I'm curious how much that is then, in particular given that 7981 is not divisible by 5 without a remainder.

Here, an explicit code, just in case. To reproduce, take a look at EHP, then take Golem Commander on tree, then take another look at EHP and compare.
`eNq9W9tX4kgTf579Kzg8B0lfk-zR3QN4YwcdFHXGefGE0EA0JJgElPnrtzqBMSqXIvudbx6cXH51r66u6ujh36-ToDJXceJH4VGVHJjVigq9aOCHo6Pq7c1pza7-_dcfh103HX8bNmd-oN_89ceXw-y6Eqi5CoDOBLrUjUcqvVvxYg_wbOqG6VhF4YX7GMVn0eCoehmFqlrpu-HAT1d3XuAmyaU7UUfV737qjasVN_FUOGi9PT8J1ESFqRv4SVqtTFw_7EXek0rP4mg2BQWqlbmvXi6iAWDbF91v1zcF4X5YFA7afznsBu5Cxb3UTSsJ_DiqNrzUnyuAgvIdf-KDlLkbzIAdq9Y3kIDf3JE6L2DNHdhjdwI_d8N7U6UGv2HkgNj_T2Q3VifDoco80or9tDV2Qw-h9b7Yi1mQ-tPAV3FBLbGJ4vwTc512G8A3EeTKcbe3W5EcGSFiCLk5bgbgRBRfjW6PQj9VaHg38pMo3EtrFLgVTfp-iNR7BW7MRxhwFAyil_A3Um5CXrih24qSNzcLvjFR00I-0I2wa_VcRG7U8Vi9_gZRso1dEbmRXTt8s4GbdAu7IpIIsVm_eZRC1dktuuMP35JfSM63LHXvT41uh95bHTOdbYxvw1glKp4XasQ2Ee9JuiqGgp1iVqYmvFYjFRZi7BzYhG4j6Cjljc-g6l-7KaK46GQr6CKdrY7S6KKjqL2N7xo_bZPwnmQPP2nC935i9gHfht7TSSehikeL3thXwTtTtvqqSFT0mUSJeW8PimRfo-ZuUlxLNje325Pji6Y4G1fqhYLqDxQDhd3l9qfoxtGj3nmD_cga8SSaxajGwvszBxdt3qzOeJH4Hmw1WeNyrQYz712tIpsjseogLqJ51rtl_Qd0aIW93tzo6mYA7R3WeOAcBHtRNNLU9Z6Oo8FI7SVkL4pTPwaPJX5h06sxsRv9DXrFljvF7L56SWEFvKHRAjr-aJyG0PHjpXwgwdsydqPkoxiOgaNFdKMXQI71mJLsh75wX3ePA6exCn8t0PzfwVECTsLBLNaph5bxkQIlZvcklL_bOd0IKg4sJihljNvU2UT8YS7ZBPvU0SPZb-zvPyHX9vdIKeu7_T2IP_f-e9q3rrn_BF43CSDlvGs-CRcW2YZcv9OvhW7f4T-RrG9bLMYxBEi1sA3IYT07BtFX7ck0itPsYcsNvCRj3A6ns7QSZicYyZMfBA_hbNLX427-_1u6F5ETP_Ee-rPhUB9nVEGlODuNOTk9PWndtO9OliQ9lW3FFS8KAneaqMFRNfSDasWHi54W1oPmw0sRaJisl0t3N_a7G3uxD8VnN1QvOoSq2fLfjdMHBggYxMENFNZFN4up0nFPcF5a7vy7sVkZQeDyVY8xK6stGKcrz10gcL_TGoE9CVTDD3QPh_HTBaRv3vxh0NCJxX5_lqIyKqtBCA30-Icwq1hJEJrmLTaC73IG2Y1c9juYfILmFun7YzVUkKWoFZqt-hv3SYXLeraqXYfZ8kgqCRS1MzVJmgvYMk61pz5sIu8AR9U0nkHJGqihOwv086uZG_jpYinz7XknPzjOnibj6KU3m05zTnpJJuDtTid_0wjSJRMt5qg6dINkeYib6ZgdBuc9S3afWZCdCAduX8vQJ9puP9CG59p9INBYze7LIQhYYs-CqO8GdKWghi03ifciCm-WD3uzySQC52QN6lkUqEl1dUpOzWplpCZtHSeVugM3devtFIyqa8vqGWu4yjkU6TMpmmzDq4Jqb1p13TjN7ooWkZUPnnOXtrOKkQXl9zO9ub2xeLP1gxf1XqWnyZVWlUytyme91vokz83c5izx8nzTlzexUhU3j0_GnyyjDTfFDwNadwp6wCYJClrMtg3BqeUYFufcEBZncM-5ZVBmUssQkkticMu2mMEkpcRghBEBQEqlIZljSYNa1AQqmwLEkhYxpMkc26DUoQZhFuGGpCZQSkGkZTDGiAk0UjiaBuDUskALYlvSMTixpTSIyR3T4I40hUFtk1CDU2EzgwgT9HBsC9QjjrANDnhucOkAS9vhwIVwCpQWFSCPMLiG_gysk4SDJGYTra8mNAkIJoyZBuEOkwYXwmHwikogsQSoQhxbA20wGyxyOAXTbUvAc2ESQwhuC3CA5TgGEyAbzDOZ1oWbtuFQUxqCOmCKbUthMEeCcpJIAY5ioKQBrrA0vQ0OlybnJnCk4HZQUZtuaalMag0EkAEDi4B1lg1-JDYFh5g5Qmi9uLRs_dMxqBQULsECob0LNLbDQB9mQ7Q4BTdB5CSoCQHQppsCREpNzkGEQR0C9hDICtBZOhyutf_hiWlCcBwqOISLQwIQsA70gYBSYWo_gbtAvCk4OJjYDGyzIG5UUgvkmCYD73PbhidESxPACrJDmpA0JEsfCDZ4y4KeWnPUiUK1uqAPc3SkQAtICAgrZ_CSQzyB3jHBZskt06lWUlgBhe9ohC0_kemMZ8tadTKAfmBwqZO_nj-5ve5kF1_GaTpN_qzXX15eDqZuOo6G6tUP1IEXTepTYAMLq5atz5oWVG_Av2bjotVo_vJIwxucNn_Ovw-73mM_aT7-IPLWqX2tqfHz1av78LQYxtbo0bz82VlcD2V3NBZJq_Zt2G-__nPrfvv6tRs3X7-TZBp4kvfcuzvPTSYdr9aeXyUwTN5Y3G-9PjSGQQ9EjmrxLWnL7532z_vnRe_llvbm3-LZcbg4vmmx-_nwiT0e92ut-K7dfri_TU4mr5PZ8QvxHHl1PxT3tZd7YtfuOvFT6_EhurP_SSbXP83z8yl9fozl-WBEL3_K1jGtXT63Z9HT8zzuMasVto7700fz_rrzo929fKRXdzft5kV63vg5SX40h09ngp7708bd1VVw1zl7HE9C35v7J__cxrOB2ex0I_J0d36vUscE9W5__WjaryfdaNT8Ohz-Os0CUV9F4jD_RpnkYVneZQVLR5JIyC7Yh9N8S1gOI2twBIoFAichVzkGx6EAIXBQ9RwMP25Ly8Hwg2qBgDlQdRAwWOooaxnnOGth1WP4Ue5grNB1CyOWEYlTT8JGgMAJAZUEEzTHtDE42CItDM6CoocRK6FwonBgB8rNkmHCwU1umqhwmBixhErCUGYwBxVdvU9jogudAiYLoBFAyXUsx8KoZ3MLI5bC1k5RyUwciapozBQoHLVtVEWzOKq2QNPnoORKibGDWJTgKiS6Blm4HYGj5HLIZ0y6CAJFEmOvKRgmD6DjZai0BwUtVFGTNm7HsiTKDujwUNVFd_wYHCcSlVcwsWBgMEII1FbpoIqknj0w7KDhXpMtMMK9dTtwA9NaNtjpcU5fXEapyt7ph6ubbNi789VLJVFu7I17aawH9l9RNLnXnY9NDgRMA0S7Vx8GnCs3vXCnqxlU45YnCdbyHCF102N_OFRxdgZSBP44qtaoaR44EFbLMmHpWvmhRzaDLydOfd1T-eA8S1RPeVE4-K7cKczX-rE-D8gPbHPgRlB2vrI6WOgF0epwN4dVSO_FnVYa_UWSuEFl6eE1wVxH-pGM4si2o5pRlCYlFVpnyw6lmipI9yQ5hRHoqcJQKtF1KrFy7sU5gf6PyHg5JWU5abK8N8vk044InKtgotJ9Ba3JJFlGzo70Owuiuf7muj9jVn4VkTLyeLlcIOUyj-8OD8ax-7Jdl14lDUfVHVFCnxI1kO0SM1hU8g8Re4ZvvZdL5ZcoQ4RakphAlLJTlHYrLRF3WW4lsXLpy_bPMl6-7JfIaVLa-QyTEBwDKqH2f2h-kJEsHwVZIivLh-E_pAu2JGta5KrBQ0t47toPR7hOYO9CsdG9JcsFPp5lzGEIP5HyYeClvSXKWINZL-WTfIdKjcksWLO3HdaXM2Q2JmdDaPbbQ1E49EeffilIj5i-_pCf_eIGeL9a6UdRoNxwOeMuv98vqQ_rH_9k618NJRc5`

**Comment by ppoelzl** [comment]
We fixed this bug by rounding down the average number of hit you can take. This makes it clear that your effective health pool only updates when you're able to withstand more hits.
