### ISSUE TITLE
Configuration to set travel distance for Projectile Attack skills doesn't appear when using a melee weapon

### ISSUE THREAD

**Issue by Inkaflare** [PathOfBuildingCommunity/PathOfBuilding#1939]
* **What happened?**
The configuration option to set the projectile travel distance does not appear in the configuration tab when using a melee weapon combined with a melee skill that has a projectile component. This affects Lightning Strike, Lancing Steel, Frost Blades and the likes.
This is important for Point Blank/Far Shot damage scaling for these skills. You can make the extra damage apply to these skills regardless by equipping a bow, setting the projectile travel distance and switching back to the melee weapon - the now hidden Projectile distance configuration will work properly in the background and modify the damage of the projectile melee skill accordingly despite being hidden.
* **What were you trying to do?**
Scale my Lightning Strike with the reworked Far Shot on Deadeye. It's possible thanks to the workaround of temporarily equipping a bow, but it's inconvenient.
* **What steps will reproduce the bug?**
Make a new build. Equip any melee weapon. Equip a melee skill with a projectile component. The config option does not appear unless you equip a bow. 
* **Does it reproduce every time?**
I retried 3 times with a fresh build and it did every time.
* **Provide a build code:**
https://pastebin.com/wyAgAHUP

**Comment by deathbeam** [comment]
This is no longer the case and the option appears correctly
