### ISSUE TITLE
Updates for Alternate Quality Skill Gems (Vitality, Precition, Discipline, Determination)

### ISSUE THREAD

**Issue by jesuslnv** [PathOfBuildingCommunity/PathOfBuilding#1940]
**Is your feature request related to a problem?**
- Yes, is an update made from GGG to alternate Quality Skill Gems.

**Describe the solution you'd like**
Here is a list of images with the Actual and the new changes needed in the required skill gems (OLD/NEW):
- Vitality (Divergent)
![image](https://user-images.githubusercontent.com/18370181/104638879-bce12980-5674-11eb-8227-f55024c65fb3.png)
![image](https://user-images.githubusercontent.com/18370181/104638890-c074b080-5674-11eb-827e-bc0b38468f9b.png)

- Precision (Divergent)
![image](https://user-images.githubusercontent.com/18370181/104638948-d4201700-5674-11eb-84ea-bcc727084ea9.png)
![image](https://user-images.githubusercontent.com/18370181/104638957-d6827100-5674-11eb-8ec8-decdf0637344.png)

- Discipline (Anomalous and Divergent)
![image](https://user-images.githubusercontent.com/18370181/104638990-e00bd900-5674-11eb-8bd9-3c4371d17f3a.png)
![image](https://user-images.githubusercontent.com/18370181/104639600-9b347200-5675-11eb-9dee-280940dadf04.png)
![image](https://user-images.githubusercontent.com/18370181/104638995-e26e3300-5674-11eb-9762-dcf2b9da627e.png)

- Determination (Anomalous and Divergent)
![image](https://user-images.githubusercontent.com/18370181/104639699-b4d5b980-5675-11eb-844f-dd6b9cd570ef.png)
![image](https://user-images.githubusercontent.com/18370181/104639001-e69a5080-5674-11eb-8c20-f5accc27eff6.png)
![image](https://user-images.githubusercontent.com/18370181/104639006-e8641400-5674-11eb-865a-7945e0faefc4.png)

All this info is related to updates coming this 15/01/2021 for Path of Exile Echoes of the Atlas.

**Comment by Wires77** [comment]
All of this information will be updated automatically once we receive the GGPK file via torrent or at the same time as everyone else.
