### ISSUE TITLE
Replica Emberwake, Ruby Ring + Flameblast Ignite

### ISSUE THREAD

**Issue by DeadWiing** [PathOfBuildingCommunity/PathOfBuilding#1948]
* **What happened?**
* -**_90% reduced ignite Duration on Enemies_** + **_Ignites you inflict deal Damage (35-45%) faster_**  x2 causes ignites to have -1.78s duration. (from the _Calcs_ tab)
* **What were you trying to do?**
* -Make an awful build using the buffed Flameblast( Throwback to Demonic Pizza Ignites)
* **What steps will reproduce the bug?**
* -Equipping **TWO** Replica Emberwake's (Any roll) & Flameblast(Any stage) causes the problem
*   -Allocating skill points or equipping items changes how negative it goes
* **Does it reproduce every time?**
* -Yes. Tried base classes 
* **Provide a build code:**
https://pastebin.com/6gwTWHQN

TY for the great work!

**Comment by benjaminysmall** [comment]
The correct behavior here would be... to make the ignite duration 0, and have the skill do no damage?

**Comment by DeadWiing** [comment]
It appears to lower it to a very minimal duration. Path lists it as -127% ignite duration.
I would think that it should take ignite duration * 180% less duration then make the remaining time faster
(Ignite Duration * Less Duration) * Faster Ignite for a formula.

**Comment by QuickStick123** [comment]
Fixed sometime likely during 3.13 when ignite less than 0.3s don't exist. 
![image](https://user-images.githubusercontent.com/31533893/221747552-ff62e1df-036b-42b6-bec3-6fdac9c99629.png)
