### ISSUE TITLE
Lightning Strike Projectiles calc doesn't use Multistrike attack speed bonus

### ISSUE THREAD

**Issue by PseudoError** [PathOfBuildingCommunity/PathOfBuilding#1949]
* **What happened?**
Noticed my Lightning Strike melee and projectile APS were wildly different. Turns out, since the projectiles have the projectile tag, they won't use melee attack speed bonuses, even though they are an effect created by a melee attack and thus _only_ melee attack speed bonuses help, not ranged attack speed bonuses.
* **What were you trying to do?**
Was trying to figure out why my APS seemed so low for the build.
* **What steps will reproduce the bug?**
Have Lightning Strike selected as active skill and go to the Calcs screen. Change Skill Part between "Melee hit" and "Projectiles" and see how the "MH/OH More Att. Speed" lines change.
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/GNHGxx3b

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
