### ISSUE TITLE
Reproducible Error pop-up when searching for Skill Gems and finding no results

### ISSUE THREAD

**Issue by Rosemary102** [PathOfBuildingCommunity/PathOfBuilding#1950]
* **What happened?**
* Mousing over any skill gems, active or support, in the skill gem addition dropdown causes an error pop up to appear that interrupts all other actions.
* **What were you trying to do?**
* Attempting to search for a gem by typing it into the search box above the dropdown.
* **What steps will reproduce the bug?**
* Place mouse cursor over where the dropdown of potential skill gems appears. Type any random characters into the search field, so that there are no results ("No matches") for your query. Remove characters from your query (ie. by using backspace) until there are matches to the search query. Mousing over any suggested skill gems will now cause the error pop-up to appear. The error pop-up will instantly reappear whenever you mouse over the suggested skill gems again. Note: removing all characters from the search bar stops this bug from occurring until it is triggered again.
* **Does it reproduce every time?**
* Yes. 100% reproduction from a limited few minutes of testing.
* **Provide a build code:**
1.4.170.22
* **Screenshots:**
![bugpob](https://user-images.githubusercontent.com/43137266/104682575-20d52200-5749-11eb-8633-a75fcafb71b5.png)

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.23.
