### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by Riizade** [PathOfBuildingCommunity/PathOfBuilding#1957]
## **Is your feature request related to a problem? Please describe.**
There's currently ~no real way to interact with Path of Building in an automated way. It'd be great if the application exposed a command line interface so that enterprising community developers can build tools on top of Path of Building's calculation engine.

## **Describe the solution you'd like**
Take https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/HeadlessWrapper.lua and have it instead parse CLI arguments to determine which actions to perform. 

I'd be happy with a simple one-time-invocation interface where you can simply load a file, perform a single operation, and get some specific output, But something like an interactive CLI where you can load a file and interact with POB entirely via the command line would be kool too.

## **Describe alternatives you've considered**
Considered automating with point-and-click macro tools. Extremely time-consuming and error prone.

## **Additional context**
Trivial ideas that could be built on top of the CLI wrapper:
- web-based PoB (although https://pob.party/ already exists)
- Item search comparison tool (a web-interface wrapper for poe.trade or the official trade site where you can load your character's build XML, and alongside the search results it displays the resulting stat changes if you were to equip the item in various slots)
- build collection/sharing tools similar to poe.ninja's builds section (https://poe.ninja/challenge/builds)

**Comment by ppoelzl** [comment]
The recommended way to interact with Path of Building is through `HeadlessWrapper.lua`, which will be stable starting with release 2.0.0. All of these tools you came up with have already been built this way.
Many programming languages have libraries for two-way Lua bindings available. Communicating across stdout or websockets is also an option.

Just out of curiosity, what are you trying to do with PoB?

**Comment by ppoelzl** [comment]
Closed due to inactivity.
