### ISSUE TITLE
Adding a Rustic Sash belt with Global Physical Damage doesn't affect SRS hit

### ISSUE THREAD

**Issue by Solidstate2021** [PathOfBuildingCommunity/PathOfBuilding#1958]
* Thank you for reporting an issue.
* Before reporting a bug, **please make sure that you are running the latest version.**
* You can get the latest version number from `CHANGELOG.md`

There is no such file, to make sure I re-installed with the exe installer and there is no CHANGELOG.md only "changelog.txt"  , please see below:

![image](https://user-images.githubusercontent.com/77499258/104745163-73690b00-5756-11eb-9475-6c6b22a53a02.png)

According to this file I am using "VERSION[1.4.170.22][2021/01/14]"

* **What happened?**
* * **What were you trying to do?**
* **What steps will reproduce the bug?**

As I wrote in the title, I added a Rustic Sash belt with "18% increased Global Physical Damage" to my level 9 witch using SRS gem level 2. The damage tooltip for the SRS "default attack" remained exactly the same. According to wiki SRS do physical damage (50% of which is converted to fire) so why didn't the number increase?

* **Does it reproduce every time?**

yes

* **Provide a build code:**

https://pastebin.com/c0V8ug33

* **Screenshots:**

NA.

**Comment by Epsynus** [comment]
In general if it doesn't say "to minions" somewhere, then it will not affect your minion.

In the instance of a Rustic Sash it gives global physical damage to you, but not to your minion, which is why it is not showing an increase.
