### ISSUE TITLE
Stats like STR/DEX/INT as suffix on weapons

### ISSUE THREAD

**Issue by Afghani84** [PathOfBuildingCommunity/PathOfBuilding#1969]
Hi there,

just started Ritual league with the updated version and had a dagger drop that has DEX as a suffix.
I cannot chose it in PoB though, so maybe it was recently changed!? Just wanted to let you guys know.

Thanks for the great work!
Afghani

**Comment by Wires77** [comment]
Are you referring to a rare dagger?  I can craft a rare dagger with dexterity as a suffix just fine: 
![image](https://user-images.githubusercontent.com/1209372/104795140-bb495b80-5771-11eb-8074-45b58064d553.png)

Please post the item that you are trying to craft and we can reopen this issue if it's a problem
