### ISSUE TITLE
Divergent Endurance Charge on Melee Stun not supported

### ISSUE THREAD

**Issue by lfigueirabr** [PathOfBuildingCommunity/PathOfBuilding#1976]
* **What happened?**
* When choosing Divergent Endurance Charge on Melee Stun the damage won't update.
* **What were you trying to do?**
* Tried to put this gem as a support of Tectonic Slam and change to Divergent quality. The damage won't update.
* **What steps will reproduce the bug?**
* Just try to support Tectonic Slam with this gem at 20% quality and the damage won't change, compared to the Standard quality version.
* **Does it reproduce every time?**
* Yes.

This gem, as the alternate quality says, should give increased damage when losing an endurance charge on the past 8 seconds. Tectonic Slam is a skill that consumes a charge every 3 attacks and should make this alternate support work, but to not attach this gem to a skill in particular, maybe it's a case to put an item on the configuration page asking "Have you lost an endurance charge recently?".

**Comment by ALT-F-X** [comment]
In Configuration>When In Combat>Do you use Endurance Charges: select the checkbox and the alternate quality works as intended. This is true for any ability that cares about charges.

**Comment by lfigueirabr** [comment]
Did you try to reproduce with the steps above? Here, if I use the Anomalous Endurance Charge on Melee Stun, the damage is correctly calculated, but if I change to Divergent, it's "discarded" (it seems the damage of the divergent quality it not being considered).

**Comment by ALT-F-X** [comment]
Oh I apologize, I completely misread this and was looking at Anomalous. My fault.

**Comment by lfigueirabr** [comment]
Solved in 1.4.170.27
