### ISSUE TITLE
Skills tab does not overflow horizontally

### ISSUE THREAD

**Issue by nmussy** [PathOfBuildingCommunity/PathOfBuilding#1977]
* **What happened?** When reducing PoB to its minimal 1280 wide size, the "Skills" tab content is slightly cutoff. Completely usable afaik, but there might be additional menus that appear is certain cases?
* **What were you trying to do?** Fit PoB on a portrait screen
* **What steps will reproduce the bug?** Reduce the PoB width to a minimum, open "Skills"
* **Does it reproduce every time?** Yes
* **Provide a build code:** 1.4.170.25
* **Screenshots:**
![image](https://user-images.githubusercontent.com/2505696/104821764-66bfe200-583e-11eb-8fef-cc1953002029.png)

**Comment by Wires77** [comment]
Added a scrollbar to fix this in 2.0.0
