### ISSUE TITLE
Siegebreaker belt not calculating caustic ground

### ISSUE THREAD

**Issue by MonkiGW2** [PathOfBuildingCommunity/PathOfBuilding#198]
Siegebreaker allows for 20% of minion life to count as damage via caustic cloud:

"Your Minions spread Caustic Ground on Death, dealing 20% of their maximum Life as Chaos Damage per second"

This used to exist in POB when it was part of the summoner ascendency.

**Comment by LocalIdentity** [comment]
Added in 1.4.162.1
