### ISSUE TITLE
Rupture modifying bleed duration incorrectly

### ISSUE THREAD

**Issue by PastaAdventures** [PathOfBuildingCommunity/PathOfBuilding#1980]
Rupture is a debuff that causes bleeds to expire more quickly, basically the opposite of temporal chains. It causes a base bleed, which has a duration of 5 seconds, to only last 2.86 seconds because every second, it removes 1.75 seconds from the duration "counter" of the bleed

Currently its calculating that rupture is applying a 75% less duration at 3 stacks which is incorrect. It should be ~57% less duration.

**Comment by ppoelzl** [comment]
Duplicate of #1917
