### ISSUE TITLE
Replacing node modifiers does not persist

### ISSUE THREAD

**Issue by RedDeathGitHub** [PathOfBuildingCommunity/PathOfBuilding#1981]
* **What happened?**
When I right-click a node - to "Replace Modifier of Node" with my timeless jewel actual effect, it works only for a moment.
It seems to be reverted semi randomly during the session, and also does not save.
* **What were you trying to do?**
Apply correct timeless jewel changes to my tree and save that.
* **What steps will reproduce the bug?**
Right click node, select modifier, save, go back, load build - modifier is not there.
* **Does it reproduce every time?**
It seems so, though it also seems to get lost (randomly?) during the session.
* **Provide a build code:**
Version 1.4.170.25

**Comment by Wires77** [comment]
Can you send me a pastebin link to your PoB build?  What timeless jewel are you using and what mods are you trying to add to a node?

**Comment by RedDeathGitHub** [comment]
OK, it's a guide I found and I was just messing with it.
Link: https://pastebin.com/A14Tv0hw

Steps:
I right clik Sanctum of Thought - select Slum Lord - save - exit - load
And selection is not there anymore.
If I select any new node it also disappears.

**Comment by Wires77** [comment]
I've submitted a fix for the issue in #1981.  In the meantime, if you convert the tree to 3.13, the nodes will work for you.
![image](https://user-images.githubusercontent.com/1209372/104853005-aaa8fa80-58c3-11eb-9b05-cce7ab8069f0.png)

Thanks for submitting this bug!

**Comment by RedDeathGitHub** [comment]
Damn, I'm blind :).
Thanks for the help!
