### ISSUE TITLE
Max Doom calculation

### ISSUE THREAD

**Issue by ErratQQ** [PathOfBuildingCommunity/PathOfBuilding#1983]
Hello!

* **Max Doom calculation for hexes is capped at 50, should be at least 55**
* **I was trying to calculate DPS with 55 Doom**

Calculation:
Normal Doom is capped at 30, +10 from Skittering Runes = 40 + 5 from Alternate Quality elemental curse (at 20 quality) = 45 + 6 from Enhance Support lvl4 = 51 + 4 from passive Malicious Intent = 55.
In PoB it's capped at 50, changing it to 55 does not change Total Damage, Combined Total Damage, etc. 

Cheers!

**Comment by Wires77** [comment]
Malicious Intent gives you "+4 doom" not "+4 to maximum doom", to enable builds that want to immediately pop doomblast or hexblast instead of waiting for doom generation.

PoB is working correctly here.
