### ISSUE TITLE
Crackling Lance not affected by Concentrated Effect

### ISSUE THREAD

**Issue by Meatwookie** [PathOfBuildingCommunity/PathOfBuilding#1985]
Hey,

Concentrated Effect is affecting Crackling Lance ingame but in PoB Concentrated Effect isnt able to be linked to Crackling Lance.

**Comment by pundm** [comment]
Can you please provide your PoB where this is show-cased?
I downloaded a random pob from poe.ninja and the damage calculation seems to work fine:

![image](https://user-images.githubusercontent.com/54453318/108986922-fbfe9380-7692-11eb-81fd-ce49aee9e0d2.png)

If this is about the size of the beam, then have a look here: https://pathofexile.gamepedia.com/Crackling_Lance

_Concentrated Effect Support: Neither the beam itself nor the branches have an area to modify, so their range is not reduced. However, their damage is properly multiplied._

**Comment by Meatwookie** [comment]
it looks like its fixed by now
