### ISSUE TITLE
Brands activation frequency not influenced by more cast speed

### ISSUE THREAD

**Issue by UpsideDownRide** [PathOfBuildingCommunity/PathOfBuilding#1986]
This is very similar to issue #1936 - adding more cast speed does not influence the activation frequency of brands at all. 

This is now relevant due to inquisitor rework - fanaticism grants more cast speed among other stats.

**Comment by Regisle** [comment]
This one is incorrect as they all specifically state "increases and reductions to cast speed", where orb of storms says "Modifiers to cast speed will increase how frequently it does this", I have not tested this yet, but its my understanding that more cast speed does not effect brands activation frequency, only how long it takes to initially "summon" (cast) the brand

**Comment by forrejam** [comment]
> more cast speed does not effect brands activation frequency

Cast speed does affect activation frequency and is one of the best ways to scale brand damage

**Comment by Quotae** [comment]
There is a difference between "Increased Cast Speed" and "More Cast Speed". One is additive, one is multiplicative. Brands say "Increases and Reductions to Cast Speed also apply to this Skill's Activation frequency". It specifies that only increases and reductions apply, not more or less modifiers like the more cast speed from Fanaticism.
