### ISSUE TITLE
Config missing Projectile travel distance option

### ISSUE THREAD

**Issue by esge** [PathOfBuildingCommunity/PathOfBuilding#1988]
If i create new build and allocate stuff manualy then everything is okay.
if i import Items and skills from an existing char, the option vanishes from config.
looks like it goes away during items and skills import, its fine after tree import

doesnt break on every import
account name Esge
it breaks for Esge_EleArcher who has point blank
even for Esge_ThornyBoi who doesnt have point blank, but if i import and select point blank, config doesnt appear

doesnt break for Esge_harBarrage who has point blank
doesnt break for Esge_boom who doesnt have point blank

all except the first char listed are in standard

v1.4.170.25

**Comment by esge** [comment]
it went away, maybe it was a problem with ggg's side being overloaded early in league

**Comment by Tasselli01** [comment]
> If i create new build and allocate stuff manualy then everything is okay.
> if i import Items and skills from an existing char, the option vanishes from config.
> looks like it goes away during items and skills import, its fine after tree import
> 
> doesnt break on every import
> account name Esge
> it breaks for Esge_EleArcher who has point blank
> even for Esge_ThornyBoi who doesnt have point blank, but if i import and select point blank, config doesnt appear
> 
> doesnt break for Esge_harBarrage who has point blank
> doesnt break for Esge_boom who doesnt have point blank
> 
> all except the first char listed are in standard
> 
> v1.4.170.25

The same problem is happening to me even after the update (v1.4.170.26)
It is just as you descibred, the problem happens when I import new items to update my build
I am using Point Blank and Far shot, maybe that is part of the problem, I dont know.
Character name is Tasselli_Barrage_Ritual
Account is Tass2gag

**Comment by ppoelzl** [comment]
Superseded by #1999
