### ISSUE TITLE
Jack, The Axe new version support

### ISSUE THREAD

**Issue by Quarr3l** [PathOfBuildingCommunity/PathOfBuilding#1989]
Please add support for the new Jack, The Axe. Including the new Thirst for Blood skill and "+(25-35)% to Damage over Time Multiplier for Bleeding from Hits with this Weapon"

**Comment by Nostrademous** [comment]
#1993 provides extraction of the "Thirst for Blood" ability from GGPK. Separate PR should be created to implement the modifiers it grants.

**Comment by livejamie** [comment]
There's also #2122

**Comment by Wires77** [comment]
This is partially fixed in v1.4.170.26.  The last line is still unsupported, but you can edit it to remove `from Hits` and it will work just fine.  Tracking that issue in #2149
