### ISSUE TITLE
I can't import any build

### ISSUE THREAD

**Issue by Lolieru** [PathOfBuildingCommunity/PathOfBuilding#1992]
Hi, I am new to POE and  I just installed PoB 1.4.170 but I can't import any build, I think  this is already the community fork but I might be wrong, can someone help me? I get the "Unknown Passive  Tree  Version" error

**Comment by Wires77** [comment]
Does your version say "PoB Community Fork" in the lower left?  If not, you'll need to install it from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases
