### ISSUE TITLE
Hierophant: Arcane surge doesn´t get granted by Arcane Blesssing 

### ISSUE THREAD

**Issue by TheDrunkenguy** [PathOfBuildingCommunity/PathOfBuilding#1996]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by pundm** [comment]
Duplicate #2302 
I will close this one, because the other one has slightly more information in it.
