### ISSUE TITLE
Issue with a crash at "render init"

### ISSUE THREAD

**Issue by ajingram726** [PathOfBuildingCommunity/PathOfBuilding#1998]
I am not getting any errors, the application freezes and then crashes. I rolled back my GPU driver to an old version, from late October 2020 to resolve.

I am using a 2070 Super QMax(notebook edition), seems the newer drivers are having a compatibility issue with this as the last 3 sets of drivers from Nvidia caused the same issue.

**Comment by ppoelzl** [comment]
Duplicate of #1843
