### ISSUE TITLE
Projectile Travel Distance(Point Blank) Bug Report 

### ISSUE THREAD

**Issue by RitualMiner** [PathOfBuildingCommunity/PathOfBuilding#1999]
- Point blank (projectile travel distance) does not work when I import my miner character.
- Already point blank is selected from the passive tree. 
- The projectile travel distance setting does not appear in the configuration settings, you can check it. 
- Now you can delete wrath and skitterbots setup,  will see projectile travel distance is coming back.
- The same problem happens when i import characters from my account.
- This issue It happens not only in kinetic bolt mine but also in other skills. (Power Siphon mine,Kinetic Bolt mine,Barrage mine, Elemental Hit mine)

[Pob Code.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/5839485/Pob.Code.txt)

I recorded the video:
https://youtu.be/s8xJTVKwI_k

**Comment by Wires77** [comment]
Try changing the skill in the Calcs tab.  Unfortunately your pastebin gives a 404 error, but there is currently an issue where the config page bases its selections off of the skill selected in the calcs tab instead of the sidebar.

**Comment by RitualMiner** [comment]
> Try changing the skill in the Calcs tab. Unfortunately your pastebin gives a 404 error, but there is currently an issue where the config page bases its selections off of the skill selected in the calcs tab instead of the sidebar.

https://pastebin.com/WLKizv2p

**Comment by RitualMiner** [comment]
> Try changing the skill in the Calcs tab. Unfortunately your pastebin gives a 404 error, but there is currently an issue where the config page bases its selections off of the skill selected in the calcs tab instead of the sidebar.

eNq9W21z4kYS_rz8iimqcpXUYawZSYPw2Unh13XF9hLw7mY_bQ3SYBQLiZUGsySV_349I4GFzUuj-G63ygap3-fpnu6RfPzL93FEnmSahUl8UqdNq05k7CdBGD-c1D_eXx549V9-rh13hRp9GJ5Ow0jf-bn27th8JpF8ktFJvc3rRIn0QapPC1H2VxA1EbEaySS-FX8k6VUSnNTvkljWyUDEQagW3_xIZNmdGMuTen8kgmRWJyLzZRyclW6IQaLkNK2TsQjjfuI_SnWVJtPJSZ3VyVMoZ7dJAHTXt90PvfuS5jAuawbL3x13IzGXaV8JRTL4cVLvQADEgzwXY_gJ0kQ0BVHMZrzpcO5alk2ZWz9cz9yfSBksmWjT8f6flOCfvBFzWJT7cPxsu9VkttXi7cXPTezdVF4Mh9JX4ZM8S0N1NhKx_yyGus3WRser0N9OIxVOolCmJe82crx_rcCyNhHfJ0pE593-ktZ2HLtJW5bDLIdvXr-cL1HPsdtE-TlUo9MIVqasBYkSzXv9EIdKVmTuJmGWxBWYF_6VWTe6eJaMB4CoKh4uWDtPD_uy3opYnCXZ8xJsxGtflYDjbKLqyW9lQnujuHP5_Vkct7fIK1Pyjdl4HauS71vErRBSttm-p0RBOd29cDfhsJQlzG1vKS3-kaa-jn2c2I9xKjOZPpUr0hYFqyxdmUIlV5gE1ow9-SDjsprmVj03UvqjK9gQQA0Ui93-aKQ9ryNjW6OkiVFR0oTrokQ5juNVkLwmd9oubXHP8bzWNiEvAmZtjpem3jteF7FMH-b9USijYDe1iVqZBRW9MsOqOyiW_X16Elk5pxzX2e5QTo9DgoT9ARgC-WLjekOObpr8oXfsaD-2TjpOpmm5NG_1OidHOd0dzbPQh03G9E89GUz9laK1UdGy9bhNnuQYMsD0PdDIlZoDa-OucRpBF_jCe3sbNqNoHcvmgCkl_MfzJHhAx9go2YvjMkwhYllY2vwONuPxmfoDtKxnYoLZ0XVWYRU8U6MV3IQPIxVDA4rX8oIF78tIJNlLNRxDjlbRTWZAOdKzTLYf9a34vrt_uUxl_OccLX-FHKXgIg6mqYYeWsdLjtdqjg_NsKc_XY8nSaoIzGWq4_vJNFbvRTaCAdBqi6Ez4NbAGwQBk5JK7tl0OBgM3RYVbU4FG3JoiQxrT4poDNE7y79qxcJXUL6NLOY69sByLSnsIfNbQ6_VdvzAltSmAYdPgxZ1A_iZ23YmIj8znl3Hk6kisRkXx2Hmfx1Mh0M9FdbB09QMtBeXlxdn99efLopglFmyxzCKvsbT8UAPJ_lvKEAFZV-amkb8JIrEJJMwUA5FlIHsED72NW8fKrmvUPSwTxXDJob6s0j9NIS1xBDrSQZlshkxMZR6bkMRAjhEJPEBu59PpAZiho1ZUVQx1GZOQ1HmgxXOQTPA4ZZB-mKOolz2Lyjqi0h2wkjvlbio3UIi5Nssjh42vTQcTBUSbWbsQNmhG2-Ug-WOE2Vx3tegZBedH4a22GZwWIOuAr0a53IoAcXIbDZV4l48yrgoxYt6d2xSKCMZ1OMrOc5O5zCzX-qovZjiVwhO6iqdguxADsU00td_m4ooVPOTehxG5es3-cmeuZqNkll_OpnkknTaZhD3m5v8TidShRCtZmF-7py20ZzYdUyfZ74bD3RlheI_0Dr0kaMYRNr13LosSvTpjwScq_pLds2phb87BnUF51WUDETElqErjiUZ6HiQ42sdealEIJQ4vFZg5KG29NCIg0-fU6FGoFV_1bTF97JoujDtW-6pJgO_ZRoLJenyMqi0XnmjtxfdUi8EHyKtd7Ybv1yPThCEGkIi-r1b8qIgWL27y6fzfP1LDm3z5yKOdCdXYHOrT8as2zAGS16CoFgrC7VW_el4bEQoCP4ggapW8vjV1ZJCo2t_97euZ24M2aS3bJFurIuMz3355_nxWYoJaKeVMmRhpjzTTZw-ud03a34FZhX6p4mO13INVq5WCLe9JdyFbFJSuQy0WQkZdKFDUCIbo5NsF-yWWdaT40RJHbHXOVa-h64aDIuyU90j-yNYY2JUvLlrUCJksJzJFk9B1hSSNVRvnFFGCVlqIStd8t6Jc9CJUimCOZkkYazIIBLxIwlhzzSdOihSI0kmIstAAlGplM1Xpq1JrcN9LLjXGpYHNqBEwNqQAFoL3cqCJUppP4NEZiRO1FvrB8xoH_0kHoYPMOaZVqNQmjXIPJkSX0DzMZI-REY1yZsH4C6ZLdUEEHclyUxvg0TEgcbYonJqq6aTt1Y_00SZ3LoGfjLWSzAQ_uPbr383kiKTywAT8QAcaDUF5E2_dw_4JCKnMblCix4LvpSfl-qsgyoaw-ALpjDPoqxhM9d1G8ylvNVwmd1qcJvabsOhlkcbFH7ZDbfNLd6gzAFyx_Vsr-E4MMI3bM68VsO2eKsNlJw2GGOcN1wLrrpwgTWox7Usi4Io3nasBrM8C1Q4nqNFsRYD4cxlDY_DTYfRllc32VZ6Vkzt4jGwtp4Xu9cFdC4yuNOOFDXvY-_GfHg3UmqSHR0ezmaz5gTQlAzld1jbJqzlYZHQB6aAHWhFhx34d9r5ct65otlwrsL77z3anhxAZ-3_zu--zIY3tx_-GLRtOvtMPz0l97b3eHXO1dnN5eX7rx-_zdiHwLr2zx5nDycnxpDDhSXH-aPoLDer-GaCrz2hnFFwFtwwZbg4g1lDR6lrIeg49WwHQ6dXEEHHWLuNked4sPwYeTalCDIACSYqNuc4b6ltuRjraNvDyGNOG-OFbbdcTJA5sy2c1haGznVpG0VHwV3MYrTaLYx5vMVQQW63KMNAioMfqChDrcK4C4UL44dNLRSSPaflotyw26hMA7BwjBtt18PopU4bpdehXgujl9oUhT6btTjKX07bHJW7zMOg1GnDpoKKMy7HbaDD4MBxYE_DxK_FUHCGPdVDpQdlqDhz2L3bKDrOOSo9OHLnaDmoGu44KHnUcm1UXNrcw-1YLY7aeRnlFEXHKSrfLMfC4LQF7RZm2ayW7aK2yjaqSvI2xailnmOvQQu0o8_dDnyBztM0qbo11R_uYAo293YOXsM0Gb-evkht33mJiMlEipTsPefU9hxMGoRgZgnwsTxO1Db0_zpoi2CZxv5TKGcgW6T-qK9SfeTzZ5KMv8AAwfS8rI9Z30uhbsVkOeVrguKQ1i6OaJVQ5-FwKFNzwLyYLTTh7yDJLh6lH5tDgGKU0J_7UpmZZZrJvoQQBvnJkrlcOszVpORJpKHQB0Z2fkBdnDT14LKaH5GPd9e_fbyodcPMFypJ_wVysv9k5FP4EEa1-ySNRZCQzxDh2qdc0BHpppKwpt20Xl7i5Utn0xS8UrX-AkHLO_aq3OIo-ogwq1ag9YicHsD_molWT347ItytXY8nUeiH-i6r_VW4dUT__isV8YM8spru3z9SfkDbP_0A6PJTvYwBMQ_4i1OJZy4YsFb4bPfA3sJ3l5DFKxNLUWWt1gH1VrjzNxGIeWRXJv33j7ZjHUDB-YmohHR8H5Dvz0lPaNivyGQWLP-KTP1Uz1gAeAsfJcmfrZWZcq0Z4B6SQo0A2sWJ4wgwT8BMsJO6K0IvIvMah3gdInuzuK6MJeQR5J_7Q0lC_gBGG5WZ2nObBD1tGzEW6ldc3QUEi-q0kYLtpHB2Urg7KfhOisWbXOYYbk1OsYW563LqZu4nWRgIWeuJ2SgMJLnXbx-Q_FHZavJANuGSh60XtjaJegfwv5RElJaTiJbS4e8VjAKeWY7Qsfgejqdjop8aruKYAkApL3BsHui9wLmG-WsZX4CQjEC_ruJ5sYHdRhLzYtTLVDnQWM1hrgWZp3a1ThBkhLmWvmJbFtHn9AV49SVzOi4BnAa7_3sc2lgcljDUj5LFOwzPjwQWW_fyuOoVUanbWrygVWwGWzaCcs1fp7g_ExPSGcyzTFeWvKlY07-sY33JxnBsr1xdoTpN9A5ezaB1vuww6lRGak-Wy0hkj8RGmcTWmWRXCy8uCOyN2JxqRvJq2nj1aNIdC7wOTztWIH-Ova-iNUjiVfTsgN9VlDzpt8T2F2xXzyJaRZ9TDQu0GvKc3cuDCey-YtfBq6LjqLrjVrCnQg20d6mBUTHf9vdcvvVRroQvtwoTKiUxC1HJT7dyWFmFdefVMsmuBl97f5Q51ct-BUzTysG3MYBwMEQVzP4HzQ9yJV_1lehV4BVQWX0Z_gFcsCVZ8yKzBk9aIXI9fSLFqpQYVjm8FcsFfj2ruGMj4kSrL4NTOVpuFW8w-VId5DtM6oyn0Zq9LR9MYWQ0J8PmqNG8pm9OZl-_p7_8e2D9atO5VIl-NSroSf33cNG89B6-u3j_tRB0fPjyb9L_CzSYSdQ=

**Comment by RitualMiner** [comment]
> Try changing the skill in the Calcs tab. Unfortunately your pastebin gives a 404 error, but there is currently an issue where the config page bases its selections off of the skill selected in the calcs tab instead of the sidebar.

https://pastebin.com/mjXK9Eng

**Comment by RitualMiner** [comment]
> Try changing the skill in the Calcs tab. Unfortunately your pastebin gives a 404 error, but there is currently an issue where the config page bases its selections off of the skill selected in the calcs tab instead of the sidebar.

I reselect already watch my video https://youtu.be/s8xJTVKwI_k

**Comment by QuickStick123** [comment]
Projectile travel distance is present on import closing.
![image](https://user-images.githubusercontent.com/31533893/177665668-0521491e-a635-4dcb-82c1-731084e45424.png)
