### ISSUE TITLE
Cluster Notable "Misery Everlasting" Does Not Count Witchfire Brew

### ISSUE THREAD

**Issue by astradamus** [PathOfBuildingCommunity/PathOfBuilding#2000]
![image](https://user-images.githubusercontent.com/12521094/105095155-2b99fa80-5a5a-11eb-9776-d090989b425b.png)

With Witchfire Brew equipped and enabled, Misery Everlasting does not show any boost to DPS for chaos-based skills. However, if you manually add Despair+Blasphemy as a skill and enable it, Misery Everlasting shows DPS boost as expected. The problem seems to be that Path of Building doesn't realize that Witchfire Brew is Despair curse.

![image](https://user-images.githubusercontent.com/12521094/105095373-6ac84b80-5a5a-11eb-97d9-8bc16132abed.png)

![image](https://user-images.githubusercontent.com/12521094/105095398-74ea4a00-5a5a-11eb-8543-4978d3a2514e.png)

**Comment by astradamus** [comment]
Interestingly, Path of Building DOES know that Witchfire Brew gives you Despair Curse--if you already have Despair Curse enabled, the stat changes shown for Witchfire Brew are much lower (it is well aware they cannot stack).

**Comment by Wires77** [comment]
According to the wiki, Despair from Witchfire Brew is not affected by curse effect, which would include this cluster jewel: https://pathofexile.gamepedia.com/Witchfire_Brew
