### ISSUE TITLE
Major Issue: DPS not accurate due to missing endu/frenzy/power charges (POB Config)

### ISSUE THREAD

**Issue by goodneight** [PathOfBuildingCommunity/PathOfBuilding#2001]
Only one type charge is appointed to each player at some point of the game, which does not change over time.
For example if you utilize 10 endu charges, 5 frenzy charges and 5 power charges lategame for damge generation like Discharge and the POB Config only recognized your Power charges, thus, your damage will be miniscule than the actual.

Hope this can be fixed! Ty!

**Comment by Regisle** [comment]
pastebin please?

**Comment by goodneight** [comment]
eNq9PWtzm8iWn69-BeWq2S-jOP0EOpvcLb_jTBx7rDiZmS-pBhqLBIECyI6ztf99TzdIAglZbY3v3JrxSHBOn_eraXRf_8-PSercqaJM8uzNHt5He47KwjxKsts3ezcfT1_4e__z78HrK1mNL-PDWZLqO_8e_Ou1-eyk6k6lb_YE3XMqWdyq6tN8KfoFlprKrBqrPLuQX_PiLI_e7H3IM7XnBDKLkmr-LUxlWX6QE_Vm70IWchapYs-RZaiy6Gh5693s9lYVmZxVe85EJtkoD7-p6qzIZ1NgfM-5S9T9RR4B5Mfrk5MW7SRr0wbe__X6KpUPqhhVsnJK-PNm7wBUIG_V2wQWv5PpDFahmBO8TxDbe_kozrGcwF97tNFUqWgBjvfdfw7wqlAncazCKrlTR0VSHY1lFrZYZ_uCbeR7J4SLWVol0zTRFp3ztwn-7dr6GKFNwB_zSqbHV6MFLEeM0n1BXPY4Sr608MbFPyfV-DAFpbYJbDXs-W2WVKqNggnGgux7PmW-vwWt60Wex10Qx8eMEkoe43Odqo88zPk-wv423Ks8KfPsSULOlfhkMY_ySZBkXZUCMQ-D0XzPAvHg7vaJIh7leRrl99kCbSPkQaHkZVzHxrWMklm5wGEbkS5kJo_yculP3uYIrZb-T_nGFa_V9zYkFhtj5Vj9WICJx9ZrA3obHf48W0qBN0cQrNeB5Hwzf3d5BXVge6y9T-KW2yOGH8ly4SsNfZ6FS4uiRxe-yQpVquKulR5B_ZYoV6qAErQUl4l9IYgP3kq58Phji1yrW7WUHWPm7bs-fQzjvVLh-AzKGlBtVyH0mPdthzJK06BtpT26Zpf1R0GfzHOdPLq6QYTss20J54OqVlRK-D5xycaAA4QeO2xHeoIGAPokU8Xtw2icqDSyxGqjtALpcQO2kawM-TcZ22RYvNHpT-5k2Q53j7DHJarh7bxSQSkGhEittAfPiHFV5F91X5Q-De2gmOSzZcImBHH3UblrhLbYWGzU1NX4oUxCiBjTG1yraBZ2curmRL3o8i7yOzWBJGZaROiOW10i21hxD1NorVdbPf8RudK0DwVvVltVyfDbcR7dKmscQ-ZpKKdJAVorE6sSvQS-hL7-SE6XOJv7Cx1d3fX5duDV9ckjpeR2XGUwcFlTWcFYJSU2cjeWeblC5QVDFuCrJDaHWH4PkGM9JS67K24DfSF_bEc4LVT282F1fWQFbkXgJItmhfY8axqrGG0yjde-fmnmaP3pfDLNi8pcPJJpWJo1z7PprHIyMwBPkjL8EsziWE-5e0CjMEP6yenpydHH808nDRttlPJbkqZfstkk0ANY_d_lBDZSJp84YZ6mcloqGJGzJN1zEvgw0pgjyKNhZQENRaIZYLbDfpZFWCSgv-2gelizYNWMv9vh9DxqAQZ2kKmyVdHHh6nSJi_ttNTkru2wZvy0gKtHOBuxzJxoo3QVygcLuEWTYAF7kqqDJNWFyEZPF-DodQWzgYZiUiTBrLLyKDNtWHCgm2sLsdrNnAWndbdgsW7TTW2HbFK2jT9BgbbU_bGKFXipVYSaqP8ov6msyWfz3PXahEfplJDUztSkPHyAyf9Ua2plL6AD8GavKmaQ3CIVy1mqr_8-k2lSPTQ0l9ff1zuP5mo5zu9Hs-m0XkmHZAnafv--vnOQVs0imsybvVimZbMPaHg0u4kHpl0y340EZktRZTJItbw1U2Wa640TJaegDby3iqdR9Kr_eg10GtyzNA9kSuYrNNulMIE6t2pyrvWtKhnJSr48r4C5l5rDl0tRbrIgn2XRInYck9A1XgOzvNOmh-f0vtdyn5uwNppbXNN1a1VAXTR0m_pmryHsdKP2GSWDFrhQEpzpcFbofmW-_7Uq4Ca45xW3WdxpF7HnFNbkXpgxUkg_hayb-DVJ-4CeLiZ5TM6ahtMl8tzSHisZpQ-bfXb1_vOasl79yY6LhaV0dQX_mDf1dE261fvbpIPspJ9qVArbGlFnz1n5FNNtE06LoA0Hud90qi2pWtesJaG2kiwXrytNzcnOmfkwz7U_7ZyWsWunJpMk9NzzMZmoA2jx2_rquWmtOGKruAvoUO_yVC16ye3C-VayXc265m--P3Ma-izvlJPHzlGe3SXhUzzZTorTFEgdy3LckqR17ZmlMSs7ZunnTjansqz0eK2n8tVE0773dImw_5hEZmlHrw1V8XmCE5i7U-U_0TT955T2uBv0KO0ZpWptiFxmZpRdE64H5JllNBScmoRzmTmaiN6h_M-1h3MKIxjyvqnykQZxDfK5e6c5oYXUzpzUM0nfZK9RlReTw0JmUUtaSJXRLKlGya0eeJ5ZNEPRqUk-S7C_VdB9Vf_BYG9UdZLFSsEiLUUtLz2zkhYL21obW4nwScr0IocOIBuNVZq2JFm7syJQPcdukYg-IpEm4NQUnJrEM4m2bJYhGV5m7U2C9X55HeR5BwJNwLkfg4w1EWe5W2EjqpURD9M8j667A2zr2jMPq3ph51pubpvLfFaEClIWcPrKe3WoxmqSV2PnrJDldOiM8jRKII9vKMlNbJudlVQGWgtPrekad6N-64WbTqgTuTAMZJUe2y5j01SVl9nbpGKPK_BxZa2qqPlkdqg-Fko5subbAONmVwi-tM-faeaA0SyP9L4SRr6gQyp8hodEICaGHAtvyD1Ghy72XV__RWxIKCLe0GXc138JRkOKBfGH1BNCDF3CBYe_voALlLhDzDkaMg97cJUi5g-5K9whE5jTIUackSEjnouGmBINwRisSihQxwQBOwx78Nd1PU2eYSCAiUvgLxb-0Nd_XMQRcAwrAm9YcH-ImaBoyH2C_SFxsSbHsA93NSvYx7Au55TqVYCxIWcYBOLwRVNCwABh1KdaCS4euh6swrmr9cFdDwSi2GXwWYC2OOYENEQ8MWQ-AYUQgnzNAGLAAHMFADIKDBAqPKJpAHuc-tgdUkR9pCG5N6Q-R3CdUE2UgmI4KJMOBdOcYgFCEkJ8PuRIaAOAAoBfxAjojgkwF4PrHnwGCwz1TViXcAqsgvLAPJRRwKUY16pxgWNOgWOQngz1QQUMVkIglKC-RhKEDQGTAV-esSPXyhPACEhgroBgQAlxbXbGkKahpQdtglFdzkBsATK6jIGg8BewBQiHfQ9r52Ac1vdc-IsQxdqjXE0XdKTVraUiiAw9BoguQRgWRp6rrcgI-AUHscAKYAFQul6Va-f0NVVGXW_oAwEwIQITUm3gPaeCgGgd4MS0OZtZB0Ad0CdRUqnog46FJoXeXL83H_41rqpp-erly_v7-_2prMZ5rH4kqdoP88nLKSwDcfbCRPsLTejlAfzv8ODk8ODo-4eJe_pDXV9_OJ18-VFcnZaf4yt_9KUYxe-Tm-DL6Pjs3dn1z9s_L8W328-_Xxwc_jZys6ODm0qI-OfX30c_x3-Qq-vZl8JD3t1xcnDmnX4a36R_nF2m77_KyV83xbvbd-KbpOTo4_1b8eGOoBcXP7H_JfzzRl5V6Zj8cf8z-PCdnx4dx3feQ_zp2y0hHz5P8Nsf0fRDpdDXMSmOg2k6ub8J__htipKTbzO_VJ_u6Rk5HX_9cSXvvv715X1xJybZ12P2PvrtaOKLF5fp19t79_zg3QvkkqPR9_fT389-TNXpt-rw4VjQT99OP_1-cf7X7e1tOJI3R7enP-7_en_L_OgSvzv7MU7fPQh5ljycnn1Nyu9jdON_O4uvvpMPl_cIiR_vx1fx_fjPw5Or8-BQndDizhjk5dwir-szsmVtnuabyWPGoi7RUyCY09S35jFmDxzW51O2w0Hao8wGDlIitYAjEAw26zHf9YTNehDZFmCQTWy0ArnWTlpMEbfhDnK0zXo6gduwB9nIRsmQpO2M4XrERgwOedjGWZhAvg0cVBHPBs4TrhVZ1_eJFRzHwkrNLrUxB5RqZGUNZEMVSjumVlJQYWVccBbXxrjQNdg4AVRPK7rCE54Nez7zrEJIQFG08mXodZZw2N8or-54WoDu5iAnvm-V0jxmlVygvRRWycV1bQyHPYLtUqR1EvLsSgJr08XeRk8Fl7bxGK77WRuBEac2rgBdmVX6g7aYulZpzfXtapbnWslBsGuTX3QjbZX_oLW0koNh18oBkUe5VbUUdnlSYKs8CaNQj9lguFs2PPAF5jgz8ulBT3_4kFfK3NMX51_MGPgpUfdOqWQRjkdVoQfen3k--dPMlvoMwVslqws5bYZXfa85f0Cb0weVrI6TOFaFOTkxn0M14B9z_l6bjYNm4NSfR6oyg-WsVCMV5llUHy0wl1uHFDSoOWzRtODXsoCx95Vz8-H895uTwbWS6cQ5ySJVDM6LPHOAlzge3GTJ95lyzo9fOb4XBhEEoqDS5YpKT8JXqWLuRypyYaaKI-R7PFASxdKHYRTjkIWchCGDESdiA8OBEfiV46FBc5rilUPQoFH4K-fwxfWLwxdn8O_hwIBeq--vHEwH55NpmoSJhsGDX7H_i1M_InWq3DGnUpz6OOh8e-Z-DDODc69PiuhH8rKR51esEczK-tFRTVdFjj636ejNmI0Q-uRlA0H6IU5Sc0hWpjXY4vqZsRes3-xVwaXgocHn9bqwnuZgcBBFJUirvxNaM1XL09zhzR2D1Nzh6BcnWewqL5lobmsX1prvOgHpdYJj8M_xf4H3lP9dOsd5XgyOilkpwScc81S07Q4iAHvD4I6IKxCVzItxjJR-00gGCPwjZFxx7oUROIQMBPwTBT7Mw54HF2HA7roD3-QOhyuu4LKuK_xvWMgYVPp_RkHMKMj126pzkth5yGe1WHfK-Q1GR1DUtdKvZaQPYE6mkSBgVXZbjQcEdRRaH7dyZAa6NQe1nPqkFjgK_UUjyjRtab0-SqU9sxwQ3l5ofojaMScNGz-7kD-SycwEXn3Is3ksUm40a3MkwTme1QcvHPgHxBuYo37a1UOZZXnlBCB4FoOitL81MP2-QHt94TeZT-au8Fk-DI7yQosHFNpeQNwwxm4QcolZHHk-ijGXviRRJOGzCjH1BSckYiyIXBFLaP8D7PssElEY-LHoeMFamFOkdTRpdKRP3YG1UMda5r0EfQZFOWif_aIDUsM5U_DZ0qRD83FVvzqIDdyt1EfInDgvHCXDsbbx5MEZJ5WO0Qdt-TqvlFsN1q9c9jeU68eR70XMxzRgXEouYtdlKvJ9wUSsfKjqnqcDDKMIlM2oiPUWkhvESCDFvW7GxfgfVC77Z5TLe5V78mCOBZxDGIS6jg6OEn3IWTkHk1mqqraGwTsRqErEYejGRIDTEokgS0GDLQKm-3GOEEYwUPmBhxGLKIe0B8UtYFEURLijYZ-3S5bbVjdp5akUqhVotHROVXEHOgCtu22tm1RzrH5USks1wJAHwkWpq88DDXgns3RKXg0RDfTzCQcj1EmF5gEGKL6BAlK1TQbEGLcNag7mwuKyrG3ZXb3fHl7XHtcH1yeD7mODQfepQdsWyPMDveXtIxIKKXgYM98NI4WRiyVWNKJEMeVzEVLOJVeuZDDe4Ji7zOc-8zu2cH3bggKdSH9B-Vgk-lVxqLWTCZjEJF2tI_NIQWfUt0k1-NWna1GESds4tTKMQ5rGLdYnIiH62C_zqt-qGXDdN9dNgW9fZ8hcX7yZ0b65YJn565Vrg6n83tB5WySTLC_mqQlo5OmdGozkxLhL_UC2k6J8EhuzuRQJJvW-M1WuCD0Pgf-EnCFoELkIwH4uc7kXcwTTvx8GmHpQG9xuAD3SFF6_OGsZjfMNRmOdqrk4GTZvhmjndru_wpj36O5X111PkhT1muhoUXePxnWLAWnvtMh_QsjVLYgz1ieWZnp9WROvH7QtWpF-U4mtJQTmiqIaQEgVST4rnasU8ksnzUHnFeIYUpje3w9gzOOE04h5OIAQw54KIijNwnMh1UG3Du16jCgkPrCijDzVTXOkY6RWZ-Z3bcLweo4avIV0kuVNz1wOKNlkj18h8a6pHspkMZtuzj8w9a0noMusTOUMwsYZZdCFA8fQ5OqOVqUdV4Y5JmAh4r4MuUuYxAELcOyh0PUEjpiAAYcFMQVdIR6ajONSShAXJJQxJKpuQ0tbmmFotfR6616F63o8dzzM2iArnacnerwSb0gotNdbFxEzz0S9mWWDmjeMkLNJMvfIozwLc3MmbwB53yQPSJzlt07uEIzHAUGxF8OkELOQ-Ii6kCDcOHYjEceRkFJhSiWG9GH-Va4HJZhgyjHxugrf5JYabql8pHucbbMjNB9aD4ZhR5lXSMAgPWjmbcLHsDbor3_6Okr09F3ew0CR3zs3RTYYJZB9i3XNgUNKH0fCRzgI_NBTkSBxRCP9BbzVD1UgRBghEuh-hYWgZQmTe-BJDm03pV3NtUol9tuaI13NQZqquzEHzw9vLfoJsHc5m5iGomkRnDAvpqUa6P4iAZz55brz62qrfk3HqeqWpSdtAOlca4Iue9AFaT3PLRqZvnUX2Nhg67dydsGuaXci8SnLLAKu1VTT3pa6D3uDI_WPbod5Ven6cyoTaOJHs3Q6nvV4UUAgmpSSKpZUUK5YoCD5oVAhLAWNIRp9DvkNxgwY1riC6YO7MbichIHOk4SvNr8LL2qHH12p1EdgWN38aodRodZC5Ohf38nMkHoDDtNtYuZj7qAHITRrGZeqxknZaGwMJQZ6t6kZ8s2vcEDw7utKo9Ng99DdPKKlnlTKypk7K7DSQ68xTGOSRxjqADpyqn-6puz1bOPzmeasIb3J0v1z5GleBEkUwQof9blRbYKi-tmTat1QYAXNNUNe4KlYcC-kMLmHOuEyJkMPQ7sWCeRGEgUw_RAOs2QUMxLE3Ffd3pqzflOvZtp54Ah_6eagWOh_Bn4TicsC1igCbGfeCp6rZxkWmxTTPwN-TqpwHOtaeFio-8GoSoL-IiQ4AWcX0o08mOtiP9LjB3Ejoo80EOhjpYcxtAQeJFfm6t-J4W4II7mKI1dFXmBXhDDrjwLpjCa5dsM0ny0CoLvz00zApm0csD4X0q8JOPo9gd7MoctvVTbbjQTDZFlOZQJjzawoYSSG8HpKwnF7Gqy3eaZH-asiKScgWTIpQZB36l6lbUXHipGYRYJLFAfQXsZeJIl0MQ8C4VLpokARzkQcBdijIpC-F3Cf-BILimNEVlxwpaPqDskHd3kCWUFpoZpeHFKA2bVdztW_tgawRpH5QpHLH5wauG2Nd1quDSrqG4IPpjDzpw9QD7Xek3yzmrjeSnc95TPdD3EPvAwTPw5CV3KPiBAcD4IURt5AsiiOsXB9aEiJ3hwiSvJw1R-7vc_flvlX3Goz9UZFX9u4MYn5ffsDqV7BeZtP1Wat6N6FMldCTqIxlSExFcvjyJcCCwZ9I3iT4lDI3IB7zPf0CThoLCn0jxHMn929Ac_WeUZjPado50Ed5zGSn2cVdH_JrarnczvNYq9nyuR2LjZK8_kb-cu3RxcPReev2Wqg-uFQ-xijeb8Eorv1uAt3UGqg-VHMOYy3DqLHptYiyI5u6-kepuuLzk96z2F8u1Xb8jM7lNZjVUzsUFpPgBc_XdPiXe_atmF6xDvMowdn_isvczixYamWUKxvKfN22hyCrEPUu5xLkDnLzbPCR54Tth8P9nnb6F5OnYPgoSx1A1U_S-15bNuHuopG7NDW_HtdFzsy1CfLFqa051ujPCkE-zgkfRzS3bRtpxPyTGhsNybd3ahZovVpE2-xd597bbFAncieSqjHsdxd6Gxx4A3Z3WJhuntQ4V0EYbv5At7N89h286xXvB7NPnXdPv_aUfId8lBPSd7O3g4pkm7TwqI2PtGc_Urfyd_4LkhWIbrW0-zS1FiIzXfWMtnBS93dAo3u5tz06U7Hdq8KO7g43ln59Olx29PB7tLCbhXqbzRSlnbe3UbuDj67u5H-hjPZpnONaxlT9qA7aG7DMGORgMjO6t0xmdjbc23mshCHWuhpfVKzNgPbWVt8l6JoEy9rQ6W1k29hadNA-rKZSM3hWnM4wvxqYZ7Fye3abxDqgTXRDwL0Dv78gfmeE-R5qmTW5LyXm9HMg5lmM3A7mtLQ5-VhXpbLn0gcjeVUFY8RucxaDwXqZwLbaQX6hXnzAHKsoo-5YXQ7Fkzx3Z_CfJommqdxT0WbHzJ8Kp6lYl6_nFv_9cvV_6-I_wfP5WkH

**Comment by goodneight** [comment]
https://poe.ninja/challenge/builds/char/goodneight259/NoEnduringCryDischarge?i=1&search=class%3DJuggernaut%26skill%3DDischarge%26sort%3Ddps

**Comment by goodneight** [comment]
I might add that this issue is mainly about poe.ninja using the automatic calculation of POB. Ofc I can manually add the charges in my own POB to check dps. Its about the tool not reconizing me using 3 charges itself and even just only counting my power charges as my total dps. I would have to buy a farruls fur, just to unlock the 3 charges in the tool which is stupid. I think many players actually get very low dps rating than they actually have.

**Comment by goodneight** [comment]
After buying Farruls Fur the tool says that I mainly use Power and Frenzy charges and not my 10 Endu Chargers. Jesus Christ, how does this not recognize my 10 endu charges which I have an uptime of 99%?? Is it just that I am am able to avoid the meta of using Enduring Cry?

**Comment by ppoelzl** [comment]
THis sounds more like you are having a problem with poe.ninja, not Path of Building. Path of Building does not automatically assume that you make use of a certain type of charge. This is intended behaviour.
