### ISSUE TITLE
Minion dmg trippled when change lvl of spectre gem 18 -> 19

### ISSUE THREAD

**Issue by Ferhnir** [PathOfBuildingCommunity/PathOfBuilding#2011]
Hi

Dmg of Spectre gem on lvl 18 is 3x lower than on 19. So not sure which one shows correct stats.

**Comment by ppoelzl** [comment]
Well it depends on the spectre. A 3x increase is possible if you don't have any additional scaling. Please fill out the bug report template you just deleted, and maybe we're able to help you.

**Comment by ppoelzl** [comment]
Closed due to inactivity.
