### ISSUE TITLE
New 'Crown' helmet basetypes introduced in 3.13 do not apply their resistance modifier to damage calculation

### ISSUE THREAD

**Issue by FarzadBT** [PathOfBuildingCommunity/PathOfBuilding#2015]
* **What happened?**
Putting on the new "Blizzard Crown" basetype does not apply its 10% resistance modifier in skill damage calculation.
* **What steps will reproduce the bug?**
Equip a normal "Blizzard Crown" and check the Calcs window, Effective DPS remains unchanged.
* **Provide a build code:**
https://pastebin.com/h4AmfVSV
Simple test build with two skills that hit, Ice Nova and Frostbolt, as well as two "Blizzard Crown" helmets, one of them edited to remove the cold resistance implicit.

It looks like the implicit modifier should act like a constant +10% to Enemy Cold Resistance against hits.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.26.
