### ISSUE TITLE
PoB doesn't show option for my minion charges in Configuartion

### ISSUE THREAD

**Issue by Bonivur** [PathOfBuildingCommunity/PathOfBuilding#2016]
When I import my character then change skill to Summon Skeletons. I don't see Minions have Frenzy charges / Power charges. Though I can get them in game for minions. As I run 3 Spectres which give those charges. And I tested it in game - charges are there.

My game ID is Garfunkel.  Character  in Ritual League - NecRitua

Also PoB doesnt show life regen from Femurs of the Saint staff (0.6% life regen per each zombie).

**Comment by Wires77** [comment]
I believe the first bit was fixed in v1.4.170.25, and the Femur of the Saints works, it just only shows it when the zombies are selected.

**Comment by Wires77** [comment]
Fully fixed by #2153

**Comment by Wires77** [comment]
Fixed in 1.4.170.27
