### ISSUE TITLE
support tencent/taiwan realms

### ISSUE THREAD

**Issue by Chuanhsing** [PathOfBuildingCommunity/PathOfBuilding#2018]
the realm url were hardcoded as 
`{ label = "PC", id = "PC", realmCode = "pc", profileURL = "https://www.pathofexile.com/account/view-profile/" }`
but there are tencent https://poe.qq.com and taiwan https://web.poe.garena.tw/
could it be an option in config file?

**Comment by Wires77** [comment]
Do you have examples of some account URLs from each realm to test with?  Seems simple enough to just add two more options to the dropdown, otherwise.

**Comment by afq984** [comment]
For the tw (garena) server:
https://web.poe.garena.tw/character-window/get-items?accountName=afg984&character=GPGPU
https://web.poe.garena.tw/character-window/get-passive-skills?accountName=afg984&character=GPGPU
