### ISSUE TITLE
Spectral Shield Throw Bleed incorrect calculations. 

### ISSUE THREAD

**Issue by JeffTheMage** [PathOfBuildingCommunity/PathOfBuilding#2019]
![image](https://user-images.githubusercontent.com/67653864/105565495-112f7d80-5cf5-11eb-9870-b0e6965bc372.png)
Incorrectly calculates 60% chance for bleeding inflicted with this weapon to deal 100% more damage for spectral shield throw.
The line only affects attacks with the weapon that it's on and spectral shield throw only uses offhand to attack
![image](https://user-images.githubusercontent.com/67653864/105565517-32906980-5cf5-11eb-9288-bb0d13d19c2f.png)
Inproperly updated it to include the 60% more damage

**Comment by Th-69** [comment]
Same applies to "Hits with this weapon ..." e.g. for "Moonbender's Wing, Tomahawk", which is shown as best "one handed melee weapon" for "SpectraL Shield Throw" (+ 35k DPS better than "The Princess, Sabre"???).

**Comment by tobsecret** [comment]
Also applies to `Attacks have #% chance to cause bleeding` affix on one-handed weapons - it shows in the tooltip inside the game, but not in PoB.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3776.
