### ISSUE TITLE
Incorrect choice of spectre and minion active skill level for calculations

### ISSUE THREAD

**Issue by zao** [PathOfBuildingCommunity/PathOfBuilding#2020]
PoB version: dev, d65f2b34534ff07763f59bd81f34fb996566628a

I looked into this when the damage bonus from the `active_skill_damage_+%_final` stat of the Redemption Sentry's Default Attack skill did not appear to apply when changing the level of a Raise Spectre skill gem (defaulting to level 20).

Spectre: `"Metadata/Monsters/AtlasExiles/EyrieInfluenceMonsters/EyrieSeraphArcherSpectre"`
Skill: `"MeleeEyrieArrow"`

The stat is represented by the second column of the elements in the levels array which indicates that it should linearly interpolate between 1 and 200 when actor level is between 20 and 84:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/d65f2b34534ff07763f59bd81f34fb996566628a/Data/Skills/spectre.lua#L4016-L4030

When altering its column in the skill definition, only the values for skill level 1 and 2 influenced the damage, whereas skill levels 3 and 4 should be involved for the level 72 spectre obtained from the level 20 skill gem.

The skill level being used is determined by the logic in `calcs.createMinionSkills` by iterating the level array and finding the highest one that that the minion can use.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/d65f2b34534ff07763f59bd81f34fb996566628a/Modules/CalcActiveSkill.lua#L667-L680

The test on line 674 is however bogus as it checks against the first element of the level, which in this case is not the level required for the skill but the level's stat value for `skill_physical_damage_%_to_convert_to_cold`.

This test should probably instead look at `levelData.levelRequirement`. Applying this change appear to make this particular skill and spectre compute more reasonable damage numbers but I have not checked other minions or spectres.

Build code: https://pastebin.com/SRAce8pm

**Comment by zao** [comment]
Skimming the minion and spectre skills in `Data/Skills` the `levelData[1]` assumption seems to be invalid throughout all the entries I looked at.

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
