### ISSUE TITLE
Gem Raise Spectre 

### ISSUE THREAD

**Issue by MuhlinkaDadim** [PathOfBuildingCommunity/PathOfBuilding#2021]
I would like to increase the list of monsters in gem raise spectre so that there are more opportunities for experimentation.
I'm sure this will delight content makers and fans of necromancers through spectres.

**Comment by ppoelzl** [comment]
@MuhlinkaDadim Check out https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1291
