### ISSUE TITLE
pob community fork can't start

### ISSUE THREAD

**Issue by kvapaa** [PathOfBuildingCommunity/PathOfBuilding#2022]
Hello
when i am opening pob community fork latest version(and any version) it just freezes and not responding.
i am using windows 10 pro x64

version 1511 (OS build 10586. 494)

![pob error](https://user-images.githubusercontent.com/77880361/105575513-14406300-5d21-11eb-84f5-47be6d1b2099.jpg)

**Comment by kvapaa** [comment]
so i have reinstalled my drivers.  tried other versions, but still not working

**Comment by Wires77** [comment]
Will you try downloading the SimpleGraphic.dll from here and replacing the one in your current install location? https://github.com/Openarl/PathOfBuilding/blob/master/runtime-win32.zip

You will need to not update, as it will replace the .dll again, but see if that older version works for you

**Comment by ppoelzl** [comment]
Your OS is end of life: https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1511-end-of-servicing
I'm afraid we won't be able to help you with your issue.
