### ISSUE TITLE
Font size / Font rendering

### ISSUE THREAD

**Issue by carlostling** [PathOfBuildingCommunity/PathOfBuilding#2028]
I am having massive issues reading the text in PoB. Does it support ClearType? Is there any way to increase font size?

**Comment by Wires77** [comment]
Unfortunately, the UI is fairly static in PoB and we won't be able to increase the font size easily.  Can you post a screenshot of your font so we can determine if it's an issue we can solve?

**Comment by ppoelzl** [comment]
Duplicate of #218
