### ISSUE TITLE
Ancestral Cry grants an incorrect amount of armour

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#2029]
Hello,

The ancestral cry warcry is granting incorrect amounts of armor according to the global base stat in calcs and everywhere else. Here are the current values in POB at 30 warcry power which is the maximum:

Lvl1   - 170 armor , 128.5 armor per 5 power 
lvl9   - 800 armor , 141.35 armor per 5 power 
Lvl10 - 848 armor, 141.35 armor per 5 power
Lvl20 - 944 armor, 157.413 armor per 5 power

The armor cap per gem level is correct but the amount granted per 5 power is not which leads to the incorrect total for any gem lvl10 or higher. 

Edit: The divergent quality effect "buff grants 20% increased armour" also doesn't work.

Best regards

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
