### ISSUE TITLE
Enemy Physical Damage reduction can go above 100%, causing damage to be negative

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#2036]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Got a negative DPS for Earthquake
* **What were you trying to do?**
Testing enemy physical damage reduction modifiers
* **What steps will reproduce the bug?**
Set Sirus in configuration
Set Enemy Physical Damage Reduction to High in Map Modifiers
Set level to 90
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/KxvsGUBG
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
![image](https://user-images.githubusercontent.com/1209372/105651062-58e01180-5e7b-11eb-8d7e-584e31d7d2d8.png)
![image](https://user-images.githubusercontent.com/1209372/105651085-70b79580-5e7b-11eb-8236-839051a66119.png)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Lothrik** [comment]
Fixed by #3775.
