### ISSUE TITLE
Divergent and Phantasmal Intimidating Cry do nothing

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#2037]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Equipped Divergent Intimidating Cry, changing the quality didn't change my damage
* **What were you trying to do?**
Testing Enemy Physical Damage reduction mods
* **What steps will reproduce the bug?**
Equip slam skill, set configuration of warcries to maximum
Equip Intimidating Cry, set to 20% quality and Divergent (or Phantasmal)
Notice changing the quality doesn't change DPS at all
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
See below, pastebin broke
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
0% quality Phantasmal Intimidating Cry
![image](https://user-images.githubusercontent.com/1209372/105651228-e4f23900-5e7b-11eb-8d54-02b4123fcd78.png)
20% quality
![image](https://user-images.githubusercontent.com/1209372/105651228-e4f23900-5e7b-11eb-8d54-02b4123fcd78.png)
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

### Note that this may be an issue across all of the warcries, so it may be worth checking all of their alternate qualities.

<details>
<summary>Full build code</summary>
eNq9W1tz2sgSfg6_Yoqqrdo8GDS6Ibns3cL4EuqYhAUn2fOUGksDzFpIRBpB2K3899MzEkYmYBpt6my2HDH6-t7T0z0mF79_m0dkydNMJPFlk7aMJuFxkIQinl42Pz7cnnnN339rXAyZnH2YXOUiUm9-a7y50M8k4kseXTaBSrJ0yuWnDSfrC6wtWCxnPIkH7K8kvUvCy-b7JOZN8sjiUMjNpyBiWfaezfllcxwAcZOwLOBx2NuuF8A5E_E4CZ64vEuTfAHqNslS8NUgCQHTHww_jB4qQkVcFQo6v7kYRmzN07FkkmTw47LZBdPZlF-zOfwEbizKgZXt0JbrGz71XJ86VrO9n3i84Dx8JjJa_v8POEz5zWTCAymWvJcK2ZuxONga4Byi24O1W95r6EEeSbGIBE-fKWjrIP93P7D33UPYh0Sy6Ho43mpiuC3HpJ7peqZpea_TJXLrp0PIz0LOriJw6QspuOAq2v40FpLXJB4mIkviGsQb-6qkB03sJfNHEdeycEPaXU5PJe2mnH2YFBk4YqHIs21yHIzbgMWsl2TbuNGDVo3lNtvMg6gR__oCSM1DyGv-DcevCjyI68cSx60KNA7rtkykLnvHkPdist1XrvFKEQnOFbYfBzimH-OUZzxdVmqPiyQY8hRqdTWmrxKO-JQjLb3nPJjdQckHEVBWjhOp_NpWwNfdo7Ao9yjgHvc4SIIT3KMId9xzuP4r8MkOuol5Ol2PZ4JH4XG09lOVBOWvKgEy2FWS021asqy6eRzvdXsKOC70HI4OIAj5zpFmej-RZJgmf6lzPDqRrpvOkzxFhrEAo6weztaZCOAA0i3RiId5gKtOz_3IIFnyOSS9bmagN9sm_yHSqwi6uh3LXzMoik6i6ErJgqfrJJzyk4ScRHErUvBWJirn25mLQH-ADrTHFpiTXu0orIAtGi3gXkxnMob2Hi9lhwRvy4wl2QnGbOFoEcNkBciZmkqy09ADtu0BDnZAtymP_16j-b-AowTcxGGeqtRDy9il-FHMRVtPbeqpP18kqdSLPRYFmWbZjxe5JLEeubInEUVf4nz-qDr_4u_tFq4i5yILvjzmk4maw5qgTKqHx5vb25veQ__TTUky5rqQkCCJIrbIOAxmsYiaRMDDWAkbQ_EMJAINB0M5sB3HfmZpkApw33GoGikQquoR7ThOzU4IGMSBRRzroof1gquIZzgvlbXrOFYPSQhcMdNgzNKTE8bpPGBrBO65MUBgbyLeFZE6gjB-GkD6FmcXBg1nSSoec4nKKN2wIzRQjSvCrGr7htC0aBAQfMsW6jiyrNiYfILjGen7az7hkKWoHap3_QN74nFZzza160Jvj4xkUNTu-Dy7WsNAfKs8tTMivwBcNmWaQ8kK-YTlkVr_I2eRkOtS5nb9vrjn0qvZLFmN88Wi4KS2ZAbevr8v3nQjWTJRYi6bExZl5e2T1lHfYnV1o6Q_awv0VVbEHpUMdQHHHiNleKHdDoHCKnZvLkBAib2LkkcWmaWC5aUcjKZkyud95WcuWcgka_clKNVWmrU1M3i6Yamcfc3BqWCAWlMEPywOYUFrWRVINyp-LSzu6w2tffa8pi8Hn1lsrd0xUh0lqlV9IbrIiELTox4sTMf6UKF_phdh1BdzAW_h7Oul64or979B-xPyiacxk9x66dKD_qvKI0rgjhfLJ71rHlLOCSv8oolpmanwoXoLqxQBmTEc8JmasTwLtJFAXLnvpVZ5lVuAC-fehHAMhO8VXbtY-Ti61w9vZlIusvN2e7VatRZMzpIJ_wZTUCtI5u0FsAGdzrSrzpSgdhf-u1I_upeXmlF7w-miuBPOCrblJ62r0oS6JvWgfMgihmX3tAdHKQz1x3Eu9Swbg7Mdz0LgTNP3Mfxsz-34GH4WpQiYbxsYr1iui7LWsm2ctdT3MPxM28dYYVkdByPWoi5OPbdjOgic41Afkyy2b3gYHLVoB4Pr-C5KrOt5JgoHdqDc7FqYcNiGbRiocBgYsdR0qYUyw_JR0YVscTHR9R0PkwXU9lFy_Y7fwajn2R2MWNPvUBOVzNR3URXNMhwUzvQ8VEXr2KjaYvmej5Lruhg7aMekuAqJrkEd3Ilgo-TakM-YdHEoFEmMvYZjYfKAeraFSntQsIMqaq6HO7E6LsoOk7qo6kKBIQZnUxeVV6aFCq_RsRzUUemjiqTrU1SNNDv7sgW6t223Ax-gUdM9nerk1MP7BEZT9U4tbj7oPu-T4CuScZYGs7FMVY_8d5LM_1v05zC4vONMDtii7H7Vu3LoscqRRzJ5LWBQTvW4tmk8FfDPjX4XujMuO0r1POZFl5tnHAa7JA4_c7ZIYr28acE1EVmyVLAYls1i1iuHnBEsy_U5-fi-_8fHmwb0-hHMclGUZ2QAzzzPGt08FQF8CnjjU8HknAxTTsyW2zK2S708Bc1lo7hm4iF5fmNWWZTDG6wajdLV52R0Bn8a2h8j_vWcuG6jP19EIhDqrdn4p9T-nH63jV-IiIOUM5hdyVjmMbnOU6ZnWvgfhvi54NmWwvxOnV9Iqu7ZAa9erwuqh1nKwe9R2PgnZfGUnxst53s3DDPyq3NGjbdEJuRX6pyZ1luyubQnxYRcpQCIcWYaxtuqWq_jz0zn7esqkZWQMyJnIiNFQCEwcZxI8p8YXLYxklyx4KnRhYmtuIEvpZHeTM_qqxmPyTrJNW-d24MkHClFiFZH_QLMKZLB2mT_QYR9FLH5zoKe3oopJ0o2d5iFFaSyf59vOossPpjB1WTdx3G8YgvSfVxnGbi73ON7ysk-0l0yE0f2gw0vUFdJIrOaCu2z5YhSVzySJ5LcwhD5RCyUSuY-lax67sU5wfxJZHY9Jd160tz63qRHArwvn45E4B2P5lyeKmhPJrl15BxJv7soWapft5zO2Kq_i2gdeXa9XKD1Ms8-Hh6MY09luy-9ahqOqjtODX1q1EDrmJhwTYob_BPDt9_LtfLLqUOE2pKYQNSy06ntVrNG3N16O8mql77W6Vlm1y_7NXKa1na-hUkIGwOqofa_aH6QkawfBbdGVtYPw79IF2xJVrTIXYOH1vDcSP12xKxTYsza7q1ZLvDxrGOOhfATrR8Gu7a3nDrWYPZL_SQ_olJ3nkd7zrZi4oSBUV_U6BsS_bWbJJ6I6Q_fpuFq3H7Hss2IXvkG3uZLOLax51s4K_VFl_XLr-AMun_uQWoJ_ewqybItdCzSPNv8Ur3U7KK9-88-_geNgTWU
</details>

**Comment by TheRealColdAutumnRain** [comment]
Same with Divergent Pride, I am using Carrion Golems.

**Comment by QuickStick123** [comment]
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2887
