### ISSUE TITLE
Skeleton Crit chance is shown 0% 

### ISSUE THREAD

**Issue by Bonivur** [PathOfBuildingCommunity/PathOfBuilding#2040]
Summon Skeletons. in Calculation its crit chance is shown as 0% so no benefit from Power Charge. Although actually Skeletons have base crit chance of 5%. so with 200% crit buff from 1 power charge makes 15% crit chance if my math is correct. Why 0%? If i change power charge # from 0 to 3. Nothing changes in DPS for my skeletons

**Comment by Wires77** [comment]
This seems to be working for me, please provide a pastebin link so we can debug your issue better.

![image](https://user-images.githubusercontent.com/1209372/105732535-2b847980-5ef6-11eb-9b7b-e79e342a86c2.png)

**Comment by PJacek** [comment]
Cold and Lightning skeleton mages have 0% base crit. Are you sure that you are not using those?

**Comment by Bonivur** [comment]
I'm using skeletons from Dead Reckoning jewel. How do you know Skeletal Mages have 0% base crit chance? I didn't find any info about it. The PoE wiki says nothing bout that apart from the fact that base crit chance for Skeletons is 5%. 
Would you please give me the link to the resource where it is said that Skeletal Mages got 0% base crit chance?

**Comment by ppoelzl** [comment]
@Bonivur It's like that in the GGPK file. We just read out the values with our exporter.

**Comment by Bonivur** [comment]
Very strange as any other minion in PoE has 5% base crit chance . Thanks for sharing the info though. I didnt know that. Much appreciated !

**Comment by Bonivur** [comment]
What about PoB not showing Life Regeneration from Femurs of the Saints (0.6% per zombie)? I got 9 and still PoB shows 300 life per second (in game it is 570)
