### ISSUE TITLE
pointers not getting recognised??

### ISSUE THREAD

**Issue by flanisco** [PathOfBuildingCommunity/PathOfBuilding#2041]
![image](https://user-images.githubusercontent.com/38883102/105699556-75259200-5eff-11eb-90f1-8a386fb0ada0.png)
i am trying to import this build:https://pastebin.com/r3EEZjCa
but it gives me that error

**Comment by Wires77** [comment]
You're using Openarl's fork of Path of Building.  Please reinstall the community version from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases
