### ISSUE TITLE
Rite of Ruin is counted twice 

### ISSUE THREAD

**Issue by banang** [PathOfBuildingCommunity/PathOfBuilding#2042]
the Berserker Ascendancy Notable "Rite of Ruin" is counted twice, for whatever reasons when calculating Life Regen/Degen.

I've tried activating/deactivating other nodes that affect life regen like eternal youth and whatnot, but rite of ruin is always counted twice.

**Comment by Wires77** [comment]
This is purely a visual bug; the math is correct, but the breakdown does show two lines.  I get 5% degen on a fresh build with Rite of Ruin and 50 rage.

**Comment by QuickStick123** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/31533893/221331489-ecd659f9-06c9-4c11-8462-dc08f15e7e30.png)
