### ISSUE TITLE
Error on hovering over item in "shared items"

### ISSUE THREAD

**Issue by OmikronGamma** [PathOfBuildingCommunity/PathOfBuilding#2055]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`
I am using 1.4.170.25 version.

Please try to fill in as much of the template below as you're able.

* **What happened?**
Pop-up window with error notification happened.

* **What were you trying to do?**
I was trying to browse items in "shared items" section.

* **What steps will reproduce the bug?**
Just hover mouse over item in  "shared items" section.

* **Does it reproduce every time?**
Yes
* **Provide a build code:**
I cannot.
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.

* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
Error message https://imgur.com/Tdx9Hs5
Item that causes an error, ingame screenshot https://imgur.com/cjKdpqM

**Comment by OmikronGamma** [comment]
Found an item in question in one of my STD stashes
![Bugged Item](https://user-images.githubusercontent.com/23458700/106471990-0bd7ed00-64c4-11eb-8835-1ff0c8695331.jpg)

**Comment by ppoelzl** [comment]
@OmikronGamma Please fill out the bug report template. Otherwise, we're not able to help you.

**Comment by OmikronGamma** [comment]
Ok, i updated the first post.

**Comment by Wires77** [comment]
@OmikronGamma This is due to the "Samite" -> "Samnite" rename.  Your saved item is called a Samite helm, which doesn't exist in the game anymore.  If you edit your Settings.xml (found in the same folder as PathOfBuilding) you can change it from `Samite` to `Samnite` and you won't get this error anymore.

**Comment by OmikronGamma** [comment]
Ah, makes sense. Thank you.

**Comment by QuickStick123** [comment]
This shouldn't be an issue anymore closing.
