### ISSUE TITLE
Quality calculation from the +Str/+Qual craft is being duplicated from imported gear causing armour number to look slightly too high

### ISSUE THREAD

**Issue by runt9** [PathOfBuildingCommunity/PathOfBuilding#2056]
* **What happened?**
  * Just realized the Armour tooltip on my shield in-game does not match the Armour of the shield in PoB (2457 in-game, 2636 in PoB)
  * This appears to happen only with imported gear as crafting the gear directly in PoB does not add the +17% quality craft to the overall Quality % number
  * I re-ran the math and figured out that the +17% to quality craft is being duplicated. Math provided below:
    * Base Colossal Tower Shield Armour == 632
    * Flat armour increase == 418
    * Total quality increase == 37%
    * % Armor Increase mod == 97%
    * (632 + 418) * (1 + 0.37 + 0.97)
    * 1050 * 2.34 == 2457 (in-game tooltip)
    * But if you add in another 17%, you get what PoB is showing:
    * (632 + 418) * (1 + 0.37 + 0.97 + 0.17)
    * 1050 * 2.51 == 2635.5 (rounded up to 2636 in PoB)
* **What were you trying to do?**
  * Add the following modifiers onto a 20% quality Colossal Tower Shield:
    * 418 Flat Armour
    * 97% increased Armour
    * +25 Strength and +17% quality craft
* **What steps will reproduce the bug?**
  * Unknown if this works with other items, but get a shield and craft one of the +quality crafts onto it from the crafting bench
  * Import your build into PoB
  * Look at the shield and observe that the overall quality number is increased by the quality craft
  * Calculate the expected defense number and observe that the defense number in PoB is higher than in-game
* **Does it reproduce every time?**
  * I have not attempted to import a character with a different shield, but every time I re-import this character into a fresh build to test this bug, it happens again.
* **Provide a build code:**
  * https://pastebin.com/7JamSZu1

**Comment by axet** [comment]
Same here. POBC shows 15k armor, game client shows 11107 armor.

https://www.pathofexile.com/account/view-profile/belop/characters?characterName=Bloomxets

**Comment by TimothyByrd** [comment]
I ran into the same thing with this item in Ritual SSF.
Needed to edit the item inside of PoB to have just 20% quality to get  correct values.
(the below is from Ctrl-C in-game)

```
Rarity: Rare
Death Curtain
Vaal Regalia
--------
Quality: +34% (augmented)
Energy Shield: 581 (augmented)
--------
Requirements:
Level: 68
Dex: 108
Int: 194
--------
Sockets: B-B-G-B-B B 
--------
Item Level: 71
--------
+79 to maximum Energy Shield
106% increased Energy Shield
+39% to Fire Resistance
13% increased Stun and Block Recovery
+20 to Intelligence (crafted)
+14% to Quality (crafted)
```

**Comment by yuzi-co** [comment]
Also happens when importing a weapon with +X quality craft
Imported weapon example:
`Bramble Razor
Corsair Sword
Unique ID: 0a4738ddf7d1d8f6820c8b3ab63f1979ed2fb90da5190ef706aaa64ef15b665f
Item Level: 81
Quality: 35
Sockets: R-R-G
LevelReq: 58
Implicits: 1
40% increased Global Accuracy Rating
149% increased Physical Damage
Adds 17 to 30 Physical Damage
Adds 45 to 79 Cold Damage
27% increased Attack Speed
{crafted}+203 to Accuracy Rating
{crafted}+15% to Quality`

**Comment by Wires77** [comment]
Can one of you give your account and character name, since it's happening on import?

**Comment by TimothyByrd** [comment]
Okay I made my characters tab public for now.
https://www.pathofexile.com/account/view-profile/CelticHound/characters
account: Celtichound
character: Celtic_Vortex

Slightly different armor, but the same issue - has 602 ES but it imports as 630.
