### ISSUE TITLE
Please change how bleed damage is calculated, average does not work

### ISSUE THREAD

**Issue by hugglesthemerciless** [PathOfBuildingCommunity/PathOfBuilding#2057]
**Is your feature request related to a problem? Please describe.**
It makes it difficult to calculate the exact value crit or items like Ryslatha's coil or a "60% chance for Bleeding inflicted with this Weapon to deal 100% more Damage" weapon, because these items benefit from fishing for the perfect bleed. Only showing average rolls is misleading to players. 

**Describe the solution you'd like**
I'd like a dropdown in config similar to ailment calculation mode, give options for something like 'average', 'best roll', 'worst roll', average best out of 5-10 hits' (when fishing for perfect bleeds)

**Describe alternatives you've considered**
I can't really think of an alternative, maybe a slider that lets the user choose how many hits to take the best from (like anywhere from 2 to 20 or something)

**Additional context**
Last time I played a bleed build I completely ignored Ryslatha because PoB told me it's only a 2% or so bleed dps increase which was very misleading. I gimped my dps for the whole league because of it.

**Comment by Regisle** [comment]
I agree this is misleading and we have discussed about changing this, I have a fix in mind but have not gotten the time to finish it

**Comment by PastaAdventures** [comment]
> **Additional context**
> Last time I played a bleed build I completely ignored Ryslatha because PoB told me it's only a 2% or so bleed dps increase which was very misleading. I gimped my dps for the whole league because of it.

Ryslatha is also not calculated by pob correctly cause its only applying to attack damage hit rolls and not base damage rolls. It has been proven Ryslatha works on bleed base damage rolls too

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3927.
