### ISSUE TITLE
Enduring Cry Buffs aren't being applied properly.

### ISSUE THREAD

**Issue by Zasilus** [PathOfBuildingCommunity/PathOfBuilding#2058]
Enduring Cry has a buff that gives 2% increased physical damage reduction and 2% to all elemental resistances per endurance charge. Currently path of building only gives the buffs for 6% for each which isn't modified by additional endurance charges. I think this is because endurance charges aren't actually factored in for enduring cry and its just hard coded at 3.

**Comment by Regisle** [comment]
please provide a pastebin so we can debug

**Comment by Zasilus** [comment]
https://pastebin.com/d4J3sGwx

If you look at this paste bin have it set to have 8 endurance charges manually in the Calcs and enduring cry says it only gives 5% Fire Cold, Lightning resistance, and 5% physical damage reduction. If you adjust the number you can see the differences.

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
