### ISSUE TITLE
Socket Group Sets

### ISSUE THREAD

**Issue by B14d3r11** [PathOfBuildingCommunity/PathOfBuilding#2060]
If its possible to implement, basically just like how the Items page has Item Sets that you can name and do stuff with, except with the skills section I want to be able to make say a set of gems for Early game, Mid game and Late game. Instead of having all the things there and named and in a giant list we can make a Socket set, name it those and just show the gems used in those options?

**Comment by ofbeaton** [comment]
This would be fantastic, been looking for this forever. The skill tree has a list, the gear has a list, sockets should have a list.

If you look at Ziz's PoBs you can see how they get around this but putting fake gems to put headers to leveling etc, and disabling gems. But really just having a dropdown to socket groups would be ideal.

Especially now that overlay programs are pulling pobs into on-screen leveling help based on your trees and gems.

**Comment by tamaroth** [comment]
This is a great idea. What also could work is having skill sets bound to item sets. That way you could create a full blown guide inside PoB. 

For each step one could create an item set, put some items that you should be using at that stage (i.e. upgraded weapons, new  four or five links). It is often the case that when you are using a different set of items your socket colours change and as a result your skills might change placement, number of links, or supports.

This feature would literally alleviate the need of having different PoBs for different "stages" of a build. You could have a single build that has everything **neatly** inside.

I'm actually surprised this is not yet in development.

**Comment by Ceryni** [comment]
Plus One to this.

As well, there should be a way to tie a Socket Group Set to an Atlas Tree Set to an Item Set. 

With that implemented, there can be a one stop drop down to change the ENTIRE character from one status to another.
