### ISSUE TITLE
Guaranteed crash when allocating node while "Show Node Power" is enabled (AUR package)

### ISSUE THREAD

**Issue by AlexFolland** [PathOfBuildingCommunity/PathOfBuilding#2065]
To reproduce:

1. Install Path Of Building from the AUR; the `path-of-building-community-git` package ([https://aur.archlinux.org/packages/path-of-building-community-git](https://aur.archlinux.org/packages/path-of-building-community-git)).  Commit `3e28ad5599ebcddf8377cb3cbb433fefe4fb7ff4` was current when this was issue was discovered.
2. Import any real character.
3. In the skill tree menu, enable "Show Node Power".
4. Wait for the skill tree to update.
5. Allocate or deallocate any node.

Current behavior:

* When allocating or deallocating a node while "Show Node Power" is enabled, Path Of Building crashes.
* This behavior was observed more than 5 times with no alternative behavior observed, so we have reason to believe it is guaranteed.

Additional information:

* This issue was discovered with the AUR package from [https://aur.archlinux.org/packages/path-of-building-community-git](https://aur.archlinux.org/packages/path-of-building-community-git).
* This issue was discovered on a system with 64 GB of RAM, with 18.5 GB of RAM in use when "Show Node Power" was enabled, so more than 40 GB of RAM free.
* Multiple other users have reported this issue in the [AUR package comments](https://aur.archlinux.org/packages/path-of-building-community-git).

**Comment by ppoelzl** [comment]
We don't endorse or provide support for third-party distributions of Path of Building, for both technical and security-related concerns. Neither this AUR package nor their maintainer are affiliated with us. 

Please check if your issue persists with our latest release here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/latest and in case open a new issue.

**Comment by AlexFolland** [comment]
I was unable to reproduce this issue with the released Windows version running in wine.  I will use that for now.  A native Linux version would be preferable, but wine works well enough for me.  I've posted about this in the AUR package comments.  Thanks for the response and development of this awesome program.
