### ISSUE TITLE
Unique Abhorrent Interrogation Work with Totems?

### ISSUE THREAD

**Issue by spamerid05** [PathOfBuildingCommunity/PathOfBuilding#2067]
the unique's described: 
Enemies take 4% increased Elemental Damage from your Hits for each Withered you have inflicted on them.
Your Hits cannot Penetrate or ignore Elemental Resistances.

i thought "Your hits" doesn't affect totem but when i try it on POB it's work just fine, now I'm kinda confused, is it working with totems or not?

**Comment by Regisle** [comment]
The hit is not yours it is the totems, what you misunderstand is the totem inherts all mods you have pertaining to the skill the totem uses, including that mod. So while it is not your hit, the totem also has that mod and thus the totems hit also "cannot Penetrate or ignore Elemental Resistances."

**Comment by spamerid05** [comment]
Thank you very much for the clarification.
