### ISSUE TITLE
Error Message While Editing Gems!

### ISSUE THREAD

**Issue by SoloPlayer78** [PathOfBuildingCommunity/PathOfBuilding#2071]
So yeah I was just editing my gems on my path of building and then I got this error message, not sure what caused it but I can recreate this error every time I try adding a support gem to my cleave gem, hope this gets fixed, asap.

**Screen Shot:**![Path of Building Fork Error Message](https://user-images.githubusercontent.com/29515945/106234724-2b160800-61ae-11eb-8ac3-a3407bfb88e9.png)

**Comment by Wires77** [comment]
We can't be sure what caused it either unless you provide us a link to your build.

**Comment by SoloPlayer78** [comment]
Would redownloading the software fix this?

**Comment by Wires77** [comment]
No, redownloading won't fix it, the issue is with your build.  There will be a fix in the next update, but if you want to manually edit your build file in the meantime, you'll want to change anywhere it says `qualityId = ""` to `qualityId = "Default"`

**Comment by SoloPlayer78** [comment]
I see, thank you very much for responding, I really like your guys' software and enjoy it very much. Thank you I'll see what I can do.

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
