### ISSUE TITLE
eHP doesn't increase when you add a small amount of life 

### ISSUE THREAD

**Issue by cyanophage** [PathOfBuildingCommunity/PathOfBuilding#2078]
* **What happened?**
In the calcs tab the "Effective Hit Pool" doesn't increase when you add a small amount of life to the character.

This is because in this code in Modules/CalcDefense.lua at line ~1209:
```
local hitsTaken = math.ceil(output[damageConvertedType.."TotalPool"] / damageTaken)
hitsTaken = hitsTaken / (1 - output[damageCategory.."NotHitChance"] / 100)  / (1 - output[damageConvertedType..damageCategory.."DamageChance"] / 100)
```

the first line here uses the ceil function to return an integer number of hits, but then the next line makes it a float again by adjusting it. This means that you get breakpoints where the eHP only goes up when the calculation of hitsTaken of that first line goes up to the next integer. Take out that math.ceil and it fixes this issue.

**Comment by Regisle** [comment]
this is becouse increasing your life wont increase the number of hits you can take in this case

if I have 4500 life and I take 1000 damage per hit I am dead on the 5th hit, if I increase my life by 200 Im still dead on the 5th
it turns into a float again becouse those are chance that your hp doesnt go down, 
so the forumla is the number of damaging hits you can take / the chance to take damage from a hit = total number of hits it would take for me to die at that incoming damage

**Comment by cyanophage** [comment]
I understand that. But that's assuming you know the size of the hit from the monster. Some monsters hit hard and slow, some hit faster and light. There is a complete range. It's not that all level 76 monsters hit for 1000 and level 77 monsters all hit for 1100. If it was a simulation then you would want the number of hits to be an integer. But it's not a simulation, it's an approximate calculation.

**Comment by Regisle** [comment]
That is true, this is like this so you can test vs known incoming damage like certain bosses, there is a config box to override it with whatever you want. The old system was separated from this config and although its useful to see an approximate EHP regardless of hit size, its also a little misleading and less useful given known values
