### ISSUE TITLE
War Bringer + Ancestral Cry interaction not working correctly.

### ISSUE THREAD

**Issue by s3784231** [PathOfBuildingCommunity/PathOfBuilding#2081]
'War Bringer' from the Berserker Ascendancy grants "Exerted Attacks deal 50% more Damage if a Warcry Sacrificed Rage Recently" but doesn't correctly apply to Ancestral Cry + Strike Skills.

When taking 'War Bringer' and using Ancestral Cry with Infernal Blow (any strike skill), the damage bonus isn't granted despite Ancestral Cry exerting the next X amount of Strike Attacks. When Tectonic Slam (any slam skill) and Seismic Cry (any slam-exerting cries) are added to the same build, the damage is increased on the slam skill.
This occurs in the following build: https://pastebin.com/vdK72gdW

**Comment by s3784231** [comment]
After some testing, this seems to not be an issue with the War Bringer ascendancy but rather with 'Exerted Attacks' not being applied to strike skills at all even when they are exerted via Ancestral Cry.

**Comment by Wires77** [comment]
Multistrike supported skills cannot be exerted.  If you disable Multistrike Support, the exerted attacks and buffs should correctly apply.

https://pathofexile.gamepedia.com/Ancestral_Cry
