### ISSUE TITLE
Fist of war + AS on wep = wrong avg dmg

### ISSUE THREAD

**Issue by Hapseleg** [PathOfBuildingCommunity/PathOfBuilding#2083]
Hi

I have found a bug with the support gem "fist of war". If you add attack speed to a weapon it will reduce the average dmg hit, here is a build that shows it: [https://pastebin.com/hg1mbkwD](url)
Enable the Fist of war support gem and swap between the 2 weapons, after that disable the gem and try swapping the weapons around again. With it enabled and if you use the weapon with 27% increased attack speed, the average dmg of the hit will be **reduced**.

Keep up the wonderful work <3

**Comment by Wires77** [comment]
See this reply for an explanation. https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1910#issuecomment-759973270
