### ISSUE TITLE
Energy shield stats for armor not calculating correctly

### ISSUE THREAD

**Issue by LilyHeavenwood** [PathOfBuildingCommunity/PathOfBuilding#2089]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
The energy shield for an armor is higher in PoB than in-game despite PoB importing the correct rolls for it.

* **What were you trying to do?**
I was trying to get a readout of the total energy shield of my character and I saw that it was higher in PoB than it was in-game.

* **What steps will reproduce the bug?**
No steps needed, the toal ES on the body armor is calculatd incorrectly despite the modifiers on it being correct numerically. 
Manually changing the modifiers so the armor has a total ES of 742 as the one I have in-game results in a total ES that does match the one I have in-game (unique item ID is 868f9050547e89f0148cfb9df470717cb4ff0fdd804219df0b81e009d68b6439 if that is useful)

* **Does it reproduce every time?**
Yes, seems to, friends have also confirmed it.

* **Provide a build code:**
https://pastebin.com/AKgeNLMU

* **Screenshots:**
See the screenshots below comparing the item in PoB to the item in PoE.
[https://imgur.com/huGkF4Z](url)

**Comment by tommysays** [comment]
This appears to be the same Quality-related bug found here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2056

Looks like any gear with +Quality modifiers will be imported from PoE as if the total quality is the base quality of the item, and then will add the +Quality mod on top of that (effectively counting it twice).

**Comment by Wires77** [comment]
> This appears to be the same Quality-related bug found here: #2056
> 
> Looks like any gear with +Quality modifiers will be imported from PoE as if the total quality is the base quality of the item, and then will add the +Quality mod on top of that (effectively counting it twice).

Agreed, closing as a duplicate
