### ISSUE TITLE
Elemental hit and Skitterbots interaction.

### ISSUE THREAD

**Issue by Dex2644** [PathOfBuildingCommunity/PathOfBuilding#2091]
Was just messing around with my Ele Hit Raider when I saw that the chill provided by Skitterbots does not affect Elemental Hit damage calculation. Ele Hit has this line "10% more Damage per Elemental Ailment on the Enemy" and seems to work fine with the shock portion of Skitterbots, but not the chill.

POB: https://pastebin.com/WDMTLWCu

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
