### ISSUE TITLE
Ritual of Awakening is not properly calculating damage or regen with Searing Bond.

### ISSUE THREAD

**Issue by FaceDisabler** [PathOfBuildingCommunity/PathOfBuilding#2093]
Tested this in game to be sure, but I have Searing bond in a multi totem setup to receive the 25% more damage bonus from 5 totems (in which the tooltip dps confirmed, and the 2.5%/s mana regen). However in POB, it seems to only be calculating 10%,, and the regen from only 2 of the totems. Nor do I have the option in calculations to choose how many totems I have active while only having searing bond in my skills.  (I could be missing something, so this is not 100%, but this is just in case I'm not) My theory is it's not adding the inherit +1 from searing bond, nor the +2 from multi totem attached to it.

**Comment by Wires77** [comment]
Can you link your pastebin so we can check it out?

**Comment by FaceDisabler** [comment]
https://pastebin.com/QscPFZ7Z

**Comment by Wires77** [comment]
Yeah, a couple issues here: 

1. Looks like we aren't calculating the number of totems correctly when your totem isn't the main skill.  
2. We _do_ have a configuration option for number of totems, but it looks like Searing Bond wasn't a condition to show that.  As a workaround until one or both of these issues get fixed, you can add another totem to your build, like Ancestral Protector, and the totem # override box should appear in the configuration tab.

**Comment by FaceDisabler** [comment]
Yeah, that was my theory, it's fine for someone like me who knows
what's going on, but I figured for the sake of my situation (just using a
throwaway totem as a damage multiplier) it was tricky to calculate.Glad to
know it wasn't user error on my end.
