### ISSUE TITLE
Shortcut to open the wiki page for a specific item

### ISSUE THREAD

**Issue by Hapseleg** [PathOfBuildingCommunity/PathOfBuilding#2094]
Hello

It would be awesome if you could mouse over an item and click for example alt + W and it will then open the poewiki page for that specific item. The same feature as [Eruyome have added to his trade macro](https://github.com/PoE-TradeMacro/POE-TradeMacro).

Keep up the great work <3

**Comment by Wires77** [comment]
Sorry, we're not interested in adding and maintaining links to external sources
