### ISSUE TITLE
Toxic rain mines is using attack speed and not mine throwing speed

### ISSUE THREAD

**Issue by martinstrotbek** [PathOfBuildingCommunity/PathOfBuilding#2095]
Pretty staightforward, Toxic rain mines is using attack speed and not mine throwing speed.
Linking toxic rain to a Blastchain mine support will not overwrite its config to use attack speed as the modifier to skill usage rate. I believe this happens to all attacks linked with blastchain but I didn't test. I've read the code and I think a checkbox in the modules/Config could be created to force mine flag (like there is one to full/low life) I wanted to develop this on my own but am just a newcomer dev and couldn't figure out more of the code

**Comment by Wires77** [comment]
Fixed in 1.4.170.27
