### ISSUE TITLE
Fortress Covenant Missing Increased Damage Taken Line and Not Effecting Notables

### ISSUE THREAD

**Issue by Crapai** [PathOfBuildingCommunity/PathOfBuilding#2096]
Fortress Covenant Is missing the line "Notable Passive Skills in Radius are Transformed to
instead grant: Minions take 20% increased Damage". It also appears to have no effect on the notables in the radius.

I am on 1.4.170.25.

It appears that perhaps a similar issue happened but was fixed in 1.4.158.1. As noted here(https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/152) but it appears to be back.

![image](https://user-images.githubusercontent.com/50451766/106484254-6dc13400-647d-11eb-8ee3-94eab43de56e.png)

![image](https://user-images.githubusercontent.com/50451766/106484308-7fa2d700-647d-11eb-95e8-07a9fb500aad.png)

![image](https://user-images.githubusercontent.com/50451766/106484389-93e6d400-647d-11eb-9a9e-1e83bdc958ce.png)

**Comment by Wires77** [comment]
Looks like I broke this in my hack for #1887 I'll look into fixing it the proper way this time.
