### ISSUE TITLE
rage support not working.

### ISSUE THREAD

**Issue by wolfwing1** [PathOfBuildingCommunity/PathOfBuilding#2097]
Unless I'm missing some kind of mechanic.  I'm was testing out a facebreaker build using the rage support.  I have it set to 60 rage as was running the berserker ascendancy, but when I add the support, it doesn't add any damage beyond the quality.   Was wanting to see how well it runs vs other supports.

**Comment by wolfwing1** [comment]
maybe a similar bug with multiple totem support as it's only calculating damage for the first one.

**Comment by ALT-F-X** [comment]
Rage support only works with attacks with weapons making it useless with facebreaker.

From the Gem description: 
Supported Attacks deal (2-39) to (4-72) added Physical Damage with Weapons while you have at least 10 Rage
Supported Attacks deal (1-4) to (2-7) added Physical Damage with Weapons per 10 Rage
