### ISSUE TITLE
Perfect Agony Calculation is 1/3 rather than 1/2

### ISSUE THREAD

**Issue by Xephaeon** [PathOfBuildingCommunity/PathOfBuilding#2099]
Perfect Agony is not scaling ailment damage by the correct amount. A naked build with +100 Crit Multi and Perfect Agony would expect a 50% increase in bleed damage but PoB is showing a 33% increase.

I suspect the math is using the 150% base crit as the baseline for the calculation rather than 100%. It therefore takes 150% crit multi to see the expect 50% damage boost that should come from 100% crit multi and so on.

A reference build with items purely to demonstrate the math: https://pastebin.com/13EK8a1X

**Comment by Wires77** [comment]
This is working correctly.

You can see the damage breakdown for ailments here:
![image](https://user-images.githubusercontent.com/1209372/106609036-c00c5e80-652a-11eb-86cd-70bf2b9c16a4.png)

I suspect you didn't account for "A character's base damage multiplier for ailments from critical strikes is 150%" from here:
https://pathofexile.gamepedia.com/Ailment#Damage_with_ailments
