### ISSUE TITLE
Supports granted by items (Cast on Crit) not working on trigger gems

### ISSUE THREAD

**Issue by foschw** [PathOfBuildingCommunity/PathOfBuilding#21]
Currently when using e.g. a shaped sword which grants cast on crit the main gem does not link properly. In effect the mana cost calcuations are off - i.e. the mana cost of my cyclone (https://www.pathofexile.com/account/view-profile/platin91x/characters/platin_yikes) is calculated to be 3 but is 4 in reality (before reduced mana gear).

**Comment by Nostrademous** [comment]
Hopefully fixed by #2294

**Comment by Nostrademous** [comment]
Fixed in 2.0.0
