### ISSUE TITLE
Berserker to Legacy of the Vaal

### ISSUE THREAD

**Issue by ciceroripi** [PathOfBuildingCommunity/PathOfBuilding#2103]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
When changing the node Berserker to Legacy of the Vaal I get an error:
In 'OnFrame': Classes/TreeTab.lua:459 See image

* **What were you trying to do?**
change the node Berserker to Legacy of the Vaal 
* **What steps will reproduce the bug?**
changing the node Berserker to Legacy of the Vaal 
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
1.4.170.25
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![Screenshot 2021-02-02 182435](https://user-images.githubusercontent.com/77643043/106680274-f2967580-6583-11eb-99a5-a6b0f522c6bb.png)

**Comment by Wires77** [comment]
Duplicates #1619
