### ISSUE TITLE
Cameria's Avarice 

### ISSUE THREAD

**Issue by aftrans57** [PathOfBuildingCommunity/PathOfBuilding#2104]
Outdated text states on kill for triggering Icicle Burst, but item currently in game shows as trigger on hit for hitting frozen enemies. Uncertain if this affects any calculations for damage.

**Comment by ALT-F-X** [comment]
This does not affect any damage calculations because this ability is a triggered ability with a .5 second internal cooldown so PoB makes no attempt on calculating the DPS, only the average damage of each hit. 

@Nostrademous will your GGPK export for #2110 fix the typo in the skill description?

**Comment by Nostrademous** [comment]
which typo? I can check when I do it later today.

**Comment by ALT-F-X** [comment]
![image](https://user-images.githubusercontent.com/5727264/106934493-cd1e7e80-66df-11eb-95d8-55c71626f4e2.png)
Needs to be:
![image](https://user-images.githubusercontent.com/5727264/106934621-f212f180-66df-11eb-94e8-c1946c1dc7f1.png)

**Comment by Wires77** [comment]
Just need to update the wording in Data/Uniques/mace.lua and the corresponding line in ModParser.lua.  The exporter won't do anything to this.

**Comment by ALT-F-X** [comment]
Gotcha, I didn't know what all the exporter touches and didn't want to edit the wrong thing if I didn't have to.

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
