### ISSUE TITLE
belt +300 evasion enchant

### ISSUE THREAD

**Issue by uranmorte** [PathOfBuildingCommunity/PathOfBuilding#2107]
I tried add "+300 to Evasion Rating while you have Phasing" in PoB but "Evasion Rating" stay the same.

I tried activate "Phase Run" skill, Quartz flask and phasing while affected by clarity from Watcher jewel and nothing.

**Comment by Nostrademous** [comment]
Right, b/c PoB doesn't have modifier parsing for that line. We will need to add it.

**Comment by Nostrademous** [comment]
Adding ModParser.lua support for the individual modifiers remains a TODO "Good First Issue"

**Comment by Nostrademous** [comment]
Decided to add support for the "+300 to Evasion Rating while you have Phasing" in that PR #2119. Once that is merged this issue will be fixed.

**Comment by Wires77** [comment]
Fixed in 1.4.170.26
