### ISSUE TITLE
Quality @ Anomalous Minion Life support gem "Minions Regenerate (0–1)% of Life per second" being treated as flat life regen

### ISSUE THREAD

**Issue by Pink-Piglet** [PathOfBuildingCommunity/PathOfBuilding#2108]
* **What happened?**
* % life regeneration from gem is treated as flat life regen
 
* **What were you trying to do?**
* trying to determing the best gem for minion build
 
* **What steps will reproduce the bug?**
* use the anomalous instead of a normal quality gem
 
* **Does it reproduce every time?**
* yes
 
* **Provide a build code:**
* https://pastebin.com/ELv3VgpU
 

* **Screenshots:**
![skill](https://user-images.githubusercontent.com/78484101/106750218-d64c1480-6627-11eb-8ca9-68a161e8709a.png)
![flat regen](https://user-images.githubusercontent.com/78484101/106750234-dba95f00-6627-11eb-88b2-6c4f3f6f0591.png)

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
