### ISSUE TITLE
Curse on Hit rings have the wrong amount of increased curse effect

### ISSUE THREAD

**Issue by Ascarbud** [PathOfBuildingCommunity/PathOfBuilding#2110]
Hi when I created a ring with infulence and put curse on it I noticed it has the wrong increased curse effect numbers.
It has 5% at ilevel 75 instead of 20% and has 8% at ilevel 80 instead of 32%
Build : 1.4.170.25

**Comment by Nostrademous** [comment]
Using PoE Trade I can confirm the numbers should be in the 20% and 36%

**Comment by ninjanick95** [comment]
The mod as a whole does not seem to be functioning correctly. Changing the "#% increased effect" does nothing, and the base resistance reductions are inconsistent (compare Elemental Weakness which is ~lvl 1 to Frostbite which is ~lvl 16)
