### ISSUE TITLE
Summon Holy Relic regen no longer works

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#2111]
Looks like "base_life_regeneration_rate_per_minute" was removed as a stat from "RelicTriggeredNova".

Adding Summon Holy Relic and checking the box in the config for its nova doesn't do anything to life regen.

**Comment by PJacek** [comment]
This has been worked on #234

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/234.
