### ISSUE TITLE
Brass Dome - Reduced block mod being treated as less block

### ISSUE THREAD

**Issue by drrcknlsn** [PathOfBuildingCommunity/PathOfBuilding#2114]
It looks like the `30% reduced Chance to Block Attacks and Spells` modifier found on The Brass Dome is being treated as a multiplier.  I don't actually own one of these in game to test it out, but I was under the impression that all "increased"/"reduced" modifiers in the game were additive, while "more"/"less" were multiplicative.  In the following screenshot, I have a new template with an Aegis and Brass Dome equipped.  From my understanding, the 32% base block and 30% reduced block from Brass Dome should be additive, giving a net block chance of 2%, not multiplicative (which gives 22%):

![image](https://user-images.githubusercontent.com/2717358/106812502-c63f2f80-663d-11eb-8081-1184433bb5b4.png)

**Comment by Wires77** [comment]
Increased/Reduced are additive to other modifiers of the same type.  So `Block Chance * (Sum of Inc/Red mods) * (Product of More/Less mods)`.  To give you 2% block, the mod would have to be `-30% Chance to Block` (e.g. the mod on Broken Faith)
