### ISSUE TITLE
Stays hanging and never updates.

### ISSUE THREAD

**Issue by SirTwsted** [PathOfBuildingCommunity/PathOfBuilding#2115]
For some odd reason the application dont want to update, it stays hanging.
Im using Build v1.4.170.25
Even prior builds did the same thing.  It stays hanging saying its updating, but it never does. I have waited almost 30 minutes.
It should not take that long to update.  I checked all my security settings and anti virus in case someone asks.

Every time there is a new update, I am forced to manually download the application and manually install the new version.
its getting to be annoying now.

This is the screen that stays hanging.  

![Screenshot_77](https://user-images.githubusercontent.com/15247713/106856041-eb5a8f00-668b-11eb-8055-c67bd4801b10.png)

**Comment by Wires77** [comment]
Can you try running PoB as administrator and see if that fixes the issue?  Alternately try installing PoB to your Documents directory.  Windows tries to prevent changes to anything in `Program Files (x86)`

**Comment by ppoelzl** [comment]
Don't install PoB to `Program Files (x86)`. Newer installers will have `AppData` as default install location.
