### ISSUE TITLE
Error while right click to set specific vaal skill

### ISSUE THREAD

**Issue by Hedikin** [PathOfBuildingCommunity/PathOfBuilding#2126]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
Build v1.4.170.25

Please try to fill in as much of the template below as you're able.

* **What happened?**
      - I was right clicking to alter a skill tree note and the program put up an error.
      
* **What were you trying to do?**
     - Right click to set Vaal modifiers to a skill tree note.
     
* **What steps will reproduce the bug?**
     -Socketed a Glorious Vanity Gem into an outer rim, Large Jewel Socket, Top Left (next to minion instability), Right clicked on the Thunders Salvo's note, to set it to the Vaal specific (Legacy of the Vaal) and error.

* **Does it reproduce every time?**
    -So far yes

* **Provide a build code:**
See Screenshot

* **Screenshots:**
<img width="640" alt="2021-02-06 145049" src="https://user-images.githubusercontent.com/78649094/107119905-ce3fdf00-688a-11eb-893c-99b0d07d5f65.png">

-Thanks for your time

**Comment by Nostrademous** [comment]
I believe this is already fixed internally and will be part of the next release

**Comment by Hedikin** [comment]
okay thanks for replying. sorry if this has been posted before, still new to this whole github thing

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
