### ISSUE TITLE
Feature request: upgrade finder

### ISSUE THREAD

**Issue by timpluta** [PathOfBuildingCommunity/PathOfBuilding#2128]
It's probably too much work but thought I'd put it out there. I spend a lot of time with different pob windows open, copy pasting things from the trade listings to see how much they help a build. It would be awesome if pob could look at the results from a trade search and sort their calculations within the build. It could do stuff like find the chaos spent/%dps increase and make decisions quicker and easier. And if someone wanted a machine learning project, you could collect results and make search suggestions for the most efficient searches to find improvements

**Comment by Wires77** [comment]
This is outside of scope for PoB.  We're not interested in maintaining a parser for different trade site outputs or interfacing with additional external APIs at this time.
