### ISSUE TITLE
Feature request: Export skill tree to image

### ISSUE THREAD

**Issue by Foeglas** [PathOfBuildingCommunity/PathOfBuilding#2138]
**Benefits**
Small QoL feature for sharing skill trees without PoB. Saves memory on older computers.
**Features**
Add a section to Build Sharing that allows exporting skill trees in the active build to image format (individually or together as zip). Automatically reuse the skill tree titles to name the image(s).
Ideally this would also include the ascendancy.
**Why not use X**
[PoESkillTree](https://github.com/PoESkillTree/PoESkillTree) has the ability to screenshot skill trees. Unlike print screen or snip, this feature captured the entire tree minus ascendancy beyond the visible border of the computer screen (in JPEG format). Resolution was about the same as zooming in the in-game skill tree all the way. Lately this program has been crashing when importing a PoB from raw code (not Pastebin link) with multiple skill trees for leveling. My sole reason to use it is gone. So rather than posting suggestions to make PoESkillTree more like PoB Fork, I'll request this one feature from the program I more commonly use.

**Comment by ppoelzl** [comment]
I'm sorry, but this is not a feature we're planning to implement. Please take a lower resolution screenshot instead.
