### ISSUE TITLE
Elevated Warlord's Quality of Socketed Active Skill Gems bug

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#2139]
Hello,

The elevated version of the +1 to Level of Socketed Active Skill Gems from warlord influence on body armor, which applies "+(5–10)% to Quality of Socketed Active Skill Gems" should apply to active skill gems only according to the text, however in POB it applies to support gems as well. 

Best regards

**Comment by dclamage** [comment]
Just to add - this is also true for the socketed support gem version.

**Comment by QuickStick123** [comment]
Seems to be fixed
![image](https://user-images.githubusercontent.com/31533893/177554237-72b6ce20-6e48-4d30-997a-04fa45b6bbf2.png)
![image](https://user-images.githubusercontent.com/31533893/177554376-24f6e8a8-e92c-4026-b73f-e9ade4462991.png)
