### ISSUE TITLE
Modifiers with conditions are not working when the modifier applies to minion

### ISSUE THREAD

**Issue by meatballing** [PathOfBuildingCommunity/PathOfBuilding#214]
v1.4.157.4

Only applies to modifiers that are built up of common mod components. Unique modifiers are not affected since they can be customised to fit the modifier. The below example contains `minions deal`, `(%d+)%% increased damage`, and `if you've used a minion skill recently`.

**Repro**
1. Create and equip a Stygian Vise
2. Create and equip a Ghastly Eye Jewel with suffix modifier `Minions deal 18% increased Damage if you've used a Minion Skill Recently`

**Expected**
Combat configurations should have a `Have you used a Minion Skill Recently` condition checkbox

**Actual**
Checkbox is missing

**Notes**
You can edit the modifier and remove the `Minions deal` part of the modifier and the checkbox will appear. I suspect its due to how the modifiers are grouped.
![image](https://user-images.githubusercontent.com/61110094/75114748-76718d80-56a4-11ea-8432-2e3b8a253c22.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
