### ISSUE TITLE
Sorting Uniques by Damage Ignoring Spiritual Aid

### ISSUE THREAD

**Issue by Dreamthief01** [PathOfBuildingCommunity/PathOfBuilding#2143]
Within the tree, Spiritual Aid adds minion damage to your dps and identifies most powerful nodes properly.  

If you are using the item search feature, it does not appear to factor in minion damage from Spiritual Aid.  The search ignores the minion damage for the your DPS calculation.

Thx.

Dreamthief01

Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by ppoelzl** [comment]
@Dreamthief01 Please fill out the bug report template.

**Comment by Wires77** [comment]
This seems to be working upon a bit of testing, and without any activity or build to work off of, I'm closing this issue.
