### ISSUE TITLE
Weighted Sums

### ISSUE THREAD

**Issue by Dreamthief01** [PathOfBuildingCommunity/PathOfBuilding#2144]
It would be really nice if there was a display to show the weighted sums for stats.

For example, if I wanted to look for gear in the trade system and was interested in identifying the energy shield gain on the item, there's a few ways to do that.  It could be through Int, it could be through flat Energy shield increases, it could be through +% energy shield gains, it could be through +% Global defenses, etc.

It would be nice if i could click on a stat like Energy Shield, and get a breakdown for my build showing what each energy shield contributor is worth.

INT +2 Energy Shield
% Max Int + 5.t Energy Shield
ES + 6 Energy Shield
% Max ES + 18 Energy Shield
% Global Def + 18 Energy Shield
.....

Basically showing me everything that will raise my Energy shield or life, or dps, dot dmg, etc and how much 1 point of each of those different stats is worth. It shows you this roughly when you hover over a node, but then i need to make an excel file of what these 15 points of this =83 points of that type thing so each point is worth 5.53 and go through that type of math for each stat, and in the end I'm probably overlooking something I didn't think of as affecting Energy shield or dps or whatever....  

Would be nice to just see a consolidated snapshot of true gains from stat and attribute increases so that I can just search for gear using the correct weighted sums for accurate apples to apples comparisons.  

Thanks,

Dreamthief01

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5507
