### ISSUE TITLE
Toxic Rain Increased Attack Damage 

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#2145]
* **What happened?** Toxic Rain's DoT DPS is increased by modifiers like "% increased Attack Damage" incorrectly.
* **What were you trying to do?** N/A
* **What steps will reproduce the bug?** Check Toxic Rain's DoT DPS, allocate any "% increased Attack Damage", check DoT DPS again.
* **Does it reproduce every time?** Yes.
* **Provide a build code:** https://pastebin.com/77aUjpfa

In-game video demonstrating that Increased Attack Damage does not increase Toxic Rain's DoT DPS (it only modifies the Hit Damage): https://www.youtube.com/watch?v=zyNCZdUYJMQ

This bug appears to be new as of 1.4.170.26, this was not happening in 1.4.170.25.

**Comment by Phil-Morley** [comment]
Caustic arrow as well

**Comment by Illedran** [comment]
Still bugged on the bow nodes:
![image](https://user-images.githubusercontent.com/4907434/110116979-9019da80-7db8-11eb-92fc-d6dbf336e2b1.png)

It looks like the two mods are summed together: 10% inc + 10% inc = 20% inc DoT DPS (there's no other inc dmg on the tree)

**Comment by Regisle** [comment]
IIRC this is intended and how it functions ingame

**Comment by Illedran** [comment]
Does it? I just tested in game:

Base DPS: 18.4
![image](https://user-images.githubusercontent.com/4907434/110117729-90ff3c00-7db9-11eb-85aa-d3a7b159f6f9.png)

Tooltip DPS + tree: 33.7
![image](https://user-images.githubusercontent.com/4907434/110117824-b4c28200-7db9-11eb-8c79-11a3da2ecedf.png)

No other equip. Inc DPS from tree is:
* 16% +
* 4 * 10% +
* 15% +
* 12% +
= 83% * 18.5 = 33.672 Tooltip DPS

If you were to count both mods on the last node, (so 12% + 12%), it would be:
No other equip. Inc DPS from tree is:
* 16% +
* 4 * 10% +
* 15% +
* 12% * 2+
= 95% * 18.5 = 36,075 Tooltip DPS

so unless the tooltip DPS in-game is wrong...

**Comment by srsbob** [comment]
Yes you are correct, this is bugged in PoB. Damage with bows is not projectile damage and does not apply.

Explains some weird passive choices people have made, since it's double increased damage on many.

**Comment by semeesee** [comment]
Just coming here to confirm this. If you grab Trickery (20% damage node near shadow start) this is a 3.4% dot dps increase in my POB. If you grab Bow Damage and Accuracy (10% inc damage with bows and 10% inc damage over time with bows, the first small node on the way to Master Fletcher) this is also a 3.4% dot dps increase in my POB. However the in game tool tip for this same change results in very different dot dps numbers. Lightee7 also confirmed this on his stream recently.

**Comment by Lothrik** [comment]
Fixed by #2554. I'm not really sure why this wasn't closed automatically.
