### ISSUE TITLE
Exerted Attacks Not Working in Latest Version

### ISSUE THREAD

**Issue by a-scribe** [PathOfBuildingCommunity/PathOfBuilding#2146]
I am attempting to get Seismic Cry and other warcries to properly exert my Ice Crash. I have attempted to try all other slam skills and other exerting warcries to see if they are boosting the damage, and none of them are working, even with the "Warcry calculation mode" in the Config tab set to Max Hit. 

Build code: https://pastebin.com/3djC21Sm

**Comment by Wires77** [comment]
Warcries cannot exert skills supported by multistrike

https://pathofexile.gamepedia.com/Warcry#Exerted_Attacks
