### ISSUE TITLE
Update check failed issue

### ISSUE THREAD

**Issue by OTJustice** [PathOfBuildingCommunity/PathOfBuilding#2152]
Sorry if I am submitting a known issue, I am new to github.

The issue I am having is when I try to check for an update or try to import a character trough an account name it fails giving me the errors in the screen shots below.

![12](https://user-images.githubusercontent.com/78776714/107315584-0e2fdd80-6aa8-11eb-91e2-96e9e2fb9570.PNG)
![13](https://user-images.githubusercontent.com/78776714/107315585-0ec87400-6aa8-11eb-8950-92d8d104cb5d.PNG)

**Comment by Wires77** [comment]
If you check in Options, do you have a proxy set?  Make sure you don't have PoB blocked by your firewall, either

**Comment by OTJustice** [comment]
![jkh](https://user-images.githubusercontent.com/78776714/107321975-9c11c580-6ab4-11eb-84ce-06f920e22953.PNG)
![asadfg](https://user-images.githubusercontent.com/78776714/107321978-9caa5c00-6ab4-11eb-951b-d98c27270ea7.PNG)

I turned my firewall off completely and i still got the error

**Comment by yuzi-co** [comment]
try to clear this:
![image](https://user-images.githubusercontent.com/7278850/107361324-e52b3f00-6adf-11eb-837d-66d65e71a009.png)

**Comment by OTJustice** [comment]
That fixed it thank you very much
