### ISSUE TITLE
Death Aura not scaling with Area Damage nodes or supports (1.4.170.26)

### ISSUE THREAD

**Issue by yuzi-co** [PathOfBuildingCommunity/PathOfBuilding#2154]
* **What happened?** Death Aura not scaling with Area Damage nodes or supports
* **What steps will reproduce the bug?** Equip Death's Oath in Items, add Concentrated Effect support socketed in Body Armour slot
* **Does it reproduce every time?** yes
* **Provide a build code:** 1.4.170.26

Looks like Death Aura (from Death's Oath) AoE tag was incorrectly removed and it stopped scaling with Area Damage
Tested with:
* Concentrated Effect support
* Awakened Increased Area of Effect
* Blast Radius passive node

Previous version calculated Area Damage correctly

**Comment by ALT-F-X** [comment]
#1995 broke this functionality.

To quickly fix your build until a new release drops you can go to the file /Data/Skills/other.lua and add "area = true," line where this screenshot shows in your preferred text editor.

![image](https://user-images.githubusercontent.com/5727264/107379473-91eec780-6ab2-11eb-9965-722adf34a9e8.png)

Please let me know if you have any additional questions or concerns.

**Comment by yuzi-co** [comment]
> #1995 broke this functionality.
> 
> To quickly fix your build until a new release drops you can go to the file /Data/Skills/other.lua and add "area = true," line where this screenshot shows in your preferred text editor.
> 

> Please let me know if you have any additional questions or concerns.

That fixes it, thanks.

**Comment by Wires77** [comment]
Fixed in 1.4.170.27
