### ISSUE TITLE
Earthquake Duration Enchant Not Supported

### ISSUE THREAD

**Issue by livejamie** [PathOfBuildingCommunity/PathOfBuilding#2155]
The Earthquake Duration enchants are not currently supported. 

Also Earthquake doesn't show up in the skills dropdown even though it's my main skill. I have to select "All Skills" to view it.

Merc
> Earthquake deals 5% increased Damage per 0.1 seconds Duration

Uber
> Earthquake deals 8% increased Damage per 0.1 seconds Duration

![image](https://user-images.githubusercontent.com/49513/107338427-62b76680-6a70-11eb-8aed-cfa42651a509.png)

**Comment by Regisle** [comment]
Does your main skill happen to be the vaal earthquake gem? as this causes it to not show up

**Comment by livejamie** [comment]
> Does your main skill happen to be the vaal earthquake gem? as this causes it to not show up

Ah. Yes. That seems like a separate issue. I can make a new bug for that or honestly it's not a huge deal.

**Comment by LocalIdentity** [comment]
This issue was solved a while ago
