### ISSUE TITLE
Enemy is Hexproof? interaction with marks

### ISSUE THREAD

**Issue by Enigmasdf** [PathOfBuildingCommunity/PathOfBuilding#2157]
It seems that Enemy is Hexproof (map mod) removes the effect of Poacher's mark, Assassin's Mark, Sniper's Mark and Warlord's Mark. Is this intended? Seeing as the marks are no longer counted as hexes, but as curse and mark instead.

"Hexproof doesn't affect Mark curses."

Source: https://pathofexile.gamepedia.com/Hexproof

**Comment by Wires77** [comment]
Fixed in 1.4.170.27
