### ISSUE TITLE
Spirit Offering's "extra max ES" and "increased duration" per consumed corpse do not work

### ISSUE THREAD

**Issue by Hapseleg** [PathOfBuildingCommunity/PathOfBuilding#216]
Here's an example: https://pastebin.com/fFvx6Vea

The necro passive "Mistress of Sacrifice" doesn't benefit from the "4% of max life as max ES" and the zombies benefits from neither spirit offering or the passive "Grave Intentions".

**Comment by LocalIdentity** [comment]
The node Grave Intentions is working to provide minions with ES values however this can only be seen on the calcs page when ticking the 'Show Minion Stats' box. Also, the ES values are being multiplied by 'Increased Minion LIfe' nodes when this should not be the case. Spirit Offering is meant to provide es and increased duration per corpse that you have consumed when activating the skill, and this functionality is not currently in PoB.

**Comment by Wires77** [comment]
This issue can be closed now, unfortunately
