### ISSUE TITLE
Corrupted implicit "(4-6)% increased maximum Energy Shield" on shield is not working correctly

### ISSUE THREAD

**Issue by ElectricPirate** [PathOfBuildingCommunity/PathOfBuilding#2164]
Corrupted implicit "(4-6)% increased maximum Energy Shield" on shield is not working correctly.

Description:
Corrupted implicit "(4-6)% increased maximum Energy Shield" on shield increase local ES on shield, instead of global.

Shield Prism Guardian with default implicit have 36 ES
![image](https://user-images.githubusercontent.com/53792396/107498207-8380d880-6ba4-11eb-83fb-08294f96aa71.png)

Shield Prism Guardian with implicit "6% increased maximum Energy Shield" have 38 ES (increase local 6%), increase all ES by 3 points
![image](https://user-images.githubusercontent.com/53792396/107498449-dbb7da80-6ba4-11eb-8751-62839b138ffe.png)

All shields added with default tool from list of uniue items.

https://pastebin.com/iraAErdE
Version: 1.4.170.26

**Comment by ppoelzl** [comment]
Duplicate of #99
