### ISSUE TITLE
Anomalous Detonate Dead does not parse

### ISSUE THREAD

**Issue by ALT-F-X** [PathOfBuildingCommunity/PathOfBuilding#2165]
From /u/OGv1va and this reddit comment: https://www.reddit.com/r/pathofexile/comments/lfky6w/path_of_building_community_v1417026_313_uniques/gmnppd4?utm_source=share&utm_medium=web2x&context=3

**Comment by ALT-F-X** [comment]
This is caused by the in-game files being incomplete. I've made a bug report on pathofexile.com's forum. Functionality will return when GGG fixes their files.

https://www.pathofexile.com/forum/view-thread/3047184

**Comment by QuickStick123** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/31533893/178733673-6821cde6-dee9-4b0b-a10c-8aab8c3cbfcd.png)
