### ISSUE TITLE
Class-specific mod lines on Pure Talent are not displayed

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#217]
![grafik](https://user-images.githubusercontent.com/33464174/75198611-5ce24b80-5761-11ea-8e5f-7bc9c6aca5c7.png)

**Comment by optionsreaper** [comment]
This seems to be a bug with how the explicit text is parsed when it has a ":" in it.  Another example is Quickening Convenant and the line "Notable Passive Skills in Radius are Transformed to instead grant: Minions have 25% reduced Movement Speed".  

Adding the {custom} tag at the start of each line fixes this issue the quickest but isn't the most future proof.

example: "{custom} Marauder: Melee Skills have 15% increased Area of Effect"

![quickening_covenant_jewel](https://user-images.githubusercontent.com/61510438/75392623-09334780-58b2-11ea-8772-2e5363f94af1.JPG)

**Comment by optionsreaper** [comment]
I can make a PR if the {custom} tag is sufficient for this issue.  Let me know.

**Comment by ppoelzl** [comment]
Possibly connected to #152 
I'd much prefer to fix the underlying behaviour instead of stopgap solutions.
Certainly an interesting bug, as Coated Shrapnel works just fine with a colon in one of it's mod lines.
Then there is also another related bug/misfeature of discarding the first n unrecognised mods.

**Comment by optionsreaper** [comment]
It looks like Coated Sharpnel works because that text is parsed as a variant:
"{variant:2}Passive Skills in Radius also grant: Traps and Mines deal (2-3) to (4-6) added Physical Damage"

Without the variant, it doesn't show up.

**Comment by ppoelzl** [comment]
Good find!

**Comment by optionsreaper** [comment]
PR [#240](https://github.com/LocalIdentity/PathOfBuilding/pull/240)

**Comment by ppoelzl** [comment]
Fixed in 1.4.158.1
