### ISSUE TITLE
Supreme Ego and Minion Instability wrong interaction?

### ISSUE THREAD

**Issue by mystified-net** [PathOfBuildingCommunity/PathOfBuilding#2176]
Using one aura, clarity, taking supreme ego keystone lowers my minion instability DPS - take a look at:

https://pastebin.com/k0VsSTUa (path over to supreme ego, dps is lowered if keystone is taken)

**Comment by Wires77** [comment]
This is because Plaguebringer is coded as an extra aura in PoB, so it needs to be changed.

**Comment by Wires77** [comment]
Fixed in 1.4.170.27
