### ISSUE TITLE
Follow-Through Notable applying to hits but not ailments

### ISSUE THREAD

**Issue by Naidai** [PathOfBuildingCommunity/PathOfBuilding#2187]
From projectile dmg medium clusters

"Projectiles deal 15% increased Damage with Hits and Ailments for each remaining Chain"

**Comment by ALT-F-X** [comment]
#2175 Fixes this functionality.

**Comment by Naidai** [comment]
Fixed it for Divergent Cobra Lash, but not for follow-through notables.

**Comment by ALT-F-X** [comment]
You're right.

The ModCache.lua line for this notable looks perfect, it has the correct "keywordFlags=786432" so it should apply to ailments as well but its just not.

>c["Projectiles deal 15% increased Damage with Hits and Ailments for each remaining Chain"]={{[1]={[1]={stat="ChainRemaining",type="PerStat"},flags=1024,keywordFlags=786432,name="Damage",type="INC",value=15}},nil}

Any ideas?
