### ISSUE TITLE
Doppelganger 'less damage' mods aren't being applied properly

### ISSUE THREAD

**Issue by mome-borogove** [PathOfBuildingCommunity/PathOfBuilding#2190]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

It looks like Doppelganger Guise is not applying its less physical and chaos damage taken mods correctly while sane. In the 'calcs' screen underneath the 'damage taken' tab, the field for physical hits taken does not apply the less physical and chaos mods. To be clear, they *are* listed, but the 'taken' modifier shown while hovering over the field does not seem to take the mods into account. Absent other modifiers, doppelganger guise as implemented will report 100% physical damage taken while sane.

I am not an active developer on this project, but I did attempt to peek at the code implementing doppelganger's mod in `ModParser.lua`. To my untrained eyes, the mod looks fine, but it's definitely not doing the right thing. The associated PR was #2031 by @Nostrademous , if it helps point in the right direction.

* **What steps will reproduce the bug?**

It's inherent to the mod itself. The mod can be extracted from the unique body armour and used in a custom item and the bug will still occur.

* **Does it reproduce every time?**

Yes.

* **Provide a build code:**

https://pastebin.com/nbbaHkGF

I've extracted the mods onto custom flasks to show them simultaneously, but I've also included both the stock doppelganger and a custom version for comparison.

**Comment by custompro12** [comment]
This seems to still be an issue.  Equipping/unequipping Doppelganger and/or toggling the "Are you Insane?" config setting doesn't change the Phys. Damage Reduction stat (it doesn't seem to change anything at all).

Can anyone confirm that the above fix worked for them?  I can open a new ticket if needed.
