### ISSUE TITLE
Curse on hit modifiers are not calculated in equipment tooltip

### ISSUE THREAD

**Issue by NathanC4** [PathOfBuildingCommunity/PathOfBuilding#2193]
* **What happened?**
Curse on hit modifers are not included in "Equipping this item will give you:" tooltip. Once the item is equipped, the damage is correctly calculated, but it does not show in the tooltip.
**Edit:** Upon investigating further, the DPS calculation for curse on hit modifiers is bugged as well. "Curse on hit with % increased effect" mods add increased effect to all instances of that curse, so "curse with +20% effect" and "curse with +40% effect" are calculated as 60% effect. This curse effect is also applied to the curse skill gem.
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/wiELmZMR

**Comment by Nostrademous** [comment]
The `CurseEffect` modifier is created typed to a skillName. That's why it's not local but rather global.
```
	["curse enemies with (%D+) on %a+, with (%d+)%% increased effect"] = function(_, skill, num) return {
		mod("ExtraSkill", "LIST", { skillId = gemIdLookup[skill], level = 1, noSupports = true, triggered = true }),
		mod("CurseEffect", "INC", tonumber(num), { type = "SkillName", skillName = gemIdLookup[skill] }),
	} end,
	["%d+%% chance to curse n?o?n?%-?c?u?r?s?e?d? ?enemies with (%D+) on %a+, with (%d+)%% increased effect"] = function(_, skill, num) return {
		mod("ExtraSkill", "LIST", { skillId = gemIdLookup[skill], level = 1, noSupports = true, triggered = true }),
		mod("CurseEffect", "INC", tonumber(num), { type = "SkillName", skillName = gemIdLookup[skill] }),
	} end,```

**Comment by LocalIdentity** [comment]
Enemies deal less damage mods apply now

**Comment by settonull** [comment]
I see this marked as closed, but the issue is still present?  Using 2.25.1 the curse's effect is not included in the "equipping this item will give you"  tooltip.  A quick example PoB - https://pobb.in/SM0FbVMiQguV.

**Comment by QuickStick123** [comment]
Yes it is present. In PoB we don't really have a good way to apply any special stat to a certain gem / granted skill. This means they just currently apply globally to any skill. There is a also another issue open on the topic https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1774.
