### ISSUE TITLE
Compact Resists

### ISSUE THREAD

**Issue by Amountstax** [PathOfBuildingCommunity/PathOfBuilding#221]
![Untitled2](https://user-images.githubusercontent.com/60943070/75239384-9c745c00-5790-11ea-8437-2702778cd272.png)

### They are also drawn in-game this way

**Comment by optionsreaper** [comment]
Submitted a PR for this enhancment [#235](https://github.com/LocalIdentity/PathOfBuilding/pull/235)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.1
