### ISSUE TITLE
Question: Does "Viridi's Veil"s mods processed correctly?

### ISSUE THREAD

**Issue by Briahas** [PathOfBuildingCommunity/PathOfBuilding#2213]
Hi.
A question - Does "Viridi's Veil"s mods processed correctly?

Cose, right now, it seems they don't.
At least the one that says **"You are Hexproof if you have a Magic Ring in right slot"**

**Comment by Wires77** [comment]
Any mods that are colored red are unsupported by PoB.

**Comment by Briahas** [comment]
Thanks for the answer.
Is there any plan for implementing? Or I should create an issue for that, in order to get into the list of mods waiting for implementation?

**Comment by Wires77** [comment]
Well, the only thing this really affects is the map modifiers section in the configuration tab, but it's fixed by #2215 in an upcoming release

**Comment by Briahas** [comment]
Huge thanks!
