### ISSUE TITLE
Using Iron Reflexes with Anomalous Flesh and Stone shows more armor in PoB than in game.

### ISSUE THREAD

**Issue by Frankpoe** [PathOfBuildingCommunity/PathOfBuilding#2216]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* In game armor value is 11790 with this combo. PoB armor value shows 11964. Armor values always matched before I added this alternate quality flesh and stone to the build. Armor values match up between game and PoB if I unspec Iron Reflexes in both and have the anomalous flesh and stone active. To me it makes sense the way PoB does it by adding the evasion increase from gem and then converting to armor with iron reflexes. Gonna make a bug report on official forum to check if its behaving correctly. Will add response here with edit if I get one.

Edit: Did some more testing, as you can see from the build code I provided all my increases to evasion from tree is a combo with increase to armor. So i specced into evasion per frenzy charge and this gets converted by iron reflexes in both game and pob. As the armor values match up again with flesh and stone deactivated. Pob: https://pastebin.com/kjqamJae

Im far from an expert on this, thinking I should maybe delete this bug report. But gonna let it stand for now to maybe get a proffesional opinion on it.
* **What were you trying to do?**
* **What steps will reproduce the bug?
* **Does it reproduce every time?**
* **Provide a build code: 
* eNrlfWtz28ay4OfwV6BUdbf2lmUJ88b42ucW9bQdyVIk-ZUvrgEwEBGDgAyAkuWt_e-3Z8AHQAIUpNBJzm5SUUigZ6an393z4Mv__j5OnFudF3GWvtpCO-6Wo9MgC-P0-tXW-6uj597Wf_9r8PJclaOzaG8SJ-bNvwa_vLSfnUTf6uTVlmRbTqnya11-mHVFvkBXNyotRzpLT9UfWX6cha-23mWp3nJ8lYZxOfsWJKoo3qmxfrV1MNFJXJRbjioCnYb7izfHiQpjVWb5ljNWcXqZBV91eZxnk5tXW2LLuY313WkWAuCb0_Ozi6va2HFaHxtw_-XleaLudX5ZqtIp4M-rrSGQQF3rAzWGv9CbSibQFaYE4R0XU8SYYFu77W0vb7QOF212KPa8vxr2PNeHUaSDMr7V-3lc7o9UGiwm4na1eyzs6SQp45sk1vnD8K9XukZuJ_BVVqrk4PxyDsukS-WOSynmknp8fbusfBidvQTIWR-Be9SV3o6LKCZ8faslscCeSzDfEYgi3NXwY1yOVoYUIFBU7LjMYy6jcl3bN9dpXOonUMQ0Ps_iIkv_BDkfTaf9bOzH6ZNmO2s6vL1-LLqnKlX7WbHgPqKd2lQuRBZ7nWy70N_qkIh1on2gvy86RGhNh3VI5HXakTdpbR54HYZ1SOl1I3iblWCLH1aNkzhaSDcjnK4xScELA_0mDRa4krUdv09zXej8tmbL1g3RbHKuc_ADZR8LYhpe6Gu9mC8CqaXcW9fgROtgdAz-5EKVPUygkbeFXkhvLZ0McJ1Oa3ttoZJH-jVYoRHa8SRCSFDhMbSujyVy4R1vHXQ7rRCRO536eZjq_Pr-chTrJHyYDpZq9Sa9qFdv0JxQryaPlIDDW1X00qlqMhV0Q1vcTs0-1eAvoEmo-7rkx7c4z7M_TJiQPK7ZMB9nk5pZRPIBI1E1aExcdorJ-ei-iANwPNbPXuhwEjQMl2A74EIwF0RILjot8jwCOs1u9RhUwkZQEBUucNihrNvTQ0jZlx7Qc5I8qsWwLFXw9SALr_WjBnlUi6M4B_IVcc0jCvEw8BlEv_vqZt6G9KP3fmY0rjkafxh4eTSIpPqMdhJfj8oUso_eQy61WBm35yxHKiuWxuw2zTXo5fG6xT-7A8iRyZ-KHhpcgz5Vi8iiE6WjXKc_7pf77wfea4DDNJzkRkCXx2B9W9SH6Ww0tLoNEaoen8TjuObwbIuXuzYlNZ_ejG-yvHQgeSyHQZBN0vK1KkbAAeHSIIJgNNISE-njQFFJlU-IJNxjkXQ10lqTLdv0QqtkDPTer74aVFVQ6rzqy418giJNotCH4BY-ID_ilARUeYzJCDqjOJyFKy_3VRIUdlpv0ptJ6aQ2px3HRfDFn0SRyVy3YJq5TbsPj44O96_efDicUqLepPgaJ8mXdDL2TQpW_d8kwBXkpbaG0wmyJFE3hYakN1JJAX3H8PHStL0ElxGUveAhgZtmPn2gP6o8yGPgfh9gk7H1QtnmwH0gTXbaCxCEQyW6P8Gu7m-0kcKiL82mxroPtE0Qe0FWGV2_CdrMsR8bdKDue0HOw6Re0IeJHsaJccH9qHYKilB5737w4Ezz2J-UPaXN5je98DDxfa8J1gPbXhhXAVSvvqchZh_YqV_qJ2sQrfTmxoGONEhxT222VuJKfdXp1BTP7N1Lq0KFU4A9PtbjYu_-4PzyyFBtqWTQAHi1VeYT6DvUkZok5vlvE5XE5f2rrTRO6s9PqvqjfVqMsrvLyc1N1ZNR2wLofnJSvRkm5bQTM8wM_WpyBkdbVaxcjP1uZ2B8Cxh_34xhCqPKT8zUK-yKJDPlFq1ugDBoa7kD09Z0_8tLGHDa9jjJfJXgOfGm5VMMra_1-I2hvS5VqEq1-wbcXLFrcN213cGn80kalJPcDG2eGPDFo_oAaIbit2rGb6yqW5rNn8Go7sqUjI8x4Xut492ec3hgCnO-fIiDOJsUizykOE8mRW1KU9AuuA3Pc3hnpFaHznQ8pzZg77mbEXpNvnINV1ll91fmvPT6CVMla6Za9e6UmVNzOz1mR3tO7kCrMLmf2f12rrbB_CyOVmM5TUe0AW2cT3gvn5QWo9V51l5teHqLnvvOh_WczuVdHJXDKEpia-vbGdgK9LM4aAdzFqNNnVFlEP-86b6AaPtPGu6-im9rGuDqIOupKhvLdF0B2DBNT3RROPPeN0vHmQsEfpl09-nk7OkGgVwqqTvB6YNNu8Cq294OUPbCfphem8xtjvz0-6ZVyPba2-L1lOJhGMZGflTy6XxVhJtvNzyhwzQx1Rz9k2QX_3nZlf-UGMD9CTHA_9uze7z8T1OJdUowB9m4JtTrC5vSA0Dv1lTufp4vnNq_A1WMamT7bRJPq-IbJ5QdaeMhPGTCWRp-jNNwHfP3sywJs7vN-_FqeMeOv7tZztiiLIRE-3ldrhtPNy7KVd-O6Xx3s8nyB6WS0ywBj3E50kk9XFh5szSr6XBPT7TMAE41glMNsVldfa0hoyn_El01dR2zjnEVj_UQoscaGdtePiQfQ6BJnqpS474icqoA5SzRc4u3wYT154Yzj4hmNhddHiW6GA3T8LK0O-vmc9pLsiy8VGk4W8jtzSnUl1N2aAeGcKrBH5yZRe40ToHGy-LfS0pf61wl4Vl0Djak4YpbX9QGsmNs2JRVYzpZ5LSMCuT8HheH0I2-BL8Q63yGol2i3LB52MvCe2fG559elLy8gWkN8zy7q6tQ7eHmbYLt3am633QR5K8rYiH0jyhi_VsG7PSxFbp2Ri69_lllrMeX7Oj_x8V01l9w444iZe3Vz5qhHWLjhjsr_4oU7DAtUmXi7mWzvfxi4-H-tPtH2u7eudmpiser0lA93fBcbKcbn8CFSq91WG0VsxtdWgrFqyCbXmFQiTmDoZyq-41P8jjX4O3z6VECXbcRK7NdB7vhaU-HcmZjrRqvVUUvIMYKzJkTmOcL5L54rW6zwNmDIHjbeZ8WunTMGsPW37tAMafpviqHxY3Z_bPhdKbq1QS_5Ug7MMxP0Ix_iwWUf7w89Ivp3-m7D5MkhRzFj5fKnEvPNytHzc6XaDz9ZHeVXOVaO6qigG2Jpjs54Ev96JhBAdKKNAvNXhBBqbtNKEPuNnNdirYJQUJuYyoFPEFSbAvssW3qCfgPufCGuFhsI9claFu4Ht7mlMFLTgQm2wJxeIA9uU0EwXybcia8bfjjom0sPE63PUbpNiIC0W0G3bvbmHHoBBHMts3JGATQXPJtIgU8Ya70-DbzJLbPTb9YEHcbUSnJNufCBVSYK8g2lQY5JDCMJJhn3iHzFGYHuHP4K10PZkowIIuxcMk25mYIjimW24wTJu3QHjzHEnBkHMHQQjJiJ4C3mRScm_kTgHFdVE2Mb0t4DoOYjhmjQCwkGAACjoAphwHxNgZ0oRvCqR3EI9umF0CHG2rAUN42wwCBJYHhMEFSblNCuG0IU_SA6EBzzhEM5MGkYXbwgAqgMWcuoUBdDL0ijCm8ZNA1QoZQTEoMfRNksEVAEfgAE8UIWgHpDVYwGHTLMBPAZsmAA9j2bvAEGOpxto09Cm8NvSngLGEWhBoB4AIkBiNKjIR4IAAcuxQQwxRwhAkICs8p0IsS7sFn6QG9QKgQAkRg8kAGQSzzQEwoRdzKF0gFpRhmTDgDQOoyoK9riM8owobKHChOiJE-ySUgZgbfJgx7nsEAhIVxYBAwwjO9A7PkllOCftROYiIyPWRp9IFObcVhGJc6fGdUwz6oP3E0fMzyS220FHACpY0DW8fIy118YP5aZXwDD4vdG-gZNLHYNYVPu3HMfN0Jw6JSveoAZ3XIyHw3WFi1qDD55RfyH06cBuB_C4isx-p7PJ6MHQNf4bW7QGw9poJQvgFM9yd5oZ1qP-ICY6vfM4xZHeMK0ri_e7D_jm1e_D2omz39TrUpsDoxMMfeiN0M-2eI_odJupegfyrK77LSWP01RE8sCe0G-gXexmYv0LZYzwTEQi6jD0DMQrW-_VmTO4u6ZmWxmJ0fbRV-WRelOvzfg_Ei6nWmB5BnWFv7NcNa1LFebvP3YG6Py6zQ2lrmGdbIraNdb_BIlMFQu267lM72wTuBStOsdA6_67x0rnIFAZhThTAtNuQSTHZ6XY7-HB7UW3DoGTJqcDpVlvmJC2d65OKn4YCwBy5oigSv918lrTURARzdOpIXM0b8DLys657hhWnDgFc7rmH80kTYZg2jqp_PsMTWpEBe7Bwm9mSZSmqmZYO0ZC6l_0SbSjZhUxGDyKgmrEh6c0FBrJshbbo7nsu12YjvVDvxW_iwEk38Ys-IQpZRasfdAVigj3np3EDuX9jV9Q2K4NKMMaUd-lmduvoJytnEAAvhzcMAbz2h3B1qqTNV28pOOvYgCMCrogb6DFs9fiKOnkc3EPo0JKFP2NYtQn816mbxfCXeJC6XaIZ4w1zpebz5LkufV9Gq6aJwojwbV0FozdH8pNl0RxDT07wrrhiED3ntAUSzyT-HCY1Ijf3zmLAm25qefW3PBrBEaGGIKvfW1uQfpcn1FIb8rZrcKfs2o1obgjbkvgb-t6A7BDyMCK_anlqo34zhGi3-JtGuFxKwhH9bzeSfKCQ8CtEnRmGNOPmvDMM2wwVznr_dtrgeF8u2ZQn6n2PgqeA_xcfWH1T1tZfvL06qkUZleVO82N29u7vbuVHlKIv0d8idd4JsPJvKc1twf27qeLtD-Gdv-Nv-cM_9bVSIA_352P_8OXt_dfEdDbUW4kP64-2953-7_X7y_Kzwn4_ii68BR974x-c3H4foa6k__n705ujkU347vifjX6--XZxNjr-g96ffh7efr65OGL0V8f4eim_V8acfJLxLf88_y-HZ2xH_9PvvX77S-7e3sZfKWF68pfz9bXAfnhGafVLFwR935enexffgW6LS7wd34fnR6ygeJ7ffAnV2MD7-cn3z7ev9l0_H_m-lO8k-_yD0E71kVx_evk2uPv34_ceHL3sZHn3-fHl0e8b2PozOPPXhw5m4zaP7j3_skW8fuXz37dvXu4ydfrn__lUPyfD42_3bj3_8Wny7ZgfvJnF0Xr67xZ_u987iT9GXT7--xedvj3BxdPRN_fZ7xYoZ5V9Wt8bN6p3Vt4VCcgzhiQNcswsk0wsYWuAQsgXRh-CAA4T2gLPrDws43gmHpezTH_XMbRY9xiVmC9KDYBIUugcY4bzXbDkiLuuDHWSHPanXZxa2mr6AI53ogefrgx7HpI8M2HWfBZzXST3EPdJntlIg3EcGkCd4H1n2KOkDB1kU6iNThHDShx12PWoBx7rp4vYZlrrUdXtNg8heZCaC9SELk8zrIy12DW8BRzvxMwt3CzjU2R9Bop8J4pz3Yoe5nanHfBFoZa9xzV2VfeBoT7EypaI-cIL14S8SuNe4lHteH3UjWPA-49plvwUc7jb1gvYyupT2Mhtg_Hrhh1xGcC_96GecqeT94MBa9XK9GPE-5sWs0_eZrxRS9BqWoz7dCcndXq5S9jKSXKI-3dkF6wWcmG2-2a1FO_DlRgd2F4XZO2E-QNpSRabm4eyL3VnxIdZ3TqFVHowuy9zsRvmRZePPr7aeEyl3iMCzf6qbNV5rVZ6qm_lWEwN8Mt_LaW_lKFV5EENEnds7RWYbPwzgJ-hVih3uoek_buUjX9ptKdM9HubzpS7t9pVJoadHsOzJTfu4dpeHAbV3kkzLGxfK7MZ_4VwMLw4He3qkx1k5co7NBjedDk4hyzDpVjIpzNavt_pOJ4P3afxtop03By8cpDQPMHN1FGrfEx6OUBCKCOkIc62CINAR-G2tgSbcC4FfoSsZRgF1uc8JDwYWHUuMF46HBvbThf72wmF08GZ8k8RBXBYvHDr4P0GuIsgX_u8QshaHOudVHjDLMeavkQMApmJWf-_EQKkKe6dieqM_Uz0em8WLZqfOda7S8oXzrFoMXqrBOdktUMQc7XEWl_4OTBE-mG_aHt5mcej42tSMLstJmupwsGY84FI2H7RKZduWUx7ZRWvZqpNMH-JbQPn1RBfdMB9VYdeBFhcPWA0yvGzKGG6RsTM_gSGy1NkDGSselLDIC4NIoiigIUOaaKW02RTCqECBH7ph5EVS4EiFOtCexsjlkdTIxwGnKhI6akiYEP_-EtZYnkGtyzN_nYg1Kr7mcihnjt50eeqvEjXSFLX379789v5wcDUC3Oypo9fZjR7s5_G4ALxWpEyoyEcB4qFLNdWYBloyBZIlA1eFIE2eYtLztCt1IEPNuEaCRQEXJCAmKQ6bdowPLhRINUjVB0DH1L7qkoZ6GImzNLl3VHXh14woBZDamaqL2eg4qD-vBjRL6tCTM0ySLADah85dXI6ySTntHqQjhS7hOYxrSzSmgDJ4bhB6YP22jea0leYfVRmMdP6_wPsU_1U4h_d6cJ7HxRhEIlilPAHVZUS6NBSC-1pggXQY-oh60gsh-hU4kEwS7ishwWn4HuVmt5lywdeAS3GblGcDe_OhnaChdIPsDWG1VnFKtgF9uFjOOyunrWtmRhcGotHIXMBntRtihvir3WdgJOBuZLaFVLwGKP_e-QjaMxo8w1XJc40taGlbOw7awTTWyrQT0Cx9r2dMOwJRGHyI8ziMVZu6kEjyCIZ1BXG9CGsmqI88zZAQwnNFwD2FqBth13V94mKEVRhRCckvpsDsplH23JpRxgvdqUS9ycL9LM8nN2au9sDmbAsJiHycWgMBb0C_QbQH9upfu1Wh-jS9yMJce-aMszCOgIB11VG5NptQ0iLK8nGlIXvZnXM6A12M3UFY3uLsjjKz4yeJU_Bta-jJaaAEV4EKsVJM-8z34XPEpHJDTBT4NMGDwHN9n3KXMwVJknYRJuAaEWZSN-jJvVVrU9s5sLTPZb5lezDdazJbo7akO9DfAXOYz0B0yr-7g6tdAnP31bkgbrUCNTZ0TYGMnarOuFX7GdoILFol9zjJcnuW6oNKDaJGRxKzF70lWA2Z1jQImM-RLzT3KchxSJAWgcAk0K7r-VHE_VAhCR4gEoKqEGwORSSirNPInxg6rqO5vZF2hd57oOXwEiTQHArwrTwDFc1mL6dQQQ5iFyzem03g5vWn2FffJqph_POFBO9nKUw3r4yBaWcq_oPXYMiBSkEHYb0WyT1O7m9Gzlluxk3LgZ1jd5RGJPIjTHgotIqQC3F_4AchGAbpQvwmFDXpAViIIGQh8wVFbhQhXxKGQkmEpk3SkppBoO66KM3rjNJwW0RR0agepRWPCdPMWk33mjzrXga0u0TM6soUy74BGrbxQWI1anqfZ3eoBPJUJvr5a5WH5gReN-DRpFKYYVGYswfdgKfKctuI0dEkDVUVGHRFA7JFiqY208SCpyr_OtiPS4jUE2NZ6-ITBEQyAU4DI625DoXHsS89EnIMsRjTmPsSUkoXY5eTUFAcIE9KTPyQitD1xOAwCQFRg0pTkuhgessMeBZvMGX5C-f4-fHzi-q_ekLQMJzu4Blj1gHPbaAVOSLMQ-6u8J8vojpwIXNjVvNM1siVIxPWVs4IOgo19IBcaDvOFmvdc6HcB3cxUsCUyY2BJhBF2Bc1v7RITJqb9pbxW8C5nZsO5zCzdckp-TpYjtwWni_O9AwWR3qaxkLJMFKeR8HFEXBvwG4XmO8xAWaECSIxU0ShKJLEE0oYP-eTgEPEQbUAb_dR5WD0wxZ-swWPL-qcbVrn1-CK0CxNOza6VlQ9ONh1Vs5qVfpQMV8amiC6kqkZNbV0LAbPhKyvVFsX-YyK1v3k0430qR6b_bBWPBpHfEws8zout6tXhK9uql9wzC7DgvilOklsKlHZEys8zy1K9rdrqizN_CZMF0-XCkOnw-M3-4P9EeBYlLP4EMQiL384R4kqvhpSAUfCJS6DOwhFxAMvIpBA-VoqqqhEUriMUAgfPQ9CHur7EoJ9D7Tdp64OEA18FUSR8FWDsayuyI14UTR11gTNeXXSbbZX0FTEwHePx5PUMqo6fuBMb9applCtZkNuPTa3PM1AgPrQtotOuI1Oh98hD4-NoVxkQPYKpyJOTAQ_p9gwhDALZpTqOtEooqHPiOAixECJ0FcUUk2P0wgilNDHFNypgP95EPYxyUngh5KLyFMu-N9Iy2YgKDuIhvgS0RoR2ezHISqT0Eon0tgZOY9oOgjVnppfTMbxjEIQtQRZld0bdYQErhqvIU-BkkJyH-HIszVHH4Gp4CFEzhQFEVMC3EMgTagWYskMEOIQg_ggglL6XtNQ4A7S8GUfYKLV-i0MYDSW4ts2Aj1raVXfTd_aqIN8tE3OLrUGRwI9HMS3IENVCWguXJelmqTBaEkjA404Ilppz2eudhmEtRJBKocwAnuLSOhqgqWLogBjH7uQzWkuwOFCSs48SsNlU9tBQbdpbBduB63uH9lxnldZrvWK9ucKIKnVaaWznC-UeTg2P1MAxjMwmbBR6NQY0fmT-0rDjdGc3ZZhyLNOy-dA6_WctdL_2wRs-Ux-96B34-jUjcnKp67j5D79Xic_hkDFj3xfQWostU-Fh8HHBUEImitpREgQaS5ZoDSVjLqURQHRIfVYqCGi5qhBfiQW5Hfrgc3F8726posmM57h6vBPdSB1pSRRKzM-Q7wZ_CBvXXAx3eA8DAIwBsH9YmN6K0l5DxfTMASGpua3DNNlLwMJseCMQnbhIYgVXMgsIDmmSqhIRSyQpngUusr3IkZ9zpkXIsjoAkq062nt-v0M5oqXYeu8zFQGL0dG69cJYAWxXvqWkt53Zxenw5PB3iRP48Kkj0dZ3MjEcCBgfgTr0DVkiDyJuBDMDzyufQU-F2MUBlKEEDprHzI1KQI30oR6QpqYu0EQSlul7GIpcKbuU6WsY9JtCelBrq6BVPuJuhscZ0mszDIVmDnIeSCLq1Mg4hg4K6TikDsAwwPXpcQngmnmMS1gkpDgq5CBF4XHYaAhAHEjHysvCAIhBq8nxnu3RJe8IR5L2UQj3iTLXoT3L_DbQNMqH3LXBZqo--yQEM1c1B7VeeZ5LYGpt25rcytzZGfMf3kT5yoZfND5GGJPuwCwpK4UHE0QhjLyNMSAHpHg0iPfoxJLApILFpFgFAmklOeCKwfzSBSwLwJJBkcf0JVq75zkXkMG8cLtVDeMFU4xGY-ztCqMfLa7EwNTGL8ytZlpmIzZamVq0H0I5BmjhnZvQFpgttd6um5SODZDRHhtliBRCzNY617QZ6TjxGa_2L8q6_UL_nFbQgfaBq9_1fpmcJHdQy9gfUAVIXeqc1ZJF-yKG4KJwwH3IarnPheKaSUpJi7E_oqBvwPGuiRwA0ZA5ahLXHMOHHlRPYXvzu86NHDv-d6SBnLWEYXU7kZzInDhkNA7an6TYf1OE9BaqzAz9ZFt6kMexzGTetcrpVPBsFtmIdErnNJcn2RKpfWd7--0ykFqZ3migXHk-uMhrcxtW_L_NbcjvoYhTJXvBsKw4XiSNJkbGMfhCRyxCPFI-UxCuMgZ4xH4EMI5eFwE-R4jXoB9F_vI1yELeUiYTwl3m05F8DqfaIfazpawTCCQ3c3L0YG6H-BG_aKajaFqtSMiMlGCidtnK1q12tkzgto1ttIRJB6b2GP0MCq1mkrtVLmZzrJ4dFXWMG7PoLQhnHKOVJ5PkvnSDcjqVR5PxjcjEx6fqDHMVeV1dppAVCohBWRNGJQUQlGlgoC42CNCS0IQKK3vU4hDA80Vksz1GAooVZxrL2BNdsq1XhH-1kMFCLEanhFRvOqqLHGmRxxB71rqKXjHdaer3YVVNDWPG4fXVelknpWuFnQuqh8GLZw0q5YkzO82TStsdlV0Nlj182Gm6fT4oUVs-aRwlbFAQ-fa9LOKywD8TWWMz9IiUROz8lgt3d3PXrQ06pAF0hYbGYm6NBE3xA97eabCkVn2rqzcb5MYwozGchPBUaDB0RqlVTjAkJWAxUZShRAthpECDUcSvrk-E76HJYIICYJmzkHFw1B1R0h0jQmuxTWtrtGsts11DYmHFj_nUWavoKo1-MHrz5Tw7qpIXanZE5W6ffX84h4kpBypRWkE4vvLcmIr9Hs6adhl3_UxkQp7PtFCKKwjHEqPY6owl5D5KHNDDqLKi0Lf93zuShL5LMLSXIgTINzNPIKbzCPNiwHKSTpXMJPATF0TkJQ3zrmaiMbWtWfHeNvXCAcE2G0X7Uy0tgauMtZmCIzWh1dihd1WyZlblUrmKmunoqoZdOoca9G5D7HZcWPuUB9c3WXPr2xsaW8odP53ZcZ2pybsP-ssA8uquObAN-pFnocxN7-wqTzkm-t5hPZEwAPPR0oQgoGjAItQ5Jn8BfkShU_ITpbTNdEVKpsUf5bWziNFW0-q4snYXuBSSSbYLF9rW542JRjQjOR-MFs1WChDMzDqqo6vSUI6QynC1qjnvLRjWDxdgLFLLbO7QxwTiUV2faux2DLdTXCUZz_0UkHzMslmPzK5-E2z2abS2a-j1oCqlL-2LXb-G-g1oNnPCsxhvFUYo_W1PdG0a6jaHlfEV4Fmt6LPO3K7OqrNC3WOVtu2jEgXUG2vNMKrQLMfF6khRbqhpj9BMu9QdIKiZVC2Cmrviqvj18LCxk3RcxRxR2d1srltndnbS-fdtOBURd41mJnETDf4rtncW9_T20YRQxBn6N8XhZqtfTstJzNaibnUDPdrtqIcq9R4IkJtc3kAKaNDj2zSqb-twtmGE3kafftRAW-oGX0akvxpo_Vs1kZN9ACH2wTqAQ5UJvGxA7WIEn_KOA_IX5dr6NEzeboeoafMhD5NGNDTRI8-zJ9Vd9lC2sf22yZgT5x5L9PT4s8fRugJdpA8NO-5E3wkA9vJ_CQJY09p1EsrVwOifhFRj5myJxMWP0EU-dO0iTxNgsnj5Yw-3fY_QarRk4lP-ihnS_jbL_59EPE_EQT15OVquN2bEfwJgvl0TvwJielrmNtzisckFb258wDtuhKSHoYGP5nCTzQa_Vm6mjf1mA_pQamWbKs3J-iT6cWe4vH6KM1qYthb1B_AqTOp3J1mlfbUq12xMJ_2szSKr6usM72ZzHoxVdU8DvW8-j0tfm9Ni-TzsRutIF-tKudzaD_LEq3S6RHX1Rb-7Ie4LqfX5hSl2UABVDo5OztoH2IVp4dGmc1mCbnmVF7uzmjxcvdclaOzaG8SJ6as9K_B_wDn52mt
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* 
![armor](https://user-images.githubusercontent.com/79255700/108345624-c9f6b880-71de-11eb-8780-4c56a8f56a9a.PNG)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
This is valid, when mods say "increased armour and evasion rating" they should only be applying once for Iron Reflexes.  Flesh and Stone was applying each mod twice (you can see that by putting "10% reduced evasion rating" on your bow) and is fixed by #2237
