### ISSUE TITLE
Can not install PoB. Tried latest and some older versions, changing the destination folder.

### ISSUE THREAD

**Issue by itssunshine** [PathOfBuildingCommunity/PathOfBuilding#2217]
Both the .zip and .exe produce the same error. This is the console, sorry for not cropping it.
![image](https://user-images.githubusercontent.com/79257107/108348456-64252380-7214-11eb-8339-25872d32bea9.png)

**Comment by dclamage** [comment]
Can you please provide a dxdiag? Thanks.

**Comment by itssunshine** [comment]
![image](https://user-images.githubusercontent.com/79257107/108445682-624c7600-728f-11eb-8eca-383205bce9d7.png)
![image](https://user-images.githubusercontent.com/79257107/108445712-7001fb80-728f-11eb-954c-f78d0fd565c4.png)

I made no changes to my system in the past week except for removing my old HDD and reinstalling win10. Before that everything works fine.



> 
> 
> Can you please provide a dxdiag? Thanks.

**Comment by ppoelzl** [comment]
@itssunshine Your operating system is out of date: https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1709-end-of-servicing. I'm afraid we won't be able to support it and recommend upgrading instead.

**Comment by itssunshine** [comment]
> 
> 
> @itssunshine Your operating system is out of date: https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1709-end-of-servicing. I'm afraid we won't be able to support it and recommend upgrading instead.

Thank you for your support.

**Comment by ivanspecht** [comment]
Hi, i have the same problem, but my windows is up to date
![image](https://user-images.githubusercontent.com/73004925/108586992-20274100-7330-11eb-89eb-9c8a7ab0547d.png)

**Comment by dclamage** [comment]
@ivanspecht Please provide a dxdiag, preferably as a text file. Run dxdiag and use "Save all information..."

**Comment by QuickStick123** [comment]
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736 see https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087 for tempoary fix.
