### ISSUE TITLE
Proper support for Minion Instability

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#222]
- Shouldn't be affected by stuff not affecting the Secondary damage type, like Spell Totem damage penalty.
- Shouldn't scale with attack/cast rate.

Siegebreaker (there is a separate issue for it, but for sake of completeness) should also not be affected by the second.

**Comment by ae9213b** [comment]
Spell totem support has a generic "less damage" modifier which according to the [wiki](https://pathofexile.gamepedia.com/Secondary_damage) should modify secondary damage so unless I'm missing something this works properly.

**Comment by ZzZombo** [comment]
You are right about that, it appears I mixed something up and wrote wrong reason; I'm certain Spell Totem still doesn't affect its damage, because I have asked on two different occasions on Discord and the consensus was Spell Totem support doesn't modify minion skills hence there should be no change to damage.

**Comment by black-snow** [comment]
Also _increased damage_ for minions is not applied to MI in this fork.

**Comment by LocalIdentity** [comment]
Does not scale with cast speed anymore
