### ISSUE TITLE
Raise Spectre

### ISSUE THREAD

**Issue by dooley1023** [PathOfBuildingCommunity/PathOfBuilding#2222]
**Is your feature request related to a problem? Please describe.**
i have found that i cannot add multiples of the same spectre to my raise spectre group.
when looking at the calcs tab you can only get the one group for combined totals.
would it be possible to allow adding the same spectre multiple times to a skill group? or if I missed on how to add the same spectre multiple times?
**Describe the solution you'd like**
allow adding multiples of same spectre in the group

**Describe alternatives you've considered**
possibly adding a count of spectre next to the selected spectre to allow recalculations based on the number spectres in your group

**Additional context**
this came to light when I wanted to review how much dps was calculated for having 3 kiln mother spectres and I could not find a great way of doing this with out just simply tripling the numbers. being fairly new still I don't not know if the damage is directly multiplicative or not.

**Comment by QuickStick123** [comment]
I believe this is resolved by the introduction of the count field 
![image](https://user-images.githubusercontent.com/31533893/177724187-0e931c83-ad1b-402e-abf5-22dc46637bc3.png)
