### ISSUE TITLE
Build cost estimatation (enhancement request)

### ISSUE THREAD

**Issue by TheveninRDM** [PathOfBuildingCommunity/PathOfBuilding#2230]
Many players do not have an intimate knowledge of the cost/value of many build-required unique items. Streamers and build guide writers frequently update PoBs with each league but their (frequently video) guides will often feature outdated approximations of the cost to obtain required items in trade. Players who are unfamiliar with the current PoE market are also players who are likely to lack the resources to fix or back out of a build if they discover they cannot afford to gear it to a minimum level of functionality.

PoB has an opportunity to help these players and increase its utility to build authors by incorporating a feature that allows a user to "price" a builds displayed item profile. Less knowledgeable players would gain quick insight to the overall expense associated with a build and authors would be able to refer interested readers to PoB for current market information rather than having to continually update guides with market information that rapidly becomes out of date.

Certain items will always be difficult to price accurately: we've seen various attempts at machine learning pricing for rares but current iterations meet with limited success. Despite this obstacle, simply providing a user with a list of unique prices along with a best guess for rares (using trade filters that simply look for matching itemization without regard for magnitude, for example) would help prospective build users identify builds that are much too expensive to attempt. 

Exploring the various PoE trade and price macros (e.g. Awakened PoE Trade) might be a good place to start to see how other tools approach retrieving/estimating prices responsibly via the trade API and 3rd party websites.

**Comment by Wires77** [comment]
This is outside of scope for PoB, which focuses on optimizing builds.  There are many other price-checking tools in the community, and we're not interested in duplicating that functionality within PoB or maintaining calls to external websites at this time.

**Comment by TheveninRDM** [comment]
"This is outside of scope for PoB, which focuses on optimizing builds. "
Optimizing a build in a trade league, by most any meaningful metric, necessarily involves interacting with the market unless the player chooses to deliberately restrict their options (in which case they'd likely be playing on SSF). 

"There are many other price-checking tools in the community,"
I completely understand not wanting to duplicate functionality of an item price checking program, but that isn't actually what the request was for. It was for a feature that helps estimate the cost of implementing/optimizing a build. 

"we're not interested in duplicating that functionality within PoB or maintaining calls to external websites at this time."
Providing uses with a feature that aids in estimating the cost of a build doesn't *necessarily* involve interacting with the trade site or external programs at all. It could be as simple as providing a render of a (list of) link(s) that user could use to expedite the process from within PoB. PoB is not an item crafting utility but it does have features to help import/export item data from/to tools that do. 

I certainly won't pester the project again regarding this request, but I think that dismissing the entire concept as out of scope, out of hand, in under an hour might be missing an opportunity. Either way, thank you (all) for your consideration and for a very useful project!

**Comment by Firedrops** [comment]
> There are many other price-checking tools in the community, and we're not interested in duplicating that functionality within PoB or maintaining calls to external websites at this time.

Please show me even one tool that lets you put in a whole inventory at once. Even if it only prices unique items.
