### ISSUE TITLE
Steelskin Buff can take 45% increased amount of damage helm enchantment isn't working

### ISSUE THREAD

**Issue by broncolor** [PathOfBuildingCommunity/PathOfBuilding#2238]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* The Helm Lab enchant, Steelskin Buff can take 45% increased amount of damage, isn't working in PoB. In the game, the guard skill can take 3,484 amount of damage, but in PoB, it is only 2,403 as it would've been if there was no helm lab enchantment.
* 
* **What were you trying to do?**
* get the correct the guard "health" pool in PoB.
* 
* **What steps will reproduce the bug?**
* using a helm with that lab enchant
* 
* **Does it reproduce every time?**
* yes
* 
* **Provide a build code:**
* PoB Community Fork 1.4.170.27
* 
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by ALT-F-X** [comment]
I see this bug as well. It's something to do with the mod parser not recognizing the language the enchantment is using. For future reference any line that is red text means that PoB is not processing/supporting it. No need to equip the enchanted helm and go the "guard pool".
