### ISSUE TITLE
Molten Shell Guard + Buff Effect Enchant

### ISSUE THREAD

**Issue by turokix** [PathOfBuildingCommunity/PathOfBuilding#2245]
* **What happened?** The Guard value in Effective "Health" Pool in Calcs considers the Guard of Molten Shell to be part of the "Buff Effect," despite it only affecting the armor buff. As such, it shows a Guard of ~23k instead of ~9.3k.
* **What were you trying to do?** Examine the increase in Guard value from the 150% increased Molten Shell Buff Effect enchant
* **What steps will reproduce the bug?** Equip a helmet with Molten Shell Buff Effect with an active Molten Shell gem
* **Does it reproduce every time?** Yes
* **Provide a build code:** https://pastebin.com/fNt0nSgh

**Comment by ALT-F-X** [comment]
The damage mitigation property of Guard skills (shield) is considered a buff, and is increased by the enchantment. This is known because of the line "Regenerate 1.5% of Life per second while affected by a Guard Skill Buff" from the Adamant notable and the skill Steelskin existing, as it has no secondary effects.

PoB is matching game functionality.

**Comment by turokix** [comment]
I suppose I should have provided screenshots for this - the issue I'm running into is that the guard is taking the 'Buff Effect' as  applying to the amount of armor, such that it gives 0.625 guard for every point of armor, rather than 0.25. This does not match game functionality, as it follows the same 0.25 guard per point of armor even with the enchant - the armor value itself is simply buffed and increases the guard by the extra armor.

I am unsure if the maximum guard value is affected as I do not have enough armor in-game to check it.

Without helmet:
![ArmorOne](https://user-images.githubusercontent.com/4359484/108873105-dc9b3400-75c8-11eb-897e-b9002fa9711a.png)
![BuffOne](https://user-images.githubusercontent.com/4359484/108873111-dd33ca80-75c8-11eb-8623-332bca9ca2fb.png)
![PoBOne](https://user-images.githubusercontent.com/4359484/108873568-40bdf800-75c9-11eb-8531-56ab913c0922.png)

With helmet:
![BuffTwo](https://user-images.githubusercontent.com/4359484/108873108-dc9b3400-75c8-11eb-8204-f6fe0dc8aa55.png)
![ArmorTwo](https://user-images.githubusercontent.com/4359484/108873110-dd33ca80-75c8-11eb-94d3-6237049ba2f9.png)
![PoBTwo](https://user-images.githubusercontent.com/4359484/108873573-41ef2500-75c9-11eb-9301-54b651d09139.png)

**Comment by turokix** [comment]
Something that I'm also noticing now, looking at the screenshots, is that the Buff Effect is also affecting the "75% of Damage from Hits is taken from the Buff before your Life or Energy Shield" (0.75 taken from guard -> 1.00) which, while I cannot test in-game, is almost certainly not accurate.

**Comment by ALT-F-X** [comment]
I don't see why not? That ability is provided by the molten shell buff, the enchantment says 150% increased buff effect. Every single stat provided by the buff should be increased. If they just wanted to increase the armor amount the enchantment should be "150% increased armor buff effect".

**Comment by Wires77** [comment]
@ALT-F-X https://pathofexile.gamepedia.com/Molten_Shell#cite_note-buffeffect-1 Buff effect only affects the armour value for molten shell.

**Comment by ALT-F-X** [comment]
That is citing a post from Mark in 2012, 7 years before Guard skills were a introduced. I'm not convinced.

**Comment by turokix** [comment]
I'll get together with my friend using the build in the pastebin to test the max guard size and if he takes any life damage while the buff is in effect later. If the armor is indeed the only part affected, GGG should probably reword the enchant.

**Comment by turokix** [comment]
Through testing, the maximum of 10000 guard holds even with the enchant. SOME damage was taken to life while the guard was up, so it is at least not 100% taken from the buff before life. I can't attest to it not being 76-99% before life, however.

**Comment by ALT-F-X** [comment]
So the only bug we know for sure to fix that's a problem in PoB is the guard exceeding 10,000. The damage portion sounds very suspicious to me that GGG just has guard skills implemented incorrectly but no really way of knowing.

Are you sure in your testing you were only taking physical damage hits?

**Comment by turokix** [comment]
The Armor/Guard ratio is also clearly not matching game functionality.

As for the ratio of damage taken before life, I just did a separate test (without any summons/DoTs to simplify things) and took physical damage to my energy shield from a goatman while Molten Shell was still active, so I can attest that it is at least not 100%, and the amount of energy shield to guard shield lost was close to 75% (~210 guard lost for ~70 energy shield).

**Comment by ALT-F-X** [comment]
Good to know. Thank you.
