### ISSUE TITLE
Implement support for Belt enchant "Withered by you have -6% to all Resistances (enchant)". "-6% to all Resistances" also works if Withered is applied by your totems

### ISSUE THREAD

**Issue by Hareide** [PathOfBuildingCommunity/PathOfBuilding#2253]
This was also registered as a bug in the "orignal" POB: https://github.com/Openarl/PathOfBuilding/issues/2075

Hope you are already working on implementing belt enchants.
Just wanted to let you know that this belt enchant also works if you use "Spell Totem Support" with "Wither", to apply "Withered". I have tested this ingame.

Belt example:
<PRE>
Rarity: Rare
Anarchy Shackle
Stygian Vise
--------
Requirements:
Level: 66
--------
Sockets: A 
--------
Item Level: 81
--------
Enemies Withered by you have -6% to all Resistances (enchant)
--------
Has 1 Abyssal Socket (implicit)
--------
+44 to maximum Energy Shield
+97 to maximum Life
+44% to Fire Resistance
+43% to Lightning Resistance
+30% to Chaos Resistance
14% increased Damage (crafted)
</PRE>

The workaround im using for POB, is to edit my helmet from "-9" to "-15". 
(The -elemental resist dosn't do much for my build, so I ignore it :))

<PRE>
Rarity: Rare
Horror Horn
Lion Pelt
--------
Quality: +20% (augmented)
Evasion Rating: 543 (augmented)
--------
Requirements:
Level: 70
Str: 92
Dex: 155
Int: 48
--------
Sockets: R-R-G-G 
--------
Item Level: 85
--------
Summon Skitterbots has 20% reduced Mana Reservation (enchant)
--------
+8 to Evasion Rating
20% increased Evasion Rating
+33% to Chaos Resistance
8% increased Stun and Block Recovery
5% reduced Mana Reserved
Nearby Enemies have -9% to Chaos Resistance
+70 to maximum Life (crafted)
--------
Hunter Item
</PRE>

Ty for all your hard work!
POB: https://pastebin.com/7cFYsPpG
POE account name: Hareide
IGN (ritual): HarRitRaidCaustic

**Comment by pundm** [comment]
Fixed in 1.4.170.28
