### ISSUE TITLE
Champion ascendancy node for Scion still mentions Impale in tooltip

### ISSUE THREAD

**Issue by NafenX** [PathOfBuildingCommunity/PathOfBuilding#2255]
The Impale chance from taking Champion ascendancy as a Scion was removed and the stat is gone from PoB but the tooltip explanation of how Impale works is still there.

**Comment by Wires77** [comment]
This is actually a PoE bug, not a PoB one.  We get the tree data from the game, and if you load up an Ascendant in game, that node will also have the impale reminder text.

**Comment by Wires77** [comment]
Bug reported here https://www.pathofexile.com/forum/view-thread/3068657
