### ISSUE TITLE
Feature Request: The admiral

### ISSUE THREAD

**Issue by Ho11ywood** [PathOfBuildingCommunity/PathOfBuilding#2257]
Hey, 

Was playing around in POB and I noticed that the unique modifier "Elemental Damage you Deal with Hits is Resisted by lowest Elemental Resistance instead" present on the unique "The Admiral" is not currently actually calculating based on the lowest resistance. 

If this is actually an already implemented feature that simply isn't working in my build please let me know and I will write up some bugs showing inconsistencies where the dmg isn't getting calculated correctly.

**Comment by Regisle** [comment]
pastebin of build?

**Comment by Ho11ywood** [comment]
https://pastebin.com/Ky0VnH56

So its supposed to be implemented? Cause its currently acting like it isn't.

**Comment by Regisle** [comment]
I didnt look at the item beforehand, no the text is red so PoB doesnt parse it correctly yet sorry
