### ISSUE TITLE
Ensaring Arrow debuff stacks do not work correctly for multiple stacks

### ISSUE THREAD

**Issue by CarefreeCloud** [PathOfBuildingCommunity/PathOfBuilding#2260]
When selecting "Ensnaring Arrow stacks" beyond the 1st (2 or 3) the damage accounted does not further increase.
1 stack correctly applies 20% increased at target, but 2 and 3 stacks do not apply 40/60% increase respectevly as they should

Possible bug reason is incorrect getting or aplying of "Multiplier: Ensnared Stack"
![image](https://user-images.githubusercontent.com/10196681/108989668-e85d2800-76a6-11eb-94f7-0627d2579c30.png)
Calc tab has 3 stacks selected for above screenshot
![image](https://user-images.githubusercontent.com/10196681/108989811-0fb3f500-76a7-11eb-91ff-e649c4d24545.png)

**Comment by CarefreeCloud** [comment]
Also a full pastebin in case a reproduction is trickier than i described https://pastebin.com/CxPGYfjG

**Comment by pundm** [comment]
But is it really? I checked https://pathofexile.gamepedia.com/Ensnaring_Arrow and the gem information states:

> Each Snare applies 40% less Movement Speed to Normal or Magic Enemies
> Each Snare applies 30% less Movement Speed to Rare Enemies
> Each Snare applies 25% less Movement Speed to Unique Enemies
> **Ensnared Enemies take (15-20)% increased Projectile Damage from Attack Hits**
> Maximum 3 Snares per Enemy

So its a fixed % damage, regardless of amount of snares, right?

**Comment by CarefreeCloud** [comment]
Huh. I guess I somehow failed to recognize multiple times that inc. dmg does not state "Each snare"
No idea why offer ensnaring stacks in cals menu? Would not "Is Enemy Ensnared" checkbox be better than?
Or is there some window with enemy estimated movement speed i've never stumbled upon?

**Comment by Wires77** [comment]
> Huh. I guess I somehow failed to recognize multiple times that inc. dmg does not state "Each snare"
> Any idea why offer ensnaring stacks in calcs menu for user? Would not "Is Enemy Ensnared" checkbox be better and simpler than?
> Or is there some window with enemy estimated movement speed i've never stumbled upon?

The count box is mostly for future-proofing.  If there's a mechanic that arises later that is based off the stack count, we already have a stack counter in place as opposed to just a checkbox.
