### ISSUE TITLE
Error on loading POBCF, cannot get to the application / tree / skills / etc.

### ISSUE THREAD

**Issue by BobDaBilda** [PathOfBuildingCommunity/PathOfBuilding#2267]
[First screenshot](https://i.imgur.com/1ysNhNn.png)

[Second screenshot, if I hit escape on the first.](https://i.imgur.com/Vbz0L9K.png)

Every time I open POBCF, I get the error shown in the first screenshot, if I hit "Enter/Escape to dismiss" I get the second screenshot. I've been getting this error since either Sunday February 23rd, 2021 or Monday February 24th, 2021.

I've attempted the following to resolve it, none of which has worked: Reinstall with the most recent installer. Reinstall with a slightly older installer. Reinstall Windows 10 (I do this about once every 4 months, so this was about the right time to do it anyway, not a big deal to do so). 

I have not tried any of the following: Installing any prerequisites that are not installed by the installer (I assume there aren't any, but if there are, I don't have them installed). 

I have attached a dxdiag, and I try to be fairly quick on responses to threads, so let me know if there's anything else you need (logs, screenshots of anything else, etc.). 

[DxDiag.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6040245/DxDiag.txt)

**Comment by ppoelzl** [comment]
There might be a problem with the build you're trying to load. Could you post your build XML as well? By default, it should be in your `Documents` folder -> `Path of Building/Builds/<your build>.xml`

**Comment by ppoelzl** [comment]
On second thought, try deleting the `Settings.xml` file in the `Path of Building` folder. Seems like it got corrupted.

**Comment by BobDaBilda** [comment]
Actually, you saying the first one solved the issue for me, I had a build that was a 0 byte which was the build I was trying to load, but removing it from that folder solved the problem. Thanks!

I've also deleted my Settings.xml to be sure.

**Comment by ppoelzl** [comment]
Great to hear! No problem.
