### ISSUE TITLE
Update issues.

### ISSUE THREAD

**Issue by SirTwsted** [PathOfBuildingCommunity/PathOfBuilding#2274]
The POB v1.4.170.26  says that there is an update.  Yet the latest version is the one installed.  (view attached image)
Not to mention my previous problems with updates getting hung up and not self-updating when updating POB.

![POB update problems](https://user-images.githubusercontent.com/15247713/109292631-aa701900-77f8-11eb-82b2-b9994b4be173.png)

**Comment by zao** [comment]
There is a v1.4.170.27 tag from five days ago which your PoB is noticing, the list of releases on the right hand side in the repository is not the ground truth for this.

There's not always a downloadable release made with a zip/installer with a new version, sometimes you've got to start from a slightly older one and have it auto-update.
