### ISSUE TITLE
Hydrosphere damage conversion priority issue

### ISSUE THREAD

**Issue by Psaakyrn** [PathOfBuildingCommunity/PathOfBuilding#2275]
Hydrosphere damage conversion isn't set as priority over non skill damage conversion.

Expected: With Avatar of Fire active, Hydrosphere should first convert damage  from Phys to Cold/Lightning (skill gem priority), then have the resulting Cold/Lightning damage converted by Avatar of Fire.

Current Build: With Avatar of Fire active, Hydrosphere calculates both at once: With single element, it converts Phys to Cold/Lightning at 100% and Phys to Fire at 50%, hence converting at a 67%:33% ratio (the resultant Cold/Lightning is then converted to Fire at 50% as expected). With both elements, it does Phys to Cold at 100%, Phys to Lightning at 100%, and Phys to Fire at 50%, hence converting at a 40%:40%:20% ratio (the resultant Cold and Lightning is then converted to Fire at 50% as expected).

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.28
