### ISSUE TITLE
BlackFlame + Burning Arrow Debuff interacting incorrectly

### ISSUE THREAD

**Issue by DarkenTheSun807** [PathOfBuildingCommunity/PathOfBuilding#2277]
Literally everywhere I have read Burning Arrow's debuff doesn't get affected by BlackFlame's ignite damage taken as chaos effect because it isn't ignite. That should mean the ignite is taken as chaos and the debuff is still taken as fire (I believe). That said, the debuff dps seems to increase when I lower chaos resistance or apply wither to the enemy and isn't affected at all when I lower fire res.

I'm pretty sure this is incorrect. If not, please enlighten me.

**Comment by PJacek** [comment]
Burning Arrow doesn't apply burning debuff since 3.16
