### ISSUE TITLE
Energy from within not updating Passives Descriptions

### ISSUE THREAD

**Issue by Creonox** [PathOfBuildingCommunity/PathOfBuilding#2278]
Energy from within doesn't update the description of passives in radius from Life to Energy Shield + it doesn't calculate in the values into your Max ES.

**Comment by PJacek** [comment]
Please fill out the bug report template.
Jewels do not change descriptions in PoB. Instead, they modify the mods obtained by allocating a passive. I see no problems with Energy From Within.
![efw](https://user-images.githubusercontent.com/18018499/109391221-49d6fe00-7916-11eb-8c75-8f7cb19c4657.png)
