### ISSUE TITLE
Correct Ballista Totem Base Placement Speed

### ISSUE THREAD

**Issue by EarthBounder** [PathOfBuildingCommunity/PathOfBuilding#228]
Ballista Totems have base placement different to other totems

https://www.reddit.com/r/pathofexile/comments/f9k14o/questions_thread_february_26_2020/fisu2x7/

**Comment by Quotae** [comment]
Implemented. I saw Mark's comment before I saw this issue and was already working on putting it in. #229

**Comment by LocalIdentity** [comment]
Added in 1.4.162.1
