### ISSUE TITLE
historic jewels

### ISSUE THREAD

**Issue by rip97000** [PathOfBuildingCommunity/PathOfBuilding#2280]
for historic jewels it's awesome that you added replacing modifiers.  however, since it would be pretty hard to figure out all the combinations for all the locations for all the variables in the jewels, can you leave it open for us to enter in what is showing up for us?

i found this jewel that has 20% increased strength (5% on 4 different nodes)

Rarity: Unique
Lethal Pride
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 86
--------
Commanded leadership over 13413 warriors under Kaom
Passives in radius are Conquered by the Karui
Historic
--------
They believed themselves the greatest warriors, but that savagery turned upon their own.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

just incase you would like it, here is the stats for this
5% on devotion, endurance, holy dominion, and overcharge
in addition, the other nodes are as follows
righteous army - !0% increased effect of fortify on you
redemption - regenerate 1% of life per second
divine wrath - 10% reduced enemy stun threshold
Divine judgement - 20% increased stun duration on enemies
divine fury - 12% increased totem placement speed
smashing strikes - 20% fire resistance
sanctum of thought - 8% increased warcry buff effect
sanctuary - 12% increased totem placement speed
Divine fervour - 12% increased totem placement speed
righteous decree - 20% increased burning damage
light of divinity - 5% of physical damage from hits taken as fire damage
singular focus - regenerate 1% of life per second
arcane capacitor - 5% of physical damage from hits taken as fire damage
amplify - 4% increased max life

**Comment by Wires77** [comment]
I'm not sure what you mean.  This is already a feature in PoB.  If you right-click on a notable within the Timeless Jewel radius, you can set the mod that the jewel adds.  Below is an example for adding % strength.  If you're referring to having PoB "know" what each node ends up being based on the mod on the jewel, that is not data GGG supplies, so it's impossible to do without a lot of manual effort.

![image](https://user-images.githubusercontent.com/1209372/109431035-15bd1500-79ca-11eb-8818-220437b475cf.png)
![image](https://user-images.githubusercontent.com/1209372/109431047-21a8d700-79ca-11eb-961d-b69c313564fd.png)

I'm going to close this issue, but if I misunderstood your request, feel free to reopen it with additional information.
