### ISSUE TITLE
Glorious Vanity - node allocation saved between POB's

### ISSUE THREAD

**Issue by jix91** [PathOfBuildingCommunity/PathOfBuilding#2282]
It seems that the allocation of passives on glorious vanity jewels is applied to all pob's globally.
If i allocate 5% aura effect on one pob, with a glorious vanity - a different pob will have the same 5% aura effect if the same glorious vanity is in that socket. Is this intended behaviour?

**Comment by Wires77** [comment]
Yes, this is intended.  If a glorious vanity (or any timeless jewel) is the same seed on it, it will have the same mods on the same notables.
