### ISSUE TITLE
changing skills bugs out

### ISSUE THREAD

**Issue by AlsoInteresting** [PathOfBuildingCommunity/PathOfBuilding#2291]
Whenever I change skills (any skills), a global error appears:
https://postimg.cc/K46V9kJ4

Build: https://pastebin.com/MVfYLgRb

Version: 1.4.170.27

**Comment by Wires77** [comment]
Your default gem level is set to 0.  If you set that value to 1 or higher, it should work again.

**Comment by Wires77** [comment]
Fixed by #2298

**Comment by AlsoInteresting** [comment]
Thanks. That fixed it.
