### ISSUE TITLE
"+# to Skill gems" affects Predator support

### ISSUE THREAD

**Issue by SyrupyLamp** [PathOfBuildingCommunity/PathOfBuilding#2295]
How to reproduce:
1. create new build, add a skill group with Raise Zombie and Predator support
2. add a new item (amulet), edit the item to have +# to skill gem mods (+2 to all Minion skill gems, +2 to all Intelligence skill gems)
3. observe that Raise Zombie is now at +4 (this is correct)
4. observe that Predator support is also at +4 (this is incorrect)

Tested in-game, global +# to skill gems does not affect support gems, like Predator.  This includes +# to minion skills, +# to intelligence skills, and +# to all skills.

<details>
  <summary>PoB code</summary>
eNrFW21v2zgS_tz8CsLAAnfYTWzqXUGyC-e1BpLUZ6ft3X0pGJm2taFEV6KTehf7329IyrGS2PFY20P7wbXoZ145HM6M2qPfvmWCPPCiTGV-3KIHnRbheSJHaT45bn28vdiPWr_9unfUZ2r6YXwyT4X-5de9d0fmOxH8gQugaxHFiglXn5ac3C_AacZyNeUyv2a_y-JSjo5bNzLnLXLH8lGqlk-JYGV5wzJ-3BomQNwirEx4PjpdrVtgxtJ8KJN7ri4LOZ8ZsQ8pf7yWI8D0rvsfBrc1oWleFwo6vzvqC7bgxVAxRUr4OG51E5U-cICC3Ks0SxVwZGIO7IJWewMJeItN-PsatrMFe8Yy-NwOH844Hz3B6AENAy_s-FHkuL7744n6BT8fj7lx2WmRqtMpyxOEWbtir-dCpTOR8qKmob-J4v0r5rSzkf2tVEyc9YfbFbFIidjkz6mangjwJ4qvRvcmeao4Gt6XaSnznbRGgU9ldpfmSL2X4O7DZDv4muXsVJYr5_mbY16tdtnZiBrwr3XgRtwZ_4bjVgduxPVyheNWB1Lf36zdg1Qmw22TfJWOV_EcvJUwkkON7eUJjunHvOAlLx5qpz9AEvR5AWlZYY6ZJhzwCUdaesV5Mr2E7D5giuOiCxNZ2jkai3KOBq5xjo8k2ME5mvC5c-iB-xZ4R_ec57yYLIbTlIsR6s5JDuskKG_VCZAbXSfZ1aIHVtaPjR-9bY2F47adQ-YGghF_cYk40Xck6Rfyd31vih3pukUm5wVyEy0YZXV_uijTBG4KU5gM-Gie4PLS0_1_LR94BgFvCgkowFaxvIn0REDphi0DgK0QO1F0lWLJ_ZkcTfhOQnaiuEgL8FaZ1m62_QCB_gB14CmbYW5ZfZ6wAlZotICrdDJVOdTweCkvSPC2TJksdzBmBUeL6MtHQE5161Huhr5mq_t_Y_K9KHj-xwLN_xkcJeA8H80LHXpoGS8pUGK2dzn2t62dC_U7zoHjuHEchx3H20T8vLvoHEQ-NBed5ecmqle1OXUi9yD2HeoGXhxGb9OtqdRfIddW6kgp6-v2HYhfV_E72reuTH8FXlfTI-U8qznj2KNvAddf-muhb1_2r0jeLF_eRCN1whYiR20z49DfetlMFsosnjKRlIZxL5_NFcnNgKK8T4X4ks-zO9202r9Xd2EdmaVl8uVuPh7rqUULVCrMqOX84uL89Lb36bwiGXJzI5NECsFmJR8dt_JUtEgKX4Za2BCqkEQh0NAfV6d4O_YzK5IihTy0HaoPHEJVkwm243Tbj4DBPjDBsS66Xcy43vcS56WqCNiONSkEgbMnHmOWySsYp_OELRC4p7BGYM8F76ZC13IYP11D-NoiEIOGoqxI7-YKFVEm_yA00N0fwqx6GkFoaittBN-qF9mOrEofTDxBnYv0_Rkfc4hS1Ak1p_6W3fO8ymfL3HVkjkdJSkhqlzwrTxZwXVxoT724QJ4BjluqmEPKGvExmwu9_q85E6laVDJX61d2KmxWy6l8HM5nM8tJH8kSvH11ZX_pClUx0WKOW2MmympWa3Q0M19bvphnY4EZ_Ap2p2XocTW7E9pwq90LAo3V7N4dgYAKeynkHRPOUkENqy6J5yJqv1SLA5aCj_-rXQSiquG302mRCc96eoe4YiOmWLunwJy2tqltmMI3Q7skNaw1xevVmipGi7rOdGnlV-u0nskJxu1Pa_r6eukUffXoHrGSR9YIfGFc-22nIU1_2vczztQ0Y8V9zfTqVyv-QibzUjdM39vgfsFBLbk82nY7zGmwh0B_vS04J8wGjSGiVQjCQ_1lhJYOsnK4uUs9hYhct0UUENdee1C3eqNhwdaN5yPI76MbTWcW6iuEw1dZDLnW3ncdB05vonl1oeJwzvSn0bQHi2V7BpxBzbL9iUFRqJOBfjwYjUqrl31f0oUegdg0bZe1Mk4Y-LFV6N077yeS5knBGWw54QZJ5JjcyHz_dF5AiGgWJRkXMiMLyIzEessq315p_z3N-TDeYM5y2ECqxmJpkReFUM5WFrl1i55T_F-13rgJtp5-8j4NVro6dV0z9i3N5hnR-B_kX3MEybLZW6ocxd6TxhZSQpJngtBn-luyH-NjMzQg9qa1I5yl8sCfdpba_xz8RJQkL9E_Ki6qecp6vcMgpE96U9covo5kvfL1BZtrjj4Oriy7qVKz8rDdfnx8PJhBPpZj_i0V_CCR2VL1fZOd93VOa3fhz4n-6B4fW9ZLTkf2Lewyl9mnJwto4NAI_KTsxVD1YWtwlPodBC6gkethcJ4fuQic40Bzi8B5URDGGH4upQhY7HUwXnGDAGWt63k4a2kcYfg5XoyxwnVDHyPWpQFOvSB0fATO92mMCRYv7kQYHHVpiMGFcYASG0SRg8KBHSg3By5mO7yO1-mgtqODEUudgLooM9wYtbsQLQFmd2M_wkQB9WKU3DiMQ4x6kRdixDpxSB1UMNM4QGU0t-OjcE4UoTJa6KFyixtHMUpuEGDsoKFDcRkSnYNC3I3goeR6EM-YcPEpJEmMvR0oATC4yHNRYQ8KhqikFkS4GysMUHZAMYrKLhQYYnAeDVBx5bio7e2Ero-6KmNUkgxiisqR0CCtiRZoFFfVDjxAT2jaR9006i83UtlKSy8uH0xL-Snlj6TkrEimQ1XoWcUfUmb_MT2kHn68h6b4ms2qllr_Vg1O3Gpsopg6S6FoL8zIZ9nbauC_n4bUpt2umlf9fciVGRvMSz7kUJWOPnM2k7lZ1nLsQBqAZkZUVZoDVkAjfUgG3cH53g1orQF7J2LOSR_0F6SbzQVXe6cFG0NxeUi0JnvQWo_Tb4e6aXzrYTgfYx6qOdAh6ewZNwz410MShnu9bCbSJFXlIaF7fyo2KQ8LXkJLmvBfMpazv_4sWD7hh50D_69_eNG-H_zzWScIEGLeDPCCmVmZHvXv_ezoutqMMXTfy4QgvVxxIdKJdradUujZRrkOWjVMNZAOlGs5GmhViFFIv_jyW5WXq-GDdqudLAi5fCFgXbuKu6eXBnYzN25kff_q_CyM0OEjm5Hu3aIsoWOrQn3NqVpH-pLMwZG9jTqRUpUNFVpnyxalTrhQO5JcCFbeExelkrNOJbeZe3FOcL4TmddMyaCZtKC5N5vE05YdeM9FxtWugtZEUtBEzpbwuxTyQf8TgN0Zu81PEW0iz2sWC7RZ5Hnbtwfj2F3Zrguvhoaj8o7fQJ8GOdDdJma0IPZl2I7bt97LjeLLb0KEOpKYjWhkp9_YrU6DfQ-anSS3Wfi6u0eZ1zztN4hp2tj5LiYgPAyogdp_o_hB7mTzXQgaRGXzbfgb4YJNyZoWeWrw0AaeG-gpvtMkxTiN3dswXeD3s4k5LsJPtPk2eI295TexBnNemgf5FpU2tZDtqoc08wozKDD_gk3m43QCiKP2y__W9z_lJBIp
</details>

**Comment by Me1v** [comment]
I would add that should not increase level of Predator support these sources:
- +1 spell skill gems (Weapon)
- +1 minion skill gems (Weapon)
- +1 int skill gems (amulet)
- +2 level of all minion skill gems (Necro Ascendancy passive)
- +# level from Empower gem
Not sure, may be there is exists something else
BUT Should work:
- +# to level of Socketed Minion Gems (local mod from helmet)
