### ISSUE TITLE
Summon Phantasm when granted by Soulwrest does not count as an "active" skill

### ISSUE THREAD

**Issue by rcpd** [PathOfBuildingCommunity/PathOfBuilding#230]
This was broken a long time ago in PoB but I'm hoping it can get some attention, it used to show up under the Main Skill tab when Soulwrest was equipped. It does show up as a sub-skill when it is supporting an active skill (with or without Soulwrest) but then there are other things that are clearly broken (https://github.com/LocalIdentity/PathOfBuilding/issues/231)

**Comment by rcpd** [comment]
Just came to add I'm 90% sure this bug was introduced when the wording of the phantasm gem was changed in 3.7 but looks like you're all over it, awesome work guys!

**Comment by LocalIdentity** [comment]
Added in 1.4158.1
