### ISSUE TITLE
Arcane surge

### ISSUE THREAD

**Issue by KRZYSIOX** [PathOfBuildingCommunity/PathOfBuilding#2302]
Hi,
By a mistake I just found out that Hierophant's "Gain Arcane Surge when you or your Totems Hit an Enemy with a Spell" mod is absolutely dead , POB doesnt calculate that u can have arcane surge with this node. This means you cant calculate your damage with arcane surge without putting arcane surge support into POB .

**Comment by Nostrademous** [comment]
Is it "red text" in PoB?

**Comment by andrewbelu** [comment]
It looks like the arcane surge buff does not work at all, regardless of source.

**Comment by KRZYSIOX** [comment]
Ok , thanks for help .Temat: Re: [PathOfBuildingCommunity/PathOfBuilding] Arcane surge (#2302)Data: 2021-03-05 2:47Nadawca: "Andrew B" Adresat: "PathOfBuildingCommunity/PathOfBuilding" ; DW: "KRZYSIOX" ; "Author" ; 
It looks like the arcane surge buff does not work at all, regardless of source.

**Comment by andrewbelu** [comment]
> Ok , thanks for help .Temat: Re: [PathOfBuildingCommunity/PathOfBuilding] Arcane surge (#2302)Data: 2021-03-05 2:47Nadawca: "Andrew B" Adresat: "PathOfBuildingCommunity/PathOfBuilding" ; DW: "KRZYSIOX" ; "Author" ; It looks like the arcane surge buff does not work at all, regardless of source. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

That was my mistake, a configuration error on my end. Looks like only Hierophant ascendency is broken as request. It is red text in POB.

**Comment by LocalIdentity** [comment]
Added to list in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/384
