### ISSUE TITLE
Thread of Hope Basic Jewel Socket Pathing

### ISSUE THREAD

**Issue by Felixoo7** [PathOfBuildingCommunity/PathOfBuilding#2307]
When claiming a basic jewel socket near scion within the medium band of a Thread of Hope it forces it to path there. In game you are able to claim the jewel sockets without pathing.

**Comment by andrewbelu** [comment]
Can you actually allocate a jewel socket with it? 

A developer in this thread said (in Jan 2020) that this was intended: https://www.pathofexile.com/forum/view-thread/2708742/page/2

Essentially you can put two threads of hope connecting each other then deallocate the entire path to the first one.

**Comment by pundm** [comment]
Good find. Solved.
