### ISSUE TITLE
Summon Phantasm Support scales with stats of active skill gem it supports and not itself

### ISSUE THREAD

**Issue by rcpd** [PathOfBuildingCommunity/PathOfBuilding#231]
This is another very old bug, but to get Summon Phantasm to show up at all it has to be supported by an active skill (https://github.com/LocalIdentity/PathOfBuilding/issues/230) and then when it does its readout in the "minion" portion of the skill pane is only affected by modifiers to the active skill gem and not itself even if that skill has no interaction with minion modifiers.

**Comment by rcpd** [comment]
Just came to add I'm 90% sure this bug was introduced when the wording of the phantasm gem was changed in 3.7 but looks like you're all over it, awesome work guys!

**Comment by LocalIdentity** [comment]
Added in 1.4158.1
