### ISSUE TITLE
Application turns black

### ISSUE THREAD

**Issue by bcbisaillon** [PathOfBuildingCommunity/PathOfBuilding#2314]
Can someone please tell me how to fix the issue where whenever I click off of PoB onto a full screen application (like PoE) PoB turns black? It's really annoying trying to check my tree and having to hover over PoB. Previous versions of PoB didn't do that, It's been like this for a few patches.

I'm running PoE in borderless full screen with multiple monitors on an AMD graphics card.

**Comment by ducyc** [comment]
I have an AMD card too, a temporary workaround (for me) is to disable desktop recording. Maybe needs some looking at, it looks like AMD thinks the program is a fullscreen app and doesnt render it when another application is full screen.
