### ISSUE TITLE
Berserk does not get levels when being linked to Empower

### ISSUE THREAD

**Issue by Gnomiro** [PathOfBuildingCommunity/PathOfBuilding#2318]
As described in the title: Bererk seems to be not recognized as active skill gem although ingame it gets level while being linked to empower.

PoB: https://pastebin.com/JgP8DRTQ

**Comment by ALT-F-X** [comment]
It wasn't gaining levels because you had Berserk disabled. Here's a photo from your build of it correctly gaining levels when enabled.

![image](https://user-images.githubusercontent.com/5727264/111164269-eaaaf780-856b-11eb-9b56-4cc3cb9fb203.png)
