### ISSUE TITLE
phys combine total damage don't add impale damage when bleeding is present 

### ISSUE THREAD

**Issue by jekoder** [PathOfBuildingCommunity/PathOfBuilding#2322]
https://pastebin.com/bSnE9S57 

in this pob where weapon has a attack has chance to cause bleeding mod, the combine total damage is not adding impale damage into it causing the combine total damage to be less than impale damage(5.28m(average+bleeding) total vs 5.33m impale damage), and if you remove the bleeding mod from weapon you get 9.5m total(average+impale)

**Comment by ALT-F-X** [comment]
Great bug report. Impale was missed when we added `Combined Total Damage`.

**Comment by pundm** [comment]
fixed in v2.0.3
