### ISSUE TITLE
Incorrect calculation of flask effect modifier

### ISSUE THREAD

**Issue by LordranKnight** [PathOfBuildingCommunity/PathOfBuilding#2323]
50*1.82=91
![X(1~B}P 15467K6QDQJCI U](https://user-images.githubusercontent.com/80196119/110235724-99e43f00-7f6c-11eb-95a0-988b925e01bb.png)

**Comment by pundm** [comment]
Can you please provide a build link?

**Comment by LordranKnight** [comment]
https://pastebin.com/WRRQAEWg

**Comment by Nostrademous** [comment]
Is this a case of Rounding of either Effect Modifier (81.6% rounded to 82% for display purposes) or of the product of multiplication?

**Comment by LordranKnight** [comment]
91 in game 90 in POB
