### ISSUE TITLE
Chain Hook Anomalous Quality incorrectly shows it as working

### ISSUE THREAD

**Issue by 77x0** [PathOfBuildingCommunity/PathOfBuilding#2328]
Chain Hook Anomalous Quality is supposed to increase the base radius but it does not. It is incorrectly shown as blue text (implemented) when it needs either fixed or changed to red text (not implemented)

**Comment by pundm** [comment]
Please always provide a build link/pob

**Comment by ALT-F-X** [comment]
I can confirm this is an issue. The SkillStatMap `active_skill_base_radius_+` is not correctly getting applied. This affects ~50 abilities. The clearest example for anyone to see is any aura normally gains radius as it levels up, set the aura as the active skill and notice how the radius stays unchanged no matter the level as you change it. This is a serious issue simply by the amount of skills affected.

If I add `"BASE"` to the `SkillStatMap` it starts working for active abilities but still doesn't work for Gem Qualities. I can't find any StatMap with a skill modifier with the BASE quality so I not sure if that's even the correct implementation.
