### ISSUE TITLE
https://pastebin.com/azYTQ1x1

### ISSUE THREAD

**Issue by KpywoBN4** [PathOfBuildingCommunity/PathOfBuilding#2338]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pundm** [comment]
Can you please add valid information to your issue/suggestion.

**Comment by LocalIdentity** [comment]
Open another issue when you state what the issue you were having was. A pastebin link does not help us
