### ISSUE TITLE
Ambidexterity Applying while Wielding a Two-Handed Weapon

### ISSUE THREAD

**Issue by Sathen834** [PathOfBuildingCommunity/PathOfBuilding#2339]
The node Ambidexterity shows that it is a damage increase while wielding a two-handed weapon. As far as I can tell, it is the only duel-wielding node with this issue. Obviously it should have no benefits for two-handed weapons.

**Comment by Wires77** [comment]
A two-handed weapon is still considered a main hand weapon, so it still gets the 50% attack damage boost.  This is working as intended.
