### ISSUE TITLE
Resists from socketted Malachai's artifice not showing up

### ISSUE THREAD

**Issue by Psaakyrn** [PathOfBuildingCommunity/PathOfBuilding#2343]
Malachai's Artifice is supposed to grant resist based on the colour of gem socketted in it, but doesn't in PoB.

Sample: https://pastebin.com/He8JJbgs

**Comment by pundm** [comment]
Thanks for your report. It's not been implemented yet. If a text is shown in red, then it's not parsed.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4981
