### ISSUE TITLE
Node power implementation improvements for build optimization

### ISSUE THREAD

**Issue by traviswdev** [PathOfBuildingCommunity/PathOfBuilding#2350]
Great job on this tool to everyone that has contributed. We love it. 

I have a few feature ideas that would make it even better. 

Feature 1: **reverse node power implementation**
- helps you decide how to get rid of the weakest nodes on your tree to spend the points elsewhere
- only highlights the nodes you currently have selected
- a checkbox to toggle on/off - "selected nodes only"
- weakest nodes are brightest (or not? design decision here, doesn't really matter, could also provide a menu toggle for this)

Feature 2: **multiple node power selections, weighted**
- if for my character I want max health, combined dps, and some other thing I currently have to switch between each of these individually with the node power drop down and manually decide which nodes I think are best. This process is tedious, inaccurate, far from optimal, and very error prone, me only being able to hold as information as my puny human brain can handle
- solution: allow us to select multiple items in the node power list
    - highlight in one color (not two like offence/defence) based on weights
    - by default weight equally when selecting multiple items in the node power list (50/50 for 2 selections, 33/33/33 for 3, etc)
    - have a "weights" button next to the dropdown menu that brings up an input form where we can decide the weights of our selections, i.e. we think max life should be weighted 80% and combined DPS should be weighted 20%, or whatever your heart desires
- this feature also combines very nicely with Feature 1, allowing you to optimize your build even further

Feature 3: **side by side node comparison**
- just a helpful tool
- a "node comparison" button
    - click the button, then click some nodes, then click the button again
    - a side by side comparison pops up on screen with the values that these nodes provide your build, probably in a table/spreadsheet type layout

Dream feature:
- You could bring all of this much further, too. With Feature 2 implemented you could even have the program create a "best" build (based on weights) for a given set of gear, gems, class choice, and level. Yeah, the processing needed here might be kinda ridiculous. Yeah, the program would probably take a while to write and optimize. But it could be done.

**Comment by Nostrademous** [comment]
See planned enhancements by @Wires77: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2250

**Comment by pundm** [comment]
Implemented in v2.0.0
