### ISSUE TITLE
flickershades are chaos damage

### ISSUE THREAD

**Issue by davoodinator** [PathOfBuildingCommunity/PathOfBuilding#2351]
if you look at their poedb entry or try them ingame you'll notice they are doing purple (chaos) damage.

i'll try to do this locally to my spectre.lua but it really should be changed from phys to chaos for pob

![image](https://user-images.githubusercontent.com/3622816/111238898-51a0ce80-85b5-11eb-9653-deb013402418.png)

**Comment by Wires77** [comment]
See this file if you want to fix it locally: https://github.com/Wires77/PathOfBuilding/commit/d5e71af0c3589781075094a101ffc5d0dfad3eff#diff-b0e5bb7b39187e18918bf4dccf348886ca741d833dc13e82e392bbea241f36d8

Looks like they convert 50% of the damage to chaos
