### ISSUE TITLE
Divergent arcane cloak buff effect applying to the shield amount

### ISSUE THREAD

**Issue by AlbertVong** [PathOfBuildingCommunity/PathOfBuilding#2353]
**Issue:** Divergent arcane cloak alternate quality gives buff effect, which should only apply to the amount of flat lightning damage/damage taken from mana spent before life ratio (specified on the skill gem). More detailed official GGG post here: [https://www.pathofexile.com/forum/view-thread/2961033/page/1#p23582656](url)
**POB:** https://pastebin.com/misQxH7p
**Details:** Arcane Cloak should only guard 66% of mana spent from the skill, and AFAIK this number should not scale regardless of arcane cloak buff effect. The only thing that should increase this number is either levels in arcane cloak, or the helm enchant "Arcane Cloak spends an additional % of mana". In the POB, one can see that the guard skill portion of arcane cloak is greater than 66% of the mana pool, even without the helm enchant or additional levels into arcane cloak.

**Comment by pundm** [comment]
Fixed in v2.0.0
