### ISSUE TITLE
Do not work calculations of gem's alt quality property of Anomalous Dread Banner

### ISSUE THREAD

**Issue by Me1v** [PathOfBuildingCommunity/PathOfBuilding#2354]
* **What happened?**
There is a anomalous Dread Banner gem. It has alt quality property:
 -Nearby Enemies deal 0.1% less Damage for 1% of quality - Do not work in PoB
 -3% less Skill Effect Duration for 1% of quality
 * **What were you trying to do?**
 I'm trying to compare EHP with different versions of Dread Banner gem. Seems like "Nearby Enemies deal #% Damage do not count in EHP.
* **What steps will reproduce the bug?**
Just enable aura of Anomalous Dread Banner gem with quality. 
* **Does it reproduce every time?**
Yes
* **Screenshots:**
https://i.vgy.me/n4vgYz.png
https://i.vgy.me/Vh8yXj.png

**Comment by Wires77** [comment]
Fixed by #4274
