### ISSUE TITLE
Anomalous/Divergent Predator support damage calculation do not work

### ISSUE THREAD

**Issue by Me1v** [PathOfBuildingCommunity/PathOfBuilding#2355]
* **What happened?**
Alt quality gems (Anomalous/Divergent) Predator support gem do not work in pob. 
* **What were you trying to do?**
Trying to switch type quality of Predator support. Default quality is working. Anomalous and Divergent - not.
* **What steps will reproduce the bug?**
Pick some damage minion gem (Zombie/Skeleton, Spectre, etc) and link it with predator. Change quality of gem to Alt quality.
* **Does it reproduce every time?**
* Yes
* **Screenshots:**
https://giant.gfycat.com/ClassicSaneCanvasback.webm

**Comment by QuickStick123** [comment]
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2887
