### ISSUE TITLE
Mortal Conviction reserving life of the only aura it should allow to use without reserving any life

### ISSUE THREAD

**Issue by UnrealNine** [PathOfBuildingCommunity/PathOfBuilding#2360]
* **What happened?**
* ANY aura + Mortal Conviction reserves life no matter what, when apparently it shouldn't
* **What were you trying to do?**
* Use "Pride" as my only aura with Mortal Conviction allocated, so it would reserve no life
* **What steps will reproduce the bug?**
* Allocating Mortal conviction, activating any aura (Pride in this case) in the skills tab
* **Does it reproduce every time?**
* yes
* **Provide a build code:** 
* eNq9W21T4sgW_jz-ihRVe2u3LmK_J_HqbiG-7ogyoOPMfJlqoYFoSDAJOMzW_vd7OgkQEbTNeu9MFYbOc177nNN9OmHvjx8j35qqKPbCYL-Ca6hiqaAb9rxgsF-5vjredip__L6115LJ8LJ_MPF8fef3rQ976bXlq6ny9ysukCUyGqjk85wV_Q5jYxkkQxUGTXkXRidhb79yEQaqYt3KoOcl829dX8bxhRyp_crhRPlenFQsGXdV0Gss75z4sufJJIwq1kh6QSfs3qvkJAonY1C7Yk099dgMewA8a7Yu21cF2V5QlA26f9hr-XKmok4iEyuGj_1KHVwgB-pQjuATuEl_AqyIjbFTswV1XYQYreysJ-6MleotiHBN2ML5f2NbkTrq91U38aaqEXlJYyiD7tISvoluDZbWyEvo5sRPvLHvqaig2kb-p8_YC7YJexUm0j9sdRZQxplNajajjDscvUIXJgs6tAl54INHixIwRgy5NQQSXLxZQkb3NDgEIoRCwri2LVy60WU3XjJ8JlYQlzK35ghsc5eKl2jPBoGXqCKxYVRq4lboxWFQgnju0hK-aoSjWy9YcTO1ObFrtutwByPnNdL6dPBWV9UjJS_7WQq0oVJM4mU8bwzOpgxkI4yXgUPxxlxMooIPN_qtrR6KSMw32nqofixhLzIsIu2NDjgLEoMUA3ZFIHtBvWmYQCF_PafOvX6hYrqCvFDOursafRZ0C5HxIuPrIFKxiqaFOviSiKckLRXBIrK0FqMXZbXVQAUFsKgJ-qKkc6W6wxNYjEAQ1LklKWGstjlBdNS97tbUWxpa9BZ6iedT_V-EbtJ8I9FRoKLBrDP0lN8z1L1IYmRDkcDQliLJ222ayrgY4Ryzlw3K8EVbyOZJVlDzgaKnVpY_9H4UrSi80yu-_zayejQKJ1GhwL5odYY2M7o1nMVeFxaOdKVsq96k-6SGkI3ldbF3aYZTNYKkTfc-sKEr7DHI5mp14MN20NR-YO37b6KoJ4ns3h-GvYF6k5A3URx7Ebgs9grL0Tbnr6MvYevakOPXBTRCnVemApZoYwHn3mCYBNAfmEtZITG3ZSjDeFWMMIEbi2iFj4Ac6q4mfhu6KZcL9saF_ThSwc_ZKn9mBC8KYJtrY28S6dBblcFNKYpiMqK9nbTt01dno3EYJelgQ_rdOGV5FowniRWkDVt87_n-92AyutWdQvZXt2o7z5AjL-5-v530-7qBq4AyUdp9Hh0fHzWuzj4f5SQdlVYTqxv6vhzHCjq6vvRjoPDgsqPFdaCGdhMjPCwR-YbeBH0jo27kgRNNwLoVMVI57e9MkLrvMgLCrEhfmTvsajZWOgJiU5_l1cwEnXY9RsisTTEzMG2HzKZBdeXMCLnYOhihj3xV93y9SJl5rQnhna1vZnhYbSLvdpIYRlu6_zbSQ-87jQwsbvaMNM52FEa8802XCTav72axBsu58Wwcqr6CKDbM5rRKXMl7FeQ1cF7v9tIUiq0YCuGJGsUHM-h5j7XXVrrgJ4D9ShJNgHdP9eXE1-OfJtL3ktl-JfD84vh5driWjsbD8LEzGY8zTjptY_D7-Xl2p-4nORMtZq5-ZpzWMT0yq6cbrPR7akF6bubLWy1Dn_rJW1-bnmm3QqCxmt2HPRCQY0_88Fb6ZOGs_CyQoIo1UKMz7WuVyJ5M5M5ZAmrtaN12UnZwdSSjZPgwAbeCCXpMEzwbbMEAsKw8EYnnSj5kNp-lyZ56bTGml-oli6W9K2bqBUhvc9eIbnpBepDZmYxGIcxkCypfIuNRFjRrHZHOlKEbFnN5rDclfVhgCn6o6-hMIul3fDnKoSV9sNFgLdcK-5aW_M4mpa3M02agYFyOWwt6XxNTEdZchlVc79_P2INokqS6PDexcOt9DVsyfmdjDpXs-bPF8vbMotX772tWxt16urq-n3HZ3uUqzDYmz2xbuf2-pmXMrSS0ituirBq-Wqcza00rtUbv_A94vstk5NW_o7x45HUb0ZOsKQy-r_dzzpZmvfOedrSl78-gW3lqyJPR97VkznppyjKI8qt0a3IVQeWT2RSmhDjfDsCX4sM1rQEsrwF0XnqBRA5xqxy7dpURF-MqF5TDgGsLUaWMObQqGHfsqiCOW6U2JaLKGSZ2FVMbsyoVNtKfHMMA4VWOHO4AieOQKndcgquU2BRVMWcAIUCCqhQJF64RwjBuE4SrNtC42AYwc0G6sJnGUqRRDuVV4ThMM8UC9AA9q4IjyqpEEJdVmcOoAwKQDbpyLEA116Vgg83h0-GMwYDWgdvEdgFOwByOXAEQzhxeZYLbmoEA9gzUcKrMpmCtTeAmFUAPagFzm4HyYBkCcgHagyMQYCm1QYJDEQGdHQFqERvRKuEupVWKGZgF_oK7AiB2lVKstUCOVpTZ2p_IdcDZAjxSxdgBB1CXa59h7Vbm2AJ0J2AOXGMEtFSAOzgB9oQ5ggPQ1qTM1UYKzGjVZVoDcLQAzRDMCwOInlAE9MBW-wQMBqsJYaAHBjO1l7CWp9UGZ1Jwg9C3IDbANdo8Cp6tElcbJqhNqFYO5CIOjiMcYoUyAX7BoArQcAcBCUQDQRAHRNigB3hXswf1YGuWQMgWHh9jmj8Z1iHK8upz1IPur3ehozXP4-v2eXrxYZgk43h3Z-fx8bE2lskw7Ksfnq9q3XC0MwY2kAnbaYZua0E7dfh3UP_UqDfGF8dHJAjcx0B8kSfx9x_nJ3-etH8mF9OLbx9bX-v88KBDTx6meMa9e-eGhEe97YvLj_fNH_Xp1zvEvNaJ__lh_Pn47mRy5TZbrd73wXiURIhcTk637xC9Y83m8OsR6lB72wmc7jdyTrBzh-qPBw_8tP0DH97NzoI2-jR96MvH9vXg4Yaf9kc_v958dP2rL9G0-c0mTXZyG4gmH4Y4PPcvpfTI4TS4u_hiT5OHh0_X3Zuj4fntJ3GdJK0_zxN5cv9tHE4ejsh1Y3B-VQftf9xftZwO-zK4qPce42G_4d2MXWT376K66hLx8duX4ew-Fu0Rql_as_bN0G_L0ZH9uL-fOnpn7um97Nl7nLk9_5ZWED1TWIBt0DklWfHMD8zW4CDikAFOQC4xExzUJWqAIxCwJvwglWzXhB_F2AAGKWjiFSqEkbUEkpOY4LDrGPHT6WiiH4UyaoLDwmg2YDkQJjgOa5JJtLi2a5sEHxHYRKyAwmfiFgHF1SSmoIKbxBRDUJlNcAwL12g2kJFYDIuLkRnUNUo1CBYTftzljomXYR0xkgtzi0z4EYfZRrOLieMYJRF2hRE_IYz87CLHJAzSHdgShzcnr-uYxAGGLZSJfrBbMwtn2LCZFCuMOCVG_mNGcmHnxUzmjWOokkb5QYyKFYH9DjLKD7PizFxhhnP0C2Im1Q8LbGaHCQzDFhYZrR2CmvCzXWHETrhG7KC7MGKnu5vnOOiplrsd-ALtU9pp6f5KX1yEiUrv6cH5l7T7-uypRytWMuoOO0mkm-yfYTj6qh-HClaD7QXmGIl096CPcE-VTJpyvDhN1eD8AFjkx7-JTA69fl9F6eH1vDfUwC96pRc1Dh7m0Fy4kB7pUXXaseZtoL7uqCQ9BZ3EqqO6YdC7UXIcBulw4cxYQ62pjDwZZKevXm9xANyG4WS2a11fnH26Ptq6GkZK9vQ54mk4VluNyBvFYWD9qR6Vv_U5Y7FrdUbQtlpt6FuXY03V8yajlcFz_eBxZQx6glnxRvaQT_WsBYKsyM1eANvNANBHb52Nxr7X9RIYQ1t_5Zbt4r8vA39myezZjNXKmoTY8oKiwgs42Qwv2rLA0834gjULONsMX_VA8V5mq9WVgXWrrLrvh12pnfPoQQs0SWBQnxbAXAeZ05LQmoWTKO22tv6KZDBQu6jG_97-laBtjH77RSO08Ud--iKGBDekz2H0-VWcpkQz7LU1nZVSQ67UeBYi85fT0pOSzZFE1kZSPfnpRd6_IB7j_8TWoRf35RQUhTgAFeo_1DIgWpGyaA3jGlqONSYRpEWyNjgWHPJnJDCGtvK03rXa24v_W2nCtdXDrmXzYtDgYhQQ_ovVXRznNaU3siDyTr1k699Ej6RMdEZkIkCX_IDR0kdHxfAruL_e68XWrwTmgFD-m2bzKyTyNnHRb6sH2EVdnnNAfBu45Bw4cLDXcViS_YrJNhYw7V7QhVSOQd3sdRcrfTy99dTaroTSkR1h6rB6YndWS7KgeDlO6Ly4bkSwVxH8Wax1_HD-RkGuSmF5mL_klFfBFypgsdit49l5lGOrfjuLY_Bnvois2UWuI10lI2Zkz6x4gjoIQygX5RRaZ8srSh0oP3kjybEv43uLGqlE1qlEy7nXzAnknchYOSVFOWmivDfxKxO8Lp5emYFT5Y9U8lZBayJJlJHzSvid-OFUv_70dsa0fBbhMvJYuVjA5SKPvT49Jo59K9t14VXScKO6w0voU6IG0tfE9GZW9p7MG6dvvZdLxRcvQ2SUkiYTUcpOXtqtpMS8i3KZRMuFL317lLHyZb9ETOPSzqcmAcFMQCXU_gebH8OZLD8LokRUlp-GfxAupiVZ0xpmjTm0hOd0Y2y2E3hzodjo3pLlwnw-y5hDDfyEy08DK-0tXsYak3wpH-SvqFQfTfw1a1vWc0LLmJ4Epmds6WvwYdD3Bs_ebtdNpqffL03fMgbvV6zbMPSVDPITvOcvxENzuvLzgNcoxpHXy38AvHyBvnl2sZ45sPV9Bf10ZCwAqJ7_oOA50d7O3At7O6u_Gf8vTGn0eA==

* **Screenshots:**
* 
![image](https://user-images.githubusercontent.com/80979778/111824502-96df3c00-88e6-11eb-828e-90a35e7dd9f1.png)
![image](https://user-images.githubusercontent.com/80979778/111824527-9f377700-88e6-11eb-9105-46c2a7d624a4.png)

**Comment by pundm** [comment]
Hi, thanks for your report. Red text always indicates that the feature is not parsed/implemented yet.

**Comment by QuickStick123** [comment]
Mortal conviction was removed closing.
