### ISSUE TITLE
Alternate Quality Phantasmal Purifying Flame not accounted for in calculations

### ISSUE THREAD

**Issue by VoxMaro** [PathOfBuildingCommunity/PathOfBuilding#2364]
When using a Phantasmal Purifying Flame, the quality modifier does not change the effect of Consecrated Ground on predicted DPS or Life Regen, which it should as a result of "% increased Effect of Consecrated Ground".
In Calcs, "Inc. Crit Chance" under the Crits category is unchanged from 100%, and Regen under the Life category remains 6%, both the regular effect of Consecrated Ground, and unchanged by the modifier from quality.
As comparison, other effects that change Consecrated Ground such as the Divergent Purifying Flame and Inquisitor ascendancy are taken into account.

Bug Reproduction:
Check both "Are you on Consecrated Ground?" and "Is the enemy on Consecrated Ground?" effects in Configuration.
Add Purifying Flame as a Skill, add Quality and switch Variant to Phantasmal.
DPS and Life Regen remain unchanged, as are the source stats in Calcs.

Pastebin: (Has all Purifying flame variants as skill groups that can be enabled and disabled to show differences)
https://pastebin.com/kwa5e6Mv

**Comment by QuickStick123** [comment]
Closing in favor of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2887
