### ISSUE TITLE
Skills always cover pantheon gods

### ISSUE THREAD

**Issue by UnrealNine** [PathOfBuildingCommunity/PathOfBuilding#2366]
* **What happened?** 
* Skills always cover the pantheon gods when you try to select one
* **What were you trying to do?**
* Read the effect of different pantheon gods
* **What steps will reproduce the bug?**
* Add one skill to the build and select it to see its average hit/dps/mana cost etc. on the left panel, then try opening the pantheon gods options and place the cursor over them
* **Does it reproduce every time?**
* yes
* **Provide a build code:**
* **Screenshots:**
* 
![image](https://user-images.githubusercontent.com/80979778/112025227-414c9e80-8b35-11eb-9f60-eb36e63ca564.png)

**Comment by piebypie** [comment]
Yep still happening
![image](https://user-images.githubusercontent.com/90422406/169225632-eb0175e8-9094-43cc-b5c2-f6729b72dcfc.png)
