### ISSUE TITLE
Elegant Hubris not showing the right passive in POB

### ISSUE THREAD

**Issue by Limiter23** [PathOfBuildingCommunity/PathOfBuilding#2367]
Following Item placed in the outer middle left socket:

Rarity: Unique
Elegant Hubris
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 86
--------
Commissioned 81180 coins to commemorate Victario
Passives in radius are Conquered by the Eternal Empire
Historic
--------
They believed themselves better than the past, but that confidence brought about nightmare.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
--------
Corrupted

POB with Necromancer is showing now Passive "Sanctum of Thought" in the south of the Hubris' circle in POB. 
This is wrong!!

Must be "Superiority" (15% increased effect of Non-Curse Aura Skills) !

Please fix. Thanks.

**Comment by Limiter23** [comment]
Here is a link to the build so you can watch: https://pastebin.com/Ym0hRdBw

**Comment by Wires77** [comment]
It's impossible to know how nodes are affected by timeless jewels without testing them all in-game, so PoB doesn't do that automatically.  If you'd like to change the node, you can right-click it and select Superiority from the list instead.
