### ISSUE TITLE
CLEANSED THOUGHTS

### ISSUE THREAD

**Issue by Galahen** [PathOfBuildingCommunity/PathOfBuilding#2371]
Anointing Cleansed Thoughts is ok, but if you use the Resistance Penality dropdown to set act resistances penalities it doubles what ever the number became, so if you have 40 chaos resist, act 10 will be -20% chaos resistance will become -40%. Will post a video later. 
To reproduce the issue, just set any passive tree chaos resistance with no penalities, anoint Cleansed Thoughts, then set the penality and look at the counter.

**Comment by ppoelzl** [comment]
When you post the video, please also take some time to fill out the bug report template you've deleted from this issue.

**Comment by Wires77** [comment]
This is working as intended
