### ISSUE TITLE
Vaal Right Fire is not enabled..I'd like to know why.

### ISSUE THREAD

**Issue by InHyeokJin** [PathOfBuildingCommunity/PathOfBuilding#2373]
I'm having fun with the build Blade Vortex
but I'm the only one who can't check Right Fire..
Tell me the reason,

https://pastebin.com/r5vWMVHa

**Comment by Wires77** [comment]
You have to enable it here in the Skills tab:

![image](https://user-images.githubusercontent.com/1209372/112699107-1e81f900-8e59-11eb-8645-abd146878cff.png)

**Comment by InHyeokJin** [comment]
네 체가 체크하면 pob상에서는 DPS가 상승하는데 
닌자사이트에서는 적용이 안되더라구요 ㅠ
저만 빼고 냉기블볼 448케릭 전부 다 정의의화염이 활성화된 디피로 적용되서 나오거든요..

**Comment by Wires77** [comment]
I can't read Korean, unfortunately, but it seems you're asking about why poe.ninja doesn't enable Righteous Fire.  Here is their FAQ page if that helps you:  https://poe.ninja/builds/pob-rules

Righteous Fire is listed as "In Progress"
