### ISSUE TITLE
Calculations assume same Doom number for curses

### ISSUE THREAD

**Issue by notablackbear** [PathOfBuildingCommunity/PathOfBuilding#2374]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* If you are using Doom, entering a Doom on curse into the configuration page will apply the same Doom to all curses in build, even when they are not self-cast.
* **What were you trying to do?**
* Calculate the damage of Hexblast when multiple curses are applied, but only one with the highest Doom is applying an Ignite, the others will be lowering resistances. However, their effect is inflated due to them being applied with on hit sources or triggered sources like Asenath's Gentle touch, trigger socketed spell crafts, Vixen's Entrapment, etc.
* **What steps will reproduce the bug?**
* Use a self-cast curse such as flammability, a different triggered curse such as Temporal Chains, and a damaging skill such as Hexblast. In the calculations page, Temporal Chain will show increased curse effect that is not correct.
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
https://pastebin.com/pt6jZTyP
Temporal Chains is not self-cast but shows a 30% increased curse effect from Doom in configuration page. This also gets wrapped into the ignite duration, which should be 7.7s but shows as 10s.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![image](https://user-images.githubusercontent.com/71364995/112706058-fbf2de80-8e5e-11eb-9d6d-cdfdc7a0149b.png)
![image](https://user-images.githubusercontent.com/71364995/112706078-23e24200-8e5f-11eb-8e91-f433e3969605.png)

**Comment by QuickStick123** [comment]
Doom has been removed this is no longer applicable afaik.
