### ISSUE TITLE
Brain Rattler "Shock Enemies as thought dealing 300% more Damage" modifier not being calculated when "Is enemy shocked" is ticked.

### ISSUE THREAD

**Issue by SBurmasS** [PathOfBuildingCommunity/PathOfBuilding#2377]
As the title says, this mod on the item is not being accounted for what so ever, if you even edit the item and remove this line your damage will not be effected so its not being calculated at all. 

I wouldn't have made this ticket if I didn't know the calculations behind this, Idk if putting 300% more Damage on a random item would suffice in its place since I don't know the if it's the same mechanic. So asking for some help and lessons :D
Thank you.

**Comment by LocalIdentity** [comment]
This mod is taken into account in the shock durations breakdown box on the calcs page. Shock is not auto-applied unless it comes from a dedicated source like skitterbots or the elementalist ascendancy which are unaffected by the  "Shock Enemies as though dealing 300% more Damage" mod
