### ISSUE TITLE
Add a tickbox when adding skills to only show gems that are at or below character level.

### ISSUE THREAD

**Issue by lewtorz** [PathOfBuildingCommunity/PathOfBuilding#2378]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I'm trying to plan out a leveling build but it takes to long to find the best gem setup.

**Describe the solution you'd like**
Add an additional tick box that allows default gem level to be capped and only show gems available at the characters level.

**Describe alternatives you've considered**
It would be nice if this was added for gear and stat selection on gear as-well.

**Additional context**
This would be an awesome feature especially for those making build guides for the PoE community.

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/221758897-0fbc3545-b63b-4d8f-b26b-9259f782321d.png)
Was added at somepoint and refined in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4724.
