### ISSUE TITLE
Pob does not take into account the property of gloves: Offering to the Serpent

### ISSUE THREAD

**Issue by Fikus123123** [PathOfBuildingCommunity/PathOfBuilding#2380]
Hello. Pob does not take into account the property of gloves: Offering to the Serpent
Legion gloves

"50% reduced Maximum Recovery per Life Leech"

**Comment by Regisle** [comment]
It does, you may misunderstand what that stat does, it limits the amount of leech in an instance, which only affects the maximum duration of the leech

![image](https://user-images.githubusercontent.com/49933620/112931268-5ba10080-9163-11eb-89dd-d6899b2958d9.png)

**Comment by Fikus123123** [comment]
Oh yeah. Sorry, you're right.
