### ISSUE TITLE
Error in "OnFrame" attempt to index a nil value

### ISSUE THREAD

**Issue by k0rn0ux** [PathOfBuildingCommunity/PathOfBuilding#2411]
When either opening previously saved PoB from https://pastebin.com/USDHDMq3 or importing it I get following error:
![image](https://user-images.githubusercontent.com/43177620/113541816-a4d1d400-95eb-11eb-89a7-a0679d7d9348.png)
PoB version is 2.0.0

**Comment by Wires77** [comment]
This is fixed in the dev branch, should be in the next hotfix.
