### ISSUE TITLE
i've just updated my pob, and have script error

### ISSUE THREAD

**Issue by vietato** [PathOfBuildingCommunity/PathOfBuilding#2412]
![pob error](https://user-images.githubusercontent.com/81954612/113551056-06676200-962f-11eb-88fa-68513bdfcb2e.PNG)

i've just updated my pob and got some issues like screenshot 

plz fix that ASAP.

**Comment by BassOfBass** [comment]
Yeah it cannot into non-english characters in path. For the time being I recommend moving the folder to a path with only english characters until it gets resolved.

**Comment by Wires77** [comment]
> 
> 
> Yeah it cannot into non-english characters in path. For the time being I recommend moving the folder to a path with only english characters until it gets resolved.

This would work.  You can also download the updater executable from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding-Launcher/suites/2420517328/artifacts/51622277

Either way, this has been fixed in the latest hotfix, so I will close this issue.
