### ISSUE TITLE
Crash when adding a second socket group to view full DPS of a two part-skill

### ISSUE THREAD

**Issue by josec87** [PathOfBuildingCommunity/PathOfBuilding#2414]
* **What happened?**
* Program crashed
* **What were you trying to do?**
* Add a second socket group of Vaal Detonate Dead so that I can view Corpse Explosion + Spell with the full DPS option.
* **What steps will reproduce the bug?**
* Create new socket group. Add second Vaal Detonate Dead gem. Click to try to add the first support gem. Program crashes.
* **Does it reproduce every time?**
* Yes. I've tried 3 times.
* **Provide a build code:**
* https://pastebin.com/snwwyjWT
* **Screenshots:**
![pob_crash](https://user-images.githubusercontent.com/747418/113578929-e1212680-9623-11eb-9536-9988461b44b6.PNG)

**Comment by QuickStick123** [comment]
Fixed sometime recently
![image](https://user-images.githubusercontent.com/31533893/175757422-5bfdc5ed-1a7a-4fe6-8cfd-00c5544e2e25.png)
