### ISSUE TITLE
PoB working extremely low in Office PC Core I5- 8gb ram Windows server 2016

### ISSUE THREAD

**Issue by diegodgo87** [PathOfBuildingCommunity/PathOfBuilding#2415]
Version doesn't matter, I tried numerous versions and installed many times, the software works but is extremely low, for example changing from tree to items i have to put the cursor over "items" button and wait till light up then click.
Do I miss something? Perhaps is windows server missing something? I had PoB in this PC back with Windows 10 and it worked fine.

**Comment by ppoelzl** [comment]
Unfortunately, server operating systems are not supported, since PoB is a desktop application.
