### ISSUE TITLE
Scaling Items/Enchants that Add New Skills

### ISSUE THREAD

**Issue by andrewkhunn** [PathOfBuildingCommunity/PathOfBuilding#2416]
**Is your feature request related to a problem? Please describe.**
Items/enchants which add new skills currently aren't able to be scaled via the new +/- toggles for Full DPS calculation. Specifically in my build: Soulwrest (unique staff) and Commandment of the Grave (glove enchant).

**Describe the solution you'd like**
I assume the new scalar +/- inputs need to be added to the skills added by items/enchants themselves.

I'd be happy to provide more information to get this added.

Thanks for this great tool!

**Comment by Wires77** [comment]
Duplicates #2417
