### ISSUE TITLE
Add ability to scale gems from items

### ISSUE THREAD

**Issue by area** [PathOfBuildingCommunity/PathOfBuilding#2417]
Because Raise Spiders is not a gem, and is granted by an item, the 'gem table' is not present, unlike with other skills (e.g. Herald of Purity), and so there is no 'count' available to be incremented. This means that when doing the 'full DPS' calculation, only one spider is considered, when up to 20 can be summoned.

![screenshot-2021-04-05_14-58-11](https://user-images.githubusercontent.com/311812/113581700-6950fd00-961f-11eb-9f5a-41a15c6bf816.png)
![screenshot-2021-04-05_14-58-23](https://user-images.githubusercontent.com/311812/113581705-6a822a00-961f-11eb-8a0a-1dc36d6b73bc.png)

**Comment by Nostrademous** [comment]
Yeah, item-generated special skills do not currently have a counter. It is something we will need to add in a future patch.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2496.
