### ISSUE TITLE
nil value on runtimeExecutable

### ISSUE THREAD

**Issue by Shawak** [PathOfBuildingCommunity/PathOfBuilding#2420]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

Getting an error every time the app is trying to update.

* **What were you trying to do?**

Literally just starting the app. The problem didn't occur in previous versions.

* **What steps will reproduce the bug?**

Literally just start it.

* **Does it reproduce every time?**

Yes, also when I try to update manually using the "Check for Update" button.

* **Provide a build code:**

I am running the latest version, which should be 2.0.1, atleast the changelog.txt say so. I can't find a build code tho.

* **Screenshots:**

![image](https://user-images.githubusercontent.com/3829602/113585856-1120f780-962d-11eb-8909-8ca0baee70c4.png)

**Comment by Wires77** [comment]
Will you download this file and replace your `UpdateCheck.lua` with it?  https://github.com/PathOfBuildingCommunity/PathOfBuilding/raw/7f260ffa950c5dc9745063fbd33495b45c9a8437/src/UpdateCheck.lua

**Comment by Shawak** [comment]
I could do that buf the diff shows that the files are exactly the same.

**Comment by Wires77** [comment]
The UpdateCheck.lua you want to replace is in D:\Programme\PathOfBuilding\UpdateCheck.lua.

The one in the Update folder (as you've shown) is indeed the same, but when the app goes to replace the old one with the new one, it errors out.

**Comment by Shawak** [comment]
Yeah that worked, thanks!
