### ISSUE TITLE
Lost builds after update t0 2.01

### ISSUE THREAD

**Issue by GrumpyBear5** [PathOfBuildingCommunity/PathOfBuilding#2421]
After updating to 2.01 all my builds were lost / gone. Although I can see them in the folder.

**Comment by Wires77** [comment]
As a workaround, you can manually set the path to your build folder in the Options page.

**Comment by Tardly69** [comment]
Same issue but any builds with in the last year are gone, not in the folder at all

**Comment by GrumpyBear5** [comment]
Hi Trevor,

Thanks for the feedback.

Yes that seems to of worked for me.

Regards
Gordon

**Comment by Wires77** [comment]
> 
> 
> Same issue but any builds with in the last year are gone, not in the folder at all. Looked in all folders restarted ect nothing =\

Can you replace your SimpleGraphic.dll file with this one?  https://github.com/Wires77/PathOfBuilding-SimpleGraphic/suites/2423159651/artifacts/51694444  I believe this will fix your issue, and if it does I'll put it into the next hotfix.

**Comment by Tardly69** [comment]
> > Same issue but any builds with in the last year are gone, not in the folder at all. Looked in all folders restarted ect nothing =\
> 
> Can you replace your SimpleGraphic.dll file with this one? https://github.com/Wires77/PathOfBuilding-SimpleGraphic/suites/2423159651/artifacts/51694444 I believe this will fix your issue, and if it does I'll put it into the next hotfix.

Switched file nothing different, the files for the builds look like they were lost when the update was done

**Comment by Wires77** [comment]
This should be fixed with the latest hotfix.  If you moved your builds, you'll have to move them back to the original folder, sorry for the inconvenience.
