### ISSUE TITLE
Cast on Crit Trigger Rate calculation does not account for Barrage triggering it multiple times per attack

### ISSUE THREAD

**Issue by ForkOfTomorrow** [PathOfBuildingCommunity/PathOfBuilding#2424]
* **What happened?**
* Looked at Trigger Rate calculations on a CoC build that uses Barrage as the Trigger.
* Barrage can Trigger CoC on every hit, not just once every attack, however it calculates the Trigger Rate based only on the Attack Speed (essentially), resulting in a much lower Trigger Rate than what it actually is in game.
* **What were you trying to do?**
* I was trying to double check my calculations of Trigger Rates using PoB.
* **What steps will reproduce the bug?**
* Create a gem setup like: CoC - Barrage - [spell]
* Give yourself 100% crit chance and 100% chance to hit. (I made a bow with 5000 crit and accuracy)
* Check the Calcs tab for the Trigger Rate calculations.
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
https://pastebin.com/Cdn04ztm

**Comment by feafarot** [comment]
I think same applies for Blast rain as well

**Comment by QuickStick123** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/3fd00099-cfbf-4417-b4ae-3832aa4cfde3)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/f41f16b4-9b1d-4ee0-a5f8-fed1fd9f541a)
This has been fixed.
