### ISSUE TITLE
show node power colorations but optionally keep Power Report frame hidden (as it was pre 2.0.0)

### ISSUE THREAD

**Issue by grrev** [PathOfBuildingCommunity/PathOfBuilding#2429]
Prior to 2.0.0 there was a check box at the bottom of the window to colorize node power with a dropdown for certain criteria. This is now a separate frame that takes up sizeable amount of screen real-estate for the exact same functionality (you could already get per point values from the mouseover tooltips).

I'm requesting either an option or a way to minimize the current frame so that Node Power is visible without losing a quarter of the screen.

**Comment by lewho38** [comment]
Sorry for you but i try to do my own fork without this un-usable mess but they broke the entire legacy color system. Sadge. Guess i ll continue to plan build on the PoB 1.4. 
Devs => Please consider adding a  "return to legacy show node power" with a working node power system.
![image](https://user-images.githubusercontent.com/32401884/115306197-c09ab580-a167-11eb-8d96-6a7547aab3f4.png)
as you can see a basic blade flurry show only 5 nodes and the new power report crash

**Comment by pundm** [comment]
Please open a new issue and fill in/follow the template, so stuff that may be not working correctly can be looked at.
