### ISSUE TITLE
General's Cry crashes PoB

### ISSUE THREAD

**Issue by hntd187** [PathOfBuildingCommunity/PathOfBuilding#2433]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
*  I tried to use general's cry in a build with earth shatter, when I started to select a support I get the error below.
* **What steps will reproduce the bug?**
*  1. Create new build
*  2. Make skill with general's cry
*  3. Link with earthshatter
*   4. Attempt to add support
* **Does it reproduce every time?**
*  Yes
* **Provide a build code:**
*  It was a brain new naked marauder/beserker.
* 
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image. 
![image](https://user-images.githubusercontent.com/6778339/113721080-33faec80-96bd-11eb-9646-947b3eb5eca8.png)

**Comment by Nostrademous** [comment]
Fixed by #2426 when it gets merged.
