### ISSUE TITLE
[bug] Summoned Holy Relic's nova DPS scales from minion attack and cast speed, not player attack speed

### ISSUE THREAD

**Issue by rwjmiller** [PathOfBuildingCommunity/PathOfBuilding#2436]
# Reproduction steps:

- Start a new build
- Add Summon holy relic and any attack (e.g. cyclone) as skills
- Add both to the full dps calculation
- Go to the skill tree, view the power report, and select Full DPS mode

Nodes such as Death Attunement, which grant bonuses to minion attack and cast speed, but not minion damage, are incorrectly highlighted as giving a bonus to relic DPS. This is wrong because the relics don't cast their novas - they are triggered by the player's attacks.

I think other damage calculation modes are also affected, but I didn't test all of them.

# Suggested behaviour

Relics trigger each time you hit with an attack, up to the cooldown recovery limit of the relics. This seems like a good candidate for including in the full DPS calculation functionality, so if one or more attacks and holy relic are included in the full DPS calculation then the attack rate should be used to determine the trigger frequency.

Increases to player attack rate and accuracy (but not minion attack or cast rate) should increase the relic trigger frequency.

**Comment by Wires77** [comment]
Duplicates #187
