### ISSUE TITLE
Make thousands seperators ON by default

### ISSUE THREAD

**Issue by cakegod** [PathOfBuildingCommunity/PathOfBuilding#244]
PLEASE make this option ON by default!
Every time I see someone's screen with millions of dps and not this option ON it kills my eyes.

**Comment by pHiney** [comment]
It's hard coded to a comma, should we attempt to internationalize it ? Or just add a new option for a person to set their own character.

But i agree it should be set on by default.

**Comment by pHiney** [comment]
So setting the default is easy. I'll add a PR for it tomorrow night. Internationalizing it is much harder. The thousands separator works but the decimal point doesn't. So i'll leave that be for now

**Comment by ppoelzl** [comment]
Internationalisation is a moot point anyways without unicode support, and that's coming from someone who would usually write them the other way round.

**Comment by pHiney** [comment]
PR #252 applies.

**Comment by pHiney** [comment]
Excuse me for hijacking a conversation.

If we change the word Internationalisation to customisation, and assuming code was in place for new Options
![image](https://user-images.githubusercontent.com/4302241/75624382-c520a980-5c07-11ea-9916-2fdadd06b1b9.png)

Would you entertain changing formatNumSep to :
```
function formatNumSep(str)
    local sep = main.ThousandsSep
    local decPnt = main.DecimalPoint
	return str:gsub("(%d*)(%d%.?)", function(s, e)
		e = e:gsub("%.",decPnt)
		return s:reverse():gsub("(%d%d)(%d)","%1"..sep.."%2"):reverse()..e
	end)
end
```

As a kind reference example (for those that haven't seen numbers outside their own country) : (https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html)

This is an idiotic example, but it serves to show
![image](https://user-images.githubusercontent.com/4302241/75624440-3a8c7a00-5c08-11ea-9a68-478098a6c7f7.png)

P

**Comment by ppoelzl** [comment]
Added in 1.4.162.1.
