### ISSUE TITLE
Wise oak with balanced resistances

### ISSUE THREAD

**Issue by danieldefoe66** [PathOfBuildingCommunity/PathOfBuilding#2447]
Hi , I was trying to balance resistances to gain full power of wise oak , I realized with balanced resists , It doesnt add penetration buff for any of those elements . But as soon as I add %1 cold resistance to build, it adds the penetration buff 
https://pastebin.com/7nNpf1Qx
https://prnt.sc/116o3cj

**Comment by pundm** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1059 maybe?

**Comment by danieldefoe66** [comment]
mm , after looking for first 1-3 page and searching for '' wise '' , I didnt see that . sorry for dupe thread

**Comment by ppoelzl** [comment]
There is a search box you can use.

**Comment by ppoelzl** [comment]
Duplicate of #1059
