### ISSUE TITLE
Error when adding socket groups

### ISSUE THREAD

**Issue by Foeglas** [PathOfBuildingCommunity/PathOfBuilding#2448]
* **What happened?**
Error popup when editing PoBs with multiple trees, item sets, and gem links.
* **What were you trying to do?** / **What steps will reproduce the bug?**

1. Select any **Enabled** socket group without skill gems. It can be labeled (e.g. ---LEVELING---) or unlabeled (No active skills).
2. Click the slot directly under Gem name.
3. Hover the cursor over any gem in the list. This step triggers the error.
a) If the socket group was disabled, hovering does not usually trigger the error.
b) The error appears much less often after one gem is successfully added to the socket group, even if that group
is then Enabled.
4. Buttons light up behind the error box when hovered, but do not activate when clicked.
5. Enter/Escape causes the box to disappear and reappear when first used. It does nothing the second time, and step 4 still applies.

* **Does it reproduce every time?**
Yes, on these PoBs. Disabling all unused socket groups reduces the error popups but is not guaranteed.
I couldn't reproduce on smaller PoBs (no skill tree or items, 20-30 4L socket groups).
* **Provide a build code:**
https://pastebin.com/f9dfXYsA
https://pastebin.com/b7hmJWcB
PoB Fork version 2.03
* **Screenshots:**
![image](https://user-images.githubusercontent.com/78708601/113942653-29c91300-97cf-11eb-91ac-1440f0a1d97c.png)

**Comment by QuickStick123** [comment]
Unable to replicate. Is this still an issue?

**Comment by Lothrik** [comment]
I was able to reproduce the error described in 2.0.0, and no error occurred while following the exact same steps in 2.19.1.

Closing as this appears to be fixed.
