### ISSUE TITLE
Detect if flasks are non-unique

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#245]
There are some mods that only apply during effect of a specific flask type. Currently, there is only a check if a flask is active, but no way to check for its type.

**Comment by LocalIdentity** [comment]
Added support for mana and life flask detection in 1.4.169.1

**Comment by Wires77** [comment]
What other mods check for flask type?

**Comment by ppoelzl** [comment]
Some Maraketh timeless jewel mod, IIRC. Not sure, it's been almost a year.

**Comment by Wires77** [comment]
Found it, "Non-Unique flasks applied to you have x% increased Effect"

**Comment by ppoelzl** [comment]
Yeah, that's it.

**Comment by ppoelzl** [comment]
As of game update 3.15.0, Maraketh timeless jewels can't apply this mod anymore.
