### ISSUE TITLE
Barrage support gem dps tooltip increases/decrease when point blank is present.

### ISSUE THREAD

**Issue by QuickStick123** [PathOfBuildingCommunity/PathOfBuilding#2451]
Please provide detailed instructions on how to reproduce the bug:
1. Path to Point Blank
2. Add a bow
3. Set travel distance to 1-34 (dps increases) or 36 and above (dps decreases)
4. Add/Readd barrage (support)
https://pastebin.com/LcahnUpU
![BarrageBug](https://user-images.githubusercontent.com/31533893/113959788-d5717200-9866-11eb-88cb-53d86e3536be.png)
![Point Blank](https://user-images.githubusercontent.com/31533893/113959794-d7d3cc00-9866-11eb-9120-3247548f68bf.png)
![Point Blank2](https://user-images.githubusercontent.com/31533893/113959803-da362600-9866-11eb-8f1a-f369096dc652.png)
First seen at https://www.reddit.com/r/pathofexile/comments/mm8okb/found_this_interesting_bug_on_pob/

**Comment by Nostrademous** [comment]
Fixed by #2453 
Mirage Archer implementation which was adding / removing a new skill group every frame while you were hovering on a potential gem choice was a culprit. New implementation of Mirage Archer fixes this.
