### ISSUE TITLE
Cluster jewel does not appear in tree

### ISSUE THREAD

**Issue by frodon1** [PathOfBuildingCommunity/PathOfBuilding#2454]
* **What happened?**

When loading a build from pastebin, a medium cluster jewel socketed in a big cluster jewel does not appear in the tree.

* **What steps will reproduce the bug?**

Load a build from pastebin and display a specific tree in the passive trees.
The medium cluster jewel MC1 socketed in the big cluster jewel LC1 does not appear in the tree.

* **Does it reproduce every time?**

The bug always reproduces.

* **Provide a build code:**

The following build reproduces the problem: https://pastebin.com/ubfN0D0J

* **Screenshots:**
![MC1](https://user-images.githubusercontent.com/6490878/113998423-57f33500-9859-11eb-93ca-30574606df86.PNG)

**Comment by PJacek** [comment]
Medium cluster jewels with 5% curse effect do not exist any more. You can edit the item or create a new one.

**Comment by frodon1** [comment]
Thanks !
