### ISSUE TITLE
Norton antivirus detected a heuristic virus in executable

### ISSUE THREAD

**Issue by Ashenbacken** [PathOfBuildingCommunity/PathOfBuilding#2458]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

**What happened?**
![Screenshot (7)](https://user-images.githubusercontent.com/46754749/114065212-b260b580-989a-11eb-99fc-0a801ac7d02d.png)

**What were you trying to do?**
Run the update patch from 2.0.0 to 2.0.3

**What steps will reproduce the bug?**
Have norton antivirus running, download latest version (2.0.0) and wait for update in client then apply the update.

**Does it reproduce every time?**
Yes

**Norton log:**
Category: Resolved Security Risks
Date & Time,Risk,Activity,Status,Recommended Action,Path - Filename
2021-04-08 18:09:20,High,Path{space}of{space}Building.exe (Heur.AdvML.B) detected by Auto-Protect,Blocked,Resolved - No Action Required,
2021-04-07 18:32:42,High,Path{space}of{space}Building.exe (Heur.AdvML.B) detected by Auto-Protect,Quarantined,Resolved - No Action Required,C:\Users\*****\AppData\Roaming\Path of Building Community\Update\Path{space}of{space}Building.exe

**Comment by ppoelzl** [comment]
This isn't a problem with Path of Building but your antivirus. You have to allow `Path{space}of{space}Building.exe` for Path of Building to be able to update.

I recommend getting a better antivirus program that reports fewer false positives. See https://www.virustotal.com/gui/file/343109dd8fac2526b705d612024c7536eed87efc03b2e6169e2a433973bad92a/detection for a comparison.

Don't trust us? No problem. You can compile the executable yourself from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding-Launcher
In the meantime, we're working on getting a code signing certificate so antivirus programs will complain less. Thank you for your understanding.

**Comment by Ashenbacken** [comment]
Thank you for your response! I got it to work by allowing the .exe file :+1:
