### ISSUE TITLE
Add support for/parse mod lines off various Legion Keystones

### ISSUE THREAD

**Issue by BassOfBass** [PathOfBuildingCommunity/PathOfBuilding#246]
I will only mention mods which don't get parsed and are relevant to the PoB calculations.
####  Eternal Youth
* 50% less Life Regeneration Rate
* Energy Shield Recharge instead applies to Life
####  Strength of Blood
* Recovery from Life Leech is not applied
* 1% less Damage taken for every 2% Recovery per second from Life Leech
####  Tempered by War
* 50% of Cold and Lightning Damage taken as Fire Damage
#### Glancing Blows
* Chance to Block Attack Damage is doubled
* Chance to Block Spell Damage is doubled
* You take 50% of Damage from Blocked Hits
#### Dance with Death
* Can't use Helmets
* Your Damage with Critical Strikes is Lucky
* Enemies' Damage with Critical Strikes against you is Lucky
#### Second Sight
* You are Blind
* Blind does not affect your Light Radius
* 25% more Melee Critical Strike Chance while Blinded
#### The Agnostic
* Maximum Energy Shield is 0
* While not on Full Life, Sacrifice 20% of Mana per Second to Recover that much Life
#### Inner Conviction
* Gain Power Charges instead of Frenzy Charges
#### Power of Purpose
* 80% of Maximum Mana is Converted to twice that much Armour
#### Supreme Decadence
* Life Recovery from Flasks also applies to Energy Shield
#### Supreme Ego
* You can only have one Aura with no Duration on you from your Skills
* Your Aura Skills do not affect Allies
* 50% more Effect of Auras from your Skills on you

**Comment by ppoelzl** [comment]
Added full support for timeless jewels in 1.4.170.12.
