### ISSUE TITLE
Add a configuration-tab Skill Option for Ball Lightning: "Hits per cast"

### ISSUE THREAD

**Issue by Irfy** [PathOfBuildingCommunity/PathOfBuilding#2462]
#1380 already suggested a full calculation of BL damage based on certain values that were to be determined dynamically or hard-coded internally. The PR was killed due to quality standards and dependence on target hitbox size.

I suggest a far simpler approach to modify BL damage to show real DPS: Add a user-editable integer field with +/- similar to e.g. "Doom on Hex" for Hexes, where the user can enter the number of hits per cast/trigger which they calculate externally, e.g. with the help of the [well-known spreadsheet](https://docs.google.com/spreadsheets/d/1Hlylu1xZGs7WY8SD4bJdDoEy-9HQH68zqoA-n0U5TmU) that was referenced in the killed PR. This number would be a direct multiplier to the single-hit DPS of BL calculated in the left pane. By default (no value/empty field), the multiplier would be interpreted as 1, i.e. DPS would be as it is now.

This addition would work equally well for self-cast and triggered CoC/CwC calculations of DPS.

**Comment by Nostrademous** [comment]
Why can’t you use the “count” variable introduced in 2.0.0?

**Comment by Irfy** [comment]
The count variable resolves the issue fully -- I wasn't aware of it. Perfect!
