### ISSUE TITLE
Equipping Ngamahu's Flame generates an error

### ISSUE THREAD

**Issue by aleksiL79** [PathOfBuildingCommunity/PathOfBuilding#2464]
After the latest update, I get an error when importing a specific character from my account. The error repeats every few seconds if I clear it and stops repeating when I unequip Ngamahu's Flame. To reproduce, import this pastebin code and equip Ngamahu's Flame in the weapon slot: https://pastebin.com/H6gLzc8j

**Comment by Helyos96** [comment]
Should be fixed by #2450 when it's merged.

**Comment by pundm** [comment]
Fixed in v2.1.0
