### ISSUE TITLE
Node difference preview not working most of the time with General's Cry selected

### ISSUE THREAD

**Issue by Helyos96** [PathOfBuildingCommunity/PathOfBuilding#2467]
Not super important since you can just select the actual skill rather than GC in the left panel, but it's still weird that even defensive options like life or res don't show a diff.

* **What happened?**
With General's Cry selected in left panel, nodes will only show mod diffs when they affect exerted attacks. Anything else (life, res, accuracy [..]) gets ignored.
* **What steps will reproduce the bug?**
Create a skill group with general's cry and a melee skill. Select General's Cry in the left panel. Hover a node on the tree.
* **Does it reproduce every time?**
Yes
* **Screenshots:**
![image](https://user-images.githubusercontent.com/67038113/114210354-f964ae80-995f-11eb-96a3-2281e1080c1c.png)

**Comment by Nostrademous** [comment]
Fixed by #2453

**Comment by xanthics** [comment]
Just adding to this that FullDPS only shows damage increase/decrease for `Exerted Attacks deal #% increased Damage`, same with Node Power Report.  Although changes to the tree that should affect damage do correctly affect the damage overview panel.

![image](https://user-images.githubusercontent.com/3137623/116455824-601a1100-a816-11eb-9982-6902123c6a5f.png)

![image](https://user-images.githubusercontent.com/3137623/116456067-aa9b8d80-a816-11eb-9596-295f59f6b404.png)
