### ISSUE TITLE
Mirage Archer showing for Frenzy on non-bow, non-mirage archer build

### ISSUE THREAD

**Issue by MatthewSbar** [PathOfBuildingCommunity/PathOfBuilding#2475]
I'm checking the DPS of various skills for my build which uses a claw and shield, and I tried adding Frenzy. If the count of frenzy is 1, I have two listings for frenzy in my full DPS calculation, one for Frenzy (MA) and one for Frenzy. I don't have a bow nor have I socketed Mirage archer, so Mirage archer shouldn't be included in my DPS. I'm not sure how it got added, either it was on accident while the app was lagging and I clicked or it was because of some kind of bug, but, either way, even if I did set up a mirage archer, it shouldn't count towards my DPS unless I have a bow equipped.

**Comment by coldino** [comment]
This is a known issue and the team are working on a fix. A Mirage Archer skill group which is used internally for gem comparisons is to blame.

**Comment by MatthewSbar** [comment]
Sounds good, will close this then.
