### ISSUE TITLE
Close Combat with frost blades

### ISSUE THREAD

**Issue by JayLosy** [PathOfBuildingCommunity/PathOfBuilding#2477]
"melee distance to enemy" didn't effect close combat, It doesn't matter of i set 15 or 30 total dps didn't change, It happen to my frost blades gladiator here is pob https://pastebin.com/kC9ZM9r0 i don't know if this happen to other skills.

**Comment by Seikah** [comment]
Not a bug. Close Combat Support is restricted to swords and axes; you are using a claw.
