### ISSUE TITLE
For clarity, be able to disable/blackout nodes in skill tree 

### ISSUE THREAD

**Issue by mauritsunkel** [PathOfBuildingCommunity/PathOfBuilding#2478]
As a beginner PoE player I would like to create my own builds instead of looking only at others. My main issue is as I'm theory-crafting I am constantly rechecking the same nodes that I DO NOT need for my build. This would be completely relieved by being able to disable/blackout nodes.   

Solution that should be simple: right mouse click on unused node makes node icon black/clearly visually disabled.

**Comment by Wires77** [comment]
I would recommend using the "Show Power Report" button at the bottom of the tree.  It will black out any nodes that don't do anything for your build already.
