### ISSUE TITLE
Issues with anointed notables

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#248]
* They always count as being unallocated for the tooltip.
* You can't manually allocate or deallocate them.

I think allowing to toggle their state discarding any anointments should be fine w/o having to manually remove the latter.

**Comment by esheyw** [comment]
A better system for picking/changing anoints would be great, but even just fixing the tooltip would be a very welcome change.

**Comment by KashouC** [comment]
Picking an anointment on the tree could just add the "Allocates" line to the equipped amulet as a quick fix I suppose.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.1.

**Comment by ppoelzl** [comment]
As of 1.4.170.5, they still always count as being unallocated for the tooltip.

**Comment by ppoelzl** [comment]
Examples:
Allocated:
![annoint_on](https://user-images.githubusercontent.com/33464174/87809225-54e38f00-c85b-11ea-8b19-68257018cbe5.png)
Unallocated:
![annoint_off](https://user-images.githubusercontent.com/33464174/87809397-a0963880-c85b-11ea-94c4-27dbcb1e29d1.png)

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.19.
