### ISSUE TITLE
Raise Spiders included in Full DPS does not have COUNT

### ISSUE THREAD

**Issue by dyoung-42** [PathOfBuildingCommunity/PathOfBuilding#2480]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
* v2.0.3
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* After Selecting 'Include in Full DPS', there is no option to increase the COUNT for Raise Spiders (from Arakaali's Fang dagger)

* **What were you trying to do?**
* Include all 20 summoned spiders in FULL DPS

* **What steps will reproduce the bug?**
* Include Arakaali's Spider in build, turn on 'Include in Full DPS' option

* **Does it reproduce every time?**
* yes

* **Provide a build code:**
* What is a build code? sorry, not clear from this text what you require
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.

* **Screenshots:**
* included
![POB_RaiseSpidersCOUNT](https://user-images.githubusercontent.com/82292416/114286204-eb736400-9a19-11eb-94a6-51bf981215b3.png)
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Nostrademous** [comment]
@dyoung-42 "build code" is a pastebin code so we can re-import your build to test.
