### ISSUE TITLE
Count issues

### ISSUE THREAD

**Issue by Kragtor** [PathOfBuildingCommunity/PathOfBuilding#2485]
Adding Counts to Scorching Ray socketed in Soul Mantle(there-by becoming a Totem) does not affect the DPS calculation in any way I can see. Not the DPS on the left, nor the Full Dps that can be toggled, nor the Calculation screen.

**Comment by EchoingZen** [comment]
I can confirm this is an issue. Scorching Ray totems has been fixed to allow multiple Scorching Rays to deal damage. It appears that anything totem related doesn't quite look right with Scorching Ray.

From 3.14 patch notes:
"Fixed a bug where Scorching Ray totems did not stack their damage correctly with other Scorching Ray totems."
