### ISSUE TITLE
Full DPS for explosive arrow might be incorrect

### ISSUE THREAD

**Issue by GhostyMcToasty** [PathOfBuildingCommunity/PathOfBuilding#2486]
Currently running version 2.0.3
PoB link for reference: https://pastebin.com/E23vv6xZ

When I tick "Include in Full DPS" for my explosive arrow, the DPS shown seems way too high. My average hit at 20 fuses is ~281k, but the full DPS shows it at ~7.1mil. I have nothing else ticked to include in full DPS.

The 7.1mil shown under full DPS seems to be assuming the average hit is per fuse. 
Given that I can reach the 20 fuse cap 1.27 times per second: `281,796.3 * 20 = 5,635,926 × 1.27 = 7,157,626.02` 
This math seems to line up with what I'm given for full DPS. If I go to any of the other fuse options, I can get the given full DPS number exactly the same way. It multiplies the average hit by 20, and then by 1.27.

My assumption was that that the average hit is already counting the given amount fuses together. This would mean I should have a full DPS of about 357k.

Because I don't know for sure if the average hit is counting all the fuses together or not, I can't really tell if this is bugged or not. But with how easily I can scale the full DPS into the tens of millions, I'm assuming it's bugged.

**Comment by Regisle** [comment]
This is correct that its wrong, but the issue is that its not diving the amount of fuses by 20, your correct in that the average hit already adds all the fuses together, so the damage is about 20 times too high becouse it thinks each arrow adds 20 fuses
