### ISSUE TITLE
Envy Crashes the app

### ISSUE THREAD

**Issue by eabemitchell** [PathOfBuildingCommunity/PathOfBuilding#2487]
In the skill section.

If you try and add Envy the app crashes as soon as you mouse over it.
![image](https://user-images.githubusercontent.com/82354357/114335555-3ff60c80-9b0a-11eb-886c-9dafd73cc13e.png)

If you only type it in, and never mouse over it. It adds the skill just fine, but still doesn't calculate damage correctly. Or select the correct levels also doesn't show any skill types in the heist skill section.

**Comment by pundm** [comment]
fixed in v2.1.0
