### ISSUE TITLE
Unnatural Instinct allocation is incorrect.

### ISSUE THREAD

**Issue by eabemitchell** [PathOfBuildingCommunity/PathOfBuilding#2488]
For some reason Unnatural Instinct acts like it allocates the passive points. This causes other things to get messed up. For example if you socket Unnatural Instinct near the Scion starting area. It will make Pure talent give you +25 to all stats. Which is wrong as this doesn't happen in game. It should only give the stats of the unallocated areas, not treat them as allocated. This causes many calculation error's regarding passive tree interactions.

**Comment by pundm** [comment]
Thanks for your report. Please use the provided template next time and provide a pob.

https://pastebin.com/Gmv9VtkX
