### ISSUE TITLE
Aura issues...

### ISSUE THREAD

**Issue by eabemitchell** [PathOfBuildingCommunity/PathOfBuilding#2489]
Was trying to theory craft a buff bot... But the app doesn't seem to calculate the same buffs being added twice. Instead it seems to break the apps ability to handle the auras all together.

How to reproduce this issue. Added an aura setup like Purity of fire, Purity of Ice, and Purity of Lighting. Copy, and pasted this setup tied one to weapon slot 1 and another to weapon slot 2. Did this for a number aura skill set ups. So I could easily compare the two when swapping in-between them. However, some auras calculate just fine when added twice while others don't calculate at all. The purities don't seem to calculate at all in the second skill setup...

It would probable be easier to look at the build than rather than to try and reproduce this issue. Use this past bin link. https://pastebin.com/e0HkKbwn

Try just swapping the weapon sets back and forth. They should have the same elemental resistances almost, but they act like the buffs completely drop off in one of the setups. It seems to be that the second buff of the same buff never calculates even if it is in an inactive slot. Weapon slot 2 doesn't calculate the purities. And weapon slot 1 doesn't calculate the wrath, hatred, and anger damage. Making this build really hard to look at.

Also maybe I should ask for a few feature request here. Like adding the options to add multiple skill setups in a single build to compare too. Making it easier for me tie things to the correct slot instead of assigning them weapon slots to compare with. Would make things much easier for me anyways. And/or an aura reserve breakdown section in the calculation page.

Thanks all

**Comment by PJacek** [comment]
Looking only at the Wrath/Anger/Hatred groups the auras in `Weapon 2` don't activate (no links/levels from item and no count controls). They don't work if I copy and paste but everything seems to be okay if I recreate the group manually. No idea what's happening here.

**Comment by QuickStick123** [comment]
This seems to be some weird legacy state where the enable1 / enable2 fields are configured in an odd way for skills which don't use these but this information is still applied.

**Comment by LocalIdentity** [comment]
Legacy build, no longer an issue
