### ISSUE TITLE
Critical Damage taken

### ISSUE THREAD

**Issue by eabemitchell** [PathOfBuildingCommunity/PathOfBuilding#2490]
I guess this should also be considered a bug.

I would like an added line to the Effective "Health" Pool: section that goes over critical damage taken. Please also note: a rework of critical strike damage done should also be considered.

From my knowledge... And correct me if I am wrong all damage is calculated if the resistances was 0 when a critical strike happens. This goes for armor too. So when you crit or get crit elemental penetration doesn't matter. And neither do your resistances. This is what makes the node  "Sanctum of Thought" so OP. As well as the watcher eye mod for determination that reduces damage from critical strikes so powerful.

I was thinking about trying to get that corrupted Jewel mod to be crit 100% the time. And combining it with the mods I listed above. To make a tanky build that doesn't have any resistances or armor. However, this would make that char really weak to DoT. But I have a different plan for that kind of damage. But I can't even do that type of calculations correctly. Well not in the current state of the tool. So hopefully this is considered at least.

Thanks All.

**Comment by pundm** [comment]
Only the Inquisitor's 'Inevitable Judgement' makes _**your**_ crits behave like the enemy has 0 zero (elemental) resistance regardless if it has positive or negative value.

That said, critical strikes _**you**_ take, do not ignore your resistance or armor. They just deal increased damage based on the mobs critical strike multiplier. You can read about it [here](https://pathofexile.fandom.com/wiki/Critical_strike)
