### ISSUE TITLE
support for All Damage from Hits with This Weapon can Poison (with workaround)

### ISSUE THREAD

**Issue by BasHamer** [PathOfBuildingCommunity/PathOfBuilding#2491]
**Is your feature request related to a problem? Please describe.**
this attribute is not supported

**Describe the solution you'd like**
have the attribute supported or add an info icon for unsupported attributes to explain,

**Describe alternatives you've considered**
add the following to an item
```
Your Fire Damage can Poison
Your Cold Damage can Poison
Your Lightning Damage can Poison
```

**Comment by Regisle** [comment]
The text is red which already indicates its not supported, though we will probably add support in the future

**Comment by QuickStick123** [comment]
Fixed sometime recently (with 100% chance to poison)
![image](https://user-images.githubusercontent.com/31533893/177551568-5f3bbda2-1a9b-417a-be99-168a7682e032.png)
