### ISSUE TITLE
Issue with a build - creates an error

### ISSUE THREAD

**Issue by R3ZN4** [PathOfBuildingCommunity/PathOfBuilding#2492]
https://pastebin.com/PuksJW40

I was tinkering as we do and this error popped up.... Just try to sort the damage in some way with show power report to see it happening. 

Screen shot of error included.
![image](https://user-images.githubusercontent.com/66842986/114412748-5e482080-9b7b-11eb-88ec-ec805bb331a8.png)

Sorry hope I reported this correctly. Thanks for working on PoB for us ;)

**Comment by pundm** [comment]
Hi, i tried to follow your steps on v2.1.1 and could not reproduce it anymore. Could you update to the newest version and see if it still persists for you?

**Comment by flotos** [comment]
I have the same error with this build : https://pastebin.com/MEpKyEKQ
It seems to have started to trigger when I used either : A cluster jewel, or 150+ points on tree.
With less points and also by unnalocating the cluster jewel, it is still bugged however.

After openning PoB and triggering the bug, I can't open the build anymore, but on first load it's fine.

**Comment by AlphaJuliettOmega** [comment]
@LocalIdentity Just pinging to notify, this error still seems to occur if I switch to Full DPS calc and click on `Power Report` before all the passive tree icons have finished calculating (glowing red - this step, before final normalization)
