### ISSUE TITLE
Several issues with full DPS on a DoT build

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#2495]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Making a Cold Snap build, noticed the Full DPS section wasn't accurate to my Cold Snap DPS.  Also missing the Righteous Fire from that section.
* **What steps will reproduce the bug?**
Add Vaal Cold Snap, add it to Full DPS.  Add Vaal Righteous Fire, add it to Full DPS.  Notice how the "Full DoT DPS" value doesn't match any of the other skills totaled up.  Also notice a difference in values from the DoT DPS from the normal Cold Snap section vs. the one under the Full DPS section.  Also notice Righteous Fire missing completely.
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
More complete build that shows a vast difference in DPS numbers
https://pastebin.com/xEt7aV9z

**Comment by Nostrademous** [comment]
It all adds up to me from components. Do note that you have Vaal and Non-Vaal Cold Snap, and Vaal and Non-Vaal RF selected for inclusion in Full DPS.

Only strange thing might be that Vaal Cold Snap has a DPS of 354,356 (which is the Average Hit of 206,303.1 times the Cast Rate of 1.72 (really 1.71852 or something close to that rounded up)).

For the "Full DoT DPS: 3,114,691"
Vaal Cold Snap DoT is 1,129,473.8
Cold Snap DoT is 799,194.0
Vaal RF is 1,012,839.3
RF is 203,182.9

**Comment by Wires77** [comment]
Ah, I was mislead by having the "Full DoT DPS" close to the other skills and I thought it was showing the DoT DPS component of them.  Useful to add, but ultimately that part isn't a bug.  I suppose that's why both RF components aren't showing, either, since Full DPS doesn't show DoT components.
