### ISSUE TITLE
Wintertide Brand +1 attach limit doesn't work

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#2500]
* **What happened?** Wintertide Brand's inherent +1 attach limit is not implemented or functioning correctly.
* **What were you trying to do?** N/A
* **What steps will reproduce the bug?** Allocate Runesmith on any Wintertide build. Set your # of attached brands to 3 or higher. Check the amount of increased damage taken Runesmith is giving, it will cap out at 1 (or 2, with Runebinder) and ignore the +1 attach limit inherent to Wintertide Brand.
* **Does it reproduce every time?** Yes
* **Provide a build code:** https://pastebin.com/3hZJNWFa
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:** ![](http://puu.sh/HxYHX/366eed0135.png)

**Comment by ALT-F-X** [comment]
Thanks for the thorough bug report, sadly it looks like the incorrect info comes from imported data from GGG and cannot be fixed by us.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/247a9ce5d044faf8cc4b46a82e83cc411e2aac35/src/Data/Skills/act_int.lua#L10471
