### ISSUE TITLE
CoC Trigger rate for Discharge ignores Endless Misery

### ISSUE THREAD

**Issue by daniel-morrison** [PathOfBuildingCommunity/PathOfBuilding#2503]
Steps to recreate: 
* Use Discharge with Cast on Critical Strike
* Use Endless Misery jewel in an appropriate socket to enable the threshold

Result: trigger rate is capped at 0.5 per second, using Discharge's original 2.0s cooldown, despite Endless Misery reducing the cooldown to 0.25s (the cooldown override is successfully applied as seen in the skill stats bar on the left)

Expected behavior: trigger rate should be capped at ~4 per second using the lowered cooldown of Discharge

Build code: https://pastebin.com/MCt89Fq0

Judging from the calcs tab, it looks like this issue is being caused by considering only the base cooldown of the skill, then applying any cooldown reduction, ignoring any cooldown override.

**Comment by XThepope** [comment]
This effects Mjolner and Cast While Channeling as well.

**Comment by QuickStick123** [comment]
Fixed recently 
![image](https://user-images.githubusercontent.com/31533893/177550979-ee8ff8e1-01e2-4789-8b77-75220e89b24b.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3832.
