### ISSUE TITLE
Add alternative to pastebin

### ISSUE THREAD

**Issue by Muramas** [PathOfBuildingCommunity/PathOfBuilding#2505]
**Is your feature request related to a problem? Please describe.**
Currently pastebin does not sell any pro accounts ( https://pastebin.com/pro ) and has a limit to 500kb for their free account which is under some builds file size

**Describe the solution you'd like**
It would be nice to have an alternative import tools to pastebin, for example ControlC ( https://controlc.com/ )

**Describe alternatives you've considered**
I understand that raw data can be imported but it is not clear how to do that with the description of "To import a build, enter the code here" 

I would suggest doing a rewrite or have a bigger box to make it look like that is where more text goes.

**Additional context**
![image](https://user-images.githubusercontent.com/2413847/114642377-cc870300-9ca1-11eb-8b0f-17c4ce3ede61.png)

![image](https://user-images.githubusercontent.com/2413847/114641932-f8ee4f80-9ca0-11eb-848e-fb1b6a08d651.png)

**Comment by margolisj** [comment]
#2537

**Comment by Lothrik** [comment]
Closing as #2537 is merged and covers this.

Additionally the 500KB+ build size thing you mentioned is almost certainly a bug (no builds should be that large) &mdash; I'm reasonably certain #3423 fixed every case where builds could get that large.
