### ISSUE TITLE
Lightning/Cold Projectile for Skeleton Mages missing %crit chance

### ISSUE THREAD

**Issue by guigasper** [PathOfBuildingCommunity/PathOfBuilding#2506]
* **What happened?**
Lightning/Cold Projectile for Skeleton Mages (Casters) is missing the 5% base crit chance as show on wiki/poedb
* **What were you trying to do?**
*Calculate the right amount of dps
* **What steps will reproduce the bug?**
* Just equip a Skeleton Gem, go to calcs tab, select caster skele, and you will see that Cold and Lightning have 0% crit even with power charges/zealotry etc, but Fire Projectiles have it just fine
* **Does it reproduce every time?**
* Yes 
* **Provide a build code:**
* https://pastebin.com/2RdYEgSs ?
* **Screenshots:**
* Cold: https://prnt.sc/11cxars
* Lightning: https://prnt.sc/11cxchd
* Fire: https://prnt.sc/11cxh1h
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
As far as we can tell, this is working correctly.  Only fire mages have a crit chance in-game as well.

https://www.pathofexile.com/forum/view-thread/2856423/page/1#p23268263
https://www.pathofexile.com/forum/view-thread/3077521/page/1#p23976167

**Comment by guigasper** [comment]
Thanks :)
