### ISSUE TITLE
Elemental focus supporting a skill and then adding another skill in a completely different setup + combustion will make it so that the skill not supported by elemental focus still isn't able to ignite

### ISSUE THREAD

**Issue by UnrealDaltonic** [PathOfBuildingCommunity/PathOfBuilding#2511]
**What happened:** I was trying to setup a build that uses spell totem with elemental focus and then another spell totem to use with wave of conviction + combustion.  When I wanted to check what my chance of ignite was I realized that it simply didn't show he ignite chance table at all.

**How to reproducie:** Simply place any spell supported by elemental focus (I checked if it was a bug related to soul mantle/ spell totem but it wasn't) and then make another setup with wave of conviction + combustion**
**Does it always reproduce?:** Yes
**Build code:** https://pastebin.com/7psrgJeB

**Comment by QuickStick123** [comment]
It seems to be working unless I'm confused.
![Capture](https://user-images.githubusercontent.com/31533893/114697271-0e2ab300-9d61-11eb-838c-0a5c9e56cd44.PNG)

**Comment by UnrealDaltonic** [comment]
Oh I am so incredibly sorry, I was changing the skill on the left completely forgetting that the calcs window functions differently.
