### ISSUE TITLE
Incorrect "Total Pool" with Arcane Cloak vs DoT damage?

### ISSUE THREAD

**Issue by ColtaineKK** [PathOfBuildingCommunity/PathOfBuilding#2517]
I might be missing something basic here, but from what I understand Arcane Cloak only works vs hits, and thus shouldn't be helpful for incoming DoT damage? Currently PoB is including the Guard Pool (from Arcane Cloak) in Effective Dot Pool, which I believe is incorrect.

PoB build link: https://pastebin.com/vYCp0A1w

![2021-04-14 21_52_19-Clipboard](https://user-images.githubusercontent.com/82542061/114771121-7f239800-9d6c-11eb-9e4b-fc629587ad08.png)
![2021-04-14 21_51_08-Clipboard](https://user-images.githubusercontent.com/82542061/114771126-8054c500-9d6c-11eb-9f2c-f15b75f76acf.png)
![2021-04-14 22_05_22-Clipboard](https://user-images.githubusercontent.com/82542061/114772030-9a42d780-9d6d-11eb-861f-4eee206a9390.png)
![2021-04-14 21_51_47-Clipboard](https://user-images.githubusercontent.com/82542061/114771112-7df26b00-9d6c-11eb-9c59-35689daa1876.png)

**Comment by Regisle** [comment]
Known issue, fixed by #2390 when I finish it
