### ISSUE TITLE
Cannot Reopen a Build

### ISSUE THREAD

**Issue by traviskm** [PathOfBuildingCommunity/PathOfBuilding#2520]
After I save any build I can't reopen it.
The build will always display in the list as "name_of_build Level 1 ?".
I have reinstalled Path of Building Community and it is still occurring. This happens no matter if it's a complete build or if it's a default empty Scion. Attached are a couple of screenshots and the xml file (it's a .txt file since Github does not support attaching .xml) that was created when I saved a build (I can't reopen it so I can't get the build code).

![Screenshot (71)](https://user-images.githubusercontent.com/6201986/114776830-86c94980-9d38-11eb-9a6c-29f425173b1b.png)

![Screenshot (72)](https://user-images.githubusercontent.com/6201986/114776837-892ba380-9d38-11eb-8343-b63c2a2e377a.png)

[ultimatum build.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6313619/ultimatum.build.txt)

**Comment by LocalIdentity** [comment]
Is this with the latest update 2.1.0?

**Comment by traviskm** [comment]
I noticed it ~an hour ago before the update was released (I was using 2.0.3) and after updating to 2.1 it is still occurring.

**Comment by traviskm** [comment]
What hasn't worked so far:
Reinstalling
Running application as administrator
Removing the "Read Only" property from the Builds folder
Changing the location the builds are saved to

**Comment by traviskm** [comment]
With my very limited knowledge of lua it seems like when a build is saved it gets its name/path saved in the Settings.xml file. Looking at mine it seems kinda messed up:

[Settings.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6313748/Settings.txt)

**Comment by traviskm** [comment]
As it turns out, it seems my antivirus software (IOBit Malware Fighter) was blocking .xml files from being accessed as part of an "anit-ransomware" thing. Going into its settings and specifically turning off .xml protection fixed this issue.
