### ISSUE TITLE
Prismatic Catalyst (Resistance) should affect unique amulet Tavukai

### ISSUE THREAD

**Issue by MrBengtGoran** [PathOfBuildingCommunity/PathOfBuilding#2521]
Running version 2.0.3 och Path of Building Community

Applying **Prismatic Catalyst (Resistance)** on the unique amulet **Tavukai** does not scale the mod **Minions have (-17-17)% to Chaos Resistance**.

In game this action does affect the amulet. See attached image for clarification.

![image](https://user-images.githubusercontent.com/82544594/114779978-1261cb00-9d77-11eb-94a4-84242b0b14b8.png)

**Comment by QuickStick123** [comment]
Also worth correcting https://docs.google.com/spreadsheets/d/11mOp3VLPXgbhJq562DdFmP34nx4tNqoF47LbrM-R93g/edit?usp=sharing

Got bored and didn't go through all of them though.
