### ISSUE TITLE
Toxic Rain shows double dps in skill damage overtime.

### ISSUE THREAD

**Issue by Jonixo** [PathOfBuildingCommunity/PathOfBuilding#2522]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Nodes including both "increased damage with bows" and "increase damage over time with bow skills" like "Aspect of the eagle" double effects the "skill damage overtime, total increased" making the calculation wrong.
* **What were you trying to do?**
* Toxic rain build.
* **What steps will reproduce the bug?**
* Import the paste: https://pastebin.com/fH5zCfBJ or any toxic rain build and check "total increased" under "skill damage overtime" in calcs.
* **Does it reproduce every time?**
* **Provide a build code:**
* https://pastebin.com/fH5zCfBJ
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* https://imgur.com/a/0JX95Wn
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
Duplicates #2145
