### ISSUE TITLE
Constant errors with new update

### ISSUE THREAD

**Issue by jdwile** [PathOfBuildingCommunity/PathOfBuilding#2523]
https://snipboard.io/F6d327.jpg

Happens no matter what passives I allocate.

**Comment by Wires77** [comment]
Please share a link to your build otherwise we can't help you.

**Comment by jdwile** [comment]
@Wires77 sorry! I thought I had included it 😂 https://pastebin.com/krd2Ne0F

**Comment by Nostrademous** [comment]
It's a minion thing in Full DPS

**Comment by pundm** [comment]
fixed in 2.1.1
