### ISSUE TITLE
Mirage Archer bug causing million DPS inc to every node

### ISSUE THREAD

**Issue by viirulencetv** [PathOfBuildingCommunity/PathOfBuilding#2524]
Using [this](https://pastebin.com/6TeQeBeT) build (and other builds tested with mirage archer) allocating any node adds 6+ million DPS to the build, even just a +10 int travel node. Tested with a couple other builds that use Mirage Archer and some that didn't and it seems to be consistent with Mirage Archer itself.

**Comment by Nostrademous** [comment]
Fixed in #2528

**Comment by pundm** [comment]
fixed in 2.1.1
