### ISSUE TITLE
Golem skills included in full DPS cause error message

### ISSUE THREAD

**Issue by Fab159ian** [PathOfBuildingCommunity/PathOfBuilding#2525]
Please try to fill in as much of the template below as you're able.

* **What happened?**
Error when hovering over a passive skill tree node if Golem skill gem is included in full DPS
* **What steps will reproduce the bug?**
Ticking the box "include in Full DPS:" for any summon golem skill gem and trying to hover over a node on the passive skill tree (except jewel nodes)
* **Provide a build code:**
https://pastebin.com/hvdrb1NT

**Comment by Nostrademous** [comment]
Ty

**Comment by pundm** [comment]
seems fixed in v2.1.1
