### ISSUE TITLE
Crash with herald of purity + full dps

### ISSUE THREAD

**Issue by Helyos96** [PathOfBuildingCommunity/PathOfBuilding#2526]
Hovering a node on a build that has herald of purity/(agony ?) + full dps will crash, looks like `actor` passed to `CompareStatList` is nil. Only crashes when another skill than HoP is selected in left panel.

Not sure if the best way to fix this is to add a check on actor, or maybe the issue is higher up the calltree where an actor other than nil should be passed down.

* **Provide a build code:**
https://pastebin.com/e0HkKbwn
* **Screenshots:**
![image](https://user-images.githubusercontent.com/67038113/114791086-2234db80-9d86-11eb-80e1-8350a75e16d5.png)

**Comment by pundm** [comment]
fixed in 2.1.1
