### ISSUE TITLE
Shattering Steel - Bleeding Damage not affacted by the Steel Shards Consumed conditional modifier

### ISSUE THREAD

**Issue by Kokleekio** [PathOfBuildingCommunity/PathOfBuilding#2527]
* Changing the "Projectile travel distance" and "Steel Shards Consumed" options in config only change direct hit and impale dps of the Shattering Steel skill, Bleeding damage is unchanged.

* I believe that the modifier "Projectiles deal up to 100% more Damage with Hits and Ailments per Steel Shard consumed at the start of their movement, lowering this bonus as they travel farther" should increase bleeding damage as well when Steel Shards are consumed.

* Here is the link for the Pob that I tried: https://pastebin.com/7ZqR7gVp

**Comment by LocalIdentity** [comment]
Shattering steel no longer has mods on it that change bleed damage
