### ISSUE TITLE
Missing implicit selection for variant 4 of Disintegrator, Maelstrom Staff

### ISSUE THREAD

**Issue by Nic-Seddon** [PathOfBuildingCommunity/PathOfBuilding#2529]
The Disintegrator staff is missing an implicit selection for variant 4.

Current Line:
{variant:3}25% Chance to Block Attack Damage while wielding a Staff
Suggested Fix:
{variant:3,4}25% Chance to Block Attack Damage while wielding a Staff

Complete Item Text:

Disintegrator
Maelstrom Staff
Elder Item
Variant: Pre 3.7.0
Variant: Pre 3.11.0
Variant: Pre 3.13.0
Variant: Current
Selected Variant: 4
Maelstrom Staff
Quality: 20
Sockets: B-B-B-B-B-B
LevelReq: 64
Implicits: 2
{variant:1,2}20% Chance to Block Attack Damage while wielding a Staff
{variant:3}25% Chance to Block Attack Damage while wielding a Staff
{variant:1}{range:0.5}Adds (270-300) to (340-380) Physical Damage
{variant:2}{range:0.5}Adds (250-280) to (315-355) Physical Damage
{variant:4,3}{range:0.5}Adds (220-240) to (270-300) Physical Damage
{variant:4}Battlemage
{variant:1,2,3}{range:0.5}Adds (376-400) to (568-600) Physical Damage to Spells
+1 to Maximum Siphoning Charges per Elder or Shaper Item Equipped
{range:0.5}25% chance to gain a Siphoning Charge when you use a Skill
{range:0.5}Adds (12-14) to (15-16) Physical Damage to Attacks and Spells per Siphoning Charge
Gain 4% of Non-Chaos Damage as extra Chaos Damage per Siphoning Charge
1% additional Physical Damage Reduction from Hits per Siphoning Charge
0.2% of Damage Leeched as Life per Siphoning Charge
Take 150 Physical Damage per Second per Siphoning Charge if you've used a Skill Recently

**Comment by Wires77** [comment]
Fixed in 2.3.0
