### ISSUE TITLE
Law of the Wilds Summon Spectral Wolf skill changing bugged

### ISSUE THREAD

**Issue by Firedrops** [PathOfBuildingCommunity/PathOfBuilding#2530]
* **What happened?**
With Law of the Wilds equipped, in Skills, "Summon Spectral Wolf", there are options "Include in Full DPS" and "Count:"
Changing either of these will "kick" you out of this menu, with values reset. This does not happen with a similar item - Araakali's Fang, for example.

* **What were you trying to do?**
"Include in Full DPS: Yes" and "Count: 10"

* **What steps will reproduce the bug?**
Try to change these values, i.e. click on them.

* **Does it reproduce every time?**
Yes

* **Provide a build code:**
v2.1.0

**Comment by Nostrademous** [comment]
This is happening b/c in 2.1.0 the `Law of the Wilds` was updated to use Level 25 Summon Spectral Wolf (stated in the patch notes) but we don't have the updated GGPK database yet which would provide that skill and provides the data for what it maps to. Previously there were only a Level 10 and Level 20 version.

**Comment by Firedrops** [comment]
Sounds like something that'll fix itself when the new patch drops, then. Thanks for investigating!

**Comment by pundm** [comment]
The gems are being worked on as we speak. I'll close this. Will work with the next patch.
