### ISSUE TITLE
Document keyboard shortcuts

### ISSUE THREAD

**Issue by lxsli** [PathOfBuildingCommunity/PathOfBuilding#2531]
**Is your feature request related to a problem? Please describe.**
Last league I discovered I can use CTRL-1 through 5 to change tabs! I really wish I'd known earlier. However, I can't figure out if there's a shortcut for Notes.

**Describe the solution you'd like**
Documentation of keyboard shortcuts. This could go in the README.adoc, in the About dialog, in a new dialog or some combination of these.

**Describe alternatives you've considered**
None.

**Additional context**
Thanks for all the work that goes into PoB, esp. preparing 2.0.0!

**Comment by imsjp** [comment]
Added a PR for a CTRL+6 shortcut to Notes tab.
Would like to add to docs to account for all existing shortcuts.

**Comment by lxsli** [comment]
#4331 thanks imsjp!
