### ISSUE TITLE
Crash on Hovering over Node in Tree

### ISSUE THREAD

**Issue by Precursorx** [PathOfBuildingCommunity/PathOfBuilding#2533]
* **What happened?**
* The Programm crashed when i hover over any node in the Tree

* **What were you trying to do?**
* Nothing special

* **What steps will reproduce the bug?**
* Importing the build code and hovering over any node in the tree tab will cause the program to crash

* **Does it reproduce every time?**
* I only tested it on one machine (windows 10) and it occurs every time

* **Provide a build code:**
eNrVPGlP48i2n5tfYUV60ntSANfiDdH3KkCAdBMICdDLF1TElcSDYwcvCeGq__s9VXaCA1kqhhnpTU9DYp99q3PK5T789_PQ18Y8ir0w-FpBe3pF40E3dL2g_7Vye3O6a1f-_a-dwxZLBle9o9TzxZ1_7Xw5lJ81n4-5_7XioIqWsKjPk7sZKXIPpEYsSAY8DJrsrzA6C92vlcsw4BXtgQWul8y-dX0Wx5dsyL9WmixiqcujisbiLg_c49dbR0CZR4_i3pB5QSfsPvLkLArTEchd0cYenzRDFwAbzdZV-6bA3AuKzEH4L4ctn0151ElYosXw42ulBjZgfX7ChvATqDE_BVLYMHTHNvaoY-uWbVb2lyN3Rpy7cyS0hyn-Z0FbEa_3erybeGN-HHnJ8YAF3Vc19FV428I2Uz_xRr4nnLAJ_vwdaaSvBL4JE-aftDpzWIJMm2Cy59i2iYj59-CFyWY1fnjJ4MgHTxS5KMaFwG30Ay_hJZFboReHQQnkmX5F1NWeDYcPXlBKwxlqbdzfFrUWcXbVy8K2zVwvjecUTGcVUpMF7DiMX_2GVydl8hqkxF6ZOm3-VIREqyFP-PMcjNI19IqA1kqrN4KCFuvIFQFNe7V04zCByrvZ3Rde7zUnqa5bawpQ90BAN4Luq4Gg1q8hfBtEHMr0uFC51rFYRGnxCIp-olIwBGKb9_mrvsgy94hur0O44Lw7OIPFAxhBeZqj2jrao-tCbg5pOHittQRw0Vr6OqpLbGUhNYR3lkJ7jkMwzf9fR-SN1fT1mq8y2UrF6gGP-tPOwOO-uxlaGq2IomS8IsKiOkoo2-s0ZnExtSih6xXK4Iu6rM7wJofVBTBcrroSb4_RisK_RHfgb4dWi4ZhWqii1vrgz8AXigVdmY-twTT2urBIyY6rzd20u1C-yMo1YN7pNMMxH0IWyEYJer9XhfYcYxX2kQ-No6oBgLLvb4VRSxLWfTwJ3T7fislWGKdeBBaLvTjZBvYKWtxjNlLpB0RaLZDftTcDK9O_8PqDJIA5QpnJGwx1TQYsjN9yMVXAlVmcpv5iA0qR5djOHqI6NvHKMOw8eot4CXvw-YGmPyPkGI5rr87lcAKiDcS0FStkfgG6yV77kpVLxGnEg5epMv0FcCUG9cBNIxHnb3mYqhhFNqvbS1kioA_mwwtvWKjy2Qp7uC8HWPGpMRyFUSIvHjO_G0t6jWCUJlogJ8-hF3fvH9JeT8yXFaAfyem4fnpaP75p3NVzEYoosXDvfZAOH8SolP2esf5y2OGy1mnd0PfZKOYwmvaYHwNtz81DowM1vpsowcMSlo-tKtA_WNSNPDC7CrCYkJRElqOqCqSYIpUAwSvM5-oGu5mOuHB_rGqzvNiqQMv5TwkyG9jUFJSDoZobeJdNlSDnrY0SdN3nNc8XS6ia1ZqQCNnqqwYPi2HkPaSJYrTJwURJDtGSKylYbEaVJM46HiXaeVOoApsvQWqxBt2GsjdOeI9DFCtms6wSN-yRB3kNnNW7Q5lCsRZDITzjw_hoCkvTqbDam92BBQBYtKIUaLu8x1JfXL9Ome8l06-VwPOL1y-ybUJ5NR6Ek046GmWURNrGYPeLi-xOzU9yIoLNTPxMOSGj3PvLarv8LjWQG4Be0PVTF2bVfEWeSeezB8G7ovXFXuFxmAZJLgkPxJrrzgBjPxTbLpyNwIKo8pYT9PBSji-HIFmOe-aHD8zHc1aZmlivLNxHcy_IZaEBHO8Y88XeZeB2fDasaE-Zzg2Z7NJqIC8fiu9NnjCXJWy_AUtZvC_Msi8Fgk8ryIj1-q123Uxx0EusUKJfz6TQMnwtIyAFbHqB3MLtpMNhCJ5vQaVMWDzMgmyp_rl-qw2Qm3imfx4AR1GaSIm3t8A8gt7TUFX_FfPTFWunycDncfwBvd6RUFVrjvjpWsnBc3Fw-4CC66ip6ippaDMiWrEP-kzFT-Gv1_tIlL6loKrgDO_zVKqJ9SKJmC8yPhfwI4qJYakHXeX2qgGmFvY0gZstX1ld-0eK_bvijj63uM-tLPpt6D96W5t4PZWtSvycjPZK5x-u9E3mDT9SK4roysVBIH2eJoulqgYjael1uxV57vbFLsPaqFDBs2-yRlnVcw7B4l71WmkkF9a3JCW1ZbpLwBaLMtHXWOIthy1NkaGL6rFERKhxz15cB3q8E_qux6MZN7mP9AnFZhY6f0e12TYsG0HiDT2wrxf0j6PpB_0yi9BVVFUdVMTXJIHFgvPoJQmPHsJE7B9-ZrnhXjz0uisNoaD6EhKqWueoUuHP00nuf63zroJSy2ioajXD_WS18upec11PDK3MPw4hFsJJ8IF1AgbgMHB_eIFbwncCVZO4_58qhLnJzkd-GLodBjNikj1e-JQCIanWAkl4-8lLIGtMjJ3svbnzT3Jj4iaC_p5lhpGoKN8MgC_FM0JCXAwsQldsJxiGSZ2qgRyrSigiepU6yLKryNGdKiY6hsuIWqhKMDZQ1aSGbVUNXce0aiETw03HhMsE27hKTQMwAdgyqibWMapiC1G9igj8qhKDErNqGsi0gIyNTLhLdFSlWAdWhm4bgIsNmwA8NqpUt0wThCEIhDGoIQBtYEV00wHCICWQpFQH8gCkw2cT4A2D2kaV2JYFTDAxSZXalAgKtmkD8wze1AHScTBgmTq1gBoBtpQQnYAgBjKqhkls4KI7QBNTA1jpFoGbyMBCGqBIbQyWMIlObYFpUfgshDexDYbTDRDYNgSKZZjARyc2cDaACkjqwE8LZAcitg7mNHWwg00x8HJ0QqvIBsODGQACYxNcQME1YF8dzA9KCBBiOhYW7OGuQSwHrIbAnFItG64gMBvGWBiDCEHB6qAcCIHFT7A2mDanaRBgix0qlLaAgoVBaYJ0EBhT2zQELwgRZBugPDYtcA7RDWE2m4KnKbLAnOAcYVrwLqhsU4AH6cGvpgVMsEMM4QkwB9J1AoZ1HPhMLAIqm8gEZSmEAeijI9MRsYOEUwzQhMINER2ODmYBLKfqmA4YASHHFiyIMLMD-KAjtcCABlCuaAnkQuF8HaL50TkR-7NyUYdiyt1LkQZ5pb5tX8gPXwZJMooP9vcnk8neiCWDsMefPZ_vdcPh_gjIQIrtyjKwKxjt1-C_o1r9uHbpD07r-PQ2rrEjcvfbJtG41xvbHfsyPLsf2bjXnSa9i2n7R1i__P39-0PLbN3fHD2N2PXv56en4d3kNglerNror-eHEQb_49POYFgzb0P3CV_gn7x39TC--eXctxx6dW091RsvrZ8vu6Nv9t0NOUFtoz_8wWv6bePk-Wr87R53vvvp7qn96_Hu6Lxx97OPz1l8lZ41grZ-PX7qsUnn5Kn7Y3Te69_aP86uRv436_S-_3T90Pr1onv1RE_DXy_E-Hnyq3F-fbN7OzB-x5PrDn9xJ1NifTPYWX3weHrX4GcD30WX4yvz4mn0UrOudtvtweUjuzr_Pqqn9eCC3CSPXWsSPk2fzEkwvb67v45-kTNcJ399c-_HJ-HNuPG7dmRMzru_b_Wv0hn7M28cZucX48w1-TdZvqQ3TYxsWFaSrA7nT9-WwCHIPgU4E5KPqsBBJSQKcBhiXYUeZJrlqNCD1FYAc6iuYhVimmrawspgqEgHaalCT5aRVzi0Uj5iGSpWlmcZVfg6UI8U4KB8OyrRItYhFfNB3VcxH8JgaJVg0aG4qsDBcqsSVARWShU9LMfUlbyhq3BFBJYOJS2Io-RcCBZTxbmOYSt5gzpKfBFGpor15HqpEPQGLMyWUhJB86UiH7RAplKSY9tWsrNakhOAU4kDQyzmKnpYWCmaqWnbKkkOZjaVso1CV6JkP2hBVfTQDYKVlg6L2kp8qVqWU6pUJKlj2mpLlmXaSnYGQCW-0HOqFV2lukGwpeRfx3IspbXSUSqSMJ8oNRowXb0Hg4HutduBLzC7yTFPDHfiw2WYcHlPXJx9kaPfnccnWszFrnUnicQg_RKGw1_irBjd02GkgmrmOAam2dPjc86SJhvNR2QBnD97RvmT54QlJ16vxyP53Hw2pArAn2ANnexZFoJ-3rAclJ0tOpTDbz6Dis8dno2zaczz7Qb5yFheLjyuFqDamEUeE-MvyR7B5216m4lNywPt9rJxfVvfabOR52r15xELRHO_cxx5wzgMtG98wv2du4zGgdaKuIb3zD198RLZI8VLx2kEuiU72Qki7mrzO-QN4ezU_YHW5PB7uCOPSQF8Eh5oeKcxHPle10vgvr7zn1yPA_TnPxEL-vxA3zP-_C_dRfj__kfsfkScxYD65kHcKx7M1AuYtjIm-iNehNBYovkAmWhU1yASeNCHi16gZTpUi0-xtQEDd2lYL9IH1n5RnrJUibGGKilL1fhbZMUga1eecgKfan0wfwK0tflxOi07T6dNBjzQpmEKZNMgg-DD6SeoRT4mgKgczdBti7DRZPCIo73GLJPy2rISYnZYWe5eLUlJmoGRpSnZZFE48LR69OTtfGdR6mlNlvo7F5z1U36gXfC-SNTNqWm9v4SQWrrSIuP8UAxkpr6TF9MDrb07_7Mjy1ybPx1ohlVMXlJMpcWckNY-AVfIM0NhZnaPx4tpS7bEoX-osR0GquI_mU4AfiaLLRgq39SFSw_TbK9TQ4bWmNMV7w-JB0DZgbRCtFapMrVW6o955MV8UZhipcJY38WGrlasFoscrIW72FREpYuoOqASRVQhcs11Yw3pIs-wvkZAMI4EJRKUvgdF4O5InMYXJpaH2TV5unNnF1ZFgVPrdsGZ3SnkvXi4s4AwO5GfoyysFfruGyuuDIy1WW1uzHtrI4S9EQLRd8Wj44ez072vZ8Rmnc7stHPeH6zpDYptwDKanQkbabWHaRyDT_Luaslctwz1LRpWQ3unxQLUURgmcUmBlumyQagj7idbopz6LH7UiJJIeJlIpJx51YyAPwmNlhPSLMfNLG9NtMHBy-JpgwfOuT_kybaMlkSSWYbPhvA786HoxWUIk_JZhMrwo-ViAZWLPLrZPSqG3ZbssvAqqbhS3TFKyFOiBpJNbNyplh1e39J9y61cKr6MMkhKKaniiFJ6GqXNikv43SyXSaRc-JLto4yWL_slYhqVNj5RCQiqAlRC7A80P4qeLO8Fs0RUlnfDB8JFtSQLXMWsUQctYbm2OP-Ey5QYXNq8JcuFuj_LqEMU7ITKu4GWtpZRRhuVfCkf5BtEqg1Tf8nals2cMDLKPXK5-yzfTQ2Dntd_96bpRLzPOV18M7VZ-7nknVSYSd-_e_sQhj5nQb4P_h5JvPY6f3fhPfDh_kysw_23_0bUfwEyi-jM

* **Screenshots:**
![image](https://user-images.githubusercontent.com/11192114/114846467-07da1c80-9ddd-11eb-9f79-b00e5a161fb1.png)

**Comment by Nostrademous** [comment]
Fixed in #2528
