### ISSUE TITLE
[2.1.0] Total DPS is not shown correctly in the Build summary panel when equipping wand

### ISSUE THREAD

**Issue by jezznar** [PathOfBuildingCommunity/PathOfBuilding#2535]
* **What happened?**
Build summary does not show correct DPS numbers

* **What were you trying to do?**
I was creating a build for 3.14. Initially it did not have any items and then I created a wand which has some spell damage stat.
It says that I should be getting +150k total DPS. But when I equip the wand, the summary only adds 40k.

* **What steps will reproduce the bug?**
1. Create build using Incinerate + CWC + Bodyswap.
2. Create a wand with spell damage
3. Check how much increase you should have
3. Equip that wand
4. Observe the Build summary DPS numbers

* **Does it reproduce every time?**
Yes
* **Provide a build code:**
eNq9W-tv4kgS_zz5Kyykk-60DnE_3LajzJ6AkIRskmFDHjP7JWpMA94Ym_iRhDnt_37VbRNIhkfjHe2MxBi7nr-qrq5qM0f_fZ2ExrNI0iCOPtdQ3aoZIvLjQRCNPtdub0723dp_f9076vJs_GXYzINQPvl179ORujZC8SxC4LOAL-PJSGR3c1nkAe5NeZSNRRxd8j_j5DQefK5dxZGoGX0eDYJs_s0PeZpe8Yn4XLsPMn9cM3jqi2jQWtxvh2IiooyHQZrVjAkPol7sP4rsNInzKRhQM54D8XIZD4C2c9n9cn2zpDyIlpWD9Z-OuiGfiaSX8cxI4eNzrQEg8JE4C0D8Mw9zkIOwZ3l1YtcONrIc8wl8anP1pkIM3qi9Ov7nCLuJaA-Hws-CZ9FKgqw15pG_sJyt49uV9jIPs2AaBiJZoLKO_uwH0TKZ1hDfxJABx93egha5DmN1C_9sjniRBmutgVwdN0PAfif5nVEUZGKZBVOP1B17C8P7LPO89QzSrh-1IIyw7dUdZxNbNw7SOKqE1w4eteJJP4g-4LbNvDlT43mkb1wjEfzLsEj6az4I8nSRwWvjeskj3orTpUJA1y69bCnF8Vqya_H0jhKtXQ7H4nUR403ylgmZuzZ3ooUXhOAN8pYpkW2vt-85zqC-b18dF8Fwka6YrYcbypd_KKk7ka9TBCTpbZSIVCTPS3Vvk4r3LF2RwO6S6eq6FiMRLamps03UF0L441PYn655JrajJHNtYYhDNqMkqd-jxDYJXoHSJhXvWXZASTK-R8mx6nQT9Y4otSORjGa9cSDChSt0M1bLPMuYrd-Zlzneu6Nl2Gqf1sLQfubp8kKieIs_Bf2yK-sDImBbAoaB-LC3_kSObhL_KVuJcDe2RjKJ82Q7nfK5IF52eT1I3fEsDXzYitRGeS0Gua9XqN5aosv4WTWZqp-CVnJ789IMoQnV9RzEhuEqjrXVu5Fl3H88jgcjsZOSnThOggTQSoOl_W4fu9upv0D32-LT7QpasVxO7xVQsp1aW8FFMBpnEcwl-lo-sOj7MuZx-oMaHXJtFSd5-L5hJZgRUvdcil3bWZuKvcfgPV_G-6E4NKxXxF3B3OH6hRO_gGljOb2lGst-ifqSL3qQtVCfJCL6PtOW_45cS0E7GuSJzHVtHR85flRzdKDmW3nVmUzjJFM3Wzz0UyWyE03zzIjUaJpK5B-ifNKX807x76JmLFNOgtR_6OfDoZxTa2BMosbs9slJu3XTuWuXLD2hKpfhx2HIp6mAwTUKwpoRDMow96BY-5kGNQxX5dywnfaeJ34SAHzbSeV0pGGqGku308mJUYMM4sBDoQvRzWwqZMRTPZTKYrmdVs17GnTFIKXjlhrUdEAXPp9p0L21IRq07VA0glDueTo4XUL6FpulDjVsXknQzzOtjFLDgoYFslvWcGu5XdSwtGhJNOSWLdt2ynKL0Mkn6Ac0sT8WQwFZqrVC1aq_4Y8iKuvZvHYdqeWRGikUtVMxSZsz2DROJFIf5vJ3BLCdJDmUrIEY8jyU93_PeRhks1Ln4v5FcSKo7qbj-KWXT6eFJLkkU0D74qJ40gizUohU87k25GFans4pG9UpX0N1Zuq78kAd9QWRH-YDmBfLvXJuXcj7UnfNGMlTwVacR1lpiYjkbjiYE6ZhLA88BJ8Cfqj2UZNUIu34dASWlbynYdznIZ57pspwBhiXWtza_CwUW7V3LOhNqeTpyDR6ncrjz2gkm6mWOgF9KoDoqHWuoCzpuzzJlM8jMZFPL0XGBzzjB50MQDuQyB0om-EK-mSIXqKmj6d5eKwfnZ_LXQDqF07AldyoZOstjw4W0hTLZRCpg91ePpmA0YMu1MyMp5MiHddjpY1LmSotnmb3Y5grZFGOoJ0FpFYjtAmTt7TbKG4VPqvAkEKMFynFWBbzszxvxQksYNiBpz8pFVYI1HW1GQ9m6YvsVP_RqDcSn0eilycj8TeCvUqKruMFr1Ew_2Tv5ErvikhksJ7UUFrZw3WSdL2U_MaygJ_saS-Lk0mTJ4k6_a_s5koxuj52omEO--GPS_WoWCBqQyz2QXl5kwhh8KL8K35U7kLwZflNlLQagx5o3qFsUuRSkzquQ0yMPWwiGzHHRBZCtkldwrCJHWwRkyLqYBMmN88xKXaYBfeZ7ZkECImJPNsDeg_b1ETUsh3TRZ5rEorgEm5gZGKgcU2bMrjjUYJN16OuiRDFlskw9SypFEQ5xDMZKEOgzKHMxJLLsSgItmwEcjyLISnHo0DnWvBp2RYyEUGMmrbteWCOspg6ngdMridds1xXGkJBjceIDawMlDGKEXjCsAOfHgJ6xyOuicE-0Oe6jIEmm8ElcqhJMKE2qCBgvc0s7Jm2C77BU4xNAh5boFThSaSNxPUseYdQB8gp3JHn_J5JbcljEaDAjlIv9VCLSG2I2KDCwdIXy8VM2gJBcF0bPLQscAhjQAWsBGKHSl89RMAQjFyTOcBGHMQIKHct8NIi0m_XgWiC1R6IczwsAcYQO-yARxAkJk3zZKTAKSIFIBlGj4DjjiPBcgAfG8LuSdfAKcDBkqa5MicoIA33IW0IcWylVMbeYTDmGxlk5dLLVETL96QyC0nZnrQHMDsMrmRClsv49vpCXXwaZ9k0PTw4eHl5qU95No6H4hW2r7ofTw6mIAaSfV-t3X2p6KABf5qNy1aj2fyWv7Q73nH6cE6_uGwyPY5Hx8M-9zv9Rmant7OLl9NvmPUap-N7C7_efT1F39qPuHVhXZx_t04DMW3k3Zez_dNe4_cLgVqPXf_b17vp80nqnNx-71892c2LL_nD7Onq7nGEcXv23b36yqwJF_7IHTZCt93rd-5u2_39YRh9O79KBnarc3Y2vc2T8yC--mNoJTfP_p-34XX7j2_tJnk45d3fBoBTnzjHp0HoPjXI7czqPdyf_xbf97-fv1Ic8_55Owntr4ndfuyPxk0oMd4FT_KzP34X4WM3Zvftu7PT6OK2yYZ0nE7HvzXb3ZH3nDjTy0gBezBH9qh48ZwWMJffVFGQkUEM0gk61KwocuURxAo6WP2WBh0sVEJ16KjtEg06KFWejjzqMsfTkQdlTIPMo5YOKrCQtbwllOp5C7VURx5UUR0v5CrVUQsFVc885mBbg862oULqBM2zXB06qPiODp3jMS21zHWxFh34oQUzIzrhkJuSpRUOS0ctwgwRLTeIpxVdyBamE13Y3nWyAPYVLb2e4zk65rnU0VGLPQdhrWSG_kCrohHL1qLDrqtV0RyqVVtgb_W09DKm4wdyMNKrkNo1yNHbEaiWXgr5rJMu0Bp6WjuWZROdPIA2jmilPRjoaBU15urtWA7T8gMjplVdZM-pQ0cR08orTLTCa0HfqLVVelpFknlIq0bCULIiW2BMWnQ78AUmIjU8yZFJXlzFmVDP5M35FzVQ3QXixUgFT_xxL0vkodz3OJ58k--5cZ1QGD9gnVnEKc4CzwTPLvl0fgioaMuTRLs8R8x4dhwMhyJRZ6Dz8U8SfoWdyqnDpGK5jkdhXRbv3I_UYFkOdvK6J4pBEWbDnvDjaFAcAKrbctYt3tcAoTpCLY8Ar3kCk-ehcd24bu-pt6vGPY8Ge90kno6FPyu-tRI-hE780JBWwTMxDF4PjeJlrDqK_RIVyuxVDxvRQJ5sz2noG83_Eh6NxKFVt_8qxm45vStGOS4rgNDDXi8fLlOjvyRVIbn8EQd5o5G_gHz_pTyDPTSwtVcG-9Bo7sPfPaXgWjwdGszd60ymYeAH8inaWzLs34TtU-s__5Knsongcu4uYCos2HO8tY-Qs_xInUyUT34hyMhiY8Jfg0k-MSQ6e7-oW8omIx4aHOQolkJkcWQsYVF5exkPrqWJhjIUErpu18qwlicBMtBvEYccWJsWy9lw1Avj-du8-fFx74VPjUZ_lqYczCiW1YoVvIr1IxvWY9tM1YzjLK1o0CpfthjVFGG2I8sJzLGPBtEyCa8yiVSDVw8E_JPYaDUjWTVtrDqaVfJpSwTORDgR2a6KVmQSq6JnS_pBKX2WPxPYXTCpvopQFX20Wi6gaplHt4dHB9hdxa5Kr4qOa9Udu4I9FWog2aZmMDOKN887hm81ypXyy67CpLUkdQJRyU-7Mqy4QtxZtZVEqqUv2T3LaPWyXyGnUWXwiU5CUB2iCmb_jeZHM5LVo8AqZGX1MPyNdNEtyT317lhr1eiTVkDuOohGep3AzoViLbwVy4V-PKu4QzRwQtXDQCujZVfxRme9VE_yLSY1Jnm4Ym8rhkkYGNXZiDp2UD8XjaNhMPrhV6ByxAzkq3f1Sz31a5R-HIeCR-WhRvmDrZL76ODjf778P8vBccc=

* **Screenshots:**
Before equiping
![image](https://user-images.githubusercontent.com/13676977/114852965-e21d3980-9e15-11eb-8c99-b71ef0356ab1.png)

After equiping
![image](https://user-images.githubusercontent.com/13676977/114853037-f7926380-9e15-11eb-9d5b-4a450d962816.png)

**Comment by Nostrademous** [comment]
Fixed in #2528

**Comment by pundm** [comment]
fixed in 2.1.1
