### ISSUE TITLE
Agnostic give mana regen based on available mana instead of max mana

### ISSUE THREAD

**Issue by antilogos** [PathOfBuildingCommunity/PathOfBuilding#2548]
Create new character, get Agnostic, observe mana regen going negative. (don't get mana/life regen on the way).
Add Haste/Hatred, see that the mana degen goes to 0.
Life regen goes down too.

Agnostic is based on the maximum of mana (you can test in game by reserving 100% and you'll still have a life regen).

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2825.
