### ISSUE TITLE
Victario influence

### ISSUE THREAD

**Issue by erocano** [PathOfBuildingCommunity/PathOfBuilding#2552]
Not sure if it's intentional or so I can get to know the difference but the base Victario's Influence has a mod " (10-15)% increased effect of Non-Curse Auras from your Skills " and the PoB one is "Increased effect of non-curse aura you cast".

**Comment by pundm** [comment]
Hi,

["effect of non-curse auras you cast"] = { "AuraEffect", tagList = { { type = "SkillType", skillType = SkillType.Aura }, { type = "SkillType", skillType = SkillType.AppliesCurse, neg = true } } },

["effect of non-curse auras from your skills"] = { "AuraEffect", tagList = { { type = "SkillType", skillType = SkillType.Aura }, { type = "SkillType", skillType = SkillType.AppliesCurse, neg = true } } },

internally they function the same. 'you cast' was the wording pre 2.6.0

**Comment by pundm** [comment]
fixed in v2.2.0
