### ISSUE TITLE
Crashes when I view my passive tree since update

### ISSUE THREAD

**Issue by Joniano** [PathOfBuildingCommunity/PathOfBuilding#2553]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**  crashes every time I use the passive tree since the update
* **What were you trying to do?** use the passive tree
* **What steps will reproduce the bug?**  go to the passive tree
* **Does it reproduce every time?** yes
* **Provide a build code:**  https://pastebin.com/HTLdtwBc

Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
![Screenshot (1)](https://user-images.githubusercontent.com/82622117/114955038-c3c13900-9e29-11eb-8554-86365b265c5f.png)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by pundm** [comment]
Hi, i just tried it with v.2.1.1 and i can hover without crash. Can you please upgrade your PoB to the newest version and report back to me if its fixed? There was a bug with Golems that would cause a crash when 'Include in Full DPS' was ticked, which is fixed now. I See you are using this in your build.

**Comment by pundm** [comment]
Closing this, as there have been no news, I think it was the Golem -> Include in Full DPS bug, which was fixed earlier.
