### ISSUE TITLE
Bleed 'Slaughter' (axe, bleed, attack speed) and 'Splitting Strikes' (axe, bleed, attack speed) are weird

### ISSUE THREAD

**Issue by Mondaysoon** [PathOfBuildingCommunity/PathOfBuilding#2564]
hi,

I'm running the latest version.

* **What happened?**
Bleed does not seem to be calculated properly on the axe nodes leading up to and including the 'Slaughter' node (on the left-hand side of the tree). Or maybe this one axe node cluster is working as intended but the others (such as 'Splitting Strikes') are not. 

* **What were you trying to do?**
I was trying to compare dps with 'Slaughter' versus 'Splitting Strikes'.
The idea is that the 3 small nodes labeled 'Axe damage and attack speed' leading up to 'Slaughter' provide very little dps increase compared to the 2 small nodes labeled 'Axe Damage' that lead up to 'Splitting Strikes'. Also, 'Slaughter' itself provides an almost non-existant dps increase, and 'Splitting Strikes' provides less dps increase compared to it's small nodes. 

The common denominator seems to be that whenever a AXE+BLEED node provides attack speed, the dps gain is very low. Might be logical somehow to be that way, but I don't see it, sorry.

* **What steps will reproduce the bug?**
Literally spec into 'Slaughter' and nodes leading up to it then remove it and spec into 'Splitting Strikes' and nodes leading up to it. Splitting Strikes and nodes leading up to it provide a lot more dps while 'Slaughter' and nodes leading up to it is next to nothing.

* **Does it reproduce every time?**
yes

* **Provide a build code:**
https://pastebin.com/BiK5WPzV

* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
can provide if needed

**Comment by pundm** [comment]
@Regisle pointed out: 
"he needs to set warcry calc to max, or if he really is using it for average then attack speed isn't good"
![image](https://user-images.githubusercontent.com/54453318/115022065-257eb300-9ebd-11eb-88e7-f3f10f67eb07.png)

![image](https://user-images.githubusercontent.com/54453318/115022104-33cccf00-9ebd-11eb-80d7-792ebf382a95.png)
![image](https://user-images.githubusercontent.com/54453318/115022140-421aeb00-9ebd-11eb-8439-5af602239592.png)
