### ISSUE TITLE
Missing Builds and Regular Error

### ISSUE THREAD

**Issue by EnaTrimene** [PathOfBuildingCommunity/PathOfBuilding#2568]
Confirmed using v2.1.1

Added a new pastebin build (https://pastebin.com/2xWmqJpj) and keep getting the error below. Also noticed I cannot delete the build and the builds I added yesterday (and old ones) are missing.

Uninstalled and reinstalled, no effect.

![Screenshot 2021-04-16 102800](https://user-images.githubusercontent.com/82672918/115062097-d164d600-9e9e-11eb-8d4c-10995a5aa2e2.png)
![Screenshot 2021-04-16 103031](https://user-images.githubusercontent.com/82672918/115062104-d3c73000-9e9e-11eb-84cc-f430ca882a17.png)

**Comment by EnaTrimene** [comment]
I uninstalled and am using the portable version. It's working on this FYI.

**Comment by pundm** [comment]
Import works flawlessly on v2.2.1
