### ISSUE TITLE
Costs and reservations need some work

### ISSUE THREAD

**Issue by PJacek** [PathOfBuildingCommunity/PathOfBuilding#2572]
- [x] Some reservation mods get parsed but don't work (e.g. Curse Aura, Stance)
- [x] Some new mods are not parsed (skills cost ..., skills reserve ..., Chainbreaker rage cost)
- [x] Reservation doesn't follow the new rounding rules
- [x] It could be useful to have a global `SkillCosts` table
- [x] Cost and reservation descriptions in gem tooltip don't match the in-game formatting
- [x] "skills that cost x" conditions are not supported
- [x] Blood Magic like mods don't convert mana costs to life costs
- [x] Forced reservation from The Coming Calamity doesn't work

**Comment by caveirabr777** [comment]
Stance Skill Reservation does not work!!!

**Comment by Aurilux** [comment]
+1
Just want put in my specific problem: equipping The Coming Calamity does not properly cap Herald reservation at 45%.

As an example using Herald of Agony (HoA):
HoA w/o CC (Coming Calamity) = 25% (Good!)
HoA w/ CC = 45% (Good!)
HoA w/ Minion Damage Support and CC = 60% (Bad!)

**Comment by Kherae** [comment]
despite being listed in version 2.3 as updated, reservation parsing rules are still not fixed. good that the reservation entry here wasnt checked, as that'd be incorrect.  ingame, my Herald of Agony is 27.89% reserved. skitterbots 27.3%

**Comment by PJacek** [comment]
@Kherae Can you please provide examples of imported characters and/or PoB builds affected? You can reply here or make a new issue.

**Comment by Kherae** [comment]
After a re-import I found a gem wasn’t swapped out (likely in the shuffle when I was trying to get info on certain combinations in the build), wish I’d recorded before’ and ‘after’ to see what I was thinking at the time. So I was actually wrong. Yay?
That said, the tooltip on the skill UI for ‘enabling/disabling this gem will give you:’ could use fractional percentages shown.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
