### ISSUE TITLE
Error when importing minion build on v2.2.0

### ISSUE THREAD

**Issue by Razunter** [PathOfBuildingCommunity/PathOfBuilding#2573]
v2.2.0, trying to import (outdated) minion build from this link: https://pastebin.com/mdi27Kma

Getting this error:
![error](https://user-images.githubusercontent.com/362900/115091078-98247880-9f27-11eb-9421-f00755d8ba4a.png)

Previous version worked fine.

**Comment by fenume** [comment]
Same here, after update to 2.2.0  
Error: https://i.imgur.com/cC4YufW.png
Build: https://pastebin.com/2xWmqJpj

**Comment by Wires77** [comment]
Fixed by #2574

**Comment by LocalIdentity** [comment]
Fixed in 2.2.1
