### ISSUE TITLE
Earthshatter Damage Bug?

### ISSUE THREAD

**Issue by caveirabr777** [PathOfBuildingCommunity/PathOfBuilding#2576]
Have you made any changes to Earthshatter? I had 8kk total dps, after the last update it dropped to 1.8kk, without me making any changes everything remains the same.

**Comment by Sokipok** [comment]
My earthshatter dropped from 1mill to 300k. My bleed lacerate dps also dropped by about half, also without making any changes

**Comment by Wires77** [comment]
Fixed by #2580

**Comment by LocalIdentity** [comment]
Fixed in 2.2.1
