### ISSUE TITLE
PoB 2.2.0 incorrectly treats Assassin's Mark as a hex

### ISSUE THREAD

**Issue by SuperJelle** [PathOfBuildingCommunity/PathOfBuilding#2578]
Latest PoB update made the unannounced and incorrect change to make hex effectiveness reduction from bosses also apply to Assassin's Mark (and presumably other marks as well) when it should only apply to hexes.

**Comment by Wires77** [comment]
Fixed by #2580

**Comment by LocalIdentity** [comment]
Fixed in 2.2.1
