### ISSUE TITLE
Earthshatter Damage bug

### ISSUE THREAD

**Issue by caveirabr777** [PathOfBuildingCommunity/PathOfBuilding#2582]
* **What happened?**
After the update my total dps of 7.8kk, dropped to 2kk, a skill was not changed in this league.

* **What were you trying to do?**
* I tried nothing just updated.

* **What steps will reproduce the bug?**
* The method was for the game to update itself.

* **Does it reproduce every time?**
Yes

**Comment by LocalIdentity** [comment]
Fixed in 2.2.1. Update your PoB
