### ISSUE TITLE
PrismGuardian aura reservation, damage calcualtion

### ISSUE THREAD

**Issue by Spastic111** [PathOfBuildingCommunity/PathOfBuilding#2584]
In version 2.2.1, Prism Guardian man reservation seems to be broken. I have it slotted, and the auras are reserving mana still. On the previous version it seemed to be reserving the aura as life but the reservation went from 50% with my setup, to being around 70% when the new gems were implemented in POB. Im not sure if that's correct or a bug

also damage calculation in the left box isn't changing when I swap from one lacerate gem to another (for comparing gem setups). IT seems to be related to the Full DPS calculation.

https://pastebin.com/gMjnSuxX

**Comment by djsall** [comment]
The prism guardian text still says blood magic, but the 2.2.1 version changed blood magic to the new gem, but the item text wasn't updated, the auras inside the shield just reserve your mana.

**Comment by Spastic111** [comment]
Text from that updated item: "Socketed Gems Cost and Reserve Life instead of Mana", but the shield is reserving mana in POB. that's still a bug

**Comment by zackdave** [comment]
The issue still persist.

**Comment by Arcinsanity** [comment]
Not sure if this is important to note: prism guardian should not use support gem data. It applies the Keystone effect of Blood Magic to socketed gems, it has _never_  been the blood magic support gem.
