### ISSUE TITLE
Application error on start

### ISSUE THREAD

**Issue by DarioJahnel** [PathOfBuildingCommunity/PathOfBuilding#2588]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** Application crashes when opening
* **What were you trying to do?** Open PoB
* **What steps will reproduce the bug?** Start PoB (normal or administrator mode)
* **Does it reproduce every time?** Yesterday it worked one time after updating manually to latest version, today happened again everytime I tried to open the application
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

![image](https://user-images.githubusercontent.com/40502503/115118734-0e9e9600-9f7b-11eb-97f7-e57da8ced29f.png)

**Comment by Wires77** [comment]
Navigate to %AppData%/Roaming/Path of Building Community and makes sure you don't have "Read-only" selected for those files.  Running PoB as admin should grant it access to read those files, so double check that their permissions didn't change upon update.
