### ISSUE TITLE
Bladestorm's new "more damage with bleeding while in Blood Stance" is not working

### ISSUE THREAD

**Issue by Causener** [PathOfBuildingCommunity/PathOfBuilding#2593]
* **What were you trying to do?**
Make Bladestorm build.
* **What steps will reproduce the bug?**
New tree, add Bladestorm gem, acquire some amount of chance to bleed because even though the gem tooltip says it causes bleed the skill has no inherent chance to bleed. Toggle between Blood and Sand stances and see no change.
* **Does it reproduce every time?**
Yes.
* **Provide a build code:**
https://pastebin.com/5rP5nJCv

**Comment by Puddlestomper** [comment]
Is this still an issue? It seems to be working for me. Pastebin also no longer has your build code.

**Comment by Causener** [comment]
> Is this still an issue? It seems to be working for me. Pastebin also no longer has your build code.

It still only adjusts "Totals DPS Including Bleed" and "Total DPS" but not "Bleed DPS", I can provide another build code later but you only need Bladestorm Gem, a suitable weapon and 100% Bleed Chance to test it.
