### ISSUE TITLE
Unable to Ctrl-V items

### ISSUE THREAD

**Issue by Mr-Boof** [PathOfBuildingCommunity/PathOfBuilding#2594]
With the start of Ultimatum and updating to the latest Fork, for some reason I am unable to Paste items into POB.  I know the Ctrl-C is working as I can paste into a notepad, however even copying and pasting from there into POB it wont paste.  Not sure if this is happening to others or not.

**Comment by shakesx** [comment]
I am having trouble copying items into POB as well - it has been recognizing rare items as unique, and when I try to edit the item text POB throws an error. I know that ggg changed the format of copied items, so I think POB needs an update to process the new item format correctly.

**Comment by FabrizioMG** [comment]
Same issue here, rare items as uniques, can't edit them either.

**Comment by phobos1984** [comment]
same here. All items pasted as uniques, can edit them, however.
