### ISSUE TITLE
i can't see DoT damage

### ISSUE THREAD

**Issue by epiedos03** [PathOfBuildingCommunity/PathOfBuilding#2600]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![image](https://user-images.githubusercontent.com/26246287/115157240-2da83f80-a0c3-11eb-8c95-2c4ba6dd76b2.png)
DoT damage of All type work well, but in each damage types are empty

**Comment by coldino** [comment]
You have a different socket group selected in the Calcs tab than the one showing in the left pane, as evidenced by the different name. The `(Main Ability)` part shows in the left pane but not on in the socket group name in the Calcs tab.

Maybe you have another unsupported Creeping Frost socketed that you selected by mistake?
