### ISSUE TITLE
Holy Flame Totem does not have [# of Summoned Totems] under When in Combat in Configuration

### ISSUE THREAD

**Issue by ZefroseKingOfSpace** [PathOfBuildingCommunity/PathOfBuilding#2602]
Holy Flame Totem does not have [# of Summoned Totems] under When in Combat in Configuration
https://cdn.discordapp.com/attachments/483411093109080087/833426936893669406/unknown.png
Build code
```eNq9HGtT2zr28-VXeDKzO92pAUvyk6V3J4TQZgo0JaG97Zc7iq0kXvwIthxI7_S_75HsEEPzUHyZLVPq2Od9js5Dcnr6n8c40uYsy8M0eddCR0ZLY4mfBmEyede6HV4cuq3__H5w2qd8-ml8VoSRePL7wW-n8lqL2JxF71o2ammcZhPGvyxJkT-B1IwmfMrS5Ir-N83ep8G71nWasJY2okkQ8uUnP6J5fk1j9q41ZPEsollLo7nPkqCzetJL7oswD3kKD2MaJoPUv2P8fZYWM5C7pc1D9nCVBgLyqv_pZlhjHiZ15iD8b6f9iC5YNuCUazn8etdqgw3ohH0IOZCiUQF0kEE85whjq3W8FeecxvBbHW0wYyx4ArePkP3_hBymnMVw12cxS_gwjFeSG0cbsfoZ647HzOfhnHWykHemNPFrOm9Udm_gqyLi4SwKWbZC2AT_4VfahrFFcRqd9wcrK5mGaR95hv3aGOkqhjZK8zXk07MInLYXfYHVmyQhZ3uj9dMwT5NG2tSRNirUSeNRmOypzxKpPZ-oI7UzRj-Ny3C8oUFY5Cv3b0S6ogntpHltdVvmJtjLcMyewW5UujtQg7uBBKEGKeTsswySH1dDEMLuhTDgq5Xlko0Ss_s6IEIbF-E5e1yBmVvo1QE3StdLVipgsk28OuRW8eYph4qkZslaeBC0Jdn6JwK6l_grU-JtdG-TjOUsm9eS9DYOz1Eq96okOYF4wyZspa5zZFvWNvBLxvzpe6ioN5QztQB9gtplJAFcN9JWqmtstIX-c4w9TCQQn5sIoSO8DXpPC3UTlk0Wg2nIokBhOQo71VGU7FVHeK6MEsq-Gs1pXl9C2CTb1Snh1TzPoAoCQsBelPJXxOhn6X9F7xLth9bO4rTIFF1YAiup3J8u8tCH0iobxxsWFL5ahnpqwa7SuWzfZNsHXe_uVuksgn5ZVXEgG0V7YbQ5p_7deRpM2F5M9sK4CDOwVh7WqtwhdndDf4I-vUNnKj2MWE3PGWwO9RW0MoPLcDLlCUxQ6lxeoKjrMqVp_gsbFXBlFhdFtF97PLgLn2NwOorYiWY8IjL2vdFoozP76QMINRUjZq6wwGrQV3TVdWw08kXGkh8LZfrPwJUYdJOgyESUK_N4iaHEpi2zgxzxLsO4NsuW9e30WE7t4qoXz9KMy5sdGvm5pNdLZgXXEjlvx2Hu_zkqxmMxVLeAfia3BLoXF93OsPelW4lQR8mFe_9Mingkhrfy31VKGjCZ5TQ_jSI6yxnM42Ma5UA7DKrQGEBm97kSPIx-1dytAv2VZn4WgtlVgMX8piSynLlVIMVcqwQIXqERUzfYcDFjwv25qs2qVKsCLadTJchytFRTUA6vam5gPl0oQT51M0rQ3Yi1w0hUTzWrXcFCKAuvGjyUwiwcFVwx2uTUoSSHaLyVFKz3n0oSl32OEu2qE1SBrYqPWqxBr6HsjXM2ZhDFiqtZZokhvWNJlQOX-e5ULqFcyyERvmdxfraA0nQhrPZiN-MZABStrADaARvTIhL3Pxc0CvniXSsJo_r9y3JvVN7Np-nDoJjNSkpi2eZg98vL8kk74hURwWYpfqmckFFueJa5XX6WGshdzzDxoyKAQbSqxUvpIjoSvFvaRGyQdtIi4ZUkLBE1N1gCvqAsiAq-v52CJBXs-ygd0Qg_WbXa88VG6xkAWpKUZaAHHC4iKAuyGLW0-1K_nlzY0kIgG4vF5yvGaUA5Pe4BZH4sTHAshYGrNSREzXyphV8qCAYRlUj045Dt0mihSXytIiAFuwoTuT89KOI4BQ_3ISNymsdlML2K3pWjIdGILEOji9QXe1T7muApXDYQUjXEE7pW4r-6ou0gYIFot5c74Y013URJVVWJrwkCWr07eE1lBzzN4jOaZXKHurGma8moqtlLxgXkOU1U8wSmKOjMXl9RYcU-SxjPaDmdNtZ1EyVVdaU_6wReXddOmvAMygckfAad7nIeb6zxdnqqeq-oaHUyZdUrU6QsaGUdE5fDjDGNlulckkBVFYEP9SM1oYFgBa091BHbsAykO6Zp6oQ4jqdbjkl0bHiuo2NiYEcnDrKJbiLTwbqJHdvQbWRhS7eI6RG4xghgbNPCOjIshHTTILatmx62TN3xANy0xA1kGhgBdQM42cg1BD8PEx0hExu6ZREC5G3XxPDUdJCOkWe5OoaJEglcC8QxABQoOKatW6btmcDQAUjL8kAQhA2Qhni2pWNsuK5AMoG5adlAGCA8uHYEQwL4jkdc0MlzDB2bBJu65RmGpSPPJpZOELKI7sF94ECAgQuyC6GBmWki19SxjR1Bm5iObjsIgy4mICKwiA03bFPw8jwd2Y5n6MDL1oknLl3kgVII8HXXBU6ghQe_bccFLhi5um1iZAAhG_QglgOSIc8EC5sEgZLYQ4IqCALMCLKFCYSE4DoL4AELpMUWSGuagCY86ILGhis8BfZ2hY8cwDWEnmBEMCsxEfxGyEDgNVCupXGIpNpZLjKrY1oROVbVInQD6OWDaxFE1Yq8vbmUF79NOZ_lJ8fHDw8PRzPKp-mYPYYRO_LT-HgGZCBAD-UiPBSMjtvw56x9e9b-9Pjlw83g3H38Pr8d8--u1c3SSSfpXJ8jZ_H-0_fOXT-hTvv71P2WD7_hx8C5db8uupPFwsedAT6ct8df_O-P0-FoNrx3pnf8a_xx2qfF58GPwwB9HZyPvmXTy_Oubf84u-2N2_f9xR8Pw3h8u_jBRt073P78wep8zOP3lGXDnH7qfRx9iiZ09NH58_P3b3f3M1702t-H55NrdHfxtX9TXN8f8p41-FZcDTzoov_o9Qc3-Y9Rx59PvOLDd9_4mpmIflzcX3v2t9lwEV-ib-8vRoO8172YvJNGO15a7bQ8085LE1af5CKV69WG2ICOj5cJqNo4WAMHkWsowEEsE1MFzrRcogCHseep0DNdWBAq9GAJKoB5pqFiFVhfStpiD5ayChwsYiV6pqeihWUi7KiogWw1Z7imY6nwtZCnEiwiuSjxtR2swtc2HKIEB9lLJaZs0EMFDsqBCj1IzogoucNQYYtE7VFSgyjBYfCGreJdKJ8qViZQ0pXkg6qjwhfKkqNkZtcktlJUQVFWkc8zXLXUh12lVGpYBCutDs_1lPiaSmGKHIzUUqRaErKRbSvZz0S2El_smCr2g1bQc5XiCqvFn-26WC3pKsWf6dmuWslybKV4wchWyfbENJWyOCE2UaEnWmyVUul4SjXG9pS42h5SW2zEWJOEYGxZdTvwASYUOcyIEUZcXKecyWfi5vKDHHC-hOxByxnN_OmAZ2KT60eaxt9EMbOPCLTHFoHuW_RKYm_tA6P8is6Wc5YArTbmKgCxf34ejscsk5uKdcA_wLQEHxHXg0wFjbVTnmydypmvmrPE9YCVoxsM5QPmp0nwldFZmsjbtb08AarNaRZSMerhcn-y2m-7gdt8caLdXvc-33YPvhQR0Cnyg3MWp4l2TicTlh18KXFPtD4MxOTIOjJWtzpFBgrwg_IMBUbGpyf4OZFqpxHuGweVC060s0P4OZCGuWH3J5rtHvTiWRT6oXiKDkzjH2KvMWNU7DuU07QmjjXEObYGbgjvmFYeLhz8ldFkwk6MI-tnOwhy7Y1rHcJo8S-Np9obCIZD6E__pS0PwauNml-xJKRdocE4d4hN-FDb2zn4q7LlCf5pgXy-ZC_AfQqe0OQBRphMNND9Q8hX4OhnnZk8uc61h5BPNT4Nc610nhYwEO6NC0IYS9ltEEJ8oC-3mcTjJ3bdhMUhy1-d3wuLCZDyOCVYx3IjnymdMw1bdXuFyRhczVcq0AkNk5xvpo_rKr1xLCl0PUTqxpEigAdgySSBtjx8eWKy2XA7ubw0yQ5OL9Xpzlm20FxIJmLR5rom4LT2nHKaaem4VGKcZpq5BNngVOk2_Fy29atDe5jCHKwt0qJ0xHNmm1RfRsLfpi_WCVy_tFsnTcAUwjQQDVJrRTHRz7fgE0Mrj5BqWEEKBYDv0vEt3hdZVI6rNLgRttGkhcR7y1aZS_GytmyEIDshrJ0Q9k4IdyeEtxNi-UbjNpDlW2tyE3JNiSFLs6wrMcPiLp2C-_8JWSH_d65dpBnPWA6rYpQmC20o3qHQylPEl4XHqBee8pajVovIOuprK9LNIfzUKxJ6XpFWUaST-lp5-wZKBSkzaEwfw7iINXHG-qKEySOhNbXnbT0DP8Pv0Cp3FjPxDImsHIoNWVhGJbW8OlLSKNeoxsOYHbwlq_ieCY2XIBLj4CxK00C7opPQXylEfl6BK0R9hVUZyj3fHXGgGvYvAgX6ky0tS707OR1E6fItj6qMoMEDnWnt0SLPRQ4qe751fd4a1JdoWA1tO9RZmkKqbybQOl12CHXGIr4nykVE8zuNKImE14lEmplXzQj4ldDMZkLazbjZza3ZJJ52eOADg46D78toTSTZTfjsCD_o2ufizbP9CZPmqwg14Wc2iwXULPLM3e5RMey-ZNeFV0PFlfKO1UCeBjmQ7GITLJYFcT_3rbdyo_iymiApLUkVRzTS02psVtzA73azlUSahS_ZP8rM5mm_QUyjxsYnKgFhqgA1EPtvND-KnmzuBbtBVDZ3w98IF9WULHAVV406aAPL3YidFNwkxeDG5m2YLtT92UQdomAn1NwNZmNrWU20UVkvzYN8h0jtuIjW1LZynISRUW7cy01x-X2CNBmHk1--HSCGTDkvy9e1xStr2ihNI0aTasv91y8UxE_fBe_QnF_CX7ccVvPV1wuMNXhPrMTevpjQs8V2BJaweNHLz9I8X33VQf5vAdUrw5VKp8cv_yOE_wGfSOq2```

**Comment by Wires77** [comment]
Use the count box to set the number of minions, totems, etc:
![image](https://user-images.githubusercontent.com/1209372/115906492-32efec00-a42d-11eb-8a17-929a7390c1d6.png)

![image](https://user-images.githubusercontent.com/1209372/115906503-371c0980-a42d-11eb-82d1-f87c963f5f95.png)
