### ISSUE TITLE
Reap has maximum blood charge by default when triggered

### ISSUE THREAD

**Issue by loldebyte** [PathOfBuildingCommunity/PathOfBuilding#2605]
Reap assumes maximum blood charges by default, but it shouldnt when reap is triggered since a triggered Reap cannot give blood charges.

**Describe the solution you'd like**
Allow number of blood charges to be configurable

**Describe alternatives you've considered**
Set blood charges to 0 by default whenever reap is linked to [CoC](https://pathofexile.fandom.com/wiki/Cast_On_Critical_Strike_Support) or any trigger support gem

**Additional context**
I'd get a PR running but i'm a complete newbie in lua so i figured i'd better open an issue instead

**Comment by Lothrik** [comment]
You can work around this by putting "-5 to Maximum Blood Charges" on a random item, but I agree this should be fixed properly.

**Comment by Wires77** [comment]
Reap now gives Blood Charges when triggered in 3.15.0
