### ISSUE TITLE
Punishment Curse DPS calculation/For Effective DPS:Is the enemy on Low Life check

### ISSUE THREAD

**Issue by netoprax** [PathOfBuildingCommunity/PathOfBuilding#2607]
**What happened?**
Selecting Enemy is on Low Life under "Configuration>For Effective DPS" doesnt affect the DPS 
**What were you trying to do?**
Get my DPS change when an enemy is affected by Punishment and on Low Life
**What steps will reproduce the bug?**
Put Punishment as a skill, select Configuration>For Effective DPS>Is the enemy on Low Life?
The DPS wont change. 
**Does it reproduce every time?**
Yes
**Provide a build code:**
eNrFW91z2rgWf-7-FR7eGyx_u0N2hyQkYSa03JC2996XjrAFaCNb1JZJ2b_-SrIJDjFw7N2Z2wdq7N_5Pjo6RyaDP34lzNiQLKc8veyhC7NnkDTiMU2Xl72vT7cfg94fv_82mGKx-rK4KihTT37_7cNAXxuMbAiTdD1D4GxJxLcdJ_uH5LTGqVgRnk7wnzy74_Fl7zNPSc-Y4zSmYvctYjjPP-OEXPZmkSTuGTiPSBpf7--XwATTdMajZyLuMl6stdgNJS8THkvMeDL98vhUE0rTulCp84fBlOEtyWYCCyOXH5e9YSTohkiolPtAEyokR8wKyc7r9Y-QSG_hJbmvYc0z2BucyM_z8NmakPgVhi6Q7zm-6QaBZbv2_59ompHRYkG0y64zKq5XOI0AZrXFTgom6JpRktU0dI9R3L9jjsyj7J-4wOxmOjuvSFskB6TDdypWV0x6HsRXocfLlAoChk85zXnaSmsQ-Jonc5oC9d6Bh5vlefAEp_ia53vn2cEx6ANdkDfQo0xHMxjuUa5KGFKpOSWZLEsCRqCUbUUwE_tst45rTH7WgeFRZ92QXzB2deBR3DgVMG51IHLd49ptuNClHuLHfU0-VTmjTwo7TiMY069pRnKSbWpl0AMSVHGF1BtF-EiWBGjpAyHR6k5uc49YEFhWvqLc085RWJBzFLDBOS6QoIVzFOGBcy7CU-CW7hmlJFtuZytKWAzafKNPdRKQt-oEwEDXSdpatMF5fdm4wWlrSjgs7ERuTJIgJge7qRX8gyTTjP-pGgjWkm6YJbzIgEEswSCrp6ttTiO5EeoO7ZHERQSrS6-N0IRvSCITXndUshPdJ_4x0isme1hoPyTZMtaKYigEjp5veLwkrYS0orilmfRWTms720cPgP4iG-JrvIY0EWo9QQXs0WABD3S5EqkcZuBSDkjgtqwwz1sYs4eDRdwWDNaszp7pW6TAc0Y-GeYvy7aDMPKOL13-IpVZqTEvByysGnqC9y3G0eHiNiPpX1sw_zdwkIBRGheZym6wjEMKkJjzE2X57OyUGJj-heP6fuDayHeOEr-d5MyLwJWDnLn7PEb1brrxQvMC2U7ghpbjeuFpuoZZ5x2ycdYBSmmefFoQv5-DWtrXtJbegZumIqCct22t73ungM19RSP0dD_xjuRkh3QSDdQJ2usM-vo8SV2NkzXPhL55jVmUa8bjdF0II9WHQbkqYT_SIpmrA4Ly__12W0cmNI9-zIvFQp0Q9aRKmT7WGt3ejq6fxt9GFcmM6E3fiDhjeJ2T-LKXUtYzaFzVy5lsdCIBQN9TUa3i89jvOIsyKuvQeahacABVdSU4j1NHLACYjANmBOqip-2aqLjnMC9VfcZ5rC4hAFy54iFm6boCcTqJ8BaAe01rAHbEyJAy1S5C_DSR6Vv2mRC07PsyOi8EKKN0_QFooAZMgFn1MgLQtGzmAXyrcec8suquIPkkW2mg72_IgsgsBa1Qveqf8DNJq3q2q10DvTxyI5dF7Y4k-dVWbhe3ylMHG8gbgOzLskKWrJgscMHU_X8VmFGxrWTu7z-UJ_D6br7iL7NivS45qSWZS28_PJRPhkxUTJSYy94Cs7w6F9c66vP1sn3R37UF-pCdphErYjJOqzazEsfwXInuGUt1HH_Ni1RUT0iqusp4Z8UBY8VTif0wkIpU2DvG55hZO0MUrNpM3qpSe1LdfMRUxuK_ypVSVPVCwjJ7bxijnSqafhxXZDuqQ3la1M_SWWNdC7S7K-AUZ0IjliRRTydE4BgL3B8L6di-8m5fs5FXb8T83MXQfOeiqPSeZKq2LjXGVioaDToeGN0_7UywS6ZFSvNVok9vmowHmNvAAmptjbRcbyVTvZjKNaQunzJCDFzmkiZDVQbLL_X3RkpRKTeVG3-uzkkC2-4ZQhLX3lAhp3r5VIJLL45iuT3EnxVd5devjw_64sNKiHX-qd9_eXm5WGOx4gvyizJyEfGkv5ZspE4ftTM_KkH9ofx3pT6Gl5eaUX_HaVC-xcpLttU3ravSBHkWCuSiE6W7q96qAYeQawJwHgpsB4Jz3MAG4CwrDCH8nMDzQwg_GyEALHRMiFdszwNZazsOzFoUBhB-lhNCrLBt34WItZEHU8_zLReAc10UQpLFCc0AgkNyKIXg_NADifWCwALhpB0gN3s2JByO6ZgmKBwmRCyyPGSDzLBDUHRltniQ6IZuAMkC5IQguaEf-hD1AseHiLVCH1mgZEahB6potumCcFYQgCqa74Bqix0GIUiu50HsQL6FYBUSXIN82I7ggOQ6Mp8h6eIiWSQh9pquDckDFDg2KO2lgj6oqHkBbMfyPZAdFvJA1QVJhhCcgzxQXlk2KLymb7ugrTIEFUkvRKAaaflN2SK7t323I7_IRk33dKqTUxefuRxZ1TN1c_dF93nfKHkxcoKzaDUTmRo0_uI8-Y9u7NRAc0-wmOB11eaqZ9UwZFejkMDihsoBOtNj3K75VMB_vx486Sa26ijV9YyUjWmREznw8TT-TvBajgWkmm3KQ6YSeBSkZ8LdkDNjfHcgVcIMNHvBa2M43-Y5ZkblxoaINZEeklkwstOoK85F3lGhJlvOKHVFmGhJciv79GfDBqlkNalkd3MvzAnWP0TmdFPS6ybN6-7NLvl0JgL3hCVEtBXUkEleFzln0k-OzBv1yqg9Y7v7KkJd5DndcgF1yzznfHggjm3Ltim9OhoOqjtuB3061ED7nJh4a5SHpy3D1-zlTvnldiECLUlIIDrZ6XZ2q9Uh7l63lWR3S1-7fZY53ct-h5xGnZ1vQxLCgYA6qP03mh9gJLtHweuQld3D8DfSBVqSFS1w1cChHTz3SNMlrBNoXSiOurdjuYDHs4s5NsBPqHsYnM7ecrtYA1kv3ZP8jErDpGANe9ugX82QehbWQ6j-xQNPF3T57ocMasSk6uXjKCXJ9oG_lL8fmXPOCE6rwbZ671hxGPQP_2bnf0IxxQw=
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment]
Fixed in 2.3.0
