### ISSUE TITLE
Aul's Uprising reservation not working

### ISSUE THREAD

**Issue by bluo999** [PathOfBuildingCommunity/PathOfBuilding#2610]
Reservation with Aul's Uprising amulet no longer works. Tried both Pride and Wrath.

* **Provide a build code:**
[https://pastebin.com/SKx2XryH](https://pastebin.com/SKx2XryH)

**Comment by bluo999** [comment]
Also found a bug with banner skills not reserving mana (18% unreserved doesn't change when activating dread banner). Couldn't produce minimal working example:
[https://pastebin.com/SKx2XryH](https://pastebin.com/SKx2XryH)

**Comment by LocalIdentity** [comment]
Fixed in 2.3.0
