### ISSUE TITLE
Wording Change for Essence Worm affecting imports

### ISSUE THREAD

**Issue by isherzad** [PathOfBuildingCommunity/PathOfBuilding#2611]
* **What happened?**
* Essence Worm's Socketed Gems reserve no mana modifier doesn't work because the in-game wording has changed from "Socketed Gems reserve no Mana" to "Socketed Gems have no reservation".
* **What were you trying to do?**
* Import a build with essence worm equipped
* **What steps will reproduce the bug?**
* Import a character equipped with Essence Worm ->Reservation Modifier is highlighted in Red.
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
https://pastebin.com/3WFN3ZYW

Using the dropdown to import the PoB version of Essence Worm will still work for now.

**Comment by Wires77** [comment]
Fixed in 2.3.0
