### ISSUE TITLE
Shock issues

### ISSUE THREAD

**Issue by Regisle** [PathOfBuildingCommunity/PathOfBuilding#262]
Shock not displaying as a debuff, also shock capped at 50% when its possible to get higher, as well as the default is nothing, if no value is given it doesn't apply any increased taken
https://cdn.discordapp.com/attachments/676256416218218496/683522033379967037/unknown.png

**Comment by git42leech** [comment]
This is related to #446, since you can not apply the Overshock value manually.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.3
