### ISSUE TITLE
Importing Abyss Jewels with Added damage to Wand Attacks are not worded correctly which makes the not recognized.

### ISSUE THREAD

**Issue by MeavesMev** [PathOfBuildingCommunity/PathOfBuilding#2624]
When you import a character with Abyss jewels that have the line "x to x Added (elemental or physical) Damage with Wand Attacks" it won't actually add the damage to your character. The line appears to be red since I assume PoB doesn't recognize the the modifier.

The first 2 mods on the item work correctly, the last 2 aren't recognized.
![grafik](https://user-images.githubusercontent.com/62435840/115434857-766a1080-a209-11eb-8fba-fd7e420eb30f.png)

This is how the Item looks in PoB. As you can see the mods are red.
![grafik](https://user-images.githubusercontent.com/62435840/115435545-3eaf9880-a20a-11eb-8d3f-966410649463.png)

Here you can see that I manually changed the wording of the mods on the Item and now the text isn't red and its actually adding the damage correctly to my build.
![grafik](https://user-images.githubusercontent.com/62435840/115435425-19bb2580-a20a-11eb-9d73-58cee78b4247.png)

Here is my PoB so you can look for yourself:
https://pastebin.com/wn3VEQNi

And again with all the fixed mods on the jewels so you can see the huge difference in dps:
https://pastebin.com/8kkqvnGE

Thanks.

**Comment by PJacek** [comment]
Fixed by #2596
