### ISSUE TITLE
Error when hovering or editing bow item after auto-import build

### ISSUE THREAD

**Issue by Hadik123** [PathOfBuildingCommunity/PathOfBuilding#2625]
Hi, I have imported a build that I am currently running and when I try to create or edit a bow the error doesn't let me.
The program is up to date Version: 2.2.1
Below you can see what pops up when I even just hover over some bow.
The issue is occurring when I try functions ''Craft item...'', ''Create custom'' or even just by hovering over a bow item in the item list.
I have tried to open a different build and when I don't use the character import function it works fine but as soon as I use the function the whole build is corrupted.
When I try to create build code and import it then the error is still there.
Build code: https://pastebin.com/fwKTvF3T

![image](https://user-images.githubusercontent.com/82848339/115457071-40865580-a224-11eb-9691-be5bff32b477.png)

**Comment by Hadik123** [comment]
I have tried different things now and it seems that the error is showing only when I select the main skill.
When I select a different skill then I can work with the problematic item normally but as soon as I select the main dmg skill it shows again. In the build example, it's caustic arrow.

**Comment by Nostrademous** [comment]
I assume you have mirage archer in the build?

**Comment by Hadik123** [comment]
Yes, I have created a new build and migrated Raider from my POE account.
BTW I have found a solution. If you edit a bow item with not main damage skill selected then the error doesn't show but if you try to edit any bow item right after the migration and with selected main dmg skill the error shows.

**Comment by Wires77** [comment]
Fixed in 2.3.0
