### ISSUE TITLE
Skill Effect Duration doesn't affect Exsanguinate/Reap/Corrupting Fever DoT DPS

### ISSUE THREAD

**Issue by Eliteish** [PathOfBuildingCommunity/PathOfBuilding#2626]
* **What happened?** Take Potency of Will notable
* **What were you trying to do?** Increase the DoT part of the mentioned skills
* **What steps will reproduce the bug?** See above
* **Does it reproduce every time?**  Yes, 
* **Provide a build code:** https://pastebin.com/ytpDumeg

Shouldn't Skill Duration be increasing DPS numbers?

**Comment by LocalIdentity** [comment]
Duration does not affect DPS, it just changes how long the DoT is on an enemy
