### ISSUE TITLE
First Among Equal value is still at 8% when new patch is now 6%

### ISSUE THREAD

**Issue by baseballbear** [PathOfBuildingCommunity/PathOfBuilding#2632]
POB:

![image](https://user-images.githubusercontent.com/5081043/115504404-79690d80-a2aa-11eb-84b4-7861c030aeb2.png)

POE:

![image](https://user-images.githubusercontent.com/5081043/115504450-8c7bdd80-a2aa-11eb-943f-123bf35bf070.png)

**Comment by pundm** [comment]
Can you please check if you are on a 3.14 build?

**Comment by pundm** [comment]
![image](https://user-images.githubusercontent.com/54453318/115703904-f6f45280-a36a-11eb-86e5-86641ba14be7.png)
![image](https://user-images.githubusercontent.com/54453318/115703964-083d5f00-a36b-11eb-8cdb-631d0b8832c9.png)
![image](https://user-images.githubusercontent.com/54453318/115704321-84d03d80-a36b-11eb-99e0-b99b483eec77.png)
