### ISSUE TITLE
Indigon's effects barely show up in newer versions

### ISSUE THREAD

**Issue by akvgergo** [PathOfBuildingCommunity/PathOfBuilding#2634]
As the title says, having a character with Indigon equipped doesn't increase spell damage or mana cost regardless of the "#mana spent recently" config option's value.

Oddly enough, this doesn't affect old builds, so importing an old guide and setting the value will result in correct damage/mana values.

This is an older build imported a few weeks ago, here everything works correctly: https://pastebin.com/izL9fskU

This is the same build, imported from the same character (Minimal changes), here indigon will only start having the expected effect once we set the mana to obscene values: https://pastebin.com/8Ruhts4V

There was no change to the calculation in-game afaik, so this seems like a bug.

**Comment by LocalIdentity** [comment]
Ggg changed the wording in the 3.14 patch and we had to update in PoB to match. Next update with this fix will be out in the next 12 or so hours

**Comment by Wires77** [comment]
Fixed in 2.3.0

**Comment by LocalIdentity** [comment]
Fixed in 2.3.0
