### ISSUE TITLE
Contacts are not valid anymore

### ISSUE THREAD

**Issue by Soulprayer79** [PathOfBuildingCommunity/PathOfBuilding#2636]
Hey LocalIdentity and git admins, 
I've searched the Discord handles which are documented in CONTRIBUTING.md but I can't find these accounts anymore. 
So, how can i contact you for write permissions to dev-branch to let me do a pull request for PoB?
I get a 403 when trying to do a pull.
Or if further contributors are not added anymore, how can I send you my QoL improvements, so someone else can add them?
Thanks.

**Comment by ppoelzl** [comment]
The list of account names is up to date, all of them exist and are active. Sounds like the problem might be on your end instead.

You don't need write permissions for a branch to create a pull request against it. That's (mainly) the point of them. What you should do is follow the steps in CONTRIBUTING instead. Note that you have to create a new branch and push your changes to _your own_ forked repository, then create a pull request against the dev branch of this repository.

**Comment by Soulprayer79** [comment]
I don't know why I can't find the tags in Discord. Maybe they are offline, maybe they've set themselves invisible.

After a bit of hassle with GIT I've managed to do the pull request with the Github Desktop app. 
I hope I can help new PoE players with this small QoL improvement.
