### ISSUE TITLE
pastebin import crash

### ISSUE THREAD

**Issue by Iloei** [PathOfBuildingCommunity/PathOfBuilding#2640]
Version 2.2.1 consistently crashes for me when importing builds from pastebin, like https://pastebin.com/b67GAarj to a new build

* **Screenshots:**
![pob-bug](https://user-images.githubusercontent.com/1270846/115611812-9278bb00-a2b8-11eb-8d93-723f96bd423a.png)

**Comment by Nostrademous** [comment]
What kind of builds are they? Anything specific about them?

**Comment by Iloei** [comment]
That build was a pathfinder build, other builds which failed were necromancer builds.

I was focusing on builds suitable for ssf hc, but they were other people's builds and I have not been able to inspect them in the application so I do not know much about them.

**Comment by Nostrademous** [comment]
I just imported the above build: <https://pastebin.com/b67GAarj> into `dev` and it works no problem.

**Comment by Wires77** [comment]
@Iloei can you make a fresh build?  What happens if you export that build and re-import it?  Does that work?

**Comment by Soulprayer79** [comment]
I think it is something like this:
The pastebin code has a status where the Power Report-Status is saved within and opened on loading.
While loading the code and drawing the power report, there is a query on the bandit choice (self.calcsTab.mainOutput.ExtraPoints) 

So it might be, when the computer is a bit slow, the import of the build might run into a not fully initialized PathOfBuilding and the reference to self.calcsTab.mainOutput.ExtraPoints in build.lua runs into an nil-error.

I've done a check on NIL on my latest commit (2646) to take that into consideration

**Comment by Iloei** [comment]
The latest build (Version: 2.3.0) now works for me!

Very nice!
