### ISSUE TITLE
New unique item Ancient Skull not work well

### ISSUE THREAD

**Issue by chawol** [PathOfBuildingCommunity/PathOfBuilding#2647]
Ancient Skull say Minions have 50% increased Critical Strike Chance per Maximum Power Charge you have
but when i add passive tree to get more Maximum Power Charge , and  Critical Strike Chance of minion does't change

and there is a skill call whispers doesn't show in configuration

**Comment by pundm** [comment]
If affix text is shown in red, it means its not implemented/not correctly parsed yet.
![image](https://user-images.githubusercontent.com/54453318/115703125-07f09400-a36a-11eb-8ae8-169a23b50169.png)

**Comment by PJacek** [comment]
Fixed by #3175
