### ISSUE TITLE
Self-Fulfilling Prophecy - Notable

### ISSUE THREAD

**Issue by LocalIdentity** [PathOfBuildingCommunity/PathOfBuilding#265]
+1% to Critical Strike Chance of Herald Skills (this is base-crit not % increased crit), +25% to Critical Strike Multiplier if you have dealt a Critical Strike with a Herald Skill recently.

**Comment by meatballing** [comment]
Also small passive "10% increased Damage while affected by a Herald"
https://i.redd.it/uw2varmp2cj41.jpg

**Comment by LocalIdentity** [comment]
Added in 1.4.158.1
