### ISSUE TITLE
Mana reservation is calculated wrong

### ISSUE THREAD

**Issue by MarekDzw** [PathOfBuildingCommunity/PathOfBuilding#2652]
If any aura reserve X.XX% of mana then it's incorrectly calculated in POB. Seems like now we have floating numbers for mana reservation value, like 13.35% etc, but POB still using non-floating number doing "ceil" on floating number. So in POB 13.35 becomes 14% which in larger scale, where there is multiple auras on and more reductions to mana reserve will show incorect values.

**Comment by PJacek** [comment]
Fixed by #2644

**Comment by LocalIdentity** [comment]
Fixed in 2.3.0
