### ISSUE TITLE
Wildcard searches for unique item mods

### ISSUE THREAD

**Issue by seankioski** [PathOfBuildingCommunity/PathOfBuilding#2656]
**Is your feature request related to a problem? Please describe.**
Searching for specific mods on uniques can be difficult for some modes. One common example is finding all strength stacking uniques. You can only search for "per 2 strength" or "per 10 strength" when I would like to see all items that do something per strength.

**Describe the solution you'd like**
The filter textbox should allow an asterisk (\*) to be a wildcard. This would allow the filter string "per\*strength" to match both "per 10 strength" and "per 2 strength", for example.

**Describe alternatives you've considered**
Search a smaller portion of the string, such as "per" and going through the small result set manually.

**Comment by ppoelzl** [comment]
You're able to use Lua patterns in all search boxes.
