### ISSUE TITLE
Relic of the Pact reservation setting request

### ISSUE THREAD

**Issue by Spastic111** [PathOfBuildingCommunity/PathOfBuilding#2657]
**Is your feature request related to a problem? Please describe.**
Relic of the Pact scales off of how much of your life you reserve, currently in the POB release adding Relic of the Pact, you cannot set how much of your life it reserves, affecting your damage calculation.

**Describe the solution you'd like**
Please add a setting where you can set how much that Relic of the Pact reserves *Per Tick* as well as *How many Ticks* you reserve for.

**Describe alternatives you've considered**
No other setting seems as useful to determine Relic of the Pacts damage calculation

**Additional context**
Please add 'Average Hit' in Relic of the Pacts 'Calcs' page, in addition to its DPS calculation, for continuity sake

**Comment by Wires77** [comment]
You can set how much life it reserves by adding support gems to the wand or increasing your reservation in other ways (e.g. Essence Worm)

Number of ticks you channel for can be set in the stages box: 
![image](https://user-images.githubusercontent.com/1209372/115789172-50b84500-a38a-11eb-91b6-3d292dc60ede.png)

There is an average hit for this skill, just make sure you have the skill selected on the Calcs tab:
![image](https://user-images.githubusercontent.com/1209372/115789205-5f066100-a38a-11eb-9acc-ba09445fc21f.png)

**Comment by Nostrademous** [comment]
@Wires77 in Calcs Tab there is a Life Reserved section that literally says how much life is reserved and tells you by what

**Comment by Wires77** [comment]
This is what @Nostrademous is referring to:
![image](https://user-images.githubusercontent.com/1209372/115789540-ebb11f00-a38a-11eb-8d9a-4e094bef07cb.png)

I'm going to close this issue as it looks like all of the issues are accounted for.

**Comment by Spastic111** [comment]
This doesnt change my request to add an option to count how many 'ticks' you have channeled for. POB currently only lets the skill count as one tick, without accounting for the rest of the skills channel

**Comment by Spastic111** [comment]
Without being able to tell POB that you are doing one large hit, you are losing out on %more you gain from channeling the skill and reserving more of your total life pool, and that makes your damage calculation inaccurate. I was trying to be helpful.

**Comment by Nostrademous** [comment]
There is a stage counter allowing you. To set how many ticks you channeled for...
