### ISSUE TITLE
Question about meaning of "Effective hit pool" stat 

### ISSUE THREAD

**Issue by imTheSupremeOne** [PathOfBuildingCommunity/PathOfBuilding#2659]
I'm sorry, I didn't find where to ask here, and no one else in other places seems to be able to give an answer...

... but what does he 4th stat of "effective hit pool" represents?..
![image](https://user-images.githubusercontent.com/13508453/115792973-e6c48d80-a3d3-11eb-9dae-00d8b262ff97.png)

I thought that it might somehow include regen or leech, but then I tried to remove them by adding Vaal Pact and Ghost Reaver so that I don't have regen and leech, but that didn't change much and now can't even imagine what is that, and no one who I asked either... so mb it's also could be made more intuitive, to better represent exactly what factors are going into this value...

**Comment by Regisle** [comment]
This doesnt factor those in yet, I am currently reworking it so it will include more things in the future 

but for now its just the number of damaging hits it would take to kill you, divided by the chance to be hit, times the incoming damage from config, basically how much incoming damage would it take on average to kill you

**Comment by imTheSupremeOne** [comment]
Idk, this stat doesn't represent PoE reality much — I'm never dying to even 10 hits, it's always 1-3 hits from Legion/Influence/Sirus-ed rares, especially when they are stacked up with their auras...

**Comment by Regisle** [comment]
thats one reason why I am reworking it
