### ISSUE TITLE
Relic of the Pact doesnt support its %more multiplier with its current state in POB

### ISSUE THREAD

**Issue by Spastic111** [PathOfBuildingCommunity/PathOfBuilding#2660]
**What happened?**
Relic of the Pacts skill 'Blood Sacrament' is a channel skill. But POB only accounts for its first tick in the channeling process. This results in the skill not accounting for the variable states that augments the skill's damage. I requested a feature that could add this, where you tell POB how many ticks you are channeling for, but my request was closed without consideration.
 
* **What were you trying to do?**
Determine damage with Relic of the Pact

* **What steps will reproduce the bug?**
Using Relic of the Pact

* **Does it reproduce every time?**
Yes, you cannot make use of the fact the skill is a channel skill, that increases its radius and %more multiplier at all.

* **Provide a build code:**
No build code is needed to reproduce. Just put Relic of the Pact into a build and look at its lack of support for channel duration

* **Screenshots:**
![Capture](https://user-images.githubusercontent.com/82694775/115796623-270a1880-a3a0-11eb-9938-9520a8ddc611.PNG)

**Comment by Nostrademous** [comment]
On left hand side under the selected tick or in Calcs Tab with Blood Sacrament selected you have the option to set the stages count which is how many ticks you have been channeling for

**Comment by Wires77** [comment]
After setting that value, you can see the More multiplier in the Calcs screen here:
![image](https://user-images.githubusercontent.com/1209372/115796856-2f5e5580-a398-11eb-9a49-e15fee406839.png)

Please don't open duplicate issues.  If you think the previous issue (#2657) was closed prematurely, we can continue the discussion there.

**Comment by Spastic111** [comment]
I messed with that and it did nothing in POB and I just updated to the latest version.

**Comment by Wires77** [comment]
> 
> 
> I messed with that and it did nothing in POB and I just updated to the latest version.

Make sure you're changing the stages box on the Calcs tab, as well:
![image](https://user-images.githubusercontent.com/1209372/115797148-d5aa5b00-a398-11eb-926d-307c7efdc809.png)
