### ISSUE TITLE
Ice Nova does not support "Count" numeric up-down in terms of shotgunning/aoe overlap

### ISSUE THREAD

**Issue by HalinSky** [PathOfBuildingCommunity/PathOfBuilding#2666]
Ice Nova does not support "Count" numeric up-down in terms of shotgunning
Configuration -> Skill Options (Cast on Frostbolt? true):
![image](https://user-images.githubusercontent.com/9516359/115901034-fb9b3280-a460-11eb-8ef3-c3d9f4692cb4.png)
**CASE 1**
Example:
Count: 1
![image](https://user-images.githubusercontent.com/9516359/115900846-b8d95a80-a460-11eb-889c-c2e83546d1e7.png)
DPS:
![image](https://user-images.githubusercontent.com/9516359/115900958-de666400-a460-11eb-9540-4ccfbbbac355.png)
**CASE 2**
Count: 2
![image](https://user-images.githubusercontent.com/9516359/115900924-d1e20b80-a460-11eb-817a-4f248949314a.png)
DPS (unchanged in the end)
![image](https://user-images.githubusercontent.com/9516359/115900941-d73f5600-a460-11eb-85bb-16ed77219a5f.png)

Since Ice Nova can shotgun/overlap when cast on frostbolt, this calculation is incorrect.

**Comment by Wires77** [comment]
Count is intended for Full DPS calculations.  If you include Ice Nova in Full DPS, you should see the effect of changing the count variable:
![image](https://user-images.githubusercontent.com/1209372/115902220-d0482180-a427-11eb-8e5d-02390f9ef745.png)
