### ISSUE TITLE
Prism Guardian not applying reduced reservation to socketed gems

### ISSUE THREAD

**Issue by Lilylicious** [PathOfBuildingCommunity/PathOfBuilding#2670]
* **What happened?** Prism Guardian is not reducing the life reservation cost of socketed gems. The auras in the provided build code are used in game with no issue, leaving me at 4% life (using the same tree that has 4% reduced reservation on tree).

* **What steps will reproduce the bug?** Equip Prism Guardian, socket auras, watch your life be reserved far more than it should.

* **Does it reproduce every time?** Yes.

* **Provide a build code:** https://pastebin.com/NidGL026

Temporary workaround is adding the following lines to any item:
25% reduced reservation of skills
25% increased mana reservation of skills

Reduced life reservation of skills didn't work, so I had to used generic reservation reduction and counter it with increased mana reservation.

**Comment by Wires77** [comment]
The wording for Prism Guardian was updated.  If you change the line on your equipped Prism Guardian (or grab a fresh one from the uniques list) to "Socketed Gems have 25% reduced Reservation"  it should work fine.
