### ISSUE TITLE
POB blocked by Antivirus

### ISSUE THREAD

**Issue by DWM00** [PathOfBuildingCommunity/PathOfBuilding#2672]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** New updates 2.10, 2.10.1 are being blocked as Malware, worked for short period yesterday. Now is blocked from opening again. Can install old version and opens fine, 1.4.170.26 but as soon as it updates becomes blocked again. 
Zero changes have been made to antivirus (Hitman pro & Bitdefender) 
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?** 1 day it worked 2.10, but now still blocked 
* **Provide a build code:** 2.10.1
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by ppoelzl** [comment]
See #2458. Please search for duplicate issues before opening a new one.
