### ISSUE TITLE
Can't see flame of judgement and storm of judgement infos with Atziri's rule

### ISSUE THREAD

**Issue by OSleyy** [PathOfBuildingCommunity/PathOfBuilding#2677]
What happened?
When equipping atziri's rule, you can see queen's demand but not flame of judgement nor storm of judgement stats, which mean you can't see any real infos about your damages at all.

What were you trying to do?
Making a build with atziri's rule

What steps will reproduce the bug?
Just pick the item in the item list, you can also put gems in your weapon but since you won't see any informations about the 2 skills, you can't see if it's supported or not, etc.

Does it reproduce every time?
Yes

Provide a build code:
https://pastebin.com/GJKVRqTH

**Comment by Nostrademous** [comment]
Not yet implemented. #2597 will fix this when complete.
