### ISSUE TITLE
Add basic glossary to the 'About' page

### ISSUE THREAD

**Issue by lakhpache** [PathOfBuildingCommunity/PathOfBuilding#2681]
With the addition of Full DPS, we now have "Total DPS", "Total DPS Including...", "Combined DPS" and "Full DPS".

These are linguistically synonymous terms and what's included in each is not immediately obvious.

While full documentation on a project like this would be pretty ambitious, a basic glossary would go a long way (e.g. included in the 'About' page or on a new section in that pane).

**Comment by Regisle** [comment]
Now that we have a help section that would be the best place to add the glossary, added it as part of todo #6093
