### ISSUE TITLE
Brutal charges count as endurance charges

### ISSUE THREAD

**Issue by totalover** [PathOfBuildingCommunity/PathOfBuilding#2683]
When you have maven belts on you, charges are replaced by diffrent charges, so stuff like endurance charges don't count for that, POB is counting increased damage with this charges even if maven belt is on

**Comment by Wires77** [comment]
Can you please share your build?  I was unable to reproduce this as a Juggernaut with the equipped belt.

**Comment by totalover** [comment]
![obraz_2021-04-26_232635](https://user-images.githubusercontent.com/33205605/116152927-d7508780-a6e6-11eb-96cb-01dc2d3aee44.png)
Heres node with belt on

**Comment by Wires77** [comment]
I'm still unable to reproduce this without a link to your build.
