### ISSUE TITLE
(Suggestion) Total spell block chance tooltip is missing

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#2694]
Hello,

In the calcs tab there is a total block stat which shows the total block % you have even if it is above maximum block at the top here https://i.imgur.com/F1h0U7S.png , for spell block this stat is missing since it was probably included to account for your base shield block value  https://i.imgur.com/AmNQ4Zw.png.

 It is useful to see how much overcapped block you have so I suggest the same is included for the spell block section as well. 

Best regards

**Comment by LocalIdentity** [comment]
Added in 2.12.0
