### ISSUE TITLE
Frost blades projectile attack speed not scaling with Multistrike

### ISSUE THREAD

**Issue by jboilard1994** [PathOfBuildingCommunity/PathOfBuilding#2695]
Projectile attack rate of frost blades should match melee attack rate, which is not the case when frost blades is supported with multistrike

![image](https://user-images.githubusercontent.com/48626957/116149840-9d648e80-a6b0-11eb-8910-b7b225e14a0a.png)
Vs.
![image](https://user-images.githubusercontent.com/48626957/116149939-bc632080-a6b0-11eb-82f5-cf35959a8ad6.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
