### ISSUE TITLE
Viridi's Veil, Praetor Crown- no hexproof

### ISSUE THREAD

**Issue by ToFloMe03** [PathOfBuildingCommunity/PathOfBuilding#2697]
When i have "Viridi's Veil, Praetor Crown" equipped and  magic ring in my second ringslot i should be hexproof. But my elemental resistances are going down to 20%. Ingame i have 75% at all elemental resistance. Pls fix for right calculation.

Heres a POB: https://pastebin.com/QtV37e6Y

Im cursed with almost every curse.

**Comment by pundm** [comment]
follow the template and provide a pob build please

**Comment by ToFloMe03** [comment]
> follow the template and provide a pob build please

I updated it

**Comment by pundm** [comment]
fixed by #2215

**Comment by ToFloMe03** [comment]
when it is fixed, why do i have this problem?

**Comment by pundm** [comment]
It's fixed when the pull request gets merged and a new version is released.

**Comment by ToFloMe03** [comment]
ok thx for helping

**Comment by Wires77** [comment]
Fixed in 2.4.0 (Though a new issue cropped up in #2928 )
