### ISSUE TITLE
Healthy Mind

### ISSUE THREAD

**Issue by 2kamikaze2** [PathOfBuildingCommunity/PathOfBuilding#2698]
![изображение](https://user-images.githubusercontent.com/15280971/116218100-dce3b700-a752-11eb-9f79-c3fe46bc3c5c.png)

Jewel "Healthy mind" work is incorrect. It converts flat life to mana, although the stone itself does not work that way (It only works for% life)

**Comment by pundm** [comment]
Please follow the template and provide a pob.

**Comment by 2kamikaze2** [comment]
https://pastebin.com/2CdQKfSc
