### ISSUE TITLE
Hollow Palm Technique - Keystone

### ISSUE THREAD

**Issue by LocalIdentity** [PathOfBuildingCommunity/PathOfBuilding#270]
You count as dual-wielding while Unencumbered. 60% more attack speed while you are unencumbered. 14 to 20 added attack physical damage while you are unencumbered. You are unencumbered while you have no equipped gloves, main hand item, or off-hand item.

**Comment by Nostrademous** [comment]
Yeah, I have this one done unless they change it before 3.10 drops

**Comment by LocalIdentity** [comment]
Added in 1.4.167.1
