### ISSUE TITLE
Path of Building isnt  Working , its Crashing.

### ISSUE THREAD

**Issue by signedupforPoB** [PathOfBuildingCommunity/PathOfBuilding#2701]
Hello , im running the latest windows 10 updated no anti virus in background etc.

rx 6700 xt graphics card and ryzen 5900x processor.

I cant get the newer Versions of PoB to work.

Either in the Startup process the application crashes.

Name der fehlerhaften Anwendung: Path of Building.exe, Version: 0.0.0.0, Zeitstempel: 0x606d1b4c
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.19041.928, Zeitstempel: 0xa0caab76
Ausnahmecode: 0xc0000374
Fehleroffset: 0x000e6a73
ID des fehlerhaften Prozesses: 0x3388
Startzeit der fehlerhaften Anwendung: 0x01d73b7b8cbe0fd4
Pfad der fehlerhaften Anwendung: xxxxPathOfBuildingCommunity-Portable-2.1.0 (1)\Path of Building.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\ntdll.dll
Berichtskennung: 5c18bc17-378c-40f0-9d29-4edbbade94f5
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

PoB 1.8 works fine.

**Comment by ppoelzl** [comment]
This isn't an issue with Path of Building, your operating system is broken. `ntdll.dll` is missing and PoB relies on it. This is a well known issue and there is plenty of information online on how to solve it.

> PoB 1.8 works fine.

Not sure what that means, there is no 1.8.x release of Path of Building.

**Comment by signedupforPoB** [comment]
Sorry but your answer sounds a bit arrogant and thread seems closed to early for me, id like to show you some more info, this crash seems to happen when the program tries to update itself.

I not only receive the ntdll.dll errors but a bunch of other Errors includign a  Memory Crash Message.

**Comment by signedupforPoB** [comment]
Pfad der fehlerhaften Anwendung: C:\Users\ibase\Downloads\PathOfBuildingCommunity-Portable-2.0.0\Path of Building.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\DriverStore\FileRepository\u0366490.inf_amd64_c0dea8a43cb81731\B366217\atioglxx.dll





Pfad der fehlerhaften Anwendung: C:\Users\ibase\Downloads\PathOfBuildingCommunity-Portable-2.1.0 (1)\Path of Building.exe
Pfad des fehlerhaften Moduls: C:\Users\ibase\Downloads\PathOfBuildingCommunity-Portable-2.1.0 (1)\SimpleGraphic.dll

**Comment by PJacek** [comment]
Did you update your graphics card drivers recently?
Is your card set to compute mode?

**Comment by signedupforPoB** [comment]
Startzeit der fehlerhaften Anwendung: 0x01d73b7bfe0f0010
Pfad der fehlerhaften Anwendung: 

C:\Users\xxxx\Downloads\PathOfBuildingCommunity-Portable-2.1.0 (1)\Path of Building.exe

Pfad des fehlerhaften Moduls: 

C:\WINDOWS\SYSTEM32\AcLayers.DLL
Berichtskennung: 514a5580-84bd-457b-b48f-348c11433db4


Hi Pjacek , no there is no Compute Mode enabled.


Graphics Driver are always the latest installed.

**Comment by signedupforPoB** [comment]
I managed to get a screenshot after countless tries
![MSI_SnapShot_05](https://user-images.githubusercontent.com/83298643/116303987-6078c480-a7a2-11eb-8998-26d27dade889.jpg)

**Comment by dclamage** [comment]
Can you try extracting to and running from a location that's not in your downloads folder? Specifically, one which does not contain your username, and only english characters. For example, create a folder C:\PathOfBuilding and extract it there, then run from there.

**Comment by signedupforPoB** [comment]
Pfad der fehlerhaften Anwendung: C:\DoesntWannaWork\Path of Building.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\DriverStore\FileRepository\u0366490.inf_amd64_c0dea8a43cb81731\B366217\atioglxx.dll

**Comment by tr1pped0ut** [comment]
Managed to fix the issue for me by disabling Compute Mode on my AMD drivers.
