### ISSUE TITLE
Flash and Stone and Maim are treated as curses.

### ISSUE THREAD

**Issue by Mitussss** [PathOfBuildingCommunity/PathOfBuilding#2702]
In the section debuffs and curses, both F&S and Maim are treated as curses. The default number of curses available for a character is 3. In my case, I use the above mentioned 3 curses, which are: a curse crafted on a ring and 2 gem curses (despair and punishment). POB counts F&S and Maim as curses - not debuffs, which results in an inappropriate display of the actual damage.

**Comment by Wires77** [comment]
Please fill out the bug report template and share with us your build.  Flesh and stone is working fine as far as I can tell:
![image](https://user-images.githubusercontent.com/1209372/116276365-0e0bb980-a74a-11eb-8924-bca88194360f.png)

**Comment by Mitussss** [comment]
Probably I have phrased it in a wrong way. What I meant is:
- the F&S and Maim are listed in this bracket: https://imgur.com/a/vObFfnc
and act as if they were curses. Or maybe the space in this bracket is limited to 3 if there are no items or gems allowing the character to have more than 3 curses.
- if I simply add, for example, "You can apply an additional curse" line to my body armour, the bracket lists up to 4 positions, which should not work like this, since F&S and Maim are not curses. I should have been allowed to use 3 curses and the 3 curses should have been listed in the "curses/debuffs" bracket. 
- As you can see in the imgur I have pasted above, there are only 3 positions listed, where only one of them is a curse. The ring's poacher's mark. However, pob treats the despair I use on my flask as a 4th curse, not the 2nd one as it should be: https://imgur.com/FjaGx3V 
- The 3rd curse I use is the punishment gem: https://imgur.com/LBMWlj9
This all adds up to having 3 curses. Did I misunderstood something? 
My pob where everything may be double checked: **https://pastebin.com/GkzcH5tB**
P.S The medium cluster jewel's "Blood Artist" notable does not add any damage.

**Comment by Wires77** [comment]
F&S and Maim are not curses, correct, they are debuffs.  That line says "Curses and Debuffs", so they are listed there.

I just noticed in your initial message you said the default number of curses for a character is 3, which is untrue.  You can only apply one curse by default, so crafting the additional curse on your body armor only gets you two curses total.
https://pathofexile.fandom.com/wiki/Curse#Curse_limit
