### ISSUE TITLE
Unleash not calculating correctly.

### ISSUE THREAD

**Issue by Proto01** [PathOfBuildingCommunity/PathOfBuilding#2705]
Unleash doesn't seem to calculate seals unleashed beyond 1. For example, increasing seals to 4 via passive doesn't increase damage, which is clearly wrong. Improving seal gain doesn't improve damage, which is clearly wrong.

**Comment by ALT-F-X** [comment]
>Unleash doesn't seem to calculate seals unleashed beyond 1.

Incorrect, Unleash doesn't do anything in PoB at all. (Besides mana cost calculations and quality effects)

![image](https://user-images.githubusercontent.com/5727264/116596508-0c78f780-a8ea-11eb-8654-0af70ee8ac32.png)

The real bug report is that Unleash isn't supported at all, which we're aware of and it's a WIP at #1331.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1331.
