### ISSUE TITLE
Add Russian Language

### ISSUE THREAD

**Issue by PatapoIIIa** [PathOfBuildingCommunity/PathOfBuilding#2706]
Hello everyone. Because of the language barrier, I, as a resident of the CIS countries, need:
1. Find the required chain of abilities on the English forum;
2. Go to the ENGLISH wiki and find this ability;
3. Switch to Russian on THIS page;
4. Learn how the ability is called in Russian.
5. Only after all this be able to buy it from a merchant;

The problem is that the translation of the game into Russian does not reflect the real state of affairs, and because of this, problems arise.
Possible solutions:
1) Play in English;
2) Update Path of Building;
Thanks for attention.

**Comment by zao** [comment]
There has been some questions about translation in Path of Building in the past, https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/999#issuecomment-647452829 covers most of the problems around supporting the other languages.

**Comment by ppoelzl** [comment]
While I understand that localisation is a desired feature to add, with the current architecture, we're not able to, as zao pointed out.
I'm closing this issue in favour of #999, to track the current translation progress there.
