### ISSUE TITLE
Scourge Arrow - incorrectly calculated total DPS per stage

### ISSUE THREAD

**Issue by LemonVillain** [PathOfBuildingCommunity/PathOfBuilding#2707]
* **What happened?**
Scourge Arrow's Total DPS has started calculating incorrectly as of 2-3 days ago.
Zero stages is the lowest DPS - makes sense. Stage 1 is the highest DPS and decreases incrementally until max stages (5). The average damage appears to correctly increase. The same result happens when viewing the main projectile release or thorn arrows.

* **What steps will reproduce the bug?**
Add a bow to any character. Add Scourge Arrow. Change main skill to Scourge Arrow and change between the stages to observe the bug.

* **Does it reproduce every time?**
Yes.

* **Provide a build code:**
Version 2.3.0
https://pastebin.com/Eut8Rpzu

* **Screenshots:**
![image](https://user-images.githubusercontent.com/63225524/116587251-ecdcd180-a8df-11eb-86fe-9afd3b327f98.png)
![image](https://user-images.githubusercontent.com/63225524/116587294-f6fed000-a8df-11eb-9d65-0759eea3dacc.png)
![image](https://user-images.githubusercontent.com/63225524/116587360-ffefa180-a8df-11eb-85fa-8f3655a324f9.png)
![image](https://user-images.githubusercontent.com/63225524/116587400-0847dc80-a8e0-11eb-8f03-097acf84c440.png)

**Comment by Thanat0sNihil** [comment]
Don't believe this is a bug, just POB reflecting that you've only got the DPS for the 'release' bit of the arrow selected, in which case the damage multiplier(150% per stage) of accruing stages does not make up for the time spent channeling those stages(+100% of the time to channel per stage). the skill makes up for this in-game by generating additional thorn pods per stage and if you want that reflected in your dps the best method I know of is to add an identical socket-group, configured to calc the dps of the thorn-pod portion of the skill, and include both groups in Full DPS.

**Comment by ppoelzl** [comment]
@Thanat0sNihil is correct. It really works like that. We get a lot of questions around Scourge Arrow as a result. Here's a more in-depth explanation: https://www.reddit.com/r/pathofexile/comments/kgn93v/comment/ghuhdsr/
