### ISSUE TITLE
The Scales of Justice - added fire damage seems to be not present in the damage calculations

### ISSUE THREAD

**Issue by moritzkiehl** [PathOfBuildingCommunity/PathOfBuilding#2709]
I am currently making a build with https://poedb.tw/us/The_Scales_of_Justice but it seems like the added fire damage from the shield is taken into account for damage calculations.

**Comment by zao** [comment]
Mods that show up in red are not yet implemented.
![image](https://user-images.githubusercontent.com/260218/116673848-2b3bc480-a9a4-11eb-824d-89091792dc48.png)

**Comment by PJacek** [comment]
Fixed by #3151
