### ISSUE TITLE
Empower supports levels up Impending Doom in PoB. PoE doesn't agree 😭 

### ISSUE THREAD

**Issue by praisethemoon** [PathOfBuildingCommunity/PathOfBuilding#2719]
Short version:
I was wondering why my damage does not fit with PoB calc, turns out Impending Doom + Empower ingame doesn't work together, however PoB gives it level.

Long version:
I am equiping a staff with +3 level of socketed support gems and level 4 Empower, PoB makes empower level 7 (which makes it give +6 level of active skill gem) thus Impending Doom im PoB has +9 level. However, in game it only have +3 from the staff. 

![image](https://user-images.githubusercontent.com/22145460/116831379-3878cf00-abaf-11eb-89c8-e4268a82eed0.png)

Proposed solution:
- Empower shouldn't raise level of Impending Doom (probably any gem with support Tag, regardless if it has active effect or not)

Goodbye my 10M build.

**Comment by Wires77** [comment]
I think this is the only support gem that also grants an active effect, so it's unlikely we'll fix this interaction until there are more gems like this.

**Comment by QuickStick123** [comment]
Related to https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2295

**Comment by mariopeixoto** [comment]
Same issue but with Awakened Void Manipulation. PoB adds a level to Impending Doom, but in game the gem doesn't gain a level.

![image](https://user-images.githubusercontent.com/25545/216723254-2d1ce049-db8b-46e2-b1d5-0129bdd5d362.png)
![image](https://user-images.githubusercontent.com/25545/216723292-ec64b61e-533f-428c-be85-2fa3b475112a.png)

**Comment by QuickStick123** [comment]
Should be fixed in #5530
