### ISSUE TITLE
Desktop pob: No import character option?

### ISSUE THREAD

**Issue by hetgepeperte** [PathOfBuildingCommunity/PathOfBuilding#2724]
Hey all, trying pob on desktop but can't find the option to import my character. On all tutorials etc there's a "Character Import" field, right above the "Build Sharing" field. What am I doing wrong? All my privacy settings are unchecked too on poe. Thanks!

![pob no import option?](https://user-images.githubusercontent.com/83582781/116865930-d8b01180-ac0a-11eb-8545-1b7c82699c79.png)

**Comment by ppoelzl** [comment]
> trying pob on desktop

Not sure what this means. What you're using is an unaffiliated and therefore unsupported third-party website. Download Path of Building Community (the desktop application) from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases
