### ISSUE TITLE
Medium cluster jewel passive not allocated despite being in the json (Replenishing Presence)

### ISSUE THREAD

**Issue by nikvaro** [PathOfBuildingCommunity/PathOfBuilding#2728]
When importing my character in PoB one skillpoint is always not allocated as you can see in the images. I tried four different cluster jewels and with two of them the Bug occured, but only in this socket. All of them should be in the attached get-passive-skills.json in the zip (Uncommented the output in the ImportTab.lua after the processing of the JSON).

Not bugged:
Medium cluster with 4 passives and cold damage over time (Brush with death and Circling oblivion)
Medium cluster with 5 passives and inc effect of non-curse auras (Among equals and replenishing presence)

Bugged:
Medium cluster with 4 passives and inc effect of non-curse auras (Among equals and replenishing presence)
Medium cluster with 4 passives and inc effect of non-curse auras (Among equals and replenishing presence)

Every cluster has atleast one additional mod. I tried to unsocket every cluster jewels but the large and the medium one needed to reproduce this bug and it still occured. Although the sample size is small I guess this bug is somehow related to a specific combination.

![PoE](https://user-images.githubusercontent.com/10902869/116929786-33735880-ac5f-11eb-821f-3212d45a97e0.png)
![PoB](https://user-images.githubusercontent.com/10902869/116929790-34a48580-ac5f-11eb-9a41-2c3c483cfc06.png)

[get-passive-skills.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6417553/get-passive-skills.zip)

If I understand the data correctly, the passive point in question should be the "229" in  the dict you get with "hashes_ex".

To try it with the import: account: nikvaro char: NikVortex

**Comment by Muramas** [comment]
I am having similar issues but I found that my Medium Cluster jewels are not expanding so I am unable to slot a jewel in them.

![image](https://user-images.githubusercontent.com/2413847/127437869-d14c8639-a7cf-44c3-8a35-074aab8f9218.png)

I created a test medium with nothing in it so and that works though. As OP said, there must be something wrong with these jewel skills.

**Comment by miki4625** [comment]
Sorry for digging it up, but it still occurse for me.
My public account name: Lyvri
Character with problem: SmallPrincess

**Problem:** Small Clusters arent properly allocated (mana reservation 2 nodes, with notable **Introspection**) even if they are in game allocated.

All of Small clusters are fully allocated in game, but in PoB:
![cluste 1](https://i.ibb.co/swK2fG1/Zrzut-ekranu-2022-09-01-193219.png)
![cluste 2](https://i.ibb.co/bXG48xt/Zrzut-ekranu-2022-09-01-193230.png)
![cluste 3](https://i.ibb.co/YdQNDFS/Zrzut-ekranu-2022-09-01-193245.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7270
