### ISSUE TITLE
Stat inconsistencies.

### ISSUE THREAD

**Issue by beerwithbatman** [PathOfBuildingCommunity/PathOfBuilding#2729]
I imported my build from Path of Exile. Made sure to check "delete jewels, gems, gear, etc". Copied and pasted my amulet from the game window into POB. I did this to check which anointment would be best. The problem I ran into, is the gear I copied and pasted is the exact same as the gear that's already in POB, but it's showing that I would lose DPS. If it's the exact same and I haven't changed anything on it yet, it should be showing no changes. I'll include a few pictures to show what I'm talking about. I've made sure to update POB. I uninstalled, reinstalled, uninstalled, and tried the standalone. Same issue across the board.
![image](https://user-images.githubusercontent.com/83619141/116946231-365e5100-ac3f-11eb-9e37-373c32d684b1.png)
![image](https://user-images.githubusercontent.com/83619141/116946255-424a1300-ac3f-11eb-80e8-aeb0415027d8.png)

**Comment by beerwithbatman** [comment]
This seems to only happen with Mirage Archer.

**Comment by Wires77** [comment]
This appears to be fixed by 2.34.0
