### ISSUE TITLE
How to setup/simulate low-life

### ISSUE THREAD

**Issue by hardc0l2e** [PathOfBuildingCommunity/PathOfBuilding#2730]
I am trying to get the buff/damage addition with low-life status, like with bloodthirst, but I cannot find any low life setup in the configuration, is there a way to simulate low-life in PoB?

**Comment by Wires77** [comment]
You should be able to see this checkbox in the first section on the Config tab:
![image](https://user-images.githubusercontent.com/1209372/116975256-f7eb8500-ac84-11eb-8e7f-f7c295e90073.png)

As the tooltip says, you can reserve half of your life and PoB will recognize that you're on low-life

**Comment by hardc0l2e** [comment]
![Path_of_Building_DuPeCkNkmR](https://user-images.githubusercontent.com/1472421/116975912-fa84c380-acf2-11eb-8805-f0c0c6860d17.png)
 No option like that on my end, even with Petrified Blood active in skill

**Comment by hardc0l2e** [comment]
here's the  character just in case https://pastebin.com/StvgAYLd

**Comment by hardc0l2e** [comment]
I am using PoB 2.3.0 (from the updates)

**Comment by Wires77** [comment]
The option only appears if you are using something that gives you a benefit when on low life.  You have Bloodthirst, but it's not linked to anything, so nothing would change even if you are on low life.  Petrified Blood doesn't give you anything when on low life either, it just makes going low life easier without reserving life.
