### ISSUE TITLE
Does not calculate level 6 gems with 23% quality

### ISSUE THREAD

**Issue by Hadik123** [PathOfBuildingCommunity/PathOfBuilding#2733]
When I have tried to calculate my build which has level 6 gem with 23% quality it automaticly downgrades the gem to level 5 and 20% quality.
And when I try to change it manually it does not calculate the DPS.

This cap feature is quite new and in some cases, it can be useful for example when editing pod overlap. It doesn't let you increase the number over the maximum projectiles.

Build code: https://pastebin.com/hUERPtd8

Below you can see proof that the gem actually exist:
![image](https://user-images.githubusercontent.com/82848339/117034960-1ba1e000-ad04-11eb-8970-2c6266300f45.png)

**Comment by ALT-F-X** [comment]
This is because there isn't an increased in multiplier from level 8 to level 9 for this support gem.

Directly from the game files:
![image](https://user-images.githubusercontent.com/5727264/117045775-825bd500-acd5-11eb-83f9-a92583c924b3.png)

**Comment by Hadik123** [comment]
Oh, I see. I have checked with the [wiki ](https://pathofexile.fandom.com/wiki/Awakened_Vicious_Projectiles_Support)and it looks like that's correct. There should be an increase but that's an issue with the game not with the app. Thank you for clarifying it. And I am sorry for wasting your time for me by me not checking the data.
