### ISSUE TITLE
Weapon removal tooltip suggests ever-increasing Full DPS improvement

### ISSUE THREAD

**Issue by zao** [PathOfBuildingCommunity/PathOfBuilding#2734]
* **What happened?**

The "Removing this item from Weapon 1 will give you" breakdown in the weapon tool tip for certain skills can be made to constantly increase the supposed Full DPS gained.

This manifests both in 2.3.0 and current `dev` (793399f).

* **What steps will reproduce the bug?**

1. Import the build code.
2. Open the Skills pane.
3. Select "Earthquake, General's Cry".
4. Hover the "Weapon 1" dropdown.
5. Observe the Full DPS figure on the Cane of Kulemak climb up as long as the tooltip is shown.

The altered amount persists into that tooltip on the Items pane but cannot be triggered to climb in there. It doesn't seem to affect any obvious calcs.

* **Does it reproduce every time?**

Yes.

* **Provide a build code:**

https://pastebin.com/6CW1XHgH

* **Screenshots:**
![gcry](https://user-images.githubusercontent.com/260218/117066385-f2e01180-ad28-11eb-8484-157bb1dcb7c2.gif)

**Comment by coldino** [comment]
Looks very similar to #2451 but that was caused by MA.

**Comment by Lothrik** [comment]
This appears to be the same bug I encountered. I recorded a video + saved the PoB:
https://www.youtube.com/watch?v=YbUq7t6y7pw
https://pastebin.com/gNtiN06Y

**Comment by Nostrademous** [comment]
It's an issue with how mirage's are handled. I fixed it for Mirage Archer. Need to fix it for General's Cry and The Saviour still.
