### ISSUE TITLE
Warning call stacks beyond 100% increased armour

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#2735]
Hello,

The warning call cluster jewel notable has a cap of 100% increased armor regardless of warcry power, however in POB you can stack multiple notables and get 100% from each one, going over the 100% maximum. 

Best regards

**Comment by Wires77** [comment]
Fixed by #3947

**Comment by Sahel9999** [comment]
https://pobb.in/TZmJ0yfRE13W

This seems to have resurfaced.
