### ISSUE TITLE
Bannerman Notable passive grants its bonus incorrectly 

### ISSUE THREAD

**Issue by Voyciechu** [PathOfBuildingCommunity/PathOfBuilding#2736]
Bannerman Notable passive grants its "Placed Banners also grant 30% increased Attack Damage to you and Allies" per every active aura affecting the player instead of per every placed banner.
This bug occurs every time and is easy to reproduce. Steps to reproduce are as follows:
1.Create new blank build
2.Equip any attack skill gem and suitable weapon
3.Pick Bannerman Notable on passive skill tree.
4.Equip a Banner skill Gem and non-Banner Aura skill gem. Activate both
5.In Configuration Tab, activate "Is Banner Planted?" Switch
6.Go to Calcs Tab and select equiped Attack Skill. In "Skill Hit Damage" Table, "All Types" Column, "Total Increased" Row, Bannerman bonus will appear more than once, while it should appear only one time because player has only one Planted Banner affecting them.

![image](https://user-images.githubusercontent.com/49199554/117083029-fb921100-ad43-11eb-874b-683629c9ba7d.png)

This image shows Bannerman Notable applying 3 times on character with only one Placed Banner and two non-Banner Auras affecting them
Code for build that represents this bug:

eNrNW-tz2kgS_xz-ChVVubqt2KDR6Omzdwtj7FBrJwSc5O5TapAG0EZIWBrssFv7v1_PSBiBeTRa38NbRYT063dPT_eIPf_lxzTSHnmahUl8UScNva7x2E-CMB5f1D_fX5-69V9-rp33mJh8HF3Ow0g--bn25lxdaxF_5BHQ1TXB0jEXX5ac6DfgNGOxmPAkvmO_JelNElzUPyQxr2tDFgehWH7zI5ZlH9iUX9QHPhDXNZb5PA7aq_s5cMrCeJD437m4SZP5TIl9DPnTXRIApnvX-9i_LwkN47JQ0PnNeS9iC54OBBNaBh8X9RaYzsb8ik3hE7ixaA6siGHaDZ16JjU86tj15nbiwYzzYEXUsEt_zv-eqJfyzmjEfRE-8nYaivaExf7KSGsX3Ras2XD3oe_mkQhnUcjTko47-b9_wd7b6eL7RLDoqjd4hhq6YzccalDXNSA4_xm6RDzT6buQX0MxuYwgLBWkSNruOA4Fr0jcS8Isif-CfWXSnSZ2pzMWratokwaxLddwbZc4--17SUyp03A91yC2R8j_ldB2Mh2G8UYsj6JsPY6PjcUdi1k7yVa5RnZG4jYc8TXoTmRngMP1od7hkFLNHk-hIgscgVT2KIKBWNUNb2fZ6POHMpBY3i7kFf9RisUefmUgsXZK7sYCx68M1Hdr95gItc1hHLkS7Bl7dgf_TIK7sY_j-jlOecbTx9Kmsof_OkUR2lLW7hXV52OOtPWWc39yA5t8nwmOS8zVbqbv9Y7EorwjgVu8g8Rv-mYv2YZnGt4-8JG-6cQ8HS8Gk5BHCCOUi8okKFeVCZBRLpMca9Ejy8qrhlq2td-enKBsimHudDGHrRwoAr7ZmlivSNJLk99kPxYdSddKp8l8Vfqovrcn9c9yPM7y3mSRhT40BaoF7vNg7q9VJ293RJbN5V3yyKeQ9qpLhWa8nNM7i8plBJ38hgfovgyNom0kOylaQjD_-1USjDmWRAk5iuI6TMFlWVja5U6pcRj9EcaONpsdFtBO5NrCClih0QJuw_FExDDT4aVskOBtmbAk2xRjY-BoEdfzKEK1toPv4TpSsGHEzzT9BwkMe2gFO-edXvIEykzktJsdllNG37FVt7GzKbxOefz7As1_DY4S0ImDeSqzGy1jk-KlmPOmOg2QV9CBJ6lQN9ss8jPFshvP5kKL1SifSc9_i-fToZwW83_lJN98gZyGmf9tOB-N5HxfB2VSdSjRub7utO-7XzoFyYCrgqX5SRSxWcZh4I_DqK6FQRHmARRqXyDQMJgWBwGHsV9Z6qchuO8wVI6TCFXViH8YJ-dtBCyfhLAuul_MuIx4hvNSUR4PY9WAjMDl8yzGLDU1Y5zOfbZA4J67EAS2E_FWGMmdDuOnO0jffIvEoGG7SsPhXKAySg0GCA1kg4wwq9wrIjTNmxEE36JjO4wsNgVMPkEHgPT9FR9xyFLUClWr_p5953FRz5a161wtj0zLoKjd8Gl2uYBN41p6auPQYA0A20k6h5IV8BGbR_L-pzmLQrEoZK7u3-bnp-puNkmeBvPZLOckl2QG3r69zZ-0IlEwkWIu6iMWZcWpptJRnY62VD-mvisL1BFpGPvRPIDhsNgdC3ERG0rRdW0sD1PbyTwWxRMey80wWFqxwVjylGLfnIMiBfYmSoYsMpacc6MMvb72mCwZqi2gC_zvJ2nyFC-nlIfcvK5avcpBBbTHUqEsGfOpfHrHBQuYYM2uAFc0pT-aSjXpthLLVbv9zFxuc5v2PctYuczPvQFXciuSPXXeWYuURVrOXFOSCuq7MFan3qCFEDwdJkK2YkXm5bodjFSeja8dKwl6pWj15jDmCs6jSxbHcvN-lYBdpZwFGxy3RWlbSBSttiQ-GIlX8MEVB6bTMGb5jPQ6HtjKE-2Dder_hhNuUubzVzJ-nRfW6ILqiLVXXKmafp9yrrF8lSh2pKij8KX87knqDvrE0H7KsuAR0zwxbctxT0yiu8YJNS1CT0xKHfOEUkt3TwzD0eGORwBjuS6lJ9R2XXJCTN2yT6hlwVOb6nDfgIf6CUzycG26ruHWNQFqld6fEbN4NZarkceuE0D7E3yQGqkb5Tsah8skHXDpO3kqp4W-ZNWCfty4kp_KBV24mTVnwBjsz5pfGIs-JGr8UTumvNsIgiy3O3_91obYaslIUyNZ_kAqZRq6WewFb968I281kUAB-hFO59McquUbu2wWlyBbobY-PW-ubMmtbW6ae_65f5vLmwgxy86azaenp8aMiUky4j-g0Df8ZLq07VSlx6l0a7MFf5fyo5N2xejXMU-G_Yevdtu6Dh-fLh8-de6HSfjwzfj41X7gLeP0sXVxkauwlHiev3lcuj3_9uwKYhsEQgjaTvNwNXfgCLF0BM4mLjUxONNyKQJnGJ6H4We6tuNh-FFCEDDP1DFeobaNspaaJs5a4rkYfgasVIxY6lgYsZTYOPVsx7AQOMsiHiZZTE93MThCiYPBOZ6NEgulzUDhwA6Um22KCYepm7qOCoeOEUsMm1CUGdRDRReyxcZE17NcTBYQ00PJ9RzPwajnmg5GrOE5xEAlM_FsVEWjuoXCGa6LqmiOiaot1HM9lFzbxthBHIPgKiS6Bjm4HcFEyTUhnzHpYhEokhh7dYti8oC4JkWlPSjooIqa7eJ2LMdG2WEQG1VdCDDE4Exio_LKoKjwQidoobZKD1UkbY-gaqThbMsW6JZX3Q58gcZY9dCyc5YX0DDmHZm8ufyi-uovIX_SMs5SfzIQqRxZf0-S6b8u6qeGZzSIlR9mvOdM3LFZMXhIRHEQYhbHIIKJq3A04qk6wlmOAhL4T9lsWQ3HMZZ_-ZGNmi2Krl5eD3g-NMwzPuDQ8gZfOZslsbq9HIoVkfbI0pDJEYPmp0FFS9uH22Jxpn3-0P30uVO7hbacL_jfgEn2D9m7TpM047VeGMfMj7h2L0_6i7OB2pec5ZnWS7lmNOyGvn6LNvTyrfY8BUNFLT-p5oH2_ITuEFAcBZ1phl4rQnWm9U_hv5ryZJ8_nGmOXutOZ1Hoh_Ipqf1RWHpG__wjZfGYn-kN6893fzf0U6r_VO7e5QFjrYQBiH5qWPpPb-UJBUzdGSiZHwSuuJJ1rq5-CkPIFrZLPAxQ6xTEBhJ3C4n1Vkvli0kQunzXqKnz8pqhlzUaiHkMkfEBky5qoLC2fLup5Ud8mpBnfNooTaba6nRIy98VZrV3ICg_25YqqMNGtRrukqAv9dSUtvK9prVMlWK97EQYBxH0IGL57lbNz_mkGiXLtyR5WmulEv38LiVfBTtXQDnZt3Akgyc201rDRZbJQ6-8bmwpUdtIN8kMHNl-1GWSiKyiQttsOaDUJYeh9ziSaxjXv2sUpZKxTSVazb04JxivRGZWU9KuJs2u7s0q-XQgAu95NOXiWEFbMsmuIudA-t1EUPiyKoxp9VVEqsgzq-UCqZZ55uHwYBx7LNtt6VXRcFTdsSroU6EG0kNigkXRGhwZvu1erpRfVhUi1JLEBKKSnVZltxoV4m5XW0m0WvrS47PMrF72K-Q0qex8ikkIEwOqoPZfaH6QkXzRVaKjYFfIyuph-Avpgi3Jkha5avDQCp7rh_EY1wkcXSh2urdiucDHs4o5FOEnUj0MZmVvWVWswayX6kl-QKXWdB5t2dvyiRMGRnX4o05Y1A_7kngUjl_8Xm-o3sP3Ipjt5S_nh0kScRYXZzfFz2oKyvPm5v9Q-G9HkikM

**Comment by CiesterMR** [comment]
yeah issue still present on 2.8

**Comment by banang** [comment]
can confirm is still bugged in 2.13

**Comment by Qtkantha** [comment]
2.15.1 and still bugged
