### ISSUE TITLE
Add support of eHP for petrified blood

### ISSUE THREAD

**Issue by hghammoud** [PathOfBuildingCommunity/PathOfBuilding#2737]
Currently the eHP and maximum hit taken is calculated without the 40% damage mitigation

If we can have this included to have an accurate representation for the one shot potential.

Tnx

**Comment by Regisle** [comment]
currently in the process of reworking both of those, eHP is unlikely to include those untill I rework some other things but was planning to include it for maximum hit

**Comment by hghammoud** [comment]
thanks. Will be waiting for the update. Maybe a new life specific for this?

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4060
