### ISSUE TITLE
Arcane cloak

### ISSUE THREAD

**Issue by Admiralkekbar** [PathOfBuildingCommunity/PathOfBuilding#2738]
After the last patch, all my pobs with arcane cloak do not have the ability to show the amount of mana spent. I am not using the unique indigon so I can't really calculate anything in pob.https://gyazo.com/5b36214c3fe40aafce201966b28d24d0, https://gyazo.com/932fd25957c2b916ce72a68cc67de362.

**Comment by LocalIdentity** [comment]
Arcane Cloak automatically calculates based off of unreserved mana
