### ISSUE TITLE
eHP Calculation for EB+MoM+Corrupted Soul combo

### ISSUE THREAD

**Issue by PraetorianMK-II** [PathOfBuildingCommunity/PathOfBuilding#2746]
**What happened:** I was checking eHP of my character while considering if its worth to add Corrupted Soul into build, and after checking whole thing realized that PoB does not calculate it right. How is it supposed to work: Eldritch Battery protect Mana instead of Life, Mind over Matter redirects 30% of Non-Chaos Damage taken into Mana before Life, then with Corrupted Soul, 50% of this damage goes straight into mana and 50% (15% of total Damage) still taken by Energy Shield. So the distribution is like this:
_30% of Chaos Damage is taken from Mana before Life
15% of Non-Chaos Damage is taken from Mana before Life
15% of Non-Chaos Damage is taken from Energy Shield before Mana before Life_
Now using physical eHP calculation as example, PoB shows that i have 50% ES Bypass (which is true), 30% MoM effect (also true), but "Total Pool" value is already wrong as it shows "Mana and non-bypassed Energy Shield through MoM" equal to 140. My unreserved Mana is 70, so it counts non-bypassed Energy shield as 70 too, which is completely wrong - any physical hit that is big enough would deal 70 damage to mana and up to maxLife/7*3-70 damage to ES. All further values are also wrong as result.
**What were you trying to do** I've tested it in PvP to make sure that ES consumption is not limited by my unreserved Mana. I was losing few hundreds ES from a single hit with only 67 unreserved Mana (not lvl 100 compared to PoB's 70 mana). There is nothing else to do really, as it proves my point; But I've also tried to get EB in the tree (normally I have it from the helmet), didn't change anything.
**What steps will reproduce the bug?** Create a character using MoM, Eldritch Battery and Corrupted Soul keystones, check eHP calculations section.
**Does it reproduce every time?** Yes.
**Provide a build code:** https://pastebin.com/Br5qGUkP - just a snapshot of my character, still enough to see the bug.
**Screenshots:**
![MoM+EB+CS](https://user-images.githubusercontent.com/83756477/117277117-38572880-ae68-11eb-8b73-9f5aa3bef0f2.png)

**Comment by Regisle** [comment]
This shouldnt be an issue with my rework to ehp and max hit (seen here #2390) when I finish it, but yes there are currently lots of issues with ehp/max hit (hence my rework)

**Comment by Wires77** [comment]
This should work correctly now with the above PR
