### ISSUE TITLE
Split Personality Prismatic Jewel - Unique

### ISSUE THREAD

**Issue by LocalIdentity** [PathOfBuildingCommunity/PathOfBuilding#275]
This Jewel's Socket has 20% increased effect per Allocated Passive Skill between
it and your Class' starting location
+5 to Dexterity
+5 to maximum Mana

**Comment by LocalIdentity** [comment]
Added in 1.4.167.1

**Comment by Markus-13** [comment]
This jewel counts every allocated passive in the shortest path between the socket it inserted into and starting location. It counts the first passive allocated near starting point, it doesn't count it's own socket. 
![SplitPersonalityCrimsonJewel](https://user-images.githubusercontent.com/15339723/78745435-dbd7c000-796c-11ea-8e71-7a2d256aa4b6.png)
The final stat bonus calculated as follows: `trunc((X*0.25+1)*Y)` and the result is truncated.
X is the number of passives and Y is the bonus stat.
* Case1: for 5 Strength / 40 Accuracy bonus when the socket with Split Personality is 17th on the shortest path it will be: `trunc((16*0.25+1)*5)` +25 Strength and `trunc((16*0.25+1)*40)` +200 Accuracy.
![SplitPersonalityCase1](https://user-images.githubusercontent.com/15339723/78745570-383adf80-796d-11ea-88d7-75c6dc0163cd.png)
* Case_2: confirmation that fraction part is omitted: when it's in 12th socket it should be `(11*0.25+1)*5=18.75` but as it seen on screenshot, it is just 18:
![SplitPersonalityCase2](https://user-images.githubusercontent.com/15339723/78745890-1f7ef980-796e-11ea-89cd-a590a6a2d01a.png)
* Case_3: confirmation that it counts jewel sockets and cluster passives:
![SplitPersonalityCase3](https://user-images.githubusercontent.com/15339723/78745976-5a812d00-796e-11ea-9c7b-b6bbaca47ce3.png)

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1

**Comment by nut-3** [comment]
Split Personality bonus is calculated wrong.
![image](https://user-images.githubusercontent.com/6929041/79744804-b2754780-830f-11ea-998f-44cbf93b4a31.png)
It must be 43 Dex from 31 passives as stated in game:
![image](https://user-images.githubusercontent.com/6929041/79744902-e0f32280-830f-11ea-8032-6b4e5e427822.png)

**Comment by LocalIdentity** [comment]
Please post a pastebin for your build but I’m guessing you have gear on with the mod % increased dexterity which is why you get more than 43 from it

**Comment by nut-3** [comment]
> Please post a pastebin for your build but I’m guessing you have gear on with the mod % increased dexterity which is why you get more than 43 from it

Actually, yes. Sorry for bothering you.
