### ISSUE TITLE
Eyes of the Greatwolf "Physical Damage Reduction" statline incorrect and non-functional

### ISSUE THREAD

**Issue by Rosemary102** [PathOfBuildingCommunity/PathOfBuilding#2754]
One of the potential mods for Eyes of the Greatwolf, the unique talisman that doubles its implicits, is implemented in PoB as "increased physical damage reduction." The mod is supposed to be "additional physical damage reduction" instead, which is used everywhere else for the stat (including in the Longtooth Talisman base implicit stat). As a result, Eyes of the Greatwolf won't be counted towards your total physical damage reduction stat in its current state.

I've confirmed I'm on the most current PoB version, and that manually changing the "increased" to "additional" makes the stat get counted correctly again. I'm assuming there was a mix-up with the alternative Eyes of the Greatwolf modifier, "increased global physical damage," which is completely understandable given the sheer scope of PoB and how niche this unique is.

(Edit: Apologies for not using the default template. It wasn't provided to me when I started typing this out. I'm assuming it messed up since I wasn't logged in when I initially pressed to start writing a "new issue" submission, and I instead logged in partway through the process. I figured it had been removed sometime over the past few months, but getting ready to add another new issue showed me the template again.

Its probably too minor to justify a post, but you can pick the base type variations on a Precursor's Emblem multiple times, in the dropdowns normally limited to different stat alignments. For example, you can make a Precursor's Emblem that is simultaneously a Topaz Ring, a Sapphire Ring, and a Prismatic Ring. I don't know enough of how variants are implemented behind the scenes to know if this is easily fixable though.)

**Comment by Lothrik** [comment]
Fixed by #2761.
