### ISSUE TITLE
Fist of War showing different damage multiplicators in "different" Path of Building pastes

### ISSUE THREAD

**Issue by 8Times** [PathOfBuildingCommunity/PathOfBuilding#2758]
* **What happened?**

I have two Pastebin links which look the same but have different damage calculations without any reason and disabling Fist of War nullifies the bug.

* **What were you trying to do?**

Comparing two builds and changing the tree

* **What steps will reproduce the bug?**

Import fist Pastebin, import second Pastebin and compare them.

* **Does it reproduce every time?**

Yes

* **Provide a build code:**

(Pastebin hates me)

Number 3:
`eNq9W1tv4sgSfh5-hYW0T6uA23dHya7IbYIUMixkZvY8jRq7AW9sN2O3k7C__lS3DRgCpPDuOTNSYvBX1XXvqrZz8ftbEmsvLMsjnl62SUdvaywNeBils8v216e7M6_9-2-tiyEV8y_TqyKK5Z3fWp8u1LUWsxcWX7Z9IBM0mzHxbcXK_AHfLWgq5oynA_oXzz7z8LL9yFPW1iY0DSOx-hTENM8facIu2zcFi6NctDWaBywNrzd3SmhCo3TMg2cmPme8WIDEbe0lYq8DHgKmPxh-GT3Vlo3S-rIg9qeLYUyXLBsLKrQcfly2e6A9nbEbmsBP4EbjAlgRy-pYhm2ZumnbrtHu7iceLxgLN0QdYhr2_xs7zNjtdMoCEb2w6ywS13OaBhtNnA45RLkHbXR8wzuGHxSxiBZxxLKaeK57iOT-3QrWQfZPXND4ZjjeMHbMju0Q1_c91_Xs_w0dF2s6_RDyeyTmVzG4ZGsVXIhI2v4sjQRrSDzkUc7TBsQr_eqkB1W85skkShtpuCLtvcxOJe1ljH6ZluE7omFU5BsOB-NkQFN6zfON38hB_g_RlG1BD-p_O8bhRlAlcEgp5pBlUMcEjkAKexLBWGyS0DAPSsx-1oGQHIeQN-wNx68O9A4av5_WXGQdYVcH6oeFe-ECthacHTcLE8M_UmWDc4nupwGO7dc0YznLXurF-cgC2ySVbzeU-tG1RmzGkNo-MBbMP8PeCEtAxcXF5hple-SohSQYZSEJ3GOhI_y3KU4wkCTcNhDRO8Yx9Mk2uk1ZNluO5xGLQ0QuSkvVSVAWqxMg_V0nOV2nF5rXc8g0jydHhcd5n8EOCQQh29nx_0WKYcb_kp1OfBpZL0t4kSGdWIJRKg_nyzwKYJNVzeOIhUWAK1Hrhm3AX1gCMa8aPuhiN-F8iPQqhv4XqziwjeOTKHpC0OD5hoczdtIiJ1HcRRlYK49qm9yZg0B_gV79mi4w3YzMJ-wCGzR6gYdoNhcpzEL4VXZI8LrMKc9PUGYDRy9xV8QxqkscP0fbSEEnMTvX9DdoK0Jr4h1OFf4KwszlkJgjEquGHtBNs3GwKbnLWPr3Es1_C45a4DYNi0xGN3qNXYr3y1x01RQtr_rJgmdCg3lX9IKAF6m4p_kcuivm-pPQJYEVuIFjWbpBLA-qfqgzYjlBCM21xwjx24p0xGicgPWuy49yYRoI2BsUL3viMs-YmlNrqoeeSQM_8AwjJNClh94kpFPGbOYEQSnbNY2DXGnWTxeF0FI1hidRHvyYFNOpnLjboGmmTgpu7-5ur5_6324rY9RJchkzP9IimciZsfy9qW9jpkqmFvA4poucwbA-pXEOvKOwircxbBOBQOFhE6wGeQz6O82CLAJfYsByUESJrEZ3DFKO0yggBAeNGd5gT8sFk4GYY21W1W0MWo3BKGQ5t-IUVPMxzg0soEsUct0codC3MetFsdyKcVYbQCKUuzgOD_tqFk0KgYw2NcOg5JCdPErBejuLkrhsmlC8q7YSg612MlysQeOC9sYNmzKIYmQ2qyrxRJ9ZWpXiVb27UCmUaznU488sya-WsN_dSavtHJJsAdbMQzalRSxv_FHQOBLLy3YaxfXvH8ozU0MHFnP-Oi4Wi5KTTNsc7P7wUN7pxaLiIZdZrVAqJ2VUp6E91Uaqz0oDdSQapUFchDDWVhv7WrqYTuTabW0mj0-v5T5TycdSuZODjiIrqoPWGmvJVS786QJEqbCfYz6hsbHhvdGrDiBrgNoI-jJcaCbmPwswflv7WWrYV6mtTFQBhwBSysxYIu8OmKAhFbTbF2CNrjRJV8kGV3sYyo15V6k1342lgtIEcCU3K9n_b4unSAZRqs60x0WScHD_EMqloHlSRlozm9Qkktr1ZOSKjMbjmCZVSOw3zjFzrEPpTnZ_U9jfjtpjn_KSUuNTTdKWiVRaWeVImRry8iljTKNlgCg6UgUmfKgf3ktRYeEUugUwuK37ntPWBBDXHhQQq3oGIMFWFWe3IewI4aOkq6z8dfSgLj7NhVjk593u6-trZ0HFnE_ZG0yEnYAn3QWwAZnOlGHP5ELdHvy76v0BPy8vFaPuitNF-SghL9lWn5SsUhLiGMSDXBKlwas-bw-OEFtH4BzimRYCZ1i-i-FnGL6P4Wd5jutj-JmEIGC-pWOsYjoOSluHmLqNkY74HtJ6GC1M07VNjHiGifKF4xoYLWyb-Ch-IJ6D4WcRw8WoYdkeRl1igD8wMeXYxEeZ2TEx7rB0S8fYxSQ6ZlniWaaDUsP0Meq6voORzvZtDxMFxPJ9nDeIg7EeMQmuYniWi8o1h_go8_m6h6t8hoeqpLptGqio8j0f5V7Pw_AjrkFwFRJZgwzX8lB2sVDrQpI7mHgxLQuV5Q5xHJR_LeKgstxwUfJZvuPhdizX8VB2ASDGH75LMHHg6K5po6qQg7KzTWDTQu2VPqpKOj7BpJvv-nv2BOjeNt0OfIBGTfV0spOTF48cZlN5T365-qD6vG8Re9VyRrNgPhaZnB7-5jz5z2X7zPDcjkd0zzd117Occmy5Z1QM6GLdA0twNfOQauQRVNxEMDxnamBbtaMS-KfkajsdXzc9x7EM0ysfUFyoNrfqOOX1mJWda5EzmPR4Gn5ndMFT9XVtUJJQNfBV88uIZtAMn2uj3ui2tTq-18i91ntjrVGRRoF2T0UwZ6J1ndEptKDnmpSuNczYNHo71x44EPTTIGM0l5NA_QFA9fzKPgXcS8NeEBQZDZYjKqJ0tkPdC8NdSqc1LqZ7-JdH9-r8ydyGyJMmSQ_ui56rU_oDkM37HVarmj7PNUNvVcEDljuD_y3l0BH7ea65pNVPgCCI5F3SIsYvcv4sRdLKeUdbW7rUoAUVt47avQ1K5xqxNcE1w3tPvEVbaq0ptVvG1q2VTlqpt1Yq3vrVcH-RrCvZdlEbC7R-hd5eIlce0koXqQSSkVWOPDFfHXWWMajVcnl1zFmF7JFwrUfpPp7jV7rQepNlnktRy4zfU6z2ke6SGTiyd1psoa44F3lDgfbp8oFQVywWJ5LcwUz5rJkokYx9IpnNzIszgvEvkVnNhHSareY0tyb5wMH74ukDD9yzOGHi1IX2RJLTZJ0Pwg_Ky4t8TnQ6Y7N5FpEm61nNYoE0izzrY_dgDHsq233h1VBxVN2xG8jToAaaHy0TLrXyJP9E9-23cqP4spsQoVIS44hGetqNzWo08LvTLJPMZuFrnh5lVvOy3yCmSWPjm5iAsDCgBmL_g-YH6cnmXnAaRGVzN_yDcMGWZEmLzBo8tIHlRjAP4DqBkwvFQfM2LBd4fzZRx0TYiTR3g9XYWnYTbTD50jzIPxCplxTxnr2tnDlhZFTnNupARL2ow9NpNHv32o0cMiP5BFy9BwHWb2sTzmNG0-q85f2bOq_yfZjl9ps9g96fe5AsZcmyn1_xPN9A1R_ZvMcm63lavW-z_Aqj-YjJs494-f59oDrlIovC6m9bPhJoEnMejmkajkX5CuIKPu493uzBg88zyX3nvbGVNKv3s1a2veju_gXUfwH1Ozq8`

Number 2:
`eNq9W21v2soS_lz_Cgup0r2qQrzrd5ScI_KOlLQcSNt7P1WLvYBPjE3tdRLOrz-zawOGABncc28rpYCfmZ2XZ2dnlvTs99dZrD_zLI_S5LxF2kZL50mQhlEyOW99fbw58Vq__6ad9ZmYfhlfFFEsn_ymfThTr_WYP_P4vOWDmGDZhItvS1XmD_hszhIx5WnywP5Ms9s0PG99ThPe0kcsCSOxfBfELM8_sxk_b10VPI5y0dJZHvAkvFw_KaEzFiXDNHji4jZLizlY3NKfI_7ykIaA6T30vwwea8tGSX1ZMPvDWT9mC54NBRN6Dj_OW13wnk34FZvBT9DG4gJUuV7btC3Xd1zLNChtne4WHs45D1dCpE1Mav-_sf2MX4_HPBDRM7_MInE5ZUmw9sRpk32SO9C07VPvEP6hiEU0jyOe1cxz3X0id29WsPaqf0wFi6_6wxXU89qu6XiGaxJiufR_I5eKlZyxD_k9EtOLGFLSYBUp25skkeANhftplKfJL_hXF93r4mU6G0VJIw-Xot3nybGi3YyzL-OSvgMWRkW-ZtVenjywhF2m-TpvZK_--2jMN6B7_b8e4nADqBI4pDSzzzOoYwInII09SmAo1puQmnst5j_rQOLsRV7xV5y-OtDbG_xeUkuRdUBdHWjsN-45FXC04OK4XphQ_0CVDToS3UsCnNqvScZznj3Xi_OBBTZFqtyuJY2Daw34hCO9vec8mN7C2ThgguOYuULZHjkYHwlGxUcCd8TngP5NiSPCIwU3w0OMNj2EPjJC1wnPJovhNOJxiNiHMk51EVS86gLIXNdFjvXomeX13WOah7dFhcdlnsPZCAIh3zrr_0GJfpb-KXuc-DixbjZLiwyZwhKMcrk_XeRRAMerahsHPCwCXHFatWoP6TOfAd9Vqwf965rK-0QvYuh8sY6D2jg-SqIrBAuertJwwo9a5CiJmyiDaOVR7Xg7cRDoL9ClX7I5po-Ruwm7wBqNXuA-mkxFAlMQfpUtEbwvU5bmRzizhqOXuCniGNUfDp-iTaRgo5h3dOOVcG7YwX6z-ukLGDOV42GO2Fg19ANbtxl725GbjCd_LdD6N-CoBa6TsMgku9FrbEu8XebsVM3P8lVvNk8zocOkK7pBkBaJuGP5FM7NIDANFrrE9D1qUNezfGoFnHmeYTnUZYTZtu1YtKVEB5zFM4jeZflWLswCwbNSF2HcMYyRNQrHnjU2bX_EXToahcyzTU5Nx-c0YIZfjphnlywOcuVZL5kXQk_UAJ5LAvxIitlIjn7lv-tiVUfOojz4MSrGYzmVtyAmmbpNuL65ub587H27rkSGXJVMPUjjmM1zDmP6mMU5SERhxbchHBOBQOFh0KxGeAz6O8uCLIJcYsByRESZrIZ2DFIO0iggkIPFHB-wx8WcSyLm2JhVdRuDVgMwCllOrDgH1WSMSwMP2AKFXLVGKPR1zLtRLI9iXNQegN7lKY7Dw7maRaNCINmmpheUHbKLRzlYb2ZRFpdNE0p31VZisNVJhuMaNC7obFzxMQcWI3ezqhKP7IknVSle1rsztYVyPYd6fMtn-cUCzrsbGbWt65ENwEp5yMesiOWDPwoWR2Jx3kqiuP75fXlbqj7Np-nLsJjPS1Vy3-YQ-Pv78kk3FpUSuc5yidI7aaS6CO2qPlK9Vy6o29AoCeIihIm2OtlX5sVsJBdv6RN5c3opD5rKFJ7IoxycFFlR3bHWVEutcuEPZ2BKhb2N0xGL6Vp36Rg1WhsAsgKow6Mn-cIyMf1ZQPRb-s_Sw57a2ypGFbAPIOXMhM_k0wcuWMgEO-0JiMapDMmpsg1e7VAoT-Ztp1Z615EKyhDAK3lsyQFg0zwl8hAl6jp7WMxmKeS_D_VSsHxWUq1ZTGoWSe-6kroiY_EwZrOKEruDcygcKyrdyPZvDAfcwXjscl5K6ulYl7LlTiqjrDZJuTfky8eMc52VBFFypCImvKnf20tTYeEEmgAIuG34ntPSBQjXviMgVnX9L8FWxbPrEI6E8LOUq6L8dXCvXnyYCjHPO6enLy8v7TkT03TMX2EkbAfp7HQOasCmExXYE7nQaRf-XHT_gJ_n50rR6VLTWfktQl6qrd4pW6UlxKHEg70kyoBXjd4OHCG2gcA5xDMtDM6yPROBo9T3Mfosz3F9jD6TEATMtwxMVEzHQXlLfZdQDI74Hkqf41IbgbMtQl1Mdj3LdDA4k7gYFtg28TE4kzg4Flg-Jmum6Zio7Lo-JiqWA25gcIZloLylrmOiomL4qK1GPQ_lhuljlnV9B5Vb3_Yw3COWj1rWIp6L4R71LNdGhcU0bNQeIj5mXdOyUBy1fMPDxI8YtklRZPY9FPss4mBwxKUEVyGRNYi6lofKh4XbRYSidodNoEii1nUcB7U9PI_iahCq9lm-4-FOLNdBnbyUOJii5hiuidof1ETRFPYHqliZro3COT6qNjs-MVAsde0d2YXubd3twBto1FRPJzs5-eJzCsOpfCY_XL5Rfd63iL_oOWdZMB2KTE4Pf6Xp7L_nrRNiW22bQHAJcWxJPTm23HEmHth81QNLcDX0mNXII5i4imB6ztTEtmxHJfA_Uqvhtw3qutQy4DQqv6E4U21u1XHK10Nedq5FzmHUS5PwO2fzNFEf1wYlCVUTn132lQOWQTPc0QfdwbUGA2Ya6hcs4do9G2WLXFNwZWxH90ytGr86uqFVwQPJk9uTQflXU8gB_9nRLV_rzeZxFEQSY2jLrwb0ctLs6LBHTizT1v_Fiom8ZuDhvzV5A6RAENboievlPUxHt9uG8VErr-Jzfc4zvXSxo5O25W2oKL3WByyRixBTA1XyX0-74q8d3fe1TybRRarDW8Gl7xrU9o9yQsw4g7FY37JU64ZhrhNDylDrzVNq1mVLE3V156URq_6oHHT0bhAUGQsWYKGIkon2yaJS8_bHxKjLqqtyvfxVAO0yzbJiDs4q2soEbSaW7Ejsympyp3dfuTYokijQ75gIplxA2NkY9HV0STutn_FxBKG6T0Ggt7Rh86ud6ltJ-xhwNwmXXpZObklDnLclHW1YjHfoL8OsomxuQpYMKglU8mcPZP07O9aa13SD2JuUdkmd0kQjdEd-t_kBR-n75LIVuby3wnQvuejGo90bR_tE3Y9SdWXbNmodAe0TDG27eLhBsWGcLm-zq21Wq9KrO--yFh2oQ3WW7tI5fGFzvTta5Lk0tazlO06rXaLbYhQn9saLDdRFmoq8oUG7fHnHqAseiyNFbmKWP-kmyiS6yySzWXhxQaD_kJjVzEin2WpO82iSdxK8i0_vZOCOxzMujl1oB5OcJuu8Qz8oL8_yG8DjFZvNdxFpsp7VjAukGfOs99ODCeyxanfRq6HjqLpjN7CnQQ0031smXOjldzRHpm93lBvxy24ihNqSmEQ08tNuHFbaIO9Os51kNqOveTzLrOZlvwGnSePgmxhCWBhQA7N_oflBZrJ5FpwGrGyehl-gC7YkS1nkrsFDG0RuAPMArhM4ulDsDW_DcoHPZxN3TEScSPM0WI2jZTfxBrNfmpP8HZO6syLecbaVMyeMjOpCTt10qV_BSpNxNAHE2en2f736G7EOWgk=`

* **Screenshots:**

![image](https://user-images.githubusercontent.com/13020561/117588534-25707c80-b124-11eb-8aed-65ee3b907de5.png)
![image](https://user-images.githubusercontent.com/13020561/117588548-43d67800-b124-11eb-95a3-1446659e9474.png)

**Comment by ALT-F-X** [comment]
So to start, the build with 144.4 damage was the one that's wrong and bugged. I was able to track the issue down to "Warcry calculation mode:" was set to "Max Hit" instead of "Average" and that was affecting dps even without a warcry as an enabled skill, also since there wasn't a warcry enabled  "Warcry calculation mode:" wasn't showing up in the "Configuration:General:" tab.

Impressively convoluted bug. Thanks for the fun exercise.

**Comment by 8Times** [comment]
Damn, I would have never thought about that, thank you very much :)
