### ISSUE TITLE
Tooltips aren't affected by Thousands separator settings

### ISSUE THREAD

**Issue by pHiney** [PathOfBuildingCommunity/PathOfBuilding#276]
![image](https://user-images.githubusercontent.com/4302241/75622572-ee383e80-5bf5-11ea-9614-da53cdc853fe.png)
It could be that they DON'T use formatNumSep() (common.lua) 

P

**Comment by LocalIdentity** [comment]
Also, the calcs page doesn't use the thousands separator

**Comment by pHiney** [comment]
Added PR #278

**Comment by pHiney** [comment]
> 
> 
> Also, the calcs page doesn't use the thousands separator

It is inconsistant.
![image](https://user-images.githubusercontent.com/4302241/75624633-4416e180-5c0a-11ea-8686-b4c78d641700.png)
but
![image](https://user-images.githubusercontent.com/4302241/75624644-598c0b80-5c0a-11ea-984c-b11d1e6f09d6.png)
(shots from the same build)

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1
