### ISSUE TITLE
CoC builds: Attack speed not taken into account in Tooltip & Power Report

### ISSUE THREAD

**Issue by julchevalier** [PathOfBuildingCommunity/PathOfBuilding#2766]
Hello,

**Steps to reproduce:** Create a CoC builds (in my case Cyclone CoC Ice Nova)
**What is the issue:** Attack speed is correctly taken into account in Calcs and Summary but **not** in tooltips (tree or items) and Power Report tab.
**POB:** https://pastebin.com/QKGghag2

**Exemple with Harrier tree point:**
![image](https://user-images.githubusercontent.com/38038607/117795454-7da39d80-b24e-11eb-98f3-55c7804bd75c.png)

**Comment by QuickStick123** [comment]
Fixed sometime recently 
![image](https://user-images.githubusercontent.com/31533893/177547654-4127988d-13b9-4b3d-9c72-9659207398f5.png)
