### ISSUE TITLE
Private account not fixed with given troubleshoot.

### ISSUE THREAD

**Issue by DishangPatil** [PathOfBuildingCommunity/PathOfBuilding#2768]
Hey 
I am facing an issue with my POB. I cant see my character in GGG. But others can view it in their GGG. I tried reinstalling, verifying the version and checked my firewall still the problem is same.
Please look into my problem and help me to troubleshoot it .
Thank You
![unknown](https://user-images.githubusercontent.com/84046713/117972055-4addd000-b348-11eb-9d9e-4375ab063dbf.png)

**Comment by ppoelzl** [comment]
You have to change you account's privacy settings like the info text tells you. This is something you have to do on the Path of Exile website. This has nothing to do with Path of Building itself, so we won't be able to help you. Contact Path of Exile support instead if this is still unclear for you.

**Comment by DishangPatil** [comment]
Hey PathOfBuildingCommunity/PathOfBuilding

Other poeple can see my character profile in their GGG. But I can't.
I have even contacted POE support and they told me that they don't deal
with third party software. And clearly it is app fault because others can
see my profile but I can't on my GGG.

Please don't close my bug report without solving my problem.

Thank you

**Comment by ALT-F-X** [comment]
Have you tried using the POESESSID instead? I had an IRL friend have this problem a couple of weeks ago and that worked for him.

**Comment by DishangPatil** [comment]
Yes I tried POESESSID. Still the problem remains same.
Let me tell you what troubleshoot I did:
1) Reinstall the app
2) Run as admin
3) I checked my POB version
4) Allowed it through firewall (Manually added it )
5) Crossed verify if my profile is private or public via different person
GGG.

**Comment by zao** [comment]
@DishangPatil Can your successfully import the public profiles of other players?
Could you please try importing characters from my "ZaoFishbones" account on the PC realm?

**Comment by DishangPatil** [comment]
I havn't tried others. But right now I tried yours and the problem is still
same.
I am sending you the SS.
[image: image.png]

**Comment by DishangPatil** [comment]
[image: image.png]

**Comment by zao** [comment]
Your images do not seem to be make it through the email system you use to respond to this issue.

A theory is that it is possible that you are on an IP address that is considered "naughty" by CloudFlare, causing requests to the PoE website to instead go to a landing page where you have to fill out a captcha challenge before being allowed on.

Have you seen anything like that in your browser when logging in? It may have looked something like the example given in this Reddit thread: https://www.reddit.com/r/pathofexile/comments/awscxe/anyone_issues_with_poe_website_captcha/

A comment suggests that you can see if your IP is known bad via Project Honeypot and that's also where you could submit a request to scrub it, according to CloudFlare's help page: https://support.cloudflare.com/hc/en-us/articles/200170136-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-

Do you have any other source of internet connectivity you could try with your computer to see if this is the cause, like tethering a mobile phone's connection to test with?
