### ISSUE TITLE
Adding Various Passives Causes Large DPS Loss

### ISSUE THREAD

**Issue by Red-Panda-Gusto** [PathOfBuildingCommunity/PathOfBuilding#2783]
* **What happened?**
    Calcs show large loss of dps when adding certain nodes.

* **What were you trying to do?**
    Theory-crafting build. Noticed that dropping the life node under Blood Siphon somehow causes an increase of ~23% dps. Noticed that other nodes cause the same drop in dps as well (ex. the strength node next to Combat Control).

* **What steps will reproduce the bug?**
    Use build code provided below. Hover over various unselected passives to see loss of dps. Select those nodes to see the calcs follow through. I find the +10 to Strength node next to Combat Control to be the most [confused nick young].jpg

* **Does it reproduce every time?**
    Yes, using the build provided below.

* **Screenshots:**
    See 3 screenshots in succession below:
![image](https://user-images.githubusercontent.com/84159344/118200846-16d7dd00-b424-11eb-83b0-3ec3010149b6.png)
![image](https://user-images.githubusercontent.com/84159344/118200875-2d7e3400-b424-11eb-822f-ebecc32ac03d.png)
![image](https://user-images.githubusercontent.com/84159344/118200922-471f7b80-b424-11eb-9021-f9ba9cfe15e6.png)

* **Provide a build code:**
```eNrlXetz27ay_1z9FRzP9M7pRHYIgE_f5NyR5WdrJ45lx22_eGAJkhhTpMKHbfWM__e7AEiJpEgJkt2cO-cmnVSmdhfY3y72AYL0h_95nvjaI4tiLww-7qA9fUdjQT8ceMHo487N9fGus_M__2x9uKTJ-PPwIPV8_s0_Wz99EJ81nz0yH_h04EtoNGLJ11wWuYNrUxokYxYGF_RbGJ2Eg48752lAIy_e0e5pMPCSjzufwoDtaH2fxvEnOmEfd67ZZOrTaEejcZ8Fg-7im1OPReF0DDJ3tAn1gl7Yf2DJSRSmU5jDjvbosaeLcACUZxeXn6-uC-N7QTb-dfoQjumE7oASP3249OmMRb2EJloM_3zc6QAWdMROPRjikfopyCIEExfv2aZlGoS4O-9Xch6C7BHblLk3ZWwwZzL2kG3-WNLLiB0Nh6yfeI-sG3lJF1DuL9TA-h4xmni3ob9I_cSb-mDQOQ_aa57e6dII3OUaiK_DhPqHl70FLXFsm7gg3zEtx_57-MKCxxiWa6E9gxjE1XET262XjIGrNKBNDFtHe8jFrum4qzgPfLDtFpPlvGejwEvYlsyXoReHwStgKrKqIdUNJ_deUFFXDaqctfM42nS-FzSg3TBemLXR4c69IStRIqeR9qinJvMKoogaJZ_nJYsgVibq092IoZdEhYBGGqfMvhcpV4BwyJ4XZKa1QmCJEqEmyrNgoQa2VgksURpm8wwfwwTymBqaixjr6mRFNO7vc-qzoF_Q3l0l-CaIWMyix0IYh0nraiyZjQuT23Mt19AtwzEdbK4ScsVGbKG7ZTt7uq5b8o-9ivGcsf74BHLzFU0WsLiOvmet8t-CjbG-EkBOXQTQWCm3Bj-iIzWOKnzY2nOaMxTnLaOGsLGHV5HXY9UcOQIWjWa9scf8QTGAroSryFSEzUYqw5QVUprZpko90ri4zEwTrdZH0hdVafbkCwZJEjgGrFI86G_HcRmF33jZ5G_G1okmYbqIlaZNVttR0hfVNht963I8i70-5FpRil6xQdovhTLDabRGXgJehI9sAs4vKkgoqQtFWnNdd-BDPV4BwMYr1PL9OhbUOL1OktD-w2E4GCnjLEbZiOPYiwCz2CskxuZVvyD-DOV_l04Lq7-5JOELS3GABbH6AOfeaJwE0Kcpj1Lh2ECXMQ1jdWUW1NUhcGPaPE79UlHebOoHr0yZ0Huf7Wv6M7qn9tAgjX51GT7BbMa8f40Xq0SF-oI-r2c4jljw16wqX1ciLw5AmuPvII24dyvrUOUoDiPN9-G96PD5p7PJNIwScbFL_X4sRJ4F0zTRAtGXT7y4f3efDoe8-d6BISKxfXB0fHzUvT77epTNosgSc2PdBenknneA8v-8h5eUPSYiltYPfZ9OYwZ9-5D6Mcj2BpmhexCp-4kSPTSPWVeuQn1Lo37kAYgqxLzrU5qy6MRVKHlzrEQIVqE-UwfsejZl3ANiVcyygKlCLZpRJUrZPaopKLpUNTOwPp0pUc7LEyXqI591PJ8nQjXULmAhyByqRg8JLfLu00TR20SroTQPXlIrKVisKZVmLOsWJdlZaadCm6UQNV-DkkHZGodsyMCLFVeziBLX9IEFWQzM490HsYRiLYZAeMIm8cEMEs0xR62yO1EigBQUpSB7wIY09fn1Lyn1vWT2cSfw_OL1c7mPKq7G4_Cpl06nUhJftjHgfn4uv-n4SSaED5NPXyrH5yg2RjuiiBM_Cw3E7qgX9P10AN1nllHnqvv0ng--o434Tmo3TIMkmwoLeAod5HrEfsjLvHAw0_L6tTIaH4jP5acPMLuM_cQP76mP58OJ0H_hBWCHygwL32QXe-lkEgK2l3zTl8aTnXzHGes7JfFoPkcu40z6STiIGK8xqiOKwb5LFM9E-BB2yAgvaZQIihGb8G8vWEIHNKHvzxJA_D2H_b0QA58Kg3zPTbuY2hy4vsQUZPLsxwt67vKVqdVo-34dlhka5jowMn86iNJEzPLST-N6CFYpPXfKejm8plHRvPPEVxgbaHMxb65oNwySCNY4rEoG5YhsgF6p9HqZGwOwEKkVZL45GqIJOuqPw1ciUC9nY62FGI3LUdaUKGraGQw8DiH1RUR9ha5NklS1PYKiGfoEZQ3XB7RsbjJJdUYQeGOo0TzuPa-NZnOtVwpXVf10Ng2TMYsmHq0GuAcvSVh0Hya8r1XGBqlaP-rTgPXSiN-A297yNVKUfVzwapJZlhwyV_yYBP2m2VjZMc_67JDG478zzx5HYZzc-17wsLFJiqxvk22Vl-oihnRD8PfwKXhN8GX9MBjcesHmC1KyaoL3zZXkTUlSKIA216wqQVWtnO_NVToAt-jz4PdmcXVZoqqSC84fH05kvX8LhSq0TPjfFV5Ejd2jwSDvOf7GMOOzeNwJBr1EHErZNNJwbg0mqmX8b5H71uNzyZLIG3psIIB6IyQahKpCMWfXMv4fA8VXL-sn3gaEJXGq6i8Y1-r9f70-UI-d4k6LrB_TiG6eDzLQm-SoYv8noxC2IoWe8g1i08Ki8QZxSQUFUZyUxG-a9IUErWmG_-HeeAbKR7AIYb7-G0WDWpGq1siZNcn9Y8JhvhlC4-RzUNzcfMUmSKMsVSS4BO1pzAJNStEW-63_iXXpv6Fgu_KC0ZblmnqmTf2ARfTea063CkvqE3uqF6ScaEvcbw1416cRyNX8R1-z_s54Zq2DO5vJG0WyqjTlpZvz_dDwJSrICzry-m_Xji2LVN_hicKRPEny_yebHj3HNBilXiDOdL2JD9aKVN5cLTH_4F2d7pjfPn5FCi3xK6-98fym9ZsurvktmDdbW0sSlbc6Nr4dpKzm0XDo9Wl_9gqzLYlQdtacsRITsk_i9vJ1xJhG5eoVTCi7pQs_FJ-D4dOEzB6EA35TGCPLJW1k2bbZRshy3LZFXNtqW4joDlzRHadNTNOEK4aB4V9dd_U2Ni0TtbHuENw2XGwabWTqNmkTZOukbRiuZbexQRz4jLBF2o6uo7apGxi3iQWyCEGcQjdBCnFM4raRoZt220QuBikOgjEMx7ZhbGwjGM9x4LML7Mi1dBekujBT4roIZBkmSDWwDgIdG6ZiGRhYTAemAdOC8fiEQBkMQ4BY3YRvkevCoBbWMUzAtmz4V4fptE3bIDAvjLnWBIBxdeA0Hcy1snTQ37aMtmnYiLRNlwADAAWTdAEIU3csmCBIaxuWC4PYBAiI7ho6wAksMBsYvY2JhTjAoANcsQggg0AF7HKZxAQYTdNwQLRrwzQsjJHRxpZjWUBtuqA8IACwmw5ADQYyAALLMYHS1Alob3JoTeQA4oS4QAOjmdwQhg2z0w0OLTbBNBgsY8O3JgbTg8oIxoILLnGsNozJ9SJ8dsJWoCxozx9AEnBwgE3HFMNxP3HANBi5tgHz0jEHX_yLkcP9BuRZJjesy3GDiRjcJrYLFoOJILCJC9ZDGCYLSMJkYR4WGMmxLTASaIgBS5CNdBucybAMGJLABZ3LBXtgbABqCOYIl0Eux183wI9c1xT-BTPEtg5en8AiKTxehozssTG-KMws2R0NvIQNPvH1kQWRm6tz8eGncZJM4_3375-envamNBmHQ_bs-WyvH07eT0EMrL1dETd2-UDvO_DnoHPT7Rz33C9_9JPvwyC0yVN0cxY97FrR93Ty5a-b28POn9-iMXPZ4xQ5d2HPGX7pX-PDB-_gGzo49cMYW_3o2u9Zu15wd9K_MA4nD7M_p53be7uDnPGf7tPNY9Qzj4-cA-rGvw9_Y5cP5JvzcHv9K_ndPZ64lwcd8qn30Ll9tIzdk8lfX9Or_uMxw53pBU0PUkYux7PAOXCc86_PHfvJcA-fv4y6-PTqauC51tfDvw4m32aXn3f1w_Pz6LcZvdx9NH67C-9-u_3j6tH5dOt1ut-sqT_44743TE6O9Yfv_md_hJyL33fZd3R0_u2PJEzv_C-np_7vt0d_3j-cpZ--n_TMYGLG489_TtK72-sgcOKjmPw2_f3Twa837Ck9vTC-d-2vZyPnOXg-Hv568G3Sfbb7xuT486337YQJw7zPLfNBPscXSzNlP4kYxy2LLHBEKJASGaSzY5M1dAjCmAKdhRxiqNDBIiUKdBi7roo8w7FsV0UeQUiBDAKTCirEspS0xbC6sQodBD4leZaNTQU6E3KMraIHpDcVayCexVTGhWxVoMufLKoRaEC2UZkgsU0VOhcipwKZDalSxakghKs4laEbuq6kBSSNAiy42R66yrgWFBamkh5ECWXILaalYl4XEpyKvhiSkopbQamlsiqxY9gq4yLHIJbSMoKaSSmoQZWlgjPUUip-gA3XVvMXqOWU7Os4KuEF2RipBUm1MATlk6WGn6E2LrYNFZxNXiCq4MIrbBU6A0p9Ffx0k2AlP7ActaRlW2p6AKGKvxiGWlI1XKS0LKGCVzEvJkreDO2UyrC8QVByKqLXBAPo-xb1DvwALZ7oBnkPyD98ChMmvuMX8x9Eh_jVY09azGjUH_eSiG8K_RWGkz94rbIHPYAOBToChOVB4VNGkws6nbfMnDQ7ZpxR8KcBDr3hkEXiiHTew3LC3z_u7GID7TnQ2iGDR135KMkH0RpnnSr_3GOy3U1jlh1QEacFxOXC0WROKo5YY1mnX4mNxH3tqnN11JLnAW9pMGhd8vc7sP5M_tSN6BCq-X2NTwy-Y0PveV_7V0SDEdvX96AyfCncLfwcyLHtZUrzRe4P5E_GCS7e3wtAUDNDlbCXDgWhuM4f1RDSksh7yJ4vI3OSuSzdtF7OggQYvBEH2lkmMYGgHzEaswG_PSKeFjFa2TnvfQ3rrcxl9rWDXfjbEtO5Yt_3NctpnU2mvtf3-LeoVZD5D2LtGvovP_PNRSk8O3op8Wq9M4iWhFpxbi3HbiRHZvErcRtHTLRl6qUvMlQ0CYsmcdGGYSTFxa13iA8rVNDCoUZhCDmQ3CPlcNfR5MZbJuaL6iIcXHHNNaE_rLY9Ux7qz58pErs6ZWeEDrLkjTefzr7cHLX4Bq52FoWBdhl6QdI6-iuczBIGOIxGLFI0Cy6bhZQwks7VAFXrHdlA90MGV4NQO_LFA5t0bq5llR9BTcq3p0iOTJ32l5EXT7STlEYDoG51INgAEr9BFNPkcyKtr1LOvgbLRkN7aE8vX8J7evFSN40gwCQt-cQWaD__htRJ38LrcetfmW776OUdNn7m-HHYFqDIB0w4vPGCGLfJyzuEVclRG79U_JKfUBB2AONqydiLRbRfsIB8XGKQGgEIc87W_JKQw9_IIM4QXcnH0DV-N1Hjx3EZHXAJ_NmeCs-YAh2G5RnxZ31Zzkv52cNiQHj3D6zvEv0XPqND9pwwbvjWO865EoGV68tesb5ITbSXp7i0U-ZPGKwtmEQAwx2k0SgM4MKamO_Y5st5CCvhABaSFNUJBhwjXBfFBek8tjY8GH0FQAWj7HF_o07MXAIfyK7Gb_RSeLC1JgEQbLzMX6rAImEWqy4JHDL_MVfqMfQG4rE6mBqqXxRXu_BX6xSXhVtJBn2JZua2F_TZm6QTeSZLyx79hHDj8i_luC0LFwNVdvEd0kVMmmQCuDatuTrc96SbTlkE9QkvA8CrdOFVApqCN4ls0Zc5gTsd11PLFW3wI7M2UH0Nff-_IOHH_x1rXz2-KwimoyyBRNONwqdgRSRZEUv0yoKx-IqRSyYDo_L9LsG_CE35s-BFRUt0zi6yfqkHBJdSg3gUW7uiAy-NS8kcJOBSLi8aQ_OGIgl8T73pFL7LyjSYUDeMonQKPlC0F9L1qsFUJKjk2RUUeC0FWUthNkebFcGmO2Zx0urESQSh5tIHCFbHGdQQY0hNcNCNLaKMORdUCi1uY1SACoEFo2ScPyuIloNQIXrMow1aFmg7uBivjBWxRf5dUdVUXTxbCc2ZpJI-52ksVy8r_lyzsN5sozYiYWcpIuWpf2mJFV3_Zz5wNVptXUHqzU4HRd4jqHztwRy0E5oGiQ_QrktwG-WsRc57Mxdcl5iaXYt7YFZTmMtCXKLudY0ZTYdkhavVC1nrK5ZZ4yrm1q5S5whObYqC4jwZ5znqMAwjsH4a0wFIOwhDcAbVFGWsSlE67_K4MvkqgpSiL-Mgqkr5wHdea5fkIH0XmesWMC41gflrYrJGsFxlzN8xMa80yo3iYoDsGXvtMJXFkQb__RGmrbws0Po0CMJEu-eF8BBg4CEDaGZA88qcRJrXtlG3tCcpLOLWr2BCLfu8dj0Xtijq8odcXL-yJ-ZHs_LCRStrUbVqVmmvAW9W0qKXju8XvIIUXJWYK1JEXftR3lYo7TiUnS1rmuetcEbkNuxKoPpCFq3LUE116zYpYt5xY0lm1UaJ8zDy8iBxDuTQEckuHCzZ1_hpzmrLrdhf46qYgpn0SgOd0FG8_417oc-i2V00V_yl0FtvnO9VxOIlsforxEKrosQccycpjvwPa9f5pTm4ySPLEHTOwyeZQghqrtvFEH3uQu3FLAf8XRQxa_vA_VJdF5iH3qrTLQ96O_Z8VrzS5iF94jFZq98Eftp_mBXOV_Pw-QZxcn3tbqylsJpjrV0Ta4XHdiYsgQWfSP9dF2tJpVU3GuMtF5dHEvFOmJpYi3W0EMe3XZBeE051u1zYLFPYRiVeKkZlVFiv5qqw6u4i0tBcWg3R8Z1RUxNZqHhNbDS9Q2RtwCT1QwOAooCqBGxNwA2zobEcdtvaG-tNTnMDq0zRY0xSrrfzjgT6ECHlqlRlz_NfycvIJl62dYPX5CNLZKjU35mLuvKk6E-VTu4UrIGyfky1S2vY2RRfNvqd3Gyq1OLWaz1oXeJ1axPvAfMTLj8ZMyhI-sx7ZFHrlNHHmca_qu5qW6pZtyBigTjWKyu4ksNo_i6oSmowd4lZru4LCZknu3zTtzvfVBOvSNLk2xJj-UCqvPMix5xmcJayHzJlClpYrVpoZUktu2fxAgW6ltAHppHCHI6ek4jmZhpG4aR6jyOfw3IOJPM2puQcWxQm1usqiKbCRKk_KjB_YjS6n5XS81mQeBNvQN9gM015q2x9Qt5yc7-yK3vROTnrtro0hSYkjbV8Y1-0z8c-jR_4SoNVoxKVXwTDPNpdQecNS3P2OYCqhwusDY6C59CLhavL98yVN84L_bRZ7qdRuV_Ox1suv84mkzQQa0wOoA2EQpmC8tVvrSs24Ts_OQn8l8asCUWrDkUQNwItwI_yvuCAxhSC1RxIcXuy9-AFiljyx0pALdGIfw5OvaQZwgO4LtslUWxCMPOX7kEsoDT0MpT83XqQSWTLLwGE8lN4P4yqwYKggVgTs5ZTt0lRApRJQBugs-ug6_iQGiawHnPkeqk_HYPgOXRfUg8yVaDuh9KsVzLE5XsUq_Gb52cVCJdaZhGbhlzWSxfQSRi_LQjVSJ9vS0GCjcI0EBsgN-BXSK9PtbVIljvq7CIhiwCeq9eEuaOE-QlAwm_pbu2uW0Cu7rLYLrussh--Gj1XCT3hoLEHRWHBazsDyP5cLfb3QVh663MRyQYgkVUGctXm4N8DaN1xIrGVBiB5Ex5985_WQCZKJrkrKjnqNvLE14v3VkvCZUAN50VWQE0EL7I06wSLOl6SLqCtFIvze3DZvdsVG6Lv0M8NpWBelz2JPYRxKH6Xj0bzzeA6xuJ2XBNfaQMuqxVJaUXJ0XkdWugEircVa22Lamzb9dMYCovMqr0JL8TK1-otzX_JUJ1JO0OBHniY4BYCL-WzIDEPYtnb1sR1s9aS6wTM75e8Qsb8dwtkMkoay8NA-xqdS7mTt9fvkvDunluRtxZggLuBtE2Zmz8qo4nHSvl5nEKJZFc2CPOjBJ3BINaIlk1Qjh6XvuadorBMmUYbRaI_WuefrRUiqB-HuRyrxu8UWcs5k8OrFQ9naPx3F6jKKtww0vdI-ZZRr-aWUc8P85dgZ29WKhw5zV-0XiCSAbNwyhXZy0TyXmOBRl-m4f3ogsJtGqlwYhXVEMlzOwUa0iSo-ByB2URUOIQ8f-__ElHhRDOylokWL6iaUy0T5S9FmCNdh1DxzbY5IWmQVVDPqhMlXriSU9SoJm8fLUjyd7Vnp2pXnKgtHt6rc6feE51qnftZHPO2W55JrjuHXMNaZcNqbEsOvIzFlhOq02XNpMSuzmYsjWus1s_q5kS2w1cNBfxGbMZ2k7S2G02RrQ5NtMbCdQ61xgIybm06UI0rWduMs8b_msK3gmSy_TpC22hibOcMaDvXM9bbZyml1SC7qdg6_9pScaXIU5Nz109oizBI1uk9z38b2q8e5q0czNyGSWlRLhctalWLgqbm1sDiLVzR2m4xke08mGzuZ8b2oX8Lr0Zbg09UFmdNiapWo66d-CtqIEVbLpXEynawtvDL7Q3xCodRjcucV3HdqJNugVxTI6IQZfDW-G4ZMdQNutQvKahDFIBa7rKU7WBsjZa5TbJTWTBLDaGyl6-ZUlMz-T7rJsUDpuJIv_gtXmEw9EZLv5OLN5vifeXi_jqgv6Pdh6HPaJA9Gpr9TpyM-8P76m8F_18Cm3gD```

**Comment by Wires77** [comment]
You're _incredibly_ close to the low life threshold.  If you get enough life (via strength, in this instance) you stop being on low life, turning off your Pain Attunement bonus.  If you level your Clarity again it will prevent this
