### ISSUE TITLE
Black Screen Crash on Launch

### ISSUE THREAD

**Issue by Yogeshi86** [PathOfBuildingCommunity/PathOfBuilding#2784]
When launching in Windows 10, PoB is freezing on the main screen and forcing windows to close it. When this started to manifest, it would resolve if the software was reinstalled. It no longer fixes the issue.

I haven't been able to recover any crash files to help diagnose this but am open to trying other ways to capture this data. A screen capture will only show a blank, black screen.

I use PoB religiously while playing PoE and I am finding this very difficult to navigate/deal with.

The issue appears to occur when the software is launched in my second monitor.

**Comment by zao** [comment]
Which Windows 10 version is this, what GPUs do you have in your machine (integrated and discrete)?
If on an older AMD GPU, is your Radeon control panel tuned for Compute or Graphics? https://www.amd.com/en/support/kb/faq/dh3-024

When does it crash, after a bit of launch or rather immediately at startup during the green console or showing the window?
Does it seem to correlate with update checking or some other long-running task?

**Comment by Yogeshi86** [comment]
Windows 10 version 20H2, OS Build 19041.928

Running GeForce GTX1070 8GB card, no integrated GPU showing on my system information. All software/drivers is up to date.

Freeze/lock up occurs right after the initial green console screen vanishes and the PoB window opens. It opens as a black screen with the top bar blank, only showing the minimize/window/close buttons there.

It does not seem to correlate with any specific tasks that I can identify, as the console has already finished its sequence/update process. It only occurs if the window has been closed and then relaunched on my secondary display, and seems to not occur as long as I never move it off my primary after a reinstall (tested this a few more times this morning since submitting issue.)

**Comment by zao** [comment]
Could you try this variant of SimpleGraphic.dll, temporarily replacing the one in your PoB folder? 
https://github.com/zao/PathOfBuilding-SimpleGraphic/actions/runs/842555056

It's going to be annoying and try to redownload the old one as an "update" every time you run but I'm curious if the changes I've made to the graphics backend make any difference.

**Comment by Neclony** [comment]
works for me, thanks!

**Comment by zao** [comment]
@Neclony Ooh, that's interesting.

Could you describe how your PoB was behaving prior to testing this DLL, please also mention what hardware and Windows version you are on?

**Comment by Neclony** [comment]
After the small green window(I believe this window opened on the primary monitor) it opened the actual window in black on the secondary monitor. It constantly had a bit, maybe 10-20% CPU usage and not responding in Task Manager. I left it like that maybe for a minute bur nothing more happened other than when I tried to close it that Windows wrote that it crashed with the typical popup to end the process.

Last time working I closed it maximized on the secondary monitor so I couldn't even "restore" it to a smaller window to move it to the primary(no key combination or option worked). I had to turn off the secondary monitor to launch it again without a problem. I should mention that it works on the secondary without a problem if it opened on the primary, so closing it on the primary is necessary(Windows cached window position).

2 monitor setup, with too many peripheral devices ^^
Version: 20H2 latest security patch
i7-9700k
16GB RAM
GTX 1080 Ti
how specific do you need the hardware?

**Comment by Neclony** [comment]
oh and it also crashes like this in a normal window when it launches on the secondary monitor and I can even move it to the primary but Windows does not remember the position of the "crashed" window when closed.

**Comment by zao** [comment]
@Neclony It should be fine for you to continue using this reworked DLL, the only bug I currently know about in it is that it once failed to completely exit for me when closing the program.

Thanks for the information on the problem and your setup, it'll help to evaluate how safe it is to integrate the changes into the main Path of Building runtime. It sounds like you're indeed in the same problem category as the original poster.

**Comment by Keinaku** [comment]
Hi, i have the same problem the green screen open and after a few second it close the main windows.

My spec :

I9-9900k
32Go Ram 2666mhz
Rx 5500 xt 8GB with radeon software update 21.6.1
3 Screen

**Comment by coffeeblacker** [comment]
FYI - Mine was crashing (is crashing) and i changed the compatibility to Win 8...And this time it stopped with an error (instead of just crashing). 

Error:  In update thread [string "#@...":110: attempt to index a nil value stack traceback: [string "#@..."-:110: in main chunk...press f5 to restart app

**Comment by aestil** [comment]
I also have this issue.
Most recent stable version of PoB.
i7-6700k, 16GB RAM, GTX1070, Windows 10 Pro

When I open PoB it flashes the green console, and then hangs on a black screen in the main window, have to force close it due to 'not responding.' I used to be able to fix this by uninstalling and then reinstalling PoB, but that doesn't work anymore.
