### ISSUE TITLE
High CPU when checking for updates

### ISSUE THREAD

**Issue by zunjae** [PathOfBuildingCommunity/PathOfBuilding#2786]
The app uses a lot of CPU power  upon app startup when checking for updates. Checking for updates can take a minute or two. Once it's done checking for updates my CPU usage is back to normal. Manually clicking "check for update" makes the CPU usage go up again meaning the issue is reproducible. As a result, performance in the app is degraded

Version: 2.3.0

OS: W10 20h2

PC specs: i7 8700K 32GB

CPU usage: about 15%

**Comment by zao** [comment]
App performance shouldn't be too affected as the update subscript runs mostly in its own thread, only occasionally calling into the main thread.

In any way, I've dug into this and found some optimization opportunities.

When the release with PR #2791 ships, the file validation step of updating should be significantly faster, for me it went from 50s to 2s.

**Comment by Wires77** [comment]
Fixed in 2.5.0
