### ISSUE TITLE
Divergent Close combat support does not enable close range modifer

### ISSUE THREAD

**Issue by mmastrocinque** [PathOfBuildingCommunity/PathOfBuilding#2787]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Enabling divergent close combat does not enable close range toggle for effective dps
* **What were you trying to do?**
Attempting to calculate DPS
* **What steps will reproduce the bug?**
Enable divergent close combat support and link to flicker strike
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/gQBGa8eC

Build code is not mine but has close combat set to default quality to 40% to accommodate the lack of divergent close combat working.  change quality to 20% and set to divergent results in loss of dps and no option to enable enemy is in close range.

**Comment by Wires77** [comment]
> no option to enable enemy is in close range.

That option is here and does appear when using the divergent version at 20% quality: 
![image](https://user-images.githubusercontent.com/1209372/118315170-c790bb80-b4ba-11eb-97ba-22c4a38227a2.png)

Whenever you see a mod as red text in PoB, it's unsupported, so this issue can be considered an enhancement to support Divergent Close Combat

**Comment by mmastrocinque** [comment]
> > no option to enable enemy is in close range.
> 
> That option is here and does appear when using the divergent version at 20% quality:
> ![image](https://user-images.githubusercontent.com/1209372/118315170-c790bb80-b4ba-11eb-97ba-22c4a38227a2.png)
> 
> Whenever you see a mod as red text in PoB, it's unsupported, so this issue can be considered an enhancement to support Divergent Close Combat
That option does appear but I figured it's not the same as Chin Sol with similar text has it's own custom toggle for "Is the Enemy at Close Range" 
But I guess when considering melee you want to keep it simple with one option  vs two (distance + is target <= 20 units)

**Comment by Wires77** [comment]
> 
> 
> > > no option to enable enemy is in close range.
> > 
> > 
> > That option is here and does appear when using the divergent version at 20% quality:
> > ![image](https://user-images.githubusercontent.com/1209372/118315170-c790bb80-b4ba-11eb-97ba-22c4a38227a2.png)
> > Whenever you see a mod as red text in PoB, it's unsupported, so this issue can be considered an enhancement to support
> > Divergent Close Combat
> 
> That option does appear but I figured it's not the same as Chin Sol with similar text has it's own custom toggle for "Is the Enemy at Close Range"
> But I guess when considering melee you want to keep it simple with one option vs two (distance + is target <= 20 units)

Now that you brought it up, I think projectile skills would benefit from being based off the one config option as well, so I brought that up with the team to see if we can get that done.
