### ISSUE TITLE
Frostbite on Hit ring not being added

### ISSUE THREAD

**Issue by td30mott** [PathOfBuildingCommunity/PathOfBuilding#2792]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** 
Running a CoC Ice Nova build - have a frostbite on hit ring.  The frostbite effect is not being calculated. 
* **What were you trying to do?**
* **What steps will reproduce the bug?** 
 https://pastebin.com/1qsZtjvC - Use this and you will see that Frostbite is not being included in the calculations
* **Does it reproduce every time?** 
Yes
* **Provide a build code:**
 https://pastebin.com/1qsZtjvC
* **Screenshots:**
![image](https://user-images.githubusercontent.com/84253647/118381233-cb096d00-b5b6-11eb-917f-375f04ec03ab.png)
Can see here it isn't applied.

**Comment by PJacek** [comment]
You can only apply [one curse](https://pathofexile.fandom.com/wiki/Curse#Curse_limit) by default. Frostbite will be added if you gain a source of additional curses. 
![1](https://user-images.githubusercontent.com/18018499/118391937-1d8a6e00-b637-11eb-8b27-3d9839994981.png)
