### ISSUE TITLE
Allow skill sets with a dropdown selector. Similar to the item section's item set dropdown

### ISSUE THREAD

**Issue by Andryshak** [PathOfBuildingCommunity/PathOfBuilding#2793]
**Is your feature request related to a problem? Please describe.**

It's very difficult to accurately compare different skill setups. You must manually enable/disable the different sets of auras and other skills. The two best examples I have is 1) my Vortex guide, where the Chaos Inoculation and Low Life variants use different setups for auras and skills, and 2) anyone who would want to compare different possible aura setups or support gem combinations for a build.

**Describe the solution you'd like**

I'd like to have a dropdown menu that functions identically to the dropdown menu in the "Items" tab. With 2 clicks in the item tab I can swap all of my equipment, flasks, and jewels. I _think_ the easiest way to accomplish this in the skills tab would be for only the selected skill setup to be enabled. Any skill setups that aren't selected would be hidden and internally marked by PoB as disabled. As soon as skill setup "B" is chosen the skills from setup "A" would disappear from the list, skills and auras from B would be enabled, and the skills from setup A would be disabled.

**Describe alternatives you've considered**

Currently my guide's PoB is this: https://pastebin.com/S5Nqbhv1

To make this work, I have to add custom spacing and titles with no gems in them to avoid confusion in the skill setups. If any players want to see the differences between CI and LL, they have to disable and enable nearly 20 different skills manually. In addition, the LL build has multiple variants on its skill choices, so several of them are manually disabled. This change would allow for setups in the dropdown menu to be labeled specifically such as "Trigger wand setup", "Self-Cast Curse setup", "Blasphemy Curse setup", etc.

**Additional context**

I know very little about coding other than the basics of JS/CSS/HTML, but I would be happy to answer any questions about my submission. I can be reached here, or on Discord/Twitter/Twitch/reddit  @ ShakCentral.  Thanks for your time!

**Comment by Crashkurs** [comment]
+1 for this, it would enable skill grouping for various leveling stages like Tree/Items already has.
Really helpful to see: what skills should I have at level 12 or 30 and not see the endgame gem setup

**Comment by QuickStick123** [comment]
Added in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4447.
