### ISSUE TITLE
Rathpith Shield + Necromantic Aegis

### ISSUE THREAD

**Issue by netoprax** [PathOfBuildingCommunity/PathOfBuilding#2798]
I did some search and apparently Rathpith Globe + Necromantic Aegis should not work together
however, path of building does make it seem like that combo work, it calculates the DPS increase of minions

here is a comment by Chris Wilson about that combo:
https://www.reddit.com/r/pathofexile/comments/bwzm8s/necromantic_aegis_rathpith

this should be fixed because other people may also think it works when it doesn't :)

**Comment by Wires77** [comment]
Duplicate of #617
