### ISSUE TITLE
Mines and Aura Totems show mana cost instead of life cost when supported by Arrogance/Lifetap

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#2805]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What steps will reproduce the bug?**
Add Pyroclast Mine, Lifetap Support.  Add Hatred, Arrogance Support, and Spell Totem Support.  Notice both skills claim to have a mana cost instead of a life cost.
* **Does it reproduce every time?**
* **Provide a build code:**
* https://pastebin.com/4ATp1jZ8
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* Pyroclast Mine: 
![image](https://user-images.githubusercontent.com/1209372/118851936-e6ff5e00-b897-11eb-81bf-f0aef96bc78c.png)
* Hatred totem: 
![image](https://user-images.githubusercontent.com/1209372/118851980-f1b9f300-b897-11eb-99ad-d776ee8db4c6.png)

If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Lothrik** [comment]
Is this still an issue? Lifetap and Arrogance both function exactly the way I'd expect them to with Pyroclast Mine in 2.13.0.

I don't see any life (or mana) cost or reservation listed for Hatred + Spell Totem + Arrogance.. which makes sense I guess as the totem would pay the reservation, and auras don't actually have costs anymore.

**Comment by QuickStick123** [comment]
This seems to be resolved closing.
![image](https://user-images.githubusercontent.com/31533893/178718470-a7aabcd6-de24-4b1b-8af5-5780e7932c98.png)
![image](https://user-images.githubusercontent.com/31533893/178718492-f88e8e1c-caa5-4ca9-aaad-39c5b1414ea5.png)
