### ISSUE TITLE
cast on crit cooldown not stacking with CDR from boots/belt in PoB

### ISSUE THREAD

**Issue by spooferclone1** [PathOfBuildingCommunity/PathOfBuilding#2807]
Title explains all, If I'm missing something else please let me know, to specify my cast on crit is crafted onto a shaper weapon. Thanks!

example 1 shows my current item which is only 1 item with CDR

![image](https://user-images.githubusercontent.com/32157369/118873105-f76f0300-b8ae-11eb-9cbb-bd25311e68b0.png)

example 2 shows PoB crafted items with 2 of them with CDR

![image](https://user-images.githubusercontent.com/32157369/118873302-343afa00-b8af-11eb-8031-9d371a1d6f6b.png)

example 3 is where CoC is located

![image](https://user-images.githubusercontent.com/32157369/118873394-546ab900-b8af-11eb-88ae-ee1d530a3b8c.png)

POB: https://pastebin.com/xcdBw4xA

**Comment by Wires77** [comment]
Sharing your build would be incredibly helpful, as it says in the issue template you removed in order to post this.

**Comment by spooferclone1** [comment]
I looked at the PoB under the calc tab and I guess I'm 9% short on CDR for the next break point. Thanks for educating me!
