### ISSUE TITLE
Saviour "Reflection" and tree tooltips

### ISSUE THREAD

**Issue by lols083** [PathOfBuildingCommunity/PathOfBuilding#2809]
Including "Reflection" form Saviour into Full DPS calcs disables additional tooltip info (everything except Full DPS) on hover info on the passive tree.
Honestly its a pretty mild bug thats easy to get around but I thought you'd want to know.
(P.S. thank you for your great work <3) 

ver: 2.3.0

Build code:
https://pastebin.com/BJsSvXQm

**Comment by QuickStick123** [comment]
Seems fixed in dev 
![image](https://user-images.githubusercontent.com/31533893/221762583-0690e7ff-16de-493b-ad5b-2461da1db311.png)
