### ISSUE TITLE
Kalisa's Grace crit chance mod doesn't work

### ISSUE THREAD

**Issue by Steven-lin97** [PathOfBuildingCommunity/PathOfBuilding#2813]
The "Gain +2% to Critical Strike Chance for 2 seconds after Spending a total of 800 Mana" of Kalisa's Grace Samite Gloves doesn't work. Cannot find an option to set this mod activated.

**Comment by Wires77** [comment]
Mods in red are unsupported.  You can edit the item to say "+2% to Critical Strike Chance" to emulate the mod, however.
