### ISSUE TITLE
blasphemy tooltip is not working with curses

### ISSUE THREAD

**Issue by locker702** [PathOfBuildingCommunity/PathOfBuilding#2818]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**     blasphemy tooltip not working or showing increases/decreases when linked together with curses
* **What were you trying to do?**        in skill gem section tried to put assassins mark and blasphemy together
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**   https://pastebin.com/RZ5sTRrq
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

![Screenshot 2021-05-21 180758](https://user-images.githubusercontent.com/84603895/119206010-8f135380-ba5f-11eb-82ad-4baf0b1f62d0.png)

**Comment by PJacek** [comment]
You can't support marks with Blasphemy, it only works with hexes.
