### ISSUE TITLE
Calculation for triple and double damage seems bugged?

### ISSUE THREAD

**Issue by DK99CFH** [PathOfBuildingCommunity/PathOfBuilding#2819]
When you have 12% chance to deal triple damage and 20% chance to deal double damage,

Calculation:
damage from triple damage = 0.12×3 = 0.36
triple damage doesn't proc, and double damage procs = (0.88×0.20)×2 = 0.352
triple and double damage don't proc = (0.88×0.8)×1 = 0.704

sum = 0.36 + 0.352 + 0.704 = 1.416

---------------------------------------------------------

But, PoB Community Fork 2.3.0 says :

×1.24(multiplier from 12.00% chance to deal triple damage)
×1.18(multiplier from 17.60% chance to deal double damage) <- actually 1.1760

1.24×1.1760 = 1.45824, which seems exaggerated.

Am I right or not?

pastebin : https://pastebin.com/U4YvPUke

**Comment by zao** [comment]
For your reference, here is Path of Building's computation of the double damage chance factoring in triple damage chance:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/77ae3a8563c4bbdefe022cf20cbea06499d1bf0e/src/Modules/CalcOffence.lua#L1829-L1835
