### ISSUE TITLE
Rage seems to be capped at 50

### ISSUE THREAD

**Issue by David-Jacobsen** [PathOfBuildingCommunity/PathOfBuilding#2823]
Please try to fill in as much of the template below as you're able.

* **What happened?**
I changed the rage in the Configuration from 50 to 70, and there was no increase in the calculated Total DPS
* **What were you trying to do?**
I was trying to set my rage to 70 for calculations.
* **What steps will reproduce the bug?**
Use a build that includes Berserking skill and Crave the Slaughter ascendency trait. Set your rage to 50 and note your total DPS. Change your rage to 70 and see that total DPS hasn't increased.
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/cAGPhEEP
* **Screenshots:**

**Comment by pundm** [comment]
Hi, 
please follow the provided template and always share your build code so we have a chance to take a look at it.

**Comment by David-Jacobsen** [comment]
I have updated the original post to include the template.

By the way, Github seems to have some log in flows which brings you to an empty New Issue page instead of a page to select the templates.

**Comment by pundm** [comment]
Your Build/Tree is based on 3.11! Crave The Slaughter back then didn't have +10 Max Rage. If you convert the build to 3.14, it works as intended.
![Path_of_Building_82Nq75GbGz](https://user-images.githubusercontent.com/54453318/119233536-f4cc1200-bb29-11eb-876f-03e28679212b.png)
![Path_of_Building_tiMeNhPuPw](https://user-images.githubusercontent.com/54453318/119233545-fc8bb680-bb29-11eb-83cb-f46b0eabda6c.png)

**Comment by David-Jacobsen** [comment]
Hmm, I clicked the update button on the bottom left and it said I had the latest. I’ll double check that and try again. Sorry for wasting your time!

Sent from my iPhone

On May 22, 2021, at 12:18 PM, pundm ***@***.***> wrote:

﻿

Your Build/Tree is based on 3.11! Crave The Slaughter back then didn't have +10 Max Rage. If you convert the build to 3.14, it works as intended.
[Path_of_Building_82Nq75GbGz]<https://user-images.githubusercontent.com/54453318/119233536-f4cc1200-bb29-11eb-876f-03e28679212b.png>
[Path_of_Building_tiMeNhPuPw]<https://user-images.githubusercontent.com/54453318/119233545-fc8bb680-bb29-11eb-83cb-f46b0eabda6c.png>

**Comment by pundm** [comment]
Your Path of Building Version is different and separated from the tree/league version. Click on the green text "Convert to 3.14"
![image](https://user-images.githubusercontent.com/54453318/119234349-c05a5500-bb2d-11eb-8158-0d678ee7d7bf.png)
