### ISSUE TITLE
Scorching Ray and Righteous Fire do not benefit from Saboteur's Perfect Crime notable

### ISSUE THREAD

**Issue by LordMotas** [PathOfBuildingCommunity/PathOfBuilding#2824]
Scorching Ray and Righteous Fire do not scale their damage on the Count of traps after selecting the Saboteur's notable Perfect Crime. Tested in game, Scorching Ray increases its damage per Trap laid. Righteous Fire, being in the same category as Scorching Ray, should also benefit from this interaction. PoB does not reflect such damage changes.

**Comment by Wires77** [comment]
Fixed by #2905
