### ISSUE TITLE
Showing/Hiding Support Gems Based Upon Required Level

### ISSUE THREAD

**Issue by TheTimtam97** [PathOfBuildingCommunity/PathOfBuilding#2830]
It's extremely frustrating to identify the best support gems when levelling. Each gem has a very different required level compared to gem level, so it's very cumbersome to figure out what gems are appropriate for my character's current level or stage in the game (acts). This makes comparing different gem set-ups difficult, I can't quickly sort by true dps because everything is either unobtainable or very under-leveled at gem level 1.

In my mind, the most user-friendly solution would show all support gems with a gem level that is as high as possible while having a required level lower than the user-selected level. 

Another solution could be implementing a sort by dps button after we have selected all applicable gems. We can then tune their gem level to be equip-able or remove them entirely ourselves. This button would either rearrange the order of disabled gems or assign them a number depending on how comparably large the dps increase is if enabled. It's not as good a solution, as the sort button would be required after each gem is enabled. Though it's far better than hovering over the enable button and trying to find the highest number each time a gem changes.

**Comment by Wires77** [comment]
Fixed by #4724
