### ISSUE TITLE
Multistrike does not increase ailment damage

### ISSUE THREAD

**Issue by joshuamaciel** [PathOfBuildingCommunity/PathOfBuilding#2847]
Version 2.3.0 does not have multistrike providing damage to ailments. To simulate on a level 1 character:

1. Equip any dagger
2. Skills -> Viper Strike + Multistrike
3. See that poison has no increased/more modifiers

[Mark_GGG has explicitly stated that Multistrike more damage on repeats affects ailments](https://twitter.com/mark_ggg/status/1318025640726175744?lang=en).

**Comment by Lothrik** [comment]
Fixed by #3685 (in 2.13.0).
