### ISSUE TITLE
Supporting Ancestral Protector with Rage Support disables buff

### ISSUE THREAD

**Issue by olechiw** [PathOfBuildingCommunity/PathOfBuilding#2848]
I put ancestral protector in Hateforge gloves, noticed that buff was not being applied. Can be reproduced like so:
![image](https://user-images.githubusercontent.com/5912683/120847879-15d92d80-c542-11eb-8923-a672788545b2.png)

![image](https://user-images.githubusercontent.com/5912683/120847953-30aba200-c542-11eb-97b6-eb09847afc85.png)

**Comment by samanthar0se** [comment]
I can reproduce this same issue. My understanding about the mechanical interaction between rage support and totems is that the totem cannot generate or gain rage but will reference the players rage value, it shouldn't disable the totem.

**Comment by ggargov** [comment]
I am having the same issue but with Ancesrtal Warchief. I am using Divergent Rage so I generate a little rage when I place a totem, and the totem seems to boost my DPS in-game, but PoB does not. Disabling Rage Support makes Ancestral Warchief apply to my Main Skill DPS on the left side of PoB
