### ISSUE TITLE
Missing Simplegraphic.cfg

### ISSUE THREAD

**Issue by Lordkabul** [PathOfBuildingCommunity/PathOfBuilding#2849]
I keep getting this report every time i try to load.   I have tried updating drivers as well as uninstalled and reinstalled POB.   I am not a programmer but love this program.
![Capture](https://user-images.githubusercontent.com/85461602/120941535-d4cf4d80-c6e8-11eb-8ee1-d905633b3326.PNG)

![image](https://user-images.githubusercontent.com/85461602/120941551-df89e280-c6e8-11eb-84f0-627c70e87c9a.png)

**Comment by pundm** [comment]
Hey, so have you checked if the file is in the folder?
I can paste you the contents of mine for a test, maybe try to create it manually under:

_C:\Users\David\AppData\Roaming\Path of Building Community\SimpleGraphic_

SimpleGraphic.cfg

set con_log "0"
set r_compress "0"
set r_screenshotFormat "jpg"
set r_layerDebug "0"
set con_fontSize "14"
set vid_mode "8"
set vid_resizable "3"
set vid_display "-1"
set vid_fullscreen "0"
set vid_last "1920,1017,0,23,1"

**Comment by Lordkabul** [comment]
thank you so much that worked
________________________________

**Comment by zao** [comment]
Which part of pundm's suggestion was it that did the trick, the new DLL or creation of the config file?

**Comment by Lordkabul** [comment]
Creation of the config file

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Lordkabul** [comment]
Well that fix worked for the next time I logged in …. Now I am getting this  one

***@***.***D75BE3.1ABBFB70]

It seems like all my simplegraphic files are just screwed


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by zao** [comment]
I'm guessing you tried attaching an image here but it got lost when using email to respond to the issue?

Please use the GitHub web interface to show it.

**Comment by Lordkabul** [comment]
yeah sorry so this is the new message i am getting -- 

![image](https://user-images.githubusercontent.com/85461602/121113362-8ba9f700-c7d7-11eb-8639-dd86becaae18.png)

I am not sure what is happening ... i have used POB for over a year and never had a problem until last week.

**Comment by zao** [comment]
The thing that is happening here is that for some reason when Path of Building is trying to initialize OpenGL for drawing, it gets stuck, typically in the graphics driver.

This can sometimes be due to some settings in the control panel for your graphics driver, or something that it has enabled on your behalf, like enabling Geforce Experience or using an older AMD GPU in "compute" mode instead of "graphics" mode.

Could you give the alternative SimpleGraphic DLL linked earlier in the issue a try to see if it changes what happens here?

**Comment by zao** [comment]
GFE _shouldn't_ be a problem in itself but this startup problem surfaces every now and then and we're trying to find a good solution to it, including some big changes to how we initialize graphics.

**Comment by Lordkabul** [comment]
well that must be the problem then ... i did update my driver through geforce experience and that coincides with the issues

**Comment by zao** [comment]
If the problem is still happening, could you please follow these steps and report back if it changes anything?

1. Download my alternate SimpleGraphic.dll from https://github.com/zao/PathOfBuilding-SimpleGraphic/actions/runs/842555056
2. Move away the old one in the Path of Building directory.
3. Put the new DLL in its place.
4. Start Path of Building normally.

If if starts successfully, it's going to think there's an update as this file differs from the stock DLL.

**Comment by Lordkabul** [comment]
ok as pathetic as this sounds how do i download this file?   sorry i am not familiar with github

**Comment by zao** [comment]
At the bottom of that page is a list of Artifacts, with one item, `SimpleGraphic.dll`.
If you are signed in, you should be able to click on the filename to download a zip containing the file.

It looks like this:
![image](https://user-images.githubusercontent.com/260218/121117221-13175a80-c818-11eb-9d52-43a9d22d100b.png)

**Comment by Lordkabul** [comment]
yes it did exactly as you thought.... stuck on checking for update

when it dinally completed i get this ...

![image](https://user-images.githubusercontent.com/85461602/121117561-f2caaa00-c7dd-11eb-9e1f-acec14c34edb.png)

**Comment by zao** [comment]
But it did start normally with the new file in place?

If it works, please don't apply the "update". Doing so will put back the old one that doesn't work on your system.

**Comment by Lordkabul** [comment]
no it did not start .... it just ran through a series of downloads on its own and then would not start up just displayed what i placed above

**Comment by zao** [comment]
Could you again try putting the new file in and see if it reaches the main window?
I appreciate the effort you're making here in testing this out.

**Comment by Lordkabul** [comment]
i get the same message ... i also tried deleting POB and reinstalling ... then replacing the .dll i file ... i get this

![image](https://user-images.githubusercontent.com/85461602/121119562-75a13400-c7e1-11eb-90b3-2152eb146513.png)

**Comment by zao** [comment]
Something is very odd here. This output signifies that it's not using the file at that point.

I have prepared a custom standalone installation of PoB that never updates and which has the modified DLL in it. If you would be willing to give it a try for testing, download it from:

https://zao.se/~zao/poe/pob/custom-pob-2.3.0.zip

You would unzip it somewhere separate on your disk like the Desktop and launch it by doubleclicking on `Path of Building.exe`.

**Comment by Lordkabul** [comment]
I appreciate your working with me on this ... so i uninstalled POB and then extracted thsi file to my desktop.  When running this time i get the following

![image](https://user-images.githubusercontent.com/85461602/121175864-2bd83e00-c821-11eb-966e-52175b389617.png)

**Comment by zao** [comment]
I've made a build with more diagnostic information and stack traces, please give it a go:
https://zao.se/~zao/poe/pob/custom-pob-2.3.0-g34006c8.zip

**Comment by Lordkabul** [comment]
Here is my error message now

![image](https://user-images.githubusercontent.com/85461602/121290912-098c0200-c8ad-11eb-9937-2e3d3d96158e.png)

**Comment by zao** [comment]
This stack trace is quite valuable, it suggests that the crash is happening within what appears to be the driver for an Intel integrated GPU.

Could you please tell me a bit about the computer you're running this on?
What CPU is it? Does the machine have some sort of hybrid Intel/NVIDIA graphics like "Optimus"?

If so, what driver version are the Intel drivers, are they a bit old or do they seem up to date? You should be able to tell either by looking in `dxdiag.exe` or in your Device Manager.

**Comment by Lordkabul** [comment]
Device name	DESKTOP-6T4O7CD
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	96F4B556-F42E-42B2-994C-C3FA48BC28C1
Product ID	00325-81688-13373-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by Lordkabul** [comment]
Nvidia GeForce RTX2060 graphics

**Comment by zao** [comment]
Could you please report which driver version you have for your Intel GPU?
It'll show either if you run `dxdiag.exe` and look on the Display tabs until you find one with an "Intel(R) UHD Graphics 630" device, or if you open the device under "Display adapters" in Device Manager and look at the Driver tab.

![devmgr-igpu](https://user-images.githubusercontent.com/260218/121307067-e0489180-c8ff-11eb-9463-9000891cba3a.png)
![dxdiag-igpu](https://user-images.githubusercontent.com/260218/121307070-e179be80-c8ff-11eb-8a69-f66a300eacef.png)

**Comment by Lordkabul** [comment]
![Capture](https://user-images.githubusercontent.com/85461602/121363396-898d8880-c8fc-11eb-8706-c08ae6942741.PNG)

**Comment by Lordkabul** [comment]
yes it is a docked laptop with two external displays iother than the laptop 
![Display 1](https://user-images.githubusercontent.com/85461602/121364787-b8582e80-c8fd-11eb-8a34-40ab5a9d1fca.PNG)
![Display2](https://user-images.githubusercontent.com/85461602/121364816-bee6a600-c8fd-11eb-9000-d0a8fcb5130f.PNG)
![Display3](https://user-images.githubusercontent.com/85461602/121364833-c1e19680-c8fd-11eb-8fb9-61d4f0fcf988.PNG)
![Display 4](https://user-images.githubusercontent.com/85461602/121364849-c443f080-c8fd-11eb-8f17-6ff8b46d0d70.PNG)

**Comment by zao** [comment]
Thanks for this information and sorry for the delay in getting back to you.

I don't have any clear solution or workaround here, the situation with OpenGL and Intel drivers is a bit weird to begin with and the additional indirection via a docking station makes it even worse.

It is possible that one of the following things may change something:

* check for updated Intel graphics drivers from your laptop vendor;
* check for updated drivers for your docking station;
* disconnect from the docking station to see if anything changes;
* see if there's any context menu item or graphics control panel option to select the GPU to use for a specific program.

From the Path of Building side, there's not too much that can be changed currently. OpenGL on Windows does not have any native way to indicate which GPU to use.

**Comment by Lordkabul** [comment]
well thank you so much Lars .... the option to choose my GPU worked.   As i chose to let it use the integrated graphics instead of NVidia the program runs fine
