### ISSUE TITLE
lucidity does not affect cyclone cost

### ISSUE THREAD

**Issue by fischeru** [PathOfBuildingCommunity/PathOfBuilding#2850]
the notable 'lucidity' has the line '-3 to the total cost of channeling skills'.

allocating the node does not have any effect. since rounding with reduced cost modifiers is kind of iffy, it would be helpful to have this work.

**Comment by pundm** [comment]
Can you please share a pob? Makes it easier for me to look into it.

**Comment by fischeru** [comment]
https://pastebin.com/3A5tNvPP

here is a minimal example. i have two cyclones, one with lifetap, one without. also i allocated chainbreaker to get rage cost.
from my understanding, lucidity should affect all costs. however, allocating and deallocating the notable has no effect.

pob community fork 2.3.0

**Comment by pundm** [comment]
This seems fixed already and will come with the next release.

![image](https://user-images.githubusercontent.com/54453318/121484549-9cbd5880-c9cf-11eb-9f59-62294fb52f90.png)

**Comment by fischeru** [comment]
great! thanks for the quick reply!
