### ISSUE TITLE
Divergent Ensnaring Arrow damage calculation

### ISSUE THREAD

**Issue by rawr1** [PathOfBuildingCommunity/PathOfBuilding#2852]
Enabling divergent ensnaring arrow (10% increased spell damage taken at 20qual) does not affect damage calculation at all for spells

**Comment by pundm** [comment]
Can you please share a pob? Makes it easier for me to look into it.

**Comment by rawr1** [comment]
Here my (own) build :P

https://pastebin.com/13WsyG58

**Comment by rawr1** [comment]
Also when I import this pob from my character the top medium cluster on the right doesnt have precise commander ticked although it is skilled on my character

**Comment by pundm** [comment]
Under configuration you can set # of Ensnare Stacks

Before:
![image](https://user-images.githubusercontent.com/54453318/121342447-ec454b00-c921-11eb-827a-07f1d8bd6474.png)
1

After:
![image](https://user-images.githubusercontent.com/54453318/121342477-f2d3c280-c921-11eb-97b9-bdc9246e44ca.png)

And then it correctly adds 10% inc dmg taken for spells
![image](https://user-images.githubusercontent.com/54453318/121342553-05e69280-c922-11eb-8031-4b910a325149.png)

**Comment by rawr1** [comment]
Damn, I feel like I looked through configuration 10 times. Thank you very much and I'm sorry to waste your time.

**Comment by pundm** [comment]
All good.

Solved
