### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by LiorBirman** [PathOfBuildingCommunity/PathOfBuilding#2853]
DELETE

**Comment by 1avatar1** [comment]
PoB also miscalculates added damage to the explosion.  PoB applies the 50% base damage modifier to all added damage when this is not the case. Comments from GGG Rory explain that both the arrow and explosion have 100% effectiveness of added damage and personal testing with fixed damage ranges confirms this.
[](https://www.reddit.com/r/pathofexile/comments/e96e9d/explosive_arrow_each_arrows_explosion_will_deal_a/fai6z4w/?context=10)
