### ISSUE TITLE
Add an option to disable immortal call and other temporary guard skill in the configuration 

### ISSUE THREAD

**Issue by Antorell** [PathOfBuildingCommunity/PathOfBuilding#2857]
**Is your feature request related to a problem? Please describe.**
I looked around in the Configuration tab, but I couldn't find it. 
I'm a new player, I used the application and thought I had a good dmg reduction until I realized what PoB was showing is just a snapshot of what my dmg reduction is with immortal call up. 

**Describe the solution you'd like**
It would be nice if either the application showed the total reduced dmg with a guard skill up and with the guard skill down/inactive, or add an option to disable guard skill calculation in the configuration tab. 

Thanks :)

**Comment by LocalIdentity** [comment]
You can disable the gem from the skill tab, just uncheck the box 
![image](https://user-images.githubusercontent.com/31035929/122203095-0910ee00-cee1-11eb-9330-2bd7434c2a92.png)

**Comment by Antorell** [comment]
I do that already, what I really wanted it an option to see the dmg reduction with and without in the calc panel, or an option to disable the calculation of guards like immortal call permanently. The skill reactivate if I import new skills with the delete skill option enabled.
