### ISSUE TITLE
Dread Banner Impale Effect for Spells

### ISSUE THREAD

**Issue by BBPainTrain** [PathOfBuildingCommunity/PathOfBuilding#2858]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** The " You and nearby allies have #% increased Impale effect" from the Dread Banner Skill Gem does not work with Spells.

* **What were you trying to do?** I was trying to build a Spell Impale Char with the support of an Aurabot

* **What steps will reproduce the bug?** Use any Physical Spell with Replica Heartbreaker for Impale chance with spells or Divergent Blade Blast which gives chance to Impale on Spell Hit and then add a Dread Banner Skill which should give Impale effect but does not.

* * **Does it reproduce every time?** I tried around a bit and have not found a single case in which it worked.

* **Provide a build code:**
Pastebin: https://pastebin.com/vEQKFbMu

* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by QuickStick123** [comment]
Seems to be working
![image](https://user-images.githubusercontent.com/31533893/218351530-b70c86e6-722b-4114-85bf-c3a5bd9ce12b.png)
