### ISSUE TITLE
support for atlas passives and watchstone modifiers + scarabs and league map device crafts

### ISSUE THREAD

**Issue by waiora** [PathOfBuildingCommunity/PathOfBuilding#2859]
**Describe the solution you'd like**
Just being able to plan out your atlas and farming strats, with an overview of adding 4 watchstones and their modifiers. 

With the new atlas, planning and gearing your atlas is as important as planning builds.

**Comment by Wires77** [comment]
While this may be a useful feature for the community, it is out of scope for PoB as a build optimization/planning tool.
