### ISSUE TITLE
Remove Old 2.6 Code

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#286]
It is my understanding that we are no longer supporting or back-porting any bug-fixes or changes to the old codebase used for Path of Exile 2.6 patch.

Please remove any 2.6 related code:

* Includes all of Data/2_6
* Includes all files that end in "*-2_6.lua"
* Files that end in "*-3_0.lua" could be renamed to drop the specifier.

Why do I request this? 

1. QoL when searching through codebase for various strings or implementation details.
2. Smaller code base

**Comment by ppoelzl** [comment]
Halted in accordance with @PathOfBuildingCommunity/maintainer until we have proper automated testing in place. If implemented, this proposal would result in a very large change set that at this point we are not comfortable with merging.
The affected code paths runs much deeper than you are suggesting, scattered all across core PoB routines. Testing is imperative to not only be able to remove the legacy code but also safely refactor what is left.
That said, to go over your points:
1) If you use any of the suggested development solutions, you will find very convenient solutions for excluding files from search in a project.
2) The right reason to push for this change is to have a less complex code base, not a smaller one. "Less complex" accomplishes a goal, "smaller" is arbitrary.
