### ISSUE TITLE
Spectral Shield Throw

### ISSUE THREAD

**Issue by ghost** [PathOfBuildingCommunity/PathOfBuilding#2860]
The node Gladiatorial Combat (spelled Gladiatoral Combat in POB) does not increased damage by the correct amount. It should make it do much more damage than it does. It might be calculating it from the base armour of the shield instead.

**Comment by Wires77** [comment]
Can you post a build link?  Looks like that node is legacy now, so I can't reproduce the issue

**Comment by QuickStick123** [comment]
Seems to be working correctly.
https://pobb.in/KbnJQPFs0U2f
![image](https://user-images.githubusercontent.com/31533893/221791992-5c2c45fb-c1d6-4ff0-b9eb-6f60dbc73bac.png)
![image](https://user-images.githubusercontent.com/31533893/221792009-1b2b77eb-b73e-4569-af34-d84dc28ada12.png)
