### ISSUE TITLE
Implement Skill Fiery Impact from Experimented One Handed Mace

### ISSUE THREAD

**Issue by Sanatorius** [PathOfBuildingCommunity/PathOfBuilding#2863]
Hi, is there a chance that u could implement the Skill Fiery Impact from that new mace? would be nice to know its damage with support Skills and mods on the Weapon.

https://pathofexile.fandom.com/wiki/Fiery_Impact
https://poedb.tw/us/Fiery_Impact
https://poedb.tw/us/Boom_Mace

**Comment by Wires77** [comment]
Fixed by #2909
