### ISSUE TITLE
How to calculate the damage of Infernal Legion?

### ISSUE THREAD

**Issue by Myrthian** [PathOfBuildingCommunity/PathOfBuilding#2867]
I'm running a Spellslinger setup with Spellslinger - Summon Skeletons - Infernal Legion - Concentrated Effect, and after tinkering around with it for a while I had 1 question: does minion life, minion damage or a mix of both provide the most damage.

Can PoB answer that, and if so, how do I do that?

**Comment by PJacek** [comment]
You need to select the Infernal Legion skill
![image](https://user-images.githubusercontent.com/18018499/174186170-2bffa9ad-854f-44b5-a866-e081b8465f42.png)
It doesn't scale with minion life at all but rather anything that affects fire damage over time. It is dealt by the minions though, so you're pretty much limited to linked supports and generic minion damage
