### ISSUE TITLE
The soul gain prevention checkbox in the config doesn't show up. 

### ISSUE THREAD

**Issue by Antorell** [PathOfBuildingCommunity/PathOfBuilding#2881]
* **What happened?**
Add an item with "increased damage with non-vaal skills during soul gain prevention " veiled mod

* **What were you trying to do?**
Check the dmg increase during soul gain prevention

* **What steps will reproduce the bug?**
Add any item with the veiled mod 
"increased damage with non-vaal skills during soul gain prevention"

* **Does it reproduce every time?**
Yes

* **Provide a build code:**
https://pastebin.com/QASuQhfL
(two boots, one with the old description taken from the wiki, and the other is a ctrl+c from the item ingame)

Seems GGG changed the description for this veiled crafted mod, and the fix that was pushed here (https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1672) doesn't work anymore. 

I tried to edit/update the pattern in my modParser.lua file with the new description, but couldn't get it to display the soul gain prevention in the config.

**Comment by Wires77** [comment]
The mods are cached in ModCache.lua, which is why updating ModParser.lua didn't do anything.  I've submitted a PR to fix it

**Comment by Antorell** [comment]
Awesome, thanks.
