### ISSUE TITLE
SSL Connection error with Wine when auto-checking for update

### ISSUE THREAD

**Issue by trenzafeeds** [PathOfBuildingCommunity/PathOfBuilding#2885]
Hi all,

I'm having an issue running PoB with wine on a Manjaro system with KDE desktop environment. I'm using wine 6.10 package from pacman. Happy to provide any other information that would be relevant.

Whenever I open PoB, or manually press the update check button, I get the error shown in the image below. 
![Screenshot_20210703_133522](https://user-images.githubusercontent.com/13912317/124362606-eaf6fd80-dc03-11eb-81f7-91424be07747.png)

I've only found threads about this error popping up when importing pastebins. The fix in that case was to change https to http. I wanted to try the same fix in this case, but I couldn't find where the update check url is hidden in the files. 

Any help would be much appreciated!

**Comment by PJacek** [comment]
You could try installing `libgnutls` https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/961#issuecomment-645647960

**Comment by zao** [comment]
Working around your problem by not using SSL won't help here, as GitHub mandates HTTPS. Their HTTP endpoint only redirects to HTTPS.

**Comment by xtertristl** [comment]
Hello I'm also Experiencing the same issue. I cannot update and I cannot reach my account to download my profile. I'm running Arch Linux with openssl installed so I shouldn't have any problems creating a SSL connection in PoB.

**Comment by zao** [comment]
Reproduced it with a fresh multilib `wine` installation on Arch.
Console output includes:
```
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
0024:err:winediag:gnutls_initialize Failed to load libgnutls, secure connections will not be available.
0024:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
```

I fixed it by installing `lib32-gnutls` as instructed in https://wiki.archlinux.org/title/wine#Other_dependencies which pulls in the following packages: `lib32-gmp-6.2.1-1  lib32-libtasn1-4.17.0-1  lib32-nettle-3.7.3-1  lib32-p11-kit-0.24.0-1  lib32-gnutls-3.7.2-1`.

After installing this update checks, character imports from API and pastebin imports work fine.

**Comment by xtertristl** [comment]
@zao 
Perfect thanks that worked for me I thought I had it installed before but I guess I missed it.

**Comment by zao** [comment]
Wine is a bit sneaky as PoB is a 32-bit application and as such you specifically need 32-bit multilib versions of libraries.
Gonna assume that the original report would be solved by doing the same.
