### ISSUE TITLE
List of all Gem Qualities that are not calculated / don't work

### ISSUE THREAD

**Issue by grimalkin-esmeralda** [PathOfBuildingCommunity/PathOfBuilding#2887]
Currently, quite a few alternate (and Default) Qualities from Gems don't work / aren't implemented. Some of these have no way to be represented in PoB right now or simply don't matter for any Calculations, but some DO matter and were overlooked it seems.
Some of these have been reported over the Months, but far from all I think.

So here is the list of Gems that have Quality on them that should seemingly work because the Functions already properly work on other Gems or Items (e.g. Reservation Reductions or Stat Requirement Reductions) or because there are dedicated Checkboxes tied to the Function of the Quality available in the Config. E.g. Predator Support makes "Is the enemy marked with Signal Prey" appear, so a check exists and the Gem not adding its Quality Benefits seems like an oversight or a Typo in the Code? Idk.

- Blasphemy Divergent (Alternate2) - Reservation missing
- Blastchain Mine Anomalous (Alternate1) - Reservation missing
- Chance to Bleed Divergent (Alternate2) - Damage missing
- Clarity Divergent (Alternate2) - Damage missing (with a hypothetical "on full Mana" Setting)
- Close Combat Anomalous + Divergent (Alternate1 and Alternate2) - Damage missing
- Controlled Destruction Divergent (Alternate2) - Damage missing
- Cruelty Default - Damage missing(but probably the Cruelty calc isn't known?)
- Dread Banner Anomalous (Alternate1) - Less Damage taken missing
- Efficacy Divergent (Alternate2) - Cost Reduction missing
- Empower Anomalous (Alternate1) - Stat Requirement Reduction not working
- Enhance Anomalous (Alternate1) - Stat Requirement Reduction not working
- Enlighten Anomalous (Alternate1) - Stat Requirement Reduction not working
- Essence Drain Anomalous (Alternate1) - Life Regen missing
- Freezing Pulse Anomalous (Alternate1) - Damage missing in certain Scenarios (Far Shot scaling)
- Frost Shield Phantasmal (Alternate3) - Life Regen missing
- Generosity Divergent (Alternate2) - Reservation missing
- Greater Multiple Projectiles Divergent (Alternate2) - Cost Reduction missing
- Immortal Call Divergent (Alternate2) - Results in less Elemental EHP and more Physical EHP
- Increased Duration Anomalous (Alternate1) - Cost Reduction missing
- Infernal Legion Divergent (Alternate2) - Damage missing by Minions
- Lancing Steel Divergent (Alternate2) - Damage missing in certain Scenarios (Point Blank scaling)
- Lesser Multiple Projectiles Anomalous (Alternate1) - Cost Reduction missing
- Meat Shield Default - Lower Minion Physical EHP
- Minion Damage Anomalous (Alternate1) - Results in less Damage dealt by Minions
- Pierce Divergent (Alternate2) - Damage missing (if pierced)
- Poachers Mark Anomalous (Alternate1) - Damage missing
- Precision Anomalous (Alternate1) - Reservation missing
- Predator Anomalous + Divergent (Alternate1 + Alternate2)  - Minus Allres or Crit Chance and Multi Missing
- Purifying Flame Phantasmal (Alternate3) - Results in lower Consecrated Ground Effect (Life Regen + Crit Chance)
- Slower Projectiles Anomalous (Alternate1) - Damage missing in certain Scenarios (Point Blank scaling)
- Storm Burst Divergent (Alternate2) - Too much AoE
- Trinity Anomalous (Alternate1) - Attack and Cast Speed missing
- Vortex Phantasmal (Alternate3) - Damage missing when cast on Frostbolt
- Warlords Mark Anomalous (Alternate1) - Damage taken on Enemies missing
- Wither Anomalous (Alternate1) - Chaos EHP increase missing
- Wrath Divergent (Alternate2) - Reservation missing
- Zealotry Anomalous (Alternate1) - Crit Multi missing

It would be awesome to one Day see these all working properly in PoB :)

-------------------------------------------------------------------------------------------------

And for Completions' Sake, here is the List of Qualities that aren't / can't be implemented / don't really matter for PoB as it is right now anyways / can't be expressed properly. 
Maybe these can serve as Inspiration for people to implement certain functionalities:
<details>
  <summary>Long</summary>

- Ancestral Protector Divergent
- Ancestral Warchief Divergent
- Animate Weapon Anomalous + Divergent 
- Arc Anomalous
- Arcane Cloak Anomalous
- Arcane Surge Divergent
- Arcanist Brand Phantasmal
- Arctic Armour Anomalous
- Armageddon Brand Divergent
- Assassin's Mark Default
- Ballista Totem Divergent + Phantasmal
- Bane Divergent
- Barrage Support Divergent
- Blade Vortex Divergent
- Bladefall Divergent
- Bladestorm Anomalous + Phantasmal
- Blast Rain Anomalous
- Blastchain Mine Divergent
- Blind Anomalous
- Blink Arrow Phantasmal
- Block Chance Reduction Default + Anomalous
- Blood Rage Anomalous
- Bloodlust Anomalous + Divergent
- Bodyswap Phantasmal
- Brand Recall Default
- Cast when Damage Taken Divergent
- Cast when Stunned Divergent
- Chain Anomalous + Divergent
- Chain Hook Divergent
- Chance to Flee Default
- Charged Dash Anomalous + Divergent
- Charged Mines Anomalous
- Charged Traps Anomalous + Divergent
- Cobra Lash Anomalous
- Consecrated Path Divergent
- Contagion Divergent
- Conversion Trap Anomalous
- Convocation Divergent 
- Corrupting Fever Divergent
- Crackling Lance Divergent
- Creeping Frost Phantasmal 
- Cruelty Divergent
- Culling Strike Divergent
- Dark Pact Divergent
- Dash Anomalous + Divergent
- Desecrate Divergent
- Despair Divergent
- Detonate Mines Default + Anomalous
- Discharge Divergent
- Divine Ire Anomalous
- Domainating Blow Phantasmal
- Double Strike Divergent
- Earthshatter Anomalous
- Enfeeble Anomalous
- Explosive Arrow Divergent
- Exsanguinate Divergent
- Faster Projectiles Anomalous
- Feeding Frenzy Default + Anomalous
- Fire Penetration Divergent
- Fireball Phantasmal
- Flame Dash Anomalous
- Flicker Strike Default + Divergent
- Fork Anomalous
- Freezing Pulse Divergent
- Frenzy Divergent
- Frost Shield Divergent
- Frostblink Divergent
- Frostbolt Anomalous + Phantasmal
- Galvanic Arrow Divergent
- General's Cry Divergent
- Greater Multiple Projectiles Divergent
- Greater Volley Anomalous
- Ground Slam Divergent
- Herald of Purity Anomalous
- Hexblast Phantasmal
- Ice Bite Divergent
- Ice Spear Phantasmal
- Impale Divergent
- Impending Doom Divergent
- Increased Critical Strikes Divergent
- Infernal Blow Anomalous
- Infernal Cry Phantasmal
- Innervation Anomalous + Divergent
- Inspiration Default
- Intensify Divergent + Phantasmal
- Item Rarity Anomalous (Meme)
- Lancing Steal Anomalous
- Lesser Multiple Projectiles Divergent
- Lifetap Divergent
- Lightning Arrow Phantasmal
- Lightning Spire Trap Divergent
- Lightning Trap Divergent
- Maim Anomalous
- Melee Splash Divergent
- Minefield Anomalous
- Mirror Arrow Phantasmal
- Multiple Traps Divergent
- Onslaught Anomalous
- Orb of Storms Anomalous
- Phase Run Divergent
- Pinpoint Anomalous + Divergent
- Plague Bearer Anomalous + Divergent 
- Poachers Mark Default
- Point Blank Divergent
- Portal Anomalous (Meme)
- Power Charge on Critical Anomalous
- Puncture Divergent + Phantasmal
- Punishment Anomalous
- Purifying Flame Anomalous
- Rage Phantasmal
- Rain of Arrows Anomalous + Phantasmal
- Raise Spectre Divergent + Phantasmal
- Raise Zombie Phantasmal
- Reap Divergent
- Reave Phantasmal (functionality is already there though)
- Riposte Divergent
- Rolling Magma Phantasmal
- Scorching Ray Default
- Scourge Arrow Anomalous
- Second Wind Divergent
- Seismic Cry Divergent
- Sigil of Power Anomalous
- Siphoninh Trap Divergent
- Slower Projectiles Divergent
- Spell Totem Divergent
- Splitting Steel Anomalous
- Storm Brand Divergent
- Storm Call Phantasmal
- Stun Anomalous + Divergent
- Summon Phantasm Default 
- Summon Raging Spirits Phantasmal
- Summon Skeletons Anomalous + Divergent + Phantasmal
- Sunder Anomalous
- Swift Affliction Divergent
- Temporal Chains Anomalous
- Unearth Divergent + Phantasmal
- Unleach Anomalous + Divergent
- Urgent Orders Divergent
- Vengeance Default
- Volley Anomalous 
- Vulnerability Divergent
- Warlords Mark Default
- Wild Strike Phantasmal
- Wither Divergent
- Withering Step Divergent
- Withering Touch Divergent
- 
</details>

**Comment by Wires77** [comment]
Thanks for the exhaustive list!  We've started work on these in #2898

**Comment by randomflyingtaco** [comment]
Still missing:
Clarity Divergent (Alternate2) - Damage missing (with a hypothetical "on full Mana" Setting)
Dread Banner Anomalous (Alternate1) - Less Damage taken missing
Empower Anomalous (Alternate1) - Stat Requirement Reduction not working
Enhance Anomalous (Alternate1) - Stat Requirement Reduction not working
(Apparently Anomalous Enlighten is fine)
Essence Drain Anomalous (Alternate1) - Life Regen missing (Life regen on base skill is blue but also does nothing)
Freezing Pulse Anomalous (Alternate1) - Damage missing in certain Scenarios (Far Shot scaling)
Frost Shield Phantasmal (Alternate3) - Life Regen missing
Lancing Steel Divergent (Alternate2) - Damage missing in certain Scenarios (Point Blank scaling)
Pierce Divergent (Alternate2) - Use # of times Skill has Pierced field for this
Predator Anomalous (Alternate1) - Minus Allres Missing
Purifying Flame Phantasmal (Alternate3) - Missing Consecrated Ground Effect
Slower Projectiles Anomalous (Alternate1) - Damage missing in certain Scenarios (Point Blank scaling)
Storm Burst Divergent (Alternate2) - Shouldn't be scaling secondary radius

No reason to support in PoB:
Cruelty Default - see https://www.pathofexile.com/forum/view-thread/3115191#p24145842
Wither Anomalous (Alternate1) - We don't really handle any "enemies deal reduced damage mods"

**Comment by QuickStick123** [comment]
Divergent and Phantasmal Intimidating Cry also don't work.

**Comment by QuickStick123** [comment]
Phantasmal Siphoning trap passing is incorrect.
![image](https://user-images.githubusercontent.com/31533893/178735235-2d9b505b-4fd8-43ea-bcaf-ebae7b0c15ec.png)
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4475

**Comment by QuickStick123** [comment]
Phantasmal Haste https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1707
"Currently the mechanic for faster buff expiration is not implemented, the old debuff expiration mechanic is also not implemented, and as that will stay after heist anyway it is a good opportunity to add it. Having the haste buff expiration effect in pob will help in situations with rounding of buff durations which are not always obvious"

**Comment by QuickStick123** [comment]
Went over the active skills and made a spreadsheet. Will try to summarise the support gems at some point as well. Has breakdown of what should be feasible to implement. 
https://docs.google.com/spreadsheets/d/1-ak0CBsz43g3AF0P3_3M91Bb90ivC01F532viDMHvDw/edit?usp=sharing

**Comment by QuickStick123** [comment]
These don't exist anymore closing.
