### ISSUE TITLE
Rage movement speed not working.

### ISSUE THREAD

**Issue by CottonCorn** [PathOfBuildingCommunity/PathOfBuilding#289]
The movement speed from Rage does not apply unless you have Crave the Slaughter Berserker ascendancy.

How to replicate: create any build, add a separate source of rage (rage support or chain hook)
set rage to 50, observe no movement increase, Change to berserker, Allocate crave the slaughter, observe movement increase.

Example build: https://pastebin.com/X80cqzzP

**Comment by NickRyder** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/28

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
