### ISSUE TITLE
Close Combat Support not enforcing only swords/axes?

### ISSUE THREAD

**Issue by Cleru** [PathOfBuildingCommunity/PathOfBuilding#2892]
First of all, thanks for making and maintaining this great tool, that makes Path of Exile playable at endgame. The game is just so wrong with that it ommits to the players. But now, for my issue:

* **What happened?**
I use a dualwield build and equipping an offhand which can not use a skill supported by Close Combat Support (due to weapon restrictions) still uses the skill.
* **What were you trying to do?**
I was planning a Cyclone Build and considered abusing the fact that Close Combat Support only works with Swords and Axes to equip a mace in my offhand and still only use my mainhand attack. (Dualwield does not alternate if it can't use the offhand!) However, equipping Brightbeak in my offhand to increase attackspeed massively dropped my DPS compared to dualwielding my mainhand weapon. Even dual Brightbleak still gives DPS on Cyclone supported with Close Combat Support (which it should not be able to cast in the first place!)
* **What steps will reproduce the bug?**
Using a skill supported by "Close Combat Support" with a Weapon that is not allowed to use it due to the Support Gem restriction.
* **Does it reproduce every time?**
Yes.
* **Provide a build code:**
https://pastebin.com/cDP5RkcU
[build.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6786655/build.txt)
* **Screenshots:**
No Graphical Bug.

**Comment by pundm** [comment]
Hi,

> Even dual Brightbleak still gives DPS on Cyclone

i had a quick glance at the PoB, with two Brightbeaks equipped you don't seem to get any DPS from CC?
![image](https://user-images.githubusercontent.com/54453318/125753985-cffabcbe-4bd1-4f11-8511-94340cb8a9c8.png)
![image](https://user-images.githubusercontent.com/54453318/125754015-5b510439-9543-48b3-9719-67279c930044.png)

When i equip a paradoxica main, brightbeak offhand, it doesn't work either
![image](https://user-images.githubusercontent.com/54453318/125754262-0e091257-5a27-4537-9c65-0040c9ea8667.png)

Can you maybe show screenshots from your PoB with weapon config + DPS hover? I cannot seem to reproduce this.
