### ISSUE TITLE
Ancestral Inspiration from cluster jewels doesn't grant Arcane Surge

### ISSUE THREAD

**Issue by Ardenian** [PathOfBuildingCommunity/PathOfBuilding#2895]
There is a notable passive in cluster jewels called Ancestral Inspiration that allows the player to "Gain Arcane Surge when you Summon a Totem". This notable can be part of a Large Cluster Jewel with "Added Small Passive Skills grant: 10% increased Spell Damage", for instance. 

Unfortunately, Path of Building does not seem to recognize this effect and it doesn't grant Arcane Surge as an active buff, even when using the Calculation Mode "Buffed" in the Calcs section. 

My assumption is that there is no option in the configuration to tick something like "Have you Summoned a Totem recently?" that would allow Arcane Surge to be active. The "# of Summoned Totems (if not maximum)" as part of When In Combat doesn't seem to do anything. Could this be added, please?

Version as of this report: 2.3.0

**Comment by LocalIdentity** [comment]
Added to list in #384
