### ISSUE TITLE
Malachai's Artifice's effect doesn't been processed correct

### ISSUE THREAD

**Issue by lx19930** [PathOfBuildingCommunity/PathOfBuilding#2896]
It seems that when inserting lightning golem to Malachai's Artifice and use fire skill the elemental equilibrium provided by the ring would increase the fire resistance of enemy rather than decrease it (I would expect it to decrease fire resistance anyway since the lighting golems do not deal fire damage ). Is it a bug or is it how the ring works?

An sample code is
eNrFG2tz2kjyc_wrpqjaq7vaDWj0xmfvFn6GOpN4jZPcfUqNpQG0GUlEGuGQrf3v1zOSQMZgGm1uz6myQer3a7pbyskvX2NBFjzLozQ57dCu0SE8CdIwSqannff3V6_9zi8_H53cMjl7NzkrIqHu_Hz06kR_JoIvuAC8DpEsm3L5oaZkfQJKc5bIGU-TEfstza7T8LTzNk14hzywJIxk_S0QLM_fspifdj5GMph1CMsDnoTn6-uXgsc8kUxEueyQmEXJOA0-c3mdpcX8tGN2yCLij6M0BNjh6Pbd3X2DeZQ0mYPsr05uBVvybCyZJDn8Ou0MwARsyt9EQH7BRAF0PM_pOv1O70WECxbDbyTOeM55uIKlXdux1j__f6TbjF9OJjyQ0YKfZ5E8n7EkWOvm7sI7FHZUCBnNRcSzhoTOLow3z4hTw9gFfJ9CjFzcjtew1PS6tG_43xsjXQfKTmkgmmdnAjxxEP3hNIkkb6LYntW1bGo6e1CexiL1-4DmOi9J95wXdQ2j61im8SLebRrladLKbAcpdp7GD1GyYcC9EtZYg8UUL98g4-zdpEyAOxZGRb7C3ZnQI5aw8zRfh8JuTW6iCX8CujNqLsc4uDtwNg5SiXnLM6ipEoeghD0IYSwbuWzvlJh_aQLupHbBv-KoNQHd3QmVrDWwzBfINQGp4-wWb5FKOORwdlxBOd4L1To4VrDDJMARfZ9kPOfZolHkd5N_ilD5FVNNFeIdn3KkpjecB7NrOJvvmOS4qFxL775oHAWLMo4C3GYcF4dwgHEU4lPj0JdADzTOZcKz6XI8i7gIEemnbNREQdmqiYB0cxPlUI0WLG8mjeO_rE0JjnM6h0MWEEK-0SmY_ndEuc3S31RzJA7EG2RxWmRIJ5bAKK1vZ8s8CuBM1cf-HQ-LAFeVVk3eKF3otlp3i9A874_kMwFt94bmLykkxEEYAylZ8PkiDaf8ICYHYVxFGVgrjxrn2msfAf0OOv5zNt_P4DxV-YRlsIZGM7iJpjOZwByG57KBgtdlxtJ8k42LAUezuCrEkwZ8t6s_R08hJXsQ_JgYX6nHQtMMd6dK-gjCzNSEmiMSqwE9YusOY-fgdJXx5NsSTf8JOIrBZRIWmYpuNI9NjOdsTnp6glefhvE8zaS-eM5EkGuSw2ReSJLo8TtXlv-UFPGDmtnKv2rq7j2DjKM8-PRQTCZqFu-AMJleJFxeXV2e3w8_XFYoY65rFQlSIdg85zCcJ5HokCis3DyG-hxIBDSMh9Xcsx_2I8uCLALz7QdV8x1CVD1m74dTUy8CDPzABMea6H4558rjOc5KVXncD6snVgRcOQNi1NJDJsboPGBLBNyq80DAXgo-iIQ65TB2GkH4lscjBhqOqyx6KCQqovQsgJBAdcUItZr9IULSsgdB0K26tP2Q1aGAiSfoAJC2v-ATDlGKylCd9ffsM0-qelbXrhOdHjnJoahd8zg_W8KhcaUstbFQeAIAx0lWQMkK-YQVQl3_tWAiksuK5_r6Tbnz1FfzWfo4LubzkpJKyRysfXNT3hkIWRFRbE47EybyagOpZdSbzIHuxfR3rYHepkZJIIoQBsLqdKzYCfagWHfIVC0-z9MikdUdnqjDMKy1yEWqZloovoR2NtkoDkqIVycgVoV5LdIHJsxaLQU2ihIw_oZgjTvVxXERxymYdNViXKeCx516NWwanScs6EpERWkY1gQ20TdF0Ny_lNYc6mKh_VEB3rJMaogpj9XdEZcsZJL1hhIs31Pm72ky8Gk7vy-1t43nxqw5rM0QlKaHT-rcU617rQdZESbPNdlprTLeSxH_uvj4yNkcJG4TIWjvqgYabojv5Lxn5DAOM7c7bEVrw_rVJ11L7jPOCSsto5Folb_wpfmcQskNbBJoe5SHTM_yf6KuYVo_ObZtez85FjWtDpFArvGMhNrV4w-FblUmvwzhuAzfKkr6QvMK4fAxzcZcKWsbDugeBYrWABo480L91rIP4WLemwNlEDzvfWBMvINzLVFfu2GYl5KWD1dUd6IGSTKG4-wzJ839vIJSslGbOlVIvHr1IzV-IDIluxFLsXtruV9WhFqG3cdpkvBHOA3CUFf_7jyZNjW5AlPOCPTX_BtvyO7Bv1p20_5BJU_GGRwnRA1fpDxJqttG8_Z65Ce61SthlPaB7qaUEUpu27DLRoKkk5JN3YaUoE6TxhSyj7CErLp2UrbtBJLzX2CDduZc6d_3Hb_Wnz4RMWZfo7iIiWpOtqmgrpM7HqQwzC3JJEtjomz8Od8GrO-soTMm-RZdQw4Bc5EWkK9Ny7fWzrYs31l5FwQCe9erkYoB2D8BkYCYjtpNn1N3R0iQx0jOSLmUIGVJ-AsUch3HMFepZqFS7XtL5PkuvrC8TfUgvrO-3EUSSrXyyxhSSSQ8z9fampbbN2ptrZeTs_LKLU-4VNGVE-uHEqpsRpX-_1NNdXu6tYQWWc6rhG-Epu95q8SztpeGJfTlRKPn20VvXijPg5P3dzcl0ZmU8_y413t8fOzOmZylE_4VilU3SONa8Nf6LHytzp3eAH7OBqPzwcWb82_26LQkX1M7KR-p12dO-W1dRFyT-mApWR7R1eJhCxyl-lDaB-dS37IxcLbjWwg40-z3MfRs3_X6GHoWpQiwvm1grGK5Lkpby7Zx2kJNx9Az7T5GC8vyHAxbi7o48VzPdBBwjkP7mGCx-4aPgaMW9TBwXt9FsXV930TBgR4oM7sWxh22YRsGyh0Ghi01XWqh1LD6KO9CtLgY7_YdHxMF1O6j-Pa9vocRz7c9DFuz71ETFcy076IqmmU4KDjT91EVzbNRtcXq-30UX9fF6EE9k-IqJLoGebgTwUbxtSGeMeHiUCiSGH0Nx8LEAfVtCxX2IKCHKmqujzuxPBelh0ldVHWhQBADZ1MXFVemhXKv4VkO6qjso4qk26eoGml626IFRvx1twNfYJrXg78a99UH6GnLbktdrL_oZcCHiD-SnLMsmEEvrnYt39I0_o-Kc6Pc-r3hTI7YvFqUqLvVxtCq9oWSyYsIOsBM7zrrpYUC_PfqhZcTvfuoNg_q85iX64si52MYsZKwXN7oy4pR-SgGAMmCZRFTyw6z3JRWs-8dXJbLY_L-7fDX95dHIyYYjAzR34BK_s-cQN8bTSJooN8nOdhPrQ6PPpSUjmEQ5sTsul1jfQl6VpBfHpVPaqCnXd0xmyQqMx-Tj0faCnf8yzFxjoYxDC9BpG7QozcsJ5SUkEe_SzbNj3_jj1wIGCM_ZavW_o_fK82O6R-vTUfPRUwIsno5tDEG5Cg6JtAx_gQdmNWn_NjoOn_8-HfPeU0N4x-amlosNYiQxxlPKv3AUHqqZHA_JNc8bsVgY-jZzuAaojVpzWK9xtzH50wUXLMZgBErfxMGFvg4g7Q7WoGrPR6ZsQVvWPrySxGJ6CGLilin5SgN75RARIsF-dp1yiC268TdCeHshahfAtJ7xXKLJ9L6yWW9K68rRf0ORJV7O_OumWJNevVudfzI5mTwsMxzVluHbKmD21A30Uwc2stQZ2kK7mkn0DZd9gh1xoU8EKXcI1kokcxtIlntzIszgvmd0Ox2QrrtuLntrdkmnvZ44A0XMZeHMtoSSW4bPnvC71qkC_WKxeGErfZZRNvws9vFAm0XefZ-92AMeyjZbeHVUnFU3XFayNOiBlr72IRLUj61P9B9263cKr6cNkiolMQ4opWeTmuzmi387rbLJKtd-FqHR5ndvuy3iGna2vgWJiBsDFALsf9E84P0ZHsvuC2isr0b_kS4YEuywkVmDR60heV0u2-2KTFma_O2LBd4f7ZRx0LY6flYhHaD3dpaThttMPnSPsj3iDSIC7HlbCvnTRgY9YZJ73X0q7ZpMommz96g5QmPl8P8LFVPSev3Z8dRVuT1a24V3klv8z_l_hdalj43
![sample](https://user-images.githubusercontent.com/63595994/125632921-f607ac4f-a255-4b56-981b-fa6e4f013646.png)

**Comment by pundm** [comment]
Hi,
you have to set the configuration correctly for it to work:

![image](https://user-images.githubusercontent.com/54453318/125653625-f5680460-cd24-4309-b32b-8fab22e2f242.png)

Tick Ignore Skill Hit Damage & Enemy was hit by Lightning Damage

![image](https://user-images.githubusercontent.com/54453318/125653844-741ba9c8-59ac-411a-9875-394c9224352f.png)
