### ISSUE TITLE
[Feature Request] Quick Weapon Set Toggle

### ISSUE THREAD

**Issue by CubeTheThird** [PathOfBuildingCommunity/PathOfBuilding#2897]
**Is your feature request related to a problem? Please describe.**
It is not always obvious which weapon set is currently selected when inspecting the tree, or other menus.

**Describe the solution you'd like**
A toggle on the top level menu to swap between sets, like on the Items tab.

**Describe alternatives you've considered**
An icon indicator to show which set is in use (I or II) on the top level menu.

**Additional context**
Many of the displayed calculations are determined by the weapon set being used, despite not making it clear which set is selected. Almost every tab uses this, so it seems intuitive that this information should be indicated in a more global fashion.

**Comment by ppoelzl** [comment]
Please continue using the "Items" tab to switch between weapon sets. Items on your character are always manipulated through the "items" tab. Also it's quite clear which weapon set is active - the last one you've selected. If this is confusing, I suggest just sticking with one set instead.

I don't think it's warranted to make the weapon set display/toggle global. I hope you understand.
