### ISSUE TITLE
Cluster Notable "Disciples" doesn't affect sentinel of dominance's crusader slam

### ISSUE THREAD

**Issue by banang** [PathOfBuildingCommunity/PathOfBuilding#2900]
with the absolution skill coming up i was tinkering with a sentinel build.
that's when i noticed that the cluster notable "disciples" affects sentinels of purity from your herald of purity minions. However it does not do so with sentinels of dominance from dominating blow minions.
EDIT: clarification - this is only for the 2nd line, about increased cooldown recovery rate. the increased damage part works as intended, not however the CDR.

this bug appears every time i create a build using those mentioned aspects. might even affect absolution sentinels...

**Comment by Ardenian** [comment]
The "Disciples" cluster jewel notable says "Minions deal 20% increased Damage while you are affected by a Herald", which means that if you use Herald of Purity, its Sentinels of Purity get increased damage. However, by itself, minions from Dominating Blow do not get the bonus from this notable if you are not affected by a Herald buff.

Opening an empty build, these steps allow me to successfully increase the damage of Sentinels of Dominance when allocating Disciples:

1. Add Herald of Purity and Dominating Blow to Skills, then select Dominating Blow as a main skill and choose Crusade Slam as Attack. Make sure both skills are active and enabled
2. Craft a cluster jewel, Medium with "Minion Damage while you have a Herald", with the "Disciples" notable as a prefix modifier.
3. Allocate any cluster jewel socket in the passive tree, socket the previously created cluster jewel and allocate "Disciples".

It does show me a damage increase of 20% for the skill Crusader Slam of Sentinel of Dominance now, from ~2142 to ~2531 damage. If you got ~1947, then your Herald of Purity is not enabled in the Skills section.

When you follow the previous steps, do you come to the same result?

**Comment by banang** [comment]
ah damn, my bad, i didn't describe the problem correclty:
the first line "% incr dmg while affected by a herald" was never the problem. it was and is still working as intended.
it's the 2nd line: "summoned sentinels have 25% increased cooldown reduction" that is broken. it applies to sentinels of purity only, not to sentinels of dominance.
