### ISSUE TITLE
Error In 'OnFrame': Classes/GemSelectControl.lua:478: attempt to index local 'grantedEffectLevel' (a nil value)

### ISSUE THREAD

**Issue by Wyrade** [PathOfBuildingCommunity/PathOfBuilding#2908]
* **What happened?**
An error message popped up, saying the following (handcopied, might have typos, I couldn't highlight+copy the error, but i tried to not typo):

In 'OnFrame': Classes/GemSelectControl.lua:478: attempt to index local 'grantedEffectLevel' (a nil value)
stack traceback:
Classes/GemSelectControl.lua:478: in function 'AddCommonGemInfo'
Classes/GemSelectControl.lua:463: in function 'AddGemTooltip'
Classes/GemSelectControl.lua:387: in function 'Draw'
Classes/ControlHost.lua:77: in function 'DrawControls'
Classes/SkillsTab.lua:399: in function 'Draw'
Modules/Build.lua:871: in function 'CallMode'
Modules/Main.lua:268: in function <Modules/Main.lua:268>
[C]: in function 'PCall'
E:\ProgramData\Path of Building Community\Launch.lua:107: in function <E:\ProgramData\Path of Building Community\Launch.lua:107:>

* **What were you trying to do?**
On a build with no active skills yet, I added petrified blood, then for second gem as a support I searched for "blood magic", deleted the search, searched for "arr" (or maybe a few more letters) for arrogance, then as I hovered over the gems on the dropdown list for the search, the above mentioned error message popped up. After dismissing it, it popped up again hovering over gems in the dropdown list, consistently, i dismissed it several times and hovered back to get the error.
I think closing the dropdown by clicking outside and reopening it solved the issue and no more errors popped up, but I might have removed the gem too, I'm not sure.
* **What steps will reproduce the bug?**
Didn't manage to reproduce it.
* **Does it reproduce every time?**
No.
* **Provide a build code:** Autoupdated 2.3.0 (Not sure where to find a build code if this is not it.)
* **Screenshots:** -

**Comment by karlperemil** [comment]
https://pastebin.com/0VGPNLvT

Happens every time for me when I swap Main Skill to Wave of Conviction

**Comment by besplash** [comment]
Same issue, current version as of 26.07.2021 (should be version 2.5.0). This is a build that doesn't allow me to add a support gem: https://pastebin.com/eXSVEiax

**Comment by PJacek** [comment]
Looks like you are using an old build which is slightly corrupted. You can fix it for yourself if you change the default gem level - it'll get adjusted to a correct value.

**Comment by Wires77** [comment]
Fixed in 2.6.0
