### ISSUE TITLE
Low Tolerance - Notable

### ISSUE THREAD

**Issue by meatballing** [PathOfBuildingCommunity/PathOfBuilding#291]
+8% to Damage over Time Multiplier for Poison
Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage

Line 1 is already supported. Not too sure if Line 2 is something we can support.

**Comment by Nostrademous** [comment]
Isn't it 300% increased Damage?

https://i.redd.it/7p7ngoj5ubk41.jpg

**Comment by meatballing** [comment]
ah yep. updated

**Comment by LocalIdentity** [comment]
Not a mod we are able to support
