### ISSUE TITLE
Empower/Enhance/Enlighten lvl 4 in Crest of Desire

### ISSUE THREAD

**Issue by Pheosics** [PathOfBuildingCommunity/PathOfBuilding#2921]
This is the smallest of issues, but it might be indicative of a larger issue that I am not aware of. Increasing the level of empower, enhance, or enlighten to level 11 with a crest of desire (either +7 level 4 or +8 level 3) causes an error to appear when hovering over the gem. Most likely this is because level 10 is the highest gem level in the database, so there is nothing to look up.

**Comment by pundm** [comment]
Confirmed, crashes for me too:

![image](https://user-images.githubusercontent.com/54453318/126955128-c34ead4b-fd5f-482b-8005-d7bb70e88c13.png)

**Comment by pundm** [comment]
That said, since the Item only has one socket, it would not make sense to put the gems in there :)
