### ISSUE TITLE
Minion Damage Support improperly updated

### ISSUE THREAD

**Issue by Shnarfalarfalus** [PathOfBuildingCommunity/PathOfBuilding#2926]
Minion Damage support registers in minion stats calculation as a reduced life modifier rather than a less life modifier, leading to misleading information about the effective healthpool of minions.

![image](https://user-images.githubusercontent.com/23371279/126578146-0d8d2835-2a48-4f8f-a642-1d09e74d5cfc.png)

**Comment by LocalIdentity** [comment]
Dammit knew something would slip through, will fix it quickly

**Comment by LocalIdentity** [comment]
Fixed it, update and it should be less life now
