### ISSUE TITLE
3.15 Swift Affliction Gem Data Wrong

### ISSUE THREAD

**Issue by jais6278** [PathOfBuildingCommunity/PathOfBuilding#2929]
Swift affliction (and awakened swift affliction) now grant 25% less Duration of Supported Skills and Damaging Ailments they inflict. PoB says 25% reduced. The calculation is actually for less, just the text on the skills tab is wrong.

**Comment by LocalIdentity** [comment]
Yep, this is due to me manually changing the gems. The tooltip will be fixed when we release an update on patch day

**Comment by jais6278** [comment]
Just wanted to make sure it was known. Thanks for updating it so quickly

**Comment by pundm** [comment]
fixed in v2.5.0
