### ISSUE TITLE
UpdateApply.lua stuck on "Updating 'C:\Program Files (x86)\Path of Building/lua/sha1/pure_lua_ops.lua'"

### ISSUE THREAD

**Issue by vomaufgang** [PathOfBuildingCommunity/PathOfBuilding#2930]
After downloading the 2.4.0 update from within the 2.3.0 version of Path of Building on Windows 10 and accepting the admin prompt the Update.exe / UpdateApply.lua gets stuck with the message "Updating 'C:\Program Files (x86)\Path of Building/lua/sha1/pure_lua_ops.lua'". During the entire time the CPU utilization of the core the Update.exe runs on is at 100%.

I let this run for about ten minutes checking the Task Manager an resmon.exe to see if it is actually doing enything. I have attached the screenshots below.

After ten minutes I terminated the Update.exe process and launched Path of Building again. The skill tree and other data from 3.15 appears to be present, however the update checker in Path of Building insists that a new update is available, this time with an empty changelog box, and after clicking apply update Update.exe once again gets stuck on the aforementioned step.

Stuck process:

![grafik](https://user-images.githubusercontent.com/8030636/126580645-3f6bbe6f-824a-43f8-a22f-5ca45261ff37.png)

resmon.exe showing the CPU utilization and what looks like a faulty file handle if you take Windows file system and restricted characters into consideration:

![grafik](https://user-images.githubusercontent.com/8030636/126580705-fd813a1c-7011-49d4-9d9e-290019716ae3.png)

Note that the file handles to not change over time at all, it seems like the process is quite literally stuck on this lua file.

Edit: Not sure if this is relevant but I checked the file system and neither the folder nor the file it is claiming to update exist:

![grafik](https://user-images.githubusercontent.com/8030636/126582815-0ecd17a1-0ced-483e-985c-f342dd436927.png)

**Comment by LocalIdentity** [comment]
It’s an issue with people that kept their old installation of PoB before we created our launcher. Run PoB as admin and it should work

**Comment by ppoelzl** [comment]
Either run PoB with elevated privileges once, or even better: reinstall PoB from the latest release. By default, it installs to `%APPDATA%` now, so you won't run into this issue in the future. Otherwise, you'll have to run PoB with elevated privileges every time we update the runtime itself.

**Comment by vomaufgang** [comment]
Worked like a charm, thanks for the tip and your work on PoB in general!
