### ISSUE TITLE
Hollow Palm incorrect DPS

### ISSUE THREAD

**Issue by daoCZ** [PathOfBuildingCommunity/PathOfBuilding#2934]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** 
I updated my Hollow Palm build to the 3.15 tree and it seems to not register the keystone is active as I go from 10m dps to 8k dps.
* **What were you trying to do?**
Above
* **What steps will reproduce the bug?**
Get a old hollow palm tree then update it to 3.15
* **Does it reproduce every time?**
I've tried it with a couple of builds off of poe.ninja and it seems to have the same issue.
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
https://pastebin.com/XifH4H4Z
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![image](https://user-images.githubusercontent.com/87791158/126581693-a22c9de4-b505-499f-bc45-014b2b24849e.png)

**Comment by chobits** [comment]
Have the same issue

**Comment by andrewtkdang** [comment]
Same Issue. Dexterity does not add flat damage inside calculations.

**Comment by bunpro** [comment]
I think same with Replica Alberon's Warpath

**Comment by pundm** [comment]
Hi,
the wording on Hollow Palm changed ever so slightly, that's why its currently not working correctly.

**Comment by Spazmeister** [comment]
> Hi,
> the wording on Hollow Palm changed ever so slightly, that's why its currently not working correctly.
> 
> As a workaround for now you can edit the hollow palm jewel to match the pre 3.15 version with 3.15 damage values.
> 
> 40% more Attack Speed while you are Unencumbered
> 14 to 20 Added Attack Physical Damage per 10 Dexterity while you are Unencumbered

Out of interest, where do we edit the notable? I can edit the jewel but not the notable unless I've missed something simple.

**Comment by pundm** [comment]
> 
> 
> > Hi,
> > the wording on Hollow Palm changed ever so slightly, that's why its currently not working correctly.
> > As a workaround for now you can edit the hollow palm jewel to match the pre 3.15 version with 3.15 damage values.
> > 40% more Attack Speed while you are Unencumbered
> > 14 to 20 Added Attack Physical Damage per 10 Dexterity while you are Unencumbered
> 
> Out of interest, where do we edit the notable? I can edit the jewel but not the notable unless I've missed something simple.

Edit the jewel and paste the lines just below it
![image](https://user-images.githubusercontent.com/54453318/126633467-41630f2c-3a87-4e8f-bcfa-16fae0b0b8e1.png)
![image](https://user-images.githubusercontent.com/54453318/126633489-1b7873f3-6ec6-4dda-80ce-8b1516f0f0ea.png)

**Comment by pundm** [comment]
fixed in v2.5.0
