### ISSUE TITLE
Multistrike not working with Totem Skills

### ISSUE THREAD

**Issue by pabloaram** [PathOfBuildingCommunity/PathOfBuilding#2936]
I dont really know how to report this but one of the changes in the Patch 3.15 from PoE was the new ability of Totem skills to use Multistrike as a support.
Please if the team can modifie this to really knew if is worth it in the new patch/league
Tranks!!

**Comment by Nostrademous** [comment]
We thought we had it working, apparently we made a typo and hence it's not working. Will be fixed in next release.

**Comment by pundm** [comment]
fixed in v2.5.0
