### ISSUE TITLE
Pantheon Bonuses have not been updated to 3.15

### ISSUE THREAD

**Issue by Kraaaaal** [PathOfBuildingCommunity/PathOfBuilding#2938]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Pantheon Bonuses have not been updated to 3.15.
* **What were you trying to do?**
View the new Upgraded Soul of Garukhan, which no longer grants 6% increased Movement Speed if you haven’t been Hit Recently, but now per patchnotes, should grant Cannot be Blinded and You cannot be Maimed.
* **What steps will reproduce the bug?**
Select any Pantheon bonus and cross-reference patchnotes
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/cijCCa25

**Comment by Nostrademous** [comment]
Right. That comes from the GGPK which we don't get until 3 hours before league start (potentially 15 hours before if it's in the torrent download).

**Comment by pundm** [comment]
fixed in v2.5.0
