### ISSUE TITLE
Implement Support for Notable Wandslinger

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#294]
https://web.poecdn.com/public/news/2020-03-03/Wandslinger.jpg

```
25% increased damage while wielding a wand
5% increased attack speed with wands
increases and reductions to spell damage also apply to attacks while wielding a wand
```

Mods 1 and 2 are already supported, mod 3 is not.

Mod 3 is supported in pieces, but does not parse as a complete 1-line mod.

**Comment by LocalIdentity** [comment]
Added in 1.4.162.1
