### ISSUE TITLE
Effective Hit Pool calculation flaw

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#2941]
* **What happened?** The way Effective Hit Pool under Calcs is currently handled does not account for the Hit Damage exceeding your Maximum Hit Taken. For the purposes of calculating Effective Hit Pool this value should be capped (or the average number of hits you can take needs to be adjusted), as the output makes no sense otherwise.
* **What were you trying to do?** Check Effective Hit Pool for relatively high Enemy Hit Damage values.
* **What steps will reproduce the bug?** Set Enemy Hit Damage under configuration to some large value greater than the maximum hit damage your character can survive. Notice that as you increase that Hit Damage, your character's Effective Hit Pool continues to go up.
* **Does it reproduce every time?** Yes
* **Provide a build code:**
`eNq9Wutz4sgR_2z-iimqkkrqykajF5KD78oPbFMxXg7s3eTT1lgMMGdJw0kjbO5q__f0SMLIXh6NNok_sDD69bunp3u0nV9eo5AseJIKGZ816YnRJDwO5FjE07Pm48P1sdf85edGZ8DU7NPkIhOhfvJz46iTfychX_DwrOnTJlEsmXL1ecXK-gqs5ixWMy7jPvtNJjdyfNa8lzFvkicWj4Va_QpClqb3LOJnzVEAxE3C0oDH48v1egGMmIhHMnjm6iaR2Rz0bZKF4C99OQZMrz_4NHyoCBVxVSgofdQZhGzJk5FiiqTwcdY8B9vZlF-xCD6BGwszYGWcGIblOrbhO7bpmoZnNlub6UdzzsdvdPTk_wgcJLw7mfBAiQW_TIS6nLE4qNiwje5QbD8LlZiHgicVrZxtFLffMbfa27APUrHwajB653fb8myf2g6ltu17_zNSqfZb_0Wo2UUI4agnSJP3prFQvD79QIpUxj9m6DvqrZGW0ZOI65q6oj5fTGtQ91nMLmWKiMidmHAcsjvC4Yaw73FIreWAJ1CZFF7ZgwhGar3FzO0a89-rQArFdwvyir_i-FWBW3G9WOG4VYHGdt0WUuXFHuPGtbWubeyonMGpRvfiAMf2MU54ypNFteDuEPCepAztmtLYSTjkU4609o7zYHYDh92QKY5LzDeU4-_2jwaj_KOBG_yzg_97igPcownfu4caJ9Yu9IEe6sY8mS5HM8HDMWIbaj9VSVD-qhIgY10lOdSiBUuru4e6u60p4LjAczjygGDMsV3C4RSDRP6mO5fwMLLzJJLZuvT5Ft1pdQFHGT2YLVMRwHGZN4JDPs4CXHV6a8H6csEjSPi8f4OOdB2abaQXIfSyWNOBbRgeRHGuFAuer-R4yg8SchDFtUjAW6moHG_HLgL9CfruSzbH9CV6O2EFrNFoAXdiOlMxTDV4KR9I8LbMmEwPMGYNR4u4zsIQ1e-NnsV7pGJPIT8lxqvZ9toT6m7t1gbyBZSZ6XEvRWysCrrP1m3G1vJ-nfD4jyWa_zs4SkA3HmeJzm60jI8U34vptPJ5WH_rRXOZqHzxkoVBmrPsxfNMkTifZVPt-a9xFj3piar4d10lqshIpMHXp2wy0QNuE5RJ8rG8e33dvXzofe6WJCOe1yoSyDBk85TDxBuLsEnEuAzzCOpzoBBoGN7KSXg_9gtLgkSA-_ZD9bCFUDUffPfj9EyKgEEcWMixLnpYzrmOeIrzUlke92Pz8RGBK-Y8jFn5QIlxOg_YEoF7azwQ2G7Iz0WoTzmMn_qQvsXxiEHDcZWIp0yhMiqfCRAa6M4YYVa1PURoWnQhCL5lk7YfWR4KmHyCDgDp-ys-4ZClqB2a7_oH9szjsp6talcn3x4pSaGo3fAovVjCoXGtPfXhzuAdAI6TJIOSNeYTloV6_deMhUItS5nr9bviBjFfTWfyZZTN5wUnvSVT8PbdXfHkPFQlEy3mrDlhYVokQech4ZywvA3TjZ-upoXJ8KN6mdgb6ypPYiinwMDxPMtqEgXElWtL6pQ3kgVY8znqdMew6cb3mq5VrDwO7_IvRzOl5ulpq_Xy8nIyZ2omJ_wV-tqTQEatObABnY7zkn-sBbXO4e9Cf5yfneWMWitOneJqMy3Ylr9yXbUm1DWpB8FSPCoUa23BUeoYCJxLPcvG4GzHsxA40_R9DD_bc9s-hp9FKQLm2wbGK5broqy1bBtnLfU9DD_T9jFWWFbbwYi1oC1Dqee2TQeBcxzqY5LF9g0Pg6MWbWNwbd9FiXU9z0ThwA6Um10LEw7bsA0DFQ4DI5aaLrVQZlg-KrqQLS4mur7jYbKA2j5Krt_22xj1PLuNEWv6bWqikpn6LqqiWYaDwpmeh6pobRtVWyzf81FyXRdjB22bFFch0TWojTsRbJRcG_IZky4OhSKJsddwLEweUM-2UGkPCrZRRc31cCdW20XZYVIXVV0oMMTgbOqi8sq0UOE12paDOip9VJF0fYqqkWZ7U7Z0WpVuB35Ao5a3nbqT01_uJQwC-pleXP3I-7zPgr-QlMP0ORspGJyb5A8po3_njZ1uE285U302L1tK_axsMa2ywYQp70rAWJLkzfGqU9XAf6306_RA3bTsKPX3EVf52-Ys5dBGy3j8hbO5jPNlLacY3QFIFiwRLIZls-isi070aAjLanlKHu97vz52G_9kMvorcEj_kRJQOFGNm1AmQmYpGYRM8cbngs0pGSSc0BPjxFgvXWYJ6K4axVjPx-TtifmRTdkwwxOjkbthyH8_Ja7XgOk4FIFQ6SkxGrcshXiRMiKNP0sbTum3n6hhGERJErFXEWUR0YPXGmB--8nZ_fzPhMVTfmqcON_-ZhrHtvH3vxARBwlnMIAQfR9IitkjT4q-HA81nuRU-hWiU3jRLmeYlvZx0dqHcnVNciHHS7K6Gl4l2tt9ShG9rZGrBqnKtIAROnphc3L-tExTFpYeIhu20SbSj2Qmjmw36kJKldZUaJMte5S64KE6kOQahqdnYqFUMjepZNVzL84J5n-JzK6npFtPmlvfm3XyaU8EbnkYcXWooA2Z5NaRsyf9oAIu9KXu4Yyt-ruI1pFn18sFWi_z7P3hwTj2ULab0qum4ai649TQp0YNtPaJeTuSDgzfZi_Xyi-nDhFqS2ICUctOp7ZbzRpxd-vtJKte-lqHZ5ldv-zXyGla2_kWJiFsDKiG2j_Q_CAjWT8Kbo2srB-GH0gXbEnWtMhdg4fW8NxQxFNcJ3Bwodjq3prlAh_P76YXhDkWwk-0fhjs2t5y6gQHs1_qJ_kelc6jLNxwthVDJwyM-QVFfjOQv9yX8URMv3tnz2MeLW-FWr_Z9_O_1Wu1kqrT-vhf6v8DkoVMDg==`

* **Screenshots:**
![](http://puu.sh/HYdji/6c3c852763.png#)

**Comment by Regisle** [comment]
A few points: this is intended but not well conveyed with the current version of the calcs, the entire thing is currently under a rework (here #2390 )
effectively it calculates how many hits you can take before dying, and then multiplies that by the incoming hit
vs a hit of 999,999 damage you can obviously only survive 1 hit, but it still means vs hits of that magnitude you have that much effective health vs hits

**Comment by Lothrik** [comment]
"vs a hit of 999,999 damage you can obviously only survive 1 hit,"

I'd personally say you can survive zero hits in that situation, but that's not really a useful number either. Hence why I think it should be capped based on your maximum hit taken. Good to know it's being reworked regardless!
