### ISSUE TITLE
Passive tree update missing custom mods

### ISSUE THREAD

**Issue by Nightblade** [PathOfBuildingCommunity/PathOfBuilding#2943]
The code that updates the passive tree to the current version doesn't copy custom mods from timeless jewels.

Tested in 2.4.0 with and without my line-space patch.

**Comment by Wires77** [comment]
Fixed in #2943, but this may end up being a problem in the future, because it's duplicating the edited nodes for each tree version, which could eventually balloon the save file size in some extreme cases

**Comment by Nightblade** [comment]
(I think you mean fixed in #2957 :)
