### ISSUE TITLE
Triggered skills not affected by mana multipliers on gems

### ISSUE THREAD

**Issue by george-ctrl** [PathOfBuildingCommunity/PathOfBuilding#2944]
* **What happened?**

Triggered skills (no matter if its from CoC or Cospris) do not get affected by mana multipliers neither by usual support gems nor by inspiration, also "-mana cost" on rings/amulets do not affect them in addition to that the indigon helmet mana increase also doesnt affect them

* **What were you trying to do?**

i was trying to get a mana regen pool needed to make a coc build work

* **What steps will reproduce the bug?**

get any coc link setup, support it with random support gems

* **Does it reproduce every time?**

yes

* **Provide a build code:**

https://pastebin.com/bWaWFJSq

**Comment by george-ctrl** [comment]
i fixed it for myself but in a messy way so i'll leave this ticket open so somebody can fix it properly for the community

**Comment by Nostrademous** [comment]
fix incoming in next update
