### ISSUE TITLE
Support WYSIWYG in notes

### ISSUE THREAD

**Issue by domagojmedo** [PathOfBuildingCommunity/PathOfBuilding#2946]
**Is your feature request related to a problem? Please describe.**
I encountered this problem when watching latest VonVinkton video on YT, he has a leveling guide in notes but he also links to google sheet version because it's color coded and has other features to make it more readable like bold and underline.

**Describe the solution you'd like**
It would be useful if notes section was WYSIWYG editor so we could 

**Describe alternatives you've considered**
Alternative is to have a link in notes to the more rich editor

**Additional context**
![image](https://user-images.githubusercontent.com/12157224/126612907-ee20151f-f657-43de-8f7f-4c7f6b620042.png)
![image](https://user-images.githubusercontent.com/12157224/126612947-17dcdaf9-d269-44cd-9981-ba3fe8ef5d50.png)

**Comment by Wires77** [comment]
Actually, color-coding already exists as an accidental feature that isn't documented anywhere.  I can see if we can put the documentation, but typing `^1` turns the text you type red, for example, and typing `^7` turns it back to white.  Experiment with different numbers to get different colors.  You can also use Hex codes to get a specific color, see here for a list of ones PoB uses: https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/src/Data/Global.lua#L7-L47

**Comment by coldino** [comment]
To add an example of HTML-like hex colour codes - they are in the form `^xRRGGBB`.

Example:
```
^xff4040R^7-^x40ff40G^7-^x4040ffB^7
```
Gives: 
![image](https://user-images.githubusercontent.com/28345893/126648097-0cba75b3-8b79-4ec4-affd-c2e663b1c1be.png)
