### ISSUE TITLE
Are you having issues updating PoB? Look here for fixes

### ISSUE THREAD

**Issue by joschahh** [PathOfBuildingCommunity/PathOfBuilding#2948]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* When trying to update PoB it gets stuck in the Udate Apply.lua
* **What were you trying to do?**
* Automaticly updating PoB to the newest Version.
* **What steps will reproduce the bug?**
* When i try to Uptade via the green update ready butten at the bottem left, it gets struck there every time.
* **Does it reproduce every time?**
* When i close the window and try again, it happens every time when i try to Update.
* **Provide a build code:**
* https://pastebin.com/k6kPfSSr
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* ![fehler](https://user-images.githubusercontent.com/87805841/126617462-4039a141-74c0-4cc6-b66a-8d123f993171.png)
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by pundm** [comment]
Hi,
can you please read this comment tree and try to apply what is discussed in them?
https://www.reddit.com/r/pathofexile/comments/op3u79/path_of_building_community_v240_315_passive_tree/h62rs4x/

**Comment by damianpetla** [comment]
I had the same issue and running PoB as admin helped (as suggested in Reddit from the previous comment link)

**Comment by joschahh** [comment]
Thanks. I tried to start PoB as an admin before and closed all instances befor since i found some older reddit posts that suggested doing so. For some reason it did not work. When i restarted my PC and then run as an admin it worked. Thanks for helping.

For me it was the same as for damianpetla. It already showed me 2.4.0 and the changelog was empty, thanks again

**Comment by pundm** [comment]
No worries, I will leave this issue open, in case more people stumble upon this error.

**Comment by HeffU** [comment]
Ran into the same issue, just posting here to confirm that running as admin made the update work fine and it no longer flags as an update needed.

**Comment by SirTwsted** [comment]
I can CONFIRM I am getting the same issue....!!!!

https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2982

**Comment by pundm** [comment]
> 
> 
> I can CONFIRM I am getting the same issue....!!!!
> 
> #2982

read the second post from the top, it covers the solution for your problem.
