### ISSUE TITLE
Ruthless supports nonstrike, nonslam skills.

### ISSUE THREAD

**Issue by Erik-Chan** [PathOfBuildingCommunity/PathOfBuilding#2949]
Ruthless was updated to only apply to Slam and Strike skills. See: https://www.pathofexile.com/forum/view-thread/3147753

When adding Ruthless to a skill, the tooltip was incorrect. I tested whether Ruthless increases your dps when supporting a nonstrike, nonslam skill and it does not appear to be just a visual error.

This was discovered on Version 2.4.0

![image](https://user-images.githubusercontent.com/46538091/126622435-b5a46fce-c5a1-491f-97fa-ee64398e537f.png)

**Comment by pundm** [comment]
fixed in v2.5.0
