### ISSUE TITLE
spectral shield throw scaling

### ISSUE THREAD

**Issue by MakZmei** [PathOfBuildingCommunity/PathOfBuilding#2951]
When you get to 23lvl SST added damage per armor\evasion is reseting to lowest.
![Screenshot from 2021-07-22 13-40-40](https://user-images.githubusercontent.com/87809493/126627808-c4e7fd0b-eda2-4fdc-9bac-f23dfda0f953.jpg)

**Comment by defry1234** [comment]
Same for Shield Charge. Seems to happen when going over level 21.
