### ISSUE TITLE
Atziri's Rule staff implementation

### ISSUE THREAD

**Issue by HiddTheDK** [PathOfBuildingCommunity/PathOfBuilding#2956]
28 april
Hello m8! Can i ask you one thing about PoB, can u add Atziri Rule skills for futher calculation?
Right now i'm trying to calc it throu lvl 29 flameblast but dont think it's rly accurate.
Much appreciated!

Yep. We almost have full support for it in our dev branch so it should be in the next update

Hey, how it's going?)

**Comment by Wires77** [comment]
Duplicates #2677
