### ISSUE TITLE
Keeps trying to update and gets stuck on "Apply Lua Update"

### ISSUE THREAD

**Issue by schtauffen** [PathOfBuildingCommunity/PathOfBuilding#2959]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** - I updated to 2.4.0. 
* **What were you trying to do?** Update to 2.4.0
* **What steps will reproduce the bug?** I see "Update Ready" button, clicking it and confirming update gets stuck on "Apply Lua Update" screen
* **Does it reproduce every time?** yes
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
![pob_blank_update](https://user-images.githubusercontent.com/8205935/126643632-72b2a0d9-d3b3-42ad-9e9c-742e2b7ed4d3.png)
![pob_updateapplylua](https://user-images.githubusercontent.com/8205935/126643654-5f8eaa5e-6c06-4b44-8015-b0b84729b93e.png)
![pob_update_notice](https://user-images.githubusercontent.com/8205935/126643656-faf6f2a3-4114-4c63-8216-c5020e9f897f.png)

**Comment by schtauffen** [comment]
I'll note it appears 2.4.0 was successfully applied (can convert to 3.15, with new passives etc).
However it keeps asking me to update.

**Comment by pundm** [comment]
Can you please have a look at #2948

**Comment by Ajatuskato** [comment]
Same here, nothing new to add. Windows 10 os and update straight from last available version.

**Comment by pundm** [comment]
> 
> 
> Same here, nothing new to add. Windows 10 os and update straight from last available version.

Did you try to follow what I posted in the linked issue?

**Comment by Ajatuskato** [comment]
Just did, "Update Available" view was blank but all the updates installed and Update Ready notice went away. Friend tried the same and seems to work as well. Cheers!!

**Comment by schtauffen** [comment]
That worked. For others, the fix is:
> Close other PoBs and run as admin
