### ISSUE TITLE
Expand passive tree searchbar pattern matching to use pattern groups

### ISSUE THREAD

**Issue by Aiadan** [PathOfBuildingCommunity/PathOfBuilding#2962]
The passive tree searchbar says it uses Lua pattern matching for complex searches, but it doesn't allow '(' or ')' which excludes pattern groups. Unless it's a deliberate choice due to some reason, searchbar should allow parentheses.

**Comment by ppoelzl** [comment]
What's the use case for pattern groups?

**Comment by Aiadan** [comment]
After reading more on the differences between regex and lua patterns, while lua has grouping, it doesn't have lookaheads, so my use case wouldn't work.
