### ISSUE TITLE
Lua Error when hovering over any passive

### ISSUE THREAD

**Issue by SimplePotential** [PathOfBuildingCommunity/PathOfBuilding#2963]
**What happened?**
After updating to 2.4.0, any passive I hover over generates a Lua error

**What were you trying to do?**
Updated PoB to 2.4 with the in application update function.  It ran fine, closed PoB, and when I relaunched it I can see the appropriate version number and option to change the tree to 3.15

**What steps will reproduce the bug?**
Hover over any passive skill after upgrading.  It does not appear to occur on a brand new build.  On 3.14 skill trees it may only be happening on Raiders.  Other builds does seem to have the issue.  Could also be related to something in the particular builds I suppose.

**Does it reproduce every time?**
Yes.  I've tried also running as admin but no luck.

**Provide a build code:**
See attached
[pob_error_build.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6862931/pob_error_build.txt)

**Screenshots:**
![image](https://user-images.githubusercontent.com/79799865/126653242-bceda624-779e-46e3-a97d-1ab164f0bff9.png)

**Comment by Wires77** [comment]
Duplicates #2945
