### ISSUE TITLE
Error Parsing... Root Element missing (updated some builds to 3.15)

### ISSUE THREAD

**Issue by AngryRoleplayer** [PathOfBuildingCommunity/PathOfBuilding#2966]
F5 does not help

![image](https://user-images.githubusercontent.com/22470478/126667540-a23c804e-e845-4ecb-adae-0cbc0c6f6fa4.png)
Files exist though

![image](https://user-images.githubusercontent.com/22470478/126667763-6480980b-80b8-4a8e-b8c4-164efa0af914.png)

**Comment by Wires77** [comment]
Something is wrong with your build XML.  If you open them up in an editor you might spot the problem.  PoB can't find the root element, `PathOfBuilding`

**Comment by AngryRoleplayer** [comment]
> Something is wrong with your build XML. If you open them up in an editor you might spot the problem. PoB can't find the root element, `PathOfBuilding`

I wish i could know what is wrong.

**Comment by Wires77** [comment]
If you upload your build files I could take a look

**Comment by AngryRoleplayer** [comment]
Ok here's one the stopped loading after "update"
https://www.sendspace.com/file/fsf0yb
THis one works however. Also after update
https://www.sendspace.com/file/pjhh51

**Comment by AngryRoleplayer** [comment]
I have a feeling that the ones that got "corrupted" are some weird empty files now

**Comment by Wires77** [comment]
Yeah, that first build is definitely corrupted somehow.  When I open it locally, I just see a bunch of NULL bytes: 
![image](https://user-images.githubusercontent.com/1209372/126671568-61d4c3a4-e0bc-4e0f-9ede-43158cf27060.png)

I'm afraid that's as much as we can do from here, hopefully you have backups of those builds.
