### ISSUE TITLE
Required level calculation possible bug

### ISSUE THREAD

**Issue by jaizix** [PathOfBuildingCommunity/PathOfBuilding#2968]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
"Required Level" does not seem to be calculating right for Scion-Ascendant. 
Skill points at top reads 115 and says required level is 93. I believe at 93 with 92 points from levels, 22 from quests, and 5 points from ascendant I would have 119 points. 115 points should be required level 89.

* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
eNrtXVtz4kiyfh5-RYUj9sRuDLZ1v_i49wTGl6bbbtPgS7tfHGWpANlCwrpgMxv9309WlQQCJCgwM7sPOzPhwSIzK29VlV-qJB__3_vQR2MSxV4YfNqTD6Q9RAIndL2g_2nv9uZ839r7v3_Wjts4GVz3TlLPp9_8s_bbMfuMfDIm_qc9W91DCY76JLnLRamPIGqEg2RAwuAKP4fRReh-2rtMAxx58R56woHrJZ_2Gr4X4T3k-DiOv-Eh-bTXdUDAHsKxQwK3ObveYBdA4h4aYi_ohs4LSS6iMB2B4nto7JG3q9AFwtZV-7pzUxjdC7LRO9jHLyQe7IEFvx23fTwhUTfBCYrhB4wAjsB98tmDIcbYT0GWIumSqR_oui7JtmnsHa7kPMVD-Lkpc3dEiDtl0g5M2TI1Q9kdPYlAvZvI6_dJ1MEJKfBayq5GaUfkrNcjTuKNSTPykuYAB85sKFs5sE1Tr-LejuMq9RNv5HskKihareLnpTFkSaoivgkT7J-2uzN9DNOw7QNdshTDgIz_U_jCWeqZmmIbB7Kqy5quSZV8914yALbiiLKkybatHxiaqsnKSs4TH6K8hbaUt9UPvIRsydwOvTgMPuCnIqugq5rh8MkL5u0V9FXO2hj3N1W4GYa-G74FUz7pQDYq0_oKB7gZxrM0qEzQS69H5ig1s4r0rCsmsgOrlxglVbNNIliRE3FtN2LoJrNJraiV_uqQ1yKlrFdSnpJ3ETIQKEjZCgr7hCqtEFiklGWzWsNxmLDNT8Sbs7Ft1V6xijtHlLoVODMVlJWCb4OIxHTPmC3_siEpYixZjKecukYniKoasmGZ1WlPhXRIn8xsVyz9wFaNVQyXhDiDC6gF5ja1lTk7WzIkc6XPKHHRZyullnhs9Qyv9pd9INuqCZ6ixYOtrBIy7y_TOtBWUW_oLL7Mzo0Am-WBrlorOb6RZCGMhnpg2pVMQL8cehlCr67k2cx8YDgLSNSfdAce8d15xkoPFFkKqq3MmiKPUPZ8UK8Ng3o2xnFxfaleB7g1nFxsGhCoJIDBJQsl1g452lH4TAtMfzO2RjQM09kWoa-seZ0jTj63XlYXvYNJ7DkwUVjh3yFu6iRiDp7WylfhmAxhBWD1NgCY2agHkly5iJz4AH8Wi1l9hV2-X8pS7bQkwc7Laej2yWbDbMZy7kXgttgrVAT71XNsRn0NiKaJR-uD3wzpxBIdYEYtPMCl1x8kAaBi8VEWWMRtGeAwXhxGEyEXHuI89efAS_UC8eLNUyb4ySdHSHqXXc1xXa3S-nb4BsoMaLsgntWuItRX-H09w3lEgj8mi_JVIfLiAGr1-uumEU1v4TEWOZaHOT5k_RT6qTUchVHCLjax78RMZCsYpQkKWB9k6MXO41Pa69Fuxx4MEbFmzdn5-VnzpnV3lmlRZIlpsB6DdPhEkTL_P22acMouYYsWckLfx6OYuJ_2etiPQbbnZoHuwlrtJEL0ALKzNogI9T2OnMgDJ4oQU3QspDJrXYhQ0iaCECFEBftE3GE3kxGhGRCL-ixbMUWoGWYXouQgW8xABubFwkAcPBGinJYnQtRnPml4Pt0Lxbx2BROBb6Ni9LClRd5TmghmG8NYQnpQXCFkYLGiFNKYVy5CsrPSToQ220LEcg2KBuFonJIegSwWnM1slbjBLyTI1sB8vTtmUyhGMSyEF2QYn0xgozmnXlvo4cwRwBYUpSDbJT2c-vT69xT7XjL5tBd4fvH6Je9as6vxIHzrpqMRl0SnbQx-v7zk3zT8JBNCh8nV58ZRHVknusHqOPY7s4C1o73A8VMXYHe2o05N9_ETHXwP9WnruhmmQZKpQgK6hbq5HbEf0kIvdCcor2AXRqMDUV1-OwbtMvYLP3zCvjIdji39V14AcVjQsPBNdrGbDoch-LYNa1GC4-Fe3t9X5L058fJURyqjxfMkdCNCS4zFEdlgr9yLlBR8SqIA8Apc7pMhvXRFEuziBB-2EnDzIfX1IeOFTwXJr3k8FWnJWw53JMikWx4t5GmeL-hTYuLhOgfmLpDWuSDLoiaGcitgG0vR6lOefatNnuZhiRBhqykvug4Q5abYBHVh2Xsh6y2tThVhHzQnjg_uXZ8EQu7IMmAqdGNPlGjzV6QAYEdIWFjvGvC_6x7foz6QDavlCbtjKgZROSjsoUzSzh3AgCDkoYNd8gG7S8UIm8u4Uc6-cxtPojRhCpUbyMjbOOJaCZm7LFHY1gLrfK6_eAmstk9hQpGtsBPkLeLc9tN4R7GeE0Ux6MwFmZ5lPmi80VICsrsk8Md8MdnFxk2rPdTh3VvUAFwXr9_Kt9i3hdNxvgVFFZrLAersLkkqN2Flk1TNFuR25G0zITO2XSSogFsI7Ho9j7isfvjoHM0NLxcq7oGcH2UCduELTXCyNlzXo-U49n-0d7ZmlQoV9sdZ4NNWGO16_zVZwdzexYGbV9QVdenGmXHuk3jQCNxuMl-pCK5djB2BXogL-Ctqtc8kwr573Wun0eLGsXXJtihz04Tg_LQ0KdEKQvTuxWcgkHQhLTwS5cOxhurOV3raAPhPWulZ8sYJpvD3BAcBiXa0rN3jaEGecMCAFeW8f80Uzssv6owr3PecDxQdJUKELW9EUdif9ex2YlvDcSDNnAksJBS9xXw33xI2tSPiePx23-Y7dc66O9vuvJJyecNewJIMYYumnDsvB7Pbd__epeF76mU367ZOl1McDyo2rmq3MiZhVCE6txuRgwPSTaP-R9BjmRRRuzgv4sw7X7tmRdPsbNj2wIk4YeDee4G7sZWcFTHew93m4kWKI3frXOwmhPggMNjcpCnnrif6v3eC32Hsd1itHKYxvQ2-o62_Wq6ox6kENBWBmIwdF-wd_IF1bVmCeFeFsqLO7F7m7rKpeX9682dmlLpRt7p4K-ajTesyWZv1rt8GJEBcDJrdHvpzOrSnUGElxRrpo4C4WvIWfdqpjMNdhb01HIKemGaqv6MlpFSkuLEZN2LsH8e9-voMoO1_djbmIvTJcLf3Kpalb7qBMQGISUDLCs5uXxTGEC7A1vZ1r0IoyIPugOwsO8okivqC86KM-S-Fl9PjxR9YD5dliBrOOg-c9S8oY-IwjRz63BQYcWQcfSNviH6so2YYsb096FfcnKZfIfkj-5S1FhLHMY5jL4ivcPRSHoxNa_tM4v_gURj_b4yY4AU3Z5_YYYSbiBCEuXVMgJIdAIBfik-pUZ3oQKFLjxCotqXJdUWzTalu6IZl1zVVVpS6ato2fJYNVa8bqqaZdc2wNLhuaLpSlxVJVuuyLplq3bZMs67qlg5iDNk26potWUyYbYEAxVBBpKoacMWUjLoiWyAS6G0NRGqSxYYFYZqkm3XDMCWzLhu2rtUVW9WBF8RbdVUxZQnkK1RNU6YamMCksM-qrcNQsm7KBuhnazb8NCiTbRqglGWCMENTQIBuWaoKPzWg0RRdA2UtxVLqGhhq13VZ1-G6DfbAlyDekHRbqSswqFI3FEmR6ybYX1clRdLrpqZpdd3U1LpqyQpwW4rKbJTrYDpI1gwwV9dlG1TWQEf4KVFXgctBc0uiVmi2DZ9lW6eusimXYVNDJaYbfUgI7ALPgMMUi4sHVWQZ7NV1zdLrQGeYdR3Em-ANHVSAz6A0XIUIgV0W2K5LqlaXLRs0UU34oi7LKr0CImzwpGVZVBOVegPcUddMVWKjW9QKsLtuq_SjqYEwiKQqs5iBWYphgH9s0JxFTqNhAXJVNkFx04TvdAlMUzSTKmxB7EENGUxTNAVcJhs0NGAkTQ4FcsmgzmGpY4B2CuiiSxYMYUg0xSixDrlkUf9AuoHt4ELVhADakHqgmqlBjCWQDT5VIRCqJoNU6juwCvQEH0HwWAxAQc2GFN1DCUycwvOgspY95kknipQtEGeAhIn7jc4ZdqF4BRH4GEZdQuezbIIhfHaxiaYqOhfx22-y9De67GU10xC_e8N0iOgayr9n5-oJVFIEyQfG32h3mS2wIxKhmEFgTqcXxXRB-6CfDLhShzOthNT0HNaujpJD5ZT-ZKtJCy7GhyO6-IxJfBizc2BvUPYcjOgKS03jT7rCyubx89O5uZpNH7zI7OVHs1F2SMolsEYrWlH3rHZ-G3g-QYOQPbOLMOIHz7gMbc5n-bkt1IvCITp7Tb3RiPqgwPC7-jfEzyiiJETsWBjKFBEYbgPXFi_wnDi-7Vxy0wdJMoqPDg_f3t4ORjgZhD3yDoMeOOEw9-s-2zn2ae4dNuCfE_rfl3Tw8PAaOqPOOHxtwyx6Mp6H31PzJhp8Gd1fNZWft2PTG1wafuvuNr36Ft21vqV-8zr4OhqHo8f3ISYXz_13Uxk8DF81--eXk7tnCT_d_jjp7ieXL7f4YTL-8hp7jh-cqRfDu_3J2_1Xc9Lp_HHm9iT3_OTn2G-f3Y_ffzaiZ_OHP04v91-Us7Eix9ej87v31-9XyR_69-_R-VO7qXyR9q1r5VK98-zL85_6uGt8nTw89kdfL0dXweXZgzW--fJw7Xv748vnrzE24lev-5r-mJz-eLy5cPrWexCMfzTeOgNteEo0ZXSh-Yb__Uer_d42ddt4MHtXOG34j7ff_ZPP53cPsux9T_rWH2e2fyUPfihflK_Ev-9dnz1ZLY-HJI_AMX_qOp-r_LfZpDRgIYLkT3h1lJ0dL6GTYYcToDNgS9NE6DTYVAToYGm0ReTB-mzaIvJUWlHnZLJcRWfDbjyjs6rIYHMtmlstT7Fhd54R2pV0sJ2J2AtViixApkPRYYqEgz4MKRJdVdJFhqU7_YzOrMwquueLuA-2btUQGBiqM6G0gu1RF6HTDLBEhE7SJCEHQpUo4kBVlmwhMsMS8p9mqLbQdAO_iPhZhypNyA7FNIT8LFumyLiKpZki48q07BKRR6t0IQfSQl5gQTBoCSmioKSrilCi2pYtNDM1oUSVTUUWWyfF1iEGaoQcSGGFwAJoyIYhlIG08BfaQKBUF5rpUO-LLbzFzFqVMYaYByHzhTJGkQ1ZKKVNRWhqUvAiYohpGyJruW3aIjsNgFJVxAyK_YS8AntSiRXHh4WyB34B4C_SAWCAjvcBOPJjyJY3Axi-5XiMI0qOnzis46iZw3reL8jwKQPxBVTMoRfvCCxhY46Bi50GDqJ5v4GByGl3Qs3wa4aeF7sQc0CaokrekOBol7clOLLmDYYivuYomONfDks5OuZ4nDcwOJrk6Js3CDjW5Liew-O8vUHROsfmHKvyVgdH0xync6jM2x4cm3PknrU9GHLP0C-D2bxfkTVOeFOE9SE46uWAeq5NwlA_a5DwVgFvgXCgzxE6x-K84cMbKgzoc7jOeysc6PMOSxHoV_VZOMhnyJz3footF9484lCftyw4nOdQn7diONSn3STejuH4njVleAeAQf2sUcD7Mwzq8y4Nh_q8V8PgfQb1ad9mGenrq5H-4Y5gXetbb2hcaJOBdHs-tH9aymcvag1vn_Sb9_NoPxh1Mrj1_NrJYR-FRR7AqKf7twz-3TH4dWp1hnfN94uxOfj-_aVlxHexdQkwaxy9nzjPEzv5wxh1W3e2-WYM76wbBeCb3ju_u_Tc9p0nn3xObr34dUiern5qinEbplI6mLziycP7qym9vz5Mnk_xvhf8sAGdkdGPx4ufI3O_OQg1gHmG9Dx6ILZ7ob0OJlfEenkF2IbPPRwFrfbL-X27M0o6zvnlMx7c3Yfdx5fbB_3lcRx0391O81qdWMP-l95zY_zl5x8_7s_Us5fLHhmalyc33-681HOfJx2n5Q0uLOe98enTf-Hcfx6cEwVC_y44JwgzqnbPrQGdII4Uxi2CRYVgibJrNCdcQgnCOdHS7T8dzYmWqsIoTbR5IormRFGaKOoTBgWicE4UjewazomiJVG4KQwPReGcKDwUhZuiOHzXaE604SHc-BJsaIk2yIQ7czvGcxUNnnI4d3xIb_TSD9_ChN95oBfzX9ht4DuPvKGY4MgZdJOI3kz_IwyHD3TqmAdQcdMdGsCBwh8e_0xwcoVH01velPZyek6HPXie4OTU6_VIxG6_5HetKeGPT3v7qnkAi5oiqWBu5rRjdtIgux1dfLYrjUl2EpTgURiwy4Wn1Skpe-o-uzPfwfTxiiN0-631_fas1vQCF-p3ejMqfEO3UVDrev6YROgcyviX2m3gvaYEtU6PENFMy-phxVTIk64Sx3Z7kqPLGkCLJ0eGRHRVpSe5NkA0LLuSokiu-gSBsBWNuORJrTFNmBuOkGnXssfrj5Ai1djVDnk9QppVaw1Hvud4SXyEpFqHOPzVKUhG_CUq_JTYJExRMwzidEgQDhB_iYWLnDAaxaR2FpChBzz55acJY3BT-sYUblr2CCxK8AtB8zcS-W0tOnRIPaHMbhxOh_5Kj2LAuHSgSZncKbfKuNmzg1twy4ybvz4iu6-2iRjTKNq18Fx4flevjJFODxqv-RRS5lOo0-ic1fJDI7Uzx_fA9yAc93q17gDTu6z8G9_NPzYj3IOAHCGa77V2RHre-xH6V4SDPjmSDqBy_pWlMZuoxGWPdMY8IudegP2bt_AzDtzbJxLJywL0X9kpHOKeTFpBPPL4OToudJ7pWxiQWjftzUuAvfrXZQheyr3FncV9JU_py5hlzjh7aJvdJWXvpNHm0j1bhY7Qyf7038IcMKXiHJBr_0pwPz5yMn1-ydJctvLzMxXBreV-RBds9Yjo0fbMQXRWsEFhahVcNWOZu88MYw5Dys6esc2miDyXX_ntaWpwTdbWp15Fmqmr0uzGSyDlL3AaJD74cC7RyrOLhar6l6UM0E3zV3kMS4PPfimNbmef_VuIrGHPr26yXuk_HvRR9ozvo8scXic-e-ZkdiENxsTzifs4DN16di1nmlHXe15Efv3L4f75Nc3XvyvSvqL_gy0y-ePE-V19WF1hBaJ5kITscHcedLqRXtGT1SADMUn8_BlbILLjVMtB1VYF9Qt2CWoMU4jox4K45pcmBmdM4qQYrunn4jakF-Ok1Kaea8A26WAoDNhm5MVDnAUK568Y-lVYi36n_lWlf1APnpL3hFDbS_0H1Gs9qM978Kpx0WrWTj08pI9y8O16he8q03VmtGLOZ2e5GsaqQM4ODu58Ysq_mmkUk-vgs5fMnQ2EwfnCLjA9i-YapctsRPipyLoPG35VMOeOGmXvV8_WUguVHTOcbdqgPcKoQ1fiMEJZfcV28NWJIVcnhrkqIpesZmr6aQzph76QN-Kv24X1X41eD_xCdwOogum5ylYUBiewTL2QSIj-CtPhkgE5TwNYldgiFD-WrLXLrOcheH_2fveFCVy0g29QRwhPRTwurJcL9OzQFjsAe4Ss8qTQ5pJCLcx8140huG3elc72xtnXCgICWCvnv2cbbqYr3xXmBNI9dgiV9yJXH9wDKspKcXdYWJ9rctmIyIsRcyAqeLCSkkYV5WGtpOKxRBBMVIxmRTJaq5LxirgeTJuPZiPQxHEakXboBUn8-CjExJ9OIwl-w5NVW8SaDMvLsEeHlzDVGaZtk2FaZYZVxgfPZdhGCaYL1GiV4-ZRQDwM1YTM8yh3fXna2P9Nm_-mzeZpI0ur8oYb8dG0OQc7k7DH3tQhWnWuS4esgHikRcaKXFArqlOtqjyluaBW5sL60GqVB6qrtxvqHgoguIMq4iSvrhoBwSaiAWINBv7GabYTcrYqwgKA44QlNciSsPXFo7QA5OS5c85zGFmv-io7OP1GuzrZyWnWOzGrQCGQJgNKNCZV26-8skfTCScwUU_SqA-GJbV7HPlh5O4UPP86Jf6YfCb-kL17fziZf00Ve6yTvt1C3gGa1ueD8I3g6GmC8uYf6-zZq0qoZReOwW2YPjikZFW3Wto1vYFa6CIiEwgLAOPal9TtM6SdBfCOSzmiax1SD2T5QJpdAxQTAWmNv1kZtJp-oywJKsdphrUw_TOtASL9Lltip_WXkm4qRPn1O232LAoRSdzPOEZBOCt1Z0nxd0Wn4En6R0nnKgvGHDVDWtW9kSIqk_c1oAQ9MXs6ji9Z_EW31IJ4NazS8lsDlRT6WgqjGprJWmn-nIRJ4oNV5xgmNOS-Pxqkecv9kuB-So5Qd0L_iBmYUZEF6kL2N8FTrDERBjFx6EMv4OEI9hEXQZV_G897WJX29XkP548c10oEOEw26xgmA7rms17xAMIN4HdELelgKNHihcgcSPvKgcSjU9F8xn0MMD6ZTlr6BOzy-FmLOmtOFwZZoescD8IjioVi9HdzX16wm6c0XS0CqmimyeqQq39K2nT9MH9xO29Yo8I9sbwzVCDiq2zh_loJTf6kZk5jLJPwxtuMJH_DfnaXacUdpuKNpTLtu294hBpPkzjGeaGJyu7LlbAusilibEv-mqM6CcMk3lKhMlvWKHVCoKrZjIXPLFVIJaVMJXU794o5QdkRm7adksZ2oxnbe1NeE-CyfFoTAT5pNx2oJJOMbcZZk36wJY_pH7bYXLC6_SyStxlP2y4X5O0yT1sfHhHHbiq2LL22NFxo3dG30GeLNVBdN8z0zfcbhq_cy1vll74Nk9CUXN6vSyKxlaH61n5Vtgi8sd1UUrfLX3XzNNO2X_e3SGp5a-erIlNTEyHaQu0PVD-Ckdw-CsYWWbl9GD6QLqJrMuUVnDXipFt4joECZZslRtnavVsuF-Lx3MYcVcBPy-BJOAza1t7St7FGZL5sn-RrVKpCkYcZjGQnLdkhRvYXzsKg5_WX_l4ZRZnsDZnsHUjs_UNPYegTHGRHJA-rWWiHoUPo31T1J-vZ6N9ROw-jxOtNNhjjMnzjf4F3LceAvhvZ98GE7I-RNAfEeVnPCGB7_u_kiRhy5qe0KS8kffmv2Albz_q5rSDxhp5Leyybst7QU1sibKDmwl_zW-Y4Psxz6PiwjZPBdY_9JT1w-D9r_w--gf2Q
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
![image](https://user-images.githubusercontent.com/87826169/126682421-1090db2a-f2e5-4458-89c6-f700ff82b5f9.png)

**Comment by Wires77** [comment]
Fixed by #2932

**Comment by pundm** [comment]
fixed in v2.5.0
