### ISSUE TITLE
Cost multipliers do not work with spells triggered by Cast while Channeling

### ISSUE THREAD

**Issue by MisterRawSushi** [PathOfBuildingCommunity/PathOfBuilding#2969]
I have cyclone with cast while channeling and soulrend and some generic support gems (void manipulation, vile toxins), but the cost of casting the skill is only the base cost of soulrend (26). The cost of cyclone does get increased by the cost multipliers of the support gems.

I've also tried socketing Lifetap support in it, but the cost of soulrend remains the same despite the 300% multiplier.

**Comment by pundm** [comment]
fixed in v2.5.0
