### ISSUE TITLE
Avatar of the Veil reads 80%, but Calcs shows 100.

### ISSUE THREAD

**Issue by BFalls158** [PathOfBuildingCommunity/PathOfBuilding#2974]
* **What happened?**
When viewing calculations, Avatar of the Veil is adding a value of 100 (vs the new 80)

* **What were you trying to do?**
Calculate Elemental Ailment Avoidance

* **What steps will reproduce the bug?**
View Value for Avatar of the Veil under the "Calc" tab

* **Does it reproduce every time?**
Yes

* **Provide a build code:**
2.4.0
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
![image](https://user-images.githubusercontent.com/21185277/126722899-14b76c85-45cc-4eac-947b-862718ec1126.png)

**Comment by Wires77** [comment]
Can you please provide a link to your build?  The new value should be 50% avoidance and I can't reproduce it on my end

**Comment by BFalls158** [comment]
https://pastebin.com/CRdwLYVF

**Comment by Wires77** [comment]
Are you on an old tree version?  I see it working just fine when I load your build: 
![image](https://user-images.githubusercontent.com/1209372/126724769-ee183ac6-928a-4e05-abf5-6921aa6ac622.png)

Make sure it says 3.15 as the game version when you hover over your tree:
![image](https://user-images.githubusercontent.com/1209372/126724806-fd1ea203-6298-47f0-920e-a50b13db0f25.png)
