### ISSUE TITLE
new gems don't appear

### ISSUE THREAD

**Issue by AngeloMerlo** [PathOfBuildingCommunity/PathOfBuilding#2975]
I don't know if it's normal or not, but the gems that have been added don't show up in the skill selection. in that case it would be the gem eye of winter

![image](https://user-images.githubusercontent.com/2489566/126726863-2004cd2a-af45-44db-987c-7fd6593a83bf.png)

ty

**Comment by RUSshy** [comment]
I hate the same issue, i tried to download fresh files, they still don't show up

I am using the portable version

**Comment by zao** [comment]
The 2.4.0 update of Path of Building only had changes to existing gems as informed by the patch notes.
The full information needed for the implementation of the new gems is not available yet.
