### ISSUE TITLE
Continuous Error - Mana Reservation Permanently at 50% with nothing on or selected (skills, gems, or items)

### ISSUE THREAD

**Issue by Caravanhymn** [PathOfBuildingCommunity/PathOfBuilding#2976]
* **What happened?**
 Looking at reserved skills - looks like reservation numbers are wrong for mana. Started a new skill tree with zero points. Set all items to none. Disabled and did not include ALL skill gem groups. Still showed Mana Reservation at 50%.
* **What were you trying to do?**
Clicking through my reserved skills - Wrath and Petrified Blood (mana reserved) and Arctic Armour (arrogance Life reserved)
Life reservation is correct. Mana reservation is wrong when I turn off both. Still shows 50% mana reserved.
* **What steps will reproduce the bug?**
Click on Reserved skills (4.1 boots and 4.2 boots) groups
* **Does it reproduce every time?**
Yes. Delayed when I tried later. Clicked to disable. Left, came back, and error showed up.
* **Provide a build code:**

https://pastebin.com/hZR12UFj
```
* **Screenshots:**
*
![image](https://user-images.githubusercontent.com/87840530/126730608-4f5ad41c-29cd-467a-aaac-b504e6a439ab.png)

**Comment by Wires77** [comment]
Apparently, if you have a gem setup selected that is disabled, but one of the skills is enabled, and you have that gem setup selected as your main skill, it will still apply the enabled skills.  In this case, the 50% mana reservation comes from Pride in your "gloves" gem setup

**Comment by PJacek** [comment]
It's this line https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/38ce2f1350d97e46a3387c756576dfe76c32faa0/src/Modules/CalcSetup.lua#L829
The `main` skill is special and also sets some implicit flags like `UsedMinionSkillRecently`

**Comment by Caravanhymn** [comment]
Unchecking the Used Minion Skill Recently stopped the constant error from popping up!!! Thank you thank you. I can now use PoB for League start :D :D

**Comment by Caravanhymn** [comment]
Orrrr I was wrong. Unenabled the Pride in the disabled gloves. Turned off the Used Minion Skill Recently. Then another error popped up. Forgot to screenshot it. Will do so if/when it pops up again

**Comment by QuickStick123** [comment]
Doesn't seem to crash any more but is odd seeing your mana at 50% even though it is disabled so will leave it open.
