### ISSUE TITLE
Inquistor - Pious Path Incorrect Details

### ISSUE THREAD

**Issue by Shellcarnage** [PathOfBuildingCommunity/PathOfBuilding#2978]
Screenshots linked, thought i'd bring it to your attention. Sorry if this was the wrong place to do it.

*EDIT* After checking the Heiro one is incorrect aswell stating ele immunity
![Screenshot_6](https://user-images.githubusercontent.com/87850237/126749337-8fa31075-e4ea-4586-a655-c6d63801eaad.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/87850237/126749353-7acc9c3e-1d87-4fe6-816b-b81d9356eb84.jpg)

**Comment by pundm** [comment]
Are you sure you are on the 3.15 tree and not looking at an old version? It's correct on mine.

**Comment by Shellcarnage** [comment]
> 
> 
> Are you sure you are on the 3.15 tree and not looking at an old version? It's correct on mine.

I am such an idiot, I imported a old PoB and never realised! Thank you

**Comment by pundm** [comment]
No worries.
