### ISSUE TITLE
Missing "Supported Skills deal ##% more Cold Damage" on Bonechill

### ISSUE THREAD

**Issue by yodelmas** [PathOfBuildingCommunity/PathOfBuilding#2979]
Missing "Supported Skills deal ##% more Cold Damage" on Bonechill

**Comment by pundm** [comment]
Hi, the gem data isn't complete yet and will be fully integrated with the next update.

**Comment by yodelmas** [comment]
Oh ok ok :) ! Do you have an ETA ?

Thanks

**Comment by pundm** [comment]
Sorry not yet, as I'm not the one fiddling with the torrent. My guess would be shortly before league start.

**Comment by LocalIdentity** [comment]
The more cold damage from the gem is actually working by the way. Just doesn’t show in the gem tooltip. You can verify by looking at the calc page and the more damage section for cold damage
