### ISSUE TITLE
1.4.157.5 - Lightning Golem Wrath Aura Error

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#298]
If I have this option enabled:
http://puu.sh/Fh4bz/10d49b36d8.png

I can very consistently get these errors to trigger by trying to add/remove support gems on multiple different gem setups:
http://puu.sh/Fh4bX/ab86f3619e.png
http://puu.sh/Fh4cz/fbb29ec1ab.png

I have to disable the "Enable Wrath Aura" option to make changes to my skill gems. This problem doesn't exist in vanilla PoB, and as far as I'm aware didn't exist in the fork either prior to 1.4.157.5.

**Comment by LocalIdentity** [comment]
Same root cause of error causing this issue https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/254
