### ISSUE TITLE
Getting constant error, screenshot included. 

### ISSUE THREAD

**Issue by Wearetestingstuff** [PathOfBuildingCommunity/PathOfBuilding#2980]
Constantly getting the error of the screen shot below. Changing ascendency nodes, ticking boxes, allocating passives, and really any thing I do to directly interact with the UI of POB is causing this error to pop up.

```
https://pastebin.com/Y07N6xiA
```
* **Screenshots:**

![Screenshot (170)](https://user-images.githubusercontent.com/35764566/126750597-c06836af-6be4-433c-bc52-f0583a6eb1b4.png)

**Comment by Wires77** [comment]
Duplicates #2945
