### ISSUE TITLE
Physical to Lightning support is scuffed

### ISSUE THREAD

**Issue by ax1m** [PathOfBuildingCommunity/PathOfBuilding#2984]
I just noticed that Phys to Light support showed up very high in my suggested supports. Upon hover it showed +38.4% dmg, too much for even the pre-nerf version. When I select it and click the enable/disable checkbox, this error shows up:
![image](https://user-images.githubusercontent.com/13188591/126785627-07ae0b5a-edd9-4180-a022-c05dbc186b42.png)

**Comment by Seyona** [comment]
What skill were you trying to link this to? I am using Phys to lightning on multiple skills without issue

**Comment by Wires77** [comment]
Should be fixed in 2.6.0
