### ISSUE TITLE
Error when switching from Summon Carrion Golem to any other skills in PoB

### ISSUE THREAD

**Issue by Icemasta** [PathOfBuildingCommunity/PathOfBuilding#2987]
* **What happened?**
![image](https://user-images.githubusercontent.com/60716357/126833493-5b02f6a7-9aa1-442e-82d2-fb54088c3c46.png)

* **What were you trying to do?**
Changing skills on the left side, from summon carrion golem to any other skills.
* **What steps will reproduce the bug?**
Have carrion golem in one slot, chose it, then pick anyone.
* **Does it reproduce every time?**
Yes.
* **Provide a build code:**
https://pastebin.com/jwb05rWy

**Comment by Icemasta** [comment]
Apparently it only bugs out like that when I hover my mouse over a node. This made me think of full dps, so I've disabled Full DPS from Carrion Golem, it no longer bugs out. If I recheck it and I pick anything else, crash.

**Comment by z0w13** [comment]
This seems to not occur with just carrions but also with summon skeletons included in full DPS needed to uncheck both

**Comment by Icemasta** [comment]
Right, there's something weird if you pick full dps. It started evaluating nodes for the minion, not yourself. So things like defense nodes get calculated for your minion, not you.

**Comment by michaelreggio** [comment]
It seems a variable is being used that is nul on use.  I fixed it myself by adding a check for the actor variable at the start of the CompareStatList function.  Added "if actor then" on line 1268 and then added the corresponding "end".

**Comment by michaelreggio** [comment]
Same issue as #2945

**Comment by ppoelzl** [comment]
Duplicate of #2945
