### ISSUE TITLE
POB Community Fork Not updating.

### ISSUE THREAD

**Issue by BSpawns** [PathOfBuildingCommunity/PathOfBuilding#2990]
I've been trying to update POB to 3.15. and when I click the update now. It brings up a blank update notes then it closes and pulls up a command prompt named "UpdateApply.lua" And it says 
Applying update...
Updating 'C:\Program Files (x86)\Path of Building/lua/sha1/pure_lua_ops.lua'

And has said this for awhile now. I've tried it twice.

**Comment by ppoelzl** [comment]
See #2948 
Please check for duplicates before opening a new issue. Thank you.
