### ISSUE TITLE
Trinity support doesn't add damage anymore

### ISSUE THREAD

**Issue by Lox90** [PathOfBuildingCommunity/PathOfBuilding#3000]
**What happened?**
Trinity support doesn't add damage on my Doomfletch Prism build anymore. It worked fine last league. Setting "lowest resonance count" to 5 in configurations also doesn't fix it.

**What steps will reproduce the bug?**
Load my build (or any build with doomfletch + skill linked with trinity support).

**Does it reproduce every time?**
yes

**Provide a build code:**
https://pastebin.com/w9WtbVc1

**Comment by PJacek** [comment]
Are you sure you are using the correct input box?
![1](https://user-images.githubusercontent.com/18018499/126904668-168a75c3-c0ff-493e-99e4-d5fddef2aff9.png)
It works fine for me 
![2](https://user-images.githubusercontent.com/18018499/126904703-09bc8038-8055-4a0e-81d9-9daa3dcec72b.png)

**Comment by Lox90** [comment]
I'm an idiot, was using the wrong box
