### ISSUE TITLE
Earthbreaker support gem is missing

### ISSUE THREAD

**Issue by jacob-vm** [PathOfBuildingCommunity/PathOfBuilding#3002]
Hey is it possible you can put the Earthbreaker support gem in PoB. I am currently using it ingame, but I have no way to create a build where I can see which items I should get until the Earthbreaker support gem is in PoB

**Comment by zao** [comment]
Work is underway, partial support can be tracked in PR https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2999

**Comment by pundm** [comment]
fixed in v2.5.0
