### ISSUE TITLE
Lesser Poison Support/Poison Support Name Updates

### ISSUE THREAD

**Issue by Thanat0sNihil** [PathOfBuildingCommunity/PathOfBuilding#3004]
![image](https://user-images.githubusercontent.com/37569877/126902116-9e2f2d06-a049-4b93-9b85-c2933b9ea985.png)

Though the effects of these two skill gems have been updated, the names have not, causing them to fail to import from in-game.
should be 'Lesser Poison Support' -> 'Chance to Poison Support' and  'Poison Support' -> 'Critical Strike Affliction Support '.

**Comment by Nostrademous** [comment]
Fixed in next release

**Comment by PJacek** [comment]
Fixed in v2.5.0
