### ISSUE TITLE
Bug with new cluster mod: Added Small Passive Skills grant: 10% increased Damage over Time

### ISSUE THREAD

**Issue by kdonah3** [PathOfBuildingCommunity/PathOfBuilding#3005]
4% Damage over time multiplier/Chaos damage over time multiplier medium cluster mods are now 10% increased damage over time 

pob doesn't recognize this mod and doesn't display the cluster properly in the tree

album demonstrating problem:
https://imgur.com/a/45Jo0w5

**Comment by Helyos96** [comment]
Seems fixed in 2.5.0.

![image](https://user-images.githubusercontent.com/67038113/126935739-355e18d5-f56f-4a9d-8b4a-53b9bf3cd35a.png)
