### ISSUE TITLE
Last line cut off in "Notes"

### ISSUE THREAD

**Issue by TheOne320** [PathOfBuildingCommunity/PathOfBuilding#3018]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Scrollbar has a normal ending and last line in "Notes" is completely visible.

### What is the actual behaviour/value?

Scrollbar is cut off and last line is not displayed completely.

### How to reproduce the issue

Open "Notes"
Paste text so last line is used.
See wrong UI formatting

### Build code

https://pastebin.com/Xtc0q5Et

### Screenshots

![image](https://user-images.githubusercontent.com/7705568/126982416-54678b68-7f83-4435-90ac-adc670a17acc.png)

**Comment by ppoelzl** [comment]
Hi, I see you have not provided a build code. Please always provide a build code we can check out, Thank you.

**Comment by TheOne320** [comment]
> 
> 
> Hi, I see you have not provided a build code. Please always provide a build code we can check out, Thank you.

Sorry, I was kinda spaced out and did not realise what "Build Code" would mean. I edited my post.
