### ISSUE TITLE
Absolution doesn't have a damage rundown for its spell damage.

### ISSUE THREAD

**Issue by BassOfBass** [PathOfBuildingCommunity/PathOfBuilding#3020]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Absolution having its own damage rundown in the skill selection panel.

### What is the actual behaviour/value?

There are 3 items: "Default Attack", "Absolution", "Absolution". All of them are for "Sentinel of Absolution" minion.

### How to reproduce the issue

Click on its selection dropdown.

### Build code

eNrtXetz2ki2_zz-K1RU5dZuBdvq1tvX2S2M8SNrxw44zmS-pNqiAcVCwnrYJlvzv-_plgABAg4yM7t362ZqMiCd569Pnz6nW2KO__469JVnHsVeGHyokQO1pvDADbte0P9Q-3J3tm_X_v63veNblgxueiep54s7f9v75Vh-Vnz-zP0PNQfYEhb1eXI_EaV9h2sjFiQDHgbX7EcYnYfdD7WrNGCRF9eUBxZ0veRD7VMY8Jri-iyOP7Eh_1C748ORz6KawmKXB93m7M55yqKux4KaMmRe0AndR56cR2E6AsNryrPHX67DLtBdXt_etO8K2r0g195mPnvk8aAGHvxyfOuzMY86CUuUGP76UGsAEKzPL7wExDE_BVmaQWx6YNm1w7Usp2wIf6O5OiPOu1NqekANbfbn3890G_FWr8fdxHvmzchLmgMWuDPvyAFdxbk99XXqJ97I93g041hFf7EsXFVXEd-FCfNPbztTWsuhln1gaKqz1vm38YWz0Flp2VcvGZz4MC4VtAjey37gJbwi823oxWHwBv-KrCtdbIbDBy-o5OGEtfHc35b1mgWsGcazISCmvor2yuvxOdqVvrQ6OLo2ZAAcpbDzlkeQ3hIcgzB2K4ZOUphO-krA2vxpjtIwVlGe8tfZaOhr5BUJCVk5lS-DmRd0rYHzlHS1gc9hAisPDsxZplYNsiZ3ukeC-jJwpwzOWrlfgojHPHou5Nx1GuZZ8hHGJDfB2OZ9PnNXNw4s01hHf8W5OziHlbPNEo4L0pnXjr4WJUFcRElfK7YEJcvBMSxiZB04umXaJiGmpap0nZB5vKhzoK-j3hKtVsCj_rgz8LhfcMpW16JWZCqiR1Fq5v1BsWzr1DOLi1PKVo31_mT0RVdWxwGHFRAYunxhSd8hx20U_hBVjL8dWyMahmmESLLC54y46LJhrrRnMI49F1ZRWS22eTd1cSlrWo1dh898CPEvyzqodotV1spwPvGhVF5wXls3n32_lGU1YEnC3MfTsNtHYyy1bMVx5kUAWewVlr99om2mvoEKvclGmJpFzCmsghk1WsGV1x8kAfRPC1ooRXLgXRmwMF70RceQo1Wcpb6PKgU7j948ZcIefH6kqK-kZxm8x1Z2SbfhCxgzEH1ljJjsBeprNitCVodIxIOfY7T8OXKUglbQTSMR3GgdixxlaqCbhZyxsQUlUFXZB9TWTGPahy6xzneH5ICYVHO07G-6immpQSK6btgHxDJsy7A0bT1fSYO0RFnaICG1lDdIWzAvN0hb-lc2K5aIyxokpJ65-pVolmmuo5yvEoD8YD39-hJhiaW07gEXNAxDeQWzlmWdeceHclNKfLocjsIokRebzHdjKfgyGKWJEsi9pFhkpe9BOnwQGw_Zf6Fgy00oUg692P3-kPZ6YnOpBiZFcm-sdXbWat5d3rdylg6Xa7nihr7PRjHvfqj1mB8Dh9fNk2AHChg3QdFfeEk-nzHUX1nkRh4kGAyxmIEok2VuwFCKbRwUIYwK8zkesLvxiIs4iLGY5bUEhlrmFxRllhBwDsrEgxsG7rIxinIa8ijqls8bni9qRBxq1xDeWXmJo4daL_Ie0gQZbTJZoewQ7SbKwWLGQVmclfMo2XnDg6HNyytcrEE1jR6NU97jEMXI2SyzxB175EGeAyf57lhOoViJIRGe82F8Moa15kygtrD6zBFAeRalILsLhVnqi-ufU-Z7yVgk2cLVq2zjP_B8EDAIXzrpaJTJEZM2BtSvrrI7DT_JRQglE-Mz14SFcjO_Ibsb-V3aL3f0vcD10y6_DPJac-q4zx6E8prSF7v_zTANktwUHojisjvxIvZD0f-E3bEyaeoWtAlFwpZfjsG6nP3cDx-YT6fq5FqRr0rzFubHH1StzbGSqX5Bfili8CEO_TRr9hbFSUlPGUSXMjNIkHPCWxaBCxR85UNx95onrMsSdniZAJyHAtNDKQY-FbU8FYZtEZWJ3JkjboYhfBKLnmhsV9pcvJGf1XxMu5OVah2OaLTyYJq0y3fhtA8qB2odNNO4XCetDKUySCYylCRUZlJ27jjkcJHAmX8Wumn8Bp9XCMK6O2VXMv6dO9oMgySCvAaZiENhNdkOqezvenlYt2dSlKKYnXs_jaBbHvAkYm90fq04rO9TIUpRymrXZdbd1nF55ucysTlR2dtlGVgX5daT0nIHYb7CZvnzz1yRLjhUaEmlxQiNNURxN_WSjtcXZmxYXwhqfekkYTQ8iVjQ3R50warkvHOrSScdDkOoRW6hdk9YPNz9PLsM3IgzqJxEoyLSdwdK2Ef-lsS6USQWl6kgZSJJmYjafbZNo5jfBPLxhuopdlkI1tcL_pqEqTvYoWcyyMUEAjO2dyoP61IhWywWM-Y_P5_8kRnkE3_J2qxsN3JXSaRMJDqNSGYl5975DDmDf73e-A3TY1EC1rEJ3-5dgiWSR9kJzVv8KhODdk4yKxl3_H9jluyg6bvgEfO7N73bNJKZBd34rRmRRZlbp2DBroQ9pcQo6OxevbgF8ngn9LsejybaZFW4w9j8CnXloHK-nufGup5x_Xdl6DMf3Dtl8WBHuXlZHnqKC04lY91NeWchE1wjclnAO-nKFQqV38qkYH3PeJWM-Q9K4M2V3RJ-kBeSebNK85SncsE73fr4r5lOnaHYvX8jynMy5mEtLi2b998ySX9cN3SarttyqBBWqyVv3w1NRfwJERaHaeSK58bBqSPrCMpeRXysK3Jie3GiAKTPorkrbeYnN__IyDzxom4jHonjw9LR2jZjSVGiDEgGXGk8i4fqF4DOP8mThLuIc4Vlrkl-mu_fw5fiY_rCJA30hF1xAqBRzdTruqoSta7rjl4njqmTukkMatQ16jgUbjp1Ylo6fHcsatcNg-hmTUlAX-FFAqLnLwgI-UYOaqsLs6P7SaiSF4pXFA4fw6jDBQqmpgK_58r6JkoO6an4Wzp3CRfjwxFIBs_iw3vG_E-hfDxFnsGIqwfdbpx5lL2D0AS4BW7ykZnshrAKXHXUzLJffnlP3okN4iF79YbpMCNVsuMicTw5ITIlVend48OZM5m7h4v-Hn9pX2X6Bkkyio8OD19eXg5GUOOEPf7q-fzADYcT3_ZlIO0LXA8b8Oek8eW0cWHEQSts_3gcG_2bkxP2W_xCaPghUzeRfpy9ZjHBOPs2dZuYlNgAbpKlh_wEv4SOEENF0JnE1nQMnW7YGoKOUvHg6mY63TYtByNPIwRB5ugqBhXNNFHearqO85Y4NkYeNS1qIOgMnVALYx8xUfaZRFNReg3iYKJF08RzJgh_dQczaibVMFoJBT8wMWWCGxg6FVIkxltqmRpqNFSUWke1VZQbmoMCGQbDxAyuY9iYICC6g9KrE9vC6KW2bmH0UsciFDWJYDnD-GHrmomaHNRGpVLV0Chqcji2g9Kro8KUWJTgUiQyCVFLx_ir68RExTPMS0y8GASyJAoX0zRR88O2KS4JWaj55pg2bsmyTFS8UGKisp9qaQYqrkwNI89yTIy7juWglhjTQWk1HYLK4RopGwyoeWfVDnyB8hZR5xLQqdUNS9fqsIJQK69oYc02aZ1aFG6Klc-uw4DZk3oYkrk6VwoTYlO47lBDr9sQonWYboYNl3W4TKihmXVTNeCmnLB16qgmqRu6CXU1JBgb6mhYhnWooCFtAj0o1SAzGnVI3yboMCyVigJcM7Iiu0501bDgOgU7iE0sva7ptq3CXU0DSkqBhpq6TUC8UEVNaql1SlVwSgNCkKnpIE03TLBS1Ujd0WwTHDPhu65bDlhkqGARLIN1Q7WpKZhtQeuowmbHAieIINNUaANghHXJAhqzZkD2DKZOAa6slQAnKFyxwA4Hloe6WP-NrIcwLAJaYIkUnzVwmFrAA7QEfFGFdQA4kOjEsuqGDVVrHT6B-SAdQCKQFay6QNoCLwAbB-DO2hUd8gXoo8IWFXIbXNAtutyjGOt7lMMdFe2tp97Z0PnNVs9Gzzejp8_7jn3R99zOk3vZv2mkV9cnw8vGb_ev3ti9vv0Re-n3yP326_3o6Wl0TX-y9HPnZ-_y1tC-JfTu6vZX9uNh5D28nn8PBw3a_PxMht3Xp9P7YeB_S33ja3P4evHtpOE-Pj2xOHq2Tdr4x9VrOPraaT59a3XI-PTnVfvx7ItpQvPQ-gYxHRixp78w17tx-k7s_Oo0ereN-6f0NdQ_jp2Ivp60dTo6a5OPdzcv6snoxG7e-IPrlJ0OP7asyHq6bPx_A_Kf1oCga6L_8AZkRdqv3IBga1Rso4JcDJFL684bEOTKj2xAsAXHv6sBwfZb2AIL24BgGwZsA4JtLLANIbaQxTYg2AJ61w0ItsDHNkjYhgbbgGAbGmyDhG0cd92AYBt09C4XbjcHu02D3PXZcQOyYiusvAE5PhQb8OLDpzDJtn_FxckXuT1_7_EXJeYscgedJBLHHD_DcPhNwGocOI5NoaeARYhkz-RfcJZcs9H0HELQ5k_02_nz_AlLTr1ej0fyXYTJYYIg_BVi2NYOICtDlQ5_nOxNwWN5JpQfE4jPHZ4dO6Qx73A3DLpfORuFgbxceAlAkMpXGfLjkjYTDyYcKe1Gu7U3OYvZu_MSFnjpUOmMPLivZA8C7TUj1oMS-0gR5u3dRrznvR4p_4xY0OdH6oFq_T49UhJvohB1SiN-d2j-SyftLXBT-_dGF2p4qPFZ8ZVobUo7xyi_5O86HClU3csH80g52Yd_9iTCbf50pJj23uVw5HuuJ-6qe--JSopHBsLWvffWOyXTJ25J9TIqBB7zyNF1yHWScd9jgXLvxXwjXrozD5iDwGvDlykgBTwaBSwMUsSC7F2wWCFK42Ecx-JhSMmy995Rl_Apx0Jbh8X5gMWJP1ZaY6585C_c3wgIRJA0JXucAaJBPMlQfItfijFLOImecUoCySis1svCjBR1yMeT4wsv6PJIPmeZxYAUQ1dCW4gtcyG2NHMJukxTrHQ5QEwMcZ9ShU1jXZm-6JA5OWUYsGeumO8UdxqXmaFKK-BDj8dKGMCVRHnxkoGSeVLPvmjqOyUSv3jAu8rkVwwU-Y7hioHU1wZ1GLmQmiLlJAyTeOMoEns-rO0SGpjsE7vuOUw20Gq8LeCXMsB8DrAWxsleDnEBmjc9E0fBZqyDrRkGz-GjeLr_Kws2Zk_j9-w4Wo6jOOuXxpMywiw-Ju-FkQEpzcUZVRZSN0G2HNglEwKGKyOd-7mLN2ddi85nmiZkRfGeh5IpA3y7Xs_jUQz5WL7hIzjFYS8DmuytgezhA4FFGU0up0A0N2-ouWY056akZRQp8zlYPt7m_Hh_-XT5-Utrr8Oe2Avz_wcQjv83Vj7xONmDFSTsKm3mCa0AC-unHECCWx6LxuUQnu9P_ymGrjEfuoVAeP8Xauxbxl8FNgKS2eui81Sauq-rf3039yJV8RS8QPwXc58I0kn2aMufApJPhwjgs8cU9og6N1dKnnBQTiBilOxd172y-1CThEofFCdxdmUC37WwUIEZM3_5zJfXwYUACq-HsdLwfW_RUULVfWKoEpD89VIYA_HwlBSYvc06KWdECQhR2Bb8ipQCteGBUcvro7xIXElBN1JoGykmPw5QEmrWutSy8KzMG1Ly2yuNDYlX3Zx4z7MoyGY3VUvDSQbePFQdP5z8bECW3ZRCzzD57aQC0eTRoQmJtUxywsXzPRMCWk6wUC4VtWrLHLlphWaQlIgtvjQ7oTPL6GABnlFMflYobwDWFP_Fmr8MuM4LGy36VdYylbAuslEc29JQLTta0aAyXzYYVTasG1jOfBY_KhrKJFpmklYNXhwIdEdsejUjzWrazOpokg0DXBZPG0Yge29wW0UlkWRW0bMh_FYkM4RgrfosIlUc0avFAqkWefrm4VlK8CXAbiu2LLwqOo7KO0YFeyrkQG2TmumyteXwlaNcKb6MKkyoKYkZiEp-GpVhpRXG3aw2k7Rq4attH2V69bRfIaaXyzUs-BomIHQMUQWz31D8IEdyqUJFj4JZISpJ5TnwhnDBpmTBi5w1eNIKyLVF50qrpBhaGd6K6QI_nksdDsIdDYETqT4MemW0jCqDg5kvS10eOsg3mNQYpn7J2pY11tAyyjMwebwkf9AvDHpeHyiODxf_txT_Avd-T-I=

**Comment by McFrugal** [comment]
The damage for the player's Absolution casts is shown below the minion's damage.
![image](https://user-images.githubusercontent.com/3614140/127628641-de4c97b6-a287-4c11-88b3-4efa6c0bf009.png)

The build code you provided seems to be invalid, I think part of it got eaten by automatic formatting, which turned it into italics.

**Comment by zao** [comment]
OP's rescued build code:
```
eNrtXetz2ki2_zz-K1RU5dZuBdvq1tvX2S2M8SNrxw44zmS-pNqiAcVCwnrYJlvzv-_plgABAg4yM7t362ZqMiCd569Pnz6nW2KO__469JVnHsVeGHyokQO1pvDADbte0P9Q-3J3tm_X_v63veNblgxueiep54s7f9v75Vh-Vnz-zP0PNQfYEhb1eXI_EaV9h2sjFiQDHgbX7EcYnYfdD7WrNGCRF9eUBxZ0veRD7VMY8Jri-iyOP7Eh_1C748ORz6KawmKXB93m7M55yqKux4KaMmRe0AndR56cR2E6AsNryrPHX67DLtBdXt_etO8K2r0g195mPnvk8aAGHvxyfOuzMY86CUuUGP76UGsAEKzPL7wExDE_BVmaQWx6YNm1w7Usp2wIf6O5OiPOu1NqekANbfbn3890G_FWr8fdxHvmzchLmgMWuDPvyAFdxbk99XXqJ97I93g041hFf7EsXFVXEd-FCfNPbztTWsuhln1gaKqz1vm38YWz0Flp2VcvGZz4MC4VtAjey37gJbwi823oxWHwBv-KrCtdbIbDBy-o5OGEtfHc35b1mgWsGcazISCmvor2yuvxOdqVvrQ6OLo2ZAAcpbDzlkeQ3hIcgzB2K4ZOUphO-krA2vxpjtIwVlGe8tfZaOhr5BUJCVk5lS-DmRd0rYHzlHS1gc9hAisPDsxZplYNsiZ3ukeC-jJwpwzOWrlfgojHPHou5Nx1GuZZ8hHGJDfB2OZ9PnNXNw4s01hHf8W5OziHlbPNEo4L0pnXjr4WJUFcRElfK7YEJcvBMSxiZB04umXaJiGmpap0nZB5vKhzoK-j3hKtVsCj_rgz8LhfcMpW16JWZCqiR1Fq5v1BsWzr1DOLi1PKVo31_mT0RVdWxwGHFRAYunxhSd8hx20U_hBVjL8dWyMahmmESLLC54y46LJhrrRnMI49F1ZRWS22eTd1cSlrWo1dh898CPEvyzqodotV1spwPvGhVF5wXls3n32_lGU1YEnC3MfTsNtHYyy1bMVx5kUAWewVlr99om2mvoEKvclGmJpFzCmsghk1WsGV1x8kAfRPC1ooRXLgXRmwMF70RceQo1Wcpb6PKgU7j948ZcIefH6kqK-kZxm8x1Z2SbfhCxgzEH1ljJjsBeprNitCVodIxIOfY7T8OXKUglbQTSMR3GgdixxlaqCbhZyxsQUlUFXZB9TWTGPahy6xzneH5ICYVHO07G-6immpQSK6btgHxDJsy7A0bT1fSYO0RFnaICG1lDdIWzAvN0hb-lc2K5aIyxokpJ65-pVolmmuo5yvEoD8YD39-hJhiaW07gEXNAxDeQWzlmWdeceHclNKfLocjsIokRebzHdjKfgyGKWJEsi9pFhkpe9BOnwQGw_Zf6Fgy00oUg692P3-kPZ6YnOpBiZFcm-sdXbWat5d3rdylg6Xa7nihr7PRjHvfqj1mB8Dh9fNk2AHChg3QdFfeEk-nzHUX1nkRh4kGAyxmIEok2VuwFCKbRwUIYwK8zkesLvxiIs4iLGY5bUEhlrmFxRllhBwDsrEgxsG7rIxinIa8ijqls8bni9qRBxq1xDeWXmJo4daL_Ie0gQZbTJZoewQ7SbKwWLGQVmclfMo2XnDg6HNyytcrEE1jR6NU97jEMXI2SyzxB175EGeAyf57lhOoViJIRGe82F8Moa15kygtrD6zBFAeRalILsLhVnqi-ufU-Z7yVgk2cLVq2zjP_B8EDAIXzrpaJTJEZM2BtSvrrI7DT_JRQglE-Mz14SFcjO_Ibsb-V3aL3f0vcD10y6_DPJac-q4zx6E8prSF7v_zTANktwUHojisjvxIvZD0f-E3bEyaeoWtAlFwpZfjsG6nP3cDx-YT6fq5FqRr0rzFubHH1StzbGSqX5Bfili8CEO_TRr9hbFSUlPGUSXMjNIkHPCWxaBCxR85UNx95onrMsSdniZAJyHAtNDKQY-FbU8FYZtEZWJ3JkjboYhfBKLnmhsV9pcvJGf1XxMu5OVah2OaLTyYJq0y3fhtA8qB2odNNO4XCetDKUySCYylCRUZlJ27jjkcJHAmX8Wumn8Bp9XCMK6O2VXMv6dO9oMgySCvAaZiENhNdkOqezvenlYt2dSlKKYnXs_jaBbHvAkYm90fq04rO9TIUpRymrXZdbd1nF55ucysTlR2dtlGVgX5daT0nIHYb7CZvnzz1yRLjhUaEmlxQiNNURxN_WSjtcXZmxYXwhqfekkYTQ8iVjQ3R50warkvHOrSScdDkOoRW6hdk9YPNz9PLsM3IgzqJxEoyLSdwdK2Ef-lsS6USQWl6kgZSJJmYjafbZNo5jfBPLxhuopdlkI1tcL_pqEqTvYoWcyyMUEAjO2dyoP61IhWywWM-Y_P5_8kRnkE3_J2qxsN3JXSaRMJDqNSGYl5975DDmDf73e-A3TY1EC1rEJ3-5dgiWSR9kJzVv8KhODdk4yKxl3_H9jluyg6bvgEfO7N73bNJKZBd34rRmRRZlbp2DBroQ9pcQo6OxevbgF8ngn9LsejybaZFW4w9j8CnXloHK-nufGup5x_Xdl6DMf3Dtl8WBHuXlZHnqKC04lY91NeWchE1wjclnAO-nKFQqV38qkYH3PeJWM-Q9K4M2V3RJ-kBeSebNK85SncsE73fr4r5lOnaHYvX8jynMy5mEtLi2b998ySX9cN3SarttyqBBWqyVv3w1NRfwJERaHaeSK58bBqSPrCMpeRXysK3Jie3GiAKTPorkrbeYnN__IyDzxom4jHonjw9LR2jZjSVGiDEgGXGk8i4fqF4DOP8mThLuIc4Vlrkl-mu_fw5fiY_rCJA30hF1xAqBRzdTruqoSta7rjl4njqmTukkMatQ16jgUbjp1Ylo6fHcsatcNg-hmTUlAX-FFAqLnLwgI-UYOaqsLs6P7SaiSF4pXFA4fw6jDBQqmpgK_58r6JkoO6an4Wzp3CRfjwxFIBs_iw3vG_E-hfDxFnsGIqwfdbpx5lL2D0AS4BW7ykZnshrAKXHXUzLJffnlP3okN4iF79YbpMCNVsuMicTw5ITIlVend48OZM5m7h4v-Hn9pX2X6Bkkyio8OD19eXg5GUOOEPf7q-fzADYcT3_ZlIO0LXA8b8Oek8eW0cWHEQSts_3gcG_2bkxP2W_xCaPghUzeRfpy9ZjHBOPs2dZuYlNgAbpKlh_wEv4SOEENF0JnE1nQMnW7YGoKOUvHg6mY63TYtByNPIwRB5ugqBhXNNFHearqO85Y4NkYeNS1qIOgMnVALYx8xUfaZRFNReg3iYKJF08RzJgh_dQczaibVMFoJBT8wMWWCGxg6FVIkxltqmRpqNFSUWke1VZQbmoMCGQbDxAyuY9iYICC6g9KrE9vC6KW2bmH0UsciFDWJYDnD-GHrmomaHNRGpVLV0Chqcji2g9Kro8KUWJTgUiQyCVFLx_ir68RExTPMS0y8GASyJAoX0zRR88O2KS4JWaj55pg2bsmyTFS8UGKisp9qaQYqrkwNI89yTIy7juWglhjTQWk1HYLK4RopGwyoeWfVDnyB8hZR5xLQqdUNS9fqsIJQK69oYc02aZ1aFG6Klc-uw4DZk3oYkrk6VwoTYlO47lBDr9sQonWYboYNl3W4TKihmXVTNeCmnLB16qgmqRu6CXU1JBgb6mhYhnWooCFtAj0o1SAzGnVI3yboMCyVigJcM7Iiu0501bDgOgU7iE0sva7ptq3CXU0DSkqBhpq6TUC8UEVNaql1SlVwSgNCkKnpIE03TLBS1Ujd0WwTHDPhu65bDlhkqGARLIN1Q7WpKZhtQeuowmbHAieIINNUaANghHXJAhqzZkD2DKZOAa6slQAnKFyxwA4Hloe6WP-NrIcwLAJaYIkUnzVwmFrAA7QEfFGFdQA4kOjEsuqGDVVrHT6B-SAdQCKQFay6QNoCLwAbB-DO2hUd8gXoo8IWFXIbXNAtutyjGOt7lMMdFe2tp97Z0PnNVs9Gzzejp8_7jn3R99zOk3vZv2mkV9cnw8vGb_ev3ti9vv0Re-n3yP326_3o6Wl0TX-y9HPnZ-_y1tC-JfTu6vZX9uNh5D28nn8PBw3a_PxMht3Xp9P7YeB_S33ja3P4evHtpOE-Pj2xOHq2Tdr4x9VrOPraaT59a3XI-PTnVfvx7ItpQvPQ-gYxHRixp78w17tx-k7s_Oo0ereN-6f0NdQ_jp2Ivp60dTo6a5OPdzcv6snoxG7e-IPrlJ0OP7asyHq6bPx_A_Kf1oCga6L_8AZkRdqv3IBga1Rso4JcDJFL684bEOTKj2xAsAXHv6sBwfZb2AIL24BgGwZsA4JtLLANIbaQxTYg2AJ61w0ItsDHNkjYhgbbgGAbGmyDhG0cd92AYBt09C4XbjcHu02D3PXZcQOyYiusvAE5PhQb8OLDpzDJtn_FxckXuT1_7_EXJeYscgedJBLHHD_DcPhNwGocOI5NoaeARYhkz-RfcJZcs9H0HELQ5k_02_nz_AlLTr1ej0fyXYTJYYIg_BVi2NYOICtDlQ5_nOxNwWN5JpQfE4jPHZ4dO6Qx73A3DLpfORuFgbxceAlAkMpXGfLjkjYTDyYcKe1Gu7U3OYvZu_MSFnjpUOmMPLivZA8C7TUj1oMS-0gR5u3dRrznvR4p_4xY0OdH6oFq_T49UhJvohB1SiN-d2j-SyftLXBT-_dGF2p4qPFZ8ZVobUo7xyi_5O86HClU3csH80g52Yd_9iTCbf50pJj23uVw5HuuJ-6qe--JSopHBsLWvffWOyXTJ25J9TIqBB7zyNF1yHWScd9jgXLvxXwjXrozD5iDwGvDlykgBTwaBSwMUsSC7F2wWCFK42Ecx-JhSMmy995Rl_Apx0Jbh8X5gMWJP1ZaY6585C_c3wgIRJA0JXucAaJBPMlQfItfijFLOImecUoCySis1svCjBR1yMeT4wsv6PJIPmeZxYAUQ1dCW4gtcyG2NHMJukxTrHQ5QEwMcZ9ShU1jXZm-6JA5OWUYsGeumO8UdxqXmaFKK-BDj8dKGMCVRHnxkoGSeVLPvmjqOyUSv3jAu8rkVwwU-Y7hioHU1wZ1GLmQmiLlJAyTeOMoEns-rO0SGpjsE7vuOUw20Gq8LeCXMsB8DrAWxsleDnEBmjc9E0fBZqyDrRkGz-GjeLr_Kws2Zk_j9-w4Wo6jOOuXxpMywiw-Ju-FkQEpzcUZVRZSN0G2HNglEwKGKyOd-7mLN2ddi85nmiZkRfGeh5IpA3y7Xs_jUQz5WL7hIzjFYS8DmuytgezhA4FFGU0up0A0N2-ouWY056akZRQp8zlYPt7m_Hh_-XT5-Utrr8Oe2Avz_wcQjv83Vj7xONmDFSTsKm3mCa0AC-unHECCWx6LxuUQnu9P_ymGrjEfuoVAeP8Xauxbxl8FNgKS2eui81Sauq-rf3039yJV8RS8QPwXc58I0kn2aMufApJPhwjgs8cU9og6N1dKnnBQTiBilOxd172y-1CThEofFCdxdmUC37WwUIEZM3_5zJfXwYUACq-HsdLwfW_RUULVfWKoEpD89VIYA_HwlBSYvc06KWdECQhR2Bb8ipQCteGBUcvro7xIXElBN1JoGykmPw5QEmrWutSy8KzMG1Ly2yuNDYlX3Zx4z7MoyGY3VUvDSQbePFQdP5z8bECW3ZRCzzD57aQC0eTRoQmJtUxywsXzPRMCWk6wUC4VtWrLHLlphWaQlIgtvjQ7oTPL6GABnlFMflYobwDWFP_Fmr8MuM4LGy36VdYylbAuslEc29JQLTta0aAyXzYYVTasG1jOfBY_KhrKJFpmklYNXhwIdEdsejUjzWrazOpokg0DXBZPG0Yge29wW0UlkWRW0bMh_FYkM4RgrfosIlUc0avFAqkWefrm4VlK8CXAbiu2LLwqOo7KO0YFeyrkQG2TmumyteXwlaNcKb6MKkyoKYkZiEp-GpVhpRXG3aw2k7Rq4attH2V69bRfIaaXyzUs-BomIHQMUQWz31D8IEdyqUJFj4JZISpJ5TnwhnDBpmTBi5w1eNIKyLVF50qrpBhaGd6K6QI_nksdDsIdDYETqT4MemW0jCqDg5kvS10eOsg3mNQYpn7J2pY11tAyyjMwebwkf9AvDHpeHyiODxf_txT_Avd-T-I=
```

**Comment by BassOfBass** [comment]
@McFrugal That was my mistake, since I assumed the damage rundown will be somewhere in the selection menu. But it does look like Dominating Blow follows the same display.
