### ISSUE TITLE
Demon Crown Helmet base type doe not apply its exposure

### ISSUE THREAD

**Issue by TnSylar** [PathOfBuildingCommunity/PathOfBuilding#3022]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

After equipping a "Demon Crown" Helmet, a new option should appear in the config tab allowing you to activate Demon Crown,'s fire, cold and lightning Exposure.
Example: an option that says "Does the enemy have fire, cold and lightning Exposure?"

This is the same for the other 2 similar Helmet base types : Imp Crown, and Archdemon Crown.

### What is the actual behaviour/value?

With "Demon Crown" Helmet equipped, there is still no way to apply exposure to the enemy.

This is the same for the other 2 similar Helmet base types : Imp Crown, and Archdemon Crown.

### How to reproduce the issue

1. Select any elemental gem as main skill and socket it in the helmet slot.
2. Equip either imp crown , demon crown or Archdemon crown Helmet.
3. Notice that the helmet does not increase your damage , and does not add an option to give enemies exposure.

### Build code

https://pastebin.com/K0L3Rjx1

**Comment by pundm** [comment]
If text is shown in red, it means that its not been implemented yet/ it is not parsed correctly. So this would rather be a feature request.
