### ISSUE TITLE
VirusTotal for v2.5.0

### ISSUE THREAD

**Issue by noraj** [PathOfBuildingCommunity/PathOfBuilding#3023]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Spotted by IDS

### What is the actual behaviour/value?

[v2.5.0 .exe setup](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.5.0/PathOfBuildingCommunity-Setup-2.5.0.exe) on VirusTotal matches several IDS rules that spot it as a trojan: https://www.virustotal.com/gui/file/4c005a4584ab6f41a5e721cc4bb2d6cf50734121e9f0237d56baa0cbf437a31f/detection

That is also happening with v2.4.0 https://www.virustotal.com/gui/file/5c0524791c52ad2f790241b5991349f9b2a10d6c49a378650825047431e15222/detection but not with v2.1.0. Are you using some sort of packer?

### How to reproduce the issue

See VT links

### Build code

N/A

**Comment by ppoelzl** [comment]
None of these antivirus engines flagged either of the executables. I'm not sure what's your issue.

**Comment by noraj** [comment]
I don't know if you can see the same thing as me with an unauthenticated account.

![image](https://user-images.githubusercontent.com/16578570/127044325-3b1a9ce2-a3cb-4024-b326-663f756fca10.png)

**Comment by zao** [comment]
Some aspects of Path of Building's runtime that these heuristics may take notice of are:
* an embedded JIT:ing Lua interpreter for scripting;
* the ability to download and replace parts of itself via an integrated upgrade mechanism;
* a high precision timer for the render loop;
* catching and handling of SEH exceptions for crash reporting;
* network access in general for build downloading and pastebin generation;
* filesystem access for settings and builds;
* possibly slightly unconventional build flags and choice of CRT, matching some environment that malware vendors uses.

The purpose of IDS software is to notice things that may be sketchy and leave the evaluation to humans. They often misidentify things, even more than antivirus do.
