### ISSUE TITLE
Boneshatter shouldnt scale with area damage. 

### ISSUE THREAD

**Issue by tyler200100** [PathOfBuildingCommunity/PathOfBuilding#3027]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I have tested in game if area damage increases the damage of Boneshatter

Here is the tooltip of my unlinked boneshatter. 
![unlink boneshit](https://user-images.githubusercontent.com/18606028/127060474-1222c684-cb2c-450f-a910-dca6ad973abb.PNG)

Here is the tooltip of my boneshatter with only level 1 pulverise support linked to it. 

![image](https://user-images.githubusercontent.com/18606028/127060687-1de4c73e-15f2-4691-9ac7-9efb59fff32d.png)

As you can see the damage values of the skill doesn't change. Only difference is mana cost increased and attack speed decreased. 

Currently in POB boneshatters damage is increased by both generic area damage such as the node "Amplify" as well as melee area damage from pulverise, blood and sand, etc. 

Thanks for all you guys do :)

### What is the actual behaviour/value?

See above

### How to reproduce the issue

^^^

### Build code

```eNrFXetT4sgW_zz8FSmq9tZODWq68_Y69xYqKjM-GHF0xy9WQxrIGBLMA2W2_N_v6U4CAQI00dm7W4sQzvN3Tp8-3emwB_99GbrSmAah43ufq2hXrkrU6_q24_U_V7_fnOyY1f_-p3LQItHgqncYOy775j-VDwf8veTSMXU_Vy1gi0jQp9FtJkp5gGsj4kUD6nsX5KcfnPr25-ql79Gq1CGe7UTZp65LwvCSDOnn6gUJSGzToCqRsEs9-2j21dHAob2IOF5VGsJr2-8-0ug08OMR2F2Vxg59vvBtIGxetK6ub3LKHS-vHIz_cNByyYQG7YhEUggvn6t1wID06TEZwitII24MorCly7K5q8iqhQxLqe4VM7dHlNpTJmUXY0P9p2lbAW30erQbOWN6FDjR0YB43Zkn8iq-bWkvYjdyRq7DYrSJ_mxJNJJXEt_4EXGPW-0praVpimLsYlnBFkbK7-Hzo81u3DnR4NCFUJTQ0ux7TkTzjKoiy_KujFW8iWk-F5GBOaOlW3idpcsaLcvkpmJDw2tMZcwt3wl97w1obunpkT_sON4CsmLmZqz1cX9bYy-IR478UCD0506PilE22mJ01xBTMUpmZYsGUAYjcWO3YmhHs0Gs6qtNpk95SmSaqyiP6UtuqBtrBOYprZWam97MC6SskzdHidBqA8d-BPOTGJhTKl0x0Zoi3d1n1E2vm8NIWyf4uxfQkAbjXHVfp2KeJQ2xSE1ljNe0T2f-apq2i1RjHcM5pd3BKUyx1yTKlR8LqbtrR9TMFVVZCxYjzoO1dgQUQIVUQY5FpDDaNQxsKZai6ibC64TMo4bQeteLIVtdKzwa9CdtaGhcW2CUMszyLHOJJqRk3hshlm1dGpMwP64wXu9OQp73BK9sbS4oTL7AYVPRRmV7jlbg_2TNk7sdWz0Y-nGQy_wNfif0ebdXF7_WYBI6XZhVeR9wTe24O1e6lJVleNoIXvhjOoQRwBtJ6I5nabM6nw9d6KxF_QfBrrsVRz2KSPfx2Lf7dCslW3GcOAEAFjq5SdBAm4mvYBFwREYCjbDPxtSc_J3VRXVGLazg3OkPIg-WWuJaFljEfRkQP1xUo4uQC6s4id25Dh1p2DSRtasbpqLr1sq4PzrzfBHpuHRfkl9Qx9JtZXUf0vKfwbQBW5GGAmM_R31BZn3JyiFyElDv10RY_hy5kIKGZ8cBS3VhHYscQmrqvEhA606H587QybUUnONgjy_y2bvmcOQHEb94RNxuyOU1vVEcSR5fnQ-dsPvQiXs9tgavgvyA7yA0Tk4aRzfN20ZqQp4lZOF98OJhh60lk7-Z6g8HbcqrndT1XZeMQgrL9x5xQ5Dt2GlqtKHKdyMheliJpsspEeo7EnQDB2AXIWZLSCGT-WJehJIts4UIISrEpeKA3UxGlIU_FMUsrbci1HyBLESZrDHFHORrWbEw0C6ZCFFOOxsh6oZL647LJlEx1C5gICTzrxg9zIeB04kjwWzjyxIhO1hHLuRgvhkVsjjpeYRkp12hCG06BYnlGjQcwtE4pj0KWSw4mnmVuCGP1EtrYFbvDvgQCqUQCuEpHYaHE5iaThhqC9sYcwQwaQUxyLZpj8Quu_4tJq4TTT5XPcfNXz9PtlL51XDgP7fj0SiRxIZt-Ll6eXV9UT9Pvqy7USqHaco8SPxjZvIt0qS888_cCb5P6nhdN7ZhsZpOypmBLukw9VWpz7ZUj_zYi1JjqMemXTsjXJDMhDK9Hw7AkpT21PU7xMVTYNNdYixX5whQJpLPBE0WWN-j4YBEEZsRnhIHm3xwc5RSyhYJIu5Lnw7Ztxc0IjaJyF4TJrJwjyGyx22Dd0US2TS66NVU8AypboIBvGPzFWvfFwzkPBeOx_e72_FwCF_aLSiZEQmHSba9CyppJrA-tUU9GgUkWQcUAbQOkmlCrZJUBEwRCoxfygt4d1_vKBn5HtReVnizJdAbPF4vT9TvKb-UCJCenWggJSua8P1BOHTBhMTyN7jeHkCxfCbj7d3Ncf7Dqc4Xu7Bi5btKpT0vkiLqe9MLR04-uw-SkvIOJfaZjiTVdbzHzbU2dH22Mc9TQEK_t_beEuLW2TwJg9plHTC737Y1-uuliKLPpEhTMdJMzj-Vh3xNxHeRts-_dObh3FzO1u7PPG8FIKAb-f_8bMPv882bv_0ILBAiikF6n5FKnP03VNdkbXPjp2uM8k6uECTqKOsd4_CdCk2GxazSYLFK8zsry7fY6T6exiSw36mpa0eUusC1fecy43xvrEWL-RmFxWT0FsDRJrxbcdAvX7fmuUWBvYM2QfJ70pHvjZ10n_p9Kpa1yd0TlwyHpOMwc98pwQpFCnfHeebVXvIUSX3URWsWCaMrL79GfUPZWilLuHKBBOl5QL2sHZ4tmze7LFyn2Y5HxHaZS3u6KEHUv4zv_1UqDn0_CktVitzIW7BNHP1Hh61yO9yERXlcVMn6khSCOfHbFnEuQVplYd52dutlc6V5B7jOKLRr9lUPqievGcKICdemRQ1bgpawsxJdYCK0nC9O2AB5tA2IOTTItPG7Su_YfGVy6-GgdAYVydgeBsYt6pciWKvqtu2wuY-4f7XeULAKxQhvUnguixn9_7U4ANKYFhUu_H495Tmsidsw0b7ThL8kTniOAEYp4XyfdgeJ5toJzL40SDaf3orCbGewSKhw48OZf99-2NpOoISz79IXvOsOL_zn9CZv2dldkCAcupRvoWSk7_jtj5uAUokkw5nzoPR-A3zIn9ZmRkIOe77NblooCGlKTUOWUWNnqM0asmSrhhUZGzWsWYpSU03VlGu6qplwRbYwEGu4pmPTqlmWgWqqrgGbaiBDqyEkm2bNUAy1hhQDwasmG0oNG4qMQISJ9JqpyTKIwHpNMQ3DYOIV0GooqIZMGXSrloLMGrYMMMlElgkcYAUG69SaoqrAjYBErqmqpRtwxdKsmqbCBYQ1BaTKusXINbWmI7CKX2CvqmLVFF1WwQvQCCSWrMN1ZMGrxk73Me90HQxHulrTNAvEICzDi8YsVE1sMnU6kCjMIsWUMXypqgjwkjUN1SzAroZ1DS4rMnwN700mUNVlvabKACFIMWUDzFWRVjNVAAGsUAAmEwAHJBFDHevwqioqApQRA0CVLWACauapppogBr42aroBJIrKQNMgjgCaisAXy8IAqCwzRGWMEQsCeKQaYAQgAnosJluBWEEkDKwzK5AFXqiGDBjrlmrVdA2-Bk5Th1fdABiwqUKENUW2NKAHCCCgql7TTAgEiMQMcAWbYLTGXAKdkCsKhJ-BJGt6TZfBLiAHTlXF4K9umqDOsJhqAzwFHhVDfoG7TJasgkcaAgOwDlECSEzMEk8Gl0zTACbM7FIVSLeqFEH65x5uQFr63AJL96whb8C0Te1Llvlpbfh-fc7ffBhE0Sjc39t7fn7eHZFo4Pfoi-PS3a4_3BuBGBhVO7wc7DBFe3X457DeOK6fDV9OGkr9tG-ju96le9NB_YdG2Dw__NY__dIYmsZfk6-o3v318659FZ88jXryc_Pm2_fDka2Nb36cPsv3989f7-X7dv20eXs7-O7f96_cr-OR6rRObn4875z13KP7zvOZ0vtpx_TiFzIfuj9uTWw_W9_pj1-dyyft8PzCvAkmvQH2L3_dt8-uTi6_XU9aw3stwsHpz8nVN52-dHQPNc2-7p08XcMoOEeDn0_3N-Pj0cP56Kn1Y0xk4_Sn08Bda-fobvx0etQdf9mRdVw_6_r948PDM9dXjC-TY-3w9sH9Zj00Gg-dX-PWvfJ1dNo2Hr93D4fWr_Odo_BHg9ZlrB_SC-3kLnwaBI_uqTUyzBv8Ev3E7dMv3-7ddnA-_nLSfLJ-BLob80DsZZE4SB4cCZOwpJ94teKR1DEyoROKkmKbHrcpoIOyJgvQ6TDyVBE6KH-KAB3GliUiTzV1wxKRB-NagMxSZRFUFF0X8hbKrJi3UJ1E5GHdwJoAnQZ1yRCxD4qCIhRdRRbSC_OfSLZApdGEcIHJSsQ8mGZFchnKn4hWmIiRSE6pMkwZIt5iQ1eEoiELqbVgvhFyQ7GEQIZg6CLBtTRTJAmgqxDSqyLTENHL58sZHVpNCF0UFhpFMAuKCETQUulCwwObQsVU1hQsNDws0xLSqwolKjIwEiuSgmUIG6qIv9Cd6UIZDSNTJGM01sUJ4QLNpdAIMU0sVoYMoRFn6abYpGXoQvmCkS5U_6A51ITySldE5BmWLuIuW1kITZaWkFZYXQhVcQUVBQNWcLN-Bz7AYo2v69hqjr259CPKv2MXsw98rXfr0GcppOzWezsKPleH7H62RAJKqtIv3x_--Fzd0RRrV9FgXQWdNvTNydm0M0qiCzKaroIZcXq4TUuPtkUkOnZ6PRrwg3nZwpQR_sXSSts1ZRjD0H2bKDnjfcBXu-nyk71v02QJG4e0Tbu-ZyeHJPjl3GE4RsrP9aVbT9eE7X3uS9f160blxKfSXUC7j5Uj3_XDMA6lC-K6NKpwNm7zvmSgSnrUbl9SzEoKJ4jY4f9WONk1fdqXNKvSHI5cp-uw71FFkf9ge2qAWEhtqQ5_0xsllezRjvQzEBvWjmKY0p8k7rMjRtT-WGHHgDkRwO88Uim5zwxqdjX5j0q6yyKNaCAlCICUXV2ZE5GeHLkmHleiVEAU_DXNyickRX7iItsMTbwCK9l-QgXJKG_5grWVum2HEpKZAKwsfYu1Oa-5mRI__Fz5BA0O46p3u3FAuhMwLHK8Phhj_sGupzhX_u4GpAfWvBp_SF3uNfvWpkyJH3dcmuliKc1iNR9rVBDr5NAqYEjDqFJPD1e4JKIAM9e1L7EkrLQC2nNe9iX2qHjxh2bmG9sGsirtuDejWf1hmkJYXkqhhTTS8Xwa_R3w8Mm72uunP80dhD9ysCBTpdmBtOT0LIMqrHyyNEYwJC_OMIY8Bjt5KbjwbZ4JEhcINWJXq6aApfs-y1gqq7Hkt6cqNw5olU4BkjGoFgBzDj99ejl7VOmWuj54PtHeA9k8qmYeVbnySV8GaX7AZhalyVuMj7oan2QbPAOIxF4EpWUVRGmQ0esxdcc0YU12C2G0sW3k_LNgSAjZDKVp_pjIeJ3SJAOTu4bfAV1rHl1eIkwGMEJLFQLJqyuEXpS6RcBrq4FPjlhUGhENPNB6GAd9cCV620g3BPIxN1J5GBNDGh4dTmYPmbExWofyh8pi-8lYxugS5unORGKqHBpKA3YaY8fidYIf1p2pXgGnXgDnIXUjsINEA5hj-Ie1uQsJhtXXwpO26jKtbuivCwDPBUFw9M9gUs3CsomgaGJtR5U_LoH2ydCXS8Dc7LXuwK-UbI0XVla0sa4aRek7jFnzcRMHT7HvhFRKL9yRwPUDW2LMm8pHNtZ41aiHjReY6VgGNL2eG7NuCz-wf4oTfhYc03hdUU02xOOIAFqTMGIfXxw_DqdX8tmeS245HzU8m_rrLswDMD-HUot4_gg6Id_LxxTpO1jlMT2mLzDSQbREPAAJOh_XdfrMVygnyxFmT_5IrOFgt8LnK5NEQokjlgyatFz9HZF-uB97Y-q41H4Y-naNZA_tvE7tnZulMdrB2ibj1iQOzrr3lVO2tjq1zILUumZt1pHPup7k7fosWjcwy4zS9TmgaKtHrryjFI5ca-laEqZRGtEHmwevRrMRnF1I_2R0M4JaD2IO8YzDyB--Jlkib5slAQ1hBurS2ly6DIlHljPlFaDZYU29x3LC66cFJS3efxo7Onec_7KKxA6xS-xXPQTqTUHaVNNmpTBpxpAphN0SVBMyaz6Bvl82v31vVM4d3_sX1Pbw36F07ZOgcgrCYbkpnbgkfKzcJkL2JcgPCe_iXXn-krIrL19CWv7aURzAgjCqJM91QvmdfqMuKCvOI2wUNCFfPZhZO6xeA5b8THZ2g1qyY_aQaiJSovyZvXyzbWj51UeXwFJzOsGyeZWJgsUVXK78nUIIOZsT8Kch7yBZ_pifUdLHcxmXnWdjrefQB1ASExdTLjU1MzLjw3PqFBgs2scycpQ5OTDocDk56rz74P02YnioQumQBSsDGkYhdM987QxYJ6FiiK8tjsrG8qlupNA3UhgbKczVRRrJBVX6C32mLpRp6PojKf2wYbpPfuFkrl4njEukrFglsCcEC00rYjPu7GHUeZqFVkteaEjNbD06468gPZ_2-Upp5L9Y3em3XT97Unz2AEy2vZX9ykaOKDt1lJGoyySsh50R6MsE2eHsjETLkySbT9lmVcKQJGRus9RaFsom3DyJWWCYb0-k7LdEphvwK0ShDaL4eciMQlmmSLrKGUn2ixLpttqaLbX87kpRfNrPZCTVO5MwZLtWyf5kwQZsEesiGxZjW8qIZSxKGlTkywajWHptyZLkjyJkEi4ySSkHrxgI-J3Y1HJG6uW06eXRRBsCXJRPGyKQlJRtFRVkkl5Gz4b0W1EzBQQr5UcRKuOIWi4XULnMUzeHZ2keKQB2W7FF6VXScaG6o5Wwp0QNVDapmU5-W4avGOVS-aWVYRIakkvdREEgSvmplYYVl4i7Xm4kKeXSV9k-y9TyZb9ETqPS4CsiI3OlM9s0oRudeEMrJBjX8jHRS-Ro-aC8IXlECzTjFRxD4qQlkFuxHBEoOLg0vCWLh3g8l1ZNAu4oAjih9TitC4NaGi2tzGwgMl6WloXCSb7BpFVLyr10TcmPnPAjHPwX5Hyv5_SXfg-OLTn5Y0_8B7oA_arU8X2XEi8td8s_IUfZrbVmeOiH4ew359oDMqJBAfVUAb8jdwQoBtRuevwxsk2a2M-gXPVmTzc3XkZ-GAeU_TbTTDXb5linmD8gO9uIOQn8IbflzImuKdvIcSebTZl3I_nVAXszW2f200U3AYmHpJ08pjP95T21iCnu9abPlGzUAMSXffBsELNnoGlYt8fJ73Uucx7sZVlwsLf4Pxf4H-GIOZY=```

**Comment by pundm** [comment]
This could be that the area damage only effects the pulse.

**Comment by giniyo** [comment]
Was going to submit this, blood and sand (and probably all other sources of area damage) currently affect Boneshatter's main strike in PoB which it shouldnt (and it doesn't in game).

**Comment by Lothrik** [comment]
Fixed by #3177 (version 2.9.0).
