### ISSUE TITLE
Some imported cluster jewels got broken by recent release

### ISSUE THREAD

**Issue by Razunter** [PathOfBuildingCommunity/PathOfBuilding#3034]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Medium cluster jewels in the build I'm using stopped working after update to a recent version of PoB (2.5.0, I think):

### What is the actual behaviour/value?

"Adds # passive skills" isn't adding passives in the imported build, but works after any minor cluster jewel edit.

### Build code

```shell
https://pastebin.com/XFfBhVXB
```

### Screenshots

![example](https://user-images.githubusercontent.com/362900/127114813-8a4308bf-db86-4709-92d6-f0c389ad6338.png)

**Comment by pundm** [comment]
Pretty sure they changed GGG changed the implicit from "+4% Phys DOT Multi" to "% increased Physical Damage over Time"

**Comment by Razunter** [comment]
Hm... Right, but it should either work or notify of error somehow.

**Comment by pundm** [comment]
Debatable, it's a snapshot from an old build with items that do not exist anymore, not even as legacy versions as every jewel in existence was changed retroactively. We can't change your local build code.
