### ISSUE TITLE
Ambush doesn't work

### ISSUE THREAD

**Issue by SaraTri** [PathOfBuildingCommunity/PathOfBuilding#3035]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Ambush gives no critical hit chance or multiplier and has no exerting section in Calcs probably because its not a warcry.

### What is the actual behaviour/value?

Should exert the next melee attack you perform.

### How to reproduce the issue

1. Equip one handed weapons and choose a skill.
2. Add ambush

### Build code

```shell
https://pastebin.com/Ajz40b4n
```

### Screenshots

![image](https://user-images.githubusercontent.com/35155898/127132792-864bf8dd-8926-4825-a7e6-c2827c0bd292.png)
![image](https://user-images.githubusercontent.com/35155898/127132829-701f5cc3-cb08-44b0-9c05-50cef2a3f2f0.png)

**Comment by SaraTri** [comment]
Same issue with Battlemage's Cry.

**Comment by andrewkhunn** [comment]
Would be great if support for these 2 skills could be added. Currently trying to theorycraft a Static Strike build and it's a lot more painful without the ability to account for their effects.

Thanks!
