### ISSUE TITLE
Life cost for Forbidden Rite/Dark Pact

### ISSUE THREAD

**Issue by SaraTri** [PathOfBuildingCommunity/PathOfBuilding#3036]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Currently Forbidden Rite and Dark Pact don't have their life/es cost shown anywhere (40% life 25% es for Forbidden Rite and 6% life for Dark Pact)

### Describe the solution you'd like

Adding a Total Degen similar to Righteous Fire scaling with cast rate of Forbidden Rite or Dark Pact.
Forbidden Rite should also check Chaos Resistance like Righteous Fire does with Fire Resistance.
And also hide total degen when cast by totems or when dark pact is used on a skeleton.

### Describe alternatives you've considered

Adding "Life Cost" under mana cost would also work (and maybe "Energy Shield Cost" for Forbidden Rite).

### Additional context

![image](https://user-images.githubusercontent.com/35155898/127134397-c9a19269-9409-4822-9acd-91746a69a39e.png)

**Comment by Lothrik** [comment]
Forbidden Rite and Dark Pact don't have life costs by default, they deal chaos self-hit damage (and sacrifice life) respectively.

I agree knowing how much damage they deal to you at a glance could be nice but I'm not sure how *useful* it would be without also showing your total life recovery rate (leech, regen, gain on hit, recoup, flasks, etc) and showing the net difference between it all, which involves a **lot** of math and seems excessively ambitious for a single line of text in a skill breakdown.
