### ISSUE TITLE
Feature request: "Apply enchantment" button for armor/weapon/belt items

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#3040]
Would it be possible to implement a copy of the "Apply enchantment" already existing for helmets and translate it to:

weapon/armor - harvest enchantments,
belt - Dedication to the Goddess enchantments?

**Comment by ppoelzl** [comment]
Hi! For feature requests, we provide an issue form for you to fill out. Thank you.
