### ISSUE TITLE
Remove fossil ES suffix from ES item affix rundown

### ISSUE THREAD

**Issue by BassOfBass** [PathOfBuildingCommunity/PathOfBuilding#305]
It was replaced by Quality bonus, but PoB has both as for 1.4.157.7
And I guess it shall be expanded on evasion and armour suffixes too.

**Comment by LocalIdentity** [comment]
The increased es suffix can still be obtained on es bases. It can no longer be rolled with a dense fossil, but still works with tangled fossils
