### ISSUE TITLE
Minion DPS toggles for temporary auras like Unholy Might

### ISSUE THREAD

**Issue by tyger249** [PathOfBuildingCommunity/PathOfBuilding#3050]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

There are notables like Grave Intention and Ravenous Horde which have a chance to grant Unholy Might for 4 seconds and Onslaught for 4 seconds respectively. Currently there doesn't seem to be a way to toggle these boons in the damage calculation other than generating a custom gem, which is bothersome and of course, a hack.

### Describe the solution you'd like

There should be toggles in the configuration tab for these types of buffs.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3146.
Passing is not support but there are toggles for these stats which should be good enough.
![image](https://user-images.githubusercontent.com/31533893/177663328-9ceec1b3-c033-40c6-abd3-f3946190383e.png)
