### ISSUE TITLE
poets pen no triggering skill found 

### ISSUE THREAD

**Issue by mindyk** [PathOfBuildingCommunity/PathOfBuilding#3052]
I am using arc socketed in poets pen and i am not able to get POB to calculate it as triggered spell. 
I have also frenzy as attack (solo and within the same group) and kinetic blast but nothing works. Did not found any option to enable "use as trigger skill" or something similar 

screenshot 
https://snipboard.io/LreFkU.jpg

pob:
https://pastebin.com/hGE0mj7B

**Comment by QuickStick123** [comment]
Fixed by  #3724.
![image](https://user-images.githubusercontent.com/31533893/177663176-4de6a632-e06e-4606-a96a-75f161a3ef57.png)
