### ISSUE TITLE
Minion Instability incorrect 

### ISSUE THREAD

**Issue by FuzzyThailand** [PathOfBuildingCommunity/PathOfBuilding#3054]
The pop-up says "No changes from unallocating this node" which is most definitely incorrect. It doesn't appear to consider the damage at all, and the damage also isn't included in the DPS when running an SRS build as Zizaran's here:
https://www.youtube.com/watch?v=pT7K5QSwGLY

Here's my example build, where Minion Instability is doing nothing at all in the tree:
https://pastebin.com/CaqeUe26
and the damage / DPS numbers also don't appear to include it (changing minion health on tree or items doesn't change the damage numbers).

**Comment by Regisle** [comment]
its set to default attack, minion instability needs to be selected here 
![image](https://user-images.githubusercontent.com/49933620/127452281-eafb0160-8478-43c9-ab7a-61c93de784ff.png)

**Comment by FuzzyThailand** [comment]
Thank you Regisle! That works, I did not see that in there :)
