### ISSUE TITLE
Item unavailable in PoB.

### ISSUE THREAD

**Issue by UmeChrono** [PathOfBuildingCommunity/PathOfBuilding#3058]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Item that exists in the game (Usurper's Penance, Eternal Burgonet), doesnt exist in PoB.

### Describe the solution you'd like

Adding that item so as a bleed build fan I can make bleed flicker zdps - quin69 edition.

### Describe alternatives you've considered

Have a good day.

**Comment by Rosemary102** [comment]
["Fixed a bug where the Usurper’s Penance unique helmet could not drop."](https://www.pathofexile.com/forum/view-thread/3153786) - From patch 3.15.0E on July 29. That's why it wasn't added in the last update, it didn't exist in game at that point.

**Comment by UmeChrono** [comment]
> 
> 
> ["Fixed a bug where the Usurper’s Penance unique helmet could not drop."](https://www.pathofexile.com/forum/view-thread/3153786) - From patch 3.15.0E on July 29. That's why it wasn't added in the last update, it didn't exist in game at that point.

Oh, I see. Thanks for letting know. <3

**Comment by pundm** [comment]
Will be added with #3055

**Comment by Wires77** [comment]
Fixed in 2.7.0
