### ISSUE TITLE
Minor typos in unique items, Divergent Boneshatter incorrect quality, Flat damage reduction not included in EHP calculations

### ISSUE THREAD

**Issue by Rosemary102** [PathOfBuildingCommunity/PathOfBuilding#3063]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

-Story of the Vaal and Fate of the Vaal have the line "Hits with this weapon always inflict elemental ailments." 

-Sidhebreath has been tagged in PoB as incorrectly having 0 implicits, instead of having 1 implicit.

-Divergent Boneshatter has an incorrect quality description and effect.

-Flat damage reductions are not used in the "Effective Health Pool" calculations.

### What is the actual behaviour/value?

-Story of the Vaal and Fate of the Vaal have the line "Hits with this Weapon always Ignite, Freeze, and Shock," as seen through the trade site and PoEDB. This is an incredibly minor issue, that really only impacts stupidly minor edge cases for people planning on using alternate elemental ailments and getting confused, and was probably implemented without GGG notice at some point in the past when alternate elemental ailments started making a return.

-Sidhebreath's mana regeneration that the item base grants as an implicit is still in PoB, its just presently slightly incorrectly due to the mislabelling of the number of implicits on the item.

-Divergent Boneshatter grants "1% increased attack speed per Trauma" stack, but also increases the self-damage taken by 1 flat damage per 1% quality (so 20 additional flat damage at 20%). The description on in PoB, on PoEDB, and in-game when you hover over the gem and press "alt" will only point out the attack speed as the quality bonus, but the displayed value of trauma self-damage will also change as quality grows without being pointed out by the in-game interface. I experienced this personally when my level 1 Trauma started doing 26 damage to me per stack instead of 6 after I changed gems, and you can search on Path of Exile's trade website and compare between Trauma self-damage stats on Divergent Boneshatter and on regular Boneshatter to see the difference too.

-Flat damage reductions, such as on the unique item from Breach League "The Formless Flame" are not considered when PoB makes EHP calculations. I opened up an old PoB I fiddled with for math/theorycraft reasons last league and to double check some stuff and noticed the error. The build had 90% fire resistance, 75% of fire damage redirected to chaos, and Chaos inoculation. As The Formless Flame grants a flat -20 damage taken from hits, and [flat damage reduction comes after mitigation](https://www.pathofexile.com/forum/view-thread/924683#p7847614) (quote from Mark_GGG), what should happen is that a hit 800 damage (or less) should be converted to 200 fire and 600 chaos, then fire resistance lowers that to 20 fire damage, then the flat damage reduction makes that 0 damage taken. PoB's EHP calculation lists my "Effective Health Pool" as 1167, including for Cold and Lightning damage, which do not have the same mitigation levels/tools in place.

Additionally, the current description on the Formless Flame does not match that shown on the PoE trade website (PoB has "-20 Fire Damage taken when Hit," PoE Trade and PoEDB have "-20 Fire Damage taken from Hits"), with the modern description matching what is used on other sources of flat damage reduction, such as the Blight Oil-exclusive notable Persistence. Additionally, attempting to switch between having Persistence anointed or not does not show any difference in my EHP calculation for physical damage, despite having 1 life and all damage bypassing my ES This may be because all sources of flat damage reduction have issues, or maybe there's another factor I am unaware of. (Also, I tried testing if Formless Flame became functional my creating a copy with the modern version of its text, and that didn't change anything).

### How to reproduce the issue

The first three issues can be seen through comparing PoB text to the Path Of Exile trade website's text. The last issue has a PoB setup included below to see the issues in action.

### Build code

```shell
https://pastebin.com/XGrT7UWN
```

**Comment by Wires77** [comment]
Fixed by #4734
