### ISSUE TITLE
Royale Support?

### ISSUE THREAD

**Issue by drunksaint** [PathOfBuildingCommunity/PathOfBuilding#3065]
I'm surprised this no one has asked for this yet! Having PoB for the royale mode would be so good to have with all the custom skills, skill tree and limited items!

**Comment by ppoelzl** [comment]
Path of Building is an endgame build planning and optimising tool, first and foremost. In Royale mode, you cannot plan ahead to a degree that would make Path of Building worthwhile to use. There is no way to ensure that in a round of Royale you'll be able to follow any build you've planned beforehand. Thus, Path of Building will not add support for Royale mode, in any way, shape, or form.
