### ISSUE TITLE
Source of Resolute Technique not correct

### ISSUE THREAD

**Issue by darylmoehrke** [PathOfBuildingCommunity/PathOfBuilding#3066]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

My sword is giving me Resolute Technique, when i look at my accuracy I expect the source of the Resolute Technique to be my sword

### What is the actual behaviour/value?

The source of Resolute Technique says its the tree

This confused me when I was trying to figure out why I couldn't crit

### How to reproduce the issue

Craft a new sword,
Add corrupted implicit -> Resolute Technique
Look at calcs page -> MH Chance to Hit

### Build code

```shell
https://pastebin.com/xnF8W3k6
```

**Comment by Peechey** [comment]
No longer an issue

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/c70dd310-f8c0-461c-b700-d6feb5855f1a)
