### ISSUE TITLE
Lightning Golem wrath aura not stacking with Wrath

### ISSUE THREAD

**Issue by Aelius51** [PathOfBuildingCommunity/PathOfBuilding#3067]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Enabling Lightning Golem's wrath aura in the configuration should increase DPS even if Wrath (the gem) is also used.

### What is the actual behaviour/value?

Enabling Lightning Golem's wrath aura in the configuration does not increase DPS if Wrath (the gem) is also use. It does increase DPS if Wrath (the gem) is _not_ used.

### How to reproduce the issue

1. Enable the Wrath gem
2. Enable the Lightning Golem gem
2. Check "Summon Lightning Golem: Enable Wrath Aura" in the configuration section of PoB
3. Notice that DPS does not change

### Build code

```shell
Sorry, what?
```

**Comment by ALT-F-X** [comment]
Auras with the same name don't stack and both of these buffs have the in-game name "Wrath". I double checked just for you!

![image](https://user-images.githubusercontent.com/5727264/127887426-4508e99e-4188-4975-8352-055a910acbca.png)
![image](https://user-images.githubusercontent.com/5727264/127887492-87520acf-cca5-4001-b6b6-47cbc79b6d5a.png)
