### ISSUE TITLE
Implement Support for Avoid Elemental/Lightning Damage

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#307]
For example - 2nd buff granted by Arakaali Major Pantheon is:
`10% chance to Avoid Lightning Damage from Hits`

2nd Example - a unveiled mod from Jun can be:
`(%d+)%% chance to Avoid Elemental Damage from Hits during Soul Gain Prevention`

PoB currently cannot parse that Mod.

**Comment by Regisle** [comment]
I was planning on adding avoidance later, note that there are lots of other types/sources of avoidance
(specific element on tree, area damage on tree, cold damage on aquamarine flask etc etc)

**Comment by Nostrademous** [comment]
For Reference: https://pathofexile.gamepedia.com/Avoidance

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1
