### ISSUE TITLE
Malachai's Artifice elemental equilibrium is always active

### ISSUE THREAD

**Issue by BrotherAzrael** [PathOfBuildingCommunity/PathOfBuilding#3072]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The elemental equilibrium given by the ring Malachai's Artifice is supposed to be effective only for the socketed gem inside that ring. 

### What is the actual behaviour/value?

As soon as I equip the ring in any build, without any gem inside the ring, the dps calculation is made as if EE was on for any element.
Equipping a gem inside the ring doesn't fix the type of damage done to trigger EE.

### How to reproduce the issue

1. Select any elemental skill as main skill.
2. Equip Malachai's Artifice.
3. Observe the dps loss due to EE being counted as on.

### Build code

```shell
https://pastebin.com/xjuMscjv
```

**Comment by pundm** [comment]
![image](https://user-images.githubusercontent.com/54453318/127771327-f8213a1a-5fd1-46b0-94e5-d8d0a2174e09.png)

Check whatever type of elemental gem is in the ring.
