### ISSUE TITLE
Incorrect "Cost and Reservation Multiplier"

### ISSUE THREAD

**Issue by uranmorte** [PathOfBuildingCommunity/PathOfBuilding#3078]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Incorrect "Cost and Reservation Multiplier" - support gems have value -10%

https://www.pathofexile.com/forum/view-thread/3152771 

### Describe the solution you'd like

Update values of "Cost and Reservation Multiplier" support gems

**Comment by pundm** [comment]
Will be included in next patch.

**Comment by Wires77** [comment]
Fixed in 2.7.0
