### ISSUE TITLE
"Attack have x% chance to cause bleeding" mod on weapon isn't included in calculation

### ISSUE THREAD

**Issue by AnNguyen1412** [PathOfBuildingCommunity/PathOfBuilding#3079]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

chance to bleed for Spectral Shield Throw is 88%

### What is the actual behaviour/value?

chance to bleed for Spectral Shield Throw is 108%, PoB doesn't include the "Attack have chance to cause bleeding" on weapon

### How to reproduce the issue

Included pastepin

### Build code

```shell
https://pastebin.com/SMByDm0S
```

### Screenshots

![image](https://user-images.githubusercontent.com/49244197/127872352-6e709fa0-cf16-411c-b1d8-4c2a0ebe6de1.png)
![image](https://user-images.githubusercontent.com/49244197/127872490-3a010c0d-6c54-4f5c-a498-3d8c1426232d.png)

**Comment by learn2draw** [comment]
Are you sure this bleed chance affix is not a local modifier?

**Comment by ALT-F-X** [comment]
It is global. 
![image](https://user-images.githubusercontent.com/5727264/127885008-a7a02d95-8d47-41d9-9791-0751a24e5645.png)

**Comment by QuickStick123** [comment]
It was changed recently to be a local modifier so this is no longer a problem
