### ISSUE TITLE
missing unique

### ISSUE THREAD

**Issue by makleikle** [PathOfBuildingCommunity/PathOfBuilding#3084]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Usurpers Penance is missing from the latest pob version

### Describe the solution you'd like

to add it

**Comment by PJacek** [comment]
Duplicate of #3058
