### ISSUE TITLE
empower Victario's influence  mana reserve problem 

### ISSUE THREAD

**Issue by ogurisan** [PathOfBuildingCommunity/PathOfBuilding#3095]
anger link to empower in Victario's influence  in real game 3.9%mana in pob says  4.2%
flesh and stone link empower in Victario's influence   in real game 2.73%mana in pob says  2.94%
my mana reserve mod is x0.36
if I pull out empower pob show same number as game does

**Comment by ppoelzl** [comment]
Please fill out the bug report issue form we provide. Thank you.

**Comment by ogurisan** [comment]
where is the link ?? I cant find it

**Comment by ogurisan** [comment]
> Please fill out the bug report issue form we provide. Thank you.

where is the link ?? I cant find it
