### ISSUE TITLE
incorrectly displayed health, damage, resistance to chaos, maximum resistance and probably many other things that I did not notice

### ISSUE THREAD

**Issue by Demidov2jz** [PathOfBuildingCommunity/PathOfBuilding#3096]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I want to see the actual data

### What is the actual behaviour/value?

Hp in game: 5371, in pob: 5294
chaos resistans in game 84, in pob 70
damdge in game: ???? in pob: ??????
What used to affect the attack speed and the speed of magic creation-now there are no indicators.

### How to reproduce the issue

import my build by the nickname Maks1990

### Build code

```shell
Maks1990
```

### Screenshots

![git1](https://user-images.githubusercontent.com/74548901/128516909-c36de8b7-b108-4a11-867d-e337a700a571.png)
![git6](https://user-images.githubusercontent.com/74548901/128517379-4950cd00-1b28-4e76-a120-4c16005dffdf.png)
![git2](https://user-images.githubusercontent.com/74548901/128517383-f28a9080-9b50-459b-b163-f15854678023.png)
![git3](https://user-images.githubusercontent.com/74548901/128517389-19034b2a-d700-4b91-a0ec-536883118517.png)
![git5](https://user-images.githubusercontent.com/74548901/128517392-398c82c8-ebfd-4cba-91c4-8ec6d5167fa7.png)

**Comment by Wires77** [comment]
Have you set the mods on these nodes within your glorious vanity properly?  PoB is unable to import those mods.

![image](https://user-images.githubusercontent.com/1209372/128521929-7d87ec89-6e88-4264-9ccf-b8989420087e.png)
![image](https://user-images.githubusercontent.com/1209372/128521985-497ed58e-4f83-4f26-9e69-cf0bfb154ec2.png)

**Comment by Demidov2jz** [comment]
Last season, everything was displayed correctly. And this ability is displayed correctly on the standard, including this ability. I did as you said, the POB does not react.
![image](https://user-images.githubusercontent.com/74548901/128532505-a95a121d-8f1c-4ab5-affa-3adad87a6f91.png)

**Comment by Wires77** [comment]
Uh, wow, I didn't even know you could try and replace the keystone mod, that should be fixed.  Try replacing one of the smaller nodes instead.  In-game, what stats do those nodes give?
