### ISSUE TITLE
Incorrect Value for Slipstream's Action Speed Buff

### ISSUE THREAD

**Issue by Yagtosan** [PathOfBuildingCommunity/PathOfBuilding#3104]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The action speed value of Slipstream should be displayed as 10%

### What is the actual behaviour/value?

The action speed value of Slipstream is being displayed as 20%

### How to reproduce the issue

1. Equip The Flow Untethered, Cloth Belt.
2. Go to Configurations
3. Hover of the checkbox for "Is Slipstream active?"

### Build code

```shell
https://pastebin.com/nt1HT8CV
```

### Screenshots

![patchnotes](https://user-images.githubusercontent.com/29215343/128624259-13da7d2e-ad64-48bf-a75d-bedb1bc11265.png)
![oftime](https://user-images.githubusercontent.com/29215343/128624260-353ae46c-fd3d-405b-a403-c44767d68c12.png)
![image](https://user-images.githubusercontent.com/29215343/128624609-d7f9572b-b8da-42d3-b8ed-2b4b10f7184f.png)

**Comment by LocalIdentity** [comment]
It is only applying the 10% updated value but the tooltip was not updated
