### ISSUE TITLE
POB error: In 'OnFrame'

### ISSUE THREAD

**Issue by Bhurin072** [PathOfBuildingCommunity/PathOfBuilding#3109]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

the error message started showing up while I was making a build. This build was not imported. The error showed both with the installer and standalone client, even after re-installing.

### What is the actual behaviour/value?

the error will forcefully show up even after restarting. 

### How to reproduce the issue

Not exactly sure, but it only seems to be happening with the linked build, maybe a certain item in the build is causing the issue?

### Build code

```shell
https://pastebin.com/ED2WL04x
```

### Screenshots

![POBbug](https://user-images.githubusercontent.com/88633582/128646178-0b69f33e-a311-4ea4-8eef-b7e6c3d54a38.JPG)

**Comment by Wires77** [comment]
Fixed in 2.7.0
