### ISSUE TITLE
Get pathofexile.com/trade/ links from items on the build

### ISSUE THREAD

**Issue by viniam** [PathOfBuildingCommunity/PathOfBuilding#3111]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Would be awesome if there was a way to auto generate a pathofexile.com/trade/ redirect from the Items tab, would speed up a lot of time.

No idea as to how hard it would be, but still good to have the idea out there for any exile to implement.

### Describe the solution you'd like

Maybe implement in a way like this: 
• Press "Find in trade" button
• Select the item you want to search
• Select the mods you want (with or without rolls)
• Click submit and it goes to the trade site.

**Comment by Nostrademous** [comment]
A version of this is currently implemented in `dev` and will be part of next release. It would be more work than we are willing to put into PoB to allow custom drop-down mod selection and roll values for items. Instead, the way we implemented it currently, is it auto determines all possible mods on the item type (armor, one handed sword, jewel, etc.) based on item slot and calculates which provide the best DPS gain and create a weighted search to retrieve those and create them within PoB allowing you to scroll through them.

**Comment by Nostrademous** [comment]
The weighted search it does will give you the URL (which you can CTRL + mouse click) it generated in PoB which will spawn a webpage in your browser if you hit “Find Item” again (to the left of the scrollable items it retrieved if it found any). That webpage will have all the filters pre-populated allowing you to modify if you chose.

**Comment by viniam** [comment]
That's awesome, it's a good feature, takes some time to run all items and then going to trade and removing weights, but it is really helpfull, great job on that!

**Comment by Nostrademous** [comment]
Reason it takes a while is because we added support for checking and enforcing rate limits for fetches and queries as documented by PoE’s trade API guidelines. Probably faster to do one at a time rather than running all items at once and then popping web browser page for each one. There are limits to how many searches, queries, and fetches you can do in a certain time window to not over-burden their server. 

Glad it’s working for you though.

**Comment by viniam** [comment]
My idea was not to get the result on PoB and just take us to a new webpage with the mods there (even without rolls) .

**Comment by QuickStick123** [comment]
It also produces a link like https://www.pathofexile.com/trade/search/Standard/O7d9JL8iE which should be good enough.

**Comment by viniam** [comment]
If PoB is able to produce the link with the mods inside it, why not just make so we don't need session ID and just go straight to the website, without weights? I'm failing to understand, is it a technical problem?

Also it doesn't search for uniques?

**Comment by QuickStick123** [comment]
I am guessing since to get a search on their servers (a url) you have to search it and since we want to use the largest number of mods we need the session id to allow larger searches to generate the urls?

**Comment by Nostrademous** [comment]
PoE trade site requires you to be signed in (which is also equivalent to have a POE session ID token. To try, open an Incognito web-browser session and go to [https://www.pathofexile.com/trade/search/Standard](https://www.pathofexile.com/trade/search/Standard). You will see a prompt to make you login through one of many methods.

The Weights are only for automating "Find best" button (currently that's only DPS based... in the future I might also include eHP weights into equation and give the user a scale to control how many DPS points is 1 eHP worth so they can favor defensive or offensive auto-itemization searches). 

You can go manually to the website and create your own search by hand. As soon as you run a query it will auto-update/generate the unique URL that encompasses the search filter criteria you created. The PoB Trade allows you to Paste the URL into the appropriate item slot and saves it as part of your build. Now, when you share the build with others, and they bring up the PoB Trade window it will already have your URL pre-populated there (with auto-correcting for league names between leagues). It even remembers the URL on a per-item-set granularity, meaning you could have a "Budget", "Endgame" and "Mirror-Tier" Itemization specification and the URLs are remembered/saved/shared as part of those item sets.

"Find best" is only for non-unique items. You can set the manual URLs described above for uniques.

Finally, to answer your question, no there isn't a "technical" problem (there is a minor one with respect to hybrid mods as we have no way of knowing when an item has armour and maximum life on it if it's 2 modifiers: 1 for life, 1 for armour; or 1 hybrid modifier unless the ranges are above limits of what could be achieved independently on those and then we wouldn't know the split up). However, you could take an item and create a search with all the "same" mods and ensure that every mod is at least of the same value or higher... however that is only useful if you actually all the best mods on the item already... and in that case you can just make your own URL and paste it in and then just click the "Price item" button to run it as often as you want.

**Comment by viniam** [comment]
I got it, the problem is that sometimes people just want an item with the same mods, similiar, not the exact same or the "best in slot" so that they can get similar results or just get the build working (I fall in this category, since I'm poor and don't know how to make builds :']).
But the way it works now it's wonderful for min maxing the build!

**Comment by viniam** [comment]
Anyway, I'm grateful for this new way to auto-find the item, it shortens a lot of the time to build for sure
