### ISSUE TITLE
Did PoB just break?

### ISSUE THREAD

**Issue by tumba00** [PathOfBuildingCommunity/PathOfBuilding#3115]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Crash when opened

### What is the actual behaviour/value?

error

### Build code

```shell
error
```

### Screenshots

![Screenshot 2021-08-08 202401](https://user-images.githubusercontent.com/49126499/128650334-95076703-47db-4e46-b926-b2eb1f75d5ca.png)

**Comment by projectsix84** [comment]
Yep, same thing here.

**Comment by Wires77** [comment]
Copy `EnchantmentBody.lua` and `EnchantmentWeapon.lua` into your `Data` folder from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/master/src/Data

**Comment by tumba00** [comment]
> Copy `EnchantmentBody.lua` and `EnchantmentWeapon.lua` into your `Data` folder from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/master/src/Data

Thanks it worked

**Comment by TheSixStringSamurai** [comment]
I'm also getting an error attempting to edit support gems for Absolution 
![poberror](https://user-images.githubusercontent.com/25860648/128653374-48d61da2-18b1-4043-80dc-79ba7f397643.png)

**Comment by Wires77** [comment]
> 
> 
> I'm also getting an error attempting to edit support gems for Absolution
> ![poberror](https://user-images.githubusercontent.com/25860648/128653374-48d61da2-18b1-4043-80dc-79ba7f397643.png)

Please open a separate issue an fill out the issue template
