### ISSUE TITLE
"Arena Challenger" gladiator's ascendancy node doesn't work on poe.ninja.

### ISSUE THREAD

**Issue by GuppiTheSlayer** [PathOfBuildingCommunity/PathOfBuilding#3135]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When i importing pob from any gladiator characters from poe.ninja with "Arena Challenger" ascendancy node it must have checkbox on "Do you use Challenger Charges" ,because you have 100% uptime of it on bosses/shaper(with or with out blood and sand or flesh and stone it is considered that you are in blood stance alltime)
![4444](https://user-images.githubusercontent.com/88807071/129119422-e6f8c248-c213-4580-bdc7-b4ebbae5cf0b.png)

https://pathofexile.fandom.com/wiki/Blood_Stance_and_Sand_Stance
![6666](https://user-images.githubusercontent.com/88807071/129120000-6eddf89d-94e3-460b-9576-b611f9d0f8ee.png)

![7777](https://user-images.githubusercontent.com/88807071/129121512-a3983a59-439b-4d2d-818a-444ea012bd53.png)

### What is the actual behaviour/value?

But in fact, this does not happen, and when you import pob you have not checkboxe on this point.
![55555](https://user-images.githubusercontent.com/88807071/129119862-2e73130f-078a-4ee2-ae19-d080f5f05d8c.png)
For example character with blood and sand skill gem https://poe.ninja/challenge/builds/char/Born%E3%86%8DTo%E3%86%8DBe%E3%86%8DPsom/GuppaNeNado
https://pastebin.com/BMFj7cwA
or with out any stance skills 
https://poe.ninja/challenge/builds/char/blauli/blauGlad
https://pastebin.com/7KJ39hPw

### Build code

```shell
https://pastebin.com/7KJ39hPw https://pastebin.com/BMFj7cwA
```

**Comment by ppoelzl** [comment]
We don't develop poe.ninja and we're not affiliated with the poe.ninja developer. Builds from poe.ninja are imported according to this configuration: https://poe.ninja/builds/pob-rules, which is outside of our control. Please take this issue to the poe.ninja developer instead.

**Comment by GuppiTheSlayer** [comment]
ok ty
