### ISSUE TITLE
Elevated "Reduced Reservation" mod shows up when crafting a Redeemer Amulet

### ISSUE THREAD

**Issue by yusayu** [PathOfBuildingCommunity/PathOfBuilding#3137]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The "Elevated" Tier should only be available when creating Body Armour, Helmet, Boots or Gloves.

### What is the actual behaviour/value?

When "crafting" an Amulet under Items->Craft Item...->Amulet (any Base Type)->Select Redeemer as Influence->Select "Reduced Reservation of Skills" as a Suffix, the Tier of the Suffix can now be set up to "of the Elevated Redeemer" which is not actually possible in game. Maven's Orbs cannot be used on Amulets, therefore an Amulet cannot have an Elevated Mod.

My assumption is that PoB uses the Helmet Suffix modifier for the same stat where it actually _can_ turn into an Elevated Suffix. This might happen with other affixes as well, I only found this one so far.

### How to reproduce the issue

1. Go to Items
2. Click Craft Items
3. Select Amulet and any Base Type
4. Select Redeemer Influence (does not happen with Shaper Influence which has a similar mod)
5. Select "Reduced Reservation of Skills" as a Suffix
6. Set the Slider to "of the Elevated Redeemer"

### Build code

```shell
eNq9Wltz4sYSfja_QkVVqs6pig2juyicFL6uq4yXA97d5GlrLDWgeJCINMImqfz30zOSjdYB02hzjh-wLl_fe3q6B_o_Py-EsYIsj9PktM1Oum0DkjCN4mR22v50f3Xst3_-qdUfcTn_OD0rYqHe_NQ66utrQ8AKBNK1DcmzGcjPL5ysr8hpyRM5hzQZ8t_S7DqNTtt3aQJt44EnUSxf7kLB8_yOL-C0PQmRuG3wPIQkOt88L4ELHieTNHwEeZ2lxVKLXcXwNEwjxNwMRx_H9zWhcVIXijof9UeCryGbSC6NHD9O2wM0nc_ggi_wE7lxUSAr88T2PJsFlmP7lu-1O9uJJ0uA6JWInZj_P-Aog8vpFEIZr-A8i-X5nCfhxoDuLrpDscNCyHgpYshqWjm7KD78jXng7sLep5KLi9Gk5vTAM4OuZZqO33Wd_w1dKvfb_SWW8zOBgWggRdHezJJYQkPiURrnafId9tVJd4c2XTzESSMLX0gHq9mhpEOe8PM0J4TgNp4CDXk5oeHGuL5pSKXlCDKsQJKu7EEEE7lZTeZujeH3OnAn7gKeadzqwJ24m0TSuNWB7-i2SqUu6RQnvqLc7jsFMuwp7E0S0ph-SjLIIVvV6qpLJKiCuql83XcJxzCDmqUnvv0e-hYgnF_jjjbmEmhZ-Ypy3vePwpL8o4Bb_OMQCQ7wjyJ865_gPfCB7vnCs4hQLBLIZuvJPAZBQGtf1klIPq0TvLGYQnKg3ZcrntfXF3Pft6aE05IDcA9Eggje7OnOP0cxytLfVBMjDiMbZIu0yIgRLMEkk0fzdR6HuI3qdnAMURHSqtdrLzZMV7DANaEbOexLN4HZRXomsKOltmTIVoiDKAZS8vDxIo1mcJCQgyiu4gy9lce1ze_YJaA_Yvd9zpeUfkUtJqqADZos4DaezWWCow1dyhsSui1znuYHGLOBk0VcFUKQ-sDJY_wtUvIHAT2j-8wcHrDI93culfQJlZmroS8nLKwaesg3bYi104IMkj_WZP7fwEkCLpOoyFR2k2W8pfi7mH5HD8Xq6maxTDOpH55zEeaa5U2yLKSR6Ik2V57_mhSLBzValf83VaKOXMR5-PWhmE7VmNtGZTI9m19eXV2e3998vqxIJqBrlRGmQvBlDjj3JrFoG3FUhXmC1TmUBDROcdU8vB-L-26Yxei-_VA1exFU1RPwfpwaTgkwjAMXQHXR_XoJKuI5zUtVedyP1dMkAVcOfxSz9IhJcTqEfE3AvbYdBOylgEEs1C5H8dMQ07fcHilo3K6y-KGQpIzSMwNBA9U6E8yqN4ekzKfAqlaFIL7q5PYjq72DknbYKBBDdAFTwGQmLWRdHO75IyRV2XspcX29inIjx9p3DYv8bI17y5Vy6Jsjh28AuOtkBVa2CKa8EOr5fwouYrmuZG6e35anjfppPk-fJsVyWXJSKzdHb9_elm8GQlZMlJjT9pSLvMyV_n0GYHDdran-UBXd0mS8qZ883kRqMzASrLrIwPF9y2obEolrZ5zMqY4vS7Dic9S_jHBtRneKrlM--TS-1RdHcymXea_TeXp6OllyOU-n8IzN70mYLjpLZIM6Heud4VgJ6gzw70x9DE5PNaPOC6d-eQ6al2yrO62r0oS5JvMxWBIWpWKdHTjGcNbbj3OZb9kUnO34FgFnmkFA4Wf7rhdQ-FmMEWCB3aV4xXJdkrWWbdOsZYFP4WfaAcUKy_IciliLuTT1XM90CDjHYQElWeyg61NwzGIeBecFLkms6_smCYd2kNzsWpRw2F272yWFo0sRy0yXWSQzrIAUXcwWlxLdwPEpWcDsgCQ38AKPop5vexSxZuAxk5TMLHBJFc3qOiSc6fukiubZpNpiBX5Akuu6FDuYZzJahSTXII-2I9gkuTbmMyVdHIZFkmJv17EoecB82yKlPSrokYqa69N2LM8l2WEyl1RdGDKk4GzmkvLKtEjh7XqWQ9oqA1KRdANGqpGmty1b-p1at4M32KjptlN1curiLsV5Qb1TD19udJ_3OYYnIwccUucTifN12_gjTRe_6sZOtYkfgMshX1YtpXpXtZhW1WDiMHgR4_SS6eb4pVNVwF9e9OvfoLp51VGq6wlI_dV0kQO20WkSfQG-TBP9WMkpJ3wE6m667D6PxhwH2nXPGA_Gl6071FoBWkOePQgwBotCgGyNIQJYQFa-O8_4FPvMnqF0ao0ymMbPPUN91_3OzaSY6ps_M57MoNc98Zjzlz7ohKg8o1dH-1zqQ-KpKJTZQ76C5JXyGzb6pmq0e0a3pb03ht97hme3cPYWcRjLvGew1p-Sz_JeBjlOQyH8KHB0--tVCaXCDHD-4hKMf7ET85iduP_-wUinhprxjCXanGtXtrwfjKxU16jpqpDl7KHzZZhGY8Xa0ALUdw1Ou3J2Od50lAfLrl-kLwctpZc36fd6GFPGdGc862Gs8ythBps88aUxeFjnORdGlfFbFtc20rdkJo3sfdRZmsq8oULbbNmj1BkIeSDJFY5Uj4ZFUsncppLVzL00J5j_EJndTEm3mTS3uTeb5NOeCHwAsQB5qKAtmeQ2kbMn_a5FulInwocztpqvItZEnt0sF1izzLP3h4fi2EPZbkuvhoaT6o7TQJ8GNdDaJyZaG-Xp4YHh2-7lRvnlNCEiLUlKIBrZ6TR2q9kg7m6zlWQ1S1_r8Cyzm5f9BjnNGjvfoiSETQE1UPs7mh9iJJtHwW2Qlc3D8B3pQi3Jipa4aujQBp4bx8mM1gkcXCh2urdhuaDHs4k5FsFPrHkY7MbecppYQ1kvzZN8j0q7RshONUPqYwt9XqB_GZAm03iGiH7n7e_r_wv2EFiz
```

### Screenshots

![image](https://user-images.githubusercontent.com/88824257/129164408-4d24d711-4219-468d-90cb-743b81cadd0c.png)

**Comment by pundm** [comment]
Hi, thanks for your post.
I checked and this data is coming straight from GGG:

`["ReducedManaReservationInfluenceMaven"] = { type = "Suffix", affix = "of Elevated Redemption", "(6-7)% reduced Reservation of Skills", statOrderKey = "1730", statOrder = { 1730 }, level = 85, group = "ReducedManaReservationsCost", weightKey = { "helmet_eyrie", "amulet_eyrie", "default", }, weightVal = { 0, 0, 0 }, weightMultiplierKey = { }, weightMultiplierVal = {  }, modTags = {  }, },`

Regisle's guess is, that they had some other method of providing the elevated mods originally that also worked on amulets, and never removed it from data.
