### ISSUE TITLE
Chain hook + 1H axe

### ISSUE THREAD

**Issue by JoPet123** [PathOfBuildingCommunity/PathOfBuilding#3144]
Hi! 
Chain hook skill gem specifies that it can be used with 1H axes but I can't get it to work in PoB 
![image](https://user-images.githubusercontent.com/15380240/129390588-d6e73f90-6b7c-467f-86a7-d5df29e8e003.png)

That's while having a Vaal hatchet equiped.

Is there a way to fix this?

Thank you

**Comment by pundm** [comment]
Hey,
this seems to work just fine, if the problem persists, please open an issue and follow the template form.
