### ISSUE TITLE
Don't recommend Elemental Gems/Skills/Support after user adds "Brutality" into a "Socket Group"

### ISSUE THREAD

**Issue by aksn1p3r** [PathOfBuildingCommunity/PathOfBuilding#3152]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Since Brutality disables all Elemental Damage, recommending Elemental Damage types of gems in the list with a tick, is somewhat misleading.
![image](https://user-images.githubusercontent.com/52001/129605061-39278580-169d-45e6-b65f-086409a45284.png)

### Describe the solution you'd like

Change the ticks to a cross and not recommend Elemental gems after adding Brutality(or other gems that disable element damage).

**Comment by aksn1p3r** [comment]
If I am mistaken by any of the functionality, let me know, since I am also not the most knowledgeable at PoE or PoB as yet. Just thought this is something to make the "Socket Groups" part a bit better, I do like how it suggests from Highest DPS to lowest but noticed this with Brutality. Thanks for PoB

**Comment by PJacek** [comment]
Gems are sorted depending on their contribution to the main skill.
![image](https://user-images.githubusercontent.com/18018499/129609815-4e752535-052e-4d16-bcac-fb2cfa3b934c.png)
Yellow check mark means that the gem can be linked but doesn't change the dps (because it's a different skill in your case)
