### ISSUE TITLE
Support Gem sorting breaks when default gem level is set

### ISSUE THREAD

**Issue by jokre33** [PathOfBuildingCommunity/PathOfBuilding#3157]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Support Gems are listed in order from most to least damage increase.

### What is the actual behaviour/value?

Support Gems are listed in seemingly random order.

Further testing leads me to believe it's sorting as if all Gems including Awakened and other lower max level Gems (Empower, etc.) are the level the default is set to, then on hover show the damage increase at their capped level (6 or 4 respectively) on mouse-over.

### How to reproduce the issue

1. Open, import or create a build.
2. Set Default Gem Level to 20 (any 6+ works but it's much more pronounced at 20) and make sure all Support Gems are shown
3. Click on the blank field that opens the support gem list on the currently selected Main Skill.
4. Hover over the potential Support Gems to see the DPS gain

### Build code

```shell
https://pastebin.com/XNN1CFpw
```

### Screenshots

![2FCaUkmNB9](https://user-images.githubusercontent.com/547069/129813443-4613f420-06d2-450c-bc20-d7b5a8694254.gif)

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
