### ISSUE TITLE
Did someone contact GGG about releasing new gem info in POB format before the league starts?

### ISSUE THREAD

**Issue by bukowa** [PathOfBuildingCommunity/PathOfBuilding#3162]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

If GGG could release the data before league starts we could theory craft the builds pretty well. Did someone already tried?

### Describe the solution you'd like

Contact GGG.

**Comment by ppoelzl** [comment]
No values are final until the moment the patch hits, basically. This arrangement would not be beneficial for GGG, and it would also not be beneficial to PoB users.

**Comment by bukowa** [comment]
> No values are final until the moment the patch hits, basically. This arrangement would not be beneficial for GGG, and it would also not be beneficial to PoB users.

Can you tell me more about this being not beneficial i am curious.

**Comment by ppoelzl** [comment]
Why plan your build around values that could and probably will change drastically on release?

**Comment by learn2draw** [comment]
This also gives an unfair advantage towards PoB devs compared to other available tools, which without GGG'S officials endorsement could cause other issues
