### ISSUE TITLE
Skip node power calculation for irrelevant nodes

### ISSUE THREAD

**Issue by buralien** [PathOfBuildingCommunity/PathOfBuilding#3163]
When Show Node Power is checked (with f.e. Full DPS selected) on a character with already selected ascendancy, the calculation also happens for nodes in each ascendancy other then the one selected, even though most if not all of such results are irrelevant - especially nodes for other classes. These combine to 200+ nodes being calculated uselesly, slowing down the final result.

The suggestion here is to set each node in an ascendancy other then the one currently selected (or at least in a class other then the one currently selected) to appear to make no difference to the character.

**Comment by ppoelzl** [comment]
Please fill out the feature suggestion issue form instead.
