### ISSUE TITLE
Focussed and Focused

### ISSUE THREAD

**Issue by Hellsing** [PathOfBuildingCommunity/PathOfBuilding#3165]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Path of Exile is using the term "Focused", here is an example:

`{crafted}Your Critical Strike Chance is Lucky while Focused`

I should be able to select the option "Are you Focused?" in the Configuration tab.

### What is the actual behaviour/value?

Path of Building however does not detect the term "Focused" and expects it to be "Focussed", which after changing that is accepted in Path of Building and then I'm able to select the option "Are you Focussed?" in the Configuration tab.

So there are two typos to be fixed in Path of Building, one the detection of the mod and two the typo on the Configuration page.

### Build code

```shell
None
```

### Screenshots

![image](https://user-images.githubusercontent.com/1331016/130356051-992ee791-3ef3-48db-b935-495fdf5f17cc.png)
![image](https://user-images.githubusercontent.com/1331016/130356060-ec7c3544-c48f-4348-872e-c599d1c63d41.png)

**Comment by Wires77** [comment]
Fixed in 2.9.0
