### ISSUE TITLE
Feeding Frenzy has no effect?

### ISSUE THREAD

**Issue by FuzzyThailand** [PathOfBuildingCommunity/PathOfBuilding#3166]
Case in point: https://pastebin.com/0NEEKVei

Under SRS if I enable or disable the Feeding Frenzy gem, nothing happens. Checked under Default Attack as well as Minion Instability. Shouldn't it have some effect? According to the gem's description: "Supported minions have a chance to give the owner the Feeding Frenzy buff on hit, which grants a damage and speed bonus to all friendly minions. " 

Or is that damage and speed bonus unknown?

**Comment by PJacek** [comment]
You need to enable it in the Configuration tab
![image](https://user-images.githubusercontent.com/18018499/130357479-1bc294fc-527b-4626-8b05-4e080376f53d.png)
In the future, please use the issue template
