### ISSUE TITLE
Anointment Command of Steel 

### ISSUE THREAD

**Issue by omnislash79** [PathOfBuildingCommunity/PathOfBuilding#3174]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Command of Steel
5% increased Attack Damage per 5% Chance to Block Attack Damage
+3% Chance to Block Attack Damage while holding a Shield

### What is the actual behaviour/value?

no changes 

### How to reproduce the issue

anoint an amulet with Command of Steel 

### Build code

```shell
https://pastebin.com/q2FS030e
```

**Comment by ifnjeff** [comment]
Looks to me like it's working as intended, your build already has Command of Steel allocated. Anointing a notable which you already have allocated does not grant you double the effect. If you deallocate the notable on your tree, you'll find that the amulet does give you the effect.
