### ISSUE TITLE
Bitterdream not updated to use Inspiration support instead of Reduced Mana support

### ISSUE THREAD

**Issue by Rosemary102** [PathOfBuildingCommunity/PathOfBuilding#3180]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Bitterdream grants "Socketed Gems are Supported by level 1 Inspiration," like Replica Bitterdream currently does.

### What is the actual behaviour/value?

Bitterdream attempts to grant "Socketed Gems are Supported by level 1 Reduced Mana," which does not function since that gem got reworked into being Inspiration instead. Manually editing the description can fix this though.

### How to reproduce the issue

Check out Bitterdream in the import uniques tab.

### Build code

```shell
Bug visible from a fresh and empty build.
```

### Screenshots

![bugpob](https://user-images.githubusercontent.com/43137266/131201277-07801b87-d245-4092-94cc-f173df83d99e.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.9.0
