### ISSUE TITLE
Herald of Agony does not show poison DPS

### ISSUE THREAD

**Issue by Draywen** [PathOfBuildingCommunity/PathOfBuilding#3181]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Herald of Agony should show poison DPS in the Calcs section with the Minion Stat enabled.

### What is the actual behaviour/value?

Herald of Agony does not show poison DPS in the Calcs section. (Show Minion Stat is enabled)
If I enable Chance to Poison support then it shows the poison DPS.
Herald of Agony has 20% and Chance to Poison Support has 40% chance to poison so Calcs should show poison DPS either way. 

Screenshot 1 is Herald of Agony calcs not showing Poison DPS.
Screenshot 2 shows Herald of Agony with Chance to poison support enabled.

### Build code

```shell
https://pastebin.com/NWDVfi9s
```

### Screenshots

![HoA DPS 001](https://user-images.githubusercontent.com/89684837/131214149-3e280f5a-a138-43fc-9f67-5fbc8023b6eb.jpg)

![HoA DPS 002](https://user-images.githubusercontent.com/89684837/131214158-81b58cd8-6a14-4f40-a394-11a2bc0df180.jpg)

**Comment by LocalIdentity** [comment]
The Herald of Agony minion does not inherit the chance to poison buff that it gives players
