### ISSUE TITLE
Help - PoB FONT doesn't not display!

### ISSUE THREAD

**Issue by DiGizap** [PathOfBuildingCommunity/PathOfBuilding#3182]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I start program all text comes in white squares.
It started doing that right before Expedition league start. (didn't brought that issue earlier since I didn't played much in this league. I am using newest updates and I have tried many things to search for similar problem even with other programs, couldn't find anything.

### What is the actual behaviour/value?

No Font whenever I start the program.

### How to reproduce the issue

Have no idea, but I guess, maybe, I miss font in my windows machine. 

### Build code

```shell
No idea where I should get that.
```

### Screenshots

![image](https://user-images.githubusercontent.com/89706664/131228669-04f72dbc-1351-4b3b-b3d6-ec6ba5e57dec.png)

**Comment by zao** [comment]
The fonts are all internal to the installation and uses no operating system components. They're image files with predrawn letters on them which the program shows one by one, but in your screenshot the contents seem to be just non-transparent white.

I'm not certain about the reason why something like this might happen but in order to rule out a corrupt installation of PoB I would recommend downloading the current Portable version of PoB and extract it somewhere separate from your existing installation and see if it behaves differently: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.7.0/PathOfBuildingCommunity-Portable-2.7.0.zip

**Comment by DiGizap** [comment]
> The fonts are all internal to the installation and uses no operating system components. They're image files with predrawn letters on them which the program shows one by one, but in your screenshot the contents seem to be just non-transparent white.
> 
> I'm not certain about the reason why something like this might happen but in order to rule out a corrupt installation of PoB I would recommend downloading the current Portable version of PoB and extract it somewhere separate from your existing installation and see if it behaves differently: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.7.0/PathOfBuildingCommunity-Portable-2.7.0.zip

Tried that, 
Even tried to play with internal machine settings such as default themes light and dark transparency effects...
I guess it is time for reinstallation of windows I almost gave up on that issue :)

Anyway, thanks for answer :)

**Comment by zao** [comment]
If you press "New" (the leftmost of the top row of buttons, does the skill tree render as it should?
I would guess at either some driver incompatibility or driver setting being weird, or running on the wrong GPU.

**Comment by DiGizap** [comment]
> If you press "New" (the leftmost of the top row of buttons, does the skill tree render as it should?
> I would guess at either some driver incompatibility or driver setting being weird, or running on the wrong GPU.

Thanks man, after you wrote GPU I tried something and it worked.

So my  set up:
Laptop Razer blade from late 2019 with Rtx2070.
I use external screen " Acer Predator Z35"
I use Dock station "Targus USB3 DV2K Dock"

I use Targus to pull refresh rate from 60Hz to 85Hz.

So If I plug off USB dock and start POB it loads properly, and if I connect back it is still fine. But if I try start POB with connected Targus dock it loads as white squares :)

Hope it will help someone if they will encounter same problem :)

**Comment by zao** [comment]
We've had some other cases earlier on where docks with graphical capabilities may be extremely inept at graphics APIs like OpenGL, great to hear that you've found a workaround.
