### ISSUE TITLE
General's cry: wildly innacurate DPS estimates. 

### ISSUE THREAD

**Issue by rlav440** [PathOfBuildingCommunity/PathOfBuilding#3190]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### General's cry gives highly innacurate damage numbers.

Currently, general's cry DPS appears to be _more_ than a best case estimate.
For each mirage warrior, the DPS calculation appears to be modification to the base DPS of the 5 link skill.
In most cases, this vastly overestimates the combined DPS, as the skill is limited by warcry cooldown. 
(In addition, combined DPS includes the self cast DPS of the trigged skill)

### Simple skills (non-channeling)
POB already has a calculator for cool-down gated mechanics, used for cast on crit/similar skills.
For non-channeled skills in most builds, effective damage would be better represented as:
> per hit damage _x_ warcry frequency _x_  general number = maximum DPS

### Non-channeling with High CDR
There is a question for high warcry CDR builds, as generals cry limits the number of generals up at one time. 
It seems really unlikely that someone can hit enough warcry cool-down reduction for this to matter, discounting travel time, which is outside the scope of POB.

### Channeling Attacks / Skills with attack speed scaling component
Generals now use channeling attacks for 0.6 seconds, as of 3.14.
The effective DPS of each warrior changes depending on the channeled attack.
Thankfully, there aren't too many of these.
Cyclone is the simplest:
> Cyclone: per hit damage _x_ mirage attack speed _x_ channel duration _x_ general number = maximum DPS

All other skills build stages, and as a result would need to calculate the number of stages reached in order to calculate the per channel damage. (Blade flurry is a good example of this; it's often pointed to as a skill that can actually come close to the POB damage numbers because of favorable mechanics.)
Charged dash makes my head hurt.

Edit: Some more mechanically complex skills, like blade storm, also scale with player attack speed.

### Channelling at High CDR

Because mirage warriors channeled skills always persist for 0.6 seconds, if roughly 2 warcries per second is achieved the general cap will limit further summons.
Again, I don't think this is at all feasible.

### Additional context

[r/pathofexilebuilds discussion](https://www.reddit.com/r/PathOfExileBuilds/comments/p2wmz0/generals_cry_and_misleading_pob_numbers/l)

**Comment by Lothrik** [comment]
This should be fixed in the next release as #3220 was merged a week ago.
