### ISSUE TITLE
Evade Chance with Avatar of the Chase + Blind

### ISSUE THREAD

**Issue by BBPainTrain** [PathOfBuildingCommunity/PathOfBuilding#3199]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The expected bahaviour is that the Chance to hit is halved for the enemy because it is blinded.

### What is the actual behaviour/value?

The players chance to evade get's a lot bigger than it should. 

### How to reproduce the issue

Showcasing in the following PoB which I made as simple as possible: https://pastebin.com/zjnf5ben

Allocated Avatar of the Chase for the more chance to evade which is the source of the error as far as I can tell.
Equiped an Evasion Stat stick.

Now Tick the Box "Is enemy blinded" in For effective DPS. 
The Chance to evade now risise from 55% to 95% which is wrong.
It should be 1-(1-0,55)/2.

Now to confirm this bahviour equip the same stat stick in the second Weapon Slot and unallocate Avatar of the Chase.
Chance to evade is now 56%
Now Tick the Box "Is enemy blinded" in For effective DPS. 
Chance to Evade is now 78% which is the correct Chance to evade. 

### Build code

```shell
https://pastebin.com/zjnf5ben
```

**Comment by boomboo** [comment]
Seems like an issue with order of applications, PoB applies blind before avatar of the chase which results in 95%. It probably should be before since AotC acts on evasion and blind modifies the chance to hit which is a function of evasion.

Though given that 3.16 reworks blind, it is likely no longer relevant.

**Comment by LocalIdentity** [comment]
No longer relevant
