### ISSUE TITLE
Acrobatics reducing ward when wearing faithguard

### ISSUE THREAD

**Issue by Crazy-KSK** [PathOfBuildingCommunity/PathOfBuilding#3200]
Faithguard states: **Increases** and **Reductions** to maximum Energy Shield instead apply to Ward
Just like Crown of Eyes excludes more and less multipliers and does not work with pain attunement, acrobatics should not reduce ward. 
I cofirmed this ingame aswell.

**Comment by Wires77** [comment]
Duplicates #3138
