### ISSUE TITLE
Life Reservation is Rounding Up 20%+

### ISSUE THREAD

**Issue by womft** [PathOfBuildingCommunity/PathOfBuilding#3206]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Round down following the logic of PoE

I acknowledge this issue is only more prevalent in this temp league due to the Expedition mob 20% cull

### What is the actual behaviour/value?

Reservation of Life in PoB rounds up to 21% ;  209/1007 =20.755% (3d.p.)

### How to reproduce the issue

erh no idea bout this part? just reserve life in PoB, attached PoB below

### Build code

```shell
https://pastebin.com/Dit1X53p
```

### Screenshots

![Path_of_Building_uoLKOo0bnk](https://user-images.githubusercontent.com/89849196/132515598-add3f24d-ec17-4bc0-8719-6e11da4bc2dc.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
