### ISSUE TITLE
Dev Branch Crashing with Show Node Power

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#321]
For certain builds, when you enable the heat map it crashes.

Example:
https://pastebin.com/dbxD2gMp

To fix you have to go into builds, pick the build it was looking at and change the "showHeatMap" value back to false or it will continue to crash everytime you restart or even start a new instance (unless you delete the build from the Builds folder).

**Comment by ppoelzl** [comment]
Cannot reproduce that. Could you run `git checkout 265beee4` and test again?
