### ISSUE TITLE
Allocating "Reduced Reservation", next to Influence on the skill tree, reduces damage by an unexplained 23%

### ISSUE THREAD

**Issue by Ghaduo** [PathOfBuildingCommunity/PathOfBuilding#3221]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Allocating Reduced Reservation shouldn't affect damage at only, on the amount of reserved mana/life of my skills.

### What is the actual behaviour/value?

Allocating Reduced Reservation, next to Influence on the passive tree, reduces calculated DPS by 23.1%.

When trying to diagnose what it is changing I found that the "total more" calculation for my skill DoT goes from 629% to 461% and the "total more" calculation for my skill hit goes from 229% to 153%.

### How to reproduce the issue

The described behavior was found in this build published by Big Ducks:

https://pastebin.com/AJfw8YK0

I had the "Low-life Items" selected along with the "90 || Low Life" passive tree selected.

Unspec "Influence" and then unspec/respec "Reduced Reservation" to see the change.

### Build code

```shell
https://pastebin.com/AJfw8YK0
```

**Comment by Regisle** [comment]
This is becouse it pushes you over the lowlife threshold, you also need to go swap gems around (as some skills are disabled when they shouldn't be and arent when they should be)

**Comment by Ghaduo** [comment]
> This is becouse it pushes you over the lowlife threshold, you also need to go swap gems around (as some skills are disabled when they shouldn't be and arent when they should be)

I should have thought of that! Thanks!
