### ISSUE TITLE
Trojan detection by Zemana antivirus

### ISSUE THREAD

**Issue by leezenn** [PathOfBuildingCommunity/PathOfBuilding#3225]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

On running should execute

### What is the actual behaviour/value?

Blocked by the Zemana antivirus (see screeshot)

### How to reproduce the issue

1. Install/update Zemana 3.2.28 (Free version available)
2. Run 2.7.0 version or POB

### Build code

```shell
https://pastebin.com/
```

### Screenshots

![AntiMalware_T2Dnx0eRbu](https://user-images.githubusercontent.com/76214474/135558831-015eef49-adf4-46ea-8015-36aa669adc37.png)

**Comment by ppoelzl** [comment]
See #2458
