### ISSUE TITLE
Can't save anything.

### ISSUE THREAD

**Issue by faeroDK** [PathOfBuildingCommunity/PathOfBuilding#3226]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should be able to save and see builds that ive imported.

### What is the actual behaviour/value?

I'm able to save a build, I see old folders that i've created a long time ago but i dont see anything in the menu. I always get the error pop-up ( image #1) 

### Build code

```shell
https://pastebin.com/Zq30FVub

not really a problem wit this exact build, i've tried multiple ones.
```

### Screenshots

![image](https://user-images.githubusercontent.com/91775305/135706666-0a9fe9b2-2f4c-4a78-a38f-4a864d518454.png)

![image](https://user-images.githubusercontent.com/91775305/135706764-9536e0a3-02b3-4143-89d9-f33c7053a4c6.png)

**Comment by PJacek** [comment]
Could you please provide some more information?
What steps exactly did you take to encounter this error?
When you start PoB, does it open a build automatically?
What do you mean by "I see old folders that i've created a long time ago"? There are no builds visible in the screenshot, can you see them in the explorer?

**Comment by faeroDK** [comment]
I made a clip to answer your questions. I've also tried reinstalling pob multiple times, didnt work once. 
https://streamable.com/ba2v2x

**Comment by PJacek** [comment]
Looks like some of your builds may be corrupted. Could you upload the builds folder? It should be under `%userprofile%/Documents/Path of Building`
