### ISSUE TITLE
Crash on loading ("Bad argument","nil","calcActualTriggerRate")

### ISSUE THREAD

**Issue by Stephfra** [PathOfBuildingCommunity/PathOfBuilding#3230]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Loading my build.

### What is the actual behaviour/value?

Pob Gives an Error warning and is unable to open the build.
"Crashes" clicking/loading the build.

### Build code

```shell
XML File of the Build.
Unable to open the build and generate a "default" build link.
https://pastebin.com/n5kU9Taa
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/44267425/136390220-b95a39a5-2532-4142-a6dd-a2cd65a82509.png)

**Comment by Stephfra** [comment]
Hey, first of all thanks, but i am still getting the exact same error with the pob you provided.

**Comment by Stephfra** [comment]
Yea i did something similar, with editing the skill group out of the xml file and it worked, no clue but theres some calculation bug there

**Comment by Nostrademous** [comment]
This should be fixed in `dev` and thus part of next release by #3905
