### ISSUE TITLE
Add support for Soul Eater stacks

### ISSUE THREAD

**Issue by approved** [PathOfBuildingCommunity/PathOfBuilding#3234]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I would like to be able to equip an item that grants Soul Eater and select the number of Soul Eater stacks to apply, but there is currently no support for Soul Eater.

### Describe the solution you'd like

When I equip an item that grants Soul Eater, or put custom text like `You have Soul Eater` or `Grants Soul Eater`, a configuration box for number of Soul Eater stacks appeared

### Describe alternatives you've considered

The functionality can be achieved by adding the custom text for all of the values Soul Eater provides

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4774
