### ISSUE TITLE
Missing/partial stat change tooltips

### ISSUE THREAD

**Issue by coldino** [PathOfBuildingCommunity/PathOfBuilding#3247]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

**Forwarding a bug report from https://github.com/VolatilePulse/PoB-Item-Tester/issues/32 that looks certain to be a PoB bug.**

After importing this build I would expect to see damage-related stat change tooltips on tree nodes and support gems, as has always been the case in the past. Examples are any of the damage-related tree nodes or any of the support gems for Frost Blades. (yes, Frost Blades is the selected skill).

### What is the actual behaviour/value?

After importing this build none of the stat-change tooltips show - this includes nodes on the tree, support gems, and oddly, many of the damage-related stats even from items.

With FullDPS disabled, if you look at the support gems for Frost Blades you would expect to get a tooltip showing the power gained/lost when hovering over the Enabled tickbox, but it isn't present at all.

Enabling Full DPS for Frost Blades allows these tooltips to partially work, but only the Full DPS difference is shown - all the other stats are still missing (average hit and attack rate should change for multistrike for example).

### How to reproduce the issue

1. Import build.
2. Ensure Frost Blades is selected as the main skill.
3. Go to the tree tab and hover over any damage-related node.
3. Go to the skills tab, select Frost Blades and hover over the Enabled flag for the support gems.

### Build code

```shell
https://pastebin.com/cG4Hm3rz
```

**Comment by bit-skipper** [comment]
Hi, 

havent done a full triage, but my first finding is that the condition is being caused by the frostbite skill / ring somehow.

disable the frostbite skill group or remove the ring in the items panel and the problem disappears.

**Comment by QuickStick123** [comment]
The issue with the tree is you have Ctrl + D enable to hide tooltips.
