### ISSUE TITLE
Tranquility / Transfiguration of Soul/Mind/Body

### ISSUE THREAD

**Issue by git42leech** [PathOfBuildingCommunity/PathOfBuilding#329]
Could you please add support for that node so it will show the unallocating text as well?

**Comment by LocalIdentity** [comment]
The node has always been supported, you can only access it by allocating it on a piece of gear

**Comment by git42leech** [comment]
The node is supported but it does not show the stats, you can see the added stats only on the gear. It would be nice to see the stats on the node, so you know exactly how much it is.

**Comment by LocalIdentity** [comment]
The nodes already do what you are asking for

**Comment by git42leech** [comment]
No, it's not showing how much Energy Shield the node is giving from Tranquility. Especially the exact value of added Spell Damage would be interesting.

`additive_energy_shield_modifiers_apply_to_spell_damage_at_30%_value`

**Comment by hammypants** [comment]
Can there be a note in the app that you can only allocate the node via gear, if that's the way it's intended? I assume this because you closed this issue. You can also acquire Transfiguration of the Mind from the tree, and POB doesn't account for any of it after taking the node. @LocalIdentity
