### ISSUE TITLE
Add configuration for hit by attack recently

### ISSUE THREAD

**Issue by lundburgerr** [PathOfBuildingCommunity/PathOfBuilding#3300]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

In 3.16, Wind Dancer have the following stat:
20% less Attack Damage taken if you haven't been Hit by an Attack recently

And there is no configuration for specifying if you were hit by an **attack** specifically.

### Describe the solution you'd like

If you choose wind dancer in 3.16 a checkbox in configuration tab should pop up whether or not you have been hit by an attack recently.

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
