### ISSUE TITLE
Add calculation for attack damage taken

### ISSUE THREAD

**Issue by lundburgerr** [PathOfBuildingCommunity/PathOfBuilding#3301]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

In 3.16, the new wind dancer have the mods:
20% less **Attack Damage taken** if you haven't been Hit by an Attack recently
20% more **Attack Damage taken** if you have been Hit recently

and currently in the calc tab there is no section that differentiates hit damage taken from attack damage taken (or spell damage taken)

### Describe the solution you'd like

In the Calcs tab under Damage Taken change Hit taken to Attack damage taken and Spell damage taken as they can now be differentiated.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3295.
