### ISSUE TITLE
LVL 5 Awakened Curse On Hit Support

### ISSUE THREAD

**Issue by Me1v** [PathOfBuildingCommunity/PathOfBuilding#333]
Hello, 
I noticed that since metamorph league start no one added support for lvl 5 Awakened Curse On Hit.

"Skill functions and interactions
Supported Skills can apply an additional Curse: This stat unlocks at gem level 5."

my PoB version 1.4.157.7 by LocalIdentity's Fork. Thx.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
