### ISSUE TITLE
"100% increased Evasion Rating from your Body Amour" from Evasion Mastery does not get applied

### ISSUE THREAD

**Issue by Kubiboi** [PathOfBuildingCommunity/PathOfBuilding#3365]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When being applied it should increase Evasion by said amount.

### What is the actual behaviour/value?

It does not change anything on the stat sheet or calculation tab

### How to reproduce the issue

Pick the "100% increased Evasion Rating from your Body Amour" Evasion Mastery and look for any changes in evasion.

### Build code

```shell
https://pastebin.com/sdH5RcrG
```

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
