### ISSUE TITLE
Icestorm support for skill damage calculations.

### ISSUE THREAD

**Issue by B3bomber** [PathOfBuildingCommunity/PathOfBuilding#337]
Right now POB does not treat it as a "skill gem" even when gems are socketed into the item that provides the skill. If it's possible to fix that, that'd be awesome.

Bug: Ice Bite is considered a support gem that does not apply to Icestorm. It absolutely does apply in game.

Some info tags to help make the Icestorm "gem": Spell, AOE, Duration, Cold.
For all intents and purposes, the Firestorm gem is a good guide for base tags/abilities if I missed anything. As far as I know, it has the same damage effectiveness modifiers too.

Other notes: Cannot have quality, max level is 1 regardless of any modifiers that I know of.

**Comment by ppoelzl** [comment]
It's correct not to treat Icestorm as a skill gem. It is a skill that is granted by an item, Whispering Ice. There are no other sources to obtain Icestorm and certainly no Icestorm skill gem.
Ice Bite does correctly apply to Icestorm. To support skills granted by items with support gems, the support gems have to be in that same socket group as the granted skill. This does closely follow the way this works in-game.
There is no way to modify Icestorm's level or quality, whether in-game or in PoB. This is also correct.
Note that there is a difference between skills granted by items having 0 innate quality and being unable to have quality. Currently, there is no distinction between these properties in-game and therefore in PoB.
