### ISSUE TITLE
Shield Crush skill numbers are wrong

### ISSUE THREAD

**Issue by Navandis** [PathOfBuildingCommunity/PathOfBuilding#3370]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

As per the patch notes https://www.pathofexile.com/forum/view-thread/3186390#shieldskills , **Shield Crush** should provide _5 to 7 Added Physical Damage per 15 Armour or Evasion Rating on Shield at gem level 20_

### What is the actual behaviour/value?

In the latest POB (2.9.0) the damage at gem **level 20** is still 4 to 6 per 15 Armour or Evasion Rating on Shield (old value)

### How to reproduce the issue

Create a new socket group then add a Shield Crush level 20 gem.

### Build code

```shell
https://pastebin.com/MyBFuBwx
```

### Screenshots

![image](https://user-images.githubusercontent.com/92758164/137804322-15cfa1ae-fb71-4f0c-a7b4-57468087dbfb.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
