### ISSUE TITLE
Safeguard and the spellblock nodes related not working

### ISSUE THREAD

**Issue by Sudd00** [PathOfBuildingCommunity/PathOfBuilding#3380]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Safeguard is a node that should give +8% to all elemental resistance, recover 50 energy shield when you block spell damage and +6% chance to block spell while holding a staff or shield. 
The effects are not applying with staffs or shields and all the notes related are also not working (small spellblock nodes)

### What is the actual behaviour/value?

The only effect working is the elemental resistance one.

### How to reproduce the issue

Just put a staff/shield on the build and select the nodes.

### Build code

```shell
https://pastebin.com/5xEC4i7t
```

**Comment by SaloEater** [comment]
This one is also duplicates https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3359

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
