### ISSUE TITLE
Gravebind Hydrascale Gauntlets not implemented

### ISSUE THREAD

**Issue by marcin7848** [PathOfBuildingCommunity/PathOfBuilding#3384]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Gravebind Hydrascale Gauntlets are not implemented.

### What is the actual behaviour/value?

https://www.reddit.com/r/pathofexile/comments/q8y5s8/try_as_you_like_to_hide_the_blood_on_your_hands/

### Build code

```shell
-
```

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
