### ISSUE TITLE
"Reduced mana reservation" to "Reservation Efficiency" update is not applied to all uniques.

### ISSUE THREAD

**Issue by GloomyC** [PathOfBuildingCommunity/PathOfBuilding#3388]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

As patch notes say
> "If not mentioned below, all sources that previously provided reduced reservation, including for specific skills or types of skills, now provide increased mana reservation efficiency at twice the value of the reduced reservation they used to give."

"Alpha's Howl" unique item, should have stat "16% increased Mana Reservation Efficiency of Skills"

### What is the actual behaviour/value?

When selecting "Alpha's Howl" unique item, "8% reduced Reservation of Skills" stat can be seen.
Same thing with "Saqawal's Nest", and probably more...
("Skyforth" boots are converted so something was done but not everywhere)

### How to reproduce the issue

- Go to Items tab
- Add "Alpha's Howl" unique helmet to your build.
- "reduced Reservation of Skills" is still on the item.

### Build code

```shell
https://pastebin.com/wR8JB3Ck
```

### Screenshots

![image](https://user-images.githubusercontent.com/23178468/137818884-f605d4ea-aea0-4d15-8423-0f1073094a01.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
