### ISSUE TITLE
[2.9.0]Solipsism should not remove the intelligence bonus to mana

### ISSUE THREAD

**Issue by Yoshiitsune** [PathOfBuildingCommunity/PathOfBuilding#3389]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The keystone Solipsism removes the Intelligence attribute inherent bonus to Energy Shield (Every 10 intelligence grants 2% increased maximum energy shield.)

### What is the actual behaviour/value?

The current Solipsism keystone removes the Intelligence attribute inherent bonus to Energy Shield AND Mana (Every 10 intelligence grants an additional 5 mana.)

### How to reproduce the issue

- Take Solipsism on the tree with any amount of intelligence
- See Total Mana being reduced.

### Build code

```shell
https://pastebin.com/FfLR03sg
```

### Screenshots

![image](https://user-images.githubusercontent.com/3777266/137819552-e591f7d4-5cdc-4a03-957e-758e05b84781.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
