### ISSUE TITLE
Reigning Veteran (glad asc. node) doesn't give base armor or evasion

### ISSUE THREAD

**Issue by JustinStitt** [PathOfBuildingCommunity/PathOfBuilding#3406]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Reigning Veteran should give armor and evasion based on attack block chance.

### What is the actual behaviour/value?

Does not give either.

### How to reproduce the issue

Spec Glad, get some block chance, spec Reigning Veteran

### Build code

```shell
https://pastebin.com/YmFKTz1S
```

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
