### ISSUE TITLE
"Skill Points Gained When Unallocating" passive hover text does not account for mastery

### ISSUE THREAD

**Issue by randombk** [PathOfBuildingCommunity/PathOfBuilding#3412]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

In the example below, the hover text should say 4 (three nodes plus the mastery)

![image](https://user-images.githubusercontent.com/1633923/137843677-f1827eb7-6233-43d3-a1d1-084c46c61907.png)

### What is the actual behaviour/value?

The hover text lists '3' rather than '4'

### Build code

```shell
https://pastebin.com/sV9hBA3V
```

**Comment by Voronoff** [comment]
The notable sees the mastery node as depending on it, but other nodes do not. We may also want to give passive masteries a red tint + highlight when hovering over the nodes they depend on, like other nodes have.

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
