### ISSUE TITLE
Aura effect affects Skitterbots when it shouldn't

### ISSUE THREAD

**Issue by jwfiredragon** [PathOfBuildingCommunity/PathOfBuilding#342]
Confirmed by viperesque that aura effect does not affect Skitterbots. However increasing aura effect doesn't seem to do anything for Skitterbots anyways (minion stats and more trap/mine damage granted stay the same when aura effect is increased), so it's not a major issue.

![image](https://user-images.githubusercontent.com/6947594/76175647-cd7a6680-616a-11ea-8e96-02680320e94a.png)

![image](https://user-images.githubusercontent.com/6947594/76175684-fac71480-616a-11ea-95f6-11fdc4c0ef6d.png)

**Comment by PJacek** [comment]
This is a slightly misleading display issue happening because Summon Skitterbots has the Aura tag. If you check "Show Minion Stats" you'll notice the minions have no aura effect. The summoning skill grants no auras (trap and mine damage is a buff not an aura) so it has no real effect.
