### ISSUE TITLE
Lua Error Forces Restart on Swapping Gems

### ISSUE THREAD

**Issue by Rowlsie** [PathOfBuildingCommunity/PathOfBuilding#343]
Just today I was updating a build when this happened:
![Path_of_Building_MZU50rnKix](https://user-images.githubusercontent.com/61955329/76177450-00bb0500-6200-11ea-9f7a-380aefef0b38.png)
Followed by (When pressing enter):
![Path_of_Building_GH75beWBWj](https://user-images.githubusercontent.com/61955329/76177499-28aa6880-6200-11ea-8d12-6ca9a7092f86.png)
On this screen I have to restart.

This is happening when I try to click specifically on the 3rd, 4th, 5th or 6th gem slot on my 6L setup in the skills section. I can change all of my other gems fine and even the two first ones in that setup but that first Lua error appears the instant i click on any of the previously mentioned slots. In case its relevant to the gems themselves they are: Controlled Destruction, Spell Echo, Power Charge on Crit, Inspriation socketed in that order after Vaal Arc and Arcane Surge. 

To be more specific this happens when clicking on a line in my 6L setup to change a gem. The drop down for gem select never appears.

also I should mention this because you can't see it in the screenshot but sometimes when this happens the "Enable Summon Lightning Golem" checkbox weirdly appears underneath the gem I clicked on even though that gem isn't in this link.

I'm not sure if this is an issue with PoB itself or this fork update but I've never had any issues with PoB before downloading this fork.

**Comment by Rowlsie** [comment]
Update: Reinstalled PoB and still having this issue. Would be great to have a fix for it since I can't update my gem links at all

**Comment by LocalIdentity** [comment]
Same error from here https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/298
