### ISSUE TITLE
Chaos Innoculate Bug

### ISSUE THREAD

**Issue by aliuznoratiuz** [PathOfBuildingCommunity/PathOfBuilding#3430]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Chaos Innoculate cause Immune to chaos damage, filling the chaos resistance with 100%, this mechanic consist in increased maximum chaos resistance to 100% and fulfill this resistance.

### What is the actual behaviour/value?

Is not showing maximum 100% chaos resistance and fill this stat, Still convert life to 1 but does not show the chaos resistance in 100% value, Does not increase the maximum chaos resistance base and is not providing the requested chaos resistance to fill it.

### How to reproduce the issue

Pick Chaos Innoculate on the tree

### Build code

```shell
https://pastebin.com/Hf1mbT1j
```

### Screenshots

![image](https://user-images.githubusercontent.com/92788800/137888451-309a1748-875b-4386-b77f-e477e70bbc2e.png)
![image](https://user-images.githubusercontent.com/92788800/137889122-33cee538-d801-4ced-816f-2787d599a060.png)

**Comment by LocalIdentity** [comment]
Chaos Inoculation does not grant your resistances but instead grants you immunity to damage, as of 3.16 this is how it will be displayed in game too
