### ISSUE TITLE
Vengeful Commander on Large Cluster Jewels bricks the jewel

### ISSUE THREAD

**Issue by Cantacuzenus** [PathOfBuildingCommunity/PathOfBuilding#3432]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Vengeful Commander should appear as a notable on a large cluster jewel when on the item.

### What is the actual behaviour/value?

the cluster jewel fails to be recognized as a cluster jewel.

### How to reproduce the issue

Import any large cluster jewel into your tree.

### Build code

```shell
v2.10.0
```

### Screenshots

![Capture](https://user-images.githubusercontent.com/92792037/137897607-4ef979cc-7aa6-439d-8bd2-db3247911e11.PNG)

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
