### ISSUE TITLE
Correct General's Cry DPS  

### ISSUE THREAD

**Issue by Antorell** [PathOfBuildingCommunity/PathOfBuilding#3434]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

The DPS calculation of General's cry is incorrect. 

### Describe the solution you'd like

The DPS calculation of General's cry is still incorrect with version 2.10. There's a pull request here (Refactor General's Cry #3220 ) with a fix, but it hasn't been merged yet. 

Is it possible to have this pull merged for a coming release?

**Comment by Lothrik** [comment]
This should be fixed in the next release as #3220 was merged a week ago.
