### ISSUE TITLE
Global Damage over Time Multiplier suffixes to items as per Patch notes

### ISSUE THREAD

**Issue by apexbabo** [PathOfBuildingCommunity/PathOfBuilding#3439]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Hey, it would be sick if you could add the announced DOT Multiplier mods for items, namely for weapons, amulets and rings.

- There are now **5 tiers** of the Global Damage over Time Multiplier Suffix modifier that rolls **on all Weapons**, going up to **26% on one-handed Weapons, and 45% on two-handed Weapons.**
- There are now **5 tiers** of the Global Damage over Time Multiplier Suffix modifier that rolls **on all Amulets** as part of their base modifier pool, **going up to 26%**.
- The **Influence modifiers on Rings** that had a chance to Ignite/Freeze/Shock as well as some flat Damage have been changed. They no longer provide a chance to apply the Ailment, but provide a lot more added Damage instead. **The Fire version rolls up to 23-30 to 47-54 Fire Damage against Ignited Enemies, the Cold version rolls up to 20-26 to 41-48 Cold Damage against Chilled or Frozen Enemies, and the Lightning version rolls up to 4-8 to 82-86 Lightning Damage against Shocked Enemies.**
- **Essence of Delirium** no longer rolls “Hexes you inflict have +5 to maximum Doom” on Rings, or +10% to Damage over Time Multiplier on Amulets. Instead, it **now rolls +12-15% to Damage over Time Multiplier on Rings**, and “Hexes you inflict have +10 to maximum Doom” on Amulets.
- Fire, Cold, Physical, and Chaos Damage over Time Multiplier modifiers **on Jewels** **now have values of +6-8% (previously +3-4%)**.
- There is a new **Global Damage over Time Multiplier Suffix** modifier that can roll **on all Jewels with a value of +4-6%**.
- Damage over Time Multiplier modifiers on Influenced Gloves and Amulets now roll values up to +16-20% at its highest tier (previously +13-16%).

### Describe the solution you'd like

Implement this and other mod changes from the patch notes

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
