### ISSUE TITLE
Support Seeker Runes Notable?

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#344]
Now that PR #328 is in dev and we have Brand Attachment Range accounted for, do we want to add support for Seeker Runes?

![SeekerRunes](https://user-images.githubusercontent.com/1735956/76207719-b2444100-61d4-11ea-8149-470b81f7727c.png)

**Comment by ppoelzl** [comment]
If anything, only for completion's sake. It's not a very useful mod to have simulated.
On an unrelated note: We don't know what the brand's base attachment range is.

**Comment by Nostrademous** [comment]
I can see them adding a "% increased damage per 100 units of brand attachment range travel" in the future. :P

**Comment by LocalIdentity** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/461
