### ISSUE TITLE
Instead of dropdowns for masteries, use a list

### ISSUE THREAD

**Issue by ufuksarp** [PathOfBuildingCommunity/PathOfBuilding#3440]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Current implemention of selecting masteries is tedious and unintiutive.

### Describe the solution you'd like

Use an open list, not a dropdown. Click the mastery you want, and the list goes away. Clicking outside the list makes it disappear. Get rid of 2 clicks per one mastery selection.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by pHiney** [comment]
I agree, the dropdown doesn't show everything quickly/easily. I'll look over the code over the next day and see what i can come up with. Should not be too hard.

**Comment by Antorell** [comment]
That list looks good. The current implantation on a 4K monitor with scaling to 175% looks like a PoB for the ants.

**Comment by pHiney** [comment]
seems Voronoff has done this already #3476

**Comment by ufuksarp** [comment]
> "Can it be one left click to open the list and one left click to select and assign" yes it could, I'd be concerned for usability and accidentally assigning things. I think there needs to be an element of surety when using the mouse. "scrollbar". I'm working on that cause i don't like it either - but IRL i have other things to do :-)

I don't think that's a big deal to let the user learn. It's much faster to do it this way instead of bonus clicks which really has no use.

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
