### ISSUE TITLE
Purity Of Elements Skill gem not updated

### ISSUE THREAD

**Issue by ForsakenDTK** [PathOfBuildingCommunity/PathOfBuilding#3456]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The new Purity Of Elements skill gem should have 50% mana reservation and should grant Elemental Ailment immunity!

### What is the actual behaviour/value?

Purity Of Elements skill gem has the old values 35% reservation and no elemental ailment immunity!

### Build code

```shell
https://pastebin.com/erF2nPmV
```

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
