### ISSUE TITLE
[2.10.0] Blade Blast + Unleash Support calculations are not showing correct values when the number of blades is changed

### ISSUE THREAD

**Issue by jezztify** [PathOfBuildingCommunity/PathOfBuilding#3469]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

It should be able to show the correct values when changing the number of blades for Blade Blast if it is linked with Unleash Support

### What is the actual behaviour/value?

Below screenshots show the same values between 1 vs 50 blades
![image](https://user-images.githubusercontent.com/13676977/138025826-6af6c920-73b1-487b-974a-f600001e40d9.png)
![image](https://user-images.githubusercontent.com/13676977/138025834-87a54d00-ae6d-4b09-9bf4-4f088c492ec3.png)

### How to reproduce the issue

1. Add Blade Blast as a skill
2. Link it to Unleash Support
3. Change the number of blades

### Build code

```shell
https://pastebin.com/9v1jGAs8
```

**Comment by LocalIdentity** [comment]
No longer an issue
