### ISSUE TITLE
Support for Unleash burst DPS

### ISSUE THREAD

**Issue by LocalIdentity** [PathOfBuildingCommunity/PathOfBuilding#347]
Unleash does not currently offer the ability to view the burst DPS from a selected number of seals being used at a time

**Comment by Reithan** [comment]
Additionally, it would be nice if it could calulate overall DPS from unleash's pseudo-increase to cast speed for sustained DPS as well.

**Comment by Cyan101** [comment]
*Bump* With the new league bringing in a bunch of exsang/reap + unleash builds, definitely a nice to have!

**Comment by Reithan** [comment]
Pretty please?
