### ISSUE TITLE
Elemental Ailment Duration on you affects bleed and poison duration

### ISSUE THREAD

**Issue by mlfickes** [PathOfBuildingCommunity/PathOfBuilding#3471]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The stat "reduced Elemental Ailment Duration on you" (as found on the notable Anointed Flesh) should not impact the duration of bleed or poison in the calcs tab.

### What is the actual behaviour/value?

The stat "reduced Elemental Ailment Duration on you" is reducing the duration of bleed and poison in the calcs tab. However, the similar stat "reduced Duration of Elemental Ailments on you", found on the keystone Solipsism, functions as expected and does not modify the duration of bleed or poison.

### How to reproduce the issue

1. Allocate "Anointed Flesh" notable.
2. Switch to Calcs tab
3. Check "Other Ailment Defences" section for bleed and poison duration

### Build code

```shell
https://pastebin.com/gYd2bZms
```

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
