### ISSUE TITLE
Enemy is Crushed and Physical Damage Reduction with Bleed.

### ISSUE THREAD

**Issue by Ahmad3223** [PathOfBuildingCommunity/PathOfBuilding#3481]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Crush enemies is added on the passive tree from the Vanquisher passive node and from Awakened Brutality Support.

### Describe the solution you'd like

Adding a check box in the effective DPS - is the enemy Crushed.

### Describe alternatives you've considered

Automatic calculation for overwhelm physical damage reduction with spread sheet on the Calculations page to see how much we need to get enemies pdr to 0% since pdr dont go nigative.

Regarding Enemy is crushed, I prefer to add a check box in the effective dps and to be treated the same why like Unnerve or Intimidate.

### Additional context

This is more of a clarification for the lack of full knowledge in the game.

I was working on a bleed build on pob, as far as i know physical damage reduction doesn't affect bleeding ailment and when every i take overwhelm physical damage reduction nodes, my bleed damage dont increase.

I did some reading and most of the resources link PDR to hits not to ailments, but if i increased the enemy pdr in maps modifiers my bleed damage is reduced massively and yet any node to overwhelm that pdr dont make any deference.

I hope you can clarify this point, if bleed is not affected by enemy pdr then it shouldn't reduce the damage in pob, and if does then overwhelm nodes dont reduce enemy pdr, or most likely i don't know what am talking about.

**Comment by LocalIdentity** [comment]
Fixed in 2.11.0
