### ISSUE TITLE
Masteries don't reset properly upon tree reset

### ISSUE THREAD

**Issue by yupitsnotme** [PathOfBuildingCommunity/PathOfBuilding#3484]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I reset the tree I expect the tree to be completely reset and all masteries being available to be chosen.

### What is the actual behaviour/value?

When I reset the tree I expect the tree to be completely reset but upon checking masteries, some of them are not in the list to be chosen.

### How to reproduce the issue

-Choose a mastery (Eg critical mastery, 150% increased crit chance on full life enemies)
-Select Reset and confirm
-Go to a DIFFERENT mastery node (i.e another critical mastery node)
- With no points at all allocated in the tree you can see the same selected nodes prior to reset have not been reset

### Build code

```shell
https://pastebin.com/E6HFtRXM
```

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
