### ISSUE TITLE
Reservation mastery doesnt work properly

### ISSUE THREAD

**Issue by ForsakenDTK** [PathOfBuildingCommunity/PathOfBuilding#3488]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

8% increased damage for each of your aura or herald skills affecting you
Auras from your skills have 15% increased effect on you

### What is the actual behaviour/value?

Both Modifiers doesnt add anything

### How to reproduce the issue

1- reserve couple of auras (with discipline u can check if the energy shield scales if the  15% increased effect of aura works reserving 5 auras for example should provide u 40% increased damage)
2 - chose a skill
3 - allocate the reservation mastery
   3.1 8% increased damage for each of your aura or herald skills affecting you
   3.2 Auras from your skills have 15% increased effect on you

### Build code

```shell
https://pastebin.com/nru4ix9y
```

**Comment by etojuice** [comment]
`Auras from your skills have 15% increased effect on you` has been fixed with this MR #3407 
`8% increased Damage for each of your Aura or Herald Skills affecting you` fix awaiting approval #3353

**Comment by LocalIdentity** [comment]
Fixed in 2.12.0
