### ISSUE TITLE
Volley Fire jewel's Attributes in Radius counts only allocated ones. Is it correct?

### ISSUE THREAD

**Issue by Eqatrpfvvzzih** [PathOfBuildingCommunity/PathOfBuilding#350]
If I place a Wolley Fire jewel, and hover the mouse, it shows "Attributes in Radius: 30 Dex".
30 is less than the total number of dexterity nodes in radius.
30 is the number of the **allocated** dexterity nodes.
Is this behaviour correct?

Other jewels, for example Fight for Survival, behaves (in PoB) differently. For Fight for Survival, Attributes in Radius shows (counts) all the dexterity nodes (both allocated and unallocated).

I have not investigated all the (other) jewels.

I now tried to search in pathofexile.gamepedia.com, but "Wolley Fire" cannot found... Does exist this jewel at all?

**Comment by BassOfBass** [comment]
You couldn't find it because it's called Volley Fire.
