### ISSUE TITLE
Unseen Strike trigger support

### ISSUE THREAD

**Issue by zmike** [PathOfBuildingCommunity/PathOfBuilding#3512]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Hidden Blade triggers Unseen Strike every 0.5s while phasing, but this trigger/cooldown rate is not correctly calculated.

### What is the actual behaviour/value?

The trigger rate should correlate to the 0.5s cooldown if phasing is enabled, but instead it starts at 1.0 and doesn't scale with cooldown recovery.

### How to reproduce the issue

* Add Hidden Blade to build
* Enable phasing
* Attack rate is not correctly updated

### Build code

```shell
https://pastebin.com/JQ5KtHMK
```

**Comment by zmike** [comment]
Gem DPS sorting also seems to be broken with this skill.

**Comment by QuickStick123** [comment]
Might be fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4599 @Paliak ?

**Comment by Paliak** [comment]
It should be correctly handled in #4599
![obraz](https://user-images.githubusercontent.com/91493239/220343528-f5fbbcb6-238e-4fd5-8a6e-11089d31fd62.png)

![obraz](https://user-images.githubusercontent.com/91493239/220343692-6c7afb2e-e81a-45cd-836a-d91b44fd28e1.png)

![obraz](https://user-images.githubusercontent.com/91493239/220343778-59d5e77e-6ad8-4d82-a3e3-ec048efbeb01.png)

**Comment by zmike** [comment]
Great, thanks!

**Comment by QuickStick123** [comment]
It hasn't been merged so will keep this open until.

**Comment by Paliak** [comment]
Closing as trigger rework has been merged into master.
