### ISSUE TITLE
Having an opt-in to the dev branch would be better than the beta branch

### ISSUE THREAD

**Issue by Morilli** [PathOfBuildingCommunity/PathOfBuilding#3539]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

The beta branch seems to consistently be less updated than either the master branch or the dev branch, and therefor doesn't make much sense as an opt-in.

### Describe the solution you'd like

The dev branch is the main "working" branch, and seems like it would make much more sense to opt-in for updates to.
Especially in times like a new league start, having an always up-to-date version of PoB can be very useful. Currently, the only way to achieve this is to use a local git version and checking out the dev branch.

**Comment by Nostrademous** [comment]
This was discussed internally by the team and we decided that it would create a larger headache for us than we could manage with our team size. It's not a bad idea, but we don't have cycles to guide and mentor people in how to work with Git and Pull Requests and merges on top of constant feature development and bug squashing. 

Instead, we hope to have a more regular release cycle and to utilize Beta more for larger feature testing.

**Comment by Nostrademous** [comment]
Simply b/c the `dev` branch is often-times unstable as a result of multiple PRs being merged that work independently on things that don't create merge conflicts but do cause functionality to break. We fix those as we encounter them but predict a large amount bug reports and issue being created by the user base. We already have a backlog of over 500 issues to resolve.

As you know, you can already use `dev` by simply creating a fork and launching PoB from the source code yourself. That's a barrier to entry that we feel is appropriate.

We are happy to hear other opinions on the topic, and trust me .. I constantly harass the maintainers to merge more PRs more frequently.

**Comment by Wires77** [comment]
> Having more frequent beta updates would probably work (if they were frequent enough, like once a week), but I can definitely see THAT requiring more effort.

On top of what @Nostrademous said, I _just_ pushed a change that makes the beta branch much more stable and it should update weekly again (if dev has changes, of course).
