### ISSUE TITLE
[2.10.0] Flask suffix modifier "of Acceleration" does not increase Attack Rate

### ISSUE THREAD

**Issue by jezznar** [PathOfBuildingCommunity/PathOfBuilding#3547]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

It should increase the attack rate as stated in %

### What is the actual behaviour/value?

It does not increase Attack Rate

### How to reproduce the issue

1. Add a flask
2. Add `of Acceleration` as `Suffix` modifier
3. Check attack rate

### Build code

```shell
https://pastebin.com/P5hKUa67
```

### Screenshots

![image](https://user-images.githubusercontent.com/13676977/138380533-4bce7b3d-3a49-4a0a-8f41-1187ab1b82f3.png)
![image](https://user-images.githubusercontent.com/13676977/138380563-11548069-30a7-466e-9bdc-dd6e17ec768a.png)

**Comment by Lothrik** [comment]
Your 3rd and 5th flask have the exact same suffix, they don't stack.

**Comment by jezznar** [comment]
@Lothrik Oh I thought they do. Thanks. I'll close this issue now.
