### ISSUE TITLE
Spell suppression and EHP

### ISSUE THREAD

**Issue by ocombe** [PathOfBuildingCommunity/PathOfBuilding#3562]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Spell suppression should count for EHP

### What is the actual behaviour/value?

Adding spell suppression doesn't change EHP

### Build code

```shell
https://pastebin.com/CfwrNPW6
```

**Comment by LocalIdentity** [comment]
Fix in 2.12.0
