### ISSUE TITLE
2.11 release calculate's storm brand's 'More Damage with hits' as Increased

### ISSUE THREAD

**Issue by Thanat0sNihil** [PathOfBuildingCommunity/PathOfBuilding#3574]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The Skill Storm Brand deals 80-130% More Damage with hits against branded enemies

### What is the actual behaviour/value?

This modifier is instead calculated as an increase to Storm Brand's hit damage.

### How to reproduce the issue

1.Open PoB release 2.11
2. Select Storm Brand under the skills tab
3. View Skill Hit Damage calculation table under the Calcs tab

### Build code

```shell
https://pastebin.com/0gYgZSVa
```

### Screenshots

![image](https://user-images.githubusercontent.com/37569877/138543429-2af45b63-f5a9-4349-941e-9ca0fb5bfd2b.png)

![image](https://user-images.githubusercontent.com/37569877/138543436-1b9b40ef-65d6-467c-a6df-2b2d0d90765b.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.12
