### ISSUE TITLE
The new wording of triggered Assassin's Mark isn't coded in

### ISSUE THREAD

**Issue by SuperJelle** [PathOfBuildingCommunity/PathOfBuilding#3581]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

To work as before

### What is the actual behaviour/value?

Doesn't work because the wording has changed.

### How to reproduce the issue

I assume it's an easy fix, just add support for the slight rewording.

### Build code

```shell
CanIpostafakebuildcodehere
```

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3680.
