### ISSUE TITLE
Barrage "support" is missing 2x with the same name "barrage" one is missing "support"

### ISSUE THREAD

**Issue by Mcah500** [PathOfBuildingCommunity/PathOfBuilding#3582]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Barrage "support" is missing 2x with the same name "barrage" one is missing "support"

### What is the actual behaviour/value?

Barrage "support" is missing 2x with the same name "barrage" one is missing "support"

### How to reproduce the issue

Barrage "support" is missing 2x with the same name "barrage" one is missing "support"

### Build code

```shell
Barrage "support" is missing 2x with the same name "barrage" one is missing "support"
```

### Screenshots

![image](https://user-images.githubusercontent.com/13663917/138572747-676d5696-52c0-4b7f-9dd9-03c3f2cb4979.png)

**Comment by Wires77** [comment]
Duplicates #1083
