### ISSUE TITLE
Aura efficiency impacting life reservation

### ISSUE THREAD

**Issue by emiliorf2** [PathOfBuildingCommunity/PathOfBuilding#3598]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Per 3.16 update, skill tree reservation efficiency shouldn't affect life reservation of auras, usign arrogance for eaxample

### Describe the solution you'd like

updated calculation for life reservation using only valid interactions

**Comment by LocalIdentity** [comment]
Reservation efficiency does affect life reservation, mana reservation efficiency does not. I will reopen the issue if you provide more details to show a bug
