### ISSUE TITLE
SRS was changed to 100% phys instead of 100% fire

### ISSUE THREAD

**Issue by rcpd** [PathOfBuildingCommunity/PathOfBuilding#3617]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

100% fire conversion

### What is the actual behaviour/value?

SRS show 100% physical damage in skill hit tab, supports like elemental damage with attacks have no effect.

### How to reproduce the issue

Repro'd with fresh/empty pob and only SRS skill.

### Build code

```shell
https://pastebin.com/xvP1J407
```

**Comment by Hapseleg** [comment]
The change can be found under the spoiler "Elemental Damage over Time" https://www.pathofexile.com/forum/view-thread/3186390#elementaldamageovertime

> Summoned Raging Spirits now convert all of their Damage to Fire Damage.

**Comment by Lothrik** [comment]
Fixed by #3808.
