### ISSUE TITLE
Impresence "curse casted as aura has no mana reservation" does not work

### ISSUE THREAD

**Issue by khanhtuonghot** [PathOfBuildingCommunity/PathOfBuilding#3619]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I use blasphemy support with flammability with flame impresense equipped, I expect the skill to not reserve mana.

### What is the actual behaviour/value?

When I use blasphemy support with flammability with flame impresense equipped, the skill still reserves mana.

### How to reproduce the issue

1. equip flame impresense
2. equip flammability with blaspheme support

### Build code

```shell
https://pastebin.com/SER6HMdT
```

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
