### ISSUE TITLE
Twin Terrors notable causes error

### ISSUE THREAD

**Issue by Challalala** [PathOfBuildingCommunity/PathOfBuilding#3645]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

To save build.

### What is the actual behaviour/value?

Trying to save build and it will not save until I remove notable from passive tree.

### How to reproduce the issue

Import pastebin into PoB and allocate twin terrors then attempt to save.

### Build code

```shell
https://pastebin.com/jCBthbBw
```

### Screenshots

![image](https://user-images.githubusercontent.com/93315621/139220225-f1daeaec-56b4-46f0-a597-6bb6879d9234.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
