### ISSUE TITLE
Small cluster with Effect of your Curses

### ISSUE THREAD

**Issue by Freod** [PathOfBuildingCommunity/PathOfBuilding#3647]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I put in a small cluster with curse I should see a passives. 

### What is the actual behaviour/value?

When I put in a small cluster with curse I not see a passives. 

### How to reproduce the issue

You need to craft or copy item from game/trade site and put it in socket then it works like normal jewel(gain nothing), should work like cluster (gain passives).

### Build code

```shell
https://pastebin.com/RP7WrWpv
```

### Screenshots

![image](https://user-images.githubusercontent.com/24257186/139237656-36cb6476-b281-44cf-a6d2-6e5fc9463e5b.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
