### ISSUE TITLE
+1 to socket active skills gems on sacrifical garb not working

### ISSUE THREAD

**Issue by leopandolfo** [PathOfBuildingCommunity/PathOfBuilding#3648]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When adding +1 to socketed active skill gems on a sacrifical garb while using Vaal Blight you expect to get extra damage and level of the gem.

### What is the actual behaviour/value?

If you take out the mod it doesn't change tha gem stats

### How to reproduce the issue

Craft a sacrifical garb
Socket Vaal Blight
Include the +1 to active skill gems

### Build code

```shell
https://pastebin.com/wr0TH86F
```

### Screenshots

![image](https://user-images.githubusercontent.com/93321506/139239552-7539ed16-82f2-4840-b10d-008b086ced0c.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
