### ISSUE TITLE
Inspired Learning Affixes (Description) Missing

### ISSUE THREAD

**Issue by Glaringsoul** [PathOfBuildingCommunity/PathOfBuilding#3664]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The Jewel should have

> With 4 Notables Allocated in Radius, When you Kill a Rare monster, you gain 1 of its Modifiers for 20 seconds

Written in its Description, and should display in the POB whether it is active or not...

### What is the actual behaviour/value?

When trying to add Inspired Learning from the Unique List in the Items Tab, the Jewel is missing the Affixes (description) which is reflected both under the items tab AFTER adding it, and on the tree when added in a jewel socket (doesn't matter which one, all are affected).

### How to reproduce the issue

1. Go Look up "Inspired Learning" from the List of uniques
2. see that it's description is missing
3. add it to the item list, and see that it's description is still missing
4. add it to the tree in a socket. See that it's description is also missing

### Build code

```shell
No idea what belongs here, but the version I am running is 2.12.3 (current Stable)
```

### Screenshots

![pobbug](https://user-images.githubusercontent.com/28360404/139453874-79a2138b-b35f-4632-9cec-6e575125e97c.png)

**Comment by Nostrademous** [comment]
Fixed in upcoming 2.14 release
