### ISSUE TITLE
Importing scourged helmet crashes PoB, probably some mods on it are the issue

### ISSUE THREAD

**Issue by lupuleasa-core** [PathOfBuildingCommunity/PathOfBuilding#3665]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I want to import this helmet, and it crashes

Item Class: Helmets
Rarity: Rare
Kraken Dome
Close Helmet
--------
Armour: 138 (augmented)
--------
Requirements:
Level: 46
Str: 100
Int: 61
--------
Sockets: R-R-R-B 
--------
Item Level: 27
--------
+25 to maximum Life (scourge)
-20% to Lightning Resistance (scourge)
--------
{ Prefix Modifier "Lacquered" (Tier: 8) — Defences }
+6(6-12) to Armour
{ Suffix Modifier "of the Drake" (Tier: 6) — Elemental, Fire, Resistance }
+23(18-23)% to Fire Resistance
{ Suffix Modifier "of Light" (Tier: 2) — Attack }
14(12-15)% increased Global Accuracy Rating
10% increased Light Radius
{ Suffix Modifier "of the Lizard" (Tier: 8) — Life }
Regenerate 2.1(2.1-8) Life per second
--------
Corrupted
--------
Scourged

### What is the actual behaviour/value?

it crashes with this message

https://i.imgur.com/VINJ8JP.png

### How to reproduce the issue

Import this paste 

Item Class: Helmets
Rarity: Rare
Kraken Dome
Close Helmet
--------
Armour: 138 (augmented)
--------
Requirements:
Level: 46
Str: 100
Int: 61
--------
Sockets: R-R-R-B 
--------
Item Level: 27
--------
+25 to maximum Life (scourge)
-20% to Lightning Resistance (scourge)
--------
{ Prefix Modifier "Lacquered" (Tier: 8) — Defences }
+6(6-12) to Armour
{ Suffix Modifier "of the Drake" (Tier: 6) — Elemental, Fire, Resistance }
+23(18-23)% to Fire Resistance
{ Suffix Modifier "of Light" (Tier: 2) — Attack }
14(12-15)% increased Global Accuracy Rating
10% increased Light Radius
{ Suffix Modifier "of the Lizard" (Tier: 8) — Life }
Regenerate 2.1(2.1-8) Life per second
--------
Corrupted
--------
Scourged

### Build code

```shell
the build is fresh, just click new
```

### Screenshots

https://i.imgur.com/l9AXDE4.png

**Comment by lupuleasa-core** [comment]
Ok. I used ctrl c normally, but because I had Awakened poe trader it
made it advanced

On October 29, 2021, Wires77 ***@***.***> wrote:
> PoB doesn't yet support copying with Ctrl-Alt-C. If you copy the
> helmet with Ctrl-C it will import fine
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3665#issuecomment-
954824556>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABLIRUGLVSTC3Q2G6W5UU33UJK24ZANCNFSM5G7RPBRQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by Wires77** [comment]
Ah, good to know that's where they're coming from.  We've gotten a few of these lately.  I'll close this issue for now, but sounds like we should prioritize supporting that format soon, then.

**Comment by zao** [comment]
Awakened PoE Trade issues a Ctrl+Highlight+C whenever it requests information from the game in response to a user keyboard shortcut.

It should not interfere with regular Ctrl+C operation in any way unless you're actually using that combination as an APT shortcut, pressing Ctrl+C alone should make a regular game item copy.
