### ISSUE TITLE
PoB spectre library is missing popular Scourge spectres

### ISSUE THREAD

**Issue by cdrg** [PathOfBuildingCommunity/PathOfBuilding#3668]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

These are currently popular:
Demon Harpy (debuff that increases enemy phys damage taken)
Pale Seraphim (defuff that increases damage taken and decreases action speed)
Pale Angel (dps single target beam)
Demon Herder (dps physical)

Possibly more I'm missing.

### Describe the solution you'd like

Add Scourge spectres

**Comment by LocalIdentity** [comment]
Added in 2.13.0
