### ISSUE TITLE
Bug with Arrogance

### ISSUE THREAD

**Issue by joca-bt** [PathOfBuildingCommunity/PathOfBuilding#3671]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

See the box below.

### What is the actual behaviour/value?

Arrogance appears to be bugged: having it at 0% or 20% quality is not affecting DPS.

In the build attached I have a Herald of Purity linked with Arrogance at 20% quality. Changing the quality of Arrogance to 0% doesn't affect DPS (when it should). Changing the Arrogance to anomalous with 20% quality greatly affects DPS (way more than expected ~200k). Changing the anomalous Arrogance to 0% quality reverts the DPS loss of the previous step.

[Exsanguinate.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/7446485/Exsanguinate.zip)

### Build code

```shell
See attached zip.
```

**Comment by SaraTri** [comment]
Herald of Purity doesn't have an aura tag so I'm guessing it wouldn't work with the aura effect from arrogance.
Have you tested ingame if this increases damage? Might just me not knowing game mechanics.

**Comment by LocalIdentity** [comment]
What Sara said above is correct, Herald of Purity is a "herald' skill not an Aura. It does not receive bonuses to aura skills

**Comment by joca-bt** [comment]
I agree, but then the behaviour of POB is not correct. The gem being at 0% or 20% quality should result in no changes, which is not the case as I described above.

**Comment by Lilylicious** [comment]
The behaviour is correct.

Herald is not an aura, but it is a reservation skill.
Arrogance can support the herald, since it's a reservation skill.
Arrogance gives aura effect, which does nothing to Herald because it is not an aura skill. That also applies to the default quality.
Anomalous Arrogance gives increased damage by supported skills. The herald is supported, so is affected by this.

**Comment by joca-bt** [comment]
>Anomalous Arrogance gives increased damage by supported skills.

It does not, it does "Supported Skills have 0.1% reduced Life Reservation".

**Comment by PJacek** [comment]
Anomalous Arrogance grants Life Reservation Efficiency which makes HoP reserve less than 50% of your life. You lose 30% more Spell Damage from Pain Attunement because you are no longer on Low Life

**Comment by joca-bt** [comment]
Thanks, I forgot about that! I do have petrified blood but forgot HP goes to full life in POB unless I check the specific low-life box.
