### ISSUE TITLE
Fleshcrafter not calculating DPS Boost

### ISSUE THREAD

**Issue by Cyan101** [PathOfBuildingCommunity/PathOfBuilding#3673]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Fleshcrafters preview panel/item hover doesnt show the DPS boost that ignoring Conq/Sirus Elemental resists should have

### What is the actual behaviour/value?

Just doesnt seem to calculate any DPS boosts

### How to reproduce the issue

Select Fleshcrafter from the unique list in items

### Build code

```shell
https://pastebin.com/H1XvQVcP
```

### Screenshots

![image](https://user-images.githubusercontent.com/2821230/139540770-35fe21ca-5f94-4b24-8597-825292f118ea.png)

**Comment by Peechey** [comment]
Red text is not yet supported in PoB. This is a feature ask.
