### ISSUE TITLE
Error when saving a build after converting the tree to the 3.16 tree. 

### ISSUE THREAD

**Issue by Antorell** [PathOfBuildingCommunity/PathOfBuilding#3674]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Able to save without error. 

### What is the actual behaviour/value?

When I convert the tree of an old build to the new 3.16 build, I get an error when I hit the save button. See the screenshot at the bottom for the error. 

### How to reproduce the issue

Hit convert to 3.16 on the tree, and hit the "Save" button after it converted to a 3.16 tree. 

### Build code

```shell
https://pastebin.com/XmXYiNwW
```

### Screenshots

![Capture](https://user-images.githubusercontent.com/25066224/139561851-d6c698a8-b99c-47c6-ab28-f5be1f295d8f.JPG)

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0

**Comment by Antorell** [comment]
> 
> 
> Fixed in 2.13.0
@LocalIdentity 

Nope.

![Capture](https://user-images.githubusercontent.com/25066224/139856092-ebf6ab4c-41ff-4ae6-b048-8601108875af.JPG)
