### ISSUE TITLE
POB does not calculate for Enchantment Flame Totem Consecrated Ground Enemy Damage Taken

### ISSUE THREAD

**Issue by kkenll** [PathOfBuildingCommunity/PathOfBuilding#3688]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Consecrated Ground from Holy Flame Totem applies * % increased Damage taken to Enemies.(Helmet enchantment of Labyrinth)
But it was not calculated on POB.

https://pathofexile.fandom.com/wiki/List_of_helmet_enchantment_mods
https://pathofexile.fandom.com/wiki/Modifier:EnchantmentFlameTotemConsecratedGroundEnemyDamageTaken1
https://pathofexile.fandom.com/wiki/Modifier:EnchantmentFlameTotemConsecratedGroundEnemyDamageTaken2

### What is the actual behaviour/value?

Damage does not increase even though checked ' Is the enemy on Consecrated Ground? '

### Build code

```shell
https://pastebin.com/ANUmt4G4
```

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
