### ISSUE TITLE
Voltaxic Burst's # of Casts currently waiting skill option in calculations doesn't contribute to DPS

### ISSUE THREAD

**Issue by darkstrikex** [PathOfBuildingCommunity/PathOfBuilding#3690]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I change the # of casts currently waiting in the Voltaxic Burst skill option, DPS should change.

### What is the actual behaviour/value?

I've tried using the skill gem by itself and in multiple setups and played around with the # of casts currently waiting; DPS is never affected.

### How to reproduce the issue

Select Voltaxic Burst as main skill.
Try changing the # of casts currently waiting

### Build code

```shell
https://pastebin.com/6HnHqKe9
```

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0
