### ISSUE TITLE
Spellslinger reservation efficiency lab enchant does not work

### ISSUE THREAD

**Issue by sybren9** [PathOfBuildingCommunity/PathOfBuilding#3698]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Should reserve less mana

### What is the actual behaviour/value?

Enchanting a helmet with increased mana reservation efficiency turns the mod red (unsupported)

### How to reproduce the issue

Create helmet
Apply spellslinger reservation enchant

### Build code

```shell
https://pastebin.com/bQUNqCPj
```

### Screenshots

![image](https://user-images.githubusercontent.com/8831368/139775400-fa4ac346-90fb-4817-a1aa-5c72ca250d5c.png)

**Comment by hebi39** [comment]
Anyone plan on fixing this? Still doesn't work.

**Comment by eakaye** [comment]
As a workaround, you could add "Socketed Gems have 30% increased Reservation Efficiency" to whichever item has your Spellslinger setup.
