### ISSUE TITLE
Bleeding Mastery - Bleeding inflicted on Poisoned enemies

### ISSUE THREAD

**Issue by Bazlish** [PathOfBuildingCommunity/PathOfBuilding#3699]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Whilst applying "60% increased damage with bleeding inflicted on poisoned enemies" from the new bleeding mastery, whilst also going into configuration enabling bleeding, poisoned & x # of poison on enemy... Should DPS Increase. 

### What is the actual behaviour/value?

No DPS Increase/Multplier

### How to reproduce the issue

Grab/Quickly make any bleed build
On tree, Apply bleeding nodes + bleeding mastery ""60% increased damage with bleeding inflicted on poisoned enemies"
Go to the Confirguration Tab, enable enemy bleeding, enemy poisoned and x # of Poison on enemy
Toggling enemy poisoned = does nothing to dps

NOTE: Did try a few random builds, made random ones.. Couldn't get it to apply.

### Build code

```shell
https://pastebin.com/qPB3Ubj3
```

### Screenshots

![bug](https://user-images.githubusercontent.com/59581414/139778690-ae957501-09c4-49ca-b18b-a4328649fdc1.png)

**Comment by Peechey** [comment]
Issue with mod parsing. Fixing.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3700.
