### ISSUE TITLE
Scourge implicit resistances not calculating properly in POB

### ISSUE THREAD

**Issue by VicePrez** [PathOfBuildingCommunity/PathOfBuilding#3701]
In-game:
![image](https://user-images.githubusercontent.com/993718/139783174-85909d7f-7556-403d-9c8a-8aa88a1dd407.png)

POB:
![image](https://user-images.githubusercontent.com/993718/139783260-8d9c8440-e50c-4cbe-9bfa-b30883a69da4.png)

To reproduce:

Add rings with positive and negative resistances. I have -29% lightning resistance on one, and +19% fire resistance, and -16% lightning resistance on another.

I had to manually set the resistance values under configuration -> customer modifiers for it to kick in.

**Comment by Wires77** [comment]
Can you please provide a link to your build so we can diagnose it?
