### ISSUE TITLE
Resistances are off since last update

### ISSUE THREAD

**Issue by azra1l** [PathOfBuildingCommunity/PathOfBuilding#3708]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When set up correctly, PoB should show the exact same values for every resistance compared to the ingame values.
Up until updating to the latest version 2.13.0 yesterday, this was working for me as expected.

### What is the actual behaviour/value?

Since that update, my resistances for fire and cold are off in PoB, it shows less then i have ingame.
It is missing 18% cold resistance and 9% fire resistance. chaos and lightning are still correct.

I asked ingame in chat if anyone can confirm this, and one other person confirmed to have the same issue, for her/him, in PoB, both fire and cold resistance are shown with lower values then the actual ingame values.

I found a related bug report, but it specifically states to be for scourge modifiers, which i don't have on my build right now:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3701

### How to reproduce the issue

Update from a previous version to 2.13.0 i guess

### Build code

```shell
https://pastebin.com/Zs5uTYg8
```

**Comment by Wires77** [comment]
Looks like they changed the text for Darkness Enthroned to specify "Abyss Jewels" instead of just "Jewels", now.
