### ISSUE TITLE
Power Siphon incorrectly gains +1 level from Awakened Ele Focus lv5

### ISSUE THREAD

**Issue by noefrey** [PathOfBuildingCommunity/PathOfBuilding#3709]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Awakened Elemental Focus lv5 gives +1 to level of supported Elemental Skill Gems. 
Power Siphon is Critical, Attack, Projectile but not any elemental tag. It should not gain a level from lv5 Awakened Elemental Focus (in game it doesn't gain a level).

### What is the actual behaviour/value?

However in POB it gains a level when linked to Awakened Ele Focus lv5.

### How to reproduce the issue

- Create Socket group with lv X Power Siphon
- Link it to Awakened Elemental Damage lv5 or more
- Mouse over Power Siphon to see the "Level : X (+1)" in blue

### Build code

```shell
https://pastebin.com/MsSBbk2U
```

**Comment by Wires77** [comment]
Fixed in 2.13.0
