### ISSUE TITLE
PoB doesn't support charset required to import from some accounts.

### ISSUE THREAD

**Issue by Davst** [PathOfBuildingCommunity/PathOfBuilding#3712]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I would expect to be able to take any account name from the PoE website and enter it into PoB so I can import that character.

### What is the actual behaviour/value?

When pasting the account name 
`ㆍThirtyㆍ`
into PoB it is replaced by
`?Thirty?`

Thus PoB states that the account name is incorrect.

### How to reproduce the issue

Try importing any character from the following account
https://www.pathofexile.com/account/view-profile/%E3%86%8DThirty%E3%86%8D/characters

### Build code

```shell
not possible due to nature of the issue.
```

### Screenshots

![image](https://user-images.githubusercontent.com/3330933/140051471-ef2bb665-d89f-4ba9-a750-c38ba8577356.png)

**Comment by zao** [comment]
Unfortunately no part of PoB supports Unicode input or rendering and it's quite a bit into the future as Lua itself is rather agnostic about character encodings. I've got some experimental forks to play around with it but it's a huge undertaking even if it's just for user-facing places like Import and Notes.

As the import tab says there, you need to URL-encode your account name by use of the linked service. PoB can't do it for you as PoB never sees the true text, it gets mangled when pasting already.
