### ISSUE TITLE
Add cpectre

### ISSUE THREAD

**Issue by NEOKARTOXA** [PathOfBuildingCommunity/PathOfBuilding#3727]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

The program does not include the ghosts granted by "Aukuna's Will".

### Describe the solution you'd like

I ask you to finish them.

### Additional context

https://poedb.tw/us/Raise_Zombie#RaisedZombieRaisedZombieStandard

![image](https://user-images.githubusercontent.com/92036737/140504043-d4be9d75-faa8-407c-8952-d42ca16ec62c.png)

**Comment by QuickStick123** [comment]
Closing in favour of putting all of them in one issue https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4558.
