### ISSUE TITLE
Diamond flask

### ISSUE THREAD

**Issue by Ghaduo** [PathOfBuildingCommunity/PathOfBuilding#3735]
Diamond Flask doesn't seem to be applying it's base effect.

Build:
https://pastebin.com/wJfsD6mP

**Comment by Regisle** [comment]
Id say fill out the issue template but issue is easy enough to disprove 
![image](https://user-images.githubusercontent.com/49933620/140607658-db6898be-289e-4c1c-8b06-c8dcf02c11ce.png)

**Comment by Ghaduo** [comment]
Wow, my fault. I didn't realize I had 2 equipped so I couldn't understand why the second wasn't working. Thanks!
