### ISSUE TITLE
Cannot Save any build

### ISSUE THREAD

**Issue by cibrage** [PathOfBuildingCommunity/PathOfBuilding#3736]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The save/export buttons should save/export a build.

### What is the actual behaviour/value?

An error message is displayed and the build cannot be saved or exported by any means. This affects both converted older builds and new ones.

### Build code

```shell
The build cannot be exported.
```

### Screenshots

![Error](https://user-images.githubusercontent.com/82127097/140611329-a211bcbf-1258-4698-bb1c-6bf86b4c7c45.png)

**Comment by pocifik** [comment]
Same here, can't save even an empty build

**Comment by SpiderLenny** [comment]
The same's happening to me. Tried with both existing builds and straight up newly made completely empty ones.

**Comment by niklaas-0rbit** [comment]
Same here

**Comment by Lothrik** [comment]
This should be fixed by #3912.
