### ISSUE TITLE
skin of lord nodes do not work

### ISSUE THREAD

**Issue by xRaiseUp** [PathOfBuildingCommunity/PathOfBuilding#3743]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when I use the chest it should calc the node effect automatically

### What is the actual behaviour/value?

I use skin of lord chest with "magebane" node in scion area, when I use the chest it does not calculate the node effect unless I choose the node in my tree, which I cant do if my tree cannot pass thro that area.
and btw I didnt test any other node, so I dont know if this problem persist with other nodes

### Build code
https://pastebin.com/NdUmE2HC
```shell


```

### Screenshots

![image](https://user-images.githubusercontent.com/93884621/140661273-169683dd-a306-452e-a100-9e6552aa86b2.png)

**Comment by mthjones** [comment]
This looks to be a bug specific to the Magebane keystone due to the casing being different in the data vs. the tree. Taking a look.

For good measure to confirm though, could you export the build code by going to "Import/Export Build" and clicking the "Generate" button, then paste that here?

**Comment by xRaiseUp** [comment]
https://pastebin.com/NdUmE2HC
you can check here, notice the stats when you place magebane or take it off from the tree, you can try this with the chest or without it and you will get the same result

**Comment by mthjones** [comment]
Thanks! I can confirm that https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3744 fixes the issue for the linked build, so this issue will be resolved when that's released.

**Comment by xRaiseUp** [comment]
thx a lot for helping community <3 .. have a good day
