### ISSUE TITLE
Awakened Elemental Focus is giving +1 to Level of Supported Elemental Skill gems at level 3 instead of level 5

### ISSUE THREAD

**Issue by Maldini999** [PathOfBuildingCommunity/PathOfBuilding#3745]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When raising Awakened Elemental Focus from level 4 to 5, the supported Elemental skill gem should receive +1 to level

### What is the actual behaviour/value?

When raising Awakened Elemental Focus from level 2 to 3, the supported Elemental skill gem should receive +1 to level (this is only suppose to happen at level 5)

### How to reproduce the issue

Change the level of the  Awakened Elemental Focus support gem and watch the text (and DPS) change from level 2 to 3 instead of happening at level 5.

### Build code

```shell
https://pastebin.com/pGZFRUTz
```

**Comment by etojuice** [comment]
Body armour in the build provides +2 to level of socketed gems which raises the level of Awakened Elemental Focus from 3 to 5...

**Comment by Maldini999** [comment]
oh my god, of course!!  I close this, as there is no bug.
