### ISSUE TITLE
tooltip issue with Cast on critical

### ISSUE THREAD

**Issue by ocombe** [PathOfBuildingCommunity/PathOfBuilding#3751]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Tooltip value should reflect the full dps changes from triggered skills (by coc)

### What is the actual behaviour/value?

I selected my skills to include them in full dps, I can see the correct dps on the left, but when I go over the nodes, the full dps is not taking into account the triggered (by coc) skill

### How to reproduce the issue

Move the mouse over a the bow nodes on the right of the tree, it says that it removes 18k dps if I remove the first node, but that's only the dps from tornado shot, not taking the triggered ice spear from coc.
You can see the full dps is 4,3M dps
![image](https://user-images.githubusercontent.com/265378/141095394-41d4aa18-214d-4ca3-9676-1031bb013182.png)

Remove the first node of the bow cluster, the dps becomes 3,7M dps, but the tooltip said that it would remove 18k dps...
![image](https://user-images.githubusercontent.com/265378/141095441-28f68ac5-32d2-42bd-9ce5-349546d2cb41.png)

### Build code

```shell
https://pastebin.com/SfXGAL0q
```

**Comment by QuickStick123** [comment]
Seems to be resolved 
![Uploading image.png…]()
