### ISSUE TITLE
Can't import my characters PoB/Can't use my imported PoB

### ISSUE THREAD

**Issue by TeamCatalyst** [PathOfBuildingCommunity/PathOfBuilding#3752]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I Import my Character I should just continue to use PoB's function naturally. But the error's make my PoB corrupted and therefore unusable.

### What is the actual behaviour/value?

When I'm importing my Scourge Character, I get a big Error Screen and when I dismiss the Errors I simply can't use any function without getting Error spammed again. This makes PoB for my character completly unusable.

The Error is attached in screenshot below.

### How to reproduce the issue

1. Click on Import Build
2. Type in Account Name "Tespihc"
3. Click Start
4. Choose "Scourge" League
5. Choose the Character named "iBroughtMahFreendsWme" Level 92 Necromancer in Scourge
6. Import Passive Tree and Jewels
7. Import Items and Skills
8. Look at the Error Screen (included as screenshot, too)
9. If you continue and dismiss the errors, try to hover your mouse on tree & items
10. Get Multiple Error screens again

### Build code

```shell
https://pastebin.com/skwBC2QN
```

### Screenshots

![pob bug](https://user-images.githubusercontent.com/15169975/141095130-dae53ef6-8dc2-42dc-9167-c7b8f9ff6146.png)

**Comment by TeamCatalyst** [comment]
It still happens when you try to import the posted PoB Pastebin links but it does not persist anymore when importing via Account Name.

**Comment by QuickStick123** [comment]
I believe this is fixed a as both importing using the pastebin and the character don't crash closing as completed. If you can reproduce this will reopen.
