### ISSUE TITLE
Img item  or French language

### ISSUE THREAD

**Issue by blawdi** [PathOfBuildingCommunity/PathOfBuilding#3753]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

No, it's only difficult to translate the gems from English to French. 

### Describe the solution you'd like

Add images, or the French version

### Describe alternatives you've considered

version French

**Comment by Wires77** [comment]
Because the parsing of modifiers is based on English in PoB, translating to another language is impossible at this time
