### ISSUE TITLE
"+#% to Damage over Time Multiplier for Poison inflicted with this Weapon" Claw mod not working

### ISSUE THREAD

**Issue by ArchieHoy** [PathOfBuildingCommunity/PathOfBuilding#3757]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

+#% to Damage over Time Multiplier for Poison inflicted with this Weapon should add its damage buff to the dps of all types, but is instead voided and has red text, indicating it isnt working

### What is the actual behaviour/value?

+#% to Damage over Time Multiplier for Poison inflicted with this Weapon should apply its modifier to your dps/stats increased it by +#%

### How to reproduce the issue

Choose a claw
Select elder influence
Choose +#% to Damage over Time Multiplier for Poison inflicted with this Weapon as a prefix
It will be Red text, meaning its not working

### Build code

```shell
https://pastebin.com/S1eJE6sN
```

**Comment by igorcastroo** [comment]
@Nostrademous 

the same error is happening, +#% to Damage over Time Multiplier for Bleeding from Hits with this Weapon

**Comment by Nostrademous** [comment]
@igorcastroo added support for it in the same PR. Testing found issues in that while the modifiers were being parsed they actually weren't doing anything. Took me a lot more debugging to figure out why. I believe I have a solution but not sure it doesn't break anything else; needs to be confirmed by testers but it's all in the same PR.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3776
![image](https://user-images.githubusercontent.com/31533893/177662747-ebf94238-9e4f-48d5-99e8-483f66f5ebff.png)
