### ISSUE TITLE
Throatseeker with  Millitant timeless

### ISSUE THREAD

**Issue by LBlood** [PathOfBuildingCommunity/PathOfBuilding#3759]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Throatseeker is change into smite the wicked which gives 10 % fire exposure if you have at least 150 devotion

### What is the actual behaviour/value?

When you use : Item Class: Jewels
Rarity: Unique
Militant Faith
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 86
--------
Carved to glorify 6148 new faithful converted by High Templar Dominus
Passives in radius are Conquered by the Templars
4% increased Area Damage per 10 Devotion
4% reduced Elemental Ailment Duration on you per 10 Devotion
Historic
--------
They believed themselves the utmost faithful, but that conviction became oppression.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

It doesn't change throatseeker

### Build code

```shell
Item Class: Jewels
Rarity: Unique
Militant Faith
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 86
--------
Carved to glorify 6148 new faithful converted by High Templar Dominus
Passives in radius are Conquered by the Templars
4% increased Area Damage per 10 Devotion
4% reduced Elemental Ailment Duration on you per 10 Devotion
Historic
--------
They believed themselves the utmost faithful, but that conviction became oppression.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
```

### Screenshots

![image](https://user-images.githubusercontent.com/71166926/141473743-35740cd5-b076-4ba4-9764-d9eb7438795f.png)

**Comment by Regisle** [comment]
We currently have no method to calculate what nodes should transform into as GGG has not provided the method by which it is done, PoB though has inbuilt a system to manually select what it should be (right click the node with the jewel in) if you wish to have it show up

**Comment by LocalIdentity** [comment]
The parsing for the mod will work when you manually add it to a build, this still cannot be done automatically though
