### ISSUE TITLE
Lua error when comparing trees

### ISSUE THREAD

**Issue by Davst** [PathOfBuildingCommunity/PathOfBuilding#3762]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When importing a tree from another build, I expect to be able to mouseover nodes without PoB crashing.

### What is the actual behaviour/value?

![image](https://user-images.githubusercontent.com/3330933/141646175-91d54d11-8062-4772-8630-4f9bf5c328d1.png)

### How to reproduce the issue

Load https://pastebin.com/JqVg9ZpC

Create a new skilltree

Import 

`https://www.pathofexile.com/passive-skill-tree/3.16.0/AAAABgYDf8KcZ05CLGwImAb7CeOEbIwe8E0N62PviITFUMNq6zy9BL8OSFVLjDYj9klR18-VLl5F6Nadqm93pAX1GMDj9toT33MOS1dwUmHiA2VHBqxHBZNvniT9X7D_3mSqibeTJ-jVjX3Rb9DQjb8ovTfU8NVirLIZwuxQQhmKSwqJ03cHTZLyHUmxxkXximSdm7VJUgEkt9nnVFfYj_rr9RqPBx5RR5ykkA1JE60c8bNjQyLq_UptOvcTdm_tP2o26KSly3BRwzoyAaB5-usrCs96t3XII1Mx-XUmlVFMMHz5NxvgfbDndMpKBbV-sLTFhxPWvlM1ew3b56k0m4YsRpTxAAukHsKcemNNDUmrUMNwBGrrlhcEv4ZP0W8gaii93vLGRboaAST7fa0cC6v5dQ==`

As skilltree

Load Phys skill tree as comparison.

Mouseover a few nodes, likely masteries

You'll get the above error.

### Build code

```shell
https://pastebin.com/JqVg9ZpC

Tree to import: https://www.pathofexile.com/passive-skill-tree/3.16.0/AAAABgYDf8KcZ05CLGwImAb7CeOEbIwe8E0N62PviITFUMNq6zy9BL8OSFVLjDYj9klR18-VLl5F6Nadqm93pAX1GMDj9toT33MOS1dwUmHiA2VHBqxHBZNvniT9X7D_3mSqibeTJ-jVjX3Rb9DQjb8ovTfU8NVirLIZwuxQQhmKSwqJ03cHTZLyHUmxxkXximSdm7VJUgEkt9nnVFfYj_rr9RqPBx5RR5ykkA1JE60c8bNjQyLq_UptOvcTdm_tP2o26KSly3BRwzoyAaB5-usrCs96t3XII1Mx-XUmlVFMMHz5NxvgfbDndMpKBbV-sLTFhxPWvlM1ew3b56k0m4YsRpTxAAukHsKcemNNDUmrUMNwBGrrlhcEv4ZP0W8gaii93vLGRboaAST7fa0cC6v5dQ==
```

**Comment by chx** [comment]
https://www.pathofexile.com/fullscreen-passive-skill-tree/3.16.0/AAAABgQCdgDgAdwB5wL2A10EBwUtBjkGiwkzCiYM9w3NDjwUTRRxFewWbxiRGjgabBpyGzcczh8CIOMhYCSqJy8pTypjK1AvzC_WNsU26DbpOYY6UjpYOq062DxNPQ9AoEb-R35LPUyzTUZNz1FgVcZYr1oyXhNf2mLsZU1qu3IPcql07XTxdqx343rvfLt82YIHg9uE2YTvivCPRpBVkvedrqcIqDWpbqmVqzmsr64-r6e5HbyfvTa-rcC_wSXBgsT2xYrGisauypDPftE22CTZfNm_3efiLONq5CLpRuoY8wb1L_ai9zL4Avjr-6r8S_5UAATqgiEMoWqYCdblU0wnS5Oj as well.

**Comment by melink14** [comment]
I also get this error. I find if I manually set the masteries after importing then the error goes away. (I can hover as much as I want and it doesn't pop up). But it has to be done for each mastery.
