### ISSUE TITLE
Importing tree causes PassiveSpec.lua:283 AllocateMasteryEffects attempt to index a nil value.

### ISSUE THREAD

**Issue by chx** [PathOfBuildingCommunity/PathOfBuilding#3767]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I am trying to import a tree into an empty build.

### What is the actual behaviour/value?

I get an error PassiveSpec.lua:283 AllocateMasteryEffects attempt to index a nil value.

### How to reproduce the issue

Import the tree provided into an empty build.

### Build code

```shell
https://www.pathofexile.com/fullscreen-passive-skill-tree/3.16.0/AAAABgQCdgDgAdwB5wL2A10EBwUtBjkGiwkzCiYM9w3NDjwUTRRxFewWbxiRGjgabBpyGzcczh8CIOMhYCSqJy8pTypjK1AvzC_WNsU26DbpOYY6UjpYOq062DxNPQ9AoEb-R35LPUyzTUZNz1FgVcZYr1oyXhNf2mLsZU1qu3IPcql07XTxdqx343rvfLt82YIHg9uE2YTvivCPRpBVkvedrqcIqDWpbqmVqzmsr64-r6e5HbyfvTa-rcC_wSXBgsT2xYrGisauypDPftE22CTZfNm_3efiLONq5CLpRuoY8wb1L_ai9zL4Avjr-6r8S_5UAATqgiEMoWqYCdblU0wnS5Oj
```

### Screenshots

<img width="617" alt="2021-11-14 22_39_53-Path of Building - Imported build (Scion)" src="https://user-images.githubusercontent.com/193045/141734390-5d23de1a-410d-4803-bf1e-b3b75bfbf029.png">

**Comment by randomflyingtaco** [comment]
Debugged for which mastery effect was causing the crash and got effectId 60034 "Recover 15% of Life when you use a Warcry" but I'm not seeing any masteries allocated on the linked tree (when viewing on pathofexile.com or in pob). That's all I can contribute to this.

**Comment by chx** [comment]
The original is

``` https://poeplanner.com/AgADABUABAIAbgDgANwB5wFdAwcELQU5BjMJ9wzNDTwOTRRxFOwVbxaRGDgabBpyGjcbzhwCH2AhqiQvJ08pYypQK8wv1i_FNug26TZSOlg6rTrYOk08Dz2gQP5Gfkc9S7NMRk3PTWBRxlWvWDJaE17sYk1lu2oPcqly7XTxdKx243fvert82XwHgtuD2YTvhPCKRo9VkK6dCKc1qG6plak5q6-sPq6nrx25n7w2va2-v8AlwYLB9sSKxYrGrsaQyn7PNtEk2HzZv9nn3SziauMi5EbpGOoG8y_1ovYy9-v4qvtL_FT-AAAIAPYCiwYmCuMghjnaX_eSAvgEAAwhguoJmGqhTFPl1qOTSycEAAIATgJQaHlzaWNhbCAxSCBBeGUAFP8AAAAG7hIBrADJEQIPABwAcRIBDAATEgEWAA4SARsAQBIBbwABXYsBDAAAAAAAAJoBTmV3IEl0ZW0AFP8AAAAAATuBAQwAAAAAAAAB____________________AAACAAAGBQgbABQUAAAAxQAUFAAAA8UBFBQAAAHfARQUAAABdgEUFAAAAcIBFBQAAAEyARQAAAABXgAUAAAAAAQEFQEUFAAAATgCFBQAAAHFARQUAAAB3wEUFAAAAQYEGQEBAAAAAZEBFBQAAAMIARQUAAABkAEBAAAAAQcEcQEUFAAAATsCFBQAAAEkABQUAAABIgAHFAAAAQEDAgIUFAAAAcsCFBQAAAEoARQUAAABAAFRAAEAAAABAwD_____________PAAAAAAUAB-LCAAAAAAAAAMDAAAAAAAAAAAA
```

**Comment by randomflyingtaco** [comment]
Looks like it is an issue with how poeplanner is encoding masteries. If you take the tree-only export URL from poeplanner and open the URL on the pathofexile.com it does not have the masteries allocated.  If you allocate the masteries on pathofexile.com and then import that tree, which leads me to believe this is only a poeplanner issue.
