### ISSUE TITLE
Vaal Summon Skeletons should not have an additional gem level when Awakened Elemental Focus provides +1 to Level of Supported Elemental Skill Gems.

### ISSUE THREAD

**Issue by ShioRemon** [PathOfBuildingCommunity/PathOfBuilding#3774]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Vaal Summon Skeletons should not have an additional gem level when Awakened Elemental Focus provides +1 to Level of Supported Elemental Skill Gems.
In game Awakened Elemental Focus does not add a gem level to Vaal Summon Skeletons

### What is the actual behaviour/value?

When Awakened Elemental Focus provides +1 to Level of Supported Elemental Skill Gems and linked to Vaal Summon Skeletons it incorrectly adds a gem level to it, even though Vaal Summon Skeletons is not an elemental skill gem.

### How to reproduce the issue

1. Link Vaal Summon Skeletons to at least Level 5 Awakened Elemental Focus

### Build code

```shell
https://pastebin.com/vskateW3
```

### Screenshots

![image](https://user-images.githubusercontent.com/94539445/142206333-f29a5065-4b31-4faa-bbda-14974da5e7bf.png)
![image](https://user-images.githubusercontent.com/94539445/142206977-649584aa-1f73-4e89-9a22-4c5779592b1a.png)

**Comment by Nostrademous** [comment]
Same as #3709. Fixed by PR: #3770
