### ISSUE TITLE
Maximum hit taken for physical Value is based on wrong mitigation

### ISSUE THREAD

**Issue by Drech00T** [PathOfBuildingCommunity/PathOfBuilding#3779]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

"Maximum Hit Taken" for physical values should apply physical damage reduction for armour correctly. 
The physical damage reduction from armour should not be based on an average monsters damage but on the "Maxiumum Hit Taken" value itself.

### What is the actual behaviour/value?

When calculating the "Maximum Hit Taken" for physical damage the calculation is based on the Armor reduction of hit values from average Monsters. So the resulting value of "Maximum Hit taken" can exceed the hit damage that is used to evaluate the physical mitigation. This Maximum Hit value then is wrong because that hit would be reduced by armor alot less.
I encountered this issue when running a scourched map with 15k damage on switch. POB told me i could survive a 21k physical hit but i instantly died because that 21k value was based on reduction calculation from a much lower hit damage of an average monster. The calculations became correct once i put 15k damage into the configuration of "Enemy Hit Damage".
What i then also noticed is that "Is enemy a Boss" has no effect on what value is used to calculate this "maximum damage taken". 
So right now it seems that this value is only useful for normal mapping against normal monsters...

### How to reproduce the issue

1. Open https://pastebin.com/7LxqGXwe
2. Check "Maximum Hit Taken" for physical : 19.100 dmg 
    So i assume i can tank a 19k dmg hit.
3. Input 15000 damage as "Enemy Hit Damage" in Configuration which i should survive based on 2.
4. Check "Maximum Hit Taken" again : 6673 dmg
    So i easily die from an actual 15k hit.
    Makes no sense to now be able to tank less maximum damage. 
    This value should not change based on Monster damage.

### Build code

```shell
https://pastebin.com/7LxqGXwe
```

**Comment by Wires77** [comment]
The eHP section has been reworked.  Feel free to open a new issue if this is still a problem
