### ISSUE TITLE
auto import field

### ISSUE THREAD

**Issue by axet** [PathOfBuildingCommunity/PathOfBuilding#3785]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Right now 'import' action requires too many clicks and site options.

### Describe the solution you'd like

Simplyfy all fields into one: 'core or url' detect data automatically only give user one field (url or code) and one button (import).

**Comment by pHiney** [comment]
"Right now 'import' action requires too many clicks and site options."
Are you referring to importing a PoB code like https://pastebin.com/WxjSYT00 ?
If you are, there are changes coming that automate the site selection based on what you paste (or type in) and short cut keys to get the import. #3732, #3813, #3818.

pH

**Comment by Lothrik** [comment]
Fixed by #4398 (it's just a single import button now for both build codes and build URLs).
