### ISSUE TITLE
Couldn't resolve proxy name

### ISSUE THREAD

**Issue by Ghettofix** [PathOfBuildingCommunity/PathOfBuilding#3786]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when importing a character using the character import I get an error.
the error message is:
Character import status: Error retrieving character list, try again (Couldn't resolve proxy name)

### What is the actual behaviour/value?

The error message is: Character import status: Error retrieving character list, try again (Couldn't resolve proxy name)

### How to reproduce the issue

happens when i try and import any character

### Build code

```shell
not relevant
```

### Screenshots

![pathofbuildingerror](https://user-images.githubusercontent.com/94675714/142588207-8d5cd56e-02f7-4896-9ed8-c03b1da57007.jpg)

**Comment by Wires77** [comment]
Do you have a proxy server saved in the "Options" window?

**Comment by Ghettofix** [comment]
Yes there is a proxy server : https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases

**Comment by MrStrben** [comment]
How do I remove a proxy server?

**Comment by MrStrben** [comment]
> Да, прокси-сервер есть: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases Я удалил его, и теперь все работает.
> 
> спасибо :)

How do I remove a proxy server?
