### ISSUE TITLE
Brass Dome has incorrect range on max res affix

### ISSUE THREAD

**Issue by rcpd** [PathOfBuildingCommunity/PathOfBuilding#3788]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

1-5% max res

### What is the actual behaviour/value?

1-2% max res

### Build code

```shell
https://pastebin.com/f7yKKXvT
```

**Comment by olop4444** [comment]
This is fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3739, just waiting for approval
