### ISSUE TITLE
Importing Character from Xbox 

### ISSUE THREAD

**Issue by GrimLicorne** [PathOfBuildingCommunity/PathOfBuilding#3790]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The import build should bring up a list of what characters and which one to start to view the build. 

### What is the actual behaviour/value?

When I open POB. I go to import my character information to pop up my build. So I go to the drop down menu and click on xbox since that is where my account is right now. I type in my gamer tab, and my other character names and it says Account name  is incorrect 

### Build code

```shell
I do not have a a build code to provide.
```

### Screenshots

![image](https://user-images.githubusercontent.com/94751908/142731515-fcc32f55-8da7-4d52-b6c4-aa67e5dca161.png)

**Comment by Wires77** [comment]
Can you link to the account/character you'd like to import?  Also make sure you're selecting the proper realm to the left of the input box: 
![image](https://user-images.githubusercontent.com/1209372/142739144-7ea5ff54-073f-4953-a007-b77ce9188370.png)

**Comment by pHiney** [comment]
I found TheGodAmongMen has an open profile

https://www.pathofexile.com/account/xbox/view-profile/TheGodAmongMen

Characters import correctly

pH

**Comment by Nostrademous** [comment]
It could have been a UTF-8

**Comment by Lothrik** [comment]
Closing -- character imports from Xbox work fine as far as I can tell (tested several different accounts).
