### ISSUE TITLE
Can't config alternative ailments through Leadership's Price

### ISSUE THREAD

**Issue by Freshi142** [PathOfBuildingCommunity/PathOfBuilding#3791]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I have equiped the unique amulet Leadership's Price and my two highest Attributes are equal. Scorch, Brittle and Sapp -Checkboxes should appear in "For Effective DPS" under "Configuration".

### What is the actual behaviour/value?

Scorch, Brittle and Sapp -Checkboxes do not appear in "For Effective DPS". I have the Conflux-icons active ingame and i'm applying these ailments while playing. 

### How to reproduce the issue

I tried to import this Charakter on 3 different PCs with the current PoB version 2.13.0, same behavior everytime.
I tried creating an Leadership's Price Amulet directly in PoB, no change. 
Apparently my config is wrong, but I can't figure out where I fucked up. 

### Build code

```shell
https://pastebin.com/XgUDUdhe
```

### Screenshots

![SS1](https://user-images.githubusercontent.com/94767551/142744633-1d5352a5-42d8-4267-9384-670feface659.jpg)
![SS2](https://user-images.githubusercontent.com/94767551/142744634-6ecc40a7-bf11-4942-bb04-2f4d3dcdfe57.jpg)

**Comment by PJacek** [comment]
![image](https://user-images.githubusercontent.com/18018499/195677947-bd44ff4b-d02f-475e-a70d-83011b5dfaa1.png)
This seems to be fixed
