### ISSUE TITLE
Second sight keystone blinds you even if you have the cannot be blinded mastery according to PoB

### ISSUE THREAD

**Issue by TiagoTheDecoy** [PathOfBuildingCommunity/PathOfBuilding#3793]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when you take the cannot be blinded mastery the blind effect of second sight will not affect you

### What is the actual behaviour/value?

the cannot be blinded mastery does not affect you at all and you continue to be blinded

### Build code

```shell
https://pastebin.com/hkm6EFqy
```

**Comment by Peechey** [comment]
No longer an issue.

Second Sight reference
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/ac797faa-e88a-40f6-8477-1f5598fe71dc)


2.13.0
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/3d14b0ff-501f-49b7-9c7c-81f205ff5184)


2.42.0
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/7f2c21a2-02f0-4d08-be1e-98cd81d63860)
