### ISSUE TITLE
3.16 Unique Jewel Survival Secrets wrong stats

### ISSUE THREAD

**Issue by SealTecH** [PathOfBuildingCommunity/PathOfBuilding#3795]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

by 11/22/2021 ingame stats are [](ur
![Screenshot_2](https://user-images.githubusercontent.com/14233243/142836238-05215666-594b-4aab-b5ef-bfa27b1d8bda.png)

### What is the actual behaviour/value?

In Pob description is
![Screenshot_3](https://user-images.githubusercontent.com/14233243/142836353-9ccc17ca-3903-4673-981d-b73078b1a45d.png)
 

### How to reproduce the issue

find Survival Secrets jewel in search and compare with one in game 

### Build code

```shell
No particular build
```

**Comment by Lothrik** [comment]
Fixed by #3799.
