### ISSUE TITLE
Flame wall secondary debuff on projectiles not taken into account

### ISSUE THREAD

**Issue by DisconnectedOne** [PathOfBuildingCommunity/PathOfBuilding#3804]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The damage calculations should have an additional parameter for damage over time DPS which would be taken into account for total DPS for the secondary debuff of flame wall for projectiles that pass through it.

### What is the actual behaviour/value?

Currently, projectiles that pass through flame wall only receive the added flat fire damage and not the secondary debuff damage. This leads to damage calculations being significantly lower than if the additional damage over time was included.

### How to reproduce the issue

1. Select a projectile skill for main skill
2. Add flame wall
3. In Configuration, under Skill Options, set "Projectile Travelled through Flame Wall" to true

### Build code

```shell
https://pastebin.com/qsi69J37
```

**Comment by PJacek** [comment]
Flame Wall's DoT damage doesn't merge into the projectile and is not affected by mods applying to it.
To view the damage from both summed up together you can use the Full DPS functionality.
![image](https://user-images.githubusercontent.com/18018499/148095176-2774ca57-b8e2-4299-a4b7-9d93381b51a6.png)
