### ISSUE TITLE
Search for Items

### ISSUE THREAD

**Issue by RevOlutix** [PathOfBuildingCommunity/PathOfBuilding#3805]
### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

No

### Describe the solution you'd like

is there no way, to bring in a button, which brings you to the PoE Trading site...?

I would llike to explain what i mean:

I have loaded a build into PoB -> goto the items section -> then klick on "SEARCH" and it forwards you to the PoE tradesite and search for all offers from the selected item.
![2021-11-24 19_58_21-Path of Building - Imported build (Necromancer)](https://user-images.githubusercontent.com/86204938/143298730-ef839be9-8da5-46ce-932d-1fdc8ac9f263.png)

**Comment by Nostrademous** [comment]
This feature has been added to PoB and currently in `dev` branch. Will be part of next release.
