### ISSUE TITLE
follow-through

### ISSUE THREAD

**Issue by shlagman** [PathOfBuildingCommunity/PathOfBuilding#3806]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?
follow-through

Projectiles deal 15% increased Damage with Hits and Ailments for each remaining Chain

### What is the actual behaviour/value?
follow-through

Projectiles deal 15% increased Damage for each remaining Chain

damage with ailments doesnt apply on pob

### Build code

```shell
z
```

**Comment by pHiney** [comment]
https://pathofexile.fandom.com/wiki/Follow-Through?so=search
