### ISSUE TITLE
Add hotkey to edit equipped item

### ISSUE THREAD

**Issue by SnosMe** [PathOfBuildingCommunity/PathOfBuilding#3812]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'm tired of manually searching equipped item by name in "All items" list to edit it.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/4292308/143769210-065ed930-e861-4308-9939-707cbc2879cc.png)

When I mouse over item slot and press `E` (for Edit) key it should select item.

![image](https://user-images.githubusercontent.com/4292308/143769232-da0c4aee-e98f-494e-9216-c36f6acb984c.png)

**Comment by PJacek** [comment]
Fixed by #3876
