### ISSUE TITLE
Import missing specters from Delve

### ISSUE THREAD

**Issue by Butsuon** [PathOfBuildingCommunity/PathOfBuilding#3816]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Lots of monster types are missing from delve, specifically the ones in less common regions. Turong, Azurite Widow, etc.

### Describe the solution you'd like

Add any missings specters from Delve encounters

### Describe alternatives you've considered

The only other option is to create custom skills to cover the monster skills, which is a little sketchy.

### Additional context

I was hoping to test the Turong's Ignite DPS with the new ignite scaling during Endless Delve.

**Comment by pHiney** [comment]
I have no idea where to find the source information for this.
pH

**Comment by LocalIdentity** [comment]
If you want a specific spectre, you need to tell us the exact name. There's a million different spectres and we're not adding all of them into PoB

**Comment by Butsuon** [comment]
Hello,

Sorry for the delayed reply. I was specifically looking for Turong (https://poedb.tw/us/Turong#TurongTaowuChampionSpectre), but there are several other monsters in Delve encounters with relevant interesting abilities. I'll link any that I personally find interesting.

https://poedb.tw/us/Gorgol#GorgolQiongqiChampionSpectre
https://poedb.tw/us/Gorgol_Alpha#GorgolAlphaQiongqiChampionSpikedSpectre_
https://poedb.tw/us/Wellwing_Matriarch#WellwingMatriarchMineBatAbyssLargeSpectre
https://poedb.tw/us/Azurite_Widow#AzuriteWidowDelveSpiderPacksMotherSpectre
https://poedb.tw/us/Enhanced_Vaal_Fallen

These are the monsters that occur in Delve that I believe to be worth including. Enhanced Vaal Fallen also occurs in temple of atzoatl.

Thanks.

**Comment by QuickStick123** [comment]
Added to https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4558
