### ISSUE TITLE
Don't see "Mana cost" under the main details pane

### ISSUE THREAD

**Issue by ahor25** [PathOfBuildingCommunity/PathOfBuilding#3821]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

On the main details pane with avg hit, crit, total dps, etc.  I see other people's PoB have "Mana Cost:" as an entry (just above the attributes like str/dex/int).

My PoB does not have that when I open it by default and click new.  Same as when I import my own character from PoE.  It's just not a line that is present in my PoB (v2.13.0).

Yet when I import another player's PoB, it's in that import.

Is it a setting that I have to check off?  I have looked everywhere and google/github searched but can't find someone posting why it's just not present on my PoB by default.  It's very hard to see the cost of my cyclone given that it's simply not showing at all (and that means any drop-down skill).

### What is the actual behaviour/value?

n/a, the line doesn't even exist, so there is nothing to hover over

### How to reproduce the issue

I simply open PoB.  

This is literally it by default.

Even after updating from weeks ago, I thought something was wrong so i re-downloaded the latest version and re-installed.  It still opens by default completely leaving out the line for 'mana cost'

### Build code

```shell
I am not a computer person, I have no idea what this means "provide a build code"
```

### Screenshots

![PoB v2 13 0 missing mana cost](https://user-images.githubusercontent.com/95474623/144585362-ec16faf7-7e42-4201-bd50-a6db7ca5297d.jpg)

**Comment by Wires77** [comment]
In your screenshot, you don't have a skill selected, so there is no mana cost.  When I create a new build and add Cyclone to it, mana cost appears just fine:

![image](https://user-images.githubusercontent.com/1209372/144621815-080fd06b-7a0c-41b5-97ce-15a1aadc8495.png)

**Comment by ahor25** [comment]
Trevor,

Thank you for your reply.

I did do that and can see mana cost appear, however that works if i start from scratch completely.

When I import my character from poe, how do I manipulate pob to do that too?

I have tried to make a new skill (despite already have multiple due to importing my character), but 'mana cost' doesn't show up like from scratch.



Sincerely,

 - Albert Hor, MD

CHPG (Centura Health Physician Group) Hospitalist

O: 719-776-8040

F: 719-776-8050

C: 720-839-1001

________________________________

**Comment by Wires77** [comment]
What is your character?  The "build code" prompt in the issue template was for you to put a link to your build, but I need that to investigate further

**Comment by ahor25** [comment]
Wow that is long



eNrVPdty2ziWz6OvYLlq9iVyQlwIgtlktny3u-PEsZ2k0y9TIAhajClS4cW2eqr_fQ9ASiJl0qZl98xud5VbEnEOcO4XAOx3_3M3ja0bleVRmrzfQq_tLUslMg2i5Or91pfLw22-9T__GL07E8XkU7hbRrF-8o_R396Zz1asblT8fssjW1YhsitVfF2gIv8EVDORFBOVJqfiR5odpcH7rY9porYsXyRBVCy-yVjk-UcxVe-3LiYiSG-3LJFLlQR7qwc7eQ6fo2TLmooouUjltSqOsrScwaK3rJtI3Z6mAYw7OT37dH7ZmDlKmjPDyv_27iwWc5VdFKKwcvgDyIEB4kodRwWgEnEJeDBxqfuaeS5mjPGtNw8C7osp_H0i7MVMqWAJY_97hgGJayNfe67rIBfZzKEeYX2AZ5k6CEMli-hG7WVRsTcRiWyQ7L52cR_sJuNPy7iIZnGksiUMeY3oA3StzYDsXiZcpoWI988uGgLDiLx2uU2QR4jz18ClDeWizHFee5y6DPdCfYuKCQA156MuZ95rlzk2R5w8CLkbg5Q3WKuGPblKokJtCHyWRnmaPINLLdAhjNpLp36UtKkdyKkF6M7N1VOXu5emMbiqZKVwr21Meh1FpsSnsLKgcxFEZb6aD_UBnYpE7KV58bhZf4hCNWzkwcWwcefg0IaN1Ks8Uxn462L4Yp8EcFGsnAC2e93GufrZHImcXtntq7uGijkPIGyNRL1TnyQrMgihDyBsjsSO27_Cm7SAOLoc6z7IzobyMu-BECHf6tEniVwCeOwhvF-STOUqu2kEDOTY6LXrDIOqxbwEZuQ18RDERQqBkdGHkJyrK5UMU6YPSsnJEaQF56JQwxR2OYpz9CC_9OAmv_hDWDvY5ZFhAOucQvZrx2GIM-Q87CDafMLOa_bQ6Cey6pvIBiQVB4nKruYXk0jFQSPCIzQE4FzJFLKo-Z6YrYjnDD8olSaCljbbw6YcpFpNkCfy7eBG5E3rfZygCqBJi9NryKcKgjtABGot5yH2C4KcZekPne_FT4TbyaZp2XTDBNsP0l4BNEnvj6Nnk3keScgTTMZ9roJStt1kv84tstdTULcpmJrJg6FoaATwXq-2G0PBcS-FfYCqOO4C6TXNnaIQ8no_Da7W-Ww_OMnTIS7K2Qx8jla2oXCHUQaczqNGqO73_6vBn8Cqm0ZNeX8qpW2yPQF7fPD6BOiBIHE1KRIoXAeTsQaxPlV_NAampvnaNGzI6PUp-sVRxq0ipF_e11F7ZCH8WL217DvshFS5qt_001tYzEQX9Ks8FQ0ZfSpW-VKvfRxmKvljvo7fHjS8OQHp99xBmWnlHjzHOkRzmipNeffGdDz0p5PpLM0KKxZ5sSNlWibFscgn77dEYLsqoNRH1BU2ZtJzpUN5KBjywpBLV1HbDgXeMqDnSsRT4N5e9VVPLGShsgoXklyg0FWeCAnmMvBdxhwf2VwoFSpCMJEkwLas1rYnYpkbyk6SWVlYiemZ5FoB_pmUU19X0dV_V3JsjpxGufynX4ahbqJsAU8y0_85ODw82Ls8-XpQg1wo420tmcaxmOUqeL-VRPGWFQW1tl1AmJHFgNFQr9dNk8fHQhIiswik-PhQXWQPWKrpgDw-TvchBgwDdRCxGsqiy_lMacXLh3GpdtKPjzUF_4BxVX0-hCzTBRjCdCXFfMC4ZQ41YOxBrHaiWIfpIXw6BfWt4vuQ0RBss8gvi0EaZaqrASvQNcUAspqZ8iDNHzKszrgGTF-npY-PrCPYELWDNGegiPbBc4EyDzJk4xwuxbVKau-7cHHvjBXlVg4u-EhN8905hLhDzdC1TlBrAAS_rATPFqhQlLH-_XMp4qiY65jQ-PVD1c8268gn6a1Olyo82m5z4PWHD9WTnbioUehJ3m-FIs7r_rJZoelT75iM03w36zfN6iiRcRlAFV5H8nq6WPh66i3rSre193RYqZ-oRAfuYEFDHqc6JU1T0Pb1WfQEeg1_ewerqgGP4tQXMV5MU1GI7a3WY7TErtGcBDrspnmxm8bFx_QG6uWfFbEnxuANu2Claqq_n6pCBKIQb04KYMUbzY83ZjXwqRtLc_4lXbJBsg5Lujh4v_UV2K_uKpV5Aapqge6VWa4-Jabj_1TKlirRgcRkocMIO1Z3RVrKyYuRZljta5_9LGG1MBjzGETOCvaFRbWbJhA34LdnSOo-juGErWArt1Vx61FDr1zZi5j6NyVm4CeRdXGrC4R7Jq8hX4rn11EBOahvfMuGWnRRTqdp0oVJ1wTDmF7hsJpIXkytTOFs4ssO5Pybk9mDB1wAG0jl71ACpEU2H0gbGmgxy8xpc4P5kviw4uAepuFmU2Ow1tK4f7_1HCtYQPHXms1XIeK9WEC9MN9Yn7pwDGe3hrYW4C9lKidS7UM1-sx4EkfJ9cYBxQD__1Ud9KjNnoCjywqhVx9vzOhOJE9IshbwlkEwTH28oamWyItPSTOhf0bG1YtruF5pHNbtRCVWhcdaVRn_CR07j5IrC_317mkfCjB9oCJRz_JQHWie6KQaGP7TCdVfy_Vl6fP84mlj96lh37wsPVP_ufQ0MDyRHssAv3CBsZNJkaiLMrtSz3BNXViGU1dBWxX4f8osdtNgbi227_5Ky9ibyzh9hiNah39CpFuAvnQ_wQQm0zB-bnRrIXkKZTqufUosDa-3SK2LIouuX5zSuuK5AvXQmxbwUJ922JjmB9ENt5_j-SwtJiqbRuIls99ntb7W4Z-Sj0llGdgXFt5JIjMlchUslKTSkedUio-ifArZC1zrSpy_NCPMyQEVVEeBNqa9C8twnT1J8lmUiWLVkf_3u3xg043K_1pvDzyN9CbWrkgSvRG5oTn1oHmCei0wWDWKNy9GYKE9T1KJcnP6urAMV6c2_EvRdiyKbBMHXxO1Bv4Eh14BvhgZKhNx8Ck8kZtnHV04nqB9FbiVhtaJ_I-XPvivNfkdKctMyPlOYsJC_qxG61mmZJRvZhQr2DcvWEsfAW3PK6PbGJ5YQVfAL0XQWfmstuUa-BNEYwC1PRzEqrNFXH8yu76XmVKWqNTVgKN6rxW-NG8L6eWauj4HbzivDwW83_qX41APjTFhGP05_hd1keeOCSWcwDf4jJ0xQYToZ4S6mIyxxxysv9nEI2PiMkThG4b_8LGDEHX1Nw-Pqcso_hPoSgO9PUw8TtHYpZSOMeeON3ZcSsbMBpxjbHvcHXvUBgwO42zsYMfGY84JTOcyh8E4DCBMPx0TjrA3hvUCDCUYObAkF-ExTEecMcXUfET2mMEKxtjBDD4SSt2x48EA7LqcjxEsgsNg13PgISxuTD1mw2eYzx278BkIoJyOKxZg5Dl8zBBzyJjahI2BXo_BQw8BJRwjDkQ4FBaKCLbHSDMV5kAVidTWS3fhL6IwntmwLodhmJp6nm3DZ9t1AJnNCTDAcZEZDouEj2jsEAocwPq2hp5K0-5wDzAgQ68RmMMQrM8B2YwpxwTmprbjwnycAAnMcygwjOshlbS1fBin-i_wY0wRA1SIu7arfweEwD9gPqUIWECwC9zEMNI2xOMxQi6xQfae54E0XQ6_6CtSmk0wnsJDBvMxTQJ2gSiPcP0DdTCsXXMSKHAQ_MXwEP46oGRGuQgFzJqVmJvPSKOHxWOXajkbJSOgjcBijmBagj0C-kNBQ7VIHfgdZApC5wQB-zCgwQ4FJoKeuLA-x4bJKZAIwylDmmQG_DSq7GH9A6gw8M12gEMYERtpmlytBg58pgSUA8M4IAympFr9XTAqiMiqcb9Pb3PJhc2xOnQcBFGhgo_aGmoH9eX8g_nwt0lRzPK3b97c3t6-nolikobqLorVa5lO38z05b4btW280rae6M0O_LN79X1X_VJOjs_Pb8u732_c_cn59vxyB3_3Px5Gv-76Oz-y787l3Q9_O_2DfP68Xeafr2-yi6PpXZSdhb8dzr38x_4v32fzGzLLjw-9Cx4efYj55Wf09e5m_-s-P59-PSBnFM8-fy63T84-2Df-9u13dzv_Lf94k9yWf_h79s8P-PzU-83b__z1S3n6Mb_6UR4S_7fJxe3NEccsPPr184-fZ9vFj_2diwu8nV0epj8__nLgyrsv0TSfHv_z6PcZC35G5CI-8m79H7PvX9Uenafe0ani1z9T5_rHsTjdo8ll5KvjlH71vuzvHSqyeyHugukvJyfq_FbszA6dw9MfJ4fX-DL5RO5-fCb49rs6OSy-xOdBdn394TL_6H7Yvfz49bdvl3v2-T6aiA8H4vKX29Odk52daGcvPVbTjx_3v_9-Vh4ieR782C8n6e4vx2dfJuzseI6_X1-XDi4_v39vBPdmIbl31XXLvBJj_c14PCN5bX2QnhRVrKiP1N4fpx3fahjtG2aMazWO9I3Tzms1DPei0x5sNY71jTM-azXO7cWnnfBqHFqE4TcNHsEXiEomgOmwpT98TAtlnukfF19MUPsaqVsrVyKTE6h1dSL3R5pOv5s4qs8ZHStRnIpZHT71s_qMEqlPKBWi2I8gzmXmbNUi5uqBvy0OvL4zcbsOn_rzhSpMmCxzdaFkmgRVWmh-XqSBBsgcxqqPFJ2bzcW31vnO-cFoZ5ZCeT6f5co6y6J8OtrT2UVh_aJuVTz6kkQ_S2Wd7L-1fKwoYx5VXFHXp67yXEfHOcmw9IkQ1HddAX6IKQwBgCmXephoD-ZySh3HHpllGJrfWpyMzKdz9fOtRfDoZDqLIwkJ5lsLj76npSWhsksLy1fWqYimKoBlZVk5A5dk7cZpGjQGREkIsPoJ5MPztBzxv-scu25ATMVdNC2nVnViz6qO7I1eIefvVpFa-pS7VZ2R0wXlCOEmrL7sV28ujRBrPql3nG6jYmJ9E0mQr9Zn9EbT2uY97uD9uZgVJSzgYK5GH_RxZWsvLnW-c5_7iHMqCJeBi20VchIg6QWUSg-MLPAEcm3bFh5WgY99AhbqhMgJKHOltBFiirS5jxrcd2iT-2T0L5mJEOj4cycIcotbZ5VHt6oUbvUYWzAAWNF-bgmgx6zeqg2phRDGX0wF1EdrUFeZSAqgssV-fUNgwf4HYEWcpwsEr4iW6r66AyYCnweDuRrstFYV3QYaoS7yrCgH9RMJ0KXRJult_7hvEYTOGZACNKgcjNkckuzRDtLWji8fTz5_ORidRpCJwwKtQwGKNroEQ4hVnnfYZoiVHbDQBq0QvqMv5QVMgKE6PPRsFoTKVYwyAUkcVSJ0wCIVZyEljsKSB2FbO9ioutn61jJK2VQPe7Qn9C03za6rOM2icG4xYmMrAecX6lWGZQx1QnKjMs0if24dR1cT61IBDpFZ--k0Ssp8VHMrB2lbmZnMKM5emgBJWQVYTNQCLh-9wsZetRzrKgPqp5Xh5tYMrAbZ1uK-5Qg1NUmZ8kGXKB_TZNsc97N0KXsf7BgQAlnyUXumnRL7Jgo5Udl_gRPO_zs3hm28qigi2SE217UV8SFnFIKREExZBUEgbCyDkCGEQoi0xCcKUlZ9tZ_6KkA00Hkj5NiOwG2xOaMP0VQnbcAoMKW22NjjPrFziD423f3EWMkrYrexWHoDAEaFaWYpISf66VQrgd6qhyTREkYUlYRXO8jG5xfiWlkUBJdV7Vjr4K7IFg7YCrN0eq-d3IW02T7rEZ7TKbxzpRkmFlqYrsQYhsBICMvzESxgmkOcuSfLkPiQomNI3yVUNIqD72W2CsD9MiWoUq50JWQmHAsFBQQOIXgGfiB9qGS4ZEi1ZOl6D8mSNsVR-ZuqPrb2y6oNPXrlNB2avgM-Mpo_0Q3TONZHFWo3OBHgtLY9Pdxc3DdytfR97h7esU7eHWbpHyqxLjMRxb0pRCgIBC7hQgXLfSEdrDAPcOBBPYPCkAUkCOFbCAkh9oErPtSKREnfgaolIJ6P13m0cFOnCv47bbEMt1mG7CbPVjciF-FFv_DAEoUVK735Rm3rJCk0n650LqadVDXV2FruxlshpA65hS0RQKUEPAfWrfDmm2BsgBszAqieVZuLL8Z35Sbr6xGV2ymqy4kJSuAMj9OZ6tdomzuOFzhIdzEEpaFASIb6XQpQMCNf8UCGLEQuiAsxl6jQDXwo3BUIkRGf0qAvqHyF5ei2UltCn5J4XttxbjXDQ5UY6dM1rahRYdNpoM4Bd-IY0lgtfJ2SpaVODLWSA3OSyjOAfkNumJnad7SNyMPhpIeh_EG_ARn8dKYCSFbqd9ws_Ic54j-qL22AbjJ38WUXJFvfGI_Mlb7XiI9aDtUkaM3rJvdBbNoyMp8zAqk3dSli3IP1SMIQ8WTgOCGzwSfZIC7JecAld0KCPc_3pUdcF1MXvNW6kdWXI7SM6ozurbW7bf5tZJGMNMWJGklfLZnc2rm6MhdWb_S-TV4FaZ2GrzS8ZooFCfVabCKk5fOKshpkLq1Yi5vn9fpgALihG52BVi4uUCBcDrY0TbOlxZOWbRmnZ66Tq8qDWvp-eB1dpumN1r7vWn0Wl45rE4Q8DzmACYwJCLd8QFbdNgQrg2e6ulyoqEjSKKlj1J5WD9GjZF6nkoFHnmXRQqNOQSZQrhibjQHnYRq1bJc6KMAed5VtY9sPJUIe5Iah9KFQIMQhTCofUg4K9RtD0nV8yB0l9pmSXHGk3LYSuCslwOta0NQBvlZJ5DLV52D-fOVhHbBVcgU-EYaW4Do1E1cjTK2BbW2ThLQSfzDKNC4LnQrKiSFwdJlFV1fg-4S1FLiBMAe5dRFoLsmv5wrjqloT2sac2m9ai5e_QH7puG0X3Vznx9RaXFhvFCRQHTG9YuS667VKblFTUnh284n-xSwyH6FWEK-ujVc6NWItzVyjwqruEVqiOmhh1SctTJoVqcfLUGS3tet05-hkb2SOK6VLf7UfianmzmEs8mut2zoVv7guk-umjkHJ6Xss9CEABALqDpcp2yU8hAiAQdfsgArMQPMQg4wWslUssYtDHAY08JFYL0lxS8caSkV7HMsXzR1z_BP8OhiYTKfKqi5FAvUE6gVZsUqXKjqaipqe6mbwCtS4B7HO6BHlf7dMtbVMqk6m0zLRWx2AsZrICkp9wbZGXCVhfYxHnWZ9pt8bolcJXIaFzctYQCic31k70zJWRcumgUZCfJuEigswbgL1G7GVraTwERQItic9FRJJfN93IZuyOQ6oZwe-bjdjJlr8Js0GDLPbDZgO570fgQ-Eyr4MriqTeIXYIoKu7mGuedWKVrNTavpWob5IMHqlFRxAzZ35ZvNlb9nS0Q5eSxFXrvW0UYzo7LwuLgFHO0r0cL6r9VLbifb0Z0pcjw6gaNAp3C5YAihQMaqOz4GWE6_-3BF43aZ8PC9wFXYF9wPPUT7zJffCUHI3VOBdA8-TzIZfKHNcl2JBJAzyEQmFhCoQ2WJg4LXOt8-bsvN67EMf-IfsPrde4aWbs8BooJZGpkuy8Mgjj7WbXprY0SuKOztkr0iVOi1frNBqn9EhYXq5xFfMlCmtWrNHht0Nkr0ok7GxnUMlstGFmM0mZr06XjddVYgJdwRTlNq-EC4YEVTQUHxBNRKEUIUgF-pugTiHykz5IVQcIXddkJgHpYcdrruqRvcMt2Me8rrahCaNMNemNcMMna0mZWUKi04j6hJHFRxbnS2ImLgjYr7CtX3p3xrCcUhPc62jiG6dcRi1vhmdclp2vluG4SPej3bY4NdIFmkG2VCVvOSquCc4DsWy8KEIZETKIHSVcKkfBODoMJQntm8rAXbm-dJlOAg9GvqBchBBzCcgc9puOru8YUhNGbYt6BjoQ3VqAWbQtpVXhLfl8AoTpH9ZnJTQiaMmQndGGrrddlRLC3iwKHeHF-XIeYGk0fGhwlPIIUJzkChFFPcwRYHDPEkcpAJku1L6kEpCThm40uFMEPOBIRt5bWaz_sqhN2dEOg8zylsdcriX_azeJvl_KQs0Vggc68gCjfYgm_SlgfZfkwb2aAnrsMIPqQCGQMU0G10U86sIqpWvUa5aVujaIVd2iJjt8RCpMESQw3mIOaHtChJQAnbnBVLvPduIU45sKCU9HNpUUo-L0V5W5iIAYemlrPcFlrqx84BeVEa548-htI6XxumwdiBrtA5N29FEIN3vyCep3vUhXr9NtkvR7jHkKTK5mOhVrmSyCnvYafkQEyObWtcnvu5-zgV4i0z3ORZ2_g1kOQNvko8-gVMCg8mLxaOvKi-MLq_1GAh_rMlAvVau42DEsaBhgP2AQ6pvc73TQFw7QMhWzPE9ov228qUSnm9LgcCT-A74ZAGga5uBdnd9ebSt_9Ueo5Xw4LZmtAJuZfyLQErdVnehLW4QZWgOF-k3B2Vmc6DdyYZ8xVQK2pX3pzznKoxNz8pEAezYjWErc698UWXfKoMyrRHwrSCFBNtkvnN9fGJYUsu76rjdtCjSqalajjKhX_vSruFOyzxvN_kEwz4YrcehePCguLA5ZD0QV8HhixCiqxcI7Cp94sR3BZi7QCxUHob6w3Mc7rabfMzrKeIc-ylFXPXCGrA2tJYjmUbgIovUzdH--qzC0a7Pql0gkNhUn5XWqb6REoSKMu-1Oa-Lzwd3Ygrl0HKD4Bdwbm1OfxMx-LxWdIUQKgPPp0qBP1VgLD5jEtKYEEsv1C1w4SjN3RBzrncIMJTJNhRyIXjWALejq9PHaYqewumqaz_CrWR0yU-9FdPP4cNMqT-U8V0m-jyhFsbdTQilCpMf17WmqfaWTIVSVN1E1TKamb3DfZcSGnoe84UPfsjlCCIUpg63qVCISKiPpX4LsE2YHWBpS-pAicyQwoFsNyEY7WtC2Gu7aWwVaXam-lTkQi9BbU-S3GzaLjVVmyI4iCbzzEueNK16nwzZdSKSW1GodTGoM_LFqC4M6-chHkTUTO3XAPtE1HVW5DTN_Ciwfk1KeR0rSBeUiCF3qO4erPrbhJMH-tuo1azmnDjKFqEXSsEIsh3JIAsNEbahaqa-zyG6IL1nxnwnYB6QAVmHAv8kAsSZMyTlhHpZB5LeEGIvkvxmUk9Nd6HuRy9Seo_dK1f5gH6HPjrSFz6W9kl5Vye8nrlHRrinpRTlU-uoFFkAydxoJ5MTwPSrdod1SFn0NiBl7e1tkHspwqMZQlOwgetxnTB6lLs-QS4hOngQX9k-wk7IhfBDSV0GhghVuAiwTXUfEdsKPKMd8PXCrUuwJjt4qJZAjxwaADkbwWgMWmrLQkKfDbD06ejVloL-Ziow4_HOq7f9Vj5KZ3v1jprZFG_DmFpurS9moKt9hsbecq11TTV0NtqmwqQzaCW1h170ukxR2c4PdNrUNE8FcV8oGysRQm3NKUhKEK6g-vaxJ6WguhDgoStR4BNHEAXpAiR_AZNChZ5cP_PV412dJ3jXZijX2y86b8pMRK_D2-pVzBWBMObQFEdt0GXS9blUpTKdxsWcy2Lb6ES9h_RYcLuI08VLGFe30penCxfvJ22MqlCRxiDv_qDFta7l8Uh0f8yu0if8l1hY31ROAw25P2jxjowlItyHqEHY8o3A9wY1jn4i3jeoeQCzA9PqjstyPtw7avFWpcXQDm6aVzQ05-xgQ-vu9HKg24OsKWPahcy8NWkxpIMPVZu_gWX5Vs_qdGfvyc7mgc4ubmhmrNXLTQ2wF-dduxi5BoaHgd1X9_u82HBFXcQ8siptFU8E6bXITqXsWhPZjMHDuIBfCIxutki22WwDwbq4iR6RcJdCPSKBysk9daIOVWKbzPOI_vU5-wGYyeZ2hDahhG6mDGgz1aOPy-d-AOxg7VPxdinYhpQPcj0dEfrxBW3gB8ljdC9D4BMF2M3mjTTM2QRokFXeT3GG5TgDKHU2ZizeQBXZZtZENtNg8nQ9o5v7_g20Gm3MfDLEODsS2mEZ7aMLf0YSNFCW9xPowYJgGyjm5pJ4hsYMdcztKuFBw-ksKAbL5hHO9RUjA9wM3pi_G7qM4QK9XzMNoIcM4FRHpTVYEnRjfjmbxLshJnOvKBys548sqbegfFNXlOY6o-lPmv_hRJqE0RWMePdm_X8N-r9BgdQv
































Sincerely,

 - Albert Hor, MD

CHPG (Centura Health Physician Group) Hospitalist

O: 719-776-8040

F: 719-776-8050

C: 720-839-1001

________________________________

**Comment by Wires77** [comment]
You have Vaal Clarity, which gets turned on by default on import.

**Comment by ahor25** [comment]
Trevor,

Wow thank you.

PoB is so complex, it can be overwhelming.


Thank you for helping me.





Sincerely,

 - Albert Hor, MD

CHPG (Centura Health Physician Group) Hospitalist

O: 719-776-8040

F: 719-776-8050

C: 720-839-1001

________________________________
