### ISSUE TITLE
Allow Adding Numbers (1/2/3/4) on Ascendancy Notables for Sequence to be Assigned

### ISSUE THREAD

**Issue by dsnvwlmnt** [PathOfBuildingCommunity/PathOfBuilding#3822]
For example, a Combo Box on the notables on the tree would work.

**Comment by randomflyingtaco** [comment]
This is currently accomplished by having multiple leveling trees saved under Tree>Manage trees...
Why would adding numbers specifically to ascendancy notables be better and why would that same reason not apply to a similar request like numbers to indicate the order for assigning all passives?

**Comment by pHiney** [comment]
For all the work required by us, it would be easier if to just add it to the notes. I notice that many streamers don't use notes, possibly believing we all have good judgement to know what to do or to make us watch the video.

In the case of the last, they are unlikely to use this facility still.

pH
