### ISSUE TITLE
Pure Talent's Marauder modifier does not parse

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#3830]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

`Marauder: Melee Skills have 15% increased Area of Effect` should parse properly

### What is the actual behaviour/value?

`Marauder: Melee Skills have 15% increased Area of Effect` appears red, means it's not supported.

Issue is that:
`["^marauder: "] = { tag = { type = "Condition", var = "ConnectedToMarauderStart" } },`
`["^melee skills [hd][ae][va][el] "] = { tag = { type = "SkillType", skillType = SkillType.Melee } },`
both have `^` requirement and that means they need to start the line.

### How to reproduce the issue

Copy/Paste Pure Talent jewel from PoE Trade using `Create custom...` item interface or just select it by name from unique items.

### Build code

```shell
https://pastebin.com/0cbSiDi3
```

### Screenshots

![Blah](https://user-images.githubusercontent.com/1735956/145132177-b0fa2310-bc85-4bba-948b-8ca4d3a61147.png)

**Comment by Lothrik** [comment]
Fixed by #3875.
