### ISSUE TITLE
Misery did not work in pob

### ISSUE THREAD

**Issue by Luibii** [PathOfBuildingCommunity/PathOfBuilding#3831]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The Endless Misery did not work well in pob,the cooldown of Discharge keeps 2s intead of 250ms,please fix it.Endless 

### What is the actual behaviour/value?

The Endless Misery did not work well in pob,the cooldown of Discharge keeps 2s intead of 250ms,please fix it.Endless 

### Build code

```shell
https://pastebin.com/2CwR3S5f
```

### Screenshots

![_ Y 5Q DQV19BL 2 CSILP8](https://user-images.githubusercontent.com/95377484/145139474-395029af-73ba-45d0-a181-1d333bccbc98.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3832.
