### ISSUE TITLE
Defense stat of unique items is off by 1

### ISSUE THREAD

**Issue by gilic** [PathOfBuildingCommunity/PathOfBuilding#3837]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Crown of the Inward Eye armour is 1151.
Atziri's Step evasion is 834.

### What is the actual behaviour/value?

Crown of the Inward Eye armour is 1150.
Atziri's Step evasion is 833.

### How to reproduce the issue

Imported from my poe profile.

### Build code

```shell
https://pastebin.com/ULtxRJ6U
```

### Screenshots

![image](https://user-images.githubusercontent.com/6068294/145558126-dace2453-c82e-42ae-8121-040847b26134.png)

**Comment by pHiney** [comment]
On a test of One, I added the Crown to XyllyFireBurst and it imported correctly
    https://www.pathofexile.com/account/view-profile/xyllywyt/characters

pH

**Comment by QuickStick123** [comment]
This is fixed as copying items from ingame or trade produce correct values in pob. The existing item in the linked pob has an invalid base percentile.
![image](https://user-images.githubusercontent.com/31533893/180673364-ad342a7f-b5c9-41c7-a09b-db816739937e.png)
