### ISSUE TITLE
Arcane Surge buff is not granted from Tree skills

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#384]
Last mod not parsed

```
5% increased Attack and Cast Speed while Channelling
Channelling Skills deal 20% increased Damage
Gain Arcane Surge after Channelling for 1 second
```

**Comment by LocalIdentity** [comment]
Other mods that grant Arcane surge that are not currently handled
`Gain Arcane Surge when you Summon a Totem
10% chance to gain Arcane Surge when you Hit a Unique enemy
Gain Arcane Surge when your Mine is Detonated targeting an Enemy
Gain Arcane Surge when your Trap is Triggered by an Enemy`
