### ISSUE TITLE
Supreme Ego incorrect aura effect calculation (Max Resist from Purities)

### ISSUE THREAD

**Issue by Irfy** [PathOfBuildingCommunity/PathOfBuilding#3841]
Level 23+ Purities provide 5% max resistances. With some additional aura effect this is mutliplied by 1.24 and rounded down to 6%.

When Supreme Ego keystone is taken, it is supposed to increase that value multiplicatively by 50%: 5% base aura vaule * 1.24 from other sources * 1.5 Supreme Ego = 9.3%, which the game rounds down to 9% max resists.

However, PoB shows this as 10% max resists, inconsistent with the calculation and the game. The rounded-down calculation of 6% without Supreme Ego is, however, correct, so my conclusion is that Supreme Ego 50% multiplier is bugged.

PoB version is 2.13.0

### Build code

https://pastebin.com/R3cZAU7w

**Comment by Lothrik** [comment]
Supreme Ego no longer works like this, and the new "more Aura Effect" modifier is not supported currently.
