### ISSUE TITLE
Delete All Unsused

### ISSUE THREAD

**Issue by jix91** [PathOfBuildingCommunity/PathOfBuilding#3845]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Not related to a problem.

### Describe the solution you'd like

In the Items list you currently have the option to Sort, Delete and Delete All.
I think that Delete All is a bad option. What I would prefer to clean up my POBs after testing stuff is "Delete all unused".
This would delete all items, that are currently not equipped and have the (unused) tag.

### Describe alternatives you've considered

Removing the Delete All button,

### Additional context

[Reference of Options](https://i.imgur.com/UFmG1wh.png)

**Comment by pHiney** [comment]
What interaction should we have if there are two items sets ? 
In case you don't use them, the items in the not currently selected set has "Unused"
