### ISSUE TITLE
Cant import character on PS5

### ISSUE THREAD

**Issue by kraurFU3RS7** [PathOfBuildingCommunity/PathOfBuilding#3846]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

My character should be imported to PoB.

### What is the actual behaviour/value?

I can find my characters if I type in my PSN Name. But when I select one of them and press DONE, I just get back to the former display with "character status: idle" on the top.

### How to reproduce the issue

You can try with my PSN Name kraurFU3RS7

### Build code

```shell
I dont have one.
```

**Comment by Wires77** [comment]
Clicking done just brings you back to that screen.  When you want to actually import things, you need to click on these buttons to import what you want:
![image](https://user-images.githubusercontent.com/1209372/146810435-7fd762ec-e0c2-43d0-9f8d-080efa0868a0.png)

**Comment by kraurFU3RS7** [comment]
Oh sorry. Stupid me and thank you for the help.
