### ISSUE TITLE
New Blade Flurry Enchantment - +1 to maximum Blade Flurry stages

### ISSUE THREAD

**Issue by eliaeatsfood** [PathOfBuildingCommunity/PathOfBuilding#3857]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Dear PoB community, there is a new Blade Flurry Enchantment - +1 to maximum Blade Flurry stages. Gem description says - "20% more damage with hits and ailments for each stage". At this moment PoB can only calculate 6 stages. 

### Describe the solution you'd like

It would be great if you make an option to add in main skill window (top left panel) an option "release at 7 stages" for new Blade Flurry enchantment, because 20% more damage makes big difference in calculating DPS.

![Screenshot_96](https://user-images.githubusercontent.com/96653716/147795440-7efdfc22-5d95-44ef-ae5f-11f261a06b8a.png)

**Comment by QuickStick123** [comment]
Fixed by #3859
![image](https://user-images.githubusercontent.com/31533893/177662234-6f56a26b-7dc5-4d2b-b340-9c111b7d8652.png)
![image](https://user-images.githubusercontent.com/31533893/177662260-7144080a-486e-4995-87f5-4ce4cca76002.png)
