### ISSUE TITLE
Trim trailing whitespaces

### ISSUE THREAD

**Issue by dovry** [PathOfBuildingCommunity/PathOfBuilding#3870]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/15201298/148528282-69b0fbe5-6c2a-40ff-9591-f557f72f1014.png)
![image](https://user-images.githubusercontent.com/15201298/148528312-26708292-c154-4735-8011-0a30aab20ee4.png)

### Describe the solution you'd like

Input fields should trim trailing whitespaces

**Comment by pHiney** [comment]
There are a few places to enter data/names.

This could be the only one where an accidental space could affect things.

Any suggestions for other locations ?

I could see someone wanting a space on build and tree name.

 pH

**Comment by dovry** [comment]
I’m not a power user so I haven’t a clue for other input fields this affects.

Since there is no visual indicator for (trailing) whitespace I would argue that you should use any of the hundreds of ASCII symbols available to you, such as “_”, to append to your build name instead of using spaces. 

PoE for example does not permit spaces in character names, so you resort to using underscores and the ‘ • ‘ character that has some spaces built around it somehow
