### ISSUE TITLE
Using Relic of the Pact + essence worm causes an error.

### ISSUE THREAD

**Issue by rockfroszz** [PathOfBuildingCommunity/PathOfBuilding#3941]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should be able to see what essence worm does with relic of the pact.

### What is the actual behaviour/value?

I get an error message

### How to reproduce the issue

Equip essence worm
Equip Relic of the Pact
Mouse over either one.

### Build code

```shell
Version 2.13.0
```

### Screenshots

https://imgur.com/a/6XO0Xwp

**Comment by Wires77** [comment]
Duplicates #3796
