### ISSUE TITLE
[Question] Skill Tree search function.

### ISSUE THREAD

**Issue by OmikronGamma** [PathOfBuildingCommunity/PathOfBuilding#3943]
Hello,
Can i search skill tree for multiple "tags" at once?
For example, i want to search for life, evasion and cold nodes. Can i do it at the same time?

**Comment by Wires77** [comment]
Nodes on the tree don't have "tags", the search is done via the text on the nodes.  The tree search supports Lua pattern matching (https://www.lua.org/pil/20.2.html) for more complex searches.

If you want to highlight all nodes that contain the words "life", "cold", or "evasion" you could use this pattern: `[lce][iov][fla][eds]i?o?n?`

If you're looking for all three of those on the same node, I don't think a node like that exists.  To find the evasion + life nodes you could do a pattern like this one (you'll have to flip the words around, as some of the nodes have the words in opposite order) `evasion.+life`

**Comment by OmikronGamma** [comment]
Thank you.
Is there a way to exclude stuff like "life on kill" and what not, and only include "max life"?

**Comment by Wires77** [comment]
Not easily.  You're better off just searching for "max [lce][iov][fla][eds]i?o?n?" and it'll find the same nodes, but only the ones that have "max" in them.

**Comment by OmikronGamma** [comment]
Understood, thanks again!
