### ISSUE TITLE
Pious Path Ascendancy from Inquisitor gives ward regeneration

### ISSUE THREAD

**Issue by hgfedcba** [PathOfBuildingCommunity/PathOfBuilding#3944]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Pious Path shouldn't interact with ward

### What is the actual behaviour/value?

it does

### How to reproduce the issue

I just took pious path, activated discipline to get some es and then it says I regenerate ward.

### Build code

```shell
https://pastebin.com/s02VJauv
```

**Comment by borisbsv** [comment]
Your pastebin link is not working and I could not reproduce with this bare-bones setup `https://pastebin.com/jKFR8ZL0`

**Comment by hgfedcba** [comment]
You are correct, I don't know why it doesn't. Even when I export it again with pastebin it doesn't work, maybe another bug you want to look into.

You skipped the step "activated discipline to get some es" that I included as it is vital to have some energy shield. Just get any energy shield and your setup is buggy, too.

Here is the link to my build without pastebin eNq9Wv9v4joS_3n5KyKkO91JLZCEUMrR9wQt7SKVLQ_a3bufViYx4Fdjs7ED5Z3uf7-xEyDtFjrknW5X6obwmfH4M188423715cFd1Y0VkyKq7JbqZUdKkIZMTG7Kj893p43y7_-UmoPiZ4_TLsJ4-abX0qf2vbZ4XRFOciVHU3iGdVft5r876BpSYSeUykG5HcZ38noqvxFClp2JkRETG8_hZwo9YUs6FX5kS6WnMRlh6iQiuh6_01f_EiYYlrClwvCxFiGz1TfxTJZ2uVXjK4HMjLIwfBh9JhbnIn84mD7p_aQkw2Nx5poR8GPq3IHKCAz-plpUEV4Anpq5epR7A1ZwM-P4eMlpdH_GzaMaW86paFmK3odM309JyJEGHsqdpBwzZac0XiHdyvBIYnPPyl3awfVP0pN-M1w_LEhpyIlwsnfmJ53OXCN0mvQ_ZlgmqLhQ8mUFCdZjQJfy8WECaTdW3BnNcOAJY_kWuQ87XnuwSyJKXmYpkE4IhFL1E4uuDwkNCCCXEuF8M89m1IcsjfG4UaQzTiksXJIY6hQGm_sSQJjvc8nzz9oMf2RBx7UdkNf9j6rH9GWBx7U1hcaZ1se6AbBYetWUsOZgaNxh2q4R0pk2DLYvghxSp9ETBWNV7nKelj9a4HMrZiCZgRHdEb3Ow0qbjM4Br-nNJzfwXE3IpriAnOv_DhBBosiyADfIcj3cQJvCWrUKxe1oNn0_MC7rLvHlLwmq1Y5WjZOpOobiRHHaE_QeLYZzxnle7TnNY4ymxdCMZwXOCFA8mIn7r63Iiqfcm5wfEcpHBcuFE5NEIgoto84XWIYy99Nb8NPE-vEC5nEqB4rbKVg1JaH841iIRzRtiMc0SgJcQVt16IN5IouIEtsdwdt7N4xh0S7HBpg7MZBLecnSXS0JuHzjYxm9KRFTpcYJ8sl1AoTX1i5WxYDy4rlTtLzBgL9AI37NVliOh2TiNgF9mj0AvdsNtcCJin8Km9E8HuZE6lO2Mwejl7iNuG49nv8zF4jNZlw2nJqL14t9JqXbvNgisk1GDM3M6ZCJGQOPSD7nubgkXUbU_HHBq3_FRy1QE9ESWyiG73GW4mfl2lX7QxunvqLpYy1fXlNeKisyr5YJtoRdnxeMBV-nyTTqZmRy7BEbAf83u1t7_qx_7WXWZEXUcZZ30WymJjhLv13X5DG1NY4J5Sck6WiMF5PCVegm0WZo8dQ10ONwsNgmI3TGDSc3WHMgEQM2Ex7KJPtYI1BmrkXBQSvEE7xhD1ultREgMJylhVMDNrOsihkOpjiNmhHXpwbaEg2KOSulUGhe5x2GDdnJ461ASRCeuzi8HAQxmySaGS02REFZYdp1VEbzLegyOzAAbN2CGVE1i9isNlZgwtKaEnQbruhUwrhjkx7W04eyTMVWbHcFsa2zTXlKKiYd3Shuhs4kW4NvW8uT14B4KyKE9Ad0SlJuHn_W0I40xtTwnNv79MLUQ9eqrlcm-4mVWOSWwHp9_fpNx2uMw1mja3t6c6MgfaWs2O7Q_vZmm-vOpkIeRLBdJudu7t9czIxa5edmbkWvZaJgHNEMG6udM1BG2038Ua10WoW_tQGUzLsHZcTwr297v2-8gB3q9KeFn1DPHjK3Aiam90f6Qbt65ShDDgksbZ7mdGF-XZANYmIJtW-BjKqhpGqNQ2e3lFoOX-zp53ePVFhygA8mRPNdPWvzEvDKF3HRkgaGObxMabUISlDVszNPAMf8nfTxnbX8Kk0jTdZXTEeEHDMKnOLEHjBme813caZf3lxWTtruM0L9yy48DzvzK01_KDsaFgsd2_uNrIrcaM8yBzTi6DQRl-M1mr65ml0bx8-zbVeqla1ul6vK0ui53JKX2AyqoRyUV2CGtjDuSXn3CxU7cCf7uyp2-131gvvYjpni3t4dWWVVrda2-n9utpyBPu2FBlizMMXCRXRfGdebj9Y2r4yunYUhSN6Ptax4eIPKRf_gtC5aFYumxd-9ifNgs-U6AFZ7sLMYLMUamQZBAfiDQNmY5v8W3cb4D-vyk0vqARNf6fUproNosx95nlM0yhIFIWiIUX0jZKlFPZ1Lu0M1NaOLBtGBA76Tct5-tL_7alXeuCx1PO_gqT6h3LSrqw0SgQLnTGUILBPq5Ipvi3H9V371CVqe-_HbJ8LBJTuKZkl8KH3sqTgVfB6KSsELcerlTLiW87duf1bsnSM6I-WU2-WoKXgLGTm-1rp39AfzmirVgn-87egdt6s_f0vpjjEFJaNHGPAK4hfOw8MRHHTHjtQp7WMia2hcprCvVpew3YqdWxvVDJnstOJwA_E5I8zlbHjg6sNo8pZz6mwSpwuiD8rG0XQbY6MAY41w9zhBOWM4iyMDyK8bX4at-z8Az474sa899pjLretbAp03PGaLJ3OZKMU4U5KtGOW02kVqm2Nekf0rZiHEzuO6kqpVUGD3tvLB0Z1KdcnitxCIXp2fJRJ3nsm-cXoxZHg_Y_E6sWMbBRbrVGczSLx9IEHPlPonvWpC70TSY0i63wQftBkrMywfLpiv3gWuUXWqxeLBbdY5NU_dg-G2FPVvhdeBTeOqjtBAXsK1ED_o2WijZMOSye6732WC8VXUEQIlZIYRxTaZ1CYVq-A3xvFMskvFr7-6VFWL172C8S0W5h8HxMQdQyogNl_ovlBerK4FxoForK4G_5EuGBLspFFZg0eWoC5ERMzXCdwcqE4SG_BcoH3Z5Ht-Aie3OJuqBdmKyiyG0y-FA_yD0zqLBL-ztmWjpMwMtrbDHtRYP_TRIopm_30XyBmyLQT-oMABEy6MC7TyPzSoYjKzkRKTonIbiSyS8ZMUbv69jcm_wtg_vGc

**Comment by Lilylicious** [comment]
This applies to all ES regen, not just Pious Path. Easiest way to replicate it is to allocate Zealot's Oath and get any source of life regen.
