### ISSUE TITLE
Spark's damage doesn't scale with added projectiles

### ISSUE THREAD

**Issue by Copperearth** [PathOfBuildingCommunity/PathOfBuilding#3955]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Spark's damage should be affected by more projectiles

### What is the actual behaviour/value?

Spark's damage is not affected by the added projectiles from greater multiple projectiles and other sources like divergent spark

### How to reproduce the issue

1. Use Spark/Divergent Spark
2. Add GMP

### Build code

```shell
https://pastebin.com/deRF4jQb
```

**Comment by Wires77** [comment]
The DPS for skills in PoB is almost always for single projectiles.  There are a few exceptions when multiple projectiles are more likely to hit or the chance can be calculated (barrage, molten strike, ice spear), but for something like Spark, hitting more than one projectile is not guaranteed (their path is random, not aimed).

If you expect to hit with multiple sparks, I'd suggest checking "Include in Full DPS" and adjusting the Count box for how many you expect to hit
