### ISSUE TITLE
Awakened Generosity innacurate with level 25 Envy Aura

### ISSUE THREAD

**Issue by rlav440** [PathOfBuildingCommunity/PathOfBuilding#3957]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

At level 5, Awakened generosity should give Envy 44% increased aura effect when socketed in some item providing level 25 Envy.
These items are united in dream, and grasping mail. 

The additional level should not effect the skill.

### What is the actual behaviour/value?

A level 4 Awakened Generosity provides level 25 Envy the correct damage boost.
A level 5 Gem will give the correct increased damage, but will drop the damage of any supported minions.

It appears, from testing, that the additional level makes level 25 Envy perform like the level 15 version provided by some elder items, when it should have no effect as this is a skill granted by the items, not a skill gem.

Testing with an elder unset amulet granting level 15 Envy had the base damage of the Envy aura remain the same regardless of the Awakened Generosity level.

### How to reproduce the issue

1. Swap to the Items tab
2. Add United in Dream as the main weapon
3. Swap to the skills tab
4. Add Summon Skeletons to a new socket group (to observe damage)
5. Add a level 4 and level 5 Awakened Generosity to a new socket group, inactivate both.
6. Place this socket group in Weapon 1.
7. Note the level 4 gem providing a greater damage boost to the Skeleton Minions.

### Build code

```shell
https://pastebin.com/Br6srQqp
```

**Comment by Wires77** [comment]
Thanks for the detailed bug report.  In the data, Envy only has three levels: 1, 15, and 25.  I'm guessing the gem tries to make it level 26, fails to find it, and falls back a level.  Does the damage go up in game at level 4 vs. level 5?

**Comment by rlav440** [comment]
Cheers.

I don't have the gem to test in-game.
It's also worth pointing out that it's odd that the level component effects the skill at all, as the wording is:

> +(0-1) to Level of Supported Aura Skill Gems

"Supported [...] Skill Gems" is shared language with the Empower support, which indicates that this should not effect skills granted by an item.
I've tested Empower, and it correctly doesn't effect the item granted skill.

**Comment by rlav440** [comment]
Just confirmed that this happens to other auras granted by items that are supported by lvl 5 Awakened Generosity as well.
This appears to be a neat little corner case.
