### ISSUE TITLE
Implement Arcing Shot Notable

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#396]
Both mods don't parse - sounds hard

```
Arrows gain Critical Strike Chance as they travel farther, up to 100% increased Critical Strike Chance
Arrows gain Damage as they travel farther, dealing up to 50% increased Damage with Hits to targets
```

**Comment by tmihor** [comment]
"Probably" works the same as Longshot notable, which is correctly parsed, so this should be really easy to get to work.

**Comment by Tasselli01** [comment]
Hi, I'm bumping this old thred because it's still not parsed on v1.4.170.26.

**Comment by LocalIdentity** [comment]
Added in 2.14.0
