### ISSUE TITLE
Constant error message upon equipping Relic of the Pact + Essence Worm

### ISSUE THREAD

**Issue by blvcksvn** [PathOfBuildingCommunity/PathOfBuilding#3963]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

No error

### What is the actual behaviour/value?

Error code shows up repeatedly.

Persists while Blood Sacrament tooltip is being shown

### How to reproduce the issue

Equipped Relic of the Pact + Essence Worm

### Build code

```shell
https://pastebin.com/GS7HVVLy
```

### Screenshots

![image](https://user-images.githubusercontent.com/8675122/151343954-59908e6d-0588-4cf1-b0fc-eefd6682a98c.png)

**Comment by learn2draw** [comment]
Duplicates #3796 
Fixed in #3952
