### ISSUE TITLE
Add Support for Primal Rhex Matriarch Spectre

### ISSUE THREAD

**Issue by andrewkhunn** [PathOfBuildingCommunity/PathOfBuilding#3965]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

One of the recommended spectres for Absolution builds is the Primal Rhex Matriach from Harvest as it has an AoE lightning debuff it perodically applies. As far as I can tell, it is yet to be implemented in Path of Building.

### Describe the solution you'd like

I'd love it if it could be added to the spectre library. Here's a link to the spectre-able monster on PoEDB:

[Primal Rhex Matriarch ](https://poedb.tw/us/Primal_Rhex_Matriarch#PrimalRhexMatriarchHarvestRhexT3Spectre)

**Comment by andrewkhunn** [comment]
@Lothrik I noticed you recently added several other spectres in another PR. Would you consider adding this too?

Thanks for considering this request!

**Comment by Lothrik** [comment]
Sure, I'll take a look at it later today.

**Comment by Lothrik** [comment]
I added Primal Rhex Matriarch (plus their Thunderous Roar debuff) and a few other things to #3932.

**Comment by andrewkhunn** [comment]
Yesssss, thanks so much!
