### ISSUE TITLE
Awakened Generosity's +1 level of Supported Aura Skill Gems wrongly affects item granted auras.

### ISSUE THREAD

**Issue by rlav440** [PathOfBuildingCommunity/PathOfBuilding#3968]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Awakened generosity gains +1 to the level of supported aura skill gems at level 5.
Supported [...] Skill Gems requires an actual gem to exist to gain this benefit.  

### What is the actual behaviour/value?

With an Unset Amulet granting some aura skill, socketing an awakened generosity increases the level of that aura skill.

(This might also happen with corruption granted auras on Unset rings that retain their socket after corruption via gilded fossils).

### How to reproduce the issue

1. Switch to the item tab
2. Create a shaped unset amulet granting some aura skill
3. Switch to the skills tab
4. Add level 5 Awakened Generosity to a new socket group, and place in the amulet
5. Mouse over the item granted skill and note the skill now has +1 level.

### Build code

```shell
https://pastebin.com/wXhRhvtL
```

**Comment by rlav440** [comment]
This error is (assumedly) partially responsible for the weird Envy behaviour in #3957

**Comment by Wires77** [comment]
Fixed by #3960 in the next update
