### ISSUE TITLE
Rupturing duration calculation is wrong

### ISSUE THREAD

**Issue by John-467** [PathOfBuildingCommunity/PathOfBuilding#3970]
The bleed duration calculation for rupturing is wrong.

The stacks are counted as multiplicative, with the formula : 
5 seconds * 0.25 = 1.25 seconds
at 3 stacks

The formula should be :
5 second / 1.75 = 2.85 seconds

The wording is "Expire 75% more quickly" meaning that at 100% more quickly we would get half the duration.

**Comment by Lothrik** [comment]
Fixed by #3927.
