### ISSUE TITLE
Atziri's Rule not a spell or area 

### ISSUE THREAD

**Issue by Pineapplecow** [PathOfBuildingCommunity/PathOfBuilding#3984]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Atziri's Rule isnt affected by AOE or Spell gems

### What is the actual behaviour/value?

Atziri's rule doesnt count as a Spell or AOE and Gems w/ those tags dont effect it 

### How to reproduce the issue

Put a Spell or area gem on Rule and it wont affect the dps 

### Build code

```shell
__
```

**Comment by pHiney** [comment]
#2597 appears to be dealing with this
