### ISSUE TITLE
The Simplest Calculations Seem to be Wrong

### ISSUE THREAD

**Issue by GlowingCrystallineEntity** [PathOfBuildingCommunity/PathOfBuilding#3988]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

PoBC calculations should match the game.

### What is the actual behaviour/value?

The calculations do not match, even in the simplest possible case.

### How to reproduce the issue

I would put this on a forum, but I can’t find one, and this does seem like a bug.  I’m on 2.13 of PoBC (even though 2.11 is the latest on GitHub.  This is what the program updated itself to.).

My own calculations in a spreadsheet were matching the game, but not PoBC, so I tried the simplest possible thing.  I ran a duelist into the first town.  On the default attack and Double Strike with a Rusted Sword, my own calculations matched the game (Scourge league), but neither matched PoBC.

I can lay this out in complete detail if needed, but I’m hoping that a developer can just make a level 1 and 2 duelist, and see the same issue.  Or tell me what I might be doing wrong.

### Build code

```shell
Any level 1 or 2 duelist.  Probably every other class as well.
```

**Comment by LocalIdentity** [comment]
You need to provide details on exactly what you think is wrong.

**Comment by GlowingCrystallineEntity** [comment]
Ok, here are several different examples of the same sort of problem – namely, attack damage calculations:

One:
Create a blank PoB build.
Select Dualist
(don’t add any weapons or skills or anything else.)
Mouse over the “Physical Attack Damage and Life” node.
Note that the “Allocating this node will give you:” text shows +19.5% for both Average Damage and Total DPS, as in the first screenshot below.
Select that node.
Now Mouse over the “Physical Attack Damage” node
The “Allocating…” text now says +34.3% for both stats.
-> This is not plausible – the relative increase of each successive “increased” node (of (about) the same magnitude) should be smaller than the previous one.  (in this case, the second node is even smaller than the first, so the relative increase should be even smaller.)

![1 POB Dualist L0](https://user-images.githubusercontent.com/11333261/151658578-7b86d3e9-9781-4cb8-88b4-effee08273b8.jpg)
![2 POB Dualist L1](https://user-images.githubusercontent.com/11333261/151658584-98b659fa-8bae-4c2b-ab33-089ad3e59fc4.jpg)

Two:
Now go to “Items” and craft a 0% quality Rusted Sword, add it to the build, and selected it as Weapon 1.
Go back to the Tree, and again, the relative increase numbers make no sense:
-- on L0 (the first node), we see a 32.9% increase
-- on L1 (the second node), we see 8.5% increase.
At least the second is smaller than the first this time, but that first value seems implausible.

![3 POB Dualist L0 Rusted Sword](https://user-images.githubusercontent.com/11333261/151658612-ceef6060-d53a-4317-81f5-ee273c8fee40.jpg)
![4 POB Dualist L1 Rusted Sword](https://user-images.githubusercontent.com/11333261/151658616-253f598c-4e21-4568-b53c-97751a41f411.jpg)

So, let’s get some stats from the game.  I’m not going to recite these in text, but you can see what the game reports for the DPS values for the Default Attack, and Double Strike with and without Chance To Bleed Support, and compare to what PoB reports, and see that they do not match.

![5 Dualist L0 Default Attack](https://user-images.githubusercontent.com/11333261/151658634-bd17fc5e-9f01-4b98-8936-b5425ab84479.jpg)
![6 Dualist L0 Double Strike](https://user-images.githubusercontent.com/11333261/151658635-63c078d4-e569-477d-b0bc-acf1a464b7c4.jpg)
![7 Dualist L0 Double Strike w Bleed](https://user-images.githubusercontent.com/11333261/151658636-4624db88-c3e9-417b-b6b6-9a98d33a7ba7.jpg)
![8 Dualist L1 Default Attack](https://user-images.githubusercontent.com/11333261/151658639-cd9bc68d-e56f-45fa-a4bf-1dcfc0ea6846.jpg)
![9 Dualist L1 Double Strike](https://user-images.githubusercontent.com/11333261/151658640-721462a9-a51a-4704-a403-95381a42aaf6.jpg)
![10 Dualist L1 Double Strike w Bleed](https://user-images.githubusercontent.com/11333261/151658641-f21713d9-43aa-4130-91f6-cd8554f98256.jpg)
![11 POB Dualist L0 Double Strike w Bleed](https://user-images.githubusercontent.com/11333261/151658642-3bed9603-327b-4e58-a90b-b54f849a080e.jpg)
![12 POB Dualist L1 Double Strike w Bleed](https://user-images.githubusercontent.com/11333261/151658644-1d197016-66dc-4f95-9ff3-88dfcbb8063b.jpg)
![13 POB Dualist L0 Double Strike](https://user-images.githubusercontent.com/11333261/151658645-87c1b922-b5bb-4f23-8481-406bf0eb4cb2.jpg)
![14 POB Dualist L1 Double Strike](https://user-images.githubusercontent.com/11333261/151658646-7ae96b6c-4bb7-4fdf-a342-560ac1079171.jpg)

Three:
For example, for L1 (one node allocated) Double Strike with Chance to Bleed Support, the game reports a DPS of 21.6, while PoB reports “Total DPS inc. Bleed” of 18.9, and other nonsensical numbers for the other damage stats.  (I say “nonsensical” here because I also did this calculation manually in a spreadsheet, and I get the final number that the game gets, but nowhere along the line do I get any of the numbers that PoB reports.)

Four:
It looks like the PoB Level is affecting the reported damage as well, but this guy has 100% chance to hit throughout, so that shouldn’t have an effect.  What’s interesting, is that in some cases, the PoB Total DPS number *with* the first passive node allocated, comes close to matching the game *without* the node allocated… but if you look at the character sheet that shows xx.xx, it doesn’t actually match.

**Comment by Regisle** [comment]
This is because PoB takes into account the average armour an enemy has at that level, in the case of your frist screenshot:
![image](https://user-images.githubusercontent.com/49933620/151659767-61220773-2efe-43e6-ba9f-60e7a2b6e14d.png)
increases in physical damage reduces the effectiveness of armour, so an increase in phys damage will give more than the actual increase, because the enemy phys mitigation will be lower, eg after the first point the enemy phys mitigation drops by 3 percent
![image](https://user-images.githubusercontent.com/49933620/151659829-bc16eeb6-81f3-468f-b63e-94eea5491823.png)
and the second node drops it a further 5%
![image](https://user-images.githubusercontent.com/49933620/151659840-eddb2728-c649-4a90-87fb-d526af51344d.png)
because your hitting harder and the armour calc cares about the ratio of your damage to the enemy armour

this is likely the issue with all of the calculations, so its not PoB which is wrong, if anything it is giving you more information than ingame

**Comment by Lothrik** [comment]
Rounding is also a factor here. At extremely low damage values you can easily reach flat damage breakpoints resulting in a node giving more damage than expected.
