### ISSUE TITLE
Unable to update from 2.11 to 2.13

### ISSUE THREAD

**Issue by Agency79** [PathOfBuildingCommunity/PathOfBuilding#3996]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Clicking the "check for update" button results in me being able to automatically update to the latest version (currently 2.13)

### What is the actual behaviour/value?

After clicking "Check for Update", it goes through the list (1/61, 2/61, etc), and eventually ends with the message

"Update check failed!
One or more files could not be downloaded.
Check your internet connectivity
or try again later."

### How to reproduce the issue

The previous explanation covers the steps I use to reproduce the error.

Steps I've taken to resolve this:

Running as admin
Installing as admin
Disabling my firewall completely
Manually adding PoB and update.exe as exceptions to windows defender
Deleting all saved builds + Uninstall & reinstall + reboot

One thing I noticed that is likely related to this issue:
When starting PoB after a fresh install... on the green screen that pops up...  several downloads fail and return the error "SSL connect error"

FWIW, PoB installs and updates normally on a separate computer in the house.

### Build code

```shell
https://pastebin.com/WbMpXdV7
```

### Screenshots

![ssl connect error](https://user-images.githubusercontent.com/98681973/151689886-88e5a43c-5ec3-488b-99f5-38cfe719cfe6.jpg)

**Comment by Lothrik** [comment]
Kaspersky Internet Security blocking the connection seems to cause this issue for most users.

Apparently disabling that Kaspersky temporarily, whitelisting Path of Building, or replacing all instances of ``https://`` with ``http://`` can fix the problem.

**Comment by Agency79** [comment]
I don't have Kapersky. I did whitelist Path of Building in Windows Defender, however. I did change all instances of https to http in one file, per a recommendation on reddit, but that didn't help.

**Comment by Lothrik** [comment]
Honestly I have no idea what could be causing this if it's not Kaspersky.

It has to be something interfering with the connection, if you can narrow down the differences between the computer it does work on and the one it doesn't that might help.

**Comment by HurkWurk** [comment]
side note on disabling windows firewall. do not disable the firewall service. instead, go into the firewall and network protection console and turn off the firewall for the type of network you are on (domain/private/public) and test that way. 
Simply disabling the windows firewall service will leave it in a default state where it still prevents many activities. 
![image](https://user-images.githubusercontent.com/53104384/151709637-3df98ca7-6450-46b3-8945-c3b7607a112b.png)

**Comment by Agency79** [comment]
Thanks for the suggestions - no luck yet. The other computer (the one where PoB works normally on) connects via ethernet (my computer connects via wifi), so my next guess is that my issue is related to my internet connection. I'll follow up once I've tried couple things related to that.

**Comment by Agency79** [comment]
Replace every instance of "https" with "http" within PoB's various .lua files.
Connecting to the internet via ethernet instead of wifi, using all 4 ports on my modem/router.
Temporarily disabling every form of security my computer has (which I'm aware of) via Windows Defender, Network Settings, and Internet Options.
Toggling all settings that look related to SSL/encryption within internet options and reinstalling.
Checking for driver updates for my network adapter.

FWIW, the last time I played was in Ultimatum, and PoB installed/updated normally at that time on this PC. The only major change to my computer since then is updating to Windows 11. That was the old PoB+fork, and obviously now I'm working with PoBC.

I guess looking into Windows 11 changes that could impact this would be a decent place to check next. 

I'm open to any suggestions. I strongly suspect I've missed something very simple that's causing this.

**Comment by Wires77** [comment]
The browser doesn't matter for PoB updates.  Have you checked the proxy settings within PoB itself?  Sometimes those accidentally get set and screw up web requests:
![image](https://user-images.githubusercontent.com/1209372/151887287-cb4aebfe-c0ab-4ace-b7b4-2c5b5fe2dfe5.png)

**Comment by Agency79** [comment]
> The browser doesn't matter for PoB updates. Have you checked the proxy settings within PoB itself? Sometimes those accidentally get set and screw up web requests:

**Comment by raylu** [comment]
shooting in the dark here: is your system clock approximately correct?

**Comment by Agency79** [comment]
> shooting in the dark here: is your system clock approximately correct?

It is, yea. I resynched it during troubleshooting to be sure.

**Comment by Agency79** [comment]
![update](https://user-images.githubusercontent.com/98681973/151888892-232d1161-3b54-4afe-8eec-b08ae352a24d.jpg)

I turned on my phone's wifi hotspot, and connected to it. PoB updated within a minute. WTF lol

Since I was able to update PoB on another PC, and wasn't able to update it on this one even using the same connection I assumed the issue wasn't with my normal internet connection. I guess there's a more subtle problem.

Whatever the cause, I can easily use my phone as a wifi hotspot to update lol

**Comment by HurkWurk** [comment]
if that is the case, i would 100% suspect DNS servers on either your device or your router as being at fault.

**Comment by Decnalabnu** [comment]
![image](https://user-images.githubusercontent.com/3722439/152288277-9357f4f8-f103-4bbf-ba86-d24d56a95443.png)
I'm also having this issue and cannot swap to a hotspot easily. .  Like the previous user I'm also on windows 11.

![image](https://user-images.githubusercontent.com/3722439/152288205-15202603-26de-4369-8846-c828016f0c41.png)

What is the expected behaviour/value?
Clicking the "check for update" button results in me being able to automatically update to the latest version (currently 2.13)

What is the actual behaviour/value?
After clicking "Check for Update", it goes through the list (1/61, 2/61, etc), and eventually ends with the message

"Update check failed!
One or more files could not be downloaded.
Check your internet connectivity
or try again later."

How to reproduce the issue
The previous explanation covers the steps I use to reproduce the error.

Steps I've taken to resolve this:

Running as admin
Installing as admin
Disabling my firewall completely
Manually adding PoB and update.exe as exceptions to windows defender
Deleting all saved builds + Uninstall & reinstall + reboot
Flushing and Re-registering dns

One thing I noticed that is likely related to this issue: Same as previous user
When starting PoB after a fresh install... on the green screen that pops up... several downloads fail and return the error "SSL connect error"

Build: https://pastebin.com/vvv4ebaw
