### ISSUE TITLE
Ancient Skull increasing minion cast speed by 50% (it should only increased Attack speed and damage)

### ISSUE THREAD

**Issue by dejrons** [PathOfBuildingCommunity/PathOfBuilding#3998]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Ancient Skull increasing minion attack speed by 50%
Ancient Skull increasing minion damage by 50%
Ancient Skull increasing minion cast speed by 0%

### What is the actual behaviour/value?

Ancient Skull increasing minion attack speed by 50%
Ancient Skull increasing minion damage by 50%
Ancient Skull increasing minion cast speed by 50%

### Build code

```shell
https://pastebin.com/Y4Gk5Xzk

You can compare how Ancient Skull works with "New item, Eternal Burgonet". 1st one is without cast speed and makes the build deal 19.5% less damage, second one with 50% incr minion cast speed and makes no difference. (actully there is 102.5dmg loss from 4,025,670.6 dmg. I assumes it comes from rouding)
```

**Comment by Flashforwarcl** [comment]
![ancientskull](https://user-images.githubusercontent.com/15824226/151951555-6146e391-96ee-44b3-8e2a-a341bfe48baf.png)
