### ISSUE TITLE
Wrong stats on Survival Unique Jewels

### ISSUE THREAD

**Issue by brandon-tanujaya** [PathOfBuildingCommunity/PathOfBuilding#3999]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

**Survival Secrets**
Flasks applied to you have 20% reduced Effect
Flasks gain 3 Charges every 3 seconds while they are inactive

**Survival Instincts**
20% reduced Flask Charges gained
50% increased Flask Effect Duration

### What is the actual behaviour/value?

**Survival Secrets**
Flasks gain 2 Charges every 3 seconds while they are inactive
50% less Flask Effect Duration

**Survival Skills**
Flasks gain 2 Charges when you hit a Non-Unique Enemy, no more than once per second
80% less Flask Charges gained from Kills

### How to reproduce the issue

Look at the jewels in POB.

(PS. Something went wrong with https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3799 ?)

### Build code

```shell
No particular build.
```

**Comment by Lothrik** [comment]
This is already in #3799, which was merged to ``dev`` on November 23, 2021. Version 2.13.0 was released 21 days before that. You'll see the updated jewels in a few days with the next release.
