### ISSUE TITLE
Tempered By War Incorrectly Gives Wrong Amounts of Resistances

### ISSUE THREAD

**Issue by ThisIsMyAccnt** [PathOfBuildingCommunity/PathOfBuilding#4007]
For some reason Tempered By War is giving +36% Lightning Resistance and -36% Cold Resistance, when it should be giving -50% Cold and Lightning Resistance.

![image](https://user-images.githubusercontent.com/97902122/151757923-89e4e344-2bfb-4b04-8a3c-b2ea6412bb91.png)
![image](https://user-images.githubusercontent.com/97902122/151757933-8f2a677c-1feb-45e4-8f44-7648008fa468.png)

**Comment by Wires77** [comment]
This is not how that modifier works.  "50% less lightning resistance" means you multiply your current resistance by 0.5.  If you have 60% lightning res, this will make it 30%.  If you have -40% lightning res, this will make it -20%.

The mod you're thinking of would be "-50% Lightning Resistance"
