### ISSUE TITLE
Energized armour not changing the tooltip of passive nodes (Visual tooltip bug)

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#4009]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The energised armour jewel should modify the tooltip of Energy shield nodes and Energy shield from equipped shield nodes to show the amount of increased armour. 

https://www.reddit.com/r/pathofexile/comments/sgy6ma/interesting_discovery_with_the_energised_armour/

### What is the actual behaviour/value?

The passive node tooltips are not modified. This is only a VISUAL issue, the effect works correctly. 

### How to reproduce the issue

Equip Energised Armour jewel in the jewel socket next to Zealot's oath and check arcane guarding notable + minor nodes. 

### Build code

```shell
https://pastebin.com/kZTtTRLe
```

### Screenshots

https://preview.redd.it/4ohjtr2q10f81.png?width=1024&auto=webp&s=565e7c63c02aa966e63a74b197b27c8b05eeeab5

**Comment by LocalIdentity** [comment]
PoB does not support re-rendering the skill tree with the changes from any transformation jewels
