### ISSUE TITLE
Allow forced triggering of trigger skills to prevent self-cast assumption

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#4019]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Skills such as Unseen Strike from hidden blade in this example, do not require a trigger skill to trigger. This leads to the "No Triggering Skill Found" error due to which DPS is calculated based on attack/cast speed instead of trigger rate.

### Describe the solution you'd like

Provide an option to force trigger skill dps to be calculated based on trigger rate insterad of Attack/Cast speed. Alternatively fix every trigger skill that does not require a triggering skill, however this sounds more tedious and harder to keep up to date.

**Comment by Paliak** [comment]
Fixed by trigger rework and https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6404 specifically.
