### ISSUE TITLE
The Battlemage keyword does nothing in 3.13 beta

### ISSUE THREAD

**Issue by AlphaToTaC** [PathOfBuildingCommunity/PathOfBuilding#4022]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when selecting the martyr of innocence staff I expect to be gaining added spell damage based on amount of melee damage the staff does in damage calculation
this does not happen

### What is the actual behaviour/value?

when I check added min/added max the number does not change

### How to reproduce the issue

created a custom item with battlemage on it:

with battlemage
Battery Staff
Crafted: true
Prefix: {range:1}LocalAddedPhysicalDamageTwoHand9
Prefix: None
Prefix: None
Suffix: None
Suffix: None
Suffix: None
Quality: 20
Sockets: B-B-B-B-B-B
LevelReq: 70
Implicits: 2
Spend Energy Shield before Mana for Costs of Socketed Skills
{range:0.5}+(140-165) to maximum Energy Shield
Adds 1043 to 1078 Physical Damage
battlemage

checked damage of a spell.
then created another custom item:
without battlemage
Battery Staff
Crafted: true
Prefix: {range:1}LocalAddedPhysicalDamageTwoHand9
Prefix: None
Prefix: None
Suffix: None
Suffix: None
Suffix: None
Quality: 20
Sockets: B-B-B-B-B-B
LevelReq: 70
Implicits: 2
Spend Energy Shield before Mana for Costs of Socketed Skills
{range:0.5}+(140-165) to maximum Energy Shield
Adds 1043 to 1078 Physical Damage

as you can see battlemage adds nothing to spells

### Build code

```shell
eNrtGl1z2jr2ufwKDU93ZycBQyBphtw7hJCUndCymLZ3nzrCPoBuZIvaMoS7c__7HkkmOBSCrO6-bTuTyvb5_j5KO789R5ysIEmZiG-q3nm9SiAORMji-U318-T-7Kr626-VzojKxafZbca4-vJr5V1HnwmHFXDEqxJJkznIL1tKzW9IaUljuQARD-kfInkQ4U31o4ihSqY0DpncPgWcpulHGsFN1Q8QuUpoGkAc9nbvDWBEWeyL4AnkQyKypWa7YrAeihBhBsPRp_GkwJTFRaYo87vOiNMNJL6kkqT446baRdXpHD4wiaQoz5DO-2bjvNG8bFVrh1H8JUD4Au2dXzSuWpde_vMY0iiB_mwGgWQr6CVM9hY0DuCFylFmZWGHGZdsyRkkBQmPYkyEpPxu5O9gm03v_LJ9aTR6_zae2NmsfgzyK5OLW44Gc-CicAfzmElwRB4Jlor4J_Qroh5VsSeiKYudNBzSmPZEurNjo3kM9JHN4BXoUXn6vh3cGOPeDlKJOYIEc1LaIShhSyHkHHwIBOZ9GR5lUAp6uDFzwOz7LggOjHy5S_nGcafD9yKg510eg7yDZzt6RcCjcINY2lErAnqt1nHpVkLqXmHjuheodv2Nqh5cK9hBHNgR_RwnkEKyKjSDtiVC7uGdovU3EccwB0tNHwGCxQP2yTGVYJcRu8bytnEUrJVxFOAB47QsEUoYRyHuGef8zWJb0jxfaRJaZGwMyXzjLxjwwlzQev-mNYtIVlYtIlgGRBGlpOb9FU2L6eW139bGgNuFB-A8gAgh7A029ePDk_hDjU68HFo3iUSWWFROpYEBtlJgtNikLMABgUbYQscQZoFdKXqZAIdiBRHGuB4lcXrdmfkY6i3HuddWcSTLeSmMrpQ0eLoT4RxKMSmP4WfLJWa6ihZbvHuWoJVTVuiCZ20L6E842_fo0maCUylly2AHbc3gkc0XMsbFyZ7LHoq9Lgsq0hLK7MCtWdxnnFtNxiOxRpILtRim5aCHdDdTHB2J7xOI_9xY038FbsWgH4dZomLUmsc-xo9sOjW9OKvTIFqKROqXPcqDVJMcxMtMklhvvekT4_xbnEVTtc6Zf3c1oggZsTT4Ns1mM7UKV1GYRO_v_fv7fm8y-NLPUXzQlYoEgnO6TAF345jxKmF48BUzH2tzIC2gcWE25c8CFrtokDA032lQtVNaiKo38NNwaiG2AEM_UA62JppslqA8ntpZKS9yp2H1lmwBZ5ZaG7X06mxjdAjoxgLuZYSwgO1z6DKuepyNnYYYvqY52kBjs0rYNJNWEaXHfwsJ1CBsoVZx1LOKfBuwfFCxYJ9PZach8w5gE3Y4Jli66A5mgMFslci6OEzoE8R52duWuI7OopSkWPseIEpvN9hL7pVB965SIiox3CB6VFeME6EqKg0kJI_mynFGeapKXZHMTVUmGb4MYUYzrt7_M6OcyY0q2YW3OQktbboQazWUGDoqu1P0yOOj-dLlMiehmGy5GvWVHvpOsquHOv2stdQXkywOeBbiOpm3y5wdp1PFukrm6gqzJ7JY5l8gplOujGh02COsaCq27zooSA77wMWU8sZWEQU2ZDG6ZE-Uwpf8ZXeaCp4p700gWnKa_CPDQa66vc5t1KuvWHhboTSlgQ7Z4EeOmtl3Y66BLiza4KgrROp5CJKGVNLaQKIxa8qiNY2IJ03we8Fbe-YIjKWQgep4amT_UYijepl4Nbx0MJoYVMdJAkCosbMm6uXexYfiPbSSv668kmIIbvJipfwYY8fFQ-vqqtmsEonkCnfg3mV-vW3QjQP7Idbl8KPCq5k3n8eP-vBuIeUyva7V1uv1-ZLKhZjBM64954GIakskg1KeaYXPFKNaF__czrv6jyZU21LqmHvydKs5aqMVV-qqw0eB5VN9Uy-3D9oYXxisSQrYsxe-TJSGfwoR_UtrrzLiA1A5pMs86NS3PJuaeS5hb7xjaJ9E14qt_xTg79vJqaMDIDe7OvtgfJulYO68vgJdYlRBnhxm4EFAXVzyTBhT7O-bazLujvuVNZMLMqVSclCVp3KLR3QUQXFms0ovoTO0-TVRwlRGCczY8zX5N45qc7j2_noUuM51wxDC17vdZC0-0Dh8_4KhfpPw-sHHocviIS8i16RRr-SuuSa3Zy9_K9qIY_h-TS7rFZxIOAuYgmlU0HdxSEznIab1kCnMRAJEdS2CJ6KuCFMiZsTQhpCYCK_kKtbPW3_9_Rfvon7mtVt_I1JgID-zKIte062gDVLi1S-aCsSrX16RrUGIsUilYGIVZjhvjhUHovmo-5eWaQCNbdIpr712X-OI-wSOs__34P_cgyXd5nOx3TJMUhLV3KSp6C-7iMnho_lbTNtDFP01XZLudJOmKKexAGnt2OT71kHUfbSGHdoPOryCuhUCveEm0CFdTgh1C1yWRLnHrvJEmlYiNQ6J1HQzr50RGv8ltAs3Idtu3Nru1vROOPhQPJ3wwAfA_UmWZXQgktoufE6EH86FK3UhUp5w0z2LPBd-F26x4LlF3sVp99gYtizZQ-HlqLhV3Wk5yONQA5un2IQbYpbnku47bGWn-Gq5IFmlpI0jnPRsOZu14eD3tlsmNd3Ct1k-yi7cy75DTHvOxm_aBMSFDZCD2D8x_Fh60t0LbYeodHfDT4SLbUlWuJZZYw_qYLkxi-d2k0DpQnHUvI7lwt6fLuo0LezkubvhwtlaLRdtbPLFPchPiNSNMn6gt5mNExdGfU2l74f0L8ZEPGNzhOjU9v8L6n8AaHZlQw==
```

**Comment by Lothrik** [comment]
This is fixed by #3893, the automatic weekly beta action just happened 31 minutes prior to that pull being merged into ``dev``.
