### ISSUE TITLE
Where to buy gems

### ISSUE THREAD

**Issue by voronoipotato** [PathOfBuildingCommunity/PathOfBuilding#4025]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

When leveling I can't always remember where or when to get gems.

### Describe the solution you'd like

When I hover over a gem, I'd like to be able to see where, and what level, and or or quest requirement to buy gems from vendors. 
(example) 
### Describe alternatives you've considered

If this is not possible, a link to the wiki for my skill gems that I can click would also be acceptable. 

### Additional context

While poe-roadmap does solve this issue, and it's pretty cool and good, it also can go down. Today when I loaded up the site it froze up when trying to generate a roadmap and didn't generate anything until the 5th time I clicked it. While I can print it out, or save as pdf, it's not exactly giving me confidence for league launch. I don't think this feature would replace poe-roadmap as poe roadmap offers additional features such as integration with poe.trade, but it would provide some offline assurance that you're not having to search the wiki for every gem in your build.

**Comment by Wires77** [comment]
We've had this discussion before, and leveling improvements or guides are out-of-scope for PoB.  We did add a shortcut key to open any item on the wiki by pressing F1 while hovering over it, however, so your alternative already exists!
