### ISSUE TITLE
Vaal BV Hit Rate is the old 0.13 instead of the current 0.2

### ISSUE THREAD

**Issue by Beastmode131** [PathOfBuildingCommunity/PathOfBuilding#4027]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Currently, PoB is calculating Vaal Blade Vortex's hit rate at 7.52 (the old hit every 0.13 seconds value) instead of the current 5.0 (hit every 0.2 seconds).

The base damage, crit chance, cast time, and duration all appear to be correct.

P.S. Thanks to all of you for updating PoB. You all rock!

### What is the actual behaviour/value?

![image](https://user-images.githubusercontent.com/98837448/152016413-e5cd37ab-6383-464d-989d-05e261650068.png)

### How to reproduce the issue

1. Add a Vaal BV Gem in the Skills tab
2. Select Vaal BV as a main skill and view "Hit Rate" or go to the calcs tab for Vaal BV and mouse over "Skill DPS"

### Build code

```shell
v2.13.0
```

**Comment by Beastmode131** [comment]
Forgot to include the 3.14 patch notes where Vaal BV was updated:
![image](https://user-images.githubusercontent.com/98837448/152017223-44260422-5e86-4f29-bb10-e2c1194bb9be.png)

**Comment by Wires77** [comment]
Looks like the radius might be wrong, too, thanks for the report, should be an easy fix

**Comment by Lothrik** [comment]
Fixed by #4030.
