### ISSUE TITLE
Crash on importing a build

### ISSUE THREAD

**Issue by Bonivur** [PathOfBuildingCommunity/PathOfBuilding#4028]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Expected importing this build - https://pastebin.com/zDfd4a2F

### What is the actual behaviour/value?

PoB crashes

### How to reproduce the issue

Import https://pastebin.com/zDfd4a2F  

### Build code

```shell
https://pastebin.com/zDfd4a2F
```

**Comment by Peechey** [comment]
This will be fixed in the next release. Currently works in the beta branch if you really want to use it right now (Options bottom left > Opt-in to weekly beta... > Save > Check for Update > Update Ready > Update).
