### ISSUE TITLE
Atlas passive tree support

### ISSUE THREAD

**Issue by CMolero** [PathOfBuildingCommunity/PathOfBuilding#4033]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

use PoB community capabilities for better planning your atlas tree, especially the highlight, search and summary functionalities 

### Describe the solution you'd like

with the new passive tree it would be nice to have it added to PoB community

the way to implement this would be as a separate tree instead of a character you can probably select "atlas" and then it will show you  summarized the passives you selected like "areas have a % of containing a breach", etc

**Comment by Wires77** [comment]
We've decided not to support this as there were a myriad of other tools available for such a purpose

**Comment by Wires77** [comment]
Outside of the ones you mentioned, here are some others I know about, the last two being standalone applications.  I've ordered them with the more feature-complete tools coming first, so hopefully one of them works for you.

https://poeplanner.com/atlas-tree
https://poeskilltree.com/?v=3.17.0-atlas
https://exilewarplan.com/?state=
https://github.com/PoESkillTree/PoESkillTree
https://github.com/keyzou/POEAtlasBuilder/tree/master

I should've expanded upon my statement by saying that we have discussed this at length internally, and came to the conclusion that it just doesn't make sense for us to make this a part of Path of Building.  The vast majority of atlas passives do not affect your build at all, and Path of Building is a build planning tool first and foremost.  Other developers have one atlas tree to focus on and can thus deliver features faster than we could, while we work on the other 490 issues relevant to making builds
