### ISSUE TITLE
Lua error while editing build

### ISSUE THREAD

**Issue by SneakyBee44** [PathOfBuildingCommunity/PathOfBuilding#4035]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The build should load and I should be able to use POB.

### What is the actual behaviour/value?

Throwing LUA error on attempt to load the build.

### How to reproduce the issue

Something to do with herald of purity double active + conductivity.

Or just copy paste the xml file and try to load the build in your POB

### Build code

```shell
Can't access it, but this is an old one, that works fine. 

https://pastebin.com/CRdFb5mB This is the build in question https://cutt.ly/YOQA3w4
```

### Screenshots

![error](https://user-images.githubusercontent.com/93332692/152163619-123f0403-a53c-4ebe-b783-f416e1e7bf6d.png)

**Comment by SneakyBee44** [comment]
Found the issue. This happens when you trigger "include in full DPS" in that build, because conducivity is seen as "no active skill"

**Comment by Wires77** [comment]
This seems to be fixed
