### ISSUE TITLE
Unable to Update from 2.11 to 2.13

### ISSUE THREAD

**Issue by Decnalabnu** [PathOfBuildingCommunity/PathOfBuilding#4040]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

What is the expected behaviour/value?
Clicking the "check for update" button results in me being able to automatically update to the latest version (currently 2.13)

https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3996
The previous issue was closed but I also experience this error and cannot easily swap to a hot spot to fix it.  Like the previous error submission I'm also on windows 11.

### What is the actual behaviour/value?

What is the actual behaviour/value?
After clicking "Check for Update", it goes through the list (1/61, 2/61, etc), and eventually ends with the message

"Update check failed!
One or more files could not be downloaded.
Check your internet connectivity
or try again later."

### How to reproduce the issue

Hit update and watch it fail.

Steps I've taken to resolve this:

Running as admin
Installing as admin
Disabling my firewall completely
Manually adding PoB and update.exe as exceptions to windows defender
Deleting all saved builds + Uninstall & reinstall + reboot
Flushing and Re-registering dns

### Build code

```shell
https://pastebin.com/vvv4ebaw
```

### Screenshots

![image](https://user-images.githubusercontent.com/3722439/152289089-54daafd2-f800-4493-89f1-ffb45ed44ca2.png)
![image](https://user-images.githubusercontent.com/3722439/152289105-8215ea65-4919-4b1b-be11-5115d13d8602.png)

**Comment by LocalIdentity** [comment]
Can you see which files didn't download correctly by Pressing `Ctrl + `` at the same time after trying to update

**Comment by Decnalabnu** [comment]
![image](https://user-images.githubusercontent.com/3722439/152289581-17dd286d-06b0-41fa-b8c7-ce28295a4a4e.png)
![image](https://user-images.githubusercontent.com/3722439/152289621-90ae6603-d671-428b-ae4f-3a1654c1fc5a.png)
![image](https://user-images.githubusercontent.com/3722439/152289636-1ec085a5-ef6e-4fe9-be80-688aec838df6.png)

**Comment by zao** [comment]
Could you open a Windows Terminal and run this to try to download one of the files:
```
curl.exe -v https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/master/src/Data/Bases/axe.lua
```

Could you also please try downloading the same URL in the various web browsers you have installed on your system like Edge, Firefox/Chrome?

On success they should get you some Lua code, the content is irrelevant but I'm curious to see if there's any errors on the way there. If it succeeds, please also try some of the other files from your logs.

Additionally, which Windows version and build are you on according to `winver.exe`?

**Comment by Decnalabnu** [comment]
![image](https://user-images.githubusercontent.com/3722439/152429201-20f5d191-d860-40c4-9b16-d1d519c35773.png)
![image](https://user-images.githubusercontent.com/3722439/152429265-726e60d1-47f6-4aac-8268-a8b1b40385f9.png)
Previews properly on chrome.
Previews properly on edge.
Previews properly on firefox
![image](https://user-images.githubusercontent.com/3722439/152429467-ef6d87e0-3d2e-4523-bba2-f262fe03f9fe.png)

**Comment by zao** [comment]
Hmm, interesting. Does the curl behavior change if you add a `-4` option at the beginning to force IPv4?
Do you have proper IPv6 from your ISP or is it via a tunnel provider? Do sites like https://ipv6test.google.com/ work?

There's an optional preview of a Cumulative Update to 22000.469 (KB5008353) which is supposed to address some connectivity issues, not sure if it includes ones like this. It might be worth installing via Windows Update.

**Comment by Decnalabnu** [comment]
-4 Does work.  
![image](https://user-images.githubusercontent.com/3722439/152440395-2fd1b31d-7ff3-4532-a1ca-62a001fe7731.png)

![image](https://user-images.githubusercontent.com/3722439/152440237-64d1927f-d2fa-40e8-ae85-a9d2c533e8ca.png)

Will check this update.

**Comment by zao** [comment]
We could try as a test to force PoB to only download updates via IPv4.

If you're comfortable with it, save a copy of `UpdateCheck.lua` and in the function `downloadFileText` below the line:
```
easy:setopt(curl.OPT_ACCEPT_ENCODING, "")
```
add a line:
```
easy:setopt(curl.OPT_IPRESOLVE, 1)
```

**Comment by Decnalabnu** [comment]
That resolved it.  Thanks a bunch.

For future searchers:

![image](https://user-images.githubusercontent.com/3722439/152461724-e564a098-11f4-4584-bf8d-dae2e7370190.png)

**Comment by zao** [comment]
Note that because the update check file itself is tracked by the update manifest, it's going to be overwritten on every update and considered corrupt on every run of the program as the contents do not match.

Until we've figured out a robust way to improve PoB when it comes to not-quite-functional connectivity, you will have to make this change when you wish to obtain updates.

**Comment by zao** [comment]
@Decnalabnu Now in 2.15.0 there is a configuration option for forcing a communication protocol, doing the same as the line you have manually added.
If you use that option, you shouldn't have to modify the code in the future.
