### ISSUE TITLE
Annoint comparison doesn't properly compare annoints, probably caused by 2 skills in full dps

### ISSUE THREAD

**Issue by hgfedcba** [PathOfBuildingCommunity/PathOfBuilding#4043]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

proper annoint compariosn

### What is the actual behaviour/value?

I think it only compares for the selected skill not full dps

### How to reproduce the issue

1. Open my pob
2. go to my amulet (first item) and try to change the annoint to melding
3. ->first screenshot
4. actually annoint melding
5. ->second screenshot
6. as you can see the numbers differ.
7. If you deselect scorching ray from full dps they are identical.

### Build code

```shell
https://pastebin.com/9UXBF1va
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/15093099/152312738-5dc9ff84-de55-4089-b34a-e886531b6b83.png)

![grafik](https://user-images.githubusercontent.com/15093099/152312775-e6852fda-ba95-4710-b48e-f3d7f1bdcab9.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5421
![image](https://user-images.githubusercontent.com/31533893/218348416-f4b7fbb8-b65b-4e79-8168-8f188438820e.png)
