### ISSUE TITLE
I wish there were more options to filter and make your search for specific nodes quicker.

### ISSUE THREAD

**Issue by Ovalidem** [PathOfBuildingCommunity/PathOfBuilding#4052]
### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I heavily use the search function to hone in on what nodes I'd like to pick.

For instance, say I need evasion + armour, I'd literally just write that into the search bar to let the program highlight all of the nodes that have that in them.

However, I'm stuck with *all* the nodes with whatever I put into the searchbar, even though sometimes they're the same or not really what I'm looking for.

More specifically, and the thing that made me ask for this feature, is that if I search for "flask recovery rate", I get those mastery nodes (which are very numerous on the tree too, slowing my search down) too (Normal.png) instead of just the ones I'd want (No mastery nodes.png).

Normal:
![Normal](https://user-images.githubusercontent.com/10993412/152427287-e41d4389-8b8a-4db6-919a-0ab4440611a7.png)

No mastery nodes:
![No mastery nodes](https://user-images.githubusercontent.com/10993412/152427279-a97587f1-ab27-4d40-9d92-3c7a7acf86ce.png)

### Describe the solution you'd like

I'd like some more filtering options to add to the search bar. Like a list of checkboxes to in- or exclude keystones, notables or the mastery nodes. Or perhaps checkboxes for other things like not wanting dex or strength or other things a node might have.

### Describe alternatives you've considered

You *could* in theory add more labels you'd want to search for, but that only constricts the search results, potentially leaving out ones you'd want. It also *adds* more work for me to find what I want.

**Comment by pHiney** [comment]
Do you use "" around your searches ?
this might make it easier for some searches.

![image](https://user-images.githubusercontent.com/4302241/152702652-cc2b23ef-ab16-491a-9d5b-1dddabda0f66.png)

> I'd like some more filtering options to add to the search bar. Like a list of checkboxes to in- or exclude keystones, notables or the mastery nodes. Or perhaps checkboxes for other things like not wanting dex or strength or other things a node might have.

So an advanced search button. The search bar is a bit small for that.

X

**Comment by Ovalidem** [comment]
Oh, I had not considered "'s with my search. That helps, thanks.
