### ISSUE TITLE
Can't save trees with too much nodes allocated from 3.16 onwards

### ISSUE THREAD

**Issue by Helmanzs** [PathOfBuildingCommunity/PathOfBuilding#4069]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should be able to normally save trees.

### What is the actual behaviour/value?

When I try to save a fully allocated tree it displays an error and doesn't let me save it.

### How to reproduce the issue

You can either manually select every node and mastery or import this pastebin https://pastebin.com/4KG5chds and convert it to 3.16.

### Build code

```shell
https://pastebin.com/4KG5chds
```

### Screenshots

![image](https://user-images.githubusercontent.com/86473760/152544625-6c667dea-0d9a-4d2c-b382-9fba8521e782.png)

**Comment by Peechey** [comment]
Fixed somewhere down the line, can't replicate in live. Converts to 3.16 and latest 3.23 and saves/loads fine.
