### ISSUE TITLE
crash on startup with release 2.13.0

### ISSUE THREAD

**Issue by TigreDomino** [PathOfBuildingCommunity/PathOfBuilding#4073]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

the program should initalize normally

### What is the actual behaviour/value?

When the program starts asks for a file which is not there on my install folder and crashes after initialization,the loading assets is screened below for review

### How to reproduce the issue

1-open the program
2-loading assets
3-crash to desktop after loading

### Build code

```shell
there is no build code available for me to send,for i'm not used on how to grab it to further help the process
```

### Screenshots

![error pob](https://user-images.githubusercontent.com/99040618/152575262-91af9ab6-d711-42c2-8eb2-c51a67b8b1a6.png)

**Comment by pHiney** [comment]
Did/Can you reinstall or download the updated zip (in case you've had a bad update) ???

**Comment by nickadamson** [comment]
Having this issue, too.

> Did/Can you reinstall or download the updated zip (in case you've had a bad update) ???

Have tried clean install and using portable version. Are there logs located anywhere I can share?

**Comment by pHiney** [comment]
What version of Windows are you on please ? 10 or 11.

if it is v11 ( i don't have it) I wonder if Windows 10 is available in the
compatibility

Right click on starting icon and select 'Properties'
Select Compatibility tab
Select "Run this program in compatibility mode for:"
[image: image.png]

then check the drop down to see what options are available
thanks
X


thanks
Peter

**Comment by TigreDomino** [comment]
i clean installed it and deleted the original folder just in case of bad downloads but even in compatibility mode for win 8 or 7 didn't work ,for reference im on the last stable version on win 10

**Comment by QuickStick123** [comment]
Do you still have this issue in the latest version?

**Comment by TigreDomino** [comment]
no the issue has been resolved now thanks
