### ISSUE TITLE
Problem with Configuration tab

### ISSUE THREAD

**Issue by Byngalo** [PathOfBuildingCommunity/PathOfBuilding#4082]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When i open "Configuration" tab in any build, i can't interact with some options, they just goes offscreen for me.
![Screen](https://user-images.githubusercontent.com/49322148/152634624-3a48b638-9e33-4519-8e4f-1a0e77ed1da6.png)

### What is the actual behaviour/value?

i dont know what i should write here...

### How to reproduce the issue

My Monitor with main resolution 1280x1024. Always happens with any build...

### Build code

```shell
Any build for me...
```

**Comment by Tkap1** [comment]
Similar thing happens to me at 1024x768
![image](https://user-images.githubusercontent.com/18644237/153343430-4005bcba-b1f5-40a8-a55a-aa38da2dfd8d.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.16.0
