### ISSUE TITLE
Equipment Calculations putting stats and DPS in the 4-5 digits and DPS into the Millions with beginner gear.

### ISSUE THREAD

**Issue by StorMaestro** [PathOfBuildingCommunity/PathOfBuilding#4087]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when copying and pasting gear from game. the values should be added correctly to the stats in conjunction to match what the games numbers are showing.  

### What is the actual behaviour/value?

Equipment stats do not have spacing in between numbers making 12(11-19) as 121,119 and summing up that way. Basically most of the gear has to be edited and corrected before adding it to the build.

### Build code

```shell
im sorry Im not well versed in coding.....
```

### Screenshots

![Screenshot (11)](https://user-images.githubusercontent.com/89699903/152652122-ffcbabd7-f475-48b5-9e18-9209816547d6.png)

**Comment by Wires77** [comment]
This is due to you using the advanced copy/paste.  We don't support that in PoB right now.  If you just Ctrl+C instead of Ctrl+Alt+C it should work.
