### ISSUE TITLE
Path Of Building ERROR

### ISSUE THREAD

**Issue by FullMetaL84** [PathOfBuildingCommunity/PathOfBuilding#4089]
When I'm running POB i am getting the error in the screenshot below. I am on Win 11, and running the latest version of POB.
Before the update of 2.14 it was running fine. Please Help me

![POB error](https://user-images.githubusercontent.com/99111742/152669181-4eb28fed-e164-4e2f-ae1e-ae49a2d60dad.jpg)

**Comment by ppoelzl** [comment]
Hi! Please fill out the [bug report template](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/new?assignees=&labels=bug&template=bug_report.yaml) and maybe we'll be able to reproduce your issue.
