### ISSUE TITLE
Issues with forbidden shako

### ISSUE THREAD

**Issue by swarls68** [PathOfBuildingCommunity/PathOfBuilding#4097]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Getting dps increase from both support gems on my forbidden shako

### What is the actual behaviour/value?

I have a forbidden shako with ice bite and fortify.
The ice bite flat damage gets added just fine, but the fortify does not appear in calcs tab under more damage.

### How to reproduce the issue

- Use forbidden shako with ice bite and fortify (in my case replica forbidden shako, but does also happen with regular)
- Put a attack skill in the helm slot (in my case flicker strike)
- Check dps

### Build code

```shell
https://pastebin.com/Rp7ru5N2
```

**Comment by LocalIdentity** [comment]
Bonechill not auto applying, when linked to Vortex, is an issue that we are aware of. You can manually set the value to 30 as that is what it will apply in your build
