### ISSUE TITLE
Ornament of the east hits cant be evaded isnt working, even though the code is green

### ISSUE THREAD

**Issue by omars252** [PathOfBuildingCommunity/PathOfBuilding#4102]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

0

### What is the actual behaviour/value?

0

### Build code

```shell
0
```

**Comment by LocalIdentity** [comment]
It's working just fine for me. As you have provided no information to help us solve your problem. I am closing this issue.
If you provide details and document the problem, we can then help
