### ISSUE TITLE
path of building not working 

### ISSUE THREAD

**Issue by aiham311** [PathOfBuildingCommunity/PathOfBuilding#4109]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when i open the program it show some weird screen with pixels 

### What is the actual behaviour/value?

when i open the program it show some weird screen with pixels 

### How to reproduce the issue

just open the app ...

### Build code

```shell
https://pastebin.com/PX2CXas4
```

### Screenshots

![Untitled](https://user-images.githubusercontent.com/99282131/153046405-c5dc9c7c-da99-4a47-a649-d5c62bc9d6b4.png)

**Comment by Magickareem** [comment]
Yep exact same issue here. Tried uninstalling and reinstalling. Ran it in combability mode same result every time.

**Comment by Niteip123** [comment]
Having the same Problem and only way i can reliably "fix" it, is by restarting my PC and then the first time i launch PoB it works fine. If i close it and try to start it again, it is broken again until i restart my PC.

**Comment by Nightblade** [comment]
Just curious -- are any of you running FPS overlays or similar?  Have you tried running PoB without them?

**Comment by Niteip123** [comment]
just the nvidia one but disabling it doesn't make a difference sadly

**Comment by Wires77** [comment]
Can you guys share what Windows version and graphics card you have?  Has this been happening since you installed PoB or did it used to work fine until recently?

**Comment by Niteip123** [comment]
for me atleast it just randomly started working just fine again a few days ago, didn't update windows or gpu driver or anything
i honestly have no idea what could have changed.
been using pob since before fork and always worked great

but i was and am running

windows 10pro version 19403
nvidia 1070  version 511.65

hope this helps fixing it if someone else still has problems

**Comment by Deebeekooper** [comment]
I'm have somewhat of the same issue except I keep getting the build you are trying to load uses an unrecognized version of the passive skill tree.

**Comment by Deebeekooper** [comment]
1.4.170! But everytime I run an update I get "You're running the latest
version!" message. The last time I didn't believe it and uninstalled then
reinstalled PoB, it updated to that same version

**Comment by Lothrik** [comment]
1.4.170 is the original Path of Building by Openarl which was [last updated on Jun 19, 2020](https://github.com/Openarl/PathOfBuilding/releases) and is no longer maintained.

You need to download the Path of Building Community Fork from here, not wherever you got 1.4.170 from: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases

The current release version is 2.18.1.
