### ISSUE TITLE
Implement Thaumophage Notable

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#411]
Last mod doesn't parse (I believe we care about 'hinder' condition)

```
0.6% of Spell Damage Leeched as Energy Shield
20% increased Maximum total Recovery per second from Energy Shield Leech
10% chance to Hinder Enemies on Hit with Spells, with 30% reduced Movement Speed
```

**Comment by dclamage** [comment]
"Touch of Cruelty" Notable needs similar support for both mods:

    Chaos Skills have 10% chance to Hinder Enemies on Hit, with 30% reduced Movement Speed
    Enemies Hindered by you take 10% increased Chaos Damage

**Comment by LocalIdentity** [comment]
The reduced movement speed on enemies is not a mod we are currently looking to support
