### ISSUE TITLE
Generals Cry with supported skills attack rate stuck at 1

### ISSUE THREAD

**Issue by SpennyEatsPizza** [PathOfBuildingCommunity/PathOfBuilding#4113]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Generals Cry with supported skills attack rate stuck at 1

### What is the actual behaviour/value?

attack speed should be increasing rate its stuck at 1

### How to reproduce the issue

Generals Cry support blade flurry stuck at 1 aps

### Build code

```shell
Generals Cry with supported skills attack rate stuck at 1

https://pastebin.com/2rNUgjYG
```

### Screenshots

https://pastebin.com/2rNUgjYG

**Comment by Wires77** [comment]
Fixed in 2.15.1
