### ISSUE TITLE
Forbidden Flame/Flesh are working in game, not in PoB Fork in my case. 

### ISSUE THREAD

**Issue by Lash111** [PathOfBuildingCommunity/PathOfBuilding#4117]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should see DPS increase from Mastermind of Discord node allocation.

### What is the actual behaviour/value?

I can't see DPS increase.

When I move cursor on 'actual' Elementalist's Mastermind of Discord gives me extra dps increase in green numbers, but Mastermind of Discord from [Forbidden Flame + Flesh] is not reflected in the results.

### How to reproduce the issue

You can easily check that from link below

### Build code

```shell
https://pastebin.com/DKbxYe2K

This is my actual character and it works in game, only not on PoB
```

**Comment by Nostrademous** [comment]
Noted, issue is that this DOES NOT work when importing characters in PoB from PoE, NOT that it doesn't work at all. If you remove the Jewels you import and replace with the same jewel buy using our item crafter it will work just fine.

We could not implement this until someone had one on their character so we can see how GGG structures it in the JSON of the retrieved character, so we know how to parse it out of the JSON.

Structure is below. We will implement soon.
```
"requirements": [
        {
          "name": "Class:",
          "values": [
            [
              "Duelist",
              0
            ]
          ],
          "displayMode": 0,
          "type": 57
        }
      ],```
