### ISSUE TITLE
Reap's calculations

### ISSUE THREAD

**Issue by Muramas** [PathOfBuildingCommunity/PathOfBuilding#4122]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

-I set my main skill as reap which is a physical spell and I turn on iron will and it does not change my damage. 
-Similar to using a cluster jewel when I add attack and cast speed with physical skills, you can remove the attack and cast speed with no change in dps.
-Also PoB suggests skills like arcane surge and inspiration which rely on you spending mana, which will never proc.

https://pastebin.com/ZWvukZh1

Rarity: RARE
Blight Cut
Large Cluster Jewel
Item Level: 61
LevelReq: 40
Implicits: 3
{crafted}Adds 10 Passive Skills
{crafted}2 Added Passive Skills are Jewel Sockets
{crafted}Added Small Passive Skills grant: 12% increased Physical Damage
Added Small Passive Skills also grant: 10% increased Attack and Cast Speed with Physical Skills
1 Added Passive Skill is Furious Assault
1 Added Passive Skill is Master the Fundamentals

### What is the actual behaviour/value?

When I click on iron will, nothing happens.

It seems that the damage calculation can't tell what effects reap

### How to reproduce the issue

https://pastebin.com/ZWvukZh1

-1
-Click on iron will
-see no change

-2
-With the first node in blight cut large cluster jewel selected
-remove  "Added Small Passive Skills also grant: 10% increased Attack and Cast Speed with Physical Skills"
-See no change

### Build code

```shell
https://pastebin.com/ZWvukZh1
```

**Comment by LocalIdentity** [comment]
You have Iron Will as one of the gems in your gem links, so clicking Iron Will on the tree does nothing. The cluster jewel mod that is not currently calculated, will be fixed for the next update as I just added support for it
