### ISSUE TITLE
restore previous Effective Health Pool table

### ISSUE THREAD

**Issue by hgfedcba** [PathOfBuildingCommunity/PathOfBuilding#4124]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

not really

### Describe the solution you'd like

I would like to get back the previous EHP table we had before, you can see it for example here https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2941
I think it was a very positive feature that it showed your EHP against every damage type separately so it is much easier to compare values. I often use POB to plan builds I am not playing already, so especially my chaos resistance is very random. Before the latest patch I could easily compare my elemental/physical EHP Pool between build version, but putting everything in a single number makes for some very awkward problems.

### Describe alternatives you've considered

I know I can go in Config and put in enemy damage type numbers so that I get the old calculation back, but it is much worse then before since I have to do it 5 times for every build version to get the old information.

I could make up a ration of phys-ele-chaos and use it for every build. This works but I consider this much worse then getting the old 5 EHP numbers back.

I could put random chaos resi under custom modifiers, but that doesn't really solve the problem.

### Additional context

All in all there are workarounds, but they are way worse then just reintroducing the old table. I would like the new EHP to stay in POB, but I think the old showed much more information.

The only situation where I can see the new value being superior is when you want to use a single number to compare your builds tankyness and don't care much about the details.

**Comment by Regisle** [comment]
I somewhat understand the split EHP being useful, but does maximum hit taken not solve most of your issues when comparing the sub elements of a builds tankiness? most of the extra things factored into the EHP calc applies to all damage types so a %change in EHP should be relatively informative

the main issue with bringing back the old 5 types is how the EHP calc is currently done, its much more accurate than the old one, but also more computationally expensive, if I bring back the old one as well the values would not match and could confuse people, if I updated it to use the new calculation it would in my opinion not add that much extra information and slow down PoB further

**Comment by hgfedcba** [comment]
Oh sorry I missed your message. Even after warming up to the concept of the new ehp somewhat I would still like to see the values for each damage type separately as I still think it is the fastest way to compare defenses between builds. You could just make it an option to show it listed for all damage types separately.

More importantly I want to question that recovery on block is included in ehp. I found out about that yesterday and think it shouldn't be included. I noticed it on my ssf char here pastebin https://pobb.in/gCPKihWRouio
, I am still considering whether to hand it in as a bug report. if you put in "recover 5% of your life on block" I quadruple my ehp. This makes even less sense considering other types of recovery aren't included. Currently any decent aegis aurora build probably hits infinite ehp...

This wasn't an issue with the old calculation.

**Comment by QuickStick123** [comment]
I feel this is mostly resolved max hit info for all types and ability to disable on block.
