### ISSUE TITLE
1% increased Spell Damage per x intelligence doesn't work when you're converting it to Attack Damage

### ISSUE THREAD

**Issue by Auxiffein** [PathOfBuildingCommunity/PathOfBuilding#4133]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

1. Caster Mastery Notable 1% increased Spell Damage per 16 intelligence should give 150% increased attack damage when you have 1600 intelligence and Crown of Eyes is equipped or 100% increased attack damage when you have wand mastery notable.
2. Hunter's Prefix Modifier 1% increased Spell Damage per 16 intelligence should give 150% increased attack damage when you have 1600 intelligence and Crown of Eyes is equipped or 100% increased attack damage when you have wand mastery notable.
3. Crusader's Prefix Modifier 1% increased Spell Damage per 15 intelligence should give 160% increased attack damage when you have 1600 intelligence and Crown of Eyes is equipped or 100% increased attack damage when you have wand mastery notable.

### What is the actual behaviour/value?

![weirdd](https://user-images.githubusercontent.com/72070731/153656627-535ea1cf-9c7b-420b-8167-b0a07b1e8af2.png)
![calcs2](https://user-images.githubusercontent.com/72070731/153659887-0fe25ae2-a154-4728-b053-b523227d7053.png)
![calcs1](https://user-images.githubusercontent.com/72070731/153659891-fe945c18-7e65-413d-b377-d692066b3cb0.png)

1. Removing/adding modifier affects my damage by 0.1%
2. MH Total Increased in Calcs increases/decreases by 1%.

### How to reproduce the issue

1. Have Increased 1% Spell Damage per 16 Intelligence modifier from either Caster Mastery Notable or from weapon modifier/amulet modifier.
2. Have Crown of Eyes or Wand Mastery notable to convert spell damage to attack damage.
3. Try equipping/unequipping or unallocating/allocating.

### Build code

```shell
https://pastebin.com/Z3s4RWxk
```

**Comment by Wires77** [comment]
Fixed by #4086 in the next release
