### ISSUE TITLE
Shock is calculated incorrectly in PoB for an Elementalist

### ISSUE THREAD

**Issue by CantripN** [PathOfBuildingCommunity/PathOfBuilding#4143]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Activating the "is the Enemy Shocked" in PoB should set the Shock at the correct amount.

For example - https://pastebin.com/6eMxUtSp

In this PoB, my actual Shock is 48% (as is indeed the case in-game). PoB insists it's a lot less.

This has several layers. 

1 - Critical Mastery for "50% increased Effect of non-Damaging Ailments you inflict with Critical Strikes" isn't added to the math it uses.

2 - Even without accounting for it, my Shock would be 39%, and PoB thinks it's 27%. 

3 - Correct Math = Shock Effect Mod x2.63 (PoB does this part correctly, except note #1) x 15 = 39.

4 - Actual PoB = Current Shock = 27%. Suspected reason? Uses base Shock as 10%?

### What is the actual behaviour/value?

1.  Correct Math = Shock Effect Mod x2.63 (PoB does this part correctly, except the 2nd bug below) x 15 = 39.

2. Critical Mastery for "50% increased Effect of non-Damaging Ailments you inflict with Critical Strikes" should be added to the math it uses.

3. End result = Shock Effect listed with the 50% from Mastery included, and then ALSO mathed correctly to come to 48% Shock.

### How to reproduce the issue

Arc as Main Skill
Go to Calcs
Look at Shock Effect Mod and Current Shock.

Notice Shock Effect listed x 15 isn't the same as Current Shock.

### Build code

```shell
https://pastebin.com/6eMxUtSp
```

**Comment by kasperhhk** [comment]
Just to add onto this, unbound ailments skill does not seem to affect the shock value at all in this scenario.
It seems like Shaper of Storms (or maybe even more generally "at least" guaranteed shock values) are not calculated correctly on the calculation screen. 

It is using the "current shock" listing the guaranteed minimum value (unless a higher shock is manually configured), even though that value is incorrect (as stated above).

**Comment by QuickStick123** [comment]
Crit mod is still broken.

**Comment by SuperJelle** [comment]
Just to add/clarify on this. The "increased Effect of non-Damaging Ailments you inflict with Critical Strikes" mod is not accounted for in PoB. There's no checkmark to enable it and even if you have 100% crit chance it still won't use it when calculating shock.

**Comment by QuickStick123** [comment]
I am going to close this in favour for https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4861 as it is dedicated to this issue.
