### ISSUE TITLE
PoB assumes Frozen = Chilled.

### ISSUE THREAD

**Issue by CantripN** [PathOfBuildingCommunity/PathOfBuilding#4144]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When "Is the enemy Frozen" is ticked, PoB also acts as if they enemy is ALSO Chilled.

As confirmed by Mark here, this isn't actually what happens: https://www.pathofexile.com/forum/view-thread/2789151/page/1

### What is the actual behaviour/value?

Frozen Enemies are NOT counted as Chilled unless ticked separately.

Hypothemia should not be a suggested link if you tick Frozen, and clusters that say they generate charges vs Chilled don't actually work vs Frozen. Now, yes, I know, it only really matters for The Three Dragons :D

### How to reproduce the issue

Tick "is the enemy frozen", and effect that happen vs Chilled are activated. This is not the case in reality ingame, it just so happens most things become Chilled from the same damage source that does Freeze, but you entirely CAN Freeze without ever Chilling (The Three Dragons comes to mind, surely there's other examples).

### Build code

```shell
https://pastebin.com/sbExUiHM
```

**Comment by Wires77** [comment]
It also matters for Expedition's End.  Interesting to know the wiki has been wrong for all these years

**Comment by Lilylicious** [comment]
It seems the wiki misunderstood the following line from 2.0:

> When frozen, you are also chilled for the freeze duration + 300ms. Previously this value was 30% of the freeze duration, but that was sometimes too short or too long.

Perhaps that line did mean that freeze automatically causes chill at some point, or perhaps it actually means "When you freeze, if you also chill at the same time, the duration is the freeze duration + 300ms".

Either way, the assumption is clearly wrong as of at least 2020.

**Comment by kolhell** [comment]
^ is the first appearance of the `implyCond = "Chilled"`

**Comment by kolhell** [comment]
Got it
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/cf1632fb2f06f4d8a4c0ef70554adc65a7d2afd1/src/Modules/CalcSetup.lua#L62
Haven't tested anything other than Hypothermia so far, but I'll throw up a branch if anyone else wants to look at it.
