### ISSUE TITLE
Total available HP pool appears halved after latest (2.15.1) version rolled out

### ISSUE THREAD

**Issue by fatherhet** [PathOfBuildingCommunity/PathOfBuilding#4149]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

PoB should be accounting my total available HP pool when calculating maximum hit taken for the build which is not the case here, unfortunately. You can see I have ~4700 life in my build and none of it is reserved/unvavailable due to any other conditions. This amount corresponds to around 16k max hit vs physical damage, 50k vs fire/lighthing damage, 80k vs cold and ~60k vs chaos (at least these were the values before the latest update). 

### What is the actual behaviour/value?

However the actual values shown by PoB for my build are much lower - this is due to total HP pool being calculated as half the actual - ~2350 instead of 4700 like it should be. Please see images attached.

### How to reproduce the issue

1. Import build from link
2. Compare the max hit taken total pool vs the actual life pool

### Build code

```shell
https://pastebin.com/BXpqYRyU
```

### Screenshots

![1](https://user-images.githubusercontent.com/99595899/153753861-344320e0-81a2-47b1-9449-ce59bd0dd6e4.png)
![2](https://user-images.githubusercontent.com/99595899/153753868-d1f1ea02-9bb3-42a5-ae70-52237766e1a4.png)

**Comment by Regisle** [comment]
This config it ticked, 
![image](https://user-images.githubusercontent.com/49933620/153754165-0db586b7-e248-4a83-88a0-6a214798dbe5.png)
which caps life recoverable to half your life, but the config is hidden due to no conditions applying that require it

Theres not a good fix for this, other than doing something like allocating pain attunement (or any other lowlife condition) so the config appears, then turning it off and removing pain attunement again

**Comment by fatherhet** [comment]
@Regisle thank you, never would have thought about that. Any idea on how it has bcome enabled by default after the update?

**Comment by Regisle** [comment]
You have petrified blood inactive in a link. My guess is, it was enabled by you (or whoever made the build) when they were messing around with that, but it didnt matter before the update so they forgot it on when they disabled the petrified blood

also 
![image](https://user-images.githubusercontent.com/49933620/153754560-dbd48fc6-ef91-4de5-999b-4958a3300a4f.png)
shouldnt be there anymore (as petrified blood now works for EHP and max hit)

**Comment by fatherhet** [comment]
Strangely Petrified Blood showed very large EHP/max hit increases before current PoB patch for me (far exceeding average 20%), but now it seems okay, thank you. Closing this.
