### ISSUE TITLE
Elementalist Exposure and Ashes of the Stars not being calculated properly

### ISSUE THREAD

**Issue by Lonnxx2** [PathOfBuildingCommunity/PathOfBuilding#4153]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I'm using a glove that has the modifier "Inflict Lightning Exposure on Hit", and Archdemon Crown (socketed skills applies exposure) with orb of storms socketed in, and both are not applying exposure properly. If i manually put "Hydrosphere" in any place of my build, it will instantly active exposure, raising dps values to the "real" value. 

Ashes of the Stars is not raising the quality on any active skill gem, my anomalous golems and anomalous crackling lance are not getting +28 to their quality

### What is the actual behaviour/value?

PoB doesnt calculate any "on hit" exposure granted by my items, so the dps is really inaccurate, even on poe.ninja. The same occurs with Ashes of The Stars amulet, as it doesnt raise the quality of any skill gem.

### How to reproduce the issue

- Put a glove with "Inflict Lightning Exposure on Hit" implicit, and the archdemon crown (Exposure on hit)
- Select any active skill gem
- Put the Active skill gem in any other piece of armour, that is not the crown
- Check the dps
- Deactivate the gloves (to see if exposure is not already coming from the gloves). The dps won't change
- Put the active skill gem on the helmet, to see if it procs exposure "on hit". Again, the dps won't change, as it is not applying the exposure
- To test the lightning exposure, just activate hydrosphere, as it applies lightning exposure when shocked.

### Build code

```shell
https://pastebin.com/Q8JHwb62
```

### Screenshots

![image](https://user-images.githubusercontent.com/99656111/153860885-94a0f52f-8a4f-437e-9fe0-a2b1a0c0d048.png)
Hidrosphere disabled
![image](https://user-images.githubusercontent.com/99656111/153860961-ad868b40-8535-4a0b-9e50-9894b4e31409.png)
Hidrosphere enabled

**Comment by Wires77** [comment]
Any red text in PoB is currently unsupported, so this is more a feature request to add parsing/support for those mods.

Ashes of the stars does work, it's adding quality to your crackling lance:
![image](https://user-images.githubusercontent.com/1209372/154340457-9fdc5b09-09b5-4ebf-86ac-41dc28bfd31c.png)

**Comment by Thomas-Masztalerz** [comment]
As I see, exposure is still not calculated and also not even shown correctly in calcs. Especially the Mastermind of Discord Node in Witch - Elementarist I can confirm doesnt work. #3801 looks like a similar problem.

**Comment by Wires77** [comment]
> As I see, exposure is still not calculated and also not even shown correctly in calcs. Especially the Mastermind of Discord Node in Witch - Elementarist I can confirm doesnt work. #3801 looks like a similar problem.

Can you provide a build for an example?  Allocating Mastermind of Discord and setting Wave of Conviction exposure to "Fire" shows the correct value:
![image](https://user-images.githubusercontent.com/1209372/154818274-38eee197-8299-46f7-bbf6-fa21643b1c4f.png)

**Comment by Thomas-Masztalerz** [comment]
thx a lot for your fast response. I am sorry! I looked at the wrong window: Curses and debuffs. There is only the -10 Exposure.
At the lightning damage window there is the correct -35 Exposure in the calculations.
![LightningDamage](https://user-images.githubusercontent.com/67073382/154818560-1e0db49e-a84f-4287-aeae-7bf55f2d1b98.png)
![Cursesanddebuffs](https://user-images.githubusercontent.com/67073382/154818562-34f0af13-9c4e-4ebf-b302-3f554a9ad42a.png)
