### ISSUE TITLE
Imported Character shows 99% spell suppression in Path of Building, 100% (or more) in game

### ISSUE THREAD

**Issue by richardcocks** [PathOfBuildingCommunity/PathOfBuilding#4154]
Importing my character eterms/archterm gives the following PoB which shows 99% spell suppression chance:

https://pobb.in/dDq9frNiEIyE

In game I'm getting 100% spell supression, even disabling grace in game I get 95% spell supression, whereas PoB with grace disabled shows 85%.

I can't work out the discrepancy, the calcs tab in PoB seems correct.

**Comment by emirkmo** [comment]
One of the major spell suppression nodes is conditional. Requires being at full life I think. Are you sure it’s not that?

**Comment by richardcocks** [comment]
> What is your account name and character name?

Sorry I thought I provided this, account Eterms, characters Archterm.

**Comment by richardcocks** [comment]
> One of the major spell suppression nodes is conditional. Requires being at full life I think. Are you sure it’s not that?

You're right, it's "Revenge of the Hunted", if I tick "always on full life" then I see the suppression in PoB. (Or more usefully, I'm not aware I'm not actually as capped as I thought!).

**Comment by emirkmo** [comment]
"Revenge of the Hunted": 10% Chance to prevent spell damage at full life.

That's the issue.
