### ISSUE TITLE
Config tab missing Ensnaring Arrow option as of the latest patch

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#4158]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

A config tab where you were able to specify how many snares from ensnaring arrow there were on the enemy

### What is the actual behaviour/value?

The tab is currently missing and projectile damage is not taking ensnaring arrow's projectile damage taken bonus is not taken into account

### How to reproduce the issue

Neither a downloaded build or a new build calculates ensnaring arrow's projectile damage bonus. Starting a new build or downloading my league starter is enough to repro it

### Build code

```shell
https://pastebin.com/9MxpUXMR
```

**Comment by combin** [comment]
Still no this option. ((
