### ISSUE TITLE
automatic interpretation of pastebin urls

### ISSUE THREAD

**Issue by rocmuse** [PathOfBuildingCommunity/PathOfBuilding#4163]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'd like PoB to automatically detect when a pastebin code is being entered into the "to import a build, enter the code here:" field.
This is a common issue for new users who do not know the difference between a PoB code and a pastebin url. This issue significantly and negatively impacts the usability of PoB for new users.

### Describe the solution you'd like

Because PoB codes do not include the "/" character, and pastebin links always include the "/" character, any time a code including that character is pasted into the field, PoB should check if "/" is preceded by "pastebin.com". If so, the field should act as the "enter website link" field.

### Describe alternatives you've considered

Alternatively, PoB could include more information in its "invalid code" error, something like "invalid code - did you mean to import from website?"

**Comment by pHiney** [comment]
Just to be clear you are asking that the popup (on the right in the piccie) be removed and it's functionality moved to the box on the left ?
![image](https://user-images.githubusercontent.com/4302241/154917270-b48bd238-c353-4aa1-a3d8-1a31abf89b1e.png)

X
