### ISSUE TITLE
Tencent/China PoB application?

### ISSUE THREAD

**Issue by ScaredTheDEV** [PathOfBuildingCommunity/PathOfBuilding#4166]
Since the current version of PoB doesn't allow importing from Tencent characters ( gives the error : Error retrieving character list : Response code 401 ), what app is there to view chinese/tencent characters, pastebins?

**Comment by Wires77** [comment]
Can you provide a link to a Tencent character for an example?  This used to work, so it's possible something changed on their end.

**Comment by ScaredTheDEV** [comment]
> Can you provide a link to a Tencent character for an example? This used to work, so it's possible something changed on their end.

Here https://poe.game.qq.com/account/view-profile/MrBoot

**Comment by ScaredTheDEV** [comment]
> Can you provide a link to a Tencent character for an example? This used to work, so it's possible something changed on their end.

found anything?

**Comment by Wires77** [comment]
If you (or anyone else) feels comfortable testing this, try inserting this bit of code in `Classes/ImportTab.lua`, on line 322, where it handles the other response codes:

```lua
elseif errMsg == "Response code: 401" then
			self.charImportStatus = colorCodes.NEGATIVE.."Sign-in is required."
			self.charImportMode = "GETSESSIONID"
			return
```

**Comment by ScaredTheDEV** [comment]
> If you (or anyone else) feels comfortable testing this, try inserting this bit of code in `Classes/ImportTab.lua`, on line 322, where it handles the other response codes:
> 
> ```lua
> elseif errMsg == "Response code: 401" then
> 			self.charImportStatus = colorCodes.NEGATIVE.."Sign-in is required."
> 			self.charImportMode = "GETSESSIONID"
> 			return
> ```
> 
> This will make the session ID input box appear, and you hopefully can copy your session ID and access characters that way. I'm unsure this will work, but like I said, I can't test it myself. It's likely that a cookie is needed as well that authenticates you with qq.com, which would take more work to implement.

I did insert that bit after the if because I saw the elseif state, and after I try to import a char's acc name from tencent, still the same error and nothing pops up, should I replace the code from line 322 or was it a problem?

**Comment by ScaredTheDEV** [comment]
And if nothing works, how should I search for chinese PoBs, what'd be some chinese poe build websites...

**Comment by cofedream** [comment]
> And if nothing works, how should I search for chinese PoBs, what'd be some chinese poe build websites...

I tested this code,that can be workes.
But first you need used website to encode acount name ,and put in field,instead of using program auto encode.
The program auto encode result is not correct to chinese word

**Comment by ScaredTheDEV** [comment]
> > And if nothing works, how should I search for chinese PoBs, what'd be some chinese poe build websites...
> 
> I tested this code,that can be workes. But first you need used website to encode account name ,and put in field,instead of using program auto encode. The program auto encode result is not correct to chinese word.

Can you explain a bit more?

**Comment by cofedream** [comment]
> > > And if nothing works, how should I search for chinese PoBs, what'd be some chinese poe build websites...
> > 
> > 
> > I tested this code,that can be workes. But first you need used website to encode account name ,and put in field,instead of using program auto encode. The program auto encode result is not correct to chinese word.
> 
> Can you explain a bit more?

I have debugged it ,just the default encode method has some problem,I remember there was a problem because  the file SimpleGraphic.dll.
You can use a single world for test,you will find different result of the program and the website.

**Comment by ScaredTheDEV** [comment]
> > > > And if nothing works, how should I search for chinese PoBs, what'd be some chinese poe build websites...
> > > 
> > > 
> > > I tested this code,that can be workes. But first you need used website to encode account name ,and put in field,instead of using program auto encode. The program auto encode result is not correct to chinese word.
> > 
> > 
> > Can you explain a bit more?
> 
> I have debugged it ,just the default encode method has some problem. I remember there was a problem because the file SimpleGraphic.dll,so the chinese POB has different dll file. You can use a single world for test,you will find different result of the program and the website.

Single world for test? I'm sorry but I can't really understand your guidance, do I have to replace the SimpleGraphic.dll with the chinese one?

**Comment by cofedream** [comment]
@ScaredTheDEV If you want importing from Tencent characters,you just do that,but you can only import the tree.
1. add code like Wires77 said
2. goto urlencoder.org paste you acount name and encode
3. copy result to pob and click start
4. copy POESESSID to pob and click go

If you want known why need do that, I can only tell you it's because of the dll.
A few months ago,I tried to replace the dll to chinese one, but it's will make pob crash.

**Comment by Wires77** [comment]
Ah, yeah if there are non-ASCII characters you'll have to convert them to something PoB can use in a web request.  Says as much underneath the import boxes:
![image](https://user-images.githubusercontent.com/1209372/154704528-f727705d-57eb-46c6-8661-4f57353d615d.png)

If that snippet of code works for you @cofedream I can make a PR to add it permanently.
