### ISSUE TITLE
support for flask duration

### ISSUE THREAD

**Issue by mindyk** [PathOfBuildingCommunity/PathOfBuilding#4176]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

i would like to see the flask duration calculation in the calc tab 

### Describe the solution you'd like

currently there is no way to see the actual flask duration the only duration shown is the one on the flask in the item menu but it does not take flask duration nodes on the tree into account (or maybe even any mods , did not test gear)

**Comment by LocalIdentity** [comment]
Hover over a flask on the Items tab and it will show you the duration and a number of other stats
