### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by NerL60** [PathOfBuildingCommunity/PathOfBuilding#4180]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when the application is first launched, the entire computer freezes with it and it closes, later after launching it immediately closes (after all downloads)

### What is the actual behaviour/value?

when the application is first launched, the entire computer freezes with it and it closes, later after launching it immediately closes (after all downloads)

### Build code

```shell
-
```

### Screenshots

![image](https://user-images.githubusercontent.com/99952372/154641099-d33a6c01-e4ac-439c-823d-fab45ad6b577.png)
after this screenshot, the application was closed

**Comment by Evinsta** [comment]
having the same issue, tried reinstall also downgrading to older version... had to install on different machine to be able to use it...

**Comment by Wires77** [comment]
Where is your PoB installed?  Did you try running it as an administrator?  Seems something is crashing when finishing the update download
