### ISSUE TITLE
Atziri's Rule spells are not properly tagged as spells.

### ISSUE THREAD

**Issue by JamesCScott** [PathOfBuildingCommunity/PathOfBuilding#4207]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The unique staff Atziri's Rule gives the following:
Grants Level 20 Queen's Demand Skill
Queen's Demand can Trigger Level 20 Flames of Judgement
Queen's Demand can Trigger Level 20 Storm of Judgement

 The spells triggered by Queen's Demand should be affected by modifiers to spells (spell damage, spell critical strike chance, etc.).

### What is the actual behaviour/value?

 The spells triggered by Queen's Demand are not being affected to most modifiers to spells.
 
The Archmage support seems to work properly, but every other source I've tried (passive tree, gear, support gems) does not seem to affect the damage of Flames of Judgement or Storm of Judgement.

### How to reproduce the issue

1. Equip "Atziri's Rule Judgement Staff"
2. Select either Flames of Judgement or Storm of Judgement
3. Equip either an amulet with #% increase spell damage or select "Witch" for class and take the starting "Spell Damage and Mana" node.
4. Watch the DPS

### Build code

```shell
https://pastebin.com/xpLi69Ak
```

**Comment by LocalIdentity** [comment]
Fixed in 2.16.0
