### ISSUE TITLE
Show GEM / Skill Purchase Information under the "Skills"-Window

### ISSUE THREAD

**Issue by manuakasam** [PathOfBuildingCommunity/PathOfBuilding#4228]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

For newer players, just looking at a PoB is quite helpful, but I think more could be done. During the leveling process for the first character a league you do not have access to any of the gem vendors. Furthermore depending on the class you play and depending on the guide you follow you may not even have access to certain gems at all. 

### Describe the solution you'd like

Enhance the "Skills" Information window with purchase informations of all actual Gems that you have equipped. I see two possible options.

1) Add a "Purchase" Window on a per-slot basis
2) Add a "Global Purchase" Window, showing all purchases for the whole setup

### Describe alternatives you've considered

Alternative does exist in the context of the "Notes" section. This, however, is something that content creators need to use and it's somewhat difficult to navigate, especially if people put a lot of textual information into the notes.

### Additional context

To my understanding the following conditions must be met:

1) A database MUST be created that stores information for gem-sources (Classes, Quests, Random only). **This might be the killer reason to NOT create this feature.**
2) Purchase Window MUST be relative to the class selected. If a selected class is unable to purchase a gem it should be highlighted in some way.
3) Purchase Window COULD show additional simple-mule information for "1st-to-town-rewards". I.e. Onslaught from Scion
4) Purchase Window COULD show prices for the gems and total cost accordingly.

**Comment by Wires77** [comment]
This is out-of-scope for PoB, especially since we don't have the data for this and would have to manually keep it up-to-date.

See #1539 and #4025 for other issues of this nature.
