### ISSUE TITLE
APK on Android and Mac

### ISSUE THREAD

**Issue by reimacneto** [PathOfBuildingCommunity/PathOfBuilding#4257]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Add a version for Android and iPhone, maybe selling on plataforms can be a good help for the owners of the project.

### Describe the solution you'd like

Add a version for Android and iPhone, maybe selling on plataforms can be a good help for the owners of the project.

### Describe alternatives you've considered

Add a version for Android and iPhone, maybe selling on plataforms can be a good help for the owners of the project.

### Additional context

Add a version for Android and iPhone, maybe selling on plataforms can be a good help for the owners of the project.

**Comment by PJacek** [comment]
There are no plans to port PoB to other platforms
