### ISSUE TITLE
When a new item is created, the changes for Minions are not displayed

### ISSUE THREAD

**Issue by FowlySenior** [PathOfBuildingCommunity/PathOfBuilding#4273]
I have imported via a pasbin link a build from Youtube into POB. In that instance of POB the changes of a new item (e.g. gloves) are shown. When a import my character into POB, the changes are not shown for minions. I have checked all settings and configurations, but it will not work.....

Thanks for helping.

![With changes](https://user-images.githubusercontent.com/101274924/157475613-86afdd54-3ede-4fe3-8a72-aafa89d168aa.PNG)
![Without changes](https://user-images.githubusercontent.com/101274924/157475774-2063cfb2-4e69-4dc7-8258-230a6bb21598.PNG)

**Comment by Wires77** [comment]
Please fill out the entire issue template, otherwise we can't help you.  My guess is you didn't select your minion skill in the left sidebar after importing your character.

**Comment by FowlySenior** [comment]
Hi, 
thanks for helping, but when I create a new issue, there is only a title and a text box for a comment. So what do you mean with "entire issue template"?

@skill selection: I have selected the skill, but still the same behavior.

**Comment by Wires77** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/new?assignees=&labels=bug&template=bug_report.yaml
