### ISSUE TITLE
Supreme Ego effect not properly calculated

### ISSUE THREAD

**Issue by xmdsx2** [PathOfBuildingCommunity/PathOfBuilding#4290]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Supreme ego's new effect is to add 1% _more_ aura effect per 2% of mana reserved. This means that, say, Hatred at 50% reservation (70% after Ego) would have 37.5% more aura effect, which PoB seems to completely ignore. I have tested the keystone in game and the damage of my main skill is visibly and numerically affected. 

### What is the actual behaviour/value?

PoB ignores the aura effect multiplier that should be added with the keystone. In my character I use Hatred aura, with 50% base reservation and 75% with the keystone. This should add 37.5% more effect, as is shown in-game before and after picking the keystone:
![image](https://user-images.githubusercontent.com/101831575/158884782-0dc893ca-1a53-4109-8abf-fb377b4d2b2d.png)
![image](https://user-images.githubusercontent.com/101831575/158884840-19afb74e-6b29-4e92-85f6-4cb1c918aaf3.png)
PoB ignores it as shown below:
![image](https://user-images.githubusercontent.com/101831575/158885055-d1e26eed-0816-4079-b610-c3cce309d848.png)

### How to reproduce the issue

Simply run an aura of your choice (in my example I use Hatred as that is my main aura) and pick/remove the keystone in-game and then in PoB and you will see the damage in PoB is unchanged and you have to add the "more aura effect" by hand under Custom Modifiers tab.

### Build code

```shell
https://pastebin.com/EvwkYsAw
```

**Comment by xmdsx2** [comment]
I just realized the PoB screenshot is not properly set. I changed to the auras setup to show they're the only auras I have, but I did not show my main skill being affected. It goes as follows:
![image](https://user-images.githubusercontent.com/101831575/158885886-6725b6a6-cbab-435f-b6b7-af7096bea567.png)

**Comment by learn2draw** [comment]
Red text isn't supported, would be a feature request and not a bug

**Comment by xmdsx2** [comment]
> Red text isn't supported, would be a feature request and not a bug

Sorry, this is my very first time using github and I didn't even see that option xd
