### ISSUE TITLE
Error when importing character from POE Account

### ISSUE THREAD

**Issue by Celavieswe** [PathOfBuildingCommunity/PathOfBuilding#4295]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should be able to import my character from my Path of Exile account into Path of Building Community fork.

### What is the actual behaviour/value?

I get an error and I have to restart the application.

### How to reproduce the issue

1. Launch Path of Building Community Fork 2.16.0 portable version.
2. Select Import/Export build
3. Use account name "Celavie"
4. Click Start.
5. Choose league SSF Archnemesis
6. Choose character "Strong_and_smart"
7. Click Import: "Items and Skills"

### Build code

```shell
I can not generate a build code.
```

### Screenshots

![ERROR](https://user-images.githubusercontent.com/101863837/158965656-fe7c891c-7a8c-40b7-bc0d-a4c11ccf5891.jpg)

**Comment by Celavieswe** [comment]
Additional information: My other characters are importing fine.

**Comment by pHiney** [comment]
https://www.pathofexile.com/account/view-profile/Celavie/characters

It's to do with the Energy Blade. Looking further into it.

X

**Comment by pHiney** [comment]
I found the error, luckily before you change your build.

Will post a fix later today. IRL interfering.

x
