### ISSUE TITLE
Increased effect of map modifiers

### ISSUE THREAD

**Issue by davidponton** [PathOfBuildingCommunity/PathOfBuilding#4300]
I'm currently trying to tweak my build a little to better deal with "60% less recovery rate of Life and Energy Shield" and I realize now that PoB only lets me select 20/40/60% as options even though my atlas tree actually puts this mod at 70%. Would it be possible to add effect of map modifiers somewhere?

**Comment by LocalIdentity** [comment]
Added in 2.29.0
