### ISSUE TITLE
Sadist Cluster skill - no option for recently ignited/chilled/shocked

### ISSUE THREAD

**Issue by asschun** [PathOfBuildingCommunity/PathOfBuilding#4304]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Cluster Jewel with the Sadist skill active adds no DPS

Didn't there used to be a section for chilled/ignited/shocked recently? What happened to those boxes?

This is NOT a duplicate of #1614. This is a new issue since the solution posted there no longer exists. 

### Describe the solution you'd like

add the function back

**Comment by LocalIdentity** [comment]
You need to provide a build code as the node is working just fine for me

**Comment by asschun** [comment]
I don't know what that is. Could you explain? 

For you, do the options for ignite/shock/chill recently exist in the "When in combat" section?

**Comment by LocalIdentity** [comment]
Provide a pastebin for the build you're looking at. Here's what  I see if I add the notable to a large cluster 
![image](https://user-images.githubusercontent.com/31035929/159617210-c3616d0b-0cc4-496f-a48c-4075fb68a3a9.png)

**Comment by Lothrik** [comment]
I can't reproduce this issue either, everything about the Sadist notable seems to work perfectly as of 2.18.1.
