### ISSUE TITLE
Implement Renewal Notable

### ISSUE THREAD

**Issue by dclamage** [PathOfBuildingCommunity/PathOfBuilding#431]
Second mod does not parse:

    Minions Regenerate 1% of Life per second
    Minions have 10% chance to deal Double Damage while they are on Full Life

Note that it does parse without the "while they are on Full Life" condition, as so:

    Minions have 10% chance to deal Double Damage

Certain minions are always on Full Life and thus should always meet this condition. For other minions, perhaps this should be a configuration by the user.

**Comment by LocalIdentity** [comment]
Renewal

**Comment by mikealy** [comment]
Was this tested? I'm on 1.4.170.7, and I don't see a config option for full life on minions, and the node only seems to give minion regen
