### ISSUE TITLE
Bug regarding the calculation of mitigated hits

### ISSUE THREAD

**Issue by DG-za** [PathOfBuildingCommunity/PathOfBuilding#4310]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When my maximum elemental resistances increase from 80% to 90%, my mitigated hits and eHP should increase somewhat proportionally.

### What is the actual behaviour/value?

When my maximum elemental resistances increase from 80% to 90% (keeping all else constant), my mitigated hits and eHP halves. Since there is no calculation tooltip for the mitigated hits, it's unclear why this is happening.

80% max ele res
![image](https://user-images.githubusercontent.com/35300630/160279100-d0a29191-65ad-40c3-82c7-decfc2c63ab5.png)

90% max ele res
![image](https://user-images.githubusercontent.com/35300630/160279075-ebf5515a-4861-40f7-b9b9-4b484abf178f.png)

This also happens when other minor changes are made to the build (e.g. adding one level of Determination aura, losing 3% of evasion rating, etc.), making it impossible to figure out how defensive changes are actually affecting the build. The screenshot below shows another example regarding chaos resistance:

Pure chaos res increase results in a eHP decrease
![image](https://user-images.githubusercontent.com/35300630/160279496-3c783f8e-bf20-446a-8749-f1d9a381dc9b.png)

My current guesses (without understanding how the mitigated hits are calculated) is that the bug is caused by one of three things:
1. Some small value being rounded up or down with a massive effect.
2. Something related to life gained on block or regen, causing players to have a net gain of life per hit.
3. Some breakpoint being missed, where if the character avoids death at a specific number of hits, it regenerates and then survives another 40 hits.

Those are just guesses though.

### How to reproduce the issue

1. Import the POB
2. Open the configuration section
3. Add "+10% to all maximum resistances" (or simply enable the Melding of the Flesh jewel in Socket 5)
4. Verify the changes to the eHP.

### Build code

```shell
https://poe.ninja/pob/4WD
```

**Comment by Lilylicious** [comment]
This relates to a known issue with Aegis Aurora. Removing that shield and making sure resists are capped makes the changes behave as expected. Specifically, the ES replenishment on block is being calculated in the EHP calcs, but it's being done so poorly. It's possible this will be entirely disabled in the future.

I believe #4227 contains at the very least a config to disable EHP gains on block, but I'm unsure if it does more for this.

A temporary way to mitigate this is to edit the Aegis Aurora in your build to disable the line. The easiest way to do this is to remove the line entirely, or add any character before it such as "-".

**Comment by DG-za** [comment]
> This relates to a known issue with Aegis Aurora. Removing that shield and making sure resists are capped makes the changes behave as expected. Specifically, the ES replenishment on block is being calculated in the EHP calcs, but it's being done so poorly. It's possible this will be entirely disabled in the future.
> 
> I believe #4227 contains at the very least a config to disable EHP gains on block, but I'm unsure if it does more for this.
> 
> A temporary way to mitigate this is to edit the Aegis Aurora in your build to disable the line. The easiest way to do this is to remove the line entirely, or add any character before it such as "-".

Thanks @Lilylicious, that solves it.

From what you said, my guess #2 (ES gain on block) is the source of the issue, while guess #3 (breakpoint being missed) might cause the symptoms. If that's the case, then I think removing the modifier from POB might be the only feasible solution.

From what I remember, these problems (minor input differences leading to dramatically different results) are usually solved by either changing your algorithm to better avoid local minima / maxima (if you're trying to find the global minimum / maximum) or by running thousands of simulations with minor changes to find an average expected result. In either case, that sounds like an engine rework to accommodate a single item, which is probably not feasible.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4227.
No Melding
![image](https://user-images.githubusercontent.com/31533893/178146707-4cf1fd74-a047-4098-8fce-b06c44afb186.png)
Melding
![image](https://user-images.githubusercontent.com/31533893/178146703-cb6b47e7-617f-489d-92f3-dfe2a4e6bc24.png)
