### ISSUE TITLE
Create a warning for high memory usage

### ISSUE THREAD

**Issue by Jzir** [PathOfBuildingCommunity/PathOfBuilding#4311]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

At the moment, POB has an issue with memory usage due to how LUA allocates and the limit of 2GB it has. Whilst this is something I know is being looked at and discussed, it is affecting users right now, and there may not be a fix for a while.

### Describe the solution you'd like

In the meantime, would it be possible to have some form of warning for users for high POB memory usage? After talking to Zao, he has mentioned the info should already be available to the app, so should be possible to display to users.

Something like: 

Pob starts at 0% memory usage. A user uses some, it goes to roughly 10%, but there is GC happening all the time, so the memory usage is somewhere between 0-10%. Then they keep using, and we go to 10-20%, 20-30%, and so on. When we reach 80-90%, it would be time to show a warning to users saying something like 'POB has almost reached the limit of its maximum allowed memory usage. This may lead to a crash of POB in the near future, please save your open POBs now.'

I know obviously the preferred solution is to not have the problem at all, but whilst it's here, I (and other users that have discussed this) would much rather know and be able to save, than just have POB crash and poof all the time you just spent into it.

**Comment by jix91** [comment]
I support this, my app is crashing all the time. I already suggested another solution, which would be even more convenient. Add an option to enable auto-save with an adjustable time in minutes. This way I can set auto save to 1 minute and not care about watching any memory levels. I at most lose 1 minute. Pobs without a save name are saved in a subfolder under "unsaved imports" pobs that are opened from a save state override the current save state.

**Comment by Debugnium** [comment]
A lot of the Memory issues are the result of the undo handler storing too much information in its tables.

In the `.\Classes` folder, there is a file called `UndoHandler.lua`, if you change the value on `self.undo[102]` to a smaller number such as `self.undo[7]` you will not experience memory-related crashes as often. The downside is that you will now only be able to undo at most 5 actions. While I was working on a detailed build guide with this change PoB only used 700MB of memory at most.

There is already Issue #3733 open which shows how to reproduce this. I think the undo actions should be lowered to 10 or 20 and a UI element exposed to adjust this with a memory warning. At least until the undo function can be improved or anything that utilises it gets reigned in a bit.  Better yet separating item, skill, and tree undos would probably make sense - its the item undos that cause the memory issue.

**Comment by ImVexed** [comment]
Could this also be temporarily fixed by increasing the 2Gb limit? 

Apparently, you can add a build flag for 64-bit builds: https://stackoverflow.com/a/56283816/3361302

**Comment by zao** [comment]
For 32-bit builds, something like LARGEADDRESSAWARE might get you to 3-4 GiB but that requires that all the code is clean enough to handle user addresses with the high bit set.

For 64-bit builds, we need to move on to LuaJIT 2.1 to get GC64. I've got private 64-bit ports of PoB with it enabled that can use quite a bit of memory but I am not entirely certain that everything about the PoB runtime is 64-bit clean and those experiments are intermingled with a lot of other work in progress.

One of the big complications with moving to LuaJIT 2.1 is that the author doesn't believe in releases anymore and you're just supposed to grab an arbitrary commit from `master` and hope it's stable. As they're actively developing it, that can be quite the gamble.

**Comment by Wires77** [comment]
Fixed by #4530 

Let us know if you're still having a problem relating to this
