### ISSUE TITLE
Can't import my account to PoB "Account profile is private"

### ISSUE THREAD

**Issue by leroggan** [PathOfBuildingCommunity/PathOfBuilding#4314]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Considering every single privacy setting in my account (wich is Rogganz8) is off, there is no reason to show that it is private.
![image](https://user-images.githubusercontent.com/84161802/161141207-70081e2b-3328-4e2b-a95a-395372ef9cd2.png)

I already tried using my POESESSID, reinstalling PoB, logging off, and marking and unmarking privacy settings, but nothing worked.
I even tried importing other public accounts, but the same message is displayed.

### What is the actual behaviour/value?

**This is how it looks before i try to import my account:** 
![image](https://user-images.githubusercontent.com/84161802/161142688-dfbd240e-cd8a-48ac-8492-a504bab9fb7e.png)

**When i press "start":**
![image](https://user-images.githubusercontent.com/84161802/161143284-c16e9074-9922-4b61-b5a4-f838101bb5f7.png)

### How to reproduce the issue

1.Insert the account name
2.Press start
3.Account profile is private

### Build code

```shell
Can't provide a code, but my account is "Rogganz8", and i use PoB Community Fork 2.16.0
```

**Comment by jwfiredragon** [comment]
I tried your account just now and was successfully able to import your characters. Have you tried this again recently?

![image](https://user-images.githubusercontent.com/6947594/162038067-648f9f62-2ea6-4de9-8654-8bee1acb9425.png)

**Comment by pHiney** [comment]
It works for ME to. I've never had to refer to my POESSESID.

I have a static IP address, use FireFox and tick the box in https://www.pathofexile.com/login to always remember me.

I'm not sure if any of that is relevant. Just wanted to list things that i can think of for how i think my setup works.

x

**Comment by botboy434** [comment]
Have you checked your firewall?
That might be blocking the connection to the server. It could also be that you were offline for some reason
