### ISSUE TITLE
wine for linux - font always too small

### ISSUE THREAD

**Issue by coldsilk** [PathOfBuildingCommunity/PathOfBuilding#4320]
To increase the font size I usually use the dpi setting in wine under "Graphics", however it has no effect. Could you add something to increase the size of all text?

Picture: 

![Screenshot_20220407_094441](https://user-images.githubusercontent.com/60486751/162213680-e7dfda9a-7da3-4157-81e2-9d3d24060db9.jpg)

**Comment by ppoelzl** [comment]
I'm afraid it's not possible to change the font size. Everything is hardcoded.
