### ISSUE TITLE
Ignite deals 90% of base fire damage per second?

### ISSUE THREAD

**Issue by stalris** [PathOfBuildingCommunity/PathOfBuilding#4322]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Hi, I'm new to Path of Exile so sorry if there was a better place to ask this.

PoB says that ignite deals 90% of base fire damage per second but I couldn't find a source for this. I saw that poewiki references the [3.17 Siege of Atlas](https://www.pathofexile.com/forum/view-thread/3229187) patch notes but when I ctrl-f ignite I don't see where it explicitly says ignite deals 90% of base fire damage per second. I don't know whether I'm misunderstanding the patch notes but can you explain how you guys know this is true? Thanks in advance.

### What is the actual behaviour/value?

Don't know actual value of ignite.

### How to reproduce the issue

In PoB I created a magic crude bow with the lowest added fire damage modifier with a level 1 duelist and no skills allocated. The "calcs" screen shows that ignite dps is 90% of ignite damage per second.

### Build code

```shell
eNqtWltz4rgSfg6_wsV7uEOAIrtFCEmoghkOzsyc8zSl2A1oI1usLUOYrf3v25JNYDJc2tqTqUqM-Vrd_XWru6Wa3u9vgXDWEMVchrfFaqlSdCD0pM_DxW3xy_PDdbv4-2-F3pSp5ef5XcKF_ua3wlXPPDsC1iBQrugoFi1Afd2tVP-OK61YqJYgwwn7Q0aP0r8tfpIhFJ0XFvpc7T55gsXxJxbAbdH1ULjosNiD0B_s36fAgPHQld4rqMdIJiujds1hM5E-YkaT6efZ84FSHh4qRZuvelPBthC5iiknxl-3xT66zhZwzwL8jasxkeBS1Vqp2bmpNm46nXa1Viwfl3VXAP5eptQ8BZxGMJzPwVN8DYOIq8GShd5e20m5I9hGqXMWPkmE4ivBIaIY9vTL-p3OKeyzVEzcT939uu1Su9O8qVU7SFX7vJhU72KVU8hvXC3vBFKaX8loEXIFh3I3JYRX25V2o1JrtdvndP4qXGuVWtV6p1Jr128ajc454anksQztabGweZAIgXvwUPIkpwMZvPDwZ0qJ3k1YyAYyJgRuzOdAQw5dGm6Gm5GG1FZOIcJyoejG5hLINLjgSSxJeXTkETnww06ZheTQtRGwUOSqfTWqnUTdwxsBNYM_fwK2TtaEUJGUrqUyPeeSE2bHDp-m78jWTaneanQ6rU61UumctCMlCpsRD5iYsDceJAHW3Wf2Cnut9ZvTRVoHeK-0cqYbeV2NHYUeLWu-hBHEEK0PmliLKJDlwb7oVc4KzmABIc2oMYC3fMRGP2MKaPtm30jPk6OxJHI08Ag5TaJADnK04AdySmcrck56vrHIJ-zrEKLF1l1yEAS04fJQhMTpoQAxHQ5Fcvo9XLP4cFdXW-e9SeG05ACcUVDAhw-jU-X0-Cf_0MOfyCfWjwKZRMR4pGCSA9PlNuYeTh9m5p2Bn3i0Cvg-w07kGgLMcDMA4_C9p_mU6J3AsZ3qOC4rRC6JvlLMe72X_gJyKckv4SarFe5znS1UuQceIcsxP-iU1y0C-jMeTQZsRRny9JaiKtijyQrGfLFUIc6cdC0fROi-LJmMczizh5NVPOD8TBqep3KDSy71uTbOh8Y2v2_tJ-2IIPyxJa__E5ykYBj6SaRzlKzjo8Svanplc-7XT6NgJSNlXg6Y8GKz5ChcJcoJzaE94LH3_SWZz_X5vIgqInOpMHx4GA6eR1-HmRWHIvErF-J7mAQv-gCb_t2XFRdMpXI8KQRbxYBH-5CLosPxwdWSLtZmTxHQOIBlR_7LWOyhXsSRvstQfc4lmGruDS7j9HmeAMM4MAFUip63K9ARj2ksZUXuMtac3Am49MBMccscyymkg8e2BNz7CEHADgX0udA9jsLTBBM9bY4UNDariL8kipRRZvgnWKDHYIJbh4MeKfMpsGxQIajPprLLyKwDUNIOxwRiiO5hDpjMpI1sikN6RkvL3q7E9cwuip0Ya98jBPHdFnvJgyb0w21LwBSmGwRjfUP6LHVFZZ6CaJzemM6ZiHVRPFzmtqiiBF_6MGeJ0O__kzDB1VaX7IO32RLG2ngpN3ooSdfRuzvGiIzH6Td9obIltJKdVuPRcwTgMDPP6QlSV9mUFvxweAE78o32gMVo_DZL89siVmes6vjQbLfr9aKjcLmDy9_qTXavm4rrla96Qx93tP9Jy5XTN19mY_NwtVRqFXfL5c1mU1oxtZRzeMOBueTJoLzCZdDKa9McrrWich9_7hZ982MWKu9W6qUXxKmCXll7Y-Kn3dUPnyRuPP2dfrn7YMj4ymHjxIDVfumqSHv4Q8rgf8Z7zeUTMDVhq4x3_V0Wh3oWBayq9xz5iUyW7YKpgf_d9dzeSGEcMtr1swvKXGMnMaQXBd-ArWRoXms9aYdEoEnLNERXM4adYdt1Jv3H0aCg7QLfcZeYAs6d3BQGEZvjm66jDShMI5jzt67zFzb2BXQrf48lDv993wdfz5pZpm_kEwv9asHFdq3R-sq8kKVO16kUMla7zuP1-7-C8X8Gf3adZgG7kOAe15BKAVePnbqjpNNytBIn1WIiop1JE03IXdtPnXaQB0yQYOTvW37G0Ul-Dmk5tqK7YSun_7KNYyac1AmnuVeTTUJHRT-K1Whiv_jwE-pOShVbGnTMlwtG3YFQOUUecNe-OnWSSbVjJtXt6KWRUPs_iTXsjGzZaWvZs1m9EOBj-XQhAk-Ak43Kq-hIJrVs9FxIv0ch1_qokn_huv0uqtroa9jlQtUu8xqXw0MhNu-yx9LL0nFS3Wla2GNRA-uX1PhbJx1rc4bvOMtW-dW0ESJtSUogrPxsWtNas4h7y24n1e3St54_yxr2Zd8ip6vW5NcpCdGggCzM_hfDDzGS9lFoWWSlfRj-RbpQS7KWJe4aOtSCuRkPF7RJIHehOEmvZbmgx9PGnTqBp6p9GBrWbDVtvKHsF_skv2BSP0jEkd6WnjjxwGiuAcz521xZy3DOF4jolT_-37Z_AMFWLB0=
```

### Screenshots

![image](https://user-images.githubusercontent.com/26214174/162318585-11008c92-8dfd-479a-906c-4570dc5705d7.png)

**Comment by Wires77** [comment]
In 3.16.0, Ignite was changed to deal 125% of base damage as ignite damage over 4 seconds.  https://www.pathofexile.com/forum/view-thread/3186390#elementaldamageovertime

In 3.17.0, GGG "lower[ed] the damage of player Ignite by 28%".  This is consistent with the wording of the 3.16.0 patch note, so 125% * (100% - 28%) = 90% is the new base damage of an ignite.  https://www.pathofexile.com/forum/view-thread/3229187#hit-basedspellcasting
