### ISSUE TITLE
Account name is incorrect

### ISSUE THREAD

**Issue by savetrev** [PathOfBuildingCommunity/PathOfBuilding#4328]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Able to import my character into POB

### What is the actual behaviour/value?

I can't import my character into POB. I looked at recent posts in here and their names work.

Name: TheFlans
PC
It says Account Name is Incorrect
Thank you for the help! :)
https://www.pathofexile.com/account/view-profile/savetrev/characters

### How to reproduce the issue

Character Import
PC: TheFlans
Account name is incorrect

### Build code

```shell
Not sure
```

**Comment by zao** [comment]
It seems like `TheFlans` is your character name. The account name is the one you are logged into the pathofexile.com website where it also shows in the top left corner - it's the one used to look at your profile.

The workflow here is that you enter your account name and PoB retrieves a list of the characters and leagues from that account.

**Comment by savetrev** [comment]
Yikes, I misread it... I'm so sorry... I thought you put in the character name there, not the account name!
I'm so sorry! and thank you so much! I can't believe I didn't even try the account name (I've been trying on an off for a month!)
