### ISSUE TITLE
Calculation Bug for Viperstrike

### ISSUE THREAD

**Issue by hurrier1** [PathOfBuildingCommunity/PathOfBuilding#4356]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I tried some numbers for viper strike and the caluation for the damage.

If you dual wield the both weapons the maximum poison stack goes from example 100 to 300.
That reason for that is that every weapon counts as doubled. the right value should be 150.
There is a *2 multiplier for main and off hand.

it should be 1 for offhand and 1 for main hand

### What is the actual behaviour/value?

hover over max poison stacks, if you dual wield waspnest and you will see that it calcs every weapon twice

### How to reproduce the issue

just use any class and dual wield 2 wasp nest to repeat the error and than check under clacs the max poison stacks,

### Build code

```shell
Sorry i can write code just found that mistake.
```

### Screenshots

![f4fa32469f4b58123d3cd81d83aa7858](https://user-images.githubusercontent.com/105184731/167333297-20664084-23ae-4ceb-8405-e80fd7991740.png)

**Comment by Regisle** [comment]
Build code refers to a code to import the build, like a pastebin link

This is correct that it should not have the stack multiplier for the skill anymore, this is leftover from when viper strike would add its weapons together for one big hit

**Comment by hurrier1** [comment]
https://pastebin.com/RyQx3EUp

i used this one as an example
