### ISSUE TITLE
PoB won't open after installing

### ISSUE THREAD

**Issue by SirLaxton** [PathOfBuildingCommunity/PathOfBuilding#4362]
![PoB won't open](https://user-images.githubusercontent.com/105388873/167928678-0c00c4ec-292f-42a6-bd2e-1b705005b3d7.png)
For some reason after installing it again, the PoB won't open, even when i try to run it as admin. I've already gonne through some other posts in the forum and see if i could find anything relatable but couldn't find. (sorry if i misspelled something, still improving my english).

**Comment by QuickStick123** [comment]
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736 see https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087 for tempoary fix.
