### ISSUE TITLE
Implement Wrapped in Flame Notable

### ISSUE THREAD

**Issue by dclamage** [PathOfBuildingCommunity/PathOfBuilding#437]
The "while Burning" condition does not parse for 2nd and 3rd properties:

    20% increased Burning Damage
    +15% to Fire Damage over Time Multiplier while Burning
    Regenerate 1.50% of Life per second while Burning

Will need to add a "Are you Burning?" configuration.

**Comment by LocalIdentity** [comment]
Added in 1.4.162.1
