### ISSUE TITLE
Radius ring for Anatomical Knowledge not shown

### ISSUE THREAD

**Issue by zao** [PathOfBuildingCommunity/PathOfBuilding#4378]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When looking at the tree I expect to see the radius of the Anatomical Knowledge jewel when socketed into a jewel socket.

### What is the actual behaviour/value?

It doesn't show any influence radius when not hovered.
When hovering it shows the three radius circles from the socket itself but nothing from the jewel.

### How to reproduce the issue

Load build code.
Look at passive skill tree around the socketed jewel.

### Character build code

```shell
https://pobb.in/UBZ7nvJT9cug
```

### Screenshots

![image](https://user-images.githubusercontent.com/260218/169303319-0e93b1da-fadf-4709-ba56-458b18fed88b.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.17.2
