### ISSUE TITLE
Lethal Pride Timeless Jewel - "Tempered By War Keystone"

### ISSUE THREAD

**Issue by Tusamie** [PathOfBuildingCommunity/PathOfBuilding#4380]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I am using "Lethal pride Timeless jewel"  With Rakaia

I select "Tempered By War Keystone" -50% less lightning and cold res

I am testing a Doryani's Prototype resistance build with melding

### What is the actual behaviour/value?

Before doing so I have -135 Lightning Resistances.

When I select I go UP to -68 lightning resistances.

### Character build code

```shell
http://poeurl.com/dEXo
```

**Comment by Regisle** [comment]
-135 * 0.5 = -68, math is correct?

**Comment by Tusamie** [comment]
> -135 * 0.5 = -68, math is correct?

Ohh this is a 0.5 modifier but it doesn't lower negative values? thanks for the insight.

**Comment by Regisle** [comment]
Yeah less refers to the magnitude of the value, it always makes it go closer to 0, even if its negative
