### ISSUE TITLE
Forbidden Rite Self Damage at a glance

### ISSUE THREAD

**Issue by Qazymoto** [PathOfBuildingCommunity/PathOfBuilding#4389]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

There is currently no way to quickly see how much damage forbidden rite does to you at a glance, you have to do the math manually.

### Describe the solution you'd like

Add a line of text in the calcs or skills tab that shows how much damage it will do to you.

### Additional context

Knowing the exact amount of damage you're taking from forbidden rite (and heartbound loop now that I think about it) is incredibly relevant for CWDT builds.

**Comment by LocalIdentity** [comment]
I'm making a Ward CWDT build atm and agree that it would be really helpful. Gonna work on it right now

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4420.
