### ISSUE TITLE
Incinerate Stage Issue

### ISSUE THREAD

**Issue by Dragonxtamer596** [PathOfBuildingCommunity/PathOfBuilding#4393]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Skill stages of incinerate won't update after 8. The labyrinth enchantment allows for a +2 stage.

### What is the actual behaviour/value?

The skill stages stops updating dps after 8 stages.

### How to reproduce the issue

Add incinerate skill gem
Add stages past 8

### Character build code

```shell
https://pastebin.com/8WfGKY6q
```

**Comment by QuickStick123** [comment]
This was fixed recently or wasn't an issue.
Without +2
![image](https://user-images.githubusercontent.com/31533893/175771325-7dc8f660-ab69-4f1c-834a-297f9b528e09.png)

With
![image](https://user-images.githubusercontent.com/31533893/175771335-6b05eb18-3ce4-4176-979f-f1c74aa2f371.png)
