### ISSUE TITLE
Effective Hit Pool makes everything lag if it gets over 1 million.

### ISSUE THREAD

**Issue by eabemitchell** [PathOfBuildingCommunity/PathOfBuilding#4408]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

It shouldn't lag... Not like this anyways.

### What is the actual behaviour/value?

When you hover over anything it takes a lot longer to display.

Trying to create an item is really hard. As it doesn't register all mouse clicks. And the hover over display takes forever to display.

It doesn't matter what you do in the tool. It will be slow and laggy. On ever single tab such as skills, tree, Items, etc....

### How to reproduce the issue

Just load in the POB link it should already be very laggy.

Unless I accidently sent it with Glancing Blows keystone allocated. You can fix the issue by clicking Glancing Blows, and re-created it by taking it off again. The math in the background seems to be what is killing it.

### Character build code

```shell
https://pastebin.com/fpkPXKwD
```

**Comment by Regisle** [comment]
should be fixed by #4227 as that speeds it up alot and fixes a few issues with speedup not working, can you please test on that branch (it works for me), or if it gets merged Ill try and follow up on this

**Comment by eabemitchell** [comment]
Hmm I never downloaded a test build before. Looks like I need to install something like github desktop... I don't have the time to figure that all out right now. Maybe if I get around to it next week. Thanks for the heads up though.

**Comment by Nightblade** [comment]
I think you can just download it as a zip:  https://github.com/Regisle/PathOfBuilding/archive/refs/heads/MinorEHPImprovments.zip

Then just start it by double-clicking: `C:\Where_you_unzipped_it\runtime\Path{space}of{space}Building.exe`

**Comment by eabemitchell** [comment]
Ok. So I downloaded it using the link provided by Nightblade. While it is a little better. It is still laggy. It went from waiting for like a minuet to have a popup show correctly. To only waiting like 3 to 5 seconds.

However; If I click the Glancing Blows keystone all the lag goes away just like before. It is improved a lot. But I am not sure I would call it fixed.

**Comment by Wires77** [comment]
Loading your build up I see you have some socket groups checked to include in the Full DPS that really don't need to be.  Turning off all of those (since 99% of your damage is coming from RF) eliminates almost all of the lag.  There are still some optimizations we can probably do, but having multiple groups of skills included in the FullDPS calculations essentially runs all of the calculations that many times (unnecessarily, in this case)

**Comment by QuickStick123** [comment]
I am getting about 0.4s of lags tops this isn't perfect but is good enough to not be a non issue. This is inpart due to lots of skill groups in full dps and ehp calculations.
Closing as fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4227.
