### ISSUE TITLE
Implement Steady Torment Notable

### ISSUE THREAD

**Issue by dclamage** [PathOfBuildingCommunity/PathOfBuilding#441]
Mods 3 and 4 do not parse:

    20% increased Poison Duration
    20% increased Bleeding Duration
    +10% to Damage over Time Multiplier for Bleeding you inflict on Poisoned Enemies
    +10% to Damage over Time Multiplier for Poison you inflict on Bleeding Enemies

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
