### ISSUE TITLE
PoB Mana Reservation doesn't match ingame mana reservation

### ISSUE THREAD

**Issue by sgtsaint** [PathOfBuildingCommunity/PathOfBuilding#4434]
Hi,

After importing my character in PoB I noticed that the mana reservation efficiency didn't match the in-game reservation.

Below you'll find the PoB calculation:
![total mana](https://user-images.githubusercontent.com/62376868/172139501-c6bceddb-4c72-468e-bb3f-3084fbbb4988.png)

![reservation calc](https://user-images.githubusercontent.com/62376868/172138291-90def853-5b20-4ae5-920c-456af900ba7d.png)

And in-game it looks like this: 
![ingame mana](https://user-images.githubusercontent.com/62376868/172138845-fe682aa8-f181-4fa7-a68d-93ac3b2c9bde.png)
Determination: 32.62%
Malevolence: 32.62%
Herald of Ice: 16.31%
Defiance Banner: 7.09%
Precision: 81 mana

No changes were made in the PoB, just a straight up import.

**Comment by LocalIdentity** [comment]
Without a build code, or account name this is impossible for us to check and see the issue

**Comment by sgtsaint** [comment]
@LocalIdentity My bad, completely forgot!

https://www.pathofexile.com/account/view-profile/SgtSaint/characters
Character name: SgtOneLastTime

PoB Fork build: 2.18.1

**Comment by LocalIdentity** [comment]
I think it's something strange to do with your militant faith timeless jewel when it imports into PoB. If you unequip the jewel and import are the values correct?

**Comment by LocalIdentity** [comment]
Tracked down the issue to the Militant Faith jewel changing the Charisma node
