### ISSUE TITLE
Implement Vile Reinvigoration Notable

### ISSUE THREAD

**Issue by dclamage** [PathOfBuildingCommunity/PathOfBuilding#444]
Last mod does not parse:

    24% increased Damage over Time
    6% increased maximum Energy Shield
    Regenerate 2% of Energy Shield per second if you’ve Killed an Enemy Recently

Likely will need to add a "Killed an Enemy Recently" config checkbox.

**Comment by LocalIdentity** [comment]
Added in 1.4.162.1
