### ISSUE TITLE
[auto-update] Auto update failed due to network issues.

### ISSUE THREAD

**Issue by phshy0607** [PathOfBuildingCommunity/PathOfBuilding#4456]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

No and yes.

I'm a player in China which have poor internet connections for pob to auto update.

I've tried 
1. change my hosts file to resolve DNS address, the update check went through, but failed to update at the end.
2. VPN

### Describe the solution you'd like

Release every version for downloading.

### Describe alternatives you've considered

Solutions for poor network connections, which is probably impossible.

**Comment by Wires77** [comment]
Yes, it seems auto-updates are an issue for Chinese users.  We try to upload every release to GitHub, but it would be good to have that done through our automated builds
