### ISSUE TITLE
Recent patch contains no update notes

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#4465]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

As with every PoB patch, there were always notes available to see what was changed. I think it's rather obvious that this would be the expected behavior :)

### What is the actual behaviour/value?

Patch/Update notes are empty.

### Character build code

```shell
n/a
```

### Screenshots

![image](https://user-images.githubusercontent.com/47370800/174262119-9ece40c5-a11f-4186-af1b-b991670af1e4.png)

**Comment by LocalIdentity** [comment]
It was the removal of a file no longer in use
