### ISSUE TITLE
How to open a build from pastebin?

### ISSUE THREAD

**Issue by its-mrarsikk** [PathOfBuildingCommunity/PathOfBuilding#4470]
I wanna open a build from this pastebin: https://pastebin.com/gVzHR7m7. How to? i cant pres open

**Comment by Dullson** [comment]
The link seems fine to me and PoB loads it without a problem.
Can you provide more info? Maybe some screenshots demonstrating the issue?
![image](https://user-images.githubusercontent.com/5316261/174477951-4ada753e-e6ed-4f0a-8be9-21978c17890a.png)

**Comment by its-mrarsikk** [comment]
There isnt such button

**Comment by Nightblade** [comment]
>  i cant pres open

There is no "open" button.

Please make sure you are running the most recent version of PoB -> 2.18.1

Using the screenshot below a reference, please check you are doing the following:

* Highlight the pastebin link (don't click it)
* Press `ctrl+c` to copy the link
* Press `Import/Export Build` button **(1 below)**
* Click in text box **(2)**
* Press `ctrl+v` to paste the link.   If `https://pastebin.com/gVzHR7m7` doesn't appear, you've done something wrong
* Press the `Import` button **(3)**

![image](https://user-images.githubusercontent.com/23911/174792936-ca2d4d51-c57f-46bc-9416-ef745ec22e29.png)
