### ISSUE TITLE
Phantasmal Siphoning Trap bug

### ISSUE THREAD

**Issue by NEOKARTOXA** [PathOfBuildingCommunity/PathOfBuilding#4475]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I choose the skill Siphoning Trap, also the phantom quality of this skill. The % regeneration is indicated there, and the program simply counts 0.4 units (not even taking into account the number of rays).

### What is the actual behaviour/value?

![Скриншот 20-06-2022 144635](https://user-images.githubusercontent.com/92036737/174595354-68c1655a-0b95-4def-b6e3-7c6e178c10d2.jpg)
![Скриншот 20-06-2022 144720](https://user-images.githubusercontent.com/92036737/174595397-2f462143-4271-4c69-a6bc-b422aa138244.jpg)
![Скриншот 20-06-2022 144800](https://user-images.githubusercontent.com/92036737/174595425-9f980e46-6f4c-4d87-9b45-e0e65f3bb2ca.jpg)

### How to reproduce the issue

Shown above in the screenshots.

### Character build code

```shell
https://pobb.in/htZmPHSuoVkd
```

**Comment by QuickStick123** [comment]
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2887
