### ISSUE TITLE
Importing items can turn explicit mods into implicits

### ISSUE THREAD

**Issue by eakaye** [PathOfBuildingCommunity/PathOfBuilding#4480]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When importing e.g. a pair of boots with a (normal) implicit and a lab enchant, the implicits count should be set to 2.

### What is the actual behaviour/value?

The implicits count is set to 3, and the first explicit mod becomes an implicit.

### How to reproduce the issue

Import the character "PiscaTotems" under the account "ekaye" in the PC realm and look at the boots. Spell suppression is an implicit when it should be explicit.

### Character build code

```shell
n/a
```

**Comment by QuickStick123** [comment]
Unable to reproduce probably is resolved.
