### ISSUE TITLE
Caster Summon Skeletons not scaling to level of gem

### ISSUE THREAD

**Issue by STSsadoni** [PathOfBuildingCommunity/PathOfBuilding#4498]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The DPS of Summoned Skeleton Casters should scale on the level of the Summoned Skeleton gem.

### What is the actual behaviour/value?

The DPS of Summoned Skeleton Casters does not scale with the level of the Summoned Skeleton gem.

### How to reproduce the issue

1. Add Summon Skeletons to the build.
2. Switch main skill to Summon Skeletons
3. Change to Summoned Skeleton Caster

### Character build code

```shell
https://pastebin.com/PFeR7NsX
```

**Comment by LocalIdentity** [comment]
You're on the beta branch aren't you? Revert back to the normal branch for the time being, it'll be fixed on beta soon

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/2867b0a2ce52756d6c86cec60e886d1d94a05d04
