### ISSUE TITLE
Cruelty shouldn't apply to DoT from minions 

### ISSUE THREAD

**Issue by Seikah** [PathOfBuildingCommunity/PathOfBuilding#4499]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Cruelty Support shouldn't affect damage over time from minions. A buff specific for 'skills supported by Cruelty support' can't work for them. 

Support gems linked to minion skills copy their stats into the minion's base stats. A minion's individual skills are never directly 'supported by' gems; they just have the support gem's stats because the minion does. 

[Developer confirmation here](https://i.imgur.com/miTZbZj.png). 

### What is the actual behaviour/value?

Cruelty scales minion DoT.

### How to reproduce the issue

Add a minion that uses a physical attack, add Vulnerability to give it chance to bleed, add Cruelty to see bleed DPS go up. 

### Character build code

```shell
eNqtWlt32jgQfu7-Ch_eCxhjLj1k9xBCUs4JKYvTdndfehRbgDayRW05lP76HckmGGJgrG0eUsf-5vZpNBpJHfzxI-TWC40TJqKrml1v1iwa-SJg0fKq9vnx9n2v9sfvvw1mRK4-La5TxtWX3397N9DPFqcvlINczZIkXlL5ZafJ-Qaa1iSSKyqiKflXxHciuKo9iIjWrCcSBUzu_vI5SZIHEtKrmueDcM0iiU-jYLR_nwFDwiJP-M9U3sUiXWuzL4xupiIAzGQ6-zR_LBhlUdEo-PxuMONkS2NPEmkl8OuqNvQle6EABbv3LGQSNBKegrpOrXFCBNgiS_qxgG2ewnprSoNXmF23u512t-n2ei3HdU4JzWI6Xiyo9mwUMzlakcinl41VxU5TLtmaMxoXPHRPSTwKSfjNzLusO0MKBD1fmVxdc6AIpVehJ8uISYqGzwRLRFTJaxR4lHIO8wCHFeETi5AxTklERiLZc-f0TkHv2YIeQE8qHXs43BzSGodUbs5oDLNU4gSUs5UEcgse9QVUgio2qogU4jAzZiA59kwEDAx5cj-xW6cHnX4vAvsn8-2G_kCom0QSZ7QItF33tNUXIfWigJrA44-zV6Tbr_e6_X6_23Kdtn0yrtlqmzCf8Cn5wcI0hLr-SJ7p3mDnTA4sVzKCOnBK1Omerqe3LKYmciPBAyO5FRGJiaDKdAQZsNT5HxR2Evm46fM5imlC45fCCtk5KzCH5FeL7xOnSIm9iXwK7VOuecHUkka4MO4p9Vd30JrMiaS4krNP0fN0KiyKTgUsodNFClQgRwkekVPvnwNXpOcriQNESYxovNx6K0Z5RXSeQ9sRWaPaN_9DURo1GIfmUHlUFKlI2PiFJMX6aHfOR5PBcVlFoTcDgYBi28pZLP5VjSuvJjaMQ5HGyPHIwKgAdqX9hoTQ2sxpkPq4teS1_55CsoQwNXQjD_uMPc2nRK857FCwgYNazitJDKUk_vONCJa0kpHqEl66XkOBUNmClVNr2pwmrNCdvO8g0J9gRqImpFr88Ab2aLSB1yUdb-VIBB-LWpArBLOHo03cwjYFte2YiQ2oXKktfFINDR3Fvos46UdMo59btP4DOMrAOArSWOUo2saxBMrM5dOC7Nvb04KsAu2rh2336k6n3Wk77VbrlOzh6UGz3nPb3WZz9_vXSr3Z3vddt97rdFt2p9NsNtvn5Uo2-2-Qbzb6dr9f73SbttPtAQsnGSw9JLBhy1B3na7jtoFC55zs2yMDZGjlBwgVeTEIuOzAABnvYa_e7XbOAct7k1Lo-Z7kjcjZ9uwsGukTtl8aNPQxpXqahGsRS_1yRLifaMWTaJ1KK9JnjCFL_G9P6WKhjhNrYCjWZ6Dj29vx6HHyZZz7UhRJnhnn36I0fFJnaNm_-9bAo7rbsHzBOVknNLiqRYzXLAYPnpL0oL_yJQIN-7W8gFzGQgPtxwxK4GWomrYIV3U9uYxTR4oIGIwD4RRL0eN2TdW4JziW8kblMlYXFAQum_-YsHSVwZBOfbJF4F7TGoEdczpkXPWpGJ6mkOhZg4tBQ8MZs6dUojJK1x-EB2oPjAirWEZQmY-B5ZsNhPl8Z3UZmXdxmLSDVh85RDd0QSGZURNZF4fsSCcre7sSN9CzKLESqH13NEyut7Cq3CpCj9aZkEhINxreqwudR6G6IuJLGt9nFzwLwhNVFItqrmoyTuFlQBck5er9nynhTG5V9S28zVVob5OV2KiNRaZHze4ERuT-Pvsy5DJXoYzsrGbhqzj0DVDWhOm_dZT6GohFPk8DOonyljc3x8mTMl2zlurCaCTSSOZfaKSOkYJdDEeKlU5l9t0AHMmxd1w8Ed7aBaJg-bp06ErhS_5yThiM1z-KbjCVX5m1mrUDxfbOFS0_CXKxndSxPW3qe0bWRJcVTXcOnJFYasSShurrlEoSEEkaEwnENhS7Da0Gng7MfC-M4BFFr4r3ofoZofCk1kO1O8-9tkrcPuKhcZ5fNEtfUh6pM0Gm_C6nBEHCA92UKypjoizsQ-lfFVw-VUbwlptE9zrTjjUchpXP7rK4doJZEcr40hUmKyzq8TGm1CLZ5NEydj5l4Y_iVa7ysqmmWgJ1ZZuvQGpyRtBwwYPb6zlOzZKgrnCNbPfyG-JMPCN2HMBiGzwouZzqz_N7_fBuJeU6-dBobDab-prIlVjQH4zTui_CxhrUgJfvNb_vlaHGEH6ul0P9oxU1dpoG2VVzsoscotGBq3DVw4OANVF9Uy93f2gyvjC6sRIKjdjKk7GK8KcQ4d86elXmPlIip2SdJ4P6lpdIJy-Q0PDcMOAn1gvALisU8K_XzlYPc067evZoNnRpQrNLoq-UrKFY0LziZc1rBjwJ0qvJrvR5XOwa3Qxm2d6GrK3h0zZJCLcyfiwXpGSWg81d4peIHou1cGLnUddCyMTQobJYLjh1DVOhosgtpO6z5aBcapW55JjRiyOh9YvE2mZOdsysdczZNMmnCyPwkULnLasaKsmkjomdC-kHC8uLOg6rrtgxn0W2ib22WS7YZpnXvjw8GGKrqi1LL8PAUXXHNfDHoAY6l8wEWyvbdlUcvnKWjfLLNRFCTUnMQBjF6RrT2jIY947ZTHLM0tepnmVt87JvkNO2MfkOJiHaGJCB2_-j-UGOpPkodAyy0nwY_ke6YEuykkXOGjzUgLk5i5a4TqByoThJr2G5wI-nSTgOgifbfBjaxmy5JtFg5ot5kl9waRimvGRtGzTyPaTeC-tNqL5SEdGCLQExaBz_V_H_ACFdlIc=
```

**Comment by Lothrik** [comment]
It is possible to exclude minions from the Cruelty buff:
![image](https://user-images.githubusercontent.com/18443616/176320999-048e6f5e-a6c0-4b03-b3d5-f8730d8e972c.png)
.. by adding a check for ``actor.minionData`` at: https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/ebc2564baabd2ac8cdb4da1f45d0ee6bf8f10744/src/Modules/CalcPerform.lua#L886

However I'm hesitant to create a PR for thism as what viperesque said makes me think the entire support gem does nothing for minions. Even if that isn't the case it sounds like it will be very soon, probably 3.19.0.

For reference, disabling the Cruelty Support gem entirely for minions just involves adding ``ignoreMinionTypes = true,`` to ``skills["SupportCruelty"]`` in ``sup_str.lua`` / ``sup_str.txt``.
