### ISSUE TITLE
Summon Arbarist's Skill Not Supported (Vorana's March)

### ISSUE THREAD

**Issue by KatelynAzurefire** [PathOfBuildingCommunity/PathOfBuilding#4500]
The '[Summon Arbalists](https://www.poewiki.net/wiki/Summon_Arbalists)' skill granted by the '[Vorana's March](https://www.poewiki.net/wiki/Vorana%27s_March)' boots is not coded in as of version 2.18.1. The different modifiers that Vorana's March can have aren't coded in either. They're all listed on the wiki page for the boots liked previously.

**Comment by LocalIdentity** [comment]
I’ll look into adding it. Heard the minions were terrible though and not worth building around

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4613
