### ISSUE TITLE
when scrolling, the bottom border goes beyond the window

### ISSUE THREAD

**Issue by Ostalaro** [PathOfBuildingCommunity/PathOfBuilding#4516]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

when scrolling, the bottom border dont goes beyond the window

### What is the actual behaviour/value?

when scrolling, the bottom border goes beyond the window

### How to reproduce the issue

notes tab

### Character build code

```shell
https://pastebin.com/yf5XJrNU
https://pastebin.com/3y7GLPgT
```

### Screenshots

![image](https://user-images.githubusercontent.com/82410380/177030657-dc2e1f45-3401-470b-8555-77a5a05df31f.png)
![image](https://user-images.githubusercontent.com/82410380/177030668-8f4a8a56-7c99-41ec-ae26-249c8c33884c.png)

**Comment by Wires77** [comment]
Fixed in the next release

https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/aa092d6693548bd2bc9fa2601717f9b892b45282
