### ISSUE TITLE
Adding life or increasing Max Hit causes EHP to decrease.

### ISSUE THREAD

**Issue by baranelitez** [PathOfBuildingCommunity/PathOfBuilding#4534]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

If all Max Hit values and Max Life goes up, the EHP should go up as well (in increments).

### What is the actual behaviour/value?

Adding extra life using any means (custom modifiers with `+1000 to life` in this case) causes all the Max Hit values to increase, but it causes the EHP to decrease.

### How to reproduce the issue

Go to Custom Modifiers under Configuration tab. Remove `+1000 to life` part and observe how the Effective Hit Pool goes up.

Sent the character to someone to confirm if he's seeing the same problem. He said it works as expected until he realized he's on 2.17. Updating to 2.18.1, he's having the same problem as well.

### Character build code

```shell
https://pastebin.com/0YbZyFkp
```

### Screenshots

less life more ehp:
![lesslifemoreehp](https://user-images.githubusercontent.com/22811291/177912408-7bc04048-33ec-45e8-84f5-57eddc895f66.png)

more life less ehp:
![morelifelessehp](https://user-images.githubusercontent.com/22811291/177912420-1ffe5395-b411-4aa3-b2b7-ef40225fac3b.png)

**Comment by Regisle** [comment]
This is an issue with the speedup function and gain on block, there were issues with es on block before so some of it was changed and thats what caused this issue, Ill look into fixing it at some point

**Comment by QuickStick123** [comment]
This seems to be resolved in dev
![image](https://user-images.githubusercontent.com/31533893/205883034-6fd48af9-4f19-4e80-baa2-cb930dce1a74.png)
![image](https://user-images.githubusercontent.com/31533893/205883073-40ff5ec2-43e1-4430-9b4c-8655643b64c3.png)
