### ISSUE TITLE
Lethal Pride manually set modifier save issue with unallocated passives

### ISSUE THREAD

**Issue by tuvshing** [PathOfBuildingCommunity/PathOfBuilding#4539]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Save the manually set modifier of an unallocated notable within Lethal Pride's radius.

### What is the actual behaviour/value?

Manually set modifier of an unallocated notable within Lethal Pride's radius gets reset after restarting PoB.

### How to reproduce the issue

1. Set a modifier on an unallocated notable within Lethal Pride's radius
2. Save and Restart

### Character build code

```shell
https://pastebin.com/am9ZS9CN
```

**Comment by QuickStick123** [comment]
The ability to manual set mods is getting removed and replaced with a proper timeless jewel implementation and search functionality very soon.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4527
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4529
![image](https://user-images.githubusercontent.com/31533893/178088029-68fc1a9f-de09-4d30-b804-112a9a6ff30f.png)
So this will be redundant soon.

**Comment by tuvshing** [comment]
Closed due to the upcoming timeless jewel implementation.
