### ISSUE TITLE
Forbidden Rite All Primary Projectiles Damage

### ISSUE THREAD

**Issue by TheHonzai** [PathOfBuildingCommunity/PathOfBuilding#4544]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Swapping from 1 Projectile to All Primary Projectiles should not change damage output with only 1 projectile.

### What is the actual behaviour/value?

Swapping from 1 Projectile to All Primary Projectiles  doubles the damage, even though I only have 1 projectile in my PoB

### How to reproduce the issue

Create a new character
Under Main Skill dropdown:
    Change 1 Projectile to All Primary Projectiles
DPS doubles

### Character build code

```shell
https://pobb.in/gLvVJi23tfB7
```

**Comment by LocalIdentity** [comment]
FR will hit with 2 projectiles as a base with no added projectiles in a build. From the wiki 
“By default, Forbidden Rite fires a projectile near your cursor, as well as additional projectiles for each enemy within range. This means that on single target, two projectiles will hit the enemy.”
https://www.poewiki.net/wiki/Forbidden_Rite

**Comment by TheHonzai** [comment]
I completely missed that in my research. Thank you!
