### ISSUE TITLE
Set limit on points required for Node Power calculation (Bonus, it will speed up calculations!)

### ISSUE THREAD

**Issue by Nitrak** [PathOfBuildingCommunity/PathOfBuilding#4553]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

When you select "Show Node Power", it requires calculating EVERY passive on the tree which for slower CPU's can take an excessive amount of time (and even on fast CPU's some time).

### Describe the solution you'd like

If there were an option next to "Show Node Power" to limit searches to "X" away from your tree it would only calculate a small subset of the tree compared to the entire skill tree.

Often when people use the Show Node Power it is to see what is the best nodes I can take, but often realistically it's only the nodes close to the tree that are important (build creation and anoints aside). Most of the time it is pretty irrelevant what a +15 Points node does since it is too far away to reach for any actual benefit (when in end-game).

**Comment by Peechey** [comment]
Fixed by #6598 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/3e592c8b-1574-4a72-9bf4-5316c8909633)
