### ISSUE TITLE
Path of Building crashes on launch!

### ISSUE THREAD

**Issue by bledarkabashaj** [PathOfBuildingCommunity/PathOfBuilding#4560]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Path of building launches

### What is the actual behaviour/value?

Path of building doesn't launch with the newest update. The script shows this error:
apppath\Community\Launch.lua':
not enough memory
stack traceback:
	[C]: in function 'perform'
	UpdateCheck.lua:35: in function 'downloadFileText'
	UpdateCheck.lua:219: in main chunk
	[C]: in function 'LoadModule'
	...ar\AppData\Roaming\Path of Building Community\Launch.lua:33: in function <...ar\AppData\Roaming\Path of Building Community\Launch.lua:17

P.S. Memory should absolutely not be a problem as there is plenty!

### How to reproduce the issue

Launch latest release of PoB or an older one, and in the first case, the script will show you that error, and in the latter case, PoB just closes without actually performing an update!

### Character build code

```shell
None is relevant!
```

**Comment by Wires77** [comment]
We're looking at fixing this right now.  As a workaround, you can download GloriousVanity.zip from here https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/dev/src/Data/TimelessJewelData (direct link: https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Data/TimelessJewelData/GloriousVanity.zip )

Copy that file into the directory where you have installed PoB, under `Data/TimelessJewelData`

**Comment by Dreamiee** [comment]
I am having same issue. Downloading GloriousVanity.zip doesn't fix the issue however it does reveal that it is an invalid zip file, possibly the issue?

**Comment by Wires77** [comment]
No, it's not a real zip file, just named that way.  You'll want to copy the actual .zip file into the directory above

**Comment by lyallp** [comment]
I note that both the installer version and portable version crash at the same update #30 - timeless jewel.
Deleted and uninstalled.
Deleted and tried portable version (does not require installation)
From my uneducated perspective, it looks like the timeless jewel update is invalid.

**Comment by Nmanh1172** [comment]
> No, it's not a real zip file, just named that way. You'll want to copy the actual .zip file into the directory above

i dont have  TimelessJewelData

**Comment by melewda** [comment]
For me worked to install 2.16 and update from it

**Comment by QuickStick123** [comment]
Should be fixed. If you added anything to timelessdata you might need to delete it to work. GV support won't work atm.

**Comment by Hocknose** [comment]
> For me worked to install 2.16 and update from it

This worked for me also

**Comment by DeckStarg** [comment]
> We're looking at fixing this right now. As a workaround, you can download GloriousVanity.zip from here https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/dev/src/Data/TimelessJewelData (direct link: https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Data/TimelessJewelData/GloriousVanity.zip )
> 
> Copy that file into the directory where you have installed PoB, under `Data/TimelessJewelData`

This did not work for me sadly

**Comment by DeckStarg** [comment]
> For me worked to install 2.16 and update from it

This also did not work for me

**Comment by wasche** [comment]
Nothing above worked for me either. I ended up making a backup of my build file and deleting any Item entries referencing the GV jewels for now.

**Comment by straylightd** [comment]
> For me worked to install 2.16 and update from it



> For me worked to install 2.16 and update from it

how can i get 2.16?

**Comment by QuickStick123** [comment]
This should be fixed if you have an issue with the current 2.19.1 please open a new issue.

**Comment by QuickStick123** [comment]
You can access past releases at https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases.

**Comment by straylightd** [comment]
> d update from it



> For me worked to install 2.16 and update from it

this worked for me as well
