### ISSUE TITLE
Script error on update/install

### ISSUE THREAD

**Issue by Hocknose** [PathOfBuildingCommunity/PathOfBuilding#4561]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

PoB should update/install without error

### What is the actual behaviour/value?

Program gets to 30/65 downloads and crashes every time. Have tried this with a an update to existing PoB and a new installation

### Character build code

```shell
n/a
```

### Screenshots

![image](https://user-images.githubusercontent.com/109137112/178440820-589b4b6d-8885-40cd-a42c-3c062c947aa0.png)

**Comment by QuickStick123** [comment]
Duplicate https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4560
