### ISSUE TITLE
Link passive trees, skill sets and item sets

### ISSUE THREAD

**Issue by josec87** [PathOfBuildingCommunity/PathOfBuilding#4569]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Passive trees and the skills sets added in 2.19.0 aren't connected. Item sets aren't connected either.

### Describe the solution you'd like

I'd like the possibility to link passive trees with skill sets. This would be useful for:

* Having multiple leveling trees tied to different leveling skill sets.
* Reservation. For example, if a passive tree invests in armor, it would be logical to link it to a skill set with determination. If I have an alternative passive tree with a focus on energy shield, maybe I would like to have it linked to a skill set that swaps determination for discipline. Or maybe another tree doesn't invest at all in reservation efficiency and I need to have it linked to a skill set with fewer auras. Not having the skill sets linked to the passive trees makes the tree comparison feature useless in this scenario.

The same is applicable for item sets.

**Comment by Smeagol001** [comment]
yeah thats basically what i asked a year ago
