### ISSUE TITLE
glorious vanity error after update

### ISSUE THREAD

**Issue by bigsarge99** [PathOfBuildingCommunity/PathOfBuilding#4570]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

running  winter orb build just opening the pob

### What is the actual behaviour/value?

running  winter orb build and it wont load the pob for it  first line glorious vanity is making error.

### Character build code

```shell
i cant get the code
```

### Screenshots

![Screenshot 2022-07-12 102059](https://user-images.githubusercontent.com/68719552/178526125-654af0b4-119c-494f-a9b3-b8d19eee29d7.png)

**Comment by DeckStarg** [comment]
Getting exactly the same message.  All other builds open fine, ones that don't us a GV.

**Comment by mktums** [comment]
Can confirm, exactly same error with GV equipped.

**Comment by bigsarge99** [comment]
but glorious vanity is still in the game correct? if it is hope they fix this cause i cant open some of my builds.

**Comment by zao** [comment]
We're working on a fix but in the meantime you can follow the instructions in this related comment to manually download a file that couldn't be distributed with the updater: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4560#issuecomment-1181438673
PoB is normally installed in `%APPDATA%\Path of Building Community`.

**Comment by QuickStick123** [comment]
Fixed in most recent release.
