### ISSUE TITLE
Base damage over time of many active skills is almost exactly 6% of what it should be (ED, Bane, Soulrend, Fire Trap, possibly more)

### ISSUE THREAD

**Issue by xPhool** [PathOfBuildingCommunity/PathOfBuilding#4573]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

![image](https://user-images.githubusercontent.com/23579145/178542647-02947049-ca82-4a25-99e3-371df8648f7c.png)

### What is the actual behaviour/value?

![image](https://user-images.githubusercontent.com/23579145/178542815-24054471-3aa1-46dc-aa59-1af583b7c89d.png)

### Character build code

```shell
https://pastebin.com/FvmpjgQ7
```

**Comment by xPhool** [comment]
Doing some further testing, this seems to be consistant for all active skill gems with a base damage over time, including Brands and Righteous Fire.

Notably, Decay Support is not affected.

**Comment by umn-anon** [comment]
Exsanguinate and corrupting fever are also affected, supporting xPhool's 2nd comment

**Comment by QuickStick123** [comment]
This will be fixed very soon a patch has already been deployed to dev which be merged to master very soon.

**Comment by QuickStick123** [comment]
Fixed in most recent release.
