### ISSUE TITLE
Getting Error trying to load a build with Glorious Vanity

### ISSUE THREAD

**Issue by Gafionpriest** [PathOfBuildingCommunity/PathOfBuilding#4597]
When trying to import a build with Glorious Vanity im getting this error message:
![pob error 1](https://user-images.githubusercontent.com/73945256/179128209-895c97e6-95b3-4969-bda4-003e4987b076.JPG)

**Comment by Gafionpriest** [comment]
the import worked before i updated POB to the latest version.

**Comment by LocalIdentity** [comment]
You most likely have an old tree in the build with a Glorius Vanity socketed in it. That bug is fixed in this PR #4587. I'll make an update with the fix included in the next couple hours
