### ISSUE TITLE
Cant start new build, after clicking NEW getting error

### ISSUE THREAD

**Issue by RaincoatSpy** [PathOfBuildingCommunity/PathOfBuilding#4605]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

PoB should start new build on clicking NEW button.

### What is the actual behaviour/value?

Can't start new build, PoB shows error.

Can only open and use saved trees.

### How to reproduce the issue

1. Open PoB
2. Click NEW
3. Get error.

### Character build code

```shell
Cant provide, error on creating new build
```

### Screenshots

![ddUX6AI](https://user-images.githubusercontent.com/109439258/179371849-5516bd17-b784-4479-9d90-d3bc911e486d.png)

**Comment by QuickStick123** [comment]
Can you shows the version number in the bottom left hand corner you might just need to redownload the latest version https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4109#issuecomment-1177031170.

**Comment by RaincoatSpy** [comment]
![yKSABAL](https://user-images.githubusercontent.com/109439258/179379960-95190b81-039e-4a64-8f22-7f55f7b4bc6a.png)
Happened after last update

**Comment by QuickStick123** [comment]
Make sure you set character level to between 1 and 100 in options otherwise it will crash.
![image](https://user-images.githubusercontent.com/31533893/179380375-02af5ca2-4bfc-496c-ba8f-f204aa1bce05.png)

**Comment by RaincoatSpy** [comment]
Worked, Wouldnt thought about that. Thanks. Should that option be 1 by default or update changed something?

**Comment by QuickStick123** [comment]
It should be 1 by default but we should ensure it is a valid value their will probably be a proper fix out soon for this.
