### ISSUE TITLE
Concentrated Effect Support increases the damage of the final hit of Glacial Cascade but not its Ignite DPS 

### ISSUE THREAD

**Issue by spawnie-no-oni** [PathOfBuildingCommunity/PathOfBuilding#4616]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I am trying to calculate the ignite damage of a Glacial Cascade final hit that's fully converted to Fire Damage.

When adding a Concentrated Effect Support Gem to my Glacial Cascade, I expect its Average hit value and it's Ignite Hit value to go up.

### What is the actual behaviour/value?

The Average hit value is going up but not the Ignite DPS value.

### How to reproduce the issue

1. Select Glacial Cascade as your main skill.
2. Convert the damage to fire by linking it with a level 20 Cold to Fire support and equipping a Pyre ring.
3.  Link the Glacial Cascade gem with a Concentrated Effect Suppost.
4. Notice that the Ignite DPS is not going up, despite the Average Hit value going up. 

### Character build code

```shell
https://pastebin.com/keZwghZV
```

### Screenshots

![image](https://user-images.githubusercontent.com/58695361/179705178-422fa149-12f4-42bf-9751-c3a2547dfd8d.png)
![image](https://user-images.githubusercontent.com/58695361/179706193-4d9a8809-31e4-4e5e-99c0-2c23b7ba8905.png)

The "Source Cold" Damage of the Ignite breakdown it not modified by the Concentrated Effect link.

**Comment by Lothrik** [comment]
This is not a bug. Ignite is never classified as area damage no matter how you apply it.
