### ISSUE TITLE
Awakened Gems defaulting to Gem Level 6

### ISSUE THREAD

**Issue by cztbg0** [PathOfBuildingCommunity/PathOfBuilding#4630]
Currently, awakened gems always default to 6 (i.e. corrupted +1 level) if the default gem level is higher than 5, while the default behavior for gem level is 20 even when selecting "Awakened" gems in the drop down menu.

I think adding a separate default gem level field specifically for awakened gems and defaulting it to 5 would correct the discrepancy in behavior between regular and awakened gems.
![image](https://user-images.githubusercontent.com/96273362/180211375-3c3cb212-0c71-4ebf-876f-5fca70626c51.png)
![image](https://user-images.githubusercontent.com/96273362/180211283-e5f06cd9-814c-4cb7-bc7a-92643ab409d4.png)
![image](https://user-images.githubusercontent.com/96273362/180211485-0a607e15-22e4-43eb-8af6-9eea6c9e5fcd.png)

**Comment by Lothrik** [comment]
Unfortunately there are various gems with different maximum levels (Blood and Sand, Empower, etc); it wouldn't just be an "Awakened vs non-Awakened" thing here.

It might make more sense to have a dropdown list or something for options like: (1, natural maximum, corrupted maximum) rather than specifying an absolute value for the default gem level.

**Comment by cztbg0** [comment]
I mentioned a separate awakened gem level because there already exists a separate classification for awakened vs. non-awakened supports anyway through the dropdown menu second to last in Gem Options, and generally speaking, it's far more likely that someone might want to set awakened gem levels separately to have those gems sorted correctly by DPS at the appropriate awakened gem level (i.e. comparing and sorting dps between level 20 regular supports vs level 1 awakened gems).

That situation isn't likely to be relevant for gems like Blood and Sand, but you're right that it applies to Empower/Enhance/Enlighten. Considering the unique way that levels affect those gems, perhaps allowing players to have those 3 gems to be listed separately at level 3, 4 and 5 (for the awakened version) would be appropriate (similar to how alt qual gems can be shown separately).

**Comment by Nostrademous** [comment]
@Lothrik we actually know the natural maximum of each gem. It's in the `src/Data/Gems.lua` file and for some reason called `defaultLevel` for each gem.
