### ISSUE TITLE
Same Mastery Node effect allocation

### ISSUE THREAD

**Issue by Sejf** [PathOfBuildingCommunity/PathOfBuilding#4639]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Being able to allocate a node mastery with the same name, with the same node effect.

### What is the actual behaviour/value?

If you allocate a mastery node like "Regenerate X% energy shield per second" from the "Elemental Shield Mastery" mastery, you can't allocate the same node effect from another "Elemental Shield Mastery" mastery with the same name.
This applies to all mastery nodes.

### How to reproduce the issue

1. Allocate a mastery node effect.
2. Search a mastery node with the same name in the passive tree.
3. Try to allocate the same mastery node effect.

### Character build code

```shell
The first two "Energy Shield Mastery" to the left with Discipline mana reservation https://pastebin.com/mDKXkWRi
```

**Comment by PJacek** [comment]
This is working as intended: https://www.poewiki.net/wiki/Passive_Mastery 
> The set of mastery passives offered are shared among their respective cluster categories, so for example a player can allocate a Fire Mastery from any of several Fire-related clusters, but **the same mastery cannot be allocated twice**. (emphasis mine)
