### ISSUE TITLE
TOTALY WRONG full dps calc

### ISSUE THREAD

**Issue by poewka** [PathOfBuildingCommunity/PathOfBuilding#4642]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

After last update dps calc become wrong

### What is the actual behaviour/value?

2.17.1 ver and after 2.19.2
![image](https://user-images.githubusercontent.com/109908253/180649952-c676d646-982e-45a1-879a-33bbf6e0466c.png)
![image](https://user-images.githubusercontent.com/109908253/180649964-94789e48-5065-41ca-90c4-4c43bcf3e0be.png)
It's happens in all builds i have saved.

### Character build code

```shell
https://pastebin.com/7NW5ZdfL
```

**Comment by poewka** [comment]
I asked my friends, they have same issue

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/180650081-83ad396f-cd69-4980-8860-3db99efe7ba1.png)
![image](https://user-images.githubusercontent.com/31533893/180650093-608c3044-2bdd-453a-89d8-5c2109715c28.png)
You had it on uber boss.

**Comment by poewka** [comment]
really, thanks
