### ISSUE TITLE
Red

### ISSUE THREAD

**Issue by EbbaAkerlund** [PathOfBuildingCommunity/PathOfBuilding#4663]
Every node is red when doing offence comb dam.

**Comment by QuickStick123** [comment]
Please fill out the issue form or atleast provide screenshots 
![image](https://user-images.githubusercontent.com/31533893/181677194-1649d6f9-8456-4ea3-aa91-1ea31bdfa923.png)

**Comment by LocalIdentity** [comment]
Properly fill out a bug report if you want something to be fixed
