### ISSUE TITLE
Question: Unallocable nodes, why?

### ISSUE THREAD

**Issue by its-mrarsikk** [PathOfBuildingCommunity/PathOfBuilding#4665]
When in passive skill tree, i see unallocable nodes, that even doesn't exist in the game. There is the examples:

![image](https://user-images.githubusercontent.com/94739102/181866389-e594d28f-ea8c-449a-a349-6e9b6260dd5b.png)
![image](https://user-images.githubusercontent.com/94739102/181866409-7d162ac6-33d2-4845-889c-2c2b07164f70.png)

![image](https://user-images.githubusercontent.com/94739102/181866436-6f66d8bc-729d-4604-88c1-2bd66c250a2c.png)
![image](https://user-images.githubusercontent.com/94739102/181866457-c8a19198-9ad1-4574-8bc6-573dbd7f79ca.png)

Why is them there and... is it made for something except to make me ask?

**Comment by Wires77** [comment]
These nodes are "anoint-only" nodes.  You can use the oil combination at the top of the tooltip to anoint them on your amulet, but otherwise cannot be pathed to.
