### ISSUE TITLE
add a way when copy pasting jewelry into PoB to add quality to those items

### ISSUE THREAD

**Issue by JeremyT313** [PathOfBuildingCommunity/PathOfBuilding#4675]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

not being able to add qaulity to jewelry that is copy pasted makes it difficult to see what catalysts should be being used

### Describe the solution you'd like

when copy then pasting jewelry into PoB id like to see a catalyst option to choose from then a slider to select the quality level so i can see what my items would be after using certain catalysts

**Comment by QuickStick123** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4662.
