### ISSUE TITLE
Glancing Blows does not change "Effective Hit Pool" when random things are changed in PoB 

### ISSUE THREAD

**Issue by bugreporter13** [PathOfBuildingCommunity/PathOfBuilding#4676]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Toggling Glancing Blows (GB) on and off should change the Effective Hit Pool (EHP).

### What is the actual behaviour/value?
Please see the video at the bottom- it shows the issue in action.

When I made a build, at some point, arbitrarily, toggling GB on or off does not change the calculated EHP. 
The way this was circumvented was by deleting a particular socket group: Enfeeble + Poacher's Mark
Disabling the socket group sometimes does not fix this issue. 

There are other ways this bug triggered:
Temp Chains + Blasphemy  + Despair socket group added
Level your character to 90

(I presume there are more ways)

### How to reproduce the issue

I do not know if all are required to reproduce bug. 
1) select witch, occultist. 
2) select Maledicton, profane bloom, void beacon, vile bastion 
3) add rare shield (with block and spell block)
4) path and get glancing blows
5) level to 90 [VARIABLE- many different things cause the bug- I found 3, listed above]
Bug randomly occurs at this point. 

### Character build code

```shell
https://pastebin.com/QbhcyX9u

^ With this you can test how disabling Enfeeble, Poacher's Mark results in the ability to correctly have GB (on or off) change the EHP. Enabled socket group results in the bug. 


https://pastebin.com/LbKjqvhm
^ level to 90 creates the bug
```

### Screenshots

https://gfycat.com/uniqueessentialargentinehornedfrog

**Comment by QuickStick123** [comment]
I think the issue here is the eHP calculation is based on integer number of hits before death so it has strong breakpoints when the number of hits are very low e.g. 2-3 hits. This means large changes are needed in mitigation to cause it to change.

**Comment by bugreporter13** [comment]
> I think the issue here is the eHP calculation is based on integer number of hits before death so it has strong breakpoints when the number of hits are very low e.g. 2-3 hits. This means large changes are needed in mitigation to cause it to change.

Yea actually this might be it. Thanks you!
