### ISSUE TITLE
Error In "OnFrame" with equipped "Atziri's Rule, Judgement Staff"

### ISSUE THREAD

**Issue by mrzhnex** [PathOfBuildingCommunity/PathOfBuilding#4679]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

At least, not crash

### What is the actual behaviour/value?

When i move my mouse cursor into:
1) items from "new item search tab"
2) Equipped weapon - "Atziri's Rule, Judgement Staff"
3) New item in "craft item" menu
an error pop up.
I notice that when i move cursor at "non weapon" item - error doesn't work and app working like it suppose to (showing item's stats etc).
I came to conclusion, that problem is "Atziri's Rule, Judgement Staff" and how it works/adds new spells.

### How to reproduce the issue

1) Equip "Atziri's Rule, Judgement Staff"
2) Select in "Main Skill" - "Storm of Judgement"
3) Move to "Items" tab
4) Move mouse cursor into "weapon" items

### Character build code

```shell
https://pastebin.com/WDPbqjqs
```

### Screenshots

![test](https://user-images.githubusercontent.com/46461216/182777930-0958ff6c-9e92-4c71-8f8f-c3258a5e404a.png)
![test2](https://user-images.githubusercontent.com/46461216/182778354-7a1cdad1-f528-4742-920d-5963793cc414.PNG)

**Comment by QuickStick123** [comment]
This seems to be related to having unleash socketed in the staff a minion skill present, storm of judgement selected in gem panel and hovering over the staff.
https://pobb.in/gfyrSsKBRSM_

**Comment by Paliak** [comment]
The skills granted by the staff seem to disappear after being moused over. Possibly something to do with the env overrrides in `calcs.initEnv(build, mode, override, specEnv)`. Possibly related to  #4631 .

**Comment by Paliak** [comment]
Seems to be caused by the way triggered skill are handled. #4599 _Should_ fix it.

**Comment by QuickStick123** [comment]
This is fixed afaik.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/92d54761-2ac9-44c1-a020-7a917e0106f9)
