### ISSUE TITLE
Shattering steel more dmg with ailments per shard consumed missing

### ISSUE THREAD

**Issue by UMTTEPATOP** [PathOfBuildingCommunity/PathOfBuilding#4680]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

"Projectiles deal up to 100% more Damage with Hits and Ailments per Steel Shard consumed at the start of their movement, lowering this bonus as they travel farther", but in PoB description there is only "hit" part, which for example, doesnt affect bleed (it should and it does in game).

### What is the actual behaviour/value?

Steel shards consumed + relativity to distance of projectiles traveled affects only hits (total dps and impale dps).

### How to reproduce the issue

1. Select shattering steel.
2. Use any axe or sword (jack, the axe - best option. Otherwise take any form of chance to bleed)
3. Put "1" in "Projectile travel distance" (for effective DPS)
4. Put "x" in "Steel Shards consumed" ( Skill options)
5. See that bleed dps doesnt change, which should, considering description of shattering steel in game, and both wiki's.

### Character build code

```shell
https://pastebin.com/LbgPqLGL
```

**Comment by deathbeam** [comment]
the ailment part was removed from shattering steel in 3.16

**Comment by UMTTEPATOP** [comment]
> the ailment part was removed from shattering steel in 3.16

My bad.
