### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by TranterS** [PathOfBuildingCommunity/PathOfBuilding#4692]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Under Bandit quest - Kill Oak - Increased physical damage. Increase is spelt icreased

### What is the actual behaviour/value?

Under Bandit quest - Kill Oak - Increased physical damage. Increase is spelt icreased

### How to reproduce the issue

Under Bandit quest - Kill Oak - Increased physical damage. Increase is spelt icreased

### Character build code

```shell
Under Bandit quest - Kill Oak - Increased physical damage. Increase is spelt icreased
```

### Screenshots

![image](https://user-images.githubusercontent.com/46983124/183285009-592aa711-5c64-4fdd-9991-9186705ef911.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4668

**Comment by QuickStick123** [comment]
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4695

**Comment by TranterS** [comment]
well done
