### ISSUE TITLE
POB.exe deletion

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [PathOfBuildingCommunity/PathOfBuilding#4725]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

POB shouldn't crash and it's executable file shouldn't get deleted.

### What is the actual behaviour/value?

POB works fine for a couple of weeks after that it crash randomly and get its .exe file constantly deleted. Once it happens I cannot re-install nor use the .zip version. Those also got their POBC.exe delete automatically.

### Character build code

```shell
I can't open POB anymore.
```

**Comment by QuickStick123** [comment]
Check if your anti virus software is blocking pob. That would be my first guess.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
Thanks. I will try that and give some feedback a bit later.

**Comment by Nightblade** [comment]
Quick way to check Windows Defender:  In PowerShell type `Get-MpThreat`.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
The issues was indeed the antivirus. Thanks for your help.
