### ISSUE TITLE
perfil privado

### ISSUE THREAD

**Issue by Talir-1** [PathOfBuildingCommunity/PathOfBuilding#4738]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

buenas tardes tengo poco jugando path of exile y veo que path of building es una herramienta fundamenta. estoy teniendo problemas con mi inicio de sesión me aparece mi perfil privado cuando ya deshabilite en la pagina de path of exile la casilla de perfil privado
![161141207-70081e2b-3328-4e2b-a95a-395372ef9cd2](https://user-images.githubusercontent.com/110950484/184091229-4a1d17cc-bcd4-4490-a924-23085db85875.png)
.

### What is the actual behaviour/value?

e incluso ya intente iniciar sesión con mi POESESSID y me sigue apareciendo lo mismo perfil privado para esto quiero agregar QUE SOY JUGADOR DE XBOX
![Sin título](https://user-images.githubusercontent.com/110950484/184091630-7c2d393c-91e3-4949-9daf-e4e89b76983b.png)
.

### How to reproduce the issue

ojala puedan ayudarme para que pueda aparecer mi personaje un saludo a todos y un gran di
![161143284-c16e9074-9922-4b61-b5a4-f838101bb5f7](https://user-images.githubusercontent.com/110950484/184091806-c668bcc4-ed94-4463-b89b-324fd14b336c.png)
a

### Character build code

```shell
Gamertag: Talir Rilat
plataforma: Xbox
```

### Screenshots

![161143284-c16e9074-9922-4b61-b5a4-f838101bb5f7](https://user-images.githubusercontent.com/110950484/184092062-2b3ef4f4-8f29-4af2-9a93-238da0cf6961.png)

**Comment by QuickStick123** [comment]
See https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4314 also please post in english.

**Comment by Nightblade** [comment]
I don't think `Talir Rilat` is a valid account name?

¿No creo que `Talir Rilat` sea un nombre de cuenta válido?
(via google translate)

**Comment by Nightblade** [comment]
Please use `Wmeizon` as your account name.

Utilice `Wmeizon` como su nombre de cuenta.
(google translate)

**Comment by Nightblade** [comment]
Resolved in #4743 good to close.
