### ISSUE TITLE
Remove Pinnacle boss penetration

### ISSUE THREAD

**Issue by blvcksvn** [PathOfBuildingCommunity/PathOfBuilding#4741]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Only specific bosses using specific skills penetrate resistances and creates an inaccurate picture of the effectiveness of resistances on most other bosses. Penetration should only be added automatically into Boss Skill Presets. Guardians do not penetrate at all, nor do 5 of the 7 pinnacle bosses. This also creates issues when attempting to build around damage shift (e.g. Cold taken as Fire) due to the implementation of Penetration as generic pen, rather than element-specific pen. Damage shift intentionally bypasses the element-specific pen. There was also no rationale provided for this change in the update notes

### Describe the solution you'd like

Please remove penetration values from boss enemy stats in config.

### Describe alternatives you've considered

See above.

**Comment by Regisle** [comment]
Can you rename issue to "remove Pinnacle boss penetration", as I am fine with requesting that the penetration should be removed, but those bosses have had penetration since we supported enemies having penetration back in #2390

**Comment by QuickStick123** [comment]
Effectively done in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5612 as it is now 3%
