### ISSUE TITLE
Boss Skill preset does not properly apply after saving a profile with it having been setup with the autofill prior

### ISSUE THREAD

**Issue by Nchi** [PathOfBuildingCommunity/PathOfBuilding#4742]
Easy enough to reproduce, setup any pob, set boss skill preset to any of the presets besides none obviously, save the file and close and open it and the numbers (for damage, the attack rate stays oddly) are no longer grey filled and the panel on the left reflects differing information than prior to reloading.

**Comment by SaloEater** [comment]
Looks like this bug is fixed within the _dev_ branch already and you have now to wait for the new release.

**Comment by QuickStick123** [comment]
Closing as it is resolved.
