### ISSUE TITLE
xbox private profile

### ISSUE THREAD

**Issue by Talir-1** [PathOfBuildingCommunity/PathOfBuilding#4743]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Good afternoon, I haven't been playing Path of Exile for a long time and I see that Path of Building is a fundamental tool. I am having problems with my login, my private profile appears when I already disable the private profile box on the path of exile page
![161141207-70081e2b-3328-4e2b-a95a-395372ef9cd2](https://user-images.githubusercontent.com/110950484/184238904-f5df59de-ada5-4378-9f54-9814e8b8ac81.png)
.

### What is the actual behaviour/value?

try to log in with my POESESSID and the same private profile keeps appearing for this I want to add THAT I AM AN XBOX PLAYER
![Sin título](https://user-images.githubusercontent.com/110950484/184239072-b6c99633-ac63-4585-bfe2-96c9ba7e6123.png)
.

### How to reproduce the issue

I hope you can help me so that my character can appear greetings to all and have a great da
![161143284-c16e9074-9922-4b61-b5a4-f838101bb5f7](https://user-images.githubusercontent.com/110950484/184239195-a9fbca57-c215-4239-af84-4f21a53ff6e1.png)
y

### Character build code

```shell
I hope you can help me so that my character can appear greetings to all and have a great day
```

### Screenshots

![161143284-c16e9074-9922-4b61-b5a4-f838101bb5f7](https://user-images.githubusercontent.com/110950484/184239225-1f3aa3ef-5e5e-43da-aa3a-c2d577b1c4f6.png)

**Comment by Wires77** [comment]
When I navigate to https://www.pathofexile.com/character-window/get-characters?accountName=Rogganz8&realm=xbox in my browser, I can't access your account.  Can you access it when logged out?

**Comment by Talir-1** [comment]
If I can enter my account, "The profile is private" keeps appearing when it is not, I am an XBOX player, and with other profiles I can see the content of path of building. But with my Talir Rilat account I have problems and I can't see my broken character

**Comment by Talir-1** [comment]
> When I navigate to https://www.pathofexile.com/character-window/get-characters?accountName=Rogganz8&realm=xbox in my browser, I can't access your account. Can you access it when logged out?

If I can enter my account, "The profile is private" keeps appearing when it is not, I am an XBOX player, and with other profiles I can see the content of path of building. But with my Talir Rilat account I have problems and I can't see my broken character

**Comment by zao** [comment]
The space in `Talir Rilat` might need to be escaped as `Talir%20Rilat`, the help text about "non-ASCII characters" doesn't mention that spaces are special in URLs as well.

**Comment by Talir-1** [comment]
> The space in `Talir Rilat` might need to be escaped as `Talir%20Rilat`, the help text about "non-ASCII characters" doesn't mention that spaces are special in URLs as well.

como podria buscar mi cuenta entonces para que aparezca ? te ha aparecido a ti? mi perfil de xbox es: Talir Rilat, y mi personaje en el juego se llama"xMaTaDorx"

**Comment by Talir-1** [comment]
como podria buscar mi cuenta entonces para que aparezca ? te ha aparecido a ti? mi perfil de xbox es: Talir Rilat, y mi personaje en el juego se llama"xMaTaDorx"

**Comment by Talir-1** [comment]
> The space in `Talir Rilat` might need to be escaped as `Talir%20Rilat`, the help text about "non-ASCII characters" doesn't mention that spaces are special in URLs as well.

How could I search for my account then so that it appears? has it appeared to you? my xbox profile is: Talir Rilat, and my in-game character is called"xMaTaDorx"

**Comment by Talir-1** [comment]
How could I search for my account then so that it appears? has it appeared to you? my xbox profile is: Talir Rilat, and my in-game character is called"xMaTaDorx"

**Comment by Talir-1** [comment]
> Talir%20Rilat

you are a genius now i can access my character thanks for the help
