### ISSUE TITLE
Error when setting character level below 1

### ISSUE THREAD

**Issue by dcroitoru** [PathOfBuildingCommunity/PathOfBuilding#4764]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Validate character level (>= 1)

### What is the actual behaviour/value?

Error "on frame"...

### How to reproduce the issue

1. create new build
2. go to tree tab
3. decrease character level from 1 to 0

### Character build code

```shell
not aplicable
```

### Screenshots

![image](https://user-images.githubusercontent.com/1316774/184405706-9d335054-7a8a-4a07-a25c-4d54b3d7b4b9.png)

**Comment by dcroitoru** [comment]
Related to #4625?

**Comment by LocalIdentity** [comment]
This is fixed on our dev branch and will be in the next update
