### ISSUE TITLE
Error when clicking on 'New' button

### ISSUE THREAD

**Issue by CloudyZN** [PathOfBuildingCommunity/PathOfBuilding#4777]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Clicking the 'New' button should open a new blank build...

### What is the actual behaviour/value?

... but it gives and error instead. Uninstalling and reinstalling does not fix the issue. I can modify other builds with no problems, and create new save files by saving an old one as a different name. I can import builds just fine into new build pages. I have taken a screenshot of the error message, of which idk what it means. 

### Character build code

```shell
This error affects the program, not a particular build.
```

### Screenshots

https://i.imgur.com/n3A4J5D.jpg

**Comment by QuickStick123** [comment]
I suspect this is due to you having character level set to 0 in the options menu it should be fixed in next release.

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/184469659-e350be00-b77f-4e7f-9473-ffb073c2fa26.png)

**Comment by CloudyZN** [comment]
> I suspect this is due to you having character level set to 0 in the options menu it should be fixed in next release.

Thanks! Such a simple goof on my part, probably accidentally changed it. The issue is fixed.
