### ISSUE TITLE
Shock Value Not Calculated

### ISSUE THREAD

**Issue by andrewkhunn** [PathOfBuildingCommunity/PathOfBuilding#4799]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Shock value should be calculated in calcs based on the ailment threshhold .

### What is the actual behaviour/value?

Running the latest dev branch, with Brain Rattler equipped, "Is the Enemy Shocked" checked on, with no value entered below, shock value is not being calculated in calcs or amplifying damage in any way.

### Character build code

```shell
https://pobb.in/_I-hTv6iJRPH
```

### Screenshots

![Screenshot 2022-08-14 115729](https://user-images.githubusercontent.com/116436/184545068-ec753b12-019f-413b-9d09-6134e584fce2.png)

**Comment by Lilylicious** [comment]
Fixed by #4795

**Comment by andrewkhunn** [comment]
Whoops, sorry about that.
