### ISSUE TITLE
Affix Stacking on Precursor's Emblem

### ISSUE THREAD

**Issue by Sinured** [PathOfBuildingCommunity/PathOfBuilding#4822]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Precursor's Emblem rolls with three randomly valid affixes and if it rolls the same mod multiple times, they stacks if applicable. A +3 Charge ring is the most famous example.

### What is the actual behaviour/value?

When adding a Precursor's Emblem to a build, it only applies a selected modifier once. 

### How to reproduce the issue

1. Under the Items tab select Precursor's Emblem
2. Select the same affix multiple times

### Character build code

```shell
https://pastebin.com/uGD93YNK
```

### Screenshots

![precursors](https://user-images.githubusercontent.com/100538010/184626143-b0df3976-be58-48c6-8664-7262b3f28552.png)

**Comment by Regisle** [comment]
This is not the case, mods show up depending on what ring base you put in, with the higher tier ring (from aul) being the only one that gives +1 charge, making a ring only able to have one total charge, also the lesser mods which do show up multiple times, have had their ranges doubled/tripled to allow for the simulation of having the mod multiple times

**Comment by Sinured** [comment]
I was trying multiple variations and also couldnt replicate this ring for example
![prec3](https://user-images.githubusercontent.com/100538010/184627296-96c98f0d-9562-4b18-8bab-6f4bfc46ec22.png)
![prec2](https://user-images.githubusercontent.com/100538010/184627384-2b68d807-0637-4d27-acda-eb26f9edb147.png)

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/184627699-9a72c784-5c45-4fc5-b4e3-e7c5efd2f348.png)
move the slider?

**Comment by Sinured** [comment]
yeah, didnt saw that. I assumed it would do it automatically
