### ISSUE TITLE
Echoes of creation unique helm integration in pob

### ISSUE THREAD

**Issue by TheKejdz** [PathOfBuildingCommunity/PathOfBuilding#4823]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Not integrated into pob.

### Describe the solution you'd like

make my slammer dps go brrr

**Comment by Sinured** [comment]
It's in the pipeline but without the support of a condition of how many warcries is exterting an attack. So you have to calculate that still manually.

**Comment by AlexPagoni** [comment]
Hello @Sinured ,
Has this change been implemented? I decided to comment here rather than opening a new issue since this is still open.
Using Echoes on my build and I don't see a dps increase over a regular helmet.

Thanks!
