### ISSUE TITLE
Helmets still have a not updated modifier for socketed minion gems

### ISSUE THREAD

**Issue by marcin7848** [PathOfBuildingCommunity/PathOfBuilding#4831]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

`Helmets can no longer roll +1–3 to Level of socketed Minion Gems. Instead, they can now roll +1–2 to Level of all Minion Skill Gems.`
it wasn't updated, still helmets have +1–3 to Level of socketed Minion Gems.

### What is the actual behaviour/value?

expected modifier on helmets: +1–2 to Level of all Minion Skill Gems

### Character build code

```shell
-
```

**Comment by Lilylicious** [comment]
Item modifiers will be updated when the patch releases by exporting them directly from game files.
