### ISSUE TITLE
Allocating Unbreakable with Forbidden Flesh/Flame not giving elemental defenses

### ISSUE THREAD

**Issue by KumaSC** [PathOfBuildingCommunity/PathOfBuilding#4833]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When using Forbidden Flesh/Flame to attain the Unbreakable Juggernaut ascendancy node I do not get additional elemental max hit. I do however still get the bonus armour from my body arour.

### What is the actual behaviour/value?

Armour should apply to 8% of hit from fire, cold and lightning damage.

### Character build code

```shell
https://pastebin.com/EGc18FWL
```

### Screenshots

![Unbreakable1](https://user-images.githubusercontent.com/52883447/184714396-7cb6bf49-3f55-430e-b005-83c2b281e8e9.png)
![Unbrekable 2](https://user-images.githubusercontent.com/52883447/184714398-20116c94-977e-49af-bca8-24fed313ee96.png)

**Comment by Lilylicious** [comment]
Try re-importing your build. It works fine on my end.

**Comment by LocalIdentity** [comment]
Make sure you are on 2.20.1 as that mod was not working in 2.20.0

**Comment by KumaSC** [comment]
It is working now - thanks a lot for your hard work <3
