### ISSUE TITLE
support MacOS，it cool

### ISSUE THREAD

**Issue by xunfeng1980** [PathOfBuildingCommunity/PathOfBuilding#4842]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'd like to run POB on MacOS,but it can't

### Describe the solution you'd like

I'd like to run POB on MacOS,but it can't

**Comment by QuickStick123** [comment]
https://www.pathofexile.com/forum/view-thread/3009944

**Comment by zgover** [comment]
@QuickStick123 why not quickly port this to Wasm using something like [ysugimoto/webassembly-lua](https://github.com/ysugimoto/webassembly-lua), then just use electron to allow cross-platform builds? Could also at that point just deploy a web version and not require anyone to install/run an executable.

**Comment by QuickStick123** [comment]
@meepen had a love2D port that was mostly functionally not sure if that will ever replace our current implementation though and should be able to support cross platform. https://github.com/meepen/PathOfBuilding/tree/cross-platform
I don't have much knowledge in this area so there would be better people to ask then me.

**Comment by meepen** [comment]
Honestly it would probably be best to go with a love2d build if you are looking for most compatible. I think in the long run SimpleGraphics should be phased out entirely but it's unprecedented for pob's engine to be completely changed in an update by itself.

My port found over there aims to support any backend engine you run it in it you, were to write a wrapper for the api. It doesn't force you to use only love2d and supports running it in both engines.
