### ISSUE TITLE
Inconsistent behaviour for enemy armour calculation when switching bosses in configuration tab

### ISSUE THREAD

**Issue by Intrets** [PathOfBuildingCommunity/PathOfBuilding#4847]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When changing `Is the Enemy a Boss?`, in the calculations tab the values stay consistent no matter the order you change them in.

### What is the actual behaviour/value?

When changing `Is the enemy a boss?`, in the calculation tab the armour my hit is calculated against doesn't always update or something else is wrong. Going in a certain order the average damage on an empty character goes from 1.9 to 0.0 on the no boss calculation.

### How to reproduce the issue

1. Open a empty character build, average damage is at 1.9, showing enemy physical damage reduction of 52% in the calcs tab.
2. Go to configuration tab
3. Switch `Is the Enemy a boss?` to `Guardian/Pinnacle Boss`
3. Switch `Is the Enemy a boss?` to `No`
4. Average damage now shows as 0.0, showing enemy physical damage reduction of 90% in the calcs tab.

### Character build code

```shell
eNqtWm9z2jgTf937FAzvGwoEmt6QuyFAEmZCyxNoe_eqI-wFdJEtxpJJuE__rCQbHIKMrFxfpMba3672j1a7knt_vkSstoVEUB5f15sXn-o1iAMe0nh1Xf8-v_14Vf_zj996UyLX35Y3KWVq5I_fPvT0c43BFhji6jVJkhXIHzmn9i_ktCGxXAOPJ-Qfntzx8Lr-lcdQry1IHFKZ_woYEeIrieC6PgsQXK8REUAcDg7vDWFEaDzjwRPIu4SnGy12S-F5wkOkGU-m3x7nBaE0LgrFOX_oTRnZQTKTRNYE_rmu91F1soIhifAvciMsBWWGq6vO5-ZlS_9t1xunwbMNQFgAtWyE0wRGyyUEkm5hkFA5WJM4OIj7ZMNVpZ2kTNINo5AUZtWxIe7fMP_yxUY755Kw4XS2J21dtLqtg5HKcVyen_9PKtc3DA3qIUVhx6uYSvAETzkVPH6HfkWo3UUpY7h63Gh5tKCxlzUmJCYDLhxs_kCX4EY5mrnRPeIycqNUs5xCggtduk-2EiCTMIOAYzKpIqMKpKCHnzAP5GjmA_AQNJOHTNKyUg3hxYFqHEsnXlsu9SZwbm566Y3up3vKrjVRT9c7QQPCJuSFRmmEiW9OnuAgo1vio9VaxrhobdD2Z3uCvaUJ-OAGnIVeuDXhwgeoItHBGLjfBb8r2nEcuIX39zgBAcm2sE12SwGPGJxqS14wcEQcRGQhftj6Pp0RtYLYTY0HgGB9h9XHI5HglhL2VJ1ycypaJ3MqwhPm7DgCKhhHAY-Mc_GljLiieX6SJHRIWTEkq91sTYFVpM5iaDcgG4cMp5xQRDs547U4pzgqQioabLQlopgSm91ybQy5W1QBllwICMG1zpwm_B9VybJqsH4S8TRx9IchdlIgT-2mgn-EMA3cto8bhp2E6-xxVoxVQvSlJMHTkIcrqCSkOmKWbja4ypXLXXFqY3oEQQslwMeuA_U3XFZOq0rtYO4CDtTOAvb7sruUI4i7LmpXraDMgdxZxL45nGDiijBN684S29rDkrc6B3sKp4ZCEzo2KlP-jDNfq45eVKPG6uNQcVinkkD8786Z_ytyJwGjOEwTtRScZRwjTomZ0wizpRBDIklNAEmC9QN6-bpeL_y6JYwtcOXjW4XqNfQ5iXoaRxueSP1yQFggNM9xvEllLdaHHBEVwa9Fulyq8wzkKRN9CDO6vR0N5uMfo2waRYh4ooz9itNooVp-8_8hWGagc2FNpAthHq_rPyg8zxRqCJJQhqYJOGNkIyC8ri8JEyiZ4qOmmaG-gSzhpqmw1MzPT07zOhDYOY1eIJGoLxYHQULBOq_9-JlJGYGqDlBus3FTJxN2RiaHD4iQZp-2WEqfAtm5qIMZqzpqsASLMUOYVXI2esYScrcBgbsqXdJARXy5y-dIbahK7BIEuFiCXYm_s53IzkMf9dgYmEE72BzX2NDZaIlV9VGR1apm1A4fQkCsuptBO3hf-vEYzWTjsqcq4fSVxzrIcdH0KVO7htWzIwZ7EjvDb3INidmKrJwmmKNyktKFk9BFKu3LuEBRYivdllospMbsUNOCWXRQYyWZ6FXjYTFokcbOynQ61kRWBs3rZYv5zGiJEnnLYJl_NmxnYCoYq_-yeqhsfWOxbF_fatAONuvjLQuZpI4cdCwPYQmYhUqDeU9TkkVlGg8x4ckSgzqyMrtSf8tpaCr1d3HTSp5mdrBUJV4mSZy0W2WOupN5r-mPGpz_xPzZuZglfxdIzjDCxHtfsrW7cdqX_vdAmLqI4Ox9DN-c_71LTy4FicOhOuJwVrTXyOvbni4pRE1g4XsHkbjZYftxq5Lm0QVHRCTudxA9qOvEOVdFOAkkJA_mejETRrShsspU6uu_V5zzIA1hSVKm3v8vJYzKnSr8C28zrjFFU4s1f1YBZvio6kdgen14MCN9JjMWSkg-EWOubBraBM1McaOvepwnAPmEsfhSJAaGP4r3m-NQTy7CIhOSXba1qpYixiYAHzpXV-12vSaRXeFutfkluzY1cMX5Q-_744N--LCWciN-bzSen58vNkSu-RJeKIOLgEeNDYJwTh915_BRsW308d_Nqq__aUaNnFPP3LYKEyANNXetplJOPXzluIGrMfUy_6FVV21G1hXNZKL0-Zfz6G-tqzIsRruckE3mBDWWOaWduQRL0CFFayR6TeeeVYR_5W1cbyzRKZmR1XMeFKkAc8nxE8iGx_q1kmPaJ0NoJcr8menPeN5qGbJac_ZMNrX-YicEYTVjn1oHUcjWOKNhhR7DWm6wcqobjmvUc0KndDkzqRtgsiLkFgP1qdZ2mlLr1JTafuZ1M0LrP4Jd-k2y6yet629Nn3g644F7wLpBVhV0IpK6PnLOhN8d41tVy1Rn3PZfRU0feZd-sdD0i7zL8-5xMWxVtqfCy1Nxp7zT8ZiPRw5snxMT7mqma6vovtNW9oqvjg_IaUm6OMJLz463WVsefu_6raS2X_i2q0fZpX_a94jpprfx2y4BcelC5DHtdxQ_jp7090LXIyr93fCOcHFNyQrruGrcST0s94jduFslUDlRWM3rmS7c_emjTtvBTk1_N1x6W6vjo43LevEP8jNT6kcpO7G39RpZD6l7Yd2E6ks9Hi_p6s0V3fHnyIeLPf1Z8ts7PYgh2o3FDRfiLO3xB9ZnAebL65NkU0YCWHMWQlKcSfaRc363-Ln43dAp-uI3yzmoUw55_Q1HQdZ5SceQ9qf8CCrzRq9x_On6_wHDtPUK
```

**Comment by Regisle** [comment]
This has to do with the enemy leveling not updating correctly, setting it to "Guardian/Pinnacle Boss" forces a minimum level onto the boss and it does not get removed untill after its processed again, making it snapshot the level

This isnt an issue for builds of level 84 and above, and can easily be solved by changing anything on the config tab which would force it to update again
