### ISSUE TITLE
Arcane Surge effect from Subline Vision isnt applying again

### ISSUE THREAD

**Issue by IceMagma** [PathOfBuildingCommunity/PathOfBuilding#4853]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Subline Vision doesnt give the 80% increased Arcane Surge effect, this was meant to be fixed but apparently got reintroduced somewhere until nowl.

### What is the actual behaviour/value?

Arcane Surge has a base 20% more spell damage multiplier. with the 60% from the tree and 80% from Subline Vision we should get 20%*2.4=48% more spell damage but only the 60% from the tree apply resulting in 32% more spell damage

### How to reproduce the issue

Take the Arcane Surge nodes on the tree and Subline Vision with Clarity and use Clarity

### Character build code

```shell
https://pastebin.com/kt4hhqTe
```

**Comment by QuickStick123** [comment]
This was never fixed I have an open pull request that fixes this and there is also an open issue about this.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4551
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4388
