### ISSUE TITLE
"support by" on items does not change manacost

### ISSUE THREAD

**Issue by hgfedcba** [PathOfBuildingCommunity/PathOfBuilding#486]
In this example barrage is socketed in a bow that supports it with cast on crit, however the manacost don't change at all. The damage of blade vortex is correctly calculated, so the stat is not ignored, however the mana multiplier on coc is dismissed for some reason.
https://pastebin.com/at5XzXEA

**Comment by LocalIdentity** [comment]
The mana cost of barrage is correctly increased in for the build that you linked when I enabled CoC. Not sure what your questions was

**Comment by hgfedcba** [comment]
the problem is barrage is socketed in a bow "supported by cast on crit" as stated above. However barrage does not cost more mana despite coc mana multiplier. The gem is there to showcase the manacost is supposed to increase, the bug is with the mon on the item...

**Comment by LocalIdentity** [comment]
Cast on Crit used to not effect the mana cost of the spell it was linked to, this was changed in 3.16
