### ISSUE TITLE
Trader window: being able to set max price

### ISSUE THREAD

**Issue by ocombe** [PathOfBuildingCommunity/PathOfBuilding#4866]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I love the new trader window to search for items on the trade website, but all it gets are mirror tier items

### Describe the solution you'd like

I would like to be able to fix the max price to get realistic items, not just the ones that I will never be able to buy.

### Additional context

Also now that the "best computation for item mods" exists in PoB, I would love to get a way to use this when creating new items to sort mods by best [dps/life/....], it would help creating new custom items for a build, or even see what mods could be interesting to craft on an item. Not sure if it's possible to use the existing code for that, but maybe ?

cc @Nostrademous

**Comment by Nostrademous** [comment]
Thanks for the feedback. I think this is a good idea. Will implement but this might be a couple weeks from now as we will be focusing time for now implementing a lot of 3.19 league concepts as we get them until we reach stability after the 3.19 start.

**Comment by ocombe** [comment]
Great, thanks ! There's no hurry, I know that new leagues are always very busy

**Comment by QuickStick123** [comment]
fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5280
