### ISSUE TITLE
Trader window: Stats other than dps

### ISSUE THREAD

**Issue by Exactuz** [PathOfBuildingCommunity/PathOfBuilding#4872]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Right now the weighted sum only solves for highest dps.

### Describe the solution you'd like

I would like if we could add custom stats and a custom weight to them and peg them against dps. For eхample i select maхimum life and set it to have 200% weight of dps, that way poe.trade search would include other stats than just dps in highest weight sum search. The most important stats currently imo are life(and other sources of ehp) and spell suppression

**Comment by Nostrademous** [comment]
@Exactuz a future expansion is to allow EHP calculations to be part of weighted search and enable the user to set the ratio of how much you care about EHP versus DPS. So this is planned, just for the future.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5507
