### ISSUE TITLE
Unique Jewels that convert attributes can convert the same stat twice

### ISSUE THREAD

**Issue by hgfedcba** [PathOfBuildingCommunity/PathOfBuilding#4873]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Art of the Gladiator gives 20 dex. When in range of fertile mind it gives 20 int. When in range of 2 fertile mind it gives 40 int, which is wrong. It should still be 20.

### What is the actual behaviour/value?

see above

### How to reproduce the issue

https://pastebin.com/2SsuwBkN

unksill and reskill art of the gladiator. That noce clearly gives 40 int.

### Character build code

```shell
https://pastebin.com/2SsuwBkN
```

**Comment by Peechey** [comment]
Your pastebin 404'ed so I'm providing a minimal build
<pre>eNrtG9ty4jj2ufMVLp52awnBGANJkZkiQNLMQkID3b2zL12KLUAT2WIsQUJv7b_vkWyDkyAjnHncmaq0sc79pnMkaP_6ElBrgyNOWHhdsivVkoVDj_kkXFyXvs5uz1ulX385a4-RWD7Mb9aEypVfzj611bNF8QZTwCtZAkULLL6llJwfQGmFQrHELByhP1h0x_zr0j0Lccl6RKFPRPrJo4jzexTg69LUA-SShbiHQ7-7fx8DBoiEU-Y9YXEXsfVKsd0Q_DxiPsAMRuOHySzDlIRZpiDzp_aYoi2OpgIJi8Of61IHVEcL3EMB_AVqiK6BVK1Sa7q1VrV12Wo1G_XSxWHk6Qpjf4dkV2o6wHGE-_M59gTZ4G5ERHeJQm_PrqrDOxV2tKaCrCjBUUYqV4fx-R1xu6olP2MC0d54mrFR06k6TrPabDVcu5mPx8RxBb4TsbyhYNECXCTuYBESgQsijxnhLPyAfllUvY_WlEL6mMGy4JGEhawxQiHqMm5g8yGZYzPI_tQMbgJ5ZAYppRzjCDJdmAt7EkLCYYo9BtXkFB6noGT0KMasAGZ_WgShAKOp2JeSuraS9PDLHkpLaxDuGdpOVU9sw4TaBo4Jp3Kv_3m8g2xqU2K83HLiITpCLyRYB1D6ZugJ73k0a3onLZYihKzVobr1ilvf_a-10S2J8AdJdBn1P0piiRjX0dA7WEaqga1gQ_SuJOwg9MzC_2sYYY6jTWYfzXPFHE8geOWe_UixIcaeRZICJttdzGqBQzM1hhh7yztoTyZIYLOSkZHCzbWnBDaypwQ8YM8c-q8xTjCPRHxtHrvSygM-0UDfUeQbFLUQR4vtdEkwPRE6iaJtF60MaqD0QhbbyBuv2RlFUhblRIP1N4hna2btiDYxeFaRmrbNHWHoygDDx6a96Dhif8hul56G1okCto4MHRIDm2mQVv-4zZ9gf-2Z7TA3FMYNU_FBLEpPwugIgbynHvMX-CQmp2NM16sV5Ll0uime3LAmmJNMm3Du1I5DP0BiGeWV3M7MGeyhjRnstm5zLm9QzHWR--pbNg0TcGMWuwlyBKUrgEKtxk-Yffc1WOscmDuMhg4FaDjMjNkzSL6UYz8_DRr6jx2CoxUlwuHPrTH9V-BGDPqhv45kKhjzeItxiM2MBFAuOe8hgSyOUeQth-Dl61Ip8-kWUfoImQ9vJVb7Qh2myKdBsGKRUC-7iHpc0RyEq7WwQnUSEhDu_Xhcz-fy0ANoikid1PRvb_vd2eBbPxEji8KfCKU_wnXwKM8F4n_3wTLFqhZafP3I48fr0jeCn6cSq4cFIhRM4zFK0Ypj_7o0R5QDZwKPCmYK-noih5qCgmYzPWQ5TGsPoKfUf8GRAH2hPfAigrVy7daPCBUzlJ2AdJuOmjy90BOKa3gXcRHv1BpLqaMiPRV5eqNVRy7m4ELMIKrlnKwesYTYrjCHbZXMiScjPt_lM4COoXLs4nmQLN42x9_JTqSnoY6DdATiRT1yfKSjw05Wc6yqjpO0Vo1X9eg97CGt7vGiHnnX_LEQzKSjsoPKoXTPQhXkkDQdQuWuofVsn-IdiJ7gg1jiKN6KtJRGUKNSkNzEicjjWujTOAORYys1mmosJNf0qPEYptFBruVUolejh8agWRg9qXjW0RayPNS0YdaYL17NUSIdGjTyJ8t6AnEHo_Vf0g_l5Tc0y_r8lot65Dg_3pMQ0dqQgorlHp5jqEK5wbyDyamiYh32oOCJHIMakop3pc6GET_u1D9ETSl5mNjeUifRiovEQbudTFFNMh81_ZsB5y8xf3IypqnfGZAjhKDwfs7Z2s0o7Vr_zxhReVnB6McIvjsB_JCeTHAU-j15yGGsaPsi7W_bqqXgFofG9w4H_GYL48etLJpvLkECJGC_w8FQ3jnOmGzCkSdwNIzvIBNmSBkq6UyFuiN8RTkNUh_P0ZrK91_WiBKxlY1_5m1CtQYv-ZI9y_iKycjmh0N1HQ7jlQ4VCQXJI5UjtlYihbKAnegdqysfZxHGqbzQe0mQGA0-ZO9AB76SLYAeE0fbZGeVE0UIMwCXB3Wt2mXZbtaqdtlu2I1m2W1U4dmtV1tlt9VynLJTr7ecsn3ZtO1yvdWqtcq2Xb9swt-WC6h2w7XLTqPVkkh2rVmuOa1yw21Vy47jAhHHdasS3a7XS5YAsTP3vPZlcoUbiyk1-NT-Ohmqh09LIVb86uLi-fm5skJiyeb4hVBc8VhwsQIk0P1cDSjnkuxFB_67WXQ6fbK6__Kz_-O3y-jmdtq949WfPzbRM29M3dnw94cvff9-03mo_1sMhk_kz8t_bgFPMb5IObfjm2Iei5F8UhaTciotITIFDgY73xyAU3bbwyXnBtKLe-rwARymfCs9Kh_uGTQtck2-TD8of8vRKpkEpyKSTvzJWPD7dem82WhW6i23EUcVZLoYodUurCVUEpKtJCKhAe8RCIZIVbQ0riXgv9QZh1tpXl46jTjsBqABT4JNPqe5seY4vg_6jtGKhep1JoIlaBK9SvEJgllke2V9vR98-do_u5XzGMXWiIT-WZc9QnWyfsPPmJ5NkE_W_Moaykn5DIYQSjyog1dW9ew_MEMv8FW14v73H3-zG-e1-t8twaxBKKCOk4XU5qyHXyDWgZU1j1hgjeNI4RYJrZiyRbg1A0J8zqIA--8ISCfBiDyRrCzFEIKz4pYyqZgHkR4QXUgDvLZE7f-WUOGTEzrZiGlPKUtPImJAy54-o5XVedxyjqiVZJy7z7JqKtQB1LdoNTO0fKgbBltYQYEO6XJEqBsMwXEayi0U2CfLMRKpdkgkp5h5zYxQ-4vQ6sWEbBTj1ihuzSLxdMQDnzG01eJURgciqVGEz5Hwu6NsI1v90wk7xbPILsKvXiwW7GKRVz_uHhPDnkr2UHgVVNyo7rgF5ClQA51jbPytFR9qnOi-w1YuFF9uESSjlDRxRCE93cJmrRXwe6NYJjnFwtc5Pcrqxct-gZi2CxvfMQmIuglQAbE_0PwYerK4FxoForK4Gz4QLqYlWeIaZo05aAHLTUi4MOsETi4UWvMWLBfm_iyijmNgJ7u4G-qFreUW0cYkX4oH-RGROsGaHtjb4nESRkZ1bKIOJ9SdNwvnZPHuBvvtV_r3997qq_3vr7xxiIPtgN8wzo_Cvv2RwlGE-NcLB8HGFHl4yaiPo6wkyQ8F0qv3ZvaLdYfg5YVvelueIjkGOOlXe1IcNx_l9deiMvKlJ7SJN9oXb3_-8T_1xuJh</pre>

For consideration, a screenshot showing the +40 int and -20 dex while hovering over an unallocated Art of the Gladiator in live 2.20.2:

![image](https://user-images.githubusercontent.com/92683202/185274789-61b505d0-424c-4548-9270-7d1425b335df.png)

**Comment by hgfedcba** [comment]
thanks, though I am interested what broke my link.

**Comment by Wires77** [comment]
> thanks, though I am interested what broke my link.

Since so many builds are created prior to league start by the community, pastebin sometimes flags them as spam and deletes them.  I'd recommend using the dropdown when exporting to select a different, dedicated website for sharing builds.
