### ISSUE TITLE
Effective Hit Pool Calculation Bug - Static Value

### ISSUE THREAD

**Issue by abkamand** [PathOfBuildingCommunity/PathOfBuilding#4877]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Expect Effective Hit Pool to increase when putting in custom modifiers like "100% increased maximum life" or checking/unchecking defensive auras. 

### What is the actual behaviour/value?

Effective Hit Pool does not change at all.

### How to reproduce the issue

Tough to reproduce as this seems to only be affecting some of my POB's and it's difficult to pinpoint what's going wrong with the calculation.

1. You can input values in 'Custom Modifiers' like "150% increased maximum life" or "30% less damage taken", generic defensive multipliers that *should* raise effective hit pool and notice how the calculation does not change.

### Character build code

```shell
https://pastebin.com/nGjxHcb7
```

**Comment by abkamand** [comment]
I think I might just be missing some sort of breakpoint with respect to survivability somewhere in this build. When I raise

**Comment by QuickStick123** [comment]
Yeah that is what it looks like lowering hit damage would give you more granurality but might cause armour calculatons to become less accurate.

**Comment by abkamand** [comment]
Not sure if there's some sort of survivability breakpoint with this specific build but it's odd to me how a generic "30% less damage taken" has no effect on the effective hit pool calculation, bumping that up to 40%+ however does, lending credence to the breakpoint theory. Similarly for life, 100% increased maximum life or 150% maximum life have no effects on effective health pool, but getting to larger numbers like 200% will start to alter the calculation.

**Comment by QuickStick123** [comment]
Your hits before death of around 10k mixed damage is 3 acording to the calculations.
![image](https://user-images.githubusercontent.com/31533893/185005593-568c05f7-836a-4e97-9952-bbfc51110886.png)

**Comment by abkamand** [comment]
I see, so it is a breakpoint situation where X amount of mitigation was still resulting in 3 hit kill but past a certain breakpoint takes that to 4. My bad! Thanks!
