### ISSUE TITLE
Add the ability to set maximum price for item and/or whole build

### ISSUE THREAD

**Issue by AloofLibra** [PathOfBuildingCommunity/PathOfBuilding#4898]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'd like to have an ability to set maximum price for the items searched by new trade integration. 

### Describe the solution you'd like

For example, I assume that the wand for my build should not exceed 200 chaos. But I want the highest DPS for the price. 
In this case I would enter the desired cost into the search box and it would show me the best result I can get. 
For now it can be done via the trade site, but it is clucky and I can't summarise total upgrade cost easily this way.

**Comment by Dullson** [comment]
Duplicate Issue, see #4866
