### ISSUE TITLE
Double corrupt curse on hit / + AoE gems improper calculation

### ISSUE THREAD

**Issue by MatthewSbar** [PathOfBuildingCommunity/PathOfBuilding#49]
I have a pair of gloves double corrupted with

+2 AoE gems
Curse on hit with level 11 vulnerability

The skills page shows this as level 11+2, but the curse on hit from the corruption is not a gem, so it should not get a benefit from the +2 AoE gems corruption.

**Comment by homutan** [comment]
Can you show your PoB? I can't reproduce this issue.

**Comment by MatthewSbar** [comment]
Alright I must be losing my mind, now I don't see this anymore. Neeeevermind

**Comment by MatthewSbar** [comment]
Ok it shows up on load, but then editing the value of despair on the gloves fixes it.

https://pastebin.com/APr7Wy22

**Comment by LocalIdentity** [comment]
How did you import the gloves to this build?

**Comment by ppoelzl** [comment]
It's a known limitation of current PoB: https://github.com/Openarl/PathOfBuilding/issues/1757

**Comment by ppoelzl** [comment]
Skills granted by corruption implicits are treated as gems socketed into that item

**Comment by MatthewSbar** [comment]
> How did you import the gloves to this build?

Imported my character

Platform: PC
Account name: Cerdom
Character name: SpeederSparker

It's indeed the same bug ppoelzl pointed out. Because it fixes itself if you edit the item (ie change it to level 9 despair, then change it back to level 11 etc), I'm assuming the issue has more to do with the init/load/save part of the code rather than the calculation itself

**Comment by Nostrademous** [comment]
Fixed a long time ago.
