### ISSUE TITLE
Problem Startup

### ISSUE THREAD

**Issue by Razerox** [PathOfBuildingCommunity/PathOfBuilding#4900]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When i start PoB to prepare for the newest league it starts and then imediately closes before showing the full application. In the Attached Screenshot everything is shown, that i can see. After the Pixel format: Need 32,24,0 the Applicationwill close.

### What is the actual behaviour/value?

The Programm closes during Startup

### Character build code

```shell
https://pobb.in/FLv9ALb3HDeA
```

### Screenshots

<img width="292" alt="PoB Error-" src="https://user-images.githubusercontent.com/102984506/185312991-7edbc6d3-5cea-4a29-a6bc-dfeac105a31c.png">

**Comment by QuickStick123** [comment]
Try this suggestion. https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087
This has some issues for exmaple timeless jewels will cause the program to crash or they won't work and there are visual bugs. There is a fix in the work for the timeless crash though.

**Comment by Razerox** [comment]
Problem solved. Thanks for the quick help.

**Comment by QuickStick123** [comment]
It is worth noting you will need to replace these file everytime it updates as well. As they will likely get overwritten.

**Comment by Razerox** [comment]
Yeah, i already tried to Update from the MEssage in the app, but got the same issue, but after replacing the files again it worked. Guess i trie to update once in a while, until it keeps working without replacing the files.
