### ISSUE TITLE
summon skeleton still has the 50% more added damage modifier

### ISSUE THREAD

**Issue by Danjojo** [PathOfBuildingCommunity/PathOfBuilding#4904]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

summon skeleton gem not having the 50% more added damage line since it was removed in 3.19

### What is the actual behaviour/value?

summon skeleton gem still has the 50% more added damage line

### How to reproduce the issue

1- put on summon skeleton
2- read the gem text

### Character build code

```shell
https://pastebin.com/jqbMf4qL
```

**Comment by Lilylicious** [comment]
Gems are not updated until the official patch releases, since we get that directly from the game files.
