### ISSUE TITLE
PoB became super laggy

### ISSUE THREAD

**Issue by GlacialSpikePoE** [PathOfBuildingCommunity/PathOfBuilding#4905]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

poB should be a lag free software

### What is the actual behaviour/value?

My PoB has become quite laggy for past three-four days. What I mean is I have to wait for a few seconds before I can click on anything, can't move the Skill Tree screen up/down. The clicks are not instantaneous anymore.I have completely uninstalled the program and reinstalled it. Even did the uninstallation with  third party software to remove all the leftovers after a normal uninstallation.reinstalled pob still the same problem persists.have restarted pc with no joy.There's no such issue on the github page of pob recorded so far. if anyone facing the same issue and has solved it please help.

### Character build code

```shell
The whole software is laggy for me with or without build code.
```

**Comment by QuickStick123** [comment]
Please check a old version e.g. 2.18 and see if it is actually an issue that has been introduced in a recent version. Otherwise it might be related to your system.

**Comment by QuickStick123** [comment]
There have been no recent changes that should effect this there is some optimsation code that lowers framerate if it inactive. Some recent driver update might've start causing this to trigger.

You can also try this suggestion. https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087
This has some issues for exmaple timeless jewels will cause the program to crash or they won't work and there are visual bugs. There is a fix in the work for the timeless crash though.
It is worth noting you will need to replace these file everytime it updates as well. As they will likely get overwritten.

**Comment by Wires77** [comment]
What build are you using?  Often times slowness can come from a build with many skills added to the full DPS calculations

**Comment by GlacialSpikePoE** [comment]
> There have been no recent changes that should effect this there is some optimsation code that lowers framerate if pob is inactive. Some recent driver/system update might've started causing this to trigger.
> 
> You can also try this suggestion. [#4736 (comment)](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087) This has some issues for exmaple timeless jewels will cause the program to crash or they won't work and there are visual bugs. There is a fix in the work for the timeless crash though. It is worth noting you will need to replace these file everytime it updates as well. As they will likely get overwritten.

Thanks for your reply mate,much appreciated. I installed an older version ,viz,2.18 and still the same problem.I know it has to be something on my side I just don't know what's that.Using windows 10,no firewall installed ( windows default one is disabled too).The whole PoB software has become laggy doesn't matter if there is a build loaded or not.guess my leaguestart is ruined :(

**Comment by PJacek** [comment]
Could you share with us how that bugged tree looks like?

**Comment by QuickStick123** [comment]
Try this https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1219670766

**Comment by GlacialSpikePoE** [comment]
> Try this [#4736 (comment)](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1219670766)

Thanks for all your help,after trying out things for several hours finally i reset my windows and turned off automatic updates .PoB is working again as it should .
