### ISSUE TITLE
grand spectrum

### ISSUE THREAD

**Issue by Alfadiron** [PathOfBuildingCommunity/PathOfBuilding#4907]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

yes

### Describe the solution you'd like

please add new uniques from grand spectrum correctly still some of them missing

**Comment by learn2draw** [comment]
#4897 A pull request for this is already open
