### ISSUE TITLE
On Frame Error when trying to search/add Alchemist mark to existing build

### ISSUE THREAD

**Issue by Takaoshi** [PathOfBuildingCommunity/PathOfBuilding#4932]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The error should not pop up when searching for/adding Alchemist mark to the build.

### What is the actual behaviour/value?

When i search for or Add alchemist mark to my build i get this error. If i close path of building and restart it i cant open the build because the error will pop up everytime.

This only happens with the build in the pob link. It doesn't happen with a completely new build. 

### How to reproduce the issue

1. Searching for/adding Alchemist mark to the build

### Character build code

```shell
https://pobb.in/rbSyA1l6P48n
```

### Screenshots

![poe building error ](https://user-images.githubusercontent.com/111612714/185712066-55a7c665-44ac-484c-a9c4-d1a425147275.png)

**Comment by Regisle** [comment]
fixed by #4931

**Comment by LocalIdentity** [comment]
Fixed in 2.21.1
