### ISSUE TITLE
Adding item in the Items tab (to compare dps, for example) results in item having insane stats like +2000%

### ISSUE THREAD

**Issue by ThirteenEra** [PathOfBuildingCommunity/PathOfBuilding#4944]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When i go into Items tab and copy-paste an item from ingame into the field, the item should appear and display its stats, as well as DPS difference when comparing to currently equipped item.

### What is the actual behaviour/value?

Importing an item instead imports an item with significantly inflated values (+2000% instead of +20%).

### How to reproduce the issue

1. Make new profile
2. Go to items tab
3. Paste an item from ingame
4. THe item now appears with inflated stats (tested on different items with same result)

Note that my screenshots show a pre-existing POB of another character, but this is reproduceable on brand new, empty profile as well.
<img width="1237" alt="bug6" src="https://user-images.githubusercontent.com/111650549/185760248-592dbc6b-3d78-4b57-943b-50ff11853e93.png">
<img width="1190" alt="bug5" src="https://user-images.githubusercontent.com/111650549/185760249-75d18c14-927a-4c0a-a1e8-af5ecbc51210.png">
<img width="969" alt="bug4" src="https://user-images.githubusercontent.com/111650549/185760251-f19bbacc-d8e7-4b98-99b3-aeb7e8e87ebe.png">
<img width="961" alt="bug3" src="https://user-images.githubusercontent.com/111650549/185760253-567d3215-0d3c-4457-8823-82d44eab5059.png">
<img width="615" alt="bug2" src="https://user-images.githubusercontent.com/111650549/185760254-6c2cf3c6-a513-4c16-ac73-d2f6c273a91e.png">
<img width="497" alt="bug1" src="https://user-images.githubusercontent.com/111650549/185760255-e84e3dfd-da95-4e91-aa70-a6de2ae6b263.png">

### Character build code

```shell
eNqtWl1z2jgXvu7-Cg_3DQUCTXfI7pBAEmZCyxtou3vVEfYBtJEtxpJJ2F__Hkk2OAkysrK9SI11nvOtoyPJ_T-fYxZsIRWUJ5eN1tmnRgBJyCOarC4b3-c3Hy8af_7xW39K5Prb8iqjTI388duHvn4OGGyBIa4RSJKuQP4oOHV-IacNSeQaeDIh__D0lkeXja88gUawIElEZfErZESIrySGy8YsRHAjICKEJLo-vDeEMaHJjIePIG9Tnm202C2FpwmPkGY8mX57mJeE0qQsFHX-0J8ysoN0JokMBP65bAzQdLKCIYnxL3IjLAPlhouL7ufWeVv_7TSax8GzDUBUArVthNMURsslhJJu4Tql8npNkvAg7pMNV5d2kjFJN4xCWtKqa0PcvWH-5YuNds4lYcPpbE_aPmv32gcnVeO4PK3_TyrXVwwd6iFFYcerhErwBE85FTx5h31lqD1EGWM4e9xoebygiZc3JiQh11w4-PyeLsGNcjRzo3vAaeRGqbScQooTXborWwuQS5hByLGY1JFRB1Kyw0-YB3I08wF4CJrJQyVpW6mG8OxANU6kE68tl3oROKWbnnqju-mesmct1NP1TtCQsAl5pnEWY-Gbk0c4yOhVxGi1lglOWhu089leYG9oCj64a84iL9yacOEDVJno4Axc78LfFe04Cd3S-3uSgoB0W1ome5WAB0xOtSQvGDgiDiLyFD8sfZ9OiFpBksvbuZlzDxCub7ELeSAS3ErDnqpb7VZF6-RWRXjErV1HQA0nKaDFSWdfqkA13fSTpJFDCUsgXe1mawqsJnWh_jXZOFQ8FYwy2ikoL8XVyqsytKbjRlsiyqWy1au2ypC7ZRlgK4aACFz7z2nK_1EdLqsHG6Qxz1LHuBhiJwOKkm86-weIstBtWbliuMNw1R61YqwWYiAlCR-HPFpBLSH1EbNss8FZr0LuilML1gMIWmoNPvYcqL9hqjvNLrWyuQs4UDsL2K_X7lJeQdxtUattDWMO5M4i9pvGCRaTGMu23nHidvcw5a3Bwb2G00ZDEzpuYKb8CTVfq52-qEeNXcmhE7GqkkLy786Z_wtyJwGjJMpSNRWcZbxGHBMzpzFWSyGGRJJAAEnD9T1G-bLRKP26IYwtcObjW4XqN_X5iXoaxxueSv3ymrBQaJ7jZJPJINGHHzEV4a9Ftlyqcw7kKVN9ODO6uRldz8c_RrkaZYh4pIz9SrJ4oY4CzP-HZJmBroWByBbCPF42flB4minUECShDF0TcsbIRkB02VgSJlAyxUdNM0N7Q1nBTVNhC1qcqxzndSCwcxo9QyrRXmwSwpSCVa_9-AmljEC1Nquw2bipEws7I1PDr4mQZp22eEqfDtm5qAMbqzlqsAKLOUOYVXI-esITcrcBgasqXdJQZXx1yOdIbagq_BKGOFnCXUW885XIzkMfAdkYmEE72Bzj2ND5aIVX9RGS1atm1A4fQkistptBO3jf-vEE3WTjsqeq4PSVJzrJcdIMKFOrhjWyIwZ7EjvDb3INqVmKrJwmWKMKksqJk9JFJu3TuERR4Su9XbV4SI3ZoWZLZrFBjVVUohcbEItDyzR2VmbHYy1kVdCiX7a4z4xWGFFsGSz658N2BqaDscYv74eq5jc2y_b5rQbtYDM_3rKQaebIQefyEJaAVagymfc0FVVUZskQC56scKgjK7MqDbacRqZTfxc3beRxZgdP1eJlisRRv9XmqHcy73X9qw3Of-L-_LzMUr9LJCcYYeG9q1ja3TjtW_87IExdUHD2PoZvzgXfZSeXgiTRUB11OBvabxb9bV-3FCIQ2PjeQiyudrj9uFFF89XFR0wkrncQ36trxjlXTTgJJaT35toxF0a0o_LOVOprwReciySNYEkypt7_LyOMyp1q_Etvc64JRVeLNX9SCWb4qO5HYHm9vzcjAyZzFkpIoYhxV66GdkErN9zYqx7nKUChMDZfisTA8Ef53nMcaeVibDIh3eVLq9pSJLgJwIfuxUWn0wgksivduba-5NepBq44f-h_f7jXDx_WUm7E783m09PT2YbINV_CM2VwFvK4uUEQ6vRR7xw-KrbNAf67Wg30P82oWXDqm1tYYRKkqXTXZirj1MNXjgu4GlMvix_adLXNyHdFM5kqe_7lPP5b26oci9kuJ2STB0GN5UHp5CHBFnRI0RupntNFZBXhX8U2rj-WGJTcyeq5SIpMgLn8-AlkwxP9Wskx2ydDaCXK45nbz3ix1TJkQWv2RDbBYLETgrDA-CfoIgrZmmA0rdDXsLYbrJrqiuMc9VTomC0nlLoCJmtCbjBRH4OOk0rtYyp1_Nzr5oT2fwQ791Oy5yet5-9Nn3w6EYE7wL5B1hV0JJN6PnJOpN8t41vVy9Rn3PGfRS0feed-udDyy7zz0-FxcWxdtsfSy9Nwp7rT9dDHowZ2TomJdoHZtdUM33Eve-VX1wfkNCVdAuFlZ9fbrW2PuPf8ZlLHL3079bPs3L_se-R0y9v5HZeEOHch8lD7Hc2PYyT9o9DzyEr_MLwjXVxLssI6zhp3Ug_PPeBu3K0TqF0orO71LBfu8fQxp-Pgp5Z_GM69vdX1scZlvvgn-QmVBnHGjqxt_Wa-h9R7Yb0J1Zd6PFnS1ZsrutefKR8u9vTnym_v9CCBeDcWV1yIk7SvP7w-CTBfZB8lmzISwpqzCNKyJvnHz8Xd4ufyd0TH6NWNVnEdWIA6Dpji24UC062GvPzuo6RfcQSVR6PffP1J-_8BFRz-9w==
```

**Comment by Peechey** [comment]
Are you doing Ctrl-C or Ctrl-Alt-C? Just tested live PoB, live game and I get the same behavior you're saying for Ctrl-Alt-C but Ctrl-C is importing fine.

**Comment by ThirteenEra** [comment]
Yes i am doing ctrl+alt+c, as it captures more data. Im used to ctrl+alt+c for stuff like Craft of Exile etc.

Are you saying POB cant parse ctrl+alt+c correctly, but can do ctrl+c?

**Comment by Peechey** [comment]
Yes, PoB only supports Ctrl+C.
