### ISSUE TITLE
Galvanic Field should not benefit from Area Damage

### ISSUE THREAD

**Issue by zuhukanah** [PathOfBuildingCommunity/PathOfBuilding#4953]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Galvanic Field should not be showing damage increases/decreases from Area Damage effects (Blast Radius, Concentrated Effect, etc.) as it does not deal area damage (similarly to Orb of Storms, it is affected by area changes but not area damage changes)

### What is the actual behaviour/value?

Allocating area damage nodes or slotting Concentrated Effect with Galvanic Field shows an increase in its damage.

### How to reproduce the issue

Select Galvanic Field as main skill
Select an area damage node or support it with Concentrated Effect

### Character build code

```shell
https://pastebin.com/AYPXJRfv
```

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4978
