### ISSUE TITLE
Pious path and zealoth oath math order in PoB is probably broken

### ISSUE THREAD

**Issue by Albulinek** [PathOfBuildingCommunity/PathOfBuilding#4956]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Zealoth's oath changes  life regen to ES regen. Then Pious path have 0 life to convert and add to ES regen. (dev confirmed, also wiki: https://devtrackers.gg/pathofexile/p/de4096e7-game-mechanics-q-amp-a-answers-part-2)

When I select/unselect Zealoth oath, it actively changes ES regen. 
This makes me believe the order which are keystone/ascendancy applied is wrong.

### What is the actual behaviour/value?

Zealoth's oath is applied before Pious ascendancy, changing life regen to ES regen, correcting all the regen math this way.

### How to reproduce the issue

Select Zealoth's oath keystone
Select Inquisitor ascendancy - travel towards pious path
Add some source of regen to observe changes - eg. vitality

### Character build code

```shell
https://pastebin.com/Ur0sBTYQ
```

**Comment by QuickStick123** [comment]
Pious path converts all life regen to energy shield regeneration before life recovery rate is applied as a lump some flat. 
Whereas zealot's oath converts flat life -> flat energy and percent -> percent based on the new energy shield pool.

This means their conversion to energy shield results in different numbers exspecially when most of your regen is coming from percent sources.
