### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by xondoi** [PathOfBuildingCommunity/PathOfBuilding#4958]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

No flickering

### What is the actual behaviour/value?

After installation and opening of the app, my Dell XPS 17 started to flicker even after closing the app. I have windows 11.

### How to reproduce the issue

Install app
Launch

### Character build code

```shell
No build code
```

**Comment by QuickStick123** [comment]
Try windows 95 compatibility mode or https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4947#issuecomment-1221418995

If need of those work I recommmend you reinstall your graphic drivers.
