### ISSUE TITLE
Incorrect Resistance Values on the Quick view but correct on on the Calc view

### ISSUE THREAD

**Issue by Serverfrog** [PathOfBuildingCommunity/PathOfBuilding#4970]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The Resistance values on the Calc view and on the Quick view should be the same

### What is the actual behaviour/value?

They are extremly different:
Calculated Max is 70% where quick view is 75% (or >10000% uncapped)

### How to reproduce the issue

Import this Build: https://pobb.in/X6VN8PHM5IsH
that should be it

### Character build code

```shell
https://pobb.in/X6VN8PHM5IsH
```

### Screenshots

![image](https://user-images.githubusercontent.com/1306404/186004124-7c3063ff-80e8-478d-9753-8fefa54e6387.png)

PS: i could also be a dumb beginner and dont understand what exactly is causing this, would be nice to point me then the way and just close this ticket ;)

**Comment by QuickStick123** [comment]
Those are your minions resistances as you have "Show Minion Stats" Ticked
![image](https://user-images.githubusercontent.com/31533893/186038362-5ad32b7c-7613-4a6f-9ba1-309314cdf928.png)
