### ISSUE TITLE
Viridian Grand Spectrum Value is Incorrect

### ISSUE THREAD

**Issue by fate0521** [PathOfBuildingCommunity/PathOfBuilding#4971]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

The new viridian Grand Spectrum jewel should be 12% chance to avoid elemental ailments

### What is the actual behaviour/value?

In PoB the jewel is set to 15%

### How to reproduce the issue

Select the viridian grand spectrum jewel - current with ailment avoidance

### Character build code

```shell
N/A
```

**Comment by QuickStick123** [comment]
Fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4952

**Comment by fate0521** [comment]
Thanks!
