### ISSUE TITLE
Both Pantheon and Bandits are not shown

### ISSUE THREAD

**Issue by Saint473** [PathOfBuildingCommunity/PathOfBuilding#4972]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

As can be seen i can neither see nor interact with both the Pantheon and Bandit quest scrolllists for some reason.
![PoBBug](https://user-images.githubusercontent.com/62121375/186041131-3646f4e7-ada6-449a-b021-b4438bb7c2e6.png)
Also since i can't see others having posted anything about neither since poe patch 2.5

### What is the actual behaviour/value?

[here is my settings .xml file to compare if there is anything that is corrupted and i need to fix.]

.<?xml version="1.0" encoding="UTF-8"?>.
.<PathOfBuilding>.
.............<Mode mode="BUILD">
...................<Arg string="C:\Users\phini\Documents/Path of Building/Builds/Bow CoC 3.19.xml"/>
....................<Arg string="Bow CoC 3.19"/>
	</Mode>
	<Accounts lastAccountName="Shorei473" lastRealm="PC">
		<Account accountName="Shorei473"/>
	</Accounts>
	<SharedItems>
		<Item>
			Rarity: UNIQUE
Windripper
Imperial Bow
Variant: Pre 2.0.0
Variant: Pre 2.6.0
Variant: Pre 3.0.0
Variant: Pre 3.5.0
Variant: Current
Selected Variant: 5
Imperial Bow
Quality: 30
Sockets: W-W-W-W-W-W
LevelReq: 66
Implicits: 4
{crafted}Quality does not increase Physical Damage
{crafted}Grants 1% increased Elemental Damage per 2% Quality
{range:1}(20-24)% increased Elemental Damage with Attack Skills
Socketed Gems are Supported by Level 10 Onslaught
{variant:1,2,3,4}{range:0.5}Adds (32-40) to (48-60) Cold Damage
{variant:5}{range:1}Adds (48-60) to (72-90) Cold Damage
{variant:1,2,3,4}{range:0.5}Adds 1 to (80-100) Lightning Damage
{variant:5}{range:1}Adds 1 to (120-150) Lightning Damage
{range:1}(10-15)% increased Attack Speed
{variant:1}{range:0.5}(80-100)% increased Critical Strike Chance
{variant:2,3,4}{range:0.5}(60-80)% increased Critical Strike Chance
{variant:5}{range:1}(30-40)% increased Critical Strike Chance
{variant:1}25% increased Quantity of Items Dropped by Slain Frozen enemies
{variant:2,3,4,5}15% increased Quantity of Items Dropped by Slain Frozen Enemies
{variant:1}50% increased Rarity of Items Dropped by Slain Shocked enemies
{variant:2,3,4,5}30% increased Rarity of Items Dropped by Slain Shocked Enemies
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Voices
Large Cluster Jewel
League: Delirium
CatalystQuality: 20
Variant: Adds 1 Small Passive Skill
Variant: Adds 3 Small Passive Skills
Variant: Adds 5 Small Passive Skills
Variant: Adds 7 Small Passive Skills
Selected Variant: 1
Implicits: 0
Adds 3 Jewel Socket Passive Skills
{variant:1}Adds 1 Small Passive Skill which grants nothing
{variant:2}Adds 3 Small Passive Skills which grant nothing
{variant:3}Adds 5 Small Passive Skills which grant nothing
{variant:4}Adds 7 Small Passive Skills which grant nothing
		</Item>
		<Item>
			Rarity: UNIQUE
Inspired Learning
Crimson Jewel
CatalystQuality: 20
Radius: Small
Implicits: 1
1% reduced Reservation of Skills
With 4 Notables Allocated in Radius, When you Kill a Rare monster, you gain 1 of its Modifiers for 20 seconds
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Thread of Hope
Crimson Jewel
CatalystQuality: 20
Variant: Small Ring
Variant: Medium Ring
Variant: Large Ring
Variant: Very Large Ring
Selected Variant: 4
Radius: Variable
Implicits: 1
1% reduced Mana Reserved
{variant:1}Only affects Passives in Small Ring
{variant:2}Only affects Passives in Medium Ring
{variant:3}Only affects Passives in Large Ring
{variant:4}Only affects Passives in Very Large Ring
Passives in Radius can be Allocated without being connected to your tree
{range:0}-(20-10)% to all Elemental Resistances
Corrupted
		</Item>
		<Item>
			Rarity: MAGIC
Ample Silver Flask of Warding
Crafted: true
Prefix: {range:1}FlaskExtraCharges1
Suffix: {range:0.5}FlaskCurseImmunity1
CatalystQuality: 20
Quality: 20
LevelReq: 22
Implicits: 0
+20 to Maximum Charges
Immune to Curses during Flask effect
Removes Curses on use
		</Item>
		<Item>
			Rarity: MAGIC
Alchemist&apos;s Sulphur Flask of Staunching
Crafted: true
Prefix: {range:0.5}FlaskEffectReducedDuration1
Suffix: {range:0.5}FlaskRemovesBleeding1
Quality: 20
LevelReq: 35
Implicits: 1
Creates Consecrated Ground on Use
Immunity to Bleeding during Flask effect
Removes Bleeding on use
25% increased effect
33% reduced Duration
		</Item>
		<Item>
			Rarity: MAGIC
Alchemist&apos;s Stibnite Flask of Reflexes
Crafted: true
Prefix: {range:0.5}FlaskEffectReducedDuration1
Suffix: {range:1}FlaskBuffEvasionWhileHealing
Quality: 20
LevelReq: 16
Implicits: 1
Creates a Smoke Cloud on Use
100% increased Evasion Rating during Flask effect
25% increased effect
33% reduced Duration
		</Item>
		<Item>
			Rarity: MAGIC
Alchemist&apos;s Jade Flask of Staunching
Crafted: true
Prefix: {range:0.5}FlaskEffectReducedDuration1
Suffix: {range:0.5}FlaskRemovesBleeding1
Quality: 20
LevelReq: 27
Implicits: 0
Immunity to Bleeding during Flask effect
Removes Bleeding on use
25% increased effect
33% reduced Duration
		</Item>
		<Item>
			Rarity: MAGIC
Alchemist&apos;s Granite Flask of Iron Skin
Crafted: true
Prefix: {range:0.5}FlaskEffectReducedDuration1
Suffix: {range:1}FlaskBuffArmourWhileHealing1
Quality: 20
LevelReq: 27
Implicits: 0
100% increased Armour during Flask effect
25% increased effect
33% reduced Duration
		</Item>
		<Item>
			Rarity: MAGIC
Alchemist&apos;s Quicksilver Flask of Adrenaline
Crafted: true
Prefix: {range:0.5}FlaskEffectReducedDuration1
Suffix: {range:1}FlaskBuffMovementSpeedWhileHealing
Quality: 20
LevelReq: 16
Implicits: 0
30% increased Movement Speed during Flask effect
25% increased effect
33% reduced Duration
		</Item>
		<Item>
			Rarity: MAGIC
Ample Diamond Flask of Acceleration
Crafted: true
Prefix: {range:1}FlaskExtraCharges1
Suffix: {range:1}FlaskBuffAttackSpeedWhileHealing1
Quality: 20
LevelReq: 27
Implicits: 0
+20 to Maximum Charges
12% increased Attack Speed during Flask effect
		</Item>
		<Item>
			Rarity: RARE
New Item
Small Cluster Jewel
Crafted: true
Prefix: {range:0.5}AfflictionNotableFettle
Prefix: {range:1}AfflictionJewelSmallPassivesGrantLifeSmall5_
Suffix: {range:0.5}AfflictionJewelSmallPassivesGrantAttributesSmall5
Suffix: {range:1}AfflictionJewelSmallPassivesGrantStrSmall5
Cluster Jewel Skill: affliction_maximum_life
Cluster Jewel Node Count: 3
Quality: 0
LevelReq: 67
Implicits: 2
{crafted}Adds 3 Passive Skills
{crafted}Added Small Passive Skills grant: 4% increased maximum Life
Added Small Passive Skills also grant: +6 to All Attributes
Added Small Passive Skills also grant: +16 to Maximum Life
Added Small Passive Skills also grant: +14 to Strength
1 Added Passive Skill is Fettle
		</Item>
		<Item>
			Rarity: UNIQUE
Storm Secret
Topaz Ring
LevelReq: 56
Implicits: 1
{range:1}+(20-30)% to Lightning Resistance
{range:1}+(20-30) to Intelligence
{range:1}(20-30)% increased Lightning Damage
{range:1}(10-15)% chance to Shock
Herald of Thunder also creates a storm when you Shock an Enemy
{range:1}Herald of Thunder&apos;s Storms Hit Enemies with (30-50)% increased Frequency
Take 250 Lightning Damage when Herald of Thunder Hits an Enemy
		</Item>
		<Item>
			Rarity: UNIQUE
Indigon
Hubris Circlet
Shaper Item
Variant: Pre 3.5.0
Variant: Current
Selected Variant: 2
Quality: 20
Sockets: B-B-B-B
LevelReq: 69
Implicits: 0
{range:1}(150-180)% increased Energy Shield
{range:1}(6-10)% increased maximum Mana
Recover (8-10)% of maximum Life when you use a Mana Flask
Non-instant Mana recovery from Flasks is also recovered as Life
{range:1}(50-60)% increased Mana Cost of Skills for each 200 total Mana you have Spent Recently
{variant:1}{range:0.5}(50-60)% increased Spell Damage for each 200 total Mana you have Spent Recently, up to 2000%
{variant:2}{range:1}(20-25)% increased Spell Damage for each 200 total Mana you have Spent Recently, up to 2000%
		</Item>
		<Item>
			Rarity: UNIQUE
Conqueror&apos;s Efficiency
Crimson Jewel
CatalystQuality: 20
Limited to: 1
Implicits: 0
3% reduced Mana Cost of Skills
4% increased Skill Effect Duration
2% reduced Mana Reserved
		</Item>
		<Item>
			Rarity: UNIQUE
Grand Spectrum
Crimson Jewel
CatalystQuality: 20
Variant: Pre 3.0.0
Variant: Pre 3.10.0
Variant: Current
Selected Variant: 3
Limited to: 3
Implicits: 0
{variant:1}Gain 75 Armour per Grand Spectrum
{variant:2}Gain 200 Armour per Grand Spectrum
{variant:3}+7% to all Elemental Resistances per Grand Spectrum
		</Item>
		<Item>
			Rarity: UNIQUE
Assailum
Sinner Tricorne
Quality: 20
Sockets: G-G-G-G
LevelReq: 64
Implicits: 0
Grants Level 20 Snipe Skill
Socketed Non-Channelling Bow Skills are Triggered by Snipe
Socketed Triggered Bow Skills deal 33% less Damage
{range:0.5}+(350-500) to Accuracy Rating
{range:0.5}+(350-500) to Evasion Rating
{range:0.5}(7-10)% chance to Dodge Attack Hits while Channelling
{range:0.5}(7-10)% chance to Dodge Spell Hits while Channelling
		</Item>
		<Item>
			Rarity: UNIQUE
Demigod&apos;s Dominance
Golden Mantle
Quality: 20
Sockets: G-G-G-G-G-G
LevelReq: 20
Implicits: 1
{range:1}+(15-25)% to all Elemental Resistances
+1 to Level of Socketed Gems
{range:1}+(30-50) to all Attributes
		</Item>
		<Item>
			Rarity: UNIQUE
Demigod&apos;s Presence
Gold Amulet
LevelReq: 8
Implicits: 0
{range:1}(12-20)% increased Rarity of Items found
+20% to all Elemental Resistances
20% increased Character Size
		</Item>
		<Item>
			Rarity: UNIQUE
Demigod&apos;s Immortality
Golden Wreath
Quality: 20
Sockets: G-G-G-G
LevelReq: 12
Implicits: 1
{range:1}+(8-16)% to all Elemental Resistances
+29 to all Attributes
10% increased Character Size
Golden Visage
		</Item>
		<Item>
			Rarity: UNIQUE
Demigod&apos;s Eye
Golden Hoop
LevelReq: 12
Implicits: 1
{range:1}+(8-12) to all Attributes
{range:1}(16-24)% increased Rarity of Items found
{range:1}(30-40)% increased Mana Regeneration Rate
3% increased Character Size
		</Item>
		<Item>
			Rarity: UNIQUE
Demigod&apos;s Bounty
Golden Obi
Implicits: 1
{range:1}(20-30)% increased Rarity of Items found
{range:1}+(16-24)% to all Elemental Resistances
10% increased Character Size
		</Item>
		<Item>
			Rarity: UNIQUE
Inspired Learning
Crimson Jewel
Radius: Small
Implicits: 0
With 4 Notables Allocated in Radius, When you Kill a Rare monster, you gain 1 of its Modifiers for 20 seconds
		</Item>
		<Item>
			Rarity: UNIQUE
Martyr of Innocence
Highborn Staff
Variant: Pre 3.5.0
Variant: Current
Selected Variant: 2
Has Variants: 1
Selected Variants: 2
Quality: 20
Sockets: B-B-B-B-B-B
LevelReq: 52
Implicits: 1
18% Chance to Block Attack Damage while wielding a Staff
{range:1}(12-16)% Chance to Block Attack Damage while wielding a Staff
{range:1}Adds (350-400) to (500-600) Fire Damage
{variant:1}{range:0.5}Adds (130-150) to (200-250) Fire Damage to Spells
{variant:2}{range:1}Adds (230-250) to (300-350) Fire Damage to Spells
Grants level 15 Vengeance Skill
{variant:1}100% increased Fire Damage if you have been Hit Recently
{variant:2}100% increased Fire Damage
Immune to Freeze and Chill while Ignited
Damage Penetrates 15% of Fire Resistance if you have Blocked Recently
		</Item>
		<Item>
			Rarity: UNIQUE
Yriel&apos;s Fostering
Exquisite Leather
Variant: Rhoa
Variant: Snake
Variant: Ursa
Selected Variant: 3
Has Variants: 1
Selected Variants: 3
Quality: 20
Sockets: G-G-G-G-G-G
LevelReq: 62
Implicits: 1
{range:1}(40-50)% increased Damage
{variant:1}Grants level 20 Summon Bestial Rhoa Skill
{variant:2}Grants level 20 Summon Bestial Snake Skill
{variant:3}Grants level 20 Summon Bestial Ursa Skill
{range:1}+(300-400) to Accuracy Rating
{range:1}(130-150)% increased Evasion Rating
{range:1}+(90-100) to maximum Life
{range:1}Projectile Attack Skills have (40-60)% increased Critical Strike Chance
{variant:1}Projectiles from Attacks have 20% chance to Maim on Hit while you have a Bestial Minion
{variant:2}Projectiles from Attacks have 20% chance to Poison on Hit while you have a Bestial Minion
{variant:3}Projectiles from Attacks have 20% chance to inflict Bleeding on Hit while you have a Bestial Minion
{variant:1}{range:0.5}(10-15)% increased Attack and Movement Speed while you have a Bestial Minion
{variant:2}{range:0.5}Adds (13-19)-(23-29) Chaos Damage to Attacks while you have a Bestial Minion
{variant:3}{range:1}Adds (11-16)-(21-25) Physical Damage to Attacks while you have a Bestial Minion
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Asenath&apos;s Chant
Iron Circlet
Variant: Pre 3.9.0
Variant: Current
Selected Variant: 2
Quality: 20
Sockets: B-B-B-B
LevelReq: 45
Implicits: 0
{variant:1}25% chance to Trigger a Socketed Spell when you Attack with a Bow
{variant:2}Trigger a Socketed Spell when you Attack with a Bow
{range:1}(10-15)% increased Attack Speed
{range:1}(10-15)% increased Cast Speed
{range:1}+(100-120) to maximum Energy Shield
{range:1}(30-40)% increased Stun and Block Recovery
30% increased Mana Regeneration Rate
5% increased Movement Speed
		</Item>
		<Item>
			Rarity: UNIQUE
Paradoxica
Vaal Rapier
Quality: 30
Sockets: G-G-G
LevelReq: 66
Implicits: 2
Skills fire an additional Projectile
{range:1}(5-7)% increased Attack Speed
+25% to Global Critical Strike Multiplier
Attacks with this Weapon deal Double Damage
20% increased Damage
43% increased Damage while Leeching
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Varunastra
Vaal Blade
League: Perandus
Variant: Pre 2.6.0
Variant: Current
Selected Variant: 2
Quality: 20
Sockets: G-G-G
LevelReq: 64
Implicits: 2
{variant:1}18% increased Accuracy Rating
{variant:2}+460 to Accuracy Rating
{range:1}(40-60)% increased Physical Damage
{range:1}Adds (30-45) to (80-100) Physical Damage
{range:1}+(2-3) Mana gained for each Enemy hit by Attacks
Counts as all One Handed Melee Weapon Types
		</Item>
		<Item>
			Rarity: UNIQUE
Headhunter
Leather Belt
League: Nemesis
Variant: Pre 3.0.0
Variant: Current
Selected Variant: 2
LevelReq: 40
Implicits: 1
{range:1}+(25-40) to maximum Life
{range:1}+(40-55) to Strength
{range:1}+(40-55) to Dexterity
{range:1}+(50-60) to maximum Life
30% increased Damage
(Hits, Rares)
When you Kill a Rare monster, you gain its mods for 20 seconds
		</Item>
		<Item>
			Rarity: UNIQUE
Pure Talent
Viridian Jewel
Limited to: 1
Implicits: 2
{range:1}(4-5)% increased Damage
1% reduced Mana Reserved
While your Passive Skill Tree connects to a class&apos; Starting location, you gain:
Marauder: Melee Skills have 15% increased Area of Effect
Duelist: 1% of Attack Damage Leeched as Life
Ranger: 7% increased Movement Speed
Shadow: +0.5 to Critical Strike Chance
Witch: 0.5% of Maximum Mana Regenerated per second
Templar: Damage Penetrates 5% Elemental Resistances
Scion: +25 to All Attributes
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Might of the Meek
Crimson Jewel
Radius: Large
Implicits: 0
50% increased Effect of non-Keystone Passive Skills in Radius
Notable Passive Skills in Radius grant nothing
		</Item>
		<Item>
			Rarity: UNIQUE
Intuitive Leap
Viridian Jewel
Radius: Small
Implicits: 0
Passives in Radius can be Allocated without being connected to your tree
		</Item>
		<Item>
			Rarity: UNIQUE
Unnatural Instinct
Viridian Jewel
Radius: Small
Limited to: 1
Implicits: 0
Allocated Small Passive Skills in Radius grant nothing
Grants all bonuses of Unallocated Small Passive Skills in Radius
		</Item>
		<Item>
			Rarity: UNIQUE
Blood of Corruption
Amber Amulet
LevelReq: 20
Implicits: 2
{range:1}(8-10)% increased Movement Speed
{range:1}(20-24)% increased Elemental Damage with Attack Skills
Grants level 10 Gluttony of Elements Skill
Adds 19-43 Chaos Damage to Attacks
{range:0}-(10-5)% to all Elemental Resistances
{range:1}+(17-29)% to Chaos Resistance
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Shackles of the Wretched
Chain Gloves
Variant: Pre 1.2.0
Variant: Current
Selected Variant: 2
Quality: 20
Sockets: B-B-B-B
LevelReq: 7
Implicits: 2
+1 to Level of Socketed Gems
+2 to Level of Socketed Curse Gems
{range:1}(40-60)% increased Stun Recovery
Curses in this item are reflected back to you
You cannot be Chilled for 3 seconds after being Chilled
You cannot be Frozen for 3 seconds after being Frozen
You cannot be Ignited for 3 seconds after being Ignited
{variant:1}You cannot be Shocked for 1 second after being Shocked
{variant:2}You cannot be Shocked for 3 seconds after being Shocked
You grant (4-6) Frenzy Charges to allies on Death
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Watcher&apos;s Eye
Prismatic Jewel
Unique ID: 841bbf1765e7edae2536649ccb03e3e6f2e977869dc26d1478ef9c30b2c53fb8
Item Level: 82
Limited to: 1
Implicits: 1
1% reduced Mana Reserved
6% increased maximum Energy Shield
6% increased maximum Life
6% increased maximum Mana
Damage Penetrates 15% Lightning Resistance while affected by Wrath
{range:1}(70-100)% increased Critical Strike Chance while affected by Wrath
{range:1}(100-120)% increased Critical Strike Chance against Enemies on Consecrated Ground while affected by Zealotry
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
The Pariah
Unset Ring
League: Warbands
Sockets: G
LevelReq: 60
Implicits: 1
Has 1 Socket
+2 to Level of Socketed Gems
{range:1}(5-10)% increased Attack and Cast Speed
+100 to Maximum Life per Red Socket
+100 to Maximum Energy Shield per Blue Socket
+100 to Maximum Mana per Green Socket
15% increased Item Quantity per White Socket
		</Item>
		<Item>
			Rarity: UNIQUE
Inpulsa&apos;s Broken Heart
Sadist Garb
Variant: Pre 3.5.0
Variant: Pre 3.7.0
Variant: Current
Selected Variant: 3
Quality: 20
Sockets: B-B-B-B-B-B
LevelReq: 68
Implicits: 1
{range:1}(40-50)% increased Damage
{range:1}+(60-80) to maximum Life
{range:1}(20-50)% increased Damage if you have Shocked an Enemy Recently
{variant:1,2}{range:0.5}(25-40)% increased Effect of Shock
{variant:3}{range:1}(15-25)% increased Effect of Shock
Unaffected by Shock
{variant:1}Shocked Enemies you Kill Explode, dealing (5-10)% of
{variant:2,3}Shocked Enemies you Kill Explode, dealing 5% of
their Maximum Life as Lightning Damage which cannot Shock
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
The Tactician
Studded Belt
LevelReq: 48
Implicits: 2
{range:1}+(20-25)% to Critical Strike Multiplier during any Flask Effect
{range:1}(35-40)% increased Critical Strike Chance during any Flask Effect
{range:1}(25-40)% increased Global Physical Damage
{range:1}+(40-50) to Strength
{range:1}+(40-50) to Intelligence
50% increased Flask Charges gained
{range:1}+(20-25)% to all Elemental Resistances while you have at least 200 Strength
{range:1}(50-60)% increased Critical Strike Chance while you have at least 200 Intelligence
Corrupted
		</Item>
		<Item>
			Rarity: UNIQUE
Death&apos;s Oath
Astral Plate
Variant: Pre 2.0.0
Variant: Pre 3.0.0
Variant: Current
Selected Variant: 3
Quality: 20
Sockets: R-R-R-R-R-R
LevelReq: 62
Implicits: 1
{range:0.5}+(8-12)% to all Elemental Resistances
{variant:3}Grants level 20 Death Aura Skill
{range:0.5}+(40-50) to all Attributes
{variant:3}{range:0.5}+(60-70) to maximum Life
{range:0.5}(10-15)% increased Attack Speed
{range:0.5}(180-220)% increased Armour
{variant:1}5% of Physical Attack Damage Leeched as Life
{variant:2}1% of Physical Attack Damage Leeched as Life
{variant:3}1% of Attack Damage Leeched as Life
{variant:1,2}Deals 450 Chaos Damage per second to nearby Enemies
{variant:1}You take 450 Chaos Damage per second for 10 seconds on Kill
{variant:2,3}You take 450 Chaos Damage per second for 3 seconds on Kill
Gore Footprints
		</Item>
		<Item>
			Rarity: UNIQUE
Faminebind
Rustic Sash
League: Talisman Standard, Talisman Hardcore
LevelReq: 18
Implicits: 1
{range:0.5}(12-24)% increased Physical Damage
{range:0.5}+(20-30)% to Cold Resistance
60% increased Flask effect duration
Deals 50 Chaos Damage per second to nearby Enemies
20% increased Projectile Damage
30% reduced Flask Charges gained while using a Flask
		</Item>
		<Item>
			Rarity: UNIQUE
Darkness Enthroned
Stygian Vise
League: Abyss
Sockets: A A
Implicits: 1
Has 1 Abyssal Socket
Has 1 Abyssal Socket
50% increased Effect of Socketed Jewels
		</Item>
		<Item>
			Rarity: UNIQUE
Umbilicus Immortalis
Leather Belt
Unique ID: cb46262628318672794dd97ce838c0d7b895d66aa3fcbf682ac688a610387dbf
Item Level: 72
LevelReq: 30
Implicits: 1
+39 to maximum Life
11% increased maximum Life
Regenerate 2% of Life per second
Flasks do not apply to you
Flasks apply to your Raised Zombies and Spectres
		</Item>
		<Item>
			Rarity: UNIQUE
The Flow Untethered
Cloth Belt
League: Harbinger
LevelReq: 60
Implicits: 1
{range:1}(15-25)% increased Stun and Block Recovery
Grants Summon Harbinger of Time Skill
{range:1}(10-15)% increased Attack and Cast Speed
{range:1}(15-20)% increased Life Recovery rate
{range:1}(15-20)% increased Energy Shield Recovery rate
{range:1}(15-20)% increased Cooldown Recovery Speed
Debuffs on you expire 20% faster
		</Item>
		<Item>
			Rarity: UNIQUE
Tombfist
Steelscale Gauntlets
League: Abyss
Variant: One Abyssal Socket
Variant: Two Abyssal Sockets
Selected Variant: 2
Quality: 20
Sockets: G-G A A
LevelReq: 36
Implicits: 1
{crafted}Trigger Commandment of Reflection when Hit
{variant:1}Has 1 Abyssal Socket
{variant:2}Has 2 Abyssal Sockets
{range:1}(6-10)% increased Attack Speed
{range:1}(4-6)% increased maximum Life
With a Murderous Eye Jewel Socketed, Intimidate Enemies for 4 seconds on Hit with Attacks
With a Searching Eye Jewel Socketed, Maim Enemies for 4 seconds on Hit with Attacks
		</Item>
		<Item>
			Rarity: UNIQUE
Bottled Faith
Sulphur Flask
League: Synthesis
Quality: 20
LevelReq: 35
Implicits: 0
Creates Consecrated Ground on Use
{range:1}(30-50)% increased Duration
Consecrated Ground created by this Flask has Tripled Radius
{range:1}+(1.00-2.00)% to Critical Strike Chance against Enemies on Consecrated Ground during Effect
{range:1}Consecrated Ground created during Effect applies (7-10)% increased Damage taken to Enemies
		</Item>
		<Item>
			Rarity: UNIQUE
The Savior
Legion Sword
Quality: 20
Sockets: R-R-R
LevelReq: 62
Implicits: 1
40% increased Global Accuracy Rating
Triggers Level 20 Reflection when Equipped
{range:1}(40-50)% increased Physical Damage
{range:1}Adds (16-22) to (40-45) Physical Damage
{range:1}(8-12)% increased Attack Speed
{range:1}(8-12)% increased Critical Strike Chance
		</Item>
		<Item>
			Rarity: UNIQUE
Windripper
Imperial Bow
Variant: Pre 2.0.0
Variant: Pre 2.6.0
Variant: Pre 3.0.0
Variant: Pre 3.5.0
Variant: Current
Selected Variant: 1
Quality: 28
Sockets: G-G-G-G-G-G
LevelReq: 66
Implicits: 1
Socketed Gems are supported by Level 10 Faster Projectiles
{variant:1,2,3,4}{range:1}Adds (32-40) to (48-60) Cold Damage
{variant:5}{range:0.5}Adds (48-60) to (72-90) Cold Damage
{variant:1,2,3,4}{range:1}Adds 1 to (80-100) Lightning Damage
{variant:5}{range:0.5}Adds 1 to (120-150) Lightning Damage
{range:1}(10-15)% increased Attack Speed
{variant:1}{range:1}(80-100)% increased Critical Strike Chance
{variant:2,3,4}{range:0.5}(60-80)% increased Critical Strike Chance
{variant:5}{range:0.5}(30-40)% increased Critical Strike Chance
{variant:1}25% increased Quantity of Items Dropped by Slain Frozen enemies
{variant:2,3,4,5}15% increased Quantity of Items Dropped by Slain Frozen Enemies
{variant:1}50% increased Rarity of Items Dropped by Slain Shocked enemies
{variant:2,3,4,5}30% increased Rarity of Items Dropped by Slain Shocked Enemies
Corrupted
		</Item>
	</SharedItems>
	<Misc betaTest="false" connectionProtocol="0" thousandsSeparator="," showThousandsSeparators="true" slotOnlyTooltips="true" invertSliderScrollDirection="false" showTitlebarName="true" defaultCharLevel="100" nodePowerTheme="RED/BLUE" buildSortMode="CLASS" showWarnings="true" defaultItemAffixQuality="1" defaultGemQuality="23" decimalSeparator="."/>
</PathOfBuilding>

### How to reproduce the issue

it's occuring at all times upon start up of program now, again not sure what is causing it.

### Character build code

```shell
here is a pastebin of my current build in progress, let's see if mayhaps another could recreate it with this if all else fails.
https://pastebin.com/vGYA0MWC
```

### Screenshots

this behaviour is also not excibited only on that build btw here is a photo
![pobbug2](https://user-images.githubusercontent.com/62121375/186042302-e0bf2c3e-285f-4c2d-b664-fc85255ead15.png)
and here is a pob link https://pastebin.com/bYsPv5Fy

**Comment by QuickStick123** [comment]
They were moved to the top left of the configuration panel
![image](https://user-images.githubusercontent.com/31533893/186042602-84850f9b-eea3-4fed-800b-3bbf0c4a204d.png)
