### ISSUE TITLE
Determination aura shows incorrect reservation

### ISSUE THREAD

**Issue by Chist-Sergey** [PathOfBuildingCommunity/PathOfBuilding#4974]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

In PoB, Determination's mana reservation value should be 40%, as shown in-game:
![image](https://user-images.githubusercontent.com/73827362/186054788-26d0bf9b-655c-4c0f-a48c-924537f6d355.png)

### What is the actual behaviour/value?

It shows that Determination have 50% mana reservation value.
![image](https://user-images.githubusercontent.com/73827362/186054948-36a9b921-a7bb-4169-8b23-16f367770de7.png)

### How to reproduce the issue

1. Select Determination as main skill.
2. Hover your mouse over it.

### Character build code

```shell
https://pastebin.com/3G2D8edZ
```

**Comment by LocalIdentity** [comment]
Your Pastebin code does not work. Please export you build with pobb.in or poe.ninja

**Comment by QuickStick123** [comment]
The reservation on the gem will always display 50% as that is the base reservation ingame. We calculate and display reservation percentages after reservation efficiency in the calculations tab. Which should correspond with the ingame value of 40% on the tooltip.

**Comment by Chist-Sergey** [comment]
My bad. It seems that I forget about my Armour Mastery with Determination mana reservation efficiency.
At least I have learned that 25% of 50% is 10%.
Thank you for respond.

**Comment by Regisle** [comment]
> My bad. It seems that I forget about my Armour Mastery with Determination mana reservation efficiency. At least I have learned that 25% of 50% is 10%. Thank you for respond.

its 50/1.25 = 40, its not reduced reservation its reservation efficiency
