### ISSUE TITLE
Energy blade does not work on new pob/imported pobs

### ISSUE THREAD

**Issue by btsrkex** [PathOfBuildingCommunity/PathOfBuilding#4976]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Energy blade should feature, half your es and provide added damage.

### What is the actual behaviour/value?

Energy blade has no effect on imported pob and newly created pob, however, previously working pob (e.g. from 3.18)'s energy blade is working as intended.

### How to reproduce the issue

Simply drag a character from ninja with energy blade or create a pob and select energy blade.

### Character build code

```shell
https://pastebin.com/6YkY6uai
*The build is randomly imported from poe.ninja
```

### Screenshots

![image](https://user-images.githubusercontent.com/34084904/186092177-e7b7c44d-56fa-47e5-8a1d-71412e8b7212.png)
![image](https://user-images.githubusercontent.com/34084904/186092468-267e17f5-440c-408f-a917-6c2357cf29c3.png)

**Comment by QuickStick123** [comment]
There are two reasons for this first is that energy blade is not enabled and there is no weapon to convert to be a energy blade so it doesn't work. 
![image](https://user-images.githubusercontent.com/31533893/186093382-42084b91-8319-452d-8cdf-7a67b4bb8ad3.png)

**Comment by btsrkex** [comment]
https://pastebin.com/uKJ6taNi
*The working pob from 3.18, forgot to put inside

**Comment by btsrkex** [comment]
> There are two reasons for this first is that energy blade is not enabled and there is no weapon to convert to be a energy blade so it doesn't work. ![image](https://user-images.githubusercontent.com/31533893/186093382-42084b91-8319-452d-8cdf-7a67b4bb8ad3.png)

Oh, you are right. my bad.
