### ISSUE TITLE
Node Power by Full DPS shows nonsense results

### ISSUE THREAD

**Issue by Reithan** [PathOfBuildingCommunity/PathOfBuilding#4982]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When using Full DPS to color nodes, the results should show a list of Full DPS delta

### What is the actual behaviour/value?

The numbers seem almost random?
At first I thought it was just showing total Full DPS for each node, but the numbers also don't seem to add up.
For example: looking at Divine Wrath, it shows 991,516.6 for 2 pts, which it says is 508,817.7 per point, but that should be 495,758.3 if it's simply the total divided by 2?
Also, my current 991,5156.6 - my current Full DPS = 118,163.8, yet allocating Divine Wrath only shows an increase of 69,902.3

None of these numbers make sense, further, EVERY node on the tree is bright green, even though the power report shows a range of values.

### Character build code

```shell
https://poe.ninja/pob/EIm
```

### Screenshots

![image](https://user-images.githubusercontent.com/7475701/186324216-5a43df5e-aa66-44ea-8985-a56362eb551f.png)
![image](https://user-images.githubusercontent.com/7475701/186324242-4d49e27e-5171-4dac-83ec-aace02d76ad6.png)
![image](https://user-images.githubusercontent.com/7475701/186324276-fa12ce3c-f0d0-421f-a7dd-4c4ac3f254c9.png)
![image](https://user-images.githubusercontent.com/7475701/186324305-8b2feb34-39fe-4aeb-aebd-9e21167d64cd.png)

**Comment by Reithan** [comment]
Probably worth noting, Combined DPS and Total DPS are also both broken and show nothing but 0.0 for all nodes in the report with all nodes on tree showing as black (after taking multiple minutes to complete due to #3006 )

![image](https://user-images.githubusercontent.com/7475701/186325901-48f4ae60-a989-4904-8565-c38b814a99e6.png)

**Comment by Reithan** [comment]
After spending a bunch of time re-running power report with different settings, turning "Full DPS" off of a lot of my link setups eventually produced reasonable numbers. So there's something on one of my skill setups breaking this.

**Comment by Regisle** [comment]
> After spending a bunch of time re-running power report with different settings, turning "Full DPS" off of a lot of my link setups eventually produced reasonable numbers. So there's something on one of my skill setups breaking this.

question is why are you trying to see the dps of your auras that cannot deal damage, PoB has to do a full calculation for each of those which slows it down by the number of things in full dps (in this case 12 skills instead of 3 is 4 times slower) and seems to be the thing which causes power report to have issues

**Comment by Reithan** [comment]
Because I'm a silly end user that clicked on things and forgot about it...but everything broke, which probably is undesirable anyway?

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5317
