### ISSUE TITLE
 raise spectre add the Deadly Tarantula

### ISSUE THREAD

**Issue by hlfshy** [PathOfBuildingCommunity/PathOfBuilding#4987]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

3.19 Minions no longer have hidden penalties to Bleeding, Ignite, and Poison damage. Summon Reaper no longer has a hidden bonus to Bleeding damage that counteracted this penalty. As a result, minions now deal approximately twice as much Poison damage, three and a half times as much Ignite damage, and seven times as much Bleeding damage.
 Deadly Tarantula had nice Poison damage  ,many necs use it, add it  plz

### Describe the solution you'd like

![20220825113534](https://user-images.githubusercontent.com/21966050/186568860-c317f575-2996-4f7e-9205-b3194d3817c4.png)
raise spectre add the Deadly Tarantula

**Comment by LocalIdentity** [comment]
There are 2 mobs with the name Deadly Tarantula, which one is it?
https://poedb.tw/us/Deadly_Tarantula#DeadlyTarantulaSpiderThornViperStrikeFlickerStrikeWeaver
or
https://poedb.tw/us/Deadly_Tarantula#DeadlyTarantulaSpiderThornViperStrikeFlickerStrike?

**Comment by hlfshy** [comment]
I'm so sorry, I didn't know he had 2 versions which one is correct. All I know is that it appears in Jungle Valley Map BOSS room 
![name](https://user-images.githubusercontent.com/21966050/186582484-dd1eb552-570e-42fe-ac6e-93d414c95df7.png)
it's always magic and can't use desecrate skill spawn it

**Comment by LocalIdentity** [comment]
https://poedb.tw/us/Deadly_Tarantula#DeadlyTarantulaSpiderThornViperStrikeFlickerStrike
looks to be the correct version, as the other one is for the spiders in the Weavers chambers in act 2.
I'll look into adding it as a new spectre. Are they any good though?
