### ISSUE TITLE
`inf` instead of number in the "Effective Hit Pool" field when "Effective Hit Pool" is too high

### ISSUE THREAD

**Issue by p0lunin** [PathOfBuildingCommunity/PathOfBuilding#4993]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

With this build I expected to see numbers in the "Effective Hit Pool" field.

### What is the actual behaviour/value?

I see `inf`.

### How to reproduce the issue

Take the build and see in the "Effective Hit Pool" section. You can change shield back from the Aegis Aurora to the Dawnbreaker and numbers rendered as usual.

### Character build code

```shell
https://pastebin.com/VWkUnVAy
```

### Screenshots

![Анимация](https://user-images.githubusercontent.com/48922415/186946356-9629a6e5-90e7-4187-9b3f-839ec39ea0cd.gif)

**Comment by QuickStick123** [comment]
You build literally cannot die to these hits as you recover more than you recieve. There was a bug with recovery not being applied properly with the speedup function however which made the calculation slightly slower than it needed to be.

**Comment by QuickStick123** [comment]
You can disable recovery by enabling this if you were interested to see your effective health without aegies or setting it to high hit damage so aegies is less effective an mitigatating all of the incoming damage.
![image](https://user-images.githubusercontent.com/31533893/187007681-2f5a7ca7-a9a9-43ce-bb6f-95a18fda9877.png)
