### ISSUE TITLE
Lightning Conduit's damage scales with AoE damage modifiers

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#5010]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Lightning Conduit does not scale its damage with AoE damage modifiers; any changes to AoE damage (e.g. passives, conc. effect or intensify) should not increase the displayed damage values.

The wiki and in-game tooltip confirm this behavior.

### What is the actual behaviour/value?

The damage shown in the PoB tooltip increases with all AoE damage mods.

### How to reproduce the issue

Quick example:

1. Lightning conduit
2. Intensify
3. Select number of intensity stacks

### Character build code

```shell
n/a; global issue
```

**Comment by QuickStick123** [comment]
Fixed in dev https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4978

**Comment by Ydoum** [comment]
> Fixed in dev #4978

was looking at open issues, didn't find anything. but that's awesome, thanks for the info.

**Comment by horsepowerhsu** [comment]
> Fixed in dev #4978

Concentrated Effect Support can't either, plz fix.

**Comment by QuickStick123** [comment]
> Concentrated Effect Support can't either, plz fix.

This should be fixed in dev as well. The area is affected in dev but not damage.
