### ISSUE TITLE
Export "Find Timeless Jewel" results

### ISSUE THREAD

**Issue by Wyrade** [PathOfBuildingCommunity/PathOfBuilding#5013]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

After I search for what I want with "Find Timeless Jewel", there is still more than a hundred good results.
There is no way to check if a number is in those results except for checking one by one with my own eyes.

### Describe the solution you'd like

I'd like to be able to export/copy the results (to use in an excel for example) and/or be able to check if a number is in that list (with a search box that can filter the results for example).
This would help when I try to buy one, so I can check if it's in the list of good jewels for me.

### Additional context

(Thanks for the "Find Timeless Jewel" feature in general, it's awesome we can do this now!)

**Comment by chuson** [comment]
I see there's a task listed as done here but unsure what progress has been made. I want to echo support for this request in hopes it will be available in the near future. Just being able to copy and paste would be a huge improvement.
