### ISSUE TITLE
Save option for POESESSID

### ISSUE THREAD

**Issue by TeslaViktor** [PathOfBuildingCommunity/PathOfBuilding#5025]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

It's not a problem but if in settings will be an option to save POESESSID It'll be great bcz it resets very often and u should every time search it (or open the file where u save it) and put it in the build.

### Describe the solution you'd like

Described above.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5028
