### ISSUE TITLE
Spell supression raises even your non-spell hit survivability?

### ISSUE THREAD

**Issue by chengsta** [PathOfBuildingCommunity/PathOfBuilding#5030]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Max hit survivability to stay the same.  It's technically not an 'average hit survivability'

### What is the actual behaviour/value?

not sure why going from 93% spell supression to 100% literally doubles my max hit survivability.  how does that work?  i go from 44k to 88k with just 7% (probably the same for going from 99 to 100).  does that mean i magically can tank a 88k hit when before it was just 44k?  

I think we need to somehow add non-spell hits too.

### How to reproduce the issue

in pob, go from any % spell supression to 100% spell supression.

### Character build code

```shell
https://pastebin.com/DCe38dSk
```

**Comment by QuickStick123** [comment]
Spell suppression is only included in max hit if it certain but is included in eHP regardless. Max suppression causes you to take half the damage and so doubles your maximum hit. 
![image](https://user-images.githubusercontent.com/31533893/188314825-9667c5eb-ac4d-489f-87fe-3798b1a5c065.png)
![image](https://user-images.githubusercontent.com/31533893/188314844-c8335235-0ff6-4366-a64e-9f255849e96c.png)
