### ISSUE TITLE
Poison immunity from flasks is not counted in calcs

### ISSUE THREAD

**Issue by Aguinore** [PathOfBuildingCommunity/PathOfBuilding#5042]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I'm clicking my flask with "less duration, Immunity to poison during flask effect" mod, I expect to see in avoidance section of Calcs tab "Poison: 100%", just as I see for shock immunity

### What is the actual behaviour/value?

Poison avoidance ignore flask mods altogether

### How to reproduce the issue

1. add a flask to a new build with suffix (less duration/immunity to poison during flask effect)
2. check the flask as active
3. see no difference in Calcs tab
4. add another flask with suffix (less duration/immunity to shockduring flask effect)
5. check the other flask as active
6. see that your character is now 100% avoiding shock, but not poison still

### Character build code

```shell
https://pobb.in/cn8WTj7z7v56
```

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4906
