### ISSUE TITLE
Labyrinth enchant "X% increased Ice Spear Critical Strike Chance in second form" does not work

### ISSUE THREAD

**Issue by ShoHeedless** [PathOfBuildingCommunity/PathOfBuilding#5044]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When i have enchant "X% increased Ice Spear Critical Strike Chance in second form" i can't see increased critical damage second form in damage window

### What is the actual behaviour/value?

When i have enchant "X% increased Ice Spear Critical Strike Chance in second form" Pob display i the old critical value

### How to reproduce the issue

1 Select Ice Spear as main skill
2 Select skill option "Second form, one projectile" or "Second form, all projectile"
3 Create any helmet with "X% increased Ice Spear Critical Strike Chance in second form" enchant and equip it
4 Skill crit chance not increased

### Character build code

```shell
https://pastebin.com/vf5z2PCp
```

### Screenshots

![изображение_2022-09-06_160141408](https://user-images.githubusercontent.com/88490358/188618895-5f450682-98dd-460b-8500-c47d2ee261a8.png)

**Comment by Paliak** [comment]
It should work fine for "Second Form, 1 Projectile" but it does't work for the all projectiles option.

![obraz](https://user-images.githubusercontent.com/91493239/188640165-db70ae64-35dd-45dd-b653-b448bf8bcfe9.png)
