### ISSUE TITLE
Error while generating a timeless jewel

### ISSUE THREAD

**Issue by 33hig** [PathOfBuildingCommunity/PathOfBuilding#5053]
Hey I get an error when I try to generate a timeless jewel, I tried to uninstall and everything I could think of.

Here's the error I get if anyone knows how to solve it I would appreciate it.

![image](https://user-images.githubusercontent.com/84081774/188937480-4d915268-eb70-4196-b96e-fb0595e51d50.png)

**Comment by Paliak** [comment]
Does this happen with a specific build ? Can't replicate.

**Comment by 33hig** [comment]
> Does this happen with a specific build ? Can't replicate.

It happens on 2 different builds that uses the same spell, my profile is public with the name Zooryx, the character is AskipCbien, but I dont really think that it comes from this honestly.

**Comment by QuickStick123** [comment]
https://pobb.in/XUDithGoAQwV Brutral restriant with skitterbots causes it
![image](https://user-images.githubusercontent.com/31533893/189080177-c69ba746-9c10-42cc-91ac-eefe7032c062.png)

**Comment by 33hig** [comment]
Oh pretty weird interaction I guess, thanks a lot

**Comment by QuickStick123** [comment]
I am keeping this open so it gets fixed.

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5055
