### ISSUE TITLE
Application closes without errors after loading

### ISSUE THREAD

**Issue by Shirolicious** [PathOfBuildingCommunity/PathOfBuilding#5081]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I expect the program to start after opening pathofbuilding.exe

### What is the actual behaviour/value?

Program closes after loading (after the green background with loading stuff.

![image](https://user-images.githubusercontent.com/113630062/190474990-f59ba253-0506-4d56-9b62-e512eefb9446.png)
After that, the whole program closes and nothing is happening. 

### How to reproduce the issue

I just start the program, normally like always. Nothing more or less.

I did uninstall and install the latest version, just to be sure.

### Character build code

```shell
.
```

### Screenshots

![image](https://user-images.githubusercontent.com/113630062/190475083-d2d1ca58-ff03-4a82-b7ee-88710e3f012f.png)

**Comment by zao** [comment]
Please try the alternate ANGLE builds of SimpleGraphic that works around this problem as outlined in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087
You won't be able to use the updater while it's in use and it has some minor graphical glitches.

**Comment by Shirolicious** [comment]
Thank you Zao, that does seem to work indeed. But, I seem to not be able to update the program anymore.
As soon as the program starts there is the update button, but if I press that the same issue appears.

So while this did fix the issue temporarily.. I would like to give the feedback that its not a permanent fix.

**Comment by QuickStick123** [comment]
This is known you can still update then reapply the fix if we release an update.
Closing in favour of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736 see https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087 for tempoary fix.
