### ISSUE TITLE
Lioneye's Fall should not affect masteries

### ISSUE THREAD

**Issue by stanly0726** [PathOfBuildingCommunity/PathOfBuilding#5087]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

in game behavior for this situation is you still get 10% suppress by equipping one dagger and 20% for two, but not for bow

1. no weapon equipped, 73% suppress (sorry for the chinese, am on the garena server)
![no weapon](https://user-images.githubusercontent.com/37040069/190864708-46cb2a0a-08b5-46dd-85b9-94bcd28dbd1b.png)

2. one bow equipped, still 73% suppress
![one bow](https://user-images.githubusercontent.com/37040069/190864709-c345d63d-88e2-4aa6-b67a-705fb33d7b20.png)

3. one dagger equipped, 83% suppress
![one dagger](https://user-images.githubusercontent.com/37040069/190864724-96112bbe-af47-4115-9896-480fbaa3a79b.png)

5. two dagger equipped, 93% suppress
![two dagger](https://user-images.githubusercontent.com/37040069/190864746-f43fad22-a827-4911-acf0-d04449f56c58.png)

### What is the actual behaviour/value?

when putting lioneye's fall on this spot (the blue ring), 
![圖片](https://user-images.githubusercontent.com/37040069/190863755-925116a0-dc50-4732-8801-6299a20235a3.png)
the 「+10% chance to suppress spell damage for each dagger you're wielding」still gives you 10% suppress when you're wielding one bow in pob
![圖片](https://user-images.githubusercontent.com/37040069/190863936-34e1d6f9-44f9-4069-b930-6ba7415ad28d.png)

### How to reproduce the issue

1. create new empty build
2. add lioneye's fall and white crude bow to build the bow should be automatically equipped
3. click on the above mentioned jewel socket and dagger mastery, choose the 10% suppress for each dagger one on skill page
4. insert lioneye's fall into socket in items page
![圖片](https://user-images.githubusercontent.com/37040069/190865395-85b5e47c-7f69-479e-87b3-afeabb961be1.png)

### Character build code

```shell
eNqtW1tT4zgWfm5-hSsP-xRCfMuFJTMVkgCZIZBOgJ7ely5hK4kb2cpYMpDe2v--R74kBiJHNtNdBY51vnPX0ZEUzn5_9Yn2jEPm0aBX0xvNmoYDh7pesOzV7u8ujju13387OpsivrpdnEceESO_HX05i581gp8xAVxN4yhcYv6QcTJ_AKc1CvgK02CCftLwkrq92g0NcE17RIHr8eyTQxBjN8jHvdrcAXBNQ8zBgTvYvU8IfeQFc-o8YX4Z0mgdi3328MuEukAznkxvZ3c5oV6QFwo6fzmbErTB4ZwjrjH40av1wXS0xEPkw0_ghkgErPRmw-527HazbdiGZdZO9oPna4zdHajR6loy0mmIR4sFdrj3jAehxwcrFDg7gd2GIUOWp55EhHtr4uFwizAahhRy9YG_3mzKiO8oR2Q4ne9o242ubXbbnU6zY7eMYhzlW5xUwjePr84JOLaCFIEdLwOP44rgKfUYDT5hXx4qNXEQEQKzSI2W-o9eUMkbExSgAWUKPr_2FliNcjRXo5vBdFKjFFpOcQgTnqsrWwqQSphjh0JRKSOjDCRnRzVhFZCjeRVABUFzvqslppRqiF-3VJYtTQ38d55Ql9bMcbDTTC-S-kx5vGwcsiKepKOr6ZayLSWdrjbMcxCZoFfPj3yokXfoCe9ktGx5NJcrHsD0lkGtZqNlSOEXXoirIQeUuBWRK0RZNajIXQWnwErpnAraceCoTYj7IMQMh8-5BbZVqMUM0lks5o8EKyJ2ItJJobIAJqKWOEjlbdTMucbYWV1C_zJDHKsVk5w2xX4VxEp-FYR7_FrA_y2ihJsEcL-b9EanCFTSUd9Q6CqUvQCHy8185WFSkjpTf4DWClVSRCOPVorKW3GlMisPLem40TNi-aKpt4qtSsjV0gxD-wYAF7_rK-XVNqQ_RW9MysH6oU-jUDEuCbGSAVnxT3YFM-xGjtoCc05gd6KqPWhFSClEn3PkPA2pu8SlhJRHzKP1Gma9CPmHvUHRyjXDzMv1E8ctBepbyHWl6SUWOHUBO2plAdulW13KO4i6LWLJLWHMjlxZxHa_OYFq4kPdjrersFfOlWJ55b-APYrSBiUmVNz4TOkLKL8SJwWsHDV0J7sGVKpKiINfG2X-b8iVBIwCNwrFdFCW8R6xT8yd50PFZGyIONIYRqGzuoZA92q13KcLRMgjzH54K1BnJ_H5i3ga-2sa8vjlABGHxTzHwTriWhAfnvgec348RouFOCcBnjyMD3dGFxejwd34YZSqkYewJ4-QH0HkP4pDhOS3OG5JKOc4rocaix5Z8tirPXj4ZS5QQ8yRR8A1DiUErRl2e7UFIgwke_AY08zBXocXcIupoBXNzmX289oRyDmNXnHIwV5oFJzQw1K9tuMHlEoEivVZhE3GTZx0yBkldXyAGE_Waomn4tMlORdx1CM1RwwWYCFnEJFKTkcPeIJv1pjByuotPEdkfHHI74A6oSrwi-PAZHE2BfFOVyM5j_joSMYgGZSDk-MfGTodLfBqfPQk9WoyKocPsYOktieDcvC2_aMBuEnGZUtVwOmGBnGSw6Tpe0QsHNLIjgjeksgZ3vIVDpPVSMppAjUqIymcOKH3GHH5NM5RFPgq3rRKPCTG5NBkYyaxQYwVVKI3mxCJQ_M0clbJrkdayIqgWc8scV8yWmBEtm2Q6J8OyxkkTYw0fmlLVDS_oWGWz28xKAcn8-MjCx5GihziXB7iBYYqVJjMW5qCKsqjYAgFjxc4VJFVsir1n6nnJt36p7jFRu5ntvNUKV5Jkdjrt9Ic493MZ13_bpPzj7g_PTeT1O8cyQFGUHivCpZ2NU7b7v8KIyIuNij5HMMP54OfspNyhgJ3KI47lA09O8n627O4pWAag8b3EvvsfAPbjwtRNN9dmPiIw3qH_WtxTXlHRROOHI7D6-TaMhWGYkelnSmPrxXfcM6S1MULFBHx_muEiMc3ovHPvU25GvCSreiLyK-EjWh-GFTX6-tkpE94ykHIyPRIvJVqEXtAT-1OzBWPdyHGmb7QewmSBAYf8temYzfWzYceE4ebdGXt1f7bbplW3Wjauv0_6OthPwAvrbZlGPWW3oEhq9XsGnVb7xpmvdM1mnW70zHNutExDF3grFbd6rTbnbptW7pV7-rw1DK6dl3XrU63brRbdqtum4Zu1nVbt6y63tE7Rt2ydFM8N4GXKUiAoKkDcwNIDKtlmfVYs7auG3XTtC27brZbbXGtDAbnLpX1bnpfnBgobP9ydj-7jh--rDhfs9OTk5eXl8Ya8RVd4FeP4IZD_ZM1gMBrx_HW5liwPenDv_Nlv38ZPh13vv_dHE7CuzFfRdOH88EzDb-7y9tvxrHDrG8v41_dZvvPkXMZXv7n0vlqj-9__fVzdXk-vHLHj5vx5I-njdPvP_R_wuderNRJptVZcmXNEhXTT7HvhQ2x2yHfOfbH24gLeA4FHyC8cSaI-IuHGwotjhgTL7MPcXaIjVi6b5zzUGwif1Hqf-_V2ma70dGbum0ZVpKGUBr4BK2380AQpjms62kOQ8s-9CB9wrgGZjNBUP7Vqx0bRrPTaHV1kVDJPeTZGCxhaYqK52xGRQwnN07fMFrTIH6dy3tBmuZ87IAZgh3M5lS7vxl_vR8dXUP88Qb_C6Ds30wTu-GjBy_0XA8F2h_4BZOjGXK9iJ1qEwy__SPYxBDPgTp6qjWP4iNJDSqOljwlOmhiXmo-dWELAymmeYGWMNFQiLU72LezBQ197Gqcauf0RZtkpHGI4NMMBUusheInpGPDruWmLQRGGPXWOuutdTe3s0n_-mgQRi4WEo7SsnCqGc2jNANOtcvj7f-3Zr2RMSc0276n5um7vMou2dKIFEQjH4R9POcvaK31HzeMIaKlyWzvBDWzBN4DfQ8z1GAfrHhDdU5hLamo0D5bDih1jgkvCbmAevWkmUoqGftUMqu5V80Jxj8Es6op2aomrVXdm_qBAO_LpwMRuMLQ3_KygvZkUquKnAPpd0nos-i5yzM2q88ivYo8q1ou6NUyzzocHhXHlmW7L70qGq5Ud-wK-lSogeYhMe5GS04XSoZvv5cr5ZddBaQ0JVUCUclOu7JbjQpxb1WbSWa19DXLZ5lVvexXyGm9svNNlYSwVIgqqP2J5kcxktWj0KqQldXD8Il0US3JAqs4a9RJK3hu5gVLtU6gdKGQurdiuVCPZxVzTAU_6dXDYFX2ll3FGpX5Uj3JD6jU9yOyZ21L9pywZYxPJOL9fnz5TIOFt_xwlfz-6_i7C-j4a_kf755xgP3NmJ1Txg7Svv8Dg4OA5C8P9pJNCXLwihIXh3lN0i_5Z3fg7fx33vbRi5vX7No6A5kKmOx7NhnGLoa8_Y5STr_sqDSNxtnJ-z_d-D-wccvw
```

**Comment by Paliak** [comment]
Radius jewels seems to apply to masteries, which they shouldn't. The spell suppression from the dagger mastery also doesn't seem to work correctly right now as it applies regardless of the weapon.
