### ISSUE TITLE
Show overcapped crticial strike chance in brackets

### ISSUE THREAD

**Issue by Darxo** [PathOfBuildingCommunity/PathOfBuilding#5101]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

If your character has more than 100% critical strike chance then 100% is always shown.
You don't know by how much you are overcapped at a glance unlike with other stats like resistances.

### Describe the solution you'd like

When a character has more critical strike chance than the maximum possible amount (100%) then the overcapped critical strike chance should be shown behind that value in brackets.

This is a very useful min-maxxing feature allowing you to instantly spot whether you have allocated too much crit chance on your build.
![OvercappedCritChance](https://user-images.githubusercontent.com/2252464/191657962-16ed8e25-c73f-4cb5-96e9-f1e1d2376ef0.PNG)

**Comment by QuickStick123** [comment]
This is provided in the breakdown section. I don't think it makes sense to put it there as by that logic overcapped hit chances and others should be shown.
![image](https://user-images.githubusercontent.com/31533893/191669668-5010e1e3-50c0-4df8-94ba-7c3e033a1c42.png)
