### ISSUE TITLE
Pulverise incorrect damage calculation with Blitz allocated

### ISSUE THREAD

**Issue by battledone** [PathOfBuildingCommunity/PathOfBuilding#5105]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Pulverise should be showing increase in DPS of around 28%

### What is the actual behaviour/value?

Pulverise shows increase in DPS 50-100% higher than it should.

### How to reproduce the issue

Allocate Blitz
Tick Pulverize Support

### Character build code

```shell
https://pobb.in/WvkzQiDyO6Jg
```

### Screenshots

![6](https://user-images.githubusercontent.com/58683445/191878939-d3ec9d07-1e34-4e46-b574-554663c16a79.png)

**Comment by QuickStick123** [comment]
For future reference the higher attack speed was decreasing the uptime on the double damage warcry which decresae damage this meant less attack speed provided double damage as compensation resulting in higher than expect dps.
