### ISSUE TITLE
Sort Timeless Jewel Search Results by Combined Node Weight

### ISSUE THREAD

**Issue by ggargov** [PathOfBuildingCommunity/PathOfBuilding#5106]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

No

### Describe the solution you'd like

When searching for a Timeless Jewel, I want to be able to sort by Combined Node Weight. Currently the sort options are pretty extensive, like Total DPS, Life, Armour, etc, however I want total control of how each node is stacked up to one-another since alot are not DPS.

Please let me sort by Combined Node Weight. The calculation is already displayed if you hover over Search Results. 

### Describe alternatives you've considered

Scrolling and seeing what pops up

**Comment by QuickStick123** [comment]
So you basicly want a node weight option that gives most efficient per point timeless jewel? Or some kind of individual node weighting? Or do you want to be able to search for 50-50 contributation of life and dps?

**Comment by ggargov** [comment]
There is already a feature to add weights to each node. Sort the search results by the largest summation of these weights.

**Comment by ggargov** [comment]
If you hover over a search result of an individual jewels, a pop up tells you the “Combined Node Weight” - just use this as the sort criteria and expose it as an option under the drop-down that lets you choose how you sort.

**Comment by Lothrik** [comment]
I'm not sure I understand what you're asking for. The timeless jewel search results are *already* sorted by Combined Node Weight. In fact it's the only sorting option available as this behavior is not currently configurable.

The dropdown list called "Fallback Weight Mode" in the "Find a Timeless Jewel" window with options like "Sort by Full DPS" are **not** how the actual Search Results are sorted &mdash; it's used for generating Fallback Node Weights.

**Comment by ggargov** [comment]
I played around with it some more and I think this is just a user error on my end. Not sure what I did wrong the first time around but I see it sorting correctly now. Sorry for the noise, it works as you described.
