### ISSUE TITLE
Error when trying to add an implicit to a jewel

### ISSUE THREAD

**Issue by Xanoth** [PathOfBuildingCommunity/PathOfBuilding#5108]
Running 2.21.1.
No duplicate issues found when searching.

_______________________

Trying to add an implicit to a jewel generates the following error:

![image](https://user-images.githubusercontent.com/46023287/191922681-793406d6-48bf-455d-bd7d-ddf506e765c6.png)

I've tried creating a new POB, editing new, or existing jewels.

This happens with all jewel types; normal, abyss, cluster, timeless.

implicit adding works fine for every other item type that I've tried.

I've tried a few restarts.

I'm not sure if my instal is corrupted as I'd have expected this to have already been reported if it was an issue with the build.

**Comment by QuickStick123** [comment]
Adding a jewel with the timeless jewel base also crashes. I assume this is because no current implicits/mods. As synth implicts arn't currently supported.

**Comment by Regisle** [comment]
Can confirm an issue with PoB not your installation specifically, The lack of previous reports is likely due to it being added recently and not used by most people, possibly when I disabled synth mods there was some regression
