### ISSUE TITLE
Resistance final values differ from in game (when using The Annihilating Light)

### ISSUE THREAD

**Issue by melink14** [PathOfBuildingCommunity/PathOfBuilding#5111]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

In game my res was 74 100 78 (Fire Cold Lightning) but POB showed 75 100 78.

I'm guessing it's a rounding error problem due to the Annihilating Light having 60% reduced resistances applied.

### What is the actual behaviour/value?

POB shows res as slightly higher than in game.

### How to reproduce the issue

Import build, look at resistances.

### Character build code

```shell
https://pobb.in/x8vfUw5GG1Nm
```

### Screenshots

![image](https://user-images.githubusercontent.com/1176550/191979224-d6d26098-b5bf-4e57-944d-e99cdde8522f.png)

**Comment by Paliak** [comment]
The resistances calculated by pob for the linked build are:

 - Fire: 74.8
 - Cold: 100
 - Lightning: 78.8

I guess the game floors the numbers while pob rounds.
