### ISSUE TITLE
15% base shock due to Shaper of Storms not applied unless highest damage type is manually set to Lightning

### ISSUE THREAD

**Issue by melink14** [PathOfBuildingCommunity/PathOfBuilding#5113]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When the Elementalist node, Shaper of Storms, is selected the minimum amount of shock becomes 15%. This means the 'shock effectc mod' should be multiplied by 15% to get the final shock value for a skill.

This should not be affected at all by the highest amount of damage being lightning since that's not a requirement of the 15% miniumum.

### What is the actual behaviour/value?

Right now, it seems that POB is calculating the base shock chance in this case as 12% (this is calculated by reverse engineering since POB doesn't show the base shock value anywhere).

When you manually select lightning damage as highest source of damage in config, then the "Shock Effect Mod" doesn't change but the Current shock value increases to the correct value (base value becomes 15% invisibly)

The odd thing is that even though lightning being highest shouldn't matter for base shock value, POB already knows what it is (since it correctly includes the 1.25 more multiplier from Shaper of Storms in the "Shock effect mod" section).

This means that changing the config is having some additional affect separate from the other highest damage calcs.

### How to reproduce the issue

1. Import POB
2. Go to calcs, change to orb of storms and observe shock value.
3. Toggle highest damage source in config and note the changes as described above.

### Character build code

```shell
https://pobb.in/mm2f8Bk_eg1t
```

**Comment by QuickStick123** [comment]
Highest damage is phys
![image](https://user-images.githubusercontent.com/31533893/192083104-6d8f074f-e948-4685-8a5d-301224ebd576.png)
3.4 * 15 = 51
Highest is lightning
![image](https://user-images.githubusercontent.com/31533893/192083126-e89376ea-0554-49ea-aa4c-156ea2811f4e.png)
4.25 * 15 = 63

**Comment by melink14** [comment]
It seems there's a misunderstanding.

1. You're switching between physical and lightning. You should be switching between Default and Lightning. I should have been clearer by what I meant by switching.
2.  As I noted, the highest amount of damage is not supposed to change the base shock value at all.

**Comment by QuickStick123** [comment]
Oh I see it is the exact same issue as https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5037 but for shock.

**Comment by melink14** [comment]
Thanks for that reference.

It makes sense that enemey mods make it hard to determine it but I think maybe for the shock case, there's a visual bug which might be fixable.

Right now with "Default" selected it shows, in the "Shock Effect Mod" that Shaper of Storms 1.25 multiplier is in effect due to "Condition: Lightning is highest damage type"

It sounds like from #5037 that the 1.25 multiplier shouldn't apply unless the highest damage is selected in config. And instead the invisible base 15 should always apply. Right now those are backwards.

Since the calcs lists a highest damage condition right now, it makes it seem like the config dropdown isn't required.
