### ISSUE TITLE
Physical damage to spells craft for both elder influence and delve craft are not included

### ISSUE THREAD

**Issue by Stratavarius79** [PathOfBuildingCommunity/PathOfBuilding#5117]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

There are missing crafts for runic daggers that are influenced or delve crafted that don't allow physical damage to spells to be added either from elder influence or delve craft.

### Describe the solution you'd like

Just want them, to be added

**Comment by QuickStick123** [comment]
Should be fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4975, duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3168.
