### ISSUE TITLE
Damage taken convertion didnt calculate right

### ISSUE THREAD

**Issue by ucokkocok** [PathOfBuildingCommunity/PathOfBuilding#5118]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

It should double dip the defense layer the lightning damage taken

### What is the actual behaviour/value?

In POB when I use the Amulet with implicit 50% of Lightning Damage from Hits taken as Fire Damage, it calculate incorrectly.
But when I try using Amulet with implicit 100% of Lightning Damage from Hits taken as Fire Damage, it calculate correctly

### How to reproduce the issue

Check on my pob, and try change the amulet 

POB : https://pastebin.com/0pqVy1Aw

### Character build code

```shell
https://pastebin.com/0pqVy1Aw
```

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5196
