### ISSUE TITLE
Armour Cruncher

### ISSUE THREAD

**Issue by Taffa2** [PathOfBuildingCommunity/PathOfBuilding#5127]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

In the Spectre Library, the Armour Cruncher should be listed.

https://poedb.tw/us/Armour_Cruncher

The Armour Cruncher is a mob from Act 2 The Caverns, it casts Curse Enemies with Vulnerability on Hit, with 4% increased Effect

### What is the actual behaviour/value?

When you open the Spectre Library, the Armour Cruncher is not listed.

### How to reproduce the issue

1. Set skill to Raise Spectre
2. Click the Manage Spectres button
3. In the Available Spectres list look for Armour Cruncher
4. Not listed

### Character build code

```shell
x
```

### Screenshots

![spectres](https://user-images.githubusercontent.com/15445697/194160418-82fa8db5-fc23-4ada-9b28-cbcfb5f1940a.jpg)

**Comment by michelrtm** [comment]
I would like to look into fixing this one!

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5201
