### ISSUE TITLE
(Meta issue) Link in readme leads to scammy gambling site

### ISSUE THREAD

**Issue by mkfink-uml** [PathOfBuildingCommunity/PathOfBuilding#5128]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I click the Feature Requests link in the readme (https :// feathub. com/LocalIdentity/PathOfBuilding) it should take me to a real website.

### What is the actual behaviour/value?

The link takes me to this extremely scammy gambling site
![image](https://user-images.githubusercontent.com/97988242/194651409-59d0bbb5-e42f-4265-ab5e-97171815b754.png)

### Character build code

```shell
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/README.md
```

**Comment by Wires77** [comment]
I went ahead and removed that link
