### ISSUE TITLE
The Devouring Diadem template still using old unveil list as variants

### ISSUE THREAD

**Issue by c20k20w** [PathOfBuildingCommunity/PathOfBuilding#5140]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Devouring diadem should have updated list of unveils as variants, or use the alt variant system as per the other updated betrayal uniques

### What is the actual behaviour/value?

There's a list of 19 variants but no updated ones

### How to reproduce the issue

1. Open item list
2. Select The Devouring Diadem in middle pane
3. Open variant dropdown

### Character build code

```shell
No
```

### Screenshots

![image](https://user-images.githubusercontent.com/62009382/195964479-7745178f-c011-4cda-b00f-50eb4e813a06.png)

**Comment by QuickStick123** [comment]
This likely affects other non-generated veiled uniques.
