### ISSUE TITLE
Few question

### ISSUE THREAD

**Issue by DragonFet** [PathOfBuildingCommunity/PathOfBuilding#5152]

**Comment by QuickStick123** [comment]
Did you mean to post this here?
We don't have any encryption.
What do you mean "interesting code for wrote items on player"

**Comment by DragonFet** [comment]
Sorry for my bad English, i want ask how you create code for charter. I mean the code we are importing into the path building

**Comment by PJacek** [comment]
Character builds are just xml files as you can see when you save them locally on your computer.
Then it gets compressed with Deflate and base64 encoded when you share it:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/ed63b36fd8370466943b154f4eb9d1909838884b/src/Classes/ImportTab.lua#L157
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/ed63b36fd8370466943b154f4eb9d1909838884b/src/Classes/ImportTab.lua#L257

**Comment by DragonFet** [comment]
Thx. Good luck.
