### ISSUE TITLE
(Bug?) Power Report showing many notables granting+50% more Effective Hit Pool (v.2.21.1)

### ISSUE THREAD

**Issue by Jebonn** [PathOfBuildingCommunity/PathOfBuilding#5161]
I checked the Show Node Power checkbox, changed it to show EHP, but many notables are showing +50%.

![Untitled](https://user-images.githubusercontent.com/93694643/198888516-f235564b-9f39-470a-aca3-3f15184b1709.png)

Pastebin link: https://pastebin.com/SGTe0AT7

**Comment by QuickStick123** [comment]
This is eHP acting as breakpoints in low number of hits in this case 2?
Should be resolved in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4915
![image](https://user-images.githubusercontent.com/31533893/198907150-7d939c0f-77c4-4e6f-9a45-f773f2142b9b.png)
