### ISSUE TITLE
"Curse Cast Speed" node in "Whispers of Doom" ring applying to Hexblast cast speed

### ISSUE THREAD

**Issue by kolhell** [PathOfBuildingCommunity/PathOfBuilding#5170]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

"Curse Cast Speed" node should not apply to Hexblast's cast speed

### What is the actual behaviour/value?

"Curse Cast Speed" node applies to Hexblast cast speed

### How to reproduce the issue

Create a new character (any)
Equip "Hexblast" and set as "Main Skill"
Path to the Int node before the "Whispers of Doom" ring (directly below "Chaos Inoculation")
Mouseover/toggle "Curse Cast Speed" and it will apply to the cast speed of Hexblast

### Character build code

```shell
eNqtG1tz2jj3ufsrGJ7TcDGGsEN2Bwi5zISGD9L226eMsAVoK1vUkpOwv36PJBsbiozsbB9SY537TedIMPjzPaC1VxxxwsLreuuyWa_h0GM-CdfX9a_Pt5-v6n_-8dtghsTmaTWKCZUrf_z2aaCeaxS_Ygp49ZpA0RqLbykl5wUobVEoNpiFU_Q3i-6Yf13_wkJcry1R6BORfvIo4vwLCvB1fbFBPnur1xD3cOiPswUNGSASLpj3A4u7iMVbxfeV4Lcp8wHmYTp7mj_nuJIwzxWE_jSYUbTD0UIgUePw57o-BN3RGt8TAaQQjYFOu-k0L6_a9cZpjMUWY38P3Lrs5v71TEizCE9WK-wJ8orHERHjDQo9vKfSMeGVhZ3GVJAtJTjKSeiaMJ6ZQPRmttjDOs5V57JXDM4ySzVNkA_rkAh8QLnltC_bbs_pdZ1m3z2DiALwSaZB2233L5vtvtt0287VOfEqsB3HlEJc5zGNuo1ZsCQh9oev60zCjuv2L686ZyQcRhg9rXQgzJFPYp4FXd-ENEUhGjOej08T6CNZ4QNQI-RkYQc3Bz_YQUoxZziCvBV2CFLYUggJhwX2GNSGMjzKoOT0qMasAuZkUQWhAqOFyNUFYyG5we9ZsDnGVA0zhq2WEWyOfx5Auq6Z7SsTsHmcV0Nl-uR-tofsmQvvZseJh-gUvZMgDqDOP6MfOOPRa5vdud6IEKqCCbVj1OSWRLg81phRvwLWBjFuQnPcy27bLQrYPajbK9jwvN8l7EPo2WXB1zDCHEevuX3STF4izCGG5Ua8pNgSI2ORZEIWYc1mMas1DhN-Ozt1HjH2NnfQewCrfKNQWEP2UP1uoWElrJVhJeAJw5rJHyKUMJNEPG2mlrk5kEilDfUdRb5FtQtxtN4tNgTTXOPl2oCnGozR1gJTOSSPbuWYQ36loiuPWtp4k1fE8-WyVRxoCbhdrGGKMSD4-Kj5bJobXPa3bG9pObRhFLA4sti4pAYa2EqBtOzrTnKO_diz21pGFOYLW-lBKkpLYQyFQN6PG-avcSkm5TEW8XYLuS9dbosnt6055iTXSXzuWkA_QbDnE6xZtMPZM8igrRns92x7Lkco9rrIfbeEMhm4NYv9xDiFchJA8VajJwy7WcobnQMDTX6a6bqt7mX_7Byk0GwmqIT-4gehtMbl3xmKZGemTgHqNQ6J6gF2PSF8j9-XMM2L05OmiVpGJ8NP0hRzUdPDYq3CvDdjb-CDjRSWWxSTHDR0WhkzoxkjHP6zs6Z_AG7FYBL6cSST2prHMcYpNs8kgLrP-Q0SqMYxirzNI8Sr8sP-0y2idAk1DN5KrEFDHQTJp4dgyyKhXo4R9bii-RBuY1EL1SFOQLj3soxXK3leIz0ZqVOmye3tZPz88G2SiJFHUcHwEsbBUp5o6P-zsF9gVdVrPF5y_Xhd_0bwmwqkGywQoWAaj1GKthz71_UVohw4E3hUMAvQ1xMF1BQU7MbpicRpWhmAmdLkHUcC9IWWx4sINsq1Xz8jlGYo-wzpNhM1eVpjJqR3ozHk1RwJIw194GWmIs-djOrIxQJciBlEjZyT1TOWELst5tAfkBXxZMQXu_wZoDVUgV08D5LF2xX4O9lTzTRGVB0TniagF83IM0a47FZOYyerBVZVhdFoVb1qRr_BHjLqrhfNyPs2loWqiz1NZQ9VQOkLC1WQQ9IMCZX7n9GzE4r3IGaCT2KDI72pGilNoUalIIWJE5FlLMxpnIMosJUawA0WkmtmVD1iGnSQawWV6GCcMhg0D2Mmpec3YyErQk07f4P59GqBEunwY5A_WTYT0L2Y0X9JZ1eU39D2m_NbLpqRdX78SkJEsSUFFcs3eIWhChUG8x6moIqKOLyBgicKDGpJSu9Kw1dGfD1zfIiaUvI0scxSpWjpInHSbqUpqpnso6Y_GtX-E_MnZ4CG-p0DOUMICu99wdZuR2k_xNxjRMVmxhj9GMFfzjo_pCcTHIX-jTy2sVZ00Ej724FqKTiMKZG4wwEf7WAYuZVFM7snUuNJgATsdzh4lPelz0w24cgTOHrU96cJM6QMlXSmQl1vHlBOg9THKxRT-f5_MaJE7GTjn3ubUA0JmJpv2JsMME1Hdj8cyuvjo14ZUpGQkExSQbS5EjGUCVrqXfJS3cMOM1mVNZS0JPRo7OOHMJnoUoEpWkqB5N2yPOPdZ9sRoT2fTwMQJwG-o2yJaDtFURPBlITgviPmuZXk5fCd8AkohxeM-gRH9zhC1H9aqZm_nl5et5v1A1atA1YPqotmwSgZP4_YK84_tQkVqHZCPT_GAsQaB3J1CjOJD9NV40GAuRvS5g1FBp6yEfdnzqlHBttTzdT2WBxqJnJkkgdlB-NyJi9UmzgIGITkDJpXgXigEwPiWcmgvN5I3a7iXIe3fHyOME7jU7FoJVECH_LX9VLLpnQsh-jeJZ2U9HwIMx88OFetdv-i5bqd_kWn3226F51O98q56LjN9kW32ek0L5yu271oN91O98JxerDWajlO58Jp91pAWYAguW8ZtPrJFwgk424SpV_njzqMNkJs-e-Nxtvb2-UWiQ1b4XdC8aXHgsYWkECbz8pCnyXZxhD-jdZ_Dcfb5_fZozN6n999743WT4vb0Xj94vF5-HIHINfaaCmXgf5KAm8kBgSLKONJk8mHLwy6QLkmX6YflEHlrJqM1gsRSSv9A5H2l7RSR-cnFE0xRdskl-VqkttOktkwydwQsHKktoY0TCTg_-V5lKMv-QYq3hL_yee0vMQc6_vD7xhtIaTla8lKD-Ia0Ah0WBkoS4d2DVZrLd7QtjZc7jhHtKaNVHMBS-hkaKbhdwL1GK1th1YMNWJQ7SsKdEqXM0KNMBUlUW4hkn_UHCuR2qdEcqqZ184I7f8IrVNNyG41bt3q1qwST2c8cI-hAxVlGZ2IpG4VPmfCD_a_V9kVlyfsVM-iVhV-nWqx0KoWeZ3z7rExbFmyp8KrouJWdcetIE-FGuicY-Pvanr-L-m-01auFF9uFSSrlLRxRCU93cpmbVfwe7daJjnVwtcpH2Wd6mW_Qky3KhvfsQmIjg1QBbE_0PxYerK6F7oVorK6Gz4QLrYlWeJaZo09aAXLzUm4tusEShcKo3krlgt7f1ZRx7GwU6u6GzqVreVW0cYmX6oH-RmRhkFMT-xtg0YyQ6qBWA2h6nqYhSuy_uWy9_iL-9kVsfoC_6-3wzjEwe6BjxjnZ2GPf4twFkH_SOEk2IwiD28Y9XGUlyT5ZUB6S93Lf8PuFLy8G00vllMkxwIn_T5PiuMWoxx-FyonX3qYmXhj0Dj-lce_bRD44Q==
```

### Screenshots

![image](https://user-images.githubusercontent.com/31980209/201971339-e2d6b0c7-1451-4d0e-bd6b-03d641c665b9.png)

**Comment by kolhell** [comment]
Looks like we're processing all hexes and marks as curses

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/911bdd878f2a2a918910b40428c0a74f0878ae5b/src/Modules/CalcActiveSkill.lua#L329-L331

Hexblast is a "hex" but not a "curse". Looks like the issue applies to Bane as well (also a "hex" but not a "curse")

Suggest:
`if skillTypes[SkillType.AppliesCurse] then`

**Comment by QuickStick123** [comment]
So a curse skill should be skill that applies a curse? You can probably just update these to uses appliesCurse this is how non-curse auras are implemented.
![image](https://user-images.githubusercontent.com/31533893/202835539-2b6d0e8e-d880-4bcc-8b15-61166d2dc3a4.png)

**Comment by kolhell** [comment]
Is one preferable to the other for any reason? I don't see why we're mixing styles throughout ModParser.lua unless that's just how it's grown with multiple contributors over the years (in which case I might get bored and clean it all up...)

A lot of CalcActiveSkill.lua is just translating a single SkillType flag into skillKeywordFlags, which would feel unnecessary unless someone decided it's either more efficient (I don't know enough about how lua handles calls behind the scenes, if all of those braces are actually slowing down calculations) or more pleasant to look at. 

Either way I've been running my fix locally without issue since I posted it here, so I'll get on submitting a PR probably tomorrow.

Thanks for the input :)
