### ISSUE TITLE
Something wrong going on with Mark of the Elder, Steel Ring

### ISSUE THREAD

**Issue by KhadaElk** [PathOfBuildingCommunity/PathOfBuilding#5174]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Thing that should happen is that Mark of the Elder, Steel Ring should give me 69% increased Attack Damage if another ring is Shaper inluenced item

### What is the actual behaviour/value?

Placing Mark of the Elder ring is making my DPS lower

### Character build code

```shell
https://pastebin.com/faMh0QCj
```

**Comment by PJacek** [comment]
You have Flammability corruption on it which makes you go over your curse limit and disables Assassin's Mark. You should instead use a regular physical damage implicit one. It will give you better damage that getting additional curse and running Flammability.
![image](https://user-images.githubusercontent.com/18018499/203619071-8fc71e26-7138-4446-b45d-34d3f3fbecee.png)
