### ISSUE TITLE
Perfect agony doesn't affect DoT dps if used with seething fury 

### ISSUE THREAD

**Issue by UMTTEPATOP** [PathOfBuildingCommunity/PathOfBuilding#5177]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Crit chance and crit multi from every source is supposed to work with perfect agony. I checked that if I add crit chance and crit multi from tree, my bleed/poison/ignite dps increases. I also decided to see what happens with in-game stats when I get perfect agony having emperor's vigilance and seething fury equiped, which has lead to numeric changes in stats for bleed, poison and ignite.

P.S. Alt quality of SST and Shield crush work for some reason.

### What is the actual behaviour/value?

Perfect agony is supposed to increase average DoT dps while Seething fury is equipped in pair with energy shield on current shield while using SST, Shield crush or Shield charge.

### How to reproduce the issue

Use this pob: https://pastebin.com/0KBb6zF7
OR
1. Equip SST
2. Get bleed/poison/ignite chance to have bleed/poison/ignite dps
3. Equip emperor's vigilance with seething fury
4. Click and unclick the perfect agony to see that nothing is happening.

### Character build code

```shell
https://pastebin.com/0KBb6zF7
```

### Screenshots

![image](https://user-images.githubusercontent.com/40309271/203964592-125aaf56-4bcc-46d7-8dba-3cc785e7eed2.png)

**Comment by Puddlestomper** [comment]
Update: This is still an issue with the new version of Perfect Agony implemented for 3.25, in PoB version 2.43.0.

Build: https://pobb.in/yK4eYsS8KPFI

We have SST and Shield Crush linked to Chance to Bleed. We're using Emperor's Vigilance with Seething Fury for crit multi. Hovering over OH Crit Multiplier in Calcs shows the 184 crit multi from the shield, but we can see this isn't in OH Eff Dot Multi.
