### ISSUE TITLE
typo in config tab

### ISSUE THREAD

**Issue by kolhell** [PathOfBuildingCommunity/PathOfBuilding#5190]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

typo in the config tab: should read "30% / 20% (Mid tier)"

### What is the actual behaviour/value?

"30% /2 0% (Mid tier)"

### Character build code

```shell
n/a
```

### Screenshots

![2022-12-02-193503_2062x1402_scrot](https://user-images.githubusercontent.com/31980209/205413419-e6b9cd3e-d388-4eec-a609-93cba10eee5f.png)

**Comment by Nightblade** [comment]
fixed in #5191
