### ISSUE TITLE
You can only have one exposure for the same element at the enemy

### ISSUE THREAD

**Issue by Nathaniell1** [PathOfBuildingCommunity/PathOfBuilding#52]
Even tho I have not been able to find any official source to this, all the reddit threads agree that you can only have one exposure of the same element at the enemy. So.. basically, enemy can have lightning and frost exposure, but not two frost exposures - this currently does not work. You can use Wave on Conviction which applies frost exposure and frost bomb and the -25 to frost resist will be used twice.

**Comment by ppoelzl** [comment]
Correct that you can only have one exposure on an enemy, the intent behind it was to make penetration more accessible, but also not as stackable.

**Comment by MatthewSbar** [comment]
TIL I was running elemental army for no reason.

**Comment by NickRyder** [comment]
@MatthewSbar Most debuffs in the game work by applying the highest possible. Would require in game testing to confirm.

**Comment by rskupnik** [comment]
Working on this

**Comment by PJacek** [comment]
Fixed in 1.4.170.12
