### ISSUE TITLE
Macos compilation script

### ISSUE THREAD

**Issue by benlstumpf** [PathOfBuildingCommunity/PathOfBuilding#5206]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Even if I need to run some scripts, having the ability to have PoB on all PoE supported platforms seems good.

### Describe the solution you'd like

Having a macOS release

### Describe alternatives you've considered

Minimum: some documentation on how to compile PoB for a different system

**Comment by Wires77** [comment]
There are no concrete plans for supporting MacOS right now.  This has been requested before in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1370 and the workaround has been to use Wine or another 3rd party package (see comments in that thread for one attempt)
