### ISSUE TITLE
Elemental Hit's "80% more area radius against enemies affected by an ailment of the chosen element" incorrectly classified as 80% more area

### ISSUE THREAD

**Issue by elendarulianreo** [PathOfBuildingCommunity/PathOfBuilding#5215]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Elemental Hit states "80% more Area Radius against Enemies affected by an Ailment of the chosen Element." With a base radius of 10 units, AoE explosions against enemies affected by an ailment of the chosen element should have radius 18 listed in the sidebar's AoE radius stats as well as skill type-specific stats under the Calcs tab.

### What is the actual behaviour/value?

PoB treats this 80% more area *radius* modifier as an 80% more area of effect modifier, incorrectly converting it to a radius increase by taking the square root of the bonus, when it should just be fully multiplicative.

### How to reproduce the issue

1. Select Elemental Hit as main skill
2. Select Fire AoE as the subskill to be displayed
3. In configuration, check "Is the enemy ignited?"
4. The displayed radius on the sidebar and in the skill type-specific stats window under the Calcs tab should be 10 (base radius) * 
1.8 (80% more area radius). Instead, these stats display 10 * 1.34 (square root of 1.8) = 13 AoE radius.

### Character build code

```shell
https://pastebin.com/sLq0TDPH
```

**Comment by QuickStick123** [comment]
Are you sure this is wrong (tested ingame) the mod internal name says aoe
"elemental_hit_area_of_effect_+100%_final_vs_enemy_with_associated_ailment"

**Comment by QuickStick123** [comment]
Based upon my testing it does look like radius
