### ISSUE TITLE
How do i make an "OR" search using the Search Box?

### ISSUE THREAD

**Issue by mojimi** [PathOfBuildingCommunity/PathOfBuilding#5221]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I've tried searching everywhere for how to do this, there are a couple related issues but no definitive and replicable answer

### Describe the solution you'd like

I would like to search, for example all nodes with Poison, Chaos or damage over time, the equivalent on Poe would be:

`"oison|haos|over Time"`

### Describe alternatives you've considered

I've tried Lua regex but it's complicated and its not clear how its implemented

**Comment by QuickStick123** [comment]
Lua regex sadly don't support or operations this would have to a be feature we add.

**Comment by AnnanFay** [comment]
Similar to this closed ticket: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/160
