### ISSUE TITLE
Scaling issue on Linux - 1440p display

### ISSUE THREAD

**Issue by Thorium0** [PathOfBuildingCommunity/PathOfBuilding#5229]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Having text/buttons be a readable size and the window correctly scaled.

### What is the actual behaviour/value?

Not sure if you care to work on something related to Linux, but I'll try posting the issue anyway.
I'm using manjaro linux with KDE Plasma as my window manager and my laptop has a 1440p display.
When I open the program the ui  is misplaced (see image). This can be fixed by setting qt scaling settings to 0.5, but the text is still so small it's completely unreadable (I'm not vision impared).

### How to reproduce the issue

1. Use linux with a 1440p display (Haven't tested on other window-managers than KDE Plasma)
2. Compile the program (yay -S path-of-building-community-git)
3. Open program

### Character build code

```shell
Happens before and after importing build
```

### Screenshots

Without QT modifier:
![without-scaling](https://user-images.githubusercontent.com/46021061/206386265-06b63ce4-1f4c-4335-8fa0-7f4ac0722683.png)
With QT modifier:
![with-scaling](https://user-images.githubusercontent.com/46021061/206386266-778b2ee2-fb30-4487-8d9e-954eaaea5303.png)

**Comment by QuickStick123** [comment]
Probably same as https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4545

**Comment by QuickStick123** [comment]
This might also work
https://www.reddit.com/r/pathofexile/comments/z8gpd5/lutris_installer_for_path_of_building_on_linux/
https://www.reddit.com/r/pathofexile/comments/girazj/psa_for_linux_exiles_you_can_now_easily_run/
