### ISSUE TITLE
Ice spear doesn't increase its dps with "All projectiles"

### ISSUE THREAD

**Issue by Sylteren** [PathOfBuildingCommunity/PathOfBuilding#523]
"1 projectile"
https://imgur.com/a/WG871EE

"All projectiles"
https://imgur.com/a/p5dvokF

Still the same dps. It shows the same dps no matter how many projectiles you add. It's been like this for a pretty long time now, so it's not a recent bug.

**Comment by LocalIdentity** [comment]
Please include a Pastebin of the build you were using the showed this bug as I cannot reproduce it

**Comment by LocalIdentity** [comment]
You are using a trigger for the spell to cast (CoC, CwC, etc so it only shows the average hit. To see the DPS, untick the trigger support gem
