### ISSUE TITLE
PoB not accounting for stats added on notables via timeless jewels.

### ISSUE THREAD

**Issue by azra1l** [PathOfBuildingCommunity/PathOfBuilding#524]
i couldn't find an issue report for this, here i go. in case i just missed it, please redirect me.
also, timeless jewels are confusing AF already, so maybe this is just me brain farting big time. 
but i am experiencing some wierd issues with stats they add on notables.

i just switched from the openarl PoB to this one, and i really dig that this fork seems to parse the actual timeless jewel item seed, so i won't have to dig manually through all the added attributes and add them by hand. this looks like witch craft to me, but i won't complain D:

now the values i get in the app don't match with what i get ingame.
ingame, the added stats on nodes add up to 98 strength (with 3 x +20 strength added on notables)
when i remove the jewel ingame and in app, i end up with 1407 strength on both.

when i put the jewel in slot, it adds 124 strength ingame, but only 48 in app.
now, when i manually add +60 strength to the jewel item, it also addes 124 strength in app.

so apparently PoB doesn't account for timeless jewel stats added on notables?

here is my build in case it helps: https://pastebin.com/fPkvaZqL

do you need anything else?

**Comment by BassOfBass** [comment]
It doesn't know what kind of stats you get on notables. And no, it doesn't know how to calculate values off seeds either. The only thing it does is add bonuses to minor passives on the jewel type it's obvious, i.e. DEX on Brutal Restraint, STR on Lethal Pride and nullifying all on Elegant Hubris. Otherwise you have to add other bonuses manually.

**Comment by LocalIdentity** [comment]
Exactly what BassOfBass said above. Support for adding the new mods yourself to he notables will come in an update soon
