### ISSUE TITLE
Bugged Juggernaut ehp calculation

### ISSUE THREAD

**Issue by ernviher** [PathOfBuildingCommunity/PathOfBuilding#5252]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

The calculation of ehp should be similar to previous version of PoB when importing exact same build.

### How does Path of Building behave?

After the update to newest version I noticed the ehp and maximum hit taken calculation from allocating the Unbreakable is much different than in previous version of PoB. 

### How to reproduce the issue

Import build to previous verion of PoB
Import the same build to newest version

### Character build code

```shell
https://pastebin.com/BSSQpce8
```

### Screenshots

Newest PoB ehp 
![image](https://user-images.githubusercontent.com/82809905/206702685-24129ab0-9e03-400d-8d45-de9c9f506135.png)

Previous version
![image](https://user-images.githubusercontent.com/82809905/206703347-eeac11f0-482c-4737-8466-3c6c8382abd5.png)

Screens taken based on max lvl gear from the build linked above

**Comment by QuickStick123** [comment]
The current numbers are much more accurate and correctly handle armour in max hit calculations. You can test this by input the hit damage and seeing what the hit you will take is.
![image](https://user-images.githubusercontent.com/31533893/206704407-5b2ba8ff-d48a-47fb-a273-a0e3a592b304.png)

**Comment by QuickStick123** [comment]
The change in eHP is due to fixing a bug related to guard skills as far as I can tell

**Comment by QuickStick123** [comment]
I am closing this as invalid unless you can provide maths why the new version is incorrect.
