### ISSUE TITLE
Legacy of Fury no longer adds scorched configuration

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#5255]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Previously, adding Legacy of Fury added the scorched checkbox and effect textbox to the configurations tab.

### How does Path of Building behave?

^ This is no longer the case.

**Comment by Seikah** [comment]
Likely related: scorched ground mods still add the 'is the enemy on scorched ground?' checkbox, but checking it does nothing.

**Comment by Lilylicious** [comment]
To be clear, the fix mentioned above doesn't make the config box appear, but it does add scorched to the enemy. There's no need for the checkbox to appear when it's a "nearby enemies are X" effect
