### ISSUE TITLE
Mana Cost still shwoing when EB is Active

### ISSUE THREAD

**Issue by Garf412** [PathOfBuildingCommunity/PathOfBuilding#5261]
Hi, this has been an issue for a longtime, I did a search couldnt see this has been rasied wasnt really an issue until now with the new -1 mana cost warning...

I dont use mana, i have over 2K ES and the cost of my skill is 40, its never gonna run out.

Can PoB be changed to relfelct the cost coming from ES not Mana when EB is being used (from an item or the passive tree node?

Thanks <3
garf412
Heist Content Youtuber.

**Comment by Lilylicious** [comment]
These fixes are already done and will be in a version to be released soon
