### ISSUE TITLE
2.22.1 Flask Enchantment "25% reduced mana cost of skills during flask effect" reducing to 25% rather than by 25%

### ISSUE THREAD

**Issue by ttei080** [PathOfBuildingCommunity/PathOfBuilding#5273]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

I don't have a character ingame / game can't be accessed atm. 
As far as I know it works just fine ingame.

### What is the value from the calculation in Path of Building?

When toggling on a Silver Flask with "25% reduced Mana Cost of Skills during flask effect" enchanted on it, it instead reduces mana costs by 75%, reducing the mana cost **to** 25%, rather than **by**.

### How to reproduce the issue

1. Click the checkmark to activate the flask
2. The flask activates and applies the "25% reduced mana cost"
3. The mana cost is reduced by 75% instead

### Character build code

```shell
https://pastebin.com/rWYm7U5A
```

### Screenshots

![](https://i.imgur.com/VM8yBrj.png)
![](https://i.imgur.com/wkM7dnO.png)
![](https://i.imgur.com/cIheQLK.png)
![](https://i.imgur.com/CX1xLiB.png)

**Comment by Regisle** [comment]
this just happens to lineup this way due to how much other mana cost reductions you have, eg if you remove rings it goes down to -47% instead of -75% (its always reducing mana cost by 18 for your setup)

**Comment by ttei080** [comment]
ah, sorry - you're correct.
