### ISSUE TITLE
PoB no longer able to fetch characters for private accounts

### ISSUE THREAD

**Issue by TwentyFiveEx** [PathOfBuildingCommunity/PathOfBuilding#5287]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I should be able to provide a valid POESESSID and list my characters for my private account

### How does Path of Building behave?

When providing a valid POESESSID for my private account I cannot list characters on that account, I received an error "Account is private".

### How to reproduce the issue

1. Set account+character tabs to private, through pathofexile.com account management
2. Log into pathofexile.com and gather a current POESESSID
3. Open PoB and import characters for the related account, providing the POESESSID
4. Observe the "account is private" error.

### Screenshots

![image](https://user-images.githubusercontent.com/109299419/206873937-71b65aaa-6687-4a9e-9f1d-36b2dae0d980.png)
![image](https://user-images.githubusercontent.com/109299419/206873939-812f3a51-b48f-46f9-9b5e-4d5addeb6e63.png)
![image](https://user-images.githubusercontent.com/109299419/206874027-dea5484e-3631-44ae-8b5b-5ad2a97332fa.png)

I have also logged a bug on pathofexile.com, but the customer service folks moved it from the bugs forum to the "gameplay help" forum. https://www.pathofexile.com/forum/view-thread/3326049

**Comment by TwentyFiveEx** [comment]
Comparing back to 2.21.1 vs current (2.23.0), this logic change may have introduced the bug:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/compare/v2.21.1...v2.23.0#diff-9c92f7ea8e0528b99067d974565d47e61b86fb3c1eb98961299b511f9be7fe5bL452-L456

**Comment by Wires77** [comment]
That is the correct segment of code, just the wrong PR you've linked to.  A workaround would be to go into the trading pop-up on the Items tab and enter your session ID there.  It now is persisted in your settings so you don't have to enter it every time.

**Comment by TwentyFiveEx** [comment]
@Wires77 Ah, oops. Yeah I'll dig some more in a bit, find the relevant PR, and see if I can't submit a new PR that both satisfies the original intent of the change while also not breaking lookups for private account (without the workaround).  Thanks!

**Comment by TwentyFiveEx** [comment]
@Wires77 thanks! just getting around to looking at this and.. already done. you are fantastic. <3
