### ISSUE TITLE
response code 500

### ISSUE THREAD

**Issue by kepekliekmek** [PathOfBuildingCommunity/PathOfBuilding#5295]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

when i try to import a build from a pobb.in link, it should be imported.

### How does Path of Building behave?

it wont import the build and gives error "response code: 500". tried with different other links. always getting the same error. tried to give permission from firewall settings.

### How to reproduce the issue

1. press "import/export build" button
2. paste the link
3. click "import" button
4. get the error.

### Character build code

```shell
https://pobb.in/igkN1hSyP4ng
```

### Screenshots

![1](https://user-images.githubusercontent.com/120317150/206906613-1401d33b-d705-4339-90af-8e7244c924dd.jpg)
![2](https://user-images.githubusercontent.com/120317150/206906616-17810e70-1634-40f0-8e2f-224c937f8f84.jpg)

**Comment by QuickStick123** [comment]
Can you open the link in a browser? It seems to work fine for me both in PoB and browser

**Comment by QuickStick123** [comment]
Make sure you are using the latest version incase that is the problem.

**Comment by QuickStick123** [comment]
Here is a poe ninja link in the mean time hope it fixes it self eventually. https://poe.ninja/pob/LfK

**Comment by kepekliekmek** [comment]
couldnt find anything about this issue on the web. 
thank you for helping. ninja link works fine. that will do it for me thanks ^^

**Comment by QuickStick123** [comment]
I am closing this as it seems to not be related to PoB and isntead pobb.in

**Comment by Dav1dde** [comment]
@kepekliekmek I've been trying to track down this issue for a while now. It seems to depend on location, are you by any chance from Turkey?
