### ISSUE TITLE
Trade Window: Add Query Option for Required Level

### ISSUE THREAD

**Issue by TKLaracuente** [PathOfBuildingCommunity/PathOfBuilding#5297]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'd like to be able to restrict the Build Pricer "Find Best" feature to items that have Required Levels at or below my character's level. Right now, I see items for level 60+ while I'd like to search for items I can use at level 10 (for example). 

### Describe the solution you'd like

Just like the recent change here: #4866, I would like an option to query for a specific min/max Required Level. For example, this POB has Item Sets per levels, and I would love to actually search for these items per level.
<img width="648" alt="POB-Trade-Levels" src="https://user-images.githubusercontent.com/21134562/206927405-814a3f9d-cfd0-4ca3-b426-4fab06337e57.png">

### Describe alternatives you've considered

If the POB already knows what level the Item Set is intended for, this wouldn't need to be an option. Could be automatic. I don't know if that's the case with POB though. I am new here.

**Comment by TKLaracuente** [comment]
Perhaps it can be based on the required level of the item in the item set so that it doesn't require a new config option in the UI

**Comment by TKLaracuente** [comment]
@Dullson RE: #5280 any world where this is fast to roll in to the work you just did with prices? Cheers my friend!

**Comment by Peechey** [comment]
Fixed by #6595
