### ISSUE TITLE
Calculate explosive trap dps

### ISSUE THREAD

**Issue by dakraSz** [PathOfBuildingCommunity/PathOfBuilding#5300]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

 Pob doesn't calculate small explosions damage 

### Describe the solution you'd like

if i'm not wrong all small explosions can't always hit. we have to calculate as written manually

**Comment by QuickStick123** [comment]
How do you think these calculations would go could you provide a breakdown to allow this to be easier to implement?

**Comment by dakraSz** [comment]
According to the wiki, nothing mentions that they do less damage. and the pob already deals 1 burst damage. we will only write the number of hits considered and the damage will be calculated

**Comment by canercetin-randomguy** [comment]
@QuickStick123 Something closer to Storm Burst can be done. Storm Burst shows two options, one orb tick, and all ticks at the end of duration. Make Explosive Trap that there is two options, one small explosions, and all small explosions possible (not explosions that hits, every explosions that skill can deal.)

Explosive traps gem progression is already on wiki,

https://pathofexile.fandom.com/wiki/Explosive_Trap#:~:text=Explosive%20Trap%20is%20a%20spell,that's%20converted%20to%20fire%20damage.

I could help if I knew Lua, but I. hope you understood my friend and me.

**Comment by canercetin-randomguy** [comment]
This is very large scale project, and I have zero intentions to learn Lua from the ground, I will leave this to future contributors :)
