### ISSUE TITLE
Concentrated Effect support gem doesn't scale Minion Instability damage in 2.23.0 (it worked in previous versions)

### ISSUE THREAD

**Issue by Kayella** [PathOfBuildingCommunity/PathOfBuilding#5302]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

Concentrated Effect should scale Minion Instability damage because it's area damage.

### What is the behaviour in Path of Building?

Concentrated Effect doesn't scale Minion Instability damage. It just applies mana modifier.
It worked in previous PoB versions.
Minion instability still has baseflag area in skills\minion.lua.

### How to reproduce the issue

Add Minion Instability keystone.
Add SRS skill gem.
Choose skill Minion Instability.
Add Concentrated effect support gem.

### Character build code

```shell
https://pobb.in/JU1unpqNMJ8i
```

### Screenshots

![no CE](https://user-images.githubusercontent.com/70760126/206979858-99433ad5-f86d-41c8-b83c-502c2c5e933b.JPG)
![with CE](https://user-images.githubusercontent.com/70760126/206979877-53550d3d-4066-4536-9dc2-17e32bf38b1f.JPG)

**Comment by QuickStick123** [comment]
I suspect it mightn't work ingame
This is probably what caused the change in PoB
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4497

**Comment by Paliak** [comment]
yeah https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4628 likely broke it. i'll see if i can come up with a better solution.

**Comment by Kayella** [comment]
I just checked in game too. CE still affect MI (area becomes much smaller).
[https://youtu.be/a82SGDwTklY](url)
