### ISSUE TITLE
chaos golem's chao aura isn't supported by void manipulation gem and concentrated effect gem now

### ISSUE THREAD

**Issue by wantproxy** [PathOfBuildingCommunity/PathOfBuilding#5313]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

chaos golem's chao aura is supported by void manipulation gem and concentrated effect gem in 3.19

### What is the value from the calculation in Path of Building?

chaos golem's chao aura isn't supported by void manipulation gem and concentrated effect gem in 3.20

### How to reproduce the issue

You can choose chao golem's chao aura skill, then click void manipulation gem and concentrated effect gem.
You can find that the dps doesn't change.
But it works in 3.19.

### Character build code

```shell
https://pastebin.com/KrYEuKSv
```

**Comment by QuickStick123** [comment]
This going to be pretty much https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5302 but on a different minion

**Comment by Paliak** [comment]
This is different. Chaos golem is being supported by both conc effect and void manipulation but the damage mods do not seem to apply (the area mod from conc effect does work). I think it may be due to skillcfg not being applied somewhere as the damage mod on conc effect requires the area mod flag.
