### ISSUE TITLE
Trade for Items - order mods by Weighted Sum

### ISSUE THREAD

**Issue by JakubKorcak** [PathOfBuildingCommunity/PathOfBuilding#5319]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I want to be able to see weighted sums that are calculated for my build using the new feature of _Trade for these items_ ordered in descending order on the trade site. The current solution orders the mods in somewhat random order.

### Describe the solution you'd like

When the search is created, the weighted mods will be ordered from the most impactful to the least impactful

**Comment by QuickStick123** [comment]
It seems this cannot be supported and gui in PoB won't really be able to support something like this with out significant rework. Closing this as won't fix.
