### ISSUE TITLE
Account profile is private

### ISSUE THREAD

**Issue by Asael665** [PathOfBuildingCommunity/PathOfBuilding#5322]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Import my poe profile

### How does Path of Building behave?

Account profile is private using steam login or ssid
my account is not private or hiden
checked on to devices and connection same issue
reinstalled pob
Support from GGG say its not them..

**Comment by QuickStick123** [comment]
What is your account name?

**Comment by Asael665** [comment]
Madcowpatrick

**Comment by QuickStick123** [comment]
I would first double check that is not set to private. It seems to be saying it is private for me also there are a couple issue related to similar occurrences mostly being related to console or special characters in the name. You could also just try adding your poesessid and seeing if that works.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4827 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4743 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4314 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2768 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1768
![image](https://user-images.githubusercontent.com/31533893/207627073-4f80de89-35fb-42ec-b6ff-3a0657291e85.png)

**Comment by Wires77** [comment]
> Madcowpatrick

https://www.pathofexile.com/account/view-profile/Madcowpatrick is the link to your profile, which says it's private.  Are you sure that's your account name and not your character name?  As @QuickStick123 said, double check your privacy settings.  If everything is public it should look like this:
![image](https://user-images.githubusercontent.com/1209372/207632723-c0cf9dc5-c986-4aa4-ac6c-5cbec01b94ad.png)

**Comment by Asael665** [comment]
I triple checked that and i never ever set profile as private - its unchecked ofc.
Yes this is my account but i never used PoB by account i did use in kalandra SSID and this time its the same as my account - private:( i dont know what is going on.. is it possible some how steam is blocking POE? (i did setup autenticator some time ago)

**Comment by Anjimoo** [comment]
I am also having this issue. My account https://www.pathofexile.com/account/view-profile/anjimoo is not private too.
