### ISSUE TITLE
Add support for consoles leagues using build pricer

### ISSUE THREAD

**Issue by xeluh** [PathOfBuildingCommunity/PathOfBuilding#5327]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

id like to sugest u guys to put a console suport for this tool... its amazing... and u guys are doing a very good job...have  happy merry christmas and a happy new year

### Describe the solution you'd like

i saw  it yesterday for pc.. and since we got trade site for consoles too would be nice have this feature

**Comment by QuickStick123** [comment]
Could you update the title to something more useful e.g. "Add support for consoles leagues using build pricer"

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/228740467-6f7816db-6a7f-44d5-9a03-49bf17da2405.png)
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5372
