### ISSUE TITLE
Wierd overlay of items

### ISSUE THREAD

**Issue by Darootz** [PathOfBuildingCommunity/PathOfBuilding#5332]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Not having items over eachtother

### How does Path of Building behave?

All of a sudden out of nowhere I have items over eachtoher. I have already reinstalled. It does this for every PoB and every new PoB i Load. 

I made a screen what is happening 

https://i.imgur.com/iXWKv22.png

### How to reproduce the issue

No idea how to reproduce

### Character build code

```shell
Every build does it
```

### Screenshots

https://i.imgur.com/iXWKv22.png

**Comment by Wires77** [comment]
What screen resolution are you running?  Do you have a vertical monitor layout?

**Comment by Darootz** [comment]
1080 x 1920, on a portrait. But no matter what screen I use or resize the window it keeps doing it. Just started today, never has any issues. My other screens 3440 x 1440 or 1920 x 1080 do the same thing.
