### ISSUE TITLE
POB very slow after reinstall

### ISSUE THREAD

**Issue by Nicolainf** [PathOfBuildingCommunity/PathOfBuilding#5333]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Fast and responsive with low latency after mouse clicks 

### How does Path of Building behave?

After a reinstall of POB it has become very laggy and slow to a point where every action input is delayed by 4 secounds. 

### How to reproduce the issue

Navigating the application. It not a in a particular tab

### Character build code

```shell
I tried deleting all my builds thinking that might cause the issue. It did not fix the issue
```

### Screenshots

I suspect the issue is related to these codes 
![Skærmbillede 2022-12-13 213325](https://user-images.githubusercontent.com/120516743/207437916-c1c509db-1f39-4ed7-8c77-a807b68db787.jpg)

**Comment by QuickStick123** [comment]
Does this occur on older versions?
Those codes aren't the cause.
I have noticed a slightly longer launch time recently but apart from that not really any crippling slowdowns.

**Comment by Nicolainf** [comment]
Hey QuickStick123
I have just tested different releases and it occur on [2.24.0], [2.23.0], [2.22.0], [2.20.0] 
CPU - AMD Ryzen 9 5900X 12-Core Processor, 3701 Mhz, 12 Core(s), 24 Logisk(e) processor(er)
GPU - ASUS GeForce RTX 2070 ROG Strix OC
Windows 10

**Comment by Nicolainf** [comment]
I updated my GPU driver and it runs smoothly now. Thank you for the help :D
