### ISSUE TITLE
Issue with new feature

### ISSUE THREAD

**Issue by khai15** [PathOfBuildingCommunity/PathOfBuilding#5334]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

I was told that POB has a new feature that allows one to search the trade website for upgrades.  I am currently playing HC ruthless and keep getting whispers from people playing SC Sanctum every 30 seconds or so wanting to buy items because of this feature.  I think there is issue with how POB filters leagues.  

### What is the behaviour in Path of Building?

a

### Character build code

```shell
a
```

**Comment by Dullson** [comment]
HC ruthless was the default league selected on PoB Build Pricer due to changes introduced with the ruthless update.
This is already fixed and will go live with the next PoB update.
Fixed in #5280
