### ISSUE TITLE
DPS build pricer not using all affixes for calculating weights

### ISSUE THREAD

**Issue by Vindicit** [PathOfBuildingCommunity/PathOfBuilding#5339]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

The dps item pricer feature is not using all the affixes usable on weapons for minions.

### What is the behaviour in Path of Building?

![image](https://user-images.githubusercontent.com/79327480/207478333-5e000508-4587-465e-818a-d6953e11b278.png)
This is what comes out of POB

![image](https://user-images.githubusercontent.com/79327480/207478457-f4630f04-cff3-46ae-976d-084bfd613623.png)
Here are some additional affixes not being used that increase dps.

### How to reproduce the issue

Use the weapon 1 dps search feature.

### Character build code

```shell
https://pastebin.com/nzdbPxew
```

**Comment by QuickStick123** [comment]
These are missing from QueryMods.lua but are in the regular mods files. It might related to duplicate mods on different bases or weird handling of minion mods unsure though.
