### ISSUE TITLE
Two-Hand Melee Weapon damage nodes no longer giving DPS with Two-Hander equiped

### ISSUE THREAD

**Issue by dannyo13** [PathOfBuildingCommunity/PathOfBuilding#534]
Have Terminus Est in the First weapon slot. Have a Cyclone 6-link setup in skills. Noticed DPS change after latest update. Nodes on the tree with "Two Handed Melee Damage" (such as Destroyer, Titanic Impacts ) aren't effecting DPS despite having a Two Handed Melee Weapon equipped.

**Comment by Nostrademous** [comment]
Can you a PoB build pastebin? I can't reproduce.

**Comment by ganesasidd** [comment]
The same issue with staves, Pastebin provided. https://pastebin.com/8xKyPb6h

**Comment by Chrjsen** [comment]
I have the same issue with axes. Seems all "Two Handed Melee Damage" nodes no longer work with 2handed weapons. PoB from me: https://pastebin.com/x9ba5Z1G

**Comment by dannyo13** [comment]
https://pastebin.com/WXCbsLhZ
Heres a bare bones PoB demonstrating the issue https://pastebin.com/hJL6KFUt
