### ISSUE TITLE
Weight system improvements

### ISSUE THREAD

**Issue by NsHideout** [PathOfBuildingCommunity/PathOfBuilding#5350]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Im using poe weight trade search for a long time, here is what can be improved

### Describe the solution you'd like

1)U can not just build 'best dps' weights, but also include survivability, and utils. For example, u can analyse how player build his tree. Avg player with simple build spend 1 point for 5.5% health and (20% increase damage node/7 damage over time multiplier, etc..). The rate u gets from this 5%max life = 20% dmg With this u can build such weights
+1 to maximum life = 4 
+1% increased maxium life = 20
+1 increased damage = 5
if u go deeper u can see player spend 3 nodes for 30 str/int/dex, so he also weight 30 stat as 1 point. This can be weighted too then. As well as resistance, and other stuff.

2)Player probably will face the limit of searth request complexity, so u can use more 'pseudo' properties, which include explicit stats and implicit stats, and  also ignore conditional properties like 'if u have killed recently'. 

3)normalize weights to 1, which is much more human readable. and also apply some rounding maybe.

**Comment by Ebuall** [comment]
Even just for DPS, it weighs `ignite duration` very highly and does not consider `ignites deal damage faster`. We need an option to chose DPS over Combined Total Damage for ignites.

**Comment by NsHideout** [comment]
not only for ignites, It also weights hit damage on cold builds, which produce tons of actually useless stats, like crits/added damage/penetration

**Comment by NsHideout** [comment]
not only for ignites, It also weights hit damage on cold builds, which produce tons of actually useless stats, like crits/added damage/penetration

**Comment by Regisle** [comment]
number 1 is mostly solved by #5376 unsure what benefit your method has, I have another branch working on allowing you to sort by multiple stats at the same time (and choose their relative weights, eg FullDPS= 1, EHP = 0.5) which completely solves it, 

number 2) pseudo mods are probably going to be implemented for specific resistances and attributes but the other ones have issues with double counting of mods in some cases and so will probably take longer before they get implemented, 

number 3) this is unlikely to happen as it just adds extra math and actually takes away information from the user, it may look nicer if you do things like round but ultimately it isnt hard for the user to just ignore the decimal precision anyway

**Comment by NsHideout** [comment]
also u can weight 'crafted cold damage over time' as 'crafted fire damage over time' coz u can swap this easily

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5507
