### ISSUE TITLE
Oauth Instead of POESESSID

### ISSUE THREAD

**Issue by Mecze** [PathOfBuildingCommunity/PathOfBuilding#5352]
First of all.

Great job on the trade feature. Really like it.

But...
https://twitter.com/pathofexile/status/1602851059361550337?s=19

Are there any plans to use Oauth instead of POESESSID? Is so, any eta?

Thanks!

**Comment by Lilylicious** [comment]
A reddit post will be going up addressing this question. The short answer is we don't really have an answer in the short term. It's not something that will be going up soon at least.

**Comment by ryanlatini** [comment]
Closing this as complete is just improper usage of how GitHub issues supposed to work.  I understand the amount of complexity in accomplishing this is not trivial whatsoever, but leaving the issue open is supposed to be the way that any future developers who may decidethat they want to contribute to this project will identify areas that they could be willing to help with.  I was surprised that I didn't see this in the open issues in the repo and was going to submit a feature reques.  This is clearly an issue that should be addressed and closing as complete just obscures visibility into the issue for anyone in the community who is looking for any status updates on this.

**Comment by QuickStick123** [comment]
You asked a question about our plans not requesting it to be implemented there seems to some issues with not having a scope for trading with OAuth and it needing a server not currently supported directly for standalone applications. Feel free to open anouther issue requesting us to try to do this.

**Comment by ryanlatini** [comment]
I didn't ask the question...

**Comment by QuickStick123** [comment]
Apologies regardless feel free to open another issue.

**Comment by ryanlatini** [comment]
Issue has been requested.  https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5360
