### ISSUE TITLE
Poison strike skills doesn't work with Cruelty?

### ISSUE THREAD

**Issue by MadMagnetic** [PathOfBuildingCommunity/PathOfBuilding#5356]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Well. it must show DPS on left column 

### How does Path of Building behave?

It says "Skill Disabled: No usable weapon equipped"

### How to reproduce the issue

I've updated to the latest version and everything was good before I've changed Vicious Projectiles support gem to Cruelty support gem in game.
After that I've imported character and DPS info disappeared.
I even triead to download previous portable version to check if everuthing will work again, but it didn't help.
Removing gem from links - returns DPS info.

### Character build code

```shell
https://pastebin.com/rqSyhEhs
```

### Screenshots
![изображение](https://user-images.githubusercontent.com/34352955/207742455-a4efc46a-b404-477c-8435-35269df56df4.png)
![изображение](https://user-images.githubusercontent.com/34352955/207742479-cd1bf2f4-f474-4d24-8c9f-42286b92eeb6.png)
![изображение](https://user-images.githubusercontent.com/34352955/207742502-85257296-75fb-4249-8dd4-f20710a23bbb.png)
![изображение](https://user-images.githubusercontent.com/34352955/207742524-114bb725-7ce2-4468-b9c0-a625c8349ff6.png)

**Comment by QuickStick123** [comment]
You have energy blade in your offhand that should be disabled but isn't this is converting your mainhand to a sword which you can't use could you please update the title to reflect this?

**Comment by MadMagnetic** [comment]
I didn't even thought about that!
Thank you very much!
