### ISSUE TITLE
Trade finder leaving out added ele damage for weapons

### ISSUE THREAD

**Issue by mewhite42** [PathOfBuildingCommunity/PathOfBuilding#5364]
Tried to use the trade finder to find a new weapon for an ele venom gyre build.  It didn't assign weights to the adds # to # fire/cold lightning damage(local) mods so it couldn't actually find an upgrade despite numerous existing.

PoB paste bin: https://pastebin.com/63Guetrg
Generated Search: https://www.pathofexile.com/trade/search/Sanctum/lKXq0Z0UV

**Comment by QuickStick123** [comment]
Yeah it seems to be assuming it has already added the non-local one and so doesn't add the local one.
