### ISSUE TITLE
Crash when pasting certain item in items tab

### ISSUE THREAD

**Issue by Lantanar** [PathOfBuildingCommunity/PathOfBuilding#5366]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://user-images.githubusercontent.com/74542902/207976212-aae6a5e3-7491-4627-90af-643ef540b0b1.png)
![image](https://user-images.githubusercontent.com/74542902/207976450-369d9851-aa8a-4e6e-bedd-c0f761ba5d58.png)

### What are your system specifications and configuration?

OS: Windows 10 Version 22H2 Build 19045.2251
CPU: Intel i 7-9700K
GPU: NVIDIA GeForce RTX 3070, Driver Version 31.0.15.1694

### How to reproduce the issue

Copy item in PoE by hovering over it and pressing ctrl + alt + c
Open PoB
Open the item tab 
Press ctrl + v

Only happens with certain items (item with which it is reproducible shown in screenshot and pasted below)

```
Item Class: Helmets
Rarity: Rare
Ghoul Salvation
Lacquered Helmet
--------
Armour: 332 (augmented)
Evasion Rating: 330 (augmented)
--------
Requirements:
Level: 60
Str: 57
Dex: 57
--------
Sockets: G G B G 
--------
Item Level: 57
--------
45% increased Elemental Weakness Duration (enchant)
--------
{ Prefix Modifier "Flexible" (Tier: 3) — Defences }
+46(28-48) to Armour
+45(28-48) to Evasion Rating
{ Prefix Modifier "Athlete's" (Tier: 2) — Life }
+80(80-89) to maximum Life
{ Prefix Modifier "Gladiator's" (Tier: 4) — Defences }
66(56-67)% increased Armour and Evasion
{ Suffix Modifier "of the Troll" (Tier: 4) — Life }
Regenerate 41.8(32.1-48) Life per second
{ Suffix Modifier "of the Prodigy" (Tier: 8) — Attribute }
+22(18-22) to Intelligence
{ Suffix Modifier "of the Bear" (Tier: 7) — Attribute }
+20(18-22) to Strength
```

**Comment by Wires77** [comment]
PoB currently doesn't support advanced copy/paste from in-game.  If you do Ctrl+C instead of Ctrl+Alt+C, the item should work.
