### ISSUE TITLE
Bleed seems to be bugged when searching dps item with new trade search

### ISSUE THREAD

**Issue by Rdee1010** [PathOfBuildingCommunity/PathOfBuilding#5371]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

nothing in game is happening

### What is the behaviour in Path of Building?

I'm trying to search for best item dpswise for my bleed character but it dosent include phys dot multi or dot multi in the website search. the jewel i find only increase my total dps by 0.2%

### Character build code

```shell
https://pastebin.com/FHRLmh1b
```

### Screenshots

![Desktop Screenshot 2022 12 15 - 22 36 51 80](https://user-images.githubusercontent.com/120698962/208016420-7450588c-f428-486a-a489-443162645143.png)
![Desktop Screenshot 2022 12 15 - 22 37 00 33](https://user-images.githubusercontent.com/120698962/208016439-2b39343d-567a-4fd0-addb-a8ec0a39fb9f.png)

**Comment by QuickStick123** [comment]
Bleed is not currently supported useful full dps in the meantime. We are aware and working towards a fix in the future.

**Comment by QuickStick123** [comment]
Bleed dps supported now in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5525
![image](https://user-images.githubusercontent.com/31533893/222108095-abd33475-ba47-40bd-9769-4b420fc034fe.png)
