### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by tipakorn11** [PathOfBuildingCommunity/PathOfBuilding#5391]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

import my own character  normally

### How does Path of Building behave?

cannot import my own character using character's acc name  only can import form link try to allow in firewall and the rule nothing happen 

### Screenshots

![image](https://user-images.githubusercontent.com/55394461/208231319-81a75ad3-7b4b-42b4-a800-04e3b5e3c33e.png)
![image](https://user-images.githubusercontent.com/55394461/208231343-0d29fa93-c005-4285-8bed-d63d091349f2.png)

**Comment by QuickStick123** [comment]
Can you connect to ggg servers your self through a browser?

Here is a related problem but occurring with pastebin https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5169

It seemed to resolve after a while.

**Comment by aiolos01** [comment]
This happens sometimes. I haven't been able to figure out when though. Allowing svchost access through the firewall seems to fix it. The peculiar thing about this is that it usually works fine without giving svchost internet access.
