### ISSUE TITLE
Glorius Vanity nodes with incorrect values

### ISSUE THREAD

**Issue by fattay** [PathOfBuildingCommunity/PathOfBuilding#5413]
glorious vanity 6854 at pain attainment curse nodes are incorrect from in game values
![image](https://user-images.githubusercontent.com/18173000/208479915-4ec57e85-fc16-469a-a052-e42fa7cfaefb.png)
![image](https://user-images.githubusercontent.com/18173000/208480002-d26c7afd-bc76-4ef8-998c-1e713b19015f.png)

notables aswell
![image](https://user-images.githubusercontent.com/18173000/208480111-46a4170b-5c8c-4f03-bbe2-062a3f97157c.png)
![image](https://user-images.githubusercontent.com/18173000/208480162-b6d04d50-8170-4afd-8044-ad79f488e940.png)

I assume this is only for Curse effect nodes

**Comment by TheHeretric** [comment]
This also seems to happen occasionally with Elegent Hubris when they are corrupted.  The values were not correct from the PoB into the game.

**Comment by QuickStick123** [comment]
@TheHeretric I assume you are referring to curse effect? Or is this a different mod.

**Comment by Regisle** [comment]
The glorious vanity being wrong was due to them changing it in the 3.20 patch and we didnt update the LuT with that in mind, Elegent Hubris would be a differnt issue as iirc nothing about them was changed

**Comment by QuickStick123** [comment]
Closing in favour of #5634 as it covers in better detail.
