### ISSUE TITLE
When I try to open it crashes

### ISSUE THREAD

**Issue by dalems4** [PathOfBuildingCommunity/PathOfBuilding#5422]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![Bug report](https://user-images.githubusercontent.com/49256624/208845824-c39e7fae-9b32-4e5e-92a9-afc8926f082a.PNG)

### What are your system specifications and configuration?

![Bug report](https://user-images.githubusercontent.com/49256624/208845920-efcdec8a-d950-4ef0-9104-dd43088cca37.PNG)

### How to reproduce the issue

1. I download PoB
2. I get the above error messege 
3. It crashing in .5 seconds unless i spam open it so it stops responding so I can take a screenshot.

**Comment by QuickStick123** [comment]
What are your system specifications e.g. os, gpu, driver version?

Reinstall your graphics drivers and if that doesn't work

Try https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087

**Comment by dalems4** [comment]
Windows 10
gpu: Nvidia Geforce RTX 3060
driver version: 31.0.15.1694

Thanks so much for your help,
Dale

**Comment by dalems4** [comment]
The second fix worked :). You guys are awesome.

**Comment by QuickStick123** [comment]
It has a couple graphical problems we haven't ironed out but we plan on moving to that in the future as it seems much more robust to various systems.
