### ISSUE TITLE
"5% Chance to deal Double Damage" from Lethal Pride is ignored

### ISSUE THREAD

**Issue by DanielEbert** [PathOfBuildingCommunity/PathOfBuilding#5427]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

![Screenshot (5)](https://user-images.githubusercontent.com/53190379/208962877-34bc4305-2ab0-43ec-8dd7-6b6579e795f4.png)
Please have a look at the screenshot. When I allocate the 5% chance to deal double damage, I expect to get higher Average Damage.

Im not at 100% chance to deal double damage yet.

### What is the value from the calculation in Path of Building?

Average Damage is 526,759.5

### How to reproduce the issue

Import build from https://pastebin.com/temWVw10

Allocate/Deallocate the Revelry Passive Tree Node

### Character build code

```shell
https://pastebin.com/temWVw10
```

### Screenshots

![Screenshot (5)](https://user-images.githubusercontent.com/53190379/208963533-236f970f-0579-453f-8a59-57ec67f959da.png)

---

I had a quick look at the source code, and I can find some references to the Lethal Pride Karui 5% Chance to deal Double Damage. This is in the src/Data/LegionPassives.lua file:
~~~
[45] = {
	["id"] = "karui_notable_add_double_damage", 
	["dn"] = "Add Double Damage", 
	["sd"] = {
		[1] = "5% chance to deal Double Damage", 
	}, 
	["sortedStats"] = {
		[1] = "chance_to_deal_double_damage_%", 
	}, 
	["stats"] = {
		["chance_to_deal_double_damage_%"] = {
			["max"] = 5, 
			["fmt"] = "d", 
			["index"] = 1, 
			["min"] = 5, 
			["statOrder"] = 4893, 
		}, 
	}, 
},
~~~

**Comment by QuickStick123** [comment]
You have capped double damage as you chill enemies with skitterbots 
![Uploading image.png…]()
