### ISSUE TITLE
[UI/UX] Show slot type in the socket group

### ISSUE THREAD

**Issue by ryuukk** [PathOfBuildingCommunity/PathOfBuilding#5429]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I always click on individual group to remember the slot type, it gets annoying when i try to follow a guide

### Describe the solution you'd like

So i figured why not show icons?

Screenshot:

![image](https://user-images.githubusercontent.com/44361234/209033622-7351b7be-1586-4f90-9da7-aa037f295fe7.png)

![image](https://user-images.githubusercontent.com/44361234/209033558-aab16824-d6ec-4702-a703-e00a01d107a4.png)

Could be improved with a smart layout checkbox to properly group things and separate slots properly and automatically

**Comment by QuickStick123** [comment]
Could you provide a list of icons that we would be able to use without to much licensing issues?
