### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by Carelesss** [PathOfBuildingCommunity/PathOfBuilding#5430]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I can only play from macbook pls make dmg version

### Describe the solution you'd like

pls make it work on mac os m1 chip

**Comment by QuickStick123** [comment]
We previously have had no plans to support macOS unless someone on the team has a change of mind it won't happen.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4842
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5206
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1370

**Comment by Mirsgid** [comment]
> ### Check for duplicates
> 
> - [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)
> 
> ### Is your feature request related to a problem?
> 
> I can only play from macbook pls make dmg version
> 
> ### Describe the solution you'd like
> 
> pls make it work on mac os m1 chip
> 
> ### Describe alternatives you've considered
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
