### ISSUE TITLE
Add full support for essence mods in trader

### ISSUE THREAD

**Issue by Guy-BEANSPerformaceUK** [PathOfBuildingCommunity/PathOfBuilding#5433]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

Trade search should include the item modifier. 

### What is the behaviour in Path of Building?

The gloves in the POB link below have 'Socketed gems deal 30% more Damage over Time'. I copied this item and removed this mod and the build loses 1.5m Full DPS. Therefore I imagine this should be included in the item trade search weighted sum? The trade url generated also has #% increase dmg per frenzy charge, but the build url doesn't have frenzy charges ticked either.

Maybe I'm just missing something or a fool haha.

### How to reproduce the issue

Click trade for these items on the gloves whilst using the POB link below.

### Character build code

```shell
https://pobb.in/wlod7k5b3csS
```

**Comment by QuickStick123** [comment]
Can you change to title to add support for essence mods.
