### ISSUE TITLE
"Trade for items" is adding implicit damage over time mod but not explicit damage over time mod for weapon

### ISSUE THREAD

**Issue by melink14** [PathOfBuildingCommunity/PathOfBuilding#5436]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

`#% increased Damage over time` is a mod that can be crafted onto Sceptres and as expected increases damage of DoT builds. Thus when constructed trade searches, it's expected that this explicit mod is included in the list of mods.

### How does Path of Building behave?

PoB does include a Damage over Time mod but instead of the explicit mod it only includes the `Implicit` version of the mod. This means that an item with Increased Damage over time will be sorted lower in the list.

### How to reproduce the issue

- Generate trade search for a better one handed weapon on dot build (I'm using righteous fire)
- Confirm trade link lists only implicit damage over time. (example: https://www.pathofexile.com/trade/search/Sanctum/zX6EqaRt4)

### Character build code

```shell
https://pobb.in/p7LqLc8hGAo6
```

### Screenshots

![image](https://user-images.githubusercontent.com/1176550/209283971-aab1645e-b9c9-41da-a9eb-6cd797210d10.png)

**Comment by QuickStick123** [comment]
This is because it is only a crafted mod on sceptres and we currently do not handle them.
