### ISSUE TITLE
Influence mod list for 2h swords is using 1h swords

### ISSUE THREAD

**Issue by rchatrath7** [PathOfBuildingCommunity/PathOfBuilding#5448]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

List of influence mods for 2h swords should use 2h sword mod table ie https://poedb.tw/us/Two_Hand_Swords#ModifiersCalc. 

### How does Path of Building behave?

Currently, the mods listed for 2h swords are 1h mods. In this example, the shaper mods for an exquisite blades are the mods for 1h swords, such as Socketed gems are supported by Added Fire / Elemental Damage with Attacks. Suffixes also has this problem. 

<img width="436" alt="image" src="https://user-images.githubusercontent.com/9171381/209431514-40c1ddbb-4933-4210-9ac3-1830c59b8831.png">

### How to reproduce the issue

1. Create a new 2h sword with Shaper influence 
2. Open up list of mods and see it's  2h, not 1h :) 

### Character build code

```shell
n/a
```

### Screenshots

<img width="436" alt="image" src="https://user-images.githubusercontent.com/9171381/209431583-f49b3e7c-ee48-4727-8d45-538e392c60b0.png">

**Comment by QuickStick123** [comment]
A fix for this is already included in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5375

**Comment by QuickStick123** [comment]
This add support for 2h_sword/axe/mace but it has a bug where the one handed mods still apply. Due to having separate influence behaviour.
