### ISSUE TITLE
Duplicate fields in ModMaster.lua

### ISSUE THREAD

**Issue by QuickStick123** [PathOfBuildingCommunity/PathOfBuilding#5450]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Shouldn't need duplicate fields in this file.

### How does Path of Building behave?

Duplicate fields
```lua
	{ type = "Suffix", affix = "of Craft", modTags = { "attribute" }, "+(15-20) to Dexterity", statOrder = { 908 }, level = 15, group = "Dexterity", types = { ["Dagger"] = true, ["Dagger"] = true, ["One Handed Axe"] = true, ["One Handed Mace"] = true, ["One Handed Sword"] = true, ["Claw"] = true, ["Sceptre"] = true, ["Thrusting One Handed Sword"] = true, ["Two Handed Axe"] = true, ["Two Handed Mace"] = true, ["Two Handed Sword"] = true, ["Staff"] = true, ["Staff"] = true, ["Wand"] = true, ["Bow"] = true, ["Body Armour"] = true, ["Gloves"] = true, ["Boots"] = true, ["Helmet"] = true, ["Shield"] = true, ["Ring"] = true, ["Amulet"] = true, ["Quiver"] = true, }, },
```
Dagger occurs twice and so does staff. This might be cause problems related to which items can have certain crafting mods but I am not sure.

### Screenshots

![image](https://user-images.githubusercontent.com/31533893/209434390-4c5acc68-e16e-4146-811c-c4f75be36e7e.png)
![image](https://user-images.githubusercontent.com/31533893/209434409-107f286b-b154-4b45-8ec8-aeb1a6e17fd9.png)

**Comment by Paliak** [comment]
Afaik lua tables are hash maps so it shouldn't matter but would be nice to cleanup nevertheless.
