### ISSUE TITLE
The Calculation for a negative resistance is incorrect for "reduced percent resistance"

### ISSUE THREAD

**Issue by TheHeretric** [PathOfBuildingCommunity/PathOfBuilding#5455]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

There was a previous issue regarding this, but it is still in the PoB.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5111

What currently happens is the %## reduced resistance increases resistances when the resistance is negative, which is not the intended calculation.  

Before Equipping Annihilating Light
![image](https://user-images.githubusercontent.com/121370728/209457558-5b714ac7-806d-4c3b-a591-27b65d9b8d52.png)

After Equipping Annihilating Light
![image](https://user-images.githubusercontent.com/121370728/209457566-e4af2dec-8139-4e29-8981-71312c0e8eef.png)

The resistance should be -99% resistance, instead it calculates to -21%. 

This behavior persists even after the value is positive.  Any percent reduced is actually displayed as a increase instead.

### What is the value from the calculation in Path of Building?

Resistance reduction is not applying a negative resistance reduction, but instead a resistance gain, when the resistance being reduced is already negative.  

### How to reproduce the issue

1.  Equip an item, such as, Annihilating Light when a resistance is negative it will increase instead.  This is true for all "#% reduced RESIST".  There are a handful of items that all have the same interaction.
2.  Notate the negative resistance before and after the item.  An increase is incorrect as it should decrease by the value instead of increase.

### Character build code

```shell
https://pastebin.com/vRHd9PtZ
```

### Screenshots

![image](https://user-images.githubusercontent.com/121370728/209457818-88db34e8-b8bb-4b48-8d9d-6a4b411e6a3e.png)

![image](https://user-images.githubusercontent.com/121370728/209457820-11af072d-1b66-45fb-8429-782b6ddac309.png)

![image](https://user-images.githubusercontent.com/121370728/209457824-426a7153-32d0-4619-9894-3c4586874d1b.png)

![image](https://user-images.githubusercontent.com/121370728/209457829-a11459ac-fa41-44d6-b85b-0326665ba861.png)

**Comment by QuickStick123** [comment]
You don't understand how this stat works. Reduced resistances acts as a multiplier on your resistances so annihilating light's 65% reduced resistances will multiply -60 * 0.35 = -21 Resistance which is correct. What might be incorrect is equipping cowl of thermophile and annihilating light giving more than 100% reduced resistance producing positive numbers.

**Comment by QuickStick123** [comment]
Testing ingame see this capped at 0% this is the only bug detailed within this issue
![image](https://user-images.githubusercontent.com/31533893/209458451-66ed3153-ba57-44e9-af21-da48d7fe3d5f.png)

**Comment by TheHeretric** [comment]
Ah I see, so I was half correct in the bug report.  Thanks for the info.  I knew _something_ was wrong, just wasn't quite on the mark with what.  

Thanks for the info and all the work you all do.
