### ISSUE TITLE
Tree Colorblind Options

### ISSUE THREAD

**Issue by OzoneOOO** [PathOfBuildingCommunity/PathOfBuilding#5462]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

There are several colorblind mode options for the tree POWER nodes. However, I have significant issues seeing the comparison colors. For me personally, I cannot tell what is green vice the yellow color of the normal modes, especially on a red Mastery. However, other colorblind persons have different needs, having the options from the Power node accessibility options would probably be fine for everyone. I know I would appreciate it being Red&Blue, which is an option. 

### Describe the solution you'd like

Add/Transfer already present colorblind options for power nodes on the tree to the comparison function. 

### Describe alternatives you've considered

The actual colors could be changed, I guess. Though the base colors that are drawn from GGG themselves likely can't be changed. If you just changed the colors to something it may work, but options are always better. 

Also, if there's simply a list of nodes to be added and nodes to be subtracted, that would work for all colorblind people. Seems extra work, but it would be best. 

### Additional context

I can't show you what I see because it's unique to my eyes. Sorry. But 10% of men and 1% of women are colorblind, so this will help a lot of people. Plus I won't have to ask my wife anymore what nodes I'm missing. I'll send her thanks!

**Comment by QuickStick123** [comment]
So you want red and blue available for mod tooltips as well? Custom colours might be a good idea to try and support as well.
![image](https://user-images.githubusercontent.com/31533893/209484030-f0824447-844c-45c6-a434-4820730a9b67.png)

**Comment by OzoneOOO** [comment]
The red is hard for me to read in this example, but it's not impossible and since the two colors are very different, no information is lost. And not all colorblind people have red darkness issues like me. 

It poses a problem, because green and blue would be better for text, but red and blue for the tree. It has to do with the background color or relative color. 

I wouldn't complain about custom colors, but that's honestly probably not necessary.

**Comment by MaxBQb** [comment]
+1 to amount of people who can't read red colored text on dark background
