### ISSUE TITLE
Importing builds containg minion aura's causes crashes if their gem level is deleted

### ISSUE THREAD

**Issue by QuickStick123** [PathOfBuildingCommunity/PathOfBuilding#5476]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://user-images.githubusercontent.com/31533893/209755418-0d564965-802d-420b-9a6d-a7fb436bdd73.png)
XML missing 3 fields upon import
![image](https://user-images.githubusercontent.com/31533893/209756062-e8d6e8bf-30d2-4630-b86b-cfb1830865d8.png)

### What are your system specifications and configuration?

Not releveant for this crash.
Is on dev branch and 2.24 release.

### How to reproduce the issue

1. Import this dudes profile either from poe.ninja or directly. Account: oslo663, Character: Kasza_chills
https://poe.ninja/challenge/builds/char/oslo663/Kasza_chills
2. Delete the gem level
3. Observe Crash

This is an identical crash as #5435 #5393 #2489 but is easily caused and isn't the result of minion garbage stuff on gems.

### Character build code

```shell
https://pobb.in/TtxzRkZOLCaJ
```

**Comment by Paliak** [comment]
This is most likely related to https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4724

Changing:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/3f843fb2f0f445ed94395fc1fb5ebc18bc4c3e2a/src/Classes/SkillsTab.lua#L668

to:

```LUA
gemInstance.level = tonumber(buf) or self.displayGroup.gemList[index].defaultLevel or self:ProcessGemLevel(gemInstance.gemData) or 20
```

Seems to fix it but i'm not sure if that's the desired behavior.
