### ISSUE TITLE
Ailment/Poison DPS modifier not working

### ISSUE THREAD

**Issue by Unpixelt** [PathOfBuildingCommunity/PathOfBuilding#548]
Due to changes in wording/in the tree it seems that ailment DPS (atleast for poison) is broken.
The stat "Claw Attacks deal X% increased Damage with Hits and Ailments" doesn't affect
poison dps at all.

Before it was spread over 2 seperate modifiers 
(Increased damage with Claws and Increased Damage with Ailments from Attack Skills while wielding a Claw)

Example of 3.9 Tree
![3 9 Tree PDPS](https://user-images.githubusercontent.com/62096973/76508285-6c92ad00-644e-11ea-909c-e09c9c8b6288.png)

Example of 3.10 Tree
![3 10 Tree PDPS](https://user-images.githubusercontent.com/62096973/76508293-6ef50700-644e-11ea-9c7b-5f60e487eb31.png)

**Comment by LocalIdentity** [comment]
Fixed as of 1.4.159.1
