### ISSUE TITLE
Kalandra's Touch ring not working

### ISSUE THREAD

**Issue by kleind** [PathOfBuildingCommunity/PathOfBuilding#5486]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Equip any ring. Equip Kalandra's Touch. See "any ring"'s stats duplicate.

### How does Path of Building behave?

Kalandra's Touch does nothing.

### How to reproduce the issue

Create new build.
Add any ring. For example: "Chaos Resistance Ring" from the rare example rings.
Notice how chaos res goes from -60 to -17
Add Kalandra's Touch ring.
Notice that chaos res is unchanged. Kalandra's Touch does not replicate the other ring.

### Character build code

```shell
https://pastebin.com/GA0NBibn
```

**Comment by Paliak** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5445 and https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5442 . Currently on dev will be in new release.
