### ISSUE TITLE
Panopticon gives +1 totem limit for skills supported by earthbreaker

### ISSUE THREAD

**Issue by bobanobahoba** [PathOfBuildingCommunity/PathOfBuilding#5488]
![image](https://user-images.githubusercontent.com/67874326/209928202-8c9b11c8-1d5a-4533-bd8d-5d0503b05aaf.png)

Panopticon should not give +1 totem limit to earthbreaker totem skills.

**Comment by Paliak** [comment]
This is due to Volcanic fissure being a slam and having the `RangedAttack` skill type which the +1 mod from Panopticon requires.
