### ISSUE TITLE
Spell/Attack Damage Modifiers apply to ailments

### ISSUE THREAD

**Issue by joris-s-k** [PathOfBuildingCommunity/PathOfBuilding#549]
![bug](https://user-images.githubusercontent.com/19972862/76515263-969d9c80-6459-11ea-9539-5caf31a5837b.png)

Per the title. All modifiers to spell damage also apply to ailments when they shouldn't.

**Comment by joris-s-k** [comment]
![grafik](https://user-images.githubusercontent.com/19972862/76515603-26434b00-645a-11ea-87cc-48413736ffd7.png)
The same is true for attack damage.

**Comment by joris-s-k** [comment]
![grafik](https://user-images.githubusercontent.com/19972862/76516776-55f35280-645c-11ea-922a-39845fa6b5c3.png)
And Area Damage

**Comment by LocalIdentity** [comment]
Fixed in 1.4.159.1
