### ISSUE TITLE
Trade for Items does not add fire multi or dot multi to jewels on an ignite build

### ISSUE THREAD

**Issue by Rottenbeer** [PathOfBuildingCommunity/PathOfBuilding#5493]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I'm searching for a jewel for my EK Ignite build and want to improve on my ignite damage.
The Trade for these items function is amazing for that and I used it for other builds.
Sadly, the calculation for the mods is incorrect, I get this search: https://www.pathofexile.com/trade/search/Sanctum/pgVQgvvi0 and it does not include burning damage or any sort of multiplier for DOTs.

Do I need to configure this somewhere?

### How does Path of Building behave?

I expect mods like those:
(14-16)% increased Fire Damage
(16-20)% increased Burning Damage
(10-12)% increased Damage over Time
+(4-6)% to Damage over Time Multiplier
+(6-8)% to Fire Damage over Time Multiplier
Damaging Ailments deal damage (4-6)% faster

to be included in the results.

### Character build code

```shell
https://pastebin.com/fcTFZN8M
```

**Comment by QuickStick123** [comment]
Use full dps in the mean time ignite dps is not yet supported.

**Comment by QuickStick123** [comment]
Ignite dps supported now in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5525
