### ISSUE TITLE
Original Sin unique missing

### ISSUE THREAD

**Issue by Haaxxx** [PathOfBuildingCommunity/PathOfBuilding#5505]
The Sanctum unique ring is missing from the PoB fork unique database.

Here's a copy-paste of the code:

Item Class: Rings
Rarity: Unique
Original Sin
Amethyst Ring
--------
Requirements:
Level: 52
--------
Item Level: 85
--------
+18% to Chaos Resistance (implicit)
--------
All Elemental Damage Converted to Chaos Damage
Nearby Enemies' Chaos Resistance is 0
--------
Innocence rose to godhood not on inspired faith,
but on the vilification and hatred of another.
--------

**Comment by QuickStick123** [comment]
All ready added in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5426 will be in next release
