### ISSUE TITLE
Error Messages on Starting up 

### ISSUE THREAD

**Issue by Firandel** [PathOfBuildingCommunity/PathOfBuilding#5508]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When staring up these Errors appears

### How does Path of Building behave?

sometimes this window disapear, sometimes not

### How to reproduce the issue

Just starting my pob

### Screenshots

![image](https://user-images.githubusercontent.com/121755390/210171694-0a4a8cbd-e3d3-4381-a7ca-4701071c0aef.png)

**Comment by QuickStick123** [comment]
Does PoB work normally cause those errors are expected.

**Comment by Firandel** [comment]
oh,... ok, thanks for this quick reply!
