### ISSUE TITLE
Slayer "Impact" node gives too much damage

### ISSUE THREAD

**Issue by Bretteur** [PathOfBuildingCommunity/PathOfBuilding#552]
![image](https://user-images.githubusercontent.com/62105868/76528036-788f6680-6470-11ea-908a-8a74018034e9.png)
using dualwielding swords, if that matters. Does not appear to be affected by skills as I tried cyclone, leap slam, bladestorm.

**Comment by Carrybag1** [comment]
I've noticed this as well using this POB - https://pastebin.com/HhtKcz1x

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.1
