### ISSUE TITLE
"Chance to Suppress spell damage for each dagger youre wielding" not calculating with Acrobatics

### ISSUE THREAD

**Issue by foodoo89** [PathOfBuildingCommunity/PathOfBuilding#5527]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

The dagger mastery to gain spell suppression per dagger wielded is not properly counting towards spell dodge when acrobatics is allocated. 
I have tested this in game to see if it works and it definitley counts in game
![Acrobatics bug](https://user-images.githubusercontent.com/11433627/210357454-fce7a860-65f0-4424-9381-5f9840ffac19.png)
![Acrobatics bug 2](https://user-images.githubusercontent.com/11433627/210357466-2cc6f0de-6cfb-49a0-8fca-31f24d4672c3.png)

### What is the value from the calculation in Path of Building?

The spell dodge in the screen shots supplied should have gone from 58 to 53 after removal of the mastery, however there was no change

### How to reproduce the issue

equip a dagger (or 2)
allocate the dagger mastery
allocate acrobatics

### Character build code

```shell
https://pastebin.com/ZCH3cAFz
```

**Comment by QuickStick123** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5089 Is probably relevant here. The config would also need to be applied to the dodge calculations.

**Comment by Paliak** [comment]
@QuickStick123 i'll make a pr.
