### ISSUE TITLE
Nodes selected using an "Impossible Escape" unique jewel are de-selected if you exit the build and re-enter.  

### ISSUE THREAD

**Issue by DARCRY1** [PathOfBuildingCommunity/PathOfBuilding#5535]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

After saving a build with nodes made accessible by an "Impossible Escape", the nodes selected using that jewel should remain selected when sharing or exiting then reopening a build.

### How does Path of Building behave?

In my current build, I am using an "Impossible Escape" jewel centered on Minion Instability in order to select the Wicked Ward keystone. When sharing my build or entering the PoB again, Wicked Ward (and any other selected nodes) are no longer selected. 

### How to reproduce the issue

1: Open PoB link given below.
2: See there is no Wicked Ward selected. 
3: Check that an Impossible Escape keyed to Minion Instability is in socket #9. 
4: Re-select Wicked Ward or any other nodes around around Minion Instabillity.
5: Save the build, exit the build.
6: Open the build, see there is no Wicked Ward selected. 

### Character build code

```shell
https://pastebin.com/YyfKWNyn
```

### Screenshots

https://user-images.githubusercontent.com/121917035/210480416-903c8dda-8652-4429-b5da-b8ea513964b8.mp4

**Comment by QuickStick123** [comment]
You cannot use a impossible escape in a cluster jewel this is why the ring is not showing but due to a bug https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4659 it still lets you allocate nodes even though they don't get saved. If you wish for this too not happen place it in a valid socket.
