### ISSUE TITLE
Bane of Legends conditional attack speed not working

### ISSUE THREAD

**Issue by Sunscorcher** [PathOfBuildingCommunity/PathOfBuilding#554]
Slayer Bane of Legends "Gain 10% increased attack speed for 20 seconds when you kill a rare or unique enemy does not appear to be working. With Bane of Legends allocated, checking or unchecking the box "Killed a Rare or Unique Enemy Recently" does not affect attack speed or damage at all.

Pastebin of build affected:

https://pastebin.com/pfqsmwNa

This can be worked around by adding 10% attack speed to a jewel.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.1
