### ISSUE TITLE
Trade Error

### ISSUE THREAD

**Issue by FlyingTornado1** [PathOfBuildingCommunity/PathOfBuilding#5544]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Should be getting the Price

### How does Path of Building behave?

When i try getting Trade Price i get an Lua Error

### How to reproduce the issue

Try to price an item

### Character build code

```shell
https://pastebin.com/15hefwwu
```

### Screenshots

https://imgur.com/a/DQTzI3L

**Comment by QuickStick123** [comment]
Might be related to no internet / lack of connection to ggg severs? Was there a particular slot you were trying to price check for?

**Comment by FlyingTornado1** [comment]
No all slots don't work. It did work before i updated to the newest version tough.

**Comment by QuickStick123** [comment]
I get a variety of crashes when testing without an internet connection but I can't reproduce yours so must be a special kinda of failure.
