### ISSUE TITLE
Elemental Hit Damage Selection

### ISSUE THREAD

**Issue by DirtyRedDirt** [PathOfBuildingCommunity/PathOfBuilding#5546]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Elemental hit does not correctly show cold and lighting damage when selected in the skill tab.

### Describe the solution you'd like

The damage type should be selectable in the "Configuration" tab, ideally with a drop-down menu with the three different elements.  An example would be something like "Elemental Hit Damage Override".

### Describe alternatives you've considered

Currently, there is no method for calculating the damage for the cold or lightning damage types.

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/210766149-fbc0cae8-fca4-44da-8faa-d0c366a68797.png)
The skill parts have cold / lightning?

**Comment by DirtyRedDirt** [comment]
My apologies
