### ISSUE TITLE
Modifiers missing from Wrecking Ball node

### ISSUE THREAD

**Issue by howtoeat6** [PathOfBuildingCommunity/PathOfBuilding#555]
What Wrecking Ball does in the game:
20% increased Damage with Two Handed Weapons
10% increased Attack Speed with Two Handed Melee Weapons
20% increased Damage with Ailments from Attack Skills while wielding a Two Handed Weapon
20% increased Stun Duration with Two Handed Melee Weapons on Enemies

What Wrecking Ball does in Path of Building 1.4.159.1:
10% increased Attack Speed with Two Handed Melee Weapons
20% increased Stun Duration with Two Handed Melee Weapons on Enemies

**Comment by LocalIdentity** [comment]
You are looking at the 3.10 tree which removed a couple of those mods from how it looked in 3.9
