### ISSUE TITLE
false-positive no enough mana cost warning

### ISSUE THREAD

**Issue by aboveyunhai** [PathOfBuildingCommunity/PathOfBuilding#5554]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

`[curse]`-`[hextouch]`-`[attack skill]`, curse is triggered by the attack skill doesn't cost mana.
So as long as you have mana to use that attack skill, it work in game.

### What is the value from the calculation in Path of Building?

`no enough mana cost warning` as long as the `curse` linked by `hextouch`, `valid attack skill` exceeds the unreserved mana

### How to reproduce the issue

The picture I post includes everything except the `Astramentis Onyx Amulet`. I used it to hide the stat requirement warning.

### Character build code

```shell
https://pastebin.com/f65yqbg3
```

### Screenshots

![image](https://user-images.githubusercontent.com/35160613/210933486-23252a07-646d-4799-8f77-f9ee663bab04.png)

![image](https://user-images.githubusercontent.com/35160613/210933418-31e80966-cccb-4953-abde-b24f4946512f.png)

**Comment by Paliak** [comment]
This will be properly fixed in #4599 as it adds proper support for hextouch but i'll see if i can come up with an acceptable solution for current dev branch.
