### ISSUE TITLE
Outdated tooltips for map curses

### ISSUE THREAD

**Issue by slaren** [PathOfBuildingCommunity/PathOfBuilding#5560]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording ingame?

In configuration -> map modifiers and player debuffs, the tooltip of some curses says that mid tier maps apply a level 10 version of the curse and high tier maps a level 15. However, this seems to be incorrect, and now this mod applies a level 1 curse in all maps.

The list of curses with this wording in the tooltip is (at least): elemental weakness, enfeeble, temporal chains, vulnerability.

### What is the wording in Path of Building?

N/A

### Character build code

```shell
N/A
```

### Screenshots

![image](https://user-images.githubusercontent.com/2141330/211051191-302336a3-1039-4a6f-9320-17be397ea953.png)

**Comment by slaren** [comment]
According to [this comment](https://www.reddit.com/r/pathofexile/comments/104entv/questions_thread_january_06_2023/j37b1y5/) this has been the case since 3.12, but I couldn't verify this from the patch notes.

**Comment by QuickStick123** [comment]
This is solved by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5074 redoing all of this code.
