### ISSUE TITLE
NR Crash Upon equipping Relic of the Pact, Rathpith Globe, and two Essence Worms

### ISSUE THREAD

**Issue by TheBugDude** [PathOfBuildingCommunity/PathOfBuilding#5568]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://user-images.githubusercontent.com/122145510/211138639-cee5d0db-de76-4156-a459-c738a7fb4e46.png)

### What are your system specifications and configuration?

Windows 10
GTX 2060 Super

(Further information not applicable, this bug has already been tested across several devices and is duplicable)

### How to reproduce the issue

1. Open a new build
2. Equip "Relic of the Pact"
3. Equip "Rathpith Globe"
4. Equip "Essence Worm" in Ring 1 slot
5. Equip "Essence Worm" in Ring 2 slot

- Not Responding then crash -

**Comment by Aesir7** [comment]
2 essences worm and relic of the pact is enough to make the app crash. 1 essence worm and relic of the pact doesn't crash.
No matter what item you equip last.

**Comment by breezystatic77** [comment]
I was able to reproduce this bug in another way.

- Equip Relic of the Pact
- Add `100% Reduced Reservation Efficiency` as a custom modifier.

Game will crash for any Reduced Reservation Efficiency value >= 100% when Relic of the Pact is equipped.
