### ISSUE TITLE
"Chance to avoid being shocked during effect" mod on flask doesn't work with stormshroud

### ISSUE THREAD

**Issue by Steven-lin97** [PathOfBuildingCommunity/PathOfBuilding#5570]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

When stormshroud is equipped, use a flask with "# chance to avoid being shocked during effect" should increase the chance to avoid all elemental ailments.

### What is the behaviour in Path of Building?

Only the shock avoidance chance was modified.

### How to reproduce the issue

Check the "avoidance" field in the Calculation tab.

### Character build code

```shell
https://pastebin.com/LKTAF6GK
```

**Comment by QuickStick123** [comment]
It seems to stop working if it has flask effect applied to it.

**Comment by luc4sdreyer** [comment]
I've noticed the same thing. It works in game, but not in PoB.

Setting "100% chance to avoid being shocked" in Custom Modifiers also doesn't work with Stormshroud. It only shows chance to avoid shock, instead of all elemental ailments.

**Comment by QuickStick123** [comment]
The 100% chance thing is simply because of the way we have programmed immunities to apply. It would require more refactoring to probably fix this but this is not the issue with the flask afaik it seem that when they get scaled by flask effect they no longer end up in the modlist that we are checking for conversion or something strongly related.

**Comment by Lilylicious** [comment]
Appears to work in current version.
