### ISSUE TITLE
Better ordering/filtering for eldritch implicits

### ISSUE THREAD

**Issue by Pyromancer404** [PathOfBuildingCommunity/PathOfBuilding#5579]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Currently, applying eldritch implicits to items is pretty unintuitive:
- The mods are all jumbled out of order between their normal, unique and pinnacle versions
- Inside a single mod, the order of tiers goes 4 -> 5 -> 6 -> 2 -> 1 -> 3

### Describe the solution you'd like

I would like to have a second box below "source" that allows me to filter normal/unique/pinnacle mods, as i do believe most users only want to see one category at a time

I would also like the mods to be ordered from 1 to 6

### Describe alternatives you've considered

n/a

### Additional context

![image](https://user-images.githubusercontent.com/51353245/211997484-a66e5e7b-f944-4852-9bee-30133fed78c8.png)

**Comment by Regisle** [comment]
This was closed already but functional duplicate of #4939, mod ordering is broken in PoB atm
