### ISSUE TITLE
Sandstorm Visage, base crit mode bugged after the latest patch.

### ISSUE THREAD

**Issue by xecutable** [PathOfBuildingCommunity/PathOfBuilding#5583]
Sandstorm visage, makes the crit of your spell to be based on your weapon crit. It used to work, until today. Took the helmet on and off no change. My hideout crit is close to like 40% less than what PoB shows atm. It was fine yesterday.

**Comment by yingkhun** [comment]
Yes me too but for some Sandstorm work for a quick fix I copy other Sandstorm in ninja to PoB its works LOL

**Comment by QuickStick123** [comment]
The wording has changed recently just use an item with the old wording.

**Comment by yingkhun** [comment]
> The wording has changed recently just use an item with the old wording.

can you share old wording?
