### ISSUE TITLE
Wrong sorting/Calculation when using Show node power -> full DPS 

### ISSUE THREAD

**Issue by doridugandzic** [PathOfBuildingCommunity/PathOfBuilding#5586]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

The full DPS sorting option for the tree should show the results of all nodes required up to the allocated notable, rather than just the notable, when sorting.

### How does Path of Building behave?

The sorting provides an incorrect sorting value, where (when sorted) option 2 appears to give less damage than option 3, with the same number of points.

The full DPS node power calc only lists the DPS of the notable, rather than the entire path up to the point.

You can see the matching numbers in the node list and on the notable for Relentless (198k full DPS).

This is most easily noticeable when checking out nodes where small passives also give a certain amount of damage - image below for Acrimony. 

### How to reproduce the issue

1. Show node power, sorted by Full DPS
2. In the power report, note the first few skills
3.  Full DPS doesn't correspond with the full DPS given by all of the nodes allocated to get to the notable

### Character build code

```shell
https://pastebin.com/UbQ6ynPb
```

### Screenshots

![image](https://user-images.githubusercontent.com/60176519/212296199-41003ff7-204f-4dd5-8c39-8260f46aa89f.png)
![image](https://user-images.githubusercontent.com/60176519/212296323-808b4739-3bf2-43a3-a82d-4a1cd27c84eb.png)
![image](https://user-images.githubusercontent.com/60176519/212297464-8b6cebc2-415f-411f-9d59-a9a7c61ce559.png)

**Comment by QuickStick123** [comment]
This intended. If you want the allocating all nodes number to be shown that would be a feature request. If you want the strongest per point node sort by that field. If you want the strongest node sort by that field.

**Comment by QuickStick123** [comment]
Open another issue requesting the addition of this if you like though as it should be fairly easy to add.
