### ISSUE TITLE
inspiration charges remains checked after removing inspiration gem

### ISSUE THREAD

**Issue by waenc** [PathOfBuildingCommunity/PathOfBuilding#559]
Steps:
1. Add Inspiration Support gem as support to a skill gem.
2. Check "Do you use Inspiration Charges?" in "Configuration" tab
3. Remove Inspiration Support
4. "5 Inspiration Charges" is still displayed in "Combat Buffs" line on "Calcs" tab

It doesn't appear to be adding the Inspiration bonus after removing the gem, only the text.

**Comment by BassOfBass** [comment]
Honestly it should be checked by default. It always gets lost in the sorting queue, despite being a mid-tier damage support.

**Comment by Wires77** [comment]
Fixed in 2.0.0
