### ISSUE TITLE
[Question] How to open PoB directly from pobb.in?

### ISSUE THREAD

**Issue by OmikronGamma** [PathOfBuildingCommunity/PathOfBuilding#5590]
Hi, there is a button on pobb.in, which should open given build in PoB, without the need to copy link, then go ti import/export etc. It was working for me, but i had reinstall windows and now its not working. I remember i installed some browser extension or some such, but i forgot what exactly i did. Any one can help me here?

**Comment by Wires77** [comment]
Have you reinstalled PoB using the installer?  That's what sets up that link for you, so try that first.

**Comment by OmikronGamma** [comment]
OK, that worked. Thanks.
