### ISSUE TITLE
Crash when trying to import my character Items and gems

### ISSUE THREAD

**Issue by Filer169** [PathOfBuildingCommunity/PathOfBuilding#5592]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://user-images.githubusercontent.com/113728646/212502779-fe419306-fb59-4ae3-8d1d-eb6011130646.png)

### What are your system specifications and configuration?

Windows 10
Intel Core i5-9300H
16GB RAM
NVIDIA GeForce GTX 1660 Ti

### How to reproduce the issue

1. Click Import/Export Build
2. Press Start with my character
3. Import Passive Tree and Jewels (everything fine after this)
4. Import Items and Skills
5. App crashes

### Character build code

```shell
I can't provide a build code because I can't import my character to PoB
```

**Comment by QuickStick123** [comment]
What is the character name as this is probably important in regards to this.

**Comment by Filer169** [comment]
My IGN: TwojStaryThor and account name is Filer1699, I didn't have any problems with this character but after I swapped my Prism Guardian to The Squire I can't open it because it crashes

**Comment by QuickStick123** [comment]
This is what it's crashing on seems to be related to offhand abyssal sockets not being handled correctly.
![image](https://user-images.githubusercontent.com/31533893/212536825-325703f2-c6d8-4ead-96b6-60b4cbf447af.png)

**Comment by QuickStick123** [comment]
Going to keep this open so it gets fixed.

**Comment by Paliak** [comment]
This is going to be hard to debug without being able to reliably replicate. ([Filer169](https://github.com/Filer169) has removed the jewel from offhand so it no longer crashes on import)

**Comment by Unknown-Guy** [comment]
@Paliak  My example in #5576 still valid.

**Comment by Paliak** [comment]
```diff
-     slotName.."Swap Abyssal Socket "..i, "Abyssal #"..i)
+     slotName.." Swap Abyssal Socket "..i, "Abyssal #"..i)
```
Fun.
I wonder whether this will break some saved builds.
