### ISSUE TITLE
Blade Vortex with Cast on Channeling shows more than 10 Blades 

### ISSUE THREAD

**Issue by Ayyes** [PathOfBuildingCommunity/PathOfBuilding#5597]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

n/a

### How does Path of Building behave?

n/a

### How to reproduce the issue

n/a

### Character build code

```shell
n/a
```

### Screenshots

![image](https://user-images.githubusercontent.com/122755862/212570980-c4a6fdd8-571f-48dd-b978-61aa9a9405d0.png)

**Comment by Paliak** [comment]
Not sure what the issues is here as you're in the picture you've attached you're showing the blades count config for blade blast and not blade vortex. A socket group with Cyclone-CwC-Blade Vortex seems to behave correctly.
