### ISSUE TITLE
Incorrect effect of turbulent cata

### ISSUE THREAD

**Issue by JustTimeToSuffer** [PathOfBuildingCommunity/PathOfBuilding#5614]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [ ] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?
![image](https://user-images.githubusercontent.com/123202230/213784574-418d8f02-4df9-4730-b1f3-8a4ddb0c1e79.png)
![image](https://user-images.githubusercontent.com/123202230/213786275-56b148e1-6afc-4a6c-92b2-8b171fa8d99b.png)

### What is the value from the calculation in Path of Building?
[![image](https://user-images.githubusercontent.com/123202230/213782650-705b4114-6cf5-4889-829f-49a9d53b7440.png)
](url)
![image](https://user-images.githubusercontent.com/123202230/213785291-a5c16271-4832-4241-9aa6-c3dd845934d9.png)

### How to reproduce the issue
When i checked in PoB, turbulent catalist scaled 4 stats on The Taming ring instead of 2 (all mods except resistans mods)
The last stats
> 12% Chance to Freeze, Shock and Ignite
> 24% increased Damage with Hits and Ailment per Freeze, Shock and Ignite on Enemy
is scaled, but in-game isn't
And it's havent Damage+Elemental tag, only Damage or Elemental (here is second issue at all, extra tag elemental on "increased damage for ailment" mod, i think)
Not checked at another jewelery, but maybe in Turbulent cata code missed second tag (Damage)

Cheched on Valaco Sign ring, and there the same - turbulent cata scaled the shock chance mod, which hasnt tag "Damage"

1. Open Items tab in PoB
2. Open The Taming Prismatic Ring in PoB
3. Select in Catalist -> Turbulent
...
Profit (u get scaled all mods except resistanses, but in game - not)

or
1. Open Items tab in PoB
2. Open Valaco Sign Topaz Ring in PoB
3. Select in Catalist -> Turbulent
...
Profit (u get scaled chance to shock mod, but in game - not)

### Character build code

```shell
https://pastebin.com/AJ3QPdQb
```

### Screenshots

[![image](https://user-images.githubusercontent.com/123202230/213782650-705b4114-6cf5-4889-829f-49a9d53b7440.png)
](url)
![image](https://user-images.githubusercontent.com/123202230/213784574-418d8f02-4df9-4730-b1f3-8a4ddb0c1e79.png)
![image](https://user-images.githubusercontent.com/123202230/213785291-a5c16271-4832-4241-9aa6-c3dd845934d9.png)
![image](https://user-images.githubusercontent.com/123202230/213786275-56b148e1-6afc-4a6c-92b2-8b171fa8d99b.png)

**Comment by JustTimeToSuffer** [comment]
Its actual only for checking in pob and theorycrafting, if u import build by the game - its importing correctly

**Comment by QuickStick123** [comment]
Should be fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4467
