### ISSUE TITLE
Wandslinger does not work properly with Spell Damage increases and reductions

### ISSUE THREAD

**Issue by paraschenko** [PathOfBuildingCommunity/PathOfBuilding#562]
Wandslinger's mod about Spell Damage applying to attacks while wielding a wand does not work.

With Wandsligner node selected there are no DPS changes highlighed when selecting any of spell-damage nodes (e.g. Spell Area of Effect and Damage). And spell-damage nodes are not colored when "Show Node Power" is enabled.

**Comment by LocalIdentity** [comment]
Will be fixed in the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.1
