### ISSUE TITLE
ancestral bond And other skill gems

### ISSUE THREAD

**Issue by BeyondSteaLikez** [PathOfBuildingCommunity/PathOfBuilding#5622]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

i have ancestral bond and if i untick the flame dash it show that i loose dmg but i dont do dmg myself so this should never give you dmg 

### What is the behaviour in Path of Building?

Tick Flame dash gives you dmg with ancestral bond 
![image](https://user-images.githubusercontent.com/21991887/213971380-5b36f768-533e-4e38-8090-18c511433d7f.png)
![image](https://user-images.githubusercontent.com/21991887/213971424-aa8a6925-63ec-4778-958b-3f5b8fad5ec2.png)

### Character build code

```shell
https://pastebin.com/fR4SZ019 here is the code to test it its my character in-game
```

**Comment by QuickStick123** [comment]
This mod seems to not be supported it shouldn't be that hard to implement though.
![image](https://user-images.githubusercontent.com/31533893/213972352-a72f9b5f-c05b-4d68-a294-f9733cab6f17.png)

**Comment by Paliak** [comment]
```LUA
["you can't deal damage with skills yourself"] = {
		flag("DealNoLightning", nil, bor(ModFlag.Attack, ModFlag.Spell, ModFlag.Hit)),
		flag("DealNoCold", nil, bor(ModFlag.Attack, ModFlag.Spell, ModFlag.Hit)),
		flag("DealNoFire", nil, bor(ModFlag.Attack, ModFlag.Spell, ModFlag.Hit)),
		flag("DealNoChaos", nil, bor(ModFlag.Attack, ModFlag.Spell, ModFlag.Hit)),
		flag("DealNoPhysical", nil, bor(ModFlag.Attack, ModFlag.Spell, ModFlag.Hit))
	},
```
Most of the work is already implemented. Just need to experiment with the flags to make sure it matches the right skills.
