### ISSUE TITLE
can't load POB

### ISSUE THREAD

**Issue by straylightd** [PathOfBuildingCommunity/PathOfBuilding#5627]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

I have just installed POB on my pc and it can't be loaded. i am getting an error when trying to do so. I have tried with previous versions of the program and recieve the same results. 

### What is the behaviour in Path of Building?

unable to load pob

### How to reproduce the issue

download and install

### Character build code

```shell
none
```

### Screenshots

https://i.imgur.com/QgNudCe.png

-----------------------------------------------------
**SOLVED**
see the picture that i was wonderfully provided below. the one drive thing

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/214173219-ed829505-4b1a-44ea-be2f-68e50215fb87.png)
![image](https://user-images.githubusercontent.com/31533893/214173337-e2e0f294-06e3-4513-aa86-4fd3cbc34a62.png)
![image](https://user-images.githubusercontent.com/31533893/214173368-e9e17ff2-0279-42be-9773-e8d49b9cae52.png)

Crashing here seems to suggest the fairly common issue with OneDrive. Here are some details on how people have fixed it in the past.
![image](https://user-images.githubusercontent.com/31533893/214173633-d79d964f-87ac-40de-9b56-7ad5964c0a9d.png)

**Comment by straylightd** [comment]
Thank you so much. this seemed to fix the issue. weird because i dont ever have onedrive loaded. i basically turn it off when i loaded windows. but ur a god send. havent been able to use pob all league
