### ISSUE TITLE
Trade for Items Currently in Build

### ISSUE THREAD

**Issue by jjstewart** [PathOfBuildingCommunity/PathOfBuilding#5631]
A large portion of users of PoB is going to use guides written by others with sample gear already in them. It would be great to have the ability for this function to generate trade links for similar items in the build and upgrades. The button says "Trade for these items," but it is more about searching for upgrades.

**Comment by Wires77** [comment]
Build creators should be saving trade links in that screen as part of their guides.  They can curate a search that finds exactly what items you're looking for better than the automatic piece of the tool can do.
