### ISSUE TITLE
Vivinsect Attribute Range wrong

### ISSUE THREAD

**Issue by MetalMMagic** [PathOfBuildingCommunity/PathOfBuilding#5637]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording ingame?

InGame the dualattribute Veils are 31-35
(https://www.poewiki.net/wiki/Vivinsect)

### What is the wording in Path of Building?

In PoB they are 6-17

**Comment by QuickStick123** [comment]
Other veiled uniques are also probably outdated. Diadem was fixed recently afaik.

**Comment by dshebib** [comment]
Wouldn't mind taking a look at this over the next couple of days as a first contribution.

**Comment by QuickStick123** [comment]
@dshebib 
If you want to join our discord to ask for help if you are unsure feel free to contact local identity on discord.
LocalIdentity#9871
