### ISSUE TITLE
Withering Step doesn't provide Elusive buff

### ISSUE THREAD

**Issue by BassOfBass** [PathOfBuildingCommunity/PathOfBuilding#564]
Even after checking "Are you Elusive?" box.

**Comment by mindyk** [comment]
any known work around for this atm?

**Comment by BassOfBass** [comment]
Add the elusive crit mod from redeemer boots to any item.

**Comment by Ydoum** [comment]
Any news on this one?

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.1.
