### ISSUE TITLE
Failed to fetch league list from JSON

### ISSUE THREAD

**Issue by lucastayar12** [PathOfBuildingCommunity/PathOfBuilding#5653]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Should search for an item in Path of Exile Official Trade site.

### How does Path of Building behave?

Fails to fetch the league list from a JSON that came from API.

### How to reproduce the issue

1. Import a build with items in ur PoB.
2. Try to find an item in Trader feature on Items Menu.

### Character build code

```shell
https://pastebin.com/Zts5S5cq
```

### Screenshots

![image](https://user-images.githubusercontent.com/24614113/215879391-3f449845-7073-4c38-93e2-a8541355e571.png)

OBS: Bottom right is showing the error.

**Comment by QuickStick123** [comment]
Related to https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5621
