### ISSUE TITLE
Incorrect blood charges value

### ISSUE THREAD

**Issue by drac69** [PathOfBuildingCommunity/PathOfBuilding#5657]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

#4258 included addition to change blood charges count in Configuration tab. The problem is that it's not possible to set the charges count to 0 (say using traps or mines). If you set the charges count to 0 or leavy it empty, POB always calculates with max blood charges and this gives inflated misleading damage numbers.

### How does Path of Building behave?

It should be possible to truly set blood charges to 0 for proper calculations.

I'm not sure whether the correct fix is what I've done, but changing "Modules\CalcPerform.lua" line 881 to be 

`output.BloodCharges = m_min(modDB:Override(nil, "BloodCharges") or 0, output.BloodChargesMax)`

makes it so the default is always 0 instead of 5 charges.

### How to reproduce the issue

1. Add REAP gem.
2. Try to set # of blood charges to 0 or leavy it empty.
3. Go to CALCS tab and check combat buffs (if it was working **properly** it wouldn't show any blood charges, instead it shows 5).

**Comment by Paliak** [comment]
The config tab overall isn't very intuitive to use. The blood charges input box actually limits the value to 1 and if set to 0 it defaults to max (there are visual off by one issues with the input boxes). Changing the config input type from count to countAllowZero allows blood charges to be set to 0.
