### ISSUE TITLE
Crystallised Omniscience + rational doctarine (scion) not giving profane ground

### ISSUE THREAD

**Issue by Nela88** [PathOfBuildingCommunity/PathOfBuilding#5658]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Doctarine says there's chance on crit to profane ground. I got crystallised omni on my scion making all attributes go 20/20/20 so being equal yet i don't have option to put profane ground on enemy. Without omni it works just fine.

### How does Path of Building behave?

it doesnt show the box at all and if i unequip omni and add some intelligence it shows up and works. after equipping omni the box turns red

### How to reproduce the issue

create new build.
pick scion
path to first avaialbe socket.
equip rational doctarine jewel
equip crystallised omniscience amulet
see the issue on configuration tab

### Character build code

```shell
https://pastebin.com/NMvSVv5H
```

### Screenshots

![image](https://user-images.githubusercontent.com/124595984/217006815-c3e0861a-8218-4ad2-8547-a96917510b88.png)
![image](https://user-images.githubusercontent.com/124595984/217006864-44138382-f5fa-463a-994f-f9154984ec2a.png)
![image](https://user-images.githubusercontent.com/124595984/217006934-3934456c-d21d-40b2-a5f3-ff5e8cba32bf.png)

**Comment by QuickStick123** [comment]
Have you tested this ingmae?

**Comment by Wasfill** [comment]
Tested ingame. Gor сonsecrated ground around char with 20\20\20 stats.

![Screenshot_515](https://user-images.githubusercontent.com/126147590/220849691-9c8e8a85-72b4-45a2-a777-ede69860b4e5.jpg)
![Screenshot_514](https://user-images.githubusercontent.com/126147590/220849705-62774040-9ce5-4211-914f-177035ab00ab.jpg)
![Screenshot_513](https://user-images.githubusercontent.com/126147590/220849706-8d871561-0b4e-47d8-b849-9a1d1740d381.jpg)
