### ISSUE TITLE
Skill hit damage and dot source damage use different mods for converted damage

### ISSUE THREAD

**Issue by PreFollower** [PathOfBuildingCommunity/PathOfBuilding#5663]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Ingame when I have a spell with 100% conversion from lightning to chaos, I believe that "% increased elemental damage" and "% increased spell damage" should behave identically in hit damage calculations and resulting poison dot damage calculations (assuming I have only lightning base damage and 100% chance to poison)

### What is the value from the calculation in Path of Building?

In Path of Building converted spell hit damage is calculated correctly, but source chaos damage for poison used different "increased" modifiers

### How to reproduce the issue

Use two gear pieces: one with spell damage, another with elemental damage with same magnitude. Make a skill have100% conversion from one element to chaos and 100% poison chance for simplicity. Add some flat elemental and chaos damage. Check skill hit damage calculation and source chaos damage calculation.

### Character build code

```shell
https://pobb.in/_jL8EIpd14mf
```

**Comment by Regisle** [comment]
spell damage does not apply to poison

**Comment by PreFollower** [comment]
Does elemental damage apply to poison? Because I'm talking about source damage, not about the poison itself.

**Comment by Regisle** [comment]
> Does elemental damage apply to poison? Because I'm talking about source damage, not about the poison itself.

yes, you have 31% inc spell damage and 132% projectile damage, neither apply to poison (according to PoB), this means the lightning-> chaos portion should still have 524% inc which it currently does, the "source" damage on poison shows all of the inc/more multipliers on it

![image](https://user-images.githubusercontent.com/49933620/217791391-f8cecc5b-291d-4dc5-9f70-e7be32e9c3ac.png)

you have 181% total dot/poison/chaosdot inc and 163% inc that only applies to the hit portion, 181-163= 18% which is the difference between the hit and dot "inc" under source

**Comment by PreFollower** [comment]
So if I get this right, %inc spell damage never applies to poison, but %inc elemental damage does if the damage is converted to chaos later?

**Comment by PreFollower** [comment]
Strange, but that's poe for you. Thanks, I'll close the issue.
