### ISSUE TITLE
Weapon-specific supports give no benefits with Varunastra

### ISSUE THREAD

**Issue by Euophrys** [PathOfBuildingCommunity/PathOfBuilding#567]
With Varunastra equipped, weapon-specific supports like Nightblade or Close Combat do not give their benefits.

Steps to reproduce:
- In Items, equip a Jewelled Foil.
- In Skills, add a melee skill and support it with Close Combat.
- In configuration, set melee distance to enemy to 1.
- In Skills, hover the checkbox next to Close Combat and observe that it would be a DPS loss to remove it.
- In Items, unequip the Jewelled Foil and equip Varunastra.
- In Skills, hover the checkbox next to Close Combat and observe that the only change from removing it is a lowered mana cost.

I'm on version 1.4.159.1.

**Comment by jwfiredragon** [comment]
Hi, update on this issue as of version 2.9.0: Close Combat works with Varunastra now, but Nightblade still doesn't.

**Comment by ganuuk** [comment]
Bringing this up again since the new trickster polymath ascendency node, there may be some others bumping into this.
Nightblade supports works partially but don't account for base crit chance and crit mult.
