### ISSUE TITLE
Increases to cast speed from cluster jewel does not apply to shockwave totem

### ISSUE THREAD

**Issue by Starbuckz** [PathOfBuildingCommunity/PathOfBuilding#5678]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

Increased physical damage Large Cluster Jewel  - Added Small Passive Skills also grant: x% increased Attack and Cast Speed with Physical Skills

This mod **does** affect the cast rate of the totem.

### What is the behaviour in Path of Building?

Increased physical damage Large Cluster Jewel  - Added Small Passive Skills also grant: x% increased Attack and Cast Speed with Physical Skills

This mod does **not** affect the cast rate of the totem.

### How to reproduce the issue

Use aforementioned cluster jewel with the mod in question -> cast rate won't change

### Character build code

```shell
https://pobb.in/dKnuQkyQUk_5
```

### Screenshots

![image](https://user-images.githubusercontent.com/5391009/218438715-2af9b971-cdf5-428a-889b-eb5f9e46be40.png)

![image](https://user-images.githubusercontent.com/5391009/218438778-9d6f10cc-fa12-44ac-89f4-7533348b106c.png)

**Comment by QuickStick123** [comment]
Fixed in dev by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5559
![image](https://user-images.githubusercontent.com/31533893/218439267-b28cf4a5-128d-407b-b0eb-991a64d4766b.png)

**Comment by Starbuckz** [comment]
ah, thank you. sorry I didn't make the connection to #5559 it's a bit obscure sometimes with the wording and all
