### ISSUE TITLE
Error on line 195 of launch.lua during import of char/tree and jewels

### ISSUE THREAD

**Issue by pHiney** [PathOfBuildingCommunity/PathOfBuilding#571]
the CE version
![image](https://user-images.githubusercontent.com/4302241/76671613-5ff78b80-65eb-11ea-8bc1-3923638fdc3b.png)

The OpenArl version
![image](https://user-images.githubusercontent.com/4302241/76671626-89181c00-65eb-11ea-8663-a752047056ff.png)

**Comment by ppoelzl** [comment]
Could you provide a build?

**Comment by pHiney** [comment]
Items and Skills worked.

**Comment by ppoelzl** [comment]
My inquiry still holds.

**Comment by pHiney** [comment]
https://www.pathofexile.com/account/view-profile/xyllywyt/characters
Toon: XyllyMinionMaster

Import Character, not build

**Comment by pHiney** [comment]
> 
> 
> My inquiry still holds.

sorry it came in whilst i was writing the second comment.

**Comment by SinisterGenocide** [comment]
this is happening to me as well. what do i do?

**Comment by ppoelzl** [comment]
Could you provide your character as well? From what I can tell, this is not a bug that was introduced in the last updates.

**Comment by jannisg** [comment]
I've got the same exact issue.

Account/Char are:
https://www.pathofexile.com/account/view-profile/meemorize/characters#Meem_isToxic

Account: `meemorize`
Character: `Meem_isToxic`

Let me know if I can help with anything else.

**Comment by igorcastroo** [comment]
I have the same type of error "/

**Comment by pHiney** [comment]
GGG updated Character format ?

**Comment by SinisterGenocide** [comment]
account: Nzonic
character: SinisterFaceroll

**Comment by avaati** [comment]
same issue here as well 
account: snwkill
character in Delirium: snwvort

**Comment by SinisterGenocide** [comment]
any word on a fix yet?

**Comment by ppoelzl** [comment]
Working on it atm.

**Comment by twherzog07** [comment]
Turns out this happens in the OpenArl version as well

**Comment by BassOfBass** [comment]
I take a guess and the problem is the new clusters, which are present on the tree even without any jewels socketed, so technically a part of any char tree.

**Comment by ppoelzl** [comment]
No, that's not the problem. Anyways, Openarl just fixed it in his repo, so we will soon have a fix as well.

**Comment by custompro12** [comment]
Any update?

**Comment by pHiney** [comment]
tried merging the openarl build to no success. Needed to have copied the original 159 directory so i could identify the few changed files first. anyways, smarter people exist.

X

**Comment by SinisterGenocide** [comment]
so is this fixed or no?

**Comment by pHiney** [comment]
I have all the files that are different between openarl's 1.4.159 and 1.4.160, but there were a lot of changes, variable renames and in amongst it all is the fix

X

**Comment by SinisterGenocide** [comment]
i dont have an update option. says there is no update available

**Comment by LocalIdentity** [comment]
I'm going to push out an update within the next 30 mins that will fix all this

**Comment by SinisterGenocide** [comment]
thanks

**Comment by SinisterGenocide** [comment]
still no update?
