### ISSUE TITLE
Is damaging ailment DPS properly calculated, accounting for scaling modifiers to the contributing damage types?

### ISSUE THREAD

**Issue by Kanarisky** [PathOfBuildingCommunity/PathOfBuilding#5711]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Have not tested the numbers ingame and not sure how we would. 

According to Mark_GGG in [this post](https://www.pathofexile.com/forum/view-thread/3123794) (ctrl F for "Increased Global Physical Damage") and [this post](https://www.pathofexile.com/forum/view-thread/1897612/page/4#p14474050), when you convert to a damage type that can inflict a damaging ailment, "% increased" modifiers affecting the original damage type are also intended to scale the resulting ailment after conversion. 

In the first post, the example given was: poison DPS that was inflicted by base physical damage is intended to scale with "% increased physical damage" modifiers, because base physical damage contributed to the hit that inflicted the poison.

In the second post according to the "New System" diagram at the bottom of that particular reply: If hitting with base physical damage, some cold conversion, and a "Cold damage can ignite" kind of mod (e.g. Shaper of Flames), then the resulting ignite should scale from "% increased" modifiers for all of physical, cold, and fire.

![image](https://user-images.githubusercontent.com/68185248/221122728-d6669d38-c5c1-4723-a7ad-af186e8c7d08.png)

This question applies to the above two examples, but the PoB I am tinkering with is for an Elementalist Explosive Arrow PoB, where all of physical, fire, cold, lightning, and chaos base damage are present in the ignite-applying hit, and all damage can ignite due to Shaper of Flames.

**Question: Mark's posts read to me like the ignite is effectively tagged with "physical" or "cold" such that it can be scaled by physical or cold modifiers. Hence, there is a possibility that "100% increased physical damage" should scale the ignite just as effectively as "100% increased fire damage" would. I am wondering whether this is the case.** 

### What is the value from the calculation in Path of Building?

I do not entirely understand how PoB is calculating it but it seems like it is applying the % increased modifiers to all the base damage types contributing to the ignite, then calculating the ignite from the sum of those scaled damage types. 
The base fire damage of the EA explosion is greater than the base physical damage. Hence, applying "100% increased physical damage" in the custom config yields a lesser boost to Ignite DPS than "100% increased fire damage" does.

**I am wondering if this method is correct, or whether "100% increased physical damage" should apply in full effectiveness to the Ignite DPS, as it is tagged with physical due to the base physical present in the igniting hit.**

### How to reproduce the issue

1. Load PoB build code
2. Config>Custom modifiers. Remove or add "." at the start of each line with a damage type modifier to toggle that modifier.
3. Observe that enabling "100% increased fire damage" modifier increases the displayed Ignite DPS more than "100% increased physical damage" modifier or any of the others do.

### Character build code

```shell
eNq1HG1z2kb6c_kVGmYycze1sd4Bj90OxjjmziQUnLR3H5pZSwsoWbRUWhmTTv77PbsrIYGRkCwunUmE9nl_3X0k9erXlyVRnnEQetS_bmottalg36Gu58-vm58e7847zV9_aVyNEVt8nN1EHuErvzR-uhLXCsHPmACeCngMBXPMPie0jC9wb4V8tsDUH6GvNHhP3evmB-rjpvKEfNdjyS-HoDD8gJb4uvm7x5xFU0Ghg323n94fELzEPkPEC1lTWSLPn1LnG2bvAxqtQICm8uzh9Yi6ADscjT9OHjPMPT_LHKT_6WpM0AYHU4aYEsJf180eGAHN8S1awt9ADZEISGldQ--0jK5ltruapTUvCpFvoiBkb6MwXWHsbpGMVls39DzYcYAHsxl2mPeM-4HH-gvkOylHKw-vKuwoIsxbEQ8HqTZ58PevSPOYyAF-pODI2_F0C9vWurbRMju6ClZqm8V4lG3xcjkM577HcJaFrhsdrdXRLNM2bN06grjrw07X0tst3dY6lmmp2jHx3sC2HxECiZXFzNWtT5dPno_d3vM8Y-xOx7JattU2DMPOZdMLMPo4k8EzQa4Xhamg7TykEfJRn4Ysw6wIdIwDyF22g3EMYYodCumeRTHA4PkpkGF0GD2X44M3w-UhKykTI1SV5m16DKZl4SoTfptAE8iYcpBTlhYUPTfZb_FLGnG5UBP81w5gu5ub2X42gvV8ts-UQQM7roZI98H9OEPV0luGZutdo6t3c_NpvNiEnoPICL14y2gJlfMRfcMpQ023CuJlvmA-VIo85HY7V7M7L8BvQOtT4r4FbYFomIvX0YoyopQpoGM6lxx66DvlEu2TH-AQB8-ZRlts6xmeQALw3v5EcGmclE2cSGVaomQ2x37McVNOpQeMncV72A0BK7ByuYKbukHVCq3LgUtZlwMesG4B_V2MCobiiIcNpUHyFWFVttXAx8F8M114mLjVoBPZ-mhVohxyU2exS5l8l12lwMmiVjbK7yhwyzWDqlI9ozBbdzWr2GASvFx4YoIxILh4b4-q5m-x6Ve-wSbV0HrBkkZBSZdL4FIKJC1D7ksn2I2ccj3qhsApqaz0IBUhlTB6jCHn2y1157gSk-oY02i1gmrBXV4Wj_e7CQ69zJbk3DKPQ3-EeC2VuLwzlmeQQpdmsO325bnsoZTXhbfrfTZ2GfDSLLZn1hFUBH6YF2deOLIfP13ewfGo1NlIAO6ewPKTiq5B8gWfWoTVoGFbk55TckUJsP99U5r-DngpBgPfjQKeCqV57GMcYvPoLaFahuEtYkgJMQqcxQN4-brZzPy6Q4Q8QebDXY51dSGmQfxquFzRgImbfUScUNAc-quIKb4Y5Cy90PnyFM1mfFYDNFkgRk2Du7tB_3H4eRCLkUUJv3mEfPGj5ROfRMh_02CZYlELlTB6CuXldfOzh9dTjnWLGfIImMahhKBViN3r5gyREDh7cClgpqCvwwqoCShojslU4DCtFCCf0uAFBwz0hSbqBB7OlWu7fkQoyZA3WO62PGp8YpJPSNbwPgrZBLFcGnI-lU-Fz4ty1eGLBbgQM4jkco5Xj1iCbVY4hK7qzTyHR3yxyx8BWkIV2MVxIFmcTYG_406UT-OGiKneYQJyMR95TL2Q9_jD2PFqgVXFJCvXqnI1H_0WOyhXd7mYj7zdVVJfbCoPU9lCFVD6QH0R5JA0PY_wrpHr2QHBW5B8gh_ZAgeyFeVSGkGNSkAKEyfwniKWn8YZiAJbiQNvjoX4Wj6qPMzl6MDXCirRztkmx6BZmHxS8kSQW8iKUCcF9XRSXEqTrXaO5eVqgf7JaSNH9Xi5QHSx-cl1fbyVKioNsM_OLw18MR9ZptZrEiyISlIQaXCLZxgKWGEebGEKCjCL_FuolazAoCVJyYbWe6aeKzf5tagJJQ8TSy1ViZasLwftVpmiOATVNf3e2egk5o9ndTmlPwNyhBDU7PuCXUE5SttTwz1GhC3GlJJ6BF_NJGvpSVmIfPeWjzpqKsonJdEKiCWSfTy0rUujbJ_q1UWy4b4Se5xQCWEn_h4vw5sNnIfueBVPHx6JExISho03wUw8Rd3BSdi5eIYiwu__FiHisQ0_Y2TuPsinwD4NltuxNpBa0DUPTUmRb7lCKMwPD3KlR1hMjLNL7CWtEwsk1NTEvfimePDbS6UWGgu5Pd8hkYuHfnxU3DqAoCcuG3-szae4WxPuUdoy-ukK5ImB3xP6hIieoIhzCGwb-XOOyGcxc119tSJvxs_GdbW5Q07bITfkzeZlRWgIkvSCgK6byl_SLkOx0RI2joHHKJBemuMlXx3B6caFc9rFkIENL7ghL4Q2cJVDVHhuzxRb2qk5HakGXPEjGB9XZcRUJMkL6RjJ8UROCqFrO3DkewwwvjS7Wrue3xLyZT0xDjyI4B6ee-FhNxRY8ZDJJD1FEnxlr_gSIl2kr8xafsm1T5JT0NHixIAf2VcjuGg6N0nIcLCJd6zcjD6creHCMk2zfWZZhqGfGW1NM89sTbe6Z5reNjpnhm2Z-plmq7pxZrV12wQYy-7CtdZtn5m2Yapnpt624W9wxJlpwF1dVzuAqXXa1pmtWoDetbr80uh2zixD042mwkD6zFsg3OpOIq0RZ_OnyYP02oKxVXh5cbFer1srxBZ0hl88glsOXV6sAAlMcC7cc87JXvTgz8181B-w-bdv4-B5-v2-_zVoz8J_PdwYuq7d_NsZDr4D9c__Hc6Goz9Wg82Dfd4ez9e9nrR-wvlKvj8SXsSeANMKL3Db84sPFLbtfI3fTH4Iz_DhQjwLmbKAm_s7pcv_iIfwVku1VKut2rbdlnUO2hYbodU2FjlsXC-7cY2Eg-itB84LRHtO4okD_gH-7egto2uaesfkf2SpF_keRwi_Tqp3FGL5yPZ3jFbUF7czhZWDZovqBMHBfHOpTHqTQeMDaMUBGo8Lj1tGuaHrRj9AM4bdS4XL1BgHeOa9XCp_B8if40vtxwN1IF1cF7t8fBp3pDW9hy6mqUXgfBhaAXw71dzHmUazAzhD3wkwgn4pZxtidmFtYflLQLs_4kZ0qehAUYbFpfL-fPtfQzhsgv-6VGyrMVyuiOd4HEZtgHihouuWwqhidFWF20GRUsZrqinWzI7Cld5ZMzp8yYZ_tgom61r3HS-XUg1F6qEIRUTwjqg74RorQm8oRy2rGXs2LjO5EPpRCOMoRDJ-Fo0nDa1niCck2l_CaifMPn0Y_vZp0LjdIBfAQNO134D0eN4oN5iwRh86GdmE7FJ5jIKniMBGe3sv66HPksulAgGj6C27lbnVj4KA48mZHlhuu6JnWaX-tPSsP7XG39DEw8uveA37aqipX1ByhP-xDbGf_6Fb54b1T-47KADYn7NFjEfgvJ4FbKvnHQm4lLsihZ_oXzEJxGGRn1F2uKjnpvrPdxxbRNVkC1WdgAi9VwSQCKszKXXsPMBUW_Y7hc6SqJMRqYhpDVgUhUIJBc2hE4dM6S-gOsN97OOlh8Mi0voPrTbhVGmcvBJ4JpllVZDjrVDZ0AjSaAb-ZcraY4uYdQibV-jLsQC6-k6ZiR5agYdejYdhbXnc8ts-VZKHeknKH8o47UhWa0dyWjuS0dpOPhdkvHUUwj4K0T4K0TkK0T1cebx0b3G4qfUC5gmXKr9F0DSDY51Ndin-lEt6R2JpW0DRN3Z-5LeXw71GzVShtnmoCoW83CcJDRb4wTPa4BmddoZHytUfE-SIQFUEjuwupia6S1cRaiSBCLfi-DxRI9lzBT-35W9Ddo90hMIZD3DGT7ArE_tW-Q6wwFK06RqtlN7TJgwhSWRfVjhvJk8_aiLhMTr7NPQ30EhRtGMoN5Sy8BRyH9K_iuy81dXBv4Nd-zfFqC65fkhy4wSee4MV9f8HDfMEutgnkMM-kW-0KlF1KLyrOPcekyVmtUQ4ENh2bQmqpMZ7Qp_5_LcmS-NEVUGrLYl5gmjUTpAVZsUwqOyzWgwPhf4pLFe9Klt1xa7bSIxKArgbRT6SqxMzhx1YP_at2hSqF5_KDq9vKOs0HtPrRp59gjJhnCDpjJoZYJ6o-dbNRO00fjUqh6RZGaOuqqfaRb8lfFIUo4637brpcyJ3nyp639T-OKG3VIE34tX1w4QPZvXaBVg_jedOUT_fGES1TWBUtbp2Inebp7G9VdsClfP_RHlaRfLeMiIHtihy0pM8rhTPoMR7vtSfefNXb-3yse1mGN7QMExf8_3EX-F9_YavE4WMLkfUzYC2NFXNTrpWybjUlePS_fUZn5HnrDl8_J2zRraPXvKQxfgsXmz8-eefygQvwbWKC9ZjNH4OrCyp6808HCgA0Wj8DERUlS-j-D1Shb8g5c8be9TlXFnO7Q5YZv8D-tQ-4lv21wjyy_qjYMI7U-87HvNvsDLwI-x60bJIkvhr-qMs-ADQ4--2QIA842COxTtYT5QSjPz4KedrrAW4Aydf0fOXRlI-_ClI-mq7gxfgVbB3ViH5FX3ying7-xnZIfjd72pSREM1zWLMne8lUrRipL3HmJX4Zb7dT7CsktzG_C2nBKlTjJT9aGbL54ha6cPcShrBnSqSiWl5Bto6brDXQpVw6j5S29aOK1LVZOnj8iom41iVTLb__dCeeFcXSe2-utj_P3z8D63LrDU=
```

### Screenshots

A: With no custom damage modifiers enabled. **Ignite DPS = 22 381.8**
![image](https://user-images.githubusercontent.com/68185248/221124059-84c823c2-05e5-44e9-9cea-08ae0ea84ba9.png)
![image](https://user-images.githubusercontent.com/68185248/221124188-27982630-a5da-49e9-b112-69fb782e9aae.png)
 
 _____________________________________
 
B: With only the physical damage modifier enabled. **Ignite DPS = 22 952.7**
![image](https://user-images.githubusercontent.com/68185248/221124399-1e9b6871-579d-4219-83fd-9302b1a948f3.png)
![image](https://user-images.githubusercontent.com/68185248/221124454-f748ec07-55ec-4bff-8ddf-a48bda0d148a.png)
 
 _____________________________________
 
C: With only the fire damage modifier enabled. **Ignite DPS = 38 369.1**
![image](https://user-images.githubusercontent.com/68185248/221124552-9adbf043-3c95-49b1-86b7-3722d621ca69.png)
![image](https://user-images.githubusercontent.com/68185248/221124592-ea51bfa9-92c4-46a2-b13a-5f9ed26debf9.png)

**Comment by Regisle** [comment]
The % physical only applies to the source from physical, theres no "tagging" involved, merely the damage from physical is also scaled by % physical (as its physical damage), where %fire applies to everything (as the final damage is fire), so it should not have the same effect.

If you set your flat lightning and cold the same value you can see that % cold has the same effect as % lighting, but both of those only apply to a subset of the damage and not ALL of the ignite damage, 

Where because the final damage is fire, %fire applies to all the damage
eg 10 phys, 10 cold, 10 fire with 100% inc phys and 100% inc fire
the phys is scaled to 30 "fire damage over time" (10 * (100% base + 100% phys + 100% fire)
the cold is scaled to 20  "fire damage over time" (10 * (100% base  + 100% fire)
and the fire is scaled to 20  "fire damage over time" (10 * (100% base  + 100% fire)
for a total of 70 "fire damage over time"
