### ISSUE TITLE
[NOT WORK ] For Effective DPS > Is the enemy Frozen + covered in Frost 

### ISSUE THREAD

**Issue by yeonding-93** [PathOfBuildingCommunity/PathOfBuilding#5718]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording ingame?

about  Polaric Devastation, Opal Ring 's option
"enemy is covered in Frost"

### What is the wording in Path of Building?

before i use the ring that Polaric Devastation, Opal Ring 
i wonder if option(enemy is covered frost) is effective. 
so i launched POB and check "Is the enemy covered in Frost" Option. 
but there are no change for my DPS (I used cold Flicker build), when "is the enemy Frozen" option is checked same time

Is POB bug? or Frozen option include the "Forst" option? (so, forst option is not to duplicated with frozen option?)
![image](https://user-images.githubusercontent.com/126460057/221529862-46f20185-d885-43c0-8ba6-4910a72bfb2e.png)

![image](https://user-images.githubusercontent.com/126460057/221529993-ee8b420e-a8cd-4f96-9d5d-08d4282dae14.png)

### Character build code

```shell
https://pastebin.com/6nahehaL
```

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/221531634-1657f977-580e-46ff-84db-7db331a3bbbe.png)
The item lets you inflict when you freeze them so it is automatically applying the mod if you have "Is the enemy Frozen" ticked. This means toggling "Is the enemy cover in Frost" does nothing.

**Comment by yeonding-93** [comment]
Oh I understand. The ash covered option is the same mechanism. thank you
