### ISSUE TITLE
It seems that the Bleed calculation is wrong

### ISSUE THREAD

**Issue by LordZeto** [PathOfBuildingCommunity/PathOfBuilding#572]
Hi,
I was setting up a bleed build and I noticed it applies "melee" and "attack" damage to the bleed calculation. This is wrong I think. Bleed only acknowledges "physical damage", "damage over time" and "damage with ailments" in addition to the native "bleeding damage". 
It becomes very obvious when you use Fortify Support and it gives the most damage out of all possible supports because it applies both its modifiers to the bleed damage (melee damage and damage from ailments). That can't be right.

I have taken my Information from the wiki: https://pathofexile.gamepedia.com/Bleed
If you look under Modifiers you can see what I mean.

Now I don't know if this is also a Problem in the original Path of Building. I never noticed it there and atm I only have your version running, which I love btw !

Cheers

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.1
