### ISSUE TITLE
Lightning Golem's spells not properly supported by spell echo/greater spell echo

### ISSUE THREAD

**Issue by Kelvin-Chang** [PathOfBuildingCommunity/PathOfBuilding#5745]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

lightning golem casts more quickly when linked with spell echo

### What is the behaviour in Path of Building?

lightning golem's spell cast rate does not change when linked with spell echo

### How to reproduce the issue

add summon lightning golem skill
link with spell echo support, see no change
equip pledge of hands and socket summon lightning golem into weapon 1, see no change in lightning golem's cast speed

### Character build code

```shell
eNrtHGtv2zjyc_0rCAML3KGtbfnVJEh2kYeT-BC3Xjvt3n0qaIm2taVEV6KSuov-9xuSkizbokxF7n04bAqktjjvGQ5nxozPf_vmUfREgtBl_kXdarTqiPg2c1x_cVH_-Hj79qT-26-18zHmyw_zq8ilYuXX2qtz-RpR8kQo4NURx8GC8E8Jpc5noLTCPl8S5o_wnyy4Y85F_T3zSR3NsO-4PHlnUxyG77FHLupTG5DrCIc28Z3rzXMF6GHXnzL7C-F3AYtWku2TS55HzAGY4Wj8YfKYYer6WaYg86vzMcVrEkw55iiEXxf1S5u7TwRAge-D67kcKGIaEUG7qUEBa-EFuc_Atg7AXkVByG-wBy8P40xXhDgbsIbV7_darfj3Ox3WOCCD-ZxIda4Dl18vsW8bcCsLO4ood1fUJcHGUo2eDuN-j7jV0pJ_ZBzTm_H0sCAKkhk44A-XL68oGNSIroAeLnyXE2PwMXND5peS2gj4OqIUdpoZLPNmrm-o4zVj1GHPfgrZb7RafR30CPv4moUbS_e6RaBjEsDO5VsYrQMIU2Iz2OxZlJPG6SkEyon8fWrAMJ-MlvODOyfmkKWUihHKSvMyPQZTU7jShF8m0AQynBnklG8SSFtPj3zNAlpWRwd5Q76Z0csC9k90gEOfm5HLAhaK98S4PNuMssTgfrwRst_ob370B8ByHbo2piP8zfUiDzLvI_5CMtu8IP4WS-5DstGhdrRmunUDUh7rGjLQC7CWmIXl0cTuMjACnLr2mYAd-rbZlv3oByQkwVPmsO4XIkxgI4l6YEaJIcaGRbwdTY5RxWpB_Jjf2kydB0Ls5R1UWBPMiVnyTqHe9QrNKmCNzCoAc8yqJ7-NUMJIAjHfSFajU4RU0kwDnwSL9XTpEuqUg04Eu8Yro5rRPstiG5l7m12piMmiljTJHzhwzE6SsjI94TCbYq1-sbkUuFlgEqghAcEhprXyOGB_imqclkO7DDwWBYYOV8BGCiSng2pCJsSJbLPj6IpCw2UqPUhFaR6G_gi95BzbX26YsyCluJTHmEarFWQK4XNTPHG8TUjoZgqat30D6A8QsEb7VpyE5gw20MYM0rPdnMsOirku4nwuocwG3JhF2uGOICV4kOplrwzt_-Gu_Rb6KaP-SAIaNmlj9gySL8XkIywHDXXMpnbRihIQ__vamP4WuBGDge9EgdgKxjx2MYzYHB6yqLX9wcnOzMSCCrvRP23rsHZHJye96pB7U4nTLhTknZN2MULOcGIPMnc4cYh8_ozCBGt_VGGqSt5m2AMumFjsw-ZMLA4Js1XIn56mvVYuYH7pcHrasIqwiiuZPZTc4s7qdvomCMXFTSFqsZiPrgfVShjeYI5RSHBgLx8gyV7U65l3t5jSGRy88FRgnTflOFe8GnorFnD58BpTO5Q0h_4q4siXs1jPDe3Ps2g-F2NXoMkDOSse3N4Orh-HnwaxGFmU8ItL6Wc_8mZibKj-32z-KZG1CAqjWaheXtQ_ueR5KrBuCMcuhcxkM0rxKiTORX2OaQicXXgpYaagr80LqEko6BmTdJJPawOgpzT4RgIO-kIRawcu0cqVrh8QSjEUMSDcpqMmsomekCqhrnHIVTxoLCUznp6KGO5q1RGLBbgQM5hqOcerByzB1ysSQlXrzl1bxH2xyx8BWkEV2MW24ayy1wX-jgtBPQ2ZnnUE1KIeWSVcHXa8WmBVmeW1VlWrevQbYmOt7mpRj5ymGObLDzryqaRQBZTew5Ejghw2zaVLRdGm9eyAkhRET_ADX5JAVYJaSiPIUQlI4cYJ3FnE9ds4A1FgK3kwaSwk1vSoaoqi0UGsFWSircNHY9AsjJ6U6si1iawIdVKQTyfFqTRpdTWWV6sF-ifdvkb1eLlAdNl7aF0fdzJFqQH6XH1qEIt6ZLW19knwIDKkILfBDZkTSGCF-yCFKUjAPPJvIFfyAoMaklIH2uUTcx3VY1eiJpXMJ7axVClaKr_k2q00RTmDqGr6ndHEUcwfz8Y1qT8DcoAQ5Oz7gqrAjFLatN8TTEUXwmg1gnufAVTSk_EQ-86NqMYrKiqK-WgFxBLJPuSVdZso26V63kwK7nNZ44QohEr8jnjh1RoapVuRxXdaJywNGxfBXF6I2MJJ2DlkjiMqnv8eYerytWgXMk8f1DUOnwVe-gkSkFqyZxGaiqIouUJIzA8PauWS8piYYJfYS1knFkiqacln8UN5h-NyI7XUWMrt-jaNHDL040lN6gCKZ0I2moyl0IJR4olrKuKTlNSiO4RTvq_OQbwY-I6yGabtBEW2JXGntS1MZiV-OI08j4HZ0-nYnZIivgDTbtW3eFhbPIZOQmAXfVcEMUVBX5VZh7JOky6KAcc4UE5eEE-sjqA5cqDNaw45uKAp_NCUZOBVPr-vGffvGDDlsDEDxLOvGIo-TsycEz1QShjta6K1VlNFgpLxZ0QFeo1CkVAR1KXs54bI_4_jf46XC4xawnQy-cg7RzYWc-VqFkpz2T5FY8PI8BqI8PrfRjO8WQQEGvygKMRDysS0j-AVeM_6O-T_DvmfG_LxSzjrZQGj6hbx8jEgJClPJBUrLg3gTfZ-pxC8JeI0hMhexz27mFX6zBHlRu_kpANhwoFc5m6psKO9QVdSfZw8KDcsOV-FZ83m8_NzY4X5ks3JN5eShs285gqQQKa30oJvBdnmJfxcLS7lj1IvoXSubpuGzVhVkF2qKZQTL94zTuSAVDxM3kjVxfwyHrdOeSD0-c6Y9x-pqyieoBbmI7xKE4BYjYuwTlx4ccxvXLBHIGv-xEEC8N_JsPdcejo2s3idFIFRSNS1LZUJ5ONMfSZA0RMOXCyc3a1n67QJPObrM_Tx_fD3j4PaGIJjQRCbo3uobMPavyJ4K1ooBALO57UHghcROUMPZAG-qX1SRM_QOCCo3eg3WtuPOg3LynnWyz67jgLQmdfUWJc4KF3p7rGPK9Az1G7VYmedoau36b-aNOqEfD1D_ZPa0FtR13YFTKf2V2yAM-vHa6v9C1KzQMQZkq03UmNVpKp09LyECELPogYXuQHH_FMibSByUpVI5033x-t2a5-M2oLFVJT6YK47GRNg2Hjzw6PZGklDoE4L3cWnyGZb1_4KsL8gZ61G78c_rHbrrdVv_fMXcVoBKDQtW-wzdnvTftP5YbVaWVBPNQ9ITK82oN0fPT2U2Ggj5kyEDEhKIj6R6yVRGeccLUT7IETnIET3IETvIET_IERyd08m6HQjij5Jv1-3Wyg43ZELOOMZpCiZJeXnK8l5P33GK3Q5W4chpkjFAxK8uTogWomEh-js0mi_gMYGxTqEcsWgCT-G3Hn6l5H9ilBeBf8WjqQvqFNe8nae5J0jeO4FVmz_DBrdI-jSP4Ic_SP5xioTVXnhXca594R6hFcSISew-5UlKLM1oN59EvPWiiw7R8oKVmVJukeIRusIu6JbMgxK-6wSw7zQP4blymflXlWxqx4knVICOGukPgKrEjP5Dqwe-73KFMonn9IOr26o3nE81q4aef0jpInOETZdp-IO6B7p8K26E63j-LVTOiS7pTGqqnqsKvol4XMkb_erbp8juftY0fui408QekkWeCFeVT9MxGCiXTkBt4_juWPkzxcGUWUTdMpa3TqSu7vHsX2vsgVK7_8j7dMykl96Ec0pUdSkJxmOy2GtvFfL_Lm72LslS3zirafudzIWf9DGN1drR8RxIy_nXu3uVx1sUORXHjTzWQzDKxaGB2F3v7zhIIL6VodcsDHFNlky6pBgS1l1Cz-5EPwu-_d6efDiGmpyhzdB6hjgJH_vk-D0ilG2_1gqI19yTSP233lz92sx_gu6C49C
```

### Screenshots

![image](https://user-images.githubusercontent.com/35503604/222570190-a28b47fd-54f1-4b3f-81bd-314d526c5171.png)
![image](https://user-images.githubusercontent.com/35503604/222570342-0e227bac-4218-407a-924b-b509d1278443.png)
![image](https://user-images.githubusercontent.com/35503604/222570482-7570fb98-968d-46b7-ba4b-c3e59c07ece6.png)

**Comment by QuickStick123** [comment]
@Paliak

**Comment by Paliak** [comment]
`SkillType.Multicastable` missing from golem's Lightning Projectile skill. I'll make a pr later.

**Comment by Wally-D** [comment]
They're actually missing many of their support gems. Added damage, penetration, crit chance and damage, elemental focus, controlled destruction, etc. all work in-game.

**Comment by Paliak** [comment]
@Wally-D Would you be able to make a list ?

Preferably in a format like:

Skill - support - works/doesn't

**Comment by Paliak** [comment]
@Wally-D That's awesome. Thank you. There's something weird going on with skill types of minion skills. Especially "special" minion skills such as Minion Instability getting the damage reduction from spell echo even though afaik it should not be supported by it.

**Comment by Paliak** [comment]
For more context on the issue. The code i removed in #4628 checked both the summoning gem and the minion skill for skill types required by the support gem when checking compatibility. Now only the skill types of the minion skill are checked. This fixed the issue with spell echo applying to minion instability but has caused a whole bunch of supports to not work with minion skills due to missing skill type flags. I've been making PRs adding those flags manually but with each pr it bothers me more and more and i'm trying to figure out a better way of handling this. Problem is i don't really know how it all should really work. I'll stare at the skill properties some more. Maybe i'll find some pattern to latch onto.
