### ISSUE TITLE
Fails to import any passive tree

### ISSUE THREAD

**Issue by KlumsyKyller** [PathOfBuildingCommunity/PathOfBuilding#575]
![image](https://user-images.githubusercontent.com/42052570/76679293-9d80f800-659c-11ea-94fc-e997542a76b1.png)

I'm on the latest update according to PoB, but it won't import passive trees of multiple characters. I can import items and skills just fine, it just won't do passives. The chars don't have cluster jewels or anything, so I don't know what's happening.

**Comment by erikhoelzel** [comment]
Same problem here.
![PoB](https://user-images.githubusercontent.com/5658912/76679826-dee8c600-65e3-11ea-87e5-b29d5c0c1a8d.PNG)

**Comment by TheOptimisticFactory** [comment]
Duplicates https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/575

**Comment by wakasm** [comment]
Same here. 

![POB-ERROR](https://user-images.githubusercontent.com/734064/76696176-cec1fc80-665e-11ea-9b31-b5bc7d1c88e9.JPG)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162
