### ISSUE TITLE
Duplicate Item

### ISSUE THREAD

**Issue by Gnawbie** [PathOfBuildingCommunity/PathOfBuilding#5750]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

no, more for convenience 

### Describe the solution you'd like

A working duplicate button on created gear.  This way if you want to see the difference between 2 pieces, with minor changes, you do not have to completely remake the item to flip back and forth between them.

**Comment by QuickStick123** [comment]
Copy pasting the item functionally achieve this?

**Comment by hexeaktivitat** [comment]
Ctrl-C & Ctrl-V work as expected, opening a copy for editing that is saved as a different item with the modification. The sidebar also mentions it fairly clearly.

It's a bit clunky and counterintuitive so I can see the benefit of a "Save Copy" button during item editing.

**Comment by Wires77** [comment]
It sounds like copy/paste solves this problem without further cluttering the UI.
