### ISSUE TITLE
Rounding error when combining more/less modifiers

### ISSUE THREAD

**Issue by grebnesieh** [PathOfBuildingCommunity/PathOfBuilding#5757]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

![image](https://user-images.githubusercontent.com/5805649/223175424-d389b1c2-10c5-42e8-abeb-bae17ada450c.png)

Flat cold damage for my ice spear in the in-game tooltip is **2530 to 3968**. I know that in-game tooltip is flawed but I disabled everything in PoB that the game would not take it into account in order to be able to test.

### What is the value from the calculation in Path of Building?

![image](https://user-images.githubusercontent.com/5805649/223175971-498e73e7-927c-41ed-a7eb-a6628ab8bd45.png)
PoB is calculating the flat added as 2538 to 3980. In the screenshot we can see that we have a 40% more and a 6% less multiplier. Combined it should be 1.4 * .94 = 1.316 but PoB rounds it to 1.32 (also in screenshot). 

If you take PoB's calculated flat damage and apply the combined increased and "corrected" combined more (1.316 and not 1.32) we get final values that match the in game amount.

### How to reproduce the issue

1) Pick a character with more/less modifiers that combined have more than 2 digits after the decimal place. (in my case, 1.40 * .94 = 1.316)

2) Make a character that only uses mechanics that either can be tracked in game or remove them from PoB while testing (such as marks/other conditional effects/charges if you dont always have them in game) The cast/attack speed can differ since we only care about the damage in a single hit.

2) PoB will round it to two digits, and the damage in between pob and the game should disagree. (as you can see in screenshots above)

3) Note that correcting the precision in the calculation produces a result that matches the in-game values.

PS: My current build is rather involved so I am instead attaching a simpler character below. It is not a complete build. Note that the final "more" calculation for the ice spear skill's damage is 1.32 instead of 1.316. See notes for any extra info.

### Character build code

```shell
eNq1G11z2rryuf0VHh4655yZQvhMci45Z0ggLTOh4Ya0vfepI2wBOpElaslJ6a-_K8kGhyIjY9_MJDHWfu9qd7U2_b9_hNR7xpEgnF3VmvWzmoeZzwPClle1z4-37y9qf__1tj9FcnW_uI4JVSt_vX3T19cexc-YAl7NkyhaYvklpdT-BpTWiMkV5myC_uHRBx5c1T5xhmveHLGAyPSTT5EQn1CIr2ozH5BrHhI-ZsHN7r4BDBFhM-4_Yfkh4vFas30m-GXCA4AZT6b3D48ZpoRlmYLMb_pTijY4mkkkPQF_rmoDUB0t8RCF8BeoIRoDqeZlvXvZveydn3eal-1urZGLfB1HQp5GYbbGONgites9G-A0wqPFAvuSPOObiMibFWL-jt2ZDa8o7CSmkqwpwdFOlbpV_I-_EL-8tME-conocDrbgp6f1budbueifXF-dtm7yMfj8rj8X4lcXVMw6AlcFO54yYjEJyJPORGcldAvi2p3UUwp7D83WB7OCTvJGoMIo_uFCbgHFJBY7KKhaUOaIIZuuNg5qp0HOcUR7HH5CuHsCMIM-xzSQhaleVa_cGBzGNnK744ssDtkIVUShKLSnKbHaOYKV5jwaQI9QI50g5zJXQZq2enh71lAe0QP8Q83clnASyu5MZNu5LKAzW7XLt4zl7r0HbOLThejj9OdzlbQ6WojiI_oBP0gYRxCsn5ET5g5YN6R5UoySDQ21LbVMrckwsWxbjgNTsBaIS6Ko6n95GAEqM3-nwp2zHy3TfqZRVjg6DlT0nu5CA-wdVQPMafYEWPHItmAmUx4hNUSs4Tfxk2dO4z91QfouR6QxG5JegvVzTergnUyqwI8YNauI0IBIylEi5Hql3lIBc00YjhabmYrgmlQDDoV7AatHfKnMnMW28ncr9kVipgsakGTfEVR4FY7isr0jEQ2qzZ7-eYy4G6BiaHTBIQAu7bX04j_oxp4WgxtEIU8jhwdboCdFEirgzm4POAg9t0q0DWFI5ir9CAVpYUwBlIi_2nIgyUuxKQ4xixeryFRKJe74qnq9oAFyXQw73sO0PcQr07bVhVCdwY7aGcG29LuzmUPxV0XVZ4LKLMDd2axPRNPICOEkOn1gXrCd-nEely5haOU0zlKAzqez6b8BSRfqVGIKAYNbczxg9NthNnPjTP9V-BODEYsiCO1FZx57GMcYvNIQsiWQgyRRJ7AKPJXd-Dlq1ot8-kWUTqHnQ93FVa_oQdM6mocrnkk9c0bRH2haY7ZOpYe09OhkAj_2zxeLNQgCGjKSE-vRre3o5vH8ZdRIkYWRTwRSr-xOJyrSYf5vwuWGda50BPxXJjLq9oXgl9mCmuIJSIUTONzStFa4OCqtkBUAGcClxpmBvr6MoeahoKeNR0bHaa1A7BTGv3AkQR9oYj6EcFWubbrR4QyDFWBVW6zUVMDGTshk8NvkJCmAbBYSg-_7FTUPMqqjlrMwYWYQdTKOVk9Ygm5WWMBVZUsiK8iPt_ljwBtoHLs4vuwWfxNjr-TSmSnoSdcNgJm0Y5splQ27GQ1x6p6Qma1qlm1ow-xj6y6m0U78ran5AzMZKOyhcqh9IkzHeSwaQaEqqph9eyI4i2IneC9XOHIlCIrpQnkqBQkd-NEZB5L-zbOQOTYSp9wLRZSa3ZUc4qz6KDWcjLRq5ONxaBZGDspcyKwJrI81IecfPqQn0rTVttiebOao3962rConizniK6bH6vrk1YqLzVAn21PDWrRjmy21q8kZBQ7UtDbYIgXGBJY7j7YwuQkYBmzIeRKmWNQR1KmoA2eOQlMk1-KmlbyMLGdpQrRMvnloN0KU9SHoLKm3zsbVWL-ZDZnSf0ZkCOEIGd_zOkK3ChtTw0fMaLq0Q2n5Qj-MoMspSeXArFgqEYdJRVVk5J4DcRSye4PtXW7KNun2m-kDXdf9zjCE9CJf8ChuN7AeehWZfG9B01IGzZpgqV-RPsKJ2UX4AWKqbr_7xhRIjfqjJG5e2ceLDMehdsJNpBa8RcVmoaiarkEJOa7O7MyoDIhptil9jLWSQTSajb1veSmfqo82EmtNb6qtcAizKdxgMcsOSpuHUDRXMn2bin_lfc7G428T_ePo9k7CjdyftUjdzUD3vpiT6StxG_6oFgC_IHyOaKtFCV5EN86q71ab6br-sAzVt7a-FQ_Tf9uTDXWvZc2e81b4lB9nsARJ4DDWmMswZANZc2GlgSu9vG13_bkh6hjxvfqtKUmUxm-WpIJYSbZxGEId4MptL0SidAEcyWKjn3FGUWHNdVgUxQZMR30_oXcIcW3VJMoah62BdDyEmLVWOP8mDGSTaOOZPdMnZ2mVD3ULRoD261nIeQaDIMXlWNw4Ck63j3zFCU1jfRm0N4-4coVh0ZeVVlEb7kfi5LK5xArbIAtLU8TSxTvm7DTqauR5i6dkE0eVpePEcZputU0m0mqgw_ZN2iUPmcqpwiJo01yBlGzF8YDlT67Fxftds2TQC7z9o7aX_4O3Uj1-eHO-GUl5Vr82Wi8vLzU10iu-AL_IBTXfR421oAEMr3XLnivyDYG8HO9HOgfo15KqW_e5xGNRFWQXauplFMXnzicdNSaSqhL7knu-WprvVWffUr8Jw9qHvRRng9di_dC5EqVtjhk3rvvMQcYTgNz5UEd9CL-kixo8bwVkV6gq14C9NtFq6m4NFvt1u-aC5_rZ0nABEkv5BFuqFmWR4TXrLdbUCXArijw-EJ9bva835r1jveHV7_s_K40STXQ_lJDpGTmBYGunPCT8_C_EMctU8KgI5ETtN6WGrWclMJ2Uv4kkkMCXox055UGmQL8z1XtffJkrK8DNwkPdZ0W41hg88D-K0ZrzvTtTJ1MQHPAXldQyqGkAs50Dh7VQaXHawbLa85e0NobzDdCqK2tXe11axrDxFXDjc4-jdYJNAqgXHPowaqQ-5D-RWS_xlSWwb-FHfzktYtL3jokebsCz51gxdb_g0anAl16FcjRq8g3pcO7iHM_YjizylIiHAjsXmkJimwNaBie1XG7JMt2RVmhWVqSTgXR2KxgV3QKhkFhn5VieCj0q7Bc8azcLSt22ULSLiRAsPHMBLRMzBx2YPnY75amUDz5FHZ4eUN1q_FYq2zk9SpIE-0KNl275A7oVFR8y-7EZjV-bRcOyU5hjLKqVtVFnxI-FXm7V3b7VOTuqqL3pPKnCJ2SBU7EK-uHB8KWJ7SH5TKn1XNV5M8Tg6i0CdpFrd6syN2damzfLW2Bwvu_on1aRPJBGNMDLUq_kQx49JBNz4j0a1WcLcjyl5ekMMPhZkZ-4ql6n1ru3qya4IDE4YHXqva_e7dD0d_BaxxmMRbXXIijsPvfJjyKYL5meBBsSpGPV5wGOHqlrPk-Xvo-2Hn2dfFD8Gpsnb7ClSK1HXDS901TnG4-yut3dTPypU_pEv_1G_vf0_wfE-h92w==
```

**Comment by QuickStick123** [comment]
Normally they are rounded to 2 d.p. but because they are different types of multipliers I believe that is what has caused it to act with higher precision at least according to my general understanding of how GGG has implemented more multipliers. We just had some code in there forcefully rounding them and not using the above logic which would normally work. E.g. you can easily check two evasion more multipliers act as being rounded but iron reflexes with armour + evasion multipliers are computed (with rounding) then multiplied with no rounding.
