### ISSUE TITLE
Cremation Corpse Explosion Damage is affected by Modifiers to Projectile Damage

### ISSUE THREAD

**Issue by po0p** [PathOfBuildingCommunity/PathOfBuilding#5764]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

As per gem text:

A targeted corpse explodes, dealing area damage and turning into a volcanic geyser, which will repeatedly unleash projectiles sequentially....etc

So as far as I know explosion part happens before firing projectiles. (?)

This may not matter as I suspect corpse explosion from cremation to be secondary damage, so I'm pretty sure it should not be affected by projectile damage modifiers at all.

### What is the value from the calculation in Path of Building?

In POB when you use projectile damage modifiers, it changes cremation corpse explosion damage

### How to reproduce the issue

1.Select cremation as main skill, select corpse explosion on the left
2.Add GMP support, saying "Supported Skills deal 35% less **Projectile** damage"
3.Corpse Explosion damage changes

### Character build code

```shell
https://pastebin.com/vJQ35Pqg
```

### Screenshots

![image](https://user-images.githubusercontent.com/68482185/224283085-83c403dd-4218-4362-8ac8-a3e8346e528a.png)

**Comment by QuickStick123** [comment]
It should be a pretty easy fix you just need to change this bit of code in both the .lua and .txt files.
![image](https://user-images.githubusercontent.com/31533893/224287836-848ba491-64a3-4175-ab4d-1bb33cef34d6.png)
