### ISSUE TITLE
When importing my character it is only partially importing, e.g., incomplete passive tree.

### ISSUE THREAD

**Issue by Kaatseyes** [PathOfBuildingCommunity/PathOfBuilding#5767]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

It should import all the details

### How does Path of Building behave?

Part of the passive tree is built only, it misses extra links

### How to reproduce the issue

Import build
character import, my account name and to my pc, start
Select character
Import passive tree, jewels, items and skills.  
Click on done
Click on tree, incomplete.

### Character build code

```shell
https://pastebin.com/0sVa0vDb
```

### Screenshots

![Passive tree incomplete](https://user-images.githubusercontent.com/127688945/224566589-4db91233-b957-4898-b337-e01dbdfbcd2f.png)
![Passive tree using POE website vs 3 2](https://user-images.githubusercontent.com/127688945/224566592-ea4241eb-3371-4e2a-8a33-daecba88f6b9.png)

The version in POE is different

**Comment by QuickStick123** [comment]
What is your account and character name?

**Comment by QuickStick123** [comment]
Assuming your account name is Kaateyes I am guess it was just the server being slow at updating as it seems to be working now.
![image](https://user-images.githubusercontent.com/31533893/224591415-958a6562-7fc5-4791-9d22-ee147ff16c1b.png)

**Comment by QuickStick123** [comment]
Actually it might be caused by you importing into a older version of the tree?

**Comment by Kaatseyes** [comment]
Hi guys, ty, seems to be sorted now.  I reinstalled and latest version appears.  No idea how I got that old version o.O?  Thanks again.

**Comment by QuickStick123** [comment]
You had an old build open with a tree from 3.11 when you current build 3.20 it tried adding the nodes onto the 3.11 tree instead remaking it with a 3.20 tree, https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5768 should fix this issue.
