### ISSUE TITLE
Mace Mastery: "All Damage with Maces and Sceptres inflicts Chill" doesn't add to chill effect calculation

### ISSUE THREAD

**Issue by Smite-Sion** [PathOfBuildingCommunity/PathOfBuilding#5771]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Using the mace mastery: "All Damage with Maces and Sceptres inflicts chill" is supposed to add all the damage to calculate the chill effect. This most notable with the rise in popularity of Heatshiver. When looking at the chill effect in the Calcs tab, it seemed lower, so I added the text from elementalist to custom configs: "All damage with hits can chill", this corrected it.

### What is the value from the calculation in Path of Building?

Without custom modifier and with or without the mastery chill effect is 12%
With custom modifier and with or without the mastery chill effect is 19%

This based on the damage, so of course variable from build to build.

### How to reproduce the issue

Have any mix damage with cold and another skill (For example with a cold to fire support)
Have a mace or sceptre equipped (In my case I used Frostbreath)
Have an attack skill that uses the weapon (In my case I used Glacial Hammer)
Make sure that enemy is chilled box is checked if using Frostbreath, otherwise the mastery will auto conclude the enemy is chilled and change the dps and thus chill effect.
Compare the chill effect with and without the mastery. They should be different, but aren't.

### Character build code

```shell
I isolated the problem:
https://pastebin.com/HBSduDxq

With or without mastery chill effect is 279%
With custom modifier(All damage with hits can chill) it jumps to 408%
```

**Comment by QuickStick123** [comment]
It just seems to apply the chill flag instead of actually all damage with maces can chill.
![image](https://user-images.githubusercontent.com/31533893/224969370-e0c820e7-5a3e-4732-8f12-7eec69420f3b.png)
