### ISSUE TITLE
incorrect mod values for 2 of the current versions of vinktar flask

### ISSUE THREAD

**Issue by carenard** [PathOfBuildingCommunity/PathOfBuilding#5789]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

current values

### What is the behaviour in Path of Building?

legacy values

### How to reproduce the issue

1. Open POB
2. find vessels of vinktar and select either the proliferation or conversion version
3. notice how its showing legacy values(80-100 instead of 125-150), these are selected variations 14 and 15

### Character build code

```shell
https://pobb.in/dQN7cIf0xMaU
```

### Screenshots

![image](https://user-images.githubusercontent.com/129223703/228356240-75c68119-5074-419c-bdef-c1f408ea9a5f.png)

**Comment by carenard** [comment]
accidentally closed(new to github posting) when trying to add a comment so reopening.
found a second unique issue but don't want to raise a new issue post, balance of terror flammability exposure mod selection is broken https://imgur.com/a/jZRSIgy

**Comment by QuickStick123** [comment]
The balance of terror seems to be a parsing issue as the generated item data that gets added looks perfectly fine. This is further supported by trying to readd the `{variant:14}` back deletes it.
Raw Data
![image](https://user-images.githubusercontent.com/31533893/228708036-1a49d3b1-e423-4435-be7f-50a69a70225b.png)
![image](https://user-images.githubusercontent.com/31533893/228707825-56c9418f-2d58-41e0-8a06-6d7a883f7e75.png)
![image](https://user-images.githubusercontent.com/31533893/228707878-d37b924c-02ee-4588-b546-e690003e5f9f.png)

Result:
```
The Balance of Terror
Cobalt Jewel
League: Sanctum
Variant: Enfeeble: Take no Extra Crit Damage
Variant: Frostbite: Unaffected by Freeze
Variant: Conductivity: Lightning Exposure
Variant: Elemental Weakness: Physical Damage as a Random Element
Variant: Vulnerability: Double Damage
Variant: Conductivity: Unaffected by Shock
Variant: Flammability: Unaffected by Ignite
Variant: Punishment: Immune to Reflected Damage
Variant: Enfeeble: Critical Strike Multiplier
Variant: Temporal Chains: Cooldown Recovery Rate
Variant: Elemental Weakness: Immune to Exposure
Variant: Frostbite: Cold Exposure
Variant: Temporal Chains: Action Speed
Variant: Flammability: Fire Exposure
Variant: Despair: Inflict Withered
Variant: Despair: Immune to Curses
Variant: Vulnerability: Unaffected by Bleeding
Variant: Punishment: Intimidate
Selected Variant: 18
Cobalt Jewel
Has Alt Variant: true
Selected Alt Variant: 18
LevelReq: 56
Limited to: 1
Implicits: 0
{range:0.5}+(10-15)% to all Elemental Resistances
{variant:1}Take no Extra Damage from Critical Strikes if you've cast Enfeeble in the past 10 seconds
{variant:2}You are Unaffected by Freeze if you've cast Frostbite in the past 10 seconds
{variant:3}Inflict Lightning Exposure on Hit if you've cast Conductivity in the past 10 seconds
{variant:4}{range:0.5}Gain (30-40)% of Physical Damage as a Random Element if you've cast Elemental Weakness in the past 10 seconds
{variant:5}{range:0.5}(6-10)% chance to deal Double Damage if you've cast Vulnerability in the past 10 seconds
{variant:6}You are Unaffected by Shock if you've cast Conductivity in the past 10 seconds
{variant:7}You are Unaffected by Ignite if you've cast Flammability in the past 10 seconds
{variant:8}Immune to Reflected Damage if you've cast Punishment in the past 10 seconds
{variant:9}{range:0.5}+(30-40)% to Critical Strike Multiplier if you've cast Enfeeble in the past 10 seconds
{variant:10}{range:0.5}(20-25)% increased Cooldown Recovery Rate if you've cast Temporal Chains in the past 10 seconds
{variant:11}Immune to Exposure if you've cast Elemental Weakness in the past 10 seconds
{variant:12}Cold Exposure on Hit if you've cast Frostbite in the past 10 seconds
{variant:13}Action Speed cannot be Slowed below Base Value if you've cast Temporal Chains in the past 10 seconds
Inflict Fire Exposure on Hit if you've cast Flammability in the past 10 seconds
{variant:15}Inflict Withered for 2 seconds on Hit if you've cast Despair in the past 10 seconds
{variant:16}Immune to Curses if you've cast Despair in the past 10 seconds
{variant:17}You are Unaffected by Bleeding if you've cast Vulnerability in the past 10 seconds
{variant:18}Intimidate Enemies on Hit if you've cast Punishment in the past 10 seconds
```

**Comment by QuickStick123** [comment]
The balance of terror issue should be fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5794

**Comment by carenard** [comment]
> The balance of terror issue should be fixed in #5794

that was fast lol, the original issue still remains unless someone is planning fixing it with next league stuff, I would submit the fix myself but I don't want to figure out how, rather spend that time making other weird off meta builds in POB. will keep contributing with any bugs and such that I find though to help keep this community tool at its best.
changing
{variant:5,6,7,8,9,10,11,12,13,14,15}(100-80)% increased Charges per use
{variant:16,17,18}(150-125)% increased Charges per use
to
{variant:5,6,7,8,9,10,11,12,13}(100-80)% increased Charges per use
{variant:14,15,16,17,18}(150-125)% increased Charges per use
in the flask.lua file under data/uniques is all that is needed(this is for vessel of vinktar on case there was a 2nd flask with so many variations).
already fixed it myself locally... but that change will be cleared if I click the update it pesters me with now.

**Comment by QuickStick123** [comment]
Yeah it is an easy fix so left it open to try and lure in new people :)

**Comment by DavidBindloss** [comment]
You've lured me. 

#5800 resolves this.
