### ISSUE TITLE
Rigwald's curse impact on passive tree not shown

### ISSUE THREAD

**Issue by oseparovic** [PathOfBuildingCommunity/PathOfBuilding#580]
With Rigwald's curse all claw nodes should contribute to unarmed attack damage, attack speed and critical strike chance. Is there a way to get this to work? Is there a workaround?

Example: https://i.imgur.com/WyqV2ni.png

PoB pastebin:  https://pastebin.com/6r357HNP

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.1

**Comment by oseparovic** [comment]
Fix confirmed after updating to 1.4.161.2 https://i.imgur.com/EjRvGN5.png

Thank you for the super quick fix 👍
