### ISSUE TITLE
Error When Importing Passive Tree and Jewels Over Top of an Existing Build

### ISSUE THREAD

**Issue by dsnvwlmnt** [PathOfBuildingCommunity/PathOfBuilding#581]
Manually importing into a New Tree in the same build worked fine.

1.4.159.1

Steps:
1) Here's a copy of the base pob https://pastebin.com/yBcUizW4
2) Then Import/Export account unsane character unsaneKnifing
3) Import passive tree and jewels (deleted jewels selected).
4) Error appears.

![image](https://user-images.githubusercontent.com/14173022/76692256-410bf000-6611-11ea-9b3a-aec9d8d40ecd.png)

**Comment by custompro12** [comment]
Probably dupe of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/571

**Comment by WSXWSX2017** [comment]
Have the new support and skill gem been added yet?

**Comment by WSXWSX2017** [comment]
Have the new support and skill gems been added yet?

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162
