### ISSUE TITLE
Can't load any build after latest master branch update

### ISSUE THREAD

**Issue by FloryanFilip** [PathOfBuildingCommunity/PathOfBuilding#585]
![Capture](https://user-images.githubusercontent.com/23243818/76697022-1e6deb80-6692-11ea-97df-8ab5d515957f.PNG)

On Branch master, version 1.4.161.1

**Comment by itsamemarkus** [comment]
same for me. Happened previously (with last release) when I tried to import public profile that had delirium jewels.

**Comment by extrover** [comment]
Same here, but not just when opening profiles with clusters. Same thing happens when trying to open a new empty profile.

**Comment by LocalIdentity** [comment]
Just pushed a fix. Should be available to download any minute now

**Comment by justin-n-meyer** [comment]
Thank you. Fix worked for me.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.162.2
