### ISSUE TITLE
Increased attribute requirements on Mjolner are broken

### ISSUE THREAD

**Issue by FruitcakeElemental** [PathOfBuildingCommunity/PathOfBuilding#5852]
I recall the increased strength and intelligence requirement explicits of Mjolner used to work. However it has been broken for a while and still is in 2.25.1 (beta). 

Steps to reproduce:
1. Create a new character
2. Search for and add mjolner from the uniques list.
3. Check str and int requirements.

Expected: Character strength requirement is 412 and intelligence requirement is 300.
Actual: Character strength requirement is 212 and intelligence requirement is 0.

Link: https://pobb.in/wcz00DFiwquQ

**Comment by LocalIdentity** [comment]
Just fixed on dev for the next update
