### ISSUE TITLE
Gems in The Squire being counted multiple times

### ISSUE THREAD

**Issue by jaden4g** [PathOfBuildingCommunity/PathOfBuilding#5867]
As of release 2.26 some gems socketed in The Squire are being counted multiple times. It appears the gem in the first slot is counted three times, the gem in the second slot is counted twice, and the gem in the third slot is counted just once. 

https://pobb.in/IqjWhNzpOGYc

![image](https://user-images.githubusercontent.com/42361715/229397492-eed87ed3-7f56-44dd-80db-e58ef60d181e.png)
![image](https://user-images.githubusercontent.com/42361715/229397623-94ffa44d-c8e0-47f9-a851-0ce7efcb46aa.png)

**Comment by Wires77** [comment]
Minimally reproducible example: ```bash
eNrlXFtv27gSfq5_BWFgD1psfZHkS5KT7MK5G4ibrJ225zwtGIm2taVFV6KSehf972d4kS07pixFejstsCuL833kDDnDGUrq6e8_FhQ9kzDyWXBWt5rtOiKByzw_mJ3VPz9eN47qv_9WO33AfH4_PY99Klp-q707ldeIkmdCAVdHHIczwr8kTM6fwLTEAZ8TFozwXyy8Yd5Z_RMLSB094cDzefLLpTiKPuEFOatPXADXEY5cEngXm_tacI5D7HIS3oleBzFnI-ZBKw9jaF1gP5gw9xvhNyGLl3JQzz55UTLD0cP9-DE1JD9IDwk0enf6QPGKhBOOOYrgP2f1ARgGz8itz4EK0xh47E6n3zw67vS79VYm6DwOI36JF3BZADxZEuKt5a3mkX3U7Vsd9V8T6CEkV9Mpcbn_TC5Cn1_MceBuejV2VlR2FFPuL6lPwo1GzWPLBLl9xW612ybhR8YxvXyYrGXBVL2m1W13shFsMzVG7q8-n59TMGwhfoEazgKfk8KwB-ZHLHiTNmmQUaGLmFJww1yyYxKR8Blzf3tAZm62ePKDgrYa4QBfsGgzF71-lugDCcHB-RaifQAwIS6DmJCGWLbd7CbOYR_n6HE_j7HrO39K8ksW0koDio7mbXpcTfLKFSZ-24DGEBXzSU5YTHNK8lRYynCH72nBI2PAuyQ_8tGlBS3LGA2HAc_HtyVo2ebxPTMud8tDhpGh5er2IRWGj_vNjtNxnG6_bZu3lfkq8l1MR_iHv4gXEM4f8TcSpGg65qU6m_MAQpQJ6xyZoNd-SIqjLhj13oCaYxYZYcdZjriJdO2Mvdw9EbLDwM3n3Z-DUEbrVArQywSMwedEuvFESU7EpgvtuXk2Z9XVjAS6v1U-de4Icec3kJaNMSf5Av0mEck2q5DNZVYhuMes3ZyAAkYSQIORmpl7U0EzXQUknK0mc59Qr5h0MrALvMwRToWZ0-hc5t7urtCKSUMLmuQrDr18m07RMT3jKB1jO-YkXNlLyedbmQRSUgB4ZCdL7mck-uwvkebTgrhBuGBxmAqITqYWSjyXEskeoQqdMfFid2tTOjYizynUajsamHM4GBel-yBG_gHn2P12ybwZyQuRnRRHTOLlEuKFmPi8OLHJQWLup_KaRi-H9D0s21zeK_bD_B1spHN3sN7h8_eyA8mvi9ild7vp2jnEc3exLp9HEBgWEPBlHT5iXjqGG0uaayjHctVWUjBnjffAXmDwc3GqEhWThoRm4-rGoYQk-HuVm39LPFcHV4EXh8Ibcvexi9jXzaO_gLAZRZeYY-TpFPgLDn0ccFse-UQEh-78Dmb_GlP6BDHgrJ6-K37tAC0BFPynLXmqJa6GiyULubx5gakbyd6HwTLmKJBHUgs_cv98iqdTcb4EHfBQHpldXV9fXTwOv1zpAach0Tef0j-DePEkTlDU_5Ou351OiAydKIqfInV5Vv_ik5eJQF0Sjn0KRnQZpXgZEe-sPsU0gp59uJQyE7CMyzPYpBTkucmp1H6ujYCZ6eoHCTnoCxuvG_rEOK51-4FBqQ7Fpiwm2MQmDnvMRCrgX-CIq6TBYCl5wGZmEedcRnVEYwYW1gymxp516wFL8NWSRLAJ-1PfFb6RPeWPIK2kMuziuuBW7ipjvvW2ZeaQp2cmAtVoBqvTMBNat2ZYVZ7BGa2qWs3wS-Jio-6q0Qxe56EskIfA-1nWUhlMn1ggFzk4zcCnYosxzuwVJWsRM-E9n5NQ7VtGphHEqEQk03FC_ynmZjdOSWTYSlbFBguJNjNUVX4GHURbRiTaqoYMBk3LmKlUFWEMZFlQlW4Y7aeTl4wp0Am6wfyqNcMISZli0F83ZziJjL-DZ-Z7KoE1uMuOWFbAgFS9PI1MxsvT7Kbp5RmvKY6-Gedbt5rhn6GG8_lqD4t6lpWLRDhVOQbhW-UYxruJxAY7zk4hZPy6JFMChs4MYGuZjPnlcXAJmxzPmNucVHJY-x1ho1ohLhXK92pamFEtUH1OmbWGlcgBItiLbjOynXxM69LplmAqHn0xWo7w1XlsKT0Zj3DgXYpjn5KKilOjeAlkycju96WrmyndZT1tJYXEqczdIhRBhXFDFtH5CirCa7E77Tx-w9KwOrnnqrxJY5LuPDLFMRX3_4ixCCyiykrdvVNP6QMWLtbH-UA1Zy8iKCpGkUpGsNfc3amWAeWaTHSX2EtZRw9IqmnJe_qmfAg_2IxaaizH7QcujT0yDHSxDKPxYaFQ_CRGJl46EIfYawNGlIlzPYKXMAtWfZd33e27UxidBt9Q9oSpnVDoVxPsdn2r3Vp3IYiGcnt16-i70nUok0JptzqakYX4PYLay4N6szXkYImWMEdLjgKu0lhp9B09YMkEauJECShO11R_LWU0xXPYgNJWZUxo7zGhQFdmRL2QoJKANLiwNdercBuf16IK1apamWHghgSDW4u6b3PKWUK9Q4x5FV7zoIQIpWv29MLSl-CuMgap0CMuH0NCkggjSS3t3fAj_QaO0Kotlk_ESbjS5YRYbwHzRMToHh05Th1xoEu9_WNb-sUeBVej-jy-U3M053wZnbRaLy8vzSXmczYlP3xKmi5btJYAgjE15Gw0BG1rAH_OZwP5R6mXMJ2qN36illYVxi7VFMqJi08MihbRJm4mP6Tq4mhFHwtNeCj0-ZuxxX-lriL-wXbGR3ipnUy06Sjq6MgJZfelD9YI5aadzJYQ_E9yyHUqF4E2srhOongcEfW4XLmnvJ24owSlQ-sYwxyvTtDnT8M_Pl_VHucETb7HfkhqUCnOcMDRGJaIh1SBU1PVwglyjhx9fQ4rRT_IAiOfoHbT6R91a7osUJL6h0FU7wQnyG7XtMVP0E0D_takVcbk-wnqt2vDxZL6ri9arZplt38RQUuvVFkSoOTZS-0WR8hBmqw2gNCnrxEOCfo6h6q-9k-Igxk5aTe7P399320cffgFcYb0YBCbagiQaxdDwt9qe-8iFwcI9jC2vqt34WnIFmgFZkIjiCLoFnb4dMfvrXa7YXXbH9K6KLsiEEXacNtjdRpdkFfHKmLIUne5XkfMGwtBJMXFuXK3ridbu65Rwj4o4RyU6ByU6B6U6B2USE7KZRDcrOlnddwqGLRC-9b3YEmW_wKviP4dIVFD1O6XEN6-imnR57Un6AGWiN10mu3tW06z__qWZe25d_z6nr0ldxGH4Ni8pg5VYcrXLb3aP1qRE-uj_dH52PnY_bkZ415XOW_A35Sr9Oy0qzgpxp9bS6_fsLcXnqxkdazfoJJRpLHOUaNj58D2tlB2v-FYuVD3UNWgF-ksKXOkyQaeF6H33Xaj1_0gnOD9MThSG67lExpNKRpkF9GGRyrzsfeaSxA4bUVmdeDHcdvMltaq23C27SiOiZE8C94NMlZbRRlFq05uhBvvzPrPzlZwE5U0Eu8pyagkA8uWPj_VMWckAg3ApjD1HBL09b6NRKycyi12g9uxwSGK9067IePULo-y5h2LCOq01VBf5jB7ggh2IoTViP_v4lOGxNFBieODElb7sMhhq67fANsOpqL8MmUR23UZlAEINtPFwxMkTTJvkw-jIPd9FscRoknlaK1swKYYSyD2Icg5g_IbDZ5WUYST_R11C_R5TijfxdsF8PL8Cjlv0BJNXvByt-vOW4hKqJ8UbxVw7FeoV4FCvQoUehPHPoWsIotr3-p0KrCIXZU2RdbbLaELwkvZY4-z9UqPwC7MULpLpyr7dytYDFYF7mFVMI5OwZVQVYixy3pkpwIDFt8zKguxTln97ZIuXGwA3iopbkusQZVblGHY79jd0gy9qqbVqirGFF-a5e3YKT2X3WoWVRHlB4uYEl5BJHQqCChOSafslMRb1dj_zTtl4UXbKYx4Sxa1gVhvsWq3bKyuaFo6VQWXyvLqN5dQBXBjP5gVmvX9ocmuZg4q2ymqKPg6b9OpqPHL7_EVJRvd0gMpv8X1igaDssHjdYfqzCd5dCcfJskXklkw9WevXi_e_dp-81Ky_MT99fvIIYnA9i4Rry5uv8U8-HI1Htzse4d59_v5g52QgCxWw-icRVE-2Yn_N3kQ31_xjfyIeH682INQ_5LAXuIHil0yZ9Qj4Ra9-sI-efu6n_6ga5-8eMCaPKVNQM4BTOJ9ibxtH-4j-XQkwXSzIfqDG0apPDZMK5QNXL8rmADSn2rvA2x_4pPqKHmrRa_G09buPxLxP0sZBY0=
```

It actually seems like the number of duplicates is based on the number of gems.  In this example, Chain is only duplicated twice, since there are only two gems in the Squire.  Note that these are bonafide duplicates too, damage multipliers and all, which *really* shouldn't happen.
