### ISSUE TITLE
Error converting build to version 3.21

### ISSUE THREAD

**Issue by konovalov-** [PathOfBuildingCommunity/PathOfBuilding#5871]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

It should convert the build to a new version correctly.

### How does Path of Building behave?

I got the error:

![image](https://user-images.githubusercontent.com/1780387/229401184-f87c921a-ab21-4f3d-bc0e-233976e11e65.png)

### How to reproduce the issue

1. Import build from https://pastebin.com/wB7ZS8BB
2. Press Convert to 3.21

### Character build code

```shell
https://pastebin.com/wB7ZS8BB
```

**Comment by Regisle** [comment]
You seem to have a broken tree, it has a broken node in `47197` which is the reservation mastery connected to sovereignty, if you allocated that mastery there and then convert it seems to work fine (if its still allocated or if you unallocate it before converting)

**Comment by konovalov-** [comment]
Thank you, this helped
