### ISSUE TITLE
Radiant crusade and certain other mods affected by aura effectiveness

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#588]
Not sure if this is a bug, but it seems unintended. The buffs from `Radiant Crusade` (and similarly, `you and nearby allies` buffs, like from the new `Precise Commander` notable, flat damage from `Crown of the Tyrant`, etc.) are affected by `#% increased effect of auras on you`.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
