### ISSUE TITLE
Error when updating tree to 3.21

### ISSUE THREAD

**Issue by PreFollower** [PathOfBuildingCommunity/PathOfBuilding#5882]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![изображение](https://user-images.githubusercontent.com/13599515/229450589-ec4b2650-83d9-40cb-b886-fb23f3ea0368.png)
![изображение](https://user-images.githubusercontent.com/13599515/229451170-67b7d08b-e4ae-4cea-924c-b7035dd8f3d4.png)

### What are your system specifications and configuration?

Windows 10
Nvidia GTX 3070
Intel i5 10400
16GB ram

### How to reproduce the issue

1. Import this Sabo build https://pobb.in/ly7av2QtcdVe
2. Click "Convert to 3.21"

### Character build code

```shell
https://pobb.in/ly7av2QtcdVe
```

**Comment by Regisle** [comment]
similar issue to #5871, You seem to have a broken tree, it has a broken node in `55491` which is the reservation mastery connected to influence, if you allocated that mastery there and then convert it seems to work fine (if its still allocated or if you unallocate it before converting)

**Comment by QuickStick123** [comment]
Basically what has caused this is the 3.18 15% mana reservation mastery got deleted when people converted the trees but didn't get removed from the allocatedNodes so now when you got to convert the tree again it crashes. I think you can fix this by reallocating all you reservation masteries.

**Comment by quodZ** [comment]
> Basically what has caused this is the 3.18 15% mana reservation mastery got deleted when people converted the trees but didn't get removed from the allocatedNodes so now when you go to convert the tree again it crashes. I think you can fix this by reallocating all you reservation masteries.

I reallocated all the passives for reservations tested various thing they dont solve the problem. 
Got any ideas if i can try another thing?
Deleting all passive trees fixes the issue but i got other builds also that have the same problem
I even removed the Implicit regarding charisma

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/229476844-971951f0-e5ba-4327-b177-80ff87827bb3.png)
Allocate any reservation mastery then unallocate it and it won't crash on convert.

**Comment by PreFollower** [comment]
Yes, unallocating the wheel and then allocating the mastery allows to convert the tree. Then you can respec back and it works as intended.

**Comment by Peechey** [comment]
@JopvanBerlo Allocate any of the reservation masteries here then convert to 3.21
![image](https://user-images.githubusercontent.com/92683202/229558560-5f768f1c-6df8-4a4f-be1a-b618faf84994.png)
