### ISSUE TITLE
Hand of Wisdom and Action

### ISSUE THREAD

**Issue by Wolsonx** [PathOfBuildingCommunity/PathOfBuilding#5883]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

3.21 Patch |Notes state that  HoWA now stacks lightning damage per dexterity, yet in pob i see someone did change everything except this one line. Patch notes below:

"The Hand of Thought and Motion Unique Claw is now found on the Imperial Claw basetype (previously Blinder). It no longer Adds 1 to 50-60 Lightning Damage or Adds 1 to 5 Lightning Damage to Attacks with this Weapon per 10 Intelligence. It also no longer has 20-25% increased Elemental Damage with Attack Skills or 10-15% increased Attack Speed. Instead, **it now provides 8-12% increased Dexterity, 8-12% increased Intelligence, and Adds 1 to 10 Lightning Damage to Attacks with this Weapon per 10 Dexterity. It also provides 5% increased Critical Strike Chance per 25 Intelligence, and has "Recover 1% of Life on Kill".**
The Hand of Wisdom and Action Unique Claw no longer provides 25-30% increased Elemental Damage with Attack Skills. Instead, it now has 1% of Attack Damage Leeched as Life."

### What is the wording in Path of Building?

Hand of Wisdom and Action
Imperial Claw
League: Breach
Variant: Pre 2.6.0
Variant: Pre 3.0.0
Variant: Pre 3.21.0
Variant: Current
Selected Variant: 4
Imperial Claw
Quality: 20
Sockets: G-G-G
LevelReq: 68
Implicits: 4
{crafted}Quality does not increase Physical Damage
{crafted}1% increased Critical Strike Chance per 4% Quality
{variant:1}Grants 25 Life per Enemy Hit
{variant:2,3,4}Grants 46 Life per Enemy Hit
{variant:1,2,3}{range:0.5}(20-25)% increased Elemental Damage with Attack Skills
{variant:4}1% of Attack Damage Leeched as Life
{range:1}(8-12)% increased Dexterity
{range:0.5}(8-12)% increased Intelligence
{variant:1,2}Adds 1 to 6 Lightning Damage to Attacks with this Weapon per 10 Intelligence
{variant:3,4}Adds 1 to 10 Lightning Damage to Attacks with this Weapon per 10 Intelligence
1% increased Attack Speed per 25 Dexterity

**Comment by QuickStick123** [comment]
>The Hand of Thought and Motion Unique Claw is now found on the Imperial Claw basetype (previously Blinder). It no longer Adds 1 to 50-60 Lightning Damage or Adds 1 to 5 Lightning Damage to Attacks with this Weapon per 10 Intelligence. It also no longer has 20-25% increased Elemental Damage with Attack Skills or 10-15% increased Attack Speed. Instead, it now provides 8-12% increased Dexterity, 8-12% increased Intelligence, and Adds 1 to 10 Lightning Damage to Attacks with this Weapon per 10 Dexterity. It also provides 5% increased Critical Strike Chance per 25 Intelligence, and has "Recover 1% of Life on Kill".

>The Hand of Wisdom and Action Unique Claw no longer provides 25-30% increased Elemental Damage with Attack Skills. Instead, it now has 1% of Attack Damage Leeched as Life.

You are confused and are referring to hand of thought and motion.

**Comment by Wolsonx** [comment]
The unupgraded version stacks dex and the upgraded one should too then, no? 
HOWA should have same lines + 1% leech instead of EDwA

**Comment by QuickStick123** [comment]
We really need clarification on GGG's part as it could be interpreted either way.
Another item they might've not explicitly mentioned being changed like the regular is Replica Red Trail as the ranges on some of the stats are the same.
