### ISSUE TITLE
Charges for minions doesn't work!

### ISSUE THREAD

**Issue by VNHPX** [PathOfBuildingCommunity/PathOfBuilding#5886]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

After the update my build drop it's DPS and I found out that the minions charges didn't work!

### How does Path of Building behave?

Here are the screenshot that the DPS didn't change either "Do your Minions use Frenzy Charges?" is tick or not and one screenshot that I have custom modifiers for the frenzy charge stats and the DPS rise up.

### Screenshots

![1](https://user-images.githubusercontent.com/129740743/229476971-2990e72b-04f0-4ff3-a08b-eaddd46f3df4.png)
![2](https://user-images.githubusercontent.com/129740743/229476979-b118dd13-3b14-4e87-a404-353e8cf281d7.png)
![3](https://user-images.githubusercontent.com/129740743/229476988-df5358bf-8987-4174-9058-599611c18ebf.png)

**Comment by QuickStick123** [comment]
Likely related

> Quick bug report, I think the update broke Unholy Might for minions, at least. Checking the node on Necromancer / Configuration doesn't do anything.

https://www.reddit.com/r/pathofexile/comments/12a5s10/comment/jes0b61/?utm_source=share&utm_medium=web2x&context=3
