### ISSUE TITLE
Allow node tooltips to ignore the benefits of level up in the new "auto" mode.

### ISSUE THREAD

**Issue by 00zau** [PathOfBuildingCommunity/PathOfBuilding#5887]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

When auto mode is enabled, the life and mana from leveling up are included in the "allocating this node will give you:" tooltip, which creates a bunch of clutter. A node that does nothing for my build has 10 lines of bloat (and could have even more if I was leech capped or my ele resists weren't all the same, etc.).

![Screenshot 2023-04-03 08 18 11](https://user-images.githubusercontent.com/63163581/229506935-9ff35ebf-3618-4291-9412-630f4439f190.png)

Example; this sword node does nothing for my bow build, but the added life changes my HP, my hit pool, 3 different "max hits (could be up to five), my max mana, my mana reserved (as a % and as a value), my many regen, and my mana leech, and this is on the low end of how many lines could be added.

### Describe the solution you'd like

I'd like for an option to have the tooltip ignore the stats from the new level when displaying what you'll gain from that node.

**Comment by QuickStick123** [comment]
You might be able to switch to manual to hide this but that isn't super desirable in some cases.
