### ISSUE TITLE
Unable to open certain builds after the last update

### ISSUE THREAD

**Issue by A68PL** [PathOfBuildingCommunity/PathOfBuilding#589]
Cannot provide Pastebin codes from obvious reasons. Attached .xml build files instead, renamed to .txt. PoB doesn't update to the latest 1.4.162.2.

[[3.8] Incinerate EB Trickster (Beor) (3,4,3).txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4334076/3.8.Incinerate.EB.Trickster.Beor.3.4.3.txt)
[[3.8] Molten Nebuloch (Tuor) (2,3,5) UPDATE.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4334077/3.8.Molten.Nebuloch.Tuor.2.3.5.UPDATE.txt)
[[3.10] Dual Strike Instant Leech Champion (Barahir).txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4334078/3.10.Dual.Strike.Instant.Leech.Champion.Barahir.txt)
[[3.9] Facebreaker Impale Warcry Cyclone Berserker.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4334079/3.9.Facebreaker.Impale.Warcry.Cyclone.Berserker.txt)
[[3.10] Tectonic Nebuloch Chieftain.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4334080/3.10.Tectonic.Nebuloch.Chieftain.txt)
![3 9  Facebreaker Impale Warcry Cyclone Berserker](https://user-images.githubusercontent.com/62204358/76700351-91855b00-66ae-11ea-8fc3-c0250600a310.png)
![3 10  Tectonic Nebuloch Chieftain](https://user-images.githubusercontent.com/62204358/76700353-92b68800-66ae-11ea-8101-62819f2b6571.png)
![3 8  Bloody Retaliation Lacerate (Isildur) (4,3,5)](https://user-images.githubusercontent.com/62204358/76700354-92b68800-66ae-11ea-836a-fb1bc4adf13b.png)
![3 8  Incinerate EB Trickster (Beor) (3,4,3)](https://user-images.githubusercontent.com/62204358/76700355-934f1e80-66ae-11ea-83ff-1d9dec786bdd.png)
![3 8  Molten Nebuloch (Tuor) (2,3,5) UPDATE](https://user-images.githubusercontent.com/62204358/76700356-934f1e80-66ae-11ea-916e-d34ae99ffabe.png)
![3 10  Dual Strike Instant Leech Champion (Barahir)](https://user-images.githubusercontent.com/62204358/76700358-93e7b500-66ae-11ea-813b-704880ca651d.png)
[[3.8] Bloody Retaliation Lacerate (Isildur) (4,3,5).txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4334081/3.8.Bloody.Retaliation.Lacerate.Isildur.4.3.5.txt)

**Comment by Panum-Wandering** [comment]
Having these exact same issues except with changing skills in my PoB.
![image](https://user-images.githubusercontent.com/62205704/76700891-a697c500-6681-11ea-8030-97e092603557.png)

**Comment by Smeagol001** [comment]
it may have to do with thecluster jewels since pob cant  import certain  chars either if youre not using the fork from localidenntity

**Comment by glitterguts** [comment]
happening for me too. i have no cluster jewels or anything, i updated straight from 1.4.159.1 to 1.4.162.2
here's the build causing it: https://pastebin.com/U6c6xy4a

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
