### ISSUE TITLE
Treat switching between Auto/Manual leveling as a change that needs to be saved.

### ISSUE THREAD

**Issue by zemoto** [PathOfBuildingCommunity/PathOfBuilding#5892]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

When switching between Auto/Manual leveling without saving a build, it does not remember my choice next time I open PoB or switch back to the build. If I do save due to a different change it does remember.

Changing between Auto/Manual leveling does not give me the option to save my build and therefore save the setting.

### Describe the solution you'd like

When I switch between Auto/Manual leveling, PoB should see that as a save-able change.

### Describe alternatives you've considered

If not a save-able change, this particular setting should just be auto-saved/remembered for my open build.

**Comment by Lilylicious** [comment]
Fixed by #5891

**Comment by Lilylicious** [comment]
Closed due to fix being merged a while back.
