### ISSUE TITLE
Mjölner/Poet's Pen/Cospri's Malice Cast speed support

### ISSUE THREAD

**Issue by 44shades44** [PathOfBuildingCommunity/PathOfBuilding#59]
Would it be possible to implement the cast speed modification in relation to attack speed of these items?

Also Mjölner's "Socketed Lightning Spells deal 100% increased Spell Damage if Triggered" Doesn't appear to do anything.

Just want to say I recently found this fork via reddit and really appreciate the work everyone's put into it, Thanks guys!

**Comment by ASprengle** [comment]
Related, having the option to filter Show Node Power by attack and cast speed would be very helpful for builds that trigger spells on attack, such as the three mentioned here.

**Comment by Nostrademous** [comment]
Fixed in #2294

**Comment by Nostrademous** [comment]
Fixed in 2.0.0
