### ISSUE TITLE
Minion Instability Calculation GONE Altoghether

### ISSUE THREAD

**Issue by Ainareth** [PathOfBuildingCommunity/PathOfBuilding#590]
Hi, i really enjoyed using Path of Building and have just come to this fork because main PoB doesn't display Minion Instability Damage as of PoE 3.10 tree. I was a little bummed to see that this Fork has the very same issue...

I assume this is known, but haven't found any other issues relating directly to this problem, so here i am posting...

**Comment by LocalIdentity** [comment]
I’ll try to release a fix for this soon, they changed the wording of the mod on the tree so it stopped parsing correctly. For the moment you can just add Minion Instability to a piece of gear and it should work

**Comment by Chemdubs** [comment]
I tried adding minion instability to a couple different pieces of gear and the text isn't red so it parses the mod name correctly; having it on gear does not change the tool behavior.

**Comment by MechanosG** [comment]
I tried the gear add thing too with no luck.  Looking forward to the next update.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
