### ISSUE TITLE
unstable Mitigated Hits calculation

### ISSUE THREAD

**Issue by jjwong0915** [PathOfBuildingCommunity/PathOfBuilding#5907]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

This is a PoB only value.

### What is the value from the calculation in Path of Building?

This is a PoB only value.

### How to reproduce the issue

When spell suppression chance hit a certain point, the Mitigated Hits value will have a unreasonable increase which greatly affects the Effective Hit Pool as a result.

I believe that this bug comes from the `numberOfHitsToDie` function, however I have not yet confirmed which line caused it.

### Character build code

```shell
Build Link: https://pobb.in/MrUkxpa_Q25d
In this build example, Mitigated Hits will jump from 0.99 to 1.41 after allocating the QuickStep notable passive which only provides 10% of spell suppression chance and some movement speeds.
```

### Screenshots

![image](https://user-images.githubusercontent.com/8567515/229675235-20bb3247-2ed1-47eb-9567-45ac6f306417.png)

**Comment by QuickStick123** [comment]
This some weird breakpointing behaviour and it was not introduce in 2.26 it was present before.
