### ISSUE TITLE
Arcane Capacitor's "mana spent recently" has no effect

### ISSUE THREAD

**Issue by A68PL** [PathOfBuildingCommunity/PathOfBuilding#591]
Arcane Capacitor's Arcane Surge's effect increase with mana spent recently has no effect. 

Icestorm is attached to Arcane Surge.

![2020-03-15 13_29_18-Path of Building](https://user-images.githubusercontent.com/62204358/76701431-f180ff00-66b8-11ea-8b50-24afa51888a3.png)
![2020-03-15 13_28_46-Path of Building](https://user-images.githubusercontent.com/62204358/76701433-f34ac280-66b8-11ea-9480-a3fb1994e738.png)
![2020-03-15 13_28_37-Path of Building](https://user-images.githubusercontent.com/62204358/76701435-f34ac280-66b8-11ea-8651-6981012cd6bf.png)

https://pastebin.com/fduQwd7r

**Comment by ppoelzl** [comment]
Known issue, it's kinda hard to fix.

**Comment by ppoelzl** [comment]
"Mana spent recently" works as intended BTW, the real issue is a duplicate of #174
