### ISSUE TITLE
Unnatural Strength Ascendency node is not being applied at all (has 0 effect in PoB).

### ISSUE THREAD

**Issue by FramFramson** [PathOfBuildingCommunity/PathOfBuilding#5911]
Necro with grouchy old SRS build (conventional, non-poison)

With yesterday's 2.26.1 update for 3.21 I noticed that for some reason my Ascendency had several nodes de-allocated on converting to 3.21 to preview changes.
![UM_Bug00](https://user-images.githubusercontent.com/101145521/229696862-c18d229d-5ec7-4bc0-ba15-5be200dffbef.png)
The four nodes leading to Unnatural Strength had been deallocated (and oddly the one small node was _added_)

This was not a major issue as everything still worked fine after I reallocated the correct Ascendency points. 

However, with today's 2.26.2 update, Unnatural Strength appears to have broken completely. This was especially confusing as this was true across all saves, including ones I had not touched in months. 

Luckily I have another copy of PoB on another computer which had not yet been updated and was using the older 2.25.1 January update. I was able to compare the exact same file using the the older version and Unnatural Strength still worked correctly (see 1st & 2nd image below). 

Furthermore, I was able to restore the functional effect of Unnatural Strength by simply editing it in as a custom modifier (see 3rd image below), and as far as I know the functionality of neither SRS nor Unnatural Strength are changing. So this appears to just be a bug specifically related to PoB's implementation of the Necromancer Ascendency. 

Any help would be appreciated, thanks! 

![UM_Bug01](https://user-images.githubusercontent.com/101145521/229696871-233cca08-b7d8-419d-94ed-c3b511bba82b.png)
![UM_Bug02](https://user-images.githubusercontent.com/101145521/229696873-fa43d3e6-75e9-4cfe-bf76-7706d7d1115c.png)
![UM_Bug03](https://user-images.githubusercontent.com/101145521/229696875-88bffbb8-ffb2-4e7d-933e-71cc0c0808ee.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5894 should be in next release.

Going to close to consolidate with https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5886.
