### ISSUE TITLE
Startup crash due to having Lua installed

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#5916]
PoB was working fine until a couple days ago. Any new thoughts on this? Seeing the following in my windows event viewer:
```
Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x606d1b4c
Faulting module name: ntdll.dll, version: 10.0.22621.1344, time stamp: 0x56ac692c
Exception code: 0xc0000374
Fault offset: 0x000ec67f
Faulting process id: 0x0x3798
Faulting application start time: 0x0x1D9664075282F1C
Faulting application path: C:\Users\Grant\Downloads\PathOfBuildingCommunity-Portable-2.26.2\Path of Building.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 411e247d-ab42-4b2c-af6d-625ba45d880f
Faulting package full name: 
Faulting package-relative application ID: 
```

Edit: I tried cloning the repo and found that if I ran the application in Dev Mode, it launches properly. If I disable Dev Mode then the application crashes as described.

_Originally posted by @hgranthorner in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4340#issuecomment-1494536695_

**Comment by hgranthorner** [comment]
Some additional information based on some questions from @Wires77:
This happened on Windows 11 both with the portable install and the full MSI style installation.
Lua and Luajit were installed via scoop.
As soon as I uninstalled Lua/Luajit, the problem was resolved.

I'm also glad to look into this, but I was unable to figure out how the executable was choosing which lua to load... bit of a lua noob over here.

**Comment by dalems4** [comment]
We need the low graphic files for windows 10.

**Comment by joegnis** [comment]
I am on Windows 10 and having a similar issue. Sometimes it crashes, while most of time the program still runs but with lua error message ("lcurl" module not found) when it tries to update. I installed lua through scoop and as soon as I uninstall lua the problem goes away.

**Comment by Wires77** [comment]
@hgranthorner @joegnis When did you install Lua via Scoop?  I ask because I'm having trouble reproducing the issue, and I see they made the change to stop clobbering LUA_PATH back in August: https://github.com/se35710/scoop-main/commit/d1f2ae4ad4f63edb3587aaa0b7bb865035988e28  You may want to try manually going to your environment variables and clearing out LUA_PATH and reinstalling the latest version of Lua via Scoop.

I'm also running on Windows 11, having both Lua and luajit installed.  I'm running Scoop v0.3.1, if that needs to be updated

**Comment by QuickStick123** [comment]
Copper on discord was having this issue 23/03/2023 this is the command they used.
![image](https://user-images.githubusercontent.com/31533893/230815523-1f683a9f-5a9b-4701-b709-5a218b884cce.png)
![image](https://user-images.githubusercontent.com/31533893/230815545-9b6a4046-2f8f-4364-a6e8-ba8fece6b47c.png)

**Comment by Wires77** [comment]
Ah yeah, forgot they posted logs there.  I was able to reproduce it installing that specific version.  Uninstalling lua now works, and reinstalling lua now breaks, so my theory is if you ever had that older version installed it messes up something within scoop.

**Comment by Wires77** [comment]
FYI @octopushugger @joegnis @hgranthorner The above PR should fix this issue once we release SimpleGraphic.dll (should be in beta somewhat soon).  If you'd like a workaround in the meantime, you can add this second line at the top of UpdateCheck.lua wherever your PoB is installed:

```lua
local connectionProtocol, proxyURL = ...
package.cpath = GetScriptPath() .. "/?.dll"
```

PoB will complain about needing an update every time you load it, but if you open the console with Ctrl + `, you can see if there are more files than just UpdateCheck.lua (You can also tell if the update is "real" if there are patch notes in the window when you click update).  If you update you'll have to make the above change again.
![image](https://user-images.githubusercontent.com/1209372/235261071-e23776f4-1e42-4a1b-93ee-b3e8628c07ab.png)
