### ISSUE TITLE
Max hit calculation with EB, MOM and petrified blood

### ISSUE THREAD

**Issue by 1nterstellar-dev** [PathOfBuildingCommunity/PathOfBuilding#5918]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

about ~44000 lightning damage according to my calculation (not in game)

### What is the value from the calculation in Path of Building?

33818 lightning damage

### How to reproduce the issue

Notes:

- pet. blood has anomalous quality, it doesnt affect the bug, but still.
- MOM is 50%.

### Character build code

```shell
https://pobb.in/EUujjnitVOI-
```

### Screenshots

![image](https://user-images.githubusercontent.com/64141676/229890783-c2df6246-a317-4815-9626-4562b636248a.png)
![image](https://user-images.githubusercontent.com/64141676/229873602-f9faf598-be33-49a2-bd91-0efa2cf8bd05.png)
![image](https://user-images.githubusercontent.com/64141676/229873689-0992c64b-28fe-4c0e-bde8-32f188fdd9c7.png)

**Comment by LocalIdentity** [comment]
Fixed in #5908

**Comment by LocalIdentity** [comment]
![image](https://user-images.githubusercontent.com/31035929/229943069-009cbac8-de42-4114-bdce-a89cb50f170e.png)
