### ISSUE TITLE
Holy Relic trigger rate cap stopped working after 3.21 update

### ISSUE THREAD

**Issue by Fiard** [PathOfBuildingCommunity/PathOfBuilding#5925]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Before the 3.21 update it was calculated properly in PoB in this tab and had around 4.98 rate or smth
[Trigger tab Image](https://snipboard.io/IuzWc1.jpg)
(screen from new PoB with error already, can't make old one)

### What is the value from the calculation in Path of Building?

Now it is much lower (3.03) in the same build, I double checked all other things like attack speed and such, everything is fine. The answer can be directly seen here:
[Image of "Trigger rate cap" mouse hover tooltip](https://snipboard.io/CO5cAm.jpg)
You can clearly see 52 in table in the bottom, which is "Holy relics have 52% increased cooldown recovery rate" from the skill quality itself (Divergent Holy Relic).
But it is not assumed in calculation above:
0.30 / 1.00 (increased/reduced cooldown recovery)
and it stays 0.30, but should be 0.198, which is actually even shown in right tab "Skill type-specific stats":
[Image](https://snipboard.io/afVxqi.jpg)

### How to reproduce the issue

You just need divergent holy relic with any +quality, or manually add in configuration "XXX% increased minion cooldown recovery rate" - this will change skill cooldown in right tab, but won't apply to trigger rate cap in left tab (check screenshots from description above)

### Character build code

```shell
https://pobb.in/MQCoUjA8CKhq
```

### Screenshots

https://snipboard.io/IuzWc1.jpg
https://snipboard.io/afVxqi.jpg
https://snipboard.io/CO5cAm.jpg

**Comment by QuickStick123** [comment]
Seems to be fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5894 in 2.26.3
