### ISSUE TITLE
Converting certain 3.20 trees to 3.21 fails with error message

### ISSUE THREAD

**Issue by Kanarisky** [PathOfBuildingCommunity/PathOfBuilding#5929]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

The tree should be successfully converted from 3.20 to 3.21.

### How does Path of Building behave?

The tree is not converted, and instead an error message shows:

![image](https://user-images.githubusercontent.com/68185248/230012158-d01cf10a-1327-4413-8f1e-2c8525bebf17.png)

### How to reproduce the issue

Select any tree in my PoB including Act4 onward, and attempt to convert it to a 3.21 tree.

Additionally, if I cut the Act4 tree back so that it is identical to the Act3 tree (including ascendancy nodes) and try to convert, it still shows the error despite no stats being different from the Act3 tree.

### Character build code

```shell
https://pobb.in/KV1-HNXgicEj
```

**Comment by QuickStick123** [comment]
See https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5882 for solution

**Comment by Kanarisky** [comment]
Thank you and sorry for the duplicate post. I somehow didn't find that one with search.

**Comment by QuickStick123** [comment]
All good.
