### ISSUE TITLE
3.21 "15% increased maximum life if there are no life modifiers on equipped body armour" not working with Hyrri's Ire

### ISSUE THREAD

**Issue by seriouschris** [PathOfBuildingCommunity/PathOfBuilding#5938]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I would expect this mastery to work since Hyrri's Ire seems to have no life mods.

### How does Path of Building behave?

The mastery is reded out and does not effect life total when allocated.

### How to reproduce the issue

Simply equip Hyrri's Ire and allocate that mastery.

**Comment by Wires77** [comment]
Red text means the modifier is not supported in Path of Building.  That being said this should be fixed by #5819

**Comment by seriouschris** [comment]
You're awsome. Thank you.
