### ISSUE TITLE
Rage has no effect unless you take a rage related passive.

### ISSUE THREAD

**Issue by Anarack** [PathOfBuildingCommunity/PathOfBuilding#595]
1.4.161.2
This is not just moment speed such as in #28 #289 but all affects of rage unless you take crave the slaughter from the berserker ascendancy, or the scion berserker node.

Heres the build I'm working with right now https://pastebin.com/KvvnxpY1

**Comment by lobsterkite** [comment]
Not addressing the bug but you can add the mod "gain 1 rage when you kill an enemy" on a random item to enable the rage option separate of any skill links.  I used it this way to see the actual benefits of the rage skill gem separate of the benefits of rage itself.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.3.
