### ISSUE TITLE
NVIDIA OpenGL Driver and Application Error

### ISSUE THREAD

**Issue by Atao38** [PathOfBuildingCommunity/PathOfBuilding#5961]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

in windows 11 application event:

Nom de l’application défaillante Path of Building.exe, version : 0.0.0.0, horodatage : 0x606d1b4c
Nom du module défaillant : nvoglv32.dll, version : 31.0.15.3141, horodatage : 0x641397b2
Code d’exception : 0xc0000409
Décalage d’erreur : 0x0141dd48
ID du processus défaillant : 0x0x135C
Heure de début de l’application défaillante : 0x0x1D96931999235E9
**Path of the failed application** : C:\Users\bertr\AppData\Roaming\Path of Building Community\Path of Building.exe
**Path of the failed module**: C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_50916785244854f2\nvoglv32.dll
ID de rapport : 3c391b68-90b6-461d-9959-3316f9d13556
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 

### What are your system specifications and configuration?

OS: Windows 11
CG: Nvidia GeForce RTX 2070 (pilote 531.41)

### How to reproduce the issue

a) install fresh last version of PathOfBuilding (2.26.3)
b) execute PathOfBuilding as administrator
c) opening and in the green splash screen of PathOfBuilding just after writing "loading Item Database..."
c) full screen become black, and when visible again, PathOfBuilding autoclosed

same behaviour with portable version.
and also if PathOfBuilding\Builds folder is empty

**Comment by QuickStick123** [comment]
Likely the same issue detailed here https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1499972807 about having a lua interpreter installed on your system.

**Comment by Atao38** [comment]
Thanks @QuickStick123 but I have no lua installed.

Anyway, I solved by uninstalling NVIDIA drivers using DDU uninstaller and re clean driver re install. Now PathOfBuilding working ifne.

**Comment by Atao38** [comment]
Thanks for this great tool^^
