### ISSUE TITLE
Allocating Recovery Mastery next to The Agnostic

### ISSUE THREAD

**Issue by KennySpellbound** [PathOfBuildingCommunity/PathOfBuilding#5963]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Allocating mastery should allocate a necessary notable node as well.

### How does Path of Building behave?

Allocates only the first node on that cluster.

### Screenshots

![pob_recm](https://user-images.githubusercontent.com/130150843/230601541-27e464b1-fcf9-420d-8f4f-a83b80251428.png)

**Comment by QuickStick123** [comment]
This seems to be the only case on the tree after checking. This can be fixed in two ways the first is fixing the tree data GGG has supplied and notifiying them the second is to only let notables lead to masteries.
