### ISSUE TITLE
Use the generalised mastery count types instead of special life mastery data

### ISSUE THREAD

**Issue by QuickStick123** [PathOfBuildingCommunity/PathOfBuilding#5965]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Added in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5843

When 6 life masteries stat was implemented it was done by adding code everywhere masteries are counted.
This can simply be retrieved from this array instead of the other unnecessary code.
![image](https://user-images.githubusercontent.com/31533893/230609856-159a6bb2-5119-4a78-b5bc-b7efde39d5f5.png)

### Describe the solution you'd like

Delete explicit life mastery counting and use that array instead.

**Comment by mortentc** [comment]
Just to be sure, is the idea to replace `allocatedLifeMasteryCount` on line 579 with `allocatedMasteryTypes["Life Mastery"]`, and then delete all references to `allocatedLifeMasteryCount`?

**Comment by QuickStick123** [comment]
Yes
