### ISSUE TITLE
Bad argument #2 to m_max (number expected, got boolean)

### ISSUE THREAD

**Issue by deathbeam** [PathOfBuildingCommunity/PathOfBuilding#597]
This started happening on PoB I had saved locally. As you can see below, I am on updated version.

![image](https://user-images.githubusercontent.com/5115805/76707581-9bc84900-66f0-11ea-9a8f-6334585f9c97.png)

**Comment by A68PL** [comment]
Same thing.

**Comment by Nostrademous** [comment]
Did you guys by any chance copy a build using PoB from a previous build?

**Comment by J-Kat** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/fb95a9e6c4de51b158a696c0882da196bc61558c

For those who want the temporary solution:

Change this in your build's XML file from
`<Input name="conditionStationary" boolean="true"/>`
to
`<Input name="conditionStationary" number="5"/>` (in number of seconds stationary)

I don't think I copied this build from a previous build, but I can't be 100% sure. I don't know enough about the code base to know whether this value type should be checked when the build is first loaded (my personal preference) or when this function is hit.

**Comment by Nostrademous** [comment]
Ty, will fix this tonight after kids go to bed.

**Comment by Nostrademous** [comment]
PR submitted to fix this: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/599

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
