### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Thebiggigz** [PathOfBuildingCommunity/PathOfBuilding#5970]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Open with I hit launch.

### How does Path of Building behave?

![image](https://user-images.githubusercontent.com/130196555/230698389-cc0fb45f-15a3-4f92-b034-8893565cd279.png)

### How to reproduce the issue

Everytime I open it

**Comment by QuickStick123** [comment]
This is caused by having your save/setting files in onedrive and it not having loaded them completely.

**Comment by Thebiggigz** [comment]
Mind giving me a run down on how to install in properly? Not to sure what that means haha

**Comment by QuickStick123** [comment]
I have been sending people to this https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5368#issuecomment-1356640714.
Feel free to ask any questions if you can't get it working.

**Comment by Thebiggigz** [comment]
Hmmm Im not signed into that Onedrive app at all. I then tried installing the PoB setup from github, but still running into that issue

**Comment by QuickStick123** [comment]
Try opening the setting file manually and see if that somehow loads it so it work should be in documents/PoB

**Comment by Thebiggigz** [comment]
I got it ! Thank you very much. I had a very old build I guess from when I tried playing before in that folder. It was not letting it open for some reason so I just deleted that folder entirely, reinstalled and it works!

**Comment by QuickStick123** [comment]
Nice.
