### ISSUE TITLE
Global and local + gem level don't wrk

### ISSUE THREAD

**Issue by Morilli** [PathOfBuildingCommunity/PathOfBuilding#5976]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Global and local `+X to level of all/socketed Y gems` apply and change the level of relevant gems accordingly.

### What is the behaviour in Path of Building?

Since 2.27, this behavior is incorrect in PathOfBuilding and additional gem levels are not applied.

### How to reproduce the issue

Use any item with a global or local gem level modifier and notice how it doesn't work.

### Character build code

```shell
https://poe.ninja/pob/Wet
```

### Screenshots

Only equipped item:
![image](https://user-images.githubusercontent.com/35152647/230736283-014d4e03-d700-4780-b03d-76d358bc9e5e.png)
Notice how Spark does not get the `+1` bonus from the item here:
![image](https://user-images.githubusercontent.com/35152647/230736290-95d7290a-414a-447c-b351-5cf51649d0c2.png)

**Comment by jwfiredragon** [comment]
Interestingly enough, something like "+1 to level of all spell gems" works. The problem is specifically with the "skill" qualifier.
