### ISSUE TITLE
Issue downloading updates

### ISSUE THREAD

**Issue by enpinzolas** [PathOfBuildingCommunity/PathOfBuilding#5977]
I have been trying to update the program and failing to do so. It gets stuck downloading at about 2/84, 6/84, 18/84 or 20/84. I have tried reinstalling to no avail, it gets stuck on the update of the reinstallation. I basically gives timeouts and if there are enough, it simply fails to update. This seems like a server issue, but I can't check.

I am installing it in the default folder AppData/Roaming, so there should not be any permission issues.

![image](https://user-images.githubusercontent.com/8517355/230741649-4684b796-f3c3-4bc6-acc2-c728328b929a.png)

**Comment by Wires77** [comment]
Unfortunately updates start over from the beginning if part of the update fails.  Which update are you trying to download?  If you download the source code zip from https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v2.27.0 you can manually replace the files in your Roaming folder (most of them will be in the `src` folder in the zip file).  Then the updater should only try and download the ones you missed, and hopefully complete before your internet gives out.

Do you have other internet issues outside of PoB?

**Comment by enpinzolas** [comment]
Thanks for the help. I did try doing what you state with the source code, but it still tried to download the 84 files.

No other internet issues outside PoB. Since this is mostly interpreted code, I just copied everything from the src file, and then changed the manifest.xml so that the 3rd line contains the platform and the branch, and thus doesn't force dev mode:

```xml
	<Version number="2.27.0"  platform="win32" branch="master" />
```

So yeah, my solution to the problem was downloading the source code of the last update, copying the src file, copying the manifest.xml file so all the hashes match and it doesn't try to redownload, and change the manifest Version tag to include the platform and branch tags so the program doesn't throw you into the dev mode. That's it

**Comment by Wires77** [comment]
Ah, yeah, the manifest is slightly different from the source code version, so it'll try and redownload the manifest file as well.  I'm surprised it still tried to download the 84 files, though.  We have some ideas for improving the updater, so hopefully those are implemented if this ever happens again
