### ISSUE TITLE
Archmage support not calculating properly

### ISSUE THREAD

**Issue by thegiantcat** [PathOfBuildingCommunity/PathOfBuilding#598]
Archmage is both improperly calculating mana and not using 6% * mana multiplier as a cost for skills. For instance when linked to a four link stormbrand with a fevered mind and apeps rage it lists the mana cost as 91 with 2298 mana. 

This should be 445 mana cost the cost of linking archmage to storm brand, lightning pen, and controlled destruction, then accounting for 90% increased mana cost. 

Additonally when looking at calcs, it looks like its adding maximum lightning damage and not flat lightning damage in game the damage it adds is flat. and not "maximum lightning damage"I.e(1-1000)

**Comment by BassOfBass** [comment]
Read the changelog maybe. Archmage isn't supported yet.
For the time being you can copy manastorm's line on any equipped item and edit the percentage to whatever you think is the final percentage of cost * 1.27. It will at least give you an overview at how much flat lightning you get by looking at its max value.

**Comment by dodspunkare** [comment]
Why would this still it not be supported when the original openarl version of PoB has been supporting it since the 17th?

**Comment by Nostrademous** [comment]
Because it has to be merged with a bunch of other changes making it different from the original PoB. Then it has to be tested to see if other thing are affected by the change. It’s coming soon.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
