### ISSUE TITLE
Skills supported by Snipe gain erroneous more damage multiplier

### ISSUE THREAD

**Issue by BillWiegert** [PathOfBuildingCommunity/PathOfBuilding#5987]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

When level 20 Snipe is used to support another skill, it gains 108% more damage per stage of Snipe and 80% more damage with ailments per stage of Snipe.

### What is the value from the calculation in Path of Building?

In PoB, a skill supported by level 20 Snipe correctly gains the more damage modifiers listed above, but additionally gains 165% more damage per Snipe stage and 120% more damage with ailments per Snipe stage. This results in 8053% more damage instead of 648% more damage for 6 stages of snipe. These are the old more damage modifiers from the unique item Assailum.  The "Calcs" tab lists the source of these modifiers as "Config"

The damage for Snipe itself when not linked to another active skill is correctly calculated.

### How to reproduce the issue

1. Create a new build.
2. Add a bow.
3. Add Snipe supporting another bow skill like Frenzy.
4. Enter 6 Snipe stages in Config.
5. Observe 8,053% more damage in Calcs tab for Frenzy.

### Character build code

```shell
https://pobb.in/90LUcrYzY7GW
```

### Screenshots

![image](https://user-images.githubusercontent.com/21974998/230748115-2dd7f211-ae30-4383-8d65-6d54b824d0b6.png)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5979
