### ISSUE TITLE
Cannot Generate a Jewel with the Trader tool.

### ISSUE THREAD

**Issue by Lward95** [PathOfBuildingCommunity/PathOfBuilding#5988]
Gives me a Lua error. Tried restarting, and it is the most recent update 2.27.1

![Screenshot 2023-04-09 112349](https://user-images.githubusercontent.com/47593736/230749525-682c2c12-8e59-4d04-9bd0-730cba83c6f8.png)

(Note: It generates other items just fine)

**Comment by QuickStick123** [comment]
Introduced in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5666 (so 2.26.0)
