### ISSUE TITLE
Add exe to your "get latest release"

### ISSUE THREAD

**Issue by jessebevil** [PathOfBuildingCommunity/PathOfBuilding#5991]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'm new to POB, I wanted to get it, but when I try your link from https://pathofbuilding.community/ it sends me to github and only lists the source files. I'm not sure what I'm expected to do with those.

### Describe the solution you'd like

Add the installer or exe or whatever is needed to run the program to the latest release so I don't need to learn how to build the program. Alternately, if I have to build it myself for some reason, please provide instructions to build it so I know what I'm doing

### Describe alternatives you've considered

I've considered asking a friend to put it on a zip drive and mailing it to me. 

### Additional context

![image](https://user-images.githubusercontent.com/4873713/230751461-4a71cbec-c416-4805-998d-d58fea68d228.png)
![image](https://user-images.githubusercontent.com/4873713/230751466-4704fd34-a0b6-430e-b572-d02932e4f858.png)

**Comment by Wires77** [comment]
If you scroll down to the release before this latest one you'll see an EXE installer.  Our automated process just happened to fail for this latest release.  I'll look into having it run again, sorry about that!
