### ISSUE TITLE
Prismatic Burst not calculating spell damage correctly

### ISSUE THREAD

**Issue by JoeMurrayH** [PathOfBuildingCommunity/PathOfBuilding#5994]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

in-game i have tested this by refunding light of divinity and my prismatic burst damage has gone down, but there is no such effect  in pob

### What is the value from the calculation in Path of Building?

in path of building, i have light of divinity allocated and it is not appearing in the prismatic burst calculation.
It appears that no spell damage boost or spell crit chance is being applied in pob to prismatic burst, I also have battlemage which is not being added to prismatic burst, unlike other spell skills. 

### How to reproduce the issue

start a templar
select any attack skill and add in a prismatic burst as a support gem.
and path to light of divinity

### Character build code

```shell
https://pobb.in/he3_6Sibr9ef
```

### Screenshots

![image](https://user-images.githubusercontent.com/49404125/230766369-4383546f-c72a-4416-8bc5-10c34b21847c.png)

**Comment by QuickStick123** [comment]
It hasn't really been implemented yet but will be in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5969. Which I assume probably fixes this issue don't really now how it is meant to work.

**Comment by Paliak** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5969 only adds basic support for it and does not consider it a self trigger. It's implemented in #4599 based on my current understanding of the gem.
