### ISSUE TITLE
Ashes of the Stars and related equip words for +1 ALL SPELL have no effect

### ISSUE THREAD

**Issue by Bodin0530** [PathOfBuildingCommunity/PathOfBuilding#5996]
Ashes of the Stars and related equip words for +1 ALL SPELL
have no effect

**Comment by QuickStick123** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5976 and already fixed in dev by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5982
