### ISSUE TITLE
Thread of Hope Passives Not Saving When Build Closed

### ISSUE THREAD

**Issue by IdrisQe** [PathOfBuildingCommunity/PathOfBuilding#600]
When I close a build with the [<<Back] button and then re-open it again, or switch to a different build, the builds will have all passives allocated through Thread of Hope unallocated, making me need to re-allocate them.

Running version 1.4.161.2 of the community fork.

**Comment by A68PL** [comment]
Same thing with Intuitive Leap.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
