### ISSUE TITLE
Incorrect Saqawal's Nest Aspect of the Avian buff effect

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#6001]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Aspect of the Avian with Saqawal's Nest equipped should provide 20% chance to deal double damage and 20% increased movement speed.

### What is the value from the calculation in Path of Building?

Both values are at 40%.

### How to reproduce the issue

1. Equip Saqawal's Nest
2. Equip any item which provides the Aspect of the Avian's skill
3. Tick the checkboxes for the Avian's Might and Avian's Flight in the configurations
4. Add any minion gem
5. Observe the damage & movement speed values in the calculations

### Character build code

```shell
https://pobb.in/TOTj7b-iNp8k
```

### Screenshots

40% movement speed:
![image](https://user-images.githubusercontent.com/7839686/230783141-3d0a5a1f-3f4b-4ecb-9768-2434e785a073.png)

40% chance to deal double damage:
![image](https://user-images.githubusercontent.com/7839686/230783144-5d829886-8b57-4709-9dfe-bc6bc1f426d2.png)

**Comment by Wires77** [comment]
We've actually tested this specifically and that's how it works (or at least worked 3 years ago) in game, so this is correct.

![image](https://user-images.githubusercontent.com/1209372/230787206-ba9c5c77-eefa-4eb0-927e-ff894dc9283a.png)

**Comment by moxaj** [comment]
Wow, that smells like spaghettio. But at least now we have this in the issue tracker so future folks are less likely to file it again.
