### ISSUE TITLE
blue screen issue when path of building is opened and path of exile client is not opened

### ISSUE THREAD

**Issue by ifakhfakh** [PathOfBuildingCommunity/PathOfBuilding#6004]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

Blue screen issue here is the screenshot 
![image](https://user-images.githubusercontent.com/20418235/230801609-8e0d585b-e602-4411-b61f-2ee75fe75ca2.png)

### What are your system specifications and configuration?

PC not a desktop
system : windows 10 21h2 
build version: 19044.2728
i7 7th generation
ram: 16gb
nvidia 1050 gx

### How to reproduce the issue

you can reproduce the issue by opening path of exile -> open then path of building -> play some maps and then close path of exile -> path of building is still opened -> after few seconds blue screen happens

**Comment by QuickStick123** [comment]
PoB cannot cause a system to blue screen under normal circumstances 

Reinstall drivers, turn off overlooks and make sure none of your hardware is broken. You could also use windows update incase you have have a bad version.

**Comment by ifakhfakh** [comment]
@QuickStick123 I know that my PC is not perfect but there has to be something wrong with pob that is causing this issue. I really appreciate the hard work that you guys do for this free tool but dont you think that this is worth investigating ?

**Comment by ifakhfakh** [comment]
@Wires77 yep it happens when pob is open and not path of exile. I installed clickup i dont know if you know it or not. Windows update should take care of the drivers. I neevr manually updated any of my pc drivers. Like i said i even checked the files system by using `sfc /scannow` but nothing was corrupted.

**Comment by ifakhfakh** [comment]
@QuickStick123 i didnt undertsand the instructions in your comment tbh. There are four zips in the branch what should i do with them ?

**Comment by ifakhfakh** [comment]
@QuickStick123 Should i unzip all of them and put them in the installation folder ?

**Comment by QuickStick123** [comment]
You need "SimpleGraphic-x86-windows-deps.dll"
"SimpleGraphic-x86-windows.dll" from the zip and copy replace into runtime with the .dlls like stated. I am not sure how the comment could be clearer as it clearly states what you need from the .dll.

**Comment by ifakhfakh** [comment]
@QuickStick123 why so salty dude ? Why did i hurt your feelings when i said i didnt undertsand your comment ?

**Comment by Wires77** [comment]
I'm closing this discussion since workarounds have been provided and the comments have turned unproductive.
