### ISSUE TITLE
active skill gem"bane" related issue

### ISSUE THREAD

**Issue by undermoment999** [PathOfBuildingCommunity/PathOfBuilding#6007]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

not noticed in game, only in POB

### What is the value from the calculation in Path of Building?

When apply support gem "Controlled Destruction" to "Bane", the value of total more damage seems count incorrectly. For example, when I link curse gem "Enfeeble"  "Despair" and support gem "Controlled Destruction" to Bane, the calculation shows the total more damage is 156%. However, it should be 123% where two curse gems give 84% plus "Controlled Destruction" give 39%. 

### Character build code

```shell
https://www.pathofexile.com/passive-skill-tree/3.21.0/AAAABgMBEHpwaxdUrt-Kf8YYakJ6eC990sHFbAvsGFgHIvQNH5MnAAA=
```

### Screenshots

![屏幕截图(18)](https://user-images.githubusercontent.com/130341096/230839130-135774bd-4665-45f3-9a4d-48687a064c7d.png)

**Comment by QuickStick123** [comment]
They multiply as they are more multipliers 1.84 * 1.39 = 2.5576 or 156% more.
