### ISSUE TITLE
Custom Cluster Jewel not socketable in allocated outer socket

### ISSUE THREAD

**Issue by Beren1305** [PathOfBuildingCommunity/PathOfBuilding#601]
After using the new Large Cluster Jewel template to create one of my in-game Cluster Jewels, I wasn't able to actually socket the jewel in my allocated outer socket. All "normal" jewels are socketable just fine.

**Comment by LocalIdentity** [comment]
Can you please provide a Pastebin and a screenshot to better illustrate what you are trying to convey, I haven't found any cases where a cluster jewel was not socketable

**Comment by Beren1305** [comment]
Found the issue, the imported tree I was using hadn't been converted to the 3.10 tree yet so the sockets weren't compatible with the Cluster Jewels. Sorry!
