### ISSUE TITLE
Cannot run PoB on fresh installed win 11 attempt to index local 'str' (a nil value)

### ISSUE THREAD

**Issue by dfwmlb** [PathOfBuildingCommunity/PathOfBuilding#6013]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

attempt to index local 'str' (a nil value) error on start
![pob error](https://user-images.githubusercontent.com/28809351/230993973-c2aa0c25-6c2d-4477-8221-29fb993fe82c.png)

### How does Path of Building behave?

should start normaly

### How to reproduce the issue

install fresh win 11
install all updates
install all vcredist libraries
![win vcredist](https://user-images.githubusercontent.com/28809351/230994352-ace550c5-e102-4f9f-9aac-7127cb4874d9.png)

**Comment by Wires77** [comment]
Navigate to your Settings.xml manually and open it that way.  Windows has made it unavailable via OneDrive until you try to open it through explorer.  It should be in Documents/Path of Building

**Comment by dfwmlb** [comment]
thanks, that helps
