### ISSUE TITLE
After 1.4.161.2 patch, Minion Instability is not applied.

### ISSUE THREAD

**Issue by aNitMotD** [PathOfBuildingCommunity/PathOfBuilding#602]
![mi bug](https://user-images.githubusercontent.com/10880354/76728770-f74f1100-679a-11ea-9ae8-a7615cf2fce0.png)

**Comment by LocalIdentity** [comment]
Will be fixed in the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
