### ISSUE TITLE
DPS changes when selecting different, identical skill set.

### ISSUE THREAD

**Issue by ThaPear** [PathOfBuildingCommunity/PathOfBuilding#6023]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When I select the other, identical skillset, I expect to see an identical DPS.

### How does Path of Building behave?

When I select a different skillset with identical skills, the DPS changes by 25%.
The Calcs tab shows no difference between the two.

### How to reproduce the issue

From my simplified build:
1. Import my "Simplified build"
2. Switch between "Less DPS" and "More DPS" to see the DPS change.

I started from the Arc Totems build on poebuilds.net, so to reproduce from that one:
1. Import the "Root build"
2. Create a new blank skillset.
3. Copy the skills over one by one from the Default skillset to your new one.
4. Switch between "Default" and your new skillset to see the DPS change.

### Character build code

```shell
Simplified build: https://pobb.in/S6WZmPUrvcFb
Root build: https://pobb.in/RMQig1vZR0IM
```

### Screenshots

![image](https://user-images.githubusercontent.com/710437/231278378-c13251f6-3d3f-4ef3-bd5a-8daca03e2bab.png)
![image](https://user-images.githubusercontent.com/710437/231278395-0de04ba2-a2b9-4e04-a7b2-9efc25414a34.png)

**Comment by QuickStick123** [comment]
![image](https://user-images.githubusercontent.com/31533893/231319710-08dd504f-82ba-477c-b80a-212559443de8.png)
![image](https://user-images.githubusercontent.com/31533893/231319726-311ead92-2e13-461f-bb2b-0c425eb3568f.png)

You have a different number of mines configured between them.
