### ISSUE TITLE
Create "APIs" to make it possible to integrate PoB with AI agents

### ISSUE THREAD

**Issue by sampaiodias** [PathOfBuildingCommunity/PathOfBuilding#6027]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

It would be really cool to have some APIs so developers could integrate with some new AI technologies, such as [AutoGPT](https://github.com/Torantulino/Auto-GPT). For example:

1. Ask AutoGPT to give a suggestion of uniques to add to my build to achieve the best Crit Chance as possible.
2. AutoGPT would use a PoB API to list all possible unique weapons (i.e.: `url/items/list?slot=Weapon1&sortBy=critchance`)
3. Get the first results and save it to a report
4. Steps 2 and 3 would repeat for each slot
5. AutoGPT would stop and give me a report, with a Unique item suggestion for each slot of the build.

### Describe the solution you'd like

An API to locally interact with PathOfBuilding

### Describe alternatives you've considered

Maybe a "headless" mode?

### Additional context

An example of AutoGPT: https://www.youtube.com/watch?v=uu3NzgnAiMk

**Comment by Wires77** [comment]
You can already do this with PoB.  See src/HeadlessWrapper.lua for the entry point.

You can also sort the list of uniques in the items tab by crit chance, filtering by the item slot it belongs in.
