### ISSUE TITLE
life cost calculation with Lifetap support and Skills Cost Life instead of 30% of Mana Mastery is incorrect

### ISSUE THREAD

**Issue by kmorozov** [PathOfBuildingCommunity/PathOfBuilding#6029]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

In game I have allocated the "Skills Cost Life instead of 30% of Mana" Life mastery and one of my skills is supported with Lifetap:
L9 Earthquake + lifetap

PoE tells me that I will pay 30 life to cast this skill.

### What is the behaviour in Path of Building?

In PoB, It reports that the skill will cost 21 life.
When I deallocate the life mastery, it correctly reports a cost of 30 life.

### How to reproduce the issue

1. Allocate the "Skills Cost Life instead of 30% of Mana" Life mastery
2. Link Earthquake to Lifetap
3. Look at the life cost of Earthquake.

### Character build code

```shell
https://pobb.in/vhKItV7OK3KP
```

### Screenshots

![image](https://user-images.githubusercontent.com/3926604/231341994-e5fa3fed-951e-4a63-b87e-bc7822b46417.png)

**Comment by QuickStick123** [comment]
Likely very related. https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6008
