### ISSUE TITLE
Darkscorn (and possible other) items damage calculation is wrong

### ISSUE THREAD

**Issue by Serdoa** [PathOfBuildingCommunity/PathOfBuilding#603]
When using Darkscorn, the line on it that increases damage of poisons by 300% with a 20% chance is applied to any attack used. This can be reproduced by using any kind of bow attack skill and deleting that line on Darkscorn.

**Comment by LocalIdentity** [comment]
Have a fix for this to go into the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
