### ISSUE TITLE
Alchemist's mark incorrectly applying to DPS numbers

### ISSUE THREAD

**Issue by 71M073J** [PathOfBuildingCommunity/PathOfBuilding#6035]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In game, my poison lasts about 2 seconds

### What is the value from the calculation in Path of Building?

PoB with the below setup says the poison duration should be approx twice that.

### How to reproduce the issue

https://pobb.in/u70eNPkxwZIw on this setup, if adding/removing alchemist's mark in the "Skills" tab, the poison damage numbers for Doom Blast (in Temporal Chains main skill) don't change. If however, i for example link the Alchemist's mark gem with High-Impact Mine Support, this suddenly halves the "total damage per poison", and also halves the poison duration in the "Calcs" tab, which it definitely shouldnt, as HIMS is 1. applying to Alchemist's mark, not Doom Blast, and 2. HIMS does not affect poison duration.

There is probably more weird things going on with why Alchemist's mark does not affect the damage.

### Character build code

```shell
https://pobb.in/u70eNPkxwZIw
```

**Comment by Regisle** [comment]
Its because you dont have enough curse limit to support the alchemists mark, and is assuming having the mine apply it for you it overrides a later curse (in this case temp chains), which kills the poison duration
