### ISSUE TITLE
Trade for these items 

### ISSUE THREAD

**Issue by fajkoson** [PathOfBuildingCommunity/PathOfBuilding#6036]
In trade for these itmes session mode is selected but realm and league cannot be choosen.
Version 2.28
![POB](https://user-images.githubusercontent.com/57269743/231677490-df9efdda-d9da-49fe-984e-f4f553f42ae2.JPG)

**Comment by QuickStick123** [comment]
Your session id is expired re enter it.

**Comment by fajkoson** [comment]
re-entering poessid works.
