### ISSUE TITLE
PoB causes high CPU load when focused. (Bugfix suggestion)

### ISSUE THREAD

**Issue by shyney7** [PathOfBuildingCommunity/PathOfBuilding#6045]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

PoB should not cause high CPU usage only when the window is focused without doing anything else like moving the skill tree, etc.

### How does Path of Building behave?

When the PoB window gets focused the CPU Load gets to ~ 20%
When unfocused its nearly 0%

### How to reproduce the issue

Focus the window open the system ressource monitor

### Character build code

```shell
https://pobb.in/YmvFdS3O19lv
```

### Screenshots

![Screenshot 2023-04-13 195446](https://user-images.githubusercontent.com/17785769/231843840-4a35a7f1-7944-4954-914d-0ccd20c8a3ae.png)

**Comment by QuickStick123** [comment]
Duplicate https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5266
