### ISSUE TITLE
Guard Skills have 15% increased Cooldown Recovery Speed - Not Working.

### ISSUE THREAD

**Issue by Amountstax** [PathOfBuildingCommunity/PathOfBuilding#605]
Not working for any 'guard' skill.

![Untitled2](https://user-images.githubusercontent.com/60943070/76764849-ee931680-676b-11ea-9e4f-1e5b05a25516.png)
It is blue on the tree, which is pretty accurate as to when modifiers work.
Maybe the skill gems haven't been added as 'guard' skills?

**Comment by LocalIdentity** [comment]
Found the issue and have a fix for it

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
