### ISSUE TITLE
[feature] page/listing of delirium notables for supported calculations

### ISSUE THREAD

**Issue by xanthics** [PathOfBuildingCommunity/PathOfBuilding#606]
Essentially how the Blight notables were done.

My request is for a section of the tree to have all the new notables so that builds can quickly see which ones they would want in a build using the various node power options, and assist in selecting between them.  Visibility would probably benefit from a toggle of some sort.

**Comment by ppoelzl** [comment]
Added in 1.4.170.12 with the new power report feature.
