### ISSUE TITLE
Spell Suppression calculation differs from ingame.

### ISSUE THREAD

**Issue by POE-Addon-Launcher** [PathOfBuildingCommunity/PathOfBuilding#6067]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In game I have 77% spell damage suppression, however, when I import my character in Path of Building the calculation says I have 67% spell suppression, I've tried swapping out different pieces of spell suppresion gear and there is always a 10% difference with PoB and PoE in-game.

### What is the value from the calculation in Path of Building?

See above.

### Character build code

```shell
https://pobb.in/pykBfWY-9gFf
```

### Screenshots

![image](https://user-images.githubusercontent.com/42203962/232329711-a6d783f0-fa71-43db-bc2e-daefbdebe84c.png)

**Comment by Peechey** [comment]
It's because of this passive, you need to toggle "Are you always on Full Life"

![image](https://user-images.githubusercontent.com/92683202/232330354-b793fc0c-aded-4391-87ab-f287a64a956e.png)

![image](https://user-images.githubusercontent.com/92683202/232330374-c3d68139-976d-4f8a-b715-91511a4ab585.png)
