### ISSUE TITLE
Putting a Timeless Jewel in a cluster jewel socket throws an error

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding#607]
Not sure if this is even possible in-game, but it causes an issue in PoB
![image](https://user-images.githubusercontent.com/1209372/76801549-e3f47380-67a3-11ea-9dc5-49448e924d83.png)

**Comment by LocalIdentity** [comment]
Found a fix for this error

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
