### ISSUE TITLE
Equipping rare timeless jewel in tree while having timeless jewels socketed sometimes makes them stop working.

### ISSUE THREAD

**Issue by QuickStick123** [PathOfBuildingCommunity/PathOfBuilding#6089]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

To show modifications even if I have a rare timeless jewel socketed.
![image](https://user-images.githubusercontent.com/31533893/233282547-d54ee7ff-1729-4d29-a623-60101494824c.png)

### How does Path of Building behave?

![image](https://user-images.githubusercontent.com/31533893/233282441-c758ccdc-97a9-4575-bf75-d47226e8cfc2.png)

### How to reproduce the issue

Unequip the lethal pride and equip it again.
Now observe it is missing 20% melee damage.

### Character build code

```shell
https://pobb.in/0hP3WPIa0to9
```

**Comment by hghammoud** [comment]
same

**Comment by hghammoud** [comment]
any news on this one? also the search for jewel stoped working after 2.28.0 update

**Comment by Regisle** [comment]
You can just disable the jewel limits for now on the config page, but we would like to get it fixed, as for the jewel search, can you please post the issue separately?

**Comment by QuickStick123** [comment]
This is invalid I think I had multiple timeless jewels socketed.
