### ISSUE TITLE
Ryslatha belt should be increasing bleed damage

### ISSUE THREAD

**Issue by Kerberos9** [PathOfBuildingCommunity/PathOfBuilding#609]
This was mentioned in issue #46 but was closed. Ryslatha works on bleed damage, that's the reason every bleed bow gladiator is using it right now. Some data about damage increase can be found [here](https://www.reddit.com/r/pathofexile/comments/ejan95/simulation_the_effects_of_ryslathas_coil_on/)

**Comment by ppoelzl** [comment]
Superseded by #2057
