### ISSUE TITLE
Searching for a body armor produces an 'Unknown stat provided' Error

### ISSUE THREAD

**Issue by maluramichael** [PathOfBuildingCommunity/PathOfBuilding#6095]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I would like to search for an new body armor for my build.

### How does Path of Building behave?

'Trade for these items' and searching for an body armor produces an Error.

The error code is `[2: Unknown stat provided: explicit.stat_4215039317 ]`

### Character build code

```shell
https://pobb.in/SVgNSSe6hYVH
```

### Screenshots

![image](https://user-images.githubusercontent.com/1489383/233426580-b13794d0-6140-4714-9710-3d18c1a6a6d3.png)
![image](https://user-images.githubusercontent.com/1489383/233426632-8b3b6b1c-c1a3-4b50-a3f5-ab548975083a.png)
![image](https://user-images.githubusercontent.com/1489383/233426664-ec572f2e-af14-418f-ae26-2c189e220d1c.png)

**Comment by QuickStick123** [comment]
Fixed in dev by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6043 this will be in the next update which I think is planned to be released soon alongside some more crucible stuff.

**Comment by QuickStick123** [comment]
Here is trade url that works from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5735 (includes local, essence and crafted).
https://www.pathofexile.com/trade/search/Crucible/2zRpZaGsk

**Comment by maluramichael** [comment]
Thanks for the information and your work.

**Comment by QuickStick123** [comment]
You can also use beta now as that just updated.
