### ISSUE TITLE
Juggernaut "Bugfix" from 3.21.0c not working ?

### ISSUE THREAD

**Issue by Xzubidhu** [PathOfBuildingCommunity/PathOfBuilding#6096]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Couldnt test it ingame yet. Neither do i have any confirmations that it works like it supposed to work or i think it should.

### What is the value from the calculation in Path of Building?

Fixed a bug where the "Armour from Equipped Body Armour is doubled" stat was not doubling Evasion from your Body Armour when the Iron Reflexes Keystone Passive Skill was allocated.

Just seen: Unbreakable doesnt give any extra Armour having a Full Evasion Body Armour equipped. With Iron Reflexes still skilled ofc.

-> the Armour should be higher with Evasion Bases, since they can reach higher values. But it is half as high even with higher values.

### How to reproduce the issue

Tested it on a fresh Juggernaut with only Iron Reflexes skilled (pob).

Armour vs. Evasion vs. A[r/Eva](https://www.reddit.com/r/Eva/) Bases.

Even tho the other bases have higher values the Armour base still beats them.

### Character build code

```shell
https://pobb.in/DVwiqJgYdbVy
```

### Screenshots

https://preview.redd.it/q2g3839b54va1.jpg?width=872&format=pjpg&auto=webp&v=enabled&s=16aa1d7b940966f85f54063fca34ddad15500973

https://www.reddit.com/r/PathOfExileBuilds/comments/12tgtm6/juggernaut_bugfix_from_3210c_not_working_in_pob/

**Comment by QuickStick123** [comment]
You would just need to update the code to also apply to evasion we just haven't gotten around / missed this.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/c60f4c188cdc1c44fb3ff6dd004ce0e3b1d6a3ec/src/Modules/CalcDefence.lua#L500
