### ISSUE TITLE
Damage on full life gem does not affect Toxic rain DOT where it should

### ISSUE THREAD

**Issue by ciechand** [PathOfBuildingCommunity/PathOfBuilding#610]
According to the tooltip DPS and the clear speed i have been experiencing, it seems like the "damage on full life" gem affects the DOT of toxic rain, however if i do any of the following it is not factored in:

- Toggle the gem in the skills menu
- Check the DPS difference between a skill that has it equipped and one that does not in the calc tab
- Compare the DPS to another gem that should absolutely give less.

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/79949545-e0e05780-84b4-11ea-8679-c13ca5101829.png)
are you CI or have ticked "are you always on full life", if you have and it still doesnt work can you send me a Pastebin?

**Comment by LocalIdentity** [comment]
Damage on Full life is working just fine for me
