### ISSUE TITLE
Crucible tree mods not working sometimes

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [PathOfBuildingCommunity/PathOfBuilding#6106]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I assumed Crucible tree mods were being properly implemented but some don't seem to work at all.

### How does Path of Building behave?

For example, increased effect of withered from crucible tree has no effect whatsoever on my chaos build. It's like the line doesn't exist. If I just type "10% increased effect of withered" on the weapon like a proper mod it gets recognised. Screenshots show the issue.
There's many issues like that, that I find here or there. Another one is chance to poison with spells, again it doesn't get recognized by spell calculations even though the in game tooltips show it works.

### Character build code

```shell
https://pobb.in/dDGw0MJTmLS2
```

### Screenshots

![Screenshot_28](https://user-images.githubusercontent.com/74437021/233777626-01cda889-f285-4a6f-9797-8eab19d82cd7.png)
![Screenshot_29](https://user-images.githubusercontent.com/74437021/233777654-0d2552bb-561f-4a54-8740-c696474ee8cd.png)

**Comment by Regisle** [comment]
I assume this is becouse wither is 6% increased chaos damage taken in PoB and 10% inc effect gets floored to still be 6% increased damage taken per wither stack

**Comment by KonstantinosKoubetsos** [comment]
Yep I was just checking up on that. But what about poison chance with spells?
![Screenshot_31](https://user-images.githubusercontent.com/74437021/233777971-7a23f8d8-c5e9-4433-8da9-ceba43115ad8.png)
![Screenshot_30](https://user-images.githubusercontent.com/74437021/233777973-b170969a-e904-4aec-a509-dab32314b507.png)

**Comment by KonstantinosKoubetsos** [comment]
Also chance to poison on hit (without spells) doesn't seem to be recognized for attack skills.
