### ISSUE TITLE
Sorting Unique Items gets stuck at 26%

### ISSUE THREAD

**Issue by prog-r-amer** [PathOfBuildingCommunity/PathOfBuilding#612]
Sorry that I can't give a detailed bug report what exactly breaks it but sorting by combined dps no longer works (i. e. you don't see list anymore cause it is stuck at 26) when I allocate the jewels from the cluster on the top. to reproduce:

character ArcShitBuild
account name: prog_r_amer

**Comment by Pegoth** [comment]
Same, in debug mode I can see [this](https://i.imgur.com/NGjDfMd.png) error message.

**Comment by Nostrademous** [comment]
This only happen when doing a search by DPS with at least one cluster jewel in place and an extension node in that jewel allocated (doesn't matter if it's empty or has something in it). Unallocating that socket fixes the DPS.

It is a bug that will need fixing.

**Comment by tsunko** [comment]
With this Hollow Palm build (https://pastebin.com/5ACVb2in), I narrowed down the buggy unique jewel to be Might in all Forms

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
