### ISSUE TITLE
Crafting Flask breaks tooltip

### ISSUE THREAD

**Issue by CapnJack22** [PathOfBuildingCommunity/PathOfBuilding#6129]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

-

### What is the behaviour in Path of Building?

Crafting a normal or magic life, mana or hybrid flask breaks the hover tooltip that shows the effects of applying said flask.

### How to reproduce the issue

1. Import linked build to PoB.
2. Switch to Items tab.
3. Click Craft item...
4. Select Flask: Hybrid, Flask: Life or Flask: Mana.
5. Hover over the selected base.

The hover tooltip starts flickering, showing different applied effects and changing very fast.

I tried to isolate what causes this problem:
1. Unallocating Nature's Boon Pathfinder ascendancy node stops the flickering effect.
2. Having only unique flasks equipped stops the flickering effect.
3. Unallocating the whole passive tree doesn't change tooltip behaviour

### Character build code

```shell
https://pobb.in/4Hq40RplEU7T
```

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5897
