### ISSUE TITLE
Error code on Launch, - Lua 439

### ISSUE THREAD

**Issue by Aeryn-POE** [PathOfBuildingCommunity/PathOfBuilding#6136]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When I Launch PoB It should go to the normal character splash screen where I can modify a saved build or add/import a new one.

### How does Path of Building behave?

When I launch PoB it gives me the following error, followed by another and wont progress past this screen. I tried uninstalling and reinstalling the application, as well as clearing the appdata cache and neither seemed to work.

### Screenshots

![image](https://user-images.githubusercontent.com/131920720/234710113-80d95ead-6732-42bc-b92c-9b4991ad0b58.png)
![image](https://user-images.githubusercontent.com/131920720/234710395-f89fc040-e33b-4cda-8861-f30bd44db7ce.png)

**Comment by Peechey** [comment]
Likely something to do with your Settings.xml. Default path is C:\Users\{name}\Documents\Path of Building. Try to rename the file to something else or copy it and delete the original and then open PoB again (basically make sure "Settings.xml" does not exist).

**Comment by Aeryn-POE** [comment]
Worked great, thanks for the assist
