### ISSUE TITLE
The Formless Inferno minion life from overcapped fire res isn't in the final calculation

### ISSUE THREAD

**Issue by junyanliu** [PathOfBuildingCommunity/PathOfBuilding#6149]
The "minion life increased by their overcapped fire res" is listed correctly in the "Total Increased:" box, but not in the final calculation of total life. See screenshot.

![image](https://user-images.githubusercontent.com/11566390/235208989-454e1f88-4d77-4462-a835-831dc4eb047e.png)
![image](https://user-images.githubusercontent.com/11566390/235209059-3e8ac213-9483-461a-8ea5-358fe56ebaeb.png)

**Comment by Ghaduo** [comment]
Bump - This issues still persist in version 2.34.1.

**Comment by PreFollower** [comment]
Bump - This issue still persists in version 2.35.5

**Comment by Nightex14** [comment]
This is still a current issue. Will this be fixed?

**Comment by Paliak** [comment]
This is caused by minion life being calculated before minion resistances. I can't think of a good fix right now that doesn't break a bunch of other things.

**Comment by paulnirenberg** [comment]
Ahh dang, just came here to report this.

**Comment by Paliak** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6663 tried tackling the problem but it seems it has been forgotten. I'll see if i can come up with something as this seems to be a rather popular issue.
