### ISSUE TITLE
Cospri's Will doesn't give poison chance against cursed enemies

### ISSUE THREAD

**Issue by JekyllGamer** [PathOfBuildingCommunity/PathOfBuilding#6150]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I would like to calculate different Poison Chance options in PoB, but Cospri's Will does not contribute to poison chance. 

### Describe the solution you'd like

When paired with an Aura Curse, a curse on hit, a self cast curse, or when "Enemy is Cursed" box is ticked, Cospris Will (Unique Assassin's Garb) should set Poison Chance to 100%, unless "Enemy is Immune to Curses" is enabled somehow (Presently the only pure curse immunity I'm aware of is from Expedition and Crucible Remnant mods, everything else is Hexproof, which Cospri's ignores). 

### Describe alternatives you've considered

The only method of setting poison chance to 100% against cursed enemies currently is to add it as a modifier in Custom Configurations yourself. 

### Additional context
You can see here my character damage, my gear, and my configuration. I have temporal chains and despair on hit on my gloves, which you can see those curses enabled in the "Calcs" screen (Rightmost panel) where my Poison Chance is still not reflected as "always" (or 100%). 
![image](https://user-images.githubusercontent.com/119968752/235209724-f29357d7-55bb-44d6-840d-a5f20f1170e9.png)

**Comment by LocalIdentity** [comment]
If you want us to find the bug quicker. please provide a build code

**Comment by JekyllGamer** [comment]
Apologies! 
Here is my current build code: 
https://pobb.in/n4RXNbNPFcKf

Here is a build code with random sources of curses and both my imported chestpiece and the PoB built-in chestpiece:
https://pobb.in/2PgZs-MQMLMh

My internet service went down for a while last night so while it was I was fiddling with it and discovered a possible cause! 

It appears to be a problem with Cospri's explicits being reworded. They now say "Always Poison on Hit against Cursed Enemies", so that is what is present on Cospri's that are Imported from character profiles, while the program still has "Poison Cursed Enemies on Hit" on the Cospri unique.
