### ISSUE TITLE
Party Tab enhancements

### ISSUE THREAD

**Issue by Mirokira** [PathOfBuildingCommunity/PathOfBuilding#6151]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

No

### Describe the solution you'd like

The new party tab is great, however there seem to be some Values Missing.
The cool thing is somone else already did all the work:
The site poecalc.fly.dev lets me put in my Aurabot and it does some magic and tells me everything ill get from my aurabot.
eg.
https://poecalc.fly.dev/auras/Hazaky/HazAurasAgain?aura_effect=

What you can see here is that things like certain rare mods are also considered which the new Party feature doesnt have yet.

### Describe alternatives you've considered

Since there is already a Solution with the Calcs tab that would be the alternative but this new cool Party Tab could definitely be built upon

**Comment by Regisle** [comment]
> What you can see here is that things like certain rare mods are also considered which the new Party feature doesnt have yet.

can you link me your actual build so I can see which rare mods are missing, iirc all of them are added for auras, though the simple display doesnt show all the effects added (check in advanced view)

if its actually missing something I would like to fix it along with a large list of other known issues with enemy modifiers/conditions (hence them not being exported atm)

**Comment by QuickStick123** [comment]
I think it is this build.
https://pobb.in/6hWHIBSeHGRN

**Comment by Regisle** [comment]
I dont see anything missing compared to what its supposed to give (looking at what it gives a minion (skeleton) in the same build, the auras seem to all be applied with all their effects at the same values)
intimidate is missing but thats currently explained
![image](https://user-images.githubusercontent.com/49933620/235281724-9114e650-75cf-4a78-a369-d53721dc08cf.png)

**Comment by Mirokira** [comment]
Hi first thanks for looking at this
This is the build im playing: https://pobb.in/4XqhnW-rQpv9
If i run my aurabot in the partytab i have around 5m dps and effective hit pool is 78k.
With the export dps is around 5m but max hit is 101k 
Im not to much of a PoB Expert to tell exactly what is missing, Sorry.

At first glance it also looked like rift Grinder (the Sceptre he's wearing) wasnt calcualted but when i looked at the Party Tab again i see that its listed under each aura.

**Comment by Mirokira** [comment]
I took a bit of a deeper dive and noticed i hadnt enabled Discipline on the Aurabot Export which i first tought was the issue.
However when i went ahead and enabled it in the export and reinported it looks like my Energy Shield is unchanged even when Discipline shows up in the party tab

![grafik](https://user-images.githubusercontent.com/7881027/235293279-f4eb9dfb-bd93-410c-9e48-c62c10592432.png)
Same seems to happen with grace

**Comment by Regisle** [comment]
the vaal versions of the skills are currently bugged (dont export vaal skills for now) and you have some effects that arnt exported
these 2 are enemy modifiers
//Champion
Enemies Taunted by you take 10% increased Damage
// Wrath Pelt Vaal Regalia
Nearby Enemies are Blinded

and this one is due to bad config on the support
//Guardian
While there are at least five nearby Allies, you and nearby Allies have Onslaught

the vaal issues should be fixed at some point, its already been reported a few times
do you have any other issues other than those 2?

**Comment by Mirokira** [comment]
>//Guardian
While there are at least five nearby Allies, you and nearby Allies have Onslaught
Can you elaborate?
I can usually switch this to say "Onslaught" since the setup we run we have that many Allies nearby

**Comment by Regisle** [comment]
> Can you elaborate?

the export you had one did not have the "number of allies" config to atleast 5, so the guardian wasnt giving onslaught in the export,

**Comment by Mirokira** [comment]
Okay thanks a lot for elaborating looking forward to using this new feature, thanks.

**Comment by Regisle** [comment]
fixed by #6159
