### ISSUE TITLE
Assets of Release 2.29.0 missing the executables

### ISSUE THREAD

**Issue by asabit** [PathOfBuildingCommunity/PathOfBuilding#6154]
The assets of release 2.29.0 contain only the source code. The portable and setup files are missing:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v2.29.0

**Comment by Wires77** [comment]
Thanks for the heads up.  This looks to be an upstream issue with Github (See https://github.com/cli/cli/issues/7283 ) but there might be a workaround

**Comment by LocalIdentity** [comment]
New assets were released with the 2.30.0 update I just released
