### ISSUE TITLE
Getting outdated version when opening PoB - 1.4.170 version

### ISSUE THREAD

**Issue by bleak001** [PathOfBuildingCommunity/PathOfBuilding#6176]
Getting 1.4.170 version when opening PoB.

**Comment by QuickStick123** [comment]
What exactly are you asking?
If it is not updating correctly you can just download a new release at https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases.

**Comment by bleak001** [comment]
Ok. When downloading PoB it goes into version 2.6 at the end of the download of PoB.
![Screenshot (1)](https://user-images.githubusercontent.com/52143752/235367133-972c5d7b-c5f9-46b9-b95f-16e9ae4c2f23.png)

**Comment by QuickStick123** [comment]
1.4.170 is openarl's last version so you will need to redownload the community version linked prior or update the manifest.xml file yourself to use the community repository instead.

**Comment by LocalIdentity** [comment]
You are using the wrong version of PoB, refer to Quicks first comment to find the download page for the current version of PoB
