### ISSUE TITLE
"Added Small Passive Skills have #% increased Effect" Enchant on Large Cluster Jewels are applying to the notable instead .

### ISSUE THREAD

**Issue by sankethcb** [PathOfBuildingCommunity/PathOfBuilding#618]
Tested in Version 1.4.161.2 with a Large Cluster Jewel with the above mod. Applied to the notables "Primordial Bond" & "Rotten Claws" instead of the minion damage small passives.

**Comment by T3N54Z4NG3T5U** [comment]
Also have the same issue applying to medium cluster jewels.

"Added Small Passive Skills have 25% increased Effect" applies to the notable "Distilled Perfection" along with the small passive nodes of "6% increased Flask Effect Duration".

Along with this, the tree doesn't reflect the increased power of the small nodes but they do apply correctly.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.2
