### ISSUE TITLE
anyone know how to fix this? kinda frustrating

### ISSUE THREAD

**Issue by pjq1991** [PathOfBuildingCommunity/PathOfBuilding#6180]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![errorpob](https://user-images.githubusercontent.com/54997687/235416956-9bd0fd44-ecf1-4d6f-b2e0-389eda776207.jpg)
![errorpob5](https://user-images.githubusercontent.com/54997687/235417189-c648d29e-9a1a-4b12-ab1c-6e1bf71efb45.jpg)
![errorpob4](https://user-images.githubusercontent.com/54997687/235417193-c44f2271-9479-4fab-bc5a-445c7aa1abca.jpg)
![errorpob3](https://user-images.githubusercontent.com/54997687/235417195-2691949c-1b57-4a4c-a622-ab11d0193815.jpg)
![errorpob2](https://user-images.githubusercontent.com/54997687/235417198-7a6a759f-d953-4a08-afac-aadf066a1267.jpg)

### What are your system specifications and configuration?

------------------
System Information
------------------
      Time of this report: 5/1/2023, 15:33:33
             Machine name: pppppppppppppp
               Machine Id: {D8FC6AA3-566F-44DB-904D-CE232B34D4AE}
         Operating System: Windows 11 Home 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)
                 Language: English (Regional Setting: English)
      System Manufacturer: Acer
             System Model: Predator PH315-54
                     BIOS: V1.11 (type: UEFI)
                Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 CPUs), ~2.3GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16148MB RAM
                Page File: 9864MB used, 9227MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 120 DPI (125 percent)
       System DPI Setting: 120 DPI (125 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.4.6
           DxDiag Version: 10.00.22000.0001 64bit Unicode

### How to reproduce the issue

got a new laptop. downloaded the newest version and it keeps giving me this error. tried reinstalling butt not working. any tips would be appreciated

**Comment by LocalIdentity** [comment]
Looks like you have downloaded the source files instead of the installer. Go here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v2.28.0
and grab the installer file `PathOfBuildingCommunity-Setup-2.28.0.exe`
