### ISSUE TITLE
Last update made suppression chance doubled

### ISSUE THREAD

**Issue by j0hnvr** [PathOfBuildingCommunity/PathOfBuilding#6195]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Since today's update every node in the PoB is giving double effect of suppression chance.

### What is the value from the calculation in Path of Building?

...

### How to reproduce the issue

Just select a suppress chance node and on the left side it will show your % doubled.

### Character build code

```shell
https://pobb.in/5ZgQ64MSQZGx
```

### Screenshots

![image](https://user-images.githubusercontent.com/132700432/236531475-1f9fbd53-2b76-406f-b945-082d3e281580.png)

**Comment by mortentc** [comment]
I have a suspicion as to what causes this, and it should only happen when unarmed. Does equipping a weapon chance the calculations to the correct value?

**Comment by j0hnvr** [comment]
I've tried equipping a two-handed weapon and the issue persisted.
