### ISSUE TITLE
Exception when equipping a small Armour cluster jewel with two notables.

### ISSUE THREAD

**Issue by DaddyYo** [PathOfBuildingCommunity/PathOfBuilding#621]
The following exception occurs when a equipping a single Armour Jewel with two notables:
In 'OnFrame': Classes/PassiveSpec.lua:828: No entrance to subgraph

It does not seem to matter which mods I use, but things work fine if I take e.g. a small Chaos jewel with two notables.

If it matters, on a fresh character, I pathed directly to the melee damage cluster slot in the bottom left. 100% repro.

**Comment by DaddyYo** [comment]
As an update, I've seen this on other small cluster jewels as well.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
