### ISSUE TITLE
One handed unique bug

### ISSUE THREAD

**Issue by jonny199292** [PathOfBuildingCommunity/PathOfBuilding#6210]
When i try to add an one handed unique axe rentless fury, decorative axe
![image](https://user-images.githubusercontent.com/76584783/236907281-781505b4-43ea-4fc4-9f2f-c9e982f9b13a.png)
 it gives me an error on this build https://pobb.in/xwrfjKa9XBJ0  
when i try to put back the axe
![image](https://user-images.githubusercontent.com/76584783/236907405-b9fde889-13a0-4b3e-83ec-23de17189000.png)

**Comment by jonny199292** [comment]
when i hover over rare +3 thicket bow 
![image](https://user-images.githubusercontent.com/76584783/236908333-48d35eb9-fdff-4dc6-b614-7db1c42e1592.png)

**Comment by jonny199292** [comment]
i've searched for 10c jewels on this build  https://pobb.in/RoNRAe3qMtoA    and after i searched all with automate function i check include enchants and this pops out 
![image](https://user-images.githubusercontent.com/76584783/236923677-c0d87bce-c6f8-445e-bd08-61d6bcd6d52f.png)

**Comment by Wires77** [comment]
> i've searched for 10c jewels on this build https://pobb.in/RoNRAe3qMtoA and after i searched all with automate function i check include enchants and this pops out ![image](https://user-images.githubusercontent.com/76584783/236923677-c0d87bce-c6f8-445e-bd08-61d6bcd6d52f.png)

Can you open a new issue for this one since it's a different error on a different build?

**Comment by jonny199292** [comment]
> > i've searched for 10c jewels on this build https://pobb.in/RoNRAe3qMtoA and after i searched all with automate function i check include enchants and this pops out ![image](https://user-images.githubusercontent.com/76584783/236923677-c0d87bce-c6f8-445e-bd08-61d6bcd6d52f.png)
> 
> Can you open a new issue for this one since it's a different error on a different build?

ok
