### ISSUE TITLE
Animate guardian items import(or stats) is it possible?

### ISSUE THREAD

**Issue by jonny199292** [PathOfBuildingCommunity/PathOfBuilding#6211]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

when a build contains animate guardian skill pob gets only the base without items stats on animate guardian

### Describe the solution you'd like

i want to see animate guardian items stats on build with the gear i put on it or i will a customization future for animate guardian skill it will be ok, like simulate another player with minion values and influences inside a build

**Comment by Wires77** [comment]
GGG doesn't provide a character's Animate Guardian setup via their website or API.  I don't see us supporting this, so I'm going to close this issue.

For a workaround, you can create a new build with the Animate Guardian's gear, export it including auras, and use the party tab to import it as a "support character".  That should get you the supported item buffs an animate guardian would apply.

**Comment by cupkax** [comment]
#10066 should prob fix this now.
