### ISSUE TITLE
Slayer ascendancy Overwhelm node gives unarmed builds a base crit chance, this doesn't happen in game

### ISSUE THREAD

**Issue by MorRochben** [PathOfBuildingCommunity/PathOfBuilding#624]
Slayer ascendancy Overwhelm node gives unarmed builds a base crit chance, this doesn't happen in game. https://imgur.com/a/3gUwMQ1 proof this does not happen in game. this character has the The Overwhelm node from slayer and does not have resolute technique.

**Comment by norepro** [comment]
Can you share a PoB with this behavior so we can troubleshoot?  First glance at the code looks like it does the right thing, but there may be a combination of factors we're missing.

**Comment by MorRochben** [comment]
https://pastebin.com/0VMxkAVh this one does it for me

**Comment by MorRochben** [comment]
nevermind, i just see what happend. the guy who created the build used statless 1h swords to simulate hollow palms
