### ISSUE TITLE
Layout of large cluster jewel is incorrect

### ISSUE THREAD

**Issue by DonTheGreatOne** [PathOfBuildingCommunity/PathOfBuilding#625]
I am not sure if this is just my cluster jewel or all cluster jewel. But the layout of small passives and notables is different in POB than the game. here is pastebin for the pob in question
https://pastebin.com/qbTFn5hD

![screenshot-0155](https://user-images.githubusercontent.com/48394127/77089771-a0387e80-69dc-11ea-9dfe-55e0873635ff.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
