### ISSUE TITLE
Colorblind tree search highlight support

### ISSUE THREAD

**Issue by po0p** [PathOfBuildingCommunity/PathOfBuilding#6253]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Now that there is some support for node POWER colours and custom colours for positive/negative values in the tooltip, the search of the nodes is still RED highlight on dark (default tree bg) background. Which I personally really can not see at instant, so to find a node in the tree using search I have to rescan whole tree with my eyes to try to catch that red circle. I am sure people with same colourblindness problem would confirm (not the green-red guys, more like dark red / dark green guys) the same problem :)

### Describe the solution you'd like

Add a similar setting for highlighting searched nodes on the tree as it is now for "Node Power colours" (so a predefined green/blue colour) or a Hex colour setting.
Hex colour would be best, because that would allow people with different vision problems to choose the right colour for themselves. As for me personally - best would be bright yellow, or something that otherwise stands out of dark background of tree/nodes A LOT. But that may not be the case for other people.

### Describe alternatives you've considered

~~getting a new pair of eyes~~

**Comment by po0p** [comment]
1080p example
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/68482185/524cfc8e-cbde-46a1-b325-e6dee414e7c6)

**Comment by Peechey** [comment]
One easy solution would be to reuse the negative hex colour option.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/913a3a75-f6df-4129-bde6-47fb1f7e4726)

**Comment by AdamSlaninka** [comment]
Hi, is this issue junior developer friendly ? Im just looking for my first open source issue and I use Path of Building frequently. If this issue is free can you say me more details and asign the issue ? Thanks.

**Comment by LocalIdentity** [comment]
@AdamSlaninka i think it should be fairly straightforward to add. Heres the PR that added the other hex change values https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6070
Message me on discord (localidentity) and I can give you an inv to the PoB discord if you have any further questions

**Comment by admSla** [comment]
Hi, I open PR https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6866

**Comment by Peechey** [comment]
PR #6866 was merged
