### ISSUE TITLE
Maximum flask charges should be able to go below the default value

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#628]
A mod on the reworked Soul Ripper unique flask grants "+(-40 to 90) maximum Charges". This makes it possible for the Quartz flask to reduce the maximum flask charges below the default value of 30. However, PoB is only able to increase the maximum flask charges above the minimum, not reduce it below.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
