### ISSUE TITLE
[feature] Include build name in the window title

### ISSUE THREAD

**Issue by SeventhHelix** [PathOfBuildingCommunity/PathOfBuilding#629]
When having multiple PoB windows open it's difficult to see which window is which without opening it entirely and reading the "Current build:" text.

Suggestion: Include the build title in the "Path of Building" window title, e.g. "Path of Building - CycloneSally", making this readable while alt-tabbing or other window selection methods.

Related to #74, but hopefully a smaller change.

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1

**Comment by esheyw** [comment]
While this is a great addition, with really not that many windows open, the build name gets fairly thoroughly [truncated](https://i.imgur.com/tvY38w2.png). An option to drop the 'Path of Building' part, or even just put it _after_ the build name, would be greatly appreciated.
