### ISSUE TITLE
Lua crash on fresh install

### ISSUE THREAD

**Issue by justj0kerr** [PathOfBuildingCommunity/PathOfBuilding#6290]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

Re-downloaded PoB Community from the website and most recent update, using the .exe installer, and getting an error message:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/141171901/03378a51-0f39-47c4-bc87-1a7b87d85af1)

### What are your system specifications and configuration?

Windows 10
AMD Ryzen 7 1800X
GeForce GTX 1070 Ti driver 536.67
32GB ram

### How to reproduce the issue

download .exe installer
install to secondary drive
attempt to run

**Comment by Paliak** [comment]
Is your settings.xml file located inside of a OneDrive directory? You could try deleting your current settings.xml and see if that makes a difference.

**Comment by justj0kerr** [comment]
> Is your settings.xml file located inside of a OneDrive directory? You could try deleting your current settings.xml and see if that makes a difference.

This absolutely worked! Guess the settings.xml was saved as a OneDrive file, which was causing the issue. Deleted that file and re-opened PoB and it's all good to go!
