### ISSUE TITLE
"60% chance for Bleeding inflicted with this Weapon to deal 100% more Damage" mod is applied to hits

### ISSUE THREAD

**Issue by ben0x539** [PathOfBuildingCommunity/PathOfBuilding#631]
afaict this should only be applied (as 60% More) to Bleed damage, but in Calcs I can see it included as a More modifier for Skill Hit Damage as well. As a result the sidebar Total DPS number and so also the Combined DPS number is too high. (A custom mod of "60% more Damage with Bleeding", which should have the same effect, seems to be used correctly.)

Check for Updates says I'm up to date.

https://pastebin.com/KwqD1mbC

**Comment by lobsterkite** [comment]
I just noticed this as well. I happened to have gotten a weapon with both this mod and the poison mod for a pestilent strike build (scaling poison), and it makes pob think the weapon is godlike when in reality the bleed mod should be pretty insignificant.

My build: https://pastebin.com/gSqnPDyZ

You can see i have two versions of this weapon among my items, Hate Song and Hate song no bleed.  The no bleed version really should be like <1% difference in dps but instead it's getting an extra 30% more dmg.  It seems like the more modifier is being split between the hit and the dot (respectively bleed vs poison), so it throws off the numbers a lot.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
