### ISSUE TITLE
Update broken

### ISSUE THREAD

**Issue by gixxpunk** [PathOfBuildingCommunity/PathOfBuilding#6316]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Update should work.

### How does Path of Building behave?

Update downloads 6 files and then bails out with following error:

_Update check failed!
One or more files couldn't be downloaded.
Check your internet connectivity,
or try again later._

### How to reproduce the issue

Install latest release (20.3.1) -> Options -> Opt-in to weekly beta test builds -> set checkbox -> save -> Check for Update

### Screenshots

 Verzeichnis von C:\Games\Path of Building Community\Update

11.08.2023  21:36    <DIR>          .
11.08.2023  21:36    <DIR>          ..
11.08.2023  21:30            21.779 Classes{slash}ModStore.lua
11.08.2023  21:30         1.109.541 Data{slash}Skills{slash}act_int.lua
11.08.2023  21:30           774.707 Data{slash}Skills{slash}act_str.lua
11.08.2023  21:30           247.217 Data{slash}Skills{slash}spectre.lua
11.08.2023  21:30           161.984 Modules{slash}CalcSections.lua
11.08.2023  21:30           519.813 Modules{slash}ModParser.lua

**Comment by Kapsonfire-DE** [comment]
having same issue

**Comment by quicksilverfox** [comment]
Can confirm

**Comment by gixxpunk** [comment]
Fixed with latest beta.
