### ISSUE TITLE
OnFrame bad argument #1 to t_insert (table expected, got nil)

### ISSUE THREAD

**Issue by songkwongwee** [PathOfBuildingCommunity/PathOfBuilding#6340]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When I access into certain PoB's, suspected (Main Culprit) Vaal Summon Skeleton Calculation

### How does Path of Building behave?

Unable to access certain PoBs

### How to reproduce the issue

1. Load into PoB 
2. Receive nil error

### Character build code

```shell
https://pobb.in/zexyfcQLE4m5
```

### Screenshots

![Capture](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/35388736/f3b8537d-49c1-4352-86a7-fbe2d0437c3c)

**Comment by LocalIdentity** [comment]
> Are you sure you are on latest version? i cant find the `CalcTriggers.lua` file anywhere

It's on the beta branch at the moment

**Comment by songkwongwee** [comment]
Ah my apologies, I had forgotten I am on the beta version. Would switch back to non-beta for now. Thank you :)

**Comment by LocalIdentity** [comment]
Fixed in the latest beta branch
