### ISSUE TITLE
"United in Dream" unique was never updated to actually use lvl 25 Envy in PoB

### ISSUE THREAD

**Issue by CodepilotNetDevport** [PathOfBuildingCommunity/PathOfBuilding#6341]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

When equipping "United in dream" unique level **25** Envy aura/skill is available.

Values according to https://www.poewiki.net/wiki/Envy

### What is the value from the calculation in Path of Building?

When equipping "United in dream" current version item description correctly reads "Grants Level **25** Envy Skill" but only level **15** Envy is activated. That results in PoB calculating around 10% less dps ( depending on build ) than it would with the correct values of Envy level **25**.

Values according to https://www.poewiki.net/wiki/Envy

### How to reproduce the issue

Add "United in Dream" unique to a build ( or use the submitted build ). Change level of Envy on the current version to lvl **15** instead of **25** - build damage does not change even though Envy lvl 15 should add less damage than level 25. Conclusion is that level 25 Envy either does not activate level 25 envy in PoB but level 15 or level 25 Envy values haven't been updated internally in PoB.

### Character build code

```shell
https://pobb.in/O9bL5CO5XHjI
```

**Comment by CodepilotNetDevport** [comment]
> Testing with a simple build the values seem correct there is definitely a bug regarding the tooltips in that build however.

When I do a minimal build just adding United in dream the hit damage doesn't change between the unmodified current version and a version mannually modified to use level 15 envy. The tooltip changes but the values don't. Pretty sure the values for Envy level 25 are the same as level 15.

**Comment by CodepilotNetDevport** [comment]
In data/skills/other.lua the values for Envy 15 / Envy 25 seem to be the same.

**Comment by QuickStick123** [comment]
Lvl 25 envy
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/3cf70542-d7e8-48f3-81e6-4b1be7dc1f78)
Lvl 15 Envy
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/30f3c4b9-40fd-4b98-9c58-9cc7cb6ee53c)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/1e07dcf4-fff7-43c6-ace6-746dfdcaad1d)
It is scaled by the level number so it works correctly.

**Comment by CodepilotNetDevport** [comment]
Okay - yes - testing it with cyclone it seems to work. No idea why the damage ion my build doesn't change though. Strange. Can I do something to find out what is going wrong there ?

**Comment by CodepilotNetDevport** [comment]
Oh well - no idea - suddenly it works. My bad, sorry ofr the time :( ...

**Comment by Wires77** [comment]
> Okay - yes - testing it with cyclone it seems to work. No idea why the damage in my build doesn't change though. Strange. Can I do something to find out what is going wrong there ?

It's just a tooltip bug.  If you watch the numbers on the left they will update upon saving the level change.
