### ISSUE TITLE
Cult-Leader notable has no effect

### ISSUE THREAD

**Issue by jaakerisalu** [PathOfBuildingCommunity/PathOfBuilding#635]
I'm running Herald of Purity and this notable seems to not trigger. I tried activating other Heralds too, but no change.

![cultleader](https://user-images.githubusercontent.com/9283537/77225863-fee82e80-6b7b-11ea-91a8-720a8d926f69.png)

Build pastebin: https://pastebin.com/KWT6Um2v

**Comment by ppoelzl** [comment]
Modifiers coloured red are unsupported.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.1
