### ISSUE TITLE
The "Ngamahu" node in "Chieftain" is not functioning normally. (2.31.1)

### ISSUE THREAD

**Issue by KRViadoR** [PathOfBuildingCommunity/PathOfBuilding#6354]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Np

### How does Path of Building behave?

Np

### Screenshots

![화면 캡처 2023-08-16 025813](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/142342560/c837e86f-c7c1-4fbb-b45d-4a47c703a655)

**Comment by Wires77** [comment]
Red text means a mod is unsupported.  In the future, actually filling out the bug report template would be appreciated instead of just putting "Np" there.

**Comment by Paliak** [comment]
Should work correctly in latest version.
