### ISSUE TITLE
how do i fix this iv reinstalled i delected every thing for it then installed it again

### ISSUE THREAD

**Issue by darrin78** [PathOfBuildingCommunity/PathOfBuilding#6359]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

wont let me import without a error

### How does Path of Building behave?

wont let me import without a error

### How to reproduce the issue

i just imported the build i wanted from my charater import

### Character build code

```shell
idk
```

### Screenshots

https://i.imgur.com/GyaUicN.png

**Comment by Wires77** [comment]
Yeah, it seems GGG removed a field PoB previously relied on.  We'll get a hotfix out for this soon

**Comment by darrin78** [comment]
thanks

**Comment by Cosito1984** [comment]
hi, you find the way to solve this problem ? im havin the same error i cant figureout wath to do? , sory mi bad english
