### ISSUE TITLE
LUA Error when try to set skills gems

### ISSUE THREAD

**Issue by bloddymane** [PathOfBuildingCommunity/PathOfBuilding#636]
![image](https://user-images.githubusercontent.com/62486460/77238563-7bdccd80-6ba7-11ea-9d02-7afe31e897db.png)

![image](https://user-images.githubusercontent.com/62486460/77238567-872ff900-6ba7-11ea-8448-da1bfc792e0c.png)

**Comment by ppoelzl** [comment]
Could you provide a build where this happens?

**Comment by bloddymane** [comment]
> Could you provide a build where this happens?

Here is https://pastebin.com/VM2M7Yjr

**Comment by LocalIdentity** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/753
