### ISSUE TITLE
Bug vs nebulis, doesnt not scale damage by resistances

### ISSUE THREAD

**Issue by ArkkBtw** [PathOfBuildingCommunity/PathOfBuilding#6361]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

you sould add resistances and the damage sould show up

### How does Path of Building behave?

Bug vs nebulis (item), doesnt not scale damage by resistances, even adding them manually

**Comment by Wires77** [comment]
I'm not able to reproduce this issue, do you have a build code?  Make sure you are increasing your maximum resistances.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1209372/c81751e1-44c9-4ebf-ac55-5f1d21295cba)

**Comment by ArkkBtw** [comment]
weird this happens to me and ato my friend aswell

**Comment by Wires77** [comment]
> weird this happens to me and ato my friend aswell

...a build code would really help in finding the issue

**Comment by ArkkBtw** [comment]
https://pobb.in/QBzb4RZyaPfV

And aso, the newchieftain ascendancy of resistances also bugged for my and my friend atleast, doesnt add cold or light resistances at 50% of fire resistance value.

**Comment by Wires77** [comment]
Not at the moment, correct.  Should be in the next patch though.

**Comment by ArkkBtw** [comment]
okay thankyou, but ask you can see this still not working idk what im doing wrong there
https://pobb.in/nG1TzfcS1N5V

**Comment by Wires77** [comment]
Your resistance has to be *above* 75%.  Allocate Prismatic Skin and then you'll be able to see what I mean.

**Comment by ArkkBtw** [comment]
![imagen](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/142361740/fd6676b6-57e1-4402-bb3b-d753cafcf8bf)
 i dont get it, now prismatic skin is alocated still not working >.<

**Comment by ArkkBtw** [comment]
im gonna try adding an utility flask with the same nebulis stats, see if works

**Comment by ArkkBtw** [comment]
okay so maybe im miss understanding the nebulis, only in creases 18% damage per max resistance up to 90% max res?

**Comment by ArkkBtw** [comment]
I am curious what you thought it was supposed to do, though.

well, anywere sais scales with MAX RES just above like other items say, overcapped res, you probs get my point haha
