### ISSUE TITLE
Issue i dont know how to fix

### ISSUE THREAD

**Issue by Jakz-gaming** [PathOfBuildingCommunity/PathOfBuilding#6362]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![Screenshot 2023-08-15 181246](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/54295780/985f4604-f31a-4e55-9258-8b5777c88a3e)

### What are your system specifications and configuration?

windows 11
RTX 2060

### How to reproduce the issue

open POB 

i have tried uninstalling then reinstalling  no fix
i have deleted all old file paths and re installed    no fix

this started happening after a smaller patch GGG released

**Comment by Wires77** [comment]
Duplicates #6359

**Comment by Jakz-gaming** [comment]
checked the duplicate from above

is there a hot fix?
