### ISSUE TITLE
Ignite acting incorrectly with less 1 stack potential

### ISSUE THREAD

**Issue by Alaexaender** [PathOfBuildingCommunity/PathOfBuilding#6366]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Ignite dps should be found using (base dps*burn rate*effective dps mod).  Note that in my case, ignites are being refreshed through the "defiled forces" node, so ignite duration is irrelevant.

### How does Path of Building behave?

Ignite dps is lower than expected, based on the detailed calculation numbers.  For me it says 444k*1.46*1.77=682k

### How to reproduce the issue

Choose vortex with shaper of flames.
Lower ignite duration to under 1 stack potential (I used replica emberwake).
Look at "Ignite DPS".
Note, Manually overriding "stack potential" does not fix the issue.

### Character build code

```shell
https://pobb.in/aj9ZwSQLXh_0
```

### Screenshots

![3e9ef5740631a16f69c98b30a7b40f7d](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/64733199/43bc60a0-77db-4750-b0bd-ebde7e06c1af)

**Comment by Wires77** [comment]
What number do you expect to see?  The formula you listed and the formula that is present are the same.

We don't support Defiled Forces (red text) if that's what you expect to make the difference.

By the way, you say you're refreshing the duration, but you curse only casts ~once per second, but the ignite expires in half that time, so you won't be able to keep it up with just curses (though obviously you might not be using Replica Emberwake in your final build)
