### ISSUE TITLE
Latency issue

### ISSUE THREAD

**Issue by ProHibbitz** [PathOfBuildingCommunity/PathOfBuilding#6370]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When I add/remove a passive, skillgem, item - Pob should respond within ms's

### How does Path of Building behave?

When doing any edits within pob the application hangs for 3-10 seconds before doing the issued command

### How to reproduce the issue

1. Load a Pob
2. Click skill tab
3. click enable/disable

### Character build code

```shell
https://pobb.in/m_ObMYeeNKul
https://pobb.in/X8ozqWOKUSYn
https://pobb.in/Ut1VJUJR0k1A
```

### Screenshots

![pob issue](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/142424269/710ffbee-7b5f-4f22-a5e3-435cac08ff0c)

**Comment by LocalIdentity** [comment]
Sounds like you might be running into the same issue people here are https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6287
The common cause for others was Avast, but take a look through the thread to see if you can find anything that helps you

**Comment by ProHibbitz** [comment]
Thank you so much! it ended up being location issue
