### ISSUE TITLE
The Searing Touch: +#% Fire Damage over Time Multiplier is ignored

### ISSUE THREAD

**Issue by xiontu** [PathOfBuildingCommunity/PathOfBuilding#639]
+#% Fire Damage over Time Multiplier is not included in the damage calculation of ignites or righteous fire

**Comment by ppoelzl** [comment]
I cannot reproduce that, for me it is included both in the DPS calculation as well as in the breakdown.
![rf](https://user-images.githubusercontent.com/33464174/77273485-04489480-6cb4-11ea-9c88-5b212139c5d1.png)
Could you provide a build that shows your described behaviour?

**Comment by xiontu** [comment]
I checked it again it works. I expected a separat listing for each source in "Total More".
