### ISSUE TITLE
Download information not found

### ISSUE THREAD

**Issue by ShadowWisp** [PathOfBuildingCommunity/PathOfBuilding#6390]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When launching PoB it should open last vieved

### How does Path of Building behave?

After latest update i  have started to open my copy of POB to an empty build with the titled error.
The only hint as to what can cause that error is default savepath being "C:\Users\X\Documents/Path of Building/builds" as opposed to  "C:\Users\X\Documents\Path of Building\builds" but fixing that didn't fix my main error.

### How to reproduce the issue

Change CPU due to the old one being physically broken with random BSODs
Install windows onto SSD
Install PoB fresh, import old files with builds
Change ownership of the old files to being active user
Restart PC
Open PoB
???
Profit

### Screenshots

![Screen1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/27205923/f28039a7-6da0-48ae-add9-f14833e123fb)

**Comment by Wires77** [comment]
Will you take a screenshot of the console?  Press Ctrl+` to open the console in PoB.

**Comment by Lilylicious** [comment]
Note that this isn't possible on all keyboard layouts, so you may need to swap to a US layout in order to open the console, if not already on one. If you do, then it's Ctrl + the button to the left of 1.

**Comment by ShadowWisp** [comment]
![Screen2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/27205923/00115580-488f-4cbb-bb85-d4ee25215ce4)
![Screen3](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/27205923/ce16b310-34d7-4e5a-84da-1304fbdcb1e2)
It cannto find Config files, wut?

**Comment by Wires77** [comment]
That's normal.  I don't see anything amiss in the logs.  My guess would be a OneDrive issue.  Can you manually open your Settings.xml file?  It should be in Documents/Path of Building

**Comment by ShadowWisp** [comment]
[Copy_Settings.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/12373298/Copy_Settings.txt)

**Comment by ShadowWisp** [comment]
Also i have OD deleted seeing as it doesnt work in Ru

**Comment by Wires77** [comment]
Does just going back to the build list work?  Can you just make a new build from there?

**Comment by ShadowWisp** [comment]
yes it opens them fine, it's just reopening to an empty errored build as screenshotted int OP

**Comment by ShadowWisp** [comment]
And creating and saving builds works fine

**Comment by Wires77** [comment]
How are you opening PoB?  The only place that message appears is when you're sending PoB a command line argument when opening it, e.g. opening a "pob://" link.

**Comment by ShadowWisp** [comment]
"C:\Users\X\AppData\Roaming\Path of Building Community\Path of Building.exe" "C:\Users\X\AppData\Roaming\Path of Building Community\Launch.lua"
as described in PoB.Lnk on desktop

**Comment by ShadowWisp** [comment]
Edit: Manually changed Lua part to force english username folder, basically changed the X' user to be X w/o suspected Ru chars? and it worked well... But the installator made the link as Admin/.exe, User/.lua. Why how and tf?

**Comment by ShadowWisp** [comment]
so basically somehow installer made desktop link with code
"C:\Users\Admin\AppData\Roaming\Path of Building Community\Path of Building.exe" "C:\Users\User\AppData\Roaming\Path of Building Community\Launch.lua"
How?

**Comment by ShadowWisp** [comment]
Okay, i'ma close that with the undestanding that installer made wrong code with Lua file starting under "user" folder despite being installed in same folder as Exe, in "Admin" folder

**Comment by Wires77** [comment]
Huh, glad you got it figured out, first time seeing this particular issue.  PoB doesn't handle unicode characters in file paths, so if you see something similar in the future double check that as well.
