### ISSUE TITLE
A Bull**** build detuning configuration button

### ISSUE THREAD

**Issue by AdamtheNoob** [PathOfBuildingCommunity/PathOfBuilding#6395]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Newer players may find it difficult to identify if a build guide posted online is realistic for them and can sustain good damage with normal gear. There exist builds online advertised as accessible but cost amounts of currency a newer player cannot be expected to get.

### Describe the solution you'd like

Create a button that allows newer players to set the config to a realistic setup to avoid inflated numbers promised by the build creator.

Summary
- Disables/toggles flasks
- Replace Awakened skill gems with regular, 20/20 gems
- Randomises timeless jewel number to avoid expensive hyper specific seed numbers
- Uncorrupts or identifies double corrupted gear
- Toggle off all guard skills for realistic ehp
- Remove ailment effect from enemies if the build does not apply them, chilled, frozen, shocked, maim, intimidated etc.
- Is enemy a boss? set to Guardian/Pinnacle
- Remove charges if no generation is present

### Describe alternatives you've considered

Currently a newer player will have no context on a build and will either have to be informed or gradually figure out the signs.

### Additional context

Based off of https://old.reddit.com/r/PathOfExileBuilds/comments/15tpape/how_to_detune_bul_builds_in_path_of_building/

**Comment by Wires77** [comment]
No.  Sometimes these things are necessary for a build to even function or sometimes the build will be geared towards hyper-specific content.  Everyone would disagree on what to turn off/on, and it's up to the player to decide that for themselves.

**Comment by Lilylicious** [comment]
In addition we'd be more likely to add warnings when something is possibly incorrect, and completely prevent things that are impossible. Neither of those options requires altering builds.
