### ISSUE TITLE
Invalid input

### ISSUE THREAD

**Issue by 999Lean** [PathOfBuildingCommunity/PathOfBuilding#6402]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/77915569/8fbb4490-a69b-47a8-a138-6c5ede80b870)

i had issues with save my pobs with onedrive bug. i solved this problem but now. i have this

can someone help what can i do please?

### What are your system specifications and configuration?

windows 10 pro n
1060 3gb
driver 536.99
16 gb ddr3
e-5 2689 8 core 

### How to reproduce the issue

1. put any link in windows for bilds url
2. click import

**Comment by Paliak** [comment]
Where did you get the pastebin link from? The contents don't look like a valid buiild.

**Comment by 999Lean** [comment]
my bad. sry)

**Comment by LocalIdentity** [comment]
The link you sent is for the trade website extension Better Trading. Contains a bunch of searches
