### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuGongjie** [PathOfBuildingCommunity/PathOfBuilding#6405]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

idk how to describe it. Screen Shot should be show everything.

### What is the wording in Path of Building?

idk how to describe it. Screen Shot should be show everything.

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/111702564/33907d39-7e7d-4e00-b5ef-4a56cf3414b0)

**Comment by SuGongjie** [comment]
mouse over try select different level

**Comment by SuGongjie** [comment]
> Provide a build code

sry . my bad . u mean is pob code ? https://pobb.in/U_MG4kBTZScX

**Comment by Peechey** [comment]
I can't recreate in live, so it could possibly be something locally with your build xml. Can you try this: open a new blank build and import the pobbin link you posted above and see if the error persists?

**Comment by harrrson** [comment]
I face similar problem with error while trying to change passive tree
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/45640997/8fd0b25f-c506-4b82-9a72-0b20a7c7c089)
Build i'm trying to load is https://pobb.in/-5kdD0wJErS-
PoB instaled via AUR repo path-of-building-community-git

**Comment by LocalIdentity** [comment]
If you're getting this error, it's cause you're on the dev branch of PoB. Switch to master for a more stable branch, dev is never expected to be 100% stable and has a number of other small issues that makes it unsuitable for mainstream use
