### ISSUE TITLE
Missing Returning Projectiles Support

### ISSUE THREAD

**Issue by spaulaus** [PathOfBuildingCommunity/PathOfBuilding#6429]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When adding skill gems I should be able to add `Returning Projectiles Support`. 

### How does Path of Building behave?

When adding a skill gem I do not have the option to add `Returning Projectiles Support`. 

### How to reproduce the issue

1. Open the Skills tab
2. Add a new skill group
3. Search `projectiles`
4. The option will not appear. 

### Character build code

N/A

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1553042/a2c9b61c-832e-44b8-b8b8-b52098308da9)

**Comment by Lilylicious** [comment]
The new skill gems are not yet in PoB. The update is in the works still.

**Comment by spaulaus** [comment]
@Lilylicious : Thanks for the update!
