### ISSUE TITLE
arcane cloak/ archmage update error

### ISSUE THREAD

**Issue by zjasonyang** [PathOfBuildingCommunity/PathOfBuilding#643]
![Annotation 2020-03-23 112045](https://user-images.githubusercontent.com/5600161/77277652-5f03df80-6cf8-11ea-98d0-ef30222be2e2.png)

**Comment by LocalIdentity** [comment]
Please provide a Pastebin for the build so I can try to replicate the issue

**Comment by zjasonyang** [comment]
https://pastebin.com/KSxwSAas  

thanks for your help.

**Comment by Magiosnik** [comment]
It happens when you hover the DPS Mod section in calc.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.167.2
