### ISSUE TITLE
Quest/vendor rewards for gems

### ISSUE THREAD

**Issue by TEXHIK** [PathOfBuildingCommunity/PathOfBuilding#6435]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I'd like to be able to check where you get skill gem in acts, so I don't need to check wiki every time.

### Describe the solution you'd like

When I'm hovering over a skill gem, somewhere in notes after gem stats info where this gem is given as quest reward or vendor reward for current class, like so:
V: act 3 - only vendor reward for current class
QV: act 2 - given as quest reward and also avaliable as vendor reward (may be leave only Q, because all quest rewards are vendor rewards too
For gems not avaliable to current class (except library/lily) there is alternative variant with 1st letter of class in [], for example this is how Ancestral warchiev info may look like.
[M] Q: act 3 
[DMTS] V: act 3
It is also possible to always make full info, but I think, there should be an option to oinly leave short version.

### Describe alternatives you've considered

Currentry the only way is to use wiki or other 3rd party sites.

**Comment by Wires77** [comment]
Not all of this info is available in the data, so it would be a lot of manual work to keep up-to-date.  In addition, PoB is primarily focused on optimizing endgame builds, so spending time on leveling improvements is largely out-of-scope for us.

If it helps, hovering over any gem and pressing F1 will open the wiki page for that gem.

**Comment by TEXHIK** [comment]
>Not all of this info is available in the data
That's sad, but reasonable. Not only because much work, but there is much space for mistakes and inconsistensy.

>hovering over any gem and pressing F1 will open the wiki page for that gem.
Didnt know about that, that is absolutely a solution, thank you!

**Comment by mositho** [comment]
Was just about to post something similiar until I saw this post and just wanted to say that the F1 feature is amazing! 
Maybe it would be helpful to have a small tip similiar to the shift pathing tip so that this feature is more obvious. 

Appreciate all the work you guys doing, you are the absolute legends
