### ISSUE TITLE
Lua Function Call Crash

### ISSUE THREAD

**Issue by TimSchiementz** [PathOfBuildingCommunity/PathOfBuilding#6438]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/118667807/f20f334f-79bc-4e70-a238-219a426cafe5)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/118667807/81842fac-c171-400b-a7a3-ee2c9bc5c21d)

### What are your system specifications and configuration?

Operating System: Win 10 Pro 64
Graphics: Nvidia gtx 1070 Ti; Driver Version: 537.1
Language: English
Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz

### How to reproduce the issue

Launch the Programm

---

I already reinstalled the programm

**Comment by APRB** [comment]
I have the same issue and it seems to be from mousing over the tooltips for the scion ascendancies class specific nodes (e.g. Witch Ascendancy)
Seems to just be for the base class node, like 'Witch Ascendancy', but not 'Path of the Witch' or 'Occultist'
Issue is replicable at will by simply mousing over the Node's again. Also applies to Shadow,Duelist,Templar,Marauder Ascendancy nodes on the Scion Ascendancy Wheel.

**Comment by Paliak** [comment]
Should be fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6454

**Comment by TimSchiementz** [comment]
> I have the same issue and it seems to be from mousing over the tooltips for the scion ascendancies class specific nodes (e.g. Witch Ascendancy) Seems to just be for the base class node, like 'Witch Ascendancy', but not 'Path of the Witch' or 'Occultist' Issue is replicable at will by simply mousing over the Node's again. Also applies to Shadow,Duelist,Templar,Marauder Ascendancy nodes on the Scion Ascendancy Wheel.

I can´t mouse over anything because it doesn´t even get to the tree or anything else. When I launche the programm it just crashes. Then i press F5 for retry but nothing changes.

**Comment by Wires77** [comment]
> > I have the same issue and it seems to be from mousing over the tooltips for the scion ascendancies class specific nodes (e.g. Witch Ascendancy) Seems to just be for the base class node, like 'Witch Ascendancy', but not 'Path of the Witch' or 'Occultist' Issue is replicable at will by simply mousing over the Node's again. Also applies to Shadow,Duelist,Templar,Marauder Ascendancy nodes on the Scion Ascendancy Wheel.
> 
> I can´t mouse over anything because it doesn´t even get to the tree or anything else. When I launche the programm it just crashes. Then i press F5 for retry but nothing changes.

Seems like something is wrong with your saved build.  If you want to copy the XML and upload it to pastebin or something we can take a look

**Comment by TimSchiementz** [comment]
> > > I have the same issue and it seems to be from mousing over the tooltips for the scion ascendancies class specific nodes (e.g. Witch Ascendancy) Seems to just be for the base class node, like 'Witch Ascendancy', but not 'Path of the Witch' or 'Occultist' Issue is replicable at will by simply mousing over the Node's again. Also applies to Shadow,Duelist,Templar,Marauder Ascendancy nodes on the Scion Ascendancy Wheel.
> > 
> > 
> > I can´t mouse over anything because it doesn´t even get to the tree or anything else. When I launche the programm it just crashes. Then i press F5 for retry but nothing changes.
> 
> Seems like something is wrong with your saved build. If you want to copy the XML and upload it to pastebin or something we can take a look

Do you mean the manifest.xml?

**Comment by suptoast** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/143233033/0b4800cb-8baa-44b6-8b56-dc071bc52e2d)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/143233033/829c9c0e-0b65-42d8-a7dd-582347726269)

got the same error and tried some stuff with onedrive that someone suggested but nothing worked. pc restarted, changed install destination, redownloaded, downloaded and older pob version nothing works

**Comment by DmILar** [comment]
@suptoast had same issue, you can temporary fix this error by adding this code
if str == null then 
  return
end

in the file "Path of Building Community\lua\xml.lua", in function xml.ParseXML(str)
like that:
<img width="227" alt="image" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/132146042/c472a04a-7ebf-4f7b-b56b-83469465bff1">

after that you can run it and update using interface

**Comment by TimSchiementz** [comment]
Hey, I reinstalled the programm today and tried the thing from @DmILar but it still shows the error. If the XML File from @Wires77 helps I would do it I just need to know the Filename.

**Comment by Wires77** [comment]
> Hey, I reinstalled the programm today and tried the thing from @DmILar but it still shows the error. If the XML File from @Wires77 helps I would do it I just need to know the Filename.

It would likely be the last build you opened up.  If you want to find your Documents/Path of Building/Settings.xml file and remove it, PoB should create a new one the next time it opens up.

**Comment by TimSchiementz** [comment]
Thanks that opened the Programm again.
