### ISSUE TITLE
UI incompatible with Portrait mode

### ISSUE THREAD

**Issue by darkdex52** [PathOfBuildingCommunity/PathOfBuilding#644]
PoB window is very limited in how small it can be stretched on horizontal plane, so on 1080p Portrait mode (vertical) monitor setups, a lot of elements become unreadable.

**Comment by Wires77** [comment]
Fixed in 2.3.0

**Comment by darkdex52** [comment]
Nice job, most elements are now readable on portrait mode monitors, but the wider PoB window still will extend into nearby monitors because it can't be small than 1280px. On most common portrait mode monitors that would have to go down to 1080px.

**Comment by Wibbbs** [comment]
I am running 2.3.0, but the minimum width still seems to be greater than 1080px. Appears to be 1280 as stated above. Would love to be able to have POB open on side 1080px portait monitor.

**Comment by Wires77** [comment]
Thanks for the feedback, I'll update that for the next release.  I don't have a portrait mode setup myself, so the one monitor I tested on didn't show the overlap.

**Comment by Wibbbs** [comment]
Thanks so much! Looking forward to it.

**Comment by Wibbbs** [comment]
I see this was merged into master. Anyway for me to get a build with the change included? Or do I need to wait for the next major release? 

Is there a beta build anywhere?

**Comment by ppoelzl** [comment]
@Wibbbs You can build SimpleGraphic yourself with the instructions provided in the repo. However, we're looking forward to a new release soon, so you might not have to wait for very long.

**Comment by Wires77** [comment]
You can also download the latest automatic build from here: https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/suites/2641550687/artifacts/57994533

**Comment by Wibbbs** [comment]
Amazing! I got the new dll from your link and just tried it out and it looks great on a 1080x1920 portrait monitor. Thanks so much!
