### ISSUE TITLE
Crash when trying to import some builds, worked just fine before 08/23 update.

### ISSUE THREAD

**Issue by joaorauta** [PathOfBuildingCommunity/PathOfBuilding#6449]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

[https://ibb.co/YybyH3D](url)

### What are your system specifications and configuration?

rtx 2060 6gb
i5 9gen
win 11

### How to reproduce the issue

import this pob: https://pobb.in/nFCrty0rjBlu

**Comment by Wires77** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6448 in the next update
