### ISSUE TITLE
error on hovering any "Effective DPS" and "Total increased %" category makes an error

### ISSUE THREAD

**Issue by Bouyou34** [PathOfBuildingCommunity/PathOfBuilding#645]
![image](https://user-images.githubusercontent.com/34380414/77333891-5c1ee400-6d24-11ea-94c8-c0382a180ca5.png)
![image](https://user-images.githubusercontent.com/34380414/77334002-853f7480-6d24-11ea-99f5-568392f3ea3e.png)
https://pastebin.com/SyagvdvN

**Comment by LocalIdentity** [comment]
The bug was fixed in the update I pushed 4 hours ago, 1.4.167.2
