### ISSUE TITLE
"trade for these items" bug

### ISSUE THREAD

**Issue by Oxleyjus** [PathOfBuildingCommunity/PathOfBuilding#6459]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

You cannot search for best items because there is error getting league list and you cannot select "Ancestor" league. It crashes client
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/39136990/d6feecc9-d848-4ad3-a4e3-5d2558a44b9c)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/39136990/8cc3e23d-f587-4aae-88d5-0f9a069ab0d6)

### How does Path of Building behave?

You cannot search for best items because there is error getting league list and you cannot select "Ancestor" league. It crashes client

### How to reproduce the issue

Press Button "Trade for these items" in the Items tab.

**Comment by jimmy-sc** [comment]
I had the same issue yesterday and got it working again after refreshing my POESESSID. 
I guess POB is using an invalid/old POESESSID here and therefore can't fetch any league information. Maybe there should be some kind of validation for that.

**Comment by Oxleyjus** [comment]
I refreshed POESESSID, but it nothing changed. Still the same error fetching "leaguelist".
