### ISSUE TITLE
Inquisitor Ascendancy node bug

### ISSUE THREAD

**Issue by Chainsaw8303** [PathOfBuildingCommunity/PathOfBuilding#646]
Hey I've been putting together an Inquisitor build and it looks like the node "Inevitable Judgement" is not ignoring enemy elemental resistances. 
Pastebin for the build is below.

https://pastebin.com/AF6QT5ph

**Comment by LocalIdentity** [comment]
You didn't have any selection for the "Is the enemy a Boss" dropdown box, mobs by default have no resistances. Set the box to Shaper/Guardian

**Comment by Chainsaw8303** [comment]
Ah ok thank you I did not know normal mobs don't have resistances.
