### ISSUE TITLE
Totem Duration incorrectly increasing Storm Burst Spell Totem skill duration

### ISSUE THREAD

**Issue by Motatopato** [PathOfBuildingCommunity/PathOfBuilding#6461]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

tgdf

### What is the value from the calculation in Path of Building?

gdftgd

### How to reproduce the issue

Allocating totem duration nodes such as Primal Manifestation, Sleepless Sentries, or Hierophant's "Pursuit of Faith", gives additional skill effect duration listed in Storm Burst's "Duration Mod" stats, increasing the listed "Skill Duration" stat, which also increases the "DPS multiplier for this skill" listed in the Skill Hit Damage breakdown, under "Skill DPS".

This seems to be a result of the change made in 2.32.0:
"Fix totem duration mods not applying by @Paliak" in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6388
(and is not present in earlier versions)

### Character build code

```shell
https://pobb.in/htEJ2jkFu0AM
```

### Screenshots

![totembug](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/53984063/3854f93b-fcca-4a26-b553-d683ba431f2f)

**Comment by Paliak** [comment]
It didn't work at all before and now it's matching against the inherited totem tag. Will need to fix.
