### ISSUE TITLE
Can you check Volatility calculation?

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [PathOfBuildingCommunity/PathOfBuilding#6477]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Don't konw

### What is the value from the calculation in Path of Building?

In this build, Volatility nearly triples the damage.
Is this correct?
Is there any wrong when Volatility interact with lucky damage or Ryslatha's Coil or damage convert?
Thx!

### Character build code

```shell
https://pobb.in/HV0sCAzzZUwz
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/10475153/497e9393-17e9-45c8-b552-2aced3ea1e28)

**Comment by LocalIdentity** [comment]
Fixed in 2.33.0
