### ISSUE TITLE
Items with variants created in versions <1.4.167.1 are partially broken

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#648]
In 1.4.167.1, the way that item variants are handled was changed. However, this doesn't correctly apply to existing items that now have additional tags which the program doesn't understand anymore.
![bricked](https://user-images.githubusercontent.com/33464174/77369306-94dbaf00-6d5e-11ea-99ba-7f64519d7270.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
