### ISSUE TITLE
Crash when using Flamewood Support

### ISSUE THREAD

**Issue by eugenikus8** [PathOfBuildingCommunity/PathOfBuilding#6485]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![2023-08-25_015656](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51211736/f6faa9d1-7ed8-4ba4-8e68-e7bab80f62f7)

### What are your system specifications and configuration?

Windows 7
ATI Mobility Radeon HD 5470  (1 ГБ)
"D:\Soft\Path of Building Community\Path of Building.exe

### How to reproduce the issue

1. Choose any totem, for example Decoy Totem
2. Add from list Flamewood Support
3. Try to select another totem from the list instead of the selected totem or click on the Remove this gem cross next to the selected totem

**Comment by Paliak** [comment]
Should be fixed by #6486

**Comment by LocalIdentity** [comment]
Fixed in 2.33.1
