### ISSUE TITLE
Arakaali's Fang cannot show DPS

### ISSUE THREAD

**Issue by matt01003** [PathOfBuildingCommunity/PathOfBuilding#6491]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

/

### How does Path of Building behave?

/

### How to reproduce the issue

In "Skills"
Select "Raise spider"
Enable "Include in Full DPS"
It should show DPS on the left, but nothing happens

**Comment by Acohen455** [comment]
Just ran into this, and took a video of it happening: https://streamable.com/qi2twg

**Comment by jajakproject** [comment]
I have the same issue as well after updated the latest patch.
