### ISSUE TITLE
POB 25.08.2023

### ISSUE THREAD

**Issue by Rachedus** [PathOfBuildingCommunity/PathOfBuilding#6496]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

error

### How does Path of Building behave?

error

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/143176769/8409b2ec-75d9-4577-ae48-38195785fb9a)

**Comment by LocalIdentity** [comment]
Assume this was fixed in 2.33.1
