### ISSUE TITLE
Flamewood support (Avenging Flame) crash

### ISSUE THREAD

**Issue by eugenikus8** [PathOfBuildingCommunity/PathOfBuilding#6498]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![2023-08-25_145237](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51211736/5815d97e-86a4-4908-9c80-7909507e0a8b)
![2023-08-25_150532](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51211736/d5137130-10c3-42c6-bfa1-2e2cf841eecb)
![2023-08-25_143601](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51211736/27ed0cd6-ff6c-4bc5-9dad-cf781626f9f7)
![2023-08-25_144840](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51211736/10748ad1-985d-4f3c-bacf-8a0edfaa1974)
![2023-08-25_144959](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51211736/6e24760a-2f70-468f-a8da-177068758e4b)

### What are your system specifications and configuration?

Windows 7
ATI Mobility Radeon HD 5470 (1 ГБ)
"D:\Soft\Path of Building Community\Path of Building.exe

### How to reproduce the issue

Trying to add a support gem for Flamewood support (main skill ->Avenging Flame)

### Character build code

```shell
https://pobb.in/2OX8k2I1QHTz
```

**Comment by LocalIdentity** [comment]
This error does not occur to me on the current version.  What version are you using?

**Comment by eugenikus8** [comment]
2.33.1

**Comment by eugenikus8** [comment]
1. choose any totem
2. Add Flamewood Support
3. switch to main skill ->Avenging Flame
4. click on an empty field to add a support gem
5. crash

**Comment by eugenikus8** [comment]
Ancestral Bond disables Avenging Flame?

**Comment by Paliak** [comment]
>Ancestral Bond disables Avenging Flame? Is this a PoB bug?

Seems like one.
