### ISSUE TITLE
Assassin's Mark and Reduced Curse Effectiveness

### ISSUE THREAD

**Issue by Thanat0sNihil** [PathOfBuildingCommunity/PathOfBuilding#650]
The calculation for the "Hits against Cursed Enemies have +#% to Critical Strike Chance" portion of Assassin's Mark is bugged, at least, when Assassin's Mark is level 10(where #=2) and the enemy is configured as having seemingly any amount of reduced curse effectiveness, the resulting added critical chance is less than it is at level 9(#=1.9). A dramatic case is when the boss is set to shaper/elder and level 10 assassin's mark is shown to contribute nothing to critical chance at all.  This is the primary PoB I encountered this on though I was able to replicate it on multiple other builds as well: https://pastebin.com/1EDnuncE

**Comment by Thanat0sNihil** [comment]
This seems to be almost certainly a Casting issue wherever the crit added base crit value is getting read in as a variable, as I've found that the issue also occurs when #=3, at gem level 30. It seems like what is happening is that the typing is not being enforced somewhere such that when the curse effectiveness calculations happen, you're performing integer division in the above cases.

**Comment by ppoelzl** [comment]
Closed as mark skills are not affected by reduced curse effectiveness on enemies anymore.
