### ISSUE TITLE
Path of Building Lua error setJewelRadiiGlobally

### ISSUE THREAD

**Issue by Daiug** [PathOfBuildingCommunity/PathOfBuilding#6508]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![Pob error](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/24322104/2c816d5b-b7b4-477d-842a-a042ee9a6994)

Just tried updating PoB just now, and it just crashed giving me this error.
Tried deleting the Settings/Builds folder under Documents but nothing really changed

### What are your system specifications and configuration?

Windows 10

### How to reproduce the issue

Open PoB

**Comment by Peechey** [comment]
Can you provide a build code or an account/character to import?

**Comment by suptoast** [comment]
got the exact same problem now after starting the new league

**Comment by Daiug** [comment]
> Can you provide a build code or an account/character to import?

Problem is i have absolutely no idea which one crashed it, i had a Tuna Impending Doom open (i think this one? https://pobb.in/SJ6n1gofwGLP ) and my own but with some random stuff added to it (and i have no idea how to pass a PoB link without being able to open PoB honestly)

**Comment by Peechey** [comment]
I checked a few different versions and haven't had a problem when importing your character. Are you not able to open a new build and then import? Even if the old build is messed up POB should load the buildlist, unless you mean the landing page is what is throwing the error?

**Comment by Crotog** [comment]
Same problem, new Laptop with a fresh download. Haven't entered any character builds.

**Comment by Daiug** [comment]
> I checked a few different versions and haven't had a problem when importing your character. Are you not able to open a new build and then import? Even if the old build is messed up POB should load the buildlist, unless you mean the landing page is what is throwing the error?
> 
> If so, it could be that something messed up during the update. You can find the latest release here for a clean reinstall: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases

The crash was happening the second i opened pob, so couldn't really do anything. Refreshing just popped the error and pressing Esc gave me a black screen.

A clean reinstall at least worked! Thanks again for the swift answer <3

**Comment by Crotog** [comment]
> Same problem, new Laptop with a fresh download. Haven't entered any character builds.

OK, mine was the OneDrive issue that was stated last week as a problem. After removing Onedrive (I don't use it) PoB is working fine with a fresh install.
