### ISSUE TITLE
Raise Spiders - Not able to include in Full DPS (new bug, 2.33.1+)

### ISSUE THREAD

**Issue by Cornholio777** [PathOfBuildingCommunity/PathOfBuilding#6516]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Include Raise Spiders in Full DPS should work.

### How does Path of Building behave?

When I click "Include in Full DPS" check mark with Raise Spiders, the skill from the Arakaali's Fang, Fiend Dagger, it instantly removes it again.

### How to reproduce the issue

Run version 2.33.1 (where I first noticed the issue) or 2.33.2, import the build below.
Before 2.33.1 Raise Spiders was included in Full DPS, now i'm not able to as it deselects it instantly.

### Character build code

```shell
https://pobb.in/HqZBjCT9NIpt
```

### Screenshots

https://pasteboard.co/vZZYf1HNS1pq.png

**Comment by LocalIdentity** [comment]
Fixed in 2.33.3
