### ISSUE TITLE
Incorrect calculation of the trigger rate for Mjolner

### ISSUE THREAD

**Issue by DragonRU1** [PathOfBuildingCommunity/PathOfBuilding#6519]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

 Amulets which I will mention give same trigger rate

### What is the value from the calculation in Path of Building?

2 very similar amulets (neither of them affects attack speed) gives very different trigger rate for Mjolner.

This issue could be related to issue #6492  - seems they appeared in the same version

### How to reproduce the issue

1. Select Manabond as main skill - you will see correct trigger rate (3.79)
2. Replace Rune Scarab to Hypnotic Scarab
3. You will see incorrect trigger rate (2.22)

### Character build code

```shell
https://pobb.in/HNkuWJD2jHgZ
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/128693297/8302fa8d-62f2-44fe-9471-78395304087a)

**Comment by shakesx** [comment]
One of the necks causes you to lose 1% hit chance

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/34324732/c41eb8cd-710c-4a55-815d-bbaa338a2ff8)

**Comment by DragonRU1** [comment]
Yes - but it should not affect trigger rate that much. Attacks still go with same frequency, and 1% chance to miss does not affect if they above cap or below it.

Moreover, if you remove jewel from socket #6 (Foe Bliss), attack rate gets reduced, but skill trigger rate sill will be calculated incorrectly

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/128693297/cdb28ddb-f201-4395-b84a-261f66a2add3)

In this scenario it should be 3.62, not 2.67

**Comment by Paliak** [comment]
There's very likely something wrong with the way cooldowns and source rate interact currently for triggers. I will fix as soon as i can.

**Comment by Paliak** [comment]
Mostly fixed by #6530 . The old simulation may still have some issues as mentioned in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6492 and https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6481 but should at least be _more_ correct.
