### ISSUE TITLE
Trigger Rate Bug

### ISSUE THREAD

**Issue by nadirulusoy** [PathOfBuildingCommunity/PathOfBuilding#6520]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

27.6m

### What is the value from the calculation in Path of Building?

14.8m

### How to reproduce the issue

After last patch pob calculating trigger rate cooldown recovery rate and attack speed calculation. 

### Character build code

```shell
https://pobb.in/rqsI_O3uFmSP
```

**Comment by Paliak** [comment]
Mostly fixed by reverting to the old simulation function. The old function may not be entirely correct either as mentioned in #6492 and #6481 but should at least be _more_ correct.
