### ISSUE TITLE
Aspect of the spider is lowering EHP

### ISSUE THREAD

**Issue by Tkap1** [PathOfBuildingCommunity/PathOfBuilding#6527]
When hovering over the item, PoB says it will increase EHP, but equipping the item makes EHP go down.

Build: https://pastebin.com/5w1jGqS2

How to reproduce: Take off helmet -> Hover over it before equipping -> See that it shows an increase in EHP -> Equip it -> EHP goes down

**Comment by Wires77** [comment]
I don't have time to fully investigate this right now, but on first glance it looks like it's because Aspect of the Spider is supported by Arrogance, which halves the majority of your hit pool.

**Comment by Tkap1** [comment]
Oh, that makes sense, my bad. It's not my build so I didn't think to look at the gems. It is still kind of confusing that PoB shows an increase of EHP before equipping, not taking into account the gems inside the helm, but I don't know if that something that should/can be fixed. Thanks!
