### ISSUE TITLE
Searing Touch level req is wrong.

### ISSUE THREAD

**Issue by weirfish** [PathOfBuildingCommunity/PathOfBuilding#653]
The Searing Touch's level requirement is listed at 60, but is 62 (same as the base, Lathi) ingame. 

Lathi appears to have the correct level req.

**Comment by ppoelzl** [comment]
Thank you for your report. I've fixed this in #654 and it will be corrected with the next update.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
