### ISSUE TITLE
Slider to item value behaviour for tier 2 of "Attacks/Spells have +X% to Critical Strike Chance" 

### ISSUE THREAD

**Issue by eXeAmarantha** [PathOfBuildingCommunity/PathOfBuilding#6548]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

The slider scales from 0.5% to 2% left to right, with a 0.1% bump when going up a tier. 
The exact same value shown on the slider is applied to the item.

### How does Path of Building behave?

In the latest version, while the sliders still scale the same way, for tier 2 of the mod (1.1% to 1.5%), the value applied to the item is the slider value in reverse.
As in +1.47% to critical strike chance on the item when slider shows 1.13%, 1.17% on the item when the slider shows 1.43% and so on.

### How to reproduce the issue

1. Go to the "Items" tab and click "Craft"
2. Select any body armour base and add Shaper or Elder influence
3. Add the suffix "Spells have +X% to Critical Strike Chance" or "Attacks have +X% to Critical Strike Chance"
4. Position the slider in tier 2 (between 1.1 and 1.5%) and compare the slider value to the value applied to the item as you move the slider to the left or the right

### Character build code

```shell
https://pobb.in/hFH-oo1FOtYu
```

### Screenshots

https://cdn.discordapp.com/attachments/1130651000320040991/1146074526879334491/image.png

**Comment by Lilylicious** [comment]
This is caused by #6056 which inverts the sliders for mods that are discontinuous between tiers, which at the time was believed to only be "reduced" modifiers on flasks that get better the lower they are. In the case of the shaper body armour crit suffix, it goes from 1% at max T3 to 1.1% at max T2, with a step of 0.01 inside tiers.
