### ISSUE TITLE
Chance to Ignite

### ISSUE THREAD

**Issue by Meatwookie** [PathOfBuildingCommunity/PathOfBuilding#656]
Hey,

Something with the Chance to Ignite on non Critical Strikes seems to not check out.
Doesnt matter how much increased Chance to Ignite I've got, its always 0% on noncrit
![image](https://user-images.githubusercontent.com/23042090/77475711-81d9e500-6e19-11ea-9d86-649b875a697f.png)

even tho it should be way above 100%.

**Comment by Regisle** [comment]
Can you give me a Pastebin of the build so I can try and figure it out?

**Comment by Meatwookie** [comment]
https://pastebin.com/y3cdN4qj

even tho its not the exact pob,

same problem

**Comment by Meatwookie** [comment]
ok, i found the issue,
it is when ignite calculation mode is set to critical damage
