### ISSUE TITLE
Copying an Item into PoB results in wrong values

### ISSUE THREAD

**Issue by RobbidyRob94** [PathOfBuildingCommunity/PathOfBuilding#6563]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When copying an item from in-game using CTRL+C and pasting it into the item screen in PoB, the item should appear with proper values.

### How does Path of Building behave?

Instead of having the proper values of the item, it adds the item with the value ranges seemingly added into the actual value, resulting in thousands of % values.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/128827296/626b1476-6494-400c-8932-88323f0cfee9)

manually removing the stat ranges through the item edit fixes this
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/128827296/fcb4e5c0-ba61-4215-8357-97fabd722531)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/128827296/f6b91dc1-9b03-43a3-bcb4-e63908b94407)

### How to reproduce the issue

1. Copy an item from PoE with CTRL+C
2. Paste the item into PoB item section

### Character build code

```shell
https://pobb.in/Ds92S6vjxZMY
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/128827296/f9ee618f-6099-448e-a210-ed3a8c5ea3a9)

**Comment by RobbidyRob94** [comment]
An extra note: I've completely swapped the CTRL and ALT behaviour inside of poe, as holding down ALT to switch the hotkey bar is much more comfortable for me, maybe the issue lies there somewhere - as copying an item with CTRL+C also opens the detailed mod info on the item at the same time.

**Comment by LocalIdentity** [comment]
PoB does not support the advanced copy-paste from the game, ctrl + alt + c is the ingame hotkey for it. You'll need to find a way to copy an item without pressing alt

**Comment by LocalIdentity** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2684
