### ISSUE TITLE
Snipe isn't supported

### ISSUE THREAD

**Issue by Supamiu** [PathOfBuildingCommunity/PathOfBuilding#657]
When adding the unique "Assailum, SInner Tricorne", the skill "Snipe" isn't added to the possible main skills and is not added as a skill at all.

I tried to check the skill list to see if I could add it as a skill itself, but it's not possible neither.

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1

**Comment by bhmorse** [comment]
I believe the calculation for ailments is wrong, and uses 165% more instead of 120% more

**Comment by Quotae** [comment]
@bhmorse I'm the one that implemented Snipe and nope, it's using 120% more per stage for ailments. Here's what it looks like for me on a bleed build:
![image](https://user-images.githubusercontent.com/39030429/79804211-32f47200-8329-11ea-81f1-d59b7aae7c71.png)

And on an ignite build:
![image](https://user-images.githubusercontent.com/39030429/79804277-5a4b3f00-8329-11ea-8d6a-240e9258381d.png)

**Comment by bhmorse** [comment]
ah ok interesting, I missed that. Sorry
