### ISSUE TITLE
ES from belt being miscalculated

### ISSUE THREAD

**Issue by dubudevs** [PathOfBuildingCommunity/PathOfBuilding#6579]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Without a belt equipped I have 4722 ES and this matches what is in PoB, and before getting this belt ES calculations were accurate on this character. However, with the belt on in game I have 5296 ES and PoB says I should have 5457. I have tried to find the cause of this but I can't so I think it might be a bug, or I'm blind. 

### What is the value from the calculation in Path of Building?

No belt: 4722 in game and in PoB
With belt PoB: 5457 ES
With belt in game: 5296 ES

### How to reproduce the issue

Remove belt, check ES, add belt, check ES.

### Character build code

```shell
https://pobb.in/7G-u3bdzXvzj
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91028108/0713877b-4f8f-4d5c-b594-3daa9e54af8f)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91028108/a335238d-6e5f-43e5-a733-bdbcc12b5022)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91028108/0a0b9d35-87a2-4232-aa90-4b9c7b741fb3)

**Comment by Wires77** [comment]
Can you check the values in game now?  This was fixed in the latest game patch

**Comment by dubudevs** [comment]
The numbers in game match what is shown in PoB, thanks GGG
