### ISSUE TITLE
Error with The Front Line/Veteran's Awareness

### ISSUE THREAD

**Issue by Dobeq** [PathOfBuildingCommunity/PathOfBuilding#658]
![image](https://user-images.githubusercontent.com/8127648/77488739-703e1080-6e0c-11ea-8ef9-538c15876228.png)

This error appears when I hover over any elemental resistance in the calcs tab when Veteran's Awareness is allocated and a guard skill is active.

PoB: https://pastebin.com/9BmzkqPL

**Comment by LocalIdentity** [comment]
Duplicate issue of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/728. Will be fixed in the next update
