### ISSUE TITLE
Add 100% shock avoidance when using tempest shield

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#6582]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Currently, Arctic Armour gives 100% freeze avoidance:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7839686/be4590bb-f7ca-4ed0-bb55-3fd3958f06ae)

Tempest Shield has the exact same wording (`Buff grants immunity to X`), however its avoidance does not show up in the calcs tab.

### Describe the solution you'd like

When using Tempest Shield, pob should show your build having 100% shock avoidance.

### Additional context

pob link: https://pobb.in/j2pjs9pgL4MN

**Comment by Lilylicious** [comment]
While the reported issue is incorrect, it does highlight a bug. Arctic Armour should not give freeze avoid, but rather freeze immunity. A while back a clarification was made to all ailments that immunity is not the same as 100% avoidance.

**Comment by moxaj** [comment]
I see, but still, I'd expect those buffs to show up in the calcs tab, in whatever form.

**Comment by LocalIdentity** [comment]
The bug issue is correct and Artic Armour does need to be changed to show Immunty instead of Avoid. I'll put up a fix for both issues in a min

**Comment by Paliak** [comment]
Fixed by #6584
