### ISSUE TITLE
Requesting a node power list for all possible notables for megalomaniac

### ISSUE THREAD

**Issue by zapcser** [PathOfBuildingCommunity/PathOfBuilding#6596]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

The related problem is the performance of different notables of the megalomaniac is not shown when selecting them.

### Describe the solution you'd like

I would like to have a node power list (like that in passive trees, for different perspectives) of all possible nodes for megalomaniac.

### Describe alternatives you've considered

or, like crafting a rare cluster , the performance of a prefix(or suffix) is shown when crafting a cluster in POB

**Comment by LocalIdentity** [comment]
The power report already has the option for you to tick "Show Clusters", which shows all the notables that can show up on cluster jewels / megalomaniacs
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31035929/c7245796-bc83-4ef8-9a97-5bf57f4b202d)
