### ISSUE TITLE
Error on "trade on items / stat weight calc"

### ISSUE THREAD

**Issue by Fleymour** [PathOfBuildingCommunity/PathOfBuilding#6600]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![Path_of_Building_JaKxuVZbbD](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/74535695/93b0746b-1cbe-4fe7-a4a3-e14083820877)

### What are your system specifications and configuration?

^^

### How to reproduce the issue

hey ill found this feature to search for gear upgrades and i really liked it (besides it doesnt can fix my resistances). and first ill used it 3 days ago / friday  ill instant found a 100k+´dps upgrade for 50c .. and i was addicted to this feature. 
next day ill even told a friend about it - i really liked it. 

the weekend went on ill replaced my "Normal" helm with a RF elder helm with 3 extra effect.. and since then (sunday) this feature is perma endless stuck in the weight calculations and throwing the error.
even swapping out the helm doesnt matter. not touching any options in this feature wont help.

### Character build code

```shell
https://pobb.in/yjXSPX_U1jqK
```

**Comment by Fleymour** [comment]
> Does it crashes when you press `Trade for these items`, `Find best` or someplace else?

no these both are fine...  it kinda "endless" run "calculating mod weights"  until error pops up.

**Comment by LocalIdentity** [comment]
I'm 99% sure your PoeSessid is out of date and needs to be updated

**Comment by Fleymour** [comment]
> 

oh yeah.. that seems like the reason !
