### ISSUE TITLE
Doomfletch's Prism wrong stats

### ISSUE THREAD

**Issue by Severinus3** [PathOfBuildingCommunity/PathOfBuilding#661]
Doomfletch's Prism still has Increased critical strike chance in the "current version", even though the version of the bow with crit is legacy now. Current version doesn't actually have inc crit chance

**Comment by ppoelzl** [comment]
Thank you for your report. This will be fixed in our next update. For now, you can do what I did in #633 to fix this issue in your own installation.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
