### ISSUE TITLE
Cannot Allocate Passives inside Thread of Hope

### ISSUE THREAD

**Issue by mosentok** [PathOfBuildingCommunity/PathOfBuilding#662]
this very well could be user error but i've googled and googled and i cannot figure out why this does not work for seemingly only me on the internet.

expected: clicking a notable within the thread of hope radius allocates it without pathing.

actual: clicking a notable within the thread of hope radius allocates it with pathing.

here are screenshots of the tree before and after simply clicking swift venoms, which should be in the very large ring, right? but instead of allocating the notable only, it paths as well: https://imgur.com/a/gBTnSLP

pob community fork version is 1.4.167.2

the first few lines of my manifest.xml are:

```
<Version number="1.4.167.2" platform="win32" branch="master"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/tree-3_7.zip" part="tree-3_7"/>
<Source url="https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/{branch}/" part="program"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/tree-3_8.zip" part="tree-3_8"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/tree-3_10.zip" part="tree-3_10"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/tree-3_9.zip" part="tree-3_9"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/" part="tree"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/runtime-win32.zip" part="runtime" platform="win32"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/tree-2_6.zip" part="tree-2_6"/>
<Source url="https://raw.githubusercontent.com/Openarl/PathOfBuilding/{branch}/tree-3_6.zip" part="tree-3_6"/>
```

**Comment by ppoelzl** [comment]
It seems like you do not have any of the fork's features. Even your screenshots should look different. Have you modified the correct manifest file? See https://github.com/PathOfBuildingCommunity/PathOfBuilding/wiki/Installing-this-Fork. The manifest file itself looks good.

**Comment by mosentok** [comment]
figured it out: removing thread of hope and adding it back into the build fixed it. the ring looks and behaves as expected. i guess something was out of whack for one reason or another. i should have tried that first before opening an issue. i added a final image to the imgur link to show this.
