### ISSUE TITLE
Error message when selecting certain flask affixes

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#6620]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I would expect crafting flasks to work as before, nothing special.

### How does Path of Building behave?

pob displays error messages when selecting certain flask affixes, see the reproduction below.

### How to reproduce the issue

1. Initiate crafting a new flask: 
    ![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7839686/0a9cd40d-b1e0-473f-9c56-94a96080c3cf)
2. Select the prefix `Gain # Charges when you are Hit by an Enemy`
3. Observe the following error message:
    ![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7839686/6cb17749-df61-4896-ae77-a98f39bf0aa9)
4. Another issue: select the suffix `#% less Duration/Immunity to Shock during Effect`
5. Observe how the roll is at max value within the range, but the slider isn't aligned:
    ![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7839686/a7e84d63-e28a-49a7-a382-562d0bc717cb)

**Comment by Lilylicious** [comment]
I've made a fix for the first reported issue, but I can't replicate the less duration mod not being flipped as it should. What version of PoB is that happening in?

**Comment by moxaj** [comment]
2.33.5 (Beta)
