### ISSUE TITLE
I would like to know the "Stat Weight Multipliers" separator.

### ISSUE THREAD

**Issue by CryAngel1970** [PathOfBuildingCommunity/PathOfBuilding#6625]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I am localizing PathOfBuildingCommunity using PoeCharm.
![snap0035](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/4d26c2b6-87a9-4055-9ae6-d8db09a6d3a1)

Common English sentences are If you write "English" or "Local language", it will be translated.
We succeeded in localizing the Jewel Node drop-down menu you told us last time.

"{0} : Full DPS","{0} 전체 DPS"

### Describe the solution you'd like

Full DPS,Combined DPS,Hit DPS... localization

### Describe alternatives you've considered

Essence Menu Localization Successful
![snap0036](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/4b950e2d-3f48-4fc7-8bf7-036a32618c08)

**Comment by Wires77** [comment]
Here's how that label is constructed:

```"0      :  "..stat.label```

That `label` attribute comes from here https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/5ab9a7b87353c202ed9fb2b0a582d9395cc39a2e/src/Modules/Data.lua#L85

**Comment by CryAngel1970** [comment]
It's been resolved. Thank you very much for your quick reply.
