### ISSUE TITLE
Support Gem level calculation wrong for CoC forbidden rite

### ISSUE THREAD

**Issue by ConstVolatile** [PathOfBuildingCommunity/PathOfBuilding#6627]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

For this setup: https://pobb.in/u/MrJimo/V3xQn9XpCgJz
I should get +2 level to my main support gems e.g awaken CoC, pcoc with the skin of lords.

### What is the value from the calculation in Path of Building?

However, pob shows +5 to these support gems, I assume that it mis-applied Dragonfang’s +3 to all forbidden rite gems modifier to its support gems as well. 

### Character build code

```shell
https://pobb.in/u/MrJimo/V3xQn9XpCgJz
```

**Comment by Paliak** [comment]
CoC is getting +2 from body and +3 from crit mastery same with power charge on crit.
