### ISSUE TITLE
Timeless Jewel Error

### ISSUE THREAD

**Issue by wuzubpips** [PathOfBuildingCommunity/PathOfBuilding#6638]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When putting a Timeless Jewel into the passive tree, it should not display any errors.

### How does Path of Building behave?

Every attempt to put a Timeless Jewel into my tree leads to an error, the error is able to be closed. The Jewel does not get put into the tree, however the entire tree is now "bricked", allowing me to allocate passive skills unlinked to my tree.
![Path_of_Building_1b0aDHc9aZ](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49508408/9956676d-6910-48af-bf55-3f9678db8aa1)
![Path_of_Building_4uVnOguEFl](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49508408/29b613c1-0fb8-4226-a736-4ea9d98267e8)

### How to reproduce the issue

1. Put a timeless jewel into a jewel socket
2. Error

### Character build code

```shell
https://pobb.in/MM3Cx1X6yxNg
```

### Screenshots

![Path_of_Building_1b0aDHc9aZ](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49508408/c6f8a75e-3a31-48f4-b86e-8f97275790db)
![Path_of_Building_4uVnOguEFl](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49508408/73474e3e-37b5-4f41-ae15-20f2eeda5083)

**Comment by LocalIdentity** [comment]
Are you on the beta branch of PoB atm or the normal branch? Take a screenshot of this and reply to this message with it
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31035929/965f7d40-16c6-4b26-8068-be48eba46443)

**Comment by LocalIdentity** [comment]
Also, press Ctrl + ` and take a screenshot of the console, it should show some info

**Comment by wuzubpips** [comment]
![Path_of_Building_3J9XBEKx9D](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49508408/b7051ef5-f063-4a10-8a80-d025dbd33a62)
![Path_of_Building_jYCcldFjm6](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49508408/a2f8e49a-6396-408f-a568-e0fe16a8ef40)

**Comment by LocalIdentity** [comment]
If you're using the Beta branch, do not expect it to be stable. Revert to the regular branch for now and see if the issue resolves itself

**Comment by wuzubpips** [comment]
I got off the beta version, it still kept happening. I did a fresh install, it's working now. Must've been something on my side, sorry for the trouble!

**Comment by LocalIdentity** [comment]
Sounds like one of the Timeless Jewel files was corrupted or missing and reinstalling would have fixed that
