### ISSUE TITLE
Tattooed Keystones not being accounted for

### ISSUE THREAD

**Issue by totalnewbie99** [PathOfBuildingCommunity/PathOfBuilding#6658]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Tattooed keystones visually appear correct but functionally still use the untattooed keystone.

### What is the behaviour in Path of Building?

For example, perfect agony gives -30 less damage with hits.

Importing a character with that keystone tattooed to something else visually appears correct (i.e. the tattooed keystone is displayed). However, allocating the keystone still gives -30% with hits from the underlying perfect agony keystone.

### How to reproduce the issue

Tattoo a keystone (e.g. perfect agony)
Import character
Allocate keystone
See -30 more modifier on calc page which is attributed to the new keystone name.

### Character build code

```shell
https://pobb.in/LdcieJrlzTgl
```

**Comment by LocalIdentity** [comment]
Fixed on dev, and will be included in the next update
