### ISSUE TITLE
Find a way to migrate new and existing users to this repository

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#666]
Changes to the upstream repository have the potential to break our own update process, so we need to have independent endpoints in `manifest.xml` under the PathOfBuildingCommunity org.
#536 is a good candidate for accomplishing this, but it still needs testing.
Any valid solution will have to:
* Migrate from LocalIdentity endpoint to PathOfBuildingCommunity endpoint
* Change all endpoints to PathOfBuildingCommunity
* Handle manifests already updated to the PathOfBuildingCommunity endpoint

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
