### ISSUE TITLE
Magic cluster jewels do not show allocatable nodes in tree

### ISSUE THREAD

**Issue by RhapsodySL** [PathOfBuildingCommunity/PathOfBuilding#6668]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Magic cluster jewels work as expected in-game, and produce allocatable nodes.

### What is the behaviour in Path of Building?

Magic cluster jewels do not produce allocatable nodes in the tree. 

An example cluster jewel with this behavior can be seen here:

> Small Cluster Jewel
> Unique ID: 78f2d7754d34c074b289f9f03812bc4cdd79afc8321a500c6f90fbf38826dcfb
> Item Level: 83
> LevelReq: 62
> Implicits: 2
> {crafted}Adds 3 Passive Skills
> {crafted}Added Small Passive Skills grant: 6% increased Mana Reservation Efficiency of Skills
> Added Small Passive Skills also grant: +5 to All Attributes
> Added Small Passive Skills also grant: +13 to Maximum Energy Shield

Manually setting the cluster jewel to Rare produces the expected behavior, and the cluster jewel works as normal.

### How to reproduce the issue

1. Import a magic cluster jewel from the example above or create your own
2. Allocate to a cluster jewel socket in the tree
3. Note that it does not produce any allocatable nodes

### Character build code

```shell
https://pobb.in/qeCUoLgX00dE
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8369578/b9ba9a3c-63fa-4c8b-9880-e066210d32f6)

**Comment by Wires77** [comment]
What version of PoB are you using?  I'm not able to replicate this using the methods described.  Do you have a character to import instead?

**Comment by RhapsodySL** [comment]
> What version of PoB are you using? I'm not able to replicate this using the methods described. Do you have a character to import instead?

I'm using version 2.33.5 (Beta). An import link is included in the initial post, but if you're referring to a character name, you can import the character with the account name "Rhapsodical" and the character name "Aurabot_Sugardaddy".

**Comment by Wires77** [comment]
That shows the issue, importing by item or pobb.in link both work fine

**Comment by LocalIdentity** [comment]
Already fixed on dev by #6655
