### ISSUE TITLE
Can't import build with new patch (v2.34.0)

### ISSUE THREAD

**Issue by tylersockington** [PathOfBuildingCommunity/PathOfBuilding#6679]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/144697056/aac6bb70-6add-43fd-af74-181608cfe77e)

### What are your system specifications and configuration?

Operating system: Windows 10
Graphics: AMD Radeon RX 5700 XT
Processor: AMD Ryzen 9 3900X
RAM: 16gb/3200MHz
Default installation

### How to reproduce the issue

Try to import this build: https://pobb.in/DGb0AirWLZae

I had that build saved and exported it with version 2.33.0. However, now that I've updated to v2.34.0, I can't open the build or import the build.

### Character build code

```shell
https://pobb.in/DGb0AirWLZae
```

**Comment by LocalIdentity** [comment]
Fixed by #6677
