### ISSUE TITLE
Critical failure tied to Saviour reflections

### ISSUE THREAD

**Issue by FramFramson** [PathOfBuildingCommunity/PathOfBuilding#6680]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

The Saviour unique sword gives your character the Reflection skill. As the skill produces two "Reflections" of your character I normally put '2' in the "number of reflections" checkbox and add the enabled skill to FullDPS.

### How does Path of Building behave?

Prior to the most recent update, 2.34.0, I was encountering a non-fatal error where any changes made anywhere which altered FullDPS would disable the Reflection skill granted by the Saviour. This meant that any time I wanted to test any changes to my DPS, I had to re-enable the Reflections. Annoying but not fatal. 

Since update, 2.34.0 however, old saved builds which had Reflection skill enabled cannot be loaded at all. If I try to import the same character as a fresh PoB build, that file immediately locks up PoB as soon as I allocate 2 Reflections or add Reflections (even just 1) to FullDPS. See attached images for error codes. 

On attempting to load an older saved build: 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/101145521/2ea073eb-e56b-4134-8611-4e67048cd8fa)

On attempting to enable Reflection skill on a fresh build:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/101145521/2ca53687-d258-4811-8e68-62dfb80b1eff)

EDIT: Oh, and please don't confuse the "Commandment of Reflection" skill (provided by the glove Labyrinth enchant) with the "Reflection" skill (provided by The Saviour). Luckily the shiny new item-slot icons for skillgroups will probably prevent this. :) 

### How to reproduce the issue

1) Select any melee skill which can work with The Saviour as a main skill (I am using Cyclone, just in case it does not occur with all melee skills)
2) Equip your character with a main hand 1H Melee weapon of some sort (I am using a crafted Jeweled Foil with a Crucible Tree)
3) Equip The Saviour unique sword as your offhand weapon
4) Attempt to enable or use the Saviour's Reflection skill in your FullDPS in any way. 

Unfortunately, I cannot attach the build's saved .xml file here (I also tried attaching it inside a .zip) for you to place in your PoB "builds" folder and attempt to load it in PoB and I cannot load the build to generate a sharing (pastebin, etc.) code. So I'm unsure of how you can duplicate the "loading existing save" issue. Please let me know if there's an alternate way for me to share a raw saved .xml build file if you do need this.

**Comment by LocalIdentity** [comment]
Fixed by #6677
