### ISSUE TITLE
Doomblast no longer allows overlapping casts as an option after update

### ISSUE THREAD

**Issue by Zamichel** [PathOfBuildingCommunity/PathOfBuilding#6683]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Doomblast overlaps at least 2 times with appropriate gems, and prior to the update there was an ability to set the overlaps in POB for DPS calculation. 

### What is the behaviour in Path of Building?

POB doesn't have the option at all to select it anymore

### How to reproduce the issue

Load temporal chains linked to impending doom in POB and check both calculations page and main skill drop downs.

### Character build code

```shell
https://pastebin.com/Hhvaz6Up
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8632142/26d6db17-9846-4ef2-9769-46ca6db60a76)

**Comment by LocalIdentity** [comment]
It is now on the configs tab
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31035929/04cc3f1c-8baf-4063-ba7f-55d8b4d22bba)

**Comment by Zamichel** [comment]
Durp. Thank you!
