### ISSUE TITLE
Open items with selected stats on Poe/trade 

### ISSUE THREAD

**Issue by gabenzxc** [PathOfBuildingCommunity/PathOfBuilding#6684]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Hello. I tried several times to find a function where I can quickly find an item in a trade with the same nodes, but all of them were not successful. Perhaps there are some plugins or something similar?
This would be the best feature to make life easier.

### Describe the solution you'd like

Add a function like in awakened poe trade where you can select the necessary item nodes and get a link to poe/trade.

**Comment by LocalIdentity** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6643

**Comment by gabenzxc** [comment]
> Fixed by #6643
Perhaps you didn't understand me. I want to get a pre-exchange link with nodes for https://www.pathofexile.com/trade/search/. This would help to quickly find similar things from other people's Pobs.

**Comment by LocalIdentity** [comment]
That is what the PR I linked does. It generates a trade search fro the same mods on an item in PoB

**Comment by gabenzxc** [comment]
> That is what the PR I linked does. It generates a trade search for the same mods on an item in PoB

ohh really, I got it. Now need realize how install this xD
