### ISSUE TITLE
Divergent arcane cloak buff effect reduces damage instead of increasing it

### ISSUE THREAD

**Issue by Crazy-KSK** [PathOfBuildingCommunity/PathOfBuilding#6688]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

divergent arcane cloak buff effect should increase the damage granted by arcane cloak

### What is the value from the calculation in Path of Building?

divergent arcane cloak with more then 2% quality reduces damage greatly instead of increasing it

### How to reproduce the issue

change arcane cloak from default to divergent and observe a reduction in damage

### Character build code

```shell
https://pobb.in/uW97FHR2LA7u
```

**Comment by Peechey** [comment]
More info, the added lightning is changing, +0.15 per mana -> +0.1 per mana

Default: 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/ed2bdae5-ff2a-45fd-b98d-59bbb84ddf4b)

Divergent:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/78d88c75-9e0e-497e-aa42-4a4aaffdcc49)
