### ISSUE TITLE
Conditional Accuracy doesn't work on Undeniable

### ISSUE THREAD

**Issue by paruri99** [PathOfBuildingCommunity/PathOfBuilding#6690]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

"40% increased Accuracy Rating against Unique Monsters" and "40% increased Accuracy Rating at Close Range" don't increase attack speed while using "Undeniable" by forbidden flame/flesh

### What is the behaviour in Path of Building?

"40% increased Accuracy Rating against Unique Monsters" and "40% increased Accuracy Rating at Close Range" increase attack speed while using "Undeniable" by forbidden flame/flesh

### How to reproduce the issue

You can easily check conditional accuracy increase attack speed with Undeiniabl

This is how I tested in game if conditional accuracy increase attack speed or not

1. Use Boneshatter
2. Make Boneshatter dmg 0 (i.e. I used Replica Alberon's Warpath and Brutality Support)
3. Check maximum trauma stack when using conditional accuracy and not using

### Character build code

```shell
https://pobb.in/HV7o2plB3gPM
```

**Comment by Wires77** [comment]
Where do those mods come from?  I was unable to find either of them on trade or on the wiki.  I put both in the custom modifier box of PoB, however.  The first is unsupported (the text is red), and the second one is supported, you just have to make sure to check the "Is the enemy at Close Range?" checkbox.

**Comment by paruri99** [comment]
> Where do those mods come from? I was unable to find either of them on trade or on the wiki. I put both in the custom modifier box of PoB, however. The first is unsupported (the text is red), and the second one is supported, you just have to make sure to check the "Is the enemy at Close Range?" checkbox.

**Comment by paruri99** [comment]
> Where do those mods come from? I was unable to find either of them on trade or on the wiki. I put both in the custom modifier box of PoB, however. The first is unsupported (the text is red), and the second one is supported, you just have to make sure to check the "Is the enemy at Close Range?" checkbox.

Both comes from "Accuracy Mastery" and what I meant was if those mods increase dps(yes I check ed at close range) but in game don't increase dps
https://pobb.in/q3HXmwHIYz4F
reattached pob allocating those modes

**Comment by Wires77** [comment]
How did you test in game?  PoE's tooltip doesn't account for most conditional modifiers because it doesn't know details about the situation.  In this case it downy know what kind of monster you're attacking or what distance you are from it

**Comment by paruri99** [comment]
> How did you test in game? PoE's tooltip doesn't account for most conditional modifiers because it doesn't know details about the situation. In this case it downy know what kind of monster you're attacking or what distance you are from it

I tested in The Desecrated Chambers, Act 10 with Avarius. I used boneshatter-brutality, and replica Alberon to make my dmg 0. If those mastery nodes increase attack speed, there would be change of maximum trauma stack. But there was no difference in trauma stack whether using those nodes or not. Of course I attacked the boss close enough. I changed build now so I can't provide videos but I think you can easily set up test situation with jugg character

**Comment by Wires77** [comment]
Honestly that sounds like a game bug to me.  There's no reason that shouldn't work as far as I can tell.

**Comment by paruri99** [comment]
> Honestly that sounds like a game bug to me. There's no reason that shouldn't work as far as I can tell.

I don't know it's intended or just a bug. Or maybe something was wrong with my test. I hope you guys test to crosscheck.
