### ISSUE TITLE
When I open POB, application gives error message

### ISSUE THREAD

**Issue by BahBahPooqan** [PathOfBuildingCommunity/PathOfBuilding#6703]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/145220311/900bc08c-e24d-4402-beef-ca875bdc1757)
![2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/145220311/0b32a86b-1ef7-4bd5-99c9-f320722c0daf)

### What are your system specifications and configuration?

windows 10, clean, just installed
nvidia geforce gtx 1080ti driver 537.34

### How to reproduce the issue

When I open POB, application gives error message

**Comment by Wires77** [comment]
Open your Documents/Path of Building/Settings.xml in explorer, then relaunch PoB

**Comment by BahBahPooqan** [comment]
Thank you very much : ) , it works

  
>Воскресенье, 17 сентября 2023, 0:37 +05:00 от Wires77 ***@***.***>:
> 
> 
>Open your Documents/Path of Building/Settings.xml in explorer, then relaunch PoB
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <PathOfBuildingCommunity/PathOfBuilding/issues/6703/1722300824 @ github . com> 
 
 
Руслан Рахматуллин
