### ISSUE TITLE
Choose League for Find Timeless Jewel feature

### ISSUE THREAD

**Issue by TuckV** [PathOfBuildingCommunity/PathOfBuilding#6706]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

It would be useful to be able to choose the league to search in when using the Find Timeless Jewel feature, but it currently only searches in the current softcore temporary league.

### Describe the solution you'd like

A dropdown or possibly copying the league selected in the "Trade for these items" feature would be useful.

**Comment by Peechey** [comment]
Fixed by #7028
