### ISSUE TITLE
More "Limit Node Distance" values (Anoints)

### ISSUE THREAD

**Issue by Fraytrain** [PathOfBuildingCommunity/PathOfBuilding#6714]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

As the Node Power is a very laggy feature that is used a lot to round out a build. It is so laggy I am using it right now to find a good amulet anointment for my build. 

### Describe the solution you'd like

I would like to suggest it being expanded to include an "Anoint only" mode so it completely bypasses keystones, small passives, jewel slots, ascendancy nodes and cluster jewel notables.

### Describe alternatives you've considered

Alternatively the Node Power search could be built up from an order of operation:
First Anoints
Second 5 distance
Third 10 distance
Fourth 15 distance

That way you can use the table ahead of time without the need to wait until everything is loaded if you so choose.

### Additional context

It has been 10 minutes now and I am still waiting for the result of Eff. Maximum Hit Taken result. Just for context.

**Comment by LocalIdentity** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31035929/bc8741c3-588f-4747-befc-b05880f0ca4f)
Use the anoint button on your amulet then sort the list there
