### ISSUE TITLE
Flame Exarch's Implicit & Utula's Hunger armor 

### ISSUE THREAD

**Issue by DEdaso** [PathOfBuildingCommunity/PathOfBuilding#6715]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [ ] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In the game, when I use a helmet with Flame Exarch's Implicit ((7-8)% of Physical Damage taken Recouped as Life), the unique Utula's Hunger armor does not stop giving an increase in health. In the game I have 6150 HP.

### What is the value from the calculation in Path of Building?

In Path of Building, my character's health is 3500 HP.

### Character build code

```shell
https://pobb.in/iGM2Y9BIlo4o
```

**Comment by ChrisJamesHassell** [comment]
+1, same issue with this item

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/32186388/f651fdd2-998d-455c-a9dd-f3ed8cdda2c3)
