### ISSUE TITLE
Error While Trying to put on support gems

### ISSUE THREAD

**Issue by nlahiry** [PathOfBuildingCommunity/PathOfBuilding#673]
![image](https://user-images.githubusercontent.com/14924787/77608254-aa113300-6f42-11ea-8685-7dfd6ea64284.png)

you can replicate it by importing the following pastebin 
https://pastebin.com/rBYBwWGt
and select divine ire skill and try to add a support gem after the already added ones

**Comment by LocalIdentity** [comment]
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/753
