### ISSUE TITLE
Guardian Elemental Relics not implemented

### ISSUE THREAD

**Issue by mr-september** [PathOfBuildingCommunity/PathOfBuilding#6739]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Elemental Relics provide level ~27 Anger Hatred Wrath auras

### What is the behaviour in Path of Building?

Doesn't seem to exist at all?

### Character build code

```shell
https://pobb.in/cBIjK8HgZfeu
```

**Comment by Regisle** [comment]
They are technically using the auras correctly, including scaling them, but the auras are never applied becouse we dont apply the auras form minions
![image](https://cdn.discordapp.com/attachments/676256416218218496/1155127665829883994/image.png)

Its on my list of things to fix, it just wasnt a high priority becouse its so easy to fake using party tab and I have been busy
