### ISSUE TITLE
Alchemist's Mark

### ISSUE THREAD

**Issue by MrToothless** [PathOfBuildingCommunity/PathOfBuilding#6759]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

No change.

### What is the behaviour in Path of Building?

A build with Alchemist's Mark no longer displays the caustic ground effect in the left-most panel of PoB. No amount of moving the skill around gear or links will add that line. The application also no longer includes the line when comparing gear items anywhere else either.

I assume your crash-related fix contributed here.

### How to reproduce the issue

6 link a curse with Impending Doom and add Alchemist's Mark in somewhere.

### Character build code

```shell
https://pobb.in/cCWxyT4xsUZf
```

### Screenshots

N/A

**Comment by Regisle** [comment]
The alchemists mark is no longer being applied due to curse limit, if you increase the curse limit it fixes it, or if you apply the alchemists mark first it can also fix it but then breaks the whole trigger setup for doomblast

**Comment by MrToothless** [comment]
Fiendish
