### ISSUE TITLE
Guardian's Unwavering Faith not applying life regen

### ISSUE THREAD

**Issue by snagbear** [PathOfBuildingCommunity/PathOfBuilding#677]
Guardian's passive unwavering faith doesn't look like it is applying life regen to the player and minions
(as of Ver 1.4.167.2)

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/77617037-12800480-6f83-11ea-8ff5-41a0bc4576e6.png)
seems to work, Pastebin so I can check whats wrong with yours?

**Comment by snagbear** [comment]
https://pastebin.com/Z7qVw1iK

Hmm.. not sure if it is just a visual bug but might have something to do with the new Replenishing Presence notable...? (Or maybe they do not stack and I didn't know about that..?)

**Comment by chinhodado** [comment]
This is indeed a bug. The regen from Replenishing Presence do stack with each other and with Unwavering Faith
