### ISSUE TITLE
Error on calculating Glorious Vanity Jewel Graphs

### ISSUE THREAD

**Issue by BlazesRus** [PathOfBuildingCommunity/PathOfBuilding#6773]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Should allow Glorious Vanity in name of Xibaqua to socketed without acting as if no jewel is socketed and crashing if try to load saved build with it socketed.

### How does Path of Building behave?

Error pops up if try to equip the jewel
![ErrorOnJewelEquip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/2676233/e1717b22-7c73-4e35-8dee-53c7ba8408a5)

### How to reproduce the issue

Equip Glorious Vanity in name of Xibaqua to any jewel socket

### Screenshots

![ErrorOnJewelEquip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/2676233/d8c98dcf-c0d2-4f92-bc90-6d1a467eb459)

**Comment by Regisle** [comment]
Likely your jewels are corrupted, this has happend to a few people, either reinstall PoB or go to `PathOfBuilding\src\Data\TimelessJewelData` and deletes all the Glorious Vanity files and reopen PoB, if one of those 2 does not solve your issue I will take another look

**Comment by BlazesRus** [comment]
Yep that fixed it
