### ISSUE TITLE
Skin of Loyal/Lords giving eHP with quality

### ISSUE THREAD

**Issue by ScottHK** [PathOfBuildingCommunity/PathOfBuilding#6776]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

If Skin of Lords/Loyal has 20% quality, nothing is affected as it has no defences.

### What is the value from the calculation in Path of Building?

When switching from a Skin of Loyal with 20% quality to a Skin of Lords without, I lost 7k eHP. Adding 20% quality to Skin of Lords does not change the outcome.

Skin of the Loyal:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22818442/b4fdd7f1-7aec-40d2-a42b-bbf5b6b95cb8)

Lords without Quality:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22818442/3495cdac-90d7-4958-8902-0f6c52a47f0b)

Lords with Quality:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22818442/8b7beca0-11a2-4fed-8695-e9cf19fa0705)

### How to reproduce the issue

Equip a Skin of the Loyal with 20% quality. Try to replace with a Skin of Lords without Quality.

### Character build code

```shell
https://pobb.in/rdSJIqoiNiqW
```

### Screenshots

Skin of the Loyal:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22818442/b4fdd7f1-7aec-40d2-a42b-bbf5b6b95cb8)

Lords without Quality:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22818442/3495cdac-90d7-4958-8902-0f6c52a47f0b)

Lords with Quality:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22818442/8b7beca0-11a2-4fed-8695-e9cf19fa0705)

**Comment by LocalIdentity** [comment]
The Skin of the Lords has Glancing Blows on it

**Comment by ScottHK** [comment]
I don't think you've noticed that the Skin of the Loyal is the one with the higher eHP, not the Lords.

**Comment by Regisle** [comment]
Actually glancing blows is net negative in terms of defense, especially on your build, you take more damage in total, as although it doubles your block chance it makes block 35% effective, thus your final block is only 70% as effective, paired with the fact that it wastes some of your attack block and its even lower than 70%

The reason people use glancing blows is to abuse "gain on block" eg with aegis aurora, or shaper shields with life gain on block

**Comment by ScottHK** [comment]
Then i stand corrected.  Thanks for the reply 👍
