### ISSUE TITLE
Item data parsing from clipboard is incorrect

### ISSUE THREAD

**Issue by dodspunkare** [PathOfBuildingCommunity/PathOfBuilding#678]
The parsing of item data from clipboard is incorrect.
Issues:
1. Some basetypes have their basetype data included in item data having PoB interpret it as affix lines. From my quick tests at least the following basetypes, across all rarities, are affected: Sceptres, Maces (1h and 2h), Shields, Wands. It also includes price data when copying from trade site.

2. Some Unique items have their flavour text included in item data. E.g. Atziri's Foible.

Issues are possibly related to this https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/391

**Comment by Nostrademous** [comment]
I believe this is fixed.
