### ISSUE TITLE
I want to know the separator for Searing Exarch drop-down menus and text.

### ISSUE THREAD

**Issue by CryAngel1970** [PathOfBuildingCommunity/PathOfBuilding#6784]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I am localizing PoB through PoeCharm.

![snap0047](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/f1ea9665-e8fb-415f-a27d-90b140753165)

![snap0048](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/aeef8b03-f5f9-4622-914a-9cd1556f87a5)

The dropdown in Searing Exarch seems to have a separator like Essence does, but I can't find it.

`"#% increased Global Physical Damage"," 일반 물리 피해 #% 추가"                                                                      
"While a Unique Enemy is in your Presence, (27-29)% increased Global Physical Damage","고유 적이 접근해 있는 동안, 일반 물리 피해 (27
`
                                                     
"#% increased Global Physical Damage While a Unique Enemy is in your Presence, (27-29)% increased Global Physical Damage","일반 물리 피해 #% 추가 고유 적이 접근해 있는 동안, 일반 물리 피해 (27
`

I've tried adding tabs and spaces, but I haven't found a separator yet.

Can you tell me the separator for the dropdown and text description?

### Describe the solution you'd like

Like Essence Dropdown, I want to know the separator between dropdown and text description.

### Describe alternatives you've considered

![snap0050](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/e47f445c-39ce-4f4e-9c46-ad3f76063589)
![snap0049](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/14a2a1d3-dce7-41ff-b56d-529d9a3524f9)

**Comment by Regisle** [comment]
you seem to have the mods themselves translated correctly, the group name is just based off the name of the first mod in the group it finds, with 2 modifications to it
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Classes/ItemsTab.lua#L2797
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Classes/ItemsTab.lua#L2863
otherwise they are the same as the mods

**Comment by CryAngel1970** [comment]
Thank you for your quick reply.

PoeCharm can change to your preferred local language if it matches an English sentence.
For Essence, the text that appears in the dropdown and on hover was generated as follows:
`"Deafening Essence of Dread   [+(121-135) to Armour] (Prefix)","귀를 찢는 불안의 에센스   [방어도 +(121-135)] (접두어)"`

The Jewel node's drop-down menu and mouse-over description were separated by multiple spaces.
`"Ancient Hex                                                (4-6)% increased Effect of your Curses Curse Skills have 20% increased Skill Effect Duration","고대의 사술"`


I used Searing Exarch also above two methods but failed.

And, referring to the page I just provided, I separated the drop-down menu and description with "/", but it failed.
`"#% increased Global Physical Damage/While a Unique Enemy is in your Presence, (27-29)% increased Global Physical Damage","일반 물리 피해 #% 추가/고유 적이 접근해 있는 동안, 일반 물리 피해 (27-29)% 증가"`

I would like to know the separator between the text "#% increased Global Physical Damage" shown in the dropdown and the description shown when the mouse is hovered over.

**Comment by Paliak** [comment]
Not entirely sure i understand the question but maybe this block of code could be of help? https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/3455b349339f93e8ddd0e0e17f27f6bb4b0a3d1f/src/Classes/ItemsTab.lua#L2493-L2510

**Comment by CryAngel1970** [comment]
I succeeded in localizing ESSENCE and Jewel Node.

Now I want to know the delimiter of Searing Exarch.
The essence dropdown and description were 3 spaces, while the jewel node was 49 spaces.

Searing Exarch also seems to have a separator between the drop-down menu and the description, but I couldn't find it.

Text visible in drop-down menu:
`#% increased Global Physical Damage`

Tip text that appears when you hover your mouse over the text above:
`While a Unique Enemy is in your Presence, (27-29)% increased Global Physical Damage`

The essence dropdown and description were 3 spaces, while the jewel node was 49 spaces.

**Comment by CryAngel1970** [comment]
There was a typo in the file extension due to my mistake.
I succeeded in localization. Thanks to everyone who helped.
![snap0054](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/ceaa8ff8-22f5-4f13-9580-e21770f943a4)
