### ISSUE TITLE
Everlasting Sacrifice calculation , Mahuxotl's Machination

### ISSUE THREAD

**Issue by dgknyl** [PathOfBuildingCommunity/PathOfBuilding#6785]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

The feature it provides is not included for [Mahuxotl's Machination](https://www.poewiki.net/wiki/Mahuxotl%27s_Machination)
+5% all maximum resistance. Everlasting Sacrifice

### Describe the solution you'd like

When the energy is full, it resets itself and gives 5% maximum all resistance. If "Mahuxotl's Machination" equipped : I think need "Sacrifice all Energy Shield" or "Everlasting Sacrifice" checkbox for proc at Configuration.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/33714761/085be6b5-7ecf-464d-bb97-23d61e6879c9)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/33714761/67bd04e3-32b6-4624-a471-0a49ffa9de2b)

### Describe alternatives you've considered

 I think need "Sacrifice all Energy Shield" or "Everlasting Sacrifice" checkbox for proc at Configuration.

**Comment by auspex92** [comment]
this isn't an issue, it's just not supported yet. you can add a custom mod "+5% to all maximum resistances" as a check box for it
