### ISSUE TITLE
Trojan being picked up

### ISSUE THREAD

**Issue by Atazala** [PathOfBuildingCommunity/PathOfBuilding#6804]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Should not have trojan horses software being picked up by windows defender

### How does Path of Building behave?

gets deleted by windows defender

### How to reproduce the issue

deleted, clean install

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/102029279/4503131a-fa59-4d8e-b30e-25151a7b088f)

**Comment by Nightblade** [comment]
Just a false positive.  There's nothing the PoB devs can do about it.

**Comment by Atazala** [comment]
great, figured I'd check in
