### ISSUE TITLE
I'm curious about the invisible word.

### ISSUE THREAD

**Issue by CryAngel1970** [PathOfBuildingCommunity/PathOfBuilding#6815]
I am localizing Poe with Poecharm.
I think the trigger for Cast when Damage Taken is Culling Strik.
I changed the level of the Culling Strike gem and noticed that the DPS values changed, and it seems to be Culling Strike.

[https://pobb.in/IFjlx0BRruET](url)

`"Culling Strike (Cast when Damage Taken):","마무리 타격^xFF9922(피격 시 시전)^x5CF0BB:"`
I want to know the English word for Culling Strike in front of (Cast when Damage Taken):

![snap0021](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/204231e5-5f0f-44a3-a599-ef0b82e17343)

**Comment by Wires77** [comment]
It's not Culling Strike, it's Creeping Frost, as that's the other skill that is on FullDPS

**Comment by CryAngel1970** [comment]
Creeping Frost has already been added.

`"Ice Spear (Cast when Damage Taken):","얼음 창^xFF9922(피격 시 시전)^x5CF0BB:"
"Creeping Frost (Cast when Damage Taken):","엄습하는 서리^xFF9922(피격 시 시전)^x5CF0BB:"
"Bonechill (Cast when Damage Taken):","마무리 타격^xFF9922(피격 시 시전)^x5CF0BB:"
"Frostbite (Cast when Damage Taken):","동상^xFF9922(피격 시 시전)^x5CF0BB:"
"Culling Strike (Cast when Damage Taken):","마무리 타격^xFF9922(피격 시 시전)^x5CF0BB:"`

I added it as in the example above, but the Ice Spear has changed, but the text for 23,427,778 damage below it has not changed.
I therefore suspected that the invisible text in front of Cast when Damage Taken was Culling Strike.

**Comment by CryAngel1970** [comment]
I found the cause. There was 6x before Creeping Frost.

thank you for your quick reply.

**Comment by zao** [comment]
In order to debug these issues, may I suggest some techniques?
* Maybe alter the sidebar code to display elsewhere in the window with a larger viewport, so you can see the true text for yourself?
* Maybe output it to the console with `ConPrintf` if this PoeCharm implementation supports the Ctrl+` (Ctrl+F1) console?

**Comment by Wires77** [comment]
Glad you found it, I was just going to post this from the XML

```<FullDPSSkill skillPart="" value="23427778.466084" stat="6x Creeping Frost" source="Cast when Damage Taken"/>```

Do know that the "6x" part is subject to change based on this Count setting, so you probably can't hardcode it in the translation file

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1209372/b04331db-af60-41f4-92d8-4f843fbf21c9)

**Comment by CryAngel1970** [comment]
I know this method is very inefficient.
If the value receives a number as an argument, Poecharm can process it as {0}.

Depending on the argument, it seems to be used between {0} and {1}. Anything above 1 didn't seem to work.

So, I'm adding all the text-based numbers, and getting the desired result.

`"1x Creeping Frost (Cast when Damage Taken):","엄습하는 서리 x1^xFF9922(피격 시 시전)^x5CF0BB:"
"2x Creeping Frost (Cast when Damage Taken):","엄습하는 서리 x2^xFF9922(피격 시 시전)^x5CF0BB:"
"3x Creeping Frost (Cast when Damage Taken):","엄습하는 서리 x3^xFF9922(피격 시 시전)^x5CF0BB:"
"4x Creeping Frost (Cast when Damage Taken):","엄습하는 서리 x4^xFF9922(피격 시 시전)^x5CF0BB:"
"5x Creeping Frost (Cast when Damage Taken):","엄습하는 서리 x5^xFF9922(피격 시 시전)^x5CF0BB:"
"6x Creeping Frost (Cast when Damage Taken):","엄습하는 서리 x6^xFF9922(피격 시 시전)^x5CF0BB:"`

**Comment by Wires77** [comment]
It might be worth asking @Chuanhsing if that can be adjusted, since Ice Spear (or any arbitrary skill) could have the same issue.  e.g. "6x Ice Spear (Cast when Damage Taken)", "4x Dark Pact (Cast when Channelling)", "40x Fireball (Cast on Critical Strike)", etc

**Comment by CryAngel1970** [comment]
@zao I am not the person who developed PoeCharm, but the person who uses it.

I think PoeCharm has a function to view PoeCharm's log, but I don't know if it is connected to PoB.

**Comment by CryAngel1970** [comment]
@Wires77 You are correct. Such cases have been found in many places.
If I don't receive a number as a variable, I input all possible occurrences of that number to get the desired localization result.

I'll have to ask @Chuanhsing.


`"While a Unique Enemy is in your Presence, 1% less Damage Taken per 160 Dexterity","고유 적이 접근해 있는 동안, 민첩 160당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 170 Dexterity","고유 적이 접근해 있는 동안, 민첩 170당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 180 Dexterity","고유 적이 접근해 있는 동안, 민첩 180당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 190 Dexterity","고유 적이 접근해 있는 동안, 민첩 190당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 200 Dexterity","고유 적이 접근해 있는 동안, 민첩 200당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 210 Dexterity","고유 적이 접근해 있는 동안, 민첩 210당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 220 Dexterity","고유 적이 접근해 있는 동안, 민첩 220당 받는 피해 1% 감폭"
"While a Unique Enemy is in your Presence, 1% less Damage Taken per 230 Dexterity","고유 적이 접근해 있는 동안, 민첩 230당 받는 피해 1% 감폭"`

**Comment by CryAngel1970** [comment]
@Wires77 I said this with reference to the screenshot you attached. A tooltip rather than a mouseover is sufficient.

**Comment by zao** [comment]
> @zao I am not the person who developed PoeCharm, but the person who uses it.
> I think PoeCharm has a function to view PoeCharm's log, but I don't know if it is connected to PoB.

For the first point, I mean that you can modify the "PathOfBuildingCommunity" Lua code that PoeCharm runs, as that is probably our Lua code, either as-is or lightly modified. That one should be able to do whatever it wants.

On the second - if there's no UI to see the built-in console in PoeCharm that's unfortunate as it's quite useful in troubleshooting things.
