### ISSUE TITLE
I would like to ask about distribution of copy versions.

### ISSUE THREAD

**Issue by CryAngel1970** [PathOfBuildingCommunity/PathOfBuilding#6835]
I'm localizing Pob via PoeCharm.

Because the fonts and word lengths of Korean and English are different, there are cases where they go beyond the input box or are obscured and are not visible.
The cause of this problem lies in the sentence length in Korean and English.

This can sometimes cause text to be cut off or go out of the input window.
![snap0033](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/49d95456-2479-40d1-b8fd-40cf880acb8c)
![snap0034](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/77eda19c-32b4-4d9c-b197-3ebb75bdc840)

To solve this problem, I am solving this problem by creating abbreviations rather than common words.
If using abbreviations does not solve the problem, you can expand the abbreviations as much as possible to maximize space.
However, since the word is not a common word, people who encounter the word for the first time are unfamiliar with it and do not know what it means even though it is written in Korean.

So, an easier way is to expand the input box without creating an abbreviation for Hangul.
It's easy to solve even if you're not an expert programmer like me.
Just change the number in the text input window to a number larger than the existing number.

However, the problem is that even if I modify the source, Pob recognizes the modified source as an older version and keeps trying to update it to return it to its original state.

So, I would like to ask if I can modify the pob source so that it can be updated in a place other than the official Pob github.

When Pob is updated, I will upload the updated original source to my github, and I will also upload the source for only the parts that have problems in Korean.

In that case, the Korean font and Korean language will not have to be truncated or abbreviated due to limitations in the input box.

I haven't figured out yet which link I need to modify in the Pob source to do that.

I plan to proceed after inquiring whether I can upload a copy version, modify it, and distribute it.

**Comment by Regisle** [comment]
if you change these 4 lines to point to your repo it should check that for changes instead <https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/manifest.xml#L4-L7>
