### ISSUE TITLE
Fractal Thoughts crashing PoB

### ISSUE THREAD

**Issue by BuHoGPaD** [PathOfBuildingCommunity/PathOfBuilding#684]
Sorry in advance for any spelling mistakes.

Build that has crashes:  https://pastebin.com/ifCLvcYN+
PoB crashes whenever I hover over Dexterity details on "Calcs" tab. 

It seems to be connected with Fractal Thoughts helmet. Cause when I remove the helm from weared items - crashes stop occuring. Also even empty build with only this helm on - crashes.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
