### ISSUE TITLE
Ceinture of benevolence applying effects of flasks twice to self

### ISSUE THREAD

**Issue by roeyb1** [PathOfBuildingCommunity/PathOfBuilding#6848]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Ceinture of benevolence unique belt states that  "non unique utility flasks you use apply to linked targets". This should never apply to self.

### What is the value from the calculation in Path of Building?

PoB will create duplicate entries for each of my flask effects (double flat armor from a granite flask, for example) when the ceinture of benevolence belt is equipped and a link skill is enabled.

### How to reproduce the issue

1.  import the following PoB https://pobb.in/dxpb5cJoMMt-
2. Go to the Items page
3. Hover over the checkbox for the quicksilver flask
4. Observe that deactivating the flask will indicate a loss of 80% movement speed when it should say 40.

Note: The repro rate seems to be somewhat inconsistent. I was able to reproduce 9/10 times in this PoB. Additionally, when trying to build a minimal working example it did not reproduce either.

### Character build code

```shell
https://pobb.in/dxpb5cJoMMt-
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/25555412/bd9953fe-0443-4cbb-9756-fee3125f722d)

**Comment by Regisle** [comment]
Fixed on dev already by #6757
