### ISSUE TITLE
Manual Zoom in and out of passive tree.

### ISSUE THREAD

**Issue by MoonieLewdmore** [PathOfBuildingCommunity/PathOfBuilding#6856]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Some users (Like me) lack a working scrollwheel, making zooming in or out impossible since there are no keybinds for it either.

### Describe the solution you'd like

Simple slider to zoom in or out, or add hotkeys for +/- to work as zoom in zoom out while in the Tree Tab.

**Comment by Regisle** [comment]
`page up` and `page down` work
