### ISSUE TITLE
Master of Metal description is wrong in Ruthless Skill Tree

### ISSUE THREAD

**Issue by Darxo** [PathOfBuildingCommunity/PathOfBuilding#6895]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

In the ruthless skill tree the node `Master of Metal` should look like this:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/2252464/29be8a97-17d4-43c0-92cf-b0332c2eff5c)

### How does Path of Building behave?

But in POB it looks like this:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/2252464/2e65390a-4e5b-49c3-a70f-43dec9c692c6)

**Comment by sida-wang** [comment]
Fixed in 48f6d4b
