### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by Loqures** [PathOfBuildingCommunity/PathOfBuilding#6903]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![пізда](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48675094/17fcdacf-fc00-4441-8da5-91f895c8d642)

### What are your system specifications and configuration?

[DxDiag.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/13550946/DxDiag.txt)

### How to reproduce the issue

1. I start the client
2. At the time of loading (it says something about pixels) - the client closes
3. The end

**Comment by Loqures** [comment]
https://github.com/zao/PathOfBuilding-SimpleGraphic/releases/tag/angle-2022-08-23


This dont help me

**Comment by Nightblade** [comment]
File Explorer ->  right-click Path of Building.exe -> Properties -> Compatibility -> High DPI Scaling override -> check Override high DPI scaling behavior. Scaling performed by: -> select System (Enhanced)

Could you try this?

**Comment by Loqures** [comment]
> File Explorer -> right-click Path of Building.exe -> Properties -> Compatibility -> Change high DPI settings -> check Override high DPI scaling behavior. Scaling performed by: -> select System (Enhanced)
> 
> Could you try this?

Tried it now - it didn't help =(

**Comment by Loqures** [comment]
And can the program not work because I have Win 10 and Microsoft Edge is installed instead of Internet Explorer? Can there be visual conflicts because of this? Because I was given the idea that it was the explorer that was missing. Because, for example, the other day, shortcut icons started to disappear, they become dull white. I was told this because of the lack of an explorer, such bullshit. Maybe you need it for work?
What is the probability of this?

**Comment by Nightblade** [comment]
You're OK there -- PoB doesn't need IE or Edge.

**Comment by zao** [comment]
My primary suspicion is that you have a laptop with two GPUs, one that seems to be an integrated AMD APU and one discrete NVidia GPU.
That kind of configuration has historically been a problem for regular OpenGL that tends to have implementations that don't quite handle coexistence too well.
I also note that you have quite old drivers for your AMD GPU - it might be worth installing proper current ones from AMD if you're relying on stock ones from Windows Update currently.

The updated PoB runtime (by yours truly) is way better at handling this kind of scenario and has way better driver support as it uses DirectX behind ANGLE.
What differed when you tried the DLLs from that runtime rather than the stock ones? Note that you can't update PoB once those are in place as it will try to downgrade itself again to the original files.

On your system behaviour with broken icons - heaven knows what's up with that but it most probably doesn't have anything to do with these problems.

**Comment by Loqures** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48675094/30437096-b565-449b-9dab-6be56f465dfc)
After unpacking all the files from that topic, the program started. But when I try to update it - I get the same problem.

**Comment by Nightblade** [comment]
Do not update it!

**Comment by Paliak** [comment]
Updating it essentially removes the fix.

**Comment by Loqures** [comment]
> The files you obtained were a preview of upcoming improvements to the runtime of ours that Path of Building runs on. I rolled that release so that we could see if it helped with problems like these, which it did. There's work underway to bring these changes (and even more cool stuff like 64-bit and newer LuaJIT) into the main releases but it needs a bit more work and packaging to be ready.
> 
> There was an opt-in beta a few months ago that had all the neat new runtime stuff, but that's not updated with any changes to Path of Building itself, so it's of limited use.
> 
> Right now, until the mythical day when I/we finish this work, I recommend that you use this alternate runtime and refrain from interacting with the update button. If there's an actual real update, perform that and replace the runtime again once it fails to start.
> 
> Another thing to look at is if you can configure in your OS which GPU you wish to launch a program with - not sure if there's any such functionality for your particular kind of setup.

Thank you!

**Comment by Wires77** [comment]
I just updated the beta branch so you should be able to use that option in PoB and get updates again.  It's a manual process, but I'm going to try to keep that beta branch in step with the latest code and the updated SimpleGraphic.dll

**Comment by Loqures** [comment]
> I just updated the beta branch so you should be able to use that option in PoB and get updates again. It's a manual process, but I'm going to try to keep that beta branch in step with the latest code and the updated SimpleGraphic.dll

I don't know how to navigate Github, to be honest. Can you please guide me or give me a link?

**Comment by Wires77** [comment]
> > I just updated the beta branch so you should be able to use that option in PoB and get updates again. It's a manual process, but I'm going to try to keep that beta branch in step with the latest code and the updated SimpleGraphic.dll
> 
> I don't know how to navigate Github, to be honest. Can you please guide me or give me a link?

If you go to options in PoB, there's an option to opt in to beta releases.  Check that box, then check for updates.  It'll have the updated SimpleGraphic.dll so you don't have to replace it every time manually

**Comment by Loqures** [comment]
> > > I just updated the beta branch so you should be able to use that option in PoB and get updates again. It's a manual process, but I'm going to try to keep that beta branch in step with the latest code and the updated SimpleGraphic.dll
> > 
> > 
> > I don't know how to navigate Github, to be honest. Can you please guide me or give me a link?
> 
> If you go to options in PoB, there's an option to opt in to beta releases. Check that box, then check for updates. It'll have the updated SimpleGraphic.dll so you don't have to replace it every time manually

Thank you very much! Now it works fine! You saved me!

**Comment by Loqures** [comment]
Windows was recently updated, after that it stopped working altogether. Same problem at the same stage. Only now the files in the folders that were supposed to fix this problem and allow it to run in the beta do not work. The program does not see SimpleGraphic.dll that I unpack for it...
