### ISSUE TITLE
Explosive Trap is calculated inaccurately.

### ISSUE THREAD

**Issue by caner-cetin** [PathOfBuildingCommunity/PathOfBuilding#6909]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

We dont know, and we didnt calculate but according to latest addition to RAQ:

> Why did you add the line ''Smaller explosions have between 30% reduced and 30% increased base radius at random'' to Explosive Trap?

> Explosive Trap has always worked this way. This is purely an update to the description.

### What is the value from the calculation in Path of Building?

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92731060/3165e0d4-3fc9-4880-8677-2ce4245ade23)

Either:
-> Formula does not calculate the -30 to +30 random base radius
-> Calculation text shown to users is wrong.

~Asides from the calculation bug (or text inaccuracy), maybe just a little bug, Explosive Trap is registered as ShrapnelTrap in skills. https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Data/Skills/act_dex.lua#L4091~

### Character build code

[https://pobb.in/nEl5FG8KIKB3

https://pastebin.com/9HRBVLij](https://pobb.in/nEl5FG8KIKB3)

**Comment by Lilylicious** [comment]
Sharpnel Trap is the internal name for Explosive trap, so this is not a bug.

Regarding the radius modifications, I believe that since it's symmetrically random, it shouldn't have an impact on the final result. Unsure if any changes need to be made here.

**Comment by caner-cetin** [comment]
Thanks for the heads up, fixed the title.

**Comment by Lilylicious** [comment]
Yep, we've come to the same conclusion. In addition, PoB's current secondary explosion hit rate calculation, even without the -30% to 30%, is overestimating the hit rate consistently at various radii. I've gotten a simplified formula for the hit rate that's far more accurate, next step is just to take into account the -30% to 30% radius modifier in some intelligent way that isn't doing the same calculation for every option.

**Comment by ychen428** [comment]
Could you share the updated formula for the hit rate? I can see if I can come up with something, but my gut instinct is it might be difficult without repeating the calculation several times because we have to round the radius first before calculating the overlaps, which means we can't get an analytic form.

**Comment by Lilylicious** [comment]
Sure! The new formula is `math.min(1/(1+math.exp(-(3.6/areaSpreadRadius)*((areaDamageRadius+enemyRadius-0.1)- areaSpreadRadius*0.9 ))), 1)`.

I'm testing it against a content creator's recent leaguestarter PoB for it, and I'm getting around 50% hitrate for secondary explosions compared to the previous 75% for that PoB.
