### ISSUE TITLE
Can't import my build to 2.35.0

### ISSUE THREAD

**Issue by tehKaiN** [PathOfBuildingCommunity/PathOfBuilding#6913]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

PoB should be able to import my character

### How does Path of Building behave?

Importing my character's passive tree causes traceback message. After skipping it, the tree remains empty.

### How to reproduce the issue

1. Go to "Import/Export build"
2. Enter account name: tehKaiN
3. Try select _AuraDaddy_ character from Ancestor league
4. Click Passive "Tree and Jewels" button

### Screenshots

![obraz](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/16180344/a4cdab9c-3028-453b-bf74-0734a281d8cc)

**Comment by CubeStick** [comment]
I get the same error.

**Comment by RealTabman** [comment]
Same for me. Trying to import from any league results in:
![poer](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/5718054/a20a2f92-cc18-462f-951f-17825e264fbc)

**Comment by Lilylicious** [comment]
We're aware of the issue and are looking into it
