### ISSUE TITLE
Physical Damage taken as <element> is broken after 2.35.0 Update

### ISSUE THREAD

**Issue by jix91** [PathOfBuildingCommunity/PathOfBuilding#6914]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

100% physical damage taken as <element> isnt working correctly. My build should have about 1mil phys max hit taken, it has 16.000.

### What is the value from the calculation in Path of Building?

100% physical damage taken as <element> isnt working correctly. My build should have about 1mil phys max hit taken, it has 16.000.

### How to reproduce the issue

just check my pob
https://pobb.in/6yriAio7tWc3

### Character build code

```shell
https://pobb.in/6yriAio7tWc3
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/61379609/a7445095-4bdf-4c1b-ac73-374724851b26)

**Comment by MeDott29** [comment]
Sweep: make a plan to fix this

**Comment by Syrou** [comment]
Can confirm, is indeed broken

**Comment by jix91** [comment]
> We're aware and will have a fix for this shortly.

pog! you guys rock :) ty!
