### ISSUE TITLE
unable to import player tree after last update 2.35.0

### ISSUE THREAD

**Issue by jmatelet** [PathOfBuildingCommunity/PathOfBuilding#6917]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

import passive tree and jewels from a charater sucessfully import the tree

### How does Path of Building behave?

currently generating an error and nothing happens

### How to reproduce the issue

character import > select a character / league (AlkaizerX garf for exemple) > click on import Passive Tree and Jewels 

### Screenshots

https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/32544062/c21efa29-ca76-425d-bc3e-4d3eba3785e2

**Comment by Wires77** [comment]
Duplicates #6913
