### ISSUE TITLE
Some items are causing PoB to fail on import

### ISSUE THREAD

**Issue by rasmuskl** [PathOfBuildingCommunity/PathOfBuilding#692]
(detected through poe.ninja builds, thus no details on the specifics)

The error appears when importing items.

![image](https://user-images.githubusercontent.com/462451/77832107-db048a00-7133-11ea-8c1b-9508570b5d18.png)

Reproduce by importing any of the 2 characters: [acc: NoxiousGLHF char: Coronascendant], [acc: MagikYams, char: BrandMageYams]

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
