### ISSUE TITLE
Show Warnings for exceeding socket limit on enabled skills

### ISSUE THREAD

**Issue by Warmachine237** [PathOfBuildingCommunity/PathOfBuilding#6925]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Id like to be able to see warnings when my socket setup is exceeding the total sockets available on each item separately or overall combined. Being able to split multiple skill links in my body armor and still keep track of sockets remaining would be nice. Especially with the new Oath of the Magi Ascendency.

### Describe the solution you'd like

When exceeding socket limit on any item with an enabled skill setup show warning on the bottom left UI similar to warnings for reservation or attribute requirements.

**Comment by sida-wang** [comment]
Added in #6937
