### ISSUE TITLE
The "trade for these item" feature always reset to 1.00 Full DPS and 0.5 Effective Health pool

### ISSUE THREAD

**Issue by lanvuive332** [PathOfBuildingCommunity/PathOfBuilding#6935]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

yes

### Describe the solution you'd like

can you guy make it keep the latest setting?

**Comment by Peechey** [comment]
Fixed by #6954, went live with 2.36.0 release
