### ISSUE TITLE
Legacy of Fury Wyrmscale Boots doesn't work in PoB now

### ISSUE THREAD

**Issue by IvanStenyaev** [PathOfBuildingCommunity/PathOfBuilding#6939]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Nearby Enemies are Scorched - take increase damage

### What is the value from the calculation in Path of Building?

Scorch from this boot's not calculate in damage calculation

### Character build code

```shell
https://pobb.in/EJNNk1rghtPN
```

### Screenshots

![RLWpYW](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/82395319/782ee859-b618-457c-897e-c8f4221c99d8)

**Comment by Lilylicious** [comment]
There is no issue. You have the chieftain node that sets the enemy fire resistance to -20% when you're stationary active. Scorch reduces enemy elemental resistances, which does nothing if the enemy is set to a fixed value.
