### ISSUE TITLE
Accuracy rating is not being calculated

### ISSUE THREAD

**Issue by Augustasssssss** [PathOfBuildingCommunity/PathOfBuilding#6940]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [x] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Around 80000 accuracy rating.

### What is the value from the calculation in Path of Building?

Around 61000 accuracy rating.

### How to reproduce the issue

Before the 2.35 update the accuracy rating value of Lightning Strike in the Calcs tab was around 80 thousand. After the update it is 61 thousand. I identified that the Accuracy Mastery: [40% more Accuracy Rating against Unique Enemies] and [50% more Accuracy Rating at Close Range] and the Mark Mastery: [50% more Accuracy Rating against Marked Enemy] aren't being calculated because allocating those masteries does not increase the accuracy rating in the Calcs tab.

### Character build code

```shell
https://pobb.in/iOQRWzDGTbhA
```

**Comment by LocalIdentity** [comment]
Accuracy that is conditional against an enemy does not affect the accuracy stat for the purpose of accuracy stacking, it only affects the hit chance calculations
