### ISSUE TITLE
Penance brand dosent have the proper text update and still have an attached duration 

### ISSUE THREAD

**Issue by iDuctile** [PathOfBuildingCommunity/PathOfBuilding#6948]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

The new penance brand dosent have an attach duration anymore

### What is the value from the calculation in Path of Building?

POB still showing and calculating the attach duration on it witch mess up the final tic rate of the brand 

### How to reproduce the issue

Just look at penance brand gem.

### Character build code

```shell
https://pastebin.com/SAy7cSmH
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153107086/c91e2b9c-3424-42a5-a60b-2e1175b1719d)

**Comment by Paliak** [comment]
Should work correctly on current release: 
![obraz](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91493239/8c7e24ad-4539-4ced-b17b-98a87e4ad732)
