### ISSUE TITLE
Show Node Power Chaos DOT missing Corruption

### ISSUE THREAD

**Issue by bradneuman** [PathOfBuildingCommunity/PathOfBuilding#695]
The Corruption node in the tree, which offers increased DOT and chaos DOT, shows completely blank under "show node power" either offense / defense or Chaos DoT DPS.

Mosueover shows signficiant DoT DPS increase (12%)
https://imgur.com/a/8wG6Fcz

This is on an ed/c character, pastebin here: https://pastebin.com/uKJUVddy

Repro steps:
1. Import pob link
2. Select essence drain as main skill
3. Go to Tree tab, check show node power
4. Look at any of the offense / DPS settings and look at the corruption skill in the top left

Expected result:
Should highlight in red in porpotion to it's increase (e.g. it should be much brighter than "disciple of the forbidden" which, according to mousover, only adds a few percent

Actual result: Corruption node is completely dark

I haven't checked if this applies to other nodes, but now I'm a bit suspicious that it might.

version is 1.4.167.2

**Comment by LocalIdentity** [comment]
Tracked it down to Decay Support doing something weird to the node power calculations. A temporary fix is to uncheck your decay support then go to the tree and it will update the node power values

**Comment by Nostrademous** [comment]
OBE - the "Corruption" notable is now an increase to the Wither Effect
