### ISSUE TITLE
Please add the switch render setting from opengl to dx11

### ISSUE THREAD

**Issue by DeadShinobu** [PathOfBuildingCommunity/PathOfBuilding#6957]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

before the last update my PoB fixes the 22 fps cap, It started to run through dx11 for some unknown reason, although it was always opengl before. and on the dx11 framerate was 60 fixed. 

### Describe the solution you'd like

add button to switch render please or tell me how to switch it manually

**Comment by Wires77** [comment]
Are you running the beta version of PoB?  I.e. is the opt-in checkbox enabled in your options?  We're testing an updated backend on the beta client, so that might be what you're seeing, and it has been restored a couple hours after you posted this issue.

**Comment by DeadShinobu** [comment]
> Are you running the beta version of PoB? I.e. is the opt-in checkbox enabled in your options? We're testing an updated backend on the beta client, so that might be what you're seeing, and it has been restored a couple hours after you posted this issue.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91910118/778f7f58-597c-4332-9f11-67be20465778)

ya its worked with beta opt. thank u for dx11

**Comment by zao** [comment]
For a bit of clarity, the new runtime in beta uses OpenGL ES, which via our ANGLE runtime is emulated on top of a variety of graphics APIs. On Windows it currently picks D3D11, which is what you see detected in your overlay.
The old runtime uses real OpenGL 1.1, which is ancient and not always works well on modern computers.
