### ISSUE TITLE
Issuse with an Hollow Palm Build

### ISSUE THREAD

**Issue by ppairan** [PathOfBuildingCommunity/PathOfBuilding#696]
https://cdn.discordapp.com/attachments/175290321695932416/694097211629240320/unknown.png the picture from the issuse 

-Build POB https://pastebin.com/8fS4wqwD - Hollow Palm Unique

**Comment by LettuceKiing** [comment]
Can confirm, issue occurs while hovering from MH Total Increased: (Physical tab) to the above Added max calculation

https://pastebin.com/EDbJAa7e

![error2](https://user-images.githubusercontent.com/44695100/77926056-ed9ed080-72a5-11ea-86a2-7d09ee2e851c.PNG)

**Comment by LocalIdentity** [comment]
Traced the bug back to the fact that the stat display breaks when trying to show the source name for stats that comes from cluster jewel Keystones. Is also a problem with Kitava's Techings Notable

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
