### ISSUE TITLE
Bonechill quality not having supported skills deal 10% increased cold damage

### ISSUE THREAD

**Issue by LkGGz** [PathOfBuildingCommunity/PathOfBuilding#6960]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

Supported Skills deal 10% increased Cold Damage

### What is the wording in Path of Building?

Supported Skills have 20% increased Chill Duration on Enemies

### Character build code

```shell
https://pobb.in/DCWEicJLnf-k
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153091013/8f5fec86-6b54-4f52-8c40-471f225d2545)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153091013/00a2d07e-9b2e-496b-b431-619886bb9fd2)

**Comment by Paliak** [comment]
Gems have been updated. This should be good to close.
