### ISSUE TITLE
Vaal Cold Snap is missing 20% more Effect of Chill

### ISSUE THREAD

**Issue by LkGGz** [PathOfBuildingCommunity/PathOfBuilding#6961]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

Nothing

### What is the wording in Path of Building?

20% more Effect of Chill

### Character build code

```shell
https://pobb.in/DCWEicJLnf-k
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153091013/9c89ed7e-9ec1-40a9-88ca-2a796fe84d31)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153091013/73ef71af-7b8d-43c2-9926-30248f6bb465)

**Comment by LocalIdentity** [comment]
Will be updated on league l;aunch
