### ISSUE TITLE
POB does not have new league gems

### ISSUE THREAD

**Issue by Skyniss** [PathOfBuildingCommunity/PathOfBuilding#6978]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

it should show the new gems but it doesn't. it imports the builds just fine but doesn't have the gems

### How does Path of Building behave?

it imports builds but doesn't show new gems

### How to reproduce the issue

import any build containing transfigured gems

**Comment by Nightblade** [comment]
PoB's developers don't get special early access to skill gem data.  They are aware of this issue, and it will be fixed Soon™.

**Comment by LocalIdentity** [comment]
Added in 2.38.0
