### ISSUE TITLE
Energy Blade Quality - More energy shield update

### ISSUE THREAD

**Issue by CRYB4DEATH** [PathOfBuildingCommunity/PathOfBuilding#6979]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

as of 3.23 the Energy Blade has been updated so you get more energy shield instead of critical strike chance when you quality your Energy Blade

### What is the behaviour in Path of Building?

Path of building still adds critical strike chance instead of more energy shield

### How to reproduce the issue

Add skill Energy Blade
Add Quality % to Energy Blade

### Character build code

```shell
https://pobb.in/hfebuWueZ7o6
```

### Screenshots

![EnergyBlade POB](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153401714/94f5e85c-9047-4b88-a399-184cdf3e3bd4)
![EnergyBlade ingame](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/153401714/275bfe8d-8da7-4aa6-bf54-c37b4136d258)

**Comment by LocalIdentity** [comment]
Handled after we export all the gems for this league
