### ISSUE TITLE
For some odd reason i can have 2 curses (Flammability + Elemental weakness) on at the same time? 

### ISSUE THREAD

**Issue by Nela88** [PathOfBuildingCommunity/PathOfBuilding#6991]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Hi.

I have flammability linked with arcanist brand and it seems to work properly.
I were looking for new gems to use and found out pob is telling me to add elemental weakness to my build aswell. I added the gem and now in calcs tab it says in debuff section that im applying both?
I have not corrupted amulet for max curse, i have not traveled nor anointed whispers of the doom. Im not using windshriek boots and my only ring im using is rare with no mods about curses.

I tried to add assassin mark aswell and it dropped elemental weakness off in the calcs tab and added the assassin mark.
I tried this on fresh char lvl 1 and added 3 curses, calcs said that i can only use 1 at a time. I also removed arcanist brand from my own pob and no change at all anywhere.

### How does Path of Building behave?

Seems to be in some rare cases adding extra curse for no reason?

### How to reproduce the issue

I allready manually copy pasted all my items into fresh pob and reconfigured everything and also copied tree and skill gems etc and problem still persists

### Character build code

```shell
https://pobb.in/InCNnj3S4V9Q
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/124595984/a2da0dcb-b4e8-4a0d-9fb7-5132c532892a)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/124595984/59ca2c69-18bc-4602-8d18-2e1fd96986ed)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/124595984/75c1163a-2187-4cfb-80b5-42e5c575575d)

**Comment by Nela88** [comment]
> The issue is to do with Lord of Drought on your Meglomaniac for future reference

Ah okay. Thanks for quick response!

**Comment by LocalIdentity** [comment]
It's still a bug we need to fix though. It's bypassing the hex limit instead of allowing Flammability to curse hexproof enemies
