### ISSUE TITLE
Ascendant ascendancies count as passive skills

### ISSUE THREAD

**Issue by Morilli** [PathOfBuildingCommunity/PathOfBuilding#6998]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Allocating ascendancy passives should not count towards the normal passive tree node limit.

### How does Path of Building behave?

It does.

### How to reproduce the issue

1. Make a new ascendant build and allocate any ascendancy node, like Witch Ascendancy -> Necromancer.

**Comment by iParadoxG** [comment]
+1 I came here to post this, I see this issue too.
