### ISSUE TITLE
Raider's Avatar of the Veil not calculated

### ISSUE THREAD

**Issue by thmour** [PathOfBuildingCommunity/PathOfBuilding#7]
Raider's avatar of the veil has elemental exposure giving -15% to all elemental resistances to monsters. Both versions of PoB do not calculate this.

Thanks

**Comment by rskupnik** [comment]
Looking at this

**Comment by ppoelzl** [comment]
This should be part of a larger rework of specifying the distance between player and enemy in the configuration tab. "Nearby" is quite ambiguous: https://pathofexile.gamepedia.com/Distance. Also, there is no logic in place for only applying one source of Exposure yet.

**Comment by rskupnik** [comment]
I was thinking of doing this the same way other "nearby" skills work so far, which is by just assuming you are always "nearby". Adding a way of setting that would be useful of course, but I think it deserves its own ticket?

Not sure if I can handle the logic for only one source of Exposure, but I can try

**Comment by ppoelzl** [comment]
I think it's best if you try to fix #52 first, then come back to this and add it in a way that assumes you are always nearby. A "nearby" rework should indeed better be it's own PR.

**Comment by rskupnik** [comment]
Alright, I can try that

**Comment by PJacek** [comment]
Fixed in 1.4.170.12
