### ISSUE TITLE
Umbilicus Immortalis wording

### ISSUE THREAD

**Issue by Toxicable** [PathOfBuildingCommunity/PathOfBuilding#7001]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

`Flasks you Use apply to your Raised Zombies and Spectres`
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/13490925/01f67023-fba1-45fc-927d-73c51713b735)

### What is the wording in Path of Building?

`Flasks apply to your Raised Zombies and Spectres`
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/13490925/4a88aacb-e084-43bf-adc7-e1ab47bb9c34)

### Character build code

```shell
https://pobb.in/ayibhpk6PvTg
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/13490925/1de96297-3a50-48c4-8ec3-c72e27a7ee4c)

**Comment by LocalIdentity** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7016
