### ISSUE TITLE
Pyroclast Mine Aura Effect scaling Maximum Added Flat Damage

### ISSUE THREAD

**Issue by ychen428** [PathOfBuildingCommunity/PathOfBuilding#7003]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Pyroclast Mine should have an upper limit for added damage dictated by the level of the skill gem, this is [2396-3954](https://www.poewiki.net/wiki/Pyroclast_Mine) at gem level 40.

### What is the value from the calculation in Path of Building?

In PoB the upper limit is scaled by the aura effect, giving 2396-3594 * 2.86 (aura effect) = 6852-10278

<img width="608" alt="image" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/43482133/59bc864b-2151-4d0c-b371-0d3e505c11d3">

### How to reproduce the issue

https://pobb.in/WlQrcdUvMT5H
Use this PoB, active mines to 50, observe the extra added damage from Pyroclast.

### Character build code

```shell
https://pobb.in/WlQrcdUvMT5H
```

**Comment by mr-september** [comment]
Is it confirmed that upper limits like those **don't** only apply to the base damage, before other scaling?

**Comment by LocalIdentity** [comment]
It would seem correct that Aura effect doesn't scale the max damage otherwise you'd never hit the cap unless you had multiple people in a party throwing Pyro mines. I've asked someone at GGG to confirm

**Comment by LocalIdentity** [comment]
Confirmed with GGG that Aura effect shouldn't scale max added damage limit. I'll have a hotfix our in the next hour or so with this and a couple other small fixes
