### ISSUE TITLE
Double damage

### ISSUE THREAD

**Issue by 83845** [PathOfBuildingCommunity/PathOfBuilding#701]
I recently found out that the chance of causing double damage is not calculated, and if you take the War Bringer berserk node as an example, the font of the double damage line shows as usual (not red, supposedly it doesn’t work) but after I tried in any of things add bonus "chance to deal double damage" he did not give any bonus

**Comment by LocalIdentity** [comment]
Double Damage chance is calculated correctly and is shown on the calcs page under the MH/OH Hit Damage tooltip when you hover over them. You need to check the box for "Used a Warcry in the past 8 Seconds?" to get the double damage values to show up
