### ISSUE TITLE
Tincture effect not increased by Enduring Suffusion

### ISSUE THREAD

**Issue by johnramsden** [PathOfBuildingCommunity/PathOfBuilding#7010]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Tincture mods should increase by 75% with Enduring Suffusion set

### Describe the solution you'd like

When checking Enduring Suffusion, mods should be multiplied by 1.75

### Additional context

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8735102/3a0bb2cb-7cec-45c1-8ef1-14d9b434eb67)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8735102/8d93bbff-144a-4442-9279-e6c3b914ba47)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8735102/5a2a91bc-ff7d-4d8d-9ae5-9a0a81925ecb)

**Comment by Regisle** [comment]
No longer relevant as the node doesnt exist and tinctures have been reworked and handled by #7749
