### ISSUE TITLE
PoB fails to start a second time 

### ISSUE THREAD

**Issue by bacms2** [PathOfBuildingCommunity/PathOfBuilding#7015]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![PoB_not_starting](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7522638/8ab0afe4-3c17-45b9-adf3-0c8471ebc58a)

### What are your system specifications and configuration?

Windows 10 Pro 10.0.19045
AMD Radeon RX 6700 XT Driver version 31.0.23013.1023

### How to reproduce the issue

1. Start the program 
2. Main window opens but no image is displayed (see attached gif). 
3. Reinstall the software and re-open the same build without issues
4. Restart computer 
5.  goes to point 1.

**Comment by Wires77** [comment]
What kind of monitor setup do you have?  It could be that the window position is being saved to an invalid location or something similar.  We've seen a few errors caused by that.  What you can try is opt in to the beta, where we have an improved graphics engine deployed.  In options in PoB, check the opt in box for the beta, and check for updates to get it installed.

**Comment by Wires77** [comment]
Closing due to no response.

**Comment by bacms2** [comment]
Apologies for the response. 
Your guess was likely correct. I use a 2 monitor setup with different resolutions on each. After your comment, I did some testing of moving the Window after it had opened from one monitor to the other and that would cause the image to be redisplayed.
