### ISSUE TITLE
Deadly Ailments Support

### ISSUE THREAD

**Issue by arserina** [PathOfBuildingCommunity/PathOfBuilding#7021]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

PoB ver 2.37.0
In Deadly Ailments Support, Supported Skills deal 80% less Damage with Hits is displayed in red and does not work.
In Awakened Deadly Ailments Support, Supported Skills deal 80% less Damage with Hits.

### What are your system specifications and configuration?

PoB ver 2.37.0
In Deadly Ailments Support, Supported Skills deal 80% less Damage with Hits is displayed in red and does not work.
In Awakened Deadly Ailments Support, Supported Skills deal 80% less Damage with Hits.

### How to reproduce the issue

PoB ver 2.37.0
In Deadly Ailments Support, Supported Skills deal 80% less Damage with Hits is displayed in red and does not work.
In Awakened Deadly Ailments Support, Supported Skills deal 80% less Damage with Hits.

### Character build code

```shell
https://pobb.in/LNfw6Ua6PnTp
```

**Comment by kilend** [comment]
I was actually checking out why this doesn't work, I think the corresponding part in the statMap in the `src/Data/Skills/sup_dex.lua` file got deleted by accident (starting at line 1545), see https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/8a01d3842e2d5a9d445e49455890c5908e87aac1#diff-e4fa52d5a92c26ba1b886bb498649cce1c501de37c3a93d5431f0c16eeedca1aL1545
