### ISSUE TITLE
Cannot open PoB after 2.37.0 patch

### ISSUE THREAD

**Issue by viocar** [PathOfBuildingCommunity/PathOfBuilding#7025]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

I updated Path of Building to the latest version and now whenever I run the program, I receive this error:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7516136/0bd7e5fd-8351-4425-ace9-75762738c737)

### What are your system specifications and configuration?

Windows 11
Ryzen 5 2600X
Radeon RX 6600

### How to reproduce the issue

1. Launch Path of Building 2.37.0

**Comment by viocar** [comment]
This was fixed with a reinstall. I'll leave this open just in case something happened specifically in the patch process that can be figured out from the error message.

**Comment by Wires77** [comment]
Since it fixed itself after a reinstall, it sounds like there was some data corruption on your end.  Going to close this issue, feel free to reopen it if it happens again.
