### ISSUE TITLE
Guardian Elemental Relic Auras cannot be deactivated

### ISSUE THREAD

**Issue by BadMojo19** [PathOfBuildingCommunity/PathOfBuilding#7030]
I'm unable to remove Wrath/Hatred/Anger from POB minion calculations despite unchecking boxes, removing ascendency skill, or changing to new ascendency.  Damage always reflects auras as on.

**Comment by Regisle** [comment]
unable to reproduce can you atleast give a build code? (there was a template to fill out for a reason)

**Comment by BadMojo19** [comment]
My apologies, first time posting!

https://pobb.in/ILw7OrWVG3oC

**Comment by BadMojo19** [comment]
Please disregard.  I rebuilt a new character in POB, and the issue is gone.  Must have been tied to other specs.  Sorry to waste your time!
