### ISSUE TITLE
Vaal Righteous Fire and Wandslinger

### ISSUE THREAD

**Issue by dotnetdan** [PathOfBuildingCommunity/PathOfBuilding#704]
When using the Wandslinger notable, a wand, and an attack skill (Elemental Hit): 

Enabling the Vaal Righteous Fire skill, which provides "% more spell damage", is not increasing the effective dps calculation. I believe that this is incorrect, since Wandslinger causes increases to spell damage to apply to attack damage with wands.

POB: https://pastebin.com/eTnEXEKk

**Comment by Regisle** [comment]
increased and reductions, not more multipliers, its using the same stat as crown of eyes, which use to work with more multipliers but was changed all the way back in 1.2 (august 2014)
