### ISSUE TITLE
double damage with paradoxica

### ISSUE THREAD

**Issue by 83845** [PathOfBuildingCommunity/PathOfBuilding#706]
when you wear 2 paradoxica, bonus "chance to deal double damage" is not working

**Comment by A68PL** [comment]
Not sure if that's what you mean. Chance to deal double damage is capped at 100%. With two Paradoxicas it's still 100%. Any other source of "chance to deal double damage" is wasted (in regards to attack hits with Paradoxicas)

**Comment by ppoelzl** [comment]
@A68PL is correct. Please try to verify how interactions like this one work before reporting issues.
