### ISSUE TITLE
'Flicker Strike of Power' is locked at 0.5 APS because of inherent CD. Not bypassed by expanding Power Charge.

### ISSUE THREAD

**Issue by Nilz0rs** [PathOfBuildingCommunity/PathOfBuilding#7066]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

'Flicker Strike of Power' Attack Rate does not bypass cooldown with power charges.

### What is the value from the calculation in Path of Building?

Attack Rate is 0.5, disregarding other stats because of the inherent 2s cooldown

### How to reproduce the issue

1. Select Flicker strike as main skill
2. Equip a handed melee weapon with more than 0.5 APS
3. look at Attack Rate

### Character build code

```shell
https://pobb.in/y5tyVmWK3GE_
```

### Screenshots

https://i.imgur.com/eHOH16K.png

**Comment by infinitedraw** [comment]
Not 100% sure the process for coding but it would likely end up looking like the "Bypass CD?" selection on the original Cold Snap.  Such as on legacy servers when using Winter's Bounty (changing frenzy charges to power charges).

**Comment by lucht7** [comment]
Can confirm. Have the same issue with normal flicker charge (Frenzy Charge in this case), attack speed did not even change when ticked the frenzy charge, 80 rage, etc.

**Comment by dummyacct7** [comment]
Yes, both Flicker versions are not bypassing the CD. Adding a ton of CD recovery in a custom line will restore your APS to what it should be until it gets fixed.
