### ISSUE TITLE
Aura mine is not calculated correctly!

### ISSUE THREAD

**Issue by Bodin0530** [PathOfBuildingCommunity/PathOfBuilding#7068]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

Aura mine is not calculated correctly!
Stormblast Mine
Pyroclast Mine
Pyroclast Mine of Sabotage
Icicle Mine
Icicle Mine of Fanning
Icicle Mine of Sabotage
and other related matters should not be correctly applied to POB calculations.

### What is the wording in Path of Building?

Aura mine is not calculated correctly!
Stormblast Mine
Pyroclast Mine
Pyroclast Mine of Sabotage
Icicle Mine
Icicle Mine of Fanning
Icicle Mine of Sabotage
and other related matters should not be correctly applied to POB calculations.

### Character build code

```shell
Aura mine is not calculated correctly!
Stormblast Mine
Pyroclast Mine
Pyroclast Mine of Sabotage
Icicle Mine
Icicle Mine of Fanning
Icicle Mine of Sabotage
and other related matters should not be correctly applied to POB calculations.
```

### Screenshots

Aura mine is not calculated correctly!
Stormblast Mine
Pyroclast Mine
Pyroclast Mine of Sabotage
Icicle Mine
Icicle Mine of Fanning
Icicle Mine of Sabotage
and other related matters should not be correctly applied to POB calculations.

**Comment by sida-wang** [comment]
Can you please provide more detail as to how it is not calculated correctly? 

Also are you sure you're setting the active mines correctly in the calcs tab? 
This is what I'm getting for Pyroclast Mine of Sabotage 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/42928828/e1c930f1-ab24-49a6-b692-2aa9b9976aeb)

The other mines are also working fine for me

**Comment by Bodin0530** [comment]
Not Aura mine can be provided to players and summons
corresponding effect
For example, Each Mine Adds (1–12) to (2–18) Fire Damage to Hits against Enemies near it, up
to a maximum of (64–601) to (96–901)
