### ISSUE TITLE
Add support for Ailment magnitude calculation

### ISSUE THREAD

**Issue by saveriodesign** [PathOfBuildingCommunity/PathOfBuilding#707]
POB has always relied on the user to input the magnitude of Shock applied to enemies manually. This requires the user to either perform some iterative table look-ups to reach an answer, or arbitrarily input whatever they think is reasonable (or simply apply 50% to make their build look better).

It is possible, from the information POB already has, to determine the near 100% up-time magnitude of Shock a build can can achieve. I've solved this problem mathematically in all conditions I personally know of and deployed a [calculator for finding this number](http://saveriodesign.gitlab.io/shock-calc). My algorithm takes between 700 and 1400 µs to execute in browser JavaScript under all conditions, so I'd like to implement it in POB. At the very least I'll fork and implement the necessary methods in the code-base.

I suggest a drop-down menu for Shock in the configuration view for users to select the source of Shock, which would then fill in and calculate the Shock magnitude. This drop-down should also include a "Manual" setting, so they can dream.

Additionally this algorithm can be applied to all other Ailments which similarly have the magnitude of their effect tied to the damage of the applying hit. This issue intersects with #190 and #262.

**Comment by Nostrademous** [comment]
Fixed in 2.15.1
