### ISSUE TITLE
Import causing attempt to Index local 'skillData' (a nil value)

### ISSUE THREAD

**Issue by markelli** [PathOfBuildingCommunity/PathOfBuilding#7070]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

Trying to import a private league character and getting the following errors when clicking the 'Items and Skills' button in the import process.  I've tried it with some other characters and no errors so might be something specific with this one.  Can give access to the league if needed to test importing it, or can try to gather more info.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/50933972/f7d6c470-9861-41a7-b7b4-3494337a8541)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/50933972/e793dfc3-50e4-492a-ae0d-055c88b17904)

### What are your system specifications and configuration?

Windows 11 Pro
AMD Ryzen 5 5600X
32GB Memory
NVIDIA GeForce RTX 3070

### How to reproduce the issue

1. Open PoB
2. New build
3. Import/Export
4. Click Start (PC/Yazilliclick prefilled for platform and account)
5. Choose private league from drop down
6. Click 'Items and Skills' (using default selected character)

**Comment by Wires77** [comment]
As long as the character is public we should be able to import it from a private league

**Comment by markelli** [comment]
Right: https://www.pathofexile.com/account/view-profile/Yazilliclick/characters?characterName=Yazpa
