### ISSUE TITLE
Hidden Blade broken with recent update to Path of Building (2.38.0) on 12/18/2023

### ISSUE THREAD

**Issue by Nightex14** [PathOfBuildingCommunity/PathOfBuilding#7083]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

If Hidden blade is in the off-hand, Unseen Strike will only use the main-hand weapon for its dmg and mods, but not its socketed supports. It will always use the main-hand weapon for its dmg and mods and never the off-hand.

Unseen Strike only uses socketed support gems if socketed in the Hidden Blade weapon.

When using 2 Hidden Blade weapons, 2 Unseen Strikes are activated. Each Unseen Strike uses the socketed support gems from their specific Hidden blade weapon. However the dmg for each Unseen Strike is still calculated based on the main-hand weapons damage and mods.

Below is 2 Hidden Blade weapons equipped:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/154223956/48cc5bcd-55a4-408c-86e4-740ea7455614)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/154223956/e6281ecc-2e46-4206-92e6-47404980de97)

### What is the behaviour in Path of Building?

With the recent update to Path of Building (2.38.0) on 12/18/2023, Hidden Blade was changed to only use the main weapon and its socketed supports. This is not how Hidden Blade actually works.

Also if 2 Hidden blades are equipped, there should be 2 separate damage calculations based on supported gems in each Hidden Blade weapon, but use the main-hand weapon for its damage. However in Path of Building there is now only 1 calculation and it ignores socketed gems in the off-hand.

### How to reproduce the issue

Create new build
Add "phasing" in custom configuration
Equip 2 The Hidden Blade weapons
Add different damage support gems to weapon 1 and 2
Check calculations

### Character build code

```shell
https://pobb.in/eu_VHX3PWFsn
```

**Comment by Paliak** [comment]
Sorry about that. I guess the wiki is wrong:

> [Support gems](https://www.poewiki.net/wiki/Support_gem) in The Hidden Blade affect Unseen Strike. If triggering Unseen Strike on a different weapon, the game will check that weapon's support gems instead of The Hidden Blade.

https://www.poewiki.net/wiki/Unseen_Strike
