### ISSUE TITLE
add support for corrupted soul 

### ISSUE THREAD

**Issue by mindyk** [PathOfBuildingCommunity/PathOfBuilding#709]
mvp would be to "just" add support for the 
"gain #% of life as extra energy shield" so people could add that manually to their timless jewel bonus points for "50% of non-chaos damage taken bypasses energy shield" which maybe only makes sense if you add an ehp calc like mom has

**Comment by ppoelzl** [comment]
Duplicate of #246

**Comment by LocalIdentity** [comment]
The 'gain #% of life as extra energy shield' is already supported in PoB and has worked for quite some time
