### ISSUE TITLE
Flicker Strike Frenzy Charge CD Bypass seems to not be working

### ISSUE THREAD

**Issue by Kindarya** [PathOfBuildingCommunity/PathOfBuilding#7103]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Flicker Strike's CD can be bypassed by spending a frenzy charge

### What is the behaviour in Path of Building?

Flicker Strike's CD can't be bypassed

### How to reproduce the issue

Equip a Flicker Strike
Attack Rate doesn't go above a certain point
Movement speed CD reduction still works

Is an issue introduced with 2.38.0 (with the implementation of Flicker Strike of Power)

### Character build code

```shell
https://pobb.in/UPqeRdiNYO7z
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/28807335/dfd31695-ba88-4b70-afcf-b63f4638906a)

**Comment by sida-wang** [comment]
Fixed in 2.38.1
