### ISSUE TITLE
Error when loading main script

### ISSUE THREAD

**Issue by sampleeli2000** [PathOfBuildingCommunity/PathOfBuilding#7106]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

PoB should load and not show an error when attempting to call "sanitiseText"

### How does Path of Building behave?

Error included as screenshot
![Screenshot 2023-12-18 195449](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/154288997/390d37cb-d7be-4750-9e47-ba971b54ce97)

**Comment by QuickStick123** [comment]
Your update probably got corrupted somehow as this should be impossible to occur. Maybe try re downloading sorry for any inconvenience.

**Comment by sampleeli2000** [comment]
Heck to the moon and back. Thanks for the response so late in the day though!

**Comment by sampleeli2000** [comment]
That did fix the issue. Thank you for responding so late in the day!
