### ISSUE TITLE
Wildwood Ascendancy Oath of the Maji stopped working in calculations

### ISSUE THREAD

**Issue by dspringsguth** [PathOfBuildingCommunity/PathOfBuilding#7111]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

When choosing Oath of the Maji, the defences of the equipped Body Armour are doubled if there are no socketed gems.

### What is the behaviour in Path of Building?

In an earlier versions the calculations were correct but one of the latest updates made it stop working. 

### How to reproduce the issue

This can easily be tested my making a new build and only equip a Body Armour without allocating skills.
1. Equip Body Armour
2. Allocate Oath of the Maji
3. See that it doesn't change the values

### Character build code

```shell
https://pobb.in/U3vdWilnfG_f
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/74304445/664a0a66-7661-4480-bed6-201763c78ba7)

**Comment by LocalIdentity** [comment]
Fixed by #7109
