### ISSUE TITLE
Enduring cry seems to be giving incorrect values for physical damage reduction and elemental resists

### ISSUE THREAD

**Issue by APWHY** [PathOfBuildingCommunity/PathOfBuilding#7122]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

When I am on a heirophant with 4 minimum endurance charges the in game estimated physical damage reduction value is 16%. After I cast enduring cry, that number goes up to 24%. I do not have any armour or any other sources of physical damage reduction.

I am aware that this seems to be a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3172 but I'm not sure that the documented fix actually fixed this particular issue.

### What is the value from the calculation in Path of Building?

In POB when I make a similar barebones character with 4 minimun endurance charges and no armour, it has 16% physical damage reduction without enduring cry and 18% with enduring cry ticked.

### How to reproduce the issue

Make a heirophant. Allocate Conviction of power. Add enduring cry as a skill and check it. Go to 'Calcs' tab and check Phys Dmg Reduct in the Armour window.

### Character build code

```shell
eNqtW92XorgSf579Kzg-z6iAn3N099jaX-e0017tmbn3vuyJEDU7gbgQ7Hb_-q0koGgbhIZ92EGo-qU-UpWqgh788eZRY4eDkDB_WDPrzZqBfYe5xF8Pa99f7r70an_8_ttghvjmeXUTESqe_P7bp4G8NijeYTqs9c2awVGwxvxHAmX_CVBb5PMNZv4U_cWCe-YOa9-Yj2vGEvku4ckvh6Iw_IY8PKy9YG9LUVAzUOhg3x0fnzwQHLDtBgCBYYMC5HAcPInlRxFnU-YCzQrREPA8RPwFc35hfh-waAtq1Ywdwa-K6HE6e56_pGQjflo20O3TYEbRHgcLjrgRwv-GtRGYCK3xA4HVd4hGgNOsNTJpb6Ig5BPkweV1nsUWY_dIVjetVrdp96xeq9lt2zqunyhwgv0YhfyFeKlV6u1uv2s2zVarb3XbLR37LMC3qxV2ONnhcUD4GKzr5BC2KO00opxsKTjwQG_W2zqOh3fgZlML_8I4opPZ4rogipLl8N9Pwjc3FPyRC1dQP659wnFu8hkjIfMLSZ2LeBxRCtGZi3aOQxzsECc5BRkzb0n8nDYZM0Zd9uofKHv1ptnXxkuA0fNK7cQ5ckkUTjEPcHjg7ug4p8hHYxYefapfRJDOcABJhZ9wNK8wLLDDIA-lWay63enbXatr97st28yx4mUc7dJPZIXzUxbSKmYoKs3H9Lhd5KUrDPwxgeaQi_NRLlhEc1LyY1azbH24_Z0mNNva9DfBb0cybep-9HmOVSd4x0SE58wztw-z49J2t1nv9ft9s93rt7vaI2SzD4mD6BS9ES_yIHe_oF_YT8H0Tf3GWm-4DwlLx9xravW_IwH-ANsY8tJH2DaIhTq-rmlnhc7RFGbLzDj-na-C-tF38kXkdz-QGTxVNWQtIFjmECmiNFlSnJvnuEwccXkOZbXYGvvxivt8Kj1h7GzuoXabI47zJejjEWH3Mm0riNO27WWhXrBtBv4pRwEzCcbLZjLteiuLq6Clbn0crPeLDcHULUadSDZG21w1rPM1zZ1rM58uV2jTpFkLmgQqZzffeVFUph0K0xnXbGebS5HnstQUQ1EKDC7OW3zPAvaXKO9pMbZR4LEoyOlwRZxLgeSwUE3RHLuRc3I6mdoYu6HQzuUVH8SitBDHiHPk_Jowd40LLVKI49BqSdZFtN1CzhDOzwsgzjwo20mqKvnSsq5TP8POzRXA4nTMv8CROvcChxM__ypnLPl1EUf2-TKdPOS5lzg4dAq5wYOkL5v4KUudyFrnQKeWq5OShDnbvxl7Bck3Ygxz7J1aeaihtLnOcBdg_5_9OX4zF3l6AVufzt0oEKGQW4dzjkt6iMkIhUCbII4MNy6If6CAIJ9bcjQUYhQ4mydw_R2idAmZYFhL35W_5DjpjlCOgwncE4sK5c8RzcTpg4YckImrR2_LAm7gN_HPDAV8n0yqJKG8AzghJ77sxyEfUVozFhv2OnJ3YqUX6KfDw3gLbbfYd08wXgKMDZRkF0cIIZUXPwwPhSD1Xm3XUGiTGq49ApBVM3wGAsCV1bG7nztm22p_ttqdtvnZbvZbTWEN0WWhYD86ZfUJSArNOk7N_aAfUSM9QdCWgnwafJ8_yYtPG8634ddG4_X1tb5FfMNW-A0OqLrDvMYWmECFL-EvQukXAdsYwX836-_jEd3w_0-m8Gs4lICNBHGgRn1hQ_0S4RsQ0Ea5vyFMIP0hbCQuvjGOQ_FM3Ex-DBZiyRD8HPB77IU3ewi5O1FYnI0-YiML6gXmav-keYY1HkRY7IsViqi4_58IUSJ83kzffVKDU58F3qF7AijwuTgZFOLLfiucMnp6Uk9GlMdgYrlkAyhHxwIZxE2cH9-U09DRUeoxok4o5Sa-QyMXWo44Gx02GEVLIZuYBItmwU10OkM6LPRpAPLExPeULRG1EpZ4PmyB7mvsiQ0xxRy5EIuNRw5KNIQmDQkHVzKeIdePVaUlI0rwnNyXm-Pd3b9TVo6vBc1EGbx2Ip2ZSHemn8MiX7nUR14cSMkihlgl3mJK3nh7xYaXW0xtInEprSwpHv1txCXgsOaR0PlzGa1WYhINmvBAjtlv7-5uxy-PP27jlJVmkdr-6UfeUkxP1b_Hg2WBZQVlhNEyVJfD2g-CX6UgE7A0oaHQi1K0DfEhZ8hdEktOgS8DTVJBz5sMsi9jHQn0SLdvOIAUt5ZDa4K1ch2eXxFKLSjKcjX8vowmJr56IFX4iQG6ahs0lpLDeT2KmHFr1REPM3jhcEBUu3L89IoluMgTsFvJijjidMx2ucgqiirDLo4DB6uzz_B3XLXqMeQIXQegHuqZ1Yhcxx0_zbCqHMhrraqe6tkn2EFa3dVDPfOhE2W-fF10GeVAlYH0jflyk0PQjAgVFabWs7cUH0j0gM98g4O4DtAhTSFHJSSZgROQZcT1YZyiyLCVHJBpLCSe6VnV-Eejg3iWkYlO5iEag6Zp9FBqjqBNZFmsqtvQ2i_uXTJcEHfpGvOrpxlGSAYVGv3jxxlBIvPvaMeIq_pXTbickWUlDCjkysPIprw8zHmXXh7xDmriX1p_x0_17N85EVXNBRRVveQCEUFVDkHEVjmE-XkhceSdZ5cQMn9BSYfB0JkJ7ECT4V8e-RM45HiGb3NCSbEuB8JRtUJYKpVf1LQwotqg8TuLrD2sSK4AwVn0kFHt5EM6TE4eMKLifTij5QDfvZsppSfjIfLdiRj8llRUzI2jLYAlkj1fKlePLj1HHTSSRkK2-KK0jwcTCw5twKv8_sMQHUXN-Icx73-ihe_VzX5H_Y67zE7cWULVNyFg-0DumWRhQfjfYa3bawOjGsQNZHMWN7viOul1oxCrF64_MdoyX95OtaExaQbZaYNKGXSswDNbQjcvOk7V9CguQ_SoXHWNzaT30rHcYMqN0XIfhogaaiJgWAX4kyXPMdrFMawKMExj8Yq250CdChTqVKBQEYwbBuF0DmAXAHjAkAzf-bbs3viQGS75pF2BT8wKMFoFDVLVnqwiyIpgyPKikNUv7kCr5P6xC4tcxEH3lO1wWGabXI6aTmGEwmqapdUs4tuRF1HMK9iCdgVp0S6tequwuYvs47mYY1ofTXyFlSsbou3Cxih_rFilEcrL0CpruFZVud0uJIm7N9TUofq81a7qtDar0cgq66LCFVTp1NKpRvN2aUHsohnLLGtss4LcXllMtavxQ6dk_VK-GilbQVUUinZVqaEyoI-0Fh-zRVV7siJXfDhGSu6kyk4Hq4JEUQWGWZVClWWt90CDRjzsUV_ZBMjFCzmZ-onFJ1uhGl_JOZJ8Ic78FVm_e70dhfj9Zz9LxihGfjyfOnz74-ANoy4OYlbsY28f_91U8l68m_7a9hJ9-k-XEqZ2NksSaod3712r07u-SvLCPGGz9ZKFZE3o80p-kbXgSNrg_E3_ey7v8FdV4m-KcIDdhXyZLT5iWGC6SmFc0TD-HpNROkd-WubuFWse3iElDD27d8U0p9-ApmS0-q1k5BlvlUHj_K8O_wWbVxp2
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8357340/43e196c7-2b65-46d9-bf96-936f21927d47)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8357340/78762f8c-b9d9-47b6-87b7-dafc5ba269c8)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8357340/84eb832a-83ce-40d1-b644-80ff75c39668)

**Comment by Wires77** [comment]
Warcry buffs get averaged out based on their duration and your cooldown recovery.  It's a bit misleading, but we went with the conservative path instead of assuming full uptime.  If you want to see the full buff value, change this setting in the Config tab:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1209372/0d1f281b-8fbe-490c-ad8e-89112eeeb007)
