### ISSUE TITLE
Sort item mods by DPS just like support gems

### ISSUE THREAD

**Issue by AzsyGaming** [PathOfBuildingCommunity/PathOfBuilding#714]
Pretty much the title, it would be great if it was possible to see mods on stuff like jewels sorted by DPS, perhaps even cluster jewel compatibility?

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1

**Comment by AzsyGaming** [comment]
What was fixed?
Jewel mods are not sorted by dps yet for example.

**Comment by LocalIdentity** [comment]
Didn’t read title pro0erly and thought it was referring to gems

**Comment by ppoelzl** [comment]
Whenever possible, we would rather want to follow the in-game mod order, for easier visual recognition. There is an open issue that proposes adding stat weights which would allow for similar functionality.
