### ISSUE TITLE
Impending Doom manual curse removal calculation with Hexblast

### ISSUE THREAD

**Issue by Warmachine237** [PathOfBuildingCommunity/PathOfBuilding#7143]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Id like to be able to see the DPS and Trigger Rate of Impending Doom on my Hexblast build, but the drop down options for ID only include Curse Expiry, Curse Overwrite or Vixens Procs. I would like a 4th option of manual removal with Hexblast.

### Describe the solution you'd like

Add 4th dropdown for Manual removal, and count cast speed as [1 / (total cast time for linked curse + enabled Hexblast skill gem)]

### Additional context

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/bd5108d1-8374-4c2c-81b8-2f9962d65f22)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/0681b3dd-b9c8-46d1-967c-cd8e32a3a76b)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/aed0c11b-82da-4e69-b2dd-13732611fc7e)

**Comment by Paliak** [comment]
Added to #6720 with [61447ce](https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6720/commits/61447ce54dbba32a5a682fc540efd92dd6a6496d). If you'd like you can download the branch here https://github.com/Paliak/PathOfBuilding/tree/capExpirationMode by pressing the green button on top right of the main file view window and run it using the executable found in the runtime folder. I'd appreciate if you could report on any issues you notice.

**Comment by Paliak** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6720 had been merged. Should be in next release.
