### ISSUE TITLE
Adding a second ring to the build which has only ES on it (energy shield) reduces total energy shield

### ISSUE THREAD

**Issue by vajura** [PathOfBuildingCommunity/PathOfBuilding#7145]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

I am only doing the build in PoB, but its just adding a plain white ES Moonstone ring

### What is the value from the calculation in Path of Building?

Adding the second plain white Moonstone ring (only energy shield on it) reduces my total energy shield. Same thing happens when the ES is explicit mods, or combined with other mods. I just did it with a Moonstone ring for ease of pointing the problem down. https://i.imgur.com/mnfKObM.png

This is not only a error with the preview when i equip it my ES drops for the previewed amount.

The build has no interaction that would cause this in any shape or form

### How to reproduce the issue

1. Import build: https://pobb.in/jVAQER06J3wk
2. In items select the second ring slot and put in the plain white Moonstone ring (or create new one with ES)
3. Total ES will drop

### Character build code

```shell
https://pobb.in/jVAQER06J3wk
```

### Screenshots

https://i.imgur.com/mnfKObM.png

**Comment by Peechey** [comment]
More info for devs: it has to do with the Evasion and Energy Shield Mastery that gives 20% increased max ES if both rings have an explicit evasion mod. Something with that mastery seems off. Even on a brand new build if you path straight to that mastery with zero gear, it's still adding the ES.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/92683202/b2de1142-5df6-490c-9eb9-564999386d01)

**Comment by Wires77** [comment]
I looked into this earlier as well.  Definitely an issue with it applying without any items equipped that has to do with this commit to support Utula's: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6288/commits/1f843dbb489ec71a6178aed618dcf2eaba083033

The mastery itself doesn't work because GGG changed the wording to include "explicit".  The code will have to be refactored slightly to support that.  Would be useful to have some tests to cover all these cases

**Comment by Paliak** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7182 has been merged. Should be fixed in next release.
