### ISSUE TITLE
Sources of "Bleeding you inflict deals damage X% faster" Don't appear in Calcs Tab

### ISSUE THREAD

**Issue by egocarib** [PathOfBuildingCommunity/PathOfBuilding#715]
The Bleed Duration calculation is correct, but when hovering over Bleed Duration, it only shows sources of "Increased Bleeding Duration" - it doesn't show node sources that reduce duration due to the "Bleeding you inflict deals damage X% faster" mod, such as Bloodletting.

![image](https://user-images.githubusercontent.com/3429497/78250655-c585bc00-74b5-11ea-8ffc-6c6347f9b95c.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
