### ISSUE TITLE
Hello, I have a feature suggestion to offer

### ISSUE THREAD

**Issue by pandacg461** [PathOfBuildingCommunity/PathOfBuilding#7156]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I am a POE player in China. The POB you developed cannot be used in POE in China, but we hope to calculate our own DB. As an unprofessional programmer, I hope to be able to connect to your api interface and use it to calculate on the web. Currently I am developing the web version of pob. This is the link: https://poe.zpdyit.com/import

### Describe the solution you'd like

I don’t know if you understand what I mean. I hope you can have an API interface for skill damage calculation, etc. I can get the calculation results through the API interface. As a fan of Poe, I hope that tools similar to PoB can also be used in China. , so I hope you can consider it

**Comment by Wires77** [comment]
There is a translation effort called [PyCharm](https://github.com/Chuanhsing/PoeCharm) you might want to look into.  Still a desktop application, but provides translations for all of the strings in PoB.  Other than translations, is there another reason PoB cannot be used in PoE in China?  We did implement support for importing Chinese accounts at one time, but as none of the primary developers play in the Chinese realm, it's difficult to maintain.

As for an API, there isn't a web API, as PoB has limited internet connectivity (and there are no plans to add one).  If you want to use the calculations, they can be accessed via a headless version.  See https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/HeadlessWrapper.lua and some examples of how it's used in [our test files](https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/dev/spec)
