### ISSUE TITLE
Penance Brand of Dissipation and energy

### ISSUE THREAD

**Issue by ghostoo666** [PathOfBuildingCommunity/PathOfBuilding#7161]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording in-game?

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/39352650/0b744d3d-c970-4d2f-a5a9-8fb7bb550f23)

### What is the wording in Path of Building?

Same as screenshot. Does not function as such

I believe whoever coded the new brand did so by reading directly off of the wiki, which has not seen an update in its mechanics description since the brand was reworked (description of mechs on wiki still reads like the one added by Shalq on May 18, 2021).  Penance brand of dissipation has no clause indicating it stops gathering energy at 20 - that was the old penance brand.  The new regular version explodes at 20, and the new dissipation version infinitely gathers energy with no cap.  What we have in POB is some hybrid child of the wiki description and the new brand's description with a huge assumption in place.  The reason the gem is so broken right now is because it scales infinitely.

**Comment by sida-wang** [comment]
I recall a guildmate testing it and the radius increase seemed to cap at 20 energy. If I had to guess I'd think that would mean the damage scaling would cap at 20 too but that was tested using phys to light and brutality.

Do you have any further references that can point towards the scaling being infinite that we can look into?

Thanks

**Comment by sida-wang** [comment]
Closing this as the updated gem description from 3.23.0.4 clarifies the energy limit of 20.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/42928828/e44e18cc-2b55-4824-83d5-12e2cbf8ee71)
