### ISSUE TITLE
Latest update crashes my PC

### ISSUE THREAD

**Issue by Tesked** [PathOfBuildingCommunity/PathOfBuilding#717]
Latest update can cause OpenGL kernel exceptions and a 0xc0000409 (STATUS_STACK_BUFFER_OVERRUN) error which either crashes your entire PC or simply your gpu. Most of the time it will not recover from the kernel exception as the desktop window manager also starts to crash.

Currently running on driver 442.59 ( gtx 970 ) and not the latest ones (as of now 445.75 ), to see if it was a driver issue but to no avail

> Unable to recover from a kernel exception. The application must close.
> 
> Error code: 3 (subcode 2)
>  (pid=13756 tid=6424 path of building.exe 32bit)
> 
> Nome dell'applicazione che ha generato l'errore: Path of Building.exe, versione: 0.0.0.0, timestamp: 0x58a9a3a1
> Nome del modulo che ha generato l'errore: nvoglv32.dll, versione: 26.21.14.4259, timestamp: 0x5e5ff4dd
> Codice eccezione: 0xc0000409
> Offset errore 0x00cf5f8b
> ID processo che ha generato l'errore: 0x35bc
> Ora di avvio dell'applicazione che ha generato l'errore: 0x01d6091b3ddf40b5
> Percorso dell'applicazione che ha generato l'errore: E:\programmi\Poe\PoB\Path of Building\Path of Building.exe
> Percorso del modulo che ha generato l'errore: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5ef913e2bcf39373\nvoglv32.dll
> ID segnalazione: 65cc88ec-3777-4827-b585-1473356a1b9b
> Nome completo pacchetto che ha generato l'errore: 
> ID applicazione relativo al pacchetto che ha generato l'errore: 

> Nome dell'applicazione che ha generato l'errore: dwm.exe, versione: 10.0.18362.387, timestamp: 0x8e064b77
> Nome del modulo che ha generato l'errore: unknown, versione: 0.0.0.0, timestamp: 0x00000000
> Codice eccezione: 0xe0464645
> Offset errore 0x0000000000000000
> ID processo che ha generato l'errore: 0x1b40
> Ora di avvio dell'applicazione che ha generato l'errore: 0x01d6091d3b0361b6
> Percorso dell'applicazione che ha generato l'errore: C:\Windows\System32\dwm.exe
> Percorso del modulo che ha generato l'errore: unknown
> ID segnalazione: afd6277c-99e6-478e-85ff-1fea1a35ad52
> Nome completo pacchetto che ha generato l'errore: 
> ID applicazione relativo al pacchetto che ha generato l'errore: 

[DxDiag.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4423096/DxDiag.txt)

Crash report
[Reporttxt.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/4423275/Reporttxt.txt)

**Comment by ppoelzl** [comment]
This does not seem to be an issue that's directly caused by PoB.
