### ISSUE TITLE
Show All Configuration Error

### ISSUE THREAD

**Issue by lrp22** [PathOfBuildingCommunity/PathOfBuilding#7177]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

It should open All Configurations options.

### How does Path of Building behave?

When I click to see All Configurations it throws me an error. *only when I import my character items*

![Lua](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/50248380/b688d6f1-410a-408d-b74c-5d21a632f22d)

**Comment by Paliak** [comment]
Possibly related #7129

**Comment by lrp22** [comment]
@Paliak Indeed it is. Whenever I leave it fullscreen i can import all my items and show all conf.

Thank you Paliak

**Comment by Paliak** [comment]
Fix had been merged. Should be fixed in next release.
