### ISSUE TITLE
[Bug] Infinite Sockets...?

### ISSUE THREAD

**Issue by IdrisQe** [PathOfBuildingCommunity/PathOfBuilding#718]
I have _absolutely_ no idea what caused this- the item was previously fine... I did recently sort items, and delete a few, but then undid that with Ctrl+Z but then sorted and deleted a few again and this time kept it... But... I can't imagine that was the cause, as I didn't touch this particular item.
Running version 1.4.167.2
![image](https://user-images.githubusercontent.com/40530630/78353337-bc9cf500-755e-11ea-87cd-ff2f316cd151.png)
and if I click the item in the sidebar to edit it and fix the sockets, the following pops up until I dismiss it or exit the program. Relaunching did not fix the issue.
![image](https://user-images.githubusercontent.com/40530630/78353461-ec4bfd00-755e-11ea-86f2-121ff58a3c3c.png)

All I can say is this is a B=B=B=B=B=Bizzare occurance. 
Luckily it doesn't seem to affect my B=B=B=B=Build at all.

**Comment by LocalIdentity** [comment]
This was a bug that got introduced if you had open a build when updating from a certain version. You can just delete and reimport the item to fix it

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
