### ISSUE TITLE
 "Arc Chains An Additional Time" helmet enchantment is not applied to Arc of Oscillating, but does in game

### ISSUE THREAD

**Issue by bantbattlemage** [PathOfBuildingCommunity/PathOfBuilding#7187]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

By equipping and removing a helmet with the  "Arc Chains An Additional Time" enchantment, I have confirmed that in game this enchantment does apply to Arc of Oscillating.

### What is the behaviour in Path of Building?

In Path of Building the additional chain is not taken into account in the DPS of the Arc of Oscillating. So far as I can tell Awakened Chain & Chain Support do add DPS as expected from Arc Of Oscillating "15% more damage for each remaining chain".

### How to reproduce the issue

1. equip a helment with  "Arc Chains An Additional Time" enchant in-game and compare results to Path of Building as described previously

### Character build code

```shell
https://pobb.in/QjtiS4Kxw16K
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/24445170/fc08f063-8db9-4c21-88ae-e93245530a3e)

**Comment by Drox346** [comment]
Looks like it's related to this #7126 
PoB currently sees Arc and Arc of Oscillating as entirely different gems. Therefore mods applying to Arc won't work for Arc of Oscillating.
