### ISSUE TITLE
Vortex of Projection cast on Frost Bolt uses 50% 'increase' instead of 'more'

### ISSUE THREAD

**Issue by Catastropherz** [PathOfBuildingCommunity/PathOfBuilding#7202]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

![Vortex of Projection](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/106801821/51b3c545-0295-4422-8a37-d678158df2e9)

### What is the value from the calculation in Path of Building?

![increase](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/106801821/c1dbbffa-94e9-4c7e-8752-69095ace2c53)

### Character build code

```shell
https://poe.ninja/pob/1068
```

**Comment by LocalIdentity** [comment]
Fixed already on dev
