### ISSUE TITLE
Enhancement: A changelog of modifications

### ISSUE THREAD

**Issue by NGRThomson** [PathOfBuildingCommunity/PathOfBuilding#7204]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

No specific problem or issue. 

I often try to help people with their builds from time to time and it can become difficult to remember the exact changes that were made.

### Describe the solution you'd like

It would be nice to have a simple changelog of the differences that are made. 

Just a list of any changes to items, passives or config would be a great start. For example:
* Item > Weapon 1 > Paradoxica removed
* Item > Weapon 1 > Beltimber blade added
* Configuration > Are you fortified? > Turned on
* Skills > Splitting Steel > Lifetap modified > Quality from 0 to 20

This way I could help a person and instead of writing out every little detail you can either copy and paste the changelog or if it's part of the PoB link (which I imagine would be tough) it can just be linked back to show what was changed.

### Describe alternatives you've considered

I guess some form of version control where PoBs can be compared side by side so that you can just see the differences. This might be a little easier as it's not actively tracking changes but rather just providing a diff. 

### Additional context

If this is fairly simple then I would like to help myself, I have good experience in python, JS and some Java but have not really started with Lua, if this is already logged somewhere and just needs to be exposed to the UI in some way then I'd love to have a go at it.

**Comment by Wires77** [comment]
I'm afraid this will clutter the UI quite a bit no matter how it gets implemented.  There has been this idea in the past for leveling guides on when to allocate passives, but it's just visually distracting.

Some alternatives:
1. Utilize the Compare checkbox in the tree tab for tree changes
2. Save the imported build, make your changes, then save a separate copy of the new build.  Then you can run a diff tool on each saved XML file and find what changed between the two.  There may be a website that even compares two web links for you if you'd rather not save each time, I'm not sure.
