### ISSUE TITLE
Timeless Jewel bonus passive stats are not displayed / Find tool has zero results

### ISSUE THREAD

**Issue by Darentei** [PathOfBuildingCommunity/PathOfBuilding#7206]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When slotting in a Timeless Jewel, it is expected that passive nodes in its radius are altered to grant new or additional stats. This can happen to any node or keystone and varies depending on the jewel.

The 'Find Timeless Jewel' tool can be used to search for jewels that grant specific bonuses that suit your build. 

### How does Path of Building behave?

Slotting in any Timeless Jewel will correctly alter keystones, but other nodes remain unaltered, although sometimes they display a default bonus value; Brutal Restraint for instance defaults to +4 dex on small nodes. Copying any jewel off of trade will not display differently.

The 'Find Timeless Jewel' tool returns zero results no matter what parameters are used.

### How to reproduce the issue

1. Open any build or create a new one
2. Path to a jewel socket
3. Allocate nearby notable passives
4. Socket a Timeless Jewel in the jewel socket
5. Notable passives in radius do not change

NOTE: I've already shared the provided test PoB with others and they did not experience this issue. It was made for the express purpose of testing if the issue was related a specific build/save; it is not.
Personally I've experienced the issue before, and it was not permanent. However currently I am unable to get functionality back no matter what I do, including a full restart.

### Character build code

```shell
https://pobb.in/BnrDmKGSViMK
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/2286784/30dc490f-2b31-4b4a-9e2a-64160fc2f850)

**Comment by Regisle** [comment]
Your timeless jewel LuTs are probably corrupted, either delete the files in `%AppData%\Path of Building Community\Data\TimelessJewelData` or you can try reinstalling

**Comment by Darentei** [comment]
I will try, thanks.

**Comment by Darentei** [comment]
Reinstalling fixed the issue. It does seem to be a reoccurring issue, but at least I know how to fix it next time. Thank you.
