### ISSUE TITLE
Feature/Calc Failure when toggling a Thread-of-Hope Jewel (2.38.4)

### ISSUE THREAD

**Issue by abrey66** [PathOfBuildingCommunity/PathOfBuilding#7208]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Yet another issue with Thread-of-Hope (ToH) Jewel.
Value/Behaviour in game: That is not the point, since the ToH is protected in game --> you have to out-spec all unconnected passive points in order to be able to remove the jewel. PoB is there to analyse scenarios efficiently ! 

### What is the value from the calculation in Path of Building?

Removing the ToH will erase all unconnected points (Good!) - re-inserting the ToH will leave the "hidden" associated points un-allocated (Very bad!) The counterargument that the user might wish to allocate different passives with the same ToH is not valid. Even if he wishes to do so the few unconnected points are clearly visible in the tree. 
Solution: Cache the distant, unconnected points within the jewel. You might also prompt the user on re-insert that these are re-allocated (not necessary, imho).

### How to reproduce the issue

Insert a ToH, allocate some points on the ring, remove the ToH, re-insert the ToH.

### Character build code

```shell
no necessary.
```

**Comment by Wires77** [comment]
I don't think we'll be implementing this.  At the extremes, this could be caching many nodes 4 times per socket on the tree, and that's just for ToH jewels.  This would want to be implemented for every radius jewel in the game, which ends up being a lot of extra data in a save file.

I'm also not sure how often this feature would be used.  If you're removing a ToH, you're usually replacing it with something different, or using a different size.

**Comment by abrey66** [comment]
Please not that I am referring from a players perspective and try to add valuable features. Ty for your comments. Allow me to adjust the strong words in your evaluation: 

1. "lot of data for many jewels" - what 'many' jewels are you referring to? Aren't you storing passive structures already, if the user usefully wants more than one passive tree? Don't you use an OO-approach?

2.  "rare use of feature" - POB is an excellent tool to COMPARE two or more scenarios. Haven't you watched top-streamers yet that go "back and forth" already in-game? Toggling items and gems, then comparing values on the skill-tooltips or status windows? Or in PoB switching + going to Config and Calculate-Tabs? 

Summary: If you don't want to implement a consistent "convenience feature" I suggest at least a warning on removing the ToH that passive allocations will be lost.

Ty for consideration.

**Comment by Nightblade** [comment]
> Allow me to adjust the strong words in your evaluation:

What strong words?


Are you aware that if you remove ToH by left-clicking the socket on the passive tree you can undo that action completely with <kbd>Ctrl</kbd>+<kbd>z</kbd> ?
