### ISSUE TITLE
error with socketed jewel

### ISSUE THREAD

**Issue by vadimXionov** [PathOfBuildingCommunity/PathOfBuilding#722]
when i put my mouse on this jewel socket in my PoB
![GH2](https://user-images.githubusercontent.com/63174991/78464717-66ae8580-76f5-11ea-9bb5-d76823b9f755.png)
it start to show this error every 0.1 second 
![GH1](https://user-images.githubusercontent.com/63174991/78464726-88a80800-76f5-11ea-8601-9d0f7bc91710.png)
and if i press Esc or F5 it shows again infinitely.
This is a jewel that socketed in this slot 
![GH3](https://user-images.githubusercontent.com/63174991/78464745-ba20d380-76f5-11ea-8157-b2126bef8138.png)
my profile poe https://www.pathofexile.com/account/view-profile/vadimXionov/characters

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
