### ISSUE TITLE
Passive Tree Node Power - Filter to only show notables (i.e. for best anoint search)

### ISSUE THREAD

**Issue by justinryder** [PathOfBuildingCommunity/PathOfBuilding#7220]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

The new filter to only compute node power for 5, 10, 15 node distance is awesome for speeding up the search! When searching for anoints though, it would be helpful to have another option to filter to only notables for quicker comparison.

### Describe the solution you'd like

Add another filter option to the node power filter dropdown that only includes notables in the power report and doesn't consider needing to path to them for the diff calculations.

**Comment by LocalIdentity** [comment]
Searching for anoints is already handled if you select the amulet in your build and click on the anoint button. There is no need for it to also exist on the tree tab
