### ISSUE TITLE
Sort Attribute Requirement Popup on Calcs Tab

### ISSUE THREAD

**Issue by z1zman** [PathOfBuildingCommunity/PathOfBuilding#7228]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

There does not appear to be a specific order to the sorting of the attribute requirements pop-up on the Calcs tab.

### Describe the solution you'd like

It would be convenient and useful to have this sorted either ascending or decending to see what gems/items have the highest requirements for use. While generally easy to read, a simple sort would be speedier!
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/74015504/95d4c7b1-6a77-4d9c-8c42-3e3bf87d32b4)

**Comment by duiker101** [comment]
This would be covered by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7211

**Comment by Paliak** [comment]
Should work as expected in latest release 
![obraz](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91493239/c4cf20bc-d0d7-4f91-935a-8cd314af198b)
