### ISSUE TITLE
Ngamahu, Flame's Advance calcualted differently than in-game

### ISSUE THREAD

**Issue by bantbattlemage** [PathOfBuildingCommunity/PathOfBuilding#7230]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

The Chieftain ascendancy passive "Ngamahu, Flame's Advance" seems to be calculating values differently than in-game. I haven't figured out whether PoB or the game is correct, but there is definitely a discrepancy.  I created a character in PoB and then used an old Standard Chieftain I had to actually make the character in-game using gear I had bought while building the char in PoB. PoB says I should have 2,053 STR while in-game I only have 1,932 STR.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/24445170/678847f5-5ac4-474d-9276-12f361742b60)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/24445170/687d774e-2437-412b-bda9-f3cc6fec5cc8)

### What is the value from the calculation in Path of Building?

Per the previous comment, in-game I have 1932 STR while a pull of this character and it's gear PoB calculates 2,053.

### How to reproduce the issue

Allocating and unallocating the "Ngamahu, Flame's Advance" ascendancy node shows that this is the source of the discrepancy, however I am not certain exactly what is being done incorrectly or if the game or PoB is correct.  If I unallocate the node in PoB I lose 285 STR, but in-game I only lose 164 STR.

Additionally, in-game with this node allocated it shows a radius around any jewels it is affecting in the tree. PoB does not show this radius.

### Character build code

```shell
https://pobb.in/KAxM6kUl9SeZ
```

### Screenshots

Showing the missing radius indicator:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/24445170/158420ea-747b-4855-973d-b0f06d7c20c2)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/24445170/cd47177c-b5aa-4107-893b-c205b6039fe0)

**Comment by bantbattlemage** [comment]
Apparently this is a duplicate, I had searched for "Ngamahu" and nothing came up. https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7209

**Comment by Wires77** [comment]
Unfortunately Github searches only open issues by default, so if there's a fixed issue that hasn't been released yet we'll often get duplicate reports since the closed issue wasn't found.
