### ISSUE TITLE
Consecrated Path's 20% more Damage to Nearby doesn't seem to apply

### ISSUE THREAD

**Issue by tsunko** [PathOfBuildingCommunity/PathOfBuilding#724]
Consecrated Path states: "Deals up to 20% more Damage to closer targets"

When increasing "Melee distance to enemy" (or setting to 0 for max effect), there is no change to any DPS calculations. Skill Hit Damage also does not report any more multipliers being applied.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
