### ISSUE TITLE
Not importing all gems in vaal caress

### ISSUE THREAD

**Issue by pedrolopa** [PathOfBuildingCommunity/PathOfBuilding#7246]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When you click import "items and skills", it should detect all gems in vaal caress.

### How does Path of Building behave?

It only detects vaal discipline, and 3 gems (impurity of ice/fire/light) are missing in skills tab.

### How to reproduce the issue

equip vaal caress
have 4 gems in it
import items and skills

### Character build code

```shell
https://poe.ninja/pob/12E6
here is the aura bot of Hypijump (public account)
in game, his gloves have 4 gems, but pob only detects one (vaal discipline) when importing.
```

**Comment by sida-wang** [comment]
Thanks for the report. This is fixed in #7189 and will be included in the next release version.
