### ISSUE TITLE
Player is Cursed By - Not functioning

### ISSUE THREAD

**Issue by ThePunkdog** [PathOfBuildingCommunity/PathOfBuilding#725]
As you can see by the SS linked below, using Version 1.4.167.2 I am unable to modify my resistances by setting the curse levels in Player Debuffs section.

https://i.imgur.com/MXYcr7o.png
https://i.imgur.com/atOZksg.png
https://i.imgur.com/wglqJOH.png

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
