### ISSUE TITLE
Inner Conviction has been changed to The Agnostic

### ISSUE THREAD

**Issue by qbishop1** [PathOfBuildingCommunity/PathOfBuilding#7262]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

The title is self explanatory.

### How does Path of Building behave?

The title is self explanatory.

**Comment by Wires77** [comment]
The title is definitely not self-explanatory, so I'm closing this issue.
