### ISSUE TITLE
The keystone Inner Conviction in path of building is not the same keystone in the game.

### ISSUE THREAD

**Issue by qbishop1** [PathOfBuildingCommunity/PathOfBuilding#7267]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Where there is the keystone Inner Conviction in Path Of Building, there is the keystone The Agnostic in the game. They are not at all similar.

### How does Path of Building behave?

The keystone represented in path of building is incorrect.

**Comment by Regisle** [comment]
Inner Conviction is not a keystone naturally on tree, its added by the timeless jewel which you likely have in path of building but not ingame, you need to provide a build code and more information

**Comment by Wires77** [comment]
Regisle is likely correct, but without a build code it's hard to confirm.  Please fully fill out the issue template in the future.
