### ISSUE TITLE
Exception thrown when starting PoB

### ISSUE THREAD

**Issue by XtolotosX** [PathOfBuildingCommunity/PathOfBuilding#7271]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

When i open PoB i should see a build list or last opened build.

### How does Path of Building behave?

When i start i get an exception thrown, see screenshot_01.png when i hit F5 as stated i get the same message, when hitting enter i get another exception screenshot_02.png.

I did an uninstall and reinstalled it, stays the same. Tried to clean up inbetween and also tried installing to a different folder, issue remains. Did not change anything manually on my system the last couple days that might impact this.

### How to reproduce the issue

As said above it just happend out of sudden and remains. That why i also think it's some OS related issue.
Running Win 11 Pro.

### Screenshots

![exception_01](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/18445200/0547f092-e722-4f21-985d-927884d04b68)
![exception_02](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/18445200/e67d567f-a62d-4cca-b3f8-d603089bad1d)

**Comment by Wires77** [comment]
This looks like a OneDrive issue.  If you navigate to and open your Documents/Path of Building/Settings.xml file manually through Explorer it should work

**Comment by XtolotosX** [comment]
Ok found the settings.xml, it's empty currently. 
What i am supposed to do with it? 
=> Just open as stated above does nothing to the issue.
=> Or add some OneDrive related config there?

**Comment by Peechey** [comment]
Usually this is a last resort but if the file is already empty there's really no difference. Curious how it got empty but anyways: 

Make sure PoB is closed, delete the file, and then open PoB. Should create the file with default settings when it can't find it.

**Comment by XtolotosX** [comment]
That worked perfectly fine! You made my day.
Playing PoE without PoB is a pain!  
Thx a lot for the quick and awesome support.
You're doing a great job!
