### ISSUE TITLE
Contribution Guidelines outdated - How to get in touch?

### ISSUE THREAD

**Issue by samisalami** [PathOfBuildingCommunity/PathOfBuilding#7279]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Is your feature request related to a problem?

I would like to get in touch with the contributors of the project, according to the contribution guide lines a dm should be sent to wires or local for an invite to the discord, but dm's aren't a thing (anymore) on Github!

### Describe the solution you'd like

I don't know if the Discord Server still exists, but maybe make it public and add role restrictions and an onboarding process directly there and update the contribution guidelines.

### Describe alternatives you've considered

I have considered contacting Local directly via Twitter, but wouldn't wanna spam him unnecessarily!

### Additional context

Ofc. this is not a real feature request, neither a bug, so this issue might seem a little memey and maybe it is, but considering my options I saw it as the least intrusive and most appropriate way to get in touch :)

To elaborate I am a professional software engineer working in the field for almost 15 years now (stuff on github tho is mostly just some very old side stuff, as my work stuff happens within orgs). However my biggest expertise is with modern web technologies and I would really like to contribute with that to the community. I have had ideas myself regarding making more specialised build helpers as sort of an extension to what PoB does, additionally I have wondered if there was ever a way to port PoB to a hosted Web App (whether you are a fan of that idea or not) for greater accessibility and easier deployment flow and modern UI.

Well tldr: I would really get into touch and talk about these ideas! You can also get directly into touch via my very passive twitter/x account @SamiSalamiGer!

**Comment by Nightblade** [comment]
I think the idea is to add `wires77` or `localidentity` to your friends list on Discord, then ask for a link to the PoB server.  Maybe the docs could be a bit clearer there.

**Comment by Wires77** [comment]
Invited!  Discord server is kept private so we can focus on development work and have feature requests/bugs contained to GitHub for the most part.
