### ISSUE TITLE
2.39 update (mana reservation efficiency problem on Precision granted by Hyrri's Truth)

### ISSUE THREAD

**Issue by ConKou** [PathOfBuildingCommunity/PathOfBuilding#7287]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Pretty much title. After 2.39 update the 100% increased mana reservation efficiency by Hyrri's Truth is not applied on Precision. It was working before the update.

### What is the behaviour in Path of Building?

.

### Character build code

```shell
https://pobb.in/1hrV5DvRNpv-
```

### Screenshots

![Screenshot_83](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/74437021/f934b9a8-696c-4986-a2e4-67d494520460)

**Comment by Paliak** [comment]
`activeSkill.skillCfg.skillGem.gameId` does not exist but is needed for SkillName condition.
