### ISSUE TITLE
2.39.0: Error: In 'OnFrame': Classes/PassiveTreeView.lua:749: attempt to index field 'title' (a nil value)

### ISSUE THREAD

**Issue by ollathir75** [PathOfBuildingCommunity/PathOfBuilding#7295]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

![error](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/105932319/a137b2dc-7bfc-4a6e-9736-8ca6147fb79f)

### What are your system specifications and configuration?

Windows 10 Pro
Processor	AMD Ryzen 9 3900X 12-Core Processor               3.80 GHz
Installed RAM	64.0 GB
Device ID	99560018-D90C-4EB2-B05D-8EF5164938B9
Product ID	00330-80000-00000-AA212
System type	64-bit operating system, x64-based processor

### How to reproduce the issue

Updated to latest today (2.39.0)
Imported a PoB via link: https://pobb.in/BihdhJL5jLVJ
Upgraded to current version
Selected one of the Ngamahu placeholders and edited to be magic instead of unique, saved.
Click on Tree, get error

### Character build code

```shell
https://pobb.in/BihdhJL5jLVJ
```

**Comment by LocalIdentity** [comment]
Fixed in 2.39.1
