### ISSUE TITLE
Discipline mana reservation cluster jewel Notable not working with Vaal Discipline

### ISSUE THREAD

**Issue by dextradei** [PathOfBuildingCommunity/PathOfBuilding#7298]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

This just happened with the most recent update 2.39.0

When I import my character, pob says I have negative mana reservation but in game I have positive mana.  Before updating pob I had positive mana.  I toggled all the skill gems individually in pob and in game and compared my mana and discovered the discrepancy was coming from a Vaal Discipline gem with Discipline skill enabled and Vaal Discipline skill disabled.  If I replace this Vaal Discipline skill gem with a normal Discipline skill gem, pob mana reservation is correct and mana total matches in game.  It is only a problem with calculating mana reservation on the Discipline skill of the Vaal Discipline gem.

### What is the value from the calculation in Path of Building?

My maximum mana in game is 37.  pob is calculating my mana to be -28.

### How to reproduce the issue

Here is an export of my pob - I imported this from my character (Busketeer on account dextradei)
https://poe.ninja/pob/146N
Notice the mana is negative
Change the Vaal Discipline gem to normal Discipline gem and notice mana is back to positive
they are supposed to have the same reservation - the Discipline gem matches what is in game.
I tried just putting a vaal discipline on a blank pob but the reservation was correct there, so it's some interaction with items/skills on my character - i have various sources of mana reservation and gem levels

### Character build code

```shell
https://poe.ninja/pob/146N
```

### Screenshots

![Discipline](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/3957615/0a15b1eb-df46-46df-9874-e845cd1d9e8b)
![VaalDiscipline](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/3957615/cd5fdd8c-7043-458a-9ddf-3935b675c589)

**Comment by LocalIdentity** [comment]
Issue was caused by this PR https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7224
