### ISSUE TITLE
2.39 Update breaks builds with cluster jewels. Can not load them.

### ISSUE THREAD

**Issue by Bagslap** [PathOfBuildingCommunity/PathOfBuilding#7305]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

It should work as usual

### How does Path of Building behave?

Can no longer open from library, nor import through client function, any build with cluster jewels. Specifically, I can not open or import GhazzyTv Poison SRS necro. Was using it fine until 2.39. 

### How to reproduce the issue

Use previous version of PoB Community Fork. Import pobb code from the relevant guide page link, at poe vault. Enjoy reading and following build guide in PoB. Update to v2.39. Try and open build. Try and import build. Delete and try it again.

The solution is to revert to an older version of PoB community fork.

**Comment by LocalIdentity** [comment]
Fixed in 2.39.1
