### ISSUE TITLE
Precise Commander notable incorrectly scaled

### ISSUE THREAD

**Issue by RosvallM** [PathOfBuildingCommunity/PathOfBuilding#731]
The Precise Commander notable on medium clusters has incorrect scaling applied.
Both the Critical Chance as well as the Critical Multiplier gets scaled with "increased effect of Non-Curse Auras from your Skills" in PoB. However this is not the case in-game. The case is easily tested, both through tool tip discrepancies as well as through testing with Tailwind on crit boot mod, with 100% PoB Crit chance.

https://poedb.tw/us/skilltree.php?n=Precise+Commander

**Comment by ppoelzl** [comment]
This bug has been fixed at some point.
