### ISSUE TITLE
Error in Calcs tab when hovering over the Aura and Buff Skills section

### ISSUE THREAD

**Issue by MrCatFace515** [PathOfBuildingCommunity/PathOfBuilding#7314]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

When I hover over this section, it should just read the active Aura and Buff skills.

### How does Path of Building behave?

Upon moving the mouse over the Aura and Buffs section of the Calcs tab, it immediately pops up an error message that will be shown below. 

### How to reproduce the issue

Import the build
Go the the Calcs tab in POB
Move the mouse over the Aura and Buff Skills part of the skill details

### Character build code

```shell
https://pobb.in/eXFjOXB-5jTT
Note, this is not my build, but Mathils most recent concoction.
```

### Screenshots

![pob error](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48973217/f08a5040-cc2c-4250-86c9-bf7dd5fefa48)

**Comment by Wires77** [comment]
This is because both types of golem supply the same stat.  A workaround is to disable one of them.
