### ISSUE TITLE
Error message after removing a gem from a group (Forced Active) and trying to add a new one

### ISSUE THREAD

**Issue by fezz8386** [PathOfBuildingCommunity/PathOfBuilding#7316]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/157768424/3b059b5b-afdf-4a96-9dbe-29a13b4cb4a0)

The problem occured after one skill group got the assignement "Forced Active" although there is another active group.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/157768424/9ee61fb2-8e92-4027-9a34-6ef7db38feac)

### What are your system specifications and configuration?

Windows 11 Pro

AMD Ryzen 7 7800X3D 8-Core Processor    

NVIDIA GeForce RTX 4070

### How to reproduce the issue

After I remove one gem (e.g. Maim) from the group that is 'Forced Active" and I try to add a new one, the issue occurs each time.

### Character build code

```shell
https://pobb.in/izKoERGPyp5p
```

**Comment by Paliak** [comment]
Related to  #6898
