### ISSUE TITLE
Badge of the Brotherhood not being shown as frenzy charge source

### ISSUE THREAD

**Issue by aiolos01** [PathOfBuildingCommunity/PathOfBuilding#7326]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What is the wording in-game?

Frenzy charges

### What is the wording in Path of Building?

10 frenzy charges are being shown correctly. However the source table lists only the 3 base charges. The other 7 come from Badge of the Brotherhood and should be listed in the table.

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31035929/fc969406-2c5e-49b4-8eba-dec60aaf7a21)

**Comment by Nightblade** [comment]
Tip:  you don't need to use an image hosting service -- it's built in to Github.   You can just copy-paste, or even drag'n'drop the image files directly into your issue report or comments.
