### ISSUE TITLE
Round decimals from the large numbers

### ISSUE THREAD

**Issue by imTheSupremeOne** [PathOfBuildingCommunity/PathOfBuilding#733]
Decimal values are somewhat useless and they take extra space and time to process a number. I'm using commas as decimals inside settings, but dots are also looking like a commas and even though it has only 1 number after it, it's still confusing and this amount of accuracy is useless with PoE numbers as if you round just a 100, the maximum rounding error would be 0.5%, and in PoE some numbers reach millions.  

Like imagine if after every number, even whole, even zero would be a ".00" tail?..  Without decimals for almost every number I would say that interface feels much more "right" and cleaner...
![image](https://user-images.githubusercontent.com/13508453/78637521-301e6980-78b3-11ea-9928-6043b2a82896.png)

**Comment by ppoelzl** [comment]
> Decimal values are somewhat useless

That seems to me like circular reasoning, among a wealth of other logical fallacies in your argument for rounding decimals.
PoB aims to provide players with accurate numbers so they can make well-informed decisions creating their builds.
