### ISSUE TITLE
coruscating elixir vs ruby flask with increased effect

### ISSUE THREAD

**Issue by wildmastin** [PathOfBuildingCommunity/PathOfBuilding#7331]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

in game it works as intended the strongest implicit of flasks applies, checked it with RF, ran out of es just at the end of elixir, then used coruscating elixir while the regular ruby flask with 67% inc effect was in slot (have mageblood) and ran out of ES 2.5-3 sec later than in first case

### What is the value from the calculation in Path of Building?

Path of building in case you are wearing MB and have ruby flask with increased effect if you activate coruscating elixir calculates your fire damage taken multiplier from coruscating - not regular flask which is stronger in that case, didn't check if this issue persists in case of using flasks normally without mageblood

### How to reproduce the issue

just character with active coruscating elixir and ruby flask with increased effect enchantment or inc effect prefix or both

### Character build code

```shell
eNq1G11z4jjyefgVKqruXrYmgPlIJkd2i0C-qpIJC8nM3dOUsEXQjmxxspyEnZr_fi3JBsMgY2PfPGSM1d_danU3ov_Hu8_QKxEh5cFFvXXSrCMSuNyjwctF_fnp-uNZ_Y_fa_0xlovH-WVEmVr5vfahr58RI6-EAV4dSSxeiPySUGp_A0pLHMgF4cED_ouLG-5d1D_zgNTRDAcelcknl-Ew_Ix9clGfuoBcRzh0SeANN-9jwAUW2JVE3Cuug0jyB-7BqhQRrPqYBlPufifyRvBoqYV6peTNwNw9jB8nTymRaJAWCTT60B8zvCJiKrFEIfy5qA_AMPiFjLAPf4EaZhGQap40nU69kYlyGYlQFsGbLgnx1qCtE8cGOBbkaj4nrqSvZCioHC5w4KaY2PCKwj5ETNIlo0SkpOraMG5_Id6zgT5xidloPN2yy9lZNjiXh6X-SuXikoEZ8xNXKHcvAZWkGM6Y05AHxZXYwrBaP2IMNlku2AkJiXjFku5IY6XN_RkNipjoAQd4yMMc9leQYyJg68pCCFPictjtRXkUxLync5IfspAeMUJRaY7T42qaF64w4eMEmkCOywc55RHLCSk3WcexQo3Iew6ou0DmovXKpT58Dsmm9_LV7XgN-anVOjntnH06azm99umpNXEvViF1MXvA79SPfMiYT_g72TBsNXsZ4fKykAEkBRtyr9e24V5TQWxo3XYzI1Uw7wh2cAzw8Ai8Bzi-b6EuWMNKPGPkHDXfwaynnc7cKujjfJ6B2G2dZW3CXOaHw9k9V9B3gZtvbz8HQmfm9Jme6d85mcCeU8UDCJ8bZ8Mm3rspzAPMXkgQc1zlU-meEHdxA16aYEnyZepNnGWbVsHmMq0C3GPabk6EAkZSiBYjnXzKQipopquAiJfVdEEJ84pBJ4IN8TJHQlVmTmPnMvc2u0IRk0YtaJKvWHj5jp2iMr3iMJ3iW71scxnwfIFJoPAEBI_krbHHgv-lqnhWDG0gfB6JnA43wLkUSE4n07NMiBe5-Y7DSwY9V17pQSrGCmEMpMTu9xH3XkghJoUw1g2VRp1GyyVkDOX7vATUGQulOE3VNqfdw8CPELfp7dtyTrNO4x0OH3vNw9C7LA6XGPm57KDkZqVLhALKbMBzs1h79AFygw85X_fXDzx1HFvdA-1Xrl5KA-bs6cb8DSRfqBlJWAwaSqk1gr3GEyT4e5Wb_hZ4LgZXgRcJtRdy89jF2MfmifqQN8NwhCVGXlyBf8GC4kA6eoATEizcxT24_hozNoNUcFFPv1WfdhBbiW_7DT2jUk93_pILici7-m-MhVxd1OeYhcQA6jdAJ5Q00L005B3G6mi64G8D71Vp8cQ5CxMkhJdLEnhbNJ4EIQgnWcRVQmgd1Qfk41DCEWWiMlRCp0Zcd54yIwo4CAC1zNlZu61UVB0YFqvBNmBAQS4JvFKTNqcdD9EMJcX2Q_95cq8fPiykXIbnjcbb29vJEssFn5N3OHVOXO43loAEAn8Mv1PGPiqyjQH8u3wZ6H-aUCOh1DfTtbBhPqm9KCjIbHzZUIpqqytLqIfPXJJQramXyYf-VLEKUQiOuCF-eLmC_XOtqoSd4URsSgU9JdIEQxonGft5ZI4jpt7_GWFGlWe1jTbv782MMuDCX3dfQAx8qzK9ofm0WirjD-7vzcqAyZicYpg42jg0FglRbxNpRiv1OMTM1Vr374JlJFGgB5g-Dd1vs2g-V9NIYCGFHrBeXV9fDZ_uvlzFGyKNon3yLYj8mRrBmf83aWtK9PmMwmgWmseL-hdK3rQgIyIxZbBJXc4YXoZkHapa6FgDBngZ1DQUdHDJFHM_rQ2AndLVOxGws16gsHMFJVa51usHhDIMVdGnEoiNmpoZ2gmZumII-9IUpRZL6amsnYoalFrVUYsZuJCTMLNyjlcPWEKqsIV9R-fUVbk32-UqyA1Uhl1cF9K2u8rwd1wU2WnoIayNgFm0I5vRqg07Xs2wqp7mWq1qVu3oI-Jiq-5m0Y687nN4AGayUVlDZVD6zAMd5LBpBpSp-sXq2StG1iB2go9yQUR8_NgoPUCOSkAyN46gs0jat3EKIsNWevZisZBas6OayYJFB7WWkYm2um2LQdMwdlKmS7UmsixUU8ta7RdXxhkuiHtAi_nNaoYRkjbYon-8nLFJdP4dvHLqmfbIsl12wLISBlQW5cnonq88md0msDzFayjOvlv9Ha_a0Z8lVZXIHiqmBMpFRG2qchTU3ipHYbJbSGxwJ9klxLrt2IucrGZt_LgbOZqC6ZmORtct3dHYOn2PyJyABpn5ew2TEd4yCkZgDJkR2jlJabH254GNdoVomZNsr6aFKZr9GX8BkbWFDcgBQnAU32YUe_korccStwQz9TUyZ-UI_vJFSyk9uQxx4I3UVLWkomooGy2BWCLZ475qfePSXar9RtJH6cZadTZx1z-VQvXPf3Pu_0f3zeopbvHacVsHNe6IgqmFDpGEjwL8dzKx6N9JaOziLlM9J01mFBLz7edXgpc80K9VQ2n6MwBEr2bOoNmZHlA3xBN4LVfn6Pnz3Z_PV7UhF1HoYtX3oCtG36moTaLZCukkWYtnFedoLAhyTnonze1X7ZPW1rthJEAZWTNdG_HQeqVdixvVc-Q0a9oQE_Lfc9Q6q0EPwagLQXuOmrUfsdjnzs9Ws_kPRANXEAxuQEky2IC0fzrdvRB6FIeMs5BU3kIeJyEKuESzlZomIFM-IVM_Ici6ygBEx31tQnzo2sDqjCEoEBEPCFLnEjwou8frHmLqHQ2Rnu8T4A3v8C5p1f8hJx6UhHokAc31BAcgmlB_1Vc1XeOieOCUAdE5CJHMcxsqCDbRoJac7Qh4GNzcDWsjPJsxIv4JURT-C3TZOH8o8BxUOkcqLmvg7jl9P0c_NMNz4PdTg5lcoSfxxEs84NSm0VyDq2tLFtd3mmnXt2o_XMPwp-o6lLNQfOIk7jGsam0IC2H4bVy-HQmxI_8vplQzFdvuS2-0_pRBuEEf549nz5N7lQ3MxMTgINjEatEMwxrZKJeESTSYrcIQM2TmW8gpgJ-w3KXRLU7DqYBGC03f8HKXUK8ChXoVKFSExiWHw2iXQLsAgVsCpcQvvi0bG0eZYZ9PuhX4pFUBjU5Bg1QVk1VssiI0dEotZPW9EeiUjJ92YZGLOOiG6eO1RJjs3zW9whRyIZjiKynP0kqnRG4dp3QRTw_8iBFZQUC2K0iS7dL-7pQ0firGnUMSTFT54BybFAurWnb7dgtvv_JHjlOaQnkZOmUN16kq77cLSeKtkBlnVp_TulWd5K1qNHLKuqhwdVU60fSq0bxbWpAiQaUzVqussVsVZPrK9lS3Gj_0StY25SuVstVVRVuxXVVqqIzQMW3HcbaoKiYrcsXRe6RkJFV2OjgVJIoqaLSqUqiyrPUrITMPmhKpB8B6QKtv1PBgTl9-uR9DAuKv7sJLHoabCzX6U2M_rB6QpW7SrC9_pyHdKJTcf-BeiuhvjhqYSo7mVBAk9Nez6guP2m9Ao6kWfDOG14PLzYU4lyw484hICxH_zi8R4jR9A30f_NZdyQTL6WYjrS9mJnd31jq3TnsH-KV-JphgHeCWvvyaoHQOqQVvigunOBXC8tc_YlS_2iOCeFN97YdHgZwSNk-R6R4WuKiSv1ypzW0d5fRdRTunB7Diq9ucMT11TQfZYZ_vcmsfwElOi7V0ne6nlhUlpC-UPc71l6DgAf1N7u6NNguj9W2FBP6snf6x4j6U7bvse0Kl30hySr-x-8vm_wGWdYIV
```

**Comment by sida-wang** [comment]
Thanks for the report, I spent some time investigating this when it was first reported but ended up getting distracted while implementing the fix. The issue comes down the way buffs from the same source are merged in the calculation. 

In this case, the less damage taken buffs from the flask implicits needed to be merged since they both originated from a Ruby Flask. Because buffs are positive, it's coded to take the larger of the two values but in this case, because less damage taken is coded as a negative value for more damage taken, PoB was incorrectly taking the smaller less damage taken value. 

In any case, given that 3.24 brings changes to ruby, sapphire, and topaz flasks so that they provide maximum resistance which follows the usual "higher is better" property of buffs, I'll close this issue.
