### ISSUE TITLE
Thousand ribbons grants thousands of stats and resistances

### ISSUE THREAD

**Issue by dfbpurcell** [PathOfBuildingCommunity/PathOfBuilding#7332]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

it seems there is an issue parsing the symbols (brackets) so instead of 20(10-30) equalling 20 it equals 2010

### What is the value from the calculation in Path of Building?

it seems there is an issue parsing the symbols (brackets) so instead of 20(10-30) equalling 20 it equals 2010

### How to reproduce the issue

paste this into a new item on a new build 

Item Class: Body Armours
Rarity: Unique
Thousand Ribbons
Simple Robe
--------
Quality: +20% (augmented)
Evasion Rating: 49 (augmented)
Energy Shield: 86 (augmented)
--------
Requirements:
Intelligence: 17
--------
Sockets: B-B-B-R-R G 
--------
Item Level: 77
--------
{ Unique Modifier — Defences, Energy Shield }
+53(30-60) to maximum Energy Shield
{ Unique Modifier — Defences, Evasion }
+41(30-60) to Evasion Rating
{ Unique Modifier — Gem }
Socketed Gems are Supported by Level 5 Elemental Proliferation — Unscalable Value
{ Unique Modifier — Life }
+34(25-50) to maximum Life
{ Unique Modifier — Mana }
+25(25-50) to maximum Mana
{ Unique Modifier — Damage, Elemental, Fire, Attack, Caster }
Adds 3(2-4) to 8(5-9) Fire Damage to Spells and Attacks
{ Unique Modifier — Damage, Elemental, Lightning, Attack, Caster }
Adds 1 to 4(4-12) Lightning Damage to Spells and Attacks
{ Unique Modifier — Damage, Elemental, Cold, Attack, Caster }
Adds 2(2-4) to 8(5-9) Cold Damage to Spells and Attacks
{ Unique Modifier — Elemental, Fire, Resistance }
+29(15-30)% to Fire Resistance
{ Unique Modifier — Elemental, Cold, Resistance }
+28(15-30)% to Cold Resistance
{ Unique Modifier — Elemental, Lightning, Resistance }
+28(15-30)% to Lightning Resistance
--------
The night of a thousand ribbons
To remember the day of a thousand flames
When Sarn burned
And was born again

### Character build code

```shell
blank character
```

### Screenshots

![Screenshot 2024-01-30 130316](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/158113601/7d56c89a-585a-4e51-9daf-7219264d86fd)

**Comment by Wires77** [comment]
PoB doesn't support advanced copy/paste from in-game (Ctrl+Alt+C), so just use Ctrl+C instead
