### ISSUE TITLE
value="table: 0x11e71d18" in saved builds is back

### ISSUE THREAD

**Issue by pHiney** [PathOfBuildingCommunity/PathOfBuilding#7347]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Not have 
		<PlayerStat stat="OffHand" value="table: 0x11e71d18"/>
		<PlayerStat stat="MainHand" value="table: 0x11e71cf0"/>

### How does Path of Building behave?

has 
		<PlayerStat stat="OffHand" value="table: 0x11e71d18"/>
		<PlayerStat stat="MainHand" value="table: 0x11e71cf0"/>

### How to reproduce the issue

On new build, save it. Don't need to do anything.
Look in file at PlayerStats

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/4302241/79c2874a-0d9c-4e14-99e5-77117baee39d)

**Comment by sida-wang** [comment]
Fixed in #7334 on dev branch awaiting next release
