### ISSUE TITLE
Bloodletting Skill Not Applying +40 Damage to Bleeding Targets

### ISSUE THREAD

**Issue by StrawFruit** [PathOfBuildingCommunity/PathOfBuilding#7349]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

I can't check the skill ingame.

### What is the value from the calculation in Path of Building?

Bloodletting does two things
- +15% damage over time multiplier for bleeding
- 40% increased Attack Damage against Bleeding Enemies

The 40% increased Damage is not calculated, the value is zero

### How to reproduce the issue

Open PoE
Take the Bloodletting Skill point.
Remove / take the Bloodletting point and look at the values
While bleed DPS changes, Hit dps does not.

Make an Item with "{custom}-15% to damage over time multiplier for bleeding", it will give the same +/- dps as Bloodletting

### Character build code

```shell
https://pobb.in/t-YDkEBdvfzE
```

**Comment by Wires77** [comment]
You need to check "Is the enemy bleeding?" on the Config tab.

**Comment by StrawFruit** [comment]
thank you very much, and sorry for the trouble :/

I was staring at the config yesterday, and to day bleeding is staring back :)
