### ISSUE TITLE
Cluster jewel passive allocations are not imported

### ISSUE THREAD

**Issue by Tartarus762** [PathOfBuildingCommunity/PathOfBuilding#735]
See the below pastebin for an example:

https://pastebin.com/aEnqMRM5

When importing a character from in-game by using the Import/Export Build function, the passive skills allocated to cluster jewels in-game are not allocated in PoB.

The method of importing the character is as follows:

Click "Import/Export Build" button
In the "Character Import" section type in my account name, click "Start" and select the appropriate character.
Click "Passive Tree and Jewels" and "Items and Skills"

I am using version 1.4.167.2

**Comment by LocalIdentity** [comment]
This is due to the fact that the character import data does not tell us the nodes that are allocated on the cluster jewels, so we have no idea which ones are allocated or not. We'll have to wait until GGG updates their web skill tree before we can auto allocate the nodes
