### ISSUE TITLE
Cannot open build after getting errors within it from skills tab

### ISSUE THREAD

**Issue by slypez** [PathOfBuildingCommunity/PathOfBuilding#7388]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)
- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

I should be able to press my build from the starting screen of PoB. It should open after i have double clicked it.

### How does Path of Building behave?

Whenever i double click my build i get an error which i assume i got when i was within the build but didnt care, but when i exited the build and the next time i tried re-entering it, it didnt open and just gave me an error.

### How to reproduce the issue

I have no idea how you would replicate this, but my assumption is that if i give you the "corrupt" build maybe you can take a look? 

Especially the error stack should give you a good indication of what it could be. 

My guess is that i did some weird combo with disabling skill groups in the skill tab. I mixed skills like snipe, bloodthirst, i had atleast 2 skill groups with snipe in it, and some were disabled, but it feels like this issue has something to do with the skill tab and how i setup the skills or disabling of them.

### Character build code

```shell
https://drive.google.com/file/d/1ko2B1NakZEwbgFOkHRUdzcJgAPKmxIyY/view?usp=sharing

Since the bug is i cant go into the build i cannot import it to get a code, so i just uploaded the .xml build file from pob. Would REALLY appreciate someone looking at this, or somehow un-corrupt the state of the build, put like 20h into the build and dont wanna redo it :(
```

### Screenshots

![POB_FORK_ERROR](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/37112780/67615677-0c07-4b0e-93b3-2987ad3826af)

**Comment by slypez** [comment]
BANDAID FIX!

**Potential clues to contributors:**
Okey so (being a programmer) i lurked around in the .xml file myself thinking if i had the possibility to remove a skill groups it could resolve my error, and it did! What i did is i removed the skill group i thought was "bugged" and after that it worked. The piece of code i removed was:

`<Skill mainActiveSkillCalcs="1" includeInFullDPS="false" label="BA + Snipe" enabled="false" slot="Weapon 1" mainActiveSkill="1">
				<Gem enableGlobal2="true" level="20" gemId="Metadata/Items/Gems/SkillGemBurningArrow" variantId="BurningArrowAltX" skillId="BurningArrowAltX" quality="20" qualityId="Default" enableGlobal1="true" enabled="true" count="1" nameSpec="Burning Arrow of Vigour"/>
				<Gem enableGlobal2="true" level="21" gemId="Metadata/Items/Gems/SkillGemChannelledSnipe" variantId="ChannelledSnipe" skillId="ChannelledSnipe" quality="20" qualityId="Default" enableGlobal1="true" enabled="true" count="1" nameSpec="Snipe" skillMinion="SummonedPhantasm"/>
				<Gem enableGlobal2="true" level="5" gemId="Metadata/Items/Gems/SupportGemDeadlyAilmentsPlus" variantId="DeadlyAilmentsPlusSupport" skillId="SupportDeadlyAilmentsPlus" quality="20" qualityId="Default" enableGlobal1="true" enabled="true" count="1" nameSpec="Awakened Deadly Ailments"/>
				<Gem enableGlobal2="true" level="5" gemId="Metadata/Items/Gems/SupportGemSwiftAfflictionPlus" variantId="SwiftAfflictionPlusSupport" skillId="SupportSwiftAfflictionPlus" quality="20" qualityId="Default" enableGlobal1="true" enabled="true" count="1" nameSpec="Awakened Swift Affliction"/>
				<Gem enableGlobal2="true" level="5" gemId="Metadata/Items/Gems/SupportGemBurningDamagePlus" variantId="BurningDamagePlusSupport" skillId="SupportBurningDamagePlus" quality="20" qualityId="Default" enableGlobal1="true" enabled="true" count="1" nameSpec="Awakened Burning Damage"/>
				<Gem enableGlobal2="true" level="5" gemId="Metadata/Items/Gems/SupportGemWeaponElementalDamagePlus" variantId="WeaponElementalDamagePlusSupport" skillId="SupportWeaponElementalDamagePlus" quality="20" qualityId="Default" enableGlobal1="true" enabled="true" count="1" nameSpec="Awakened Elemental Damage with Attacks"/></Skill>`
				
And if you dont wanna dig through the code, its basically my 6-linked BA like this
BA of Vigour - Snipe - Awk. Deadly ailments - Awk. Swift affliction - Awk. Burnign Damage - Awk. Ele damage with attacks

Now my kneejerk reaction to that combo of gems should cause some sort of bug doesnt seem right (just by looking at the stats), maybe something weird with snipe? But you can probably figure out more by looking at that code snippet to get more metadata!

But yea, if you wanna figure out the bug, you essentially just download my build from the drive link, go into the .xml and remove this snippet and it should be openable.

**Comment by Paliak** [comment]
Most likely related to https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7317
