### ISSUE TITLE
Update will successfully download files and then break 

### ISSUE THREAD

**Issue by Teramond** [PathOfBuildingCommunity/PathOfBuilding#7411]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

The download for an update should end successfully

### How does Path of Building behave?

One or more files couldn't be downloaded

### How to reproduce the issue

Every time i update the programm

### Screenshots

<img width="244" alt="image" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/111453865/f1890671-e398-47e6-94dc-f63761e5b296">

**Comment by Teramond** [comment]
<img width="253" alt="image" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/111453865/6ea23510-e0f0-477b-8971-7d5b91ad9245">

**Comment by LocalIdentity** [comment]
I pushed a fix for this 20 mins ago. Press `ctrl` + tilde (to the left of 1) to open the console and have a look to see if any of the files have a manifest mismatch
