### ISSUE TITLE
Crash on launch "ERROR: Could not find dll named 'SimpleGraphic.dll'"

### ISSUE THREAD

**Issue by frans-de-waal** [PathOfBuildingCommunity/PathOfBuilding#7413]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

PoB crashes immediately on launch after a clean install of the latest version.

<img width="663" alt="Screenshot 2024-03-24 at 12 10 40" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/25571709/e16f3109-4082-4b6c-8f98-4e6f6fadcfd3">

### What are your system specifications and configuration?

I'm running PoB via [Whisky](https://github.com/Whisky-App/Whisky) on Macos Sonoma v14.4, on a Macbook M1 Pro 16" (2021 model).

Whiskey is set up to emulate Windows 10 with the following configuration.
<img width="1076" alt="Screenshot 2024-03-24 at 12 24 26" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/25571709/aa2114a9-2c40-4226-bd5c-ee0cc2323a6b">

### How to reproduce the issue

1. Install Whiskey via homebrew `brew install --cask whisky`.
2. Launch Whiskey and create a new Windows 10 bottle.
3. Download the latest `PathOfBuildingCommunity-Setup.exe` and run it on the Windows 10 bottle. The installation completes successfully.
4. Run PoB in the Windows 10 bottle.
5. PoB crashes immediately on launch with the "Could not find dll named 'SimpleGraphic.dll'" error message.

I realise PoB isn't officially supported in this environment, but I'm reporting the issue just in case it is an issue on native Windows as well.

Please feel free to close this issue if this issue is irrelevant.

**Comment by TheDataWrangler** [comment]
I'm having the same issue on Windows 11. Just downloaded it after finding it suggested in the PoE Vault. Fresh install results in the same behavior.

**Comment by LocalIdentity** [comment]
@TheDataWrangler do you have multiple copies of PoB open? Also try running PoB as Admin to see if it fixes the update

**Comment by PimpFloyd** [comment]
Same here

**Comment by arturluizbr** [comment]
Same error.

Windows 11 user.

**Comment by zemamede** [comment]
I was having this issue and it persisted even after reinstalling, I fixed it by downloading the previous release(2.39.3). It updated fine to the newest release then(2.40.0)

**Comment by TheDataWrangler** [comment]
> @TheDataWrangler do you have multiple copies of PoB open? Also try running PoB as Admin to see if it fixes the update

I've confirmed only 1 process is running.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/20749012/3c5e2230-7c53-4f8d-b52f-e77816bd4612)

**Comment by arturluizbr** [comment]
> I was having this issue and it persisted even after reinstalling, I fixed it by downloading the previous release(2.39.3). It updated fine to the newest release then(2.40.0)

Can you check the hash of the SimpleGraphic.dll in PoBC folder?

**Comment by PimpFloyd** [comment]
> > I was having this issue and it persisted even after reinstalling, I fixed it by downloading the previous release(2.39.3). It updated fine to the newest release then(2.40.0)
> 
> Can you check the hash of the SimpleGraphic.dll in PoBC folder?

Thank you, thats help.

**Comment by LocalIdentity** [comment]
Is everyones issue here only occurring cause they downloaded the latest 2.40.0 installer?

**Comment by arturluizbr** [comment]
I had to install the [Release 2.39.3](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v2.39.3) and update from it.

**Comment by arturluizbr** [comment]
> Is everyones issue here only occurring cause they downloaded the latest 2.40.0 installer?

Yes

**Comment by TheDataWrangler** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/20749012/699be297-4539-4340-9238-ebc29969af5d)

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          20A13167FB754902A4C80173CA010BF18001B0641F685478D94171F1BE5A11EF       C:\Program Files (x86)\Path o...

**Comment by ploxiz** [comment]
Another fix that worked for me was to copy everything in the "Update" directory to the root directory.

**Comment by kelppo** [comment]
I'm also seeing this running PoB on Linux through Wine:
```011c:err:module:import_dll Loading library re2.dll (which is needed by L"Z:\\run\\media\\ketsui\\A8920F48920F1A88\\Users\\User\\Downloads\\PathOfBuildingCommunity-Portable\\SimpleGraphic.dll") failed (error c0000020).```

**Comment by Wires77** [comment]
> I'm also seeing this running PoB on Linux through Wine: `011c:err:module:import_dll Loading library re2.dll (which is needed by L"Z:\\run\\media\\ketsui\\A8920F48920F1A88\\Users\\User\\Downloads\\PathOfBuildingCommunity-Portable\\SimpleGraphic.dll") failed (error c0000020).`

Our installer needed to be updated to package these up in the release.  You can download any missing DLLs from this folder in the meantime: https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/dev/runtime

**Comment by kelppo** [comment]
> > I'm also seeing this running PoB on Linux through Wine: `011c:err:module:import_dll Loading library re2.dll (which is needed by L"Z:\\run\\media\\ketsui\\A8920F48920F1A88\\Users\\User\\Downloads\\PathOfBuildingCommunity-Portable\\SimpleGraphic.dll") failed (error c0000020).`
> 
> Our installer needed to be updated to package these up in the release. You can download any missing DLLs from this folder in the meantime: https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/dev/runtime

Yes, I tried copying everything from the Update folder to the root like the previous comment suggested and I got past the missing dll error but sadly PoB still won't start on Wine:
```wine: Unhandled page fault on read access to FFFFFFFFFFFFFFFF at address 00006FFFFC71EA65 (thread 0118), starting debugger...```

**Comment by ppoelzl** [comment]
Fixed in the [latest release](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v2.40.1). Please redownload the installer.

**Comment by ppoelzl** [comment]
> > > I'm also seeing this running PoB on Linux through Wine: `011c:err:module:import_dll Loading library re2.dll (which is needed by L"Z:\\run\\media\\ketsui\\A8920F48920F1A88\\Users\\User\\Downloads\\PathOfBuildingCommunity-Portable\\SimpleGraphic.dll") failed (error c0000020).`
> > 
> > 
> > Our installer needed to be updated to package these up in the release. You can download any missing DLLs from this folder in the meantime: https://github.com/PathOfBuildingCommunity/PathOfBuilding/tree/dev/runtime
> 
> Yes, I tried copying everything from the Update folder to the root like the previous comment suggested and I got past the missing dll error but sadly PoB still won't start on Wine: `wine: Unhandled page fault on read access to FFFFFFFFFFFFFFFF at address 00006FFFFC71EA65 (thread 0118), starting debugger...`

Tested the new installer against Wine 9.4 through Lutris on openSUSE Tumbleweed. No issues.

**Comment by kelppo** [comment]
> Tested the newest update against Wine 9.4 through Lutris on openSUSE Tumbleweed. No issues.
Yep, I tried downgrading DXVK to 2.2 and PoB 2.40.1 starts up just fine now, I should try to bring this up to the DXVK developers..

**Comment by ppoelzl** [comment]
DXVK 2.3 works for me, it's the default. I cannot easily test 2.3.1, since my Lutris installation doesn't offer that yet.

**Comment by frans-de-waal** [comment]
I can confirm that doing a clean install of version 2.40.1 fixes the issue, thanks for the quick response!

As mentioned in the Reddit post you need to run the `d3dcompiler_47` winetrick, if you're using Wine (or in my case Whisky).

**Comment by nerzid** [comment]
If anyone is having this issue for version 2.57.0 (i.e., the latest release as of this comment), just download the previous release (2.56.0) and update it inside the app.
