### ISSUE TITLE
Kinetic Bolt of Fragmentation has an incorrect modifier value

### ISSUE THREAD

**Issue by EmperorBB** [PathOfBuildingCommunity/PathOfBuilding#7416]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What is the wording in-game?

Kinetic Bolt of Fragmentation **has an incorrect modifier value shown**.

The gem is supposed to have **"Increases and Reductions to Spell Damage also apply to Attack Damage from this Skill at 200% of their value"** but instead in PoB it is **"Increases and Reductions to Spell Damage also apply to Attack Damage from this Skill at 0% of their value"** for the transfigured gem **"Kinetic Bolt of Fragmentation"**.  However, I do believe it is calculating any increase/reduction to spell damage correctly.

The normal version of the skill gem "Kinetic Bolt" has the correct modifier value.

I have updated to the latest version available.

Best regards,
Emperor BB

### What is the wording in Path of Building?

When I look at the description of the skill gem "Kinetic Bolt of Fragmentation", it says: **"Increases and Reductions to Spell Damage also apply to Attack Damage from this Skill at 0% of their value"** instead of **"Increases and Reductions to Spell Damage also apply to Attack Damage from this Skill at 200% of their value"**

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/78990809/230110cf-22f8-4a29-97f7-37a61e787938)

### Character build code

```shell
2.40.1
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/78990809/6367ff2f-d8d8-4fda-a9ce-a685be72d684)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/78990809/837e954f-23b5-4e61-abd4-a911d35b37c6)

**Comment by Wires77** [comment]
[From the 3.24 Necropolis patch notes](https://www.pathofexile.com/forum/view-thread/3496784#skillgemchanges):
> Kinetic Bolt of Fragmentation: No longer has "Increases and Reductions to Spell Damage also apply to Attack Damage from this Skill at 200% of their value"

The description still being there is just an artifact of us not having the data from the game yet, as that patch hasn't been released.
