### ISSUE TITLE
QHD and Blurred text (125%)

### ISSUE THREAD

**Issue by Sheodar** [PathOfBuildingCommunity/PathOfBuilding#7433]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Text will be clear.

### How does Path of Building behave?

Text blurred.

### How to reproduce the issue

Run PoB on windows with size screen scaling 125%

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/23509297/50149ebb-43b4-489e-af56-742645d336d4)

**Comment by SimonYdeMadsen** [comment]
120% scaling, I also have blurred graphics.

**Comment by Cavelore** [comment]
same, got blurry after i updated today

**Comment by Sheodar** [comment]
> same, got blurry after i updated today

It was blurred for me before update too

**Comment by lostrofl** [comment]
![Path_of_Building_4tFvhqMBE3](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/61546931/d3d7d540-7f59-47a7-9990-2c948a588254)
Same issue, it was always like that (version 2.38.4 on screenshot and before)

**Comment by Wires77** [comment]
I'm going to close this and track it under https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7414

There are some workarounds posted there that may help you until we find a permanent fix.
