### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by meanbeanmachine** [PathOfBuildingCommunity/PathOfBuilding#7435]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Successfully check for updates

### How does Path of Building behave?

Gives me an SSL error when attempting to check for updates.  My internet connection is fine since I can post this, and previous versions of POB never gave me this problem.  I don't use a proxy.

### Screenshots

![Screenshot from 2024-03-24 10-40-49](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/29932473/5c86c242-0ad9-4008-897b-782feff5ee90)

**Comment by meanbeanmachine** [comment]
Looks like I also get SSL issues whenever I try to do something that needs an internet connection:
![Screenshot from 2024-03-24 11-04-12](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/29932473/ac5281ed-a6dd-45e6-b90d-de2273aaf32c)
![Screenshot from 2024-03-24 11-06-16](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/29932473/2e5dc5cb-6cae-4f5a-b861-046c6ad799ca)

**Comment by Wires77** [comment]
Some people have had success with changing their Connection Protocol setting in the options (bottom left).  See if that works for you
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1209372/72648017-06e3-4df8-b843-8ba9cf13b563)

**Comment by meanbeanmachine** [comment]
upgrading to 2.41 fixed this.  Did not have this problem with 2.39 or 2.41 or now 2.42.  Not sure what the deal was with 2.40.
