### ISSUE TITLE
An error occurred when starting the program

### ISSUE THREAD

**Issue by Loqures** [PathOfBuildingCommunity/PathOfBuilding#7437]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48675094/488fc19a-8c25-46e8-ae53-853619aa2ccd)

### What are your system specifications and configuration?

[DxDiag.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/14736137/DxDiag.txt)

### How to reproduce the issue

1. It gives an error when starting.

**Comment by zao** [comment]
Someone else that had the problem reported that they could update by changing the "Connection Protocol" in the Options box to "IPv4" instead of "Auto", you may be having some problems with your network stack:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/260218/362e6e2e-4373-43c4-8b17-55c91c88ced6)

**Comment by Loqures** [comment]
> Someone else that had the problem reported that they could update by changing the "Connection Protocol" in the Options box to "IPv4" instead of "Auto", you may be having some problems with your network stack: ![image](https://private-user-images.githubusercontent.com/260218/316326563-362e6e2e-4373-43c4-8b17-55c91c88ced6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDAzNzEsIm5iZiI6MTcxMTMwMDA3MSwicGF0aCI6Ii8yNjAyMTgvMzE2MzI2NTYzLTM2MmU2ZTJlLTQzNzMtNDNjNC04YjE3LTU1YzkxYzg4Y2VkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxNzA3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2IxNmIwOGI1ZGZmMGRkMWFkMWI4NTJlNDJlYmU1OGQzZDM1ZjY0ZTMwYTZlZGI2MzlmNzc4ZWY1MTViYWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2Mp4-Xd0qWQbTJI7Pfi0ESY9IuAOgXX2k4J1tY4x4oQ)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48675094/98d3393d-79d7-4212-a954-fbf03c57878a)
Dont help :(

**Comment by Loqures** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48675094/e4b171f2-0b25-45df-b3ee-c23c46d8261b)
I also use these files to run the program. Otherwise, it doesn't work for me for some reason. Maybe this is the problem?

**Comment by Loqures** [comment]
An unknown miracle happened. Deleted pob. Installed the latest version - it worked without additional files. The topic has lost relevance. I hope that I will no longer have to look for some "crutches" to start)
