### ISSUE TITLE
POB not starting

### ISSUE THREAD

**Issue by Yasho1313** [PathOfBuildingCommunity/PathOfBuilding#7440]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

I expect it to open.

### How does Path of Building behave?

It doesn't open. I've a new computer and I downloaded the latest version of PoB and did a first-time installation. When I double click on the shortcut I can see that the little wheel appears on the cursor but nothing else happens. It doesn't launch. No error messages appear. Updated my drivers - didn't help. Tried running it as administrator - didn't help. Tried reinstalling.
Installed an older version of POB - opened it and it launched. Saw the green window with the text and it started updating. After it applied all the updates it didn't launch. 
Please help.

### How to reproduce the issue

Install POB.
Run it.

### Character build code

```shell
Cannot do that.
```

### Screenshots

Nothing to see it just doesn't open.

**Comment by Theyflower** [comment]
For me on the latest version it opens but is simply a black window. I'm running it through WINE on Fedora

**Comment by zao** [comment]
@Theyflower Likely unrelated to OP, try `winetricks d3dcompiler_47`.

**Comment by zao** [comment]
@Yasho1313 Is your Documents folder in OneDrive and is it working properly? Do you get any crashes for PoB recorded in Event Viewer?

**Comment by zao** [comment]
Closing this to gather feedback in #7431 where OP has also participated.

**Comment by LordBumi** [comment]
I have a similar issue , but PoB was working fine until i updated it yday
