### ISSUE TITLE
pob is being quarantined by crowdstrike falcon

### ISSUE THREAD

**Issue by crosscutsaw** [PathOfBuildingCommunity/PathOfBuilding#7445]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

![2b](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/73831924/b82d76f4-5344-4b5a-9eae-40c32ba4a08a)
![3b](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/73831924/95abdc6e-921d-4cc5-8a7e-a10f6740aa0c)

### What are your system specifications and configuration?

windows 10
falcon sensor: v7.11.18110

### How to reproduce the issue

1- download latest installer from github
2- install it
3- run path of building.exe to get blocked by crowdstrike falcon

**Comment by Nightblade** [comment]
Just a false positive related to generic virus detection techniques.  Nothing the PoB devs can fix.

**Comment by crosscutsaw** [comment]
> Just a false positive related to generic virus detection techniques. Nothing the PoB devs can fix.

thank you for the information. i can assign an exclusion but this happens only on latest version. older versions are not being blocked.

**Comment by Nightblade** [comment]
Newer versions have changes that account for the novel detection (overhaul graphics engine to v2.0).  A [Virus Total scan](https://www.virustotal.com/gui/file/014e4633b93db1974f69dfcaa8284b5d215c9359acd3bfeb787138be920bce24/detection) shows 1 positive out of 71 negatives if that helps.
