### ISSUE TITLE
Major DPS loss

### ISSUE THREAD

**Issue by Nodachiii** [PathOfBuildingCommunity/PathOfBuilding#7447]
**Hi, I downloaded the update today and it now shows that my DPS is about 113,000,000 lower than it was yesterday. I haven't had any issues with POB until this but this is my first league so i feel like i might be missing something. Any info you could give me would be greatly appreciated. Thank you.

This is my POB- Yesterday i was at about 167,000,000 now I'm only at 54,000,000?

eNrtfW1znDi28OftX0G5ap8vcRL0LvIke8tvsTOxE4_tJJP9MiVAuElocIC249na_36PBHRDN7S7bc9O7uxMplw0OudIOjrvEvDyf75PEuda50Wcpa-20DN3y9FpkIVxevlq68PF66dy63_-MXp5qsrx-2h3Giem5R-jv720106QqKJ4pyb61db5WIXZzZajikCn4d684SKPg69FqfMtZ6Li9DwLvuryMM-mV6-25JZzHeubkywEwDcnp-_PLracRF_r5NWWx7ecUuWXuvzYjI_8CuO7Umk51ll6or5k-WEWQg9jvZvHqX4LY2u1x2ndfqYS9VUX4y0nGKtcBTCWY9PHzrTMqq4jlRR6y_FVGsblq613Waq3YJZ_e3maqFudn5eqdAr482prB5ilLvVRXMLQVTIFZMQ9KpjEzziR0mVbz1di7k7zotxXE7jclML5ldbhDIk8Q5LP_hNDSDDSe-Gd5voginRQxtd6L4_LvbFKg9aQXXcIc3Pok2lSxldJbGSkxuDP2KoprU__IitVsn96PoNl1HU59vgzLhhn3mq8bL7Mgz18isvxbgIsvkcvBvfNZRqX-p7Ip1lcZOkD5tdGHV6kaZKAcq0Fe6YLnV-rMu4Oa5h2NvFBee_DvZ1cq_dRJaZnKoynxYkuc13M6NBng0K0m4Oy75SlCsYTnQJ6eqkt9nwQz9BK5Atj12bQmA8Bn6hU7WXFXJI8ugr0VOdgQcsOhnsHwrkOMjC6bRTsec8YvVPNWz320xns-jiO9PqQG82qRth0NPebx8H5unAbE77fgM7ANawHeZ5NkzUhy7xlLMWw7n7rQg76on39fQ5GVxiDbx1IIocg36TzaTCximAbEtMVI7zOjBGaU2UrbeHB0WmbrBTeM08I6UmOB33k-LaIA5WcqO_xZDoBv3QBgUba4p_HEB4W2ctxmYJZHULnnicG-fU6zvW9EPeyJLwf4lhlxRBmnEarVHPOkhXBTfDCgL5Jg_mSraL5Ic2tq2nFNmgV_BnooInB_ESvhzDvoFbkdeKNqqdLndbd3c4DL7FyOsdaB-NDiJDPVKnXs_zz8SBGVjLWQLcZu5JsH2PdNTEWOSXBhRMXcykhtiVkFZF-riHmPlvpLzfk20Gq88vb83Gsk7BlGgReB6EZ3Z66WgvX8r5NoL0Gwluvyz6uPJXuWjPsZw5CiA4z9ZPKw_W8VP_Yhgd2rYq2QaaceHw16yqMNtcwGdTZEw1ROKCEeiE9kHQ4y8m-mBwn2RBvJ59k07mjlKunUUGvpX-NS6kyxDMdToOOEyODQ9pNILNemABeZRWSpA9lcGQ2Vv66n4WXel0U28lGGLOU06KeT6-uwLAYEVggQFb6RUhB4lZUNGx358DvQYTbWi1Wuc-16c-BF-nju8OCtXtZwFjsiq906Au9PKV0DfDFLu5ezxOwESbPsrWIk2xuYPAzOqjQryHtXCuHtIBr5rKn2Q0MfmwqS_PsbThKa4ND8LMGxutcp7_drt9DB369Lg7ScJobhVjsha2L0e6nQbqIJ2BBi2JflcopbJ3udZyUOt-HJTe4hqtOWMfVH1Ueq7REJohavIntzUKrPBgfA_Krrfav1ypJfLAlcNd0_PK5LSaaq3dZqQszFnO3-fHyItfaUY1ZCAxtO17zw5koU1u8rQSteLX1L0QRxtuMuJT_e_tfiCNMtol0hWt-YcS2KXdNC2PUQ9vYxCXwi7qUeNDEBYZfGBwkYGEphGmjHhDE3KXwg1ABBKlLXNskkCe2OQT6FSD25DaVRLJ_b1XF0TehUUCYvMn_VH67My-PmqY0TracNAs1jJx4ksKAXE8KoC8E30aYI7KNBWd8G2Mk6DZk9JRtc4g5yHY1NYokTIMQgtxtTigV20xiSrchdxNsmwA4BgoMZsBdzLxt4cIl8AHmVw2XA8M8QKKMblv-MCa52CZMenS7mh_jiMntirEVMyzvgCHU3Qa-SaBCCWPb2BMIQAgX7jbmGP4iBOEfDA-at6m5AZ1JDzoSEhhsBwfD4GZKcI2YBxPjnMHkscuw3MaEwKUUMDhOMcwRSSTxdrUKmFGEYDDYwFCXQSuDDu0AANDl0B0jyLAEcaBlV1VQ4A6WEngBHUtupiHM-jIXb3vUhbkQDsRBghDgeBIzO2kKUoQwDN3lhg0YprTNPJgWAmKw6h53gd_YIzA64QrglzCj8JgLQ6QIpAvomr-weMAdz-XmPgcmmzsAjihwkGEPRoQkAd5DFgrC5Hl2dVzDeiQtNLMiADMymNTwSzLLNQ_4BRwxjSATFAkEksTNfEGUzLgMMewh-AuCAQPDnoegJ8rNagC_gaew4CBnQBhwQfxACgncg-VEZmQEVttSBvkDbTESxmHwmEmCzFJCLwgZxgGSWUTI-GH4sDhiWwCHAFwaUXIFJ9seNiyQnAJTuQcrzEAgOPQqqdU3mGallsBEaaQQe0Y6gVFbTgk2obUvAIFOe-fBqBa2RuJvLz-cHduLv43L8qp48fz5zc3NsytVjrNIf4fA71mQTZ5fARKYl6fF1zhJnhriz3fgv93Lz3vRT9Pxh2gane-_fu3vjD-l5Ud0ej39ktE32vOiL-O95PTL5Cy_fV9-ORQ_X_vcfSueXn_9eHn-K_4yPXmXj0Ojbm_Hhyf45LQ4fHv94Sl-5x68_fbpn1e0dLO3_sFb_nX34uh6_5fvkfrCkg_7Oz-9Odo9f1r-dLSb6S-f3Xeh_FK8O_jZO_xyfPCa_jY-T767H4Lj6eR6ekN_O_v89eY0Pvrt-5V7qTyZnB4m__weXJ8kX3a_f977-vXd50Pm3pQuuaYJOXyN1Ofi-vv5jfyc_Zz4Xsr23haTna9H41-m-vvrk_fJoXe7_-s1Ct99-8lFv3zCZ-_d9_vvv_wzuSBX2Ufv_YfJ6dnkIv2F0nwvxTcfKDkpv8vPX37Nvu3d_lyys2Tvfbn_c3mdv8sZIRdvTn3mhW_3bnaSnd2dg4OdnXhnL9s5uNm53Nn7fHD4888XO7tf3ybHn58-Fe5u_nN29ivwT3yb0F8Cid_d5u-i3cMT3xOfbxj6bczf7_gf3_5SJnuhd_PqlV3o581Kv6z2mIpq2etf1spaa2yUa8uJSz0xP2vntwxnNGkOhobAjMWYg4lBasYyzuHoEJw1-XM4bwjO2tg5HB6kZ6xgaxqD8zDaOYeTg_MwZmAOR4bgrFeZw_FhvniotRqoDttgNduL-NIEnHkMbrKKVJ4b129DBxMbmItzo7gFxCGRmibloZ4cV7uIaZZPZgU68MNZbhqL3VuIFV-bDHlhA2JO4OepSuLy1sY8dfBh-jjXZRXcjDMQ5rKGMjRn24idTl5tlflUV_Amn6naLm6vjMvfOT6uQ5matBOHTXhT33R0aipWYUPH7KHuzIdjx7Jwb08lQWEb4jRIpsDotI6kZ0NMlG-4A8NKMpPya3WVpQ5yzm8gqq9XCobpXFbLcqJLFUJU-PwNrFPx3Ezu-XwyH7M4PFFpfDVN7LbPaTItZtu4IPSpmtSB286NKRrq0DEoThtnq57nYZL5KsFzXpoJmSHU3fX3dV2FnQauD6DGhZAsm6bV8n2r1s1g7FdL3h0Bavj9rSUG3aWYCaoZ4v-tFTuJU7M9Z2sMndVCvatVgTvNrvV6K7XcR2uVFhv_hCsEo7yGzGzNpTF9wNXrPCvKpjjZaFBnUSyE04DcsRQW2LTqDvc7vTyE43iA5RuI4ps0yLUqwPxCflpZgkYWZXveMzhnDrieIPb00OLFUuvvKYpry8F5fBkn7yNbfBgQBAviZJFTA93BjL04DxI9I9niQLevH0Uc2nv7cw64_SJhgA0rGvANBaPbV59wtCH-hLbqSCcTXW5oq_bjIjCndlI9IKFtgDtWpA3a4n_79h-ijjO53AnD2FgHlfxyOpsuac_2IE1MHVavbZe6JFuzbjc8irDhB1qjT2AZxwOLXLfdMeUaqjXJ-s4faWQPcxXMZRfx9rTqtjumVUO1plXf-dMFmnhD4_BmMgGxVabDZMZi0bHeNYRTgdzB6S69tonuNPyxRmJPFeX7Oqqtj0c0wtXRGQPn3Ix1E1I7NfB6dqOnlxY_llr_vMnPpjK5l6V2O_UapjRgzbogd4VUHeD2GnQafo-I6g9i_G6WlZumNGcqLix37dnK3kDOgjgzmDvY3iXYYnu34SFsR_jBtuBEq6VErjNpA7BuHtdNqXWkU1OtPi-bPfF5Xj3r9cdIY-wBAGuLdiC9GlC6f2oF0pXfrXBL5NpZzGLbH-sKDqcqD2Fsxa7ZUbUPJvTOvYH7f2DRiv9fOHPw9USip592NLLY-jjh5I9mlMJbpz6Qs5l4nsLwQIPsae6atacqL23A3LtaNYJjMUzCCQlKEV-tV444UZcTZZPtnaT8pbNO7YFUjX9wGg4piA5n50p6CoWst1Bo0ZwZ3oYVw-FOu8lRL9CjSLYpOT1WAcM82DI_yTUgUPMSRgO-Ic8Gu-urYnRhfldbsAHHWids3qdmiAMO08I5FaDzPp1xbF1W9fTTVsHF1h-FPUvHOQdEqYJzapD1WNJDu8WSpdYfhSUz9Qe7qct8edOp3zrN7VILb11WDffZ4tgQ0J_R7TZJ2P12oO5cQvRnXMIfcw9xw6ipMgiVqZwvV8dUVyBOA3PH8rzTN12a7bC-0_AQ3rOHB0V5oFJwm-15046YWgCnhlgz6GkTbcc58_s_RCr3OoFp7qtiPOCdbbtTAdy1Kzkn1d6UnN_9fVWsvjzXpT1BUp0cMZdvJobNoCWFeb64elD8CAZkyndBSKJQME9pGrjYjXAgkHRp5AZYel4ogkhoGz1-t6EGZBG3LbUryjPIcScQZexVP3cCO8eKukaYYulLTAMidcBYhBUOlGCuCHw3RG5INGWkOgv00tJ2Ql2UcWqtE8iKKX2emwMp4bXJIy6yLJkfR1FXVzoNm5-Whl1fZ1ro6rnEyhDYky0NjrUrBqw-72IZZ363T6icweqVty-cs52zg5F5GNE5m8bpCKKnSQGG5Sd9o5PRhzT-NtXOm_0XjhAyED6RyPMZkS5TLiOKcRd5KPQoFcTHCtgqJVMyUBK7xCeu7wbI9TlxcTSyA7Ane144koxgwZI4iMvihYNHe1meT69KcBK7SZaFDqhPmpWOr8EeRgBmWmBQt9l0hMnfndw8WgG3qj09k8sBA4OvDcgT5Dpl5pyXuU4vy7Fj8r19_R0kAmY8Quzvxso2oXsGtq6KqQ3e3w2iAht-kNgj7xDTV6fmzdIU83FasTzJQvvosZObvyC-z8BOxa0TXcMQ5E4IeidEc_Tbanx3jXF3jU92Dt_sjXaKwpyUnJUrjqdXMVg8oy4Tw8NyrJ0zFYc6b687qI2nJQ4DTSKPuzKgEVI89CXBLoiBpoR6AktEKSKURTzwOObMlR6TEmRkYd1Ze93dUWcp6geGYAylCRKuIGGojtfXvmj0hNjlmWVbsMDxV-3M30BgcdqpxmoGojtZjIdZTBbU6OAYWGysELAYLJhzUATqSo8-xnlsqjjLChUEJEAIh4wID-yG8DyFXNfFjGolVUCiQIL-uJEEA-ZpQZTkEVMiovC_YoJ1GUtH1UP0L5zzCcjv6DiexEZryuyFg7pMP63OyxbAeqdCMqv_Tgd5NgF7HgfOjr6MC6OERgPBQGWBMjJ_E5fjbGrU0qwPGJ9UB1UfRu1ye653XRVBw5ylPQYKoqFLUEfQc5WHoxMNo544exDagVIvs5Z7rnYZDT2PErDxSgmPK195geY4xNynTGk_wkK5QoWECy5cT0cuYswHdgfuoq2yV2f6G2gDbfOSjP4V5CqCyf57JwwLhzo1b53KMc2bUV1e6bQ7wGRVjd6pTkx26AG4XcsFos4l8LKEVcVt5amqWrUhW4EMLiJrKDwhZulgfZ2dElTJn5Zg4tbFZW0TOxqcXzWu4-xWJcb2DoEdZQmoeZbCChblI2ntf8b8roDgd0KIYS1gQ276SEMQAWoGEVS5LPoqYC4F6TbPD4SKM-Rh5DLshlzzUEVCURYGwnWJBpOtIgmBCzhxGZEwFODe_ZVuGrtz31u9-WR2oKvxvZ-zact7n6h4ApYA0bao2mp_s3t6M47BWI4z-3Ii0IYqZxjJNsKkOgHs1FWSGuQJqtzBPK2ce2poxJWvMO7dSmAPVLGhsfpRBKpPXHhXXD68e_Pzh4PRSQyBNeir81qB7R41D4ktiw3ISaQj5PGIIhe5BFGBIiLAvUeRL6VPzLVQENURyil1BedMIya5H0Q-FuGQMzq2XrjjfvaUedbcLM5lkuVxdOt4DHMn1TdOZEYZgYyDb7nWufEt_q1zBEvnXGigoXJnP5vE6bToOLG8cmIq17UJyStEE9DUeMUItSVKzwLHd1n6dG-aF-DnQJILG0FA-Ni8gGJEW9HmLCTciRNztSj8S8hHIGgwxeD_lEHrky7RY4yOMwWx9VEGQc5d_piIAJKswNccLrgIoyhiAiPsBtyDhMEnXiS4S4NAIhmxUGodROCGqYtJSCmm_y3-GN-Rfqztm4cN40Md9bnWX2GJz6YpjOcvP22etumJVjPtfMqmaTiy9m9YMXztowhHWELmrCMmgwhr1w2l4DJwOfal4lEUYuJJFbrcoxLsNEWahJJj7FJ9X8WQg4qB-xa-sq1txSjurxmLO4y_q1TvxwUYYNAk219cgC9YIdyneVxMlMmAqiBrWAvArE-c_TxOQRn-UgP7sNuyGnyMr-PQ-Sm7XZEFKwrBBtYKggg_Cgl1I458xKWMPE4ZQqABXuD74CYkgTjBUxy8BEQgmkjGlKtXlhcQXyl4T0z76oKCSXlbiLW2oE4wYQ-wz0giS9K8nMLGnTYAbdvwH0dY-pYRuY9XOVIyCplEvuv5IZdUag9jKs2jzpEfhAGNfE64DzEA8nxPBThytYd86jMwc667nIV3llZuVjliP1DlCKF1eAypyfUSk99AdBsXMVifNqM9CKCEVBC6R4IiFkCYzpDyhMsVeJbI10KHAVOckEAIFoqQChJGmjGPKY_QYCWjn2C0VEx9k5aQwsWX2qZaPxRveyufB98VZA06b3i7H6tJBvN4najiq-HtGSSBU7Dml222UgqxKCUuiYRvivsi4q6HWeQRjypEmR-Y4JX7WHIEBkyHSBIcBiGCwDUIBOmwFfxx_bgpJNJuy1HTTnUOzf3qByPZ9qBx_doPSERUMHYgP0pGuCP_TR4yom6ntr2wJNV7eJzQzrQunv-etoT0-ISDtMyzq1vnndZhYqqFkP6HzieQqjbrJaGE-hFVVAB7sa8xDSUOsI_gyhOcupQTRmlAUAhM4ZTD6gikEQplqHQ0Oh8rI3VmLIseYrYM7qiOZV44h_Bvt70oXndRbNBk9QCTJT9i1cPUNAqrHNW7loqaOEzObMXZAKreC6ySU9uZgySk5jY2NGe_jQBWXdnqGvYqP1L7FiQ6i2vOods38owEW2PVoyyvR2mclKXf1FXMm9j-ZEFMrzz2FZb3VJ4b1wEhehmMbUko_TLNYUGqZ0BHnaITyAIRo_bZml3gef3ePJBkEKpn3MNtUY5cgXyCwNdFnlZCRxgrl_uej4mCACbAQlHPo9SLwIYEkfDAGSLCtaSMBUGIB8UXt-T37Omu-deO_1m3dGe2tszzhvUryhrR3ZsVWjqhdSNxIFhBJT7Q_CFNzWsCTRluEoM5MhJF67fjFKYEchSXoycUG9j5dtsTLNqy1q3hCa_jxrv1PSrmoVS7tFffX4is5oaTdtKNTp3RnoQyWvbfFrKvgJArNIb1edMLoFBcmne7ZTOP-pMK9dydmlDlQ2443dYEDUZdhzwUAefKRS7EKpLLkATUp1oIXyElQi60FxHpcQka4JvEwJPalwwS5Y4mUDzgT7G405-aUp0PYjvRdRU7HJnXLIKBrw8ozqCM1QapNvYakhcj-LcjCkphi6gzr_tmMpkCmVsjlXVZvOtjz_TE2BJnd5pb9QJdmRb6RzeX_SXlw1xd61mUeq5Bz8rRXpJBaLirk7JTVGYy4K5PzMabx3xBGZg--EdFoHwIq7jAhAjfDUM_lBF2qQwx0iARiggcMd41faK1yFx2F9k-kOiMVeHgTgRkarrNIjzhfNgQddE6jrGxNwP7DKapfkVJJ8gtRsD0OIL4t7AgcboMAl2C71ehOeaR3LbBdnxQritbW56RqztZbjIVCW0O0QyPxcp3H2Y9gOZR9BnCo-2M_LeYStGrLbsqBDq1SdzNQUt0Ps6ycHQxzb9NM_Po1M5kmuiO3rg08sLAVRrSCs_svSgNCbLn-r4MpKt8jn3lE8FNMkJcLdxQMoyFJ0OmISdRi5sxLb1xu1HBvIhXb_IXzsH3qySz1a6qxvsEy45DX04AP5u9_0bsOnl3VzJv23BdafO6R3LAs2c3kM7Xb6c1eb1l4oWxPUlTHFxO87vRxGyP5yCZ2gm1dmk66Sim7TAHZq8d1aU89whT29geyAjjHvTOgfcZ9qVRw3o4f5UN7SuueuuGZon2sptktJvEv_2mcpPVgESM6kLPCwcihObHcgSOIDhYCNule0fUjrjoxCrCR8QjIsSagf-CuCXSUkksA9BMAVrmKxxQRojHKGcipAr5gfTdIPIZAXUcfVJ5ksG4bQZ6pkOtJ335qPBaYYycB_S7Tz-Zfy3VFazr8lZ5HtFbHTOKu7iFTvtD7BW032mVQzjUJAFjUATnaXu3vS8krwhWKa85rdekxvNXONsseY4wbyic09islAnA1OzlCs6F_brQf7Gb6tUmr_8UgEoUGKh4Vr7NsqvRkconWRoHzvlVDNCNSCzoDUbeXYrjgip2ipEqCJHveUyiMMKKIRmB0miqPCZcJiPf126oIgapLoSBkfa4eUMn56BDhAoxnO-Kdr571qnX8AXl4L3JbpRnExPOQ0BmHklwIFy070Vu0l1M2Yp0FA_rhIke5x7AGvkFD1BnxysOwix5pWPrSMyeWCdkBEq2DmgC0f7R2LOwhfU3M8dTlQ774X8oHVp1qNXtle7mC2GNdIMgQFpmI5MzcLP2ULF59H1UPWYKQsXry2VhhgxFLlV85F0aIEin4iMkuAWCQP6JQJEmCJJaEUIKRFQgme8LoqgOOIvAY7icEe5LqbkknsIqxIsHOwc0wNZ7np61dIDwVQ5i9g7p2bI_Qf11lNmumFWNVgPp5EjNS8HrGuSeORJvNAocghHNJoVKpxMfZM1EYUsjuBunG02ugfBXErNCf9A6eyPncXJtAut2LedoOgGYSz_OO1V6T0rKqaeYhGDI5wiRKJLUdVloXnksacCwwNQcbmZRAGYfMUwRDrWESIqwhfxeuEMbJN69Nki83g2S7lGEeQ39P7YpgnGvEbsY2wCstIUl8xEPU5g2cU5lqeaBLyJgbAYjX5MFLtovIu-qWCMpZGf3hZKIe5HSka9VCNbNo0ghTsxzM6Z2ozEPAk4CSjHm2CUejyDAJZwGLvd95g8bMG_RgC2WrcXCbljldZcDx53soIoYcXfLa0WsK2S7_GO-2jOiwwatJ7u0X0zRuclFBbMELFBVALeXiyZuhDjtRhR1-3ZD2oyzEyjMJPXPart6lYL0WaYTVWQQ5xRlY5pAjvLyt65pequ-QmtbekPKUBRwHiEv9LSCQFS5VIeQlQWKSkYVDf3QPM3k-XDD90KCcRhy87k9xFyJFnfD-60Sw_exSrYMh2ctK-vMTPY96GTPqhZNKWMDq_Ww54lor9WqnhPZmeZZrkYwqcmV0b23pgBea10TcyEXEomhqAsjuWS1sHu31SKdo3QBdlVgdswQJCCSYuYh140EWCuGIUsXLIDsQnIXBVhRLmTEcORHkhgDh7AeNlpyRd6xIAXiXnkHIQvniQybetP1u55Pq89iNEZuKbSDyG5vlqfYLwiN6iJbt6t50Q7bGdVDmslrhYq6pnc2ombLzZydqnbDm4NTfwVkHa1ivVpl36-9q0rzaZTRaZ5djXVwu3REAikXu64Pts08y6GRAtMmuWe3XAiPfOlxQcHOaeUylyAUahd0w1MqIObJVLJYJB7Is7vueXHfpV7p5nF7MExGJvplU7YeHmlnvosPZM7PNTDSbqgeGh443jB6QvnSkYZVZSzM1s_E_5LajtTyPmcNTvkSeKjSlrc239jtySZMgp6otixj7QoXg6gK4Xs65D4B30whY5YhpMwBCyJz-ieiPiQZKvQ9VysSIk0p8gTzIjQsy22XzcW9XTZZ02XzFacS_2MZhuh7MvU01wGEDvMd-4OJD2o6urjJnp6XWQrpx8LxN42p4BDoe7AqMoIQX4c-5G_KRFQck5DhEAce98wz38JlSihGZKgZ0j4iLifDu1DdjK61C2V3ks4D84zphVHAwikg87ThfLv2O7Gv0psVKobP2j7BdMWD4OzuZ8x6QWzqgPpKft09IxsKgQShO7KM5azh7-3ZLkYTs-8K9qQo_yesz4P2WbHs9ZnnY3WdmweSG_E-M9JWZVInWZYWvSKOidaUBYxLyG4DQQkYGmbOy0qfIdc3Zwk5J5AXCGk-McVRaI4e6lB62DMfU1rcymkV49xVIn4COWyWNzIegotfkPAKYPSEuMNHFp4I-_huZyv2zJxRcKydMa-JeeG0Hsdspa_WOy7BtvPbZ1Xc1w0K59nuMvIT4M-SAz7W0fBoglpL8nbH3Sku4rcAqWu7sGOqXoSxBA3cW8G-_7ZDCysgvF51M1-0WfGWkc7Hbmy8-Cb8cHbc802iUx_umzcXmRfOvNqqHiOyzc-H0VvfIOrFr9obArDeXdDmm0Rug2XOJjk7_m1RqOYZJodtgN95Y9YiIfzAgeD7DGSBBtqcBvrdGEIfYULsPhN6pMH0E-KPwGL-CJzZhIbd-lokQDYgUH1e4iHS1ifx_LEkjT3CmjyG6jyakOFHGMwaNBDpHU0HsXqRVPOWrn4yuCFTpXibsKE6YH-PxcC0VzQeqhVs08k37_BsJk9WObTWx_x6HVrVvoJA66uBvQSq9hUEWp_r6yVQtT_UMuAHU3i4daIPFYVH02ay0Uhm78J-iIXqZ8mjuXa0SsTmH9TslTDb_CgMwQ9dYf5gQ8UfZybswQNZaXbmX0Lt13mC0ENZiTZ2GqxrN9dgQfM9udnnru7G8BbFeQ3HgnsWbI2uaHeB1uioy9E1EGbzNzWMtZyk6GDgx7Jo7HHEnj8wgHx4oLFOkDTjYXVI_4FjRo_DOvJYpvzRCPHVmfzsm80Dmbxpf3hW9PDA4zHyO_JguVyDF5gtDmPj0JV3TfCjmQe0OgKdfUh7IAI17Q8XhUeKuh5uYzZPKUh3XVays_W98f6UwrbfbeV422g90MaRR1i-B4fveKUQzr-C3i-Etr1VEa1eNv23lxe5CvW5Vnkw_qRN_dt-0LyCse-gNt8z_xjrm-p74aUq9-Mo0rmpzBezT4lb_PMyN93-lmWTzyYXl89E9et49mZy8-uXV1tPKX5WjeblXpZG8WVVn02vpqVTlKba_WrrYqx34Uq_tZ8QquZypdJyrLP0RH3J8sMsrCfURWyOTi8hxekykp9liVZpM5EKw9SG7abFSWZO5HYQqlO5sy8HghO18m9fNFZsQLp5aPtuFH8aRe13sm_eR_vI0Qbo5mX9g6gNH5i7hGeP6tffrr2zt2mhq92-ei96g_HZ7en6-f1wrZ5mm5J9nTUzmsW9ReszxCD4aw3OLNb7tEjUFFRp07lYxulwU7TZM7wH36-yYprr1dOK5t_aXndWwLrW12j62TbPMqwq2CNSYx1eZHaMm85pbxwnyYwVp4kKtHmdqs7ngtcgagufx2V1aGYFyjxFm8ze4_MpNk-vasOK4Ks9in-uk2gVEezRTtfNVnb9naNhTEqZhzqo7VysF4W4S7O8sxtJpOxg1Uc2VqAIt9uP3cZfCd8Br4Z0liWJ3Ypbxbw7dOvl85k_eGk_H9Jj3w9evz7Yu3jz8WC2mHER_GoU7wScYa9szrs1J_Z-rW7XkOe6OndQTP2iuny1ZfydPdy3r0sVJ0W1MVh_pCGx3-QOYLbqqtCdzxj0U7N4R7OVs7RaPzegdPBd5-bYzSdwt3ms63HNf206qGoI5qSkeYluRW0_22x21VlIc8DNPNBcc8rKzyZUjGTX06k-hLUBrj16VffcXG_KifL2ShdXOoijODBBTnvJL6CtvrcJX4IAfE1wO1vv2jxtQmM3sXw0BOrLDZBPs7gwnyKKw_n1Jly17_youVpfb4C-rwNVz72-3ADZBi7mjFqWHhlhMFRm9zai9C6rvjwMSlO_37he2YNEz29sQPC9cRdVcFNTOgHzM7uxmeLUr6ev6LR_b8KrOKpXqbraANWcNannYK82sUTtuLBiaOfOBqTMg0EzQ7YZanUsruZf9WOzJaj8b8X--noTJtSOtZp_82MTJam-DnudxWFlG6y6LN7cyGBABPlwMvtZePkIo7EHkM374cxrlWaMeghFWz-o17u53gD9Q2leHX97B5X5R5oGFe5hFIy2PYzC2SyQOFuMIe7AbEL4ytU2P9bHn6VQ96ZQpXv3Rrch472xrfm236sOdMt-z-9sIt7lNG2ebHsgKTusBTswSGydKda-bc2Z3kGx0tgL85hPW4XrG5vaO3DFR7Ng776UKocbX-sjrZJyfAoZ5cMI1g9UwMgeY55ZWUASvG9Odj5wouZJpukVEGtG9r4brQ-Qna0oZFRVHvXy-akqx--j3WlsP0vyj9H_Am2iZr0=

**Comment by LocalIdentity** [comment]
We updated PoB with the changes coming in the 3.24 patch. Storm Brand of Dissipation got a major nerf which is why your build has so much less DPS in PoB now
