### ISSUE TITLE
Dark Discourse cluster jewel notable bugging out PoB

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#745]
When the Dark Discourse node is found on a cluster jewel, the whole PoB bugs out and shows the following screen (screenshot)

![darkdiscourse](https://user-images.githubusercontent.com/47370800/78886759-099d3180-7a5f-11ea-82d9-f6e92db9a382.PNG)

Checked other added passive notables on that jewel and they were not causing this to happen.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
