### ISSUE TITLE
Bug - Missing jewel & flask calculation on damage taken as

### ISSUE THREAD

**Issue by jlberlanga** [PathOfBuildingCommunity/PathOfBuilding#7452]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Last version calculate all the sources of "dmg taken as"

### How does Path of Building behave?

Now is missing the jewel and flask

### How to reproduce the issue

Just mouse over on the window physical and you will see almost all the caluculations

**Comment by Regisle** [comment]
Can you please link an example build that has the issue?

**Comment by jlberlanga** [comment]
Sure https://pobb.in/WhamUJYSqMxr

**Comment by Regisle** [comment]
Sorry that I didnt get back to this earlier, it seems its becouse your set to "buffed" and not "in combat"
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49933620/7d09f39d-d6a3-446a-8d27-6831eb4db352)

The sidebar correctly updates when flasks are toggled, and so does the calcs page when set to in combat, unsure if this has changed recently or has always been the case
