### ISSUE TITLE
My POB wont start / launch

### ISSUE THREAD

**Issue by UltraCyl** [PathOfBuildingCommunity/PathOfBuilding#7461]
Hi, POB was woking fine today and after clicking on update, it never starts back like usual . I did tried to install anew with both full and portable versions , still the same issue. When I click on POB , It just wont start. Nothing happen. I already did make it run as admin, and already did window compatible version. Nothing works . Is there a fix? I did some google search but nothing helped .

**Comment by zao** [comment]
Were you on an older version (2.39.x) before this? It is likely that you're running into the same problem as the people over in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7431#issuecomment-2017006351 .
Take a look to see if your Documents folder is in a location with non-English letters. If so there's suggestions to move it to a simpler name.

**Comment by UltraCyl** [comment]
Yea it worked fine before the update , and yes my document folder is not in english. let me find a way to change it.

**Comment by UltraCyl** [comment]
Yep it worked, I have to right click on onedrive/user/"non english document" folder, click or properties and change its current location from " non english document" to "documents". Thank you
