### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by chalvors** [PathOfBuildingCommunity/PathOfBuilding#7463]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

I can add skill gems to my builds

### How does Path of Building behave?

When attempting to add a new skill gem the application lags and ultimately crashes

### How to reproduce the issue

add a gem

### Character build code

```shell
https://pobb.in/CesrpnqnL8kv
```

### Screenshots

https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/85187242/6dd8d15b-b171-4dad-bfc2-ec0c229d877b

**Comment by Squirtrex** [comment]
Same thing happening for me

**Comment by Wires77** [comment]
The latest update in 2.41.1 speeds this up a lot.  Let me know if you're still crashing after updating.
