### ISSUE TITLE
Crashes after trying to update from 2.39.3

### ISSUE THREAD

**Issue by wildmastin** [PathOfBuildingCommunity/PathOfBuilding#7468]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Should update

### How does Path of Building behave?

If I try to install the latest release it installs but just won't start, there's even no process in task manager, I tried zip version - same thing, then downloaded the earlier zips the earliest I could make working was 2.39.3 (which is labelled as 2.40.0 on release page for some reason) when I try to update it seems to start the process but shuts down quickly, after that system asks if if still want to run it - run it anyway and the same thing, won't start, the process is not even in the task manager. Updater has the same issue it asks to press any key and shuts down

### Screenshots

https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/158079702/2f15d533-fabd-4db5-92d7-4ec34c51d16f

**Comment by bridde** [comment]
I have the same issue on Win11. And I guess you duplicate thread [**The application does not start after the update** #7431](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7431)

**Comment by wildmastin** [comment]
duplicated the thread
