### ISSUE TITLE
Crush PoB after start. 

### ISSUE THREAD

**Issue by Gadty** [PathOfBuildingCommunity/PathOfBuilding#7469]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Hi guys! An update to the latest version is required (the SSL protocol returns an error) and stable operation of PoB after installing the version, starting from 2.40.0 it crashes every time it is launched.

### How does Path of Building behave?

Hi guys! For some reason, starting from version 2.40.0 of the program, after installation and launch, the glfw3.dll library error appears every time and the program closes. In turn, when trying to update the program from version 2.39.3, it gives the error “Couldn’t download version manifest. Reason: SSL connect error.”. I checked the firewall settings to make sure the SSL certificate is up to date. I checked two Internet providers. What else can be done? I have Windows 7 service pack 1 x64 installed.

**Comment by Wires77** [comment]
Will you check this issue thread?  It sounds like you're running into the same problem as folks there and they have a workaround
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7431

**Comment by Wires77** [comment]
Closing as a likely duplicate, can reopen if it's not the case
