### ISSUE TITLE
Precision reserving too much mana

### ISSUE THREAD

**Issue by CriticalDuck** [PathOfBuildingCommunity/PathOfBuilding#747]
Precision seems to quite often reserve the wrong amount of mana, having 44% at level 1 and 372% reservation at level 20.

**Comment by dclamage** [comment]
Precision reserves a flat amount of mana, not a percentage. See wiki here https://pathofexile.gamepedia.com/Precision

Do you have an example of the flat reservation being incorrect?

**Comment by ppoelzl** [comment]
As @dclamage pointed out, Precision reserves mana like Clarity for example. This is reflected correctly in PoB.
