### ISSUE TITLE
Lua error?

### ISSUE THREAD

**Issue by Oufdr** [PathOfBuildingCommunity/PathOfBuilding#7473]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

![Screenshot_106](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165053137/0e4bb449-13b9-4bde-ac86-ba5d001c4cd5)

### What are your system specifications and configuration?

W11

### How to reproduce the issue

Just opening it and getting stuck to this i uninstalled and reinstalled nothing changed.

**Comment by Wires77** [comment]
Your Settings.xml is likely stored in OneDrive.  If you navigate to where it is stored (Usually `%AppData%\Path of Building`) and open it in your favorite text editor, PoB will be able to load it again.

**Comment by Oufdr** [comment]
Oh i see it did work! will i have to do that every time or once will do it for good?

**Comment by Wires77** [comment]
Shouldn't be every time, but Windows may decide to "help" you free up space and send that file back to the cloud.  You can try right clicking on it and selecting "Always keep on this device" to mitigate the issue.
