### ISSUE TITLE
CTRL+Z doesn't undo and closes the build on azerty keyboard

### ISSUE THREAD

**Issue by ocombe** [PathOfBuildingCommunity/PathOfBuilding#7478]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Using CTRL+Z should cancel the last action

### How does Path of Building behave?

On an azerty keyboard (where the letters Z and W are inversed compared to a qwerty keyboard), CTRL+Z works like CTRL+W and closes the current build. It used to work fine a few months ago, not sure when it changed but it's recent, I would say during 3.23.

### How to reproduce the issue

- Change keyboard layout to azerty
- Change something in a build
- Use CTRL+Z (if you have a qwerty keyboard, you probably need to hit CTRL+W, check in a text editor that the letter you typed is Z before checking this)

**Comment by rasmushy** [comment]
Same bug in dvorak, but using ctrl+Z (as where z would be in qwerty) does work.

**Comment by ocombe** [comment]
yeah, if I use CTRL+W on my azerty keyboard it works as "expected"

**Comment by sida-wang** [comment]
Thanks for the report, we're aware of this issue that's caused by the recent changes. It looks like the framework being used is sending keycodes rather than the layout dependent keys. We have this on the short-term to-do list so hoping to have it fixed soon.
