### ISSUE TITLE
Crash on clicking scrollbar on alternative skills dropdown in skills tab (attempt to index field 'sortCache' (a nil Value))

### ISSUE THREAD

**Issue by canuysal** [PathOfBuildingCommunity/PathOfBuilding#7484]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Holding scrollbar with mouse to drag should work as expected in skills tab

### How does Path of Building behave?

Clicking on scrollbar in the skills tab while checking alternative skills results in a crash

### How to reproduce the issue

I'm currently in developer mode.

1. Open a build
2. Open skills tab
3. Click on any skill to open recommended skills dropdown
4. Click on scrollbar

### Character build code

```shell
https://pobb.in/qymeL8n9wGND
```

### Screenshots

![Screenshot from 2024-03-27 07-30-39](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/59864253/bee12961-a071-4692-bb5d-a8ece041c736)

**Comment by Wires77** [comment]
Fixed by #7459
