### ISSUE TITLE
Mark mastery can be allocated without Relentless pursuit notable

### ISSUE THREAD

**Issue by Dimmitsaras** [PathOfBuildingCommunity/PathOfBuilding#7493]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Mark mastery cannot be allocated without Relentless pursuit notable
You can *not* allocate the mastery with "just Mark mana cost" allocated
You can allocate the mastery with "Mark cast speed" and "Relentless pursuit" allocated
You can not allocate the mastery with just "Mark cast speed" allocated

### What is the behaviour in Path of Building?

Mark mastery can be allocated without Relentless pursuit notable. 
You *can* allocate the mastery with "just Mark mana cost" allocated
You can allocate the mastery with "Mark cast speed" and "Relentless pursuit" allocated
You can not allocate the mastery with just "Mark cast speed" allocated

I assume "Mark mana cost" is probably tagged as a notable

### How to reproduce the issue

1. Start with any blank passive tree
2. On the relentless Pursuit notable cluster, click on the mastery icon and allocate any mark mastery
3. Mark mastery is allocated without the notable

### Character build code

```shell
eNqtW1134jYTvt7-Ch-uScA2NtBD2kMSssnbsKGQ7LZXe4QtQI2QqC0noe_pf-_IssFhkWNj70UW0MwzH9KMZsYw-PVtTY0XHISEs4uGed5uGJh53CdsedF4erw56zV-_eWnwQSJ1cPiMiJUrvzy06dB_Nqg-AVT4HMbhkDBEouvKZT9HaA2iIkV5myM_uLBZ-5fNL5whhvGHDGfiPSdR1EYfkFrfNGYecDcMFDoYeZf7T9PCFcoQJ7Awb0UO4wEH3MfVkUQweoaETbj3jMWnwMebUCrhvFC8KuiuRtPHqaPGZUIy6oEJn0aTCja4mAmkDBC-HPRGIJn0BJfozX8BTREI4Cyzvt2p9uz3HbP7TvdRiuX-TIKQnEawmyDsb9jMs8tHeEkwKPFAnuCvOCrgIirFWLeXlxbx1eWdhxRQTaU4CCjlaPjuP0B3Gxr4R-5QPR6MtvR2ueOZXbtvmm3O3anl8_HxccGfCNidUnBoydIkbx3S0YEPpF5wknIWQX7sqz6PYoohfgsRDvFIQ5ekCDv1dJj8_WcsJO8N0YMXfGwwB5JygkOIPpFKYYZ9jgkjLIySnLekwUuTlnKjoShrDan2TGaFaUrDXyaQlNIjsUoZzyiBSnFPknZ2hx1jd-KZKc7tpdotfVgL1zEF9hHysVRPbqd7EEt87zvuJ2u6XZ6Tkeb6FfbkHiIjtEbWUdryLCP6BmzDIytPy7LlWCQHXS8ptvX8d6QAJ_AdsWpfwrbCvFQy2f39YFN2C1UFkPPi6BO2Ga84uYFURHvwVXs_SyJ75hXLDSfWBBn2MwNnrs7CzyFiJE1w5zioix7IUngFTnMStYSs0TgtphB9xh7q8_g4ykSuFia3Wtj9XI9K4kLeVYSHvFsDv57jhJukozH3WTpKzHJVNJRI4aD5Xa2Ipj65ahTxa7QpkA-lH7Ochfy93txpc5MlrWkS76hwC92a5TV6QWF2QRtWfnuUuRZT1na3DzGUFwCh48Pqt6csp3_JYt2Wo5tGKx5FBTccUVczIL0dlHdyhT7kVfsOruk0HcVbSRALUpLcQyFQN7zNfeXuJSQUhy7BipmnUWbDeQMuftFAeQlCUU1yRQnZ7b1MfUDHN1CESyv0-IC9tSFBexKhOJSDliK2yLv-EMxbhHywiJ2GzqG5LCGpB-302OeuTW0mwN9VKGmKCYs2JxN-CtovpJjkrAcNdRC-1JWq0qA2T_bwvjvyAsJGDEfyioIhcIyDjmOiXkka8ibYXiNBDL8pID-igKCmLDiGU6IUeCt7mHrbxClc8gEF43sp_LdAaOZ7u2gFc-p5Ku79YYHwsBv8r8JCsT2orFANMSKMP4EcEJBWNwUQ9qhtGHMVvx16L9IKx45p2HKZKDNBjP_HcZjgLGB0iTiSSViG-UbY41CAXeUOpUA83_X6jr9JjTQjv3vu5HXnS99ajAO2oCjLMdxmma7Z_Wbpmu63abTafeaZt_sdJq247Ttpgv9t9t0baiNm6bZ6XebCttt9ztW03Z7PbPZ6fWsXtOye03bdoC_60rhttPtNJ1ez7alR2XDhoLt8L0qjIAbBJiWme3BHaLGdkpXaeWnwdP0Pn7xaSXEJvy51Xp9fT3fILHiC_wGl9y5x9etDTCBf87CZ0LpmYRtDeHf5XI4HP3RC357bn__39vTchaS34Kzvtv_exy6iyfWXbq_j-Zub_jgXjmXdtB--nM49CKnP_MuYuGtVPpAzQDDlnon00VAwJPquLXkXsQHQ26WfPGFCxzKNflh-mYwk-qFRghn5TNeh5dbCPEbWckcDEKS3ZbUMyzUec3ypMNJHy9QROXnv0eIEnn42tlP79UglfFgvevuAAoOn7yJFOLjdiMPxPD-Xq0MqUjApLj0JKoTlyhkEH8fCsom-fIKUS-2eXDHNpEwWDxkXZPQ-z6PFgs5MQURIoinwKObm9HV493XURKxWZZ4F7-zaD2XI0H1_z6vznBcPxhhNA_Vy4vGV4JfY0WusUCEQhbxOKVoE-JdLMVKJxZQ4MtBi6mgR0znq8ex9gR6pNEbDiD0l1B6egHBWr126x8opQTKslRmOB2aHFzqgVTdcwWJQ5XNGk_FU2I9ihzcas2Rizm8kDQR1UpOVj_whJDHFqKOLIgnL4f8LZeHXFHl-GXX4Gv3Oyna9BjxJFgHoBb1zGqaq-NOVnO8Gk-StV5Vq3r2a-whre1qUc-868Q4AzfpUHZUOUhfOIsPOQTNkFBZYGl3dkTxjkQP-CBWOEjuRx3SGHJUSpIbOAGZR0IfxhmKHF_FwyGNh-SanlVNPzQ2yLWcTPRuHqBxaJZGD6X6aG0iy2NVxbbWf0npnrMFSZOqcb9azXFC2qhr7E-Wc4Ikzr_DF0581b5pwuWALC9hQF1RHSbuSavDHDap1RFvoJx71u53sqpnfxJEViJHUFQBVAhEBlU1BBlb1RCmh4XEnneaX0Ls-qKjzOlqXuAn7dLJCKqpO5k97jlP5o7T9zVeYLAgN3_vaHKOt4jYNThD5BztglCxWsfzwN66UljqJjtqaWlEFZ_JI468EFYkHwDBVXybU-wVQ9rNTW4xovLJNafVAH94lFPJTi5CxPxrOfetaKgcG0cbAEs1ezhWre-39BB10Er7qLjzl51NMpaYiUBOJf7hfP3nRePM7FrOedd23T405B31edLwmVbS5UHJe03A80F8YlKxkvIPQLC6Xfvcsq12t2-rZ1mDOwFNX9J_ytdp-xmFWD16_YbRhrP4Y9nCq95NEWqJkn4xaaQphwYSOCZzaK6lQarpUzwGyJKLagLQyme5xFQYw_k2DBE1VINuWCX4U5GHGE55DKsGDNOYvaLNIZBbg0FuDQaVwbjkEE-HAHYJgFsM2fCHva16Nk5yw7E9cWrYE7MGjE5Jh9R1JusIsjIYcXlVyutHT6BV8fzYpVUus0GfKX_BYZVjcjxq3NIIpc00K5tZZm-H64hiUcMRtGtIi3Zl0zul3V3mHE-hejslXlXiK21c1RB1Sjuj-rViVUaorkOnquM6deV2u5Qm_tZQU5f685ZT121t1mORVXWLSldQlVOLW4_lTmVF7LIZy6zqbLOG3F5bTDn17INbsX6pXo1UraBqCkW7rtRQG9AprcVpvqjrTNa0FSfHSMWTVNvtYNWQKOrAMOsyqLas9SPQoJWMeuI5VTwrih_8c7Ygy_TbOh5ecerjIBGBGV5vk98cpY_yu9nvxx6jz_6EKGVytCwhWRL6sIgHzTOB4mn54bcGcgSlj_lTFvsD5dI43Imw8umTLz5ySqeIZQV1PxD0_puTGb58tt1TrpTe1TOsd7-9kr8nwgH2Z_G3A3jExAzTRcZKJx1PJrs9aB3-fu8_WQnJ9w==
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/35996393/bb255b68-d579-42f2-b7df-d5638e74db24)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/35996393/a5557001-3ec4-4838-a800-3a8d16dcfe89)

**Comment by Wires77** [comment]
It's a data issue on GGG's side.  We should have better data by league launch and it'll be fixed then.
