### ISSUE TITLE
My POB havent launch when i open

### ISSUE THREAD

**Issue by blingee** [PathOfBuildingCommunity/PathOfBuilding#7494]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

My POB havent launch when i open
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/85160795/a5db9621-bfc9-4442-a64e-e4d49caf9555)
Please help me

### What are your system specifications and configuration?

AMD 6600XT
AMD Ryzen5 3600

### How to reproduce the issue

I have updated my POB.
And then i couldnt open.
just double click and POB havent launch UI yet.
It's just havent happen please help
i have remove, reinstall many times and still got the same

**Comment by Wires77** [comment]
Have you taken a look at these issues and tried some of the responses from there? https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7487 https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7431

Another thing that would be helpful for us to diagnose would be to check Windows Event Viewer for error logs, or your `%LocalAppData%\CrashDumps` directory

**Comment by blingee** [comment]
> Have you taken a look at these issues and tried some of the responses from there? #7487 #7431
> 
> Another thing that would be helpful for us to diagnose would be to check Windows Event Viewer for error logs, or your `%LocalAppData%\CrashDumps` directory

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/85160795/b1ac4d60-ca84-4adb-8e9a-59592cc6678e)

i got these
and
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/85160795/e9cc0917-1f16-4343-a9ab-eeee0ba9f64e)

**Comment by blingee** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/85160795/1b86603f-06ec-441a-9c1a-8a744b13a022)

**Comment by blingee** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/85160795/528eb300-756c-46e3-afca-58db9396078b)

**Comment by zao** [comment]
Fault offset is `abort()`, it's likely the localised Documents problem as described in #7431.

**Comment by zao** [comment]
Issue addressed over DM, was localized Documents.
