### ISSUE TITLE
resolution issues after 2.40.0 update, old win7 system

### ISSUE THREAD

**Issue by brzroman** [PathOfBuildingCommunity/PathOfBuilding#7496]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

PoB app resolution should match system resolution (1920x1080 in my case)

### How does Path of Building behave?

currently PoB uses low resolution (check screenshots), happened after one of the march updates.

### How to reproduce the issue

1. Launch PoB
2. Notice non native resolution for your system
3. Can be a case of old OS (windows 7), if I can provide any additional useful information about my config/system, let me know

### Screenshots

![pobscr1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/98549382/137178c8-e76c-4162-9063-2d5ced4743fb)
![pobscr2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/98549382/5411b6f7-ab1b-445e-8676-9296c955be17)
![pobscr3](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/98549382/41820078-fa97-4a03-881b-6896019ab407)

**Comment by brodiemvl** [comment]
same issue here for me

**Comment by Razunter** [comment]
Probably related.
Windows 11, 3440x1440... PoB started scaling to my resolution, but everything is blurry now and there is no option to disable it.

**Comment by NinjaBlazin** [comment]
Same here, PoB looks super blurry on my 1440p monitor.

**Comment by Wires77** [comment]
> Same here, PoB looks super blurry on my 1440p monitor. Also using 1.25 custom scaling.

Gonna release this soon that should fix it, but if you want to confirm it works for your situation, can you download `
SimpleGraphic-x64-windows.dll ` from this link and replace your existing `SimpleGraphic.dll`?  https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/actions/runs/8478133540

**Comment by NinjaBlazin** [comment]
> > Same here, PoB looks super blurry on my 1440p monitor. Also using 1.25 custom scaling.
> 
> Gonna release this soon that should fix it, but if you want to confirm it works for your situation, can you download `SimpleGraphic-x64-windows.dll` from this link and replace your existing `SimpleGraphic.dll`? https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/actions/runs/8478133540

Yes, that solves it, thanks!

**Comment by Razunter** [comment]
> > Same here, PoB looks super blurry on my 1440p monitor. Also using 1.25 custom scaling.
> 
> Gonna release this soon that should fix it, but if you want to confirm it works for your situation, can you download `SimpleGraphic-x64-windows.dll` from this link and replace your existing `SimpleGraphic.dll`? https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/actions/runs/8478133540

This helps if scaling is set to "application-controlled", thanks.

**Comment by Wires77** [comment]
Closing as fixed in 2.42.0

**Comment by brzroman** [comment]
> Closing as fixed in 2.42.0

for me issue is still present in updated (2.42.0) PoB

**Comment by brzroman** [comment]
@zao no, no dpi settings is used for the pob app. system resolution is 1920x1080 and for some reason pob uses lower resolution.

i checked both registry folders, no mention of pob.exe there

**Comment by zao** [comment]
Path of Building is aware of the display scaling in your display control panel and scales the window contents by that percentage as a good desktop citizen.

There's two ways to get it to not scale:
* change your display scaling factor to 100% globally,
* override the display scaling to be performed by the "Application" in the EXE properties.

This was the case before the new runtime in 2.40 and now also with the recent fix in 2.42.0 which makes it understand the override once again. From version 2.40.0 and up until 2.42.0 it didn't understand the override as I assumed that if you have a scaling factor you want to use it.

**Comment by brzroman** [comment]
After some digging i figured out i have some kind of global DPI scaling, my bad, sorry for misinformation.
![pobres1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/98549382/9c4106e1-7c20-4a1e-950b-cded65262366)

So when i swap from x1.25 to x1.0, PoB goes back to normal 
![pobres2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/98549382/472f269c-7188-4c6d-a690-0fba7e83e739)
(text in the browser and OS interface gets really small, not usable for me sadly)

There is compatibility tab for the shortcut/exe file, but for some reason setting i need, "disable display scaling on high dpi settings" is greyed out
![pobres3](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/98549382/5c2381aa-81bf-44ce-a517-9bc5eba0ecc7)
Found one mention of this problem here
https://superuser.com/questions/282648/windows-7-cannot-turn-off-dpi-ppi-scaling-for-an-application
"it may be because Microsoft built logic to deny this setting for 64 bit applications."
Which seems to be true, setting is available for exe files of old games on my PC.

**Comment by zao** [comment]
As Windows 7 seems extraordinarily silly here - I recommend that you either use the suggested app compat tools to set the flags for you, or set the Registry key yourself which will check the disabled checkbox if done correctly.

1. Determine the full path to your `Path of Building.exe` by looking at the shortcut to the EXE.
2. Open a command prompt.
3. Run the following, substituting your EXE path:
`reg add "HKCU\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Users\Lars\AppData\Roaming\Path of Building Community\Path of Building.exe" /t REG_SZ "~ HIGHDPIAWARE" /f`

Steps 2 and 3 could also be done interactively in `regedit.exe`, adding a string value to that `Layers` key (creating it if it doesn't exist) with the Name of the path to the program and the Value the string `~ HIGHDPIAWARE`.

There's unfortunately no good way of detect the user intent in this scenario and there's no good place in PoB to wire up an option for it until we finish work planned for way later around scalable UI.

**Comment by brzroman** [comment]
Thanks a lot, registry string fixed my PoB, way better UI now. Appreciate your help.
