### ISSUE TITLE
Path of Building takes forever to start up

### ISSUE THREAD

**Issue by orlp** [PathOfBuildingCommunity/PathOfBuilding#7503]
Since a recent update (I believe the new graphics engine), Path of Building takes like 20 seconds to a minute to actually show the window after starting the program.

I'd love to be able to help diagnose this problem, because I feel it is rather excessive.

**Comment by zao** [comment]
The core culprit for many slowdowns is very varying performance of LuaJIT builds, having a correlation of how small the DLL built with how fast it is. We shipped a LuaJIT build that we see is faster for overall tasks like skill gem selection in a recent patch.

There's been other issues raised that claim similar slow startup times and it would be great if you might be able to identify any interesting aspect of your PoB installation.

Do you have a lot of builds, are the builds on a network share, any non-Defender antivirus, any highly complicated build open?
Does it have similar slow startup if you boot up into the Builds menu rather than a specific build, and does it differ if you save an empty build?
Does it do it if you run a completely separate portable PoB installation with no builds and settings.xml around?

**Comment by zao** [comment]
For comparison, typical startup duration on my machines is maybe half a second to black UI and a few seconds more until frames start flowing normally.

Try launching PoB with `--no-jit`, see if it gets better/worse.
If you have a profiler handy like Superluminal, a capture from that would be nice to have.

**Comment by 7ekken** [comment]
I'm back in on this.  Earlier today I full uninstalled 2.39.3 and did the full install of 2.41.1.  After accepting the Win Defender blue warning the app installed fine and it worked very quickly as expected sub 2 seconds full functional launch.  After opening / closing the app multiple times then restarting the pc, the app is unbearably slow to start up... at least 10-15 seconds.  

I didn't notice anything special in task manager that jumped out at me to explain this.

**Comment by orlp** [comment]
> The core culprit for many slowdowns is very varying performance of LuaJIT builds, having a correlation of how small the DLL built with how fast it is. We shipped a LuaJIT build that we see is faster for overall tasks like skill gem selection in a recent patch.

I do believe that is actually faster for me as well now.

> Do you have a lot of builds

I don't think so? 12 right now.

> are the builds on a network share

Nope.

> any non-Defender antivirus

No.

> any highly complicated build open?

Nope, same issue booting into the builds menu.

> Try launching PoB with --no-jit, see if it gets better/worse.

Seems about the same.

> Does it do it if you run a completely separate portable PoB installation with no builds and settings.xml around?

Downloaded the latest release as a portable installation and launched it, same slow startup.

**Comment by orlp** [comment]
Pausing Path of Building.exe a couple times with a debugger it seems I'm running into this: https://stackoverflow.com/questions/10967795/directinput8-enumdevices-sometimes-painfully-slow.

**Comment by orlp** [comment]
Yes, that was the issue, the problem wasn't in Path of Building itself. Apparently I have some device with a shitty driver that makes `EnumDevices` take forever. Using the open-source tool [HidHide](https://github.com/nefarius/HidHide) I was able to identify and hide it from the system.

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/202547/51998d7a-b62a-4087-808c-9ebb135f6be4)

It may sound insane but if I hide that device Path of Building starts up instantly, if I don't it takes forever, it's completely reproducible. I will close this now, perhaps it helps others.

**Comment by zao** [comment]
Nice digging! It's definitely something that's going to crop up for people over time as there seems to be an endless supply of less-than-stellar HID devices.

**Comment by zao** [comment]
@orlp Would you mind unhiding your naughty device and try with the GLFW3 from the GH actions of a tentative fix that skips dinput8 in GLFW completely? https://github.com/zao/PathOfBuilding-SimpleGraphic/actions/runs/8493182979
