### ISSUE TITLE
Application throws error: "No Error" when deleting empty folder

### ISSUE THREAD

**Issue by krss** [PathOfBuildingCommunity/PathOfBuilding#7508]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Application is supposed to delete folder then refresh the current folder contents, optionally with a success message.

### How does Path of Building behave?

When deleting a folder you receive this message:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1586853/fe4e693f-fb02-40b5-802c-2a14d860e27d)

despite deletion being successful, however it still shows up in the folder view until manually refreshed, by either opening and closing a build or navigating back and forth to another folder.

### How to reproduce the issue

1. Create new folder
2. Delete folder

**Comment by Maaziasq** [comment]
I'm also getting an error with creating a folder since the latest update

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/46649712/2378e27c-8e5a-4893-bcb9-94ca3c503b09)

**Comment by Wires77** [comment]
> I'm also getting an error with creating a folder since the latest update
> 
> ![image](https://private-user-images.githubusercontent.com/46649712/318056739-2378e27c-8e5a-4893-bcb9-94ca3c503b09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDA3MzAsIm5iZiI6MTcxMTc0MDQzMCwicGF0aCI6Ii80NjY0OTcxMi8zMTgwNTY3MzktMjM3OGUyN2MtOGU1YS00ODkzLWJjYjktOTRjYTNjNTAzYjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE5MjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOTEzNDMzZjViZjEyMzA4NTBjMjU3NGZmMjFlOWZhYjc1MzhhOTIwNDY0OTA1ZjRjMmE1ZWM4MWM3ZmMwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CZM1ji4b5d2qKyrrDTMo5ZpcgdwmMGJwB6rdPbEEOPU)

Can you go into detail about how or where you're creating the folder?  I can reproduce the error when deleting the empty folder, but not when creating one.  Does the folder actually get created, too?
