### ISSUE TITLE
I can't see the Medium Cluster Jewel, etc. connected to the Large Cluster Jewel. 

### ISSUE THREAD

**Issue by poby70** [PathOfBuildingCommunity/PathOfBuilding#752]
If you look at the POE site account, you can see a Medium Cluster Jewel connected to a Large Cluster Jewel as follows.

It's a Jewel in the right three o'clock direction:
[https://poe.game.daum.net/account/view-profile/sp_sp/characters?characterName=코브라찍찍](url)

The POB does not show any jewelry. However, displayed when replaced by another Jewel.
Pob: https://pastebin.com/rmzesai5

**Comment by LocalIdentity** [comment]
Same issue as https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/716
