### ISSUE TITLE
Spell Suppression calculated differently on the left side vs. on the "Calcs" tab

### ISSUE THREAD

**Issue by PalchekVikin** [PathOfBuildingCommunity/PathOfBuilding#7522]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In game Spell Suppression shows 76%

### What is the value from the calculation in Path of Building?

"Calcs" tab shows 76% (same as ingame), but on the left side it shows 94%.

### How to reproduce the issue

1. Select any passive points that grant Spell Suppression
2. Select the "Chance to Suppress Spell damage is lucky" mastery
3. The calculation on the left side is different than the one on the "Calcs" tab

### Character build code

```shell
https://pobb.in/HS_BlBGLNGkB
```

### Screenshots

![spellsupp](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/116655410/cd55d2da-a2e8-4d13-aa1f-bc82a07d8c77)

**Comment by Paliak** [comment]
The left build panel is showing the effective spell suppression chance (you have spell supression mastery allocated). Aka:

```lua
EffectiveSpellSuppressionChance = (1 - (1 - SpellSuppressionChance / 100) ^ 2) * 100
```

Where `SpellSuppressionChance = 76`
