### ISSUE TITLE
An error pops up after installation

### ISSUE THREAD

**Issue by I7uBaC** [PathOfBuildingCommunity/PathOfBuilding#7523]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

there is an endless download of the build import

### How does Path of Building behave?

if I try to open it immediately from the site, then it's just a very long black screen

### How to reproduce the issue

After installing the application, an error immediately pops up, and you cannot import the build

### Screenshots

![125](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165548960/453d2660-1eaf-419f-9130-e51cbb9e72b7)

**Comment by Nightblade** [comment]
What exactly are you importing?

**Comment by I7uBaC** [comment]
> Что именно вы импортируете?

[https://pobb.in/of5bENFuieXP]

**Comment by I7uBaC** [comment]
> Что именно вы импортируете?

but that's not the point, when installing the program immediately upon logging in, this error occurs, and that's it

**Comment by MrKim4a** [comment]
![Screenshot_1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165568601/878e2fad-f9cd-4cd4-b96d-3c0ba842b0f2)
i have same error today, It was working yesterday.

**Comment by Paliak** [comment]
Is your Settings.xml file stored in onedrive? If you installed POB with the installer it should be in your documents folder.

You could also try deleting the Settings.xml file and see if that fixes the issue.

**Comment by MrKim4a** [comment]
> Is your Settings.xml file stored in onedrive? If you installed POB with the installer it should be in your documents folder.
> 
> You could also try deleting the Settings.xml file and see if that fixes the issue.

No, the folder in documents is not onedrive. Deleted the file didn't help, it doesn't open pobb from the site, I have to enter manually.

**Comment by Wires77** [comment]
Can you post your Settings.xml here after removing the `<Accounts` section?  Trying it myself in several different ways works fine, so I'm not sure what the issue is.  Can you also press CTRL+` to open the console and send a screenshot of that output?

**Comment by I7uBaC** [comment]
> Можете ли вы опубликовать здесь свой Settings.xml после удаления `<Accounts`раздела? Попробовав несколько разных способов, все работает нормально, поэтому я не уверен, в чем проблема. Можете ли вы также нажать CTRL+`, чтобы открыть консоль и отправить снимок экрана с этим выводом?

I have a portable version, is that what you asked for?
![124](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165548960/7c45c0ee-dc4a-4b2c-841f-312e8db04a1a)
![125](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165548960/d801255c-c012-43f4-9417-e2fdddd8efd1)

**Comment by I7uBaC** [comment]
> Can you post your Settings.xml here after removing the `<Accounts` section? Trying it myself in several different ways works fine, so I'm not sure what the issue is. Can you also press CTRL+` to open the console and send a screenshot of that output?

I have a portable version, is that what you asked for?
![124](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165548960/cf84d067-0df8-4108-95a8-35a3103070af)
![125](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165548960/2a42a5a9-2b3b-4f4a-b221-ab4386f480b1)

**Comment by Wires77** [comment]
@I7uBaC The portable version doesn't have the error, right?  So if you can post the same thing from your installed version that has the error, that would be what I'm looking for.

**Comment by I7uBaC** [comment]
> @I7uBaC The portable version doesn't have the error, right? So if you can post the same thing from your installed version that has the error, that would be what I'm looking for.

there is no error in the portable version, but still I can't download more than one build, in the same way there is an endless download

**Comment by I7uBaC** [comment]
I checked it now, everything worked, for some reason, although I didn't do anything

**Comment by MrKim4a** [comment]
> Can you post your Settings.xml here after removing the `<Accounts` section? Trying it myself in several different ways works fine, so I'm not sure what the issue is. Can you also press CTRL+` to open the console and send a screenshot of that output?

![Uploading Screenshot_1.jpg…]()

**Comment by MrKim4a** [comment]
is if I just open the installed pob

**Comment by MrKim4a** [comment]
![Screenshot_3](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/165568601/393948a7-b236-4a17-9294-ae42898ab20d)
maybe this would be more convenient.

**Comment by Wires77** [comment]
@MrKim4a it looks like you sent two different Settings.xml files.  The second one is the issue, where it just says `<Mode />` instead of being populated by the data in your first screenshot.  I was able to naturally get that error, but I'm not certain how it came about, as I can't reproduce it again without manually editing the Settings.xml.
