### ISSUE TITLE
Mana gets multiplied by 0 with Blood Magic, so it does not show up

### ISSUE THREAD

**Issue by BogdiB** [PathOfBuildingCommunity/PathOfBuilding#7527]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Calculation is total_base * total_increased.

### What is the value from the calculation in Path of Building?

0, it does not show up. PoB wrongly multiplies by 0.0 (from more/less modifiers that don't exist) at the end of the Total Mana calculation.

### Character build code

```shell
https://pobb.in/qywzwbdg3Lzm
```

**Comment by LocalIdentity** [comment]
Please provide more detail and make sure you're on the latest update. I see the life cost as being correct
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31035929/faaf6d12-0642-4a9d-b699-1e91cea200c3)
