### ISSUE TITLE
Lightning Golem Wrath Aura + Arcane Surge Support crash

### ISSUE THREAD

**Issue by Ayjay** [PathOfBuildingCommunity/PathOfBuilding#753]
I replicated this on both master and dev branches.

Steps to recreate:

1. Create new build
2. Add new socket group
3. Add "Summon Lightning Golem"
4. Select Configuration tab
5. Check "Enable Wrath Aura"
6. Select Skills tab
7. Delete "Summon Lightning Golem" socket group
8. Add new socket group
9. Add "Storm Brand" to group
10. Add "Arcane Surge" to group
11. Click to try to add another gem to group
12. Observe [crash](https://user-images.githubusercontent.com/433210/79019661-36199080-7bba-11ea-826b-bdccc7b349d8.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
