### ISSUE TITLE
Update Check Failed - Invalid Local Manifest

### ISSUE THREAD

**Issue by sk3l3tom** [PathOfBuildingCommunity/PathOfBuilding#7536]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

When I open PoB, the update check should complete and let me know either that I have no pending updates or that an update is available. 

### How does Path of Building behave?

PoB returns an error saying 
"Update check failed!
Invalid local manifest."

The bug is not build specific. Screenshots below are from after I manually dismissed the bug and attempted to check again.

### How to reproduce the issue

1. Open PoB
2. Update check fails and error message is displayed. 
3. If error is dismissed and "Check for Update" button is pushed, the update fails again and the error is displayed again. 

### Character build code

```shell
https://pobb.in/u-5YtA0fiRvL
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/129226388/d90627ee-26ca-49b2-b817-b363a6a38fb5)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/129226388/e226c9d8-f64d-457b-aa86-c0fd086d2612)

**Comment by Wires77** [comment]
Can you find your manifest.xml file in that app data folder and post it here?  Compare the first lines with the one stored in this repository, as I'm guessing you're missing the version number

**Comment by sk3l3tom** [comment]
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/129226388/69b67c3a-e2a4-478b-bb9c-b3bf02803ca4)
I appear not to have a manifest file. I will attempt to download the manifest.xml file directly, put it in this folder, and update the issue.

**Comment by sk3l3tom** [comment]
Downloading the manifest from Github manually and putting it in the folder has put me in dev mode. Deleting the downloaded manifest file returns me to the originally reported behavior. I think I'll probably be fine with a reinstall but I'll wait a little to do that in case any of you have any questions or would like me to try anything else.

**Comment by Wires77** [comment]
Yeah, that manifest looks pretty corrupted to me.  A reinstall will certainly solve it, but if you want, changing the `<Version>` line at the top will fix it also.  Here is mine from my installed PoB:
```<Version number="2.41.1" platform="win32" branch="master"/>```

**Comment by sk3l3tom** [comment]
A clean reinstall fixed this issue.
