### ISSUE TITLE
Berserker Rite of Ruin rage degen not accurate

### ISSUE THREAD

**Issue by Durandle** [PathOfBuildingCommunity/PathOfBuilding#754]
berserker rite of ruin rage degen is 1 per 1000 per rage rather than .1% per rage
this causes you to get an extra 50 life degen as you reach 1000 life thresholds

in game testing in delirium 3.10.1c with my current 3973 hp and 4.98% hp regen and no sources of flat regen causes me to start slowly losing hp in line with the expected .1% per rage and not with the threshold based 1 per 1000 per rage

**Comment by dclamage** [comment]
I've created pull request #763 to fix this.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1

**Comment by gonferjim** [comment]
I was PoBing my Berserker build and found this problem, not sure when it returned or why.

**Version: 2.55.0 (Beta)  Date: 06/30/2025**

Capture when your life is close to the floor of a 1000 threshold:

_I have put the same Life used in #763 (Understand that now Rite of Ruin makes 50 rage have the effect of 75 = It should be 7.5%)_

![Image](https://github.com/user-attachments/assets/f27f3bc2-b9da-48e4-ba10-9ab7ab5bcef0)

As you get closer to the next 1000 threshold you get the appropiate 7.5%:

![Image](https://github.com/user-attachments/assets/0d7b752d-dca2-467b-acfe-08dabc837769)

The Configuration used in the captures:

Level 1 - Marauder > Berserker
Ascendancy:  Crave The Slaughter > Rite of Ruin
Rage:  50

Custom Mods (For 1st capture):
1240 life
72% increased maximum life
+20 to maximum rage

Custom Mods (For 2st capture):
1674 life
72% increased maximum life
+20 to maximum rage
