### ISSUE TITLE
Perandus pact not showing stats it increases.

### ISSUE THREAD

**Issue by Weltszmelc** [PathOfBuildingCommunity/PathOfBuilding#7541]
![obraz_2024-04-06_043318966](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/166191841/152d6941-23cf-442c-bccd-9e5f6d393fc4)

perandus pact not showing what it does, not only in description stats of character also dosent change

**Comment by LocalIdentity** [comment]
Fixed on dev and will be in the next update
