### ISSUE TITLE
I can't open my account.

### ISSUE THREAD

**Issue by barebyh1** [PathOfBuildingCommunity/PathOfBuilding#7545]
Hello.
The problem is that I can't open my account. He always writes that the account is in private, but this is not the case and POESSID does not help either. The account name is in Latin. I asked my friends to check everything is fine with them , tried to reinstall , the problem was not solved .
![2024-04-07_06-18-35](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/152603238/0a33c5ba-0e13-4b1d-8232-490eaf6cb36e)

**Comment by Paliak** [comment]
What's the account name?

>The account name is in Latin.

POB currently does not handle utf-8 (but there's work being done on that front). Though if it works for your friends then the issues has the be somewhere else.

**Comment by barebyh1** [comment]
https://ru.pathofexile.com/account/view-profile/barebyh

**Comment by Paliak** [comment]
I assume you're just using the PC realm? Does 
```
https://pathofexile.com/account/view-profile/barebyh/characters
```

open just fine for you or are you redirected into the ru subdomain?

If you run this in powershell:

```
curl "https://www.pathofexile.com/character-window/get-characters?accountName=barebyh&realm=pc"
```
and this:

```
curl "https://ru.pathofexile.com/character-window/get-characters?accountName=barebyh&realm=pc"
```

what are the responses?

**Comment by barebyh1** [comment]
![2024-04-10_20-16-31](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/152603238/f58520a4-878d-4f8f-ba7a-9ece4224de45)

**Comment by Paliak** [comment]
Hymm. You should be able to import your character normally. Does it work now? Could've been something on GGG's side.

**Comment by barebyh1** [comment]
No , it doesn 't open .
Should I contact GGG support?

**Comment by Paliak** [comment]
I don't think GGG support will offer help with 3rd party tools. Right now the only thing i can thing of is your location (since you're getting forbidden on the http response) + some cert authority shenanigans being the issue.

You could try using a vpn / mobile tethering to see if that makes any difference.
