### ISSUE TITLE
I have a question about the name of the item.

### ISSUE THREAD

**Issue by poby70** [PathOfBuildingCommunity/PathOfBuilding#755]
I solved a problem that jewel couldn't see on the first question.

I am a country that does not use English. So I changed it to SimpleGraphic.dll made in China.
If I changed the file and made a translation text file in the ZdDroid folder, I could see it in Korean.

I know that item names are made by combining suffixes and prefixes.
So I made a translation file by referring to here.
https://pathofexile.gamepedia.com/Rare_Item_Name_Index

The name of the flask was translated by combining the suffix and prefixes separately.

It was the result I wanted.
However, you have to enter a combined name for the jewelry and item names to be translated.

It is too hard to translate names by combining all suffixes and prefixes.

Even if you translate the suffix and prefix separately, like the name of the flask, can the translated name be combined to become one?

The contents of the translation file are as follows.
{"en":"Bubbling","cn":"sentences translated into Korean 1"}
{"en":"Hallowed Life Flask","cn":"sentences translated into Korean 2"}

If you do this, you can see the name of the flask translated from POB.
However, item names and jewelry names are not being translated.

If it is difficult to answer, can you tell me the file that combines the suffix and prefixes of the flask name and item name?

I'm not good at English, so I used Google Translator.
I hope you understand my writing even if the sentence is a bit strange.

**Comment by Regisle** [comment]
PoB doesnt currently support translations to my knowledge but Im sure its on somones todo list somewhere

I would recommend looking at how the official translations for the game are done and do that

**Comment by poby70** [comment]
Thanks for the quick answer.
I know that the POB does not support national translation.

So, instead of using SimpleGraphic.dll included in the original POB, I am using SimpleGraphic.dll that supports translation.

No other POB files are touched, only the SimpleGraphic.dll is modified, and additionally translated files are added to support the native language.

As you can see in the photo, the flask and unic names could be changed, but the items and jewels did not.
[https://i.imgur.com/hhFOGu3.jpg](url)
[https://i.imgur.com/tWpgzvc.jpg](url)
[https://i.imgur.com/My97WxH.jpg](url)

**Comment by ppoelzl** [comment]
Changing the Lua host to a different language does not accomplish i18n, as you could only have one language at a time then. For further discussion on this topic, please refer to #999 instead.
