### ISSUE TITLE
Crush when im import builds with The Perandus Pact Prismatic Jewel

### ISSUE THREAD

**Issue by xpapahet** [PathOfBuildingCommunity/PathOfBuilding#7553]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

![Path_of_Building_7olrldK8fF](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/44637122/8b8518e0-8f4e-44aa-8ed6-5bc9844a5a9e)

### What are your system specifications and configuration?

win10

### How to reproduce the issue

Import any  CHARACTER (from account, not build code or pastebin, pobbin, etc) with The Perandus Pact. 
For eg. my account greensun60, champion character. 

### Character build code

```shell
its works with build codes. but not works with char import.
```

**Comment by DrRoq** [comment]
It appears to be happening with build codes as well:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48545122/67bea2eb-9041-443c-b8e5-30d4d51cd4d4)

Received this error when importing this Pobb.in Build code: https://pobb.in/AJzqSUXv_BIG

**Comment by xpapahet** [comment]
hmm. its can be imported with some variotions, but they dont works.
for eg. its can be imported but havent stats 
https://poe.ninja/builds/streamers/character/SH00N/ShoShoBlade?i=1&search=uniqueitems%3DThe%2BPerandus%2BPact

**Comment by LocalIdentity** [comment]
I just fixed this on the dev branch, will be pushed to beta when we make the next release

**Comment by xpapahet** [comment]
> I just fixed this on the dev branch, will be pushed to beta when we make the next release

when? maybe?

**Comment by LocalIdentity** [comment]
@xpapahet it was fixed on the beta branch 2 days ago btw
