### ISSUE TITLE
Doppelgänger Guise "Unhinge" skill Bonuses not Calculated

### ISSUE THREAD

**Issue by evolite** [PathOfBuildingCommunity/PathOfBuilding#7557]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

It's supposed to grant

58% more Critical Strike Chance while Insane
Enemies Killed by your Hits are destroyed while Insane
38% less Physical and Chaos Damage Taken while Sane
Regenerate 10% Life over one second when Hit while Sane

And switch between stats by toggling the "Unhinge" Skill which the body grants. But atm it does nothing in PoB. (Works as expected ingame.

### What is the value from the calculation in Path of Building?

Null

### How to reproduce the issue

1. Equip "Doppelganger Guise"
2. Enable / Disable the "Unhinge" Skill.
3. Notice nothign changes.

### Character build code

```shell
https://pobb.in/Y3Rc0Oo7OzLs
```

**Comment by Regisle** [comment]
Try this config
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49933620/d909d111-695d-439d-9c9c-896ef3dd1ffd)

**Comment by evolite** [comment]
I guess working as intended then!

**Comment by Regisle** [comment]
To be fair, I have no idea why its there and not in a more obvious place, but yeah, it does "work" if you can find it
