### ISSUE TITLE
Pob not opening 

### ISSUE THREAD

**Issue by Csabo1119** [PathOfBuildingCommunity/PathOfBuilding#7573]
I have 64 bit laptop, every time I try to open Pob I get a notification saying that it is not compatible with my pc. From my understating I thought 64 bits was required.

**Comment by Nightblade** [comment]
Please take a screenshot of the error and post it here.

**Comment by Csabo1119** [comment]
![image_2024-04-14_205627583](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/46506821/57f0d3a7-d26c-4f2c-a43f-8ef4b6ebec4c)

**Comment by Nightblade** [comment]
It should work.  Do you have "McAfee WebAdvisor" Chrome Extension installed?

**Comment by Csabo1119** [comment]
no I don't

**Comment by Nightblade** [comment]
Ok.

1. What version of windows are you running?
2. Have you tried uninstalling, downloading and installing a fresh copy of PoB?
3. If so, and you are using the "standard" PoB installation (the .exe version), could you uninstall that and try the [portable version of PoB](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.42.0/PathOfBuildingCommunity-Portable.zip)?

**Comment by Nightblade** [comment]
Closing due to lack of feedback.
