### ISSUE TITLE
Might in All Forms crashes PoB [Bug]

### ISSUE THREAD

**Issue by BuHoGPaD** [PathOfBuildingCommunity/PathOfBuilding#758]
https://pastebin.com/erR5pvXt

Howering over Might in All Forms crashes PoB.
![image](https://user-images.githubusercontent.com/31807434/79044927-e0240780-7c10-11ea-9d7e-9b6d3a840f1d.png)

**Comment by LocalIdentity** [comment]
Has been fixed here https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/681. This will be in the next update
