### ISSUE TITLE
Lancing steel of spraying number of projectiles is not included in cast on crit effective source rate

### ISSUE THREAD

**Issue by marbemac** [PathOfBuildingCommunity/PathOfBuilding#7580]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In game it shows that lancing steel fires 10 projectiles.

### What is the value from the calculation in Path of Building?

Path of building is not including the projectile count when calculating Eff. Source Rate.

### How to reproduce the issue

1. Import https://pobb.in/ycBKx-WTk4gE. This build is from https://www.youtube.com/watch?v=L8yZJHBtiCw.
2. Note how eff source rate IS correctly calculated (see first screenshot). So it maybe worked in the past, whenever this build code was created?
3. Anyways, now go to the skill gems and change lancing steel of spraying to anything else, then back to lancing steel of spraying (to simulate as if we were creating this from scratch in latest PoB).
4. Now check eff source rate - it does not include any projectile calculation (second screenshot).

Can also reproduce with a fresh build by just adding lancing steel of spraying + cast on crit + desecrate and checking eff source rate to see that it does not include the x10 lancing projectile multiplier.

### Screenshots

Example of it including the multiplier for number of projectiles when importing the build created on older version of PoB (see repro steps): 

![Screenshot 2024-04-17 at 9 48 49 AM](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/847542/4fb80e26-2f9d-4c7a-82c6-595082740b06)

Example of it not including the multiplier if try to use lancing steel of spraying in latest build:

![Screenshot 2024-04-17 at 9 50 28 AM](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/847542/7eb7099a-4c5b-4375-aafe-0192d809550b)

**Comment by marfenij** [comment]
Hi @marbemac 
seem you miss some configuration when changing gems/skill (or begin build from scratch)

![Path_of_Building_MoDZNK9VUq](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/35066157/f4402f97-0ae1-4f61-82be-d3cb7fcb313c)

**Comment by marbemac** [comment]
🤦‍♂️.. thank you
