### ISSUE TITLE
Unholy Might Calculation issue - Probably. 

### ISSUE THREAD

**Issue by Ahmad3223** [PathOfBuildingCommunity/PathOfBuilding#7587]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

its not supported in game, 

### What is the value from the calculation in Path of Building?

its way less than what it should be, i have BV poison build, unholy might used to add 30% of physical damage as chaos and now it increased to 100%, yet it add very small amount to my build in pob.
for example, atziri promise flask got 8% phys to chaos and yet give more damage.

### How to reproduce the issue

try using atziri promise flask vs sins rebirth flask

### Character build code

```shell
this is my pob you can check the flask list and how much damage they add and you can check unholy might in configuration list.
```

**Comment by Ahmad3223** [comment]
sorry forgot to link pob:
https://pobb.in/_Z0aFCWKwsTi

**Comment by Regisle** [comment]
> unholy might used to add 30% of physical damage as chaos and now it increased to 100%

it changed from "30% phys ***gained as***" to "100% phys ***converted to***"
which for poison is much less (as converting it has no effect for poison, so you are just losing the 30% extra damage)

**Comment by Ahmad3223** [comment]
hmmm, didnt pay attention to the wording of it, i will check.
thanks mate for the clarification.
