### ISSUE TITLE
Imported Builds from valid code; items in wrong slots

### ISSUE THREAD

**Issue by IdrisQe** [PathOfBuildingCommunity/PathOfBuilding#760]
v1.4.167.2
![image](https://user-images.githubusercontent.com/40530630/79060724-5f2f3500-7c3d-11ea-8219-d22d50124cc5.png)
When importing some builds, trying to switch to a different equipment set seems to put the items into the wrong slots, causing the following error when trying to switch to them:
![image](https://user-images.githubusercontent.com/40530630/79060731-8a198900-7c3d-11ea-946e-433b1a0aa2a6.png)
The build for reference: https://pastebin.com/Sai85NL4

**Comment by ppoelzl** [comment]
That builds seems to be corrupted (items in wrong slots, missing items in slots). However, in the latest version (1.4.170.16, only one I tested) it loads without errors, discarding any invalid items.
