### ISSUE TITLE
Ngamahu, Flame's Advance Strength Calculating Wrong With Lethal Pride Radii Overlap

### ISSUE THREAD

**Issue by nekooooooooo** [PathOfBuildingCommunity/PathOfBuilding#7604]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Strength in game: 1820

### What is the value from the calculation in Path of Building?

Strength in PoB: 1825

### How to reproduce the issue

1. Allocate Ngamahu's Flame Advance
2. Equip Lethal Pride and Non Unique Jewel wherein their radii overlap

### Character build code

```shell
Current Build PoB: https://pobb.in/WMBnC0phfGBr
Minimal Build PoB: https://pobb.in/rL9DlkUXlddC
```

### Equipped Lethal Pride, Equipped Jewel, Allocated Ngamahu
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/5b9a946f-d5a1-4065-9340-2983e8be8173)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/33d35afd-624b-47f8-a62a-ba0c6f160b5b)

### Equipped Lethal Pride, Equipped Jewel, Unallocated Ngamahu
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/f0dd3819-ace4-4dcc-9d3c-d5ae43111f11)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/1b5b3ba0-500b-4824-a65c-60acfa2630a7)

### Minimal Build Str Calcs
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/e712da33-15c2-46e9-99f6-98063c79a4ac)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/673cbc29-843e-4822-a3ba-ff06c2697cd9)

#### +3 Strength on node from ngamahu in PoB while Lethal Pride equipped
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/90394509-6bc5-4fa0-8d59-1ceea10a7143)

#### But, not in-game
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/fa109dc1-87bd-4a20-ae85-289865b3a6bf)

#### Unequipped Lethal Pride, +3 Strength appears from Ngamahu in-game
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/bc404a6d-d7df-4ec5-8f04-ddfdd3ff6eae)

#### -3 Strength Custom Modifier Makes In-Game and PoB Values Match
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/d1ae5244-9949-463c-9ca1-5c0889a63de4)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/69033860/ca62e1c9-5e34-489d-8b37-784524644861)

**Comment by NL908** [comment]
I've tested in-game with Lethal Pride and Brutal Restraint near the ranger starting point. 
Timeless Jewel effect should **overwrite** the Ngamahu ascendency effect, for both smaller nodes and notables. 

In-Game:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/56325975/257d4a16-cdfe-4550-a88a-164608420335)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/56325975/336fe884-02b2-4532-be4b-d29feb6619b4)

Compare with PoB:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/56325975/bd05cacf-87b3-4a99-af4a-dceed93bd930)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/56325975/251b51b1-8316-457a-948b-18f3283ebed5)
