### ISSUE TITLE
Staff Accuracy Notes above/between One W/ River & Blunt Trauma incorrect

### ISSUE THREAD

**Issue by Coldflame356** [PathOfBuildingCommunity/PathOfBuilding#7607]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

These nodes in game give accuracy,

### What is the value from the calculation in Path of Building?

 in PoB they state they are giving accuracy but appear to be giving attack speed seems about 3% as damage effect is similar to taking a different node.

### How to reproduce the issue

I'm hoping that when you look in the below Build link you'll can review from there. I can't rule out that the issue might be specific to my PC. I have not done any modifications of PoB code in any way that would lend itself to cause this.

### Character build code

```shell
https://pobb.in/9_109q2DBA_3
```

### Screenshots

<img width="1150" alt="Staff Accuracy Granting Attack Speed" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/168740553/db400c9c-f5c5-47bb-ab3b-f59b982411c9">

**Comment by Regisle** [comment]
Your build is a jugg, you get attackspeed per 150 accuracy
