### ISSUE TITLE
Incorrect ranges on The Tides of Time

### ISSUE THREAD

**Issue by viocar** [PathOfBuildingCommunity/PathOfBuilding#7609]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What is the wording in-game?

The bottom three mods on The Tides of Time have these ranges in-game:

Life Flasks gain (0-3) Charges every 3 seconds
Mana Flasks gain (0-3) Charges every 3 seconds
Utility Flasks gain (0-3) Charges every 3 seconds

### What is the wording in Path of Building?

The bottom three mods on The Tides of Time have these ranges in Path of Building:

Life Flasks gain (1-3) Charges every 3 seconds
Mana Flasks gain (1-3) Charges every 3 seconds
Utility Flasks gain (1-3) Charges every 3 seconds

**Comment by n1tr0xs** [comment]
Seems, has already been fixed in dev branch (#7528).
So now we need to wait for new release.

**Comment by viocar** [comment]
Ahh, I see. I'll close this, then.
