### ISSUE TITLE
Full DPS calculation of Spark should adjust for hit rate

### ISSUE THREAD

**Issue by lextra2** [PathOfBuildingCommunity/PathOfBuilding#7612]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Is your feature request related to a problem?

[A Spark projectile can hit once every 0.66 seconds, per cast.](https://www.poewiki.net/wiki/Spark#Skill_functions_and_interactions)

The Full DPS calculation does not adjust for that (instead, it assumes that there is only one hit per second, per cast).

### Describe the solution you'd like

An easy fix would be to give Spark a 1.34x DPS multiplier.

### Describe alternatives you've considered

Using `34% more projectile damage` in the custom mod field

**Comment by Regisle** [comment]
> instead, it assumes that there is only one hit per second, per cast
PoB does not actually even do that, it only assumes 1 hit per cast

The projectiles traveling randomly and the size of the enemy/arena play a large factor, and thus there are too many assumptions that need to be made for PoB to calculate this, the best option is to determine for your setup how many times you think it hits and then either use a custom mod, or full dps count to adjust for that

**Comment by Selmafudd** [comment]
You can setup Spark's full dps already.

On Calc tab check Spark's skill duration, divide that by 0.66 seconds and round down, this value is your theoretical max hits from a single cast of spark .  
On Skill tab check Include in Full DPS for spark and in the count field enter the value above.

**Comment by Nerotox** [comment]
Added a new mode for Spark in my PR that automatically calculates the DPS with 100% hitrate. We still can't estimate the real hit-rate, but this should at least provide some clarity and in some scenarios (optimized build in e.g. maven arena) also provide decently accurate DPS numbers for Spark.
