### ISSUE TITLE
Circle of Ambition is not in the list of uniques

### ISSUE THREAD

**Issue by Jzir** [PathOfBuildingCommunity/PathOfBuilding#7619]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Is your feature request related to a problem?

Circle of Ambition is not available as an item in pob

### Describe the solution you'd like

I'd like to be able to search for and add  [Circle of Ambition](https://www.poewiki.net/wiki/Circle_of_Ambition#:~:text=Circle%20of%20Ambition%20has%20restrictions,Drops%20from%20Uber%20Venarius) just as I can do with any other unique in the Items section of POB

### Describe alternatives you've considered

You can copy the item text for now, but that doesn't allow you to play with catalyst values easily, or corrupts easily, and so on.

### Additional context

This issue also exists for the utmost, hands of phrecia, and variations of the perandus pact other than global crit chance and life.

**Comment by n1tr0xs** [comment]
Already fixed in dev branch (#7528), so just waiting for next release.

**Comment by Jzir** [comment]
Oops, sorry - I did do a search in issues but didn't think to also search PRs.
