### ISSUE TITLE
Adorned rounding error for jewels with same stats on explicit and implicit mods

### ISSUE THREAD

**Issue by KaoXinRei** [PathOfBuildingCommunity/PathOfBuilding#7645]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Game calculates stats on the jewel with adorned with both mods from implicits and explicits together, which provides more breakpoints if you have the same mods.
Here is my jewel with 144% adorned:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48526413/751c4fce-3d5c-4ca7-a007-bf3a1a9e5744)
And here is the same jewel with 149% adorned:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48526413/8b5a4133-2ac3-4cfb-8f80-cc126f729ab0)
as you can see the 149% has 1 more int, which is only possible if you add explicit and implicit together and only then multiply with adorned (16 * 2.49 = 39.84, 5 * 2.49 = 12.45, 39 + 12 = 51. (16 + 5) * 2.49 = 52.29)

### What is the value from the calculation in Path of Building?

PoB calculates this values separately. That can be seen in calculations:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48526413/a9963583-184b-4543-a296-d4824f32179f)
And if you try changing adorned it also won't show any difference: 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48526413/18e3d3c2-e86d-4919-92fe-2517e7be5ed8)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/48526413/99d72774-17bb-486b-bf82-d834150ff9b8)

### How to reproduce the issue

Use synth jewel with the same stats in implicit and explicit and find adorned breakpoints

### Character build code

```shell
https://pobb.in/TNpXyz96x5QI
```

**Comment by KaoXinRei** [comment]
Seems like this is the same problem just for the Widowhail: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6879. I will create pr based on it.

**Comment by KaoXinRei** [comment]
Seems like this is the same problem just for the Widowhail: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6879. I will create pr based on it.

**Comment by KaoXinRei** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7647

**Comment by Paliak** [comment]
The patch was merged and will most likely be included in next release. This should be good to close.

**Comment by aliunwala** [comment]
This is still a problem in the latest build: 2.49.3

The 150% adorned and the 149% one both have the same "attack rate" of 3.33 (I am assuming this is because the implict mod is the same as the explict mod.)

Here is a test pob:
https://pobb.in/r4OFZwVfI-y0

![image](https://github.com/user-attachments/assets/aa2bc19b-cc56-4f93-a7cf-58e6e3ca7711)

![image](https://github.com/user-attachments/assets/ecf1b9ed-af65-4da9-97db-7c0b2878c655)

You can also see in the skill section where the attack speeds are calculated these 3 mods are not separated - this pic should have 3 lines, not 2:
![image](https://github.com/user-attachments/assets/1d2abc44-9183-4955-bece-9f65de6d6e70)
