### ISSUE TITLE
I can not start PoB 

### ISSUE THREAD

**Issue by TurtleIs** [PathOfBuildingCommunity/PathOfBuilding#7649]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

while trying to open PoB I get this error
![PoB error](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/173210850/03e8c719-ea66-4245-9963-8d8d2061f6d9)

### How does Path of Building behave?

pressing enter/escape, ot f5 does not work... I have uninstalled and reinstalled a few times now...

### Screenshots

![PoB error](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/173210850/8d466e7c-9cbd-4c3b-84bd-f0ca810c019a)

**Comment by Nightblade** [comment]
Dupe of #7639

**Comment by TurtleIs** [comment]
I just did a factory rest of my pc, and still can not open PoB... any suggestions?
![PoB error 1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/173210850/79ab0ad9-87ca-41c8-9e0a-6cb8a07ab218)
![PoB error 2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/173210850/eb142edb-f30c-438b-8276-a03d97824136)
