### ISSUE TITLE
Renaming a saved build does nothing when only changing upper/lower case

### ISSUE THREAD

**Issue by klein-sipgate** [PathOfBuildingCommunity/PathOfBuilding#7659]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

It should rename my build.

### How does Path of Building behave?

It does not rename my build.

### How to reproduce the issue

- Create new build
- Save build with name "one"
- Click the back button in the top left corner to go back to the build list
- Highlight the freshly created build
- Click the Rename button
- Enter "One" as the new build name (capital "O")
- Press the Save button
- Notice how the build is still called "one" (with a lower case "o")

**Comment by n1tr0xs** [comment]
I can't reproduce.
Both (user and dev) versions renaming build as should. 
Give some details about your system/machine/etc. that may be useful, please.

**Comment by klein-sipgate** [comment]
I am using pob through wine on Ubuntu 22.04.

I recorded a screencast: https://www.youtube.com/watch?v=E1Zs9f7V74Q

**Comment by tojaprice** [comment]
Does Wine emulate Windows' case-insensitivity (sorry for my ignorance, I've not used Wine)? Could that be the cause?

**Comment by n1tr0xs** [comment]
Wine isn't case sensitive AFAIK.

**Comment by klein-sipgate** [comment]
Looking through google results, it seems like this might be the case. Sorry for opening the false report then.
