### ISSUE TITLE
Hexblast of contradiction base poison damage

### ISSUE THREAD

**Issue by priorGuesstimator** [PathOfBuildingCommunity/PathOfBuilding#7665]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

When I use any reasonable setup for Hexblast of Contradiction, it shows meaningful base damage

### What is the value from the calculation in Path of Building?

5 to 8 millions base damage

### How to reproduce the issue

Check tooltip for source chaos in poison box for HBoC

### Character build code

```shell
https://pobb.in/W_0cgfKL6Cn8
```

### Screenshots

![изображение](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/13599515/8c7b4fa3-4c4e-479e-9290-3d14d3c4cd86)

**Comment by NL908** [comment]
I think it's showing 3 decimal places. This is the breakdown of the chaos Skill Hit Damage.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/56325975/be48f7e1-fa4e-40f1-bd82-f7cb7e9d2d02)
