### ISSUE TITLE
Passive Point "Dual Wiled Attack Speed and block"

### ISSUE THREAD

**Issue by Pachelor** [PathOfBuildingCommunity/PathOfBuilding#7722]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

If you choose the passive Point "Feline Swiftness" at the duelist side Pob automatically path but it skips the second "dual wield attack speed and Block" note.
![passiv point](https://github.com/user-attachments/assets/78060da3-40a8-4590-ac0b-a268be16f7d6)

### How does Path of Building behave?

It should pick the node while path it.

### How to reproduce the issue

Just path directly to "Feline Swiftness"

**Comment by Regisle** [comment]
Confirmed issue with tree data, node 12095 is connected to the wrong one, 
I will fix it for PoB, and pass it along to ggg
