### ISSUE TITLE
Can't save any build, latest git, linux

### ISSUE THREAD

**Issue by errantmind** [PathOfBuildingCommunity/PathOfBuilding#7740]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Linux - PoB Frontend

### How is Path of Building expected to behave?

Saves should succeed

### How does Path of Building behave?

No builds can be saved

### How to reproduce the issue

Checkout latest git and build. Run. Create a new build or import. Click Save. Give it a name and click 'Save'.

![2024-07-20_17-43](https://github.com/user-attachments/assets/3fd71e30-fd48-4ab7-a8ef-6db59e3d3465)

### Character build code

```shell
All builds, no code required.
```

**Comment by zao** [comment]
Better traceback:
![image](https://github.com/user-attachments/assets/e72029f4-e6e4-4c54-95b5-bc450ce6eedd)
