### ISSUE TITLE
Add "Have you blocked recently?" Configuration option, so the new "More than skill" can be accounted for

### ISSUE THREAD

**Issue by andrecadete** [PathOfBuildingCommunity/PathOfBuilding#7751]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

Yes, no way to calculate Lucky Block and Spell Block chance for new Gladiator ascendency node. Lucky Suppress already works like this where the % of suppression visibly increases when using lucky.

### Describe the solution you'd like

A configuration option, such as "Have you blocked recently?", which would add the % increase for Lucky block and spell block if this node is selected.

### Additional context

Rework is mentioned here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7704 
But no reference to an open issue (nor can I find one), so I created this one..

**Comment by Regisle** [comment]
see #7730

**Comment by andrecadete** [comment]
I see, thanks. Might want to add the node name in the desc to make it easier to find! Thanks, can be closed then.
