### ISSUE TITLE
Authopathing does not allocate a minor passive that leads to a notable

### ISSUE THREAD

**Issue by bloodgrom** [PathOfBuildingCommunity/PathOfBuilding#7752]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Allocating the Feline Swiftness notable should allocate all small notables that lead to it.

### How does Path of Building behave?

Allocating the Feline Swiftness notable fails to allocate the second small notable that leads to it.
E.g The Felline Swiftness notable wheel is made of 4 passives -> 3 small (Dual Wield Attack Speed and Block) and 1 notable (Feline Swiftness). When directly allocating the Feline Swiftness notable, the autopathing fails to allocate the second small passive. The passive itself and the connection to it doesn't appear highlighted.

### How to reproduce the issue

1. Select any base starting class (provided build code uses Duelist)
2. Directly allocate Feline Swiftness notable in order to autopath to it
3. Notice second small passive in the Feline Swiftness notable wheel is not allocated.

### Character build code

```shell
https://pobb.in/CyKLLNmQHNeq
```

### Screenshots

![image](https://github.com/user-attachments/assets/9309a9d6-8b2d-4835-adbd-a252cbbcfb58)
![image](https://github.com/user-attachments/assets/f65371b1-4550-47b9-aa28-ba4b3a7b331f)

**Comment by Wires77** [comment]
Fixed by #7723 for the next release
