### ISSUE TITLE
Can't update PoB community fork

### ISSUE THREAD

**Issue by AnastrianaNailo** [PathOfBuildingCommunity/PathOfBuilding#7754]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Trying to get the weekly beta to work.

### How does Path of Building behave?

It give me an error saying it cannot download the files.

### Screenshots

![image](https://github.com/user-attachments/assets/f5c8c806-a06b-4f95-b762-c0ebe7398ba8)

**Comment by LocalIdentity** [comment]
Are you updating from a really old version?

**Comment by AnastrianaNailo** [comment]
I actually uninstalled and fresh installed after I had the issue.

**Comment by Wires77** [comment]
Looks like you're getting SSL errors on some of the files.  This would be an issue with your internet connection usually.  There may be a workaround that involves copying the files you have in the Update folder and replacing those in your main install, while downloading the erroring ones from GitHub, but I'd check your connection first.

You may also just need to wait for a full release so you can download all the files through your browser instead.

**Comment by AnastrianaNailo** [comment]
Fair enough. My internet is pretty solid. 
![image](https://github.com/user-attachments/assets/447e1b10-2a2b-4608-b546-4fb486ad7005)

**Comment by AnastrianaNailo** [comment]
but oh well I suppose I will just wait. Thank you for your assistance.

**Comment by Wires77** [comment]
This does remind me that we need better error handling for updates, as right now if someone runs into problems like you did, there's not really a better solution than to try again and hope the whole load of files download properly since it starts from the beginning each time.

**Comment by Nightblade** [comment]
@AnastrianaNailo Did you resolve this issue?

**Comment by AnastrianaNailo** [comment]
As of yesterday I have access to 3.25. It's not from the weekly beta download but I have it. So I guess?

**Comment by Nightblade** [comment]
Ok, feel free to re-open if you need help.
