### ISSUE TITLE
One of new mana wheels in POB doesn't match the one in the 3.25 reveal's tree.

### ISSUE THREAD

**Issue by here2reportissues** [PathOfBuildingCommunity/PathOfBuilding#7755]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

The mana wheel, which contains the notable "Spirit of War", should be between the Duelist's starting dexterity points and the basic jewel socket to the right of the Duelist's starting points, as is shown in the 3.25 reveal video. Screenshots are provided. Red is currently in POB. Blue is the 3.25 reveal.

### How does Path of Building behave?

The mana wheel, which contains the notable "Spirit of War", is in the wrong position.

### Screenshots

<img width="512" alt="Screenshot 2024-07-21 101424" src="https://github.com/user-attachments/assets/c60386cb-de72-40b8-9c56-adef0d3b8ca3">

![Screenshot 2024-07-21 102442](https://github.com/user-attachments/assets/08bf1cf5-2d8d-497d-99de-99954fc3e275)

**Comment by LocalIdentity** [comment]
#.25 reveal is most likely old and out of date. The tree data comes directly from GGG and would be the most up to date
