### ISSUE TITLE
Impale damage doesn't take the right average damage hit to calculate impale dps

### ISSUE THREAD

**Issue by Maxensimon** [PathOfBuildingCommunity/PathOfBuilding#7787]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

In game the calculation is that each stack of impale take 10% of the incoming damage. So if I inflict a 10000 physical damage hit, I should have 1000 damage stored. PoB actually does this well but the average hit taken is wrong.

### What is the value from the calculation in Path of Building?

I have a build with an average physical hit of 330000 physical damage. The average physical hit taken is 150000 but I cannot find this value anywhere from the impale calculation.

### How to reproduce the issue

- Get a melee skill.
- Put a phys weapon.
- Get 100% impale chance and watch the average hit indicated on your skill and the average hit used by the impale calculation
- See the difference.

### Character build code

```shell
https://pobb.in/pvEW2M29dUAN
```

### Screenshots

![image](https://github.com/user-attachments/assets/24abbcfc-639b-4cff-b361-6fa89d571ba8)
![image](https://github.com/user-attachments/assets/110a5e1b-ad36-40f6-b315-f984c3818892)

**Comment by bdemolder** [comment]
Going to give my opinion already, but we might wait for someone with a better thorough knowledge....

According to my knowledge and what I found out:
https://www.poewiki.net/wiki/Receiving_damage
https://poedb.tw/us/Receiving_damage ("After damage mitigation, modifiers to damage taken are applied.")

The damage taken is step 7, and impale is calculated based on unmitigated damage (end of step 3 in poe wiki):
"When a hit applies impale to a target, 10% of that hit's [physical damage](https://poedb.tw/us/Physical_damage) is recorded before any [damage mitigation](https://poedb.tw/us/Receiving_damage) is applied."

**Comment by bdemolder** [comment]
@Regisle Sorry if you don't like this tag, tell me if I should not, but I was told you might be good in answering this with almost certainty. :D

**Comment by mcheese** [comment]
Gonna tag in here, as I was also just trying to figure out what's wrong with my impale damage on the updated PoB.
My issue, which also applies here, is that increased damage taken modifiers seem not to be applied to impale at all.

In the OPs PoB, if I disable Pride, Maim (gem) and uncheck Intimidate the average physical hit in impale calc matches the actual Average Damage. Which is all correct, given that impale is based on the pre-mitigation damage. But the final impale damage and dps does not increase when these things are enabled again. And AFAIK at least Pride and Vulnerability should be applied to the dealt impale damage at the end.

**Comment by bdemolder** [comment]
Going to add a little bit easier to calculate example based on the other issue:

- Has 1k damage, has flesh and stone at level 1 (so 10% inc damage taken),
- Enemy has 50% physical damage reduction,
- Overwhelm 100% both normal and impale physical damage reduction

```
https://pobb.in/gTjzKKugMDEC
```

**Comment by Seikah** [comment]
It appears to handle base impale damage correctly, but the impale calculation is incomplete. It only applies physical 'damage reduction' (the specific stat gained from Armour + Additional Physical Damage Reduction), not other relevant modifiers on the enemy, such as increased/reduced/more/less damage taken.

**Comment by bdemolder** [comment]
Seems indeed I missed over this line in the poewiki:

"It cannot be evaded, dodged, suppressed, or blocked, but it **can be affected by mechanics such as** [damage taken as](https://www.poewiki.net/wiki/Damage_taken_as), [avoidance](https://www.poewiki.net/wiki/Avoidance), [damage reduction](https://www.poewiki.net/wiki/Damage_reduction), **and modifiers to damage taken**, including reflect-specific modifiers."

So the issue described the base impale damage being wrong, whilst it is correct, but the eventual dps might need to take into account those things indeed like @Seikah mentioned, to be confirmed?

**Comment by Seikah** [comment]
Yes. Impale stores damage before mitigation, and is mitigated when it deals damage, so the enemy doesn't double-dip its defenses. 

As a secondary damage reflected hit, it's mitigated normally: 
- cannot take reflected physical damage 
- damage taken as elemental/chaos
- physical immunity (or other immunities if shifted) 
- physical/generic damage avoidance (such as from elusive) 
- damage reduction (physical, or elemental/chaos if shifted) 
- flat damage taken 

I don't know how many of these are implemented in PoB.

**Comment by SuperJelle** [comment]
Could there be more issues with the calc in 3.25? For me, the average damage used by impale is higher than the average damage.
https://i.imgur.com/RXFOrsc.png

**Comment by mcheese** [comment]
Yes, as noticed in #7831 critical hits are broken differently.
Could you share the PoB so I can check if my current fix works for this?

**Comment by SuperJelle** [comment]
Yes, of course!
https://pobb.in/EcCBlL7M4cW8

**Comment by bdemolder** [comment]
be careful @mcheese , it can happen it is higher cuz it is taking the **unmitigated** damage, whilst the average on top is **mitigated**
@SuperJelle 

see https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7726

**Comment by SuperJelle** [comment]
I'm not sure the new calc is right. Now the value used by impale for average hit is around half of what my average hit is?

**Comment by mcheese** [comment]
The average base damage is before mitigation, including damage taken. So it misses all your Pride and Vulnerability effect, but gets it back in the impale damage multiplier. We are aware the whole calc breakdown may be a bit unclear and were discussing ideas how to improve it.

**Comment by SuperJelle** [comment]
Ahh, I think I found it. It looks like it is calculating Pride as increased damage taken instead of more damage taken.
My DPS modifier is 53% increased and 20% more which is x1.836 overall while impale is using x1.72 instead.

If I multiply the impale's average damage by 1.836 I get the exact number I have under Average Damage.

**Comment by mcheese** [comment]
Is the 20% more from flesh and stone? That one is bugged right now (increased damage taken from HITS is missing...), I'm on it.

**Comment by SuperJelle** [comment]
No, it's from pride: 
<img width="477" alt="2024-07-24 (2)" src="https://github.com/user-attachments/assets/826267de-1b7b-4be0-8833-56906dcde455">
<img width="314" alt="2024-07-24 (3)" src="https://github.com/user-attachments/assets/84b03c51-f708-42e6-a051-3afb5b5c4d14">

You can have a look for yourself if you want to. I posted the pob in this thread yesterday: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7787#issuecomment-2244884370

**Comment by mcheese** [comment]
Attack (Intimidate) is not contributing.

(1 + 0.12 + 0.2 + 0.11) * 1.2 = 1.716 -> rounded for display to 1.72

**Comment by SuperJelle** [comment]
Should it not be counted? I don't see why the debuff would not work for Impale - it affects hit damage and Impale is a reflection of your hit.

**Comment by bdemolder** [comment]
But if you look at it this way, if it were a hit then:
- you would proc on hit effects. Which would be weird?

**Comment by SuperJelle** [comment]
The Impale itself is not a hit. But it is based on the damage from the hit which is affected by the debuff.

**Comment by mcheese** [comment]
> The Impale itself is not a hit. But it is based on the damage from the hit which is affected by the debuff.

No, impale damage is a hit. It's Reflected Physical Damage. And it records before debuffs or armour apply. The impale hit is then scaled by debuffs. But it is no longer an attack.

We just ingame tested for Intimidate (and Snipers Mark). And this seems to be correct. (Even if the numbers are kinda hard to test)
Also, which was easier to test: "-50 Physical Damage taken from Attack Hits" (Immortal Flesh) is definitely not applying to impale damage. The test character was close to immune until impale got stacked, but took regular damage after. Which confirms that Attack damage taken modifiers to not apply to impale.

**Comment by SuperJelle** [comment]
Very interesting. I believe this implies that impale damage has been calculated incorrectly in every single version of PoB until now? 
In 2.42 which is based on PoE 3.24 impale damage is affected by Intimidate (and assuming I've done my checks correctly this has been the case since ~3.12 when I started using impale)

**Comment by bdemolder** [comment]
Yes, I can't speak of all versions before this, but l ast version before 3.25 had this.
Base impale damage was fixed with:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7726
... As damage reduction was thus double dipping.

And this issue being resolved solved:
- Debuffs (damage taken) are now taken into account if applicable, like @mcheese says
- Critical strikes calculation for impale is improved as well
