### ISSUE TITLE
Seismic Cry has old AoE

### ISSUE THREAD

**Issue by mahuu** [PathOfBuildingCommunity/PathOfBuilding#7788]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

Seismic Cry is supposed to give 50% more AoE to exerted attacks instead of the old behaviour of 30% increased + 30% increased for each previous exerted attack.

### What is the behaviour in Path of Building?

Seismic Cry gives 50% more AoE **and** 30% increased + 30% increased for each previous exerted attack

### How to reproduce the issue

1. Add Slam Skill (e.g. Ground Slam)
2. Add Seismic Cry

### Character build code

```shell
https://pobb.in/BCWDTE5Www2p
```

### Screenshots

![image](https://github.com/user-attachments/assets/3ce93f70-6c8e-4392-b7b1-6c2b2e5c0428)

**Comment by LocalIdentity** [comment]
I'll fix this for the next hotfix
