### ISSUE TITLE
Adding {1} to a list item in every tab results in an error and no linked loadout

### ISSUE THREAD

**Issue by priorGuesstimator** [PathOfBuildingCommunity/PathOfBuilding#7790]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

By appending {1} to the end of list item names in all 4 tabs a loadout should be created

### How does Path of Building behave?

![изображение](https://github.com/user-attachments/assets/5e3c6c1a-4504-44b6-abae-af29d9f98da8)
I added {1} to a tree, skill setup, gear setup and config setup, on saving the last one it shows an error and does not link the loadout

### How to reproduce the issue

Take a pob with multiple saved trees, skill setups, etc
Try to link a loadout by appending {1} to the end of names

### Character build code

```shell
https://pobb.in/_uzI5QJEoaKh
```

**Comment by Wires77** [comment]
Put a space between your tree name and `{1}` should fix it for now
