### ISSUE TITLE
New militant faith search works weird?

### ISSUE THREAD

**Issue by eQuara** [PathOfBuildingCommunity/PathOfBuilding#7792]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

-

### What is the behaviour in Path of Building?

New Militant faith blocking search only block whatever u picked as node but it still gets random stuff on blocked nodes? is that intended for example; scion right jewel I want 5% mana as extra es on harrier and keep rest of the nodes in that area as they are normal  nodes  but this blocking is only block them to become as extra es but not anything else so blocked nodes are still turned into something else. I thought blocking a node will block all nodes militant can convert.

https://prnt.sc/uowOvWc2RbBM
https://prnt.sc/3uKTQsuowA7k

### Character build code

```shell
https://pobb.in/9E57dE5FFLcr
```

**Comment by LocalIdentity** [comment]
You pasted the screenshot link instead of the build code. Did you click on add after selecting the node to avoid?

**Comment by eQuara** [comment]
yeah sorry edited the link, yes i added them but it only block the node I want on these blocked ones not all possible outcomes so lets say blocking leadership is doesn't save leadership from turning into something else

**Comment by LocalIdentity** [comment]
Fixed in the latest update (2.47.0)
