### ISSUE TITLE
2.43.0 Blade Flurry base damage value is incorrect

### ISSUE THREAD

**Issue by E2A4E789A3DCC7236FF998692ADE60E2** [PathOfBuildingCommunity/PathOfBuilding#7794]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

According to the game patchnotes lvl 20 Blade Flurry Effectiveness of Base and Added Damage supposed to be 111%

### How does Path of Building behave?

Attack damage field is set to 101.2%
Effectiveness of Added Damage is set to 50%

**Comment by LocalIdentity** [comment]
I accidently used the values for Incision on the main gem. Will have a fix for it in a sec
