### ISSUE TITLE
Rage effect not increasing all rage related bonuses

### ISSUE THREAD

**Issue by Moremackles** [PathOfBuildingCommunity/PathOfBuilding#7795]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

It appears that the rage mastery "1% increased movement speed per 5 rage" is not affected by rage effect, like other per x rage effects are. We obviously do not have the ability to check in game at the moment, but similarly worded bonuses _are_ affected, and the patch notes supports this implementation. Something that I'm less sure about are skill effects based on rage, like the radius increase from cleave of rage. It _is_ worded the same, but skills could have some unique interaction with rage effect that we don't know about yet.

### What is the value from the calculation in Path of Building?

With the mastery, 30 rage, and 100% increased rage effect, the value for increased movement speed in pob is 6% when it should be 12%. The cleave of rage bonus is also 6%, when in theory it should be 12%.

### How to reproduce the issue

1. Use beserker with rite of ruin + berserk level 11 for 100% increased rage effect
2. Use Cleave of Rage (Optional)
3. Spec movement speed per rage mastery
4. movement speed/cleave radius is not affected by any of the previous changes

### Character build code

```shell
https://pobb.in/mVCpx0zHtM2S
```

### Screenshots

![image](https://github.com/user-attachments/assets/7331b5b7-024a-4594-907f-32666d7c9c6e)

In the image, I have rite of ruin and level 11 berserk both enabled.

**Comment by Moremackles** [comment]
I updated the post to include cleave of rage being affected by the same issue. The character import has also changed in light of this.

**Comment by Moremackles** [comment]
I believe rite of ruin's life loss per second is also the same wording. It could also be affected by rage effect

**Comment by LocalIdentity** [comment]
The Mastery, Cleave of Rage and Rite of Ruin all specify `per x Rage` while the mods that scale with Rage effect all specifically have the wording of `Rage also grants` the second one is the wording that would scale effect while the first only counts the base Rage value

**Comment by Moremackles** [comment]
Ah, I see the difference now. It still could be argued that my interpretation is correct, since the effects are 'granted' in the literal sense of the word, but I would assume that if there are other mechanics that work similar to this in the game and they do not function like I describe that it probably doesn't. You would know more than me for sure though, thanks for the input.

**Comment by barry-hill-jr** [comment]
> The Mastery, Cleave of Rage and Rite of Ruin all specify `per x Rage` while the mods that scale with Rage effect all specifically have the wording of `Rage also grants` the second one is the wording that would scale effect while the first only counts the base Rage value

This is not what the patch notes say.

https://www.pathofexile.com/forum/view-thread/3531661#ragerework

Bullet point 4 under the heading:

> Rage effect applies to the damage inherently granted by Rage, and other bonuses granted per X Rage if you have any.

**Comment by LocalIdentity** [comment]
Just created a fix for it. Sorry for dismissing the PR @Moremackles I should have read the patch notes more closely. Thankyou @barry-hill-jr for pointing it out

**Comment by Moremackles** [comment]
No worries, I had intended to link the patch notes, must have gotten distracted by something.

**Comment by Moremackles** [comment]
On review, I believe Cleave of Rage still is not receiving the radius bonus from rage effect. Not sure if I should create a new issue or if this one can be reopened.

**Comment by Moremackles** [comment]
Now that I've tested it in game, I think your original interpretation was correct.

without berserk active
![1](https://github.com/user-attachments/assets/0498948b-0e1c-4b7e-82f5-756450b129ef)
with berserk active
![2](https://github.com/user-attachments/assets/a8a4775f-2841-4a96-9fdb-e059d435e962)

Even with the -3 rage the effect should be obvious considering the 1m ~ radius it should give.

I have no images for it, but I checked my character panel early in the league (after getting the rage effect ascendancy) and I wasn't getting the movement speed bonuses either.

**Comment by LocalIdentity** [comment]
Hard to know if this is intended by GGG. I'll ask someone and find out

**Comment by Moremackles** [comment]
My guess is that it's intentional. It would be lovely to find out it isn't and gets fixed since it would substantially increase the chance I stick with this build rather than reroll lol.

**Comment by Moremackles** [comment]
Oh and just in case I can make some fellow rage enjoyers life easier, if you do get a chance to inquire with a dev or someone that would know, it would also be nice to know if the 100 rage cap is intentional as well. I know a few people (myself included) that was planning on having somewhere in the neighborhood of 150ish, but it seems that even with warcry buff effect in enough quantity to hit that number, 100 is the max you can get visually. I haven't personally done enough testing to see if mechanically it is also capped however.

**Comment by LocalIdentity** [comment]
@Moremackles GGG just fixed the max Rage issue `Fixed a bug where Maximum Rage could never exceed 100.`

**Comment by Moremackles** [comment]
NIce, that should make my zerker feel a bit better lol

**Comment by LocalIdentity** [comment]
@Moremackles got a response from GGG. The mod's on Chain Hook and Cleave of Ragte are designed to not scale with Rage effect. 

> Stats that scale based on increased Rage effect are described as "Every Rage also grants X", whereas the above stat is described as "per X Rage"
It's basically just the distinction between "something that this effect will additionally grant to you" and "something that happens because you have this effect"
Which applies in many other places
e.g "Your Auras grant" vs "Allies affected by your Auras have"
