### ISSUE TITLE
'While Channeling' offensive bonuses only applying to the Channeling Skill

### ISSUE THREAD

**Issue by ThtRandomGuy** [PathOfBuildingCommunity/PathOfBuilding#780]
'While Channeling' bonuses, in particular the bonuses from the Precise Focus notable, only apply to the channeling skill and not any non-channeling skills that may be triggered while channeling. For example, any skills triggered with Mjolnir, Cast on Crit, etc. while channeling Cyclone. This makes it difficult to calculate accurate damage values for any non-channeling skills. 
**This also applies to other 'While Channeling' flagged bonuses, such as the defensive bonuses from the [Assailum](https://pathofexile.gamepedia.com/Assailum) unique item if you don't have a Channeling skill selected as a Main Skill.

Simplified, there is no way to indicate that your character 'is Channeling' without having a Channeling skill selected as your Main Skill.

```
Precise Focus
50% increased Critical Strike Chance while Channelling
+30% to Critical Strike Multiplier if you've been Channelling for at least 1 second
```

Example: Link to a CoC Cyclone-Magma Orb build where the issue is applying.
https://pastebin.com/dcBJcKJ7
Allocating and unallocating the Precise Focus notable from any of the Medium Cluster Jewels only modifies the Crit Chance/Multi of the Cyclone, not the Magma Orb.

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1
