### ISSUE TITLE
Crash on Party Import with Warcries

### ISSUE THREAD

**Issue by retlom779** [PathOfBuildingCommunity/PathOfBuilding#7801]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/user-attachments/assets/2643a343-30d4-42ed-b3dd-87d88ddb3604)

### What are your system specifications and configuration?

![image](https://github.com/user-attachments/assets/32322b8e-cba9-46d2-bfee-8865ae3a4f21)

### How to reproduce the issue

https://pobb.in/2bV3vWyoidyG
Import a warcry sup as a Party member 

### Character build code

```shell
https://pobb.in/tLrrZIwpl57r
```

**Comment by Regisle** [comment]
Caused by the banner mastery, which is changed in #7853

**Comment by LocalIdentity** [comment]
Fixed v2.45.0
