### ISSUE TITLE
Cyclone of Tumult mana cost

### ISSUE THREAD

**Issue by Xeko-92** [PathOfBuildingCommunity/PathOfBuilding#7805]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

According to the patch notes, cyclone of tumult is supposed to be 5 mana at level 1, scaling to 6 mana at level 20.

### What is the value from the calculation in Path of Building?

3

### Character build code

```shell
https://pobb.in/FDFqdMuXRCJC
```

**Comment by LocalIdentity** [comment]
I assumed this was a bug cause the skill never had a mana cost of 6 despite what the patch notes say(had a mana cost of 2)
`Now has a Mana cost of 5 at gem level 1, scaling up to 6 at gem level 20 (previously 6 at all gem levels).`

**Comment by Xeko-92** [comment]
Oh yeah, I hope you're right! 6 base mana cost would be prohibitively expensive.

**Comment by Xeko-92** [comment]
Looks like only the old mana cost portion was wrong. The new gem info shows it being 6 mana after the update.
