### ISSUE TITLE
Master of Metal Ascendancy Passive Skill

### ISSUE THREAD

**Issue by Geeezas** [PathOfBuildingCommunity/PathOfBuilding#7830]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

Impale Damage dealt to Enemies Impaled by you ignores Enemy Physical Damage Reduction" and "Impales you inflict last 1 additional Hit (3.25)

### What is the wording in Path of Building?

different

**Comment by Geeezas** [comment]
![image](https://github.com/user-attachments/assets/eca133fb-faf1-4cd5-b977-59c38337b168)

**Comment by Geeezas** [comment]
![image](https://github.com/user-attachments/assets/f1ebcc23-6cfb-4643-b739-d0b27da4fdfb)

**Comment by LocalIdentity** [comment]
![image](https://github.com/user-attachments/assets/bf69d9f6-e2e4-4990-8554-3234d9e280ab)
![image](https://github.com/user-attachments/assets/b5921121-f424-430c-aa6b-9392c64943f9)

**Comment by Geeezas** [comment]
thanks and I am sorry,
