### ISSUE TITLE
Crash when adding a skill after allocating new Perfect Agony

### ISSUE THREAD

**Issue by tervay** [PathOfBuildingCommunity/PathOfBuilding#7834]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

v2.44.0 (Beta)

![image](https://github.com/user-attachments/assets/0d6f1723-d370-4d95-b295-155cea205fcd)

### What are your system specifications and configuration?

Win 11, ryzen 5 5600x, rtx 3070

### How to reproduce the issue

1. Create new build
2. Allocate Perfect Agony on the skill tree
3. Go to skills
4. Click new socket group
5. Type in `bl` into gem name
6. Crash

100% reproduction rate for me

**Comment by LocalIdentity** [comment]
Fixed in 2.44.1
