### ISSUE TITLE
Seismic Cry not giving 50% more AoE

### ISSUE THREAD

**Issue by 13ootyknight** [PathOfBuildingCommunity/PathOfBuilding#7836]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

50%

### What is the value from the calculation in Path of Building?

32.3%

### Character build code

```shell
https://pobb.in/Pv4jviCvT7dh
```

### Screenshots

![Screenshot 2024-07-23 095527](https://github.com/user-attachments/assets/0ac2d51f-44ec-4c05-9bf7-07a91a30a172)

**Comment by LocalIdentity** [comment]
The issue is it's multiplying the more AoE mod by the Uptime of the warcry duration instead of the uptime of the exerted attacks given by Seismic. Should be a pretty simple fix
