### ISSUE TITLE
"Increased Mana Burn Rate" from tincture affix applies inversely

### ISSUE THREAD

**Issue by hibernacle-cc** [PathOfBuildingCommunity/PathOfBuilding#7841]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Tinctures are not in game, but this is a simple calculation. See below. I imagine that this is how this would work given that "Increased Mana Burn Rate" is engineered to be a downside.

### What is the value from the calculation in Path of Building?

Tinctures are not in the game, so see this information: Taking the affix that increases mana burn rate (downside, 64%) for increased effect (upside, 35%) makes the mana burn infliction rate happen every 0.99 seconds (0.61 + (0.61*0.64) = 0.99 instead of 0.61 - (0.61*0.64) = 0.22 seconds. 

![image](https://github.com/user-attachments/assets/eab5779f-ce90-4283-94f3-ee120ffc7084)

![image](https://github.com/user-attachments/assets/25930adc-a300-4d74-a89c-24fa1ec58a5f)

### How to reproduce the issue

1. Open a new build
2. Craft a rosethorn tincture and view the rate.
3. Add the affix and view the incorrect rate.

### Character build code

```shell
I generated a fresh pob to make this easier, issue is still reproduced. 
https://pobb.in/-_tnMeR5Uj7x
```

**Comment by Fidelisraphael** [comment]
The Enduring Suffusion node on Warden also has the same issue in regards to the less modifier, it applies inversely. The reduced mana burn rate tincture nodes h
