### ISSUE TITLE
Feature Request: Contaminate (from Sporeguard)

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#785]
I would like to request Contaminate to be added in the displayed granted skill info.

Contaminate has the following tags: Spell, Area, Duration, Triggerable, TriggeredGrantedSkill. This means it can be supported by gems like inc. AoE, awakened. inc. AoE, increased duration, etc.

_I tested it, and in fact the covered area is larger when linked with area supports_

It would be a QoL feature to see what would be its area of effect / uptime with specific supports linked to the chest.

**Comment by ppoelzl** [comment]
Added in 1.4.170.15.
