### ISSUE TITLE
The description on the type of hit to gain 3 rage on rage support 

### ISSUE THREAD

**Issue by TheoXween** [PathOfBuildingCommunity/PathOfBuilding#7854]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

From the 3.25 pn, it should be "Gain 3 Rage on **Attack** Hit" to replace the "Supported Skills to grant 1 Rage on Melee Hit, no more than once every 0.4 seconds"

### What is the wording in Path of Building?

In 2.44.1 version of POB, the description of rage support is  "Supported skills grant 3 Rage on **Melee** Hit"

### Screenshots

![微信截图_20240723200404](https://github.com/user-attachments/assets/7b501b40-125d-44a7-a879-eb911eaea9c2)
![微信截图_20240723200459](https://github.com/user-attachments/assets/f266ba0b-a1a3-41ad-ba7f-a479a5fcdc20)

**Comment by LocalIdentity** [comment]
Will be fixed when we export the gems on patch day
