### ISSUE TITLE
Filter uniques by tier

### ISSUE THREAD

**Issue by josec87** [PathOfBuildingCommunity/PathOfBuilding#7860]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Linux - Wine

### Is your feature request related to a problem?

In a league start or SSF scenario, planning a build with a tier 0, 1 or even 2 unique might not be the best idea. I'd like the possibility to filter out these uniques to make it easier to find more easily obtainable ones.

### Describe the solution you'd like

I would like to add more options to the following drop down filter:
![image](https://github.com/user-attachments/assets/5950a645-c690-471d-83d1-7c4735eb5985)

The options would be:
Up to tier 1
Up to tier 2
Up to tier 3
Up to tier 4
Up to tier 5

poewiki.net could be used as a source for these tiers:
https://www.poewiki.net/wiki/Guide:Analysis_of_unique_item_tiers

**Comment by Wires77** [comment]
Unique tiers aren't exposed in the game data and we don't want to have to make more manual updates on league starts.
