### ISSUE TITLE
Base crit values for some daggers

### ISSUE THREAD

**Issue by MarsAndon** [PathOfBuildingCommunity/PathOfBuilding#7878]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

Boot Blade, Boot Knife, Butcher Knife, Carving Knife, Ezomyte Dagger, Flashfire Blade, Flickerflame Blade, Imperial Skean, Infernal Blade, Royal Skean, Skean, and Slaughter Knife now have a base Critical Strike Chance of 8% (previously 6.3%).

### What is the wording in Path of Building?

8,5%.

**Comment by HashBR** [comment]
Will try to fix and PR.
