### ISSUE TITLE
pob.party nubmers wrong after import?

### ISSUE THREAD

**Issue by Smeagol001** [PathOfBuildingCommunity/PathOfBuilding#788]
numbers seem to not match in pob.party when you import stuff to it or from it 
like in pob it says  my skill is doing 2.2 million dps and in pobparty the same thing says aroud 270k dps
is there maybe a conversion error somewhere?

**Comment by ppoelzl** [comment]
pob.party is unaffiliated with this project. Unless you have considerable reason to believe that something is wrong with the calculations of Path of Building Community, its calculations are authorative.
