### ISSUE TITLE
Generic added damage has 0% damage effectiveness on explode effects

### ISSUE THREAD

**Issue by blaat155** [PathOfBuildingCommunity/PathOfBuilding#7895]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Sources like Innervate buff, manastorm buff or mods like on Sacrificial Heart should add to the explode damage and works.

### What is the value from the calculation in Path of Building?

PoB calculates this damage with 0% damage effectiveness, resulting in no added damage in the calculation

### How to reproduce the issue

Add any explode effect.
Add any generic added damage.
See those added damage numbers correctly added in the damage columns.
See those numbers multiplied by 0% damage effectiveness in the calculation column.
Result: 0 added damage.

### Character build code

```shell
https://pobb.in/ieZm1Gdjr8cs
```

### Screenshots

![afbeelding](https://github.com/user-attachments/assets/627cb3d6-c80a-4c2c-8563-7ff7869b0eea)

**Comment by blaat155** [comment]
![afbeelding](https://github.com/user-attachments/assets/ae0c42ac-8351-47df-894d-b5d8e3927f59)
Explode like Minion Instability works fine.
Profane Bloom doesn't, but that's a mathematical nightmare I suppose IF the minion is the source of the killing blow.

**Comment by LocalIdentity** [comment]
Do you have any source that says that generic added damage works on corpse explosions?

**Comment by Seikah** [comment]
[Here's](https://www.youtube.com/watch?v=tE5COp6RMi0) Crown of the Tyrant adding flat damage to a minion's minion instability explosion, [here's](https://www.youtube.com/watch?v=J24ZM7t5a4I) generic added chaos on a ring adding damage to the player's Inpulsa explosion. 

(In both cases the explosion deals 0 damage without added chaos due to Void Manipulation and Replica Alberon's Warpath.)

**Comment by blaat155** [comment]
Thanks for posting the video proof and updating the wiki.
Act3 lvl26 mauler @ 716 life * 0.035 "estimated" lifeloss from video results in the expected damage roll @ 100% effectiveness (assuming no other damage increases).

I'm assuming that unless a value is specified, it defaults to 100% damage effectiveness for generic added damage.
Secondary damage already gets flat crit, ailment chance etc., so why not flat generic damage?
An exception would be HoI on kill effect where 80% damage effectiveness is specified in the skill.

**Comment by LocalIdentity** [comment]
@Seikahthanks for the clear testing. I’ll update the skills with their damage effectiveness values for the patch that’ll come out after league launch
