### ISSUE TITLE
Enduring Cry does not grant Endurance Charges

### ISSUE THREAD

**Issue by groink19** [PathOfBuildingCommunity/PathOfBuilding#7896]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

Gain 1 Endurance Charge per 5 Power

### What is the wording in Path of Building?

Non-existent. It seems to me that the line was removed because the latest patch notes were misinterpreted. It says:

"Enduring Cry: No longer grants a brief burst of life regeneration, or a buff which grants resistances and physical damage reduction based on your endurance charges. Instead, the user and nearby allies gain a buff that grants life regeneration. The Buff grants 2% of Life Regenerated per second per 5 power, and can count a maximum of 25 power. The base duration is now 2.5 seconds at gem level 1, scaling up to 3.4 at gem level 20 (previously 2 at all gem levels). Additionally, nearby allied players are now granted Endurance Charges as well as the user." 

The last sentence indirectly confirmes that Enduring Cry is still generating Charges. Since no respective line was added on the gem, the pre-3.25 line "Gain 1 Endurance Charge per 5 Power" must still be in place.

### Character build code

```shell
https://pobb.in/bwxtH0K6b3bp
```

**Comment by LocalIdentity** [comment]
This is just a wording issue that will be fixed when we export all the gems on league launch
