### ISSUE TITLE
AutoExerted Seismic Cry and RallyingCry

### ISSUE THREAD

**Issue by Akorpz** [PathOfBuildingCommunity/PathOfBuilding#7899]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Not available yet.

### What is the value from the calculation in Path of Building?

Seismic Cry is not giving the AoE bonus with autoexertion with exerted attacks.
Rallying Cry is not giving the %more damage per affected ally affected with exerted attacks (for example running Herald of Purity - up to 4 allies)

### How to reproduce the issue

autoexertion gem support with Seismic Cry and RallyingCry connected.
Also add Herald of Purity for the 4 allies

### Character build code

```shell
x
```

**Comment by 13ootyknight** [comment]
+1 on the rallying cry not working with autoexertion but seismic cry is working on mine

![image](https://github.com/user-attachments/assets/1344ab7d-74c5-46d3-a2e0-a5c0a53a27e4)

**Comment by evovolvo** [comment]
Automated Seismic cry AOE does work. 
Seismic Cry itself is bugged in PoB though and it does not give Rage Vortex AOE for example, automated or not.

**Comment by evovolvo** [comment]
Which skill are you using that doesn't get AoE from Seismic in pob ?

**Comment by Akorpz** [comment]
Any Ground slam variant

**Comment by evovolvo** [comment]
> +1 on the rallying cry not working with autoexertion but seismic cry is working on mine
> 
> ![image](https://private-user-images.githubusercontent.com/66153856/351760745-1344ab7d-74c5-46d3-a2e0-a5c0a53a27e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTExMjUsIm5iZiI6MTcyMTg1MDgyNSwicGF0aCI6Ii82NjE1Mzg1Ni8zNTE3NjA3NDUtMTM0NGFiN2QtNzRjNS00NmQzLWEyZTAtYTVjMGE1M2EyN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE5NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MTFmNzM0OGM1NTFjZmExNzU0MDU2YWM5YzA3ZDVmYzk0Yjk1MGM5YzYyY2QzMWVhYzZlNjdmZmRiN2QwM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NJ1m0Iqut6OMEkIMBcGdSVjApve7OvBm-ZWxMbT5Df4)

It shows in the list but doesn't actually increase the number.
