### ISSUE TITLE
New Skill gem missing - Swordstorm

### ISSUE THREAD

**Issue by NNydek** [PathOfBuildingCommunity/PathOfBuilding#7903]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

I wanted to theory craft new skill gem, however as of now it is unavailable.

![image](https://github.com/user-attachments/assets/d735fc51-4765-4701-af94-1792c2e30a12) 
*Result when searching for "Sword"*

### Describe the solution you'd like

New skill gem added to the Path of Building

https://poedb.tw/us/Swordstorm
https://www.poewiki.net/wiki/Swordstorm

**Comment by LocalIdentity** [comment]
Gems will be added after league launch
