### ISSUE TITLE
PoB says 'Couldn't save the build file... Make sure the folder exists and is writtable'

### ISSUE THREAD

**Issue by Vic05Vicious** [PathOfBuildingCommunity/PathOfBuilding#7907]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When I click the Save button I should be able to write the name of the file and click to save it.

### How does Path of Building behave?

When I click the Save button, I get to write the name of the file, but after i try to save it an error window pops up saying:
'Couldn't save the build file: 
 *file path*
 Make sure the save folder exists and is writable'
 
 I've already uninstalled and deleted all folders, and reinstalled the software and it still happens.
 During the week I opt in for betas to see the new tree, but after the latest release i unchecked that box.
 But the problem started when I opt in for betas.

### How to reproduce the issue

-Make a new build
-Click the Save button
-Write the name of the build in the window that pops up
-Click the Save button
-Error pops up

### Character build code

```shell
https://pobb.in/1CIZ4EoVE1b-
```

### Screenshots

![pob_not_saving](https://github.com/user-attachments/assets/eaa4d530-5cf1-490d-ac02-4fe1cca2f0a6)

**Comment by Wires77** [comment]
Is your documents folder governed by one drive?  If you go to that file in explorer and open it in notepad, does the PoB save properly after that?

**Comment by Vic05Vicious** [comment]
> Is your documents folder governed by one drive? If you go to that file in explorer and open it in notepad, does the PoB save properly after that?

I have OneDrive uninstalled, so it shouldn't. No file gets created when I do this, if I go to the folder is just empty.

**Comment by Vic05Vicious** [comment]
Nope, it doesn't, just letters.

I tried to change the saving directory but it shows this error:
![imagen_2024-07-25_002210996](https://github.com/user-attachments/assets/60ec7fb7-f7ab-419a-9bc1-15b47e2dcf0c)

That file also doesn't exists in the folder, I'm showing all hidden elements in there too and still nothing.
No worries, I can still export them and make pob links to import them when I need them, thats at least what I've been doing.

**Comment by Wires77** [comment]
Something else must be preventing PoB from being able to save files at all, then.  Is that "Path of Building" folder writable?  Do you have an anti-virus software blocking PoB from making file changes?

You can most likely get the portable version of PoB to work, in any case: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.45.0/PathOfBuildingCommunity-Portable.zip

**Comment by Vic05Vicious** [comment]
It was Windows Defender, it had the Folder Access activated and that was preventing the software to read the folders.
Thanks for your help! I would not imagine WD would do that so randomly xdd
