### ISSUE TITLE
Vengeful Cry skill gem is missing

### ISSUE THREAD

**Issue by Adelor** [PathOfBuildingCommunity/PathOfBuilding#7910]
From patch notes:

>Added a new Strength Skill Gem, Vengeful Cry: Retaliate against a savage hit with a warcry, taunting all nearby enemies to attack the user. The user and nearby allies gain a buff which grants rage and prevents rage from being lost.

skill details
https://www.pathofexile.com/forum/view-thread/3532728

![image](https://github.com/user-attachments/assets/c97a444f-b75a-49bf-81e1-9319892eda95)

**Comment by Wires77** [comment]
New gems will release when the patch comes out
