### ISSUE TITLE
After the 2.45 from 2.44 my exsanguinate trap trickster build isnt loading - error

### ISSUE THREAD

**Issue by assfeet** [PathOfBuildingCommunity/PathOfBuilding#7923]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Open the build as it has in the previous version with no problems

### How does Path of Building behave?

error - view screenshot

### How to reproduce the issue

load build
[3.25 exsang.xml.zip](https://github.com/user-attachments/files/16369036/3.25.exsang.xml.zip)

### Character build code

```shell
i cant provide the build code since i cant open the build, i did add the build xml above
```

### Screenshots

![image](https://github.com/user-attachments/assets/b24546b5-d2d1-4ab2-a434-95049c83888d)

**Comment by LocalIdentity** [comment]
Fixed by #7920
