### ISSUE TITLE
Enabling Vaal Impurity of Ice would decrease Frost Blades' damage

### ISSUE THREAD

**Issue by Eqatrpfvvzzih** [PathOfBuildingCommunity/PathOfBuilding#793]
Here is a build:
https://pastebin.com/gUZXvrnZ

Hover the mouse near Vaal Impurity of Ice.
"Enabling this gem will give you: [**red** text] .. -25 Total DPS".

Now in the Configuration change the Enemy Cold Resistance, from 1 to 3.

Hover the mouse near Vaal Impurity of Ice.
"Enabling this gem will give you: [**green** text] .. +25 Total DPS".

Now in the Configuration change the Enemy Cold Resistance, from 3 to 2.

Hover the mouse near Vaal Impurity of Ice.
(No popup message at all!)

Is this behaviour correct?
How much is the Enemy Cold Resistance? (I could not find it in the Calcs.)
Before I filled the Enemy Cold Resistance, it was empty. Empty is equivalent (if I am right) with 0.
So, Shaper's Cold Resistance is zero?
How can Vall Impurity of Ice **decrease** the damage of Frost Blades?
Some negative resistances are involved? (And Vaal Impurity of Ice ignores even the negative resistances?)
The tree contains 2 "penetrates" nodes (selected). They give about 13 penetration (for cold).
(I also cannot find in Calcs: how much cold etc. enemy resistance will be penetrated. (Or "ignored".))

**Comment by Regisle** [comment]
not a bug 
![image](https://user-images.githubusercontent.com/49933620/79406493-6c9a4580-7fd6-11ea-8222-07da39eb1c0c.png)
