### ISSUE TITLE
Doomfletch and Doomfletch Prism have multiple errors

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#794]
Both of these items have various errors (missing/wrong stats) in their item data.

Doomfletch for example looks like this: ![](http://puu.sh/Fyca5/fbb6a5f0e4.png)

Doomfletch Prism has data for 4 item variants, but only 3 are actually available for selection: ![](http://puu.sh/Fyccm/2809ea18d7.png)

These errors are not present in Openarl's version, and it looks like they were introduced in 1.4.157.4: https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/e1e6cfe10fd9699201c5bdbc524760c669693027

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/Data/Uniques/bow.lua#L149

https://github.com/Openarl/PathOfBuilding/blob/master/Data/Uniques/bow.lua#L145

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
