### ISSUE TITLE
Vulnerability Quality Blank and not Functioning

### ISSUE THREAD

**Issue by Gunni14** [PathOfBuildingCommunity/PathOfBuilding#7942]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When I roll over variant for Vulnerability it should display what the quality does.

When I increase quality on Vulnerability it should give the gem "(1-20)% increased Duration of Bleeding on Cursed Enemies"

### How does Path of Building behave?

There is no description in variant and quality does not enhance the gem.

### How to reproduce the issue

Add Vulnerability as a skill, ensure variant is set to Default, attempt to read the tooltip then, increase quality.

### Character build code

```shell
https://pobb.in/GonSreVCzzEd
```

### Screenshots

![image](https://github.com/user-attachments/assets/f75eca08-8b50-4fcf-8bb6-21a24cedb75f)
![image](https://github.com/user-attachments/assets/85d89aa8-eeba-405d-b101-1043c1f75ef0)

**Comment by LocalIdentity** [comment]
Will be updated after the league launch. The mods doesn't affect anything in PoB atm anyway
