### ISSUE TITLE
Clarification on how the Patreon of POBArchives ties into Trending in POB

### ISSUE THREAD

**Issue by Cloudslapper** [PathOfBuildingCommunity/PathOfBuilding#7946]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

How does POBArchive's Patreon-paid Build Highlight functionality tie into the Trending Page on the new POB update pushed by the creator of POBArchive?
I am worried about the situation of this turning POB into an ad platform for creators.
You have no incentive to even create the build yourself, the Pob can be taken from anywhere and uploaded, and as long as the user pays the Patreon tier, can be pushed to the front page as well.

### Describe the solution you'd like

Clarification of above concerns requested.

**Comment by aminoginji** [comment]
I think POBArchive is just the first website added im sure more will be added as for POBArchive there are not pateron only builds as the feature lists how builds will be shown as trending and latest that data would be taken from the website. Having a quick view to check websites like POBArchive and see what people are looking at quickly and checking them out without having to scrounge around multiple websites. If a creator is making really good builds i would expect them to be trending. Having this feature in doesn't stop people from "creating a build themselves" but could help new players with finding builds not knowing the websites to look for them overall i enjoy this feature I played around with it a bit before release and i look forward to more websites being added

**Comment by Cloudslapper** [comment]
> I think POBArchive is just the first website added im sure more will be added as for POBArchive there are not pateron only builds as the feature lists how builds will be shown as trending and latest that data would be taken from the website. Having a quick view to check websites like POBArchive and see what people are looking at quickly and checking them out without having to scrounge around multiple websites. If a creator is making really good builds i would expect them to be trending. Having this feature in doesn't stop people from "creating a build themselves" but could help new players with finding builds not knowing the websites to look for them overall i enjoy this feature I played around with it a bit before release and i look forward to more websites being added

Many (Incl. Zizaran) did/does not even know their builds are scraped and placed on the website.
The person also requested for his website(POBArchive) to be placed as the default data source. On an open source project.

This does not change the fact that a for-profit closed website is integrated into PoB, and could easily be seen as a traffic harvester.
This combined with the 800 different vendors POBArchive is tied to through cookies for user data.
^(credits: [BellabongXC](https://www.reddit.com/user/BellabongXC/)

On top of ninja-editing the Patreon tier perks when called out within an hour. 2 Times.
First edit removed the "Your builds will be favored in Search"
Second edit removed the "Your builds will be highlighted"
As can be seen here: https://i.imgur.com/pPsuF1e.png

On top of harvesting all of the builds on the POBArchive website through Youtube&Reddit with a bot scraping both.
To many people's annoyance, no less. (People on PathOfExileBuilds' subreddit in particular are displeased)

I cannot see how this was made with good faith, but I'm open to further info.

**Comment by aminoginji** [comment]
> > I think POBArchive is just the first website added im sure more will be added as for POBArchive there are not pateron only builds as the feature lists how builds will be shown as trending and latest that data would be taken from the website. Having a quick view to check websites like POBArchive and see what people are looking at quickly and checking them out without having to scrounge around multiple websites. If a creator is making really good builds i would expect them to be trending. Having this feature in doesn't stop people from "creating a build themselves" but could help new players with finding builds not knowing the websites to look for them overall i enjoy this feature I played around with it a bit before release and i look forward to more websites being added
> 
> Many (Incl. Zizaran) did/does not even know their builds are scraped and placed on the website. The person also requested for his website(POBArchive) to be placed as the default data source. On an open source project.
> 
> This does not change the fact that a for-profit closed website is integrated into PoB, and could easily be seen as a traffic harvester. This combined with the 800 different vendors POBArchive is tied to through cookies for user data. ^(credits: [BellabongXC](https://www.reddit.com/user/BellabongXC/)
> 
> On top of ninja-editing the Patreon tier perks when called out within an hour. 2 Times. First edit removed the "Your builds will be favored in Search" Second edit removed the "Your builds will be highlighted" As can be seen here: https://i.imgur.com/pPsuF1e.png ^credits: https://www.twitch.tv/ghazzytv
> 
> On top of harvesting all of the builds on the POBArchive website through Youtube&Reddit with a bot scraping both. To many people's annoyance, no less. (People on PathOfExileBuilds' subreddit in particular are displeased)
> 
> I cannot see how this was made with good faith, but I'm open to further info.
I would assume its the default data source because it was what the user who made the feature wanted. As for an open source program with a built in function to get builds from a closed source website what's the issue? Its grabbing a https://pobb.in/ link from the page.

How old is that information? Looking at the patron myself i don't see those options. If your saying they were called out on it and then removed those perks id say that's a good thing? 

Harvesting public data and organizing it giving credit to the creator I believe that's proper.

Still lost as to why people would think this is a bad feature. If what your saying is true the creator:

1. Removed ill gotten gains from Patreon which would have boosted Patreon subs builds
2. Scrapes publicly available data giving credit to the author of said builds

As for the feature itself yes there should be an option to disable the function in POB if your don't want POBArchive to load content keeping all them cookies safe for people. I'm hoping more websites want to add in their own functionality down the road or others add it themselves.

PathOfExileBuilds cant find any discontent about pobarchives or POB please share, also the video i am genuinely interested. 

I do see issues with stealing builds and posting them as your own from creators but that doesn't seem to be the case.

**Comment by Cloudslapper** [comment]
> How old is that information? Looking at the patron myself i don't see those options
From today, you can see it through one of Ghazzys top clips.

> Still lost as to why people would think this is a bad feature. If what your saying is true the creator:

No one says it's a bad feature, it's where and how the information is pulled. I'm all for an opt-in version of this feature
Though I request it being turned off by default due to new players getting into issues with certain builds if they choose to follow them, without the needed context from the video the build originates from.



> PathOfExileBuilds cant find any discontent about pobarchives or POB please share, also the video i am genuinely interested.

The scraping bot was banned on PathOfExileBuilds as of today, so that users no longer see it. Doesn't prevent the scraping though. I'll need some time to find the discontent, though users made it very obvious in the threads regarding this situation on the normal poe subreddit.


Ghazzy's clip/vod: https://www.twitch.tv/ghazzytv/clip/SpineyVivaciousTireSwiftRage-HJKDbTZeH2flvtnK

**Comment by aminoginji** [comment]
thanks for the vid and a link to the bot posts

**Comment by Cloudslapper** [comment]
closing this, as reading LocalIdentity's reddit post clarified the issue
