### ISSUE TITLE
Trending/Latest Builds not loading (empty list)

### ISSUE THREAD

**Issue by GnetDan** [PathOfBuildingCommunity/PathOfBuilding#7947]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

After "Loading..." text is cleared in Trending/Latest builds window, should list Trending/Latest Builds

### How does Path of Building behave?

After "Loading..." text is cleared in Trending/Latest builds window, nothing is listed

### How to reproduce the issue

Open application with default settings

### Screenshots

![image](https://github.com/user-attachments/assets/86230d3f-0899-440a-9d25-19ea0b9734e7)

**Comment by GnetDan** [comment]
Tried:
- Run as admin
- Add Path of Building.exe to firewall approved applications list

**Comment by kan3** [comment]
Also having same issue, saw this feature on reddit and updated mine just to see a blank screen.

**Comment by mcheese** [comment]
As far as I know, because of the concerns surrounding this feature it has been disabled for now. Until everyone figures out how to proceed.

**Comment by Rybadour** [comment]
Pretty sure it hits this URL with a simple GET request and you can see it's currently returning an empty payload: https://pobarchives.com/api/builds?q=Latest

**Comment by jjstewart** [comment]
It has been removed from the current release, further everyone using POB was without their knowledge polling his API which brought his site down.

**Comment by LocalIdentity** [comment]
The list is removed for now until we find a better way to implement it
