### ISSUE TITLE
Warcries are not applying to Minions, only Rallying Cry does

### ISSUE THREAD

**Issue by Scorptice** [PathOfBuildingCommunity/PathOfBuilding#7952]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

According to GGG's 45 min video at 28:50 Mark specifies that Warcries apply to Allies per default. 

### What is the behaviour in Path of Building?

In PoB no warcry with the exception of Rallying Cry applies to Minions in the config.

### How to reproduce the issue

Equip Warcry as skill, equip a minion skill, select infinite power chieftain - no changes to their resistances/life reg/whatever

### Character build code

```shell
https://pobb.in/eZKYHwsrXAaG
```

**Comment by LocalIdentity** [comment]
Fixed in the latest update (2.47.0)
