### ISSUE TITLE
Visual bug. Calcs tab showing 0% generic DoT multiplier, shows separate multipliers when hovered over. 

### ISSUE THREAD

**Issue by MarsAndon** [PathOfBuildingCommunity/PathOfBuilding#7956]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

Pretty much the title. 
All modifiers apply to damage, all of them are present when hovering over the total value. 
Just the total value shows as 0.
Checked on Blight of Contagion, Vaal blight in my build and also on ED and Wintertide Brand on an empty build with Acrimony cluster allocated.

### What is the wording in Path of Building?

![image](https://github.com/user-attachments/assets/b2c059a0-cd68-4d04-8397-f1bb955c3d47)

### Character build code

```shell
https://pobb.in/W2bTRwTfLHG2
```

**Comment by Rybadour** [comment]
Looking into this as my first bug fix in the project! I can see it happening locally with the latest version.
