### ISSUE TITLE
Removal of the POBArchive integration and the link to the website with the "See All"' button.

### ISSUE THREAD

**Issue by falingsumo** [PathOfBuildingCommunity/PathOfBuilding#7959]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

PoB should not be adding 3rd party integration to build websites. It invites bad actors to try and promote builds based off of payments they have received and also poses a security risk as the integration can have malicious code executed on clients machine. A user should be able to choose and how to import builds. 

### Describe the solution you'd like

Removal of the whole "Trending and Latest" panel as well as the "See All" button at the bottom of the panel that links to POBArchive.

### Describe alternatives you've considered

There should not be an alternative. We already have PoENinja as a build aggregator and it is already being abused.

### Additional context

PoB should not be linking to external source especially if they are being monetized with Patreon Tiers where you can pay someone not part of PoB to be featured on the PoB front page.

**Comment by LocalIdentity** [comment]
Duplicate of #7944
