### ISSUE TITLE
Is buildMode:CloseBuild working properly?

### ISSUE THREAD

**Issue by poby70** [PathOfBuildingCommunity/PathOfBuilding#796]
I selected a build from the build list and clicked it.
I changed some nodes.
I clicked the <<Back button.

This build has unsaved changes.
Do you want to save them now?

I chose Don't Save.

However, when the build was selected again from the build list, the last changes are saved.

Isn't it right to keep the existing build contents unless you open the build and change the node, click Save New or Save?

I used Google Translator because English is not a language.

**Comment by ppoelzl** [comment]
I cannot reproduce this.
