### ISSUE TITLE
Fist of war not applying to Doryani's touch skill

### ISSUE THREAD

**Issue by Truckyer** [PathOfBuildingCommunity/PathOfBuilding#7963]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

Fist of war supports Doryani's touch applying the skill gem's damage increase and visual

### What is the behaviour in Path of Building?

Damage increase does not happen, area of effect does not change

strength requirement DOES change

### How to reproduce the issue

add doryani's fist
add fist of war support gem

tested with other slam skills and then all work, eg:

add ground slam
add fist of war support

### Character build code

```shell
https://pobb.in/FjbZGSzLS74L
```

### Screenshots

![image](https://github.com/user-attachments/assets/e279252b-2029-4f7f-ad8c-151577452a82)
![image](https://github.com/user-attachments/assets/ac16e052-e104-4fcc-a3b7-6219ee8a30a2)

**Comment by LocalIdentity** [comment]
Fixed in the latest update (2.47.0)
