### ISSUE TITLE
Set default item quality to 20%

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#7966]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

When you create a rare item, the quality by default is 0%, which is rarely, if ever, the intended value.

### Describe the solution you'd like

The quality should be at 20% by default. Additionally, we could have the option to specify the default value in the options menu.

**Comment by Wires77** [comment]
Hmm, this used to happen, I'm guessing it accidentally changed when we added a UI box to set the quality of an item.
