### ISSUE TITLE
The Redeemer suffix "Auras from your skills grant X% increased damage to you and allies" does not properly stack

### ISSUE THREAD

**Issue by findar** [PathOfBuildingCommunity/PathOfBuilding#798]
This is a suffix available on one-handed weapons with the Redeemer influence.  When two wands are created in PoB, the expected behavior is that each mod will individually add a 2% modifier to auras for a total of 4%.  Actual behavior is only one modifier seems to work.

Repro steps in Path of Building: 
-  Using provided build: https://pastebin.com/JTpBwtSr
- Select "Arc" as Main Skill
- Go to "Items" tab
- Alternate between sets - No weapon - One Wand - Two Wand - Expected Two Wand
- Observe

Repro steps in Path of Exile:
- Acquire two wands with affix and no other mods that impact skill
- Acquire Clarity
- Observe tooltip DPS of skill
- Enable Clarity
- Equip one wand and observe
- Equip second wand and observe

**Comment by findar** [comment]
Here is a link with screenshots in game: https://imgur.com/a/isLgmIT

**Comment by findar** [comment]
Workaround: Manually edit one of the wands to have 4% instead of 2%

**Comment by LocalIdentity** [comment]
This is fixed in the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
