### ISSUE TITLE
Importing character missing gear

### ISSUE THREAD

**Issue by steelle** [PathOfBuildingCommunity/PathOfBuilding#7980]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Importing a character from their profile should show all items/skills. 

### How does Path of Building behave?

After importing a character using import "Passive Tree and Jewels" along with "Items and Skills", some items are missing (Body Armor is commonly affected for example). The item does display properly on the public POE profile. 

### How to reproduce the issue

- Select Import/Export Build
- enter profile name "PoEDan79"
- select start
- choose league hardcore settlers
- choose character DanBaldLightning
- select Passive Tree and Jewels button
- select Items and Skills button
- select items tab on the left panel

### Character build code

```shell
https://pobb.in/aI7nLVs-nI_Y
```

### Screenshots

![Screenshot 2024-07-27 114348](https://github.com/user-attachments/assets/8697f01d-3c11-4066-84d2-041ae0d9266c)
![Screenshot 2024-07-27 114411](https://github.com/user-attachments/assets/c1eed6c3-7ef0-41eb-8be0-7cd1aa0119cd)

**Comment by LocalIdentity** [comment]
He's got one of the new Evasion / ES Body armours on which is not in PoB yet. It'll be fixed once we release the update with all the new league stuff
