### ISSUE TITLE
Can't import new builds

### ISSUE THREAD

**Issue by twofoldAnnihilation** [PathOfBuildingCommunity/PathOfBuilding#7984]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When I choose to import a build, it should work as intended

### How does Path of Building behave?

When I select to import a build, I get an error message. I've tried with a few build codes so far, all of them reproduce the same error message.

### Character build code

```shell
https://pastebin.com/Xx3EAYWC
```

### Screenshots

![5137925f10973460c67f1ec688986449](https://github.com/user-attachments/assets/596b7424-0d87-4570-939e-c4d2f9966b24)

**Comment by twofoldAnnihilation** [comment]
I was also asked in another post to share my config or configsets .xml files but they appear to be missing from my documents folder where my builds are saved. Might be the overall issue but this is after a fresh installation of the current POB Fork

**Comment by Nightblade** [comment]
Could you check if Defender has quarantined your .xml files?   This PowerShell command can show you the last blocked items:
```powershell
Get-MpThreatDetection | Select-Object -ExpandProperty resources
```

**Comment by twofoldAnnihilation** [comment]
> Could you check if Defender has quarantined your .xml files? This PowerShell command can show you the last blocked items:
> 
> ```powershell
> Get-MpThreatDetection | Select-Object -ExpandProperty resources
> ```

![666d11dd1ef3c44b0fd70bb4bf821cc0](https://github.com/user-attachments/assets/e9695368-7679-4181-b255-c647e4038257)
I get no response to that command in Powershell

**Comment by frzensade** [comment]
I am having the exact same error and it is returning the same in powershell. 

![image](https://github.com/user-attachments/assets/5031e046-9e9c-42f0-8ffc-cd9897c8d2d4)

**Comment by Wires77** [comment]
@frzensade are your builds stored in OneDrive?
