### ISSUE TITLE
Incorrect Spell Block calculations

### ISSUE THREAD

**Issue by CrowdControlled** [PathOfBuildingCommunity/PathOfBuilding#7987]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

49% chance to block spells

### What is the value from the calculation in Path of Building?

59% chance to block spells

### How to reproduce the issue

With a 25% chance to block shield, i have Shield Mastery "1% chance to block spells per 5% chance to block attacks" and "1% chance to block attacks per 5% chance to block on shield, Versatile Combatant and Determined Survivor Gladiator Ascendancy node. I belive this is because of how the logic is treating the 50% block chance on shield override as this adds up to the extra 10% spell block (an extra 25% chance to block on a shield leading to an extra 5% chance to block attacks, being doubled to 10% chance to block spells).

### Character build code

```shell
https://pobb.in/2gUXFz6SnTn9
```

### Screenshots

![Untitled](https://github.com/user-attachments/assets/934d316a-e36f-461b-af71-ccd601c748df)

**Comment by CrowdControlled** [comment]
I forgot to write that im using version 2.46 (beta).

**Comment by LocalIdentity** [comment]
This is fixed on our dec branch and will be included in the next update
Fixed by #7979
