### ISSUE TITLE
Eviscerate not found

### ISSUE THREAD

**Issue by ascent-sys** [PathOfBuildingCommunity/PathOfBuilding#7989]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

There is no Eviscerate skill in the skill list.

### How does Path of Building behave?

There is no Eviscerate skill in the skill list.

### Screenshots

![1](https://github.com/user-attachments/assets/3ca30a84-20ff-4da3-b830-860e50154cf1)

**Comment by LocalIdentity** [comment]
Fixed by #7988
