### ISSUE TITLE
Shield Mastery that provides '1% chance to block attack damage per 5% chance to block on equipped shield' should use the shield's value instead of Determined Survivor's value

### ISSUE THREAD

**Issue by Rullamas** [PathOfBuildingCommunity/PathOfBuilding#7998]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Using the Shield Mastery that provides '1% chance to block attack damage per 5% chance to block on equipped shield' uses the value of the equipped shield in-game, NOT the 50% value provided by Determined Survivor.

### What is the value from the calculation in Path of Building?

 POB uses the 50% to calculate this value, giving you 10% chance to block attack damage.

### How to reproduce the issue

Take Determined Survivor
Take Shield Mastery

### Character build code

```shell
https://pobb.in/bo359iNHke-N
```

### Screenshots

https://www.pathofexile.com/forum/view-thread/3534068

**Comment by LocalIdentity** [comment]
Fixed of dev for next update
