### ISSUE TITLE
Chance to block attack damage craft not adding to block attack chance calculation

### ISSUE THREAD

**Issue by caseytoomey** [PathOfBuildingCommunity/PathOfBuilding#8014]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

5-7% Chance to Block Attack Damage

### What is the value from the calculation in Path of Building?

0%

### How to reproduce the issue

Create chest piece with chance to block attack damage craft

### Character build code

```shell
https://pobb.in/U92lGh6PMS7j
```

### Screenshots

https://i.imgur.com/7zpx8yk.png
https://i.imgur.com/c8slyaf.png

**Comment by LocalIdentity** [comment]
Fixed in 2.47.2 that I just released
