### ISSUE TITLE
2.47.2 causes Viper Strike of the Mamba to apply multiple poison stacks

### ISSUE THREAD

**Issue by JustinStitt** [PathOfBuildingCommunity/PathOfBuilding#8018]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Mamba should poison only once

### What is the value from the calculation in Path of Building?

Showing too many poison stacks (inflating the dps)

### How to reproduce the issue

select mamba, get some attack speed, see more than 1 poison stack in calcs page

### Character build code

```shell
https://pobb.in/bGsEMVjn1KQ-
```

**Comment by 71M073J** [comment]
Same issue, more specifically the "Cap to Single Poison on enemy" toggle does nothing when using low tolerance/poison mastery with viper strike of the mamba. Changing to a normal Viper strike fixes the behaviour.

**Comment by LocalIdentity** [comment]
Fixed in v2.47.3 that was just released
