### ISSUE TITLE
Trade for those item not working

### ISSUE THREAD

**Issue by Emp1xD** [PathOfBuildingCommunity/PathOfBuilding#8024]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When I click trade for this item I should have the ability to select league.

### How does Path of Building behave?

Got LUA Error.
Error while fetching League list: response code 503.

### How to reproduce the issue

1. close build ads, open build directly from content creator
2. clic on trade for this item in item tab

### Character build code

```shell
https://pobb.in/20ygT23MsdQV

Tested on various builds
```

### Screenshots

![image](https://github.com/user-attachments/assets/e16e80b3-645a-4f3e-8904-b72cde23c8a8)

**Comment by LocalIdentity** [comment]
Your poesessid is out of date and needs to be removed or updated
