### ISSUE TITLE
Support Build Import Error

### ISSUE THREAD

**Issue by Sora1276** [PathOfBuildingCommunity/PathOfBuilding#8033]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

![Screenshot 2024-07-30 122026](https://github.com/user-attachments/assets/f9927a1c-3f30-4b90-a186-3fdd0dabd0f8)

### What are your system specifications and configuration?

Windows 11 pro, GeForce RTX 3070, Ryzen 5600x, 32gb DDR5 Ram

### How to reproduce the issue

By trying to import any support onto a POB

**Comment by Sora1276** [comment]
For example, this pob is unable to be applied as a support without the error. But it's not the only one I've tried.
https://pobb.in/TuA9Mk1Tn28N
It seems like removing the Haste gem from the support fixes being able to import, but it a bit finicky.

**Comment by Regisle** [comment]
looks like its fixed by #8022

**Comment by LocalIdentity** [comment]
Fixed in v2.47.3 that was just released
