### ISSUE TITLE
Temporal Chains cap is not respected

### ISSUE THREAD

**Issue by enizor** [PathOfBuildingCommunity/PathOfBuilding#806]
Initially reported on [Reddit](https://www.reddit.com/r/pathofexile/comments/g4k0ml/path_of_building_community_v141691_installer/fny8ilh/)

Using cluster Jewels with Curse Effectiveness, one can make Temporal Chains have more than 187% effectiveness. That makes is expiration effect go past the 75% hard cap.
If you stack enough jewels, you can have exactly 250% curse effect and infinite debuff duration or even negative duration when you go past that mark.

[Exemple pastebin](https://pastebin.com/KaE4cwRv)

The Enfeeble cap is also probably not respected but I saw no simple way to test it.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
