### ISSUE TITLE
Error 'OnFrame': ClassesCalcBreakdownControl.lua:414: attempt to index a a nil value stack traceback

### ISSUE THREAD

**Issue by AceKuper** [PathOfBuildingCommunity/PathOfBuilding#8060]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/user-attachments/assets/3acfd27d-8b8a-48be-b528-063f30e37ee4)

### What are your system specifications and configuration?

Windows 10
Intel i7-7700K
GTX 108
16gb 2133MHz RAM

### How to reproduce the issue

Opening calcs tab of this [Carry build](https://pobb.in/rc2V3e82Beji) in PoB results in this error.

The cause seems to be the imported Party tab. If importing a build from a direct pobb.in link, like in the [Aurobot](https://pobb.in/JDvQLXM_0-TW) build as the pair for the build above, it sets

Currently `FireResistAura` should be `PurityOfFire`
Currently `LightningResistAura` should be `PurityOfLightning`
Currently `ColdResistAura` should be `PurityOfIce`
Currently `SpellDamageAura` should be `Zealotry`

Simply changing this 4 in the party screen seems to fix it.

Exporting the said Aurobot with Export Support checked, also seems to fix the problem, but throws the calcs off since it exports the specific Loadout selected.

Might be an issue of incorrect names being imported from direct links in general.

### Character build code

```shell
In the description of the issue
```

**Comment by capSAR273** [comment]
Experiencing this also on 2.48.1

**Comment by Regisle** [comment]
Sorry I didnt see this issue before, I will see if I can find time today to fix it, should be pretty easy, but yeah for now you can just re-export the support to fix it

**Comment by Regisle** [comment]
Sorry again for not seeing this earlier, fixed by #8211
