### ISSUE TITLE
Warden Seasoned Hunter

### ISSUE THREAD

**Issue by amaddalo** [PathOfBuildingCommunity/PathOfBuilding#8063]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

The Warden's seasoned hunter node isn't making tinctures work with ranged weapons for any sort of calculations

### Describe the solution you'd like

Likely have the Warden's Seasoned Hunter node change a flag in tinctures to allow them to work with ranged weapons

**Comment by SaltedNinja** [comment]
Confirmed I'm having this same exact issue...
