### ISSUE TITLE
Lua:1959

### ISSUE THREAD

**Issue by Olieyuh** [PathOfBuildingCommunity/PathOfBuilding#8064]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When I open PoB it should start up and fine and show my build.

### How does Path of Building behave?

When I launch the app it get a Lua:1959 error

### Screenshots

![image](https://github.com/user-attachments/assets/26c92708-0dd7-4c41-98d3-33c226b8b59c)

**Comment by Olieyuh** [comment]
It started doing this today when I got home, before and after I updated it. I tried restarting, re downloading and running as admin. Not sure what to do? Can't find anything anywhere on this specific error.

**Comment by Paliak** [comment]
Seems to be caused by POB having issues parsing the build xml of your build. Could you post the build file here?

**Comment by Paliak** [comment]
> > Seems to be caused by POB having issues parsing the build xml of your build. Could you post the build file here?
> 
> I'm not sure how to post my build here.

Drag and drop the xml file or open in preferred editor and paste the contents.

**Comment by zao** [comment]
Your `Builds` directory is by default either in your `Documents` folder under `Path of Building\Builds`, or in the case of a portable Path of Building installation, in a Builds directory directly inside the portable installation.
Each build you have in your collection is stored as an XML file by the same name.

**Comment by Olieyuh** [comment]
I found the file, for some reason it was empty even though other builds I had in for this league had content in them. I just deleted the file and I can now launch the app as normal and am now re importing my character. Everything seems fine so far.
