### ISSUE TITLE
Ward calculation wrong on last version

### ISSUE THREAD

**Issue by Basti3n** [PathOfBuildingCommunity/PathOfBuilding#8073]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

I'm a wardloop player and I encountered an issue with the calculation of the ward in POB.
The value is different between the number in game and the one on POB.

It' might a question of order because new unique belt and helmet.

In game, I currently have *8107* ward.

I could had that the issue is the same with Olroth resolve on or off.

### What is the value from the calculation in Path of Building?

In POB, I currently have *7123* ward which is wrong.

### Character build code

```shell
here is the pobb code: https://pobb.in/leydQTiJxeyQ

And if you want to have some more accurate value, here is my IGN "tag94360" and the character is "un_feutre_bleu".
```

### Screenshots

![image](https://github.com/user-attachments/assets/ae2ab182-107a-494e-b115-5c4140e68dba)
![image](https://github.com/user-attachments/assets/0e009f4a-bbeb-418e-943b-0729b2d8c776)

**Comment by Regisle** [comment]
The belt mod isnt being scaled in PoB correctly and is fixed by #8062

**Comment by Basti3n** [comment]
@Regisle I you're right i didn't see !

Should i close the issues then ?

Thanks in advance

**Comment by LocalIdentity** [comment]
@Basti3n It'll be auto closed when we merge the fix

**Comment by Basti3n** [comment]
Amazing 👍 

It's my first time making an issue, sorry !
