### ISSUE TITLE
Feature request: Exclude nodes from the heatmap

### ISSUE THREAD

**Issue by Malecious** [PathOfBuildingCommunity/PathOfBuilding#808]
When looking at node power on offence/defence or DPS (didnt test others) PoB tells me that elemental overload is a major increase in DPS. This cannot be true as I am playing hollow palm, thus unarmed, thus my crit chance is 0%, so I could never activate elemental overload. All my damage is elemental.

**Comment by Regisle** [comment]
it does this becouse you can crit by other methods

**Comment by Malecious** [comment]
> 
> 
> it does this becouse you can crit by other methods
I guess I could get a spell that crits for me. In that case I would propose that there would be a way to disable that node showing up, as right now it kinda screws up the red colour palet for DPS when highlighting

**Comment by Lothrik** [comment]
This seems more like a feature request than a bug, as you want to blacklist a specific keystone from the heatmap.

**Comment by lorrey** [comment]
If selected main skill have 0% chance to crit EO must not show damage increase. Isn't it intuitive? If skill acquire any crit chance it will be re-calculated anyways.

**Comment by ppoelzl** [comment]
Update 1.4.170.12 added a "Power Report" feature that adresses this issue.
