### ISSUE TITLE
25% inversion mastery is no longer calculated in dps

### ISSUE THREAD

**Issue by koticgood** [PathOfBuildingCommunity/PathOfBuilding#8089]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

25% chance for inversion

### What is the behaviour in Path of Building?

Mastery does not affect dps

### How to reproduce the issue

Allocate the node

### Character build code

```shell
https://pobb.in/eYDXWM0dsgAX
```

**Comment by Regisle** [comment]
You do not have the enemy configured to have resistances (eg set it to a boss to give them default res)
It works fine if they have res
![image](https://github.com/user-attachments/assets/e91469a9-2017-45fc-86b6-cb94405650e5)

**Comment by koticgood** [comment]
... sorry
