### ISSUE TITLE
Spaces aren't automatically HTTP-encoded

### ISSUE THREAD

**Issue by TNTftw21** [PathOfBuildingCommunity/PathOfBuilding#8095]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Linux - Wine

### How is Path of Building expected to behave?

I would expect PoB to automatically sanitize spaces to at least an HTTP-compliant form. 

### How does Path of Building behave?

Spaces (and presumably other special characters) are used as-is. Interestingly, entering the space in HTTP encoding ('%20') causes it to automatically get converted to a '+'.

### How to reproduce the issue

Attempt to import a build via account name
Enter an account name that uses spaces (e.g. XBox realm "soL Phantom")
PoB returns "account profile is private" error

### Character build code

```shell
N/A
```

### Screenshots

![image](https://github.com/user-attachments/assets/3695af04-93a1-4044-b561-7b61d62f033f)
![image](https://github.com/user-attachments/assets/18df57ec-4ca6-4e28-9012-e5ffbec2d383)
![image](https://github.com/user-attachments/assets/91eac1ad-a032-4dfb-8ba9-ec1678248f22)
![image](https://github.com/user-attachments/assets/94d86cd2-55f3-4fef-840d-e8e9e1f823e1)

**Comment by TNTftw21** [comment]
Worth noting: This issue seems to be related specifically to console accounts, as PC only allows using alphanumerics in account names.

**Comment by LocalIdentity** [comment]
Fixed on dev. Will be in the update out tonight
