### ISSUE TITLE
Support for Bonechills

### ISSUE THREAD

**Issue by jan-car** [PathOfBuildingCommunity/PathOfBuilding#810]
The Bonechill Support Gem has the two following lines:
```
Enemies Chilled by Supported Skills have Cold Damage taken increased by Chill Effect
Enemies in Chilling Areas from Supported Skills have Cold Damage taken increased by Chill Effect
```
Would it be possible to implement this modifier?

The (global) Chill Effect is listed in the Calculations Tab under Elemental Ailments and would need to be added to Bonechills local increased Chill Effect (up to 44% at Level 20) and any other Supports like Hypothermia or Unbound Ailments (the latter having "increased Effect of non-Damaging Ailments on Enemies"). According to the Wiki, this value is capped at 30%. 

The value then would need to go into the calculation of the "Effective DPS Mod", right next to calculations like Shock.

**Comment by ppoelzl** [comment]
Added in 1.4.170.3.
