### ISSUE TITLE
Error Spell Suppression Calculation & DPS Jumping around

### ISSUE THREAD

**Issue by LostFelix** [PathOfBuildingCommunity/PathOfBuilding#8104]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

https://pobb.in/-4BrYmk-cSGQ
With this build ingame i have 79% spell suppression chance ingame, without the dagger
Equipping it does give me 100% (114%).

### What is the value from the calculation in Path of Building?

@Fanfarik 1 Incandescent Invitation is already sold, sorry for the inconvenience Fanfarik
With this build, i have 100% spell suppression, but unqeuipping the Dagger does turn the spell suppression into 23% ....

Also when i import my passive tree or change notes and back, i often get jumps in DPS, sometimes drastically a few hundret thousand missing or adding.
The tincture and flask i check that they are unchecked, and my config for the enemy is always guradian/pinnacle boss.

### How to reproduce the issue

I can't tell you, i just build this abomination and now i found this issue.

### Character build code

```shell
https://pobb.in/-4BrYmk-cSGQ
```

**Comment by Regisle** [comment]
> With this build ingame i have 79% spell suppression chance ingame, without the dagger
Equipping it does give me 100% (114%).

You have 69 spell suppression chance ingame without dagger, this goes up to 79 while on full life (from revenge of the hunted)
that +10% while on full life is also why the value with the dagger is different (104->114%), if you tick "always on full life" the value will be the same as ingame while you are full life ingame

> With this build, i have 100% spell suppression, but unqeuipping the Dagger does turn the spell suppression into 23% ....

You have ehp calcs set to very unlucky
![image](https://github.com/user-attachments/assets/2476440a-6b81-4a9f-9f24-6389980c6d2f)
This gives you 0.69*0.69*0.69*0.69 = 22.667121% chance to suppress, set it to average if you want it to reflect the ingame value or check the full value on calcs page
![image](https://github.com/user-attachments/assets/ed06d56d-fd66-4ad9-990c-35eccb82d166)

> Also when i import my passive tree or change notes and back, i often get jumps in DPS, sometimes drastically a few hundret thousand missing or adding.

I have no idea what this means, allocating or unallocting random nodes does not seem to change dps by any meaningful amount, and removing or adding impactful nodes (eg notables) does change your dps by +- (4-7)% which is 100,000-200,000 a node? can you give me an example of a node which gives an incorrect dps change when allocating/unallocating it?

**Comment by LostFelix** [comment]
ah man i'm stupid, i thought "ehp calculation" only affected ehp, especially with spell suppression being a percentile based stat.

So that explains a lot .... used that setting for a long time now.... sorry for that.

The DPS jumping i can't replicate, just wanted to mention it.
Without any concrete changes triggering it it's more of a fluke ... i hope.
A friend currently playing also has the issue, but he loses/gains 1 - 3 millions randomly.
But again he could also not tell me why.
Soooo yeah, second half not as important.
But the spell suppression ... so sorry for that.

**Comment by Regisle** [comment]
> i thought "ehp calculation" only affected ehp

It was changed recently to also show on the sidebar, its doing the same thing as the lucky suppress mastery (which would altar the sidebar value before), and those do "only affect ehp" as the stat isnt used for anything else, the actual spell suppress value is preserved before lucky/unlucky for anything which could care about it

Also dont worry about making issues, its easy enough to check if its invalid and Its better to know if theres issues

> A friend currently playing also has the issue,

If you or your friend do find the problem please make an issue so we can fix it
