### ISSUE TITLE
Seismic Cry More Armour Buff Effect Calculation 

### ISSUE THREAD

**Issue by OnurcanPekgoz** [PathOfBuildingCommunity/PathOfBuilding#8106]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

In game with Chieftain's Sione Sun's Roar (Infinite power and 30% increased buff effect) it gives 32% more armour. (6.5% per 5 power=32.5 rounded down )

### What is the value from the calculation in Path of Building?

In PoB it calculated as 4% per 5 power. It also changes with skill level which should not happen.

### How to reproduce the issue

1.  Set the seismic cry skill.
2.  Choose Chieftain's Sione Sun's Roar  ascendancy
3.  Look Calc tab and see Total More Armour

### Character build code

```shell
https://pobb.in/CT6eC6TG-fd6
```

### Screenshots

![image](https://github.com/user-attachments/assets/8d8f09a4-89e5-4a28-b94c-dab321510cc3)

**Comment by Regisle** [comment]
You gave us a minimum example and not your actual build, PoB rounds the value per power, so its very possible we are wrong and need to look at it in more detail, currently with 100% uptime PoB calculates it as 6% more per power (for a total of 30% more)

The other issue which I suspect you were seeing in your build is PoB also scales it based on uptime, either increase duration/cooldown recovery speed to increase uptime or set "exerted/boosted calc mode" to max hit to always calc as if warcry is active
![image](https://github.com/user-attachments/assets/04688b0f-52af-4570-9521-83a61164cb58)

**Comment by LocalIdentity** [comment]
Fixed on dev for the next update
