### ISSUE TITLE
Error when creating/importing an elder staff/warstaff with "socketed gems supported by power/endurance charge on crit/stun"

### ISSUE THREAD

**Issue by Balline** [PathOfBuildingCommunity/PathOfBuilding#8107]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

When importing or creating a staff or warstaff with elder influence which has either the "Socketed gems are supported by level 10 power charge on critical strike" or "Socketed gems are supported by level 10 endurance charge on melee stun" I get this error.
![error](https://github.com/user-attachments/assets/0a95130b-8275-404e-8bdd-2ee021b24694)

### What are your system specifications and configuration?

Windows 10

### How to reproduce the issue

1. Create a staff or warstaff;
2. Give it elder influence;
3. Add the prefix for socketed endurance or power charge. Upon hovering the item in the list, the error appears.

**Comment by Paliak** [comment]
Fix is on dev. Should be included in next release: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8048
