### ISSUE TITLE
Add Better Support to Explosive Trap (and more traps in general too)

### ISSUE THREAD

**Issue by gabrielsubzero** [PathOfBuildingCommunity/PathOfBuilding#811]
I have been playing a Explosive Trap character this league and it has been a blast, the issue is that PoB doesn't really support it and traps in general, not calculating trap throwing speed or the small explosions from ET especially.

I think it might be possible to add a dropdown like scorching ray or a option in the options to set how many explosions are hitting the enemy. I'm not sure if trap throwing speed is calculated the same way as cast speed, but if so I think it would help theorycrafting traps much more easily.

Also support for multiple trap being throw would also be greatly appreciated, like cluster trap or multi trap, maybe adding a option for the amount of traps hitting the enemy as well in the options would do it.

Thanks for the hard work! Love your updates :)

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5309
