### ISSUE TITLE
Skills that are granted from items should not count towards attribute requirement

### ISSUE THREAD

**Issue by hhat42** [PathOfBuildingCommunity/PathOfBuilding#812]
I have a char with an amulett that grants level 26 vitaltiy skill. A level 26 vitality skill gem would need 180 strength. However, since the skill is granted from an item, it does not require any strength at all. Thus, skills granted from items should not add attributes requirements in the calculation for the required attributes on the "Calcs" screen.

I am running version 1.4.169.2

**Comment by Lothrik** [comment]
Could you provide a PoB? I can't seem to reproduce this error.

![](http://puu.sh/FDNhh/6125acf4ea.png)

![](http://puu.sh/FDNgq/1e5bb85c11.png)

PoB: https://pastebin.com/f4HxTEHp

**Comment by Lothrik** [comment]
Oh, that's strange. The error actually does occur if I import my own PoB:
![](http://puu.sh/FDNlu/7f694d40da.png)

Removing and re-equipping the offending equipment fixes the incorrect attribute requirements, so it seems to be some sort of problem with importing items. Simply reloading the build does not fix it.

**Comment by LocalIdentity** [comment]
Doesnt seem to be an issue anymore
