### ISSUE TITLE
Pob 3.24 Build - Error when trying to open in Pob

### ISSUE THREAD

**Issue by mas0ny1** [PathOfBuildingCommunity/PathOfBuilding#8136]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Pob should load this pob link without any errors
https://pobb.in/gZZjfLkiq6Se

### How does Path of Building behave?

When I click open, the following error appears
![image](https://github.com/user-attachments/assets/8e13976c-c4d1-4df5-9286-a523a648a40e)

### How to reproduce the issue

1. Open up https://pobb.in/gZZjfLkiq6Se in browser
2. Click on "Open"
3. Wait for POB to load and produce the error.

### Character build code

```shell
https://pobb.in/gZZjfLkiq6Se
```

### Screenshots

![image](https://github.com/user-attachments/assets/a1c9b3b7-92e9-405e-b796-51053ce69aa4)

**Comment by Nightblade** [comment]
Can confirm.

Seems to have something to do with having two `Penance Brand of Dissipation` skill gems enabled, as I can load the build if I first edit the xml and delete one of them, or by changing `enabled` to `false` on one of the parent groups.
```xml
<Gem enableGlobal2="true" level="21" gemId="Metadata/Items/Gems/SkillGemPenanceBrand" variantId="PenanceBrandAltX" skillId="MagmaSigilAltX" quality="23" skillPart="2" qualityId="Default" enableGlobal1="true" enabled="true" count="2" nameSpec="Penance Brand of Dissipation"/>

<Gem enableGlobal2="true" level="20" gemId="Metadata/Items/Gems/SkillGemPenanceBrand" variantId="PenanceBrandAltX" skillId="MagmaSigilAltX" quality="23" skillPart="2" qualityId="Default" enableGlobal1="true" enabled="true" count="2" nameSpec="Penance Brand of Dissipation"/>
```

**Comment by Paliak** [comment]
Mostlikely caused by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7678. I'll take a look.

**Comment by mas0ny1** [comment]
@Paliak thank you for your work :)
