### ISSUE TITLE
Large Cluster Jewel won't show the extension passive skill tree that can be allocated.

### ISSUE THREAD

**Issue by waniqra** [PathOfBuildingCommunity/PathOfBuilding#814]
https://pastebin.com/zcP3ewAY

I tried putting in the other medium cluster jewels I have and it works, i can extend the skill points to the tree. But this specific Large Cluster Jewel does not work. Hope this can be look into. Thank you!
![Screenshot (25)](https://user-images.githubusercontent.com/24509835/79813163-6c6ec100-83ad-11ea-9f02-bb998628c91b.png)

**Comment by oafijev** [comment]
@waniqra I had this same problem.  Looks like it will probably be fixed when #820 is released.  I was able to work around this issue by editing the cluster and swapping the order of the Claw and Dagger enchant (implicit) lines so that the Dagger enchant appears first.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
