### ISSUE TITLE
Adding small cluster, throwing a error

### ISSUE THREAD

**Issue by hyultis** [PathOfBuildingCommunity/PathOfBuilding#8142]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Linux - Wine

### How is Path of Building expected to behave?

Not throwing a error when adding small cluster into a medium cluster

### How does Path of Building behave?

When adding a small cluster into a medium, a error is throw, it can lock the build if it's saved after ignoring the error.

### How to reproduce the issue

open the build in pob, go in "item", select "Socket 4#" and put a small cluster into.
(error with both of the small cluster, and in any socket)

### Character build code

```shell
https://pastebin.com/j8tbBET0
```

### Screenshots

![cluster_crash](https://github.com/user-attachments/assets/dd947871-9ac9-4be5-9c0d-470dc8ab1953)

**Comment by KibaddaKaboodle** [comment]
I'm getting the same issue using Windows and the beta branch of PoB.
The error denies me access to my build entirely!
![image](https://github.com/user-attachments/assets/d64b1754-a3da-42a3-9682-da71a39697a3)

**Comment by LocalIdentity** [comment]
You have an impossible small cluster jewel with 2 notables on it. That jewel can't exist in game. Remvove it from the XML file line 542 etc

**Comment by hyultis** [comment]
oh ty.

but the UI allow to to it for information (adding 2 notables)
