### ISSUE TITLE
Issues with newly added spectres Baranite Thaumaturge and Redemption Sentry

### ISSUE THREAD

**Issue by Gaardean** [PathOfBuildingCommunity/PathOfBuilding#815]
The "AtlasExilesCrusaderMageguardProjectile" skill labeled as "Default Attack" for Baranite Thaumaturges in /Data/3_0/Skills/spectre.lua incorrectly has "attack = true" set as a value, causing it to use attack stats instead of its spell stats.  The "Default Attack" label is misleading as well, since it's not an attack, PoE internal labeling for it is "MonsterProjectileSpell."

The "Default Attack" and "Snipe" skills used by Redemption Sentry spectres should get a 200% more damage mod at spectre level 84 (Raise Spectre gem level 26), however the "Default Attack" starts getting the bonus at gem level 20, and the "Snipe" skill doesn't get the bonus until gem level 34.  Checked against Enhanced Vaal Faalen's "Elemental Hit" skill, which should get the same bonus at the same level, but it fails to get the bonus at any gem level at all.  The skill values in /Data/3_0/Skills/spectre.lua are correct, so I'm unsure of where the issue lies.

**Comment by LocalIdentity** [comment]
Fixed the default attack for the Baranite Thaumaturges but am unsure of why the spectre level mods aren't working properly

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.4
