### ISSUE TITLE
Character Import gives error "Response Code: 403"

### ISSUE THREAD

**Issue by OmniDefenestrator** [PathOfBuildingCommunity/PathOfBuilding#8152]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When I click Start import with my account name (or any account name), it should fetch the list of characters.

### How does Path of Building behave?

Character import status: Error retrieving character list, try again (Response code: 403)

### How to reproduce the issue

1. Input a PC account name that you know is public (e.g. one you've used before and/or your own) to Character Import..
2. Press Start

### Character build code

```shell
https://pobb.in/TvZbJXoypNKx
```

### Screenshots

![image](https://github.com/user-attachments/assets/498e8938-912d-480b-9bc7-0d3ea97ea72e)

**Comment by sf754** [comment]
I'm getting the same error. Tried restart, reinstall - no luck. Tried multiple public accounts and same error. Just started happening today, nothing else changed as far as I can tell.

**Comment by crush74** [comment]
Same issue here, seems to be systemic as I tried restarting, flushing IP etc.

**Comment by ejpham** [comment]
Same. Was working an hour ago. Suddenly stopped working. Might be an SSL issue.

**Comment by ggcatu** [comment]
Same

**Comment by aerde** [comment]
Same

**Comment by gstrauss42** [comment]
Same

**Comment by Christoffer-M** [comment]
Same issue

**Comment by dreiki** [comment]
Experiencing the same issue here. I also tried to roll back to [2.47.1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v2.47.1). The issue still presist.

**Comment by ineedanamepls** [comment]
Same here

**Comment by LaDuelo** [comment]
Same here

**Comment by zao** [comment]
We're aware of the problem, can reproduce it and are investigating.

**Comment by Loerf** [comment]
Same for me, a friend of mine can't even import from my account but can from his.

**Comment by pruzsi** [comment]
now work

**Comment by Esoterism** [comment]
same here, does not work at all

**Comment by ZHEkaZHE** [comment]
same

**Comment by Anabolkick** [comment]
Same

**Comment by DamadoHanabusa** [comment]
Same

**Comment by dancrista** [comment]
for me now error changed to 503

**Comment by Nightblade** [comment]
Looks like it's working now.  Was something on GGG's side of things.
