### ISSUE TITLE
Lethal pride - Rage on melee hit

### ISSUE THREAD

**Issue by Morkhe** [PathOfBuildingCommunity/PathOfBuilding#8153]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

-

### What is the wording in Path of Building?

Find a Timeless Jewel tool shows node "Gain 1 rage on melee hit" as "Physical damage taken as fire"
![image](https://github.com/user-attachments/assets/a3d5fbbd-7f5e-43c8-852b-c2f3afafe58e)
![image](https://github.com/user-attachments/assets/a123fb72-0e9c-4a55-bf7a-4744b31c5c3d)

**Comment by feltax** [comment]
hello, I've tracked that cause of this one to GGG reworking the notable but not renaming it.
https://www.pathofexile.com/forum/view-thread/3552862 
Not sure if pob devs want to fix it or wait for ggg to do it, else I would have put in a PR.

**Comment by Regisle** [comment]
see  #8080
