### ISSUE TITLE
Tablet version or Web Based version

### ISSUE THREAD

**Issue by EnricoOS** [PathOfBuildingCommunity/PathOfBuilding#8158]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

I would like a version of POB that is accessible on tablets or mobile devices. Or a web based version. So many times I would be at the office with down time between projects, and wishing I could theorycraft a build or change a build on POB, but I can’t download POB on my work laptop. I always have my iPad with me, so I wish I could POB on it. The other planner websites aren’t that great. 

### Describe the solution you'd like

I am willing to research how to create a tablet/mobile app if there are more people wanting this kind of app. And if there are people who would like to contribute to it. A web based version could also be possible if that would be easier than creating an app.

**Comment by Wires77** [comment]
This kind of work isn't something the core maintainers want to focus on, as we'd rather focus on keeping up with league changes and calculations.  That being said, have you seen https://pob.cool/ ?  It's being worked on at https://github.com/atty303/pob-web and is a decent wrapper for PoB.
