### ISSUE TITLE
Failure to load build list

### ISSUE THREAD

**Issue by KrKlof** [PathOfBuildingCommunity/PathOfBuilding#8159]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Upon launching, Path of Building is suposed to load the list of saved builds from the default build folder

### How does Path of Building behave?

Path of Building gives me an error that I can't quite make sense of before failing to load my build list. It will still save new builds but doesn't display them in the build list. 

### How to reproduce the issue

launch path of building or attempt to return the open build list

### Character build code

```shell
https://pobb.in/78gFJiUu7fs3
```

### Screenshots

![pob sc](https://github.com/user-attachments/assets/874813ed-86eb-4356-a6a6-2b9e15ef1628)

**Comment by Nightblade** [comment]
OneDrive has given us trouble in the past.  You could try opening one of your builds with Notepad first.

**Comment by KrKlof** [comment]
taking advice from both the email i recieved and your comment, switching the default folder to a local one and change the launch app notepad worked. Thank you very much!
