### ISSUE TITLE
DPS preview with Jack the Axe equipped is incorrect (reproducer available)

### ISSUE THREAD

**Issue by theofidry** [PathOfBuildingCommunity/PathOfBuilding#8163]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Not provided.

### What is the value from the calculation in Path of Building?

Multiple available, see bellow.

### How to reproduce the issue

- Import the following character: https://pobb.in/f-BEMx4k_bOa
- Enable the following configurations (in case the import does not do it - this should not really affect the bug, but it is necessary for the numbers described to be accurate):
  - For effective DPS
    - the enemy is moving
    - the enemy is bleeding 
    - the enemy is maimed
  - Enemy Stats 
    - the enemy is a Guardian/Pinnacle Boss
  - When in Combat
    - Frenzy charges
    - Endurance charges
    - Onslaught
 - Check the DPS of the skill Lacerate of Haemorrhage, One Slash
 
With the above, the Total DPS inc. Bleed is 3.46M.

Now, if I create the following custom item:

<details>

<summary>Spirit Butcher Infernal Axe</summary>

```
Item Class: One Hand Axes
Rarity: Rare
Spirit Butcher
Infernal Axe
--------
One Handed Axe
Physical Damage: 177-315 (augmented)
Elemental Damage: 79-120 (augmented)
Critical Strike Chance: 6.30% (augmented)
Attacks per Second: 1.30
Weapon Range: 1.1 metres
--------
Requirements:
Level: 69
Str: 158
Dex: 76
--------
Sockets: R-R 
--------
Item Level: 84
--------
139% increased Physical Damage
Adds 23 to 47 Physical Damage
Adds 79 to 120 Fire Damage
26% increased Critical Strike Chance
12% reduced Enemy Stun Threshold
25% chance to Poison on Hit
--------
Note: ~price 0.8 divine

```

</details>

- On the button "Create", as a stat preview, I get `-644,614.1 Total DPS inc. Bleed (-18.6%)`.
- Click "Create"
- Check the preview of the stats when switching from the current Axe to the new one. The preview shows `+620,023.9 Total DPS inc. Bleed (+17.7).`
- Equip the new axe, the Combined DPS (the stat name changes due to the impale I guess) is 3.42M (so not an improvement).

I think the reason is due to the `Thirst for Blood` skill that may not be taken into account correctly into account when swapping weapon the weapon, but appears to be when creating it. It makes me wonder if the calculation used for the trade links is using the right values.

### Character build code

```shell
https://pobb.in/f-BEMx4k_bOa
```

### Screenshots

![Screenshot 2024-08-12 at 23 14 20](https://github.com/user-attachments/assets/f2839285-9bb8-4fb0-a18e-30d011c1ffa7)

![Screenshot 2024-08-12 at 23 16 27](https://github.com/user-attachments/assets/bc731841-402b-4dd8-884c-d62ef73de32b)

**Comment by marfenij** [comment]
Hi @Paliak  could you check this commit https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/0f522febf3f201a3ad922bc6b71b1566b802a7af
I'd revert locally and full dps diff came back

**Comment by Paliak** [comment]
> Hi @Paliak could you check this commit [0f522fe](https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/0f522febf3f201a3ad922bc6b71b1566b802a7af) I'd revert locally and full dps diff came back

it shows up because the if statement will always result in false. Making it always show up as long as it's calculated. My guess is that the useFullDPS is clobbered somewhere since it's a global.

**Comment by marfenij** [comment]
by docs it should work, but...

original 
![notepad++_NCkCtElvK1](https://github.com/user-attachments/assets/592c1069-055d-4004-a6c6-028c485a1482)


with revert 
![notepad++_pRabD7kFSF](https://github.com/user-attachments/assets/9381134f-6535-4b1e-a7ad-ab38a61eb055)

**Comment by Paliak** [comment]
Removing the if block will have the same effect. This is not the way to fix it.

**Comment by Paliak** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8247 has been merged. This should be fixed in the next release.
