### ISSUE TITLE
Enemy armour for Shaper and Sirus are miscalculated.

### ISSUE THREAD

**Issue by rudradevbasak** [PathOfBuildingCommunity/PathOfBuilding#817]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/a594f1459de77f3b3e055291bfbe472eacfb69e3/Modules/CalcOffence-3_0.lua#L1177

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/a594f1459de77f3b3e055291bfbe472eacfb69e3/Modules/CalcOffence-3_0.lua#L2306

Do not need to multiply by enemyDB:More(nil, "Armour") since calcLib.val(enemyDB, "Armour") already does that. The current code is double dipping on the more multiplier, giving Sirus 64644 armor instead of his correct 32322.

**Comment by LocalIdentity** [comment]
Just submitted a PR to fix this

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
