### ISSUE TITLE
A build i was making is corrupt after update

### ISSUE THREAD

**Issue by jumperz1985** [PathOfBuildingCommunity/PathOfBuilding#8182]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

I was trying to open a build i was working on for the hole day

### How does Path of Building behave?

It gave me an error message i didnt let me enter the build

### How to reproduce the issue

I dont know... it happends everytime i try to enter the build.

### Screenshots

![bug](https://github.com/user-attachments/assets/cd252ba6-1703-4221-807a-3b39daf93cb7)

**Comment by Wires77** [comment]
Will you upload your build's XML file here?

**Comment by jumperz1985** [comment]
Can you guide me on how to do it? is a build i was making from 0

**Comment by Wires77** [comment]
Whereever you save your builds, you'll have a "Fire golem.xml" file there.  You can see where your builds are saved in Options.

**Comment by jumperz1985** [comment]
Here is it. Thank you for the help!

[Fire golem.zip](https://github.com/user-attachments/files/16618741/Fire.golem.zip)
