### ISSUE TITLE
Auto-calculating max. impales on an enemy has broken 

### ISSUE THREAD

**Issue by mg262** [PathOfBuildingCommunity/PathOfBuilding#821]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

On updating to 1.4.169.2, 'Total DPS inc Impale' disappears.

* **What steps will reproduce the bug?**
Open https://pastebin.com/KgbLpYBf

* **Does it reproduce every time? If not, why so?**

Yes.

* **Additional information:**

Overriding the #impales in the Config section bypasses the bug.

**Comment by mg262** [comment]
Guessing it's related to 

https://github.com/PathOfBuildingCommunity/PathOfBuilding/commit/b50f76b4ae32efda0dcb78a567cebd6162e20826

**Comment by LocalIdentity** [comment]
You have your number of Impales set to 0 so it is not calculating any impale damage. To auto calculate the max you need the box to be empty
