### ISSUE TITLE
"# of warcries used recently" configuration option unavailable when taking the Admonisher notable

### ISSUE THREAD

**Issue by DevAir-1** [PathOfBuildingCommunity/PathOfBuilding#8216]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

While tooltip damage is not accurate to know actual values, the fact that it's going up every time I warcry (including from Autoexertion) shows that I'm getting increased damage for it.

### What is the behaviour in Path of Building?

The "# of Warcries Used Recently" option (to configure the damage that Admonisher should give) has disappeared and is appearing in red (saying it's invalid) when importing characters that had already checked it. Removing the existing value makes the line disappear and it is then not available again, even when using the "Show All Configurations" button.
On the other hand, the existing input value is still taken into account as damage goes down when I remove the value, but it won't help when creating new builds or importing an updated charactee into a build that didn't check the option previously.

### How to reproduce the issue

1. Path to the Admonisher Notable
2. Check the Configurations tab to input the number of warcries used recently, and see it's not there
3. (Optional) Click on "Show all Configurations", it's still not available.

### Character build code

```shell
https://pobb.in/eDLsd8NGKH98
```

**Comment by n1tr0xs** [comment]
Seems little bit strange.
Simply changing active skill group helps with this problem.
