### ISSUE TITLE
Account for Statistic Requirements on Items

### ISSUE THREAD

**Issue by livejamie** [PathOfBuildingCommunity/PathOfBuilding#8227]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

It's common for Unarmed builds like Poisonous Concoction or Hollow Palm to intentionally place a high stat requirement item like Mjolnir in their weapon slot or Repentance in their glove slot to level gems and to allow easy weapon swapping. It also prevents you from accidentally equipping a weapon off the ground.

![image](https://github.com/user-attachments/assets/3dc99baa-5335-4cea-8b04-0ff3bab36591)

![image](https://github.com/user-attachments/assets/521d81be-972b-4d8d-a517-462ec15d7aab)

This is perfectly normal behavior. 

It would be nice to get an accurate portrayal of statistics for these builds when importing and viewing them on the ladder.

It's better in the long run for POB to ignore these items if you don't have the stats for them anyway.

### What is the behaviour in Path of Building?

By default, Path of Building enables these items and the gems inside even though you can't use them and it bricks the DPS/EHP calculations on poe.ninja. 

Characters will have 12 auras enabled and 10k dps.

### How to reproduce the issue

Take any unarmed build and equip Mjolnir

### Character build code

```shell
eNrtPWtznMaWn-_8CkpV2S8e2fQbvPbdGr2VWJYsyVacL6kGGg0RA2NgLCu37n_f0w0zAyMYMZKcm-wmqZIZOI_u0-fZ3TRv_ufbJLa-qiyP0uTtFnppb1kq8dMgSq7fbn28PNh2tv7nn4M3Z7IYn4Y7syjWT_45-Mcbc23F6quK3265zpZVyOxaFZ_mpMivQGoqk2Ks0uRE_pZmh2nwdut9mqgty5NJEBXzX34s8_y9nKi3Wxc-IG9ZMvdVEuwu74_MDaAG0GOZSb9Q2TvNezQr0pM0AJBQxjkQm8gouUj9G1UcZulsCn3asr5G6rYEOj45Oz2_rDUsSuoNg479481ZLO9UdlHIwsrhDzAH-chrtScn8BeoyXgGpLjDCHkpmKP_E2zr1VrknVmWF6sUOBX2S-4KhzockS4KF1OlggUSfUnWcDvL1H4YKr-IvqrdLCp2xzLxlxztLrxNYU9mcRFN40hlD8Mf3SON7E7gy7SQ8d7ZxQKW2DZ30UuHC4SpS9fjpcXDzbmKivFODCJ9BBeNe3ydRIV6JPJZGuVp8oT-1VG7R2gWx2CmvWDPVa6yr7KIms3qpp1OvCh5lPROZCJ303w5Rmwd5JnKwOaLBoL9AMKF8lPwGw0eL6lDiejDqp1AJ893Uaj6Q27UnQph09Y8rh_7F33hNib8uAadg5PsB3mRzuKekMXSU2Ekuq3hSx2SItwFuae-Lf2Zg9dRbICyTk08Tpb9EHwNvTogsXl3C7-mhQmnDwnHOJf9o7MFpEsJJi8ZRogIYXfK4Gx8l0e-jE_kt2gym4Cjv5Q3askQYZuwboW9HhcJuKkubMIY6xTrQZSpRyHupnHQhUixcLsd31imeSdLTKnodjFRcgQZz8j3Z5C63C358W5NPA3DjXG0D6jpLhFrUgr_tYY-TvxlOrLWt3xMMhMp6qnIGg4a5RxsXmc_Xqx64yzZVL6jT9JQMrtWScXxrpZivcTrsN4p5Y8PYXzOZVHLTxyIGpQSzgUR3YmZDh1LiyXuWmlr4Lq014ayFmELpx_CfbG9ZIw6NhGO49prY3O7CBFfh9MuQJe8RAi5AmPHdrsFs5-o7PruYhypeNlR4vA-8PN27sppH1QzBnX8XmPRZNgmnV6o7ULqzlBlFvSLkv2gNm35V5n3ChulTEvoujhd1KkxChJvwAhU32LjLEt_0-VMvBnaKJuks2UcRy6h67tRItR7gelDYa8s585VMPMbcZZ3erhFbbYTQ4m60hnuPIgGTY3jVtxOkY-KQvo3e2lw3Vt4hstGGM0GXsymU3BHWi36F346oEMtEtWSue6kfQl8CjpddwHIWRf4Vxg4-GHgVQYMPZjQ9O7GCsa9voi1uUhvNjXoeyzwg0N6Am5jAhHFTEOcpEvPhF92Z4YHUIH2KicNYM-y9iy9hdaP9TxTvhk0pG3LINHZlEwlv9-t0ke9wOsMaHdICCCXA3vozWMVo60fl9EEvGqe78lCWkGV83-SWSSTApvpr1zJzB-_g-E_kHHsgTt4u1W_a36ZKbODKC5Utgf3NFMt3FWKaN7aN6_MDKC-Op5M06yw1Df9z5nMirv5bJwBNHeATl5EiZlnAKcUx1vWxTi9HQVfNafLNI3zxRSenE5VEjRoXGZKWXLuYnzdCNN5_cOayBxafVdqLJD5F3MJYUPsUO7-e_gvhwh7yAjjcE0oQWKIhEsx_MIYEqMhZbb978ac43Fg5Jak0GjQc8YQGmJCBRoi28HukGEihoYsIi7GQw5k3SFnHLgiRF0xdAlHcENwMeQUc6YfUjIkRGA2pBS5aMgcF6MhYYLRIWbCgWvCbGdIXIfra9dxDQVooONgBxpgcz7kCHM8dLENl4RjG_46QBhDXg3kXYEcgwQthWwPmHDmlC0TQ0qIw8xTF-CF6wxdauMh5QwBCEEuhb-6TYgjroVEKYP2MZsADDTBoOIhEcymhqRhpWVrc-EOCdICwoKCQDC1HWgOpfBXY5Ehg1JawB0hKPRfdxbpzmoCICjdwyEIjoBEHRDJEAREKVwjYA79JIafbgEwRYJpUtBgDnAOAyo2jOeQ2tDnobChk-UwQ8pr20PCgRJ1XQEixC50EtkMSDFoIgwWhoFjDhX6NtdjhoEugGsQ6FUpO5CvwI6WMowbsIFnhHKhGQutaEaNoDsUm3EuR54NSzUkIDtkyAAxKmwXlAaUgDiEOsDa0dRtF2khExcEBcIHldSc4BKuYXgQNqz1-GjhUOSAJiDOdMcIh34w0DHQHIeDAFyipYM4tBdRUA7DmuqmgkA4dI6Y4dJN5EMQCGgGIMLAOpqebj8Ih3MKrUAuiBhGEaSIiWks6CoMHKgOcm1QI5CCqz2JntuR2d2oaUJJBFZegOXWFgUwq-b7NYBtjPgfbz6evzMX_xgXxTR__erV7e3ty6ksxmmovkHq99JPJ6-mgATmv53fRHG8rcm-GsF_O9ejHR-fJlfc-XJ5fo6O3x3jz1_Ds3enNzc3Yf7jtcB5sv15-su7q1324wyNT662vx6kUtj0N_drtL999V6d_5JPLoKfgz0Zs8_v6c0suyJukbH80knOd69-yoQf3aR7By7JvspvTO1T-buNt4_Q-HBHfbt0_d-mF-fi0093-5Icvs9_iW7OybX89v5mRk-TM9vLPn9-f8OvT89OTvhVcDz9cefj9U_b4Y2MJrGDf90Jd76cyenJjzP2-_6YeMUZCj98m2bJNzY6__Xk48G7X34--egdotPzn29z78x7f8Y-f_70joTy9KcPP-1-uXp_5sR3-zce-bp3ujfa_Zm9-z1wA9v5xT88vtoLzr98OBlPRiMx-3miMPsp_IDfH4x2fhud-iN5u3c9Ot0f_fJhbzo6PR79cr33ZXR6MuK3INnD_ZH8sBePDv3R5-u9yegw3T84vb3Obz5fja_t8_gg_OD9_nPy7fbtWzOQr-Yj-aZcgsnLYa1-GYeqx93Y4ZYVFWpiXG1Vtd0HNKa6BMS4C9C4mhpF1gWo7ahGkHbBGX9VA7Q7OWtLq3EWXYDGz9YAnS5A41RqrFk3RXCbNUDUDQiepQZIOjujo06tjVXlDgNbH883OovMIgiOZQbySkdhkxLoMK0v3qeFMrD65vzHmwttuTmkGllxqCb5zh1kfQe6Pl5ZVajivIa-UEWZwtRx3m4V2Uzp1CSUs1jf_zCTcaTTDrt-9125OJmk2WQxRwmkIO3QFUpJ8fJuqmP86N278skoLipimt08BylzjapBVhTM84_qpll0HC1bvStjXycOIMnEj2cg26RKiBc5jkr0tFgw70oep9DRnTS4s-al6wpNTa4aNGhZhX8Yp56M8ZxKtRoLimBdlyN4ogoZQGL46hiGNH-l-_Rq2XlTukJSX81jmQRPY1UQx0k-jTJZ1rbG7XY9_DKXP9jJ_IeG3SvHYqvRXDRv7ooM_HSWlKOdyEmV5tW5vOrZfdaz92YyolnLn8WzvE0So1s92wuSuo9yXzJrgb-bpOZcLcPWmvO1Ksavnlt3LrMogba3SWvxaFUyiwffTQpzDs-tK1dKTtNkPzaVcF9tWQHX67_lbEzerTTrcL6_7iy4V2pj3QJ_a96AB4VqOqXLvcoBot5qpRHh6pOU8ac09mUS-QdRns8y1RBw6_OFKFufNoS2aKBp23OKUPO25sytOfdnd1l620VeZNHNw65qCbrGRdWB_gDXVGO3SCx00x6OpWjzWJoWeUsURb2jqN1LZc9S6Y-hvjmR2U1jPJoPFiPQvL2UOXlemVds_gvcVv7fuWW4PXsM0FRPk6OoaFPE2sNV9as9-m5Kp3lYp4mlufTtOO814gcxMNmT-bjR69rdRXdr977bQBselmHypzepfkFgNwaprmQWi3sL2S7ufKnl_s8p2DmD7y3VIxVPVPEkT9VPrkcqk3FwGo5WNLdxfyHfxt3vZqUlFysNrdFCgZ-tw3uqUNmkmnRudHnlyaLTK_e_l2o12Tyvd9qJ0zQYJcGFTIJGn5sPFl1u3v5ePTZcLGBhGT7PPNBHsshUs7fzW0t9rm58rx5W9O95i-ryQhVmhqScA9GXxl8YiONkOisMqbdbkyj3f_VmYaj3K0PzIVnSO7H3Dw72dy-PP-1Xiz51FNPFX5PZxNO7cct_l2tKF8osTlv5zMvLS0hWI3VrGgKKKKM41z2KYznN1WLVxUxyVC2PAW8NNQMFYXZe4rbTWgJ0U9r_prIC-nslMz-LVGe7Fs8faFTJUG970ItkXdT0ruFuQmXxsyvzoty80SEps0e7m4reM93ZHf1wDe7xZCrjTs7V0wckUehpLtDTKIx8vb64fsj1pFgJtUYui41pneNdLf530zDbsLsIlA-7kcut1F3Y1dM1UjXbuDulWj7tRt9Tvuzse_mwG3mxHygtk-B2KguoNZTep4lRcjCaURTr2r1zZKG2X4B0EzwtoGqoVlK7KJ2Aj5qDrDWcLPJmRbcZ1yDWyMrsaeyQkH7WjVrOa3b0QT9b44kaO9M6BFqH6SZV7ubqdGTrUMs9G53yqzaArBmCaiq5Q_zl0zVCmG8E6-h_9XiNkRj_O_qaRkG5DajDXFbA1jmM1L95Ohmzt-npZFY3Oz2dIhRz-U3neFdPu9E_FpHOZ1qolHlLLyLaqJ5GQdvW0yhcQglVzDL1aALnq5nIEvd8fQ6y2JvTijx_us5zVFt2Hk2h3Fj0aHSz7-nR2Mb_QzKsoAdrA8ACZo19FLNkbzZfI3oSKdOsdkey7N1GtMpQ2NrTjSmWBl69EbDOB5QgDxCCWH60JlvsR2mxfe9IyVi_d5bGTyN4782HpxDTm5FnU6gE5-RO23L05Tj0lF5a5EDT7Evb03uenyrDRE3uWgh1t-vNq3lVZ3as6Tqr2md3UWR6m93vaTr5bGpPfVUtUJNqURoy7r0Ixi0z-jbnowF_nu9zfGOq32qFXF8vFsi7CcxyVb59VS5iGYzasramUl_SPjfTXq-t89H5_gDq4HRi_aTUdHCYyXwKummdQMk4KJOH1xZmdnW9I_P5C2hRrF5baFAlCCVQ9aMFyqRRVplHvbbY_E554z78xyT6MlPW8d5rK2ChZATbwvdC4buBJ32bh8QXoeMgJ3Al4kwy5SIlMaKIMj8IJJchk4gSaauB6bsZhdeWwwfVyj802B5UGx5eW1fbV9s72-fw_9XAgJ6rLwBtD6DyiiM_0jB48C8_k2Ghgn9XNKwgVbmVpIWeDcwU9MKaO5IlLIgUsnHrBbKKFB5_K5QWvTVVmYV_sCpKg3-F-n1niIbBv9EPC3JBtSxnmdKzxGFLIoMXjDaoDl4gx_CZlIZs6Tg_eEHoD_qm2SJslQml9rADQn7Qb1rDpX5sPG9tdXBeSAwIvg_mKa0l2vknKlh21qm3vdGI9SA6mzBzKidpcC6Ta2Vl-i9YxEu2VSluNevSCYEfhCAPQtAHIdiDEPxBCPEghPMghPsgBJrvmjazaU03gJtu4OP74w8f9wcnv6UxmOXgUIIF1G1QOVIGUoApCsRs6nEcIKloGISe8AJH-og7vhs6SDoESWK7PhitUFTo_aU2t5s2SLptsG59vGF9pI_1rWyIWKKstylnaYeI_WBl5Y4Zy4QGo-PW5Rjy1HEaB4PLLLq-BhxplQ0HuMUOf8sUC1ZqFqSG5bq6tOyXYLPl9klrF0J0kN4mgy7k3BqD8KFXln7l1YpCq2IIVvaC2LZ1nBQAFl1rLwO2_GUWZcZgBy8wPIUIpJJrYFt_4op671dlhGy7_njZnup5taELnEeUGC8GETwf7KZZNptCB_4aVvtXsEmymU1SoRxGuKeUxxlYZaBkqFxuQyDkwlVIcGR7HvU8FwKi47keYh4SLlwy4YYEN22S_W2TfyKbdN2_TfLPYJK0LVvOoom1o2SQDw5BcazRZBarom6ZXDiIOoHn-TwMQ8I5g6TQsSWnkqqAuZQJz-EOpy6VxIMYKQOOMENC2TbCtly1zJr5OR3mN4rj1JcF2N5o4kXBIh9EjWxrmSciXL-v37Sb69YLinWWJ8FmllO3gxfcXU00sXs_0aTCJJpLha0lm9qKa_YO_-oV4bKEHWD73sNVd_E-Tbb1YkOizLknVmUExjS3hWZrTjgwqaQx1L_zyT_OUFhr7NqNMj9WZuE_uZ5F-XhwPvPurHMYvrq9EI5B9aGCQzRgTHnSxiFWELUwwo4DT7DwmCekTSD9VJ6PA64Up7YtQhsrjFezy6W9IN60F0Qa5lBpvGivjj6nM-tae9jTJI_lDFTaCtPMolXcyKuYokOAxp-7-cEogGfYFGZYNG2LcMPK3KtxAutqu2_djqEctqQxEWgviK6xlWLQ-AWWkEN8rndwZxYuLOxvY1g1hjY95i0O_yBVEPDB4Q8uIxgX6xCuv4JPnM-OUJt2zo7UtNwnMvAV56CxVBCfui4TIeKg5ZC6uQR02yOMQBnFhMMJFxRChmK2pNLDgfR4rxrqcPtwe2d7p2YCAjfnMF4g0fTkrD1CvGBOL4_PSuPRkbCu0Z1TDg0Fnb92XOZ9S1-Pm7mhEe7y6QtE7zXkb_Xe3Ne3GYBoMYAjSCzB8V1mcjo4ifws3dYvD0P0VdkdZEJxI_lRArnMdzjnriNsn4M7h3QopGHIFOgyloK5nu1jLoVkDuQ8MvQExrZyPBlIItYkP6KpyeX6kH6ROI5AS0Aj7sBjm3ygqWWVB9yVSblTttCzpZZBByjwuiEk5xdxCq6ciVWlp06L0jutSq-TrXmdUlKvlmI0v2BAG0q9bhd-ldvUSiXWErf-Vvk-Ht1pzUwO9GwryP5ynOrAng_M1v4TGLPlhLbApPeENiJ2_xltqA5c7tqB6yDJXf2OsYIfKAgDhDD2see4RCLlYEV8KQUkPxIgiRNiXwhBg4aJINtuDwXnZjr7sG5AjVCAlvVuudVV77azrlUB5bED9mNq3f-Sk-l_W7XjA63loZCQ0TeqiEpWZgNgQzwQDUhpMDAGpsy9MK8H1Gjpono5Nx5BWg8lBNwuIOFvlNcrZUQNJ1wW2mvx1xqhnnlAdt0BmGropGb-c5gG1b9Y7d3bKtssym0JEWc6T96_U4PRRBXjO9Cc1SQ_YBAKlOSEKj-Uvh0GDEl9CAFW0nd9zwlI4GKCIKWHsMC4bRNKA8U835FKKNY3LiAYso6EvrbGQtxNfXFLaGhJQ16gMpPX5fOS6rINhk53jfx3sds7GrRpJrJbnf25mupxMHaazXIZgAEfxmk9hxcId69wrrh6SjZw9YFDXRwyhwZcBqENmb2irvD9QELmTynBigWg36Fk0ifKgTzJC7zQ9hxs-17YnAoSNU9fc_Q72_dmaRtlrz1gzSn-xbxOfUYyH6CGa1yUs7Q5V1RKqcXJH2fg-69ATf9EqtiqJKhVSS71-TK6lD6ShRpcQFY51tW4yePqI2q72IHSjficeQiKFoaghsO-6wYuV1hCTHSxa_s-FiokyLOFnrUgkP2iEHPBwqYfa8bu2sSF0_RpC8fwUY_B7Vgli9wSxsUfW-EMBK_TXuiBmUbQA7Q6cWyFWTrRcxa5VejtDJbMyyS2ehzM9Eb0eb6sd6VaOtwCyZUJao24_63IZBu6KtF1Y9pXjXfHunYIVth1wx9k6e_Q2Cb4n9wTrSywnowOj3cH4CamqoABt34EJ1TVCCDdYqys09vmiiuVkiAOyV_Ilc2VGwgbea4UlIaQN3LKqQhcpjyGMPICcDFMYI-EWHoMMxmuW93pDp391Iw21i5KAGt-9OBAT0EtVmvMWOku7s6yXJkpM12kbTCUT7P19jW1syyFtE2H3WW-cs_QFaQhvgf5NwXTJk5ghx7ljhc6tlShHVIe2MgPIU1xXZdjl2ImqE0p5a6Lof5dGQHaNQL2Y0ZAZxlzGc8f67QU6swBbozOfGve4EqTAtNvWunQwqWBm8w2TvO89BGVRZdeItVvAcDYwfDWZj-jBBymDP6wpKF1fOl6M_swi_ybPIp1yxvWBlFMBuCF0uYuB2WDMTElGA19QXDgecJ3mIJCjAUUxtjzmANBXPkOhRAueMCFpL4bcur4HvuuNuessznGW0L0H2Zk7ZP_I53uQoiIrU-RrgsHn6IsCiKox35UtyvbSzgSIgiR67jMD2wJRodB2i5F2vFBeHWkKxHYli1FCLEV-RJisAqQ7yuqPGd1arSR_LxAdjNxhz5GIdSceVUkVBFnvse7WjCeB7o4T80U010TumuzlCULi5VhGPQsyqxP-iC_Z0qJWqXP2yc40syLggCU6SBW-RgKVE_GxX3R2y7l4Mdc5PmUQ8hxfEWwZJ5EtuvbDuXYxh4WoWC2L5SHA4SYp_QsBVLUW5mLAC9XZZSQV-jzvyzzqY_meCyXKo8TgM2jIjXl_2LyTtvnRBb-WGvvpBosHTnqfZKTTYvuVuGJVuHtT8CZpov36ndniU6i1imwRzFyhE88KoXvSo8LrM9i9qh2Jx5loMhK4oD51HERIhAzfOYxASi-40m8ukexmb23T9A3l0zLdxmt-Qtb1rnU79gNyKrXMB9VsS6i3_-4-cNWwbdPy50mytKnoVjv00IP_-Bioivp3XimD3-8L_cw8JAnKFKc2KGAjNyVtu0KxT0cBhClsUAOCTDk4dIBrwJpOFZ-iN3AYRQFvrPqsRuOeaFeVvliqw_leFpATgoiDQFMPynzmXLJ7ygFzb61zmQ8sS6VPzbNfPaZoVZpuq3SvNJGtDweQk_PnGVRDrYV-S2eQDCFAubZMnSpIK6gTsAd8LWekoqy0INkh3LtD0gAuRFosN5RJO1AEEdChduUpWjqMG3b9NmsH3nn1lHauWOUOK3VyW6aQFgsykWBeoXSsqBq3ugdsIYx9UJZO0VTxpyVOZoWWtX5A_8PZg1x-9yM3sQlzRL2UTrV8zPRJE9bPGyIHKR0cQMm7vtCuJCQM0mIresioRTyibR5GAQYApmEclyEYO6YMEQJCwNyL05B-jcD1TQn3nqxaqrraQLxvhynHAzanEmpM17rk17yelcmX9o_1Z-VJLWb0D5iHuYCM5mYzoqqmIXkOSmHv1ywyszhmYNtPfuyduLwP-mucdtrAzuZnIDkLONTBqVQOj018Yk5KReFlNFAIUxsfe6rr5CSnoRqNrD1Nv5QcdtVLoysxx3uCUJ923YCx18dv658ur4nSjtlhOfjd29RDVsAoTffNZ5bMlNl86vNhHmDop4ZMzFpBeta7_KHqIFbNjU2PMmerkuutMfT-lObkl5D3CShFYcqna2vSAx6opKuDZd9CbxYmQJfg1Yuw7K2Zdj_o0slj5sowrjFsvQXj0p_2J1yeh4PGJgUcZFghFKfIIfZNPAxlVwREggvtFUI9RR4TA6ekkmf-y4PQofa_qpBkebSOm1Zbm5odn1FEMYVEFUCWSe48flyCcKryyWNXVJmfrJjE0pjL3Cb1bDOVOH_0zocJg9WfqZK6gqp0ib6i4QQMYntBhT8swPlNeaupFDlSRz6kApC9U2lVA4irhTKUUGohKe3lzvkP1X6leXsU0s_3La39-huCik-ZMc7cZTnD8U0h9vSI75nBx7nkCU7OIDSIiChzb3ACwKqiGQ44H4IhSBYKuGOXvR0JLUdIeywb0xjf62YpvdNLmslM_FbJkFQdsZmtbwlLGjXoTPq-cuxy7fP_mIh0vk7RP4Jt7Xh9jnKnWxWpdlFJqOkGMy_s3Hf2JFn-yzwpRtKBjkpIozB0FKKQuxw4UM49nDAlHDtgBM9nelxxELuei5yie-orgLE-Jimm9xTYDugDTrERr5ZlGTEwVagbvQMjq41tKOU5S94uiNjT8ayUY1kZTWiLR_KYehFVlacGvME8MALjAdHUF2kWeT_p4oLfdB295vLzTO4Y_1SEeCceR_P3-nXrMuDscqF_Npx5vND3DsxSj5W_YT4h1DMoYjWyLvLczn3oVbt-PYHeepdkqv4uBd--Rb4_DXvklq5lFE_kB737bR1cSunqy2hG_RkQegJ0qho4F40zKPjAAisHp5fEivjWu08_Tmzp0iEP4NE-DNIhPeUSHWmf10itWP-N5MIbpUI6tmS6psK9ZbUPrOw2pK2rpTfWmh0Zfn5hZ5daTVY8gyDih8zqE-1ufL00F4jsoH_4U9uAd6YwhLBeRxL8lzyZ8-gDOgZLBw9QzvohpqwBBdP8pKbjH-rRdJnEOAmjSgD56OGvq3_5Kn9x0804c0asPjuyFN0sMy3Hhsdqu_j1J177ZM5PZ17u2dgvZtgvpPTbMLi0zlPagJ_LsVCz-XlcE-hlF9Mqstk-Q2lPjG7_DJTI2YvP9b0oEy7c9yaIBB63KDQJys3ex4r28TYy5fKlwj0saGBPIOHJX2VqPziV0OLlh8B65u5tbg52rMB1ZfE6g2ofVzsCQ1Az6MBj05enlgp1j_DRh9DoKa6iPRt-RKHPEbm7KnB9ZkGjT6XL-a9A5T54lszQC0-AvcctRx5bJzaAE8vj9d1wH2c78XPM4jPFpmfY5qDPq5PNRvsJfya_rPHCf-Z0kv25Aj89BjON_UmS3j-KO9zn2E591l-I0AfHSkDdWGOjbxS-j2NvDxb0pz9aD4dkCZhdF055fJHdQ6kwV_csYqoiFXt4wb1WdP6JwSUPjrpON9J83z5zYGzKEmkHy8-1VRHmOWq9mm-xZm5XprGSiZVnGjB05O5kUYxhzWVp6wHPfD2olxvxdk_OtOvnpwm1UHQG_Kr3i7pgedlMgnMIs9YBZepwd6YnTnBHkS5CaJ-D_Zc6TfG4i6GZ7H0lT7cSmX14Ss_QbD4_oOw7QcQGh-Rn6ORh7AWLw7NP_cwx8SYooc4ZouPAizQ2AM4-o2l1UayB7sGdx7RPs3rEWhm5WaJ4dBu-MnitWa9l1UvvFyYz0voD4pcqDisfb-D9ejjxoJZjN6ZPsJ3Meh9sTYfCK1jqyJ1XN5jIDZqodasVTakj5b05XLhp-YU3_JLjCsfWenkUDbpPI1js_RVt84HMOdxfY7A9RsQ3Th5dB3Fp6E5-xsaaZxx30aufqJ0A81ffCFgwctGdJ0Ux-C2O4T45tUibpUnKZtf_xy8eXUmi_FpaI51Bh385-B_AXYtMjk=
```

**Comment by Regisle** [comment]
> It's better in the long run for POB to ignore these items if you don't have the stats for them anyway.

This has been discussed before and was deemed not a good idea to change, as its very annoying, especially when starting to make builds, to have to set the attributes first to be able to use items, we instead give warnings if you do not meet any stat requirements.

Making this configurable doesnt make sense either, as it would take as much effort to disable them via config, as it does to just remove the items in the first place.

> and it bricks the DPS/EHP calculations on poe.ninja.

This is something you can try and ask rasmuskl to fix for poe ninja, and is unrelated to us

**Comment by livejamie** [comment]
For me and other build creators when making a build from scratch it's common to use the Custom Modifiers section to add stuff like that.

This is from a recent Jungroan video

**Comment by livejamie** [comment]
Thanks for your quick response.

For me and other build creators when making a build from scratch it's common to use the Custom Modifiers section to add stuff like that.

This is from a recent Jungroan video in which he described givving all his new builds 200% all res in the config:

![image](https://github.com/user-attachments/assets/553bcaac-d14f-4b93-b06a-0ed2dd78bf68)

I could see doing +200 all attributes as well or something silly.

This isn't very intuitive for the average user.

It speaks to the different use case of making a build from scratch in Path of Building. I could see there being a benefit to checking a box or clicking a button that allows you to theorycraft without those annoyances you speak of versus the use case of inspecting exsiting builds that need to account for basic things like stats and resistances.

I could see it tying into the Auto/Manual button feature that Lily implemented and see them as similar features.

Thanks for your time and consideration.

**Comment by Regisle** [comment]
A possible solution would be to check items at import time, and to create a new item set that has all invalid items removed, and a skill set that has all skills no longer socketed into an item also removed, but this may be annoying depending on import order

**Comment by Wires77** [comment]
I'm not interested in making build creation more tedious or complicated just for a third party ladder website, even one as integral as PoE Ninja.  In-game restrictions are not PoB restrictions, and we try to make PoB more flexible where we can.

Builds that need to disable these slots should instead just uncheck this option in the game settings:
![image](https://github.com/user-attachments/assets/43a5beea-7f7b-45cf-b068-4cc88878183f)

**Comment by livejamie** [comment]
> I'm not interested in making build creation more tedious or complicated just for a third party ladder website, even one as integral as PoE Ninja. In-game restrictions are not PoB restrictions, and we try to make PoB more flexible where we can.
> 
> Builds that need to disable these slots should instead just uncheck this option in the game settings: ![image](https://private-user-images.githubusercontent.com/1209372/359739312-43a5beea-7f7b-45cf-b068-4cc88878183f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTY1NjEsIm5iZiI6MTcyNDIxNjI2MSwicGF0aCI6Ii8xMjA5MzcyLzM1OTczOTMxMi00M2E1YmVlYS03ZjdiLTQ1Y2YtYjA2OC00Y2M4ODg3ODE4M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDQ1NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA2Nzg2NzhhZTRiYTM5N2ExOTU4OGI0YTI1NWIxODhiYWRiZGM1NDZkYzlkMWY0NTBmM2RjMDFlMzZkZGM5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VLc-cFB4C-i8WOqYQ19hftgF27N48Q_lG-AmUdm5YgY)

The auto equip checkbox is global and not per character, unfortunately. 

The main issue here is that POB is setting incorrect expectations for people planning and viewing builds by calculating items that could potentially be invalid.

It would be disappointing to make a bunch of changes to a build and think you have everything ready to go only to get into game and realize you don't have the correct attributes to equip an item.

I understand that this is done in the interest of convienence, both for the programmers working on POB and for people theorycrafting new builds but it still has the potential to mislead users and it has the lesser side effect of a wacky poeninja ladder.

Regardless, thanks for your time.

**Comment by Wires77** [comment]
This is precisely what the warning system was made for.  Things that we want to allow in PoB, but will break once you're in game.  I was remiss not to highlight it in my previous comment as well
