### ISSUE TITLE
Mjolnir Effective Trigger rate

### ISSUE THREAD

**Issue by ArchanDelon** [PathOfBuildingCommunity/PathOfBuilding#8244]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Not calculated in game

### What is the value from the calculation in Path of Building?

When switching from a Normal Mageblood to a Double Corrupted Mageblood the effective trigger rate of Mjolnir (Ball Lightning of Orbiting) drops from 3.59 down to 2.17.

### How to reproduce the issue

1. Go to Items
2. Go to the Belt Slot
3. Replace the normal Mageblood with the Double Corrupted Mageblood
4. Effective Trigger rate decreases
5. Full Dps decreases

### Character build code

```shell
https://pobb.in/la4cZzkj38PJ
```

### Screenshots

![Mjolnir Trigger Rate](https://github.com/user-attachments/assets/95d15edf-2d67-415d-9a09-4c2d71e9d3d4)

**Comment by Paliak** [comment]
Don't see an issue here. The double corrupted mageblood increases your attack speed past the trigger rate cap causing hits to land while ball lightning is on cooldown. Reducing your effective trigger rate.

**Comment by Paliak** [comment]
I appreciate the high effort screenshot but again i don't see an issue here. Feel free to comment if you disagree or have further questions.
