### ISSUE TITLE
Passive Skill Tree Zoom Slider

### ISSUE THREAD

**Issue by Kazz580** [PathOfBuildingCommunity/PathOfBuilding#8264]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

Unable to zoom in and out of the passive skill tree due to the lack of a scroll wheel on mouse.

### Describe the solution you'd like

A zoom bar similar to what is available in game to zoom in and out of the passive skill tree.

**Comment by zao** [comment]
I'm happy to inform you that PageUp/PageDown also zooms the passive skill tree.

**Comment by Kazz580** [comment]
This is a good alternative/work around thanks
