### ISSUE TITLE
Discussion) Correct DPS for Holy Relic Skills

### ISSUE THREAD

**Issue by nextkaki** [PathOfBuildingCommunity/PathOfBuilding#8297]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

The ‘Holy Relic’ skillgem is currently not measuring the correct DPS.
PoB: https://pobb.in/OqNUqJlH20pk

### Describe the solution you'd like

If you can tell me ‘why?’ you're not measuring in your current PoB and what the issue is, I'd love to help.

### Describe alternatives you've considered

I am an IT programmer. I've never used the Lua language before, but if I can help, I'd love to.

**Comment by Regisle** [comment]
> If you can tell me ‘why?’ you're not measuring in your current PoB and what the issue is

This is what we would like to know, based on lots (5 different builds using the transfigured holy relic, each on atleast 3 different bosses totaling 21 different boss kills) of testing as far as we can tell PoB does have the correct dps (or atleast within some margin of error in the case of poison ramping, or people starting the boss before its DR has fallen off), if you can give us definitive proof that the dps is incorrect it would really help us try and debug it, all I can think of is that some thing of the minion is handled in a ggpk file we do not currently look at (similar to what happened with dancing dervish)

**Comment by Regisle** [comment]
Looking at your build, you only have 1 holy relic configured, and do not have a good triggerrate because its using vaal rain of arrows to trigger instead of stormrain, I would ask Paliak about triggers, but fixing the trigger rate and setting the relics to 3, you should have around 40-41 mil dps, you also dont have an animate guardian properly setup (they dont work well atm, but eg no custom mods or party tab), and you dont have nearby corpse configured, which pushes you up to 42 mil dps

This means you should kill uber shaper from half hp in around 3-4 seconds (2.67 seconds of ramp, dealing a total of around 17 mil damage, and then 2 seconds at max dps of 12.87 mil dps)

**Comment by nextkaki** [comment]
My explanation was inadequate, and I apologise to you first.

The order of the mechanisms in this build.
1. use the ‘Corrupting Fever’ skill for the quiver option to work. The ‘Trigger’ is triggered by the quiver.
2. the ‘Manaforged Arrows Support’ skill on the armour triggers the 2 skills on the armour.
The ‘Storm Rain’ skill and the ‘Blast Rain’ skill.
The two skills are triggered simultaneously.
3. numerous projectiles will ‘attack’.
The ‘trigger condition’ for ‘holy relic’ is ‘attack’.
I think the ‘attack hits’ are around 50.
Example) 50 attacks in 1 second = 0.02 Attack Rate
4. ‘holy relic’ has a trigger cooldown of 0.165 seconds.

Suggestions for correct calculation 1.
In PoB - Calc, Triger should be able to be set to work up to 6 times like in debug1 image.
The rate for 1 skill should appear.
Forced to increase the attack speed very much in Configuration.
ex)8000000% increased Attack Speed
![debug 1](https://github.com/user-attachments/assets/34f2e550-e824-433a-9b0a-5f3be723db24)

**Comment by nextkaki** [comment]
- I would like to check the holy Relic DPS excluding the Agony skill. Presumably, what you are checking is not including Agony.

Q1. I can summon up to 3 holy relics. I can't find where to set 3. Is this reflected in the PoB?
![image](https://github.com/user-attachments/assets/ddc8bf2b-3ef1-47a3-8c51-fd9b52910747)
Above, Right here ??

**Comment by nextkaki** [comment]
![image](https://github.com/user-attachments/assets/5f87e60c-e549-44c1-8582-99bc045960b8)
![image](https://github.com/user-attachments/assets/728c1359-9780-477b-8d85-d54d75038244)
![image](https://github.com/user-attachments/assets/bc119921-ca9e-4e04-92bf-49d938709a8f)
- According to your words, this is the ‘correct resultant DPS’ with these settings.
Is that correct?

**Comment by Nightblade** [comment]
![image](https://github.com/user-attachments/assets/92ef53ea-8150-448e-94ff-d10bad8f105c)
Set "count" to 3

**Comment by Regisle** [comment]
>     * According to your words, this is the ‘correct resultant DPS’ with these settings.
>       Is that correct?
> 
> 
> If this is correct, let's double-check.

Yes I believe that dps is correct for your current build if you can trigger it at that rate
If you believe this value is incorrect compared to ingame, any tests you can run would be helpful


The trigger issues are not related to the relic itself and is a more generalized issue, is known and is mostly a limitation for performance reasons (trigger recursion depth of 1, only 1 skill being the trigger skill)

**Comment by nextkaki** [comment]
> Yes I believe that dps is correct for your current build if you can trigger it at that rate
> If you believe this value is incorrect compared to ingame, any tests you can run would be helpful

I'm comparing to others to see if 8.5 million DPS is correct. I will leave a comment after the comparison.

**Comment by nextkaki** [comment]
**I had many conversations with my acquaintances.
The DPS of the ‘Holy Relic’ in PoB is correct. and we have decided that
We apologise if we have confused you.

I was also confused about the DPS by the options that disappear in the boss pattern, such as ‘Poisoned’ and ‘Atrophy’.
That's why we asked these questions, but in the end, PoB is the correct answer. I think.

Thank you for your help.**
