### ISSUE TITLE
Request for one more digit in the Damage Taken section

### ISSUE THREAD

**Issue by rudradevbasak** [PathOfBuildingCommunity/PathOfBuilding#833]
https://imgur.com/HRT00de

Even glass cannon builds will have ele dmg taken number of 0.25, and tankier builds will have far less, like in the above screenshot.

Thats a super low amount of significant figures, and makes it very hard to evaluate small changes in defences. Going from 0.064 dmg taken to 0.056 dmg taken is a whopping 14% increase in EHP, but both show up as 0.06.

**Comment by QuickStick123** [comment]
This seems to be fixed in current release.
