### ISSUE TITLE
(18-20)% to Chaos Damage over Time Multiplier on Bow and caustic arrow of poison DPS not calculating

### ISSUE THREAD

**Issue by ChristianPyth** [PathOfBuildingCommunity/PathOfBuilding#8345]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

Should increase damage of caustic arrow of poison by bench crafting (18-20)% to Chaos Damage over Time Multiplier on bow

### What is the behaviour in Path of Building?

Not increasing Full DPS of poison of caustic arrow

### How to reproduce the issue

1) Make caustic arrow of poison character and make it full DPS
2) add bow with (18-20)% to Chaos Damage over Time Multiplier
3) No changes with or without

### Character build code

```shell
https://pobb.in/58mE2PlhxqyX
```

**Comment by Regisle** [comment]
Red text is unsupported, its becouse you added the mod wrong, it needs a "+" at the start, hope this helps and good luck with the theory crafting.
![image](https://github.com/user-attachments/assets/fd726ee1-7c4c-4067-9ec8-07a2bfdcce0f)
