### ISSUE TITLE
Can't import account

### ISSUE THREAD

**Issue by ronibranco** [PathOfBuildingCommunity/PathOfBuilding#8354]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

Hi there,

I cant import my account, even using the POESESSID
I've used path of building before, this issue started in the new league "Necro Settlers"

### What is the wording in Path of Building?

![image](https://github.com/user-attachments/assets/c773adaf-4744-45f9-83ab-3517ab0ff16a)
![image](https://github.com/user-attachments/assets/27571930-1520-497d-adc7-8a10e71fe2d9)
![image](https://github.com/user-attachments/assets/40c7feed-7737-4fb6-b734-5b8c4e60a690)
![image](https://github.com/user-attachments/assets/00f36e50-15c9-49ce-b3bd-09337a9b0116)

**Comment by LocalIdentity** [comment]
It sometimes takes some time for GGGs servers to propagate the changed setting. I just tried your account and it works now

**Comment by ronibranco** [comment]
I can see the character in poe.ninja, but I still can't import it. 
Must be something in my end,  just dont know what is
