### ISSUE TITLE
Viper Strike and Total More

### ISSUE THREAD

**Issue by vrtrtr** [PathOfBuildingCommunity/PathOfBuilding#8356]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

In the calc tab, poison total more should correctly add up all sources of +%more damage.

### How does Path of Building behave?

The value seems to be inflated by a magnitude of 10 (?)

### How to reproduce the issue

-Go to calcs 
-skill Viper Strike of the Mamba
-look at total more 
-notice insanely high value 
-check sources
-they dont correspond: it shows 4656%, but the sources only add up to 585%

### Character build code

```shell
https://pobb.in/G2qcRj2TwQYk
```

### Screenshots

![totalmore](https://github.com/user-attachments/assets/9b632c9f-91c9-4798-aba7-fff8814cc2ae)

**Comment by LocalIdentity** [comment]
These are sources of more damages which are multiplied against each other, not summed with each other. 
E.g 3.9 x 1.54 x 1.54 x 1.49 x 1.29 x 1.2 x 1.16 x 1.14 x 1.1 x 1.1 x 1.39
