### ISSUE TITLE
Unable to import build - account privacy settings not active.  Worked three weeks ago.

### ISSUE THREAD

**Issue by darrochb** [PathOfBuildingCommunity/PathOfBuilding#8364]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Previously I would click import build and window would open and I would enter character name and click start. This would lead to additional option like import skills and gems.  This last time I do not get to the options screen.  Red message text says account cannot be accessed because of privacy settings.  Checked account and they are not set. Updated and confirmed update. Tried using POESESSID but that got same red message.   GGG recently did a patch to 3.25 to establish crossover worth POE2.  No idea but maybe this changed something?  Thanks for your attention.

### How does Path of Building behave?

Say Account Profile is Private in red.  Checked account setting and it is not private as far as I can tell.

### How to reproduce the issue

Open POB, try and import build from my account.

### Character build code

```shell
Dont know how to do this.  Running POB 2.49
```

### Screenshots

![image](https://github.com/user-attachments/assets/0ac63ea5-ff58-4d1f-a991-8d9175e61b1c)

**Comment by Nickbinder** [comment]
Confirmed, reproduced following instructions. POB 2.49

**Comment by Wires77** [comment]
What account name are you trying to use?  GGG added a 4 digit number to the end of everyone's account name, so check what yours is now and make sure you're using that.

E.g.: 
<img width="223" alt="image" src="https://github.com/user-attachments/assets/3beec77f-6400-427b-877f-ed7f1528f8ef">

**Comment by xPlasmos** [comment]
I also have the same issue, I tried with including the numbers thats were added after the new patch and it says that account profile is private.

**Comment by trevorash** [comment]
Same issue for me, as xPlasmos described word for word. I will add that I tried three forms of the account name

- The account name without any number (as it was before)
- The account name followed by a # and 4 digit number
- The account name followed by a 4 digit number (no hash)
- Tried PEOSESSID for all combinations above.

**Comment by trevorash** [comment]
https://www.pathofexile.com/account/view-profile/snarsophagus-6909

Note: I may edit/delete this comment after issue determined

**Comment by Wires77** [comment]
@trevorash Just to confirm, you're on PoB version 2.49.0, right?  Your profile imported just fine for me:
![image](https://github.com/user-attachments/assets/436b6227-8383-4ecf-ad87-d1f84d29289d)

**Comment by trevorash** [comment]
I was NOT. That resolved the issue

**Comment by RoooostPOE** [comment]
@Wires77 I am using the latest version 2.49 and I am receiving the error message. Please feel free to try my account. https://www.pathofexile.com/account/view-profile/Roooost-8989

**Comment by Wires77** [comment]
@RoooostPOE Yours is an Xbox account, which should be fixed by this PR: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8365

**Comment by Wires77** [comment]
@RoooostPOE That PR hasn't made it out to a release yet, next PoB update should fix your issue

**Comment by LocalIdentity** [comment]
@RoooostPOE it's now fixed in 2.49.1

**Comment by RoooostPOE** [comment]
@LocalIdentity Working now. Thank you very much!

**Comment by OcularDisease** [comment]
It works now with 2.49.1 version. Everyone make sure you are including the #4 digits at the end of the account name or it doesn't work.

**Comment by darrochb** [comment]
I tried with the #(4-digit number) and got to the import screen.  Looks like GGG appended the 4-digit code with the last patch.  Thanks to everyone for the assist.
