### ISSUE TITLE
Dashes in account names are wrongly replaced with discriminator hashes

### ISSUE THREAD

**Issue by clemenshimmer** [PathOfBuildingCommunity/PathOfBuilding#8369]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

The following (not mine) profile should be importable:

https://www.pathofexile.com/account/view-profile/Dj-Reck1-9507

`Dj-Reck1#9507` is not importable currently.

I think I have identified the issue, and it seems to me this change does not work in all cases, and a more sophisticated approach should be used.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8361/files#diff-9c92f7ea8e0528b99067d974565d47e61b86fb3c1eb98961299b511f9be7fe5bR458

Since I am not a lua dev I'd like to just place this here, and maybe take a shot at it later or tomorrow, else this is up for grabs

### How does Path of Building behave?

Fetch failed, account is private is shown.

![image](https://github.com/user-attachments/assets/bbcf1c05-a292-4c90-9c60-853be1455120)

### How to reproduce the issue

Import Dj-Reck1#9507

**Comment by tarekis** [comment]
OP again (private account). Have an idea on a fix, will try it later. Want to be one of the cool guys that „contributed“ to PoB

**Comment by Wires77** [comment]
Do you know how this account was created?  The account name is not allowed when trying to create that account through pathofexile.com, so I assume this is a console or Steam account that got migrated over

**Comment by tarekis** [comment]
Correct, it‘s a migrated PS5 account.
