### ISSUE TITLE
Parsing error on mod :  Bleeding cannot be inflicted on you

### ISSUE THREAD

**Issue by Marco000001** [PathOfBuildingCommunity/PathOfBuilding#837]
The unique items:

- Death's Door Crusader Boots
- Craiceann's Carapace Golden Plate

have the mod: 

- Bleeding cannot be inflicted on you

This mod doesn't work when copy-pasting from trade/game. The current implementation for this mod on pob created items is:

- You are Immune to Bleeding (Death's Door)
- Cannot be inflicted with Bleeding (Craiceann's Carapace)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
