### ISSUE TITLE
Account Private

### ISSUE THREAD

**Issue by MajikalDischarge** [PathOfBuildingCommunity/PathOfBuilding#8373]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

MacOS

### How is Path of Building expected to behave?

In this aspect I should be able to type in my PSN and then load a list of my characters and select one to then look at my job

### How does Path of Building behave?

When I type in any name on psn it says that the profile is set to private, no my account isn't private I went to the settings on poe website and triple checked

### How to reproduce the issue

Type in Kyng_Kenpachi, TM_ROOKIE, or Necralosa in the username area and it should say we are both private

### Character build code

```shell
N/A
```

### Screenshots

N/A

**Comment by LocalIdentity** [comment]
you need to add the e.g.`#1234` numbers on the end of your name. GGG just updated all accounts to use this new format so PoB needs that too

**Comment by MajikalDischarge** [comment]
Thank you

**Comment by MajikalDischarge** [comment]
nope still same issue
<img width="1728" alt="Screenshot 2024-11-25 at 5 20 41 PM" src="https://github.com/user-attachments/assets/06bd621a-0851-4267-b709-be5272b3d68d">
<img width="1728" alt="Screenshot 2024-11-25 at 5 20 45 PM" src="https://github.com/user-attachments/assets/d51c3522-0bf4-498f-b53e-f44e2043c4aa">

**Comment by LocalIdentity** [comment]
Can you link your poe account here so I can test when I get home
