### ISSUE TITLE
Cannot login - Account private error

### ISSUE THREAD

**Issue by Krisanai-Hong** [PathOfBuildingCommunity/PathOfBuilding#8374]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

I have set all settings to public so I should be able to login as normal.

### How does Path of Building behave?

It keeps giving error saying my account is set to private.
I think the error is because me account name has a - in it. 
Some of the players are saying it.

### How to reproduce the issue

Just login with any account that has a - in it.

**Comment by Nightblade** [comment]
Please provide the account name(s) have you tried.

**Comment by Regisle** [comment]
If I understand the issue correctly its fixed by #8370, which will be in the next release.

**Comment by Krisanai-Hong** [comment]
Hi Nighty,
The issue has not been fixed. I found out that I had two accounts using the
same email so I tried to combine the account in case all the characters can
be under Krisanai1980#7397 which will solve the problem. (I thought this
was solve the problem because the account name does not have - in it)
However the characters are still on the separate accounts.

Currently all my characters are on the below account which is unable to
load in POB because of -
Krisanai-hong#9676

I don't know which way is easier is it possible to transfer all the
characters into Krisanai1980#7397? Or just rename old account to the
account with all the characters in it. Kindly advise.

Best Regards,
Kris

**Comment by Nightblade** [comment]
As Regisle mentioned, the issue should be fixed in the next release of PoB.

In the mean time, you can try using this account name as a work-around:  `Krisanai%2Dhong#9676`.

**Comment by Krisanai-Hong** [comment]
Hi,
I tried to work around code and still didn't work. Able to load up the
characters but when importing passive tree and items it gave an irre
response code of 403
Thanks
Kris

**Comment by LocalIdentity** [comment]
@Krisanai-Hong I just pushed the update that fixes this issue for your account

**Comment by Krisanai-Hong** [comment]
Great! Thanks. It's working now
Krisanai Luesukprasert
Mob: +66 (89) 7947373
email: ***@***.***
