### ISSUE TITLE
Import Build "Missing discriminator" error

### ISSUE THREAD

**Issue by tasadar** [PathOfBuildingCommunity/PathOfBuilding#8381]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Import character should be possible with valid name

### How does Path of Building behave?

When open an import tab error already there, and any fields changes didnt do anything

### How to reproduce the issue

1. Open the application 2. click "Import/Export Build" button 3. Try to import character

It starts after im updating old version. I dont know previous version, but i didnt update PoB atleast for a month or two. I tried to delete settings file from user/Documents/settings after it hapens. Fields is empty now, but still have an error

### Screenshots

![Path of Building Error](https://github.com/user-attachments/assets/98a37cd9-d628-44ca-bbd1-c00bb2a337e8)

**Comment by n1tr0xs** [comment]
When Path of Exile 2 was released GGG added to your login discriminator.
For example: my login was `n1tr0xs`, now this is `n1tr0xs#6429`.
So just check out your _new_ login on site.

**Comment by n1tr0xs** [comment]
Not sure if I get you, but maybe this will solve issue.
When Path of Exile 2 was released GGG added to your login discriminator.
For example: my nickname was `n1tr0xs`, now this is `n1tr0xs#6429`.
So just check your new login on `pathofexile.com`
