### ISSUE TITLE
Unable to import character: "Account profile is private"

### ISSUE THREAD

**Issue by Cyinthia** [PathOfBuildingCommunity/PathOfBuilding#8382]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

I enter my account name VK479#3687 it loads my account and lets me load a character.

### How does Path of Building behave?

It says my account is private when it is not.
![image](https://github.com/user-attachments/assets/cf393883-0426-466a-8a81-55b37c7e0c3f)
![image](https://github.com/user-attachments/assets/19f57c27-548b-4f86-a828-e3d78758c285)

### How to reproduce the issue

1. Entered account name
2. Pressed start
3. Got error
4. Tried poesessid
5. Still has error

**Comment by NagualBaz** [comment]
I got the same problem from yesterday.

**Comment by infidel007** [comment]
I'm also having this issue.

**Comment by Aziz891** [comment]
I am having the same problem too

**Comment by mitkabraun** [comment]
Same

**Comment by risu82** [comment]
Same here, entering the session ID didn't help either.

**Comment by 9564519** [comment]
+1 same problem.

**Comment by thieman** [comment]
Is there any way to capture the HTTP log from the requests PoB is trying to make? Guessing that might make for a more helpful report here

**Comment by timeshifter** [comment]
It's definitely not a PoB issue, there are all kinds of sporadic website issues. Trade site is up and down at random, I couldn't even load my filter list at one point. This is all on GGG.

**Comment by thieman** [comment]
I agree that something seems to have changed on the server-side, but that doesn't necessarily mean we can't fix it from the client. Would be good to see the error we're getting back if possible.

**Comment by ReinerBforartists** [comment]
Older versions that has worked before to me also throws the error. So it's no bug at the POB end. I checked my profile, but my account is still public, like it was since many years. So i guess GGG is pulling the plug here because of POE 2. Maybe Cloudflare is the guilty one.

**Comment by namaedesu** [comment]
I captured some attempts in wireshark and other than a ton of out of order ACKs on most of the attempts, it's ending with an TLS Alert/FIN. So PoB would need to dump the 403 payload to see if it actually says what is wrong or not (the RFC doesn't state it must). 

The 403 is serviced here:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/5dc8ca4ed85ae5a17b018bd1801340a83b1edd09/src/Classes/ImportTab.lua#L433

**Comment by thieman** [comment]
I was having this issue but an import worked for me just now, is it fixed for everyone else as well?

**Comment by namaedesu** [comment]
It enumerated my account, so it's fixed for me, too.  Probably a GGG stored procedure call going off in the weeds causing downstream lockouts.  I noticed that I kept getting constant cloudflare human verify screens going between different parts of my account on the web interface as well.

**Comment by ReinerBforartists** [comment]
I can confirm, it is working again. So it was a hiccup at Path of Exile end.

**Comment by ZdDroid** [comment]
GGG uses the CDN acceleration service provided by cloudflare for the website. The CND will perform human-machine authentication for non-browser access, and the error comes from this

**Comment by LocalIdentity** [comment]
Error was caused on GGGs end
