### ISSUE TITLE
Possible aura snapshotting in POB

### ISSUE THREAD

**Issue by razmyr** [PathOfBuildingCommunity/PathOfBuilding#841]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
I noticed that deleting a level 20 pride and adding it again to a POB was causing DPS numbers to change.
* **What were you trying to do?**
Someone on reddit was attempting to recreate a POB but was unable to reproduce the DPS numbers from a linked POB.
* **What steps will reproduce the bug?**
The bug is able to be reproduced using this POB https://pastebin.com/Y4RQcYHk and deleting the gem and adding it again. I was not the creator of the original pastebin link so I am unable to produce the setup that happened prior to being linked this pastebin.
* **Does it reproduce every time? If not, why so?**
Yes the change in DPS does happen every time while using the initial pastebin linked. https://pastebin.com/Y4RQcYHk I am not able to recreate the issue in other builds. 
* **Additional information:**

**Comment by LocalIdentity** [comment]
This isn't a bug with PoB. You can set the effect of the Pride Aura in the main skill selection dropdown box when you select the Pride gem. The Pastebin you linked had the aura effect set to maximum and when you delete the gem then re-add it, it will default back to initial effect
