### ISSUE TITLE
Incorrect energy shield calculated

### ISSUE THREAD

**Issue by orcasauce** [PathOfBuildingCommunity/PathOfBuilding#842]
Thank you for reporting an issue.

* **What happened?**

Clean import of my character, enabled cluster jewels, corrected activated auras (this was hand verified twice, then the entire process repeated again with another fresh import to duplicate the incorrect values).

* **What steps will reproduce the bug?**

https://pastebin.com/5htpJPbB import this build
Ensure Aspect of Avian is disabled
There are two Haste gems, the Vaal Haste's Haste effect should be disabled
Purity of Lightning should be enabled and Vaal Purity of Lightning disabled

Total Mana is 1242, reserved 1184, unreserved 58. These values are correct in PoB.

PoB Energy Shield is calculated as 7344
Actual in game Energy Shield is 7260

* **Does it reproduce every time? If not, why so?**

Yes.

* **Additional information:**

The only thing I can think of is some inconsistency with how quality on rings is affecting the %es. In PoB ring quality is not shown, only the final improved values. Perhaps the increased energy shield from catalyst is _not_ being affected by sources of increased energy shield in game and is double dipping on that increase in Path of Building?

**Comment by LocalIdentity** [comment]
It's almost impossible for me to be able to figure this out without being able to look at your character profile and/or doing some in-game testing. It's not directly related to increased energy shield as far as I can see and my guess is that it is something to do with the increased aura effect of Discipline or some other flat energy shield in your build

**Comment by ppoelzl** [comment]
Manually calculating your total ES value, I get the same result as PoB. As your character changed, there is no way for us to verify that your PoB build accurately represents your character.

**Comment by orcasauce** [comment]
For what it is worth I listed what was calculated by PoB in the linked pastebin and what the game actually showed at the time. Regardless, mechanics related to this build changed and updated versions of PoB would calculate a different value anyway.
