### ISSUE TITLE
Combustion+Elemental Focus - Incorrect DPS

### ISSUE THREAD

**Issue by anntari** [PathOfBuildingCommunity/PathOfBuilding#853]
What:
When a skill is supported by both Combustion and Elemental Focus with "Is enemy ignited" checked(the ignite being from a different source without Combustion), the -19% fire resistance is still applied to the effective DPS mod even although it cannot inflict ignites.

Reproduce:
1) Pick up Avatar of Fire on any character
2) Add any spell(I used Blade Vortex), add both Combustion and elemental focus to it
3) Check off 'Is enemy ignited'*

-Look at the Effective DPS mod on the Calcs page, Combustion is applying it's fire res penalty.

*The ignites were from a different source, in my case a CWDT Firestorm+Eye of Innocence loop.
I can easily add Combustion to the Firestorm to get the Fire Resistance Penalty on Blade Vortex(or whatever spell I'm using) despite the elemental focus support, but PoB is incorrect in what support gems give the most damage for Blade Vortex(or whatever spell is used) due to the bug.

Build Link: https://pastebin.com/DRTgenFr

**Comment by tobsecret** [comment]
This is still a problem and also applies to the new Flame Surge which no longer can ignite, leading to lots of players using Combustion Support as a dead link in Arcanist Brand - Flame Surge - Combustion - Flammability.
