### ISSUE TITLE
Numbing Elixir not affected by a hybrid flask

### ISSUE THREAD

**Issue by wolfie-poe** [PathOfBuildingCommunity/PathOfBuilding#858]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
The +3% phys reduction of Numbing Elixir (life/mana medium cluster jewel) is not activated when the hybrid flask is ticked.

* **What were you trying to do?**
Adjusting my build.

* **What steps will reproduce the bug?**
Spec out on Pathfinder tree. Put the large cluster jewel on the socket on the 3:00 of the tree.
Large cluster (8 points): +2 socket, Wicked Pall, Unholy Grace, Touch of Cruelty. Enable them.
Medium cluster (4 or 5 points): +1 socket, Numbing Elixir, Distilled perfection. Enable them.

Get a hallowed hybrid flask -> activate it --> Cannot get +3% phys damage reduction from the Numbing Elixir.

Since a hybrid flask also regenerates life, it should activate Numbing Elixir.

* **Does it reproduce every time? If not, why so?**
Yes.

* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
