### ISSUE TITLE
Reduced flask charges crash

### ISSUE THREAD

**Issue by abyxcos** [PathOfBuildingCommunity/PathOfBuilding#859]
I believe this is related to issue #628. On flasks like Dying Sun where charges can go below `0% increased charges used`, they are instead being written out as `1%%% reduced charges used`. This looks like the code interprets the extra percents as new stat lines. Easiest way to reproduce is to set the charges on a Dying Sun below 0%, then change the area slider.

Build 1.4.169.2

**Comment by norepro** [comment]
This is fixed by 1a621871420e903636b7971439a35f4b2805771e and should be in the next release.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
