### ISSUE TITLE
Import build via character name -  spurious drop down issue

### ISSUE THREAD

**Issue by surio** [PathOfBuildingCommunity/PathOfBuilding#861]
Thank you for reporting an issue.

Running 1.4.169.2 

Please try to fill in as much of the template below as you're able.
When attempting to import a specific build from a character name, the UI adds an additional drop down that only contains those builds that were previously extracted as part of the non-forked PoB build. This interferes with the lookup functionality. In the end, we have to run the original PoB to extract a specific build, then save it, then re-open with the fork to take advantage of the new features. Attaching both screenshots to highlight the UI dropbox that causes the issue.

How to replicate:
1. Click "import/export build"
2. Add a new character name that is not already in your application memory.
3. The UI box will prevent you from querying the POE website and returning with all the builds of that character.
4. Ideally, the dropbox on the side should not be used while originally querying the character name. After the list of builds is returned from the character, the dropbox, containing the character name (selected and in focus) can be displayed.

** If you receive an error or experience graphical bugs, include a screenshot.
Screenshots are attached.

![PoB-fork-import](https://user-images.githubusercontent.com/4346901/80691764-5324ed80-8aee-11ea-8bfb-a7d49a13b74f.png)
![PoB-import](https://user-images.githubusercontent.com/4346901/80691769-54561a80-8aee-11ea-9dde-1f239a09f662.png)

**Comment by ppoelzl** [comment]
If this issue still persists, installing one of our own releases should fix it.
