### ISSUE TITLE
Virulence Stacks for Herald of Agony is hard capped at 40

### ISSUE THREAD

**Issue by banang** [PathOfBuildingCommunity/PathOfBuilding#862]
**Is your feature request related to a problem? Please describe.**
WIth the new Herald Cluster Notables you can increase your maximum Virulence Stacks. In PoB however you can enter numbers above 40, but it won't change anything in the damage calculation.

**Describe the solution you'd like**
Remove the hard cap on Virulence stacks, allowing any numbers entered

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.6
