### ISSUE TITLE
Bug with "awakened supports only" option on skills page

### ISSUE THREAD

**Issue by worldendDominator** [PathOfBuildingCommunity/PathOfBuilding#863]
I'm running version 1.4.169.2.

![PoB bug report](https://user-images.githubusercontent.com/6707627/80738007-cb5ed380-8b2d-11ea-8a69-def26b6591a7.png)

(1) I have a gem setup on skills page.
(2) I turn on "Show support gems: Awakened" and click one of my non-awakened support gems. A dropdown menu appears.
(3) I close the dropdown menu by pressing Esc. The support internally (but not visibly) changes to the first awakened support in the list, and its level visibly changes to awakened gems' default level.
(4) After switching to another skill and back, that support's name updates.

If in part (3) I close the dropdown menu by clicking elsewhere, support name updates immediately instead.

Either way, it's not desired behavior. If I close the menu, I don't want any changes to happen.

It also works the other way around, changing awakened supports to non-awakened if the switch is set to "non-awakened only".

**Comment by Wires77** [comment]
Fixed by #4633
