### ISSUE TITLE
Cluster jewels and alternate trees

### ISSUE THREAD

**Issue by worldendDominator** [PathOfBuildingCommunity/PathOfBuilding#864]
I'm running version 1.4.169.2.

![PoB bug report 2](https://user-images.githubusercontent.com/6707627/80741157-9f921c80-8b32-11ea-89ef-bf83291572b3.png)

I have a cluster jewel in a socket.
I create a new tree and allocate that jewel socket.
The jewel appears in the socket (visually, and I can hover to see its stats), but its added cluster doesn't.
I have to go to items page, unsocket that jewel and socket it again to make the cluster appear.

**Comment by tbraun89** [comment]
Same bug for me with the following jewel:

![cluster_jewel_bug](https://user-images.githubusercontent.com/1345378/80864723-bfd1f080-8c84-11ea-8e0a-5c417daa79ea.png)

It's working with other jeweles in the same tree.

> I have to go to items page, unsocket that jewel and socket it again to make the cluster appear.

This does also not work for me. There is no way I can make the cluste rappear.

**Comment by egorchern** [comment]
same bug for me:
![image](https://user-images.githubusercontent.com/46675707/80929120-775c2500-8da1-11ea-8afe-1d667079bd47.png)

![image](https://user-images.githubusercontent.com/46675707/80929130-83e07d80-8da1-11ea-9c58-6d8664517b66.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
