### ISSUE TITLE
Increasing Berserk Gem Quality does not increase attack damage

### ISSUE THREAD

**Issue by Maldini999** [PathOfBuildingCommunity/PathOfBuilding#869]
.* **What happened?**

Using Berserk gem in the skills section:  Adding levels works correctly.  Adding quality seems to do nothing.

According to Wiki, quality should be 1% attack damage per 1% quality
https://pathofexile.gamepedia.com/Berserk

**Comment by dclamage** [comment]
What version are you on? It is working properly for me on 1.4.169.2

Without quality:
![image](https://user-images.githubusercontent.com/10701249/80913840-88068f80-8cfc-11ea-879a-3f4e4b696ce1.png)

With quality:
![image](https://user-images.githubusercontent.com/10701249/80913849-99e83280-8cfc-11ea-886d-0df48902e0f6.png)

**Comment by Maldini999** [comment]
I am on the same version.  I was not talking about the GEM text itself, I was talking about the DPS calculation.  

Look at these two images.  One is with 0% quality and one is with 25% quality.  The DPS numbers are identical.  Usually when one changes a quality related to damage on POB, you can watch the DPS numbers tick up.

![Screenshot (41)](https://user-images.githubusercontent.com/59538941/80919347-61197f00-8d37-11ea-83a1-bfa5c7736401.png)

![Screenshot (42)](https://user-images.githubusercontent.com/59538941/80919349-65459c80-8d37-11ea-8cec-30bd9f16ddb0.png)

**Comment by dclamage** [comment]
Thanks for the additional details. A fix will be in a future release.

**Comment by Maldini999** [comment]
fantastic!  Thanks for looking into this.

**Comment by dclamage** [comment]
We'll close the issue once the fix is released. Thanks!

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
