### ISSUE TITLE
Transcendent Flesh Crit Multi is wrong .

### ISSUE THREAD

**Issue by Kerkrom** [PathOfBuildingCommunity/PathOfBuilding#876]
templar jewel socket as example. it should give 49%(7X7 from 70STR) when you travel past it on the outside. it says 70STR in radius when you mouse over the jewel. but it adds 55% crit mult

**Comment by ppoelzl** [comment]
@Kerkrom Please fill out the issue template, and most importantly provide a build code.

**Comment by Kerkrom** [comment]
seems like it affects all my crit multiplier numbers of my build. everything gives more than it should . i am trying to find out why
