### ISSUE TITLE
Incorrect number of totems

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#878]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
The active totem limit in the calcs tab doesn't take into account extra Siege Ballista totems from Iron Commander. The breakdown does list them correctly, however.
* **What were you trying to do?**
Get number of active totems.
* **What steps will reproduce the bug?**
Have Siege Ballista as main skill, Iron Commander equipped and >= 200 Dexterity.

* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.
Build link: https://pastebin.com/K6hgG5XW
Graphical representation: https://media.discordapp.net/attachments/175290321695932416/706536483758014524/unknown.png

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
