### ISSUE TITLE
Bone Barrier isn't working

### ISSUE THREAD

**Issue by EThaNol2005** [PathOfBuildingCommunity/PathOfBuilding#88]
Hey, so i was wondering that my res wasn't cappedin PoB. Also Bone Armour will not added to the skills.
![image](https://user-images.githubusercontent.com/6765072/71559722-11ae0400-2a62-11ea-82df-4c7faed61b7f.png)

greeting etha

**Comment by LocalIdentity** [comment]
Added support for the physical damage reduction, resistances and recovery rates. Still need to add Bone Armour but that requires a fair bit more work

**Comment by ppoelzl** [comment]
Added full support in 1.4.170.19.
