### ISSUE TITLE
Awakened Generosity not increasing the supported aura gem levels

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#884]
Awakened Generosity support is not adding the intended level (+1) to supported auras. The gem gets 0.05 per 1% quality to supported gems, meaning at 20 quality it should add a level.

Doesn't matter which helmet I choose as the base or how I setup my links and socket colours - "it won't budge".

![generosity](https://user-images.githubusercontent.com/47370800/81441927-ed320900-9172-11ea-9665-7b7562b595c1.PNG)

Couldn't find a bug report on this; is this a known issue?

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
