### ISSUE TITLE
Feature Request: Tabular list of most effective next-step nodes

### ISSUE THREAD

**Issue by anthonyclarka2** [PathOfBuildingCommunity/PathOfBuilding#887]
My build is mostly complete at level 91. The next couple of levels I'm at a loss to choose, and thus enabled the "Show Node Power" checkbox. However the different shades of red or blue are difficult to distinguish between.

I'd like to see a table with the "most powerful nodes I can choose next" listed. An added bonus would be to sort the table based on different columns I can add or remove.

Example table for my Cyclone/Impale Champion:

Node Name | Combined DPS | Total Life
------------ | ------------- | -----------
Crimson Dance | 45,486.2 | 0
Physical Attack Damage and Life | 20,375.4 | 40
Melee Damage | 17,742.1 | 0
Beef | 10,205.2 | 49

**Comment by ppoelzl** [comment]
While not exactly as you requested, there are improvements made in 1.4.170.3 that allow you to see the best next node based on the node power criteria you choose, as well as a per-point effectiveness heatmap.
