### ISSUE TITLE
Projectile Travel Distance setting for minions (Point Blank support)

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#888]
I would like to request the same window players get for Projectile Travel Distance once Point Blank is allocated or support used.

There are multiple commonly used spectres that are projectile-based (e.g. Redemption Sentries), which also do benefit from Point Blank support. Unfortunately, unless we add the "30% more damage" as a mod somewhere on an item, the Point Blank part of the support gem will not be calculated.

**Comment by ppoelzl** [comment]
Do you have any source which states that Point Blank interacts with minions?

**Comment by ppoelzl** [comment]
Closed due to inactivity.
