### ISSUE TITLE
Craft prefix missing: #% increased Spell Damage, Gain #% of Non-Chaos Damage as extra Chaos Damage

### ISSUE THREAD

**Issue by zjcheah** [PathOfBuildingCommunity/PathOfBuilding#892]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Prefix missing in mods selectable while crafting
* **What were you trying to do?**
Craft Wand
* **What steps will reproduce the bug?**
Craft wand look for #% increased Spell Damage, Gain #% of Non-Chaos Damage as extra Chaos Damage
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by LocalIdentity** [comment]
The mod is in the crafter section as has always been there
