### ISSUE TITLE
Ngamahu, Flame's Advance

### ISSUE THREAD

**Issue by DragooNick** [PathOfBuildingCommunity/PathOfBuilding#896]
The every 10s gain 100% Phy Dmg as Extra Fire Dmg for 4s does not get calculated.
If I'm not totally wrong it could be calculated as 40% Phys as Extra Fire since the 100% are up 40% of the time.

**Comment by ppoelzl** [comment]
This is a supported mod, You can easily tell this as it is in blue, compared to unsupported mods which are in red. You can enable this buff with a config option. Calculating the average is wrong, since it would give wrong damage values in respect to ailments and stun.

**Comment by DragooNick** [comment]
As it is not enabled by default and hidden when not allocated I got confused. Thanks and sorry to bother.
