### ISSUE TITLE
Bleed Duration has no effect

### ISSUE THREAD

**Issue by mithlug** [PathOfBuildingCommunity/PathOfBuilding#901]
Version 1.4.169.2

Bleed damage doesn't seem to account for Bleed duration. A bleed stack that is on an enemy a shorter amount of time will deal all it's damage over a shorter amount of time compared to one with an increased duration.
Example: 1000 Dmg (fixed damage, just interested in comparing duration)
Long duration: 10s
Short Duration: 5s
1000/10<1000/5, duration should matter for Bleed damage (Not sure how it should be accounted for with DPS in mind)

**Comment by AdmiralChopper** [comment]
Bleeding doesn't work like ignite where you have "total damage that will be dealt over duration", instead it has a base damage per second applied, that will be dealt throughout the duration, thus decreasing duration won't actually increase DPS, just decrease total damage applied by a single instance of bleed.

**Comment by mithlug** [comment]
Yeah, I realized that Bleed DPS works differently and therefore don't mention it. You say:
"just decrease total damage applied by a single instance of bleed." And when I change the bleed duration nothing changes in any calculation. This is my point, that changing the bleed duration should somehow reflect that something has changed. Sure, bleed works in complicated ways. But when I change the bleed duration I want to know how that effects my damage. And that doesn't seem to be the case right now. Unless I'm missing something.

**Comment by pikzen** [comment]
The longest period for which PoB calculates damage is over a second. Since bleed damage is always expressed as damage dealt per second, you will never be able to see a difference, even if you make it last.

To see a difference in numbers, we'd need to implement a "Total damage per bleed" recap item, in which case bleed duration would actually show a difference.

**Comment by Nostrademous** [comment]
Fixed at some point. I see this in our code:
```
				globalOutput.BleedDuration = durationBase * durationMod / rateMod * debuffDurationMult
				globalOutput.BleedDamage = output.BaseBleedDPS * globalOutput.BleedDuration```
