### ISSUE TITLE
Skin of the Lords is missing a keystone

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#902]
* **What happened?**
There is no Mortal Conviction keystone mod available for Skin of the Lords.
* **What were you trying to do?**
Craft a Skin of the Loyal with the Mortal Conviction keystone.
* **What steps will reproduce the bug?**
Try crafting a Skin of the Loyal with the Mortal Conviction keystone.
* **Does it reproduce every time? If not, why so?**
Yes.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
