### ISSUE TITLE
Negative Physical damage reduction does not affect dps

### ISSUE THREAD

**Issue by shagour18** [PathOfBuildingCommunity/PathOfBuilding#91]
Increasing the damage reduction does affect the dps but reducing it does nothing.

**Comment by LocalIdentity** [comment]
PoB currently does not contain the armour values for certain mobs, which is why the negative physical damage reduction does not currently affect your dps

**Comment by ppoelzl** [comment]
"Enemies have -x% to Total Physical Damage Reduction against your Hits" does not work like  penetration and therefore cannot reduce enemy physical damage reduction below zero.
This is intended, see the  [Metamorph balance manifesto](https://www.pathofexile.com/forum/view-thread/2686983), section "Monster Resistances, Armour and Life".

In the "Configuration" tab, you can select the "Armoured" map mod. This will correctly reduce physical DPS and "Enemies have -x% to Total Physical Damage Reduction against your Hits" will correctly increase your DPS, up to 0% Total Physical Damage Reduction.

It's true that armour values are not implemented yet, but that has nothing to do with negative physical damage reduction, which is working fine.
I suggest you to change the title of this issue to something like "Add support for armour values on enemies".

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1
