### ISSUE TITLE
Ability to Allocate Single Unconnected Nodes

### ISSUE THREAD

**Issue by Reithan** [PathOfBuildingCommunity/PathOfBuilding#914]
**Is your feature request related to a problem? Please describe.**
When developing a build, it's often useful to focus first on keystones and noteable that are important, then figure out your per-level path to get them, and optimize smaller nodes and notables around them.

**Describe the solution you'd like**
To that end, it would be useful to be able to allocate skills without being forced to connect them, even just temporarily, so that you can determine path & order afterwards.

**Describe alternatives you've considered**
Alternatives unknown

**Additional context**
Additionally, any sort of tool that could then optimize paths to/from/around pre-allocated unconnected nodes would be awesome, but you run into NP-hard travelling salesman stuff.

**Comment by SabreCat** [comment]
For a minute I thought maybe you could work around this by adding a bunch of "Allocates X" mods onto some piece of gear, but unfortunately PoB doesn't yet support items allocating keystones except for some specific uniques. :\

**Comment by ppoelzl** [comment]
This isn't something that we desire to support. There are strong technical reasons to ensure the passive skill tree remains valid at any point. Otherwise, various advanced features like support for radius or timeless jewels will not behave as intended.
