### ISSUE TITLE
Preview support for Cluster Jewels

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#917]
**Preview for the main skill in the item tab is missing**
I get it's because unlike regular items, Cluster Jewels do nothing by themselves and require first to socket them, and then also to allocate at least one skill point in them. However, shouldn't PoB give a sort of an overview, and show what impact one has on your build as if it was socketed:

- and fully allocated if it's a new item?
- otherwise, only with allocated points taken into account?

I know I can get to the Skill Tree and manually allocate all the points and hover over them, but then I'm missing the nice condensed listing of changes that the Items tab provides, plus while crafting, I have to craft every and all versions of Cluster Jewels and manually track the impact they have.

**Comment by ZzZombo** [comment]
Please can we give this more priority for the incoming new league? I shudder over the idea I'll have to jump through all the hoops yet again...

**Comment by ppoelzl** [comment]
I see you're also a programmer. You're welcome to give this more priority yourself 😉.

**Comment by LocalIdentity** [comment]
Notable preview was added in 1.4.170.4

**Comment by ppoelzl** [comment]
The power report feature added in 1.4.170.12 allows you to sort cluster jewel notables by power increase.
