### ISSUE TITLE
MSVCR100.DLL is missing, but it's installed

### ISSUE THREAD

**Issue by cbftw** [PathOfBuildingCommunity/PathOfBuilding#922]
I installed the community fork using the setup.exe and when I attempted to start PoB I receive a popup stating:

"The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem."

I attempted a reinstall and t hat didn't work. I also retrieved the dll from Microsoft and it still claims that the DLL isn't found. I restarted the computer and the issue persists.

**Comment by cbftw** [comment]
I resolved this by copying the files from the portable version into the install directory and it worked. That said, this should still be investigated.

**Comment by Rayniac** [comment]
Hi cbftw,

I had this same exact problem, what fixed it for me was installing the 32-bit version of Microsoft's 2010 c++ SP1 redistributable package.

**Comment by LocalIdentity** [comment]
This issue will be fixed with a new installer when the next update comes out

**Comment by Kaikas** [comment]
> Hi cbftw,
> 
> I had this same exact problem, what fixed it for me was installing the 32-bit version of Microsoft's 2010 c++ SP1 redistributable package.

This fixed it for me as well. Thanks.

**Comment by ColinDabritz** [comment]
We ran into the same problem, on a relatively fresh windows install.

Keywords to assist searches, this was oddly difficult: MSVCR dll

We also found the 2010 SP1 Redistributable here:
https://www.microsoft.com/en-us/download/details.aspx?id=26999

But we assumed the 64 bit version was correct to match windows. It was not sufficient.

We retried with the 32 bit version and it did work correctly :)

In case it helps there is an old issue on the parent project:
https://github.com/Openarl/PathOfBuilding/issues/89

And it sounds like the answer is to include the redistributable with the installer? Not sure why the behavior changed in the Fork.

Please note we did NOT have this issue on 2 other windows 10 64 bit installs, also recent.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.4.
