### ISSUE TITLE
Awakened Support Gems treated as Lv20

### ISSUE THREAD

**Issue by meatballing** [PathOfBuildingCommunity/PathOfBuilding#924]
v1.4.169.2

Tooltip for stats comparison when selecting Awakened support gems incorrectly uses 20/20 gem stats for calculation. Should be using 5/20 for calculations.

Tooltip when selecting Awakened Lightning Penetration
![image](https://user-images.githubusercontent.com/61110094/82749347-f87c6a00-9deb-11ea-856c-c94aaf72db8f.png)

Tooltip when enabling 5/20 Awakened Lightning Penetration
![image](https://user-images.githubusercontent.com/61110094/82749361-1b0e8300-9dec-11ea-8de0-13ecc0e5fd4a.png)

Tooltip when enabling 20/20 Awakened Lightning Penetration
![image](https://user-images.githubusercontent.com/61110094/82749427-83f5fb00-9dec-11ea-8aac-9cdcd6886766.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
