### ISSUE TITLE
Stormbind says "more damage" where it should say "more damage with hits and ailments"

### ISSUE THREAD

**Issue by teuneboon** [PathOfBuildingCommunity/PathOfBuilding#932]
* **What happened?**
Stormbind has an incorrect description, this causes it to scale stuff like decay where it doesn't ingame, this Jebaited RaizQT.

* **What steps will reproduce the bug?**
Add decay support to Stormbind and increase amount of times it's improved

* **Additional information:**
Correct text should be "Runes deal 100% more Damage with Hits and Ailments for each time they have been Improved" like it says on https://poedb.tw/us/Stormbind. The wiki is wrong on this as well.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
