### ISSUE TITLE
Misleading node change readout when adding new line to DPS breakdown

### ISSUE THREAD

**Issue by SabreCat** [PathOfBuildingCommunity/PathOfBuilding#936]
* **What happened?**

A node adding a trivial amount of ignite DPS where I had none before made it look like it would more than double my overall DPS.

* **What were you trying to do?**

Perusing notables looking for good anointment selections, checking what they would do for the build

* **What steps will reproduce the bug?**

1. Put together a build that doesn't include any added-on DPS types, like ignite, bleed, or impale
2. Hover over a node that adds some amount of ignite/bleed/impale DPS and do a double-take at what the summary implies

* **Does it reproduce every time? If not, why so?**

Yes!

* **Additional information:**

![image](https://user-images.githubusercontent.com/4501321/83084140-b94d5380-a04d-11ea-92a9-15e375c08068.png)

https://pastebin.com/AATDuJ1v - mouse over Divine Fury node

Ideally, the "+xxx Total DPS inc. Ignite" would take into account that we _had_ a total DPS including ignite previously, it's just that the ignite inclusion was 0!

**Comment by ppoelzl** [comment]
It's only misleading if you don't take the full tooltip into account.
