### ISSUE TITLE
Opportunistic more damage conditions

### ISSUE THREAD

**Issue by swordsha** [PathOfBuildingCommunity/PathOfBuilding#947]
The Opportunistic ascendancy for assassin reads that you do 25% more damage while there is AT MOST one Rare or Unique enemy nearby. This suggests that it should be active when there are NO rare or unique enemies nearby. Currently in PoB Fork it is applied only if there is EXACTLY one rare or unique enemy nearby.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
