### ISSUE TITLE
CLUSTER JEWELS INCORRECT DISPLAY

### ISSUE THREAD

**Issue by p4zv4l** [PathOfBuildingCommunity/PathOfBuilding#957]
WHEN I IMPORT A BUILD (FROM A PASTEBIN LINK OR SOMEONE'S ACCOUNT), WHILE THE REST OF THE NOTES AS SELECTED BY THE PLAYER INDICATE WELL, THOSE ON CLUSTER JEWELS DONT [DISPLAY.]
https://imgur.com/gallery/yEx1K3Z

Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time? If not, why so?**
* **Additional information:**
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by LocalIdentity** [comment]
If you try an import from a Pastebin and it doesn't have the nodes allocated, that is cause the person who made the link did not allocate the nodes before exporting their build, it is not a problem on our end. When importing from someone's account, the points are not allocated on cluster jewels as we do not receive the data from GGG. They need to update their website so we can receive this data
