### ISSUE TITLE
SSL Connect Error for Update Check on Linux

### ISSUE THREAD

**Issue by xllvrr** [PathOfBuildingCommunity/PathOfBuilding#961]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** When starting the application, the update check turns up with an error message asking to check internet connection. The error is listed as SSL Connect Error.
* **What were you trying to do?** Automatic Update Check
* **What steps will reproduce the bug?** Opening the App
* **Does it reproduce every time? If not, why so?** Yes
* **Additional information:** System is Archlinux. PoB was installed through Lutris and Wine
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by norepro** [comment]
Could not reproduce the issue on Ubuntu 20.04 LTS with lutris 0.5.6, wine 5.0-3ubuntu1, and PoB 1.4.169.2 (latest as of this writing).  Both the automatic check on startup and clicking the button did not produce an SSL error.

Does it still fail for you?

**Comment by xllvrr** [comment]
Yes the problem is still present. I'm running on Archlinux with lutris 0.5.6-2, wine 5.10-1, and PoB 1.4.169.1, downloaded as a standalone from the releases page. Neither the button nor the automatic check work. The pastebin works however, should I input a http instead of a https link.

**Comment by kmhuff** [comment]
I'm trying to run PoB on Manjaro (an Arch derivative) with lutris 0.5.6, and PoB 1.4.169.1. I tried two different wine versions: lutris-5.6-2-x86_64 and 5.9. I'm getting the same results as @xllvrr: neither automatic nor manual update work, https pastebin links don't work but http ones do.

I'm afraid I'm too much of a wine noob to know what the problem might be.

**Comment by kmhuff** [comment]
I fixed this error for me. 

To find out what was wrong, I went into the configure menu in Lutris for PoB and change "Output debugging info" to "Enabled" under the "Runner options" tab. You can then see the output while PoB is running with the "Show logs" button.

The debugging logs showed that wine wasn't loading the package "libgnutls". I installed the package "lib32-gnutls" and that fixed the problem immediately. There are other errors that I haven't had the chance to look at, but PoB seems to run fine for me now.

**Comment by norepro** [comment]
Good find!  Confirmed I already have libgnutls30 package installed on my Ubuntu box, which explains why it worked for me.

**Comment by xllvrr** [comment]
I couldn't get it to show the logs (probably because I'm on bspwm and bspwm doesn't like being nice to certain windows) but installing libgnutls did the trick. Thanks @kmhuff !
