### ISSUE TITLE
Spreading Rot enables Withered Stacks configuration option, but increasing it doesn't add DPS

### ISSUE THREAD

**Issue by SabreCat** [PathOfBuildingCommunity/PathOfBuilding#962]
* **What happened?**

When adding the Spreading Rot jewel to a build with the Blight skill, the "# of Withered Stacks:" config option appears under Effective DPS, but adding stacks does not change the DPS output.

* **What were you trying to do?**

Assess the effectiveness of Wither applied by the Spreading Rot threshold jewel during use of Blight skill, without use of e.g. a separate Wither totem

* **What steps will reproduce the bug?**

1. Start a new build
2. Allocate a Basic Jewel Socket
3. Add a Spreading Rot jewel to the build and equip it to the jewel socket
4. Add Blight skill to the build as main skill (other chaos skills like Bane also work, but Blight makes most sense for the flow!)
5. Go to Configuration and increase the # of Withered stacks. DPS does not change.
6. Add Wither as an additional active skill
7. Increase the # of Withered stacks. DPS goes up.

* **Does it reproduce every time? If not, why so?**

Yes

* **Additional information:**

https://pastebin.com/WTg8p8DC

**Comment by SabreCat** [comment]
Withering Step correctly enables the number field and adds damage per count. Might be an issue with Spreading Rot specifically?

**Comment by Quotae** [comment]
I'm the one that originally added the current implementation of Withered. The reason this bug happens is because the effect of Withered is given by the skills that can apply it, it's not a global effect like most buffs and debuffs. Changing Withered to be a global effect turned out to be super complicated and I wasn't able to figure it out.

**Comment by SabreCat** [comment]
@Quotae: Aha, ok! Hmm... is there any precedent for setting up an invisible dummy skill behind the scenes, for things like this? Then Spreading Rot could give a Wither skill and let it work.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.4
