### ISSUE TITLE
Feature Request: The Saviour's clone damage calculation

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#976]
The Saviour has been around for a few leagues now. It would be a decent feature to have the damage from your clones taken into account for each active melee skill that Reflection can support.

How I would see it implemented:
Once The Saviour is equipped, a new option in config tab would be present: 
**Are clones active?**
_Checkbox_

Once ticked, the damage of both clones will appear as a new damage descriptor on the left side:
Average Damage:
(...)
**Clone DPS:**
Total DPS:
(total DPS would now also include damage from Reflection clones)

Is there any remote possibility of this being implemented, or is the PoB code too convoluted for it?

**Comment by Nostrademous** [comment]
Fixed in #2294

**Comment by Wires77** [comment]
Released in 2.0.0
