### ISSUE TITLE
"Aura X has Y% less mana reserved" modifier is not taken into account when calculating reserved mana. (Hyrri's Truth & Precision)

### ISSUE THREAD

**Issue by Rayniac** [PathOfBuildingCommunity/PathOfBuilding#980]
The level 22 Precision aura from Hyrri's truth is reserving 202 mana in PoB. It should be 202/2 = 101.
Oh right,the version that I'm using is 1.4.169.2

**Comment by LocalIdentity** [comment]
I'm unable to replicate this. Can you supply me with a Pastebin so I can try and reproduce it

**Comment by Rayniac** [comment]
Sure: https://pastebin.com/SFtdYzq5

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
