### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Chnago** [PathOfBuildingCommunity/PathOfBuilding#985]
i used POB for years, now when i launch it, i see the script loading in the Green screen, after that it stay as black screen, do you know what can i do?

i did reinstall it/download it

1- launch POB
2- Creen screen for loading script
3- black screen in POB Window

**Comment by Hyve747** [comment]
Have the same problem for months now, but have a work arround. After closing my Asus Phoebus software and restating POB it launches normaly.

**Comment by LocalIdentity** [comment]
Can you try using the new 1.4.170.4 installer and see if that fixes the issue for you

**Comment by ppoelzl** [comment]
Closed due to inactivity.
