### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by BAAZKonqi** [PathOfBuildingCommunity/PathOfBuilding#989]
When I click check for updates, the Downloading progress counter counts up until 25/25. Then it fails with the Message Update Check failed.

**Comment by maximsiziov** [comment]
Same here

**Comment by tarantio85** [comment]
Same here

**Comment by BAAZKonqi** [comment]
Solved. Sry for the lack of pacience. Good Job on the fast updates. ;)
