### ISSUE TITLE
Increased ES implicits apply locally instead of globally

### ISSUE THREAD

**Issue by ghost** [PathOfBuildingCommunity/PathOfBuilding#99]
Recently upgraded my Alpha's Howl for one with the % increased ES corruption and discovered that PoB doesn't reflect this change; ES stays identical regardless of which helm I use. I can confirm that the ES is in fact increased in game.
![image](https://user-images.githubusercontent.com/808674/71645985-28489b00-2cae-11ea-8c86-5718e71bc8b8.png)
![image](https://user-images.githubusercontent.com/808674/71645991-35658a00-2cae-11ea-875b-50a6b38900bc.png)

Here's the pastebin if you want to test for yourself https://pastebin.com/0Y9GLxUp

**Comment by meatballing** [comment]
The corruption mod is being applied locally instead of globally. Other sources of "increased maximum energy shield" mods are only available on jewellery which are correctly treating it as global. I'm a bit confused as to how the mods are being parsed differently.

**Comment by Wires77** [comment]
Looking at this again, we can maybe look at the "Local" field on a stat from the GGPK, and tag the line as such, but that only works when adding corrupted mods from PoB itself.  When importing a character or copying an item, we'll have to cross-reference the implicit (only on corrupted items, to exclude synthesized mods) with the corrupted mods to find a match, and still might have false positives from Synthesis items.

**Comment by OzoneOOO** [comment]
I had the same error as others with the EoW increased ES. Came to report but it's already been done. Workaround is to add custom modifier "X% increased global energy shield" to the item. 

Oddly, PoB doesn't miscalculate the local number. The EoW implicit is just ignored.

**Comment by QuickStick123** [comment]
These mods have slightly different wording the corrupted mod is x% increased maximum energy shield whereas the local one is always x% increased energy shield. This should be fixable by a special mod passing for x% increased maximum energy shield to always apply globally. E.g. this mod is also found on rings and applies globally.
