### ISSUE TITLE
Can't type "^" or "*" in the notes section without text changing color

### ISSUE THREAD

**Issue by m4xolotl** [PathOfBuildingCommunity/PathOfBuilding#991]
This is very frustrating, I'm trying to add math equations calculating my big dicks deeps, what the hell is going on?

**Comment by pikzen** [comment]
Cannot reproduce on the latest development build:

![image](https://user-images.githubusercontent.com/373126/85146547-f91ee980-b24d-11ea-9f49-e35abfd624ae.png)

**Comment by ppoelzl** [comment]
PoB uses these special symbols combined with colour codes to add colour to text. This should not be an issue for your calculations if you leave space between operators, which also improves readability. If anything, this is a feature.
