### ISSUE TITLE
Removal of dual wielding physical damage mod

### ISSUE THREAD

**Issue by jeroenroosen** [PathOfBuildingCommunity/PathOfBuilding#992]
As per the [3.11 patch notes](https://www.pathofexile.com/forum/view-thread/2873739#characterbalance), the `20% more physical damage` for dual wielding will be removed from the game.

I can identify the mods in
- [CalcSetup](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/Modules/CalcSetup.lua#L237)
- [Minions](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/Data/3_0/Minions.lua#L374)

but I am not familiar enough with the code base to confidently say that removing these lines is the way to fix this in PoB.

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
