### ISSUE TITLE
3.11 Chieftain ascendency not supported

### ISSUE THREAD

**Issue by SacDeFromage** [PathOfBuildingCommunity/PathOfBuilding#993]
Bug: Chieftain new nodes ascendency are not properly supported.

- Valako, Storm's Embrace: We can't lose endurance charge anymore in the Configuration tab
- Tawhoa, Forest's Strength: Does nothing

Steps to reproduce:
3.11 Tree
Select Chieftain ascendency nodes mentionned
Select Use Endurance Charge, and set a high number, you won't find the option to remove charges.
Tawhoa won't change anything.

Full example:
https://pastebin.com/dVMRiZ7r

**Comment by ppoelzl** [comment]
Added in 1.4.170.19.
