### ISSUE TITLE
Increased Brand Damage is Applying to Generic Spells and Attacks

### ISSUE THREAD

**Issue by qikink** [PathOfBuildingCommunity/PathOfBuilding#995]
The text "Increased Brand Damage" is currently increasing the average hit of both Frenzy and Volatile Dead. When allocated, the increase can be found in the "All Types -> Total Increased" Hover, showing no associated conditional skill types.

**Comment by Zarbokk** [comment]
Yep got the same error

**Comment by LocalIdentity** [comment]
Added in 1.4.170.1
