### ISSUE TITLE
Pob Crashing after launch, Stopping to respond on start of download or during the middle of download

### ISSUE THREAD

**Issue by shoderra** [PathOfBuildingCommunity/PathOfBuilding#996]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
Pob got stuck during installation of the new update. Tried it 5 or 6 times. Reinstalled. Now Pob stops responding at some point during the download. I tried to use the ZIP. Pob would close itself a few seconds after launching every single time. Moved my builds to make sure POB wouldn't load them. Same behaviour. Pob has gotten stuck on 6/23, 13/23, 14/23 and the latest is 18/23. Each one have occured multiple times. Also tried to run it as admin. No change
* **What were you trying to do?**
Updating POB
* **What steps will reproduce the bug?**
Launching POB
* **Does it reproduce every time? If not, why so?**
YES
* **Additional information:**
Edit: Current version is displayed as 1.4.169.2
Edit: I was able to work around it by downloading the original POB and editing the manifest again. Then it updated normally
If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by ppoelzl** [comment]
This can happen when you update PoB while GitHub processes changes for a new update. I recommend you to wait 5-15 minutes if this is the case, as GitHub is known to cache old file versions quite agressively.
